### ISSUE TITLE
Bug:Why does llama-cli choose a GPU with lower performance?

### ISSUE THREAD

**Issue by badog-sing** [ggerganov/llama.cpp#10009]
### What happened?

I have 2 GPUs in imc2017 RAM64G, one of which is connected through eGPU. Llama-cli->ggml->always don't use a GPU with higher performance? How can I use a higher GPU, or both?

### Name and Version

 METAL_DEVICE_WRAPPER_TYPE=0 (or 1 or 2 ) ./llama-cli
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for x86_64-apple-darwin22.6.0

### What operating system are you seeing the problem on?

Mac

### Relevant log output

```shell
ggml_metal_init: allocating
ggml_metal_init: found device: AMD Radeon VII
METAL_DEVICE_WRAPPER_TYPE=0 ./llama-cli
build: 0 (unknown) with Apple clang version 15.0.0 (clang-1500.3.9.4) for x86_64-apple-darwin22.6.0
main: llama backend init
main: load the model and apply lora adapter, if any
llama_load_model_from_file: using device Metal (AMD Radeon Pro 570) - 4096 MiB free
llama_model_loader: loaded meta data with 39 key-value pairs and 963 tensors from models/7B/ggml-model-f16.gguf (version GGUF V3 (latest))
...
ggml_metal_init: found device: AMD Radeon Pro 570
ggml_metal_init: picking default device: AMD Radeon Pro 570
ggml_metal_init: using embedded metal library
ggml_metal_init: GPU name:   AMD Radeon Pro 570
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: simdgroup reduction support   = false
ggml_metal_init: simdgroup matrix mul. support = false
ggml_metal_init: hasUnifiedMemory              = false
ggml_metal_init: recommendedMaxWorkingSetSize  =  4294.97 MB
......
```

**Comment by badog-sing** [comment]
Here is the content of ggml-metal.m: What might I need to modify?

% nano ggml-metal.m

#import "ggml-metal.h"

#import "ggml-impl.h"
#import "ggml-backend-impl.h"

#import <Foundation/Foundation.h>

#import <Metal/Metal.h>

#undef MIN
#undef MAX
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define MAX(a, b) ((a) > (b) ? (a) : (b))

// max memory buffers that can be mapped to the device
#define GGML_METAL_MAX_BUFFERS 64

// max number of MTLCommandBuffer used to submit a graph for processing
#define GGML_METAL_MAX_COMMAND_BUFFERS 8

#define UNUSED(x) (void)(x)

// globals

// overload of MTLGPUFamilyMetal3 (not available in some environments)
static const NSInteger MTLGPUFamilyMetal3_GGML = 5001;

// initialized in ggml_backend_metal_reg
static struct ggml_backend_reg    g_ggml_backend_metal_reg;
static struct ggml_backend_device g_ggml_backend_metal_device;

// information about a Metal device
// note: assumes single GPU device - the default one
// TODO: support multiple GPU devices
static struct ggml_backend_metal_device_context {
    id<MTLDevice> mtl_device;
    int           mtl_device_ref_count;

    bool support_simdgroup_reduction;
    bool support_simdgroup_mm;

    char name[128];
} g_ggml_ctx_dev_main = {
    /*.mtl_device                  =*/ nil,
    /*.mtl_device_ref_count        =*/ 0,
    /*.support_simdgroup_reduction =*/ false,
    /*.support_simdgroup_mm        =*/ false,
    /*.name                        =*/ "",
};

// acquire
static id<MTLDevice> ggml_backend_metal_device_acq(struct ggml_backend_metal_de$
    assert(ctx != NULL);

    if (ctx->mtl_device == nil) {
        ctx->mtl_device = MTLCreateSystemDefaultDevice();

        ctx->support_simdgroup_reduction  = [ctx->mtl_device supportsFamily:MTL$
        ctx->support_simdgroup_reduction |= [ctx->mtl_device supportsFamily:MTL$

        ctx->support_simdgroup_mm = [ctx->mtl_device supportsFamily:MTLGPUFamil$

        strncpy(ctx->name, [[ctx->mtl_device name] UTF8String], sizeof(ctx->nam$
    }

    ctx->mtl_device_ref_count++;

    return ctx->mtl_device;
}

// release
static void ggml_backend_metal_device_rel(struct ggml_backend_metal_device_cont$
    assert(ctx != NULL);
    assert(ctx->mtl_device_ref_count > 0);

    ctx->mtl_device_ref_count--;

    if (ctx->mtl_device_ref_count == 0) {
        [ctx->mtl_device release];
        ctx->mtl_device = nil;
    }
}

// kernels

struct ggml_metal_kernel {
    id<MTLComputePipelineState> pipeline;

**Comment by ggerganov** [comment]
Likely this has to be updated:

```c
    ctx->mtl_device = MTLCreateSystemDefaultDevice();
```

But keep in mind that AMD GPU support in Metal is really poor and likely running on the GPU will be slower compared to the CPU.

**Comment by badog-sing** [comment]
Thank you very much! Sure enough, metal is worse than CPU.

**Comment by ggerganov** [comment]
Yes, writing mid-quality kernels for the AMD GPU that would result in improved performance is not very difficult, but I consider it not worth complicating the backend implementation since that hardware is legacy at this point in the Apple ecosystem. If there is a lot of interest, we can reconsider, but I'm doubtful.

**Comment by badog-sing** [comment]
Don't bother. It is too time-consuming and laborious to do so, and the benefits are not great.
