### ISSUE TITLE
Feature Request: Support Aya 

### ISSUE THREAD

**Issue by maziyarpanahi** [ggerganov/llama.cpp#10035]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

The new Aya Expanse models require support for `CohereTokenizer`. 

- https://huggingface.co/CohereForAI/aya-expanse-8b
- https://huggingface.co/CohereForAI/aya-expanse-32b

```
ValueError: Tokenizer class CohereTokenizer does not exist or is not currently imported.
```

However, I see something similar has been done but only for the Command R/R+ and I was wondering that can be extended to these new models: https://github.com/ggerganov/llama.cpp/pull/7063

### Motivation

These are new multilingual models with small sizes and great performance that could be useful to users with languages that are not represented in the existing models

### Possible Implementation

https://github.com/ggerganov/llama.cpp/pull/7063

**Comment by foldl** [comment]
Yes, Command-R and Aya share the same mode arch.
