### ISSUE TITLE
Bug: issue in CUDA flash attention

### ISSUE THREAD

**Issue by agray3** [ggerganov/llama.cpp#10031]
### What happened?

There seems to be some memory corruption issue in the CUDA flash attention kernel. 

This is demonstrated by the debug prints inserted before and after the `vec_dot_KQ` device function here:
https://github.com/ggerganov/llama.cpp/compare/master...agray3:llama.cpp:ag_demonstrate_fattn_memory_issue

These print out the first element of Q_ds, which is const in the function so shouldn't be altered. (`Q_ds` is in local memory so it also shouldn't be altered by any other thread.)

However we get the result: 
Before vec_dot_KQ: Q_ds=-32752.000000
After vec_dot_KQ: Q_ds=nan

Q_ds is being altered and becoming NAN. This is reproducible across different GPUs and models. 

### Name and Version

version: 3964 (3488adf3)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

**Comment by agray3** [comment]
@JohannesGaessler FYI

**Comment by JohannesGaessler** [comment]
How did you come to notice this? Are you using `-ctk` to specify a quantized K cache? Because otherwise `Q_ds` should be unused and optimized out by the compiler. Did you check the PTX code for where exactly something is written to the register that is being printed?

**Comment by agray3** [comment]
> How did you come to notice this? Are you using `-ctk` to specify a quantized K cache? Because otherwise `Q_ds` should be unused and optimized out by the compiler. Did you check the PTX code for where exactly something is written to the register that is being printed?

I initially saw some weird behaviour in some internal work using a port of this. That environment was hard to debug, so I switched to hacking around with the master branch to see if I could see any inconsistencies. I wasn't specifically focusing on `Q_ds`, and I'm not using `-ctk`, but with these print statements present the compiler of course can't optimize it out and therefore it should print the same unititialized value after the function call. So I think this reproducer indicates there is some issue in the kernel, or I guess possibly in CUDA. I haven't done any more in-depth debugging yet.

**Comment by agray3** [comment]
> therefore it should print the same initial value after the function call.
Actually I can see now it is not even initialized in this case, so maybe this is a red herring. I'll close the issue for now and reopen if there is a more solid reproducer. Maybe the issue is in my port.

**Comment by agray3** [comment]
Closing as above

**Comment by JohannesGaessler** [comment]
Generally speaking the best way to assist in debugging would be to write a test case in `test-backend-ops` that is representative of the problem and fails with the code on master.

**Comment by agray3** [comment]
Closing the loop on this, I found the bug in my port so there is no indication anything is wrong with the kernel. My mistake and apologies for the false alarm.
