### ISSUE TITLE
M1 Max + GNU coreutils: "Your arch is announced as x86_64, but it seems to actually be ARM64"

### ISSUE THREAD

**Issue by Birch-san** [ggerganov/llama.cpp#101]
When I build, the makefile detects my M1 Max as 86_64.

This is because I have GNU coreutils `uname` on my `PATH`, which announces my architecture as `arm64` (whereas the system distribution of `uname` would call the same architecture `arm`).

https://github.com/Lightning-AI/lightning/pull/13992#issuecomment-1204157830  
https://github.com/Lightning-AI/lightning/issues/13991

this condition needs widening to accept both `arm` and `arm64`:

https://github.com/ggerganov/llama.cpp/blob/c09a9cfb06c87d114615c105adda91b0e6273b69/Makefile

**Comment by cryolite-ai** [comment]
@Birch-san is this an issue which can be closed? I think there's an urgent need to try to close issues (because there are now over 800 live on the repo). I have an M1 Max and haven't had that issue with the current build, so I think this is probably stale..
