### ISSUE TITLE
Bug: b3990 ascend cann build error

### ISSUE THREAD

**Issue by HMING666666** [ggerganov/llama.cpp#10105]
### What happened?

27.81 /app/ggml/src/ggml-cann.cpp: In function 'ggml_backend_buffer* ggml_backend_cann_host_buffer_type_alloc_buffer(ggml_backend_buffer_type_t, size_t)':
27.81 /app/ggml/src/ggml-cann.cpp:1230:19: error: 'struct ggml_backend_buffer_i' has no member named 'get_name'; did you mean 'get_base'?
27.81  1230 |     buffer->iface.get_name = ggml_backend_cann_host_buffer_name;
27.81       |                   ^~~~~~~~
27.81       |                   get_base
27.85 gmake[3]: *** [ggml/src/CMakeFiles/ggml.dir/build.make:174: ggml/src/CMakeFiles/ggml.dir/ggml-cann.cpp.o] Error 1
27.85 gmake[2]: *** [CMakeFiles/Makefile2:1619: ggml/src/CMakeFiles/ggml.dir/all] Error 2
27.85 gmake[1]: *** [CMakeFiles/Makefile2:3368: examples/main/CMakeFiles/llama-cli.dir/rule] Error 2
27.85 gmake: *** [Makefile:1323: llama-cli] Error 2
------

### Name and Version

version: b3990
os: openeuleros:22.03
framework: ascend-cann

### What operating system are you seeing the problem on?

Mac

**Comment by slaren** [comment]
@hipudding sorry, I probably introduced this issue when adapting the CANN backend to the interface changes in #10026. It would be useful to have a build of the CANN backend in the CI to avoid this from happening again in the future.

**Comment by hipudding** [comment]
> @hipudding sorry, I probably introduced this issue when adapting the CANN backend to the interface changes in #10026. It would be useful to have a build of the CANN backend in the CI to avoid this from happening again in the future.

Yes, it is necessary to have CI to take care of the backend of CANN. We are limited by hardware resource issues and have not yet provided CI resources. We will solve this problem as soon as possible.

**Comment by slaren** [comment]
> We are limited by hardware resource issues and have not yet provided CI resources.

A build of the CANN backend in `.github/workflows/build.yml` would be useful to check that everything builds correctly. A full CI that can run tests on Ascend hardware would be better of course, but the build test can be added without requiring more resources.

**Comment by hipudding** [comment]
> > We are limited by hardware resource issues and have not yet provided CI resources.
> 
> A build of the CANN backend in `.github/workflows/build.yml` would be useful to check that everything builds correctly. A full CI that can run tests on Ascend hardware would be better of course, but the build test can be added without requiring more resources.

Yes, build test is not require any Ascend hardware, we will add this build test workflow ASAP.
