### ISSUE TITLE
Bug: Failed To Load Model (LM Studio)

### ISSUE THREAD

**Issue by m01ali** [ggerganov/llama.cpp#10104]
### What happened?

[HF Model Card](https://huggingface.co/bartowski/stable-code-instruct-3b-GGUF)
![image](https://github.com/user-attachments/assets/8f377a46-a50c-4db6-8e23-5ac6194f92f3)

[Model Download Link (LM-Studio)](https://model.lmstudio.ai/download/bartowski/stable-code-instruct-3b-GGUF)
![image](https://github.com/user-attachments/assets/1bfaeac8-0719-4ab0-bd23-5851490448c1)

### Name and Version

LM Studio Version: [0.3.5] 

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
🥲 Failed to load the model

Failed to load model

llama.cpp error: 'error loading model architecture: unknown model architecture: 'sd3''
```

**Comment by ngxson** [comment]
llama.cpp only support language model, not diffusion model
