### ISSUE TITLE
Feature Request: count tokens before calling '/v1/chat/completions'

### ISSUE THREAD

**Issue by GPTLocalhost** [ggerganov/llama.cpp#10115]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

We recently integrated Microsoft Word with llama.cpp through a local Word Add-in. You can see a demo of the integration [here](https://gptlocalhost.com/demo/#llama.cpp). We're planning to add a feature that allows users to see how many tokens are left before they call '/v1/chat/completions'. The question is: Is it possible for llama.cpp to count the tokens of the prompt before calling '/v1/chat/completions'? Any insights would be greatly appreciated.

### Motivation

This feature would enhance user experience by providing better control over token usage, especially for those working with token-sensitive operations. To achieve this, we're investigating whether llama.cpp can count the tokens of a prompt in advance of making the API call.

### Possible Implementation

For OpenAI models, [this cookbook](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) might be a direction. For models with different tokenizers, it is not as clear how to achieve the same result.

**Comment by slaren** [comment]
You should be able to do this with the tokenize endpoint. See https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#post-tokenize-tokenize-a-given-text for more details.
