### ISSUE TITLE
Bug: Unable to enable AVX_VNNI instructions

### ISSUE THREAD

**Issue by kylo5aby** [ggerganov/llama.cpp#10116]
### What happened?

I have built it on Windows env with OneAPI setup and try to enable AVX_VNNI instructions. My computer is support AVX_VNNI:
![image](https://github.com/user-attachments/assets/7c513c5f-1353-4468-81b7-5dcbd8d209fd)
and I followed the [doc's steps](https://github.com/ggerganov/llama.cpp/blob/master/docs/build.md#intel-onemkl) :

```shell
# in OneAPI env, execute:
cmake -B build -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=Intel10_64lp -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_NATIVE=ON
cmake --build build --config Release
```

but it still shows no AVX_VNNI support:
![image](https://github.com/user-attachments/assets/974f6b65-a80b-47a0-a059-0b076c19c768)

#### my platform
+ msvc: MSVC 19.41.34123.0( Visual Studio 2022) on Windows SDK 10.0.22631.
+ oneAPI:  oneAPI 2024.2

### Name and Version

.\llama-cli.exe --version
version: 3983 (8841ce3f)
built with MSVC 19.41.34123.0 for x64

### What operating system are you seeing the problem on?

Windows

**Comment by slaren** [comment]
`GGML_NATIVE` with MSVC uses `FindSIMD.cmake`, which does not seem to have a check for AVX_VNNI. You should still be able to build by disabling `GGML_NATIVE` and setting the corresponding flag (assuming that it would actually work without other AVX512 instruction sets).

**Comment by kylo5aby** [comment]
Thanks. I'll take a try
