### ISSUE TITLE
Bug: Docker image not found when trying to pull it

### ISSUE THREAD

**Issue by tifDev** [ggerganov/llama.cpp#10112]
### What happened?

docker run -v /home/dietpi/llama-models ghcr.io/ggerganov/llama.cpp:full -m llama-models/Llama-3.2-1B.Q2_K.gguf -p "Building a website can be done in 10 simple steps:" -n 512
Unable to find image 'ghcr.io/ggerganov/llama.cpp:full' locally
docker: Error response from daemon: Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.1.254:53: no such host.
See 'docker run --help'.

### Name and Version

Not installed as the docker image wasn't found

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
NA
```

**Comment by slaren** [comment]
Looks like a problem with your DNS server.

**Comment by tifDev** [comment]
Yes I just had the same error for other project.
Closing this.
