### ISSUE TITLE
Bug: llama-quantize --help is not printed

### ISSUE THREAD

**Issue by ivanstepanovftw** [ggerganov/llama.cpp#10122]
### What happened?

Appended `--help` does not print help immediately, but starts quantization or throws error:
```shell
./llama-quantize model-bf16.gguf --help IQ4_NL
./llama-quantize model-bf16.gguf IQ4_NL --help
```

### Name and Version

c02e5ab2a675c8bc1abc8b1e4cb6a93b26bdcce7

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
./build/bin/llama-quantize --leave-output-tensor ./qwen2.5-coder-7b-instruct/qwen2.5-coder-7B-instruct-BF16.gguf --help IQ
4_NL                                                                                                                                                          
main: build = 4000 (c02e5ab2)                                                                                                                                 
main: built with cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0 for x86_64-linux-gnu                                                                                     
main: quantizing './qwen2.5-coder-7b-instruct/qwen2.5-coder-7B-instruct-BF16.gguf' to '--help' as IQ4_NL                                                      

---

./build/bin/llama-quantize --leave-output-tensor ./qwen2.5-coder-7b-instruct/qwen2.5-coder-7B-instruct-BF16.gguf 1 --help 
main: invalid nthread '--help' (stoi)
```

**Comment by paulgekeler** [comment]
I think `--help` is considered to be called only together with `./llama-quantize --help` in order to print the functionality of the tool. Meaning when calling `./llama-quantize model-bf16.gguf IQ4_NL --help` or `./llama-quantize model-bf16.gguf --help IQ4_NL` it is considered a number of threads (can be seen in the error message, it is trying to convert your string '--help' to an integer number of threads ). Also stated in this code comment (`examples/quantize/quantize.cpp` line 105): 
```
// usage:
//  ./llama-quantize [--allow-requantize] [--leave-output-tensor] [--pure] models/llama/ggml-model.gguf [models/llama/ggml-model-quant.gguf] type [nthreads]
```

If you call `./llama-quantize --help [....]`, i.e. with the help flag and other flags or arguments after, the functionality will still be printed.
I don't think this is a bug. More like not its intended use.

**Comment by ivanstepanovftw** [comment]
I believe the CLI should be more intuitive to use. When I add `--help` to the end of a command, I'm just looking for a quick way to see available quantization types or options without interrupting my workflow. Ideally, `nthreads` could be made optional and non-positional, so that flags like `--help` work seamlessly regardless of placement.

Right now, because `nthreads` is positional, the tool interprets `--help` as a thread count instead of displaying the help message. This isn’t quite what users expect; most would anticipate that `--help` can be appended anywhere without changing functionality. Making `nthreads` optional would let us put `--help` at the end of commands, which feels more natural and would improve the overall user experience.

**Comment by slaren** [comment]
Initially `llama-quantize` didn't have a command line parse, it only had the positional arguments. Eventually more arguments where added, and the positional arguments were kept to avoid breaking existing scripts. I am not sure that it would be worth changing it at this point.

**Comment by ivanstepanovftw** [comment]
I just want to note that llama.cpp had a lot of breaking changes in even broader examples, including removing some samplers, setting new default sampler parameters, and adding new samplers that are not disabled by default.
