### ISSUE TITLE
Bug: gguf tries to access newbyteorder, which was removed in numpy2.0

### ISSUE THREAD

**Issue by renxida** [ggerganov/llama.cpp#10127]
### What happened?

`newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

### Name and Version

gguf==0.1.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
File "/home/sfdemo/.local/lib/python3.12/site-packages/gguf/gguf_reader.py", line 151, in _get                                .newbyteorder(override_order or self.byte_order)
     ^^^^^^^^^^^^                                                                                                           AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
```

**Comment by paulgekeler** [comment]
I think your Numpy version is conflicting with the one specified in `llama.cpp/requirements`. The current one is `numpy~=1.26.4`. You might have to downgrade the version on your end or run the script in a venv, having installed the requirements.

**Comment by renxida** [comment]
I was using this in a project that needed numpy 2.0

Would be very nice if we could make this compatible for both.
