### ISSUE TITLE
Bug: prompt construction changed in commit 958367bf

### ISSUE THREAD

**Issue by anagri** [ggerganov/llama.cpp#10138]
### What happened?

the prompt construction changed in commit [958367bf](https://github.com/ggerganov/llama.cpp/commit/958367bf)

i have an internal test that started failing. on investigating figured out the above commit that was causing the issue.

The commit changes the way prompt is constructed -

to reproduce -
1. checkout the previous commit - [40f25557](https://github.com/ggerganov/llama.cpp/commit/40f25557)
2. build the llama-server
3. run the llama-server with model `TheBloke/Llama-2-7B-Chat-GGUF` filename `llama-2-7b-chat.Q4_K_M.gguf`
`./build/bin/llama-server -m $HOME/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGUF/snapshots/08a5566d61d7cb6b420c3e4387a39e0078e1f2fe5f055f3a03887385304d4bfa/llama-2-7b-chat.Q4_K_M.gguf --chat-template llama2 --verbose --verbose-prompt`
4. run the given curl request
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "llama2",
    "seed": 42,
    "messages": [
        {"role": "user", "content": "What day comes after Monday?"}
    ]
}'
```
in the received response, the `response['__verbose']['prompt']` is `"prompt":"[INST] What day comes after Monday? [/INST]"`

5. checkout `958367bf`
6. rebuild the server and run the server same as above
7. run the curl request same as above

this time, the prompt received in the `response['__verbose']['prompt']` is - 
`"prompt": "<s> [INST] What day comes after Monday? [/INST]",`

it adds an extra `<s>` for no change in the build or request process.

### Name and Version

$ ./build/bin/llama-cli --version
version: 3974 (958367bf)
built with Homebrew clang version 18.1.5 for arm64-apple-darwin23.3.0

### What operating system are you seeing the problem on?

Mac

### Relevant log output

```shell
commit: 40f25557


request: POST /v1/chat/completions 127.0.0.1 200
request:  {
    "model": "llama2",
    "seed": 42,
    "messages": [
        {"role": "user", "content": "What day comes after Monday?"}
    ]
}
response: {"choices":[{"finish_reason":"stop","index":0,"message":{"content":"  The day that comes after Monday is Tuesday.","role":"assistant"}}],"created":1730554128,"model":"llama2","object":"chat.completion","usage":{"completion_tokens":13,"prompt_tokens":14,"total_tokens":27},"id":"chatcmpl-FQGh1CrHnyK31rYX0uuYiyLGBItzaQ0R","__verbose":{"content":"  The day that comes after Monday is Tuesday.","id_slot":0,"stop":true,"model":"llama2","tokens_predicted":13,"tokens_evaluated":14,"generation_settings":{"n_ctx":4096,"n_predict":-1,"model":"/Users/amir36/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGUF/snapshots/08a5566d61d7cb6b420c3e4387a39e0078e1f2fe5f055f3a03887385304d4bfa/llama-2-7b-chat.Q4_K_M.gguf","seed":42,"seed_cur":42,"temperature":0.800000011920929,"dynatemp_range":0.0,"dynatemp_exponent":1.0,"top_k":40,"top_p":0.949999988079071,"min_p":0.05000000074505806,"xtc_probability":0.0,"xtc_threshold":0.10000000149011612,"tfs_z":1.0,"typical_p":1.0,"repeat_last_n":64,"repeat_penalty":1.0,"presence_penalty":0.0,"frequency_penalty":0.0,"mirostat":0,"mirostat_tau":5.0,"mirostat_eta":0.10000000149011612,"penalize_nl":false,"stop":[],"max_tokens":-1,"n_keep":0,"n_discard":0,"ignore_eos":false,"stream":false,"n_probs":0,"min_keep":0,"grammar":"","samplers":["top_k","tfs_z","typ_p","top_p","min_p","xtc","temperature"]},"prompt":"[INST] What day comes after Monday? [/INST]","has_new_line":false,"truncated":false,"stopped_eos":true,"stopped_word":false,"stopped_limit":false,"stopping_word":"","tokens_cached":26,"timings":{"prompt_n":14,"prompt_ms":313.306,"prompt_per_token_ms":22.378999999999998,"prompt_per_second":44.68474909513383,"predicted_n":13,"predicted_ms":220.327,"predicted_per_token_ms":16.94823076923077,"predicted_per_second":59.00320886682068},"index":0,"oaicompat_token_ctr":13}}
```
commit: 958367bf
```
request: POST /v1/chat/completions 127.0.0.1 200
request:  {
    "model": "llama2",
    "seed": 42,
    "messages": [
        {"role": "user", "content": "What day comes after Monday?"}
    ]
}
response: {"choices":[{"finish_reason":"stop","index":0,"message":{"content":"  The day that comes after Monday is Tuesday.","role":"assistant"}}],"created":1730554010,"model":"llama2","object":"chat.completion","usage":{"completion_tokens":13,"prompt_tokens":14,"total_tokens":27},"id":"chatcmpl-1MI5RsJZVBOPAMJSOPs33LkEXqbBVgta","__verbose":{"content":"  The day that comes after Monday is Tuesday.","id_slot":0,"stop":true,"model":"llama2","tokens_predicted":13,"tokens_evaluated":14,"generation_settings":{"n_ctx":4096,"n_predict":-1,"model":"/Users/amir36/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGUF/snapshots/08a5566d61d7cb6b420c3e4387a39e0078e1f2fe5f055f3a03887385304d4bfa/llama-2-7b-chat.Q4_K_M.gguf","seed":42,"seed_cur":42,"temperature":0.800000011920929,"dynatemp_range":0.0,"dynatemp_exponent":1.0,"top_k":40,"top_p":0.949999988079071,"min_p":0.05000000074505806,"xtc_probability":0.0,"xtc_threshold":0.10000000149011612,"tfs_z":1.0,"typical_p":1.0,"repeat_last_n":64,"repeat_penalty":1.0,"presence_penalty":0.0,"frequency_penalty":0.0,"mirostat":0,"mirostat_tau":5.0,"mirostat_eta":0.10000000149011612,"penalize_nl":false,"stop":[],"max_tokens":-1,"n_keep":0,"n_discard":0,"ignore_eos":false,"stream":false,"n_probs":0,"min_keep":0,"grammar":"","samplers":["top_k","tfs_z","typ_p","top_p","min_p","xtc","temperature"]},"prompt":"<s> [INST] What day comes after Monday? [/INST]","has_new_line":false,"truncated":false,"stopped_eos":true,"stopped_word":false,"stopped_limit":false,"stopping_word":"","tokens_cached":26,"timings":{"prompt_n":14,"prompt_ms":327.297,"prompt_per_token_ms":23.378357142857144,"prompt_per_second":42.774605327882625,"predicted_n":13,"predicted_ms":221.774,"predicted_per_token_ms":17.059538461538462,"predicted_per_second":58.61823297591241},"index":0,"oaicompat_token_ctr":13}}
```

difference -
commit 40f25557 - `"prompt":"[INST] What day comes after Monday? [/INST]"`
commit 958367bf - `"prompt":"<s> [INST] What day comes after Monday? [/INST]"`
```

**Comment by corrosive4354** [comment]
You can check the specific changes in commit 958367bf to confirm whether the addition of the <s> character is an intentional change. If so, you may need to adjust your test cases according to the new prompt format.

Seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use on Mac than Docker and homebrew

**Comment by anagri** [comment]
@ngxson - kindly have a look. the commit is authored by you. tx.

**Comment by ngxson** [comment]
To be honest, this is kinda expected and I don't think we gonna want to fix it.

The returned `"prompt"` now reflects the exact thing being process and in your case it's not wrong. The `<s>` is always there (even before the change), and it's required by the model to be added

**Comment by anagri** [comment]
ok, so previously, the behaviour was incorrect, and this change fixed it.

i will close this for now.  reopen if there are new findings.
