### ISSUE TITLE
Feature Request: langchain with_structured_output support

### ISSUE THREAD

**Issue by ymcki** [ggerganov/llama.cpp#10168]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

https://python.langchain.com/api_reference/community/llms/langchain_community.llms.llamacpp.LlamaCpp.html

I found that with_structured_output function is not implemented at langchain_community.llms.llamacpp.

Is it possible someone at llamacpp collaborate with langchain to implement it?

### Motivation

I am learning RAG from these jupyter notebook by loading ggufs with langchain_community.llms.llamacpp
https://github.com/langchain-ai/rag-from-scratch/blob/main/rag_from_scratch_10_and_11.ipynb

Some of them calls the with_structured_output method but it complains this method is not implemented.

Is it possible to implement this function at langchain? If not, is there anyway to do the same thing with another method implemented else where or some simple code?

**Comment by JohannesGaessler** [comment]
I think the correct place to ask for an implementation is the LangChain repository rather than the llama.cpp repository.

**Comment by ngxson** [comment]
The function is intentionally left unimplemented in langchain. There is nothing we can do inside llama.cpp because this part of the code is outside of llama.cpp

<img width="783" alt="image" src="https://github.com/user-attachments/assets/7feee2bd-96b2-4794-aa77-5ac4190be7a1">

**Comment by ymcki** [comment]
I found that it is supported by 
from langchain_community.chat_models import ChatLlamaCpp

So I will close this issue
