### ISSUE TITLE
tts : add basic example for text-to-speech

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#10173]
This new model seems suitable for integration: https://github.com/edwko/OuteTTS

We should add a very minimalistic example for generating audio with it. Ideally, we will implement the (audio tokens) -> (wav) from scratch.

**Comment by ggerganov** [comment]
> Do you have any opinions regarding if and how TTS should be integrated into the server?

Not yet. Seems like the biggest question is how to implement the WavTokenizer. If it's too complex, it might have to live in a separate project? With it's own server? Not sure.

Pinging @PABannier as they have experience with [encodec.cpp](https://github.com/PABannier/encodec.cpp) and to my understanding, WavTokenizer is something similar to Encodec?

**Comment by ngxson** [comment]
A bit off-topic, but having some kind of `audio-tokenizer.cpp` inside `llama.cpp` will be a very huge deal. It could potentially unlock all the pipeline like TTS, speech-to-text, speech-to-speech.

**Comment by bachittle** [comment]
> Pinging @PABannier as they have experience with [encodec.cpp](https://github.com/PABannier/encodec.cpp) and to my understanding, WavTokenizer is something similar to Encodec?

The paper mentions Encodec a lot, and says it follows the same paradigm in using a VQ-GAN: https://arxiv.org/pdf/2408.16532 . It is definitely feasible to implement an audio tokenizer here.

**Comment by PABannier** [comment]
+1 to @ngxson , tokens to WAV is a big step that bridges the gap between LLMs and TTS model. Encodec is one of those models.

Happy to explain in greater details what I did and help integrate Encodec (or a similar model to llama.cpp). As an example of how Encodec integrates after LLMs, you can check [Bark.cpp](https://github.com/PABannier/bark.cpp).

FYI, I'm in the process of upstreaming a bench of Metal kernels to ggml which come very handy to support Encodec (`ggml_conv_transpose_1d`, `ggml_elu`, `ggml_argmax`, `ggml_set_i32`, etc.).
