### ISSUE TITLE
ggml : move LLAMAFILE/tinyBLAS into a backend

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#10183]
The `LLAMAFILE` SGEMM routines are currently called directly from within `ggml-cpu.c` based on compile-time conditionals:

https://github.com/ggerganov/llama.cpp/blob/a9e8a9a0306a8093eef93b0022d9f45510490072/ggml/src/ggml-cpu.c#L7454-L7481

In order to simplify the logic and reduce the coupling of the different BLAS implementations, the `LLAMAFILE` code should be moved into a `ggml` backend, similar to the other BLAS implementations.

Not sure if it has to be a new backend, or if we can move it in the existing `ggml-blas` backend - TBD.

**Comment by Djip007** [comment]
I think I'll have a try to put it in a new backend...

It as not the standart sgemm API, nor support thread inside.

**Comment by slaren** [comment]
It may be better to keep it in the CPU backend to avoid the overhead of stopping and starting the threads that happens when switching to a different backend.

**Comment by ggerganov** [comment]
See discussion in https://github.com/ggerganov/llama.cpp/pull/10343#issuecomment-2480882304

**Comment by Djip007** [comment]
Start a [Discussion](https://github.com/ggerganov/llama.cpp/discussions/10350) to get a better idea of ​​how to do it
is there a better place to move forward on this topic?
