### ISSUE TITLE
Bug: SYCL crash

### ISSUE THREAD

**Issue by 0xDEADFED5** [ggerganov/llama.cpp#10184]
### What happened?

this is from b4020, as you can see from the task it took a while to occur.  earlier builds this didn't happen.
```
slot launch_slot_: id 38 | task 496680 | processing task
slot launch_slot_: id  2 | task 496681 | processing task
slot update_slots: id  2 | task 496681 | new prompt, n_ctx_slot = 2333, n_keep = 0, n_prompt_tokens = 683
slot update_slots: id  2 | task 496681 | kv cache rm [0, end)
slot update_slots: id  2 | task 496681 | prompt processing progress, n_past = 683, n_tokens = 689, progress = 1.000000
slot update_slots: id  2 | task 496681 | prompt done, n_past = 683, n_tokens = 689
slot update_slots: id 38 | task 496680 | new prompt, n_ctx_slot = 2333, n_keep = 0, n_prompt_tokens = 339
slot update_slots: id 38 | task 496680 | kv cache rm [0, end)
slot update_slots: id 38 | task 496680 | prompt processing progress, n_past = 339, n_tokens = 1028, progress = 1.000000
slot update_slots: id 38 | task 496680 | prompt done, n_past = 339, n_tokens = 1028
Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
Exception caught at file:D:/a/llama.cpp/llama.cpp/ggml/src/ggml-sycl.cpp, line:4221, func:operator()
SYCL error: CHECK_TRY_ERROR(dpct::gemm_batch( *main_stream, oneapi::mkl::transpose::trans, oneapi::mkl::transpose::nontrans, ne01, ne11, ne10, alpha, (const void **)(ptrs_src.get() + 0 * ne23), dpct::library_data_t::real_half, nb01 / nb00, (const void **)(ptrs_src.get() + 1 * ne23), dpct::library_data_t::real_half, nb11 / nb10, beta, (void **)(ptrs_dst.get() + 0 * ne23), cu_data_type, ne01, ne23, cu_compute_type)): Meet error in this line code!
  in function ggml_sycl_mul_mat_batched_sycl at D:/a/llama.cpp/llama.cpp/ggml/src/ggml-sycl.cpp:4221
D:\a\llama.cpp\llama.cpp\ggml\src\ggml-sycl\common.hpp:107: SYCL error
```

same error occurs in b4033

### Name and Version

.\llama-server.exe --version
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path:
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll
ggml_sycl_init: GGML_SYCL_FORCE_MMQ:   no
ggml_sycl_init: SYCL_USE_XMX: yes
ggml_sycl_init: found 1 SYCL devices:
version: 4033 (a9e8a9a0)
built with MSVC 19.41.34123.0 for

### What operating system are you seeing the problem on?

Windows

**Comment by 0xDEADFED5** [comment]
command line: `llama-server.exe -t 16 --threads-http 8 --mlock -ngl 99 -m C:\LLM\Qwen2.5-3B-Instruct_Q4_1.gguf --port 8888 --ctx-size 112000 -np 48 --temp .3 -dt .25 --batch-size 2000`

i was able to get it to crash on b4016 after 1200 or so queries, i've now rolled back to 4006 and i'll see how long it runs.

**Comment by NeoZhangJianyu** [comment]
what's your hardware info? like:
    GPU, free memory for GPU.
    Parameters of cmd

**Comment by 0xDEADFED5** [comment]
Intel Arc A770, parameters above. had another crash on b4058.  so far b3987 doesn't have this crash.

**Comment by 0xDEADFED5** [comment]
closing because i'm having trouble reproducing it now
