### ISSUE TITLE
Bug: ggml_metal_init error: zero-length arrays are not permitted in C++     float4x4 lo[D16/NW4];

### ISSUE THREAD

**Issue by a1ix2** [ggerganov/llama.cpp#10208]
### What happened?

Trying to run a llama-server on Apple Silicon M2 running Ventura. Same error either using the latest release or building from source. I'm trying to load Llama-3.2-3B-Instruct F16 from Meta. I created the gguf using `convert_hf_to_gguf.py`.
```
$ ./llama-server -m Llama-3.2-3B-Instruct-F16.gguf --verbose
```

#### From source
./llama-cli --version
version: 4048 (a71d81cf)
built with Apple clang version 15.0.0 (clang-1500.1.0.2.5) for arm64-apple-darwin22.6.0

#### From the release
$ ./llama-cli --version
version: 4044 (97404c4a)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.6.0

### What operating system are you seeing the problem on?

Mac

### Relevant log output

```shell
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2
ggml_metal_init: picking default device: Apple M2
ggml_metal_init: using embedded metal library
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:5134:17: error: zero-length arrays are not permitted in C++
    float4x4 lo[D16/NW4];
                ^~~~~~~
program_source:5391:18: note: in instantiation of function template specialization 'kernel_flash_attn_ext_vec<metal::matrix<half, 4, 4, void>, 1, &dequantize_f16, 64, 1, 32>' requested here
typedef decltype(kernel_flash_attn_ext_vec<half4x4, 1, dequantize_f16, 64>) flash_attn_ext_vec_t;
                 ^
program_source:5186:21: error: zero-length arrays are not permitted in C++
        float4x4 mq[D16/NW4];
                    ^~~~~~~
" UserInfo={NSLocalizedDescription=program_source:5134:17: error: zero-length arrays are not permitted in C++
    float4x4 lo[D16/NW4];
                ^~~~~~~
program_source:5391:18: note: in instantiation of function template specialization 'kernel_flash_attn_ext_vec<metal::matrix<half, 4, 4, void>, 1, &dequantize_f16, 64, 1, 32>' requested here
typedef decltype(kernel_flash_attn_ext_vec<half4x4, 1, dequantize_f16, 64>) flash_attn_ext_vec_t;
                 ^
program_source:5186:21: error: zero-length arrays are not permitted in C++
        float4x4 mq[D16/NW4];
                    ^~~~~~~
}
ggml_backend_metal_device_init: error: failed to allocate context
llama_new_context_with_model: failed to initialize Metal backend
common_init_from_params: failed to create context with model '/Users/username/dev/RAG/Llama-3.2-3B-Instruct-F16.gguf'
srv    load_model: failed to load model, '/Users/username/dev/RAG/Llama-3.2-3B-Instruct-F16.gguf'
main: exiting due to model loading error
```

**Comment by stefanb** [comment]
According to [llama.cpp pull requests in Homebrew](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+llama) the problem started appearing in https://github.com/Homebrew/homebrew-core/pull/196827, between tags b4034 and b4038

Diff: https://github.com/ggerganov/llama.cpp/compare/b4034...b4038

**Comment by a1ix2** [comment]
I can confirm that b4034 works, but b4036 throws the same error.

**Comment by stefanb** [comment]
> I can confirm that b4034 works, but b4036 throws the same error.

Which narrows down the problematic diff to https://github.com/ggerganov/llama.cpp/compare/b4034...b4036

**Comment by a1ix2** [comment]
The bug was introduced in [a1eaf6]. Previous commit [b8deef] works.

**Comment by stefanb** [comment]
Commit a1eaf6a9600bb1608753420ba886a3b0a208ffc0 was from merging
* https://github.com/ggerganov/llama.cpp/pull/10149

cc @ggerganov, any clues?

**Comment by ggerganov** [comment]
@stefanb Should be fixed now. Let me know if the issue persists.

**Comment by stefanb** [comment]
Tnx @ggerganov, waiting for the next tag (>b4056) containing the fix.

**Comment by stefanb** [comment]
@ggerganov, thanks, seems to be fixed 🎉 in
* https://github.com/Homebrew/homebrew-core/pull/197164

**Comment by a1ix2** [comment]
Can confirm, works on my M2! Thank you so much!

**Comment by eugeniosegala** [comment]
It looks like this problem is back?

I'm experiencing it as well, but I also noticed someone else opening a new issue: https://github.com/ggerganov/llama.cpp/issues/10696
