### ISSUE TITLE
web UI : support syntax highlighting

### ISSUE THREAD

**Issue by slaren** [ggerganov/llama.cpp#10246]
Add support for syntax highlighting in the code fragments of the model output.

**Comment by ChineseHamberger** [comment]
I would like to try this issue.

**Comment by ChineseHamberger** [comment]
I would like to try this issue.

**Comment by ChineseHamberger** [comment]
I am new to this area and would appreciate any guidance you can provide on how to get started. Could you please offer some suggestions or point me towards resources that might be helpful?

Thank you,

**Comment by slaren** [comment]
The web UI is made using vuejs and daisyui, so I would suggest looking into them and see if they have any components that may be useful for this purpose. I don't have any experience with these frameworks, so I can't offer you much more guidance that.
