### ISSUE TITLE
Bug: -ub cannot handle large number

### ISSUE THREAD

**Issue by FNsi** [ggerganov/llama.cpp#10251]
OS: windows 
Build: 3987
Backend: AVX2
Model: 14b qwen 128K ctx 

What's wrong:

ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer

ggml_gallocr_reserve_n: failed to allocate CPU buffer of size 139183763104

Reproduces: inference with -ub 6500, or larger.

**Comment by ExtReMLapin** [comment]
Sounds like a segfault error because 139183763104 is 139 gb

**Comment by slaren** [comment]
What is `-nb`?
```
$ ./llama-cli -m models/Qwen2.5-32B-Instruct-Q4_K_M.gguf -nb 6500
error: invalid argument: -nb
```

**Comment by FNsi** [comment]
> What is `-nb`?
> 
> ```
> 
> $ ./llama-cli -m models/Qwen2.5-32B-Instruct-Q4_K_M.gguf -nb 6500
> 
> error: invalid argument: -nb
> 
> ```

Sorry it's my silly fault... -ub indeed.

**Comment by FNsi** [comment]
> Sounds like a segfault error because 139183763104 is 139 gb

No clue, toady I change -ub to 4096 with -b 32768 in llama-cli also fault.

**Comment by slaren** [comment]
I have not been able to reproduce this, in my tests the compute buffer size always scales linearly with the batch size.

**Comment by FNsi** [comment]
![image](https://github.com/user-attachments/assets/6a7fb7b9-8df1-4b02-84cb-26e9c43e5143)

![image](https://github.com/user-attachments/assets/c0f7e872-e6b9-41b8-a287-b5ef4b74f597)

![image](https://github.com/user-attachments/assets/b98e7d98-aec0-4ba1-bca3-2562967d13ae)

![image](https://github.com/user-attachments/assets/52816a74-70f4-4bac-bed3-2affb9946c75)

I think it's by cause somehow

**Comment by slaren** [comment]
That stills looks to increase roughly linearly with the batch size, which is expected. Large contexts with large batch sizes can require a lot of memory. Enabling flash attn with `-fa` should reduce the memory usage to a much more reasonable level.

**Comment by FNsi** [comment]
> That stills looks to increase roughly linearly with the batch size, which is expected. Large contexts with large batch sizes can require a lot of memory. Enabling flash attn with `-fa` should reduce the memory usage to a much more reasonable level.

I think you are right but no clue why it works by chances...
