### ISSUE TITLE
Bug: docker sample usage will always trigger unhealty container status

### ISSUE THREAD

**Issue by lilunxm12** [ggerganov/llama.cpp#10262]
### What happened?

In the [docker usage documentation](https://github.com/ggerganov/llama.cpp/blob/54ef9cfc726a799e6f454ac22c4815d037716eda/docs/docker.md)

multiple sample usage of server image tells http server to listen on 8000 ([eg](https://github.com/ggerganov/llama.cpp/blob/54ef9cfc726a799e6f454ac22c4815d037716eda/docs/docker.md?plain=1#L53))

the problem is for server images, health check is [hardcoded to 8080 port](https://github.com/ggerganov/llama.cpp/blob/54ef9cfc726a799e6f454ac22c4815d037716eda/.devops/llama-server-cuda.Dockerfile#L40), so docker health check will always get connection refused and then report unhealthy status

the easist solution would be changing the sample command to use 8080 port

### Name and Version

that's a documentation issue unrelated to cli

### What operating system are you seeing the problem on?

Linux

**Comment by cchadowitz** [comment]
This still seems to be the case.
