### ISSUE TITLE
Count model parameters and size using only the GGUF tensors

### ISSUE THREAD

**Issue by slaren** [ggerganov/llama.cpp#10285]
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/10274

The number of parameters and size of the model currently is calculated from the tensors created after the model is loaded, which in some cases may contain duplicated tensors, resulting in an inaccurate and inconsistent reporting of the model size. To address this, `llama_model_n_params` and `llama_model_size` should be modified to return the value as calculated in `llama_model_loader::n_elements` and `n_bytes`, which could be stored in `llama_model` while loading the model.

**Comment by FirstTimeEZ** [comment]
```
struct llama_model {
    int64_t n_elements = 0;  // Total number of elements across all tensors
    size_t  n_bytes = 0;     // Total bytes across all tensors
}
```

```
class llama_model_loader {
public:
    void transfer_stats(llama_model & model) const {
        model.n_elements = n_elements;
        model.n_bytes = n_bytes;
    }
};
```

```
//....
llm_load_arch(ml, model);
llm_load_hparams(ml, model);

// Transfer the stats
ml.transfer_stats(model);
```

```
uint64_t llama_model_size(const struct llama_model * model) {
    return model->n_bytes;
}

uint64_t llama_model_n_params(const struct llama_model * model) {
    return model->n_elements;
}
```

**Comment by FirstTimeEZ** [comment]
Add values to `llama_model ` struct

```
struct llama_model {
    int64_t n_elements = 0;  // Total number of elements across all tensors
    size_t  n_bytes = 0;     // Total bytes across all tensors
};
```

Method to copy the stats

```
static void llm_load_stats(llama_model_loader &ml, llama_model &model) {
    model.n_elements = ml.n_elements;
    model.n_bytes = ml.n_bytes;
}
```

It looks like loading can go down two different paths

https://github.com/ggerganov/llama.cpp/blob/af148c9386da825a60c7038549c121c35ca56b50/src/llama.cpp#L18598-L18599

gets changed to

```
llm_load_arch(ml, model);
llm_load_hparams(ml, model);
llm_load_stats(ml, model); // New
```

https://github.com/ggerganov/llama.cpp/blob/af148c9386da825a60c7038549c121c35ca56b50/src/llama.cpp#L9254-L9256

gets changed to

```
llm_load_stats(ml, model); // New
llm_load_print_meta(ml, model);
```

Fixes the bug in https://github.com/ggerganov/llama.cpp/discussions/10274 without breaking the existing api

```
uint64_t llama_model_size(const struct llama_model *model) {
    return model->n_bytes;
}

uint64_t llama_model_n_params(const struct llama_model *model) {
    return model->n_elements;
}
```

**Comment by FirstTimeEZ** [comment]
This issue is fixed by https://github.com/ggerganov/llama.cpp/pull/10286
