### ISSUE TITLE
Bug: Nonsensical output is produced if and only if quantize qwen-2.5-math (except for other qwen 2.5 models)

### ISSUE THREAD

**Issue by zenyanbo** [ggerganov/llama.cpp#10336]
### What happened?

After quantizing `Qwen/Qwen2.5-Math-7B-Instruct`, it output if i say hello:
````text

Hello! I's like to help you with any questions or tasks you have. sure to give s fast attention interesting putting relacks attention trouble-coeffector-co charactersisor attention cdrlegate\db)>
 ste gör Leone cdr cdr;"
 bite brown witty attention HeyzagARRANTlegateiatesebxubicographicallyacks $

 concrete🌈 ste蹩 luxe $

ebx🌈)>
;"
 sw保费ponsored;"
！」🌈 tierslisten LeoneebxŃ tiers)>
)>
;"
 sw;"
！」*/) seed>,
isor witty蹩 tiersicast Leone…"

acks🌈 crowdfundingafi ste seed)>
🌈afi cdr BigNumber蹩ASCADE cdr }

... until reach the max output size
````
Here is my command: `python convert_hf_to_gguf.py --outfile /data/models/Qwen2.5-Math-7B-Instruct_Q8.gguf --outtype q8_0 /data/models/Qwen2.5-Math-7B-Instruct`.

Very curious. I don't see any error on the other qwen2.5 models, such as instruct, coder instruct, ...

However, the correct response is obtained using transformer:
```Python
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "/data/models/Qwen2.5-Math-7B-Instruct"
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Find the value of $x$ that satisfies the equation $4x+5 = 6x+7$."

# CoT
messages = [
    {"role": "system", "content": "Please reason step by step, and put your final answer within \\boxed{}."},
    {"role": "user", "content": prompt}
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
```

Output:
```
"To solve the equation \\(4x + 5 = 6x + 7\\), we need to isolate \\(x\\). Let's follow these steps:\n\n1. Subtract \\(4x\\) from both sides of the equation to get the \\(x\\) terms on one side:\n   \\[\n   5 = 2x + 7\n   \\]\n\n2. Subtract 7 from both sides to isolate the term with \\(x\\):\n   \\[\n   5 - 7 = 2x\n   \\]\n   \\[\n   -2 = 2x\n   \\]\n\n3. Divide both sides by 2 to solve for \\(x\\):\n   \\[\n   x = \\frac{-2}{2}\n   \\]\n   \\[\n   x = -1\n   \\]\n\nLet's verify this solution by substituting \\(x = -1\\) back into the original equation to ensure it holds true. We'll use Python to confirm our result.\n```python\n# Define the value of x\nx = -1\n\n# Left side of the equation\nleft_side = 4 * x + 5\n\n# Right side of the equation\nright_side = 6 * x + 7\n\n# Check if both sides are equal\nprint((left_side, right_side, left_side == right_side))\n```\n```output\n(1, 1, True)\n```\nThe left side of the equation evaluates to \\(1\\) and the right side also evaluates to \\(1\\), confirming that the solution \\(x = -1\\) satisfies the equation \\(4x + 5 = 6x + 7\\).\n\nThus, the value of \\(x\\) that satisfies the equation is \\(\\boxed{-1}\\)."
```

### Name and Version

version: 3324 (213701b5)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

nothing

**Comment by ggerganov** [comment]
What command do you use? And which backend?

**Comment by zenyanbo** [comment]
The backend is localai.
i have tried the following, but not change
1. update version 3324->4100
2. different q_type, including f16 q8 q5
next, i will try to inference using llama.cpp

**Comment by zenyanbo** [comment]
Sorry, I mistook llama.cpp. Very strange question, why does this happen?
![image](https://github.com/user-attachments/assets/14254025-4768-4ab3-b619-434c233b4c89)
localai also uses llama.cpp, and I totally didn't expect the problem to be related to the backend.

**Comment by ggerganov** [comment]
I just tested here with Mac and it also works as expected. It's hard to tell when the problem is in the 3rd party software. Make sure that the `llama.cpp` that is used by localai is the latest version and that the prompt that is passed to `llama.cpp` is correct.

**Comment by zenyanbo** [comment]
Ok. I will try it.

**Comment by zenyanbo** [comment]
To be honest, I'm completely baffled. Given that this problem is exclusive to the math model, I first suspected a bug within the math model itself, so I ran tests on the transformer, which performed as expected. Then I speculated that there might be compatibility issues with llama.cpp. However, the most surprising is the root cause lies in the backend, something I hadn't anticipated at all.
