### ISSUE TITLE
 I want to use gpt4all, but there is no convert-gpt4all-to-ggml.py file.

### ISSUE THREAD

**Issue by Hoozia** [ggerganov/llama.cpp#1036]
I tried to convert the gpt4all binary to the file written in the README, but I couldn't run it because there was no executable file.
Maybe the name of that file has been changed? Or is there a separate location?

**Comment by prusnak** [comment]
Just run `python3 convert.py models/gpt4all-7B/gpt4all-lora-quantized.bin`

More details in PR https://github.com/ggerganov/llama.cpp/pull/980

**Comment by onionhammer** [comment]
Do the docs need to be updated?

**Comment by prusnak** [comment]
> Do the docs need to be updated?

Yes, PR https://github.com/ggerganov/llama.cpp/pull/980
