### ISSUE TITLE
Bug: split-mode row, llama-bench works but llama-cli outputs is garbled

### ISSUE THREAD

**Issue by alain40** [ggerganov/llama.cpp#10384]
### What happened?

I can successfully run llama-bench, it shows a slight performance improvement with row splitting.

| model                          |       size |     params | backend    | threads | n_batch | n_ubatch |    sm | fa |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ------: | ------: | -------: | ----: | -: | ------------: | -------------------: |
| llama ?B IQ4_XS - 4.25 bpw     | 216.72 GiB |   410.08 B | CUDA,BLAS  |      64 |    1024 |     1024 | layer |  1 |           pp3 |          3.09 ± 0.01 |
| llama ?B IQ4_XS - 4.25 bpw     | 216.72 GiB |   410.08 B | CUDA,BLAS  |      64 |    1024 |     1024 | layer |  1 |           tg3 |          1.87 ± 0.01 |
| llama ?B IQ4_XS - 4.25 bpw     | 216.72 GiB |   410.08 B | CUDA,BLAS  |      64 |    1024 |     1024 |   row |  1 |           pp3 |          3.12 ± 0.01 |
| llama ?B IQ4_XS - 4.25 bpw     | 216.72 GiB |   410.08 B | CUDA,BLAS  |      64 |    1024 |     1024 |   row |  1 |           tg3 |          1.96 ± 0.01 |

build: 74d73dc8 (4094)

But when I run llama-cli with the same parameters (- fa --numa distribute -sm row) I get garbled output very slowly. 

Once this happens llama-bench gives a different result for -sm row!  performance is now about 1/10th of what it was before running llama-cli.

### Name and Version

$ ./llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA RTX A4000, compute capability 8.6, VMM: yes
  Device 1: NVIDIA RTX A4000, compute capability 8.6, VMM: yes
version: 4094 (74d73dc8)
built with cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
numaclt --hardware 
available: 8 nodes (0-7)
node 0 cpus: 0 1 2 3 4 5 6 7 64 65 66 67 68 69 70 71
node 0 size: 48131 MB
node 0 free: 41900 MB
node 1 cpus: 8 9 10 11 12 13 14 15 72 73 74 75 76 77 78 79
node 1 size: 48378 MB
node 1 free: 41791 MB
node 2 cpus: 16 17 18 19 20 21 22 23 80 81 82 83 84 85 86 87
node 2 size: 48378 MB
node 2 free: 42224 MB
node 3 cpus: 24 25 26 27 28 29 30 31 88 89 90 91 92 93 94 95
node 3 size: 48378 MB
node 3 free: 41685 MB
node 4 cpus: 32 33 34 35 36 37 38 39 96 97 98 99 100 101 102 103
node 4 size: 32203 MB
node 4 free: 26135 MB
node 5 cpus: 40 41 42 43 44 45 46 47 104 105 106 107 108 109 110 111
node 5 size: 48378 MB
node 5 free: 41767 MB
node 6 cpus: 48 49 50 51 52 53 54 55 112 113 114 115 116 117 118 119
node 6 size: 48378 MB
node 6 free: 15017 MB
node 7 cpus: 56 57 58 59 60 61 62 63 120 121 122 123 124 125 126 127
node 7 size: 48335 MB
node 7 free: 42239 MB
node distances:
node   0   1   2   3   4   5   6   7 
  0:  10  12  12  12  32  32  32  32 
  1:  12  10  12  12  32  32  32  32 
  2:  12  12  10  12  32  32  32  32 
  3:  12  12  12  10  32  32  32  32 
  4:  32  32  32  32  10  12  12  12 
  5:  32  32  32  32  12  10  12  12 
  6:  32  32  32  32  12  12  10  12 
  7:  32  32  32  32  12  12  12  10 

GPU0 in CPU0 slot
GPU1 in CPU1 slot
```

**Comment by JohannesGaessler** [comment]
I am unable to reproduce the issue. Can you share the exact model and command that you are using?

**Comment by JohannesGaessler** [comment]
`llama-bench` does not check the results for correctness at all, it only measures how long the model evaluation takes. Just to be clear: when you run `llama-cli` without `--split-mode row` the results are as they should be, right?

**Comment by alain40** [comment]
Understood. I observe 2 things:
- A bug. llama-cli works fine, but fails with the -sm row option and produces garbage.
- An oddity. llama-bench -sm row produces two different results, 10x apart (on a freshly rebooted machine) depending on whether I run it before or after running the failing llama-cli -sm row

**Comment by JohannesGaessler** [comment]
I am still unable to reproduce the issue.

**Comment by alain40** [comment]
I assume that this means that the bug is specific to my hw configuration.

**Comment by alain40** [comment]
Made some progress: if I plug the 2 GPUs in the 2 Pcie slots connected to a single CPU -sm row works as expected.

The problem arises when each GPU is in a slot connected to a different CPU (I run a dual CPU system). Perhaps as I suspected a P2P dma Access issue or similar.

Perhaps  llama-bench is able to handle (based on the reported performance) but llama-cli can't.

**Comment by alain40** [comment]
Just recompiled the latest version (4145) ... And the bug is gone. -sm row works reliably in all my tests

**Comment by alain40** [comment]
Fixed in version 4145.
