### ISSUE TITLE
Feature Request: [CANN] Use the RoPE operator provided by aclnn

### ISSUE THREAD

**Issue by noemotiovon** [ggerganov/llama.cpp#10396]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Use the RoPE operator provided by aclnn instead of manually coding RoPE to improve the performance of the RoPE operator.

### Motivation

The RoPE performance of the aclnn operator library will be better!

### Possible Implementation

Adjust the RoPE operator provided by the operator library using aclnn.

**Comment by hipudding** [comment]
see #10488
