### ISSUE TITLE
Anyplan to make CodeGenCPP?

### ISSUE THREAD

**Issue by v3ss0n** [ggerganov/llama.cpp#104]
Llama models seesm to be not useful for code genration.

Any chance to get CodeGen models work on CPU ? https://github.com/salesforce/CodeGen

**Comment by v3ss0n** [comment]
Now since Discussion tab is opnened , i am going to open a topic and post there.

**Comment by AayushSameerShah** [comment]
Hey!!!! @v3ss0n 
Looking for the same, I am willing to convert this: https://huggingface.co/NumbersStation/nsql-2B model into GGUF - which infact based on the CodeGen model.

Any luck with this?

**Comment by ruze00** [comment]
Why are there crickets for this question?  Is it that Salesforce is too non-standard or something else?
