### ISSUE TITLE
Bug: llama-server not loading the UI

### ISSUE THREAD

**Issue by anagri** [ggerganov/llama.cpp#10404]
### What happened?

building the llama-server from scratch using the latest 8e752a7

```bash
./examples/server/deps.sh
rm -rf build && cmake -S . -B build && cmake --build build --config Release -j $(sysctl -n hw.logicalcpu) --target llama-server
```

on running the server, then loading the `http://127.0.0.1:8080` getting the following logs -
```
main: server is listening on http://127.0.0.1:8080 - starting the main loop
srv  update_slots: all slots are idle
request: GET / 127.0.0.1 200
request: GET /index.js 127.0.0.1 404
request: GET /completion.js 127.0.0.1 200
request: GET /json-schema-to-grammar.mjs 127.0.0.1 404
```

the index.html is expecting `/index.js` and other files, which are returning 404. i have downloaded the dependencies, but still few files are missing. kindly check if these files are downloaded with `deps.sh`.

### Name and Version

$ ./build/bin/llama-cli --version
version: 4131 (8e752a77)
built with Homebrew clang version 18.1.5 for arm64-apple-darwin23.3.0

### What operating system are you seeing the problem on?

Mac

**Comment by anagri** [comment]
attn: @ngxson

**Comment by ngxson** [comment]
It's either your browser cache the old page, or you need to clean the build. Ref: https://github.com/ggerganov/llama.cpp/pull/10175#issuecomment-2463316247

**Comment by anagri** [comment]
run `git clean -dfX` to clean the ignored files, and rerun the build.
