### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#105]
We should probably make a logo for this project. Like an image of a 🦙 and some C++

**Comment by prusnak** [comment]
Not really a logo, but something that Midjourney came up with 😄 

![stick_llama_programming_on_a_computer_writing_c_code_51b1da50-f389-4cb5-ba4f-9b09083d7b4e](https://user-images.githubusercontent.com/42201/224839373-29ce1bda-22b5-48af-aa97-afb57942b1a6.png)

**Comment by gjmulder** [comment]
Stable Diffusion:

![llama_cpp](https://user-images.githubusercontent.com/10833500/224841861-3c8d70e6-3668-4ce5-864a-83e60b728091.png)

**Comment by leszekhanusz** [comment]
![llama3](https://user-images.githubusercontent.com/4641499/224842324-6bef0d46-17b6-400f-8afc-fa9521fa23da.png)

**Comment by gojosh** [comment]
![llama_cpp](https://user-images.githubusercontent.com/229941/224846830-71002ab8-6c0d-49bc-bfcc-669618bbcdbe.png)

**Comment by tljstewart** [comment]
![Untitled (1)](https://user-images.githubusercontent.com/8463038/224852365-dcf76fd8-e52d-46b1-9de9-fafda5a81495.png)

**Comment by richinseattle** [comment]
![image](https://user-images.githubusercontent.com/1887673/224868447-6dafecf7-ed84-4842-8210-3843de49bf34.png)

**Comment by Acelogic** [comment]
> ![llama_cpp](https://user-images.githubusercontent.com/229941/224846830-71002ab8-6c0d-49bc-bfcc-669618bbcdbe.png)

I like this one, but I think we need a white version too :)

**Comment by leszekhanusz** [comment]
@gojosh which font did you use?

**Comment by gojosh** [comment]
> @gojosh which font did you use?

Verlag Compressed Black for LLAMA and Verlag Bold Italic for C

**Comment by gojosh** [comment]
I'll work up some variations with alternate colors, including white.

**Comment by gojosh** [comment]
A few variations with LLaMA:
![llama_cpp_concepts](https://user-images.githubusercontent.com/229941/225038032-291f6f06-7f8f-426f-a6fd-8e8527a2ba51.png)

**Comment by leszekhanusz** [comment]
Using your font in a banner with my icon:

![banner](https://user-images.githubusercontent.com/4641499/225039541-486ae03d-ec58-4393-85ed-88e676af8839.png)

**Comment by tim-gromeyer** [comment]
> A few variations with LLaMA: ![llama_cpp_concepts](https://user-images.githubusercontent.com/229941/225038032-291f6f06-7f8f-426f-a6fd-8e8527a2ba51.png)

IMO the first 1 ist the best

**Comment by gjmulder** [comment]
> Using your font in a banner with my icon:
> 
> ![banner](https://user-images.githubusercontent.com/4641499/225039541-486ae03d-ec58-4393-85ed-88e676af8839.png)

Perhaps shorten to "Make your LLaMAs run at speed C++"?

**Comment by leodr** [comment]
> A few variations with LLaMA: ![llama_cpp_concepts](https://user-images.githubusercontent.com/229941/225038032-291f6f06-7f8f-426f-a6fd-8e8527a2ba51.png)

I quite like this one, simple and clever. Probably also looks good in small sizes like in an app icon.

**Comment by mohataj** [comment]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/879585/225055999-b9a5be53-69ae-44dd-a899-f4ee343956a8.png">

**Comment by mohataj** [comment]
![image](https://user-images.githubusercontent.com/879585/225065922-88a4c6a4-2b0a-46a0-b2b8-750f31ff2d32.png)

**Comment by mohataj** [comment]
![image](https://user-images.githubusercontent.com/879585/225067376-c0e18678-c484-4a22-9bee-544e376bb9d3.png)

**Comment by mohataj** [comment]
![image](https://user-images.githubusercontent.com/879585/225068294-f751484a-2efa-49f0-adb7-803d42f9db19.png)

**Comment by mohataj** [comment]
![image](https://user-images.githubusercontent.com/879585/225069972-ae2bc54c-c614-47aa-87af-ac792fd8fa66.png)

**Comment by mohataj** [comment]
![image](https://user-images.githubusercontent.com/879585/225071189-36ee5987-b5ca-466b-b7fc-c8c21227b472.png)

**Comment by samuelahmed** [comment]
The font one posted by @gojosh is good, clean and simple. 

Adding this one for fun. 
<img width="355" alt="llamacppLogo" src="https://user-images.githubusercontent.com/25234980/225105837-23af4a82-7921-430b-a282-d22756e2bb9c.png">

**Comment by ggerganov** [comment]
Yup, I also like @gojosh suggestions

**Comment by DJPatron** [comment]
![LLama_github_logo](https://user-images.githubusercontent.com/67385488/225127607-1c4e2c49-a0cd-43da-b70b-117995c63d36.png)

**Comment by pluja** [comment]
I made a simple and classic-looking logo:

![Llama cpp logo](https://i.imgur.com/RnMqzgv.jpeg)

**Comment by pluja** [comment]
and here's another concept idea:

![llama.cpp 2](https://i.imgur.com/n6f8Cvv.jpeg)

**Comment by pluja** [comment]
And here's another concept idea:

![](https://i.ibb.co/hYfn1Tz/llamacpp3low.jpg)

I can provide the full scale HD image on request, and the PSD file for editing

**Comment by tim-gromeyer** [comment]
> ![](https://i.ibb.co/hYfn1Tz/llamacpp3low.jpg)

I like this one

**Comment by jrflga** [comment]
![llamacpp_logo_dark](https://user-images.githubusercontent.com/3507471/225431812-175446e0-1f95-405a-821f-79ed3fd23498.png)
![llamacpp_logo](https://user-images.githubusercontent.com/3507471/225431818-cf83c98e-bc28-4537-8d24-4da4fb8ada99.png)

**Comment by G2G2G2G** [comment]
@ggerganov since you were looking at something funny but decided the pull req one was too cocky. What about a mixture of @leszekhanusz 's and @pluja 's "DOOM" one which is funny

**Comment by gucr** [comment]
Here are my 2 cents with a funky version
<img width="877" alt="llama" src="https://user-images.githubusercontent.com/6040008/225515419-d02ab031-9fcc-4d17-9ca4-1573c3a2a7d9.png">

**Comment by solacrypto** [comment]
Just a friendl go at it. Really appreciate the work done here with things here  🙏

![llama](https://user-images.githubusercontent.com/90992099/225522866-80486e7e-bb16-42c1-b403-9d919189ae19.png)

**Comment by ueberf** [comment]
Gave it a quick shot myself! 🦙

My thought behind this design was to create a logo that:
- incapsulates the element of a language model (abstracted text lines, inspired by fonts like [Flow Rounded](https://fonts.google.com/specimen/Flow+Rounded?preview.text=Lama&preview.text_type=custom&query=rounded))
- works in color and in monochrome
- is adaptable to different needs (e.g. only the icon, or icon + project name)


![llama-logo](https://user-images.githubusercontent.com/19748898/225653701-943df06c-044d-4cf1-8242-d3075fba1c96.jpg)

**Comment by tim-gromeyer** [comment]
> ![llama-logo](https://user-images.githubusercontent.com/19748898/225653701-943df06c-044d-4cf1-8242-d3075fba1c96.jpg)

Great job! I like all of them!

**Comment by Da-mi-en** [comment]
![Llama logo](https://user-images.githubusercontent.com/9321540/226150364-fb32858f-5c95-45c3-8188-6e2e8fdef7d3.jpeg)

**Comment by Jungwon-Chang** [comment]
![DALL·E 2023-03-22 11 37 52 - a surrealistic dreamlike oil painting of robotic lama that is coding](https://user-images.githubusercontent.com/44089395/226805507-7a811801-7195-4e91-ae08-c68befddc99c.png)
not sort of a logo, but made a painting of a LLAMA chatbot via DALL-E2 :)

**Comment by mmyjona** [comment]
![llama_title](https://user-images.githubusercontent.com/1235078/227151619-154fd341-705e-47b1-9464-d8b492cd4bb7.png)
![llama_icon](https://user-images.githubusercontent.com/1235078/227151634-ea02cb3b-0040-483d-8975-ff9607d2634b.png)

**Comment by mmyjona** [comment]
![llama_icon](https://user-images.githubusercontent.com/1235078/227153969-b2eedf06-db12-45c5-80de-e01556497871.png)
![llama_title](https://user-images.githubusercontent.com/1235078/227153978-ca0c5608-71ca-44bd-97d8-d6ec5cc42268.png)

**Comment by Da-mi-en** [comment]
> ![llama_icon](https://user-images.githubusercontent.com/1235078/227153969-b2eedf06-db12-45c5-80de-e01556497871.png)
> ![llama_title](https://user-images.githubusercontent.com/1235078/227153978-ca0c5608-71ca-44bd-97d8-d6ec5cc42268.png)

This should be it.

**Comment by mmyjona** [comment]
![llama_title_2](https://user-images.githubusercontent.com/1235078/227241206-385d5ada-1cde-4e68-bb19-d7da75229b48.png)
![llama_icon_2](https://user-images.githubusercontent.com/1235078/227241216-3e19fafa-2d14-4dc7-b548-6f4fce76db59.png)

**Comment by leszekhanusz** [comment]
> @ggerganov since you were looking at something funny but decided the pull req one was too cocky. What about a mixture of @leszekhanusz 's and @pluja 's "DOOM" one which is funny

Here you go:
![banner](https://user-images.githubusercontent.com/4641499/227257715-56a58d83-207d-48b7-8a93-8cb5410b5c40.png)

And a second version with a simplified logo:
![banner2](https://user-images.githubusercontent.com/4641499/227257798-d8c1bb5f-d919-4e0d-838b-ba5f8950977f.png)

**Comment by Auxnon** [comment]
> Gave it a quick shot myself! 🦙
> 
> My thought behind this design was to create a logo that:
> 
> * incapsulates the element of a language model (abstracted text lines, inspired by fonts like [Flow Rounded](https://fonts.google.com/specimen/Flow+Rounded?preview.text=Lama&preview.text_type=custom&query=rounded))
> * can be used in small sizes (like an app icon)
> * works in color and in monochrome
> * is adaptable to different needs (e.g. only the icon, or icon + project name)
> 
> ![llama-logo](https://user-images.githubusercontent.com/19748898/225653701-943df06c-044d-4cf1-8242-d3075fba1c96.jpg)

Bumping this one, love the compactness

**Comment by anzz1** [comment]
I think I found the one

![llamalul](https://user-images.githubusercontent.com/13628128/227761001-0c5940cb-de4f-4cd3-8b69-003a6f64506a.png)

**Comment by ggerganov** [comment]
> And here's another concept idea:
> 
> ![](https://camo.githubusercontent.com/0941c760a0702f80cbb8e16433afa1d0a76edfb82b6bae35271cf86a8c02e062/68747470733a2f2f692e6962622e636f2f6859666e31547a2f6c6c616d61637070336c6f772e6a7067)
> 
> And here's an idea of a banner for it:
> 
> ![](https://camo.githubusercontent.com/199807ad0d5cb45124c13eb1920abab0c801768a7aa7be533332013b353a87d9/68747470733a2f2f692e696d6775722e636f6d2f3230644b6f66392e706e67)
> 
> I can provide the full scale HD image on request, and the PSD file for editing

Adding this one for now, but there are so many others that are good, so I am thinking we will just shuffle them over time!

**Comment by ueberf** [comment]
> Gave it a quick shot myself! 🦙
> 
> My thought behind this design was to create a logo that:
> 
> * incapsulates the element of a language model (abstracted text lines, inspired by fonts like [Flow Rounded](https://fonts.google.com/specimen/Flow+Rounded?preview.text=Lama&preview.text_type=custom&query=rounded))
> * can be used in small sizes (like an app icon)
> * works in color and in monochrome
> * is adaptable to different needs (e.g. only the icon, or icon + project name)
> 
> ![llama-logo](https://user-images.githubusercontent.com/19748898/225653701-943df06c-044d-4cf1-8242-d3075fba1c96.jpg)

Love the idea of rotating banners, @ggerganov!

I attached my logo/ banner pack as png and svg if someone wants to remix them further 🦙


![Llama-Banner-Blue](https://user-images.githubusercontent.com/19748898/228299979-1470812b-9d0b-4060-b923-586ebeb9f3c9.png)
[Llama.cpp-logo.zip](https://github.com/ggerganov/llama.cpp/files/11091512/Llama.cpp-logo.zip)

**Comment by jessicachitas** [comment]
> A few variations with LLaMA: ![llama_cpp_concepts](https://user-images.githubusercontent.com/229941/225038032-291f6f06-7f8f-426f-a6fd-8e8527a2ba51.png)

Are there svgs available for these logos?

**Comment by d-kleine** [comment]
> Adding this one for now, but there are so many others that are good, so I am thinking we will just shuffle them over time!

Please don't shuffle, this might lead to confusion and a lack of brand recognition ⚠️ 

> I quite like this one, simple and clever. Probably also looks good in small sizes like in an app icon.

I would prefer a more compact, quadratic design for the logo with a single color scheme with a white/transparent background, rather than the current wide text-included and multi-colored version (I would remove the "LLaMa" before the "C++"; the "C++" with the llama ears are sufficient imho as a logo / icon)

**Comment by codeAndxv** [comment]
Have you considered setting an official logo in a circular or square shape?

**Comment by ggerganov** [comment]
@codeAndxv No, I don't have the skills to do it. Contributions are welcome.

**Comment by MariaLeonova** [comment]
> > A few variations with LLaMA: ![llama_cpp_concepts](https://user-images.githubusercontent.com/229941/225038032-291f6f06-7f8f-426f-a6fd-8e8527a2ba51.png)
> 
> Are there svgs available for these logos?
> 
> Edit: Or even a png with no background of logo 3A would suffice if that one is in use.

@jessicachitas I don't know if you ever found the svg, but here's a trace: 

![Image](https://github.com/user-attachments/assets/4d0df499-ba76-4676-95f5-db5bd9198bfc)
