### ISSUE TITLE
Compile bug: CI case in github action "ubuntu-latest-cmake-cuda" is fault

### ISSUE THREAD

**Issue by NeoZhangJianyu** [ggerganov/llama.cpp#10521]
### Git commit

0bbd2262a3263f37385297b30de37941836e57f7

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

0bbd2262a3263f37385297b30de37941836e57f7

### First Bad Commit

https://github.com/ggerganov/llama.cpp/pull/10474

### Relevant log output

```shell
CI case in github action "ubuntu-latest-cmake-cuda" is fault.
It breaks all release build after merge https://github.com/ggerganov/llama.cpp/pull/10474.
```

**Comment by slaren** [comment]
I don't think there is anything wrong with the CUDA CI. The reason this error only shows on that build is likely because it uses a newer version of GCC.
