### ISSUE TITLE
Compile bug: ARM neon instructions when compiling cuda

### ISSUE THREAD

**Issue by bruceloco** [ggerganov/llama.cpp#10531]
### Git commit

45abe0f74ee281aea6e5283c1e738061256cfcae

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I am on a raspberry pi, downloaded cuda toolkit 12.6 on arm64, same happened on cuda 11 toolkit
__ARM_NEON is being defined and passed to the cuda files that include either:
ggml/src/ggml-cpu/ggml-cpu-impl.h 
or
ggml/src/ggml-impl.h

It breaks the build as nvcc tries to include arm_neon for these two files:
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/opt-step-adamw.cu

a dirty fix is to undefine it at the top of these files
a more permanent fix would be to segment CPU flags/includes from GPU includes

### Relevant log output

```shell
/usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h(1829): error: identifier "__builtin_aarch64_ssubwv4hi" is undefined
return __builtin_aarch64_ssubwv4hi (__a, __b);
^

/usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h(1836): error: identifier "__builtin_aarch64_ssubwv2si" is undefined
return __builtin_aarch64_ssubwv2si (__a, __b);
^

/usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h(1843): error: identifier "__builtin_aarch64_usubwv8qi_uuu" is undefined
return __builtin_aarch64_usubwv8qi_uuu (__a, __b);
^

Error limit reached.
100 errors detected in the compilation of "ggml/src/ggml-cuda/opt-step-adamw.cu".
Compilation terminated.
```

**Comment by bruceloco** [comment]
Ah, this is funny, it was a matter of hours :D

**Comment by ggerganov** [comment]
The change should be synced now. @bruceloco See if it works now and close the issue if all is good.

**Comment by bruceloco** [comment]
@ggerganov  perfect, it builds now
