### ISSUE TITLE
Compile bug: ggml-impl.h(314): error: identifier "__fp16" is undefined on Jetson AGX Xavier

### ISSUE THREAD

**Issue by pondahai** [ggerganov/llama.cpp#10555]
### Git commit

Commit 9f91251

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I am trying to compile
llama.cpp
on an NVIDIA Jetson AGX Xavier and I am getting the error:

/tmp/llama.cpp/ggml/src/ggml-cuda/../ggml-impl.h(314): error: identifier "__fp16" is undefined
There were other errors originally, but since
Commit 9f91251
, those errors have disappeared. However, now I am encountering the error mentioned above.

### Relevant log output

```shell
cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- CMAKE_SYSTEM_PROCESSOR: aarch64
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- OpenMP found
-- Using llamafile
-- ARM detected
-- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E
-- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E - Failed
-- Using runtime weight conversion of Q4_0 to Q4_0_x_x to enable optimized GEMM/GEMV kernels
-- Including CPU backend
CMake Warning at ggml/src/ggml-amx/CMakeLists.txt:104 (message):
  AMX requires x86 and gcc version > 11.0.  Turning off GGML_AMX.


-- Found CUDAToolkit: /usr/local/cuda-11.4/include (found version "11.4.315") 
-- CUDA Toolkit found
-- Using CUDA architectures: 52;61;70;75
-- The CUDA compiler identification is NVIDIA 11.4.315
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA host compiler is GNU 9.4.0

-- Including CUDA backend
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/llama.cpp/build
nvidia@ubuntu:/tmp/llama.cpp$ cmake --build build --config Release
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  3%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-aarch64.c.o
[  3%] Linking CXX shared library libggml-base.so
[  3%] Built target ggml-base
[  4%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/acc.cu.o
[  4%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/arange.cu.o
[  5%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/argmax.cu.o
[  5%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/argsort.cu.o
[  5%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/binbcast.cu.o
[  6%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/clamp.cu.o
[  6%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/concat.cu.o
[  7%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/conv-transpose-1d.cu.o
[  7%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/convert.cu.o
[  7%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/count-equal.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/cpy.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/cross-entropy-loss.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/diagmask.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn-tile-f16.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn-tile-f32.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/getrows.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/ggml-cuda.cu.o
/tmp/llama.cpp/ggml/src/ggml-cuda/../ggml-impl.h(314): error: identifier "__fp16" is undefined

1 error detected in the compilation of "/tmp/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu".
make[2]: *** [ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/build.make:314: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/ggml-cuda.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1760: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by frankier** [comment]
I think maybe we need to guard this branch:

https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L314

and this branch

https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L319-L336

from NVCC.

You could try changing this line:

https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L311

to `#if defined(_MSC_VER) || defined(__CUDACC__)`

And this line:

https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L318

to `#if defined(__ARM_NEON) && !defined(_MSC_VER) && !defined(__CUDACC__)`

Could you make these changes and then test? I'm also trying to fix this for packaging on conda-forge, but it's a bit annoying since I don't have this configuration available locally.

**Comment by pondahai** [comment]
@frankier 
Thank you, the compilation was successful. However, I noticed something strange. When I used CMake to compile, it was very slow, but when I used Make, it was much faster. But this might be because I ran the
make llama-server
command, and after CMake finished compiling, it got stuck on the model loading part for a long time. So I switched to using the Make command instead, and the same command ran smoothly. Everything is working fine now.

**Comment by walker-ai** [comment]
> I think maybe we need to guard this branch:
> 
> https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L314
> 
> and this branch
> 
> https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L319-L336
> 
> from NVCC.
> 
> You could try changing this line:
> 
> https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L311
> 
> to `#if defined(_MSC_VER) || defined(__CUDACC__)`
> 
> And this line:
> 
> https://github.com/ggerganov/llama.cpp/blob/76b27d29c22af03172cf211a8a31025c7c828a57/ggml/src/ggml-impl.h#L318
> 
> to `#if defined(__ARM_NEON) && !defined(_MSC_VER) && !defined(__CUDACC__)`
> 
> Could you make these changes and then test? I'm also trying to fix this for packaging on conda-forge, but it's a bit annoying since I don't have this configuration available locally.

I m using AGX Orin and I have encountered this error too. And this method is also useful for me. Thx

**Comment by frankier** [comment]
Hm this only seems to affect CUDA 11 but not CUDA 12 or 13 in conda-forge. I think maybe we could also guard with `__CUDACC_VER_MAJOR__ <= 11`.

@walker-ai @pondahai Are you both on CUDA <= 11? If so I'll add this too and put together a PR.

**Comment by walker-ai** [comment]
> Hm this only seems to affect CUDA 11 but not CUDA 12 or 13 in conda-forge. I think maybe we could also guard with `__CUDACC_VER_MAJOR__ <= 11`.
> 
> @walker-ai @pondahai Are you both on CUDA <= 11? If so I'll add this too and put together a PR.

I m using cuda-11.8 right now.

**Comment by pondahai** [comment]
My system has CUDA 11.4.19 installed.

**Comment by pondahai** [comment]
I used CMake to build the latest source code, and it compiled successfully, but it doesn't run properly. It gets stuck on model loading, and even with verbose mode, there are no additional messages.
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Xavier, compute capability 7.2, VMM: yes
build: 4261 (2759916d) with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for aarch64-linux-gnu
system info: n_threads = 8, n_threads_batch = 8, total_threads = 8

system_info: n_threads = 8 (n_threads_batch = 8) / 8 | CUDA : USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : NEON = 1 | ARM_FMA = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | 

main: HTTP server is listening, hostname: 127.0.0.1, port: 8080, http threads: 7
main: loading model
srv    load_model: loading model '/media/nvidia/sd/qwen2.5-coder-7b-instruct-q4_k_m.gguf'
```

**Comment by frankier** [comment]
Ah ok. I misunderstood the earlier messages to mean this worked with the proposed fix. This fix somewhat suspect then. It's a bit difficult to do much without the hardware though. You should try to run run using a debugger then you should be able to interrupt and get a stack trace of where things are getting stuck which should clarify the problem a bit.

**Comment by pondahai** [comment]
@frankier Thank you for your suggestion. It seems like it might not be easy. I'll give it a try.

**Comment by pondahai** [comment]
I temporarily don't know how to troubleshoot the issue with CMake compilation, so I use
```
LLAMA_MAKEFILE=1
```
to continue using Makefile for compilation.

**Comment by hkr04** [comment]
I've also encountered a similar problem like that on Jetson AGX Orin:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Orin, compute capability 8.7, VMM: yes
build: 0 (unknown) with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for aarch64-linux-gnu
main: llama backend init
main: load the model and apply lora adapter, if any
```
With successful compilation, the process got stuck on loading the model.

**Comment by hkr04** [comment]
> > I've also encountered a similar problem like that on Jetson AGX Orin:
> > ```
> > ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
> > ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
> > ggml_cuda_init: found 1 CUDA devices:
> >   Device 0: Orin, compute capability 8.7, VMM: yes
> > build: 0 (unknown) with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for aarch64-linux-gnu
> > main: llama backend init
> > main: load the model and apply lora adapter, if any
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With successful compilation, the process got stuck on loading the model.
> 
> I have similar problem like that on Jetson AGX，Do you have a solution?
> 
> ```
> ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
> ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
> ggml_cuda_init: found 1 CUDA devices:
>   Device 0: Xavier, compute capability 7.2, VMM: yes
> ```

Sadly I didn't solve that. And now I couldn't access to the previous Jetson AGX (not a private one). But maybe the container from [dust-nv/jetson-containers](https://github.com/dusty-nv/jetson-containers/tree/master/packages/llm/llama_cpp) could be your temporary solution. (Or checkout to the version it used?)

**Comment by sangyuxiaowu** [comment]
> > > I've also encountered a similar problem like that on Jetson AGX Orin:
> > > ```
> > > ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
> > > ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
> > > ggml_cuda_init: found 1 CUDA devices:
> > >   Device 0: Orin, compute capability 8.7, VMM: yes
> > > build: 0 (unknown) with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for aarch64-linux-gnu
> > > main: llama backend init
> > > main: load the model and apply lora adapter, if any
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > With successful compilation, the process got stuck on loading the model.
> > 
> > 
> > I have similar problem like that on Jetson AGX，Do you have a solution?
> > ```
> > ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
> > ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
> > ggml_cuda_init: found 1 CUDA devices:
> >   Device 0: Xavier, compute capability 7.2, VMM: yes
> > ```
> 
> Sadly I didn't solve that. And now I couldn't access to the previous Jetson AGX (not a private one). But maybe the container from [dust-nv/jetson-containers](https://github.com/dusty-nv/jetson-containers/tree/master/packages/llm/llama_cpp) could be your temporary solution. (Or checkout to the version it used?)

Okay, thank you for your reply. I am trying to upgrade CUDA and compile it, and I have also seen the nv Docker project. It seems too old and many new models do not support it.
