### ISSUE TITLE
Misc. bug: Cannot get GPU offloading to work even though compiled with CUDA support

### ISSUE THREAD

**Issue by vmajor** [ggerganov/llama.cpp#10553]
### Name and Version

version: 4199 (9e2301f4)
built with cc (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Problem description & steps to reproduce

git pull 
make clean
make GGML_CUDA=1 GGML_CUDA_ENABLE_UNIFIED_MEMORY=1

./llama-server -m /media/user/AI2/models/qwen2.5-7b-instruct-q6_k-00001-of-00002.gguf -c 0 --mirostat 2 -fa -j {} -ngl 20 --no-mmap

ggml_cuda_init: failed to initialize CUDA: unknown error
warning: not compiled with GPU offload support, --gpu-layers option will be ignored
warning: see main README.md for information on enabling GPU BLAS support
build: 4199 (9e2301f4) with cc (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0 for x86_64-linux-gnu
system info: n_threads = 44, n_threads_batch = 44, total_threads = 88

system_info: n_threads = 44 (n_threads_batch = 44) / 88 | CUDA : ARCHS = 520 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | 

### Relevant log output

```shell
No errors during compile
```

**Comment by JohannesGaessler** [comment]
The warning is misleading. llama.cpp was compiled with CUDA support but for some reason the calls to the CUDA library are failing so the CUDA backend is not being initialized correctly.

I am unable to reproduce this issue.

**Comment by vmajor** [comment]
I have solved this issue by installing the new CUDA toolkit and nvidia-open from here

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local

then recompiled as before.
