### ISSUE TITLE
Eval bug: fail to load model in MacOS

### ISSUE THREAD

**Issue by Animaxx** [ggerganov/llama.cpp#10585]
### Name and Version

https://github.com/ggerganov/llama.cpp/commit/5931c1f233c616083d64e41a228249d58e039aa5 (ggml : add support for dynamic loading of backends) this commit causing model loading error in MacOS

in llama.cpp, `make_cpu_buft_list` function
 ```
    // add extra buffer types
    auto * cpu_dev = ggml_backend_dev_by_type(GGML_BACKEND_DEVICE_TYPE_CPU);
    auto * cpu_reg = ggml_backend_dev_backend_reg(cpu_dev);
```

cpu_dev is NULL and `ggml_backend_dev_backend_reg(cpu_dev)` give EXC_BAD_ACCESS 

### Operating systems

Mac

### GGML backends

Metal

### Hardware

Mac M1

### Problem description & steps to reproduce

Load this commit, build in MacOS and load any model.

### First Bad Commit

https://github.com/ggerganov/llama.cpp/pull/10469

### Relevant log output

```shell
"exception" : {"codes":"0x0000000000000001, 0x0000000000000078","rawCodes":[1,120],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000078"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":3547},
  "vmregioninfo" : "0x78 is not in any region.  Bytes before following region: 4308057992\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->
```

**Comment by slaren** [comment]
That's not enough information to reproduce the issue.

**Comment by Animaxx** [comment]
hmm let me create a demo project

**Comment by Animaxx** [comment]
the issue related to my project cache, thank you for replying @slaren. I am going to close this one
