### ISSUE TITLE
Parallel Quantize.sh, add &

### ISSUE THREAD

**Issue by tljstewart** [ggerganov/llama.cpp#106]
@prusnak 

`./quantize "$i" "${i/f16/q4_0}" 2 &`

**Comment by prusnak** [comment]
The fix need to be more elaborate, because if you pass `--remove-f16` then the `rm` command is called before `./quantize` has finished. 

Can you come up with a solution that does not have this issue?

**Comment by tljstewart** [comment]
This should work:

```
for i in `ls models/$1/ggml-model-f16.bin*`; do
    ./quantize "$i" "${i/f16/q4_0}" 2 &
    pids+=($!)
done

# Wait for all background processes to finish
for pid in "${pids[@]}"; do
    wait "$pid"
done

if [[ "$2" == "--remove-f16" ]]; then
    for i in `ls models/$1/ggml-model-f16.bin*`; do
        rm "$i"
    done
fi
```

**Comment by prusnak** [comment]
> This should work:

Yes, this works. But now I realised this completely defeats the purpose of the remove flag. The remove flag is there to save disk space after each conversion has been done. So this means the remove flag only makes sense when processing the files one after each other.

@ggerganov Do you think it makes sense to run the script in parallel by default and switch to serial processing when `--remove-f16` is provided or do we want to have a separate orthogonal flag for parallel/serial processing?

**Comment by tljstewart** [comment]
ah I see what you mean, *swapping disk resources*

**Comment by tljstewart** [comment]
This should cover it:

```
# Initialize array to store PIDs and file names
pids_and_files=()

# Loop over F16 model files and start quantization processes
for f16_file in models/"$1"/ggml-model-f16.bin*; do
    q4_file=${f16_file/f16/q4_0}
    ./quantize "$f16_file" "$q4_file" 2 &
    pid=$!
    pids_and_files+=("$pid:$f16_file")
done

# Loop over PIDs and file names to check if the processes are done
while [[ ${#pids_and_files[@]} -gt 0 ]]; do
    # Check if each process is still running
    for i in "${!pids_and_files[@]}"; do
        pid=${pids_and_files[i]%%:*}
        file=${pids_and_files[i]#*:}
        if ! ps -p "$pid" > /dev/null; then
            unset pids_and_files[i]  # Remove PID and file from array
            if [[ "$2" == "--remove-f16" ]]; then
                rm "$file"
            fi
        fi
    done
    sleep 1
done
```

**Comment by ggerganov** [comment]
I think it is better to multi-thread the `quantize.cpp` program.
Each tensor is divided in `n` parts and each of the `n` threads quantizes the corresponding part.
This way, even when quantizing the 7B model which has only 1 part, we will utilize all available CPU resources and still gain performance.

If you agree, either reformulate this issue and add "good first issue" tag or create a new one and close this.

**Comment by prusnak** [comment]
> I think it is better to multi-thread the `quantize.cpp` program.

I agree. This makes sense especially for this reason:

> This way, even when quantizing the 7B model which has only 1 part, we will utilize all available CPU resources 

>If you agree,  ...

ACK 

FWIW, I really respect your shell skills @tljstewart 👍

**Comment by tljstewart** [comment]
Trying to brief message on twitter @ggerganov @prusnak, please allow messages or follow me @tljstewart just so i can send message, Thanks

**Comment by prusnak** [comment]
Done another way (rewrite to python) in https://github.com/ggerganov/llama.cpp/pull/222
