### ISSUE TITLE
Add OpenCL clBLAS support

### ISSUE THREAD

**Issue by apcameron** [ggerganov/llama.cpp#1072]
Please consider adding OpenCL clBLAS Support similar to what as Done in [Pull Request 1044](https://github.com/ggerganov/llama.cpp/pull/1044)

Here is one such [Library ](https://github.com/clMathLibraries/clBLAS)

**Comment by Azeirah** [comment]
Duplicate of https://github.com/ggerganov/llama.cpp/issues/1059
