### ISSUE TITLE
Eval bug:  EXAONE-3.5-2.4B-Instruct has relatively low context limit (50% the limit of Qwen 2.5 3B)

### ISSUE THREAD

**Issue by 0xDEADFED5** [ggerganov/llama.cpp#10823]
### Name and Version

ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Intel(R) Arc(TM) A770 Graphics (Intel Corporation) | uma: 0 | fp16: 1 | warp size: 32 | matrix cores: none
version: 4326 (56eea078)
built with MSVC 19.42.34435.0 for x64

### Operating systems

Windows

### GGML backends

SYCL, Vulkan

### Hardware

Ryzen 7900X + Intel Arc A770

### Models

EXAONE-3.5-2.4B-Instruct

### Problem description & steps to reproduce

EXAONE-3.5-2.4B-Instruct for me has a context limit of 60k, whereas Qwen 2.5 3B has a context limit of 120K (important for using -np) quantized KV cache NOT used

confirmed on SYCL and Vulkan builds

I don't know enough about the topic to know if it's a bug or not, or maybe just due to how EXAONE works, so I decided to open an issue

### Relevant log output

```shell
n/a
```

**Comment by ggerganov** [comment]
Probably you run out of memory.

**Comment by 0xDEADFED5** [comment]
thanks for stopping by! my question is, is the memory limit less for EXAONE due to something intrinsic with the model, or some limitation with llama.cpp?

**Comment by arch-btw** [comment]
The model's page says this:

> Context Length: 32,768 tokens

https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct

**Comment by 0xDEADFED5** [comment]
i use -np, hence context is split by N

**Comment by ggerganov** [comment]
The EXAONE models likely require more memory for the KV cache compared to the Qwen models. It depends on the head size, number of heads and the GQA factor.

**Comment by 0xDEADFED5** [comment]
that's exactly what an LGAI team member said. thanks G!
