### ISSUE TITLE
Compile bug: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by mashdragon** [ggerganov/llama.cpp#10881]
### Git commit

4da69d1abd15263061aff94c10f205836a96a4bc

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I'm trying to compile llama.cpp on Ubuntu 22.04 with CUDA support. I have used python virtualenvs in the past and get this error message when I try to run `cmake -B build -DGGML_CUDA=ON` per the instructions:

```
$ cmake -B build -DGGML_CUDA=ON
-bash: /home/user/.local/bin/cmake: /home/user/myproject/venv/local/bin/python: bad interpreter: No such file or directory
```

I had no issues prior to the switch to the cmake build process. I know this is a "my configuration" issue, but it blocked me enough that I think others might also share the problem. I am not in a virtualenv when I am running the build commands.

I would expect the steps to reproduce are to use a virtualenv elsewhere which has a Python binary and then start the llama.cpp build process.

### Relevant log output

```shell
~/llama.cpp$ cmake -B build -DGGML_CUDA=ON
-bash: /home/user/.local/bin/cmake: /home/user/myproject/venv/local/bin/python: bad interpreter: No such file or directory
```

**Comment by JohannesGaessler** [comment]
I am not running into build issues (both for ggml and llama.cpp) after activating a venv on Manjaro (CPU+CUDA) or Ubuntu 24.04 (CPU).

**Comment by mashdragon** [comment]
Sorry to bother you, then. I looked into this some more and figured it out: Somehow one of my virtualenvs installed `cmake` to `~/.local/bin` and this overrides the regular cmake.

To fix the problem, I deleted `cmake` from `~/.local/bin` and logged in again. I can now build properly.
