### ISSUE TITLE
cuBLAS - windows - static not compiling

### ISSUE THREAD

**Issue by cmp-nct** [ggerganov/llama.cpp#1092]
When static linking is selected the CUDA::cublas_static target is not found.
Dynamic binary compilation works.

**Comment by slaren** [comment]
I don't know why that may be, these targets are listed [in the documentation](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#cuda-toolkit-cublas).

**Comment by cmp-nct** [comment]
hmm interesting, especially given that cublas_static seems to be the target for very old versions.
I have 11.7 installed

**Comment by Green-Sky** [comment]
cublas has no static targets on windows.

**Comment by slaren** [comment]
What does software that depend on it (or other libraries in the CUDA toolkit) do, distribute the dll files along with the software?

**Comment by Green-Sky** [comment]
https://github.com/ggerganov/llama.cpp/pull/1271
python ships the dynamic libraries. one of the reason each virtual env is so bloated.
