### ISSUE TITLE
Eval bug: qwen2-vl-2B on jetson agx orin ; try to allocate  655521.35 MB memory

### ISSUE THREAD

**Issue by chaoszzz123** [ggerganov/llama.cpp#10956]
### Name and Version

llama.cpp-master 

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

jetson agx orin 64 GB

### Models

qwen2-vl-2B

### Problem description & steps to reproduce

ggml_aligned_malloc: insufficient memory (attempted to allocate 655521.35 MB)
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 687363958272
ggml_gallocr_reserve_n: failed to allocate CPU buffer of size 687363958272
/home/lab123/llama.cpp-master/ggml/src/ggml-backend.cpp:262: GGML_ASSERT(buf != NULL && "tensor buffer not set") failed
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
Aborted (core dumped)

### Relevant log output

```shell
ggml_aligned_malloc: insufficient memory (attempted to allocate 655521.35 MB)
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 687363958272
ggml_gallocr_reserve_n: failed to allocate CPU buffer of size 687363958272
/home/lab123/llama.cpp-master/ggml/src/ggml-backend.cpp:262: GGML_ASSERT(buf != NULL && "tensor buffer not set") failed
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
Aborted (core dumped)
```

**Comment by HanClinto** [comment]
Looks like a simple case of trying to load a model that's too big for your system, and running out of memory.

If you want to try again, you might consider using a [quantized model](https://github.com/ggerganov/llama.cpp/tree/master/examples/quantize) that is more efficient for memory (looks like some pre-built quantized models of your chosen model [are already available on HF](https://huggingface.co/turingevo/Qwen2-VL-2B-Instruct-gguf/tree/main) -- start with Q4_0 and see if that works for you -- also [note the other instructions on that page](https://huggingface.co/turingevo/Qwen2-VL-2B-Instruct-gguf)), and possibly note other restrictions when attempting to load models larger than your available RAM (i.e., are you [unknowingly turning off mmap](https://github.com/ggerganov/llama.cpp/tree/master/examples/main#no-memory-mapping)?).

**Comment by HanClinto** [comment]
Closing for now -- please re-open if your issue persists.
