### ISSUE TITLE
Misc. bug: Revert disable of rocm p2p copy

### ISSUE THREAD

**Issue by IMbackK** [ggerganov/llama.cpp#10996]
### Name and Version

cfbf76b1e89302fa983f5938cde219706831a42a

### Problem description & steps to reproduce

cfbf76b1e89302fa983f5938cde219706831a42a works around a bug that is not really a bug at all. The reason the p2p copies fail on rocm is that the mainline kernel is not supported for this operation. Unfortionatly the rocm runtime dosent properly convey that the operation has failed.

when pcie p2p is available the rocm runtime uses the kfd interface for p2p, this interface is a private extension to amdgpu that was rejected upstream. This means that rocm only works correctly on downstream amdgpu (rock). Amd is working on replaceing it with dmabuf, but for now rocm still relies on it. Unfortunately rocm is often deployed by users without rock sutch as from distro packages on arch linux or on gentoo, causing this issue.

**Comment by slaren** [comment]
I am not sure that I understand what you are requesting here. This is a compile-time option that is disabled by default. What would be the purpose of removing it?

**Comment by IMbackK** [comment]
its not nesscary so i could go as a refactoring mesure, but i gues your right.
