### ISSUE TITLE
Error when using Zig : "no field or member function named 'standardReleaseOptions' in 'Build'"

### ISSUE THREAD

**Issue by TheGreat-Chain** [ggerganov/llama.cpp#1112]
When I perform the third step of the readme, which is entering the `"zig build -Drelease-fast"` command, I get this error : 
```
llama.cpp/build.zig:5:23: error: no field or member function named 'standardReleaseOptions' in 'Build'
    const optimize = b.standardReleaseOptions();
                     ~^~~~~~~~~~~~~~~~~~~~~~~
/zig/lib/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    runBuild__anon_7424: /zig/lib/std/Build.zig:1545:27
    steps__anon_6622: /zig/lib/build_runner.zig:891:20
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

OS : LinuxMint 21
Zig version : 0.11.0-dev.2689+b7c00999b

**Comment by SlyEcho** [comment]
The `build.zig` is written for zig 0.10, the API has changed in 0.11 so it will need to be fixed.

**Comment by jdc4429** [comment]
I get the same error...

**Comment by tristanisham** [comment]
This files has broader issues than simple one depreciated function. Though, to fix this particular micro-issue line five should be:
```zig
const optimize = b.standardOptimizeOption(.{});
```

**Comment by SlyEcho** [comment]
I think it's probably better to track with the dev releases of zig rather than the "stable" ones. It could also probably support most of the advanced features that the Make and CMake configurations do.
