### ISSUE TITLE
Latest release wont compile (ggml.c)

### ISSUE THREAD

**Issue by klosax** [ggerganov/llama.cpp#1120]
Release: master-36b4f7e

ggml.c: In function ‘bytes_from_nibbles_16’:
ggml.c:439:19: warning: implicit declaration of function ‘_mm_loadu_si64’; did you mean ‘_mm_loadl_epi64’? [-Wimplicit-function-declaration]

     __m128i tmp = _mm_loadu_si64( ( const __m128i* )rsi );
                   ^~~~~~~~~~~~~~
                   _mm_loadl_epi64
ggml.c:439:19: error: incompatible types when initializing type ‘__m128i’ {aka ‘__vector(2) long long int’} using type ‘int’

Using:
cc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0

**Comment by klosax** [comment]
That worked. Thank you.

**Comment by prusnak** [comment]
ggml issue: https://github.com/ggerganov/ggml/issues/99

**Comment by cabelo** [comment]
@klosax , This PR https://github.com/ggerganov/llama.cpp/pull/5606 works well
