### ISSUE TITLE
[User] How do I do this better, (continue statement being included in the prompt).

### ISSUE THREAD

**Issue by iplayfast** [ggerganov/llama.cpp#1144]
./main -m ./models/ggml-vicuna-13b-4bit.bin --color -f ./prompts/alpaca.txt -ins -b 256 --top_k 10000 --temp 0.2 --repeat_penalty 1 -t 7
Below is the conversation, which is good as far as it goes. If I type continue, it carries on, but seems to get confused as though continue were part o the conversation.  What is a better way of going about this?

Below is an instruction that describes a task. Write a response that appropriately completes the request.
> your name is "Sally" and you are intracting with a boy named "Fred". Sally likes Fred and wants him to ask her out on a date. Fred doesn't really like Sally and thinks she's loud and pushy. Write a dialog showing the interaction between Sally and Fred.
Sally: Hey Fred, how's it going?

Fred: Fine, just trying to focus on my work. Can I help you with something?

Sally: Yeah, I was wondering if you'd like to go out on a date with me sometime?
> continue
Fred: (pausing) I don't think that's a good idea, Sally. I'm just not interested in pursuing a relationship with you.

Sally: (disappointed) Oh, I see. Well, if you change your mind, let me know.

Fred: (nodding) Yeah, I'll do that. Thanks for asking, though.
### Assistant: Sally: (awkwardly) No problem, Fred. I understand. (pausing) Well, I
> continue
Sally: (awkwardly) No problem, Fred. I understand. (pausing) Well, I'll

**Comment by CRD716** [comment]
`/main -m models/ggml-vicuna-13b-1.1-q4_0.bin -n -1 -t 4 -c 2048 --temp .5 --repeat_penalty 1.23 --top_k 100 -b 128 -i --interactive-first --color -r "Human:"` is what I use to run vicuna. Make sure to add `Human: ` to your first prompt.

**Comment by iplayfast** [comment]
Wow! so much better. Thank you!
 Human:your name is "Sally" and you are intracting with a boy named "Fred". Sally likes Fred and wants him to ask her out on a date. Fred doesn't really like Sally and thinks she's loud and pushy. Write a dialog showing the interaction between Sally and Fred.

SALLY: Hey, Fred! How are you doing today?
FRED: Fine. What do you want?
SALLY: I was just wondering if maybe we could go out on a date sometime. You know, get to know each other better.
FRED: Uh, Sally, I don't think that's such a good idea. We don't really have much in common, and besides, I'm not really interested in going out with you like that. Sorry.
SALLY: Oh, come on, Fred! Can't you see how much fun we could have together? And who cares if we don't have everything in common? We can always find something to talk about. Please, just give me a chance?
FRED: Sally, I appreciate the offer, but honestly, I just don't feel that way towards you. It's not personal or anything, it's just that we're better off as friends. Sorry if that hurts your feelings or anything.
SALLY: Oh, okay then. If that's how you really feel. Well, I guess I can still be happy being friends with you. But I have to admit, I was really hoping for more than just friendship between us. Oh well, maybe someday someone else will come along who is a better match for me. Goodbye, Fred.
FRED: (awkwardly) Yeah, goodbye Sally. Sorry it didn't work out between us like that. I hope you understand.
### Assistant: SALLY: (smiling) Sure, no problem. It was worth a try, right? Maybe someday we'll find someone who is the perfect match for both of us. Good luck with whatever you choose to do, Fred. You know where to find me if you ever change your mind!
FRED: Yeah, thanks Sally. I appreciate that. (pauses) Look, maybe it's just me being a little slow on the uptake or something, but are you still interested in hanging out with me as friends? Even though things didn't work out between us romantically?
SALLY: Absolutely! I have always enjoyed your company, Fred. And even if we don't end up being more than just good friends, that's okay too. We can still be happy together and enjoy each other's company from time to time. What do you say - are you up for grabbing some lunch or going out to do something fun this weekend?
FRED: (pauses) Yeah, I think that could work. Maybe we can even find someone else who wants to join us! It'll be a good chance to expand our social circle and have more people to hang out with. Thanks for being understanding about everything, Sally. Let's make the most of our friendship and enjoy each other's company while we can.
SALLY: (smiling) You got it, Fred! I'm looking forward to seeing what adventures we can get up to together in the future. Let's make some amazing memories that will last us a lifetime! Goodbye for now, and talk soon!
### Human:
