### ISSUE TITLE
error loading model: unrecognized tensor type 5

### ISSUE THREAD

**Issue by justarmadillo** [ggerganov/llama.cpp#1147]
How can I solve this issue ?

llama.cpp: loading model from models\ggml-vicuna-13b-1-1\ggml-vicuna-13b-1.1-q4_3.bin
error loading model: unrecognized tensor type 5

llama_init_from_file: failed to load model
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

**Comment by justarmadillo** [comment]
downloaded q4_1.bin because q4_3 and  q4_2 are WIP. and aren't compatible

**Comment by Th3WalkingDad** [comment]
@justarmadillo I've downloaded 'uncensored' model  **ggml-vic13b-uncensored-q5_1.bin** added recently from https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main  . I got similar error (but for type 7):
`llama.cpp: loading model from /usr/src/app/weights/ggml-vic13b-uncensored-q5_1.bin
error loading model: **unrecognized tensor type 7**`

Shouldn't it be used ... or ? Any way to know which model is compatible with llama.cpp ? thx

**Comment by Green-Sky** [comment]
they are just new, so you need the lastest llama.cpp.
