### ISSUE TITLE
Error build on centos 7 

### ISSUE THREAD

**Issue by Chting** [ggerganov/llama.cpp#116]
![image](https://user-images.githubusercontent.com/17468133/224892691-9a1f7fac-5a4c-46a1-8ab2-c47aee610a42.png)
![image](https://user-images.githubusercontent.com/17468133/224892885-ea80b64e-5630-4a0a-8aba-8997b8326726.png)
![image](https://user-images.githubusercontent.com/17468133/224893003-7f8aaa36-d3c2-4703-856f-97db1001edef.png)
Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Where is the problem? What should I do?

**Comment by zhoujian1028** [comment]
error fix
ggml.h add #define _POSIX_C_SOURCE 199309L
![image](https://user-images.githubusercontent.com/6960679/224895052-6094294b-0d80-4462-964a-941f1f717c9b.png)

**Comment by Chting** [comment]
> error fix ggml.h add #define _POSIX_C_SOURCE 199309L ![image](https://user-images.githubusercontent.com/6960679/224895052-6094294b-0d80-4462-964a-941f1f717c9b.png)

Thank you very much
