### ISSUE TITLE
Convert h5 format to ggml

### ISSUE THREAD

**Issue by chenguokai** [ggerganov/llama.cpp#117]
There has been a llama model file hosted on [Hugging Face](https://huggingface.co/decapoda-research/llama-30b-hf/tree/main)

It would be good if there is a convert script for this format as well, just like what has been done on [whisper.cpp](https://github.com/ggerganov/whisper.cpp/blob/09e90680072d8ecdf02eaf21c393218385d2c616/models/convert-pt-to-ggml.py)

**Comment by hpnyaggerman** [comment]
Just download the original models here: https://github.com/facebookresearch/llama/pull/73
