### ISSUE TITLE
Can't convert LoRA to ggml on windows, files in correct structure No such file or directory: 'lora/llama-oasst-lora-13B\\adapter_model.bin'

### ISSUE THREAD

**Issue by captainzero93** [ggerganov/llama.cpp#1175]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

LoRA Model converts

# Current Behavior

 python convert-lora-to-ggml.py lora/llama-oasst-lora-13B
Traceback (most recent call last):
  File "C:\Users\pwnzr\Desktop\LLM\lora\convert-lora-to-ggml.py", line 83, in <module>
    model = torch.load(input_model, map_location="cpu")
  File "C:\Users\pwnzr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", l
![folder structure](https://user-images.githubusercontent.com/125401979/234351775-34b75aac-e972-4d57-99b7-3f962d482a0b.png)
ine 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\pwnzr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\pwnzr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'lora/llama-oasst-lora-13B\\adapter_model.bin'

# Environment and Context

Windows 11, trying to convert https://huggingface.co/serpdotai/llama-oasst-lora-13B/ to be used as a LORA with ggml-vicuna-13b-1.1-q4_0 

The files are in the correct structure but I don't know why it is trying to look with a double backslash?  No such file or directory: 'lora/llama-oasst-lora-13B\\adapter_model.bin'

**Comment by SlyEcho** [comment]
It looks like the path is wrong from your screenshots. If you are running the script from that folder, you need to type
```
python convert-lora-to-ggml.py llama-oasst-lora-13B
```

You can also SHIFT-right click on the folder and "Copy As Path" then paste that on the command line.
