### ISSUE TITLE
[Feature request?]: Running larger models without quantization.

### ISSUE THREAD

**Issue by acheong08** [ggerganov/llama.cpp#118]
Current error
```bash
[1]    11624 segmentation fault (core dumped)  ./llama -m ./models/13B/ggml-model-f16.bin -p  -t 8 --temp 0.5 --top_p 1 
```

**Comment by acheong08** [comment]
Everything works when quantized.

**Comment by gjmulder** [comment]
> Current error
> 
> ```shell
> [1]    11624 segmentation fault (core dumped)  ./llama -m ./models/13B/ggml-model-f16.bin -p  -t 8 --temp 0.5 --top_p 1 
> ```

Check whether you have enough memory:

Size| Precision| Approx. RAM req.
-|-|-
13B  | fp16 | 25GB
30B  | fp16 | 62GB
65B  | fp16 | 122GB


You can add swap on Linux, but even using NVME it will be very slow due to the random access patterns of the code.

**Comment by acheong08** [comment]
Even my primary memory + swap is not enough.

**Comment by gjmulder** [comment]
As per the comments from @MarkSchmidty in issue #53 use the 4bit quantized models to reduce your memory requirements by approx. 4X. The loss in quality should be negligible.

**Comment by acheong08** [comment]
Yes. The quantized models work perfectly for me. I just wanted to test out the other versions to check out how they perform

**Comment by gjmulder** [comment]
Slowly :smile:

If there's a specific model size and prompt you need I can compare the 4bit to the f16. I'm currently exploring different option permutations in issue #69
