### ISSUE TITLE
It should be possible to set the RNG seed after restoring state.

### ISSUE THREAD

**Issue by asgeir** [ggerganov/llama.cpp#1182]
The new llama_copy_state_data, llama_set_state_data API preserves the RNG seed without providing an option of changing the seed.

It would be useful to have some llama_set_rng_seed function to have an option of setting the seed after restoring the state.
[rng_seed.patch](https://github.com/ggerganov/llama.cpp/files/11326802/rng_seed.patch)

**Comment by xaedes** [comment]
Personally I think that makes sense. 
When you have a working version you could make a pull request.

**Comment by asgeir** [comment]
I've created a pull request. #1184
