### ISSUE TITLE
perf(CuBLAS): explore reduction in launch overhead via CUDA graphs

### ISSUE THREAD

**Issue by jon-chuang** [ggerganov/llama.cpp#1192]
See  https://developer.nvidia.com/blog/cuda-graphs/ for reference.

One can take one of two approaches:
1. Within operator.
2. Spanning multiple operators (operator fusion)

**Comment by jon-chuang** [comment]
Any thoughts @slaren ?

**Comment by jon-chuang** [comment]
Looking at https://github.com/ggerganov/llama.cpp/issues/1129#issuecomment-1523261299

It seems that inter-operator fusion is required.

This means we need a concept of a device tensor. Looks like we are slowly reimplementing PyTorch...

**Comment by dfyz** [comment]
Using CUDA graphs would make sense if the duration of our kernels were comparable with the launch overhead (a couple of microseconds). As far as I understand, we intentionally use GPU only for large GEMMs that take at least a couple of milliseconds.
