### ISSUE TITLE
Incorrect command for model quantization in README.md

### ISSUE THREAD

**Issue by javadyaali** [ggerganov/llama.cpp#1199]
The correct command for quantizing the model is not reflected accurately in lines 206 and 207 of README.md (Prepare Data & Run). To perform model quantization, you should use the following command instead.

```
# quantize the model to 4-bits (using method 2 = q4_0)
./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin 2
```

**Comment by slaren** [comment]
If this isn't working for you, you need to update to current master, check #1191 that was merged today.

**Comment by javadyaali** [comment]
Thanks @slaren for mentioning that!
