### ISSUE TITLE
Getting an error while running "convert.py": "zipfile.BadZipFile: Bad magic number for file header"

### ISSUE THREAD

**Issue by fbyukgo** [ggerganov/llama.cpp#1208]
I am trying to use "python convert.py models/7B/" command to convert my model to ggml FP16 format.
Models and 7B folders contain the following files;

models/
├── 7B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── tokenizer.model
└── tokenizer_checklist.chk

When I run the command I get the "zipfile.BadZipFile: Bad magic number for file header" error. I've tried to tinker with the "convert.py" file but I couldn't manage to solve the problem.  Does anyone know what might cause the issue and how can I fix it? 

I am using Python version 3.9 with the requirements( found in requirements.txt in llama.cpp file) installed.

**Comment by prusnak** [comment]
Run `sha256sum --ignore-missing -c SHA256SUMS` to check whether you have downloaded the files correctly.

Please reopen if this says the files are correctly downloaded

**Comment by fbyukgo** [comment]
It turned out there was a problem with the files I've downloaded so re-downloading them fixed the problem, thanks!
