### ISSUE TITLE
llama_model_load: llama_model_load: unknown tensor '' in model file

### ISSUE THREAD

**Issue by james70s** [ggerganov/llama.cpp#121]
$ ./main -m ./models/30B/ggml-model-q4_0.bin -t 8 -n 128 -p 'The first president of the USA was'
main: seed = 1678775977
llama_model_load: loading model from './models/30B/ggml-model-q4_0.bin' - please wait ...
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 6656
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 52
llama_model_load: n_layer = 60
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 17920
llama_model_load: n_parts = 4
llama_model_load: ggml ctx size = 20951.50 MB
llama_model_load: memory_size =  1560.00 MB, n_mem = 30720
llama_model_load: loading model part 1/4 from './models/30B/ggml-model-q4_0.bin'
llama_model_load: ................................................................... done
llama_model_load: model size =  4850.14 MB / num tensors = 543
llama_model_load: loading model part 2/4 from './models/30B/ggml-model-q4_0.bin.1'
llama_model_load: llama_model_load: unknown tensor '' in model file
main: failed to load model from './models/30B/ggml-model-q4_0.bin'

**Comment by sliterok** [comment]
Sorry, can you please elaborate? I'm also getting the error but I'm not getting what's "not planned"? Why there's memory usage stats for 30B model if this is marked as wontfix/not planned?

**Comment by sliterok** [comment]
Ah, I see. Everyone else, please refer to this comment :) https://github.com/ggerganov/llama.cpp/issues/38#issuecomment-1465104765
(I came here because I'm on windows machine https://github.com/ggerganov/llama.cpp/issues/103#issuecomment-1466990359)
