### ISSUE TITLE
Fine-Tune GPT4ALL "gpt4all-lora-quantized.bin" missing config.json file

### ISSUE THREAD

**Issue by Muhamad-Nady** [ggerganov/llama.cpp#1246]
I want to fine-tune gpt4all-lora-quantized.bin which supported by the llama.cpp but i can't not find the tokenizer config.json file in the repo LLukas22/gpt4all-lora-quantized-ggjt, I just found .bin model file. could any one help with that.
or told me how to fine-tune gpt4all model which  i could run with llama.cpp

**Comment by Green-Sky** [comment]
right now, llama.cpp does not support finetuning.
the issue kind of tracking finetuning for llama.cpp/ggml : https://github.com/ggerganov/ggml/issues/8
it can also be found on the lowp section of https://github.com/ggerganov/llama.cpp/discussions/1220
