### ISSUE TITLE
Gpu support

### ISSUE THREAD

**Issue by moh21amed** [ggerganov/llama.cpp#1267]
I have low end laptop with i5-8250u and Nvidia mx 150 with 4 gb vram (equivalent to gt1030)  and 8gb ram 
I used whisper.cpp to transcribe a 43 minutes video and it takes about 30 minutes, then I tried [Const-me/Whisper](https://github.com/Const-me/Whisper) which supports GPU inference of whisper.cpp and it only takes 3 minutes (that is 10x faster)
Can we use the same method for llama? cpp especially with the similarity of whisper.cpp and llama.cpp? I am not good at these things but can someone look at the repo and start the discussion of how easy will it be to implement the same method?

**Comment by j-f1** [comment]
We’re discussing this in #915.
