### ISSUE TITLE
Unbuildable Source

### ISSUE THREAD

**Issue by JackJollimore** [ggerganov/llama.cpp#1287]
Hello,

my device is samsung s10+ and I can no longer compile your source files.

I expect that downloading the source files and typing make to compile is suffecient.

make LLAMA_OPENBLAS=1
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  aarch64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_OPENBLAS -I/usr/local/include/openblas -mcpu=native
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -mcpu=native
I LDFLAGS:  -lopenblas
I CC:       clang version 16.0.2
I CXX:      clang version 16.0.2

/data/data/com.termux/files/usr/bin/sh: 1: scripts/build-info.sh: Permission denied
make: *** [Makefile:216: build-info.h] Error 126

The error message makes no sense to me.

**Comment by slaren** [comment]
Maybe you copied it in such a way that build-info.sh lost the execute permission. Try `chmod +x scripts/build-info.sh`.

**Comment by JackJollimore** [comment]
> 

I didn't know that was possible. Your solution allows me to compile.

Thank you very much.

**Comment by slaren** [comment]
Maybe this could be prevented by running the script explicitly with sh in the Makefile ie. `sh scripts/build-info.sh`. 
cc @DannyDaemonic

**Comment by prusnak** [comment]
> Maybe this could be prevented by running the script explicitly with sh in the Makefile ie. `sh scripts/build-info.sh`. 

This sounds like a good way how to fix this.

**Comment by DannyDaemonic** [comment]
@slaren Yeah, that's a good idea. I can put in a PR/

**Comment by DannyDaemonic** [comment]
Fixed in #1294

**Comment by JackJollimore** [comment]
Thanks fellas. I downloaded the newest source, and it compiled withour a problem. I appreciate!
