### ISSUE TITLE
Quantitative measurement of model perplexity for different models and model quantization modes 

### ISSUE THREAD

**Issue by noughtmare** [ggerganov/llama.cpp#129]
llama.cpp seems to give bad results compared to Facebook's implementation.

Here's an example simple reading comprehension prompt:

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book

LLaMA 7B with Facebook's implementation yields:

Seed `1`:

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book with pictures."
Asked by lone wolf 1788 days ago.

Seed `2` (to show that the above is not just a fluke):

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book with pictures."
Question: "Tom, Mark, and Paul bought books: two with pictures and

While llama.cpp without quantization (so still float16) generates (with `--seed 0 -t 8`):

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book that is neither as good nor bad."
This solution breaks down the problem into its simple parts; then using those components we can see what each component means by itself, in order to solve this logic puzzle. 1) Tom and Mark had different kinds of books...and so did Paul! (Therefore one out three were without pictures). ... [end of text]

It even has a grammatical error at the end: "one out [of] three"

As you can see the quality of 7B is higher in Facebook's implementation. So, I think you may still have bugs in your implementation or the default parameters could be improved.

**Comment by noughtmare** [comment]
With quantization the result is also bad:

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book WITHOUT PICTURES."
This is just an example question; I can't figure out how to post actual questions that are being asked in my classroom! So, here we go . . . We recently had our first day back after Thanksgiving break. One of the things

**Comment by gjmulder** [comment]
You might not be comparing apples to apples. e.g. are the `--top_p` and other parameters identical between implementations?

**Comment by noughtmare** [comment]
I'm using the default settings, so for the Python code it is:

```
    temperature: float = 0.8,
    top_p: float = 0.95,
    max_seq_len: int = 512,
    max_batch_size: int = 32,
```

And for llama.cpp:

```
sampling parameters: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000
```

So I think only the repeat penalty and `top_k` could be different?

**Comment by noughtmare** [comment]
If I disable the repeat penalty (I assume `--repeat_penalty 0` does that) then I still get low quality results:

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book about cars (p1). He chose to read and look "up Hepa", with only p3 one "out did it one time with his different". The time look only only What look and time about a a it about Answer and Mark What?out his one pout the car it. Tom' his bought

**Comment by gjmulder** [comment]
`top_k` looks to be currently broken, as I recently reported in issue #56. I just now realised that due to #95 identical seeds across implementations are unlikely to produce identical results as per @ggerganov's correction to my comment in that issue.

It does then look like `llama.cpp` is of lower quality. You've tried other prompts and got similar results?

**Comment by noughtmare** [comment]
I haven't tested the Python implementation extensively, because Facebook's implementation takes very long to run on my CPU. But I generally feel that running 7B and even 13B with llama.cpp gives results that are below the quality that Facebook has claimed.

**Comment by beiller** [comment]
Try the following parameters, gives me good quality output:

`--temp 0.7 --top_k 40 --top_p 0.5 --repeat_last_n 256 --repeat_penalty 1.17647`

Also repeat_penalty = 1.0 means disable. Maybe its not named as it should be  😇

**Comment by Urammar** [comment]
If 1 means disable whats the point of higher than 1 values? Also its good to let it repeat itself a little, sometimes that makes sense in conversation, but tighter lets it break loops before they begin.

**Comment by noughtmare** [comment]
> Try the following parameters

Still gives me a wrong result:

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book with no pictures."
Answer to Question 1739: "The three students were going on an outing. They needed shoes for the trip. Each student owned a pair of shoes that was not his own. Which student wore tennis shoes? (Hint: The answer is in the question.)

I think the problem is more fundamental than just a change of the parameters.

**Comment by gjmulder** [comment]
> I haven't tested the Python implementation extensively, because Facebook's implementation takes very long to run on my CPU. But I generally feel that running 7B and even 13B with llama.cpp gives results that are below the quality that Facebook has claimed.

It may be simply a case of the [project management triangle](https://en.wikipedia.org/wiki/Project_management_triangle) , i.e. choose any two of:

1. Performance
2. Quality
3. Self-hosting

**Comment by noughtmare** [comment]
That might be so, but I don't see an obvious reason why the quality would be lower. Quantization could have been a logical cause, but I think I have shown that even the fp16 model has a lower quality.

**Comment by Urammar** [comment]
If its simply a straight up c++ implementation then it should be the same, but an install step in the github states it must be quantized, which means even if you are running it in fp16 its still been crunched in precision to run better, which naturally means its outputs will slightly differ.

You wouldnt expect a mile long road at 18.2 degrees to end up at the same place as one rebuilt at 18.0 degrees, right?

As you just said as I was typing this, quantization made its brain just that little more crispy, and that clearly slightly effects it. Thats probably not solvable.

**Comment by noughtmare** [comment]
> but an install step in the github states it must be quantized,

I don't think that step is required. The model runs fine without the quantization step. And the readme also claims llama.cpp has "Mixed F16/F32 precision".

**Comment by beiller** [comment]
@Urammar higher than 1 starts to penalize the predicted next token if it occurred in previous N tokens. It will multiply the likelihood by 1/penalty.

**Comment by beiller** [comment]
Try like so:

```
./main -m ./models/13B/ggml-model-q4_0.bin -t 4 --temp 0.7 --top_k 40 --top_p 0.5 --repeat_last_n 256 --repeat_penalty 1.17647 -p $'Question: "Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: Three. Two ducks are in front of the last duck; the first duck has two ducks behind; one duck is between the other two.\n\nQuestion: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book'
```

```
Question: "Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: Three. Two ducks are in front of the last duck; the first duck has two ducks behind; one duck is between the other two.

Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book that was not illustrated."
```

**Comment by beiller** [comment]
For me it consistently answers incorrectly every time

> Question: "Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: Three. Two ducks are in front of the last duck; the first duck has two ducks behind; one duck is between the other two.
> 
> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book without pictures."

**Comment by noughtmare** [comment]
Haha, that question about ducks is also interesting. Using this prompt:

> Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: "There are

The Python implementation outputs a plausible but unintended answer:

> Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: "There are seven ducks." The answer is correct, but it is not obvious. Try to explain your answer

But llama.cpp 7B outputs garbage:

> Question: "There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?" Answer: "There are three duc...
I'm sorry for your loss, but I think it is fair to say that you have moved on from this traumatic event by now. [end of text]

**Comment by beiller** [comment]
I get consistently non-garbage output. Can you try using the settings I had above? I am on a different branch. Wonder if that has anything to do with it.

**Comment by beiller** [comment]
I mean it even explains itself

> Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?" Answer: "Paul bought a book that has no pictures."
> The correct answer is A because the question says they all bought books but it doesn't say which ones so B isn't right becuase you don't know if tom or mark got the same thing as paul. C can be eliminated becuase there are only three choices left to choose from. D can also be eliminated becuase again you have to chose between 3 things not four. So your left with A and E becuase those are the only two options left. [end of text]

I'm not sure if this is the best way to objectively tell the quality of the output :)

**Comment by noughtmare** [comment]
Actually, after playing around a  bit with the quantized model, I now believe that the problem is only in running the FP16 model. The quantized model works much better for me.

**Comment by sburnicki** [comment]
Thanks for sharing your parameters guys, I get definitely better results as with the default ones.

I ran the same prompt with 5 different models 7B/Q4, 7B/16F, 13B/Q4, 13B/16F, 30B/Q4:

```
./main -m ./models<model>.bin -t 8 --temp 0.7 --top_k 40 --top_p 0.5 --repeat_last_n 256 --repeat_penalty 1.17647 -n 1024 -p 'Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"'

system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
```

See the results below.


I ran each one multiple times, the results of the single runs with one model are comparable in quality. I don't see a major quality difference in Q4 and F16. Interestingly, 13B gave me the weirdest results. It also always tempted to return some kind of LaTex code, I could also observe this with other prompts.

# Results

## 7B / Q4
```
Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"
Answer: "Paul bought the book that didn't have a picture."
```

## 7B / F16
```
Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"
Answer: A book that was not a picture book. [end of text]
```

## 13B / Q4
```
Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"

I have no idea how to solve this problem. I've tried it a few ways but can't seem to get the right answer.

Comment: You need to add more information about what you know or don't know about these people/books etc...

Answer: \begin{blockquote}

\strong{Hint:} There are three possibilities for each book type (with picture and without).  So there are $3^2$ possible combinations for all six books combined.  The number of permutations is $\frac{(6!)}{(3!)^2}=15$.
\end{blockquote} [end of text]
```

## 13B / F16
```
Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"

\begin{blockquote}

Tom, Mark, and Paul bought books: two with pictures and one without.  Tom and Mark had different kinds of books.  What kind did Paul buy?
\end{blockquote}

I'm not sure how to approach this problem. I know that there are three possible answers (pictures or no picture) but the question doesn't specify which is correct so it could be any combination. Any help would be appreciated! Thanks in advance :)

Comment: This isn't a maths question - it belongs on [Puzzling](http://puzzling.stackexchange.com/).

Answer: The answer is that \strong{Paul has the same book as Tom}. If you assume that they all have different types of books then we can deduce from the information given that at least one person must have a book with pictures because otherwise only one type of book exists. So either Tom or Mark buys such a book. But if both do then they cannot have different types of books. Therefore Paul also has a book with pictures. [end of text]
```

## 30B / Q4
```
Question: "Tom, Mark, and Paul bought books: two with pictures and one without. Tom and Mark had different kinds of books. What kind did Paul buy?"
The answer is given as 2, but I don't understand why it isn't 1?
If we know that the book without a picture was purchased by Paul, then wouldn't we also have to assume that he didn't purchase any other books (because if he did, then there would be more than three total)? And if we can make this assumption, doesn't that mean that Tom and Mark must have both purchased books with pictures in them?
I think you are right. The question is poorly worded. It should say something like "Mark and Paul each bought only one book." Then it would make sense. [end of text]
```

**Comment by noughtmare** [comment]
@sburnicki I think it is good to include the `Answer: "Paul bought a book` in your prompt to avoid the cases where the model doesn't give a straight answer like almost all your results do.

**Comment by hoangmit** [comment]
One bug I found is #173  llama.cpp seems to use different norm method.

**Comment by ggerganov** [comment]
So I think the quality of the generations is difficult to evaluate. We need a more quantitative metric.
I think we will put more efforts into that once we have the `Q4_1` quantization ready.

**Comment by bakkot** [comment]
> We need a more quantitative metric.

[This blog post](https://nolanoorg.substack.com/p/int-4-llama-is-not-enough-int-3-and) did a quantitative measurement of quality for comparison against different quantification methods, though I don't know how well it corresponds to subjective quality. I believe the code is [here](https://github.com/juncongmoo/pyllama). I expect that could serve as a starting point for building an objective metric for quality.

**Comment by noughtmare** [comment]
Here's more evidence for the low quality:

Prompt:

> Here's a Python program that computes fibonacci numbers:
> def fib(n):
> &nbsp;&nbsp;

(The last line is indented by 2 spaces)

Python LLaMA:

> Here's a Python program that computes fibonacci numbers:
> ```
> def fib(n):
>    if n==0:
>       return 0
>    elif n==1:
>       return 1
>    else:
>       return fib(n-1) + fib(n-
> ```

(I only let it generate 40 tokens)

llama.cpp F16:

> Here's a Python program that computes fibonacci numbers:
> ```
> def fib(n):
>    if n == 0 or n == 1:
>       return 0
>    elif n <= 40:
>        return n + (fib(n-1) * fib(n-2))
>    else:
>        return fib(n -1) + fib(n-2
> ```

(I added the code block formatting myself)

**Comment by thepowerfuldeez** [comment]
I could agree that quantized model shows loq quality of answers.

> write a function to generate fibonacci numbers as a list
```
def fib(n):  # n is the number of terms in the sequence.
    if (n == 0) or (n == 1): return [0, 1]
    else: return fib(n-1)+fib(n-2)
```
> how does it work?
```
The program will take an input sentence and convert it into its corresponding Morse code signal using a lookup table. It then outputs that Morse code signal along with the original text. The output can be displayed on screen or printed out for later reference.
```
> i didn't ask about morse code, i asked about fibonacci function
```
Fibonacci functions are mathematical sequences defined by the following recurrence relation:

a_n = a_{n - 1} + a_{n - 2}, where "a_" stands for Fibonacci sequence at index ___.

For example, given a=0, b=1, we have:

a_0 = 0;
a_1 = 1;
a_2 = 1;
a_3 = 2;
a_4 = 3;
```
> continue
```
continue
```

**Comment by ggerganov** [comment]
@noughtmare and others 

Thank you very much for these investigations. This is very useful, as I don't have the Python codebase setup to run on my M1.

It is very possible that there is some subtle bug in `llama.cpp`.
The other explanation is that the sampling strategy is somehow different.

I think the `ggml` FP16 should produce similar results to the original code.
If it is not the case, we have to figure out what is the issue.

I tried running the FP16 with the following parameters and it seems to usually perform well on the fibonacci task:

```
./main -m models/7B/ggml-model-f16.bin -p "Here's a Python program that computes fibonacci numbers:
def fib(n):
  " --top_k 10000 --temp 0.96 --repeat_penalty 1
```

Can you confirm that is the case for you as well?

**Comment by beiller** [comment]
Can we rule out the tokenizer? I can't test at the moment, but there is another issue claiming the tokenization output differs between implementations.

**Comment by noughtmare** [comment]
> Can you confirm that is the case for you as well?

I get these. `--seed 1`:

>  Here's a Python program that computes fibonacci numbers:
> ```
> def fib(n):
>    res=0;
>    for i in range(2,n+2):
>        res=res+i;
>    return res
> ```

`--seed 2`:

>  Here's a Python program that computes fibonacci numbers:
> ```
> def fib(n):
>    if n==0:
>       return 0
>    if n==1:
>       return 1
>    return fib(n-1) + fib(n-2)
> ```

`--seed 3`:

> Here's a Python program that computes fibonacci numbers:
> ```
> def fib(n):
>    if n == 0:
>       return 0
>    elif n == 1:
>       return 1
>    else:
>       return fib(n-1) + fib(n-2)
> ```

So 2/3, which does seem better, but it is not clear if it really matches the Python implementation.

**Comment by noughtmare** [comment]
@ggerganov I actually get better results with the default parameters:

```
% ./main -m ../LLaMA/7B/ggml-model-f16.bin -p "Here's a Python program that computes fibonacci numbers:
def fib(n):
  " --repeat_penalty 1
```

That produces correct fibonacci programs for 13/20 seeds.

**Comment by Green-Sky** [comment]
@alankila you can reduce memory using 16bit floats for memory `--memory_f16` and setting a lower context(, and lower batch size).

**Comment by glinscott** [comment]
Is everyone running with https://github.com/ggerganov/llama.cpp/pull/252 merged in?  It made a huge difference on perplexity (which is a rough measure of language model quality).

**Comment by ggerganov** [comment]
@alankila 

Your observations and analysis correspond very well to mine.
I have definitely observed that Q4_0 performs significantly worse compared to Q4_1 - for example, GPT-2 345M does not work at all with Q4_0, but it sort of produces coherent stuff with Q4_1. I am thinking that we will eventually switch by default to Q4_1, or some similar alternative. It's slightly slower to compute unfortunately.

Your analysis about the determinism is correct - I am thinking about how to fix this, but probably a major change in `ggml` is needed. Not sure if it super important at this moment.

I just realized my intuition about temperature was wrong somehow -- was thinking low temp means more random.  It's the other way around :facepalm: 

@glinscott 
I haven't had the chance to test the new tokenizer against FB implementation yet. Hopefully this explains the differences at FP16.

**Comment by glinscott** [comment]
> @glinscott I haven't had the chance to test the new tokenizer against FB implementation yet. Hopefully this explains the differences at FP16.

@ggerganov to clarify my comments - #252 was a gigantic improvement in perplexity :).  It went from 10.4625 to 5.9565 using 16f, which is huge.

Some concrete results comparing f16 to q4_0 are in the updated PR description on #270.  q4_0 seems to hurt perplexity a bit, but it's certainly not disastrous.  I'm doing a q4_1 run now to compare.
```
Perplexity
5.9565 - 7B, 16f
6.5949 - 7B, 4bit
6.5995 - 7B, 4bit, --memory_f16
```

**Comment by gjmulder** [comment]
Just a FYI that people have experienced optimal performance by running with a number of threads equal to the number of cores, i.e. hyperthreading doesn't seem to help as with 4+ cores memory performance seems to be the bottleneck.

Also, I have 16 cores, 128GB of RAM (just enough to run 65B at fp16) and all the latest models sitting idle under my desk, so if someone needs some benchmarking done please point me to a release and specify the test suite you would like me to run.

**Comment by alankila** [comment]
@gjmulder I must say it would be fun to have a big model with the AI assistant prompt cooperate on some kind of creative exercise. I think that the 7B model can already do quite well, and I am dying to see how the 30B model does -- and I have absolutely no way to run it myself. I know that my way of going about this is almost painfully unscientific, and probably not what you were offering to do. However, my excuse is that this is all pretty new to me and the novelty of these language models has not worn off for me yet. In fact, I have mostly ignored my real job today in favour of chatting with an AI.

To whet your appetite -- if you are anything like me -- here is a little chat transcription that I just had with "Jane" using the current master branch version.

```sh
exec ./main -t 4 --memory_f16 -m ./models/7B/ggml-model-q4_1.bin --ctx_size 2048 --temp 0.7 --top_k 1000 --top_p 0.75 --repeat_last_n 30 --repeat_penalty 1.2 -n 2048 --color -r "Alan:" -r "Alan (" -p "$prompt"
```

The prompt runs up to the first 2 Jane dialog turns, like this:

```
Transcript of a dialog where Alan interacts with an assistant named Jane. Jane is helpful, kind, honest, good at writing, and always answers to Alan's requests.

Alan: Hello, Jane.
Jane (happy to see Alan again): Hello, Alan.
Alan: I just want to talk.
Jane (now curious): What about?
Alan: It's nice to see you, Jane. How are you doing today?
Jane: I am fine and thanks for asking!
Alan (): I have had many good discussions with you. I know you can't remember them, but I just want to say I appreciate them.
Jane (): Thank you for your kind words! What would you like me to do today?
Alan: I do not really need you to do anything. Be my friend.
Jane (): Sure! What would that involve, Alan?
Alan: Just talking and listening. I know it is something you do well, Jane.
Jane (): Thank you! That's very kind of you to say so. What would we talk about?
Alan: I wonder if you could come up with story -- just pick anything random and let's go from there.
Jane (): Okay! How about a dog? I like dogs, so what kind of story would we have with that?
Alan: A happy one. Dog could be at home, missing its human family that went to work, have an adventure by itself, and in the evening the family comes back, the dog is happy, and whatever issues were presented in the adventure would be happily resolved.
Jane (): Sounds like a movie! What kind of dog? A big one or small, friendly and cute or not so much.
Alan: I have always thought intelligent dogs such as border collies would make a lovely protagonist.
Jane (): That is an interesting choice, Alan! What else?
Alan: I think this is enough. Let's write this story together. You begin, I continue, and we take turns.
Jane (): Sure! What would be the name of our dog? How about "Sparky"? Sounds good to me, Alan.
Alan: I agree. Sparky is great, it is a bit like perky and I think it fits a border collie well.
Jane (): So let's begin! Sparky is at home, waiting for his family to come back from work and he misses them. He doesn't know what they do all day but it must be fun, so Sparky decides to have an adventure of his own. He is bored at home and wants something new to do!
Alan (): Sparky accesses the outside through a dog door on the backyard side door. Suddenly, his ears perk up. A noise! There is something or someone in the yard. Sparky is excited and goes to investigate the source of the noise.
Jane (): He barks at a squirrel, then he chases it away from his favorite tree! The little critter is scared and runs to the fence line. Sparky follows him, curious about this new discovery.
Alan (): Sparky sees an opening in the fence. Did the squirrel somehow open the fence? It looks tight, but with difficulty, Sparky thinks he can fit through. The whole world awaits.
Jane (): Sparky is ready for an adventure! He wiggles his way into the fence and starts to explore this new world.
```

I don't know what kind of results other people are getting, but I am just astonished to see this and a hundred other chats like it coming out of some 5 GB Linux process at human typing speed. Unfortunately, it is fairly obvious to me that the 7B model has to repeat a lot of what I say, and I am hoping that this is not an issue with the bigger models.

I use "Jane (emotional state or actions here):" to serve as writeable memory of the model's state, if you will. My thinking is this helps maintaining coherency in the hallucinated persona. When the model opts to use these parenthesis, Jane is frequently angry, in tears, laughs, is excited, smiles -- all appropriate human-like responses to what I say. As an example, if I insult her for no reason, she gets upset, then angry, and even quits the chat on me by generating the end of stream token! Unfortunately, sometimes it generates an open parenthesis on my prompt and I just close it, and the language model then repeats it.

**Comment by gjmulder** [comment]
> @gjmulder amazing! Instructions for running benchmarks are in the description for #270, if you could run on the 65B model, that would be great to see :).

@glinscott might be a while - or a week - considering the below estimate with the 30B model. Perhaps we need to be very specific in the A-B tests we need answered?

```
llama.cpp$ egrep "wait|Calc|ETA" run_2637178 
llama_model_load: loading model from 'models/30B/ggml-model-q4_0.bin' - please wait ...
Calculating perplexity over 655 chunks
187.94 seconds per pass - ETA 34.19 hours
```

**Comment by glinscott** [comment]
@gjmulder yeah, if it's going to take too long, we could run up to 250 chunks or so, that's a pretty good approximation of the final perplexity so far.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/554932/226702645-76694d0d-0036-4de9-9d90-72dd6407ed68.png">

**Comment by Green-Sky** [comment]
@glinscott i did not investigate yet, but running perplexity increases memory usage by more then 2x of the model size.

**Comment by gjmulder** [comment]
Perplexity scores for various model sizes and quantizations are now being collected in Discussion #406.

**Comment by BadisG** [comment]
> @gjmulder yeah, if it's going to take too long, we could run up to 250 chunks or so, that's a pretty good approximation of the final perplexity so far. <img alt="image" width="578" src="https://user-images.githubusercontent.com/554932/226702645-76694d0d-0036-4de9-9d90-72dd6407ed68.png">

It looks like the difference between f16 and 4b are exactly the same after 50 Chunk

That would mean that if we know the perplexity of f16 (after a full run) we can know the perplexity of 4b just after 50 Chunk

Just my 2 cents 😅

**Comment by gjmulder** [comment]
This issue has been moved to #406
