### ISSUE TITLE
RPTQ state of the art quantization

### ISSUE THREAD

**Issue by bennmann** [ggerganov/llama.cpp#1295]
Per yuan etc all, RPTQ quant is state of the art down to 3bit

It would be good to implement RPTQ for llama and other c++ downstream projects

https://github.com/hahnyuan/RPTQ4LLM/blob/master/quantize/quantizer.py

https://arxiv.org/abs/2304.01089

**Comment by SlyEcho** [comment]
It's an interesting idea, but I don't understand how well it would translate to ggml because it usually only dequantizes only one row at a time.
