### ISSUE TITLE
[User] Error when converting Hugging Face model to GGML using convert.py script

### ISSUE THREAD

**Issue by nbvnbv** [ggerganov/llama.cpp#1322]
Hello,

I am trying to convert a Hugging Face model named `whisper-atco2-medium` to GGML format using the `convert.py` script from the `llama.cpp` repository. However, when I run the script, I encounter the following error:

`TypeError: ‘staticmethod’ object is not callable`

Here is the full traceback of the error:

`Traceback (most recent call last): File “.\convert.py”, line 1165, in <module> main() File “.\convert.py”, line 1145, in main model_plus = load_some_model(args.model) File “.\convert.py”, line 1071, in load_some_model models_plus.append(lazy_load_file(path)) File “.\convert.py”, line 865, in lazy_load_file return lazy_load_torch_file(fp, path) File “.\convert.py”, line 737, in lazy_load_torch_file model = unpickler.load() TypeError: ‘staticmethod’ object is not callable`

I am using the latest version of the `llama.cpp` repository and PyTorch version `2.0.0+cpu`. Can anyone provide guidance on how to resolve this issue and successfully convert the model to GGML format?

Thank you for your help.

**Comment by prusnak** [comment]
You should use the `convert-pt-to-ggml.py` script from the whisper.cpp repo: https://github.com/ggerganov/whisper.cpp/blob/master/models/convert-pt-to-ggml.py

If there is an issue with that, please open an issue in the whisper.cpp repo.
