### ISSUE TITLE
Investigate supporting starcode

### ISSUE THREAD

**Issue by Azeirah** [ggerganov/llama.cpp#1326]
Bigcode just released [starcoder](https://huggingface.co/bigcode/starcoder). This is a 15B model trained on 1T Github tokens. This seems like it could be an amazing replacement for gpt-3.5 and maybe gpt-4 for local coding assistance and IDE tooling!

More info: https://huggingface.co/bigcode

**Comment by notswileynet** [comment]
It looks like gpt-2. I'd imagine it's like codegen where you can use the normal gpt-2/gpt-j conversion/quantization scripts/main binary. You just need enough memory to convert/run it.

**Comment by ggerganov** [comment]
If it is like Saleforce's CodeGen model, checkout this repo: https://github.com/ravenscroftj/turbopilot

**Comment by redthing1** [comment]
I'm very much interested in this too.

**Comment by NouamaneTazi** [comment]
Working on it! Should be coming soon

**Comment by NouamaneTazi** [comment]
PR to support StarCoder/SantaCoder is ready! And results looking fine 🔥 
https://github.com/ggerganov/ggml/pull/146

**Comment by christianwengert** [comment]
I have seen it is supported in https://github.com/ggerganov/ggml/pull/146 but how I can this be used in llama.cpp?

**Comment by NouamaneTazi** [comment]
It cannot be used in llama.cpp as it's not the same model architecture. but you can find a similar repo to llama.cpp in https://github.com/bigcode-project/starcoder.cpp @christianwengert
