### ISSUE TITLE
Support for BioGPT

### ISSUE THREAD

**Issue by umhau** [ggerganov/llama.cpp#1328]
I didn't see any prior discussion of this. A few months ago this GPT model [was released](https://github.com/microsoft/BioGPT) which seemed to do very well with medical Q&A. 

I don't see any indication that it's based on the existing GPT variations. There's a couple demos here: [Q&A demo](https://huggingface.co/spaces/katielink/biogpt-qa-demo) and [BioGPT-Large demo](https://huggingface.co/spaces/katielink/biogpt-large-demo).

**Comment by PABannier** [comment]
@umhau I implemented it [here](https://github.com/PABannier/biogpt.cpp). 

@ggerganov Do you want me to open a PR to include BioGPT into the examples? (could be on the `ggml` repo as well). Note that BioGPT has a few tricks (it's not the exact same as GPT-2), and the tokenizer is different (Moses tokenization + BPE).

**Comment by ggerganov** [comment]
@PABannier 

Sure! Looks great
Let's add it as an example in https://github.com/ggerganov/ggml

**Comment by umhau** [comment]
Wow, that's awesome. I was totally stuck on that tokenizer.

**Comment by evanmiller** [comment]
Looks like the example has been added to the docs, closing
