### ISSUE TITLE
[Announcement] OpenLLaMA 7B 300BT preview ready for llama.cpp

### ISSUE THREAD

**Issue by rozek** [ggerganov/llama.cpp#1330]
Just for the records: I've uploaded the [300BT preview](https://huggingface.co/openlm-research/open_llama_7b_preview_300bt) of the [Open LLaMA](https://github.com/openlm-research/open_llama) model based on the [RedPajama 1T dataset](https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T), converted to GGML and quantized to 4 bit, ready to be used with llama.cpp - see [my repo on Huggingface](https://huggingface.co/rozek/OpenLLaMA_7B_300BT_q4)

**Comment by prusnak** [comment]
Closing in favor of https://github.com/ggerganov/llama.cpp/issues/1330 where more is being discussed.

**Comment by Green-Sky** [comment]
@prusnak :rofl: you meant https://github.com/ggerganov/llama.cpp/issues/1291, right?
