### ISSUE TITLE
How to quantize a model ?

### ISSUE THREAD

**Issue by LeLaboDuGame** [ggerganov/llama.cpp#1344]
Hello ! I m new here ! I don’t know if here is the good place to ask my question so sorry in advanced if it’s not the case.
I would quantize a model on Hugging Face: https://huggingface.co/decapoda-research/llama-13b-hf.
I have try to quantize this model but I can’t because with the covertor.py I can only convert this model in f16 or f32 model and not in q1 or q0.

I don’t know if I do correctly the quantisation or something else so if someone can explain me how to do it it’s very appreciated!
Thanks in advance. 
Labo.

ps: I don’t speak very good in English (not my first language and I m young)

**Comment by klosax** [comment]
Follow the instructions in the [Prepare Data & Run](https://github.com/ggerganov/llama.cpp#prepare-data--run) section of the readme.

**Comment by tristanvdb** [comment]
@LeLaboDuGame the instructions are indeed quite sparse... I am running through them myself right now.

You should provide the commands you ran and the errors you received.

PS: use code-blocks to format commands and code ; Never use screenshots of a terminal (that is the first thing I tell students)

**Comment by LeLaboDuGame** [comment]
okay, so at first thanks for your reply ! It's verry appreciate :-D.
I use this cmd to transform the model to fp16
`python .\convert.py --outtype f16 .\ia\llama-13b-hf\`
And I think I want to qantize directly with the convertor but it not work.
So I think I have to use the Quantize app but I dont were she is in the repo...
If someone can explain me how to fin the Quantize app (./quantize) ...
Thanks in advance !

**Comment by tristanvdb** [comment]
`quantize` is an executable that you need to build by running `make` in the repository (it seems that you are using Windows so Cmake instead).
I found a script to download the original weights: https://github.com/juncongmoo/pyllama (see below for direct link to the script)
I did not have to add any arguments to `convert.py`.

Frankly, the [Prepare Data & Run](https://github.com/ggerganov/llama.cpp#prepare-data--run) section need to be improved.

Here is what I used (Ubuntu):
```
git clone https://github.com/ggerganov/llama.cpp.git
python3 -m pip install -r llama.cpp/requirements.txt
make -C llama.cpp -j4 # runs make in subdir with 4 processes

wget https://raw.githubusercontent.com/juncongmoo/pyllama/main/llama/download_community.sh
chmod +x download_community.sh
./download_community.sh 7B llama.cpp/models
#./download_community.sh 7B,13B,30B,65B llama.cpp/models
python3 llama.cpp/convert.py llama.cpp/models/7B/
./llama.cpp/quantize ./llama.cpp/models/7B/ggml-model-f16.bin ./llama.cpp/models/7B/ggml-model-q4_0.bin q4_0
```

**Comment by tristanvdb** [comment]
If you followed the instructions to build with Cmake then `quantize` might be under `llama.cpp/build` or `llama.cpp/build/examples/quantize` (probably the second)

**Comment by SlyEcho** [comment]
It should not be necessary to build it, you can also use the binaries from the [Releases](https://github.com/ggerganov/llama.cpp/releases) page. Pick your processor type (AVX2 should be most common) and `quantize.exe` should be there. If you run it without arguments it gives you instructions.

**Comment by LeLaboDuGame** [comment]
Perfect ! Thanks to all ! It function !

**Comment by ShubhBuchunde** [comment]
i am trying to run in windows i am getting the error as 

(llama2) C:\Users\Shubh\Documents\Data Profiling\llama-main\llama.cpp>./examples/quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SlyEcho** [comment]
You need to either build quantize.exe using the instructions or download it from the releases page.

**Comment by ShubhBuchunde** [comment]
How can i build quantize.exe? can u please share the steps

**Comment by SlyEcho** [comment]
Please read the [build instructions](https://github.com/ggerganov/llama.cpp#build). It will build all the programs, including main.exe and quantize.exe.

Or download the [latest release](https://github.com/ggerganov/llama.cpp/releases/latest). The file `llama-master-*-bin-win-noavx-x64.zip` should be good enough for any 64-bit processor to quantize models, but for generation you want some other version, probably.

**Comment by klosax** [comment]
> C:\Users\Shubh\Documents\Data Profiling\llama-main\llama.cpp>./examples/quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0

I think the relative path name is wrong for windows, try without leading `./`:
`examples/quantize models/7B/ggml-model-f16.bin models/7B/ggml-model-q4_0.bin q4_0`

**Comment by ShubhBuchunde** [comment]
> > C:\Users\Shubh\Documents\Data Profiling\llama-main\llama.cpp>./examples/quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0
> 
> I think the relative path name is wrong for windows, try without leading `./`: `examples/quantize models/7B/ggml-model-f16.bin models/7B/ggml-model-q4_0.bin q4_0`

(llama2) C:\Users\Shubh\Documents\Data Profiling\llama-main\llama.cpp>examples/quantize models/7B/ggml-model-f16.bin models/7B/ggml-model-q4_0.bin q4_0
'examples' is not recognized as an internal or external command,
operable program or batch file.

**Comment by klosax** [comment]
Forgot that windows uses blackslash also..
`examples\quantize models\7B\ggml-model-f16.bin models\7B\ggml-model-q4_0.bin q4_0`

**Comment by learning-log** [comment]
Recently the location of quantization file has changed and now required following command:

llama.cpp/build/bin/llama-quantize models\7B\ggml-model-f16.bin models\7B\ggml-model-q4_0.bin q4_0
