### ISSUE TITLE
[User] Chinese alpaca need more REQ memory

### ISSUE THREAD

**Issue by morningtzh** [ggerganov/llama.cpp#1354]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I used [Chinese LLaMA / Alpaca](https://github.com/ymcui/Chinese-LLaMA-Alpaca) Model

# Current Behavior

When I input less than 19 Chinese characters, it worked. But llama will segmentation fault when I input more than 19 Chinese characters

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

macOS Intel

* SDK version, e.g. for Linux:

```
[morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
% python3 --version                                                                                           127 ↵ ✹ ✭
Python 3.8.3
[morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
% make --version                                                                                                    ✹ ✭
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
[morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
% g++ --version                                                                                                     ✹ ✭
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
%
```

# Failure Information (for bugs)

ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)

# Steps to Reproduce

# Failure Logs

Example run with the Linux command [perf](https://www.brendangregg.com/perf.html)

```
% ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f ./prompts/alpaca.txt  -c 40000 -n 40000  -t 8 -ins
main: warning: model does not support context sizes greater than 2048 tokens (40000 specified);expect poor results
main: build = 516 (1b0fd45)
main: seed  = 1683458208
llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 40000
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  68.20 KB
llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  = 20000.00 MB

system_info: n_threads = 8 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 40000, n_batch = 512, n_predict = 40000, n_keep = 21


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - If you want to submit another line, end your input in '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 一二三四五六七八九十一二三四五六七八九十
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
[1]    2177 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  -c 40000 -n  -

```

# Debug

MEM_REQ_EVAL at llama.cpp@87 looks like needs a bigger value. After I edit 7B memory as 1024MB, the Chinese model can work on hundreds of Chinese characters.

I don't know much about AI frameworks, so I can only make a tentative modification to MEM_REQ_EVAL and hope that someone else with the same problem will provide some simple modification schemes.

Edited llama.cpp
``` cpp
// this is mostly needed for temporary mul_mat buffers to dequantize the data
// not actually needed if BLAS is disabled
static const std::map<e_model, size_t> & MEM_REQ_EVAL()
{
    static std::map<e_model, size_t> _MEM_REQ_EVAL = {
        { MODEL_7B,   1024ull * MB }, // I only have a 7B model, so I only modified this value locally.
        { MODEL_13B, 1024ull * MB },
        { MODEL_30B, 1280ull * MB },
        { MODEL_65B, 1536ull * MB },
    };
    return _MEM_REQ_EVAL;
}
```

**Comment by Green-Sky** [comment]
> main: warning: model does not support context sizes greater than 2048 tokens (40000 specified);expect poor results

are you sure, this is what you want? the models are knows to have very poor quality with ctx >2048 , and 40k is ludicrous.

**Comment by SlyEcho** [comment]
The memory overflow comes directly from the large context, it is unsupported.

They are LoRa models over the base LLaMa, so it shouldn't change the context size.

Here they show how to convert and run it with llama.cpp and they just use the default context 512: https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/notebooks/convert_and_quantize_chinese_llama.ipynb

**Comment by ymcui** [comment]
Try to use a lower batch size. 
And, of course, please do not use a very large number for `-n` and `-c`. `2048` is enough.

**Comment by FNsi** [comment]
For me with Loras, ctx limit should be 2048 or lower.
(I do try 2304, and it works sometime. )

**Comment by morningtzh** [comment]
@FNsi @ymcui @Green-Sky @SlyEcho 

Yes, I started with a default value of 512 for both -c and -n, but it's easy to crash with that setting too. Even setting it to 128 also causes the crash.

like that:

``` 

# default 512 context

[morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
% ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f ./prompts/alpaca.txt -ins  130 ↵ ✹ ✭
main: build = 516 (1b0fd45)
main: seed  = 1683640239
llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  68.20 KB
llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  =  256.00 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 21


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - If you want to submit another line, end your input in '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 一二三四五六七八九十一二三四五六七八九十
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
[1]    21621 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  -ins


# 256  context

[morningtzh@MBP-yeshigelaji:~/workplace/freedom-gpt/llama.cpp on master]
% ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color        -f ./prompts/alpaca.txt --ctx_size 256  -n -1  -ins -b 256  --top_k 10000 --temp 0.2 --repeat_penalty 1.1 -t 7
main: build = 516 (1b0fd45)
main: seed  = 1683640676
llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 256
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  68.20 KB
llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  =  128.00 MB

system_info: n_threads = 7 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 10000, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 256, n_batch = 256, n_predict = -1, n_keep = 21


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - If you want to submit another line, end your input in '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 一二三四五六七八九十一二三四五六七八九十
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
[1]    22691 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  --ctx_size 256
```

**Comment by FNsi** [comment]
> @FNsi @ymcui @Green-Sky @SlyEcho 
> 
> 
> 
> Yes, I started with a default value of 512 for both -c and -n, but it's easy to crash with that setting too. Even setting it to 128 also causes the crash.
> 
> 
> 
> like that:
> 
> 
> 
> ``` 
> 
> 
> 
> # default 512 context
> 
> 
> 
> [morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
> 
> % ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f ./prompts/alpaca.txt -ins  130 ↵ ✹ ✭
> 
> main: build = 516 (1b0fd45)
> 
> main: seed  = 1683640239
> 
> llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
> 
> llama_model_load_internal: format     = ggjt v1 (latest)
> 
> llama_model_load_internal: n_vocab    = 49954
> 
> llama_model_load_internal: n_ctx      = 512
> 
> llama_model_load_internal: n_embd     = 4096
> 
> llama_model_load_internal: n_mult     = 256
> 
> llama_model_load_internal: n_head     = 32
> 
> llama_model_load_internal: n_layer    = 32
> 
> llama_model_load_internal: n_rot      = 128
> 
> llama_model_load_internal: ftype      = 7 (mostly Q8_0)
> 
> llama_model_load_internal: n_ff       = 11008
> 
> llama_model_load_internal: n_parts    = 1
> 
> llama_model_load_internal: model size = 7B
> 
> llama_model_load_internal: ggml ctx size =  68.20 KB
> 
> llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
> 
> llama_init_from_file: kv self size  =  256.00 MB
> 
> 
> 
> system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> 
> main: interactive mode on.
> 
> Reverse prompt: '### Instruction:
> 
> 
> 
> '
> 
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> 
> generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 21
> 
> 
> 
> 
> 
> == Running in interactive mode. ==
> 
>  - Press Ctrl+C to interject at any time.
> 
>  - Press Return to return control to LLaMa.
> 
>  - If you want to submit another line, end your input in '\'.
> 
> 
> 
>  Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> > 一二三四五六七八九十一二三四五六七八九十
> 
> ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
> 
> [1]    21621 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  -ins
> 
> 
> 
> 
> 
> # 256  context
> 
> 
> 
> [morningtzh@MBP-yeshigelaji:~/workplace/freedom-gpt/llama.cpp on master]
> 
> % ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color        -f ./prompts/alpaca.txt --ctx_size 256  -n -1  -ins -b 256  --top_k 10000 --temp 0.2 --repeat_penalty 1.1 -t 7
> 
> main: build = 516 (1b0fd45)
> 
> main: seed  = 1683640676
> 
> llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
> 
> llama_model_load_internal: format     = ggjt v1 (latest)
> 
> llama_model_load_internal: n_vocab    = 49954
> 
> llama_model_load_internal: n_ctx      = 256
> 
> llama_model_load_internal: n_embd     = 4096
> 
> llama_model_load_internal: n_mult     = 256
> 
> llama_model_load_internal: n_head     = 32
> 
> llama_model_load_internal: n_layer    = 32
> 
> llama_model_load_internal: n_rot      = 128
> 
> llama_model_load_internal: ftype      = 7 (mostly Q8_0)
> 
> llama_model_load_internal: n_ff       = 11008
> 
> llama_model_load_internal: n_parts    = 1
> 
> llama_model_load_internal: model size = 7B
> 
> llama_model_load_internal: ggml ctx size =  68.20 KB
> 
> llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
> 
> llama_init_from_file: kv self size  =  128.00 MB
> 
> 
> 
> system_info: n_threads = 7 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> 
> main: interactive mode on.
> 
> Reverse prompt: '### Instruction:
> 
> 
> 
> '
> 
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 10000, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> 
> generate: n_ctx = 256, n_batch = 256, n_predict = -1, n_keep = 21
> 
> 
> 
> 
> 
> == Running in interactive mode. ==
> 
>  - Press Ctrl+C to interject at any time.
> 
>  - Press Return to return control to LLaMa.
> 
>  - If you want to submit another line, end your input in '\'.
> 
> 
> 
>  Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> > 一二三四五六七八九十一二三四五六七八九十
> 
> ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
> 
> [1]    22691 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  --ctx_size 256
> 
> ```
> 
> 
> 
> 

I guess your ram is not enough. Maybe you should try q4_0 instead.

**Comment by SlyEcho** [comment]
Can you try without BLAS enabled?

I think the problem is somewhere in the work buffer calculation.

**Comment by ymcui** [comment]
> @FNsi @ymcui @Green-Sky @SlyEcho 
> 
> 
> 
> Yes, I started with a default value of 512 for both -c and -n, but it's easy to crash with that setting too. Even setting it to 128 also causes the crash.
> 
> 
> 
> like that:
> 
> 
> 
> ``` 
> 
> 
> 
> # default 512 context
> 
> 
> 
> [morningtzh@MBP-yeshigelaji:~/workplace/llama.cpp on master]
> 
> % ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f ./prompts/alpaca.txt -ins  130 ↵ ✹ ✭
> 
> main: build = 516 (1b0fd45)
> 
> main: seed  = 1683640239
> 
> llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
> 
> llama_model_load_internal: format     = ggjt v1 (latest)
> 
> llama_model_load_internal: n_vocab    = 49954
> 
> llama_model_load_internal: n_ctx      = 512
> 
> llama_model_load_internal: n_embd     = 4096
> 
> llama_model_load_internal: n_mult     = 256
> 
> llama_model_load_internal: n_head     = 32
> 
> llama_model_load_internal: n_layer    = 32
> 
> llama_model_load_internal: n_rot      = 128
> 
> llama_model_load_internal: ftype      = 7 (mostly Q8_0)
> 
> llama_model_load_internal: n_ff       = 11008
> 
> llama_model_load_internal: n_parts    = 1
> 
> llama_model_load_internal: model size = 7B
> 
> llama_model_load_internal: ggml ctx size =  68.20 KB
> 
> llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
> 
> llama_init_from_file: kv self size  =  256.00 MB
> 
> 
> 
> system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> 
> main: interactive mode on.
> 
> Reverse prompt: '### Instruction:
> 
> 
> 
> '
> 
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> 
> generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 21
> 
> 
> 
> 
> 
> == Running in interactive mode. ==
> 
>  - Press Ctrl+C to interject at any time.
> 
>  - Press Return to return control to LLaMa.
> 
>  - If you want to submit another line, end your input in '\'.
> 
> 
> 
>  Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> > 一二三四五六七八九十一二三四五六七八九十
> 
> ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
> 
> [1]    21621 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  -ins
> 
> 
> 
> 
> 
> # 256  context
> 
> 
> 
> [morningtzh@MBP-yeshigelaji:~/workplace/freedom-gpt/llama.cpp on master]
> 
> % ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color        -f ./prompts/alpaca.txt --ctx_size 256  -n -1  -ins -b 256  --top_k 10000 --temp 0.2 --repeat_penalty 1.1 -t 7
> 
> main: build = 516 (1b0fd45)
> 
> main: seed  = 1683640676
> 
> llama.cpp: loading model from /Users/morningtzh/Downloads/llama/7B/ggml-model-q8_0.bin
> 
> llama_model_load_internal: format     = ggjt v1 (latest)
> 
> llama_model_load_internal: n_vocab    = 49954
> 
> llama_model_load_internal: n_ctx      = 256
> 
> llama_model_load_internal: n_embd     = 4096
> 
> llama_model_load_internal: n_mult     = 256
> 
> llama_model_load_internal: n_head     = 32
> 
> llama_model_load_internal: n_layer    = 32
> 
> llama_model_load_internal: n_rot      = 128
> 
> llama_model_load_internal: ftype      = 7 (mostly Q8_0)
> 
> llama_model_load_internal: n_ff       = 11008
> 
> llama_model_load_internal: n_parts    = 1
> 
> llama_model_load_internal: model size = 7B
> 
> llama_model_load_internal: ggml ctx size =  68.20 KB
> 
> llama_model_load_internal: mem required  = 9180.13 MB (+ 1026.00 MB per state)
> 
> llama_init_from_file: kv self size  =  128.00 MB
> 
> 
> 
> system_info: n_threads = 7 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> 
> main: interactive mode on.
> 
> Reverse prompt: '### Instruction:
> 
> 
> 
> '
> 
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 10000, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> 
> generate: n_ctx = 256, n_batch = 256, n_predict = -1, n_keep = 21
> 
> 
> 
> 
> 
> == Running in interactive mode. ==
> 
>  - Press Ctrl+C to interject at any time.
> 
>  - Press Return to return control to LLaMa.
> 
>  - If you want to submit another line, end your input in '\'.
> 
> 
> 
>  Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> > 一二三四五六七八九十一二三四五六七八九十
> 
> ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819311376, available 805306368)
> 
> [1]    22691 segmentation fault  ./main -m ~/Downloads/llama/7B/ggml-model-q8_0.bin --color -f  --ctx_size 256
> 
> ```
> 
> 
> 
> 

Your batch size is still too big. You can just simply set it to 32 or 16 (or even lower) without significant slow down.

**Comment by SlyEcho** [comment]
I tried to see how the increased vocab size affects allocated memory, but I didn't find it yet. In any case, the memory requirements are hardcoded and may be not sufficient for other models. If you edit `llama.cpp` there are some numbers near the start of the file for different LLaMa model sizes. You can increase them from 512 MB to 1024 MB etc. and see if it helps.

> Your batch size is still too big. You can just simply set it to 32 or 16 (or even lower) without significant slow down.

It's not too big, 512 is the default now. And it doesn't help because if the context is filled up it will run out of memory because the work buffer gets larger. Maybe using a very small _context_ of would work but then it would not be usable.

**Comment by cedonley** [comment]
I've noticed the same issues with this model, but *only* with the 7B q4_x. Somehow the 13B q4_0 loads and works just fine. Using M1 with 16GB RAM. Definitely something is miscalculating the memory required when using the 7B model with the expanded Chinese vocabulary. 7B loads okay, then anything more than a dozen or so characters of context and it blows up with the same error documented in the original post. 13B works with 2048 ctx and default batch size.

**Comment by FNsi** [comment]
> I've noticed the same issues with this model, but *only* with the 7B q4_x. Somehow the 13B q4_0 loads and works just fine. Using M1 with 16GB RAM. Definitely something is miscalculating the memory required when using the 7B model with the expanded Chinese vocabulary. 7B loads okay, then anything more than a dozen or so characters of context and it blows up with the same error documented in the original post. 13B works with 2048 ctx and default batch size.

I think it's the Blas related setting, which set 768 in 7b. Try not using Blas I guess that would work, and if it work without Blas, 

modify 7b parameter in 

Static const std::map<e_model, size_t> &MEM_REQ_EVAL()

From 768 to 1024.

**Comment by cedonley** [comment]
> in llama.cpp
> 
> modify 7b parameter inside
> 
> Static const std::map<e_model, size_t> & MEM_REQ_EVAL()
> 
> From 768 to 1024.
> 
> And the Blas version should be work.

That did the trick.
