### ISSUE TITLE
[User] Support for newline reverse prompt

### ISSUE THREAD

**Issue by MrJackSpade** [ggerganov/llama.cpp#1362]
It would be really helpful to be able to define return carriage and newline as reverse prompts. 

It doesn't look like there's a way to cause control to return on a new line. I've tried a few different combinations on the command line, but it flies right through them while generating.

**Comment by DannyDaemonic** [comment]
I guess I could make `-e` work on reverse prompts as well. It wouldn't work as is, but out of curiosity, did you try "\n"?

In Linux or macOS, try  `-r $'\n'`. If you're in Windows and don't have Powershell, I think it's impossible, but if you have it installed, you should be able to do it like this ``-r "`n"`` (that's the tick mark above the ~ key).

**Comment by MrJackSpade** [comment]
I'm on Windows. 

Here is the results of my testing

1. "`n" in PowerShell appears to work
2. "\n" (literal) through PInvoke command line arguments appears to work
3. "\n" (escape sequence) does not appear to work in any context

Given the above, I would expect "^\n" (literal) to work through cmd.exe, however I haven't tested that since (2) actually solves my use case. 

It might be a good idea to add a note to the documentation.

It would also be nice to have the -e work on the reverse prompt as well, but as long as there's a note in the document its probably not necessary.  Its always good to have the functionality standardized across the different parameters though. I assumed using a literal wouldn't work largely because -e was offered on the prompt.

Feel free to close this ticket

**Comment by SlyEcho** [comment]
`-e` could be made to work for other text arguments. But should it change all of them or just the next following one...
