### ISSUE TITLE
Tried to run AVX2 instruction on AVX only CPU

### ISSUE THREAD

**Issue by inferrna** [ggerganov/llama.cpp#1380]
![image](https://github.com/ggerganov/llama.cpp/assets/4245277/55f2642f-2441-4fb5-89b6-96f01e56ddf0)

Built from master, latest commit is 41654efea879bbdf4fd794e13335929d4cf0eb90
My CPU is Ivy Bridge XEON 2680v2, which is only AVX capable.

**Comment by hungerf3** [comment]
Did you use Make or Cmake to build?  The Makefile should set the architecture to "native" which detects the supported features at compile time.

**Comment by inferrna** [comment]
I used Cmake. Problem has gone after reconfiguring with 
` -DLLAMA_NATIVE=ON`
thank you.
