### ISSUE TITLE
multiline-input

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#1382]
I'm testing newest build.
I have a stupid question as I added --multiline-input as parameter .
How to end of my input now? 
Pressing enter just invoking a new line.

Also without that parameter I can invoke answer but arrows up and down are not working so I can not see my history questions. 
Arrows left and right also not working  so I can not correct my spelling mistakes .  

All those things were working  fine earlier.

**Comment by DannyDaemonic** [comment]
The directions will change depending on if you use --multiline-input or not.

Without it:
```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
 ```
 
 With it on
```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - To return control to LLaMa, end your input with '\'.
 - To return control without starting a new line, end your input with '/'.
```

So if you are on `--multiline-mode`, you should be able to end your input with \ to return control:
```
This is what it would look like\
```

>Also without that parameter I can invoke answer but arrows up and down are not working so I can not see my history questions.
Arrows left and right also not working so I can not correct my spelling mistakes .

What platform are you on?

**Comment by mirek190** [comment]
Windows

Tested with CMD and Power shell .

**Comment by DannyDaemonic** [comment]
Ah, this is a feature of Window Terminal I wasn't aware of. The arrow keys I can fix. The history is a bit harder. Do you use the history feature?

**Comment by mirek190** [comment]
Of course I use the history why I wouldn't? 
Do you not use a history of your inputs by up / down arrows?

In terninal  , cmd  or power shell is a very important feature.  :)

**Comment by DannyDaemonic** [comment]
I use the history feature on the shell, it is very useful there, but I've never seen it used a program before.

**Comment by mirek190** [comment]
Your newest fix  master-e6a46b0  not helped at all.   :-/
Anything changed.

**Comment by maddes8cht** [comment]
Regarding multiline input:

Can't we simply use `Shift-Return` for having a new line without sending control back to Llama?
This would be kind of standard behaviour.
Doing shift-return to submit a new line without submitting a command is pretty common.
It works that way in the ChatGPT Web interface and it's easy discoverable if you are familiar with keyboard standards.
I think it's the best way to handle multiline input.

**Comment by DannyDaemonic** [comment]
@maddes8cht I would love to make it use `Shift-Enter`! It seems in a terminal/console, `Enter` comes across as `\n` weather or not you're holding shift. There might be some hacks we could use to accomplish this but we'd probably have to implement it separately on Windows, macOS, and Windows. I'll have to think on it and see if I can come up with something, but don't hold your breath.

For what it's worth, `\` is fairly typical in terminal/console apps.

**Comment by maddes8cht** [comment]
I know basic c/c++, and the main.cpp doesn't look really complicated at first sight (except for the fact that everything is in a rather unstructured queue).  However, I find it surprisingly difficult (but I haven't tried too hard) to find the place where the distinction of multiline input is processed, and finally the input of enter should be processed somewhere there as well.

So I ask myself why it doesn't boil down to a simple query of the last two values. If at the end there is a combination of 0/13 or 224/13, then it was shift enter, if it is an alphanum and 13, then it was enter.
Am I seeing this wrong, or is there a reason why this cannot be implemented in the existing main.cpp?

**Comment by patrakov** [comment]
@DannyDaemonic That's why the "unless inside the MarkDown block" suggestion.

**Comment by mirek190** [comment]
I think the best will be fast double enter.
Shall we say 0.1 second between second enter pressed.

**Comment by DannyDaemonic** [comment]
Hmm, interesting approach, but it will trigger when someone pastes text into the terminal. Two `Enter`s would happen almost instantly.

I'm softening on the `Ctrl-D` idea but I still wonder how mobile users are effected by control keys. I also wonder if there are systems where it closes the stream permanently.

**Comment by mirek190** [comment]
"almost instantly" is different than pressed twice enter by human. I think the proper code could recognize it easily  ;)
something like pressed between 10 ms to 100 ms between first and second press only.
Pasted text will be "press enter" faster than 1 ms I presume....

**Comment by mirek190** [comment]
> Yes, thank you. `f9a6364` is the one right before `41654ef`. So that's the latest one without the arrow keys. You can use that one in the meantime if you want the arrow keys. I'll drop an update here once the arrow keys are working.
> 
> This was a feature specific to Windows Terminal (I believe Windows 11) only. When I add the arrows back in, it will work for everyone, but it could take a day or so with everything else that's going on right now.

Few days past  .. are you going to fix it? 

I will be appreciate

**Comment by DannyDaemonic** [comment]
Yeah, sorry. I caught COVID. I'm not dying or anything but it takes a lot out of me.

It's still in my plans though. So don't worry, I haven't forgotten!

**Comment by mirek190** [comment]
Ok no problem ;P

I had covid few mounts ago I know feeling  ....

**Comment by DannyDaemonic** [comment]
Sorry, there's a not on github but it probably didn't go to your email. You can try out the patch at #1558. If you're only using the precompiled versions you'll have to wait for it to be reviewed and merged.

**Comment by mirek190** [comment]
Would be nice multi line input plus working arrows at the same time

**Comment by DannyDaemonic** [comment]
You can combine multiline with `--simple-io`, but you loose the cleaness of the look. It will work though.

I also have a future PR that adds the arrows/controls back in along with some other additional features. If you do compile it yourself, I can probably post the PR as a draft for you to try out.

**Comment by mirek190** [comment]
Downloaded newest build binaries run main.exe with  --simple-io    <-- such parameter not exist  ...

**Comment by DannyDaemonic** [comment]
Yeah, it has to be approved first. There's a bit of a process involved.

**Comment by mirek190** [comment]
Any improvements?
I still waiting for fix it  ;)
