### ISSUE TITLE
[issue] [enhancement] add OpenCL guide and distro guides

### ISSUE THREAD

**Issue by skidd-level-100** [ggerganov/llama.cpp#1385]
# Prerequisites

# Expected Behavior

Not be a pain to set up CLBlast

# Current Behavior

I managed to get it to work on my fedora (silverblue,Nvidia) machine it took WAY to long (8 hours of package finding, header tinkering, etc), then I went to help my friend set it up
on amd and we cannot get it to work the issue seems to be that we cannot find all the required packages to use clBlast or openBLAS
# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

physical

* Operating System, e.g. for Linux:
fedora linux (silverblue)
Linux 6.2.14-300.fc38.x86_64

* SDK version, e.g. for Linux:
Python 3.11.3
GNU Make 4.4
g++ (GCC) 13.1.1 20230426 (Red Hat 13.1.1-1)

# Failure Information (for bugs)

fatal error: cannot open file '/usr/lib64/clc/gfx909-amdgcn-mesa-mesa3d.bc': No such file or directory
*on my friends amd pc*
I looked it up and no guides where working (we are probably missing a package)

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.
1. attempt to get clBLAST to work on fedora (probably most distros)
2. cry in corner for 8 days, 3hours, 53 minutes and 5.6969 secounds
# Failure Logs
fatal error: cannot open file '/usr/lib64/clc/gfx909-amdgcn-mesa-mesa3d.bc': No such file or directory
```
tried finding packages related to gfx,mesa,amd,opencl,clblast,openblas,blas etc
afterwards llama detected my friends amd gpu (laptop,radeon)
and then crashes with above error

I know its possible but I feel like I tried everything to get it to work please help!

please add more documentation for openCL and add names of required packages for linux (not specific distros packages) 
example: "you need rocm runtime,pkg2,pkg3,etc for amd find thease in your distros repo"

edit: currently waiting on him to install ' rocm-opencl' we already have rocm-runtime but i dont think we have this (we still might though)

edit2: it worked but non the less it was a pain to get running please add documention

**Comment by DaniAndTheWeb** [comment]
Try building it with `GGML_CLBLAST_PLATFORM` and `GGML_CLBLAST_DEVICE` setting each to a number. Default is GGML_CLBLAST_PLATFORM=0 and GGML_CLBLAST_DEVICE=0 so you should specify other numbers. For my 5700xt for example I have to set GGML_CLBLAST_PLATFORM=1.

**Comment by zenixls2** [comment]
For clblast, check https://github.com/CNugteren/CLBlast and compile your own.
If you already have cuda installed, you could skip the opencl part by flags.

**Comment by SlyEcho** [comment]
This is not a problem of llama.cpp, but rather Mesa.

Can you try with the AMD OpenCL driver?

It is called `community/rocm-opencl-runtime` on Arch. Maybe you can use [AMD's instructions](https://amdgpu-install.readthedocs.io/en/latest/) for others?
