### ISSUE TITLE
Does llama.cpp support gpt-2-q4?

### ISSUE THREAD

**Issue by realcarlos** [ggerganov/llama.cpp#1386]
I noticed ggml could run gpt-2 , I wonder if llama.cpp support too, I have download gpt-2-q4 model from huggingface ,but failed to run.

**Comment by realcarlos** [comment]
I tried to convert Cerebras-GPT-111M for llama.cpp, it could run with ggml , but I got error like below 

❯ ./quantize ./models/Cerebras-GPT-111M/ggml-model-f16.bin ./models/output/cerebras-q4-0.bin q4_0
llama.cpp: loading model from ./models/Cerebras-GPT-111M/ggml-model-f16.bin
llama_model_quantize: failed to quantize: missing tok_embeddings.weight
main: failed to quantize model from './models/Cerebras-GPT-111M/ggml-model-f16.bin'

**Comment by realcarlos** [comment]
❯ python3 convert.py ./models/Cerebras-GPT-111M/
Loading model file models/Cerebras-GPT-111M/ggml-model-f16.bin
Traceback (most recent call last):
  File "/Users/bytedance/llama.cpp/convert.py", line 1149, in <module>
    main()
  File "/Users/bytedance/llama.cpp/convert.py", line 1137, in main
    vocab = load_vocab(vocab_dir)
  File "/Users/bytedance/llama.cpp/convert.py", line 1078, in load_vocab
    raise FileNotFoundError(f"Could not find tokenizer.model in {path} or its parent; if it's in another directory, pass the directory as --vocab-dir")
FileNotFoundError: Could not find tokenizer.model in models/Cerebras-GPT-111M or its parent; if it's in another directory, pass the directory as --vocab-dir

**Comment by realcarlos** [comment]
<img width="712" alt="截屏2023-05-10 11 29 51" src="https://github.com/ggerganov/llama.cpp/assets/13853/acfedbb2-a1c7-47a0-a4c0-9e207980564e">
this is the screenshot of "models/Cerebras-GPT-111M"

**Comment by LostRuins** [comment]
Cerebras is a GPT2 based model, not llama, and won't work with this repo. 

You can run it with the gpt2 example main.cpp example in the ggml repo, or via KoboldCpp which automatically detects format. 

(Disclaimer: I am a koboldcpp dev)
