### ISSUE TITLE
[Feature request] make model combination possible (long shot!)

### ISSUE THREAD

**Issue by skidd-level-100** [ggerganov/llama.cpp#1400]
I would love to see a model combination tool! it would be awesome! we have loras which is awesome, but full fledged combining would be even better!

**Comment by SlyEcho** [comment]
How does model combination work?

Do you have some paper to link to so I could understand?

**Comment by FNsi** [comment]
> How does model combination work?
> 
> 
> 
> Do you have some paper to link to so I could understand?

I think he means merge multi lora weights to the llama? For example merge both wizard-vicuña and starcode in the same time.
