### ISSUE TITLE
llama.cpp runs WizardLM 7B

### ISSUE THREAD

**Issue by rozek** [ggerganov/llama.cpp#1402]
Just for the records: the new [WizardLM](https://github.com/nlpxucan/WizardLM) model seems to run fine with llama.cpp, just download file [wizardLM-7B.ggml.q4_0.bin](https://huggingface.co/TheBloke/wizardLM-7B-GGML/blob/main/wizardLM-7B.ggml.q4_0.bin) from [Huggingface](https://huggingface.co/TheBloke/wizardLM-7B-GGML)

**Comment by ggerganov** [comment]
Feel free to add a reference in the README

**Comment by Alumniminium** [comment]
There's also Wizard-Vicuna, which is the best model ever.

**Comment by aseok** [comment]
> 

Pls send link.

**Comment by zacharyfmarion** [comment]
@rozek what exactly did you do to quantize? Which files do I need to download to do it myself?
