### ISSUE TITLE
Interactive mode does not work

### ISSUE THREAD

**Issue by CoffeeAddictGuy** [ggerganov/llama.cpp#144]
On Windows 10 I run the command
```
G:/LLaMa/llama.cpp/Debug/llama.exe -m G:/LLaMa/llama.cpp/models/7B/ggml-model-q4_0.bin -t 8 -n 256 --repeat_penalty 1.0 --color -i -r "User:" -p "Transcript of a dialog, where the User interacts with an Assistant named Bob. Bob is helpful, kind, honest, good at writing, and never fails to answer the User's requests immediately and with precision.

User: Hello, Bob.
Bob: Hello. How may I help you today? 
User: Please tell me the largest city in Europe.
Bob: Sure. The largest city in Europe is Moscow, the capital of Russia.
User:"
```
, it works out, but then the AI continues to simulate the dialogue, not giving me access
Nothing happens when you try to press Enter
Maybe I'm doing something wrong? 
![image](https://user-images.githubusercontent.com/31831491/225138823-e03443ba-bd59-4ede-a0da-d0510c3263eb.png)

**Comment by Alumniminium** [comment]
You're not supposed to include

```
User: Hello, Bob.
Bob: Hello. How may I help you today? 
User: Please tell me the largest city in Europe.
Bob: Sure. The largest city in Europe is Moscow, the capital of Russia.
User:
```
in the command. 


`G:/LLaMa/llama.cpp/Debug/llama.exe -m G:/LLaMa/llama.cpp/models/7B/ggml-model-q4_0.bin -t 8 -n 256 --repeat_penalty 1.0 --color -i -r "User:" -p "Transcript of a dialog, where the User interacts with an Assistant named Bob. Bob is helpful, kind, honest, good at writing, and never fails to answer the User's requests immediately and with precision."`

this should do.

**Comment by nschulzke** [comment]
No, you're definitely supposed to be able to include the first few turns in the command, but it looks like PowerShell does weird things with the line breaks in strings.

@CoffeeAddictGuy, the example you copied in and adapted is intended to run in bash or zsh, which both automatically treat all strings as multiline. It looks like PowerShell eliminates newlines inside of regular strings, so I suspect you'll need to [use a Here-String instead](https://devblogs.microsoft.com/scripting/powertip-use-here-strings-with-powershell/).

**Comment by CoffeeAddictGuy** [comment]
@nschulzke Thank you, Here-String really helped)
