### ISSUE TITLE
 starcoder - not working

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#1440]
NOn the Roadmap May 2023 is see 

I tried to run  starcoder
https://huggingface.co/nouamanetazi/starcoder-ggml/tree/main

But getting error 

main: build = 545 (bda4d7c)
main: seed  = 1684021875
llama.cpp: loading model from models/starcoder-13b-q4_1.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/starcoder-13b-q4_1.bin'
main: error: unable to load model

Is that means is not implemented into llama.cpp yet ?

**Comment by BetaDoggo** [comment]
The mention on the roadmap was related to [support in the ggml library](https://github.com/ggerganov/ggml/tree/master/examples/starcoder) itself, llama.cpp still only supports llama models.
