### ISSUE TITLE
HuggingFaceH4/starchat-alpha CPP LLM

### ISSUE THREAD

**Issue by ekolawole** [ggerganov/llama.cpp#1441]
What we need is a local cpp for llm "HuggingFaceH4/starchat-alpha A". It  is much better than any other open source chat models at coding. And it does very well at chatting too. This is better than Vicuna.

**Comment by chat-guy** [comment]
This would be great. It is indeed significantly better than Vicuna as far as code-generation is concerned.

**Comment by s-kostyaev** [comment]
Looks like we need to integrate https://github.com/ggerganov/ggml/tree/master/examples/starcoder into `llama.cpp`
