### ISSUE TITLE
CUDA acceleration doesn't seem to work

### ISSUE THREAD

**Issue by megupta** [ggerganov/llama.cpp#1445]
I compiled the latest code in this repo with cuBLAS support as described in the README

It doesn't seem to be utilizing my 1070 although main is running in nvidia-smi
```
llama_model_load_internal: [cublas] offloading 0 layers to GPU
llama_model_load_internal: [cublas] total VRAM used: 0 MB
```

What am I missing here?

**Comment by FSSRepo** [comment]
Add the option -ngl 10, for upload 10 layers to your gpu memory
