### ISSUE TITLE
Can't compile on Jetson Orin NX with "LLAMA_CUBLAS=1"

### ISSUE THREAD

**Issue by dnhkng** [ggerganov/llama.cpp#1455]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
Compiling on the the Jetson Orin works as expected, but with the "LLAMA_CUBLAS=1" flags, I get errors.

# Current Behavior
Compilation fails with 2 errors:
```
/usr/local/cuda/include/crt/sm_80_rt.hpp(141): error: more than one instance of overloaded function "__nv_associate_access_property_impl" has "C" linkage

ggml.h(217): error: identifier "__fp16" is undefined

2 errors detected in the compilation of "ggml-cuda.cu".
make: *** [Makefile:133: ggml-cuda.o] Error 1
```

# Environment and Context

Fresh install of Jetpack on a fresh Ubuntu installation, on a Jetson Orin NX 16Gb.

```
$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-3
Off-line CPU(s) list:            4-7
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           1
Model name:                      ARMv8 Processor rev 1 (v8l)
Stepping:                        r0p1
CPU max MHz:                     1984,0000
CPU min MHz:                     115,2000
BogoMIPS:                        62.50
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        1 MiB
L3 cache:                        2 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dc
                                 pop asimddp uscat ilrcpc flagm
```

* Operating System, e.g. for Linux:
```
$ uname -a
Linux orin-desktop 5.10.104-tegra #1 SMP PREEMPT Tue Jan 24 15:09:44 PST 2023 aarch64 aarch64 aarch64 GNU/Linux
```

* SDK version, e.g. for Linux:

$ python3 --version
Python 3.10.10

$ make --version
GNU Make 4.2.1

$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

$ nvcc -V
Built on Wed_Jun__8_16:59:16_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. step 1
2. step 2
3. step 3
4. etc.

# Failure Logs

```
$ make LLAMA_CUBLAS=1
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  aarch64
I UNAME_M:  aarch64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include
I LDFLAGS:   -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L/usr/local/cuda/lib64 -L/opt/cuda/lib64 -L/targets/x86_64-linux/lib
I CC:       cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
I CXX:      g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include   -c ggml.c -o ggml.o
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -c llama.cpp -o llama.o
llama.cpp: In function ‘size_t llama_set_state_data(llama_context*, const uint8_t*)’:
llama.cpp:2686:36: warning: cast from type ‘const uint8_t*’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers [-Wcast-qual]
 2686 |             kin3d->data = (void *) inp;
      |                                    ^~~
llama.cpp:2690:36: warning: cast from type ‘const uint8_t*’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers [-Wcast-qual]
 2690 |             vin3d->data = (void *) inp;
      |                                    ^~~
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -c examples/common.cpp -o common.o
nvcc --forward-unknown-to-host-compiler -arch=native -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -Wno-pedantic -c ggml-cuda.cu -o ggml-cuda.o
/usr/local/cuda/include/crt/sm_80_rt.hpp(141): error: more than one instance of overloaded function "__nv_associate_access_property_impl" has "C" linkage

ggml.h(217): error: identifier "__fp16" is undefined

2 errors detected in the compilation of "ggml-cuda.cu".
make: *** [Makefile:133: ggml-cuda.o] Error 1
```

**Comment by hungerf3** [comment]
I've got an Orin NX, so I'll take a look.

Are you running the default packages that shipped with the Jetson image, or have you upgraded any packages (like the CUDA libraries)?  Do you have Jetpack installed?

**Comment by hungerf3** [comment]
It looks like you might have upgraded the CUDA libraries from the default 11.4 version to 11.7 ; try using the 11.4 version. I don't think the 11.7 package supports the Orin modules yet. I had issues using it for some other applications and ended up rolling back to 11.4.

**Comment by d0rc** [comment]
Can my version of CUDA (release 11.6, V11.6.124) explain these errors on Linux?

```
/root/llama.cpp/ggml.c: In function 'bytes_from_nibbles_32':
/root/llama.cpp/ggml.c:534:27: warning: implicit declaration of function '_mm256_set_m128i'; did you mean '_mm256_set_epi8'? [-Wimplicit-function-declaration]
     const __m256i bytes = _mm256_set_m128i(_mm_srli_epi16(tmp, 4), tmp);
                           ^~~~~~~~~~~~~~~~
                           _mm256_set_epi8
/root/llama.cpp/ggml.c:534:27: error: incompatible types when initializing type '__m256i {aka const __vector(4) long long int}' using type 'int'
CMakeFiles/ggml.dir/build.make:75: recipe for target 'CMakeFiles/ggml.dir/ggml.c.o' failed
```

**Comment by hungerf3** [comment]
It built fine for me, with some minor tweaks, and I see it using the GPU when it's running.

I had to adjust the following things:

* The Makefile has x86_64-linux paths hardcoded for the CUDA include files; swap in aarch64-linux instead.
* One of the ARM Neon optimizations uses a type that the CUDA compiler doesn't recognize.
* nvcc on the Orin doesn't like the arch=native or -fPIC options

Try applying this diff and see if it works for you.
[orin.patch](https://github.com/ggerganov/llama.cpp/files/11474122/orin.patch)

**Comment by dnhkng** [comment]
Thanks for the great advise! 🥇 

I was in a conda environment that had been bumped CUDA to 11.7;  deactivating conda and using your patch got the compilation to work 👍 

Did you test the output? I'm getting gibberish from a freshly generated ggml-model-q4_0.bin and ggml-model-q8_0.bin, both on the CPU and GPU.

What is a little weird is that quantised model I create on my Desktop machine (Ryzen+4090) work, but on the Jetson produce gibberish like this at inference:
```
fortunately noreferrer▲ MasterinlineBFGNify devantlärchartsicaleness▶ gyreload Erroruers poorquipeiko 
Хронологија Method Ofadratста Chanspan Ricozeichnispacesempio↵ ArrayeteorEng downright,
```

But if I quantise on the Jetson, the model generates this kind of mess, and never words:

```
 ⁇ #

 ⁇ ############################
```


Finally, with Q4.0, on GPU I get about 652,02 ms per token, and I can see its using the GPU, and only on CPU I get 560,25 ms per token, so GPU slow me down about 16%!

**Comment by KyL0N** [comment]
I think what I'm done fix it. :D
`nvcc` dose not recognise ARM NEON's `__fp16`, so I add a `__CUDACC__` macro in order to define `half` to be `ggml_fp16_t` rather than `__fp16` . They're same with FP16.
![image](https://github.com/ggerganov/llama.cpp/assets/56434533/e4e81dab-f298-402c-b57d-27bb05468cd2)
### git diff ggml.h:
```
diff --git a/ggml.h b/ggml.h
index 255541d..368ac2e 100644
--- a/ggml.h
+++ b/ggml.h
@@ -212,9 +212,11 @@
 extern "C" {
 #endif
 
-#ifdef __ARM_NEON
+#if defined(__ARM_NEON) && !defined(__CUDACC__)
     // we use the built-in 16-bit float type
     typedef __fp16 ggml_fp16_t;
+#elif defined(__ARM_NEON) && defined(__CUDACC__)
+    typedef half ggml_fp16_t;
 #else
     typedef uint16_t ggml_fp16_t;
 #endif
```
<details><summary>Makefile log for me</summary>
![image](https://github.com/ggerganov/llama.cpp/assets/56434533/d44236f3-3dde-4771-b77b-6e0fe03ad1b6)
</details>

**Comment by javadan** [comment]
out of interest, how is the llama.cpp performance on the jetson orin nx?

**Comment by dnhkng** [comment]
On a Jetson Orin NX 16Gb: Not great. About the same inference time per token on both the CUDA core or CPU, and the CPU is not great!

**Comment by samuelkoes** [comment]
> I think what I'm done fix it. :D `nvcc` dose not recognise ARM NEON's `__fp16`, so I add a `__CUDACC__` macro in order to define `half` to be `ggml_fp16_t` rather than `__fp16` . They're same with FP16. ![image](https://user-images.githubusercontent.com/56434533/239672773-e4e81dab-f298-402c-b57d-27bb05468cd2.png)
> 
> ### git diff ggml.h:
> ```
> diff --git a/ggml.h b/ggml.h
> index 255541d..368ac2e 100644
> --- a/ggml.h
> +++ b/ggml.h
> @@ -212,9 +212,11 @@
>  extern "C" {
>  #endif
>  
> -#ifdef __ARM_NEON
> +#if defined(__ARM_NEON) && !defined(__CUDACC__)
>      // we use the built-in 16-bit float type
>      typedef __fp16 ggml_fp16_t;
> +#elif defined(__ARM_NEON) && defined(__CUDACC__)
> +    typedef half ggml_fp16_t;
>  #else
>      typedef uint16_t ggml_fp16_t;
>  #endif
> ```
> 
> Makefile log for me

Could we merge this patch to the main branch?

**Comment by KyL0N** [comment]
> > I think what I'm done fix it. :D `nvcc` dose not recognise ARM NEON's `__fp16`, so I add a `__CUDACC__` macro in order to define `half` to be `ggml_fp16_t` rather than `__fp16` . They're same with FP16. ![image](https://user-images.githubusercontent.com/56434533/239672773-e4e81dab-f298-402c-b57d-27bb05468cd2.png)
> > 
> > ### git diff ggml.h:
> > ```
> > diff --git a/ggml.h b/ggml.h
> > index 255541d..368ac2e 100644
> > --- a/ggml.h
> > +++ b/ggml.h
> > @@ -212,9 +212,11 @@
> >  extern "C" {
> >  #endif
> >  
> > -#ifdef __ARM_NEON
> > +#if defined(__ARM_NEON) && !defined(__CUDACC__)
> >      // we use the built-in 16-bit float type
> >      typedef __fp16 ggml_fp16_t;
> > +#elif defined(__ARM_NEON) && defined(__CUDACC__)
> > +    typedef half ggml_fp16_t;
> >  #else
> >      typedef uint16_t ggml_fp16_t;
> >  #endif
> > ```
> > 
> > Makefile log for me
> 
> Could we merge this patch to the main branch?

sure, I will create a pull request later
