### ISSUE TITLE
mac M1: very low memory usage on 7B but 10x higher on 13B

### ISSUE THREAD

**Issue by DKormann** [ggerganov/llama.cpp#1465]
running 4bit quantized models on M1 with 8gb RAM. When I run the 7B model i see a memory usage of only up to 300 Mb although it says its gonna use ~6gb. But for 13B it uses a lot more (as expected). Why is using 7B so little memory what am I not understanding?

file size for 13B is twice as big as 7B as expected at around 8Gb

**Comment by SlyEcho** [comment]
It is probably mapped to memory from the SSD. Try using `--mlock`, it works well on macOS, or `--no-mmap` to load directly to RAM but it will probably cause the OS to start swapping.
