### ISSUE TITLE
Add a webui to this

### ISSUE THREAD

**Issue by suoko** [ggerganov/llama.cpp#1479]
This repo was the only way I find to successfully run a vicuna model (ggml-vic13b-uncensored-q8_0.bin) but I miss a web ui.
Can you suggest how to add one ?
How can I make text-generation-webui use this llama.cpp ?

**Comment by akx** [comment]
[oobabooga/text-generation-webui already has support for llama.cpp](https://github.com/oobabooga/text-generation-webui#llamacpp) – if you have trouble making it work with this repo, you should probably ask there.

**Comment by evanmiller** [comment]
See the new code in [examples/server](https://github.com/ggerganov/llama.cpp/tree/master/examples/server) – web UI included!

**Comment by rain-1** [comment]
That's great that a Chat UI was added. Please add a Text Continuation UI also.

**Comment by rain-1** [comment]
Related

* https://github.com/ggerganov/llama.cpp/pull/1998
* https://github.com/ggerganov/llama.cpp/pull/1424

**Comment by Green-Sky** [comment]
closing as completed.
