### ISSUE TITLE
[Feature request] Add a way to pipe text into a running session

### ISSUE THREAD

**Issue by skidd-level-100** [ggerganov/llama.cpp#1489]
I would love a way to inject information into a running session, like detect a string that says "<search>QUERY</search>" and pass it into a script that runs a search on 'QUERY' and dumps the search output into the running session, basically I want to easily inject arbitrary text into a give session. this would allow me to have a set of instructions teaching the AI how to use various tools that I set up I can already see out put by piping ./main into the tail command but I cannot inject input from a different script.

**Comment by misutoneko** [comment]
Nice idea! Did you find a way to do it? (GUIs or something?)
I guess for one-shot queries it's possible to use shell wrappers, but it's a bit awkward.

I'm pretty bad at C++ but here's some VERY rudimentary code to try this out.

[llamacmd_test.diff.gz](https://github.com/ggerganov/llama.cpp/files/13781968/llamacmd_test.diff.gz)

To use it, create the script llamacmd.sh and add QUERY("param1 param2") to your input.
