### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 717778556, available 454395136)

### ISSUE THREAD

**Issue by YongeBai** [ggerganov/llama.cpp#153]
Hey, I know someone already posted a similar issue that has already been closed, but I ran into the same thing. On windows 10 and cloned just yesterday

**Comment by wafflecomposite** [comment]
Constantly hitting it with `-c 2048 -n 2048`
As of now, https://github.com/ggerganov/llama.cpp/pull/438 actually gets it fixed.
