### ISSUE TITLE
I updated and it crashes with an error

### ISSUE THREAD

**Issue by intulint** [ggerganov/llama.cpp#1538]
Updated today and does not start. The build will run without errors. I used to make.
Ubuntu 22.04 

main: build = 574 (ea60007)
main: seed  = 1684581738
llama.cpp: loading model from ../Wizard-Vicuna-7B-Uncensored.ggmlv2.q4_1.bin
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by intulint** [comment]
2d5db48 this is the commit that stopped working

**Comment by SlyEcho** [comment]
You need to quantize your model again from F16. the Q4_0, Q4_1 and Q8_0 formats changed.

**Comment by intulint** [comment]
@SlyEcho again? I'll have to stay on the working version for now. I understand

**Comment by SlyEcho** [comment]
https://github.com/ggerganov/llama.cpp/pull/1508 is the change. There really should be an error message.
