### ISSUE TITLE
Model not loading - nothing happens

### ISSUE THREAD

**Issue by AlphaCapella** [ggerganov/llama.cpp#1543]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Trying to get llama.cpp to run on windows 10

# Current Behavior

Generally everything seems to work, but the model does not load. After it tries to load the model, it just exits after a few seconds and that is it. No error, message, nothing. RAM gets loaded for a few seconds, same with CPU and GPU.
I have tried every binary available, always with the same outcome. Also the two models I have tried are: [ggml-vicuna-7b-1.1](https://huggingface.co/eachadea/ggml-vicuna-7b-1.1) and [ggml-vicuna-13b-1.1](https://huggingface.co/eachadea/ggml-vicuna-13b-1.1)

If I try for example ".\main.exe --help" the output is correct. So it seems to work in principle, also my GPU gets detected if the binary is with clblast.
Below I attached the console input and output. I am really out of words. Hours of googling did not seem to yield anything, because there is apparently nobody with that problem.
![grafik](https://github.com/ggerganov/llama.cpp/assets/102863031/aa3742b4-b6ee-486b-abfe-99087cfcef23)

# Environment and Context

- 32 GB of RAM
- AMD Ryzen 9 5950x
- Nvidia RTX 3090

**Comment by SlyEcho** [comment]
The file format has changed for Q4_0, Q4_1 and Q8_0. The files on that repo are too old.

What you're seeing is the program silently crashing. True, that's not something desirable, maybe an issue on its own.

Q5_0 and Q5_1 models should still work as before.

It was changed here: https://github.com/ggerganov/llama.cpp/pull/1508

**Comment by AlphaCapella** [comment]
Interesting, I was using the model "[ggml-vic7b-uncensored-q4_0.bin](https://huggingface.co/eachadea/ggml-vicuna-7b-1.1/blob/main/ggml-vic7b-uncensored-q4_0.bin)", which has been updated for the new quantization. Apparently not correctly, because after what you said I tried the q5 version and it works like a charm. Happenend with the 7b and 13b model.

Anyways, thank you for your help.

**Comment by SlyEcho** [comment]
Yeah, it was updated, but then the format changed again :)

**Comment by VioletFlare** [comment]
I just checked out an older version that dates back to september 11 so that i can use older GGML models :)
