### ISSUE TITLE
OpenCL can select discrete GPU by default?

### ISSUE THREAD

**Issue by DickyQi** [ggerganov/llama.cpp#1546]
I have Old MacBook Pro with one intel GPU and one AMD discrete GPU. I am using OpenCL ggml, and ggml default choose Intel GPU. I hope ggml can using discrete GPU by default, or we can set GPU device though API?

**Comment by SlyEcho** [comment]
It is possible to select the OpenCL device with an environment variable:

```sh
export GGML_OPENCL_DEVICE=1
./main ....
```

You can use numbers 0, 1, 2 ... or you can use string matching, like `GGML_OPENCL_DEVICE=AMD` but what strings to use depends on what info the OpenCL platforms give. You can use the `clinfo` command to see what is there.

**Comment by SlyEcho** [comment]
Actually, I need to write the documentation for this part. It doesn't seem to be anywhere.

**Comment by Jp1337** [comment]
> Actually, I need to write the documentation for this part. It doesn't seem to be anywhere.

Is there a way to do this for cuda devices? I have no idea how to tell it to use my other gpu

**Comment by SlyEcho** [comment]
> Is there a way to do this for cuda devices? I have no idea how to tell it to use my other gpu

- CUDA: [`CUDA_VISIBLE_DEVICES`](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars)
- HIP: [`HIP_VISIBLE_DEVICES`](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars) with #1087

You just list the devices that are visible to the application:
```sh
CUDA_VISIBLE_DEVICES=1 ./main ...
```

**Comment by SlyEcho** [comment]
README now should have info about GPU selection for CUDA and OpenCL.
