### ISSUE TITLE
[ISSUE] --gpu-layers in useless.

### ISSUE THREAD

**Issue by skidd-level-100** [ggerganov/llama.cpp#1555]
I am on linux with an nvidia card using CLBLAST (CUBLAST hates me) and --gpu-layers (any number) is no faster than without it,
I checked the nvidia-smi ouput and it is showing me only 80mib vram used (same as without -ngl) 

pls help

**Comment by battlecity19** [comment]
have you tried using --mlock and/or --no-mmap?

**Comment by Green-Sky** [comment]
Please use the cuda/cublas variant over the OpenCL one. It is always better on nvidia hardware.

**Comment by JohannesGaessler** [comment]
The PR for OpenCL GPU acceleration https://github.com/ggerganov/llama.cpp/pull/1459 hasn't been merged yet so setting --n-gpu-layers with `LLAMA_CLBLAST` does nothing.

**Comment by KerfuffleV2** [comment]
Would it be a good idea to have `--n-gpu-layers` fail if stuff isn't compiled in a way that enables actually putting layers on the GPU? Could probably just add some `#ifdef`s around the commandline option unless there's actually a reason to allow the user to use the argument even when there's no effect.

**Comment by JohannesGaessler** [comment]
I opened a PR that adds documentation and an error upon trying to use --n-gpu-layers without an implementation. I'll revisit it once my other PR for optimization options gets merged.
