### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by apcameron** [ggerganov/llama.cpp#1569]
./main -m ./models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512
main: build = 584 (2e6cd4b)
main: seed  = 1684832847
ggml_opencl: selecting platform: 'PowerVR'
ggml_opencl: selecting device: 'PowerVR B-Series BXE-4-32'
ggml_opencl: device FP16 support: true
llama.cpp: loading model from ./models/7B/ggml-model-q4_0.bin
terminate called after throwing an instance of 'std::runtime_error'
  what():  unexpectedly reached end of file
Aborted (core dumped)

**Comment by apcameron** [comment]
./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0
After running the command above it seems to work again

**Comment by mgroeber9110** [comment]
This may be the same error as #1589: `std::runtime_error` is currently not caught in all places of the code, because exceptions are a mix of `std::string` and `std::exception` derived types.

**Comment by ibndias** [comment]
> ./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0 After running the command above it seems to work again

this solved my issue
