### ISSUE TITLE
Compiling using CLBlast on Windows undefined reference

### ISSUE THREAD

**Issue by jan-tennert** [ggerganov/llama.cpp#1573]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I was trying to compile **llama.cpp** with CLBlast support (``make LLAMA_CLBLAST=1``). I followed the README's guide for windows and compiling without the clblast option works completely fine. For OpenCL I used [this](https://github.com/KhronosGroup/OpenCL-SDK) SDK and [this](https://github.com/CNugteren/CLBlast/releases) for CLBlast. All headers and libs for both sdk's are in `w64devkit's` directory.

# Current Behavior

It failed to compile with the error from below.

# Environment and Context

OS: Windows 11 Pro
GPU: RX 5500 XT

# Failure Information (for bugs)

```batch
H:/SD/make/w64devkit/bin/ld.exe: ggml-opencl.o:ggml-opencl.cp:(.text+0x952): undefined reference to `clblast::StatusCode clblast::Gemm<float>(clblast::Layout, clblast::Transpose, clblast::Transpose, unsigned long long, unsigned long long, unsigned long long, float, _cl_mem*, unsigned long long, unsigned long long, _cl_mem*, unsigned long long, unsigned long long, float, _cl_mem*, unsigned long long, unsigned long long, _cl_command_queue**, _cl_event**, _cl_mem*)'
H:/SD/make/w64devkit/bin/ld.exe: ggml-opencl.o:ggml-opencl.cp:(.text+0x1a03): undefined reference to `clblast::StatusCode clblast::Gemm<float>(clblast::Layout, clblast::Transpose, clblast::Transpose, unsigned long long, unsigned long long, unsigned long long, float, _cl_mem*, unsigned long long, unsigned long long, _cl_mem*, unsigned long long, unsigned long long, float, _cl_mem*, unsigned long long, unsigned long long, _cl_command_queue**, _cl_event**, _cl_mem*)'
H:/SD/make/w64devkit/bin/ld.exe: ggml-opencl.o:ggml-opencl.cp:(.text+0x20a0): undefined reference to `clblast::StatusCode clblast::Gemm<unsigned short>(clblast::Layout, clblast::Transpose, clblast::Transpose, unsigned long long, unsigned long long, unsigned long long, unsigned short, _cl_mem*, unsigned long long, unsigned long long, _cl_mem*, unsigned long long, unsigned long long, unsigned short, _cl_mem*, unsigned long long, unsigned long long, _cl_command_queue**, _cl_event**, _cl_mem*)'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:210: main] Error 1
```

**Comment by LostRuins** [comment]
I have experienced the same issue, logged as https://github.com/CNugteren/CLBlast/issues/467 

I believe it is a flaw in the prebuilt libraries.

You may consider doing what I do, which is wrapping the SGEMM C style functions for use in C++. Note that the C++  GEMM function is polymorphic, so make sure you use the correct one.

**Comment by jan-tennert** [comment]
> I have experienced the same issue, logged as [CNugteren/CLBlast#467](https://github.com/CNugteren/CLBlast/issues/467)
> 
> I believe it is a flaw in the prebuilt libraries.
> 
> You may consider doing what I do, which is wrapping the SGEMM C style functions for use in C++. Note that the C++ GEMM function is polymorphic, so make sure you use the correct one.

I'm sorry, not that familiar with C/C++. Would you mind sharing the changes you did? Thanks :)

**Comment by LostRuins** [comment]
You may refer to my fork.

https://github.com/LostRuins/koboldcpp/blob/concedo/ggml-opencl.cpp#L702

**Comment by jan-tennert** [comment]
Thank you very much, that works perfectly!

**Comment by LostRuins** [comment]
You're welcome. Hopefully they'll fix this at the library level so such hacks aren't needed since they do make it more error prone.

**Comment by mikeyang01** [comment]
> You may refer to my fork.
> 
> https://github.com/LostRuins/koboldcpp/blob/concedo/ggml-opencl.cpp#L702

Your project works, thanks, BTW, what is the difference between your code and llama.cpp?

**Comment by LostRuins** [comment]
I don't use the polymorphic GEMM functions, instead directly calling the appropriate C functions.

**Comment by mikeyang01** [comment]
> I don't use the polymorphic GEMM functions, instead directly calling the appropriate C functions.

Thanks for the reply, so how to modify the code in llamacpp to fix this isssue?

```
C:/w64devkit/bin/ld.exe: ggml-opencl.o:ggml-opencl.cp:(.text+0x5b38): undefined reference to `clblast::StatusCode clblast::Gemm<unsigned short>(clblast::Layout, clblast::Transpose, clblast::Transpose, unsigned long long, unsigned long long, unsigned long long, unsigned short, _cl_mem*, unsigned long long, unsigned long long, _cl_mem*, unsigned long long, unsigned long long, unsigned short, _cl_mem*, unsigned long long, unsigned long long, _cl_command_queue**, _cl_event**, _cl_mem*)'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:282: main] Error 1
```

**Comment by LostRuins** [comment]
refer to my fork: https://github.com/LostRuins/koboldcpp/blob/concedo/ggml-opencl.cpp#L1742

you need to replace all calls to clblast::Gemm with the correct Sgemm or Hgemm functions.
