### ISSUE TITLE
is it possible to use llama,cpp with other neural networks?

### ISSUE THREAD

**Issue by dbpaul** [ggerganov/llama.cpp#158]
I have no clue about this, but I saw that chatglm-6b was published, which should run on CPU with 16GB ram, albeit very slow.
[https://huggingface.co/THUDM/chatglm-6b/tree/main](url)

Would it be possible to substitute the llama model?

**Comment by v3ss0n** [comment]
if you are going to write the code  in c base on ggml , yes.

**Comment by Ayushk4** [comment]
So far 10 different models are supported across 5 different architectures (including OpenAssistant and Open-Chat-Kit models) are supported by [nolanoorg/cformers](https://github.com/ggerganov/llama.cpp/issues/github.com/nolanoorg/cformers).

You can now interface with the models with just 3 lines of code from python.
```
from interface import AutoInference as AI
ai = AI('OpenAssistant/oasst-sft-1-pythia-12b')
x = ai.generate("<|prompter|>What's the Earth total population<|endoftext|><|assistant|>", num_tokens_to_generate=100); print(x['token_str'])
```
