### ISSUE TITLE
MinGW: clblast "variable length arrays are not supported", unicode issues in common.c

### ISSUE THREAD

**Issue by asctime** [ggerganov/llama.cpp#1581]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

Sorry I am not sure how much of what I have to ask fits into your template. First, thank you for this project many people are extremely excited about it, and several from the mingw community are looking at this I think (mingw is just gcc/clang compiler on windows). So to my issue.
Essentially, I compiled llama.cpp #5ea4339 Windows (MinGW64 gcc)  OpenCL headers 20200327 with clinfo:
Number of platforms                               2
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 3.0 CUDA 11.6.134
...
Get a crash in main.exe:
Initializing CLBlast (First Run)...
Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
Using Platform: NVIDIA CUDA Device: NVIDIA GeForce GTX 1650 Ti
<kernel>:1:133: error: variable length arrays are not supported in OpenCL

I was hoping an experienced user could help me understand what "variable length arrays are not supported in OpenCL" implies concerning a mingw-llama. Is it something that could be theoretically patched around?

Also, I thought it was worth mentioning while I have anyone's ear that I am working on a mingw patch. It's mainly focused on the projects existing/conflicting use of ascii/unicode (wchar) on windows in the examples. I am sure it all compiles on msvcrt to mix unicode and ascii, but gcc has a coniption. Basically in mingw to support unicode wide-characters you need to compile with -DUNICODE and link with -municode and have a main called wmain. Everything has to be completely consistent.  I understand that most devs don't anticipate gcc on windows but it's actually [a thing](https://gitlab.com/wireshark/wireshark/-/issues/17771) now and growing. I am still testing my patches, just thought I should point it out..

**Comment by asctime** [comment]
Sorry? https://learn.microsoft.com/en-us/cpp/c-runtime-library/unicode-the-wide-character-set?view=msvc-170

**Comment by asctime** [comment]
I had a couple more hours free this week so I tested the latest commit as opposed to the latest release, as suggested. I can report from my experience that the OpenCL support now seems to work correctly, at least in the basic sense appropriate to this issue. I realize that the console issue is completely separate and will re-open once I have a reasonable patch to propose. Thank you. Good to close from my side.

**Comment by SlyEcho** [comment]
OpenCL is going to have more updates, you can test them as well: https://github.com/ggerganov/llama.cpp/pull/1653

**Comment by asctime** [comment]
Great!! Thank you I will do my best.

**Comment by asctime** [comment]
Sorry I had another project to finish.
https://github.com/ggerganov/llama.cpp/pull/1897/commits/5dc35d3b59b8d76a7438036166c786a1b1675b3f

I'll get to the rest now..
