### ISSUE TITLE
Does this support safetensors files?

### ISSUE THREAD

**Issue by guranu** [ggerganov/llama.cpp#1586]
Hello, so i want to install wizardlm 7b uncensored but the model is a safetensors file so i was wondering does this support .safetensors files?

**Comment by EliEron** [comment]
No not directly. Safetensor files are usually given for GPTQ models which are models designed to run on [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) or [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ), not on llama.cpp. 

For llama.cpp you want GGML files, practically all models that are offered in GPTQ form is also offered in GGML somewhere else. For WizardLM-7B Uncensored you can find GGML files [here](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/tree/main). You only need one of the files. The lower the Q after the file name the less accurate they are but the less resources they need. So Q4_0 is the easiest to run and Q8_0 the hardest.

**Comment by CRD716** [comment]
Yes, it does. You need to run the convert.py script on the files to turn it into a valid ggml.

**Comment by guranu** [comment]
> No not directly. Safetensor files are usually given for GPTQ models which are models designed to run on [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) or [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ), not on llama.cpp.
> 
> For llama.cpp you want GGML files, practically all models that are offered in GPTQ form is also offered in GGML somewhere else. For WizardLM-7B Uncensored you can find GGML files [here](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/tree/main). You only need one of the files. The lower the Q after the file name the less accurate they are but the less resources they need. So Q4_0 is the easiest to run and Q8_0 the hardest.

Ok so i downloaded the model i put it into the models folder and i can't use it (by that i mean i can't type anything into it) because i don't have a txt file for prompt that makes wizardlm work does anyone have a working prompt for wizardlm uncensored?

**Comment by guranu** [comment]
I can't launch it the command thats used in the huuging face dosen't launch it for me.
