### ISSUE TITLE
Reading model error std::runtime_error: unexpectedly reached end of file

### ISSUE THREAD

**Issue by dmeleedy** [ggerganov/llama.cpp#1596]
Davids-M1-Max-1020 : ./main --model ../llama_files/models/ggml-vic13b-uncensored-q8_0.bin
main: build = 590 (66874d4)
main: seed  = 1685068791
llama.cpp: loading model from ../llama_files/models/ggml-vic13b-uncensored-q8_0.bin
libc++abi: terminating due to uncaught exception of type std::runtime_error: unexpectedly reached end of file
zsh: abort      ./main --model ../llama_files/models/ggml-vic13b-uncensored-q8_0.bin

To download the model:
https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main
This model file was working on build  = 552 (b5c9295)

I am using git pull origin master
Davids-M1-Max-1021 : uname -a
Darwin Davids-M1-Max 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
Davids-M1-Max-1024 : python3 --version
Python 3.10.9
Davids-M1-Max-1025 : make --version
GNU Make 3.81
Copyright (C)
Davids-M1-Max-1026 : g++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by dmeleedy** [comment]
ah never mind I just found out about this
https://github.com/ggerganov/llama.cpp/pull/1508

**Comment by JACKHAHA363** [comment]
Did you manage to solve this? Or just something waiting to be resolved?

**Comment by DMMeleedy** [comment]
> Did you manage to solve this? Or just something waiting to be resolved?

The author of the ggml-vic13b-uncensored-q8_0.bin model is aware of the issue and is working on a fix.
