### ISSUE TITLE
Add avx-512 support?

### ISSUE THREAD

**Issue by FNsi** [ggerganov/llama.cpp#160]
No clue but I think it may work faster

**Comment by congdm** [comment]
> No clue but I think it may work faster
On i7-11700F, when I built with AVX512 flags in VS2022, my speed increased from ~0.37 token/s to ~0.34 token/s. Don't know if it was placebo or not. Maybe a proper assembly inline code will be better

**Comment by FNsi** [comment]
> > No clue but I think it may work faster
> 
> 
> 
> On i7-11700F, when I built with AVX512 flags in VS2022, my speed increased from ~0.37 token/s to ~0.34 token/s. Don't know if it was placebo or not. Maybe a proper assembly inline code will be better
> 
> 
> How a single flag can make 10% boost? Seems great!

**Comment by congdm** [comment]
> How a single flag can make 10% boost? Seems great!

It's actually placebo :) Now I'm testing again, they're both running at the same speed

**Comment by FNsi** [comment]
> > How a single flag can make 10% boost? Seems great!
> 
> 
> 
> It's actually placebo :) Now I'm testing again, they're both running at the same speed
> 
> 
> 
> 

😂hahah, that make more sense

**Comment by RazeLighter777** [comment]
This would require code changes, not just compiler flags.

**Comment by dzid26** [comment]
Interesting https://stackoverflow.com/questions/63484266/enabling-avx512-support-on-compilation-significantly-decreases-performance
