### ISSUE TITLE
Is guanaco supported?

### ISSUE THREAD

**Issue by guranu** [ggerganov/llama.cpp#1627]
So recently guanaco was released this model uses the new QLORA quantization method. I was wondering if it is supported? here's the url to the ggml versions of the models: https://huggingface.co/TheBloke/guanaco-7B-GGML

https://huggingface.co/TheBloke/guanaco-13B-GGML

https://huggingface.co/TheBloke/guanaco-33B-GGML

https://huggingface.co/TheBloke/guanaco-65B-GGML

**Comment by KerfuffleV2** [comment]
It's against the rules to link to LLaMA based models due to the license, but yes, those will work fine (see the main repo README). As far as I know, the only GGML models published by TheBloke that won't work are the MPT ones like storywriter.
