### ISSUE TITLE
shows Killed when using ggml-model-q4_0.bin

### ISSUE THREAD

**Issue by JerryYao80** [ggerganov/llama.cpp#1637]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [√] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [√] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [√] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [√] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I just wanna running ggml-model-q4_0.bin on my Windows 7.

# Environment and Context

> Docker Toolbox 1.13.1
> docker client: 1.13.1 os/arch: windows 7 /amd64
> docker server:19.03.12 os/arch:ubuntu 22.04 /amd64
> CPU type: Intel Core i7 6700 , supported command set: MMX, SSE, SSE2, ......, AVX, AVX2, FMA3, TSX

# Failure Information (for bugs)
when I executed:

> ./main -m /media/ggml-model-q4_0.bin -c 512 -b 1024 -n 256 --keep 48 --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt

Error occurs:

> main: build = 603 (0e730dd)
> main: seed  = 1685353971
> llama.cpp: loading model from /media/ggml-model-q4_0.bin
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 32000
> llama_model_load_internal: n_ctx      = 512
> llama_model_load_internal: n_embd     = 4096
> llama_model_load_internal: n_mult     = 256
> llama_model_load_internal: n_head     = 32
> llama_model_load_internal: n_layer    = 32
> llama_model_load_internal: n_rot      = 128
> llama_model_load_internal: ftype      = 2 (mostly Q4_0)
> llama_model_load_internal: n_ff       = 11008
> llama_model_load_internal: n_parts    = 1
> llama_model_load_internal: model size = 7B
> llama_model_load_internal: ggml ctx size =    0.07 MB
> llama_model_load_internal: mem required  = 5407.71 MB (+ 1026.00 MB per state)
> 
> Killed

# Steps to Reproduce

1 Download and install DockerTools
2 Pull and run Ubuntu image
3 Follow the steps written in README.md, make LLAMA_OPENBLAS=1
4 Generate ggml-model-f16.bin and ggml-model-q4_0.bin
5 Use ggml-model-q4_0.bin

FYI. the memory is sufficient.
Compare to success experiment, the following output should be :

> llama_init_from_file: kv self size  = 1600.00 MB

According code review, I think the error occurs:

>     if (!params.vocab_only) {
>         if (!kv_cache_init(ctx->model.hparams, ctx->model.kv_self, memory_type, ctx->model.hparams.n_ctx)) {
>             fprintf(stderr, "%s: kv_cache_init() failed for self-attention cache\n", __func__);
>             llama_free(ctx);
>             return nullptr;
>         }
> 
>         {
>             const size_t memory_size = ggml_nbytes(ctx->model.kv_self.k) + ggml_nbytes(ctx->model.kv_self.v);
>             fprintf(stderr, "%s: kv self size  = %7.2f MB\n", __func__, memory_size / 1024.0 / 1024.0);
>         }
>     ......
>     }
where kv_cache_init may something wrong happens
 and in kv_cache_init function:

>     cache.ctx = ggml_init(params);
> 
>     if (!cache.ctx) {
>         fprintf(stderr, "%s: failed to allocate memory for kv cache\n", __func__);
>         return false;
>     }

and in ggml_init function:

>     if (is_first_call) {
>         // initialize time system (required on Windows)
>         ggml_time_init();
> 
>         // initialize GELU, SILU and EXP F32 tables
>         {
>             const uint64_t t_start = ggml_time_us(); UNUSED(t_start);
> 
>             ggml_fp16_t ii;
>             for (int i = 0; i < (1 << 16); ++i) {
>                 uint16_t ui = i;
>                 memcpy(&ii, &ui, sizeof(ii));
>                 const float f = table_f32_f16[i] = GGML_COMPUTE_FP16_TO_FP32(ii);
>                 table_gelu_f16[i] = GGML_FP32_TO_FP16(ggml_gelu_f32(f));
>                 table_silu_f16[i] = GGML_FP32_TO_FP16(ggml_silu_f32(f));
>                 table_exp_f16[i]  = GGML_FP32_TO_FP16(expf(f));
>             }
> 
>             const uint64_t t_end = ggml_time_us(); UNUSED(t_end);
> 
>             GGML_PRINT_DEBUG("%s: GELU, SILU and EXP tables initialized in %f ms\n", __func__, (t_end - t_start)/1000.0f);
>         }

SO memcpy function is suspicious, But I don't know why
MY physical memory is 9000M free
Does anyone can help?

**Comment by JerryYao80** [comment]
It's OOM indeed, that's because memory of Ubuntu image if limited to 1024M, When I changed the limitation, problem was solved.

**Comment by msj121** [comment]
@JerryYao80 How do you increase memory to avoid Out of Memory error?

**Comment by Commander-Crash** [comment]
So are you going to explain this or close like a a-hole?

**Comment by Commander-Crash** [comment]
@msj121 I doubt he found a solution.
