### ISSUE TITLE
ggml alpaca model don't work

### ISSUE THREAD

**Issue by seongmin0219** [ggerganov/llama.cpp#1661]
i download alpaca model into local "/models/" folder through this huggingface url 

[https://huggingface.co/Sosaka/Alpaca-native-4bit-ggml]

and run examples/alpaca.sh 

./main -m ./models/ggml-alpaca-7b-q4.bin \
       --color \
       -f ./prompts/alpaca.txt \
       --ctx_size 2048 \
       -n -1 \
       -ins -b 256 \
       --top_k 10000 \
       --temp 0.2 \
       --repeat_penalty 1.1 \
       -t 7 >> "$log_file"

program print this and it's over 

main: build = 607 (ffb06a3)
main: seed  = 1685605906

what should i do?

**Comment by SlyEcho** [comment]
Model file format is too old. The original model is linked in URL that you gave. It can be [converted](https://github.com/ggerganov/llama.cpp#prepare-data--run) by the tools in llama.cpp already (convert.py, quantize)

**Comment by seongmin0219** [comment]
> Model file format is too old. The original model is linked in URL that you gave. It can be [converted](https://github.com/ggerganov/llama.cpp#prepare-data--run) by the tools in llama.cpp already (convert.py, quantize)

thank you! you godsend. i didn't even know origin model in my url 
[https://huggingface.co/chavinlo/alpaca-native](https://huggingface.co/chavinlo/alpaca-native)

i download origin model and convert and quantize successfully


my try write down for other people
i convert and quantize the original model and run, but failed of same error 

`python3 convert.py \models\{origin_huggingface_alpaca_reposity_files}`
print Python. 
it's over

`python convert.py \models\{origin_huggingface_alpaca_reposity_files}`
this work.

and next, 

first time my command was like README.md 
`./main -m .\models\ggml-model-q4_0.bin -n 128`
main: build = 607 (ffb06a3)
main: seed  = 1685667571
it's over. don't work


`./main.exe -m .\models\ggml-model-q4_0.bin -n 128`

now it's truely run
