### ISSUE TITLE
it’s so long a lime to wait while using a server

### ISSUE THREAD

**Issue by niubi-AI** [ggerganov/llama.cpp#1663]

**Comment by dansinboy** [comment]
Any way to run as quickly as using llama.cpp directly? I need to save each input and response

**Comment by jessejohnson** [comment]
@dansinboy are you using the default server binary that comes with llama.cpp or a binding?

**Comment by dansinboy** [comment]
> @dansinboy are you using the default server binary that comes with llama.cpp or a binding?

you get the point , at first I used a binding mode with llama_cpp_python, worked badly. and then change into default server, wow, it works well right now ...
