### ISSUE TITLE
ggml_cl_pool_malloc potential issue

### ISSUE THREAD

**Issue by LostRuins** [ggerganov/llama.cpp#1668]
Mainly asking @SlyEcho and @0cc4m 

While going through the ClBlast code I noticed that `ggml_cl_pool_malloc` does not take into account a buffer's existing flags when reassigning buffers, only during initial allocation. Could this be a problem if it reassigns to a `CL_MEM_READ_ONLY` buffer to a `CL_MEM_WRITE_ONLY` requestor or vice versa. Is this possible? 

Strangely, I have not personally encountered an issue with this, but I'm wondering if it is indeed a potential pitfall.

What's the performance impact of changing the buffers to `CL_MEM_READ_WRITE`?

**Comment by SlyEcho** [comment]
I think most of the bigger buffers are RO, RW is used for reading the results back from the GPU and they are smaller usually (`n_batch * n_embd`).

**Comment by LostRuins** [comment]
Having tested changing them I did not notice any performance loss. Not changing them also does not seem to cause any errors, perhaps on most systems the OS transparently treats all the buffers as RW anyway.
