### ISSUE TITLE
chat-persistent.sh not rotating cache files correctly

### ISSUE THREAD

**Issue by spencekim** [ggerganov/llama.cpp#1670]
On Mac M2, I am running `./examples/chat-persistent.sh` on the latest release: https://github.com/ggerganov/llama.cpp/releases/tag/master-ffb06a3 at the time of writing.

The cache files do not rotate as expected when the context size of 2048 is reached. Instead, the process exits and this error log appears: `llama_load_session_file : token count in session file exceeded capacity! 2089 > 2048`.

On this older commit https://github.com/ggerganov/llama.cpp/releases/tag/master-66874d4 the script works as expected.

Looking at the diff, it seems like the issue might have been introduced in this commit, but I'm not 100% sure: https://github.com/ggerganov/llama.cpp/commit/248367605ead6fb7c36d2bfb1ebd8f00a23f7c71 

cc @ejones @DannyDaemonic

**Comment by ejones** [comment]
Nice find! Quick fix might be to be more conservative in `chat-persistent.sh` about how much it's willing to predict. It's all kind of a hack right now anyway as it's scraping the stderr logs to track token usage. Deeper questions would be, how is the session file allowed to overrun the context size.

**Comment by spencekim** [comment]
Do you think it's an issue with the bash script, or a recent change to main.cpp? As mentioned above, this was working great on an older commit.

**Comment by DannyDaemonic** [comment]
I don't see how that patch could be related to the problem you describe. It's not actually changing the context size, it's just forcing some extra calculations to ensure accuracy.

You could try reversing [the patch](https://patch-diff.githubusercontent.com/raw/ggerganov/llama.cpp/pull/1609.patch) to see if it fixes things for you. If you aren't compiling it yourself you could try [official releases](https://github.com/ggerganov/llama.cpp/releases). I'd start with [this one](https://github.com/ggerganov/llama.cpp/releases/tag/master-affc76e) and jump forward a bunch at a time until you find one that doesn't work and then work backwards. If you can find the exact point at which it stops working for you, then that will make it easier to figure out what's going wrong.

**Comment by ejones** [comment]
Yeah, it came down to how the evaluated tokens were appended to the existing session. I've got a fix in #1678.

**Comment by spencekim** [comment]
Works perfectly! Thanks @ejones
