### ISSUE TITLE
Opaque pointers support

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/llama.cpp#1672]
./main -m ./models/ggml-model-q4_0.bin -n 128

main: build = 607 (ffb06a3)
main: seed  = 1685690398
ggml_opencl: selecting platform: 'Clover'
ggml_opencl: selecting device: 'AMD Radeon (TM) RX 480 Graphics (polaris10, LLVM 15.0.6, DRM 3.51, 5.19.0-43-generic)'
ggml_opencl: device FP16 support: false
ggml_opencl: kernel compile error:

fatal error: cannot open file '/usr/lib/clc/polaris10-amdgcn-mesa-mesa3d.bc': Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.7' Reader: 'LLVM 15.0.7')

Clinfo -l

Number of platforms:				 2
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (3558.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.1 Mesa 22.2.5
  Platform Name:				 Clover
  Platform Vendor:				 Mesa
  Platform Extensions:				 cl_khr_icd

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 0
  Platform Name:				 Clover
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Max compute units:				 36
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 4
  Preferred vector width double:		 2
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 4
  Native vector width double:			 2
  Max clock frequency:				 1303Mhz
  Address bits:					 64
  Max memory allocation:			 2147483648
  Image support:				 No
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 32768
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 No
    Round to +ve and infinity:			 No
    IEEE754-2008 fused multiply-add:		 No
  Cache type:					 None
  Cache line size:				 0
  Cache size:					 0
  Global memory size:				 8589934592
  Constant buffer size:				 67108864
  Max number of constant args:			 16
  Local memory type:				 Scratchpad
  Local memory size:				 65536
ERROR: clBuildProgram(-11)

OS : Ubuntu 22 LTS

Kindly help. I'm trying to run the model on GPU. OpenCL is installed and cmake happens just fine. My driver is : amdgpu-install_5.5.50500-1_all.deb and my GPU is RX-480 8GB. CPU is Intel i5.

**Comment by aiaicode** [comment]
Closing the issue. Not getting the error with latest build.

**Comment by Darin755** [comment]
How did you solve this error?
