### ISSUE TITLE
[User] Support small models for embedding

### ISSUE THREAD

**Issue by YAOYI626** [ggerganov/llama.cpp#1679]
Hey guys,

Is there any possibility of supporting smaller models (smaller than 7B)? Like what ggml already did for GPT-J and BERT. Or any guidelines I can have to do that by myself?

Thanks

**Comment by FNsi** [comment]
Openllama 3B is supported, and you can download the ggml file from huggingface

**Comment by YAOYI626** [comment]
> Openllama 3B is supported, and you can download the ggml file from huggingface

Hey @FNsi Thanks for your reply. Since I want to deploy an embedding model on the client side. A sentence-bert like model is what I want. Is there any guidance I can have?

Thanks

**Comment by FNsi** [comment]
> > Openllama 3B is supported, and you can download the ggml file from huggingface
> 
> 
> 
> Hey @FNsi Thanks for your reply. Since I want to deploy an embedding model on the client side. A sentence-bert like model is what I want. Is there any guidance I can have?
> 
> 
> 
> Thanks

Check Bert.cpp? Or llm.

**Comment by YAOYI626** [comment]
> > > Openllama 3B is supported, and you can download the ggml file from huggingface
> > 
> > 
> > Hey @FNsi Thanks for your reply. Since I want to deploy an embedding model on the client side. A sentence-bert like model is what I want. Is there any guidance I can have?
> > Thanks
> 
> Check Bert.cpp? Or llm.

Awesome! Thanks @FNsi for the information.
