### ISSUE TITLE
How do i use llama.cpp as an API?

### ISSUE THREAD

**Issue by Shreyas-ITB** [ggerganov/llama.cpp#1683]
Hello! Im making a cool project that involves llama.cpp, but i need it in the form of an API to make the communication easier rather than catching the output of llama.cpp in the console. Is there any way to use this as an API?

**Comment by TusharAgey** [comment]
https://github.com/ggerganov/llama.cpp/pull/1443 - Use this.

**Comment by Green-Sky** [comment]
llama.cpp provides a C "API".
Not sure what your mean.

**Comment by mirek190** [comment]
what do you mean c api?

**Comment by Green-Sky** [comment]
> what do you mean c api?

https://github.com/ggerganov/llama.cpp/blob/master/llama.h

**Comment by mirek190** [comment]
you mean server?

**Comment by Shreyas-ITB** [comment]
@TusharAgey thankyou very much, i have been looking for it for ages! :)
