### ISSUE TITLE
AWQ: Activation-aware Weight Quantization???

### ISSUE THREAD

**Issue by UnsGentoals** [ggerganov/llama.cpp#1685]
https://github.com/mit-han-lab/llm-awq

AWQ: Activation-aware Weight Quantization sounds interesting 🧐🧐🧐

**Comment by shouyiwang** [comment]
Are you interested in implementing this new algorithm in Llama.cpp? The performance with 3 bits seems amazing

**Comment by UnsGentoals** [comment]
Sorry,I'm not pro developer 😔 
just a user who care about open llm news, and with tech background.☺️

**Comment by qwopqwop200** [comment]
If my understanding is correct, it is that GPTQ and AWQ are stored in very similar formats and can be stored in the same format as well.
Additionally, currently GGML has imperfect support for the format of GPTQ, and improving it could save about 0.5 bit more.

**Comment by namtranase** [comment]
Hi everyone, I have tried to make a PR to add AWQ. I really appreciate the comments to make it better, thanks!
[The PR](https://github.com/ggerganov/llama.cpp/pull/4593)
