### ISSUE TITLE
Server example not working - failing on Runtime Error unexpected EOF

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [ggerganov/llama.cpp#1704]
# Expected Behavior

Working server example.

# Current Behavior

Fails when loading

llama.cpp: loading model from models/7B/ggml-model.bin
libc++abi: terminating with uncaught exception of type std::runtime_error: unexpectedly reached end of file
[1]    66278 abort      ./server -m models/7B/ggml-model.bin

I had to change the model to -m  models/7B/ggml-model.bin as the default value didn't take into account the directory where the models are stored.

# Environment and Context

MAC OSX M2

**Comment by BartlomiejLewandowski** [comment]
./main works well with the same model file

**Comment by FSSRepo** [comment]
Requantize your model to the lastest version, and update use the latest server example release

**Comment by BartlomiejLewandowski** [comment]
both have been done, but I'll pull again and report back

**Comment by cmann50** [comment]
If you are trying to get the latest version of llama.cpp to work, you can download this model created yesterday: [selfee-13b.ggmlv3.q2_K.bin](https://huggingface.co/TheBloke/Selfee-13B-GGML/blob/main/selfee-13b.ggmlv3.q2_K.bin).

Put the model in the models directory and run:
```
make -j && ./main -m ./models/selfee-13b.ggmlv3.q2_K.bin -p "Building a website can be done in 10 simple steps:" -n 512
```
I'm running on a mac M1.

If you read over this thread from yesterday, it led me to a working model using the new quantization method mentioned: https://github.com/ggerganov/llama.cpp/pull/1684#issuecomment-1578585886

**Comment by fbalicchia** [comment]
Thanks @cmann50  with that models works for me too

**Comment by Aisuko** [comment]
Hi, guys. I hit this issue in most of the models. Is there exist any smaller size model(<200MB) we can use for the test?
