### ISSUE TITLE
Ziya support

### ISSUE THREAD

**Issue by etyhh** [ggerganov/llama.cpp#1731]
Ziya  is a large-scale pre-trained model based on LLaMA with 13 billion parameters.It add Chinese token. And model vocab size is not equal to tokenizer.

Could anyone give some hint here？

**Comment by wyzhangyuhan** [comment]
follow the readme and expand the tokenizer on your own works well for me.

**Comment by thatname** [comment]
See my repo on huggingface: https://huggingface.co/thatname/Ziya-LLaMA-13B-v1-ggml

**Comment by etyhh** [comment]
problem solved,thanks
