### ISSUE TITLE
I am trying to load  vicunlocked-65b.ggmlv3.q2_K.bin  but nothing happening just quit without any error.

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#1743]
I am trying to load  vicunlocked-65b.ggmlv3.q2_K.bin  but nothing happening just quit without any error.
The newest build  master-5c64a09](https://github.com/ggerganov/llama.cpp/releases/tag/master-5c64a09

PS F:\LLAMA\llama.cpp> build\bin\main --model models/new2/vicunlocked-65b.ggmlv3.q2_K.bin --mlock --color --threads 8 --keep -1 --batch_size 512 --n_predict -1 --top_k 10000 --top_p 0.9 --temp 0.96 --repeat_penalty 1.1 --ctx_size 2048 --interactive --instruct --reverse-prompt "### Human:" --reverse-prompt "### User:" --reverse-prompt "### Assistant:" -ngl 36
main: build = 635 (5c64a09)
main: seed  = 1686149787
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090
llama.cpp: loading model from models/new2/vicunlocked-65b.ggmlv3.q2_K.bin
PS F:\LLAMA\llama.cpp>

**Comment by mirek190** [comment]
...yeah works ... previous build ... try to add any GPU layer and you will get ONLY gibberish...

**Comment by MoodCharge** [comment]
This is fixed with later releases
