### ISSUE TITLE
GML_ASSERT: ggml-metal.m:558: false && "not implemented"

### ISSUE THREAD

**Issue by cspenn** [ggerganov/llama.cpp#1745]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When running the chat-13B.sh with -ngl 1, expected behavior is to see llama.cpp initiate with GPU support.

# Current Behavior

Immediately after compiling using either the make or cmake instructions for Metal (have tried both), when the script starts up, it spits out:

Error:
GML_ASSERT: ggml-metal.m:558: false && "not implemented"

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

MacOS 14.3 Ventura
MacBook Pro M1 Max, 64 GB RAM
Python 3.10.10

Model: ggml-v3-13b-hermes-q5_1.bin

**Comment by aarons** [comment]
Metal currently only supports full 16bit or 4bit quantized models. So if you are looking to run that model then would need to quantize it to 4bit instead of 5.

around line 558:
```objective-c
switch (src0->type) {
    case GGML_TYPE_F16:  [encoder setComputePipelineState:ctx->pipeline_get_rows_f16]; break;
    case GGML_TYPE_Q4_0: [encoder setComputePipelineState:ctx->pipeline_get_rows_q4_0]; break;
    default: GGML_ASSERT(false && "not implemented");
}
```

**Comment by cspenn** [comment]
Thank you!
