### ISSUE TITLE
batch inference

### ISSUE THREAD

**Issue by liuxiaohao-xn** [ggerganov/llama.cpp#1754]
I have multiple prompts, I want to feed them all at once to the model to generate the output，can you tell me how to achieve it ?

**Comment by SlyEcho** [comment]
Not supported yet.

**Comment by kogolobo** [comment]
Hi, just following up on this. Is there any timeline for this feature? @SlyEcho  Thanks!

**Comment by SlyEcho** [comment]
I don't know if anyone is working on it. Right now we are still solving issues with single generation like beam search, etc.
