### ISSUE TITLE
[Feature Request] Restart a fresh conversation while using `interactive-first`

### ISSUE THREAD

**Issue by Foul-Tarnished** [ggerganov/llama.cpp#1760]
# Expected Behavior

Please add a keyboard shortcut (Like "\\", CTRL+C, "/", Return, ...) to clean the model cache or whatever, so we can start a whole new conversation, without needing to restart the app completely

# Current Behavior

Here's the command i'm using : 
`.\build\bin\Release\main.exe -m ./models/7B/ggml-model-q4_0.bin -n 128 --interactive-first --color --threads 4 --mlock`

I write a sentence, press enter, and the model answer.
I then do CTRL+C, write a different sentence, but the model remember the first one and is getting confused. (I tried to first enter "\\" then my new sentence, but the first one is still influencing the model)

I don't want to use a prompt file, and reloading the app/model after each conversation can take a bit of time (and electricity, rip laptop battery)

# Environment and Context
Built with Intel_MKL and BLAS or whatever

* Physical hardware
Windows 11, laptop
i7 8565U 4c/8t, 16gb ram, Intel UHD 620

* Operating System
Windows 11 22H2
Python 3.11.3
cmake version 3.26.4

**Comment by sergedc** [comment]
Are you using main.exe? 

If so, tinker with this line: 
if (n_past + (int) embd.size() > n_ctx) {
const int n_left = n_past - params.n_keep;

And replace with something like this
if (n_past + (int) embd.size() > n_ctx || (((int) embd.size() > 1 ) {
if lastinsertedtextbyuser is equal to "forget everything"
const int n_left = 0;
else 
const int n_left = n_past - params.n_keep;

To get the lastinsertedtextbyuser : play with this: 
for (auto id : embd) {
      printf("%s", llama_token_to_str(ctx, id));

You might need to use this loop to build lastinsertedtextbyuser.

**Comment by msj121** [comment]
This is being requested here as well: https://github.com/ggerganov/llama.cpp/issues/1780

And an issue I noticed here: https://github.com/ggerganov/llama.cpp/issues/1771

The suggested fix from sergedc did not work for me.
