### ISSUE TITLE
feature request - support huggingface tokenizer

### ISSUE THREAD

**Issue by keunwoochoi** [ggerganov/llama.cpp#1764]
currently in llama.cpp, `convert.py` assumes `tokenizer.model` file in the model path. seems like this works for any case that uses a `sentencepiece` tokenizer, but nothing else. 

huggingface's tokenizer library is neat and provides more options than `sentencepiece`. it would be really great if ggml support any tokenizers from huggingface. i believe this means it'd expect `merges.txt` and `vocab.json`.

**Comment by Ender436** [comment]
I'm trying to convert a model that I've trained and exported in huggingface format, but when I try to convert, it is giving me an error saying it can't find vocab.json. What exactly is this file, where would I get it?

**Comment by goerch** [comment]
`vocab.json` is the vocabulary part of `tokenizer.json`. I believe these are serialization formats of different versions of HF.

**Comment by Ender436** [comment]
Ok, thank you! I've tried taking the vocab section out and putting it in it's own file, but I'm getting this error:

raise Exception(f"Expected the {len(actual_ids)} added token ID(s) to be sequential in the range {vocab_size} - {expected_end_id}; got {actual_ids}")
Exception: Expected the 3 added token ID(s) to be sequential in the range 32000 - 32002; got [0, 1, 2]

Any idea what I'm doing wrong? Thanks for the help.

**Comment by teleprint-me** [comment]
The tokenizer is the mapping between the vocab and encodings representing the mapped sequence for a language model. That's [what sentencepiece is for](https://github.com/google/sentencepiece/blob/master/README.md#technical-highlights).

> SentencePiece treats the sentences just as sequences of Unicode characters. There is no language-dependent logic.

So, I could train a model on a vocab of a fixed size and then use differing techniques like BPE, SPE, Unigram, etc. They all represent supported subword algorithms.

A transformer model creates associations for next token predictions using the vocab during training usually using SGD (stochastic gradient descent). The derivative allows the model to error correct throughout the process; This is where the models weights are adjusted.

It's more complicated than this, but this is my general understanding as of the moment.

https://huggingface.co/docs/tokenizers/quicktour

**Comment by Ender436** [comment]
I tried just removing the items in added_tokens.json, and the model converted, but it seems to have lost it's ability to stop on it's own now, and just rambles about random things after finishing saying what I'd expect.

**Comment by strutive07** [comment]
Hi. I put up a PR that runs convert.py based on the huggingface tokenizer without tokenizer.model. I hope this helps.

PR: https://github.com/ggerganov/llama.cpp/pull/3633

**Comment by keunwoochoi** [comment]
@strutive07 that's great! thanks for letting us know
