### ISSUE TITLE
Seeking Recommendations for Optimal AWS EC2 Instance for Hosting llama.cpp (CPU)

### ISSUE THREAD

**Issue by tgcandido** [ggerganov/llama.cpp#1766]
Hello everyone,

I was wondering if anyone has experience hosting `llama.cpp` on AWS EC2. Could you please recommend an instance that works well for this purpose? I've already tried using c5.large, but unfortunately, it turned out to be quite slow. Your suggestions and insights would be greatly appreciated!

Thank you in advance!

**Comment by tgcandido** [comment]
I'm using the `llama-cpp-python` package to run with the default parameters and `n_ctx=2048`

**Comment by bnusunny** [comment]
Try c5.2xlarge. It has 8 vCPU. Should get around 150 ms per token.

**Comment by MoonKraken** [comment]
I also had the same question.

What about GPU instances? ie g4, g5, p2, p3, etc.

Thinking of writing a tool that benchmarks all of them...
