### ISSUE TITLE
[Feature] Support resetting the status of llama_context

### ISSUE THREAD

**Issue by AsakusaRinne** [ggerganov/llama.cpp#1780]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Here's my assumption: sometimes one may want to restart a session with the model. However if inputting the new prompt directly, the previous session will impact on the new session (unless the new prompt is long enough), because `llama.eval` will leave some effects in `llama_context`. Therefore, clearing the some variables such as `embd` and `embd_inps` in `main.cpp` is not enough, making it's necessary to reload the model to restart a session.

I'm still new to LLM so please correct me if what I said is wrong. :)

Under the assumption, I think it's better if an API is provided to allow resetting the status of `llama_context`. Thus users need not to reload the model to restart a session.

# Current Behavior

Need to reload the model to restart a session.

**Comment by AIWintermuteAI** [comment]
@slaren @ggerganov Perhaps it is possible to re-open the issue? I noticed a few other issues, that request a similar feature.
And yes, I stumbled upon it when searching for how to reset the context without reloading the model myself xD

**Comment by ggerganov** [comment]
There is already API - just call `llama_kv_cache_clear()`.

**Comment by AIWintermuteAI** [comment]
Thanks for the quick reply!
