### ISSUE TITLE
Is there any LLAMA.CPP .exe package that can be used for the inference process in CLI

### ISSUE THREAD

**Issue by ekolawole** [ggerganov/llama.cpp#1781]
Both make and cmake not working in my environment. This process was much easier when we could use a .exe file and some other variables like --threads --tokencontextsize etc. 

Please any repo out there with this capability?

**Comment by AlphaAtlas** [comment]
There are many front ends, but Kobold.cpp is a good one. They build one click exes for Windows.

**Comment by lorenzoFIS** [comment]
@ekolawole did you first check the releases page?

get this one llama-master-98ed165-bin-win-avx2-x64.zip
