### ISSUE TITLE
A sampling function that returns top token probabilities

### ISSUE THREAD

**Issue by WangHaoranRobin** [ggerganov/llama.cpp#1784]
I was using playing around with the [server example](https://github.com/ggerganov/llama.cpp/blob/98ed16557432d7a5179c57eddcc3a08a7ae6d54d/examples/server/server.cpp) and wanted to expose the probabilities of the generated tokens to the server client to implement custom stopping sequences and criteria(similar to openai's api [here](https://platform.openai.com/docs/api-reference/completions/create#completions/create-logprobs)). 

All it would take should just be creating a different version of "[llama_sample_token](https://github.com/ggerganov/llama.cpp/blob/98ed16557432d7a5179c57eddcc3a08a7ae6d54d/llama.cpp#L2208)" and "[llama_sample_token_greedy](https://github.com/ggerganov/llama.cpp/blob/98ed16557432d7a5179c57eddcc3a08a7ae6d54d/llama.cpp#L2192)" that returns an object containing the top X tokens and their probabilities. 

The only related issue/pr/discussion I was able to find is [this pr](https://github.com/ggerganov/llama.cpp/pull/246#issue-1629958364) about logging probabilities. Please give me pointers if similar requests have been discussed somewhere.

Since I'm relatively new to the repo, what is the protocol here? Should I just make a PR?

**Comment by nauyisu022** [comment]
Did you find out how to achieve this?

**Comment by WangHaoranRobin** [comment]
Yes. I realized the parameters passed into the sample functions are references. So no need to change the core logic to get the probs. just read directly from the candidate list object after passing it through the sampling function is enough. 

i.e. in server.cpp :
https://github.com/ggerganov/llama.cpp/blob/049aa16b8c5c6d086246e4e6b9feb18de4fbd663/examples/server/server.cpp#L293
Read `candidates_p.data[i].p` after the sampling functions are called to get the probs.

I'm working on a PR for server example about this rn.
