### ISSUE TITLE
Program hangs after some time

### ISSUE THREAD

**Issue by siddhsql** [ggerganov/llama.cpp#1793]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Please provide a detailed written description of what you were trying to do, 

i was trying to run the program with this command:

```
./bin/main -m ./model.bin --gpu-layers 40 -n 256 --repeat_penalty 1.0 --color -i -r "User:" --in-prefix " " -f ./chat-with-bob.txt
```

and what you expected `llama.cpp` to do.

i expected the program to run

# Current Behavior

Please provide a detailed written description of what `llama.cpp` did, instead.

the program does run but predictably hangs after sometime. I have done 3 runs so far and reliably reproduced the issue.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

```
$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:                        0
CPU MHz:                         2299.998
BogoMIPS:                        4599.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode;
                                  SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prct
                                 l and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointe
                                 r sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional,
                                  RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge m
                                 ca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht sysc
                                 all nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xt
                                 opology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq
                                  ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
                                  aes xsave avx f16c rdrand hypervisor lahf_lm abm invp
                                 cid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjus
                                 t bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_cl
                                 ear arch_capabilities
```

* Operating System, e.g. for Linux:

`$ uname -a`

```
$ uname -a
Linux deeplearning-2 5.10.0-22-cloud-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```
$ python3 --version
$ make --version
$ g++ --version
```

```
$ python3 --version
Python 3.9.2
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ g++ --version
g++ (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

the program will hang after a while. CPU usage is 0 when it hangs. I have waited for extended period of time but it never comes out of the hanged state.

my system info:

```
system_info: n_threads = 2 / 2 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. sync to commit `2d7bf110edd8c49209401a16132052cba706ffd0`
2. build the code using `cmake` and with `CUBLAS` flag ON
3. run the program using this command: `./bin/main -m ./model.bin --gpu-layers 40 -n 256 --repeat_penalty 1.0 --color -i -r "User:" --in-prefix " " -f ./chat-with-bob.txt`
4. after 1 or 2 questions it will hang in the middle of printing an answer

**Comment by spencekim** [comment]
Since you are in interactive mode, get rid of `-n 256`

**Comment by siddhsql** [comment]
thanks. that fixed the problem. llama.cpp is amazing program. btw this time
when I was running it with same arguments as above (except I removed the n
parameter), the prompt changed from Bob to Socrates all of a sudden!
[image: image.png]

**Comment by shouyiwang** [comment]
I am currently using Apple's M1. However, the program seems to intermittently hang for several seconds, regardless of whether the "-n" is attached or not.
