### ISSUE TITLE
Honest Llama

### ISSUE THREAD

**Issue by m1chae1bx** [ggerganov/llama.cpp#1799]
Anyone wants to try incorporating this: https://github.com/likenneth/honest_llama

**Comment by SlyEcho** [comment]
Seems similar to the steering vector thing...

**Comment by walking-octopus** [comment]
Had there been any progress on this? Mitigating hallucinations could be one of the most important obstacles to mass local LLM adoption. If this is any better than RLHF or fine-tuning, this can be a major step in the right direction.
