### ISSUE TITLE
[User]make LLAMA_CUBLAS=1 fails due to arch=native 

### ISSUE THREAD

**Issue by iplayfast** [ggerganov/llama.cpp#1803]
An error in the Makefile.

The nvcc compiler does not recognize the -arch=native flag, deleting this parameter (on line 162 of the make file) allows the make to proceed correctly.

**Comment by slaren** [comment]
Updating your CUDA toolkit should fix the issue. I believe that the `-arch=native` flag was added in version [11.6.0](https://docs.nvidia.com/cuda/archive/11.6.0/cuda-compiler-driver-nvcc/#options-for-steering-gpu-code-generation).

**Comment by iplayfast** [comment]
Does this flag actually add anything? To me it looks like it doesn't since the arch is nvidia and it's an nvidia compiler. By forcing the use of the flag you are forcing the upgrade of Cuda to a version which isn't in distro's repositories yet. Unnecessary restriction for no gain.
