### ISSUE TITLE
any plans to speed up the prompt-ingestion phase using metal? 

### ISSUE THREAD

**Issue by daboe01** [ggerganov/llama.cpp#1805]
is this even feasible/possible?

**Comment by ggerganov** [comment]
Should be possible - we need a GEMM kernel that works with quantized data.
The poor-man solution is to first dequantize and use MPS GEMM

**Comment by daboe01** [comment]
ggml-metal.metal already has kernel_mul_mat_q4_0_f32
would you just need a kernel_mul_mat_q4_0_q4_0?

**Comment by daboe01** [comment]
closing this in favour of #1867 and #1632
