### ISSUE TITLE
What is the input embedding of LlaMa? Is it trainable?

### ISSUE THREAD

**Issue by magic-YuanTian** [ggerganov/llama.cpp#1814]
I am trying to get something like an encoder from LlaMa. Is any one know how to do that?

**Comment by daboe01** [comment]
./embedding -m ./models/llama-30b-supercot.ggmlv3.q4_1.bin -p 'encode me'
main: build = 659 (31d2b5f)
main: seed  = 1686587571
llama.cpp: loading model from ./models/llama-30b-supercot.ggmlv3.q4_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size =    0.13 MB
llama_model_load_internal: mem required  = 21695.49 MB (+ 3124.00 MB per state)
.
llama_init_from_file: kv self size  =  780.00 MB

system_info: n_threads = 8 / 12 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
-0.771720 -0.292218 0.541149 0.307581 ...
