### ISSUE TITLE
Suggestions for Contributing as non-C developer

### ISSUE THREAD

**Issue by robinnarsinghranabhat** [ggerganov/llama.cpp#1835]
I am a Python based ML engineer with general understanding of C/C++. I am in love with llama.cpp. Apart from it's cause to open-source llms, I am astounded/overwhelmed by clever-optimizations added here. 

I am ready to take on the long route to understanding this code-base and hopefully maintain this or other projects like this. 
My question is, What is the path to do so ?  to be like @ggerganov or any other core-contributors.  

I feel like I would need essential knowledge about computer architecture, operating systems, systems programming, gpu programming e.t.c  I am determined to learn these stuffs with  llama.cpp as the reference. 

It would be amazing if system-programming gurus of the community provide a clear guideline. Because trying to understand the repo by skimming through the code, I just get lost.

**Comment by 0xspringtime** [comment]
I'd quickly look over the C documentation at https://devdocs.io/c/ or read the classic guide by Kernighan and Ritchie. Then instead of going into the code blind, read along with chatgpt by asking it to explain blocks of code component by component. If you truly understand ML concepts in python it shouldn't be too difficult to see what's going on from there.

**Comment by robinnarsinghranabhat** [comment]
@0xspringtime Really appreciate this advice. Is there anything else to add to corroborate my learning in addition to Chat-gpt. 
I mean, for domain you are not much familiar with, you cannot figure out when LLM starts to give seemingly-factual-nonsense. 

Last time I tried to understand workings of python-virtual-machine with chat-gpt, it didn't go too well. maybe that's the problem with me.
