### ISSUE TITLE
[Contributor] Proposal - adding node bindings, similar to whisper, a la examples/addon.node

### ISSUE THREAD

**Issue by yacineMTB** [ggerganov/llama.cpp#1841]
# Prerequisites
- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

## Proposal
My proposal is to add node bindings, under examples/addon.node similar to whisper.cpp's [node addon](https://github.com/ggerganov/whisper.cpp/tree/master/examples/addon.node)

## Why
- There already [has been work](https://github.com/yacineMTB/llama.cpp/tree/yacine/node.addon) on it, and I think it might be useful for other people to have!

## Why you should stop me 
- More maintenance
- More things for people to create issues regarding
- More code - diffs to main might necessitate a diff to addon
- If I could write it myself, maybe other people should too!

## If a contributor says yes, I'll clean up my diffy, and attempt to mainline it.
A no is completely reasonable! 

cc @cto-junior - helping me with the cpp

**Comment by bakkot** [comment]
One of the [roadmap items](https://github.com/ggerganov/llama.cpp/discussions/1729) is a general refactor, and [another](https://github.com/ggerganov/llama.cpp/discussions/1220#discussioncomment-5956605) is to clean up state in general, for which there's now a [PR](https://github.com/ggerganov/llama.cpp/pull/1797). You might want to wait until those are done (at least the open PR) before adding new bindings which depend on the current design.

**Comment by cto-junior** [comment]
@bakkot Thanks for the quick response! THe PR looks backward compatible right now but you're right it might go through some changes in the process.

I also wanted to know if there's a PR or an issue to make lora adapters hot-swappable?

**Comment by ggerganov** [comment]
Adding `examples/addon.node` is welcome

In general, the purpose of the `examples` is to demonstrate usage of `llama.cpp`. We rely heavily on contributions to maintain those and we are fine if they break at some point and there is no longer interest in supporting them. Having a dedicated CI that runs upon local changes in the example is optional, but recommended to ensure longer term support.
If the example comes with no or little changes to `llama.cpp` and `ggml`, then it is always easy to get merged
