### ISSUE TITLE
Error converting pth to ggml

### ISSUE THREAD

**Issue by richardr1126** [ggerganov/llama.cpp#1842]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [y] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [y] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [y] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [y] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Convert `consolidated.00.pth` to ggml model using `convert.py` or `convert-pth-to-ggml.py (I know this is deprecated)`, and get an f16 ggml model.

# Current Behavior

`KeyError: ('torch._utils', '_rebuild_meta_tensor_no_storage')`

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Hardware I am using: **_Apple M1 Pro on Macbook Pro_**

* Operating System: **_macOs 13.3.1_**

* SDK version: Darwin Richards-MBP 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 **_arm64_**

```
$ python3 --version --> **_Python 3.11.4_**
$ make --version -----> **_GNU Make 3.81_**
$ g++ --version ------> **_Apple clang version 14.0.3 (clang-1403.0.22.14.1)_**
```

# Error output

Richards-MBP:llama.cpp richardroberson$ python3 -m trace --count -C . convert.py models/guanaco13b
Loading model file models/guanaco13b/consolidated.00.pth
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/trace.py", line 741, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/trace.py", line 729, in main
    t.runctx(code, globs, globs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/trace.py", line 451, in runctx
    exec(cmd, globals, locals)
  File "convert.py", line 1168, in <module>
    main()
  File "convert.py", line 1148, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "convert.py", line 1074, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "convert.py", line 864, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "convert.py", line 736, in lazy_load_torch_file
    model = unpickler.load()
            ^^^^^^^^^^^^^^^^
  File "convert.py", line 725, in find_class
    return self.CLASSES[(module, name)]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
**_KeyError: ('torch._utils', '_rebuild_meta_tensor_no_storage')_**

# Steps to Reproduce

1. Load a LLaMA merged LoRA model (e.g. Guanaco13B) in a jupyter notebook in Google Colab, and save the model using `torch.save()`.
2. I had regular LLaMA 13B working from my models folder. So duplicated that model folder and replaced `consolidated.00.pth` with the one from `torch.save()`.
3. Update the checklist.chk with the new md5 for `consolidated.00.pth`.
4. Run `convert.py` or `convert-pth-to-ggml.py` with the new model folder and I almost immediately get the error KeyError: ('torch._utils', '_rebuild_meta_tensor_no_storage').

# More environment info:
```
llama.cpp$ git log | head -1 -----> commit ffb06a345e3a9e30d39aaa5b46a23201a74be6de

llama.cpp$ pip list | egrep "torch|numpy|sentencepiece"
appnope            0.1.3
asttokens          2.2.1
backcall           0.2.0
cachetools         5.3.1
certifi            2023.5.7
charset-normalizer 3.1.0
comm               0.1.3
debugpy            1.6.7
decorator          5.1.1
distlib            0.3.6
executing          1.2.0
fairscale          0.4.13
filelock           3.12.0
fire               0.5.0
fsspec             2023.6.0
hiq-python         1.1.12
huggingface-hub    0.15.1
idna               3.4
ipykernel          6.23.1
ipython            8.14.0
jedi               0.18.2
Jinja2             3.1.2
jupyter_client     8.2.0
jupyter_core       5.3.0
markdown-it-py     3.0.0
MarkupSafe         2.1.3
matplotlib-inline  0.1.6
mdurl              0.1.2
mpmath             1.3.0
nest-asyncio       1.5.6
networkx           3.1
numpy              1.24.0
packaging          23.1
parso              0.8.3
pexpect            4.8.0
pickleshare        0.7.5
Pillow             9.5.0
pip                23.1.2
platformdirs       3.5.1
prompt-toolkit     3.0.38
psutil             5.9.5
ptyprocess         0.7.0
pure-eval          0.2.2
py-itree           0.0.19
Pygments           2.15.1
pyllama            0.0.9
python-dateutil    2.8.2
PyYAML             6.0
pyzmq              25.1.0
regex              2023.6.3
requests           2.31.0
rich               13.4.2
safetensors        0.3.1
sentencepiece      0.1.97
setuptools         65.5.0
six                1.16.0
stack-data         0.6.2
sympy              1.12
termcolor          2.3.0
tokenizers         0.13.3
torch              2.0.1
torchaudio         2.0.2
torchvision        0.15.2
tornado            6.3.2
tqdm               4.65.0
traitlets          5.9.0
transformers       4.30.1
typing_extensions  4.6.3
urllib3            2.0.3
virtualenv         20.23.0
wcwidth            0.2.6
wheel              0.40.0
```
I also made sure to update my checklist.chk file with the new md5 for consolidated.00.pth.
```
$ md5 ./models/guanaco13b/consolidated.00.pth 
---------> c1d923ab6a6c12214a20354508f0d0ae  ./models/guanaco13b/consolidated.00.pth
```

**Comment by KerfuffleV2** [comment]
`convert.py` has its own implementation of PyTorch model loading that only supports a limited number of classes: https://github.com/ggerganov/llama.cpp/blob/92549202659fc23ba9fec5e688227d0da9b06b40/convert.py#L698-L720

You could attempt to hack support in based on the function definition in PyTorch: https://github.com/pytorch/pytorch/blob/69b09eca5ad863067d723d49f06c409deada2db6/torch/_utils.py#L283-L286

I'd guess it's probably not very likely to work. Your best bet is to try to save your model without any "weird stuff" like meta tensors (don't ask me what that means).

**Comment by richardr1126** [comment]
I got it working by saving the model on Hugging Face in float16, then using convert.py in llama.cpp. I didn't know it was that simple.
