### ISSUE TITLE
[User] Training examples sometimes gets broken when training data is in Japanese

### ISSUE THREAD

**Issue by Igoorx** [ggerganov/llama.cpp#1843]
This is an issue to track the problem reported at https://github.com/ggerganov/llama.cpp/pull/1652#issuecomment-1586381277.

# Expected Behavior

No `�` characters in the examples.

# Current Behavior

The examples sometimes contain `�` characters (which aren't in the training data).

# Failure Information

<details>
<summary>Example 0 during Training</summary>

![image](https://github.com/ggerganov/llama.cpp/assets/14041768/40fc8be9-a327-42d7-867e-e746bae487be)
</details>
<details>
<summary>Output of the trained model</summary>

![image](https://github.com/ggerganov/llama.cpp/assets/14041768/6eb3ea01-2130-4238-a90c-c836f519c5d7)
</details>

# Steps to Reproduce

Try to train using this training data: [dataset.txt](https://github.com/ggerganov/llama.cpp/files/11716289/dataset.txt)

**Comment by kolinfluence** [comment]
@Igoorx possible to provide the instructions on how you train the dataset? is there a tutorial of sorts u are following online?

**Comment by Igoorx** [comment]
@kolinfluence You can find the instructions for training here: https://github.com/ggerganov/llama.cpp/blob/master/examples/train-text-from-scratch/README.md

But this is the command that I used:
```sh
train-text-from-scratch --vocab-model "chronos-13b.ggmlv3.q4_0.bin" --ctx 64 --embd 768 --head 12 --layer 6 --checkpoint-in chk-jp-256x16.bin --checkpoint-out chk-jp-256x16.bin --model-out ggml-jp-256x16-f32.bin --train-data "dataset.txt" -t 6 -b 16 -n 32 --seed 1 --adam-iter 16 --print-details-interval 1 --predict 16 --use-flash --mem-model 5
```

**Comment by SlyEcho** [comment]
I don't know very closely how the trainer works, but I assume it breaks the input into batches of tokens and runs the training on those.

The way the tokenizer in the stock LLaMA works is that a lot of non-Latin text will be split into multiple tokens per character. In this case, this batch cannot be converted back into a string losslessly, but for the model the only thing that should matter is that the tokens are coming in the right order (but ideally it shouldn't learn to generate broken UTF-8...).

Ultimately, a better tokenizer for the target language would be best.
