### ISSUE TITLE
Is it possible to load Excel files for data analysis or upload code for conversion via CLI?

### ISSUE THREAD

**Issue by breisig** [ggerganov/llama.cpp#1845]
Is it possible (like hatgpt) to upload Excel files or upload code for data analysis against any model via the CLI? Something like uploading a few excel files and getCting a data analysis from all files or uploading a folder of code (php) and getting it converted to c/c++?

**Comment by randaller** [comment]
@breisig It is possible, if your raw excel data or php code size around 2-3-4 kilobytes (2048 tokens).
