### ISSUE TITLE
build train-from-scratch.cpp

### ISSUE THREAD

**Issue by JackJollimore** [ggerganov/llama.cpp#1853]
Hi,

I want to test the train-from-scratch.cpp example in llama.cpp.

Following the usage instruction precisely, I'm receiving error: 
```
./bin/train-text-from-scratch: command not found
```

I guess I must build it first, so using..
```
cmake -B build 
cd build
make -j8
```

Then I fail to make:
```
[ 50%] Building CXX object CMakeFiles/train-text-from-scratch.dir/train-text-from-scratch.o
/data/data/com.termux/files/home/ollama/examples/train-text-from-scratch/train-text-from-scratch.cpp:1:10: fatal error: 'ggml.h' file not found
#include "ggml.h"
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/train-text-from-scratch.dir/build.make:76: CMakeFiles/train-text-from-scratch.dir/train-text-from-scratch.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/train-text-from-scratch.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

Any direction on this matter is appreciated.

**Comment by JackJollimore** [comment]
For any like myself:

After compiling llama.cpp like normal,  then navigate to build/bin and run like with ./

Like this:
```
./train-text-from-scratch \ _parameters_
```

**Comment by cuongdl** [comment]
Hi-

Do you know the hardware requirements to train it? I have tried and got the message: zsh: illegal hardware instruction  ./bin/train-text-from-scratch --vocab-model ../models/ggml-vocab.bin

**Comment by JackJollimore** [comment]
> Hi-
> 
> Do you know the hardware requirements to train it? I have tried and got the message: zsh: illegal hardware instruction ./bin/train-text-from-scratch --vocab-model ../models/ggml-vocab.bin

I don't know the hardware requirements, sorry.

I do know the command to run train-from-scratch is pretty sophisticated. Here's my command:
`
LD_LIBRARY_PATH=/vendor/lib64 ~/cllama/build/bin/train-text-from-scratch --vocab-model ~/ollama/models/ggml-vocab.bin --ctx 64 --embd 256 --head 8 --layer 16 --checkpoint-in chk-shakespeare-256x16.bin --checkpoint-out chk-%2-256x16.bin --model-out ggml-shakespeare-256x16-f32.bin --train-data ~/ollama/shakespeare.txt -t 3 -b 16 -n 32 --seed 1 --adam-iter 16 --print-details-interval 0 --predict 16 --use-flash
`

Error:
```
main: seed: 1
llama.cpp: loading model from /data/data/com.termux/files/home/ollama/models/ggml-vocab.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
main: tokenize training data
main: number of training tokens: 27584
print_params: n_vocab: 32000
print_params: n_ctx:   64
print_params: n_embd:  256
print_params: n_mult:  256
print_params: n_head:  8
print_params: n_ff:    768
print_params: n_layer: 16
print_params: n_rot:   32
main: number of unique tokens: 3070
ggml_opencl: selecting platform: 'QUALCOMM Snapdragon(TM)'
ggml_opencl: selecting device: 'QUALCOMM Adreno(TM)'
ggml_opencl: device FP16 support: true
main: init model
load_checkpoint: Training iterations: 0.
load_checkpoint: Training samples:    0.
load_checkpoint: Training tokens:     0.
main: opt iter 0
used_mem model+cache: 242364416 bytes
main: begin training
ggml_opencl: ggml_cl_h2d_tensor_2d(queue, d_X, 0, src0, i03, i02, NULL) error -30 at /data/data/com.termux/files/home/cllama/ggml-opencl.cpp:1324
```

but yeah, I don't actually know if my device can accomplish this :)

**Comment by aseok** [comment]
Where to access chk-shakespeare-256x16.bin & chk-%2-256x16.bin?

**Comment by aseok** [comment]
@JackJollimore also getting same error compiled for opencl on Android device

**Comment by JackJollimore** [comment]
> Where to access chk-shakespeare-256x16.bin & chk-%2-256x16.bin?

Shakespear.txt is the example in train-from-scratch.

`%1 the input txt and %2 the output name` is how I got it to run except instead I pathed directly to the txt file instead of %1 for the input.

**Comment by the-crypt-keeper** [comment]
The --checkpoint-in is not needed.

I only have a 16GB machine and the default memory allocator will fail obtusely if you have under 32GB:

```
used_mem model+cache: 242364416 bytes
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

So far this is working and consuming around 2GB.  Make sure to adjust `-t 4` to your hardware.

```bash
./train-text-from-scratch \
--vocab-model models/ggml-vocab.bin \
--ctx 64 \
--embd 256 \
--head 8 \
--layer 16 \
--checkpoint-out chk-shakespeare-256x16.bin \
--model-out ggml-shakespeare-256x16-f32.bin \
--train-data "shakespeare.txt" \
-t 4 \
-b 8 \
-n 32 \
--seed 1 \
--adam-iter 16 \
--print-details-interval 0 \
--predict 16 \
--use-flash \
--mem-compute 8
```

**Comment by aseok** [comment]
seems inconsistent with default memory parameters passed for training,
maybe missing something?
