### ISSUE TITLE
WARNING:  Unable to resolve breakpoint to any actual locations.

### ISSUE THREAD

**Issue by siddhsql** [ggerganov/llama.cpp#1858]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Hello, can anyone show me how to debug this program? This is what I am trying:

0. I am on macos
1. I first built the program with CMake using Debug configuration. I created a directory `build/debug` from the root. Then I ran following commands:
```
cmake -DLLAMA_METAL=ON ../..
cmake --build . --config Debug
```
my build log can be found [here](https://gist.github.com/siddhsql/815255228669ec1724374874e1298d09)
2. I then try to debug the program using `lldb` like this:

```
╰─⠠⠵ lldb main
(lldb) target create "main"
Current executable set to '/llm/llama.cpp/build/debug/bin/main' (x86_64).
```

3. The problem starts when I try to define a breakpoint:

```
(lldb) b /llm/llama.cpp/examples/main/main.cpp:54
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) b main.cpp:54
Breakpoint 2: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
```

what is wrong here and how can I fix it? I am not a C++ developer so sorry for asking basic question.

**Comment by SlyEcho** [comment]
`--config` option for `cmake --build` is for "multi-config" systems, of which I think I've seen only MSVC.

On Linux and Mac you should configure the build with the `CMAKE_BUILD_TYPE` variable, with `ccmake .` GUI tool, with the command `cmake . -DCMAKE_BUILD_TYPE=Debug` or just editing the CMakeCache.txt file.

After that build normally.

But I suggest using the mode `RelWithDebInfo` instead, because regular `Debug` is very slow.

**Comment by siddhsql** [comment]
Thanks Henri. yes that works.
