### ISSUE TITLE
Can't seem to load 65B Q4K_M models with Metal on Apple Max silicon with 64GB memory

### ISSUE THREAD

**Issue by Xonar92** [ggerganov/llama.cpp#1859]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

To load 65B models in the new quant types, specifically 65B Q4 K_M and use the GPU/Metal acceleration since the required amount of unified memory is in my system.

# Current Behavior

I am not sure if my issue is related to some other issues about Metal because there seem to be more issues related to Metal currently. I expect the 65B model to load into memory but it fails.

It is worth noting that I also use multiple other apps that use the latest llama.cpp code and they all seem to have the same behavior with the models ultimately not working/loading (or getting stuck at 30GB of loading into memory) with Metal and mLock enabled. The 64GB of unified memory should be more than enough to run these quantized 65B models so I am not sure what is going on.

# Environment and Context

M1 Macbook Pro Max 64GB, Latest MacOS ventura 13.4

**Comment by CyborgArmy83** [comment]
Hey there! I see you are having a similar problem and no one has replied to you yet. Please see here: https://github.com/ggerganov/llama.cpp/issues/1870#issuecomment-1593941659

It seems like we cannot use the full memory of our systems :(
