### ISSUE TITLE
How to? (install models)

### ISSUE THREAD

**Issue by dnelyubenko** [ggerganov/llama.cpp#188]
Hi, i can't find the models
Can u tell me, how i can install?
(ls ./models 65B etc is not working)
*sorry, my english isn't good)

**Comment by thezolon** [comment]
Those have to either be requested from Meta via their project sign up, or from leaked sources. They do not ship with the project.

Once you have the modules downloaded, and there is a github that has a script to help with that, you will need to put them in a folder called 'models', and then run the two commands in the main readme.md of this repository that will convert and quantinize the files to work with this project.

**Comment by dnelyubenko** [comment]
I can't find, cuz I'm in the region under sanctions
And my VPN doesn't work now :(

**Comment by tmzncty** [comment]
> Hi, i can't find the models Can u tell me, how i can install? (ls ./models 65B etc is not working) *sorry, my english isn't good)

如果你来自中国，请使用链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 
提取码：1p5n 
--来自百度网盘超级会员V4的分享
如果你来自其他国家，我还没上传到onedrive等，谷歌云盘暂时作为备份，不分享。
If you come from CHINA, please use this 链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 
提取码：1p5n 
--来自百度网盘超级会员V4的分享
If you come from another contury ,please wait me upland.

**Comment by xiliuya** [comment]
https://huggingface.co/datasets/nyanko7/LLaMA-65B/tree/main

**Comment by tmzncty** [comment]
![image](https://user-images.githubusercontent.com/72063145/225485940-243db2f8-7893-4b0c-b98e-6df05df423fd.png)在传了在传了

**Comment by tmzncty** [comment]
![image](https://user-images.githubusercontent.com/72063145/225486017-5ba28778-62b5-4e19-9ac1-fdcf0e467135.png)

**Comment by mikewii** [comment]
what you do with .pth files? llama executable requires .bin model

**Comment by tmzncty** [comment]
> what you do with .pth files? llama executable requires .bin model

Use convert-pth-to-ggml.py
May be you can read this https://www.bilibili.com/read/cv22434771
Or this https://github.com/ggerganov/llama.cpp/issues/103
.pth is real LLAMA, need to change to .bin
I am uploading them.
https://zl86n-my.sharepoint.com/:f:/g/personal/ticrawler_tmzn_top/EosXk2cjaGNKu_LdygSz7uMBQT8GHMWO14Y-0EqWhxphxw?e=7LdG9i

**Comment by tmzncty** [comment]
![图片](https://user-images.githubusercontent.com/72063145/225547272-35527103-aa2c-4e8f-96aa-48be69a776d0.png)
There are changed models.

**Comment by dnelyubenko** [comment]
> > Hi, i can't find the models Can u tell me, how i can install? (ls ./models 65B etc is not working) *sorry, my english isn't good)
> 
> 如果你来自中国，请使用链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 提取码：1p5n --来自百度网盘超级会员V4的分享 如果你来自其他国家，我还没上传到onedrive等，谷歌云盘暂时作为备份，不分享。 If you come from CHINA, please use this 链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 提取码：1p5n --来自百度网盘超级会员V4的分享 If you come from another contury ,please wait me upland.

I from Crimea and I'll be very grateful if u can upload through another service

**Comment by tmzncty** [comment]
> > > Hi, i can't find the models Can u tell me, how i can install? (ls ./models 65B etc is not working) *sorry, my english isn't good)
> > 
> > 
> > 如果你来自中国，请使用链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 提取码：1p5n --来自百度网盘超级会员V4的分享 如果你来自其他国家，我还没上传到onedrive等，谷歌云盘暂时作为备份，不分享。 If you come from CHINA, please use this 链接：https://pan.baidu.com/s/1Y7YWdFWX1Yzy2Yuujp8Tqg?pwd=1p5n 提取码：1p5n --来自百度网盘超级会员V4的分享 If you come from another contury ,please wait me upland.
> 
> I from Crimea and I'll be very grateful if u can upload through another service
> 
> UPD: tnx, files downloaded

[https://zl86n-my.sharepoint.com/:f:/g/personal/ticrawler_tmzn_top/EosXk2cjaGNKu_LdygSz7uMBQT8GHMWO14Y-0EqWhxphxw?e](https://zl86n-my.sharepoint.com/:f:/g/personal/ticrawler_tmzn_top/EosXk2cjaGNKu_LdygSz7uMBQT8GHMWO14Y-0EqWhxphxw?e=7LdG9i)

**Comment by pjq** [comment]
Actually, we can download the models with aria2
- https://github.com/facebookresearch/llama/pull/73
For download 7B:
```
aria2c --select-file 21-23,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'

```

**Comment by tmzncty** [comment]
YES, I want to let him download fasterly.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianqing ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 晚上6:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ggerganov/llama.cpp] How to? (install models) (Issue #188)





 
Actually, we can download the models with aria2
  
facebookresearch/llama#73
 For download 7B:
  aria2c --select-file 21-23,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&amp;dn=LLaMA'

**Comment by jart** [comment]
You can access the LLaMA model files by filling out the following form https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform to request Meta's permission to use it. That is the primary source of the primary materials. Please do not post links to alternative sources on this issue tracker. This issue tracker is for bugs and feature requests. Thank you!
