### ISSUE TITLE
Question : Perplexity computation of short (very short) prompt.

### ISSUE THREAD

**Issue by ZergCitizen** [ggerganov/llama.cpp#1882]
Hello,
I am interested in using the model to score multiple short prompts, each containing a maximum of 20-30 tokens, using perplexity. However, I have found that the main program does not support this feature. Additionally, the perplexity program seems to be designed to compute perplexity for large files, at least one chunk. Is there a way to compute perplexity for these concise prompts? Thank you.

**Comment by d-Tal** [comment]
You can change the batch and prompt context sizes with -b and -c respectively. Setting them both to the token length of the prompt works for me:

/perplexity -t 4 -m ~/Downloads/llama-7b.ggmlv3.q8_0.bin -p "Four score and seven years ago" -b 7 -c 7
[...clipped...]
perplexity: calculating perplexity over 1 chunks, batch_size=7
perplexity: 0.80 seconds per pass - ETA 0 minutes
[1]1.2943,

./perplexity -t 4 -m ~/Downloads/llama-7b.ggmlv3.q8_0.bin -p "Four score and seven bananas ago" -b 8 -c 8
[...clipped...]
perplexity: calculating perplexity over 1 chunks, batch_size=8
perplexity: 0.75 seconds per pass - ETA 0 minutes
[1]59.3287,
