### ISSUE TITLE
Implement Flash Attention Option

### ISSUE THREAD

**Issue by zoidbb** [ggerganov/llama.cpp#19]
Would love to see a faster, more memory efficient attention implemented like Flash Attention. :)

**Comment by ggerganov** [comment]
In `whisper.cpp` I tried using FA in the Decoder and it did not help (it does help a lot in the Encoder).
I guess it is a matter of the tensor sizes, but of course, maybe I didn't implement it properly.

https://github.com/ggerganov/whisper.cpp/pull/284

**Comment by Orevantum** [comment]
Is it possible to implement [multi-query attention](https://twitter.com/GuillaumeLample/status/1634587466416914433?s=09) then?

> In `whisper.cpp` I tried using FA in the Decoder and it did not help (it does help a lot in the Encoder). I guess it is a matter of the tensor sizes, but of course, maybe I didn't implement it properly.
> 
> [ggerganov/whisper.cpp#284](https://github.com/ggerganov/whisper.cpp/pull/284)

**Comment by xloem** [comment]
also note in flexgen they use top 10% sparse attention

**Comment by jamesbiederbeck** [comment]
> also note in flexgen they use top 10% sparse attention

Sparse attention is cool, but lossy. Flash attention is exact.
