### ISSUE TITLE
Question about new models

### ISSUE THREAD

**Issue by djtech-dev** [ggerganov/llama.cpp#1900]
Hi everybody,

I wanted to ask if it was possible to train a new model from a series of text files, either starting from scratch or starting (with a process similar to fine-tuning) from a pre-existing model compatible wiht llama.cpp

Thanks in advance.

**Comment by SlyEcho** [comment]
There is [train-text-from-scratch](https://github.com/ggerganov/llama.cpp/tree/master/examples/train-text-from-scratch) but it's early days still.

**Comment by djtech-dev** [comment]
Thanks, I'll check it out

**Comment by djtech-dev** [comment]
Is it also possible to fine-tune models?
