### ISSUE TITLE
Use llama.cpp to load the model on Android Termux

### ISSUE THREAD

**Issue by TangYuanMaster** [ggerganov/llama.cpp#1906]
This problem occurred when I tried to load ggml-7B-q4_1.bin with llama.cpp.
![image](https://github.com/ggerganov/llama.cpp/assets/109419998/5a354ab2-2b7c-42bd-9e3a-f10f7ab58edd)

**Comment by JackJollimore** [comment]
> This problem occurred when I tried to load ggml-7B-q4_1.bin with llama.cpp. ![image](https://user-images.githubusercontent.com/109419998/246588579-5a354ab2-2b7c-42bd-9e3a-f10f7ab58edd.jpeg)

Hi,

Without more information then I guess lack of ram, or incompatible model. To figure it out then please help me understand: 

1. How did you build llama.cpp? (make or  cmake?)

2. What's the # of physical cores in your device? Ram? What version Termux? (playstore or fdroid?)

3. What model is that? There are 7B GGML models that are not yet compatible with llama.cpp, like MPT.
