### ISSUE TITLE
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."

### ISSUE THREAD

**Issue by SignalRT** [ggerganov/llama.cpp#1912]
**Running the main demo it works when compiling with static libraries:**

cmake -DLLAMA_METAL=ON ..

**And it fails with the error "The file name is invalid":**

cmake -DLLAMA_METAL=ON -DLLAMA_STATIC=Off -DBUILD_SHARED_LIBS=ON  ..

Any idea to solve that issue?

**Comment by SignalRT** [comment]
I know, and it doesn't work.

**Comment by SignalRT** [comment]
**When running with the dynamic link library this is the output:**

**ggml_metal_init: loading '(null)'**
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."

**When running with static build:**

llama_init_from_file: kv self size  =  400,00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
**ggml_metal_init: loading 'xxxx/llama.cpp/build-metal/bin/ggml-metal.metal'**

**sgml-metal.metal exist in both cases in the directory.**

**Comment by djosh34** [comment]
And for my context, the library is also in the same bin folder? Or if it is in another folder did you try copying the ggml-metal.metal over there?

**Comment by SignalRT** [comment]
The library is in the same bin folder. The output of the build in both cases.

**Comment by SignalRT** [comment]
My fault, I was testing this in the wrong way

**Comment by siddhsql** [comment]
> the ggml-metal.metal file needs to be in the same directory as your executable

I am getting this same error. I have verified I have ggml-metal.metal file in the same directory as my executable. please see below:

```
 ⚡  ls build/release/bin
baby-llama              perplexity              test-grad0
benchmark               q8dot                   test-quantize-fns
embd-input-test         quantize                test-quantize-perf
embedding               quantize-stats          test-sampling
ggml-metal.metal        save-load-state         test-tokenizer-0
main                    server                  train-text-from-scratch
metal                   simple                  vdot
```

this is the error log:

```
⚡  ./scripts/run-main.sh
+ ./main -m /Users/xxx/.cache/huggingface/hub/models--thebloke--gpt4-x-vicuna-13B-GGML/gpt4-x-vicuna-13B.ggmlv3.q5_1.bin -c 2048 --repeat_penalty 1.0 --color -i -r User: --in-prefix ' ' -ngl 40 -f /Users/xxx/github/llama.cpp/scripts/../prompts/chat-with-bob.txt
main: build = 805 (84525e7)
main: seed  = 1688756911
llama.cpp: loading model from /Users/xxx/.cache/huggingface/hub/models--thebloke--gpt4-x-vicuna-13B-GGML/gpt4-x-vicuna-13B.ggmlv3.q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 11359.06 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  = 1600.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
```

**Comment by Spandyie** [comment]
were you able to resolve this error ? I a getting similar error

**Comment by rozek** [comment]
FYI: i just ran into this problem as well (Macbook Air 15", M2 processor), found this thread and the need for `ggml-metal.metal`.

The solution surprised me as compiling `llama.cpp` with Metal support generated files named `ggml-metal.m` and `ggml-metal.o` rather than `ggml-metal.metal` (which I had since Aug, 2nd) - but copying `ggml-metal.metal` solved the problem...

Now I'm wondering what `ggml-metal.m` and `ggml-metal.o` are good for...

But, hey, my MBA became so incredibly fast now, that I do not really worry...
