### ISSUE TITLE
Investigate PagedAttention KV-cache memory management for faster inference

### ISSUE THREAD

**Issue by Azeirah** [ggerganov/llama.cpp#1955]
New research just came out on using a technique inspired by kernel virtual memory and pages to manage the KV cache.

Results? Way faster inference!

https://vllm.ai/

They claim up to 24x the throughput (measured in requests handled per second) compared to huggingface's transformers library

![afbeelding](https://github.com/ggerganov/llama.cpp/assets/4040870/0388704e-5924-42d6-a3d4-2e4625268389)

## How?

Inference is bottlenecked by memory, most notably the KV cache. They say the KV cache's most notable features are

- That it's very large
- That it's dynamic, size depends on sequence length which is variable. Existing systems waste 60-80% of memory due to fragmentation and over-reservation

PagedAttention is an alternative approach to managing the KV cache which is inspired by virtual memory, pages and blocks. By allocating the space dynamically with this approach, only up to about 4% of memory will be wasted, instead of the aforementioned 60-80.

For further details, better refer to their [website](https://vllm.ai/) and [Github](https://github.com/vllm-project/vllm).

**Comment by JohannesGaessler** [comment]
llama.cpp currently only ever serves one user at a time so this optimization is not applicable.

**Comment by nivibilla** [comment]
I assume it would be useful if we want to host the models and have a interface like chat.openai.com?

**Comment by Azeirah** [comment]
> llama.cpp currently only ever serves one user at a time so this optimization is not applicable.

Oh I wasn't aware this was exclusively for a client-server application, that explains why they measure performance in requests/sec 🥲

**Comment by howard0su** [comment]
this optimization is still applicable as it can save vram usage of kv tensor.

**Comment by nivibilla** [comment]
If we do end up building this for server use and I think that would be a good idea. Then this paging system would be very useful.

**Comment by howard0su** [comment]
Read through the blog and the code. It turns out the paged attention is a way to manage the memory so that the compute kernel doesn't require kv have to be continues. This make it possible that you can have one prompt's kv append by multi output's KVs. like the following

Prompt KV Block ------ Output 1 KV Block
                            ------ Output 2 KV block
                              ....
This is super helpful if your prompt is long and you need to output multi results. This is a purely engineering trick. The change is mainly around the how we manage the KV in VRAM. If we are using CPU, this is even simpler to implement. (simple as list v.s. vector)

**Comment by slaren** [comment]
We allocate all the KV memory required for the maximum context length on startup in one block, so we shouldn't have any fragmentation either.

**Comment by randxie** [comment]
@JohannesGaessler Is serving multiple users concurrently or batch inference on the roadmap of llama.cpp?

**Comment by JohannesGaessler** [comment]
I don't have any plans for it because I don't care about commercial use but I can't speak for the other devs.

**Comment by okpatil4u** [comment]
Should it not be on the list ?

Today we are talking about chatbots, in 6 months or so, people will start
looking for autonomous agents.

Would it not make sense to build a system that can process multiple
requests simultaneously and efficiently ?

**Comment by nivibilla** [comment]
Yeah, I think first we need to solve batch inference. It's implemented in babyllama but I'm haven't tried to port it over to the main llama yet

**Comment by JohannesGaessler** [comment]
I'm not really concerned with what other people want to use llama.cpp for. I'm implementing things that are useful for me personally first and foremost. And I don't see how I would benefit from batched inference since I only run llama.cpp for myself on my own hardware.

**Comment by nivibilla** [comment]
That's fair, batch inference would be useful for me use this at scale. For example if I want to do sentiment analysis for a large dataset or summarisation at scale.

**Comment by nivibilla** [comment]
And in this case having a server to handle multiple users at the same time

**Comment by vikigenius** [comment]
I have a comparison for the pytorch implementations with and without paging on a single GPU and the gains are significant. My use case is primarily batch inference, so I am not sure about model serving.

WIth a 40 GB A100 GPU

Inference on a vicuna-13B model without paged attention produces 20 tokens / sec
Inference on a vicuna-13B model with paged attention produces 190 tokens / sec

So the speedup is almost 10x. Obviously this is a bit skewed because our workload involves using the same initial prompt prefix in a batch inference setting so there might be good reuse of the KV cache which is helped by Paged Attention.

**Comment by okpatil4u** [comment]
Thanks Vikash. You mentioned in another thread, that there may be some misalignment in terms of understanding, in this thread, on how vllm works. Could you please explain what you meant by it ?

Also, there have been other comments in terms its effect on CPU, GPU and Mac M1/M2 GPU in terms of performance. Could you or someone else shed some light on it ?

**Comment by keeganmccallum** [comment]
From what I understand this isn't so much related to multi-user/client-server use case so much as it it is batched inference, which does seem to be a valid use case even for single-user/local apps, depending on the use case

**Comment by chrfalch** [comment]
Wouldn’t the decreased memory requirement (they state that they cut 55% memory usage) be positive when running inference on smaller devices like phones and laptops as well?

**Comment by FNsi** [comment]
Should be useful if there's a large context.

**Comment by viktor-ferenczi** [comment]
Both vLLM and lmDeploy have high throughput batch-inference modes with various tricks. Problem is they don't support GGUF.

How complex would it be to port those tricks (KV cache paging, dynamic batching) to llama.cpp?

**Comment by KerfuffleV2** [comment]
#2813 - still need to implement the non-tricky version.

Related, there's #2969 - also should be a 50% memory use reduction.

**Comment by kiratp** [comment]
#2813 only covers "same prompt, multiple output", not "multiple prompt, multiple output".

**Comment by henk717** [comment]
Would like to voice my support for this, over at the KoboldAI community we had requests for multi-user support and it would also help out our Horde platform which currently benefits from TGI's speed but TGI has poor output for us compared to Llamacpp.

Having Llamacpp be fast for these use cases means multiple communities would begin using it as a general purpose inference server which would be a cool addition for the project.

**Comment by tikikun** [comment]
I think this feature is important to make llama cpp usage spread even more

**Comment by viktor-ferenczi** [comment]
Which one would be easier? Porting performance/throughput tricks into llama.cpp or porting GGUF support into vLLM? 

(lmDeploy is out of the picture, since they don't want to support GGUF. They closed the feature request / suggestion ticket with the reason that they want to concentrate on other things instead.)

**Comment by randxie** [comment]
IMO, implementing the same idea inside llama.cpp is much better. Currently, vllm leverages Pytorch extension to customize the attention kernel. One benefit of llama.cpp is that it gets rid of pytorch and is more friendly to edge deployment.

We can consider porting [the kernels in vllm](https://github.com/vllm-project/vllm/blob/main/csrc/attention/attention_kernels.cu#L74C17-L74C23) into llama.cpp. It probably requires a certain amount of refactoring in llama.cpp though..

**Comment by bobqianic** [comment]
#3479

**Comment by naik-amey** [comment]
Where is the KVCacheManager implemented, is it on the GPU or host (CPU)?

**Comment by 64933988** [comment]
很多的一项优化，居然没有人想集成进来！！！

**Comment by phymbert** [comment]
> 很多的一项优化，居然没有人想集成进来！！！

Please discuss in english here, and would you please elaborate which feature as of today no one want to integrate ?

**Comment by K-Mistele** [comment]
Worth re-opening? the `server` executable can handle multiple users at a time so it seems like this would be a really valuable thing to add.

**Comment by YanlinWangWang** [comment]
> Worth re-opening? the `server` executable can handle multiple users at a time so it seems like this would be a really valuable thing to add.

And it can help reduce gpu-memory usage.I think it's time to start work

**Comment by jkrauss82** [comment]
A year has passed, any update on this?

I am getting a little jealous when seeing benchmarks like this ([source HF](https://huggingface.co/spaces/textgeflecht/inference-benchmarking-results-phi4-200-tokens), [source Reddit](https://www.reddit.com/r/LocalLLaMA/comments/1kscn2n/benchmarking_fp8_vs_ggufq8_on_rtx_5090_blackwell/)): 

![Image](https://github.com/user-attachments/assets/2856263e-34d4-4732-bd7e-4bf8715476d2)

**Comment by JohannesGaessler** [comment]
Batched inference performance has since become more of a priority for me since I started a project for [benchmarking language models](https://github.com/JohannesGaessler/elo_hellm). For my use case in particular I think paged attention is the wrong solution, though it can be expected that there will be synergies in terms of the CUDA code.

In general there has recently been more effort within the project to improve performance for a usage scenario with one server and many users.

**Comment by celsowm** [comment]
![Image](https://github.com/user-attachments/assets/03132709-9e27-4517-a6ab-c80a0bf594db)

I am currently trying jules to implement a PagedAttention KV-cache implementation

**Comment by yadirhb** [comment]
So, this got closed ... any updates?

**Comment by Aaryan-Kapoor** [comment]
+1 :)

**Comment by ThalusA** [comment]
+1

**Comment by Nakanokensetsu** [comment]
異種GPU環境での並列推論を突き詰めた結果、現状の最適解としてExLlamaV3へ移行しました。llama.cppと比較して並列スループットの性能差は圧倒的で、実務環境では比べるべくもないという結論です。

本件、llama.cppに対して特に改善を期待していた、あるいは課題と感じている点は以下の通りです。

1. 並列スループットのアーキテクチャ的限界
異種GPU構成において、llama.cppの並列処理はExLlamaV3等の専用バックエンドと比較すると効率で大きく劣ります。特にスループットを求めるワークロードでは、llama.cppの設計思想がボトルネックになっていることは明らかです。

2. 「Slot Up」にかかる深刻なオーバーヘッド
現在のllama.cpp最大の欠点は、コンテキスト初期化およびKVキャッシュ確保（Slot Up）に要する時間の長さです。推論を開始するたびにこの時間を強制されるのは実務上極めて非効率であり、長年指摘されながらも未だ根本的な改善が見られない点は、高頻度で推論を行う環境においては致命的な無駄です。

3. CPUオフロードに対する切実なニーズ
個人的には、GPUメモリが溢れた際にも並列性を維持できるような「CPUオフロードの高度な実装」を期待していました。現状の設計を見る限り、今後もこの機能が実装される可能性は低そうですが、これが実現すればllama.cppの活用の幅はより広がっていたはずであり、非常に残念です。

現在、Dflashの適用などを行い環境を調整中ですが、llama.cppが目指す汎用性やCPUオフロードの利便性と、私たちが求める高スループットな並列推論環境は、現時点では明確にトレードオフの関係にあります。

llama.cppが今後、この「並列推論時のスロット確保の遅延」を解消するアーキテクチャへの刷新を行うのか、あるいはこのまま汎用重視の路線を進むのか、非常に注目しています。同じような課題を感じ、環境移行を進めている方や、代替案がある方の意見を伺いたいです。

**Comment by maikelthedev** [comment]
Now that there's a parallel = 4 and usable Web UI I this seems very applicable to llama.cpp

Let alone running sub-agents inside any harness.
