### ISSUE TITLE
Improve experience running models that don't individually fit in RAM or VRAM by freeing GPU offloaded layers

### ISSUE THREAD

**Issue by IgnacioFDM** [ggerganov/llama.cpp#1964]
Edit: This is already implemented [here](https://github.com/ggerganov/llama.cpp/blob/bbca06e26949686d61a5126332680ba3cccf235c/llama.cpp#L799), you need to use `--no-mmap`

Right now you can use GPU offloading to run models that individually wouldn't fit in RAM or VRAM. For instance, a 65B 4bit model cannot reasonably be run solely on a CPU with 32GB RAM, or solely on a 24GB GPU.

However, by utilizing some GPU layers, a system with 32GB RAM + 24GB VRAM can successfully run a 65B 4bit model at ~1.5 tokens/s.

Currently, this approach works well because even though llama.cpp will allocate the whole thing into RAM, and memory paging will be required, the GPU offloaded layers aren't accessed by the CPU. As a result, the OS keeps the offloaded layers on disk, and the non-offloaded in physical memory. So there will be no performance hit and no swap access after model loading.

The downside is that the OS is not very happy in this scenario, and any other process will have to fight to be kept in physical memory. So although llama.cpp will run fine, the PC will be quite unresponsive.

If the GPU offloaded layers were freed after model loading, it would drastically improve system performance, since the OS would not have to guess what to keep in physical memory and what to page to disk.

This would help the following scenarios:
65B 4bit models on 32GB RAM + 24GB VRAM (my setup)
33B 4bit models on 16GB RAM + 12GB VRAM (untested)

**Comment by lorenzoFIS** [comment]
@IgnacioFDM what speed do you get when you run q3_K_S 65B model with just your cpu? This one is at 1.3-1.5 t/s for me on 32gb ram, 28.9/31.3G on ubuntu. 

I didn't test yet with adding the gpu (3090)

**Comment by IgnacioFDM** [comment]
Never mind, this is already [implemented here](https://github.com/ggerganov/llama.cpp/blob/bbca06e26949686d61a5126332680ba3cccf235c/llama.cpp#L799). You need to use --no-mmap if you want offloaded layers to be freed. Also I believe I'm seeing quite significant performance improvements, I'll keep testing.

**Comment by IgnacioFDM** [comment]
Running a q4_K_M model with `--gpu-layers 45 --no-mmap` I get 1.93t/s on my 3090, with only 32GB of system RAM.

It uses around 22GB of system RAM, and 22GB of VRAM. I'd probably need to decrease a couple of layers, or use `-lv` in order to handle larger context sizes (untested).

I think this is a relatively underappreciated way to run 65B 4bit models, often considered too big for consumer hardware, assuming you don't need fast responses.
