### ISSUE TITLE
[Termux] ggml_opencl error on clGetPlatformIDs

### ISSUE THREAD

**Issue by albbus-stack** [ggerganov/llama.cpp#1969]
I set up a Termux installation following the FDroid instructions on the readme, I already ran the commands to set the environment variables before running `./main`.

Here is a screenshot of the error:
![WhatsApp Image 2023-06-22 at 21 01 17](https://github.com/ggerganov/llama.cpp/assets/57916483/fba5dd55-7ff8-4c94-a518-344ae6bbcd30)

I suspect it's an OOM error but I cannot be sure since I'm using the smallest ggml model possible.

**Comment by JackJollimore** [comment]
> I set up a Termux installation following the FDroid instructions on the readme, I already ran the commands to set the environment variables before running `./main`.
> 
> I suspect it's an OOM error but I cannot be sure since I'm using the smallest ggml model possible.

Yeah, the readme is inconsiderate, but the model you're attempting is 258MB, so I doubt it's a memory issue.

The error means that llama.cpp tried to use OpenCL on your device, but it failed.

Try like this
`
LD_LIBRARY_PATH=/vendor/lib64 ./main -m ~/llama.cpp/models/ggml-model-gpt-2-117M.bin -p "Hi" -n 128
`
add -i if you want to interact with the model after the prompt.

**Comment by albbus-stack** [comment]
@JackJollimore Thank you! Now the error has changed:

`llama.cpp: loading model from /data/data/com.termux/files/home/llama.cpp/models/ggml-model-gpt-2-117M.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/data/data/com.termux/files/home/llama.cpp/models/ggml-model-gpt-2-117M.bin'
main: error: unable to load model`

The model is directly downloaded from ggerganov's hugging face.

**Comment by JackJollimore** [comment]
> The model is directly downloaded from ggerganov's hugging face.

Sorry, it's incompatible. Try something like open llama 3b ggml.

**Comment by albbus-stack** [comment]
@JackJollimore Yep that was it. It works with ggml-openllama-3b-350bt-q4_0.bin

Do you know of any other compatible model that is smaller than this?

**Comment by JackJollimore** [comment]
> @JackJollimore Yep that was it. It works with `ggml-openllama-3b-350bt-q4_0.bin`
> 

I'm glad it works. I'd use SlyEchos ggml.


> Do you know of any other compatible model that is smaller than this?

Nope, sorry.


> It is also saying that no layers are offloaded to the gpu

To offload onto the GPU then add the -ngl # parameter to main. If the entire model fits inside VRAM then it's better to offload all layers like this:
`
-ngl 100
`

For my device, offloading _slows_ inference, so you may have to test and see what's best for your device.


Without offloading, here's some parameters which may improve the inference for you:
`
/main -m ~/llama.cpp/models/ggml-openllama-3b-350bt-q4_0.bin -t 4 -b 10 -p "Hi"
`

-t or --threads can me modified from 1~8 on your device, but 3 or 4 is probably best. 

Close all background applications - no web browser or anything.

Finally, ensure to  _move_ the model from the downloads folder to ~/llama.cpp/models as loading from the downloads folder decreases performance.

**Comment by albbus-stack** [comment]
@JackJollimore Thank you a lot! With 8 threads is noticeably faster (even more than 4) and with gpu inference, as you said, is way slower. I'm going to make a PR to update the readme instructions asap
