### ISSUE TITLE
[dejimarquis] Convert.py ''unknown format: models/open_llama_7b/pytorch_model-00001-of-00002.bin"

### ISSUE THREAD

**Issue by dejimarquis** [ggerganov/llama.cpp#1994]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

convert.py should convert the model weights to the appropriate file type

# Error

python3 convert.py ./models/open_llama_7b 
Loading model file models/open_llama_7b/pytorch_model-00001-of-00002.bin
Traceback (most recent call last):
  File "/Users/x/repos/llama.cpp/convert.py", line 1225, in <module>
    main()
  File "/Users/x/repos/llama.cpp/convert.py", line 1205, in main
    model_plus = load_some_model(args.model)
  File "/Users/x/repos/llama.cpp/convert.py", line 1126, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/Users/x/repos/llama.cpp/convert.py", line 924, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
**ValueError: unknown format: models/open_llama_7b/pytorch_model-00001-of-00002.bin**

**Comment by samho93** [comment]
i having the same problem here

**Comment by michaelbauerinc** [comment]
same here

**Comment by rolandtannous** [comment]
Guys the reason this is not working is because you're missing the GIT large file support module.
If you go into your model directory and do ``` ls -alh```, you'll notice that your .bin files are very small in the order of 130 Bytes. They should be at least 3.5GB.

To solve this, if you're on mac:

- [ ] delete the current model directory
- [ ] install git-lfs using brew on mac: ```brew install git-lfs```
- [ ] run this command ```git lfs install```
- [ ] git clone the model again
- [ ] run the convert.py script.

It should work.

If you're on linux replace step 2 with : 

- [ ] sudo apt-get install git-lfs

Happy hunting.

**Comment by michaelbauerinc** [comment]
> Guys the reason this is not working is because you're missing the GIT large file support module. If you go into your model directory and do ` ls -alh`, you'll notice that your .bin files are very small in the order of 130 Bytes. They should be at least 3.5GB.
> 
> To solve this, if you're on mac:
> 
> * [ ]  delete the current model directory
> * [ ]  install git-lfs using brew on mac: `brew install git-lfs`
> * [ ]  run this command `git lfs install`
> * [ ]  git clone the model again
> * [ ]  run the convert.py script.
> 
> It should work.
> 
> If you're on linux replace step 2 with :
> 
> * [ ]  sudo apt-get install git-lfs
> 
> Happy hunting.

This is the solution, tyvm!
