### ISSUE TITLE
Running " python3 convert-pth-to-ggml.py models/7B/ 1 " and running out of RAM

### ISSUE THREAD

**Issue by WeissAzura** [ggerganov/llama.cpp#200]

**Comment by a-nayeem** [comment]
If you are using linux, you can solve this by using a large swap memory. You can use the following commands to create temporary swap memory in your / directory.

`sudo dd if=/dev/zero of=/swapfile bs=4M count=5120 status=progress`
`sudo mkswap /swapfile`
`sudo swapon /swapfile`

If you continue to face the same problem, try increasing the count value of first command and double it.

**Comment by WeissAzura** [comment]
@a-nayeem Thanks, it works like a charm on my pc but not on google colab because you can't create swap file on the instance

**Comment by conorwsullivan** [comment]
> I am in WSL, someone knows how to solve this in this context ?

Use the same swapon trick shared above, it works fine as long as you have enough hard drive space. But it is slow. There is a warning about permissions (644 vs 600) but there doesn't seem to be a problem. Open a second terminal and use the command "free" to see how much memory and swap is being used.

**Comment by royokello** [comment]
Created 100gb swap, still produces a 'killed' message after running for some time.

**Comment by solispauwels** [comment]
On my case (wsl2) I solve this by using the .wslconfig file and increasing there the swap size, so no need of swapon.

**Comment by dagelf** [comment]
@royokello you can `sudo systemctl stop systemd-oomd.service` if you're on most Linuxes. OOM is the Out-of-Memory killer which starts pruning processes that take up too much RAM.
