### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by flippercy** [ggerganov/llama.cpp#2024]
In file included from ggml.c:7:0:
k_quants.h:32:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q2_K) == 2*sizeof(ggml_fp16_t) + QK_K/16 + QK_K/4, "wrong q2_K block size/padding");
               ^~~~~~
k_quants.h:32:79: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q2_K) == 2*sizeof(ggml_fp16_t) + QK_K/16 + QK_K/4, "wrong q2_K block size/padding");
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.h:53:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q3_K) == sizeof(ggml_fp16_t) + QK_K / 4 + QK_K / 8 + 12, "wrong q3_K block size/padding");
               ^~~~~~
k_quants.h:53:85: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q3_K) == sizeof(ggml_fp16_t) + QK_K / 4 + QK_K / 8 + 12, "wrong q3_K block size/padding");
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.h:74:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q4_K) == 2*sizeof(ggml_fp16_t) + K_SCALE_SIZE + QK_K/2, "wrong q4_K block size/padding");
               ^~~~~~
k_quants.h:74:84: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q4_K) == 2*sizeof(ggml_fp16_t) + K_SCALE_SIZE + QK_K/2, "wrong q4_K block size/padding");
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.h:97:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q5_K) == 2*sizeof(ggml_fp16_t) + K_SCALE_SIZE + QK_K/2 + QK_K/8, "wrong q5_K block size/padding");
               ^~~~~~
k_quants.h:97:93: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q5_K) == 2*sizeof(ggml_fp16_t) + K_SCALE_SIZE + QK_K/2 + QK_K/8, "wrong q5_K block size/padding");
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.h:110:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q6_K) == sizeof(ggml_fp16_t) + QK_K / 16 + 3*QK_K/4, "wrong q6_K block size/padding");
               ^~~~~~
k_quants.h:110:81: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q6_K) == sizeof(ggml_fp16_t) + QK_K / 16 + 3*QK_K/4, "wrong q6_K block size/padding");
                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.h:118:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(block_q8_K) == sizeof(float) + QK_K + QK_K/16*sizeof(int16_t), "wrong q8_K block size/padding");
               ^~~~~~
k_quants.h:118:85: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(block_q8_K) == sizeof(float) + QK_K + QK_K/16*sizeof(int16_t), "wrong q8_K block size/padding");
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:263: ggml.o] Error 1

What shall I do to fix this installation error, please?

**Comment by evanmiller** [comment]
This might be fixed by replacing `static_assert` with `_Static_assert`

https://en.cppreference.com/w/c/language/_Static_assert

**Comment by EvolventaAGG** [comment]
I've run into this issue while trying to compile llama-cpp-python for oobabooga  in conda env using gcc/gxx installed from conda-forge. None of conda-issued versions of gcc compiler worked for me, tried 11.3.0 up to 13.1.0, and they all gave that error.

Removing conda-forge gcc and reverting to system-wide gcc fixed it (in my case version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1, but I suspect any will work. And yes, conda-forge gcc was ver was 11.3.0, too) 

Messing with llamacpp source seemed both excessive and unsustainable.

**Comment by carygravel** [comment]
I've got this error, also using gcc and gxx from conda-forge. However, my system compiler is too old and I can't change it. Any other suggestions?

**Comment by AoZhang** [comment]
> I've got this error, also using gcc and gxx from conda-forge. However, my system compiler is too old and I can't change it. Any other suggestions?

I meet the same problem.
any other solution except compile a gcc/g++ by hand?
