### ISSUE TITLE
Model runs but doesn't produce any output

### ISSUE THREAD

**Issue by michaelk77** [ggerganov/llama.cpp#204]
I checked everything several times and quantized it, but both models do not output anything, in which mode I would not run them, the processor loads, but there is no output, no matter how long I wait
 input to the console also does not lead to anything

for ubuntu 22.04 8gb+15 swap (everything fits)

![Снимок экрана от 2023-03-16 11-42-21](https://user-images.githubusercontent.com/93709232/225592978-99f3c8a6-85a0-4606-a39d-6ddc1e334778.png)

**Comment by gjmulder** [comment]
It is hard to see from your screenshots. Properly formatted markdown of your complete run would make it easier to see what you're doing.

It does however look like you are running in interactive mode?

**Comment by michaelk77** [comment]
> I was just having this issue, what resolved it was pulling latest to get a ggml.c change & re-running make

thanks it worked for me, even with old models, I don't know what went wrong the first time, but now everything is super
