### ISSUE TITLE
"start reply with" option 

### ISSUE THREAD

**Issue by EdwardDali** [ggerganov/llama.cpp#2040]
is there any 'start reply with' option? oobabooga has this option
I use llama.cpp directly from command line

**Comment by JackJollimore** [comment]
> is there any 'start reply with' option? oobabooga has this option I use llama.cpp directly from command line

Hi, I'm not familiar with oobabooga. It might help if you describe what you want to make llama.cpp do.

What's your ./main prompt? What parameters are you trying? Have you checked ./main -h?


Without more information, then I guess you're looking for the -p or --prompt parameter. For example,
`./main -m ~/llama.cpp/model/your-ggml.bin -p "You are an A.I."
`

**Comment by EdwardDali** [comment]
Hi,
Thanks for the quick reply. What I'm looking for is similar to the prompt option but is not for the user's input but for the response output. The model's response should start with something like "Sure thing!".
Below the code for the bat file that I'm using:
title llama.cpp
:start
main -i --interactive-first -r "### Human:" --temp 0 -c 2048 -n -1 --ignore-eos --repeat_penalty 1.2 --instruct --color --threads 3 -m camel-13b-combined.ggmlv3.q5_K_M.bin
pause
goto start

**Comment by abc-nix** [comment]
See https://github.com/ggerganov/llama.cpp/tree/master/examples/main#in-suffix

You would use --in-suffix "### Assistant: Sure thing!"

Is that what you are looking for?

**Comment by JackJollimore** [comment]
> You would use --in-suffix "### Assistant: Sure thing!"
> 

I agree with this. Also remove --interactive-first, otherwise llama.cpp will require your input.

**Comment by EdwardDali** [comment]
Sure thing! this is what I was looking for :)
