### ISSUE TITLE
Training Custom using train-text-from-scratch

### ISSUE THREAD

**Issue by archit0** [ggerganov/llama.cpp#2049]
Hi.

I have been trying to train some custom data using the base model file: open-llama-7B-open-instruct.ggmlv3.q4_0.bin

Here is the command Im running

`./bin/train-text-from-scratch \
        --vocab-model ../models/ggml-vocab.bin \
        --ctx 64 --embd 256 --head 8 --layer 16 \
        --checkpoint-in  ik.bin \
        --checkpoint-out ik.bin \
        --model-out ik.bin \
        --train-data ik.txt \
        -t 6 -b 16 -n 32 --seed 1 --adam-iter 16 \
        --print-details-interval 0 --predict 16 \
        --mem-model 12 --mem-compute 12  --use-flash`

I'm able to train the data but I have following 2 concerns:

1. How Can I pass multiple text files instead of 1 text file? I have about 1 lakh+ text file which I need to train the model. Should I combine the text files?
2. I have a GPU of 24GB VRAM. But its not able to utilize more than 1gb and hence the process of training is slow.

**Comment by daboe01** [comment]
how do you manage to train on a specific base model? afaik train-text-from-scratch does not load a base model but starts with an empty (random) model.

**Comment by NalaGinrut** [comment]
You may concatenate training data with `cat file-1 file2 > all-file`.

BTW, maybe you need `-m ../models/open-llama-7B-open-instruct.ggmlv3.q4_0.bin` for loading base model that you mentioned but didn't load.
