### ISSUE TITLE
a bit confused about this in function ggml_cl_mul_f32

### ISSUE THREAD

**Issue by gotope** [ggerganov/llama.cpp#2050]
static void ggml_cl_mul_f32(const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
    GGML_ASSERT(src1->backend == GGML_BACKEND_GPU);
    const int64_t ne00 = src0->ne[0];
    const int64_t ne01 = src0->ne[1];
    const int64_t ne02 = src0->ne[2];
    const int64_t ne03 = src0->ne[2];     //  is ne03 the same as ne02 ?

**Comment by ggerganov** [comment]
Looks like a bug

**Comment by 0cc4m** [comment]
Yes, this is a bug that has never caused an issue cause we only use 2D matrices at the moment. You can make a PR to fix it or I'll do it eventually.

**Comment by gotope** [comment]
@0cc4m,  PR   https://github.com/ggerganov/llama.cpp/pull/2088

**Comment by howard0su** [comment]
the PR is committed
