### ISSUE TITLE
[User] Insert summary of your issue or enhancement..

### ISSUE THREAD

**Issue by paillave** [ggerganov/llama.cpp#2085]
Hello,

On the main page, you mention the following: "This project is for educational purposes". 

Want makes it, according to you, not suitable for real world situations and production environments?

Thanks.

**Comment by JackJollimore** [comment]
> Want makes it, according to you, not suitable for real world situations and production environments?
> 

If you genuinely want a response then I suggest posting in the discussion section as there's no technical issue, or enhancement details in your message.

**Comment by paillave** [comment]
I created a discussion: https://github.com/ggerganov/llama.cpp/discussions/2089
