### ISSUE TITLE
LLAMA_BUILD_SERVER=1 make command execution error

### ISSUE THREAD

**Issue by stoneLee81** [ggerganov/llama.cpp#2096]
I execute the LLAMA_BUILD_SERVER=1 make command in the root directory of the llama.cpp project， But compilation fails with below error

> I llama.cpp build info:
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_K_QUANTS -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS
I LDFLAGS:   -framework Accelerate
I CC:       Apple clang version 14.0.3 (clang-1403.0.22.14.1)
I CXX:      Apple clang version 14.0.3 (clang-1403.0.22.14.1)

make: *** No rule to make target `private', needed by `server'.  Stop.

I don't know what went wrong, causing the failure

os: Ventura 13.4.1 m1max 
gcc: Apple clang version 14.0.3 (clang-1403.0.22.14.1)

**Comment by Green-Sky** [comment]
try to install gmake via brew, or use the cmake project

**Comment by SlyEcho** [comment]
It's caused by Apple using a very old GNU Make version.

**Comment by SlyEcho** [comment]
@Green-Sky, I planned to fix this, I will make a quick PR, alright?
