### ISSUE TITLE
Simultaneous interactive and instruction mode to extend/improve model?

### ISSUE THREAD

**Issue by FrankDMartinez** [ggerganov/llama.cpp#2108]
Hi.

I hope you are having a great new year so far.

Is there currently a way to load a model in interactive model and toggle back and forth between interactive and instruct modes, allowing the interaction to improve said model?

If so, is there a way to do this in a persistent chat?

Thanks in advance.

**Comment by JackJollimore** [comment]
> Is there currently a way to load a model in interactive model and toggle back and forth between interactive and instruct modes, allowing the interaction to improve said model?
> 
> If so, is there a way to do this in a persistent chat?
> 
> Thanks in advance.

Hello, 

--instruct internally prefixes user input with  `### Instruction:` followed by `### Response:` whereas --interactive provides more of a _fluid_ conversation. Here's [Interaction Options](https://github.com/ggerganov/llama.cpp/blob/31cfbb1013a482e89c72146e2063ac4362becae7/examples/main/README.md?plain=1#L90).


It's possible to train a model. Here's [example usage](https://github.com/ggerganov/llama.cpp/blob/31cfbb1013a482e89c72146e2063ac4362becae7/examples/train-text-from-scratch/README.md?plain=1#L1).

**Comment by FrankDMartinez** [comment]
@JackJollimore I saw that, thanks. I’m talking about being able to temporarily enter instruct mode while in interactive mode; is there a way to do that?

**Comment by JackJollimore** [comment]
> I’m talking about being able to temporarily enter instruct mode while in interactive mode; is there a way to do that?

Ah, now I see what you mean. Currently there's no way to swap between modes.
