### ISSUE TITLE
Compatibility with aws inf1/2 instances

### ISSUE THREAD

**Issue by sonic182** [ggerganov/llama.cpp#2109]
Is it compatible with aws infer instances??

Please see

* https://aws.amazon.com/ec2/instance-types/inf1/
* https://aws.amazon.com/ec2/instance-types/inf2/
* https://awsdocs-neuron.readthedocs-hosted.com/en/latest/index.html

Basically there are cheaper instances than gpu (at leas inf1.xlarge is cheaper than g4dn.xlarge) with a custom nerual chip called **AWS Inferentia chips**

I think it would be nice to make compatible this lib with that kind of instances/chips

**Comment by nathan-sixnines** [comment]
Anyone working on this?

**Comment by rhuddleston** [comment]
This would be really nice

**Comment by ggerganov** [comment]
Is there any kind of API for these chips? If yes, one can try to implement a `ggml` backend similar to CUDA, Metal, etc.

**Comment by jaysonfrancis** [comment]
https://github.com/aws-neuron/aws-neuron-sdk/blob/master/neuron-customops/programming-guide/custom-c%2B%2B-operators-devguide.rst#implementing-an-operator-in-c

**Comment by nathan-sixnines** [comment]
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-api-guide.html

**Comment by virajkanwade** [comment]
Can we reopen this?

**Comment by swtb3-ryder** [comment]
This would be useful

**Comment by MoonKraken** [comment]
this would be incredible to have, inf instances look to be extremely cost effective relative to the equivalent nvidia based instances. cheapest inf instance is less than 1/4 the cost of a g6.xlarge and has twice as much GPU memory
