### ISSUE TITLE
[User] convert.py KeyError for redpajama chat 3B

### ISSUE THREAD

**Issue by LachlanGray** [ggerganov/llama.cpp#2114]
# Expected Behavior
I'm trying to convert the [redpajama 3b chat model](https://huggingface.co/togethercomputer/RedPajama-INCITE-Chat-3B-v1) to a ggml model from the `pytorch_model.bin`.

I saw in [this discussion](https://github.com/ggerganov/llama.cpp/discussions/1394#discussion-5182815) that this is expected to work.

# Current Behavior
I get a failure running convert.py on a directory containing the `pytorch_model.bin` from HF as:
```
python3 convert.py models/RedPajama-INCITE-Chat-3B-v1/
```

# Environment and Context
I am on an m2 mba with 16gb of ram with macOS Ventura.

python version: 3.10.11
make: 3.81
g++: Apple clang version 14.0.0 (clang-1400.0.29.202)

# Failure Information (for bugs):
`convert.py` raises:
```
Loading model file models/RedPajama-INCITE-Chat-3B-v1/pytorch_model.bin
Traceback (most recent call last):
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 1256, in <module>
    main()
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 1236, in main
    model_plus = load_some_model(args.model)
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 1157, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 947, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 819, in lazy_load_torch_file
    model = unpickler.load()
  File "/Users/lachlangray/local/llama.cpp/convert.py", line 808, in find_class
    return self.CLASSES[(module, name)]
KeyError: ('torch', 'BoolStorage')
```

# Steps to Reproduce
1. `pip install -r requirements.txt` in a conda environment
2. compile llama.cpp with make
3. clone HF repository into `models`
4. run `convert.py` on cloned directory

I also re-installed the latest pytorch release

**Comment by alishobeiri** [comment]
Hi, were you able to resolve this?

**Comment by DavidGOrtega** [comment]
I had this issue also

**Comment by Galunid** [comment]
Please use `convert-gptneox-hf-to-gguf.py`, `convert.py` is for llama based models.
