### ISSUE TITLE
Would it be possible to use llama.cpp for ARC, HellaSwag, MMLU and TruthfulQA benchmarking?

### ISSUE THREAD

**Issue by TyraVex** [ggerganov/llama.cpp#2117]
Hello,

I am interested in performing benchmarking beyond the perplexity measure using ARC, HellaSwag, MMLU, and TruthfulQA, similar to the huggingface leaderboard.

My main motivation for this goal is to experiment with the models and observe if quantization has varying effects on different benchmarks. I am curious to explore whether quantization has different impacts on tasks such as reasoning.

In this issue, I am aking for guidance about how such a task could be accomplished.

Thank you.

**Comment by bullno1** [comment]
Yes, it's a library
