### ISSUE TITLE
Build failure during linking for examples/server and examples/embd-input-test

### ISSUE THREAD

**Issue by ssenthilanand** [ggerganov/llama.cpp#2123]
I am on Windows 11 with the latest w64devkit.

Updated to the latest code from the w64devkit terminal.

Ran make.

...
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -march=native -mtune=native -DGGML_USE_K_QUANTS -Iexamples/server examples/server/server.cpp ggml.o llama.o common.o k_quants.o -o server
C:/w64devkit/bin/ld.exe: C:\Users\senan\AppData\Local\Temp\cc7Bwt7M.o:server.cpp:(.text+0x462): undefined reference to `__imp_WSACleanup'
C:/w64devkit/bin/ld.exe: C:\Users\senan\AppData\Local\Temp\cc7Bwt7M.o:server.cpp:(.text+0xfd2): undefined reference to `__imp_select'
...
C:/w64devkit/bin/ld.exe: C:\Users\senan\AppData\Local\Temp\cc7Bwt7M.o:server.cpp:(.text$_ZN7httplib6Server24process_and_close_socketEy[_ZN7httplib6Server24process_and_close_socketEy]+0xfd): undefined reference to `__imp_closesocket'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:309: server] Error 1

Searching around for the error, looks like unable to link with winsock library.

**Running the failing GCC command again after adding -lws2_32 to the end fixed the problem.**

The next example also fails to build.

~/llama.cpp $ g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -march=native -mtune=native -DGGML_USE_K_QUANTS examples/embd-input/embd-input-test.cpp ggml.o llama.o common.o k_quants.o -o embd-input-test  -L. -lembdinput
C:/w64devkit/bin/ld.exe: cannot find -lembdinput: No such file or directory
collect2.exe: error: ld returned 1 exit status

In this case the libembdinput.so is present in the current directory. I am not sure how to fix this.

The train-text-from-scratch example builds successfully.

**Comment by laura-a-n-n** [comment]
Re: the first error, I encountered the same problem and solution myself on both Windows 11 and Windows 10. As you mention, adding the `-lws2_32` flag to the Makefile does fix it. 

As for the `cannot find -lembdinput: No such file or directory` error, I also got this and couldn't fix it. But you should be able to use `main` without having the rest of the build succeed.

**Comment by SlyEcho** [comment]
> In this case the libembdinput.so is present in the current directory. I am not sure how to fix this.

It should not be a .so file on Windows, but .dll and .dll.lib

The Makefile needs fixes for Windows, (w64devkit, MSYS2, etc.)

**Comment by przemoc** [comment]
Fixed in 9cf022a1889e50113fd348dc96b4557fc75a6296, at least for MSYS2.
I don't use w64devkit, but hopefully it's good there now too.

**Comment by ssenthilanand** [comment]
Everything compiles and links under w64devkit too.
