### ISSUE TITLE
Will the prompt evaluation use the mps GPU?

### ISSUE THREAD

**Issue by stoneLee81** [ggerganov/llama.cpp#2125]
I found that when testing under mac, i compiled mps, and when the length of prompt is relatively large, it will wait for a long time, and the GPU has not moved when processing it

> llama_print_timings: load time = 2130.57 ms 
llama_print_timings: sample time = 171.49 ms / 147 runs ( 1.17 ms per token, 857.21 tokens per second) 
llama_print_timings: prompt eval time = 167565.72 ms / 804 tokens ( 208.42 ms per token, 4.80 tokens per second) llama_print_timings: eval time = 26200.71 ms / 146 runs ( 179.46 ms per token, 5.57 tokens per second) 
llama_print_timings: total time = 194420.15 ms

**Comment by shouyiwang** [comment]
Known issue. This is the reason why you shouldn't buy Mac studio instead of 3090/4090s for local LLM inference at the moment :)

**Comment by stoneLee81** [comment]
The inference speed of the nvidia card really crushes the mac

**Comment by daboe01** [comment]
i would really appreciate a solution for this issue.

**Comment by shouyiwang** [comment]
> 

Me too

**Comment by ggerganov** [comment]
> This is the reason why you shouldn't buy Mac studio instead of 3090/4090s for local LLM inference at the moment :)

Yes - at the moment 😉
