### ISSUE TITLE
GPU instead CPU?

### ISSUE THREAD

**Issue by DimasRulit** [ggerganov/llama.cpp#214]
How can we use GPU instead of CPU? My processor is pretty weak. I don't have a macbook or a very powerful pc. the desire to run a model on CUDA cores. Thanks

**Comment by j-f1** [comment]
You might have better luck with the original LLaMA repo which I believe supports CUDA. This repo is focused on running on the CPU.

**Comment by DimasRulit** [comment]
> You might have better luck with the original LLaMA repo which I believe supports CUDA. This repo is focused on running on the CPU.

Where i can original repo?

**Comment by j-f1** [comment]
https://github.com/facebookresearch/llama

**Comment by dontknowhy** [comment]
Wait,i haven't any CUDA devices...
So What about OpenCL or Vulkan(I can use them on my device)

**Comment by DimasRulit** [comment]
> 

Maybe we can use openCL. But with cuda its not work good. I have very low pc
