### ISSUE TITLE
[User] I have two GPUs, and I want to use only one GPU to inference. How can I do?

### ISSUE THREAD

**Issue by riverzhou** [ggerganov/llama.cpp#2154]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

I have two GPUs, and I want to use only one GPU to inference. How can I do?

**Comment by alecGraves** [comment]
If your GPUs are Nvidia GPUs, you can use the `CUDA_VISIBLE_DEVICES` environment variable. You might also need to modify the NVCC flags to compile for the architecture of each GPU if your GPUs have different Nvidia architecture names.

Using CLBlast, I am not sure.

**Comment by riverzhou** [comment]
> CUDA_VISIBLE_DEVICES

It's work. Thanks a lot.
