### ISSUE TITLE
C based server options missing

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/llama.cpp#2156]
Hi, 

the chat.sh program accepts -c -b -n --keep options but the server does not accept --keep and -n option.

Also the new server UI does not auto scroll. Adding overflow:auto to chat section fixes the issue. 

C Server also seg faults when connected to two clients inferencing at same time.

**Comment by aiaicode** [comment]
Also it would be helpful to include the C server and addition of new server UI information in the main readme file. 2 lines.

**Comment by SlyEcho** [comment]
`n_keep` and `n_predict` are API options that are sent with each completion request. The included web chat does not have a way to configure many options yet.

It also doesn't support multiple users at this time but of course segfault should be looked into...

Can you make a PR for the CSS fix?
