### ISSUE TITLE
server options

### ISSUE THREAD

**Issue by EdwardDali** [ggerganov/llama.cpp#2158]
# Prerequisites

- [ x] I am running [master-6463955](https://github.com/ggerganov/llama.cpp/releases/tag/master-6463955)
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

ability to use the following options with server:

--in-suffix "Sure thing! Here it is:" 
-n -1 
--ignore-eos

maybe also the ability to save the chat as a text file either manually or automatically

# Current Behavior

no such options identified for the server

# Environment and Context
I'm using a bat file to open the server: 

@echo off
start "" server.exe -c 2048 -m models\13B\orca_mini_v2_13b.ggmlv3.q4_K_M.bin
timeout /t 5 >nul
start "" http://127.0.0.1:8080

**Comment by SlyEcho** [comment]
All these options are sent to the request to `/completion` as they are not dependent on how the server is running, only on how to predict output.

I think the problem you are having is with the built-in web chat, as it doesn't support setting all of the options manually.
