### ISSUE TITLE
how to pipe whisper.cpp transcripts into sdin

### ISSUE THREAD

**Issue by itsPreto** [ggerganov/llama.cpp#2161]
I'm basically looking for a way to save every ~5 secs of transcribed audio from my mic to a file, and have my interactive model read that into the terminal.

i'm assuming there is a better way than to just run:

```
./main -m ./models/wizard/wizardLM-7B.ggmlv3.q4_0.bin -n 256  --keep -1 --color -i -r "User:" -f prompts/chat-with-bob.txt
```

this will load the model every single time there is a new audio chunk transcribed-- but I want a way to leave the model running while piping in the text updates as prompts. Any help is appreciated!

**Comment by mqy** [comment]
The basic idea is pipe in a file to stdin, use `tail -f` to avoid EOF.

step 1: open two consoles C1 and C2, the C1 for running main, the C2 for appending text.

step 2: in C2, prepare an empty input file:
```
touch chat-input.txt; echo "" > chat-input.txt
```

step 3: in C1, run main:

```
tail -f chat-input.txt | ./main -m ./models/wizard/wizardLM-7B.ggmlv3.q4_0.bin -n 256 --keep -1 --color -i -r "User:" -f prompts/chat-with-bob.txt
```

step 4: in C2, append prompts:
```
echo "hello bob, what time is it?" >> chat-input.txt
```
C1 will output the answer.

again:

```
echo "tell me the size of earth?" >> chat-input.txt
```

**Comment by bullno1** [comment]
They are both libraries. The CLI programs are just examples of how to use them.
You'd have much better control writing your own program calling those 2 libraries.
A lot of the model also requires a "system prompt" and proper prompt format too.

That said, it's doable with pipe.
You can spawn both whisper and llama, with your program in-between as a mediator:

`whisper | your-program | llama`.

That way, your program get to control what gets into llama, timing (every 5s) and prompt formats...

Although in that case, I'd still prefer:

```
    controlling-program
      |            |
      |            |
   whisper       llama
```

Have your program spawns both the other 2 and control their stdin/stdout.

**Comment by itsPreto** [comment]
@mqy this is perfect thanks!

**Comment by LucasZNK** [comment]
> They are both libraries. The CLI programs are just examples of how to use them. You'd have much better control writing your own program calling those 2 libraries. A lot of the model also requires a "system prompt" and proper prompt format too.
> 
> That said, it's doable with pipe. You can spawn both whisper and llama, with your program in-between as a mediator:
> 
> `whisper | your-program | llama`.
> 
> That way, your program get to control what gets into llama, timing (every 5s) and prompt formats...
> 
> Although in that case, I'd still prefer:
> 
> ```
>     controlling-program
>       |            |
>       |            |
>    whisper       llama
> ```
> 
> Have your program spawns both the other 2 and control their stdin/stdout.

You know where i can see how to send data to llama instead of CLI? want to use in a program and send the user input into it throw my ui + server + llama
