### ISSUE TITLE
Can't we use multiple GPUs independently?

### ISSUE THREAD

**Issue by gotzmann** [ggerganov/llama.cpp#2165]
I'm trying to use llama.cpp as a backend for scalable inference and it seems the current architecture just doesn't allow to use multiple GPUs working in parallel with different models.

From what I've understand reading code, it always suggest we are going to SPLIT the same model between multiple GPUs, not to use 1 .. N models for 1 .. N GPUs.

There global vars like `g_main_gpu`, etc, and from my POV this should be set within context, thus allow inference within GPU0 from CTX0, GPU1 from CTX1 - all at the same time.

**Comment by JohannesGaessler** [comment]
I won't implement it but feel free to make a PR yourself if you want that feature.

**Comment by slaren** [comment]
I am working on refactoring the CUDA implementation, and one of the goals is to remove the global state. After that, associating a device or set of devices to a ggml-cuda context should be fairly straightforward.

**Comment by gotzmann** [comment]
@slaren are there estimate for when it will be implemented? week or two .. or some months?

**Comment by slaren** [comment]
I hope to open a draft PR sometime this week, but it will still take some time (weeks) until it is ready to merge. If you need this now, I would suggest hacking it yourself in the meanwhile.

**Comment by Rajansharma44** [comment]
Multiple GPUs can help render frames much faster, Higher FPS in games, improved multitasking, 4K gaming becomes a reality and it might also enable having a multi-monitor setup

**Comment by daddydrac** [comment]
@slaren any movement on this feature?

**Comment by slaren** [comment]
We are getting closer, you can track the progress in the ggml repository. https://github.com/ggerganov/ggml/pull/586 is the most recent update of the framework that will allow us to support this and other features, and it was just merged yesterday. It is still going to take a few weeks before this is ready to be used in llama.cpp, but we are working on it.
