### ISSUE TITLE
Request : Distributed Inference on cluster connected via Internet 

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/llama.cpp#2167]
This is a request to enable inference using distributed compute connected via Internet.

Not sure if this is possible or tried by anyone but imagine the public cluster to run a huge open source model.

 .main -m ./model.bin -ip 192.168.50.50 192.168.20.20

**Comment by USBhost** [comment]
You should be able to No? Make sure the ports are open on every node and you should be good.

**Comment by aiaicode** [comment]
Hmm I did not notice the port (1) in greg's post about inferencing on raspberry pi and thought MPI only works locally. Let me try then. Thanks.
