### ISSUE TITLE
baichuan model converting steps

### ISSUE THREAD

**Issue by stoneLee81** [ggerganov/llama.cpp#2176]
Is there a step-by-step document for converting baichuan model to gmll support model?

**Comment by riverzhou** [comment]
python convert.py  [--outfile OUTFILE]  model

**Comment by stoneLee81** [comment]
I use this command to export the baichuan model, the reasoning is messed up。

**Comment by FNsi** [comment]
> I use this command to export the baichuan model, the reasoning is messed up。
> 
> 

13B model isn't it?
Current script only for 7b, 13b use alibi.

**Comment by LiuKai22** [comment]
> Today I dig a bit inside it, the layers are the same like 7b, so that script is working well I suppose. All needed is using alibi function from ggml to Handel the attention part.

Seems like it only supports CPU inference. 
CUDA version of alibi OP is not released, like "ggml_cuda_op_alibi" and "alibi_f32_cuda" in ggml-cuda.cu.
Thus no CUDA  full GPU acceleration for models like Baichuan 13B.

**Comment by FNsi** [comment]
> Seems like it only supports CPU inference. 
> 
As I remember there's a falcon branch support that. [ggllm.cop](https://github.com/cmp-nct/ggllm.cpp)
