### ISSUE TITLE
[requirement] Support baichuan 13B model.

### ISSUE THREAD

**Issue by riverzhou** [ggerganov/llama.cpp#2185]
Baichuan 13B model use ALiBi , any plan to support this model?

**Comment by Magic-Fy** [comment]
Agree

**Comment by ouwei2013** [comment]
I implemented it based on llama.cpp. Try it if you are interested:

https://github.com/ouwei2013/baichuan13b.cpp

**Comment by riverzhou** [comment]
> I implemented it based on llama.cpp. Try it if you are interested:
> 
> https://github.com/ouwei2013/baichuan13b.cpp

Great Job!
