### ISSUE TITLE
Can this code base be extended to support other transformer-based LLMs such as Pythia or its instruction-tuned version Open Assistant?

### ISSUE THREAD

**Issue by michaelbogdan** [ggerganov/llama.cpp#219]

**Comment by gjmulder** [comment]
If you provided links and more information about Pythia it would make it easier for someone to know what Pythia is and if the model can be converted into the format that `llama.cpp` supports.

See #172 for Stanford's Alpaca.

**Comment by michaelbogdan** [comment]
@gjmulder I'm going to hijack this issue to expand my question by all available FOSS LLMs. (WIP)

[BLOOM](https://huggingface.co/docs/transformers/model_doc/bloom) is massive LLM at 176B parameters and was developed by a collaboration under Hugging Face leadership. There is a version of the model that has only 7.1B parameters and can feasibly run on a laptop using the related project [bloomz.cpp](https://github.com/NouamaneTazi/bloomz.cpp/). Should this project be extended to include `BLOOM`, merged with the `bloomz.cpp` effort or should they be kept as separate projects? I am not currently aware of any efforts to instruction tune this LLM.

[GPT-NeoX](https://huggingface.co/docs/transformers/model_doc/gpt_neox) is a 20B parameter model trained on The Pile, the largest publically available dataset for LLM training. There is an effort by [OpenChatKit](https://openchatkit.net/) to create an instruction-tuned version of GPT-NeoX as an open source alternative to ChatGPT. The model itself is released on Hugging Face as [GPT-NeoXT-Chat-Base-20B](https://huggingface.co/togethercomputer/GPT-NeoXT-Chat-Base-20B).

GPT-Neo (tbc)

GPT-J (tbc)

GPT-2 (tbc)

**Comment by Ronsor** [comment]
Are we basically making an open source ts_server (https://bellard.org/ts_server/) now? If so, I also nominate RWKV (https://github.com/BlinkDL/RWKV-LM)

**Comment by michaelbogdan** [comment]
@Ronsor I am not sure, that is why I am asking and doing some preliminary research. The maintainer(s) can of course tell that running other models than `LLaMA` is out of scope.

**Comment by Ayushk4** [comment]
Hi, @michaelbogdan , we (at [nolano.org](https://twitter.com/nolanoorg)) are working on something akin to Huggingface (Python based interface) for running LLMs, but with C/CPP backend for speed.
For tomorrow's initial release, we plan to have GPT-J and BLOOM. GPT-NeoX (and hence Pythia & OpenAssistant) is next - I will also get these out by tomorrow.

**Comment by Ayushk4** [comment]
Update: Its here - https://github.com/NolanoOrg/cformers
I am working on getting Pythia/GPT-NeoX models out next - [OpenAssistant/oasst-sft-1-pythia-12b](https://huggingface.co/OpenAssistant/oasst-sft-1-pythia-12b) is much better than Alpaca and will be added soon.

**Comment by Ayushk4** [comment]
OpenAssistant and Open-Chat-Kit models have been added to [nolanoorg/cformers](github.com/nolanoorg/cformers).

You can now interface with the models with just 3 lines of code from python.

```
from interface import AutoInference as AI
ai = AI('OpenAssistant/oasst-sft-1-pythia-12b')
x = ai.generate("<|prompter|>What's the Earth total population<|endoftext|><|assistant|>", num_tokens_to_generate=100); print(x['token_str'])
```

So far 10 different models are supported across 5 different architectures.
