### ISSUE TITLE
[User] Insert summary of your issue or enhancement..

### ISSUE THREAD

**Issue by MasterDimmy** [ggerganov/llama.cpp#2205]
Any way to support Windows 7 x64 ? 

Error "PrefetchVirtualMemory" not found in kernel32.dll in all executables after launch. Used latest version of llama for now.

Can someone recompile it for windows? Or maybe you can distribute for win7 users too in download section ?

**Comment by zaciam** [comment]
you should change the title of this issue

**Comment by staviq** [comment]
To be honest, using llm on Windows 7 is like trying to move your couch with a ford model T. It's not that it is impossible, but there are way better ways of solving this situation :)

I know this is not the answer you want, but I highly recommend installing Linux in dual boot configuration, so you can still use Win7 if you insist, and use Linux for llm.

In the context you are describing, Linux will likely give you something like 10-30% increase in overall performance, and not just for llm and AI, but for everything you do with this computer.

However, considering you are in Win7, your computer is likely several generations old, and whatever GPU you have, will probably be incompatible. Luckily, llamacpp can run in CPU mode.
