### ISSUE TITLE
[User] android clang does not support "-mfp16-format" argument

### ISSUE THREAD

**Issue by RossComputerGuy** [ggerganov/llama.cpp#2210]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

llama.cpp should compile for Android

# Current Behavior

Fails with:
```
clang++: error: unknown argument: '-mfp16-format=ieee'
ninja: build stopped: subcommand failed.
```

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

Use case: Flutter library

* Physical (or virtual) hardware you are using, e.g. for Linux:

`neon-fp-armv8`

* Operating System, e.g. for Linux:

Android

* SDK version, e.g. for Linux:

NDK 23.1.7779620

# Failure Information (for bugs)

Command executed:
```
/usr/local/lib/android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16 --gcc-toolchain=/usr/local/lib/android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/local/lib/android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DGGML_USE_K_QUANTS -DLLAMA_BUILD -DLLAMA_SHARED -Dllama_EXPORTS -I/home/runner/work/flutter_llama/flutter_llama/src/llama.cpp/. -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mfpu=neon-fp-armv8 -mfp16-format=ieee -mno-unaligned-access -funsafe-math-optimizations -pthread -std=gnu++11 -MD -MT llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -MF llama.cpp/CMakeFiles/llama.dir/llama.cpp.o.d -o llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -c /home/runner/work/flutter_llama/flutter_llama/src/llama.cpp/llama.cpp
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Try compiling llama.cpp for Android

# Failure Logs

https://github.com/ExpidusOS/flutter_llama/actions/runs/5538864077/jobs/10109227613

**Comment by rdcoder33** [comment]
+1

**Comment by useCallback** [comment]
Any solution ?

**Comment by JackJollimore** [comment]
I'd build excluding `-mfp16-format=ieee`. I compile `llama.cpp` daily with `make` and `cmake`.

**Comment by RossComputerGuy** [comment]
@JackJollimore Is there an option to remove that argument because it looks like there isn't [in `CMakeLists.txt`](https://github.com/ggerganov/llama.cpp/blob/849408957c687cde4ab32c147107f643fc55130b/CMakeLists.txt#L476-L479).

**Comment by RossComputerGuy** [comment]
Gotcha, I'm hoping to avoid forking if possible. I add `llama.cpp` as a submodule so patching isn't necessarily that easy. I could probably make a PR that adds an option to bypass the argument or check if the argument is supported by the compiler.

**Comment by JackJollimore** [comment]
> I could probably make a PR that adds an option to bypass the argument or check if the argument is supported by the compiler.

I don't speak for `llama.cpp` folk, but from what I've seen that's probably the most reasonable option assuming it's done in a way the devs value.

**Comment by ggerganov** [comment]
Adding a build flag for this use case is OK, so feel free to propose a PR

> I add llama.cpp as a submodule so patching isn't necessarily that easy.

In general, 3rd party projects don't have to use `llama.cpp`'s build system. In fact, I think it is best if the project builds `llama.cpp` with the optimum flags and options for that specific project.

**Comment by RossComputerGuy** [comment]
I made a PR, it seems on my M1 Pro with NixOS Asahi also faces this issue without the PR.
