### ISSUE TITLE
CuBLAS version on Windows uses excessive ram

### ISSUE THREAD

**Issue by Rotatingxenomorph** [ggerganov/llama.cpp#2223]
Since the CFG update, the cublas version uses so much ram I can't fit 65b in 64gb of memory. I don't think it's a leak, because for 33b it just uses a ton of ram and doesn't keep going.

**Comment by Dampfinchen** [comment]
Yeah, I've been noticing very high RAM usage as well on Windows and with cuBLAS.

**Comment by Dampfinchen** [comment]
> If you do not enable CFG there should be no difference

I don't know what that is and I didn't enable it.

**Comment by Rotatingxenomorph** [comment]
> If you do not enable CFG there should be no difference

It turns out turning on ROPE scaling also does it, but using neither makes it work normally. I'm only using it for prompt ingestion, as I have 3gb vram. clBLAS seems fine.

**Comment by Dampfinchen** [comment]
> > If you do not enable CFG there should be no difference
> 
> It turns out turning on ROPE scaling also does it, but using neither makes it work normally. I'm only using it for prompt ingestion, as I have 3gb vram. clBLAS seems fine.

Is this enabled by default? I'm not using a CTX beyond 2048.

**Comment by Rotatingxenomorph** [comment]
> Is this enabled by default? I'm not using a CTX beyond 2048.

No, you have to set parameters for it. I'm currently using both CFG and ROPE simultaneously (for airoboros-65b-gpt4-1.4.1-PI-8192.ggmlv3.q4_K_M.bin) at the same time on clBlast.

**Comment by Dampfinchen** [comment]
After comparing with CLBlast, the RAM usage is indeed significant. 

After loading and running a small test, my RAM usage with cuBLAS was 91% in Windows Task Manager.

With CLBlast it was just at 79%. 

I understand cuBLAS needs more VRAM due to faster prompt injection, but what's the deal with the RAM? Maybe this is something @JohannesGaessler or @slaren could explain, because I genuinely  don't understand.

**Comment by JohannesGaessler** [comment]
I was not involved in the CFG and RoPE scaling implementations so I don't know what could be causing this.

**Comment by Dampfinchen** [comment]
> I was not involved in the CFG and RoPE scaling implementations so I don't know what could be causing this.

I'm not using CFG and RoPE. This is at standard ctx of 2048.

**Comment by JohannesGaessler** [comment]
Okay, but the OP is specifically talking about high RAM usage *after the CFG changes*. If your problem doesn't fit that description, make a new issue.
