### ISSUE TITLE
Using convert.py from a transformers model -> ggml loses support for emojis

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#2231]
I have a pytorch transformers model and I used the `convert.py` script from here to convert it to a ggml f16.bin.

I found it loses the ability to output emojis.

The prompt is simply: "What's a good emoji for saying Hello?"

Using the pytorch model it responds with a few emoji suggestions, but the converted ggml model does not. The English response part is the same, up until the emojis, where it is just blank. The output whole sentence structure is the same, just the emoji part is now blank.

This leads me to think it may be a tokenisation problem? Does anyone have any idea why this is happening?

**Comment by mirek190** [comment]
maybe character encoding problem?

**Comment by l3utterfly** [comment]
I'm using the oobaboga GUI. Do you think it's the problem with the GUI or the model itself? Any way I can determine this?

**Comment by mirek190** [comment]
That is ggml model ?
So try with llama.cpp straight without any gui under terminal / shell .

**Comment by dranger003** [comment]
I have seen this issue using llama.cpp via C# interop and I found that some multi-byte characters are split into multiple tokens which was breaking the encoding. I fixed it by buffering the token if I detect a multi-byte character. Below is an extract from my code as an example.
```
                var bytes = LlamaCppInterop.llama_token_to_bytes(_context, id);

                // Buffer bytes to avoid breaking multi-byte character encoding
                if ((bytes[0] & 0x80) != 0)
                {
                    buffer.AddRange(bytes);
                    continue;
                }
                else if (buffer.Count > 0)
                {
                    buffer.AddRange(bytes);
                    bytes = buffer.ToArray();
                    buffer.Clear();
                }

                yield return Encoding.UTF8.GetString(bytes);
            }
```

**Comment by l3utterfly** [comment]
Thanks! I found this solution as well!
