### ISSUE TITLE
FPE in llama_eval_internal when load a model.

### ISSUE THREAD

**Issue by 360AIVul** [ggerganov/llama.cpp#2247]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [√] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [√] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [√] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [√] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Check fields in the model before load it.

# Current Behavior

Floating point exception.

# Environment and Context
ubuntu 22.04

# Steps to Reproduce
[vocab_1_embd_32_mult_1_head_0.zip](https://github.com/ggerganov/llama.cpp/files/12065968/vocab_1_embd_32_mult_1_head_0.zip)
1.unzip vocab_1_embd_32_mult_1_head_0.zip
2../main -m vocab_1_embd_32_mult_1_head_0.bin -p "steps to build linux"

# Failure Logs

```
$./main -m vocab_1_embd_0_mult_1_head_1.bin -p "steps to build linux"
main: build = 0 (unknown)
main: seed  = 1689564528
llama.cpp: loading model from ../crash/vocab:1_embd:32_mult:1_head:0.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 1
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 32
llama_model_load_internal: n_mult     = 1
llama_model_load_internal: n_head     = 0
llama_model_load_internal: n_layer    = 1
llama_model_load_internal: n_rot      = 1
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 85
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.00 MB
llama_model_load_internal: mem required  = 1792.03 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  =    0.06 MB

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 |AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p= 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


Floating point exception
```
It is caused by the codes below. When the `n_head` field in the model is 0, an FPE vulnerability will be triggered.
```
#https://github.com/ggerganov/llama.cpp/blob/b7647436ccc80970b44a270f70f4f2ea139054d1/llama.cpp#L1346
static bool llama_eval_internal(
	){
	...
	const int n_rot        = hparams.n_embd/hparams.n_head;
}
```

**Comment by SlyEcho** [comment]
What is that model?

`n_head` should be at least 1, otherwise a lot of things won't work.

**Comment by aivul** [comment]
> What is that model?

I generate a small model for test, since we cannot guarantee the user will input a normal model when using llama.cpp.

> n_head should be at least 1, otherwise a lot of things won't work.

Yes, so I suggest there should be a check for `n_head`.
