### ISSUE TITLE
convert-pth-to-ggml.py how to handle torch.view_as_complex

### ISSUE THREAD

**Issue by haolongzhangm** [ggerganov/llama.cpp#225]
llama code block include view_as_real: https://github.com/facebookresearch/llama/blob/main/llama/model.py#L68

how to convert-pth-to-ggml.py handle this part of weight

**Comment by gjmulder** [comment]
Please improve your question with more text and examples so it is easier to understand what you are asking.

**Comment by nullhook** [comment]
If you are asking about applying rotary embeddings, then that is done in the [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L705) file and not during conversion

**Comment by haolongzhangm** [comment]
@nullhook  ths for u info
