### ISSUE TITLE
newer version-GPTQ to GGML convert failure

### ISSUE THREAD

**Issue by joshuachris2001** [ggerganov/llama.cpp#2254]
I am trying to convert [https://huggingface.co/FPHam/Rachel_Assistant_Editor_13b_GPTQ](https://huggingface.co/FPHam/Rachel_Assistant_Editor_13b_GPTQ) to a GGML model. so I use python convert.py /pathtomodel/Rachel-AE-4bit-128g.safetensors --outtype f16 --outfile /pathtomodel/Rachel-f16.bin

# Expected Behavior

Convert the model by dequantizing the model as a f16 ggml model.

# Current Behavior

`Loading model file /mnt/1TB_backupDrive/LLaMA/Rachel_Assistant_Editor_13b_GPTQ/Rachel-AE-4bit-128g.safetensors
Loading vocab file /mnt/1TB_backupDrive/LLaMA/Rachel_Assistant_Editor_13b_GPTQ/tokenizer.model
params: n_vocab:32001 n_embd:5120 n_mult:256 n_head:40 n_layer:40
Writing vocab...
[  1/363] Writing tensor tok_embeddings.weight                  | size  32001 x   5120  | type UnquantizedDataType(name='F16')
[  2/363] Writing tensor norm.weight                            | size   5120           | type UnquantizedDataType(name='F32')
[  3/363] Writing tensor output.weight                          | size  32001 x   5120  | type UnquantizedDataType(name='F16')
Traceback (most recent call last):
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 1263, in <module>
    main()
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 1258, in main
    OutputFile.write_all(outfile, params, output_type, model, vocab)
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 1058, in write_all
    for i, ((name, lazy_tensor), ndarray) in enumerate(zip(model.items(), ndarrays)):
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 980, in bounded_parallel_map
    result = futures.pop(0).result()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 1055, in do_item
    return lazy_tensor.load().to_ggml().ndarray
           ^^^^^^^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 563, in load
    ret = self._load()
          ^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 571, in load
    return self.load().astype(data_type)
           ^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 563, in load
    ret = self._load()
          ^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 660, in load
    return lazy_tensor.load().permute(n_head)
           ^^^^^^^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 563, in load
    ret = self._load()
          ^^^^^^^^^^^^
  File "/home/joshuachris/Downloads/llama.cpp/convert.py", line 731, in load
    return GPTQForLLaMaQuantizedTensor(model, namebase)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class GPTQForLLaMaQuantizedTensor with abstract methods part, permute_part`

* Physical (or virtual) hardware you are using, e.g. for Linux:

Intel(R) Core(TM) i7-4765T CPU @ 2.00GHz with 3.00GHz for boost.
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arc
                         h_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1
                          sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow flexpriority 
                         ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts vnmi md_clear flush_l1d
15GB of usable memory with zram and 18GB of disk swap.

* Operating System, e.g. for Linux:

ARCH

* SDK version, e.g. for Linux:

```
Python 3.11.3
GNU Make 4.4.1
g++ (GCC) 12.3.0
```

# Failure Information (for bugs)

I think its just a python error, but it was complaining about me trying to convert a newer version of GPTQ.
EDIT:[in the editor the trace log is not messed up, but I'm not sure what to do to fix it. sorry.]

**Comment by TimonLukas** [comment]
This regression occurred between commits c943d823c14cef33092205ca3944de6fdf7abf99 and 471aab6e4cb89d8ef6d043f1bc93acb6eb78ab67. Reverting to the earlier one lets the script run further. Seems like the `Tensor` ABC has new methods which weren't added to `GPTQForLLaMaQuantizedTensor`.
