### ISSUE TITLE
Add llama 2 model

### ISSUE THREAD

**Issue by tikikun** [ggerganov/llama.cpp#2262]
Meta just released llama 2 model, allowing commercial usage

https://ai.meta.com/resources/models-and-libraries/llama/

I have checked the model implementation and it seems different from llama_v1, maybe need a re-implementation

**Comment by Green-Sky** [comment]
link to paper: https://ai.meta.com/research/publications/llama-2-open-foundation-and-fine-tuned-chat-models/

**Comment by Azeirah** [comment]
Interesting to note that the model evaluation section in their paper lists a 34b model even though the site doesn't talk about it.

**Comment by Green-Sky** [comment]
Interestingly, the paper talks about a 34B model, which is missing from the model card.

**Comment by slaren** [comment]
The paper implies that they are planning to release the 34B model later.
![image](https://github.com/ggerganov/llama.cpp/assets/2141330/c73ddb65-3707-4dd8-af19-f041fa144402)

**Comment by Green-Sky** [comment]
@Azeirah no, i did not hear back yet either.

> Once your request is approved, you will receive a signed URL over email. Then run the download.sh script, passing the URL provided when prompted to start the download.

> Keep in mind that the links expire after 24 hours and a certain amount of downloads. If you start seeing errors such as 403: Forbidden, you can always re-request a link.

also, they are available on hf if your email is the same https://huggingface.co/meta-llama

**Comment by Azeirah** [comment]
I was really hopeful for an alternative to gpt-4 for coding assistance, but the evaluation states their 70B model is about equivalent in performance to get-3.5.

Not bad, but the jump in quality from 3.5 to 4 has been what it made it really useful in day-to-day coding tasks. ;(

<img width="1152" alt="Screenshot 2023-07-18 at 19 05 26" src="https://github.com/ggerganov/llama.cpp/assets/4040870/b3480427-b3bf-4321-9b2b-73f35eb1c8fb">

**Comment by goranmoomin** [comment]
The updated model code for Llama 2 is at the same facebookresearch/llama repo, diff here: https://github.com/facebookresearch/llama/commit/6d4c0c290aeec1fa4399694fefb864be5a153bb6

Seems codewise, the only difference is the addition of GQA on large models, i.e. the `repeat_kv` part that repeats the same k/v attention heads on larger models to require less memory for the k/v cache.

According to the paper, smaller models (i.e. the 7b/13b ones) don't have GQA, so in theory it seems it should be able to run unmodified.

**Comment by dmadisetti** [comment]
Email below with tracking links stripped. Same as llama-1 for the most part. Now if it would actually download.....

---

You’re all set to start building with Llama 2.

The models listed below are now available to you as a commercial license holder. By downloading a model, you are agreeing to the terms and conditions of the license, [acceptable use policy](https://ai.meta.com/llama/responsible-use-guide/) and Meta’s [privacy policy](https://www.facebook.com/privacy/policy/).

Model weights available:

    Llama-2-7b
    Llama-2-7b-chat
    Llama-2-13b
    Llama-2-13b-chat
    Llama-2-70b
    Llama-2-70b-chat

With each model download, you’ll receive a copy of the Llama 2 Community License and Acceptable Use Policy, and can find all other information on the model and code on [GitHub](https://github.com/facebookresearch/llama).

How to download the models:

    Visit GitHub and clone [the Llama repository](https://github.com/facebookresearch/llama) from there in order to download the model code
    Run the download.sh script and and follow the prompts for downloading the models.
    When asked for your unique custom URL, please insert the following:
    <redacted for legal reasons>
    Select which model weights to download

The unique custom URL provided will remain valid for model downloads for 24 hours, and requests can be submitted multiple times.
Now you’re ready to start building with Llama 2.

Helpful tips:
Please read the instructions in the GitHub repo and use the provided code examples to understand how to best interact with the models. In particular, for the fine-tuned chat models you must use appropriate formatting and correct system/instruction tokens to get the best results from the model.

You can find additional information about how to responsibly deploy Llama models in our Responsible Use Guide.

If you need to report issues:
If you or any Llama 2 user becomes aware of any violation of our license or acceptable use policies - or any bug or issues with Llama 2 that could lead to any such violations - please report it through one of the following means:

    Reporting issues with the model: Llama GitHub
    Giving feedback about potentially problematic output generated by the model: [Llama output feedback](https://developers.facebook.com/llama_output_feedback)
    Reporting bugs and security concerns: [Bug Bounty Program](https://facebook.com/whitehat/info)
    Reporting violations of the Acceptable Use Policy: [LlamaUseReport@meta.com](mailto:LlamaUseReport@meta.com)

Subscribe to get the latest updates on Llama and Meta AI.

Meta’s GenAI Team

**Comment by swyxio** [comment]
anyone else also randomly getting 

```
Resolving download.llamameta.net (download.llamameta.net)... 13.33.88.72, 13.33.88.62, 13.33.88.45, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.33.88.72|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-19 01:24:43 ERROR 403: Forbidden.
```

for the small files?  but `/llama-2-7b-chat/consolidated.00.pth` is downloading fine it seems. will share checksums when i have them

**Comment by Azeirah** [comment]
> anyone else also randomly getting
> 
> ```
> Resolving download.llamameta.net (download.llamameta.net)... 13.33.88.72, 13.33.88.62, 13.33.88.45, ...
> Connecting to download.llamameta.net (download.llamameta.net)|13.33.88.72|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-07-19 01:24:43 ERROR 403: Forbidden.
> ```
> 
> for the small files? but `/llama-2-7b-chat/consolidated.00.pth` is downloading fine it seems. will share checksums when i have them

I genuinely just think their servers are a bit overloaded given what I see posted here. It's a big release

**Comment by trrahul** [comment]
Yeah the GGML models are on hf now.
https://huggingface.co/TheBloke/Llama-2-7B-GGML

**Comment by Azeirah** [comment]
> Yeah the GGML models are on hf now.
> https://huggingface.co/TheBloke/Llama-2-7B-GGML
> https://huggingface.co/TheBloke/Llama-2-13B-GGML

Thebloke is a wizard O_O

**Comment by Johnhersh** [comment]
> Yeah the GGML models are on hf now.
> https://huggingface.co/TheBloke/Llama-2-7B-GGML
> https://huggingface.co/TheBloke/Llama-2-13B-GGML

These worked as-is for me

**Comment by jonataslaw** [comment]
It works, but it is veeeeery slow in silicon macs.

**Comment by LoganDark** [comment]
> Yeah the GGML models are on hf now. https://huggingface.co/TheBloke/Llama-2-7B-GGML https://huggingface.co/TheBloke/Llama-2-13B-GGML

Holy heck what is this dude's upload speed? I'm watching https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/tree/main fill in live, they uploading gigabytes of model per minute

**Comment by Azeirah** [comment]
> > Yeah the GGML models are on hf now. https://huggingface.co/TheBloke/Llama-2-7B-GGML https://huggingface.co/TheBloke/Llama-2-13B-GGML
> 
> Holy heck what is this dude's upload speed? I'm watching https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/tree/main fill in live, they uploading gigabytes of model per minute!

Wouldn't be surprised if he's uploading from a service like AWS or Azure, those have insane bandwidth available.

**Comment by Johnhersh** [comment]
> It works, but it is veeeeery slow in silicon macs.

Hmm really? On the 13B one I get crazy-good speed.

![image](https://github.com/ggerganov/llama.cpp/assets/20746719/30a6f8bd-163c-4aff-9c7e-bdd241283877)

**Comment by LoganDark** [comment]
> > > Yeah the GGML models are on hf now. https://huggingface.co/TheBloke/Llama-2-7B-GGML https://huggingface.co/TheBloke/Llama-2-13B-GGML
> > 
> > 
> > Holy heck what is this dude's upload speed? I'm watching https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/tree/main fill in live, they uploading gigabytes of model per minute!
> 
> Wouldn't be surprised if he's uploading from a service like AWS or Azure, those have insane bandwidth available.

As in, renting a VPS or dedicated server just to quantize + upload? (actually, come to think of it, this is an official recommendation by huggingface, wouldn't be surprised...)

**Comment by LoganDark** [comment]
> > It works, but it is veeeeery slow in silicon macs.
> 
> Hmm really? On the 13B one I get crazy-good speed.
> 
> ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)

Woah, apple silicon is literally god

**Comment by Azeirah** [comment]
> > > It works, but it is veeeeery slow in silicon macs.
> > 
> > 
> > Hmm really? On the 13B one I get crazy-good speed.
> > ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)
> 
> Woah, apple silicon is literally god, I don't get anywhere near those speeds with my 3060 pulling hundreds of watts (:/)

Depends on if you're using the quantised or non-quantised version as well, neither of you two posted which model you're using so comparing doesn't make sense :p

**Comment by Johnhersh** [comment]
> > > > It works, but it is veeeeery slow in silicon macs.
> > > 
> > > 
> > > Hmm really? On the 13B one I get crazy-good speed.
> > > ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)
> > 
> > 
> > Woah, apple silicon is literally god, I don't get anywhere near those speeds with my 3060 pulling hundreds of watts (:/)
> 
> Depends on if you're using the quantised or non-quantised version as well, neither of you two posted which model you're using so comparing doesn't make sense :p

Quantized. I'm using llama-2-13b.ggmlv3.q4_1.bin

**Comment by LoganDark** [comment]
> > > > > It works, but it is veeeeery slow in silicon macs.
> > > > 
> > > > 
> > > > Hmm really? On the 13B one I get crazy-good speed.
> > > > ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)
> > > 
> > > 
> > > Woah, apple silicon is literally god, I don't get anywhere near those speeds with my 3060 pulling hundreds of watts (:/)
> > 
> > 
> > Depends on if you're using the quantised or non-quantised version as well, neither of you two posted which model you're using so comparing doesn't make sense :p
> 
> Quantized. I'm using llama-2-13b.ggmlv3.q4_1.bin

q4_0 should be even faster for only slightly less accuracy

**Comment by Green-Sky** [comment]
iirc q4_1 has an outdated perf/size tradeoff, use one of the kquants instead. (or q4_0)

**Comment by nullhook** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/8665427/5f6bcd96-a33d-4bfd-8109-5bfaab29eb38)

inferencing with q4_1 on M1 Max (64GB) 

`2.99 ms per token` slow

**Comment by LoganDark** [comment]
> > > It works, but it is veeeeery slow in silicon macs.
> > 
> > 
> > Hmm really? On the 13B one I get crazy-good speed.
> > ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)
> 
> Woah, apple silicon is literally god, I don't get anywhere near those speeds with my 3060 pulling hundreds of watts (:/)

huh nevermind

![image](https://github.com/ggerganov/llama.cpp/assets/4723091/2e49a115-8766-46f2-8895-cf9d7b38f8d0)

(llama-2-13b-chat.ggmlv3.q4_0 with all layers offloaded)

**Comment by Johnhersh** [comment]
> huh nevermind
> 
> ![image](https://user-images.githubusercontent.com/4723091/254367272-2e49a115-8766-46f2-8895-cf9d7b38f8d0.png)
> 
> (llama-2-13b-chat.ggmlv3.q4_0 with all layers offloaded)

How do you offload the layers?

**Comment by Green-Sky** [comment]
> What is the prompting format for the chat model?

did not test, but https://github.com/facebookresearch/llama/blob/cfc3fc8c1968d390eb830e65c63865e980873a06/llama/generation.py#L44-L49

**Comment by asgeir** [comment]
> What is the prompting format for the chat model?

Looks like it's
```
[INST] <<SYS>>
Always answer only with emojis
<</SYS>>

How to go from Beijing to NY? [/INST]
```

**Comment by TheBloke** [comment]
> > Wouldn't be surprised if he's uploading from a service like AWS or Azure, those have insane bandwidth available.
> 
> As in, renting a VPS or dedicated server just to quantize + upload? (actually, come to think of it, that is an official recommendation by huggingface, wouldn't be surprised...)

Currently using 4 x LambdaLabs H100s



> > What is the prompting format for the chat model?
> 
> Looks like it's
> 
> ```
> [INST] <<SYS>>
> Always answer only with emojis
> <</SYS>>
> 
> How to go from Beijing to NY? [/INST]
> ```

I have put this in my READMEs, based on reading the generation.py, but am not 100% certain about it:
```
System: You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
User: {prompt}
Assistant:
```

**Comment by SlyEcho** [comment]
It seems like it also needs `BOS` and `EOS` tokens for every message pair

**Comment by Green-Sky** [comment]
> It seems like it also needs `BOS` and `EOS` tokens for every message pair

yes, it does https://github.com/facebookresearch/llama/blob/cfc3fc8c1968d390eb830e65c63865e980873a06/llama/generation.py#L248-L251

**Comment by SlyEcho** [comment]
It works with 4096 tokens out of the box.

**Comment by kacchan-001** [comment]
> > > > It works, but it is veeeeery slow in silicon macs.
> > > 
> > > 
> > > Hmm really? On the 13B one I get crazy-good speed.
> > > ![image](https://user-images.githubusercontent.com/20746719/254361824-30a6f8bd-163c-4aff-9c7e-bdd241283877.png)
> > 
> > Woah, apple silicon is literally god, I don't get anywhere near those speeds with my 3060 pulling hundreds of watts (:/)
> 
> huh nevermind
> 
> ![image](https://github.com/ggerganov/llama.cpp/assets/4723091/2e49a115-8766-46f2-8895-cf9d7b38f8d0)
> 
> (llama-2-13b-chat.ggmlv3.q4_0 with all layers offloaded)

Can you give me your main command? I couldn't get 13b running on a 3060

**Comment by wizzard0** [comment]
70B requires patches for GQA btw (as seen in TheBlokeAI discord)
https://github.com/facebookresearch/llama/commit/6d4c0c290aeec1fa4399694fefb864be5a153bb6

**Comment by SlyEcho** [comment]
Currently works in web chat with these settings:

prompt:
```
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
```

User name: `[INS]`
Bot name: `[/INS]`

Template:
```
<<SYS>>
{{prompt}}
<</SYS>>

{{history}} [/INS]
```

History template:
```
 {{name}} {{message}}
```

<details>
<summary>screenshot</summary>

![image](https://github.com/ggerganov/llama.cpp/assets/795193/703148fc-08bb-4834-8490-e77c33fa5d29)
</details>

However, it will reevaluate the last response all the time no matter how much I massage the whitespace, which I think is because it is adding the `BOS` tokens into the response and there is no way to model that right now in the API.

**Comment by jxy** [comment]
So the chat model uses something like

```
{BOS}[INST] <<SYS>>
{system}
<</SYS>>

{instruct-0} [/INST] {response-0} {EOS}{BOS}[INST] {instruct-1} [/INST] {response-1} {EOS}{BOS}[INST] {instruct-N} [/INST]
```

The model generate EOS automatically, but there's no way to insert BOS with the current code in this repo, neither in main nor in server.

**Comment by oobabooga** [comment]
Quantizing 70B works and generates a GGML, but loading the model fails with this error

> error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024

**Comment by SlyEcho** [comment]
EOS doesn't matter that much since it's in the end. main.cpp could handle it because it doesn't retokenize the history all the time. But currently the formatting is hardcoded for Alpaca-style models.

**Comment by 19h** [comment]
@oobabooga I was able to make it work by 1) commenting out the `if (lt.ne != ne) {` block from llama.cpp and 2) removing the `GGML_ASSERT(ggml_nelements(a) == ne0);`, `GGML_ASSERT(ggml_nelements(a) == ne0*ne1);`, `GGML_ASSERT(ggml_nelements(a) == ne0*ne1*ne2);`, and`GGML_ASSERT(ggml_nelements(a) == ne0*ne1*ne2*ne3);` asserts from ggml.c.

**Comment by 19h** [comment]
Also I had to fix some shizzle in the codebase to make it work with a 4096 context ...

**Comment by 19h** [comment]
Ok nvm, llama is producing garbage with the quantised 70b model..

![CleanShot 2023-07-19 at 03 04 26@2x](https://github.com/ggerganov/llama.cpp/assets/280212/8a2f62c9-a692-4e4c-ad21-e6579f1f4c9a)

**Comment by TheBloke** [comment]
@19h what about at 2048 context?

**Comment by 19h** [comment]
Pretty sure I fucked it up by ignoring the shape discrepancy.. garbage output always happening at all context sizes.

Pretty sure this is due to the Grouped-Query Attention (GQA) that's used with the 70B model as per the paper [0].

[0] https://scontent-fra3-1.xx.fbcdn.net/v/t39.2365-6/10000000_663429262362723_1696968207443577320_n.pdf?_nc_cat=101&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=5ol-jUSglG4AX9ujLdk&_nc_ht=scontent-fra3-1.xx&oh=00_AfC_KCiPbWk1TklOxA_A7j2jVxSbux7fjeoalGZZQ0D4VA&oe=64BBB691

**Comment by TheBloke** [comment]
OK thanks for the update. Yeah it was a bit surprising that just removing the checks would get it working, but you never know until you try!

**Comment by 19h** [comment]
@ggerganov once you have time to look into this, the paper is referencing this paper elaborating the GQA idea: https://arxiv.org/pdf/2305.13245.pdf.

**Comment by oobabooga** [comment]
So who will be the hero to implement GQA and send a PR? 😬

**Comment by 19h** [comment]
Trying to figure out the GQA implementation details .. https://github.com/facebookresearch/llama/issues/384.

**Comment by bullno1** [comment]
> So the chat model uses something like
> 
> ```
> {BOS}[INST] <<SYS>>
> {system}
> <</SYS>>
> 
> {instruct-0} [/INST] {response-0} {EOS}{BOS}[INST] {instruct-1} [/INST] {response-1} {EOS}{BOS}[INST] {instruct-N} [/INST]
> ```
> 
> The model generate EOS automatically, but there's no way to insert BOS with the current code in this repo, neither in main nor in server.

You mean from the CLI right?
Using the library, BOS is available as `llama_token_bos()`.

It might be possible to cook up something just for this.

Special syntax to express BOS/EOS from the CLI might be a bit of a pain

**Comment by kharvd** [comment]
Got this working with [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) based on https://github.com/facebookresearch/llama/blob/4d92db8a1db6c7f663252bf3477d2c4b8bad2385/llama/generation.py#L212:

```python
def make_prompt_llama2(llm, messages: List[Message]) -> List[int]:
    if messages[0]["role"] != "system":
        messages = [
            cast(
                Message,
                {
                    "role": "system",
                    "content": DEFAULT_SYSTEM_PROMPT,
                },
            )
        ] + messages
    messages = [
        cast(
            Message,
            {
                "role": messages[1]["role"],
                "content": B_SYS
                + messages[0]["content"]
                + E_SYS
                + messages[1]["content"],
            },
        )
    ] + messages[2:]
    assert all([msg["role"] == "user" for msg in messages[::2]]) and all(
        [msg["role"] == "assistant" for msg in messages[1::2]]
    ), (
        "model only supports 'system', 'user' and 'assistant' roles, "
        "starting with 'system', then 'user' and alternating (u/a/u/a/u...)"
    )

    dialog_tokens = sum(
        [
            llm.tokenize(
                bytes(
                    f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",
                    "utf-8",
                ),
                add_bos=True,
            )
            + [llm.token_eos()]
            for prompt, answer in zip(
                messages[::2],
                messages[1::2],
            )
        ],
        [],
    )
    assert (
        messages[-1]["role"] == "user"
    ), f"Last message must be from user, got {messages[-1]['role']}"

    dialog_tokens += llm.tokenize(
        bytes(f"{B_INST} {(messages[-1]['content']).strip()} {E_INST}", "utf-8"),
        add_bos=True,
    )

    return dialog_tokens
```

and then
```python
completion = llm.generate(tokenize(llm, [[
    {
        "role": "user",
        "content": "Hi",
    },
]])[0], top_p=0.9, temp=0.6, top_k=65535)

for token in completion:
    if token == llm.token_eos():
        break
    print(llm.detokenize([token]).decode("utf-8"), end="")
```

**Comment by tmm1** [comment]
are `[INST]` and `<<SYS>>` supposed to be tokens?

```
    518 -> ' ['                                                                                                             
 25580 -> 'INST'                                                                                                           
 29962 -> ']'                                                                                                              
  3532 -> ' <<'                                                                                                            
 14816 -> 'SY'                                                                                                             
 29903 -> 'S'                                                                                                              
  6778 -> '>>'

**Comment by kharvd** [comment]
The llama repo tokenizer seems normal to me with respect to the [INST] and <<SYS>>: https://github.com/facebookresearch/llama/blob/main/llama/tokenizer.py

**Comment by tmm1** [comment]
thanks @kharvd. I was able to get your sample working as well via llama-cpp-python

I notice that `llm.generate` is not able to stream the output, but `llm()` is. however when I tried to change `s/llm.generate/llm/ s/temp/temperature/` it still had some problems

**Comment by ggerganov** [comment]
I believe an initial version of GQA has been demonstrated by @jploski in (see https://github.com/ggerganov/llama.cpp/issues/1602#issuecomment-1606332010 and related comments).
It still needs some work to support BLAS and GPU backends.

**Comment by BEILOP** [comment]
How many 80g a100's should I have in order to fine-tune the 70b model

**Comment by philschmid** [comment]
> How many 80g a100's should I have in order to fine-tune the 70b model

1x is enough when using QLoRA and int-4

**Comment by ggerganov** [comment]
> I believe an initial version of GQA has been demonstrated by @jploski in (see https://github.com/ggerganov/llama.cpp/issues/1602#issuecomment-1606332010 and related comments).
It still needs some work to support BLAS and GPU backends.

Without looking into the details of GQA, and assuming my comment above is correct, I would guess that all it takes to support CPU inference for 70B would be something similar the following change that was made for the Falcon convert script:

https://github.com/jploski/ggml/blob/2e30a2b0356c1f3d589e670523fbca0b342e1438/examples/falcon/convert-hf-to-ggml.py#L105-L124

Again - I could be wrong. When I get access to the model will take a deeper look

**Comment by philschmid** [comment]
@ggerganov someone uploaded the weights on huggingface without the gate: https://huggingface.co/NousResearch/Llama-2-70b-hf. 
And its not against the license since it allows redistribution.

**Comment by Green-Sky** [comment]
We should really push for GGUF before adding GQA, to avoid an extra fileformat.

**Comment by Cookie771** [comment]
Hi !
I'm sorry i'm new on github. I tried to download Llama 2 but it's not working, the cmd's program close without downloading anything after I wrote the model  (I've download and install "wget" before, and i don't know how to get "md5sum" on Windows).
Can anybody help me please ?

**Comment by yaroslavyaroslav** [comment]
@ggerganov Just in case, I've got the access to the models download page, and I'll be happy to share it with you if it's still necessary via whatever channel you choose.

**Comment by Green-Sky** [comment]
The section on Redistribution (1.b.) reads like torrents would be legal under certain conditions.

**Comment by SlyEcho** [comment]
If you get the email from Facebook with the link, you can also apply to get access to their [Hugging Face Hub model pages](https://huggingface.co/meta-llama), if you're using the same email for the HF user registration.

**Comment by klosax** [comment]
> Hi ! I'm sorry i'm new on github. I tried to download Llama 2 but it's not working, the cmd's program close without downloading anything after I wrote the model (I've download and install "wget" before, and i don't know how to get "md5sum" on Windows). Can anybody help me please ?

@Cookie771 You can download quantized ggml files here:

https://huggingface.co/TheBloke/Llama-2-7B-GGML/tree/main
https://huggingface.co/TheBloke/Llama-2-13B-GGML/tree/main

**Comment by ggerganov** [comment]
I got official access and have already downloaded the models. Thanks

**Comment by Cookie771** [comment]
> > Hi ! I'm sorry i'm new on github. I tried to download Llama 2 but it's not working, the cmd's program close without downloading anything after I wrote the model (I've download and install "wget" before, and i don't know how to get "md5sum" on Windows). Can anybody help me please ?
> 
> @Cookie771 You can download quantized ggml files here:
> 
> https://huggingface.co/TheBloke/Llama-2-7B-GGML/tree/main https://huggingface.co/TheBloke/Llama-2-13B-GGML/tree/main

Thanks, is it the chat's version ?

**Comment by klosax** [comment]
> Thanks, is it the chat's version ?

Chat versions:

https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/tree/main
https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/tree/main

**Comment by JackJollimore** [comment]
> It works with 4096 tokens out of the box.

@SlyEcho Hi, I see the model is fine tuned for 4096 context. Are you using RoPe parameters, or what?

**Comment by alphadl** [comment]
[a not-relevant but important question] have anyone noticed that the ``max_position_embeddings`` is 2048 rather than 4096 in the downloaded hf llama2 checkpoints?

**Comment by SlyEcho** [comment]
I was using @TheBloke's quantized 7B model.

Just passed the args `-c 4086` and no scaling and a big file (>6000 tokens) with `-f` and it was generating coherent text.

**Comment by ggerganov** [comment]
I think I have a 70B prototype here: https://github.com/ggerganov/llama.cpp/pull/2276

Needs some more work and not 100% sure it is correct, but text generation looks coherent.

**Comment by wizzard0** [comment]
Note #2276 breaks non-GQA models:
```
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  4096 x   512, got  4096 x  4096
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'llama-2-7b.ggmlv3.q2_K.bin'
main: error: unable to load model
```

**Comment by TikkunCreation** [comment]
> So the chat model uses something like
> 
> ```
> {BOS}[INST] <<SYS>>
> {system}
> <</SYS>>
> 
> {instruct-0} [/INST] {response-0} {EOS}{BOS}[INST] {instruct-1} [/INST] {response-1} {EOS}{BOS}[INST] {instruct-N} [/INST]
> ```
> 
> The model generate EOS automatically, but there's no way to insert BOS with the current code in this repo, neither in main nor in server.

For clarity, it uses <s> and </s> for EOS and BOS (I checked with a python script using tokenizer.model)

**Comment by jxy** [comment]
I made a simple change to main to add BOS.

```patch
diff --git a/examples/main/main.cpp b/examples/main/main.cpp
index bcbcf12..5906cde 100644
--- a/examples/main/main.cpp
+++ b/examples/main/main.cpp
@@ -605,6 +605,8 @@ int main(int argc, char ** argv) {
             // replace end of text token with newline token when in interactive mode
             if (id == llama_token_eos() && params.interactive && !params.instruct) {
                 id = llama_token_newline.front();
+                embd_inp.push_back(llama_token_bos());
+                is_interacting = true;
                 if (params.antiprompt.size() != 0) {
                     // tokenize and inject first reverse prompt
                     const auto first_antiprompt = ::llama_tokenize(ctx, params.antiprompt.front(), false);
```

and run it like

```bash
./main -m "$MODEL" -c 4096 -n -1 --in-prefix ' [INST] ' --in-suffix ' [/INST]' -i -p \
"[INST] <<SYS>>
$SYSTEM
<</SYS>>

$FIRST_MESSAGE [/INST]"
```

I don't know if we want an argument like `--insert-bos-after-eos` to main.

Regarding `<s>` and `</s>`, main or server cannot encode those to BOS or EOS.

**Comment by SlyEcho** [comment]
I think `inp_pfx` and `inp_sfx` should also be changed?

**Comment by XiongjieDai** [comment]
> Hi ! I'm sorry i'm new on github. I tried to download Llama 2 but it's not working, the cmd's program close without downloading anything after I wrote the model (I've download and install "wget" before, and i don't know how to get "md5sum" on Windows). Can anybody help me please ?

If you have Git Bash installed, you can run the .sh file from the Git Bash command line with: ’bash path/to/script.sh‘

**Comment by XiongjieDai** [comment]
> Hi ! I'm sorry i'm new on github. I tried to download Llama 2 but it's not working, the cmd's program close without downloading anything after I wrote the model (I've download and install "wget" before, and i don't know how to get "md5sum" on Windows). Can anybody help me please ?

If you have Git Bash installed, you can run the .sh file from the Git Bash command line with: `bash` path/to/script.sh

**Comment by jxy** [comment]
> I think `inp_pfx` and `inp_sfx` should also be changed?

Those are hard coded for the instruct mode
```
  -ins, --instruct      run in instruction mode (use with Alpaca models)
```

**Comment by ziwang-com** [comment]
Global launch, llama2-map module library frame composition

【23-7-20】全球首发，llama2-map模块库架构图
[https://github.com/ziwang-com/AGI-MAP](https://github.com/ziwang-com/AGI-MAP)

**Comment by Green-Sky** [comment]
@ziwang-com those are just callgraphs for the python code. I'm sorry, but the python code already is simple to read as is, we don't really need those image. (also imho they feel harder to read than the python code)

**Comment by sowa705** [comment]
> > I think `inp_pfx` and `inp_sfx` should also be changed?
> 
> Those are hard coded for the instruct mode
> 
> ```
>   -ins, --instruct      run in instruction mode (use with Alpaca models)
> ```

Would it be possible to move them into the model file? That would solve the issue of different models having different prompt formats

**Comment by bullno1** [comment]
That would create the issue of creating a templating language

**Comment by viniciusarruda** [comment]
Is Meta tokenizer identical to llama_cpp tokenizer? I think it should be. But I'm having a issue while decoding/encoding. 
This is also related to the chat completion format already mentioned above by @kharvd @jxy @TikkunCreation 
You can see the issue in details and also replicate it [here](https://github.com/viniciusarruda/llama-cpp-chat-completion-wrapper/#issues). I'm comparing Meta original tokenizer with a model from @TheBloke .

**Comment by jxy** [comment]
for llama-2-chat, #2304

**Comment by jxy** [comment]
and server, #2306

**Comment by ggerganov** [comment]
70B support should be ready to merge in #2276 

Btw, I did some tests with 7Bv2 and the generated texts from short prompts using `Q4_0` and `Q5_0` definitely feel weird. I wrote more about it in the PR description. Would be nice if other people confirm the observations.

**Comment by kurnevsky** [comment]
It doesn't work with the following input:
```
llama-cpp -c 4096 -gqa 8 -t 16 -m llama-2-70b.ggmlv3.q4_K_M.bin -p "### HUMAN:\na\n\n### RESPONSE:\nb\n\n### HUMAN:\nb\n\n### RESPONSE:"
```

The error is `GGML_ASSERT: /build/source/ggml.c:10648: ne02 == ne12`.

**Comment by WiSaGaN** [comment]
> 

It worked in the vanilla case for me, but got similar error when I run the binary from "make LLAMA_CLBLAST=1". "-gqa 8" was added in both cases.

**Comment by kurnevsky** [comment]
I actually do use `LLAMA_CLBLAST`, but tested without gpu offloading - didn't know it affects the execution somehow :)
And I got this error on the model from https://huggingface.co/TheBloke/Llama-2-70B-GGML

**Comment by Cebtenzzre** [comment]
> I am having same problem, are you able to fix it?

See #3002. The only workaround I know of is to not use the OpenCL backend with LLaMA 2.

**Comment by kleenkanteen** [comment]
@tikikun What do you mean to add the llama 2 model when this repo about the llama model? Also on the main page why does it say "Supported models:" and then lists a bunch of other LLMs when this repo is just about llama?

**Comment by ggerganov** [comment]
LLaMA v2 and many other models are currently supported by `llama.cpp`.
See the [status page](https://github.com/ggerganov/llama.cpp/discussions/3471) for more info

**Comment by ggerganov** [comment]
No, `llama.cpp` can run inference for all model architectures listed in the status page. It started just with LLaMA v1, but since then there has been a lot of progress and it now supports a variety of models.
