### ISSUE TITLE
CUDA Error 400: Invalid Resource Handle when Running on Single GPU

### ISSUE THREAD

**Issue by michelg10** [ggerganov/llama.cpp#2269]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I am trying to make `llama.cpp` run on a single GPU (in my case, GPU 5) on a multi-GPU system because there are other tasks running on my other GPUs.

# Current Behavior

`llama.cpp` crashes with `CUDA error 400 at ggml-cuda.cu:3343: invalid resource handle`

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              112
On-line CPU(s) list: 0-111
Thread(s) per core:  2
Core(s) per socket:  28
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz
Stepping:            6
CPU MHz:             1000.013
CPU max MHz:         4000.0000
CPU min MHz:         1000.0000
BogoMIPS:            5400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-27,56-83
NUMA node1 CPU(s):   28-55,84-111
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

* Operating System

Linux cb68e1005cfb 4.15.0-184-generic #194-Ubuntu SMP Thu Jun 2 18:54:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* SDK version:

```
Python 3.10.12
GNU Make 4.1
g++-11 (Ubuntu 11.4.0-2ubuntu1~18.04) 11.4.0
```

# Failure Information (for bugs)

llama.cpp crashes after outputting

```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
```

with `CUDA error 400 at ggml-cuda.cu:3343: invalid resource handle`

# Steps to Reproduce

1. Run `llama.cpp` with the arguments `-ts 0,0,0,0,0,100,0,0,0,0 -mg 5` (to try to instruct `llama.cpp` to only utilize GPU 5)

# Failure Logs

```
./main -m '/home/michel/workspace/Inference Models/chinese-alpaca-plus-7b-f16-ggml.bin' -c 2048 --interactive-first --color --reverse-prompt "User:" --in-suffix "Assistant:" --prompt $'The following is a conversation between an AI assistant called Assistant and a human user called User.\nThe assistant is intelligent, knowledgeable and polite to answer questions of user.\n\n' -ngl 40 -ts 0,0,0,0,0,100,0,0,0,0 -mg 5
main: build = 0 (unknown)
main: seed  = 1689738272
ggml_init_cublas: found 10 CUDA devices:
  Device 0: GeForce RTX 3090, compute capability 8.6
  Device 1: GeForce RTX 3090, compute capability 8.6
  Device 2: GeForce RTX 3090, compute capability 8.6
  Device 3: GeForce RTX 3090, compute capability 8.6
  Device 4: GeForce RTX 3090, compute capability 8.6
  Device 5: GeForce RTX 3090, compute capability 8.6
  Device 6: GeForce RTX 3090, compute capability 8.6
  Device 7: GeForce RTX 3090, compute capability 8.6
  Device 8: GeForce RTX 3090, compute capability 8.6
  Device 9: GeForce RTX 3090, compute capability 8.6
llama.cpp: loading model from /home/michel/workspace/Inference Models/chinese-alpaca-plus-7b-f16-ggml.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 5 (GeForce RTX 3090) as main device
llama_model_load_internal: mem required  = 2062.35 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 14154 MB
llama_new_context_with_model: kv self size  = 1024.00 MB

system_info: n_threads = 56 / 112 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
main: interactive mode on.
Reverse prompt: 'User:'
Input suffix: 'Assistant:'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 2048, n_batch = 512, n_predict = -1, n_keep = 0


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

CUDA error 400 at ggml-cuda.cu:3343: invalid resource handle
```

**Comment by SlyEcho** [comment]
Did you try [CUDA_VISIBLE_DEVICES](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/)?

**Comment by Vertigor** [comment]
I meet the same problem.who can resolve it?

**Comment by Vertigor** [comment]
I try CUDA_VISIBLE_DEVICES=0 and solve the problem. Multiple gpus may cause the error.

**Comment by huangyingting** [comment]
I have same issue, I am using 4 GPUs

api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr ggml_init_cublas: found 4 CUDA devices:
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr   Device 0: Tesla T4, compute capability 7.5
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr   Device 1: Tesla T4, compute capability 7.5
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr   Device 2: Tesla T4, compute capability 7.5
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr   Device 3: Tesla T4, compute capability 7.5
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama.cpp: loading model from /models/wizardlm-13b-v1.2.ggmlv3.q8_0.bin
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: format     = ggjt v3 (latest)
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_vocab    = 32000
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_ctx      = 2000
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_embd     = 5120
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_mult     = 256
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_head     = 40
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_head_kv  = 40
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_layer    = 40
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_rot      = 128
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_gqa      = 1
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: rnorm_eps  = 5.0e-06
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: n_ff       = 13824
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: freq_base  = 10000.0
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: freq_scale = 1
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: ftype      = 7 (mostly Q8_0)
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: model size = 13B
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: ggml ctx size =    0.11 MB
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: using CUDA for GPU acceleration
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr ggml_cuda_set_main_device: using device 0 (Tesla T4) as main device
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: mem required  =  656.13 MB (+ 1562.50 MB per state)
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 477 MB VRAM for the scratch buffer
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: offloading 40 repeating layers to GPU
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: offloading non-repeating layers to GPU
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: offloading v cache to GPU
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: offloaded 42/43 layers to GPU
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_model_load_internal: total VRAM used: 14282 MB
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr llama_new_context_with_model: kv self size  = 1562.50 MB
api_1  | 5:21AM DBG GRPC(wizardlm-13b-v1.2.ggmlv3.q8_0.bin-127.0.0.1:35873): stderr CUDA error 400 at /build/go-llama/llama.cpp/ggml-cuda.cu:4973: invalid resource handle
api_1  | [172.26.0.1]:37254  500  -  POST     /v1/chat/completions
