### ISSUE TITLE
Support for Baichuan-13B on GPU inference. (CUDA version of ALiBi OP)

### ISSUE THREAD

**Issue by LiuKai22** [ggerganov/llama.cpp#2273]
Baichuan-13B is a new SFT model based on llama-13B, huge performance improvement on MMLU and C-Eval.

ggml already supports ALiBi OP, so I add some changes in llama.cpp's "llama_eval_internal" and replace RoPE with ALiBi. 

And it works  for CPU inference, but the eval speed is slow since CUDA version of alibi OP is not supported, like "ggml_cuda_op_alibi" and "alibi_f32_cuda" in ggml-cuda.cu.

So, currently there is no GPU acceleration for models like Baichuan 13B. Is anyone has a plan on this? @ggerganov @JohannesGaessler

**Comment by JohannesGaessler** [comment]
Unless I'm misinformed Baichuan is a model specifically for Chinese. I don't speak Chinese so I'm not interested in implementing GPU acceleration. I am however willing to provide guidance on how to do it if it doesn't require too much time on my end.

**Comment by LiuKai22** [comment]
> Unless I'm misinformed Baichuan is a model specifically for Chinese.

Not just because the Baichuan model, I think ALiBi is a good position embedding method, and it is already implemented in ggml.c. There are many more models like Baichuan start using ALiBi, like MPT, BLOOM . It is very worthwhile to implement GPU acceleration for such OP.

> I am however willing to provide guidance on how to do it if it doesn't require too much time on my end.

Much appreciated. I will try that. 

From my point of view, next thing I need to do is implement "ggml_cuda_op_alibi" and "alibi_f32_cuda", and follow the way how ggml_cuda_op is calling an OP computation.

Any other advice ?

**Comment by JohannesGaessler** [comment]
CUDA isn't used automatically. You will need to manually move tensors to the GPU, see `llama_eval_internal` and `llama_load_internal`.

**Comment by riverzhou** [comment]
> > Unless I'm misinformed Baichuan is a model specifically for Chinese.
> 
> Not just because the Baichuan model, I think ALiBi is a good position embedding method, and it is already implemented in ggml.c. There are many more models like Baichuan start using ALiBi, like MPT, BLOOM . It is very worthwhile to implement GPU acceleration for such OP.
> 
> > I am however willing to provide guidance on how to do it if it doesn't require too much time on my end.
> 
> Much appreciated. I will try that.
> 
> From my point of view, next thing I need to do is implement "ggml_cuda_op_alibi" and "alibi_f32_cuda", and follow the way how ggml_cuda_op is calling an OP computation.
> 
> Any other advice ?

Any news?

**Comment by helldog-star** [comment]
> 

Hi, I'm also trying to implement Alibi on the GPU. How's your progress going?
