### ISSUE TITLE
GPU offloading,  but there's no response output

### ISSUE THREAD

**Issue by luoweb** [ggerganov/llama.cpp#2274]
GPU offloading,  but the result can not output, it wait a very long time…

debug log as follows: 

ggml_init_cublas: found 2 CUDA devices: Device 0: NVIDIA A100-PCIE-40GB Device 1: NVIDIA A100-PCIE-40GB llama.cpp: loading model from /models/vicuna-13b-v1.3.0.ggmlv3.q4_1.bin llama_model_load_internal: format = ggjt v3 (latest) llama_model_load_internal: n_vocab = 32000 llama_model_load_internal: n_ctx = 512 llama_model_load_internal: n_embd = 5120 llama_model_load_internal: n_mult = 256 llama_model_load_internal: n_head = 40 llama_model_load_internal: n_layer = 40 llama_model_load_internal: n_rot = 128 llama_model_load_internal: ftype = 3 (mostly Q4_1) llama_model_load_internal: n_ff = 13824 llama_model_load_internal: model size = 13B llama_model_load_internal: ggml ctx size = 0.09 MB llama_model_load_internal: using CUDA for GPU acceleration ggml_cuda_set_main_device: using device 0 (NVIDIA A100-PCIE-40GB) as main device llama_model_load_internal: mem required = 2145.75 MB (+ 1608.00 MB per state) llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer llama_model_load_internal: offloading 40 repeating layers to GPU llama_model_load_internal: offloading non-repeating layers to GPU llama_model_load_internal: offloading v cache to GPU llama_model_load_internal: offloading k cache to GPU llama_model_load_internal: offloaded 43/43 layers to GPU llama_model_load_internal: total VRAM used: 9782 MB llama_new_context_with_model: kv self size = 400.00 MB llama_predict: attempting to load saved session from '/models/vicuna-cache' llama_predict: loaded a session with prompt size of 17 tokens llama_predict: session file has exact match for prompt!

**Comment by swapaj** [comment]
Similar issue ... I can see that model has been loaded on GPU but when it runs ... its using CPUs and GPU utilisation is 0. 
Mac, Mac-Metal working fine .. issue with Ubuntu + GPU run.

**Comment by swapaj** [comment]
Using `https://github.com/abetlen/llama-cpp-python/tree/main` and now everything working fine. The backend is the same .. not sure what the issue is.
