### ISSUE TITLE
7B/13B: Inability to write certain words/names with smaller models

### ISSUE THREAD

**Issue by niansa** [ggerganov/llama.cpp#228]
Hey!

When I attempted to tell the bot in a chat-like prompt that my name is "Nils", I ran into an issue where the bot kept interpreting my name as "Nil" instead. I then noticed further issues with the word "guild" and some other words too.
Is this a bug or to be expected? It does not happen on 30B, I couldn't give 65B a try.

Thanks
Niansa

**Comment by gjmulder** [comment]
Larger models are going to perform better. They "understand" a wider range of concepts such as the difference between "niL" and "nils".

**Comment by niansa** [comment]
Alright, that explains it. Thanks!
