### ISSUE TITLE
Web Chat server does not properly escape HTML output

### ISSUE THREAD

**Issue by coder543** [ggerganov/llama.cpp#2300]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When Llama 2 generates code as output, it should not be rendered in the chat output, since that both defies expectations and renders the code unreadable.

# Current Behavior

it renders an inline dropdown element, instead of showing the code:

![image](https://github.com/ggerganov/llama.cpp/assets/726063/352c86ef-86d1-4488-a9c3-8bf307b97b6e)

# Steps to Reproduce

1. Ask Llama 2 to generate some kind of HTML
2. The HTML that it generates will be rendered inline instead of written as a code block

I followed [these instructions](https://github.com/ggerganov/llama.cpp/issues/2262#issuecomment-1640950910) to get the web chat working, and it seems to work great as long as no HTML is being emitted by the model.

**Comment by Green-Sky** [comment]
fun in its own regard. :)
