### ISSUE TITLE
Use clblast for the flake.nix

### ISSUE THREAD

**Issue by leiserfg** [ggerganov/llama.cpp#2335]
Considering that a good quality opencl is now shipped as part of mesa, isn't better to use clblas as default blas backend?

**Comment by Freed-Wu** [comment]
Will fixed by https://github.com/ggerganov/llama.cpp/pull/2337

**Comment by Freed-Wu** [comment]
See <https://github.com/ggerganov/llama.cpp/wiki#install>.
