### ISSUE TITLE
ggml_opencl: device FP16 support: false (dGPU), true (iGPU)

### ISSUE THREAD

**Issue by Lhasrt** [ggerganov/llama.cpp#2343]
Linux 6.3.7
Driver Version: 525.116.04   CUDA Version: 12.0 

When I offload to the Nvidia GPU with opencl, it produces garbage. A few weeks ago, everything was fine (before some kernel and gpu driver updates).

Clinfo reports cl_khr_fp16 for Intel iGPU, but not for Nvidia GPU. I assume this is related to "device FP16 support: false".

I have no idea how to troubleshoot this. 

Cuda still works, but eval prompt is slower than opencl.

**Comment by yukiteruamano** [comment]
Hi! 

If  `clinfo` output show `**FP16 support: false**` for your NVIDIA, this is an issue with your driver on your Linux distribution, please report the issue in OS bug tracker. 

More info over this issue here: https://forums.developer.nvidia.com/t/cl-khr-fp16-opencl-support/191106/2

**Comment by kelteseth** [comment]
FP16 support has been added to NV OpenCL 551.52 update: https://us.download.nvidia.com/Windows/551.52/551.52-win11-win10-release-notes.pdf

> 2.8.1.1 NVVM 7.0 New Compiler Features
> The new NVVM 7.0 based compiler takes advantage of years of development in the
> Clang+LLVM framework. In addition to several minor bug fixes and diagnostic
> improvements, this compiler introduces the following noteworthy features:
> > 16-bit floating point (half) type
> 16-bit floating point types or “half” type is available as a native data type in the new
> compiler. This type is enabled by the cl_khr_fp16 feature guard pragma.
> Example:

```cpp
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
half scalar_arith(half n, half k) {
    half w = n + k;
    half x = n - k;
    half y = w * x;
    half z = y / x;
    return -z;
}
__kernel void foo(__global int* x) {
    half a = 3.5H, b = 4.5H;
    if (scalar_arith(a, b) == -8.0)
    *x = 1;
    return;
}

```

**Comment by yukiteruamano** [comment]
Good news!
