### ISSUE TITLE
Llama 2 70B - with --prompt-cache memory.txt crashing without error 

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#2350]
Llama 2 70B - with --prompt-cache memory.txt llamacpp is crashing without any error.

my full command 

build\bin\main --model models\new2\llama-2-70b-chat.ggmlv3.q4_K_M.bin --mlock --color --threads 16 --keep -1 --batch_size 512 --n_predict -1 --top_k 40 --top_p 0.9 --temp 0.96 --repeat_penalty 1.1 --ctx_size 4096 --interactive  --gqa 8 --instruct --reverse-prompt "### Human:" --reverse-prompt "### User:" --reverse-prompt "### Assistant:" --prompt-cache memory.txt

**Comment by ggerganov** [comment]
Is it crashing just for 70B models?

**Comment by mirek190** [comment]
Yes only with llama 2 70B .
I tested smaller llama 2 models and llama 1 all sizes .
All are ok except llama 2 70B.

**Comment by slaren** [comment]
Probably `llama_set_state_data`, `llama_copy_state_data` need to be updated to use `n_embd_gqa` instead of `n_embd`.

**Comment by randxie** [comment]
Can confirm the command crashes from a ubuntu machine.

Run the command for the first time works:

```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 
> 
1950s as part of a larger campaign to suppress dissent and maintain control over the population. The regime used various tactics to enforce its policies, including propaganda, censorship, repression, and violence.
```

Then exit the program and run the same command that attempts to load saved session, it will give `Segmentation fault`:

```
system_info: n_threads = 16 / 32 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
main: attempting to load saved session from 'memory.txt'
Segmentation fault (core dumped)
```
