### ISSUE TITLE
quantize exiting prematurely without error msg

### ISSUE THREAD

**Issue by anujcb** [ggerganov/llama.cpp#2361]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ Yes] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ Yes] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ Yes] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

llama.cpp generates ggml-model-q4_0.bin

# Current Behavior

I am able to build using cmake. 
downloaded the .pth file from https://huggingface.co/nyanko7/LLaMA-7B/tree/main
I was able to create ggml-model-f16.bin in the models dir
When i ran quantize, it runs for a bit and exits with out creating the ggml-model-q4_0.bin

Here is what i see in the console

PS F:\work\llama.cpp> ./build/bin/release/quantize models/ggml-model-f16.bin models/ggml-model-q4_0.bin 2
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070, compute capability 6.1
main: build = 894 (2f9cf97)
main: quantizing 'models/ggml-model-f16.bin' to 'models/ggml-model-q4_0.bin' as Q4_0
PS F:\work\llama.cpp>

Processor	Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)
OS Name	Microsoft Windows 10 Pro
Nvidia toolkit 11.8

# Environment and Context

Processor	Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)
OS Name	Microsoft Windows 10 Pro
Nvidia toolkit 11.8
VS 22 community edition
Python 3.11.4

PS F:\work\llama.cpp> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

PS F:\work\llama.cpp\build> cmake .. -DLLAMA_CUBLAS=ON
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
-- cuBLAS found
-- Using CUDA architectures: 52;61
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (4.8s)
-- Generating done (0.6s)
-- Build files have been written to: F:/work/llama.cpp

PS F:\work\llama.cpp> cmake --build . --config Release
MSBuild version 17.6.3+07e294721 for .NET Framework

  ggml.vcxproj -> F:\work\llama.cpp\ggml.dir\Release\ggml.lib
  llama.cpp
  llama.vcxproj -> F:\work\llama.cpp\Release\llama.lib
  common.vcxproj -> F:\work\llama.cpp\examples\common.dir\Release\common.lib
  baby-llama.vcxproj -> F:\work\llama.cpp\bin\Release\baby-llama.exe
  benchmark.vcxproj -> F:\work\llama.cpp\bin\Release\benchmark.exe
  embdinput.vcxproj -> F:\work\llama.cpp\examples\embd-input\Release\embdinput.lib
  embd-input-test.vcxproj -> F:\work\llama.cpp\bin\Release\embd-input-test.exe
  embedding.vcxproj -> F:\work\llama.cpp\bin\Release\embedding.exe
  ggml_static.vcxproj -> F:\work\llama.cpp\Release\ggml_static.lib
  main.vcxproj -> F:\work\llama.cpp\bin\Release\main.exe
  perplexity.vcxproj -> F:\work\llama.cpp\bin\Release\perplexity.exe
  q8dot.vcxproj -> F:\work\llama.cpp\bin\Release\q8dot.exe
  quantize.vcxproj -> F:\work\llama.cpp\bin\Release\quantize.exe
  quantize-stats.vcxproj -> F:\work\llama.cpp\bin\Release\quantize-stats.exe
  save-load-state.vcxproj -> F:\work\llama.cpp\bin\Release\save-load-state.exe
  server.vcxproj -> F:\work\llama.cpp\bin\Release\server.exe
  simple.vcxproj -> F:\work\llama.cpp\bin\Release\simple.exe
  test-grad0.vcxproj -> F:\work\llama.cpp\bin\Release\test-grad0.exe
  test-quantize-fns.vcxproj -> F:\work\llama.cpp\bin\Release\test-quantize-fns.exe
  test-quantize-perf.vcxproj -> F:\work\llama.cpp\bin\Release\test-quantize-perf.exe
  test-sampling.vcxproj -> F:\work\llama.cpp\bin\Release\test-sampling.exe
  test-tokenizer-0.vcxproj -> F:\work\llama.cpp\bin\Release\test-tokenizer-0.exe
  train-text-from-scratch.vcxproj -> F:\work\llama.cpp\bin\Release\train-text-from-scratch.exe
  vdot.vcxproj -> F:\work\llama.cpp\bin\Release\vdot.exe
PS F:\work\llama.cpp>

F:\work\llama.cpp\models>certutil -hashfile consolidated.00.pth SHA256
SHA256 hash of consolidated.00.pth:
700df0d3013b703a806d2ae7f1bfb8e59814e3d06ae78be0c66368a50059f33d
CertUtil: -hashfile command completed successfully.

PS F:\work\llama.cpp> python3 convert.py models
Loading model file models\consolidated.00.pth
Loading vocab file models\tokenizer.model
params: n_vocab:32000 n_embd:4096 n_mult:256 n_head:32 n_layer:32
Writing vocab...
[  1/291] Writing tensor tok_embeddings.weight                  | size  32000 x   4096  | type UnquantizedDataType(name='F16')
[  2/291] Writing tensor norm.weight                            | size   4096           | type UnquantizedDataType(name='F32')
..............
[290/291] Writing tensor layers.31.feed_forward.w3.weight       | size  11008 x   4096  | type UnquantizedDataType(name='F16')
[291/291] Writing tensor layers.31.ffn_norm.weight              | size   4096           | type UnquantizedDataType(name='F32')
Wrote models\ggml-model-f16.bin
PS F:\work\llama.cpp>

PS F:\work\llama.cpp> ./build/bin/release/quantize models/ggml-model-f16.bin models/ggml-model-q4_0.bin 2
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070, compute capability 6.1
main: build = 894 (2f9cf97)
main: quantizing 'models/ggml-model-f16.bin' to 'models/ggml-model-q4_0.bin' as Q4_0
PS F:\work\llama.cpp>

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

1. cmake .. -DLLAMA_CUBLAS=ON
2. cmake --build . --config Release
3. python3 convert.py models
4. ./build/bin/release/quantize models/ggml-model-f16.bin models/ggml-model-q4_0.bin 2

# Failure Logs

none

**Comment by anujcb** [comment]
![llama](https://github.com/ggerganov/llama.cpp/assets/565237/c65c1a06-75ec-427b-b25d-213f5db606de)
looks like this is where it is failing

**Comment by anujcb** [comment]
![llama1](https://github.com/ggerganov/llama.cpp/assets/565237/088e9859-7518-4582-b56d-41a804be1c6e)
Looks like the 10 words are red from the file ggml-model-f16.bin, the 10th word in the file have an issue

**Comment by goerch** [comment]
First idea: does this behavior persist if you reduce number of threads to one? If yes, it could be helpful to catch `std::exception` in `main` and try to see if and what kind of exception is thrown (by `std::unordered_map`?). Maybe even easier: try  a debug run?

**Comment by anujcb** [comment]
> std::exception

That is the weird part. I tried adding both the std::runtime_error and std::exception, nothing thrown. Also changed the thread to 1.

![image](https://github.com/ggerganov/llama.cpp/assets/565237/f9fc2896-6d3e-449d-b765-2fbc7af732c6)
![image](https://github.com/ggerganov/llama.cpp/assets/565237/e1f52c08-baef-4f01-a28c-bd74fdf3ee6f)

**Comment by anujcb** [comment]
i tried with the 13B v1 and 7 vB v2, same issue

**Comment by goerch** [comment]
Then I assume an access violation. If you let the program crash in a shell you'll see `some` information in the event viewer.

**Comment by anujcb** [comment]
how would i do that? i am running it from the PoweShell? Should i look in windows event log?

**Comment by anujcb** [comment]
I wonder why this docent throw an exception

**Comment by goerch** [comment]
`llama.cpp` does use some `mmap`-magic. I'd not be surprised if we need some Windows runtime error handling to catch such problems. But maybe there is some error handling missing inside `llama.cpp`.

**Comment by anujcb** [comment]
do you suggest i do a CHKDSK /F? u think its a disk problem? or build this from another location/drive?

**Comment by goerch** [comment]
I don't know enough about your environment, but I'd try logon/logoff and then reboot first.

**Comment by anujcb** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/565237/8e711d76-b413-443d-add4-ad1a3899483f)
I wrote a separate program with replicating the read_vocab(), it looks like the issue is the memory, at 6 words, it pretty much ate up 27GB of memory

**Comment by goerch** [comment]
OK, for me this looks like you are having a serious issue. I had tried a download of the model you mentioned and a conversion using the current main branch. So I can only assume

* you are not using current main branch
* your download is corrupted
* or else (hardware, OS?)

Sorry for not being really helpful...

(I don't understand the memory requirements you mention, although I have to admit I'm on 64 GB, but this shouldn't be necessary for llama-7B).

**Comment by anujcb** [comment]
can you point me to the place you downloaded the v1 7B bin file, also where did you download the .pth file?

**Comment by anujcb** [comment]
i could try your converted bin file, can you share the bin file you created. In the mean time let me refresh the code from main

**Comment by anujcb** [comment]
ok, some progress, i was bale to pull out the code to read the bin file into a console application and run it outside of llama.cpp and it ran all the way to 32000(hparams.n_vocab) and was successfully complete         read_magic();  read_hparams(); and  read_vocab(); routines. This eliminated the fact that there is any file corruption issue or system issue in reading the file.

The same code within llama.cpp for those routines stops after the 10th iteration.

![image](https://github.com/ggerganov/llama.cpp/assets/565237/181fa3e6-7b49-46f6-ab7c-ffc97602fe88)
![image](https://github.com/ggerganov/llama.cpp/assets/565237/abbbec81-386e-42db-9956-7f598657196e)

**Comment by anujcb** [comment]
by the way, what is the right formatter to print the "word" read from the file?

        std::string word = file.read_string(len);
        fprintf(stderr, "llama.cpp: inside read_vocab word **%s**\n", **word**);

**Comment by goerch** [comment]
Format string `%s` is correct, access the raw data with `word.c_str()`.

**Comment by goerch** [comment]
Interesting: can reproduce now. This happens on MSVC (I switched to the integrated Clang compiler recently).

**Comment by anujcb** [comment]
some progress using clang compiler, at least i am getting a message



![image](https://github.com/ggerganov/llama.cpp/assets/565237/21a1354c-042b-4639-8ee7-186fbff0983f)

![image](https://github.com/ggerganov/llama.cpp/assets/565237/22f28583-68ff-460a-80f8-9262ab7ff9c9)

**Comment by anujcb** [comment]
the issue is in this line

vocab.token_to_id[word] = i;

The unordered map is not able to take in the word read from the file. It exits without any message. Looks like when the word is a special character it coughs up.

std::unordered_map<token, id> token_to_id;

**Comment by anujcb** [comment]
Finally success....the issue was with the unordered_map, i changed it to regular map and it worked. CHanged two places, llama_vocab and llama_load_tensors_map

![image](https://github.com/ggerganov/llama.cpp/assets/565237/90e92bc3-fdab-49ac-a542-3c5549d8e70d)
![image](https://github.com/ggerganov/llama.cpp/assets/565237/0bd79592-4b48-4809-b7fd-177fba62c4bf)

**Comment by goerch** [comment]
> Interesting: can reproduce now. This happens on MSVC (I switched to the integrated Clang compiler recently).

Sorry, I have to retract this confirmation: just retested and main works fine with MSVC, too. Most probably a testing error on my side!

**Comment by Cebtenzzre** [comment]
This seems like heap corruption more than anything else. Since you are using clang-cl already, maybe you could try to build with AddressSanitizer?
https://github.com/google/sanitizers/wiki/AddressSanitizerWindowsPort
