### ISSUE TITLE
empty generation on 84e09a7 

### ISSUE THREAD

**Issue by staviq** [ggerganov/llama.cpp#2367]
I'm getting empty responses in this latest update 84e09a7, which didn't happen in d2a4366 that I was using before.

I'm using mostly unmodified persistent chat script with TheBloke/Nous-Hermes-Llama2-GGML model q4km.

I downloaded and compiled the 84e09a7as soon as I saw it, I copied the model, the prompt template, the persistent data and the chat script.

It complained about incompatible persistent data, so I removed persistent data and let the script regenerate it, and after starting, each response is empty and consists only of the name, as in "ainame: " and nothing else. No crashes or anything, just each response is empty.

I went back to d2a4366, and I also deleted the persistent data just to make sure that wasn't the problem, and let the script regenerate it, and it ran fine, responses are normal.

So I'm not sure what is going on, but it definitely happened between those two releases.

**Comment by anildwarepo** [comment]
Hi, 

I am also getting empty response. Please see below output. 

./main -m ./models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512
main: build = 899 (41c6741)
main: seed  = 1690233140
llama.cpp: loading model from ./models/7B/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 3949.96 MB (+  256.00 MB per state)
llama_new_context_with_model: kv self size  =  256.00 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 512, n_keep = 0


 Building a website can be done in 10 simple steps:
 sierpandesign.com/10-steps-to-build-a-website/ [end of text]

llama_print_timings:        load time = 61127.43 ms
llama_print_timings:      sample time =    10.59 ms /    22 runs   (    0.48 ms per token,  2077.43 tokens per second)
llama_print_timings: prompt eval time =  2208.09 ms /    14 tokens (  157.72 ms per token,     6.34 tokens per second)
llama_print_timings:        eval time =  3618.97 ms /    21 runs   (  172.33 ms per token,     5.80 tokens per second)
llama_print_timings:       total time =  5842.60 ms

**Comment by yagil** [comment]
@staviq probably same as https://github.com/ggerganov/llama.cpp/issues/2350. 
@anildwarepo you actually did get a response `sierpandesign.com/10-steps-to-build-a-website/ [end of text]`

**Comment by staviq** [comment]
No longer reproducible.
