### ISSUE TITLE
No output after commit 84d9015 on Android

### ISSUE THREAD

**Issue by gjmulder** [ggerganov/llama.cpp#237]
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **ShouNichi** March 17, 2023</sup>
When `git checkout 84d9015` and `make`, there will be no output (only the model loading message) in termux.
`git checkout 63fd76f` will produce a fully-functional binary.</div>

I've moved this to issues. Please provide sample output from the working build and the non-working build.

**Comment by ShouNichi** [comment]
The output here. Meanwhile, the latest commit doesn't work either.
However, on another device it will spit out error messages like
```
ggml.c:1364:25: warning: call to undeclared function 'vdotq_s32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        int32x4_t p_0 = vdotq_s32(vdupq_n_s32(0), v0_0ls, v1_0ls);
                        ^
ggml.c:1364:19: error: initializing 'int32x4_t' (vector of 4 'int32_t' values) with an expression of incompatible type 'int'
        int32x4_t p_0 = vdotq_s32(vdupq_n_s32(0), v0_0ls, v1_0ls);
                  ^     ~~~~~~~~~
ggml.c:1365:19: error: initializing 'int32x4_t' (vector of 4 'int32_t' values) with an expression of incompatible type 'int'
        int32x4_t p_1 = vdotq_s32(vdupq_n_s32(0), v0_1ls, v1_1ls);
                  ^     ~~~~~~~~~
ggml.c:1367:13: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
        p_0 = vdotq_s32(p_0, v0_0hs, v1_0hs);
            ^ ~~~~~~
ggml.c:1368:13: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
        p_1 = vdotq_s32(p_1, v0_1hs, v1_1hs);
            ^ ~~~~~~
1 warning and 4 errors generated.
make: *** [Makefile:182: ggml.o] Error 1
```
and would work just file, so I assume it is a device specific issue.
The original output is
[terminal output.txt](https://github.com/ggerganov/llama.cpp/files/11003959/terminal.output.txt)

**Comment by j-f1** [comment]
The latest commit should include the changes from https://github.com/ggerganov/llama.cpp/pull/139 which ar supposed to avoid the usage of `vdotq_s32` if it isn’t available, but maybe a usage snuck in somewhere?
