### ISSUE TITLE
Cannot convert the gpt4all-lora-quantized.bin into ggml

### ISSUE THREAD

**Issue by shreesha345** [ggerganov/llama.cpp#2388]
![Screenshot (32)](https://github.com/ggerganov/llama.cpp/assets/71629361/d3c00839-858a-4e70-85f9-036a03db01b3)

**Comment by shreesha345** [comment]
anyone can fix this

**Comment by goerch** [comment]
My `convert.py` fetched from repository shows at line 960

```
        fp.seek(size, io.SEEK_CUR)
```

Are you running an older version? I'd recommend updating and retrying then.

**Comment by quantonganh** [comment]
https://github.com/ggerganov/llama.cpp/issues/2080#issuecomment-1619490637

**Comment by shreesha345** [comment]
I have installed the latest on

**Comment by shreesha345** [comment]
But I have this error

**Comment by shreesha345** [comment]
Let me try what you sent me and then if it works I will close this issue
