### ISSUE TITLE
I can't run llama v2 13B on GPU after  make LLAMA_CUBLAS=1

### ISSUE THREAD

**Issue by gabrielcustodio** [ggerganov/llama.cpp#2396]
```
(llm) user@gpu:~/projects/llama/llama.cpp$ make clean
(llm) user@gpu:~/projects/llama/llama.cpp$ make LLAMA_CUBLAS=1
[  2%] Generating build details from Git
-- Found Git: /usr/bin/git (found version "2.25.1") 
[  2%] Built target BUILD_INFO
[  4%] Building C object CMakeFiles/ggml.dir/ggml.c.o
/home/user/projects/llama/llama.cpp/ggml.c: In function ‘ggml_init’:
/home/user/projects/llama/llama.cpp/ggml.c:4346:9: warning: implicit declaration of function ‘ggml_init_cublas’ [-Wimplicit-function-declaration]
 4346 |         ggml_init_cublas();
      |         ^~~~~~~~~~~~~~~~
/home/user/projects/llama/llama.cpp/ggml.c: In function ‘ggml_compute_forward’:
/home/user/projects/llama/llama.cpp/ggml.c:14576:21: warning: implicit declaration of function ‘ggml_cuda_compute_forward’; did you mean ‘ggml_compute_forward’? [-Wimplicit-function-declaration]
14576 |     bool skip_cpu = ggml_cuda_compute_forward(params, tensor);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                     ggml_compute_forward
/home/user/projects/llama/llama.cpp/ggml.c: In function ‘ggml_graph_plan’:
/home/user/projects/llama/llama.cpp/ggml.c:16175:25: warning: implicit declaration of function ‘ggml_cuda_can_mul_mat’; did you mean ‘ggml_can_mul_mat’? [-Wimplicit-function-declaration]
16175 |                     if (ggml_cuda_can_mul_mat(node->src[0], node->src[1], node)) {
      |                         ^~~~~~~~~~~~~~~~~~~~~
      |                         ggml_can_mul_mat
In file included from /home/user/projects/llama/llama.cpp/ggml.c:256:
At top level:
./frame/include//bli_type_defs.h:1354:18: warning: ‘bli_obj_init_subpart_from’ defined but not used [-Wunused-function]
./frame/include//bli_type_defs.h:1319:18: warning: ‘bli_obj_init_full_shallow_copy_of’ defined but not used [-Wunused-function]
[  6%] Building CUDA object CMakeFiles/ggml.dir/ggml-cuda.cu.o
[  8%] Building C object CMakeFiles/ggml.dir/k_quants.c.o
[  8%] Built target ggml
[ 10%] Linking CUDA static library libggml_static.a
[ 10%] Built target ggml_static
[ 12%] Building CXX object CMakeFiles/llama.dir/llama.cpp.o
[ 14%] Linking CXX static library libllama.a
[ 14%] Built target llama
[ 16%] Building CXX object tests/CMakeFiles/test-quantize-fns.dir/test-quantize-fns.cpp.o
[ 18%] Linking CXX executable ../bin/test-quantize-fns
[ 18%] Built target test-quantize-fns
[ 20%] Building CXX object tests/CMakeFiles/test-quantize-perf.dir/test-quantize-perf.cpp.o
[ 22%] Linking CXX executable ../bin/test-quantize-perf
[ 22%] Built target test-quantize-perf
[ 24%] Building CXX object tests/CMakeFiles/test-sampling.dir/test-sampling.cpp.o
[ 26%] Linking CXX executable ../bin/test-sampling
[ 26%] Built target test-sampling
[ 28%] Building CXX object tests/CMakeFiles/test-tokenizer-0.dir/test-tokenizer-0.cpp.o
/home/user/projects/llama/llama.cpp/tests/test-tokenizer-0.cpp:19:2: warning: extra ‘;’ [-Wpedantic]
   19 | };
      |  ^
[ 30%] Linking CXX executable ../bin/test-tokenizer-0
[ 30%] Built target test-tokenizer-0
[ 32%] Building C object tests/CMakeFiles/test-grad0.dir/test-grad0.c.o
[ 34%] Linking CXX executable ../bin/test-grad0
[ 34%] Built target test-grad0
[ 36%] Building CXX object examples/CMakeFiles/common.dir/common.cpp.o
[ 38%] Building CXX object examples/CMakeFiles/common.dir/grammar-parser.cpp.o
[ 38%] Built target common
[ 40%] Building CXX object examples/main/CMakeFiles/main.dir/main.cpp.o
[ 42%] Linking CXX executable ../../bin/main
[ 42%] Built target main
[ 44%] Building CXX object examples/quantize/CMakeFiles/quantize.dir/quantize.cpp.o
[ 46%] Linking CXX executable ../../bin/quantize
[ 46%] Built target quantize
[ 48%] Building CXX object examples/quantize-stats/CMakeFiles/quantize-stats.dir/quantize-stats.cpp.o
[ 51%] Linking CXX executable ../../bin/quantize-stats
[ 51%] Built target quantize-stats
[ 53%] Building CXX object examples/perplexity/CMakeFiles/perplexity.dir/perplexity.cpp.o
[ 55%] Linking CXX executable ../../bin/perplexity
[ 55%] Built target perplexity
[ 57%] Building CXX object examples/embedding/CMakeFiles/embedding.dir/embedding.cpp.o
[ 59%] Linking CXX executable ../../bin/embedding
[ 59%] Built target embedding
[ 61%] Building CXX object examples/save-load-state/CMakeFiles/save-load-state.dir/save-load-state.cpp.o
[ 63%] Linking CXX executable ../../bin/save-load-state
[ 63%] Built target save-load-state
[ 65%] Building CXX object examples/benchmark/CMakeFiles/benchmark.dir/benchmark-matmult.cpp.o
[ 67%] Linking CXX executable ../../bin/benchmark
[ 67%] Built target benchmark
[ 69%] Building CXX object examples/baby-llama/CMakeFiles/baby-llama.dir/baby-llama.cpp.o
/home/user/projects/llama/llama.cpp/examples/baby-llama/baby-llama.cpp: In function ‘int main(int, char**)’:
/home/user/projects/llama/llama.cpp/examples/baby-llama/baby-llama.cpp:1616:32: warning: variable ‘opt_params_adam’ set but not used [-Wunused-but-set-variable]
 1616 |         struct ggml_opt_params opt_params_adam = ggml_opt_default_params(GGML_OPT_ADAM);
      |                                ^~~~~~~~~~~~~~~
[ 71%] Linking CXX executable ../../bin/baby-llama
[ 71%] Built target baby-llama
[ 73%] Building CXX object examples/train-text-from-scratch/CMakeFiles/train-text-from-scratch.dir/train-text-from-scratch.cpp.o
[ 75%] Linking CXX executable ../../bin/train-text-from-scratch
[ 75%] Built target train-text-from-scratch
[ 77%] Building CXX object examples/simple/CMakeFiles/simple.dir/simple.cpp.o
[ 79%] Linking CXX executable ../../bin/simple
[ 79%] Built target simple
[ 81%] Building CXX object examples/embd-input/CMakeFiles/embdinput.dir/embd-input-lib.cpp.o
[ 83%] Linking CXX static library libembdinput.a
[ 83%] Built target embdinput
[ 85%] Building CXX object examples/embd-input/CMakeFiles/embd-input-test.dir/embd-input-test.cpp.o
[ 87%] Linking CXX executable ../../bin/embd-input-test
[ 87%] Built target embd-input-test
[ 89%] Building CXX object examples/server/CMakeFiles/server.dir/server.cpp.o
[ 91%] Linking CXX executable ../../bin/server
[ 91%] Built target server
[ 93%] Building CXX object pocs/vdot/CMakeFiles/vdot.dir/vdot.cpp.o
[ 95%] Linking CXX executable ../../bin/vdot
[ 95%] Built target vdot
[ 97%] Building CXX object pocs/vdot/CMakeFiles/q8dot.dir/q8dot.cpp.o
[100%] Linking CXX executable ../../bin/q8dot
[100%] Built target q8dot
(llm) user@gpu:~/projects/llama/llama.cpp$ ./main -m ./models/llama-2-13b-chat/ggml-model-q4_0.bin  -n 256 --repeat_penalty 1.0 --color --interactive --color --n-gpu-layers 32
**warning: not compiled with GPU offload support, --n-gpu-layers option will be ignored
warning: see main README.md for information on enabling GPU BLAS support**
main: build = 899 (41c6741)
main: seed  = 1690325064
llama.cpp: loading model from ./models/llama-2-13b-chat/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_head_kv  = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.11 MB
llama_model_load_internal: mem required  = 7390.01 MB (+  400.00 MB per state)
llama_new_context_with_model: kv self size  =  400.00 MB

system_info: n_threads = 3 / 6 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
main: interactive mode on.
sampling: repeat_last_n = 64, repeat_penalty = 1.000000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 256, n_keep = 0


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 2019 Kia Sorento SX Limited AWD Review: The SX Limited trim adds many premium features to the Sorento, including a 3.3-liter V-6 engine making 290 horsepower, a panoramic sunroof, heated and cooled front seats, a heated steering wheel, and a 8-inch touchscreen infotainment system with navigation and a 10-speaker Infinity sound system. The SX Limited also receives unique exterior styling, including a more aggressive front bumper and side skirts, as well as LED headlights and taillights.



2019 Kia Sorento SX Limited AWD














The 2019 Kia Sorento SX Limited AWD is a midsize crossover SUV that offers a compelling blend of features, performance, and value. With a starting price of just over $45,000, the Sorento SX Limited AWD delivers a lot of content for the money, including a powerful V-6 engine,

llama_print_timings:        load time =   756.11 ms
llama_print_timings:      sample time =    10.22 ms /   256 runs   (    0.04 ms per token, 25051.37 tokens per second)
llama_print_timings: prompt eval time =   853.05 ms /     2 tokens (  426.53 ms per token,     2.34 tokens per second)
llama_print_timings:        eval time = 114322.56 ms /   256 runs   (  446.57 ms per token,     2.24 tokens per second)
llama_print_timings:       total time = 1067202.34 ms
```

Hardware Requirements
NVIDIA V100 16GB
112GB RAM
6 CORE

**Comment by nero-dv** [comment]
Have you installed the Nvidia CUDA 11.7 Toolkit?

https://developer.nvidia.com/cuda-11-7-0-download-archive

**Comment by gabrielcustodio** [comment]
> Have you installed the Nvidia CUDA 11.7 Toolkit?
> 
> https://developer.nvidia.com/cuda-11-7-0-download-archive

I have installed Nvidia Cuda 12.2 Toolkit, its a problem?

**Comment by nero-dv** [comment]
On second thought, the version may not matter. Can you try building with cmake and see if the build can find cuBLAS?

**Comment by nero-dv** [comment]
sudo apt install cmake clang nvidia-cuda-toolkit -y
sudo reboot
cd into the root llama.cpp directory
rm -rf build; mkdir build; cd build
cmake .. -DLLAMA_CUBLAS=ON


This is on WSL, but it should be the same on non-wsl systems.

`louis@StarCactus:/mnt/f/llama/hf/llama.cpp/build$ cmake .. -DLLAMA_CUBLAS=ON
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found CUDAToolkit: /usr/include (found version "11.5.119")
-- cuBLAS found
-- The CUDA compiler identification is NVIDIA 11.5.119
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Using CUDA architectures: 52;61
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/f/llama/hf/llama.cpp/build`

**Comment by gabrielcustodio** [comment]
> cmake .. -DLLAMA_CUBLAS=ON

`(llm) user@gpu:~/projects/llama/llama.cpp/build$ cmake .. -DLLAMA_CUBLAS=ON
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- BLAS found, Libraries: /usr/local/lib/libblis.so
-- BLAS found, Includes: /usr/local/include/blis
-- Found CUDAToolkit: /usr/local/cuda-12.2/include  
-- cuBLAS found
-- The CUDA compiler identification is NVIDIA 12.2.91
-- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Using CUDA architectures: 52;61
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done
CMake Error at CMakeLists.txt:518 (add_library):
  Target "llama" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:518 (add_library):
  Target "llama" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-tokenizer-0" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:13 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-tokenizer-0" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:13 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-quantize-perf" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:11 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-quantize-perf" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:11 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-sampling" links to target "CUDA::cublasLt" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:12 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-sampling" links to target "CUDA::cublasLt" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:12 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-grad0" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:14 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-grad0" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:14 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-quantize-fns" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:10 (llama_add_test)


CMake Error at tests/CMakeLists.txt:3 (add_executable):
  Target "test-quantize-fns" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  tests/CMakeLists.txt:10 (llama_add_test)


CMake Error at examples/main/CMakeLists.txt:2 (add_executable):
  Target "main" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/main/CMakeLists.txt:2 (add_executable):
  Target "main" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/quantize/CMakeLists.txt:2 (add_executable):
  Target "quantize" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/quantize/CMakeLists.txt:2 (add_executable):
  Target "quantize" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/quantize-stats/CMakeLists.txt:2 (add_executable):
  Target "quantize-stats" links to target "CUDA::cublasLt" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/quantize-stats/CMakeLists.txt:2 (add_executable):
  Target "quantize-stats" links to target "CUDA::cublasLt" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/perplexity/CMakeLists.txt:2 (add_executable):
  Target "perplexity" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/perplexity/CMakeLists.txt:2 (add_executable):
  Target "perplexity" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/embedding/CMakeLists.txt:2 (add_executable):
  Target "embedding" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/embedding/CMakeLists.txt:2 (add_executable):
  Target "embedding" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/save-load-state/CMakeLists.txt:2 (add_executable):
  Target "save-load-state" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/save-load-state/CMakeLists.txt:2 (add_executable):
  Target "save-load-state" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/benchmark/CMakeLists.txt:2 (add_executable):
  Target "benchmark" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/benchmark/CMakeLists.txt:2 (add_executable):
  Target "benchmark" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/baby-llama/CMakeLists.txt:2 (add_executable):
  Target "baby-llama" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/baby-llama/CMakeLists.txt:2 (add_executable):
  Target "baby-llama" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/train-text-from-scratch/CMakeLists.txt:2 (add_executable):
  Target "train-text-from-scratch" links to target "CUDA::cublasLt" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at examples/train-text-from-scratch/CMakeLists.txt:2 (add_executable):
  Target "train-text-from-scratch" links to target "CUDA::cublasLt" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at examples/simple/CMakeLists.txt:2 (add_executable):
  Target "simple" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/simple/CMakeLists.txt:2 (add_executable):
  Target "simple" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/embd-input/CMakeLists.txt:11 (add_executable):
  Target "embd-input-test" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/embd-input/CMakeLists.txt:11 (add_executable):
  Target "embd-input-test" links to target "CUDA::cublasLt" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/embd-input/CMakeLists.txt:2 (add_library):
  Target "embdinput" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/embd-input/CMakeLists.txt:2 (add_library):
  Target "embdinput" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/server/CMakeLists.txt:4 (add_executable):
  Target "server" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/server/CMakeLists.txt:4 (add_executable):
  Target "server" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at pocs/vdot/CMakeLists.txt:7 (add_executable):
  Target "q8dot" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at pocs/vdot/CMakeLists.txt:7 (add_executable):
  Target "q8dot" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at pocs/vdot/CMakeLists.txt:2 (add_executable):
  Target "vdot" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at pocs/vdot/CMakeLists.txt:2 (add_executable):
  Target "vdot" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:496 (add_library):
  Target "ggml" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/CMakeLists.txt:13 (add_library):
  Target "common" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at examples/CMakeLists.txt:13 (add_library):
  Target "common" links to target "CUDA::cublasLt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by gabrielcustodio** [comment]
```
(llm) user@gpu:~/projects/llama/llama.cpp/build$ pip install cmake
Requirement already satisfied: cmake in /home/user/miniconda3/envs/llm/lib/python3.10/site-packages (3.17.0)
(llm) user@gpu:~/projects/llama/llama.cpp/build$ pip install^C
(llm) user@gpu:~/projects/llama/llama.cpp/build$ conda install cmake
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/azureuser/miniconda3/envs/llm

  added / updated specs:
    - cmake


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cmake-3.26.4               |       h96355d8_0        16.7 MB
    expat-2.4.9                |       h6a678d5_0         156 KB
    libuv-1.44.2               |       h5eee18b_0         864 KB
    rhash-1.4.3                |       hdbd6064_0         220 KB
    ------------------------------------------------------------
                                           Total:        17.9 MB

The following NEW packages will be INSTALLED:

  c-ares             pkgs/main/linux-64::c-ares-1.19.0-h5eee18b_0 
  cmake              pkgs/main/linux-64::cmake-3.26.4-h96355d8_0 
  expat              pkgs/main/linux-64::expat-2.4.9-h6a678d5_0 
  krb5               pkgs/main/linux-64::krb5-1.20.1-h143b758_1 
  libcurl            pkgs/main/linux-64::libcurl-8.1.1-h251f7ec_1 
  libedit            pkgs/main/linux-64::libedit-3.1.20221030-h5eee18b_0 
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1 
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.52.0-h2d74bed_1 
  libssh2            pkgs/main/linux-64::libssh2-1.10.0-hdbd6064_2 
  libuv              pkgs/main/linux-64::libuv-1.44.2-h5eee18b_0 
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.4-h6a678d5_0 
  rhash              pkgs/main/linux-64::rhash-1.4.3-hdbd6064_0 
  zstd               pkgs/main/linux-64::zstd-1.5.5-hc292b87_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                                                                           
Preparing transaction: done                                                                                                                                                                
Verifying transaction: done                                                                                                                                                                
Executing transaction: done                                                                                                                                                                
(llm) azureuser@AlanGPU:~/projects/misterturing/llama.cpp/build$ cmake .. -DLLAMA_CUBLAS=ON
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BLAS found, Libraries: /usr/local/lib/libblis.so
-- BLAS found, Includes: /usr/local/include/blis
-- Found CUDAToolkit: /usr/local/cuda-12.2/include (found version "12.2.91") 
-- cuBLAS found
-- The CUDA compiler identification is NVIDIA 12.2.91
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Using CUDA architectures: 52;61
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done (3.5s)
-- Generating done (0.1s)
-- Build files have been written to: /home/user/projects/llama/llama.cpp
```

I change the version cmake and its pass now

**Comment by gabrielcustodio** [comment]
But I got this
```
 (llm) user@gpu:~/projects/llama/llama.cpp/build$ cmake --build . --config Release
Error: could not load cache
```

**Comment by staviq** [comment]
I'd check if you have "pkg-config", run pkg-config --help and it will tell you the flag to list all the libraries it sees, and check if you have Nvidia cuda thing on that list
