### ISSUE TITLE
13b model issue tensor 'tok_embeddings.weight' has wrong size in model file

### ISSUE THREAD

**Issue by Tarang** [ggerganov/llama.cpp#24]
I try the following with the latest master (6b2cb6302ffaf8264e33af1dc52e3ea54003e690)

```
python convert-pth-to-ggml.py models/13B/ 1
./quantize ./models/13B/ggml-model-f16.bin   ./models/13B/ggml-model-q4_0.bin 2
./quantize ./models/13B/ggml-model-f16.bin.1 ./models/13B/ggml-model-q4_0.bin.1 2
```

```
ls models/13B/
checklist.chk         consolidated.00.pth   consolidated.01.pth   ggml-model-f16.bin    ggml-model-f16.bin.1  ggml-model-q4_0.bin   ggml-model-q4_0.bin.1 params.json
```

```
./main -m ./models/13B/ggml-model-q4_0.bin -t 8 -n 128
main: seed = 1678568386
llama_model_load: loading model from './models/13B/ggml-model-q4_0.bin' - please wait ...
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: ggml ctx size = 8559.49 MB
llama_model_load: memory_size =   800.00 MB, n_mem = 20480
llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
main: failed to load model from './models/13B/ggml-model-q4_0.bin'
llama_model_load: ⏎                                                                                                                                                                                       
```

What would  tensor 'tok_embeddings.weight' has wrong size in model file mean?

**Comment by djkz** [comment]
It means you are running it on the old version. recompile your main and quantize and re-quantize the weights, it should work after.

**Comment by Tarang** [comment]
That was it!

**Comment by maria-mh07** [comment]
Hi! I'm trying to use the Alpaca 13B model obtained by torrent from https://github.com/cocktailpeanut/dalai/issues/97
I'm in Windows and I have a file ggml-alpaca-14b-q4.bin

`bin\Release\main.exe -m models\Alpaca\13B\ggml-alpaca-13b-q4.bin --color -f prompts\alpaca.txt -ins`

`
main: seed = 1679987958
llama_model_load: loading model from 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin' - please wait ...
llama_model_load: n_vocab = 32000 
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: ggml ctx size = 8159.49 MB
llama_model_load: mem required  = 10207.49 MB (+ 1608.00 MB per state)
llama_model_load: loading model part 1/2 from 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin'
llama_model_load: llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
llama_init_from_file: failed to load model
main: error: failed to load model 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin'

`
So I follow the steps of https://github.com/ggerganov/llama.cpp/issues/361

`python convert.py models/Alpaca/13B models/LLaMA/tokenizer.model`

I rename the generated file ggml-alpaca-13b-q4.bin.tmp to ggml-alpaca-13b-q4.bin

`bin\Release\main.exe -m models\Alpaca\13B\ggml-alpaca-13b-q4.bin --color -f prompts\alpaca.txt -ins`

`
main: seed = 1679990927
llama_model_load: loading model from 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin' - please wait ...
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: ggml ctx size = 8159.49 MB
llama_model_load: mem required  = 10207.49 MB (+ 1608.00 MB per state)
llama_model_load: loading model part 1/2 from 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin'
llama_model_load: llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
llama_init_from_file: failed to load model
main: error: failed to load model 'models\Alpaca\13B\ggml-alpaca-13b-q4.bin'

`

How can I solve that? This worked for model alpaca 7B

**Comment by Komal-99** [comment]
Hi, 
I am not able to Quantize my model after running convert.py from Llama.cpp the mode has been converted into gguf type but while running. '
./quantize C:\PrivateGPT\privategpt\privateGPT-main\llama.cpp-master\models\ggml-model-f16.gguf C:\PrivateGPT\privategpt\privateGPT-main\llama.cpp-master\models\ggml-model-q4_0.gguf q4_0

Error Occured :- ./quantize is not a cmdlet or script function.
 Also @Tarang  Can you please tell how you are able to create .bin file convert.py is creating .gguf file by default.
