### ISSUE TITLE
Server chat is not scrolling

### ISSUE THREAD

**Issue by staviq** [ggerganov/llama.cpp#2409]
I don't know if that's a firefox issue, or simply nobody noticed that so far, but the chat element has a js code to autoscroll but it's not working because it scrolls the wrong element.

Here is a quick fix, in the index.html, in the body of `useEffect`:

Old code:
```
if (container.current && container.current.scrollHeight <= container.current.scrollTop + container.current.offsetHeight + 300) {
          container.current.scrollTo(0, container.current.scrollHeight)
}
```

Working code:
```
if (container.current.parentElement && container.current.parentElement.scrollHeight <= container.current.parentElement.scrollTop + container.current.parentElement.offsetHeight + 300) {
          container.current.parentElement.scrollTo(0, container.current.parentElement.scrollHeight)
}
```

**Comment by JackJollimore** [comment]
Hi, I experience the same with Firefox. 

It appears there's [fix](https://github.com/ggerganov/llama.cpp/pull/2425#issuecomment-1654144127). Something along the lines of..
```
var parent = container.current.parentElement; 
if (parent && parent.scrollHeight <= parent.scrollTop + parent.offsetHeight + 300) {
parent.scrollTo(0, parent.scrollHeight);
}
```
