### ISSUE TITLE
Prompt structure after the --in-prefix-bos commit

### ISSUE THREAD

**Issue by JackJollimore** [ggerganov/llama.cpp#2417]
Hello, I'm adhereing to [llama.cpp/example/main/README.txt](https://github.com/ggerganov/llama.cpp/tree/b5472ea0ada081a6e1c06998ebbc9a24aa2cd4a4/examples/main#in-prefix) 

Here's main: `./main -m ~/wizardlm-7b-v1.0-uncensored.ggmlv3.q4_0.bin -i -r "User:" --in-prefix " " --in-suffix "Assistant:" -f ~/storage/shared/PT/Wiz.txt`

Working as expected [Grammar commit](https://github.com/ggerganov/llama.cpp/commit/84e09a7d8bc4ab6d658b5cd81295ac0add60be78) :
```
Assistant: Hi! Is there anything that you would like to discuss? User: Hi, what's the best movie?
Assistant: That is a subjective question as people have different opinions on what makes a good movie. However, some popular movies that have been widely appreciated include "The Shawshank Redemption," "The Godfather," and "Forrest Gump."
User: 
```

Note at the end of the Assistants message: llama.cpp inserts, `User:(space)`, compared with --in-prefix-bos commit:
```
Assistant: Hi! Is there anything that you would like to discuss? User: Hi, what's the best movie?
Assistant: There are many great movies out there, but it really depends on your personal preferences and interests. Some of my favorite movies include The Shawshank Redemption, Forrest Gump, Titanic, The Godfather, and The Matrix. Is there anything specific you're looking for in a movie?
 
```
llama.cpp negates, `"User:"`, and _only_ puts a space, breaking the structure of conversation.

The directions in llama.cpp/example/main/README.txt do not work as expected since the [ --in-prefix-bos commit.
](https://github.com/ggerganov/llama.cpp/commit/0c06204fb39aa5560e883e0ae74be9518c57d88e) 

Thank you.

**Comment by JackJollimore** [comment]
[Same issue](https://github.com/ggerganov/llama.cpp/pull/2304#issuecomment-1653860890)

**Comment by jxy** [comment]
Previously, the first reverse prompt (if existed) is always inserted. Now if the model generate EOS, the reverse prompt is not inserted. To get the same behavior, please use
```
./main -m "$MODEL" -i --in-prefix "User: " --in-suffix "Assistant:" ...
```
instead.

**Comment by JackJollimore** [comment]
Thank you for your response! I tested last night, and it appears to be _mostly_ working.

I'll test more today and possibly close on this later.

**Comment by jxy** [comment]
`-r` still works, if the model generates the reverse prompt, the code will stop the generation at that reverse prompt. It's just that the code no longer inserts the first reverse prompt if the mode generates EOS.

**Comment by JackJollimore** [comment]
> It's just that the code no longer inserts the first reverse prompt if the mode generates EOS.

Sure, I appreciate the explaination. If I understand correctly then ,`-r`, is obselete.

I don't know how to dicern whether or not a model generates an EOS - most model cards don't contain that information, so I'd rather not guess and use an obselete parameter.

**Comment by jxy** [comment]
`-r` is not obsolete.

It does exactly what it advertises to do, stopping generation when the code sees the string, which can be anything. If you work with models that do not generate EOS as needed (such as all the base models), you would need the reverse prompt.

Of course the `--grammar` can work like `-r`, but `--grammar` also does a lot more, while `-r` is simple and effective.

**Comment by jxy** [comment]
Please read Nous Hermes model card https://huggingface.co/NousResearch/Nous-Hermes-Llama2-13b

It's an instruction model, not a chat model.

After reading over the model card, you'll find a link to github that gives you example prompt. To strictly follow prompt structure, you unfortunately need to be able to read the Python code and reconstruct its prompt, https://github.com/teknium1/alpaca-roleplay-discordbot/blob/3595c171c2bab18feaa834518c1af990b978c49b/roleplay-bot.py#L116-L177

**Comment by JackJollimore** [comment]
> Please read Nous Hermes model card https://huggingface.co/NousResearch/Nous-Hermes-Llama2-13b
> 
That's not the model, but I checked out the model card and it shows a Prompt Template section. 


> To strictly follow prompt structure, you unfortunately need to be able to read the Python code and reconstruct its prompt

There was no need reconstruct a Prompt Template previously, and now decyphering Python is required? 

So @TheBloke's nous-hermes-llama-2-7b [Prompt Template](https://huggingface.co/TheBloke/Nous-Hermes-Llama-2-7B-GGML) is incorrect?

**Comment by TheBloke** [comment]
Actually mine might be incorrect in that I don't have a newline after instruction and they do. I'll fix that.

Whatever is in the original model card will be correct, which is at the bottom of my readme. I'll update my PT section later this evening

**Comment by JackJollimore** [comment]
> Actually mine might be incorrect in that I don't have a newline after instruction and they do. I'll fix that.

@TheBloke Thanks for clarifying. I tried with an updated PT and it works.

@jxy I'll double check PT's going forward and close on this issue. Thank you.

It's notable that the, `--in-prefix` `--in-suffix`, examples from  [llama.cpp/example/main/README.txt](https://github.com/ggerganov/llama.cpp/tree/b5472ea0ada081a6e1c06998ebbc9a24aa2cd4a4/examples/main#in-prefix) are confusing.

**Comment by JackJollimore** [comment]
Related: https://github.com/ggerganov/llama.cpp/discussions/2578
