### ISSUE TITLE
Build fail in mac A2 with "LLAMA_METAL=1 make"

### ISSUE THREAD

**Issue by ilisin** [ggerganov/llama.cpp#2430]
build with
> 

output error with

```
I llama.cpp build info:
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -pthread -DGGML_USE_K_QUANTS -DGGML_USE_ACCELERATE -DGGML_USE_METAL -DGGML_METAL_NDEBUG
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS -DGGML_USE_METAL
I LDFLAGS:   -framework Accelerate -framework Foundation -framework Metal -framework MetalKit -framework MetalPerformanceShaders
I CC:       Apple clang version 14.0.3 (clang-1403.0.22.14.1)
I CXX:      Apple clang version 14.0.3 (clang-1403.0.22.14.1)

: command not foundsh: line 2:
: command not foundsh: line 5:
scripts/build-info.sh: line 24: syntax error: unexpected end of file
make: *** [build-info.h] Error 2
```
Am I missing any software tools?

**Comment by appleguy** [comment]
@ilisin at the time of reading this comment, the "build with" line seems blank - what is your build invocation, and git commit hash of the code? macOS version and Xcode version?

**Comment by ilisin** [comment]
after i edit scripts/build-info.sh, add a line text and save if, after to remove the line and save it. 
than to build again, It worked this time
maybe because of file line breaks code

**Comment by hieunc229** [comment]
I had the same issue and figured out how to solve it by make end of lines sequence with LF ([instead of CRLF](https://stackoverflow.com/questions/48692741/how-can-i-make-all-line-endings-eols-in-all-files-in-visual-studio-code-unix))

I guess because I was using WSL, which messed up when downloading the repo in Windows, but run on Ubuntu

**Comment by dusty81** [comment]
A +1 for me, I opened the build-info.sh in VI and replaced all the line endings and off to the races!  Successful compile.

**Comment by BurkovBA** [comment]
Effing carriage returns.

How is a build system that breaks because of return characters and tabs even considered viable in 2023?
