### ISSUE TITLE
Default CUDA setting and CUDA 12.2

### ISSUE THREAD

**Issue by stevegrubb** [ggerganov/llama.cpp#2437]
When using the default CUDA architecture from CmakeLists.txt, we get the following

-- The CUDA compiler identification is NVIDIA 12.2.91
-- Using CUDA architectures: 52;61

But when compiling, it ends like this:
[  6%] Building CUDA object CMakeFiles/ggml.dir/ggml-cuda.cu.o
In file included from /usr/include/cuda/std/detail/libcxx/include/atomic:727,
                 from /usr/include/cuda/std/atomic:18,
                 from /usr/include/cuda/atomic:14,
                 from /home/llm/llama.cpp/ggml-cuda.cu:6:
/usr/include/cuda/std/detail/libcxx/include/support/atomic/atomic_cuda.h:16:4: error: #error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."
   16 | #  error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."

The README.md page does not talk about setting the CUDA architecture and might benefit from adding that. But if I use this to generate the build scripts:

CUDAARCHS=61 cmake .. -DLLAMA_CUBLAS=ON

We get "-- Using CUDA architectures: 61" and the subsequent build no longer stops at the preprocessor error. So, I'd say that sm_52 is unsupported on CUDA 12.

**Comment by slaren** [comment]
CUDA atomics aren't used at all, the standard C++ header `<atomic>` is included for CPU only use. Are you on windows? I don't get that error with CUDA 12.2 under linux (wsl).

**Comment by stevegrubb** [comment]
No, this is on Fedora 38.

**Comment by slaren** [comment]
I think there is something wrong with your system configuration. Including `<atomic>` should include the host C++ standard library, but in your case it seems to be including `libcu++`. This shouldn't happen automatically, the `libcu++` version should require explicitly including `<cuda/std/atomic>` instead.

**Comment by stevegrubb** [comment]
I'll re-install my whole cuda setup from nvidia sources instead of a 3rd party repo. I'll update this issue later.

**Comment by stevegrubb** [comment]
Yes, this was something wrong in the fedora-multimedia repo. Using nvidia provided packages fixes this. Sorry for the noise.
