### ISSUE TITLE
Commit "CUDA: Quantized matrix matrix multiplication" causes assert "ggml-cuda.cu:4749: i01_high == rows_per_iter || g_device_count > 1" on Windows when vocab_size != 32000

### ISSUE THREAD

**Issue by dranger003** [ggerganov/llama.cpp#2484]
Using CUDA on Windows when model `vocab_size != 32000`, inference crashes immediately with:

`ggml-cuda.cu:4749: i01_high == rows_per_iter || g_device_count > 1`

See https://github.com/ggerganov/llama.cpp/pull/2160#issuecomment-1660093406 for more details.  
Reverting to commit before 11f3ca06b8c66b0427aab0a472479da22553b472 resolves the issue.  
Also, the workaround proposed in https://github.com/ggerganov/llama.cpp/pull/2160#issuecomment-1657203763 appears to work (at least for me).

**Comment by mirek190** [comment]
The same problem 

My arguments - model is llama2 variant 13B

main --model models\new2\newhope.ggmlv3.q4_K_M.bin --mlock --color --threads 30 --keep -1 --batch_size 512 --n_predict -1 --top_k 10000 --top_p 0.9 --temp 0.96 --repeat_penalty 1.1 --ctx_size 4096 --interactive --instruct --reverse-prompt "### Human:" --reverse-prompt "### User:" --reverse-prompt "### Assistant:" -ngl 43 


ggml-cuda.cu:4749: i01_high == rows_per_iter || g_device_count > 1
PS E:\LLAMA\llama.cpp>



without -ngl parameter is working.

**Comment by dranger003** [comment]
It appears PR https://github.com/ggerganov/llama.cpp/pull/2480 solves this issue.

**Comment by mirek190** [comment]
Still not merged ....

**Comment by dranger003** [comment]
Confirmed latest commit 4f6b60c77652cdfc9d5545fe247ae5d764815598 resolves the issue on my end.
