### ISSUE TITLE
MPI Job Always Selects Mac Studio for Computation

### ISSUE THREAD

**Issue by AlphaSue** [ggerganov/llama.cpp#2492]
I have been trying to use MPI to distribute computation over a cluster of machines for LLM prediction. I have two machines: a Mac Studio and another Mac, both of which are properly set up for MPI. Password-less SSH access is enabled between the two machines, and the hostfile is configured correctly with the hostnames and their relative "weights" (slots). However, regardless of how I adjust the slots, the computation is always distributed to the Mac Studio.

Mac Studio: Running macOS 14.0 Beta (23A5301h), 32 GB RAM, M2 max chip.
Another Mac: Running macOS 14.0 Beta (23A5301h), 16 GB RAM, M1

This is my hostfile:
192.168.31.44 slots=2
192.168.31.141 slots=1

When I run the MPI job using the following command:
mpirun -hostfile hostfile -n 3 ./main -m ./models/7B/ggml-model-q4_0.bin -n 128

Only the Mac Studio (192.168.31.44) is selected for computation, despite the fact that the other Mac (192.168.31.141) is specified in the hostfile and has been allocated slots. The SSH connection between the two machines is functioning correctly, as I can run a simple MPI "Hello, World!" program without any problems.

Could anyone please help me understand why the computation is not being distributed across both machines as expected? Is there any additional configuration I need to set up to ensure the computation is distributed according to the slots specified in the hostfile? Any guidance would be greatly appreciated.

**Comment by ggerganov** [comment]
Try to use `-np 4` instead of `-n 3`

**Comment by AlphaSue** [comment]
Unfortunately it don't work.
here is the hostfile:
192.168.31.224 slots=2
192.168.31.141 slots=2

Here is the command:
mpirun -hostfile hostfile -np 4 ./build-metal-mpi/bin/main -m ./models/llama-2-7b-chat.ggmlv3.q4_0.bin --prompt "Once upon a time" -n 128

In the activity monitor, I can only see two process on mac studio, there is still no process on my mac mini. That's so weird. Also, I get duplicate input prompt in my terminal:
"Once upon a time Once upon a time,,"

**Comment by AlphaSue** [comment]
> Try to use `-np 4` instead of `-n 3`

Sorry, just realize the origin question used wrong slots number. I'm pretty sure two slots sum is equal to the command np number.

**Comment by knoel99** [comment]
In the end, did you manage to perform inference using MPI on your 2 Macs?

**Comment by AlphaSue** [comment]
> In the end, did you manage to perform inference using MPI on your 2 Macs?

Can't remember the detail, after updating latest version at that time, it worked and I can see 2 macs with cpu and memory running. However, it seems each mac have to load whole memory, the split part didn't work well. You can test the latest version.
