### ISSUE TITLE
3090 with CUDA (24GB GRAM): Best command line for more fast execution a 3090 with CUDA

### ISSUE THREAD

**Issue by SilvaRaulEnriqueCJM** [ggerganov/llama.cpp#2496]
With the actual (2/8/23) basic parameters specified in README.txt for construct and execute example:
make LLAMA_CUBLAS=1
./main -m ./models/7B/ggml-model-q4_0.bin -n 128

the velocity of the generation time is more slow that one with pytorch llama2:
https://github.com/facebookresearch/llama

The problem is that not charge o process all in GRAM memory?

What is the best line command to construct and execute in a CUDA 3090 with 24GB GRAM in the more fast posibility for each model?

**Comment by mirek190** [comment]
I'm using q4k_m models ( which are much better than q4 ancient models with high perplexity ) . 
q4k_m models are very close to q5_1 perplexity and have speed q4. 

For RTX 3090 and q4k_m models I am using -ngl and default -n 

7B - 33 all layers
13B - 43 all layers
33B - 63  all layers 
65B - 45 of 83 layers
70B - 40 and of 83 layers

**Comment by SilvaRaulEnriqueCJM** [comment]
thank you
Please, explicity write line orders for construct, train, or execute, with chat models, and url to download.

**Comment by SlyEcho** [comment]
As you managed to already compile and run, you just need to add a command line argument:

```sh
./main -m ./models/7B/ggml-model-q4_0.bin -n 128 -ngl 99
```

99 to always offload all layers which you should be able to do with 24GB.
