### ISSUE TITLE
convert.py can not identify type of pytorch BF16 tensors

### ISSUE THREAD

**Issue by klosax** [ggerganov/llama.cpp#2504]
The original model files have tensors stored in BF16 which have a wider numeric range than F16. The quality will suffer too much if the norm tensors are converted to lower precision, I believe this is the reason why they are always stored in F32 since there is no support for BF16 in ggml.

When I tried to list the tensor types in convert.py for experimentation purposes, I discovered that all BF16 tensors in pytorch and safetensors models are identified as F16, but are for some unknown reason correctly converted to F32. BF16 tensors in .pth model files are correctly identified.

Directly following this line:
https://github.com/ggerganov/llama.cpp/blob/8183159cf3def112f6d1fe94815fce70e1bffa12/convert.py#L88

Insert this:
```
        if tensor.data_type == DT_F16:  print(name + " DT_F16")
        if tensor.data_type == DT_F32:  print(name + " DT_F32")
        if tensor.data_type == DT_BF16: print(name + " DT_BF16")

        if tensor.data_type == DT_F16:
            return DT_F16
        else:
            return DT_F32

```
This will keep any tensors identified as F16 and convert all else to F32. There should be no reason to store F16 tensors as F32 since F16 is supported by ggml. Now perplexity will shoot up compared to storing all tensors as F32.

[openllama-3b-v2](https://huggingface.co/openlm-research/open_llama_3b_v2)

Perplexity all F32: [1] 4.7087, [2] 6.3550, [3] 6.4358  ...
Perplexity keep F16: [1] 28972.1316, [2] 29087.7513, [3] 30817.8770 ...

[llama2-13b-hf](https://huggingface.co/TheBloke/Llama-2-13B-fp16)

Perplexity all F32: [1] 3.9331027798115668
Perplexity keep F16: [1] 33766.1105509410190280

[llama2-13b-pth](https://huggingface.co/anonymous4chan/llama-2-13b-original)

Perplexity all F32: [1] 3.9331135303250822
Perplexity all F16: [1] 33766.1105509410190280

**Comment by SlyEcho** [comment]
Which models are affected by this and in what format?

**Comment by klosax** [comment]
> Which models are affected by this and in what format?

You could replicate with
https://huggingface.co/openlm-research/open_llama_3b_v2

**Comment by klosax** [comment]
https://huggingface.co/TheBloke/Llama-2-13B-fp16

**Comment by klosax** [comment]
Testing listing llama2-13b-hf tensor types by using torch.load():
```
model = torch.load("pytorch_model-00001-of-00003.bin", map_location = 'cpu')
for name in model.keys():
    data = model[name]
    print( name + " type " + str(data.type())+ " dtype " + str(data.dtype) )
```
do not list the tensors as BF16 either

```
model.layers.0.mlp.up_proj.weight type torch.HalfTensor dtype torch.float16
model.layers.0.input_layernorm.weight type torch.HalfTensor dtype torch.float16
model.layers.0.post_attention_layernorm.weight type torch.HalfTensor dtype torch.float16
```
But the LazyTensor loader in convert.py can convert them to F32 as i they are BF16.

This is weird, if the tensors are stored as BF16 but the type is reported as F16 then this would be a bug in pytorch and not in convert.py.

**Comment by klosax** [comment]
Maybe I got it all wrong.. Does the evaluation code stop working if the norm tensors are anything else than float32?

**Comment by klosax** [comment]
Answered by https://github.com/ggerganov/llama.cpp/pull/2398#issuecomment-1677029940
