### ISSUE TITLE
bad display of answer in server chat client

### ISSUE THREAD

**Issue by ml13390** [ggerganov/llama.cpp#2513]
I'm working on an implementation of llama.cpp on a remote server. Everything works perfectly on my local setup, but when I execute llama.cpp server on the remote machine, the response seems truncated and makes no sense.
I can't figure out why, but it seems that some parts of the message generated in response are lost...
Here's an example with "./server -t 12 -ngl 500 -c 2048 --host 0.0.0.0 --port 8080 -m ~/models/13B/llama-2-13b-chat.ggmlv3.q8_0.bin" :

User: can you give me a long description of the eiffel tower.

llama: ohisk thee what choicet deepll, even 😅iff, heart, is the land world was 8s to the0versary f designed brilliantaveiff this structure impress2 (0)igh70 🤯thee made ,0ought pieceed like puzz lattice not the look provides strength strong earth. you e s up8 ()s 🌬 it secure its and 🔨as, the thee breaking clear you up4eters5) direction inunningamais siagneying dinnermit the the 🥂👫 wait' thel tower has

Hereunder is the answer I get from the shell with "./main -t 12 -ngl 500 --color -i -ins -c 2048 -m ~/models/13B/llama-2
-13b-chat.ggmlv3.q8_0.bin" : 
> can you give me a long description of the eiffel tower.
The Eiffel Tower, located in the heart of Paris, France, is an iconic symbol of engineering and architectural innovation. Standing at an impressive height of 324 meters (1,063 feet), it was the tallest man-made structure in the world when it was first built for the 1889 World's Fair, held to celebrate the 100th anniversary of the French Revolution. The tower was designed by Gustave Eiffel, a French engineer and architect, and his company Eiffel et Cie.[...etc]

**Comment by aiaicode** [comment]
Are you providing the context and prompt which says "You are an assistant and respond with precision" with some examples? Parsing it well?

**Comment by ml13390** [comment]
Sure, my test is done with the same context and prompt locally and in remote. 
I tried again today to reproduce the issue from my local environment that runs on WSL/Ubuntu with the client launched from a chrome browser/Windows11 on the same PC.
There, all works perfectly... 
The configuration of Ubuntu on WSL is quite the same than the one on the remote server.
What should I check on my remote server ? I have no idea what's causing the problem.

**Comment by ml13390** [comment]
Thanks to snichols for the fix #2391.
I’ve just seen it but it seems to completely solve my issue.

https://github.com/ggerganov/llama.cpp/pull/2391
