### ISSUE TITLE
QuiP - 2 bit Quantization

### ISSUE THREAD

**Issue by Jipok** [ggerganov/llama.cpp#2518]
https://arxiv.org/abs/2307.13304
https://github.com/jerry-chee/quip

Is it possible to add this method?

**Comment by Azeirah** [comment]
Viable 2 bit quantization would be crazy

**Comment by Dampfinchen** [comment]
Someone is already working porting it to Llama: https://github.com/AlpinDale/QuIP-for-Llama

**Comment by SlyEcho** [comment]
How long before 1-bit? 🤣

**Comment by paryska99** [comment]
Any news on this front?

**Comment by shermansiu** [comment]
Now that NeurIPS is around the corner, news about QuIP# is popping up again (QuIP# has been accepted as a Spotlight Poster there). Getting this accepted into Llama.cpp would be awesome!

**Comment by PoignardAzur** [comment]
This issue and #4386 are duplicates.
