### ISSUE TITLE
Enhancement for java bindings.

### ISSUE THREAD

**Issue by codeastra2** [ggerganov/llama.cpp#2526]
In the readme the currently supported  list of bindings does not contain java, I would like to implement these bindings for usage from java code. 

This does not seem to be in the roadmap so can this issue be used to track that? Open to implementation ideas or help.

**Comment by aiaicode** [comment]
I guess you should build it and add a new PR? 

[I'm not from Llama.cpp team]

**Comment by Peng-YM** [comment]
In fact, I am building a Java binding for llama.cpp because I am not familiar with C++. I still need some time to complete it and hope to release it as soon as possible.

cc: @ggerganov

**Comment by codeastra2** [comment]
@Peng-YM that's great , we can collaborate on this ? I'm also building Java bindings.

**Comment by Peng-YM** [comment]
> 

Sure, gladly. Currently I've built a version of Java that works fine under a Mac, and I'm working on cross-platform issues, so maybe we can work on that together. I'll be releasing the first draft release this week!

**Comment by Peng-YM** [comment]
> @Peng-YM that's great , we can collaborate on this ? I'm also building Java bindings.

Hi, here is a working example of inference with LLaMA.cpp on the Java side

https://github.com/JavaLLM/llama4j/blob/main/src/test/java/org/javallm/llama4j/model/impl/LlamaModelImplTest.java

**Comment by mymagicpower** [comment]
https://github.com/crimsonmagick/llama-cpp-java-bindings/tree/master
