### ISSUE TITLE
Requesting Qwen-7B Support

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/llama.cpp#2528]
https://huggingface.co/Qwen/Qwen-7B

https://huggingface.co/Qwen/Qwen-7B-Chat

These two models are performing better than 13B models. and on C-eval beating ChatGPT.

Requesting model support for Llama.cpp.

**Comment by vonjackustc** [comment]
Qwen is similar to Llama model.
You need add bias params for QKV, and change the tokenizer to tiktoken.

I wonder if we can convert tiktoken vocab format to sentencepiece directly.

**Comment by arch-btw** [comment]
I haven't tried it but this might help:

https://huggingface.co/JosephusCheung/Qwen-LLaMAfied-7B-Chat

**Comment by vonjackustc** [comment]
https://huggingface.co/JosephusCheung/Qwen-LLaMAfied-7B-Chat
This repo from JosephusCheung can be converted into ggml format. You still need to change the EOS token from ggml source code (2 for llama but other for Qwen).

I think this model is still slightly different from the original Qwen especially in QwenAttentionBlock, Qwen applied log(n) to query.

**Comment by wtarreau** [comment]
Sadly I couldn't convert it, always getting cryptic python errors.

**Comment by arch-btw** [comment]
@aiaicode @vonjackustc @wtarreau 


https://github.com/ggerganov/llama.cpp/issues/3337

**Comment by KerfuffleV2** [comment]
I found this script for converting from Tiktoken vocab to HF: https://gist.github.com/xenova/a452a6474428de0182b17605a98631ee (didn't test it, but it looks reasonable and seems to be from a HF person.)

To actually use it, you'll also need to use #3743 since there wasn't already support for loading from `merges.txt`.

@TheBloke too since I assume you're looking to support these Qwen models.

**Comment by ggerganov** [comment]
Is there a blocker to support these models in `llama.cpp`? Would be nice to support the new 1.8B and 72B versions

**Comment by simveit** [comment]
https://github.com/QwenLM/qwen.cpp
can this maybe be of any help to support qwen in the future?

**Comment by choyakawa** [comment]
We should first support QKVO bias in llama.

**Comment by choyakawa** [comment]
There was an implementation here but failed, can anyone figure out what's wrong with this? 
https://github.com/ggerganov/llama.cpp/pull/3743#issuecomment-1825923608
It seems correct just to add bias terms to each parts.

**Comment by ggerganov** [comment]
- The bias tensors were not offloaded via a separate`cb()` call
- Seems like special tokens (`<|im_start|>`, `<|im_end|>`) were not escaped in their test?

**Comment by DavidGOrtega** [comment]
should this be closed by https://github.com/ggerganov/llama.cpp/pull/5037 ?
