### ISSUE TITLE
Interactive mode doesn't work

### ISSUE THREAD

**Issue by sussyboiiii** [ggerganov/llama.cpp#255]
Hello, 
I wanted to test the interactive mode but it just doesn't work for me, the AI on its own with one promt gives me an output but with the command for a promt for the user it doesn't work and I just get "dquote" until I exit the program. 
Thank you for your help!

<img width="1728" alt="Bildschirm­foto 2023-03-18 um 07 53 36" src="https://user-images.githubusercontent.com/90244617/226090388-9e64b610-38f8-4800-a18a-3b8b3563a0c2.png">

**Comment by JamoDevNich** [comment]
I'm not familiar with that shell, but I think the 'dquote' is cause by a missing end quote `"` at the end of your user prompt.

Try copying all the lines from the transcript [in the Readme](https://github.com/ggerganov/llama.cpp#interactive-mode) instead of only the first one?

**Comment by sussyboiiii** [comment]
Oh, thank you I completley overlooked the last quote I thought the conversation was an example of a "real" conversation. I'll close.
