### ISSUE TITLE
Is there a way to run ggml models on Intel ARC 770 GPU

### ISSUE THREAD

**Issue by tarunmcom** [ggerganov/llama.cpp#2552]
Is there a way to run ggml models on Intel ARC 770 GPU. Thanks

**Comment by akarshanbiswas** [comment]
Build with LLAMA_CLBLAST=1 with -ngl [number of layers]?

Also this isn't an issue and should be in discussions imo.

**Comment by tarunmcom** [comment]
I compiled with this flag and it compiled successfully. but GPU arguments ex:- -ngl are not enabled, so not able to use GPU offloading.

**Comment by SlyEcho** [comment]
Yes, with [OpenCL](https://github.com/ggerganov/llama.cpp#clblast).

Or Vulkan in the future.

**Comment by delock** [comment]
@SlyEcho have you observed any speed up when running on Intel ARC 770 GPU?  I have an ARC770m GPU which I think should be similiar but I get even worse performance than using 12700H CPU.  What GPU speed you observe with ARC770?

The speed I observed with the following command:
```
./main -m llama-2-7b-chat.Q5_K_M.gguf -p "Long long ago there is a little girl live in a kingdom that is far far away, one day" -n 256 -ngl 32
```
The performance I observed is around 6.8 tokens per second, way slower than I would expect
```
Log start                                                                                                                                                                                                                                                      
main: build = 1382 (11bff29)                                                                                                                                                                                                                                   
main: built with cc (GCC) 13.2.1 20230801 for x86_64-pc-linux-gnu                                                                                                                                                                                              
main: seed  = 1697381054                                                                                                                                                                                                                                       
ggml_opencl: selecting platform: 'Intel(R) OpenCL HD Graphics'                                                                                                                                                                                                 
ggml_opencl: selecting device: 'Intel(R) Arc(TM) A770M Graphics'                                                                                                                                                                                               
ggml_opencl: device FP16 support: true                                                                                                                                                                                                                         
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from ../llm-models/llama.cpp/llama-2-7b-chat.Q5_K_M.gguf (version GGUF V2 (latest))           
...
llama_print_timings:        load time =    4656.35 ms
llama_print_timings:      sample time =      72.17 ms /   143 runs   (    0.50 ms per token,  1981.41 tokens per second)
llama_print_timings: prompt eval time =    1255.12 ms /    21 tokens (   59.77 ms per token,    16.73 tokens per second)
llama_print_timings:        eval time =   20939.83 ms /   142 runs   (  147.46 ms per token,     6.78 tokens per second)
llama_print_timings:       total time =   22335.98 ms
Log end
```

**Comment by SlyEcho** [comment]
Sorry, but I don't have an Arc card. ARC770m is a mobile GPU which generally don't have very good performance yet.

**Comment by shibe2** [comment]
@delock Things to try:
- On longer prompts (600 tokens or more), see difference in prompt eval between CPU and CLBlast builds (you need to build without CLBlast to avoid using GPU).
- Different ngl values, including 0.
- [Tuning CLBlast](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md) for your GPU. It says that it is already tuned for Arc A770, but your GPU seems to have a different identifier, also possibly different characteristics.
- Different heuristic for choosing between CPU and GPU. Apply this [patch](https://gist.github.com/shibe2/b8df828ce594dda4075f5ad9c5e7df56) and try different values for `ratio` (you need to change it in the source and recompile every time).

These things are interdependent, the best result may be achieved with some combination of them.

**Comment by delock** [comment]
> @delock Things to try:
> 
> * On longer prompts (600 tokens or more), see difference in prompt eval between CPU and CLBlast builds (you need to build without CLBlast to avoid using GPU).
> * Different ngl values, including 0.
> * [Tuning CLBlast](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md) for your GPU. It says that it is already tuned for Arc A770, but your GPU seems to have a different identifier, also possibly different characteristics.
> * Different heuristic for choosing between CPU and GPU. Apply this [patch](https://gist.github.com/shibe2/b8df828ce594dda4075f5ad9c5e7df56) and try different values for `ratio` (you need to change it in the source and recompile every time).
> 
> These things are interdependent, the best result may be achieved with some combination of them.

@shibe2 Thanks for the tip.  I have been trying tuning CLBlast on Intel Arc A770M.  However after tuning and rebuild CLBlast and llama.cpp, I get extremely low token/s (around 0.2).  I also tried to copy the tuning parameter from `A770` to `A770M`, but the performance is also not as good as using CPU only.

Given that Arc 770m has 512GB/s memory bandwidth I think this result should not be expected.  I'll try your patch as next step to see if there is any difference.

**Comment by shibe2** [comment]
What about prompt eval? `-f long.txt -c 4096`

**Comment by shibe2** [comment]
@delock Possibly related: [Llama.cpp is slower on Iris Xe GPU than on CPU](https://redd.it/17gf824) on reddit.

**Comment by riverzhou** [comment]
Mark
