### ISSUE TITLE
console.cpp compatibility issue on Windows 7

### ISSUE THREAD

**Issue by whoreson** [ggerganov/llama.cpp#2567]
Doesn't compile on Win7 btw. These need to be commented out (no clue how to fix it properly, maybe someone should ask chatgpt):

```diff
--- examples/console.cpp.orig	2023-08-09 15:23:43.952009572 +0200
+++ examples/console.cpp	2023-08-09 15:24:20.209355303 +0200
@@ -69,11 +69,11 @@
         }
         if (hConsole) {
             // Enable ANSI colors on Windows 10+
-            if (advanced_display && !(dwMode & ENABLE_VIRTUAL_TERMINAL_PROCESSING)) {
-                SetConsoleMode(hConsole, dwMode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
-            }
+//            if (advanced_display && !(dwMode & ENABLE_VIRTUAL_TERMINAL_PROCESSING)) {
+//                SetConsoleMode(hConsole, dwMode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
+//            }
             // Set console output codepage to UTF8
-            SetConsoleOutputCP(CP_UTF8);
+//            SetConsoleOutputCP(CP_UTF8);
         }
         HANDLE hConIn = GetStdHandle(STD_INPUT_HANDLE);
         if (hConIn != INVALID_HANDLE_VALUE && GetConsoleMode(hConIn, &dwMode)) {
```

And yes I have no clue how to format/quote this on shithub either, sry :)

**Comment by DannyDaemonic** [comment]
That allows color to be added to the output. Which compiler are you using?

**Comment by SlyEcho** [comment]
Windows 7 is too old for VT sequences, I think they were only added in Windows 10.

**Comment by DannyDaemonic** [comment]
Yeah, it's new to Windows 10. There shouldn't be anything wrong with `SetConsoleOutputCP` though. It's quite old, and `CP_UTF8` was introduced in Windows 2000, which predates Windows 7.

But the real issue here isn't Windows 7, it's that the compiler/sdk doesn't know about `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

Rather than using an `#ifdef` to avoid calling `SetConsoleMode` at that point in the code, it might be better to just set it using 0x04 and check for errors. After all, an executable compiled with a modern MS compiler and SDK will still run on Windows 7.

**Comment by DannyDaemonic** [comment]
@whoreson
PR #2569 should take care of this. It would be great if you could verify everything works for you.
If you don't know how to check out that PR or just prefer a patch, you can download it here: [2569.patch](https://patch-diff.githubusercontent.com/raw/ggerganov/llama.cpp/pull/2569.patch)

**Comment by DannyDaemonic** [comment]
@whoreson I haven't heard back from you, but this fixes the issue in my limited testing. If you still have issues compiling on Windows 7, let me know which compiler you're using so I can try to reproduce it.

**Comment by whoreson** [comment]
Ah, sorry about that, I don't really check github. In any case yes, it did fix it, thanks.

**Comment by karim23657** [comment]
@DannyDaemonic Any prebuilt for windows 7?

**Comment by DannyDaemonic** [comment]
@karim23657 I believe the latest builds should work for Windows 7 now. The last thing holding it back was a DLL requirement that made it error on Windows 7, but that was resolved. If those DLL errors have snuck back in, it wouldn't hurt to open a issue for it.
