### ISSUE TITLE
What is the format of weights for the input model to convert.py?

### ISSUE THREAD

**Issue by RonanKMcGovern** [ggerganov/llama.cpp#2571]
Here is a comment from the ReadMe regarding usage of convert.py:
```
# obtain the original LLaMA model weights and place them in ./models
```
However, it's not clear what format those weights need to be in...

1. In what format do I need to have the original weights? consolidated.00.pth or .bin?
2. If .bin, do the weights need to be float 32 or can they be bf16?
3. If .bin, is there a way to handle sharded weights? e.g. Llama 2 7B sharded into ~10 GB and ~3 GB? Can I specify each shard as a command line argument here:
```
# convert the 7B model to ggml FP16 format
python3 convert.py models/7B/
```

**Comment by RonanKMcGovern** [comment]
Ok, I should have just looked at convert.py before in llama ccp.

To answer my own Qs:
- convert.py supports input models in many formats (including .pth and .bin)
- convert.py supports multiple data types, including float 32 and bf16
- convert.py even supports shards and finds them automatically (very nice!)

**Comment by Kushagrapuro** [comment]
thnx
