### ISSUE TITLE
POST to server takes forever

### ISSUE THREAD

**Issue by YerongLi** [ggerganov/llama.cpp#2572]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
```
curl --request POST \
    --url http://localhost:8080/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'
```
This should return something

# Current Behavior
**main** works while **server** can run while POST takes forever
```
./main -m $SCRATCH/.cache/pyllama/65B/ggml-model-q4_0.bin -p "Who is Elon Musk" -t 1 -n 128 --temp 0.1 --top-p 0.90 -ngl 41
This works 
```
server also starts
```
$ ./server -m $SCRATCH/.cache/pyllama/65B/ggml-model-q4_0.bin -c 2048
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4986 MB
llama_new_context_with_model: kv self size  = 1024.00 MB

llama server listening at http://127.0.0.1:8080

{"timestamp":1691652169,"level":"INFO","function":"main","line":1409,"message":"HTTP server listening","hostname":"127.0.0.1","port":8080}

```

While POST takes forever
```
curl --request POST     --url http://127.0.0.1:8080/completion     --header "Content-Type: application/json"     --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'

```
# Environment and Context

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             1
NUMA node(s):          4
Vendor ID:             AuthenticAMD
CPU family:            25
Model:                 1
Model name:            AMD EPYC 7763 64-Core Processor
Stepping:              1
CPU MHz:               2445.587
BogoMIPS:              4891.17
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              32768K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
NUMA node2 CPU(s):     32-47
NUMA node3 CPU(s):     48-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 invpcid_single hw_pstate sme ssbd rsb_ctxsw ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq overflow_recov succor smca
```

* Operating System, e.g. for Linux:

`$ uname -a`
```
$ uname -a
Linux ccc0312.campuscluster.illinois.edu 3.10.0-1160.92.1.el7.x86_64 #1 SMP Thu May 18 11:23:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
* SDK version, e.g. for Linux:

```
$ python3 --version
3.9.12
$ make --version
GNU Make 3.82
$ g++ --version
g++ (GCC) 11.2.0
```

# Failure Information (for bugs)

```
$ ./server -m $SCRATCH/.cache/pyllama/65B/ggml-model-q4_0.bin -c 2048
Illegal instruction

```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. 
`make LLAMA_CUBLAS=1`
2. `$ ./server -m $SCRATCH/.cache/pyllama/65B/ggml-model-q4_0.bin -c 2048`
# Failure Logs

Please include any relevant log snippets or files. If it works under one configuration but not under another, please provide logs for both configurations and their corresponding outputs so it is easy to see where behavior changes.

Also, please try to **avoid using screenshots** if at all possible. Instead, copy/paste the console output and use [Github's markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to cleanly format your logs for easy readability.

Example environment info:
```
llama.cpp$ git log | head -1
commit 1a7cdf4c5a54f12de0feab033ba75c36f8f3bd3a
```
![screenshot](https://github.com/ggerganov/llama.cpp/assets/13112023/b5ac30c8-69c6-42a0-b036-73218c5f5e72)

**Comment by YerongLi** [comment]
![screenshot](https://github.com/ggerganov/llama.cpp/assets/13112023/d709fc80-7796-4744-a12d-be0ee0d08beb)

**Comment by SlyEcho** [comment]
Could you try with a different smaller model? It looks like the 65B model is just processing too slowly.

Did you try running `make clean` before `make LLAMA_CUBLAS=1`?

---

> ```
> $ ./server -m $SCRATCH/.cache/pyllama/65B/ggml-model-q4_0.bin -c 2048
> llama_model_load_internal: offloading 32 repeating layers to GPU
> llama_model_load_internal: offloading non-repeating layers to GPU
> llama_model_load_internal: offloading v cache to GPU
> llama_model_load_internal: offloading k cache to GPU
> llama_model_load_internal: offloaded 35/35 layers to GPU
> llama_model_load_internal: total VRAM used: 4986 MB
> llama_new_context_with_model: kv self size  = 1024.00 MB
> ```

This log is just full of anomalies. A 65B size model has 80 layers, not 32. So it's actually 7B?
Without `-ngl 35` on the command line it will not load 35 layers to VRAM.
Many lines missing, especially the build info.

**Comment by YerongLi** [comment]
- I `make clean` and re-make the repo
- with 7B model it also does not work, as a ablation test, I found the 7B model works with ./main, while the server POST takes forever.
```
./server -m $SCRATCH/.cache/pyllama/7B/ggml-model-q4_0.bin -c 2048 -ngl 83 
```

**Comment by YerongLi** [comment]
Any update?

**Comment by SlyEcho** [comment]
I have not been able to replicate this error, maybe it's related to some CUDA thing?

**Comment by YerongLi** [comment]
> I have not been able to replicate this error, maybe it's related to some CUDA thing?

How I can debug on this, I tested it on A10 and V100 with two different machines, the server simply does not response, while I see the ./server is using GPU memory.

**Comment by staviq** [comment]
Update llamacpp, lots of bugfixes happened in the last two weeks, chances are this already got fixed.

I recommend renaming, or deleting your current llama.cpp directory, (you can keep the models) and downloading fresh build or doing a clean git clone, and rebuilding from zero.

Find an even smaller model, there are already 3b models in gguf on huggingface.

Then, run that small model with just `./main -m modelpath -n 4 -p "hey"` and see if it works.

If it works, run it the same way but add `-ngl 1`

Then we would be able to tell if it's a problem with the GPU or something else

**Comment by YerongLi** [comment]
Still my `./main` works for GPU and CPU while the `./server` does **NOT** work for either GPU or CPU.
![screenshot](https://github.com/ggerganov/llama.cpp/assets/13112023/05b5d78e-f0da-4010-b01e-67b1052d43fd)

**Comment by YerongLi** [comment]
In the `examples/server/server.cpp`

I cannot receive POST request
```
  svr.Post("/completion", [&llama](const Request &req, Response &res)
           {
      fprintf(stdout, "POST /completion");
      ...
```

**Comment by YerongLi** [comment]
> I have not been able to replicate this error, maybe it's related to some CUDA thing?

I found there is a infinite loop in the code, not the cuda thing.

**Comment by SlyEcho** [comment]
It looks like it's hanging inside `llama.doCompletion()`. I can't really know why, though.

**Comment by YerongLi** [comment]
with the verbos option I got the following output:
```
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/35 layers to GPU
llm_load_tensors: VRAM used: 0 MB
..................................................................................................
llama_new_context_with_model: kv self size  = 1024.00 MB
llama_new_context_with_model: compute buffer total size =  153.47 MB
llama_new_context_with_model: VRAM scratch buffer: 152.00 MB

llama server listening at http://127.0.0.1:8080


Yerong 
{"timestamp":1693631431,"level":"INFO","function":"main","line":1609,"message":"HTTP server listening","hostname":"127.0.0.1","port":8080}
POST /completion
{"timestamp":1693631861,"level":"VERBOSE","function":"parse_options_completion","line":1196,"message":"completion parameters parsed","frequency_penalty":0.0,"grammar":"","ignore_eos":false,"logit_bias":[],"mirostat":0,"mirostat_eta":0.10000000149011612,"mirostat_tau":5.0,"model":"/scratch/yerong//.cache/pyllama/Llama-2-7b/ggml-model-q4_0.gguf","n_ctx":2048,"n_keep":0,"n_predict":128,"n_probs":0,"penalize_nl":true,"presence_penalty":0.0,"repeat_last_n":64,"repeat_penalty":1.100000023841858,"seed":4294967295,"stop":[],"stream":false,"temp":0.800000011920929,"tfs_z":1.0,"top_k":40,"top_p":0.949999988079071,"typical_p":1.0}
{"timestamp":1693631861,"level":"VERBOSE","function":"loadPrompt","line":389,"message":"prompt ingested","n_past":0,"cached":"","to_eval":" Building a website can be done in 10 simple steps:"}
POST /completion AFTER loadPrompt
POST /completion !llama.stream
llama.has_next_token: true
While loop

```

> I am not able to reproduce this. Running the server with `-v` to see a detailed log may help find the issue.

![screenshot](https://github.com/ggerganov/llama.cpp/assets/13112023/e4184aa8-d720-4a87-9efd-6c0da59586f7)

**Comment by jpadhye-cisco** [comment]
I'm experiencing the same issue on M1 MAC. Server queries are 10x slow and give incomplete output

**Comment by YerongLi** [comment]
My server is even worse, there is an infinite loop in `llama.doCompletion()`

**Comment by jpadhye-cisco** [comment]
> I'm experiencing the same issue on M1 MAC. Server queries are 10x slow and give incomplete output

Got resolved after updating to latest version

**Comment by YerongLi** [comment]
> > I'm experiencing the same issue on M1 MAC. Server queries are 10x slow and give incomplete output
> 
> Got resolved after updating to latest version

The latest version did not fix it for me
```
(base) [yerong2@ccc0351 llama.cpp]$ curl --request POST     --url http://localhost:8080/completion     --header "Content-Type: application/json"     --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'



```
```
Every 1.0s: nvidia-smi | tail -n 8                                                                                                    Thu Sep 14 04:26:50 2023

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     43206      C   ./server                         5861MiB |
+-----------------------------------------------------------------------------+

```

**Comment by wigbkons** [comment]
Hi,
I had the same problem with llama.cpp installed on a virtualbox and I managed to make it work by reducing the context to 128

**Comment by phymbert** [comment]
See: https://github.com/ggerganov/llama.cpp/blob/master/examples/server/tests/features/wrong_usages.feature
