### ISSUE TITLE
Specify the version of `python3` to use in repo docs

### ISSUE THREAD

**Issue by chris-hatton** [ggerganov/llama.cpp#258]
The default `python3` on my system is `3.11.2` for which `sentencepiece` [does not install](https://github.com/google/sentencepiece/issues/378).

Where Python toolchains in general seem fragile to minor version differences, specifying the exact expected Python version for newcomers (like me) will reduce frustration and make this work more accessible.

Specifying `python3.9` on CLI worked for me; unsure if this was the intended version.

**Comment by LoganDark** [comment]
It's because the devs are stupid and do not publish the needed build files to pypi. You have to use a version with a wheel, which for Windows on x86_64, is Python 3.10

**Comment by prusnak** [comment]
Added a comment about Python version in https://github.com/ggerganov/llama.cpp/pull/269
