### ISSUE TITLE
Inconsistent Embedding Results on Different OS Platforms

### ISSUE THREAD

**Issue by saddam213** [ggerganov/llama.cpp#2582]
Summary:
The embedding function in the LLM library is producing inconsistent results for the same token when executed on different operating system (OS) platforms. Specifically, the embeddings generated for the token "cat" differ between Ubuntu 22 and Windows Server 2022.

We have identified the bug mentioned in LLamaSharp [PR #97](https://github.com/SciSharp/LLamaSharp/pull/97)

Steps to Reproduce:

    On Ubuntu-22:
        Command: ./embedding -m ~/llama-2-7b-chat.ggmlv3.q3_K_S.bin -p cat
        Resulting Embedding: -0.099176 -0.717907 -0.008532 -0.989839 -0.663397

    On Windows Server 2022:
        Command: embedding.exe -m llama-2-7b-chat.ggmlv3.q3_K_S.bin -p cat
        Resulting Embedding: -0.127304 -0.678057 -0.085244 -0.956915 -0.638633

Expected Result:
The embedding function should produce consistent embeddings for the same token across different OS platforms, given the same model and input parameters.

Actual Result:
The embeddings generated for the token "cat" vary between Ubuntu 22 and Windows Server 2022, indicating an inconsistency in the embedding function's behavior across different OS platforms.

**Comment by martindevans** [comment]
I just had a CI run on LLamaSharp fail due to a simple test (inferring a response to `"Question. what is a cat?\nAnswer: ";`) returning different results on Windows and Linux.

I suspect this is the same fundamental issue - since the embeddings are different the model will produce slightly different results.

**Comment by martindevans** [comment]
To add a little more weight to this, another test I did which fails on some platforms and not others is this:

```csharp
var cat = _embedder.GetEmbeddings("cat");
var kitten = _embedder.GetEmbeddings("kitten");
var spoon = _embedder.GetEmbeddings("spoon");

var close = Dot(cat, kitten);
var far = Dot(cat, spoon);

Assert.True(close < far);
```

i.e. check that `cat` and `kitten` are more similar than `cat` and `spoon` (according to dot product). This passes on windows and fails on Linux.

This shows that it's not just tiny differences in floating point rounding that barely matter, the embeddings just seem to be _wrong_ on some platforms.

**Comment by d-kleine** [comment]
Has this issue been resolved?
