### ISSUE TITLE
Add quantized-matrix full-precision-vector product kernel for significant speed up

### ISSUE THREAD

**Issue by RonanKMcGovern** [ggerganov/llama.cpp#2585]
This may be a naive suggestion, but why not do this as GPTQ did to achieve speed-up in toks?

From the [GPTQ paper](https://arxiv.org/pdf/2210.17323.pdf):

Next, we consider language generation, one of the most appealing applications of these models, with
the goal of latency reduction. Unlike LLM.int8(), which reduces memory costs but has the same
runtime as the FP16 baseline, we show that our quantized models can achieve significant speedups
for this application. For language generation, the model processes and outputs one token at-a-time,
which for OPT-175B can easily take a few 100s of milliseconds per token. Increasing the speed at
which the user receives generated results is challenging, as compute is dominated by matrix-vector
products. Unlike matrix-matrix products, these are primarily limited by memory bandwidth. We
address this problem by developing a quantized-matrix full-precision-vector product kernel which
performs a matrix vector product by dynamically dequantizing weights when needed. Most notably,
this does not require any activation quantization. While dequantization consumes extra compute,
the kernel has to access a lot less memory, leading to significant speedups, as shown in Table 6. We
note that almost all of the speedup is due to our kernels, as communication costs are negligible in
our standard HuggingFace-accelerate-like setting (see Appendix A.2.2 for details).

**Comment by JohannesGaessler** [comment]
This technique is already known to us and it's slower than quantizing the hidden state and doing the calculations with a quantized matrix and a quantized vector.

**Comment by RonanKMcGovern** [comment]
Thanks, closing this off then.
