### ISSUE TITLE
Models not loaded into RAM on CPU-Only setup. Is the library using the disk as RAM?

### ISSUE THREAD

**Issue by jacmkno** [ggerganov/llama.cpp#2589]
Inference is painfully slow on CPU-Only setup and it seems to be because the model is not fully loaded into RAM. Standard hugging face transformers do load the whole models into GPU RAM in order to maximize performance.

I'm using https://github.com/abetlen/llama-cpp-python which I believe to be using this library to run the models and I found that the model is not fully loaded into memory while doing an inference with CPU-Only and then I found this comment on GGML's Features in the README: "Zero memory allocations during runtime" (https://github.com/ggerganov/ggml):

Same issue with another independent library using GGML (ctransformers): https://github.com/marella/ctransformers/issues/85

Seems to me this library is possibly to blame.

Questions:

1. Does this mean this library indeed does not ever load the whole model into RAM? That seems to me like a waste of RAM for users with high RAM.
2. Is the library just doing lots of reads to disk during inference?
3. Is there an easy option to let the library load the whole model into RAM and keep it there?

Here is the Colab to test it (keep an eye on resources during inference):
https://colab.research.google.com/drive/1iGifBXEaXI2JDbJG1Il7BAS8gqVWm8kR

**Comment by Azeirah** [comment]
You can load the entire model into system ram by adding the `--mlock` parameter.

If you're offloading to the gpu, you can tell llama.cpp how many model layers you want to put on the gpu with `--ngl NUM_LAYERS`. For instance, 7B model has 32 layers. You can say `--ngl 32` to put the entire model on GPU VRAM, `--ngl 0` to offload none, and anything in between depending on how much VRAM you have available.

**Comment by SlyEcho** [comment]
It normally loads the model using memory-mapped files. But there are some options:

- `--no-mmap`: load using memory allocation, this is what you are asking for.
- `--mlock`: use memory mapping but lock the pages, most useful on macBooks with little RAM (yes even 8GB is very little).
- `-ngl N`: load N layers to the GPU for GPU backends.

Note that if the system does not actually have enough RAM for the model and compute buffers the inference will always be "painfully slow" because it will have to use virtual swap memory which is pretty much the same thing as mmap. In the worst case it could even lock up or crash the machine.

**Comment by Manouchehri** [comment]
When you offload 100% of all the layers to the GPU, does the model still stay in the system's RAM? If so, is that intentional?

**Comment by youforgetsomething** [comment]
how to force the model to be completely on RAM (CPU only) , even use the RAM as much as it can fit all the model in , not just a part from the model , i want assure the model ALL THE MODEL is loaded to ram, not disk not swap , how to do this ? . current problem is after first prompt the model act like it reading from hell slow hdd..1st prompt run as fast as my cpu is , but when requesting another prompt it uses 0% 1% from the cpu..there;s something wrong here, is it memory issue or what ?

**Comment by SlyEcho** [comment]
> how to force the model to be completely on RAM (CPU only) , even use the RAM as much as it can fit all the model in , not just a part from the model , i want assure the model ALL THE MODEL is loaded to ram, not disk not swap , how to do this ? . current problem is after first prompt the model act like it reading from hell slow hdd..1st prompt run as fast as my cpu is , but when requesting another prompt it uses 0% 1% from the cpu..there;s something wrong here, is it memory issue or what ?

You should look into the `--no-mmap` and/or `--mlock` switches.
