### ISSUE TITLE
[User] `--reverse-prompt` no longer echoes in the console

### ISSUE THREAD

**Issue by 44670** [ggerganov/llama.cpp#2598]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [Y] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [Y] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [Y] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Hi!

I have been using the `--reverse-prompt "User:"` parameter along with the interactive mode in previous versions. When waiting for user input, the console used to echo "User:" as shown in the screenshot below:

![image](https://github.com/ggerganov/llama.cpp/assets/3153194/c8528844-53aa-4a18-b944-6b195f683a5a)

# Current Behavior

However, in the new version found in `llama.cpp`, the "User:" prompt is no longer echoed in the console. I've checked the documentation, and it doesn't seem to mention any changes regarding this behavior. Is this an oversight or an intentional modification?

<img width="951" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/3153194/a5bbc3ff-7619-4c3d-9d8e-f643b921de96">

My command-line args could be found at: https://github.com/OpenBuddy/OpenBuddy/blob/main/chat-llamacpp.bat

Please let me know if you need any additional information or if there's something else I need to do to restore the previous behavior.

Thank you!

**Comment by JackJollimore** [comment]
Apparently, it's [intentional](https://github.com/ggerganov/llama.cpp/issues/2417#issuecomment-1654868632): "Previously, the first reverse prompt (if existed) is always inserted. Now if the model generate EOS, the reverse prompt is not inserted. To get the same behavior, please use

`./main -m "$MODEL" -i --in-prefix "User: " --in-suffix "Assistant:" ...`


There are seemingly unintentional effects after the `--input-bos` commit. Here's a [Poll](https://github.com/ggerganov/llama.cpp/discussions/2578).


Here's a repo without `--input-bos`: https://github.com/JackJollimore/llama.cpp-without-input-bos/tree/master

**Comment by 44670** [comment]
Ahh, thank you for the explanation! I will update my demo script soon.

**Comment by 44670** [comment]
Hmm...

I have read through the documentation and example code again, and I'm feeling even more confused. 

In the original examples within the repo, the cmdline was `--r "User:" --in-prefix " "`, but the reasoning behind this doesn't seem to be clearly explained. Could it be because `--in-prefix "User: "` itself is incorrect? 

Moreover, Is the behavior of `--in-prefix "User: "` in the new version (including what is displayed in the console and what is fed into the model) completely consistent with `--r "User:" --in-prefix " "` in the old version? I hope that the differences between the behavior of new and old versions can be more clarified in the documentation/example shell script.

**Comment by JackJollimore** [comment]
> I have read through the documentation and example code again, and I'm feeling even more confused.

Welcome to the Club.


> In the original examples within the repo, the cmdline was `--r "User:" --in-prefix " "`, but the reasoning behind this doesn't seem to be clearly explained. Could it be because `--in-prefix "User: "` itself is incorrect?
>

The current documentation is not updated, so if you absolutely rely on, `-r "User:" --in-prefix " "`, then I suggest using a repo where the `--input-bos` commit is reverted, and the documentation is applicable.


> Moreover, Is the behavior of `--in-prefix "User: "` in the new version (including what is displayed in the console and what is fed into the model) completely consistent with `--r "User:" --in-prefix " "` in the old version? I hope that the differences between the behavior of new and old versions can be more clarified in the documentation/example shell script.


I suppose it's intended to be consistent, but my testing has shown that, No - it's not 1:1

Related: https://github.com/ggerganov/llama.cpp/issues/2507, https://github.com/ggerganov/llama.cpp/issues/2417


If if were my decision then llama.cpp would either resolve the unintended effects that I mentioned in the [Poll](https://github.com/ggerganov/llama.cpp/discussions/2578), or simply revert `--input-bos` commit.

**Comment by IDDT** [comment]
From what I understood, using `--in-prefix "User: "` relies on model outputting end-of-stream token after Assistant response. If there is no end-of-stream, the model keeps generating user input, which is undesirable. Launching llamacpp with `-r "User:" --in-prefix " " --ignore-eos` seemed to fix the issue for me.

**Comment by jxy** [comment]
@IDDT yes.

**Comment by JackJollimore** [comment]
ggerganov [accurately summed it up](https://github.com/ggerganov/llama.cpp/pull/2646#issuecomment-1685193819): "Ok, I think I see the problem. It comes from keeping EOS token. Ignoring it is not the same as before the BOS commit because there is no new line.

I'm on a phone so cannot push a fix. likely on monday or tuesday"

Thank you @wtarreau for bisecting to help identify the problem.

**Comment by JackJollimore** [comment]
@IDDT, @44670:

If you'll help test then here's a PR for fix: https://github.com/ggerganov/llama.cpp/pull/2689
