### ISSUE TITLE
reason only last? increase 2048 tokens?

### ISSUE THREAD

**Issue by SilvaRaulEnriqueCJM** [ggerganov/llama.cpp#2599]
Does it reason only the last entered tokens? Is there a way for it to accept more than 2048?

**Comment by klosax** [comment]
LLaMA-2 models work with context lengths up to 4096. You can change the max context length by using the `--ctx-size` parameter.  See https://github.com/ggerganov/llama.cpp/tree/master/examples/main#context-management

**Comment by SilvaRaulEnriqueCJM** [comment]
if specify: ... -m models/TheBloke/llama-2-70b-chat.ggmlv3.q2_K.bin -c 4096, say:
main: warning: base model only supports context sizes no greater than 2048 tokens (4096 specified)

If specity: -m models/TheBloke/llama-2-70b-chat.ggmlv3.q2_K.bin -c 32768 --rope-scale 8, say:
main: warning: base model only supports context sizes no greater than 2048 tokens (32768 specified)

Only 2048 tokens are remember efectivaly?
In documentation say: "However, increasing the context size beyond 2048 may lead to unpredictable results."
Specify more tokens produce un predictable results in all cases, or there are a posibility for utilize more tokens to input more text to process?

**Comment by klosax** [comment]
> if specify: ... -m models/TheBloke/llama-2-70b-chat.ggmlv3.q2_K.bin -c 4096,

This should work since the model supports a sequence length of 4096

> main: warning: base model only supports context sizes no greater than 2048 tokens (4096 specified)

This is an old warning for previous llama models, just ignore it.

> If specity: -m models/TheBloke/llama-2-70b-chat.ggmlv3.q2_K.bin -c 32768 --rope-scale 8, say:

The rope scale works best with models fine-tuned with a larger sequence length like:
https://huggingface.co/togethercomputer/LLaMA-2-7B-32K

**Comment by SilvaRaulEnriqueCJM** [comment]
Thank you.
¿Is there are any chat optimized works best?

**Comment by SilvaRaulEnriqueCJM** [comment]
@klosax 
¿https://huggingface.co/togethercomputer/LLaMA-2-7B-32K is a model for python?
¿what order is need to run with llama.cpp?

**Comment by klosax** [comment]
Download all files and convert the model to ggml using the convert.py script. See https://github.com/ggerganov/llama.cpp#using-openllama

**Comment by klosax** [comment]
No need to convert. Found ggml models here https://huggingface.co/s3nh/LLaMA-2-7B-32K-GGML/tree/main

**Comment by SilvaRaulEnriqueCJM** [comment]
1) For this model with params:
-m models/s3nh/LLaMA-2-7B-32K.ggmlv3.q8_0.bin --mlock -ngl 254 -c 32768 --rope-scale 8 -eps 1e-5 --reverse-prompt "User:" --file chat_dies_User_Assistant.txt --in-prefix ' ' "$@"

n_ctx is informed like this:
llama_model_load_internal: n_ctx      = 2048

The generation is fast, but unaccerted. ¿Is this because the model is not chat?


2) For another model, with this parameters:
models/TheBloke/llama-2-13b-chat.ggmlv3.q8_0.bin --mlock -ngl 254 -c 32768 --rope-scale 8 -eps 1e-5 --reverse-prompt "User:" --file chat_dies_User_Assistan
t.txt --in-prefix ' ' "$@"

The generation is not accerted, is delirious.


3) For bether configuration:
-m models/TheBloke/llama-2-13b-chat.ggmlv3.q8_0.bin -ngl 254 -c 4096 --reverse-prompt "User:" --file chat_dies_User_Assistant.txt --in-prefix ' ' "$@"

The generation is accerted in many cases.

But in none option the n_ctx informated is more that 2048:
llama_model_load_internal: n_ctx      = 2048


Is there a better configuration option and model to chat?
