### ISSUE TITLE
Failed to quantize a model

### ISSUE THREAD

**Issue by LeLaboDuGame** [ggerganov/llama.cpp#2600]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
I want quantize a pythia model f16 to q5_1

# Current Behavior

I got this error:
```cmd
.\quantize.exe C:\Users\ad\PycharmProjects\finetuneModel\pythia-410m-deduped\ggml-model-f16.bin ./pythia410Mq5_1.bin q5_1
ggml_opencl: selecting platform: 'AMD Accelerated Parallel Processing'
ggml_opencl: selecting device: 'gfx1032'
ggml_opencl: device FP16 support: true
main: build = 778 (1cf14cc)
main: quantizing 'C:\Users\ad\PycharmProjects\finetuneModel\pythia-410m-deduped\ggml-model-f16.bin' to './pythia410Mq5_1.bin' as Q5_1
llama.cpp: loading model from C:\Users\ad\PycharmProjects\finetuneModel\pythia-410m-deduped\ggml-model-f16.bin
llama_model_quantize: failed to quantize: unexpectedly reached end of file
main: failed to quantize model from 'C:\Users\ad\PycharmProjects\finetuneModel\pythia-410m-deduped\ggml-model-f16.bin'
```

# Environment and Context
I'm on windows 11
rx 6600xt
16 go ram
I5100400f
clblast ON

# Failure Information (for bugs)

I initial try to quantize with the dolly quantize from ggml example git and it's work but know I want that work with llamacpp 
PS:The quantize with dolly dont work with llamacpp.

# Steps to Reproduce

1-Download https://huggingface.co/EleutherAI/pythia-410m-deduped
2-Use the convert-h5-to-ggml.py script to get a F16 ggml .bin
3-Try to quantize
4-BUG (F*CK)

PS:
I dont speak very good in english I apologie !

**Comment by klosax** [comment]
Pythia is a GPT-NeoX model and is not supported by llama.cpp yet. There is an example for using GPT-NeoX models here: https://github.com/ggerganov/ggml/tree/master/examples/gpt-neox

**Comment by LeLaboDuGame** [comment]
Thanks but that say I can’t use with python api ?
or else how can I do because a believe that python llama api work with llamacpp

**Comment by LeLaboDuGame** [comment]
Ho snif ...
For the moment how I can know the model arch on HF ? I have to choose GGML arch model or something else ??

**Comment by klosax** [comment]
Most models include "llama" in the name.
You could also look for `LlamaForCausalLM` in config.json:
https://huggingface.co/NousResearch/Llama-2-7b-hf/blob/main/config.json#L3
