### ISSUE TITLE
¿Prompt to charge llama-2-70b-chat.ggmlv3.q2_K.bin?

### ISSUE THREAD

**Issue by SilvaRaulEnrique** [ggerganov/llama.cpp#2601]
What is the prompt to charge llama-2-70b-chat.ggmlv3.q2_K.bin   (26 GB)

There is a error:
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024

**Comment by klosax** [comment]
Use the parameter `-gqa 8` for 70b models to work.
