### ISSUE TITLE
'Llama' object has no attribute 'model'

### ISSUE THREAD

**Issue by Giulianini** [ggerganov/llama.cpp#2606]
llama-cpp-python: 0.1.77
langchain: 0.0.263
model: llama-2-7b.ggmlv3.q2_K.bin

I cannot figure out the problem.

I'm on windows.
On mac, with same configuration it works

**Comment by klosax** [comment]
To get help with this you should open an issue at the llama-cpp-python repo here https://github.com/abetlen/llama-cpp-python
