### ISSUE TITLE
[User] Feature Request: Prompt Caching Server Support

### ISSUE THREAD

**Issue by nova706** [ggerganov/llama.cpp#2617]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Server.exe could support `--prompt-cache` to allow loading from a session and saving to a session. The `--prompt-cache` arg could be passed when starting the server to load the session with the completions. An additional endpoint could allow the user to initiate a save of the cache file. This would effectively allow the user to initiate a session, chat, reset, chat, save, close and then resume from the save point.

This behavior would be slightly different than the main.cpp behavior where the saving would be triggered by the user rather than after each completion. In this case `--prompt-cache-all` and `prompt-cache-ro` would not be needed.

# Current Behavior

The server does not currently support `--prompt-cache`

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

12th Gen Intel(R) Core(TM) i9-12900H, 2500 Mhz, 14 Core(s), 20 Logical Processor(s)
Nvidia 3050 TI
16GB RAM

* Operating System, e.g. for Linux:

Windows 11 - 10.0.22621 Build 22621

* SDK version, e.g. for Linux:

```
cmake version 3.27.1
```

**Comment by SlyEcho** [comment]
It would have to be not a server executable argument but an API argument, because it could be different for different clients of the server. But how do you upload and download the files? The files are rather large as well. How do you manage sessions so that one client's cache is not overwritten by another client's request?

I think a better way would be to cache the contexts in some kind of database and look them up on the most common matching prefix string.

**Comment by amakropoulos** [comment]
I'd also be interested in this feature
