### ISSUE TITLE
[Question] about encode and decode

### ISSUE THREAD

**Issue by phamkhactu** [ggerganov/llama.cpp#2619]
Thanks for great repo!!

I use llama 2 7B, convert to ggml q4_0. When I test with question. Model want to remind my question, but missing some character in word. For example: ```ỉ``` in word ```thỉnh```. I don't find any solution for it?? Could you give me some advance!!
![image](https://github.com/ggerganov/llama.cpp/assets/42369268/21de7697-1948-473e-a642-ad5616627da3)

**Comment by klosax** [comment]
Since you are using an LLaMA-2 model try parameter `-eps 1e-5` for full generation quality.

**Comment by phamkhactu** [comment]
> Since you are using an LLaMA-2 model try parameter `-eps 1e-5` for full generation quality.

@klosax Oh, Thank you, I will try on it.
