### ISSUE TITLE
Bug: Gibberish output when using ngl more than 0. [Linux VM AG100]

### ISSUE THREAD

**Issue by fizahkhalid** [ggerganov/llama.cpp#2621]
I compiled CUDA using CUBLAS make and whenever I use ngl to offload some layers to GPU, the speed is awesome but the response is totally gibberesh. On CPU the response quality, is fine. 

I just want to know if someone else is facing the same issue or what to look for to resolve this?

**Comment by JohannesGaessler** [comment]
>what to look for to resolve this?

The first step would be to provide debugging information.

**Comment by mkll** [comment]
I ran into a different problem, but it may have similar roots. In interactive mode, immediately after launch, without waiting for a prompt, the model starts generating a response to an arbitrary prompt. I can't figure out where it comes from.

**Comment by JackJollimore** [comment]
> I ran into a different problem, but it may have similar roots. In interactive mode, immediately after launch, without waiting for a prompt, the model starts generating a response to an arbitrary prompt. I can't figure out where it comes from.

Unfortunately, you're not giving enough information for people to figure out what's happening. There may be a valid problem, but it's confusing without following the template for Issues.


[README](https://github.com/ggerganov/llama.cpp/blob/1f0bccb27929e261744c979bc75114955da49e98/examples/main/README.md?plain=1#L90) explains usage of `--interactive-first` if you expect llama.cpp to wait for your prompt.

**Comment by mkll** [comment]
@JackJollimore Thank you, you're right. But I just passed by and reported what I had, not setting out to get an answer. I'm not a person from the AI world, so it's possible that I did something wrong. So, never mind then.

**Comment by JackJollimore** [comment]
> But I just passed by and reported what I had, not setting out to get an answer. I'm not a person from the AI world, so it's possible that I did something wrong. So, never mind then.

I don't intend to discourage you, more so there's a several reasons llama.cpp can ramble in `interactive` mode, so share your ./main if you feel like solving it.
