### ISSUE TITLE
Add rust bindings to the list

### ISSUE THREAD

**Issue by mdrokz** [ggerganov/llama.cpp#2628]
Hi i made rust bindings for llama.cpp https://github.com/mdrokz/rust-llama.cpp can we add it to the bindings list in the readme ? 

I know there is [rustformers](https://github.com/rustformers/llm), but these are direct bindings to llama.cpp and it doesnt have any dependencies.

**Comment by klosax** [comment]
Create a PR and it will probably be merged.

**Comment by mdrokz** [comment]
> Create a PR and it will probably be merged.

I have created a PR #2656 here
