### ISSUE TITLE
llama : add LoRA test to CI

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#2634]
Add a simple test to [ci/run.sh](https://github.com/ggerganov/llama.cpp/tree/master/ci) to make sure LoRA functionality is OK

**Comment by slaren** [comment]
To test the LoRA functionality, we could check the perplexity against the dataset of the LoRA. If it was applied correctly, I think it should be lower than the perplexity of the base model with the same dataset.

The problem with that is that I cannot find many LoRAs for openllama-v2. I could try to train one myself, but that may take a while. Finding LoRAs for llama2 should be easier. Would it be possible to use llama2 in the CI?

**Comment by ggerganov** [comment]
Yes, the CI currently uses OpenLLaMA v2 7B when running with CUDA, but we can easily switch this to LLaMA v2.
I think after #2398, the LoRA functionality will need some changes related to saving/loading of the data.

**Comment by slaren** [comment]
I decided to give a try to training a LoRA for openllama 3B, it was simple enough, and seems like that's required for the CPU tests anyway. In the future if we want to use LLaMa v2, maybe @TheBloke models could be an option? I have no idea of the legal implications there.

**Comment by TheBloke** [comment]
Belatedly just saw the ping, when this got closed. I think using any Llama2 model would be legally fine?

If you do want to use any of my repos and I can do anything to make that easier, let me know. For example I could make a DOI version of the Llama 2 GGUFs, so you have a static target that's guaranteed never to change.

Let me know.  I'll be starting to make GGUFs for previous GGML repos, with Llama 2 being top priority, tonight.
