### ISSUE TITLE
Unable to tokenize Chinese string prompt

### ISSUE THREAD

**Issue by xhy2008** [ggerganov/llama.cpp#2640]
Excuse me,I need some help.
I want to use the code to develop a GUI for the llama models.
I wrote the code like this to test the model:

     //init
     std::vector<llama_token> embd;
    const std::string init_prompt = " Below is an instruction that describes a task. Write a response that appropriately completes the request.";
    const auto inp_pfx = ::llama_tokenize(ctx, "\n\n### Instruction:\n\n", false);
    const auto inp_sfx = ::llama_tokenize(ctx, "\n\n### Response:\n\n", false);
    const auto init = llama_tokenize(ctx, init_prompt, true);
    UINT start = time(0);
    llama_eval(ctx, &init[0], init.size(), 0, 4);
    printf("startup time:%d\n", time(0) - start);
    std::string prompt;
    std::cin >> prompt;
    auto embd_inp = llama_tokenize(ctx, prompt, false);
    embd.insert(embd.begin(), inp_pfx.begin(), inp_pfx.end());
    embd.insert(embd.end(), embd_inp.begin(), embd_inp.end());
    embd.insert(embd.end(), inp_sfx.begin(), inp_sfx.end());
    UINT n_past = init.size();
    llama_eval(ctx, &embd[0], embd.size(), n_past, 4);
    n_past += embd.size();
    embd.clear();
    embd_inp.clear();
    llama_token first = sampling();
    printf("%s", llama_token_to_str(ctx, first));
    embd.push_back(first);
    n_past++;
    while (1)
    {
        if (llama_eval(ctx, &embd[0], embd.size(), n_past, 4))
        {
            fprintf(stderr, "%s : failed to eval\n", __func__);
            return 1;
        }
        llama_token id = sampling();
        embd.clear();
        embd.push_back(id);
        if (id == llama_token_eos())
            break;
        else
            printf("%s", llama_token_to_str(ctx, id));
        n_past++;
    }

And when I enter Chinese string,it produces messy output like this:    Prima鑷籧od鍖?Vor缃戣cod Blues .. BluesBas懈BL缃戣 Primadst Frovd Gener Blues Blues宸ュ湴鎾倂ik缇瞓r Maj瀹?Rec宸ュ 湴韬负鍖?Maz瀹挎棩鎶ラ亾鑲渻绛?restart韪?@闅嶣L椤垮鐨勫懗閬

When I enter English words,it can produce the correct output.

I used Chinese-Alpaca model 7B,and when I use the model in main.exe it can produce correct output.
I tried to convert the input string to UTF-8,but it didn't work.
I'm using VS2022 as the editor,running in Windows 10,cpu only.
I used openblas.
Is there anyone can help me correct my code?

**Comment by KerfuffleV2** [comment]
The first thing that occurs to me is to ask: What is `sampling()`, what's it doing? A lot of Chinese characters require multiple tokens to compose so something like an excessively high temperature can cause the sequence to get broken. In some cases that will be in the middle of constructing the UTF8 character and you'll just get 100% invalid output.

Another thing you can try is running the `main` example with `--verbose-prompt` so it will dump the list of token ids from the prompt. If you make your example code also dump the token ids it's feeding to the model, you can verify that there isn't something different with how the initial prompt is being processed.

希望我的建议能够帮你一点！

**Comment by xhy2008** [comment]
yes,they are different,and I can see my prompt wasn't tokenized correctly.
they are messy code,from the tokenized prompt to the output.
the sampling() function is copied from the code of main.exe. it will call llama_get_logits() and use temperature sampling to get the token that the model predicted.

**Comment by xhy2008** [comment]
I found another problem: the size of my tokenized prompt is 22 in main.exe,but it is 33 in my code.(the same model,prompt and commandline args)
and if i make my program show them,the chinese words are just messy codes,but the English ones are correct.
So i think the problem happens in the tokenizer part.

**Comment by KerfuffleV2** [comment]
Sorry, I guess I misunderstood your initial question. I thought you were saying output from the LLM was messed up rather than the initial prompt.

Does doing something like:

```c++
// std::string prompt;
// std::cin >> prompt;
std::string prompt = "我的车被一只老虎吃掉了！“;
```

help at all? (I'm not a C++ expert, I think just using the characters in a string literal would work but you might need to do something extra.)

**Comment by xhy2008** [comment]
you didn't misunderstand me,I mean that both the tokenized input and the output are messy codes.
I have already tried the way you said,but it didn't work too.

**Comment by klosax** [comment]
There are known problems with the current tokenizer. We have merged fixes to the tokenizer in the PR for the new file format which may solve your problems. https://github.com/ggerganov/llama.cpp/pull/2398

**Comment by xhy2008** [comment]
Thank you,i have little time to complete my project.Hope Work Fast.

**Comment by klosax** [comment]
Feel free to test the gguf branch if it solves your problems.

**Comment by zhangchn** [comment]
Probably an encoding issue.

In Windows 10, Chinese prompt in cmd.exe resulted in messy output. However, loading from text file input (-f) worked just fine if input file was saved as UTF-8 encoding.

**Comment by xhy2008** [comment]
I encode the prompt using UTF8,and it worked.
I need to get unicode input and turn it into utf8.
And I set /utf8 in the VS2022 project settings.
It worked.Thank you.
