### ISSUE TITLE
A100 GPU generate 11.30 tokens/s with llama.cpp

### ISSUE THREAD

**Issue by bigmover** [ggerganov/llama.cpp#2641]
I build it with cmake:
```
mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON
cmake --build . --config Release_
```
and convert llama-7b from hugging face with convert.py

but when I run it:
```
(myenv) [root@alywlcb-lingjun-gpu-0014 llama.cpp]# CUDA_VISIBLE_DEVICES=7 ./build/bin/main -m ./models/llama-7b/ggml-model-q4.bin -n 128
main: build = 992 (0919a0f)
main: seed  = 1692254344
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A100-SXM4-80GB, compute capability 8.0
llama.cpp: loading model from ./models/llama-7b/ggml-model-q4.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 5504
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 4343.77 MB (+  256.00 MB per state)
llama_model_load_internal: offloading 0 repeating layers to GPU
llama_model_load_internal: offloaded 0/35 layers to GPU
llama_model_load_internal: total VRAM used: 288 MB
llama_new_context_with_model: kv self size  =  256.00 MB

system_info: n_threads = 64 / 128 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 2019-07-13 05:00 - Tuesday July 16, 2019
The NHL released its list of all-star captains and alternates for the 2019 Honda NHL All-Star Game, which will be hosted by the San Jose Sharks at SAP Center in San Jose on Saturday, Jan. 25, 2020 (8 p.m., ET; FOX, SN, TVAS). The Honda NHL Fan Vote concluded with an overwhelming result for
llama_print_timings:        load time =   630.57 ms
llama_print_timings:      sample time =    67.33 ms /   128 runs   (    0.53 ms per token,  1901.00 tokens per second)
llama_print_timings: prompt eval time =    92.04 ms /     2 tokens (   46.02 ms per token,    21.73 tokens per second)
llama_print_timings:        eval time = 11235.86 ms /   127 runs   (   88.47 ms per token,    11.30 tokens per second)
llama_print_timings:       total time = 11426.94 ms
```

![image](https://github.com/ggerganov/llama.cpp/assets/26063296/491084b9-1bdd-43c4-9d2a-15f56d4fd73a)

the inference speed got 11.30 tokens /s. I can't figure  out what's the problems with it？ Is there somthing  I misuse?

**Comment by KerfuffleV2** [comment]
llama_model_load_internal: offloading 0 repeating layers to GPU
    llama_model_load_internal: offloaded 0/35 layers to GPU

You aren't offloading any layers to the GPU, so aside from the prompt (if it's big enough to use BLAS), the rest of the evaluation is happening on CPU.

Try setting `-ngl`  - you can just set it to a really high value like 1000 since all the layers are going to fit on an A1000. I think the real max value for a 7B model like you seem to be using is 38. You can also try setting `-mmq` to see if that increases performance once you're actually offloading layers.

**Comment by bigmover** [comment]
> ```
> llama_model_load_internal: offloading 0 repeating layers to GPU
> llama_model_load_internal: offloaded 0/35 layers to GPU
> ```
> 
> You aren't offloading any layers to the GPU, so aside from the prompt (if it's big enough to use BLAS), the rest of the evaluation is happening on CPU.
> 
> Try setting `-ngl` - you can just set it to a really high value like 1000 since all the layers are going to fit on an A1000. I think the real max value for a 7B model like you seem to be using is 38. You can also try setting `-mmq` to see if that increases performance once you're actually offloading layers.

Thank you for quick reply! That works by setting `-ngl`! Now it infer by 75.91 tokens per second! I'll to try whether to be able to increases performance.
 `(myenv) [root@alywlcb-lingjun-gpu-0014 llama.cpp]# CUDA_VISIBLE_DEVICES=7 ./build/bin/main -m ./models/llama-7b/ggml-model-q4.bin -n 128 -ngl 1000 -mmq
main: build = 992 (0919a0f)
main: seed  = 1692256552
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A100-SXM4-80GB, compute capability 8.0
llama.cpp: loading model from ./models/llama-7b/ggml-model-q4.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 5504
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  =  380.21 MB (+  256.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 288 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4508 MB
llama_new_context_with_model: kv self size  =  256.00 MB

system_info: n_threads = 64 / 128 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 2014-present (The Greatest Hits)
Guitar, Keyboards, Vocals (1987-present)
Aaron Kamin, born on June 25, 1968, is a founding member of the rock band Live. He plays guitar and keyboards and provides background vocals in concerts when not singing lead vocals for songs where Ed Kowalczyk sings backing vocals (which are rare). His playing can be heard on most of the group's records since its debut album Mental Jewelry, with his strong blues-rock
llama_print_timings:        load time =  1823.33 ms
llama_print_timings:      sample time =    64.23 ms /   128 runs   (    0.50 ms per token,  1992.71 tokens per second)
llama_print_timings: prompt eval time =   128.71 ms /     2 tokens (   64.36 ms per token,    15.54 tokens per second)
llama_print_timings:        eval time =  1673.02 ms /   127 runs   (   13.17 ms per token,    75.91 tokens per second)
llama_print_timings:       total time =  1893.95 ms
`

**Comment by bigmover** [comment]
> > ```
> > llama_model_load_internal: offloading 0 repeating layers to GPU
> > llama_model_load_internal: offloaded 0/35 layers to GPU
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You aren't offloading any layers to the GPU, so aside from the prompt (if it's big enough to use BLAS), the rest of the evaluation is happening on CPU.
> > Try setting `-ngl` - you can just set it to a really high value like 1000 since all the layers are going to fit on an A1000. I think the real max value for a 7B model like you seem to be using is 38. You can also try setting `-mmq` to see if that increases performance once you're actually offloading layers.
> 
> Thank you for quick reply! That works by setting `-ngl`! Now it infer by 75.91 tokens per second! I'll to try whether to be able to increases performance.
 ```
`(myenv) [root@alywlcb-lingjun-gpu-0014 llama.cpp]# CUDA_VISIBLE_DEVICES=7 ./build/bin/main -m ./models/llama-7b/ggml-model-q4.bin -n 128 -ngl 1000 -mmq main: build = 992 ([0919a0f](https://github.com/ggerganov/llama.cpp/commit/0919a0f73d95cfb93a1646a1d1741a0615fe2c5e)) main: seed = 1692256552 ggml_init_cublas: found 1 CUDA devices: Device 0: NVIDIA A100-SXM4-80GB, compute capability 8.0 llama.cpp: loading model from ./models/llama-7b/ggml-model-q4.bin llama_model_load_internal: format = ggjt v3 (latest) llama_model_load_internal: n_vocab = 32000 llama_model_load_internal: n_ctx = 512 llama_model_load_internal: n_embd = 4096 llama_model_load_internal: n_mult = 5504 llama_model_load_internal: n_head = 32 llama_model_load_internal: n_head_kv = 32 llama_model_load_internal: n_layer = 32 llama_model_load_internal: n_rot = 128 llama_model_load_internal: n_gqa = 1 llama_model_load_internal: rnorm_eps = 5.0e-06 llama_model_load_internal: n_ff = 11008 llama_model_load_internal: freq_base = 10000.0 llama_model_load_internal: freq_scale = 1 llama_model_load_internal: ftype = 3 (mostly Q4_1) llama_model_load_internal: model size = 7B llama_model_load_internal: ggml ctx size = 0.08 MB llama_model_load_internal: using CUDA for GPU acceleration llama_model_load_internal: mem required = 380.21 MB (+ 256.00 MB per state) llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 288 MB VRAM for the scratch buffer llama_model_load_internal: offloading 32 repeating layers to GPU llama_model_load_internal: offloading non-repeating layers to GPU llama_model_load_internal: offloading v cache to GPU llama_model_load_internal: offloading k cache to GPU llama_model_load_internal: offloaded 35/35 layers to GPU llama_model_load_internal: total VRAM used: 4508 MB llama_new_context_with_model: kv self size = 256.00 MB
> 
> system_info: n_threads = 64 / 128 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000 generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0
> 
> 2014-present (The Greatest Hits) Guitar, Keyboards, Vocals (1987-present) Aaron Kamin, born on June 25, 1968, is a founding member of the rock band Live. He plays guitar and keyboards and provides background vocals in concerts when not singing lead vocals for songs where Ed Kowalczyk sings backing vocals (which are rare). His playing can be heard on most of the group's records since its debut album Mental Jewelry, with his strong blues-rock llama_print_timings: load time = 1823.33 ms llama_print_timings: sample time = 64.23 ms / 128 runs ( 0.50 ms per token, 1992.71 tokens per second) llama_print_timings: prompt eval time = 128.71 ms / 2 tokens ( 64.36 ms per token, 15.54 tokens per second) llama_print_timings: eval time = 1673.02 ms / 127 runs ( 13.17 ms per token, 75.91 tokens per second) llama_print_timings: total time = 1893.95 ms `
```

**Comment by bigmover** [comment]
> ```
> llama_model_load_internal: offloading 0 repeating layers to GPU
> llama_model_load_internal: offloaded 0/35 layers to GPU
> ```
> 
> You aren't offloading any layers to the GPU, so aside from the prompt (if it's big enough to use BLAS), the rest of the evaluation is happening on CPU.
> 
> Try setting `-ngl` - you can just set it to a really high value like 1000 since all the layers are going to fit on an A1000. I think the real max value for a 7B model like you seem to be using is 38. You can also try setting `-mmq` to see if that increases performance once you're actually offloading layers.

Thank you for quick reply! That works by setting -ngl! Now it infer by 75.91 tokens per second! I'll to try whether to be able to increases performance.

```
(myenv) [root@alywlcb-lingjun-gpu-0014 llama.cpp]# CUDA_VISIBLE_DEVICES=7 ./build/bin/main -m ./models/llama-7b/ggml-model-q4.bin -n 128 -ngl 1000 -mmq
main: build = 992 (0919a0f)
main: seed  = 1692256552
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A100-SXM4-80GB, compute capability 8.0
llama.cpp: loading model from ./models/llama-7b/ggml-model-q4.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 5504
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  =  380.21 MB (+  256.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 288 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4508 MB
llama_new_context_with_model: kv self size  =  256.00 MB

system_info: n_threads = 64 / 128 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 2014-present (The Greatest Hits)
Guitar, Keyboards, Vocals (1987-present)
Aaron Kamin, born on June 25, 1968, is a founding member of the rock band Live. He plays guitar and keyboards and provides background vocals in concerts when not singing lead vocals for songs where Ed Kowalczyk sings backing vocals (which are rare). His playing can be heard on most of the group's records since its debut album Mental Jewelry, with his strong blues-rock
llama_print_timings:        load time =  1823.33 ms
llama_print_timings:      sample time =    64.23 ms /   128 runs   (    0.50 ms per token,  1992.71 tokens per second)
llama_print_timings: prompt eval time =   128.71 ms /     2 tokens (   64.36 ms per token,    15.54 tokens per second)
llama_print_timings:        eval time =  1673.02 ms /   127 runs   (   13.17 ms per token,    75.91 tokens per second)
llama_print_timings:       total time =  1893.95 ms
```
