### ISSUE TITLE
[Feature] I am wondering whether there will be a huge crowd expecting to see some rest APIs for these projects as well.

### ISSUE THREAD

**Issue by vithushanms** [ggerganov/llama.cpp#2653]
I am happy to contribute developing a rest api set for the main.cpp. please let me know your thoughts.

**Comment by WeirdConstructor** [comment]
There already is something like that in `examples/server/`, as far as I understood. And `koboldcpp` closely follows the progress of llama.cpp and implements another HTTP API.

**Comment by vithushanms** [comment]
awesome. thanks for letting know
