### ISSUE TITLE
wierd ram behavior 

### ISSUE THREAD

**Issue by clemens98** [ggerganov/llama.cpp#2662]
# Expected Behavior
wehn i launched a model it used to top up my ram close to capacity while taking a while to load up because HDD

# Current Behavior

it dosent anymore it jumps straight from ram 9.0 gb used to 13.5gb which is very short for the 18.4gb model i am trying to run 
--mlock dosent seam to change anything either 
atlest llama 30b q4.0 runs almost instantly now 

vicuna on the other hand starts extremly slow and then either defaults on pressing n/ or just write out the prompt file (literally anything in the promt file like if someone just pressed control a control c and v)  and then do nothing at all 

and i dont know if the issue is with the model ,the promt or llama.cpp

# Environment and Context
it says in the resource monitor 9.0 gb memory usage of 33.6gb(very strange given i only have 32gb ram total)    swap is 262kb of 2.1gb.  and 26.9gb cache 
everything except the memory usage stays the same wen i run the model 

clblast --n-gpu-layers 0

**Comment by SlyEcho** [comment]
What is the issue you have, that it's too fast?

This is normal behaviour after memory-mapping was added in March.

https://github.com/ggerganov/llama.cpp/discussions/638 ← more discussion

**Comment by clemens98** [comment]
That i don't know what's going on 
And we're the so called cache is 
Shouldn't -mlock remove the Memory mapping

**Comment by SlyEcho** [comment]
`--mlock` is still memory-mapped files, it just alters the way it works which makes it better on some system (like macOS).

If you want to turn off the mapping use `--no-mmap`

**Comment by clemens98** [comment]
ty very much for --no-mmap

**Comment by clemens98** [comment]
> `--mlock` is still memory-mapped files, it just alters the way it works which makes it better on some system (like macOS).
> 
> If you want to turn off the mapping use `--no-mmap`

thank you very much for --no-mmap. some other issue i found is its not deleting the old data with the mapping it will just continue to map the cache and even swapping even if the old terminal has been closed
