### ISSUE TITLE
[ISSUE] Disable printing of prompt before generation

### ISSUE THREAD

**Issue by YerongLi** [ggerganov/llama.cpp#2664]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
When I prompt llama with "Who is Elon Musk?"
I want to get the genertaion without prompt:
```
Elon Musk is a South African-born American business magnate, investor and engineer. He is the founder, CEO and CTO of SpaceX; co-founder, CEO and product architect of Tesla Motors; and co-founder and chairman of SolarCity. In December 2015, he was ranked 40th on Forbes' list of The World_s Most Powerful People.
Musk has stated that the goals of SpaceX are to reduce space transportation costs and make humanity a multiplanet species by colonizing Mars. He has
```
Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do.

# Current Behavior
With the following command prompt is printed before generation, I want to print the generation directly without prompt, what should I do (without   `--verbose-prompt`)
```
./main -m $SCRATCH/.cache/pyllama/7B/ggml-model-q4_0.bin -p "Who is Elon Musk?" -t 1 -n 128 --temp 0.1 --top-p 0.90  -ngl 83
```
```
 Who is Elon Musk?
Elon Musk is a South African-born American business magnate, investor and engineer. He is the founder, CEO and CTO of SpaceX; co-founder, CEO and product architect of Tesla Motors; and co-founder and chairman of SolarCity. In December 2015, he was ranked 40th on Forbes' list of The World_s Most Powerful People.
Musk has stated that the goals of SpaceX are to reduce space transportation costs and make humanity a multiplanet species by colonizing Mars. He has
```

# Steps to Reproduce

1. step 1
```
./main -m $SCRATCH/.cache/pyllama/7B/ggml-model-q4_0.bin -p "Who is Elon Musk?" -t 1 -n 128 --temp 0.1 --top-p 0.90  -ngl 83
```

**Comment by JackJollimore** [comment]
Hi, I don't understand your intention, so please answer this question: 

Why not load the generation from a text file? i.e. save `Elon Musk is a South African-born American business magnate, investor and engineer. He is the founder, CEO and CTO of SpaceX; co-founder, CEO and product architect of Tesla Motors; and co-founder and chairman of SolarCity. In December 2015, he was ranked 40th on Forbes' list of The World_s Most Powerful People.
Musk has stated that the goals of SpaceX are to reduce space transportation costs and make humanity a multiplanet species by colonizing Mars.` to Elon.txt then load it from ./main with `-f ~/storage/Downloads/Elon.txt`

What do you expect llama.cpp to do after running it with the Elon description?

**Comment by YerongLi** [comment]
I want to read the stdout from python.subprocess.
> Hi, I don't understand your intention, so please answer this question:
> 
> Why not load the generation from a text file? i.e. save `Elon Musk is a South African-born American business magnate, investor and engineer. He is the founder, CEO and CTO of SpaceX; co-founder, CEO and product architect of Tesla Motors; and co-founder and chairman of SolarCity. In December 2015, he was ranked 40th on Forbes' list of The World_s Most Powerful People. Musk has stated that the goals of SpaceX are to reduce space transportation costs and make humanity a multiplanet species by colonizing Mars.` to Elon.txt then load it from ./main with `-f ~/storage/Downloads/Elon.txt`
> 
> What do you expect llama.cpp to do after running it with the Elon description?

**Comment by YerongLi** [comment]
I want to remove `Who is Elon Musk?` in the first line. That is a encoded-then-decoded prompt

```
 Who is Elon Musk?
Elon Musk is a South African-born American business magnate
```

> Hi, I don't understand your intention, so please answer this question:
> 
> Why not load the generation from a text file? i.e. save `Elon Musk is a South African-born American business magnate, investor and engineer. He is the founder, CEO and CTO of SpaceX; co-founder, CEO and product architect of Tesla Motors; and co-founder and chairman of SolarCity. In December 2015, he was ranked 40th on Forbes' list of The World_s Most Powerful People. Musk has stated that the goals of SpaceX are to reduce space transportation costs and make humanity a multiplanet species by colonizing Mars.` to Elon.txt then load it from ./main with `-f ~/storage/Downloads/Elon.txt`
> 
> What do you expect llama.cpp to do after running it with the Elon description?

**Comment by JackJollimore** [comment]
OK, I get it - thanks for explaining. You want to prompt llama.cpp with your question, have the console exclude the question and only print Elons description.


As far as I know, llama.cpp cannot exclude the initial prompt from the console. Maybe @SlyEcho can confirm?

**Comment by YerongLi** [comment]
Yeah, in principle, maybe that is the case for **completion**. Let's wait for confirmation.

I find a work around to duplicate the user prompt that has been encoded and then decoded, and enclose it within <INP> </INP> in the output string. This will enable me to distinguish the section that constitutes the prompt, namely, my question.

**Comment by SlyEcho** [comment]
The basic solution is to either remove the amount of characters that the prompt contains from the output, or make some kind of separator like newlines or something else to search for and cut the result from there. Be aware that llama.cpp adds a space in front of the prompt always so it's a good idea to just trim the output as well.

The other option is to use the server, that way you get just the generated content as output.

**Comment by atsepkov** [comment]
Any chance to revisit this with the same solution llamafile implemented in their fork (https://github.com/Mozilla-Ocho/llamafile/commit/28d3160145e7595f84a9d7ec7f24e11ba153f796)?

It seems like a relatively small lift for a useful feature. I understand that we can truncate the characters corresponding to original input after the fact, just seems like an inefficient way of doing it when we can avoid parsing that extra context altogether.

**Comment by taha-y-merghani** [comment]
@jart I think you got the green light for making a PR if you haven't already! I would really like your solution to be added to the code base.

**Comment by bakkot** [comment]
In case anyone else ends up here, this was done in https://github.com/ggerganov/llama.cpp/pull/4541 as `--no-display-prompt`.
