### ISSUE TITLE
is there a way to train the llama? using cpu etc.

### ISSUE THREAD

**Issue by kolinfluence** [ggerganov/llama.cpp#2666]
is there a way to train the llama? using cpu etc. how to train the bin file?

**Comment by JackJollimore** [comment]
Yep, it's quite resource intensive. Here's the [README](https://github.com/ggerganov/llama.cpp/blob/1f0bccb27929e261744c979bc75114955da49e98/examples/train-text-from-scratch/README.md)  on train-text-from-scratch.

I don't have the hardware to run it, but here's a comment from someone that did: https://github.com/ggerganov/llama.cpp/issues/1853#issuecomment-1601028101

**Comment by SlyEcho** [comment]
There is a way as @JackJollimore said.
