### ISSUE TITLE
Android instructions failure 

### ISSUE THREAD

**Issue by Jkintree2** [ggerganov/llama.cpp#2673]
The following is what happened when I tried to install the essential packages for the playstore Termux on a brand new Oneplus 11 5G smartphone using the Android section in the README.md instructions at github.com/ggerganov/llama.cpp

$ pkg install clang wget git cmake
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml/: ok
[*] https://termux.mentality.rip/termux-packages-24: bad
Picking mirror: https://grimler.se/termux-packages-24
Get:1 https://grimler.se/termux-packages-24 stable InRelease [14.0 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  404  Not Found
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Get:6 https://grimler.se/termux-packages-24 stable/main aarch64 Packages [491 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by JackJollimore** [comment]
> The following is what happened when I tried to install the essential packages for the playstore Termux
> 

Hi, the README links to https://termux.dev/ which show Github & Fdroid as a source for Termux.

Playstore Termux is outdated, and not maintained, so that's the problem.

**Comment by Jkintree2** [comment]
Thank you.
