### ISSUE TITLE
Compilation with CLBlast in onboard graphics

### ISSUE THREAD

**Issue by SilvaRaulEnriqueCJM** [ggerganov/llama.cpp#2676]
In order to compile with CLBlast:
make LLAMA_CLBLAST=1

say error:

g++ --shared -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CLBLAST -I/usr/local/include -I/home/raul/Desktop/Librerias/OpenCL-SDK/install/include  examples/embd-input/embd-input-lib.cpp ggml.o llama.o common.o k_quants.o ggml-opencl.o ggml-alloc.o -o libembdinput.so -L/usr/local/lib -lclblast -L/home/raul/Desktop/Librerias/OpenCL-SDK/install/lib -lOpenCL                  
/usr/bin/ld: /usr/local/lib/libclblast.a(xaxpy.cpp.o): warning: relocation against `_ZN7clblast8database11XaxpyDoubleE' in read-only section `.text.startup'                
/usr/bin/ld: /usr/local/lib/libclblast.a(xdot.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTSZN7clblast6BufferISt7complexIdEEC4ERKNS_7ContextENS_12BufferAccessEmEUlPP7_cl_memE_' can not be used when making a shared object; recompile con -fPIC                                                                                                
/usr/bin/ld: falló el enlace final: bad value                                                                                                                               
collect2: error: ld returned 1 exit status                                                                                                                                  
make: *** [Makefile:382: libembdinput.so] Error 1    

¿What is the problem?

**Comment by SlyEcho** [comment]
You need to compile CLBlast with `-fPIC`

Add it to `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` (in the file CMakeCache.txt file in the build directory of CLBlast). Recompile it and reinstall it.

**Comment by SilvaRaulEnriqueCJM** [comment]
Now CLBlast compile in AMD with CuDA and run fast. Thakyou.

But if compile in Intel (without graphics card), no errors in compilation time, but in runtime of main say:

main: build = 1015 (226255b)
main: seed  = 1692672569
ggml_opencl: clGetPlatformIDs(NPLAT, platform_ids, &n_platforms) error -1001 at ggml-opencl.cpp:965

**Comment by SilvaRaulEnriqueCJM** [comment]
And in another Intel Core I3 (without graphics card), in runtime of main say:

main: build = 1018 (8e4364f)
main: seed  = 1692703705
ggml_opencl: selecting platform: 'Portable Computing Language'
ggml_opencl: selecting device: 'pthread-haswell-Intel(R) Core(TM) i3-4100M CPU @ 2.50GHz'
ggml_opencl: warning, not a GPU: 'pthread-haswell-Intel(R) Core(TM) i3-4100M CPU @ 2.50GHz'.
ggml_opencl: device FP16 support: false
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /media/raul/f3a54992-da3d-4e46-93f6-e84c1180f25d/models/TheBloke/llama-2-7b-chat.ggmlv3.q3_K_L.bin

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/media/raul/f3a54992-da3d-4e46-93f6-e84c1180f25d/models/TheBloke/llama-2-7b-chat.ggmlv3.q3_K_L.bin'
main: error: unable to load model

**Comment by SilvaRaulEnriqueCJM** [comment]
The parameters are:
-m /media/raul/f3a54992-da3d-4e46-93f6-e84c1180f25d/models/TheBloke/llama-2-7b-chat.ggmlv3.q3_K_L.bin -ngl 43 -i --prompt "Sabiendo que hay un celular azul sobre la mesa, ¿cuál letra corresponde a la respuesta correcta?: a) hay un celular azul sobre la mesa, b) hay un celular marrón sobre la mesa, c) hay un celular negro sobre la mesa, d) hay un celular gris sobre la mesa, e) hay un celular verde sobre la mesea. Respuesta: La letra que corresponde a la respuesta correcta es "

**Comment by SlyEcho** [comment]
Model format has changed, you need to convert files or download new files: #2398
