### ISSUE TITLE
Finetuning tokenizer.model missing

### ISSUE THREAD

**Issue by l0d0v1c** [ggerganov/llama.cpp#2679]
I tried to finetune llama2 using https://towardsdatascience.com/fine-tune-your-own-llama-2-model-in-a-colab-notebook-df9823a04a32 . It works but when I save the finetuned model using:

base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map=device_map,
)
model = PeftModel.from_pretrained(base_model, new_model)
model = model.merge_and_unload()

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right
model.save_pretrained("sample_data/")
tokenizer.save_pretrained("sample_data/")

it produces 3 json files for tokenizer.('sample_data/tokenizer_config.json','sample_data/special_tokens_map.json', 'sample_data/tokenizer.json')

then when I run python convert.py I get an error because a tokenizer.model file is required. Is there a converter doing that?

**Comment by Igoorx** [comment]
Just use the LLaMA 2 `tokenizer.model`: https://huggingface.co/TheBloke/Llama-2-7B-fp16/resolve/main/tokenizer.model
