### ISSUE TITLE
Analyze file

### ISSUE THREAD

**Issue by kirkog86** [ggerganov/llama.cpp#2693]
Is it possible to feed the "./main" app with let's say bash script asking to find errors or add any remarks?

**Comment by klosax** [comment]
I guess you will have to use an Instruct fine tuned model file. And using the `-f` parameter to feed the prompt as a file. The file would look something like this (using the alpaca instruct format):
```
### Instruction:
Find and report on all errors in the bash script provided as input.
### Input:
<contents of the bash script>
### Response:

```
