### ISSUE TITLE
The Best combinated parameters now is:

### ISSUE THREAD

**Issue by SilvaRaulEnriqueCJM** [ggerganov/llama.cpp#2696]
**The idea of this post is construct and maintain colaborativaly a complete and actualizated best orders ranking list table to compile and executate, considering best models results for the more very long context with efectively complety coherent response, by example:**

**For NVidia 3090 (with CUDA and 24 GB RAM), for now the best orders are:**
-  **compile:**
    make LLAMA_CUBLAS=1

- **run main example:**

   ./main \\
-m models/TheBloke/llama-2-13b-chat.ggmlv3.q8_0.bin \\
-ngl 254 \\
-c 4096 \\
-gqa 8 \\
--reverse-prompt "User:" \\
--file chat_dies_User_Assistant.txt \\
--in-prefix ' ' "$@"

   or?

   ./main \\
-m models/s3nh/longchat-7b-v1.5-32k.ggmlv3.q8_0.bin \\
-ngl 254 \\
-c 32768 \\
--rope-scale 8 \\
--reverse-prompt "User:" \\
--file chat_dies_User_Assistant.txt \\
--in-prefix ' ' "$@"

- **fine tuning? train-text-from scratch:**

   ./train-text-from-scratch \\
--vocab-model ServidorIA/models/models/TheBloke/llama-2-13b-chat.ggmlv3.q8_0.bin \\
--ctx 64 \\
--embd 256 \\
--head 8 \\
--layer 16 \\
--checkpoint-out chk-Ultimas_Acordadas_y_Circulares-256x16.bin \\
--model-out ggml-Ultimas_Acordadas_y_Circulares-256x16-f32.bin \\
--train-data "Ultimas_Acordadas_y_Circulares.txt" \\
-t 4 \\
-b 8 \\
-n 32 \\
--seed 1 \\
--adam-iter 16 \\
--print-details-interval 0 \\
--predict 16 \\
--use-flash \\
--mem-compute 8

or?

   ./train-text-from-scratch \\
--vocab-model ServidorIA/models/s3nh/longchat-7b-v1.5-32k.ggmlv3.q8_0.bin \\
--ctx 64 \\
--embd 256 \\
--head 8 \\
--layer 16 \\
--checkpoint-out chk-Ultimas_Acordadas_y_Circulares-256x16.bin \\
--model-out ggml-Ultimas_Acordadas_y_Circulares-256x16-f32.bin \\
--train-data "Ultimas_Acordadas_y_Circulares.txt" \\
-t 4 \\
-b 8 \\
-n 32 \\
--seed 1 \\
--adam-iter 16 \\
--print-details-interval 0 \\
--predict 16 \\
--use-flash \\
--mem-compute 8

**Note: models TheBloke, and s3nh are in https://huggingface.co/**

**¿There is the best parameters or considerer _"now"_ one best?, ¿and for another hardware configuration?**

**Comment by JackJollimore** [comment]
This topic is more suitable for [discussion](https://github.com/ggerganov/llama.cpp/discussions) as there's no technical issue or enhancement here.

[Heads up](https://github.com/ggerganov/llama.cpp/issues/2726#issuecomment-1689093731) that model saving in training is temporarily disabled.
