### ISSUE TITLE
Silently failing ggml to gguf conversion

### ISSUE THREAD

**Issue by staviq** [ggerganov/llama.cpp#2697]
@KerfuffleV2 
#2398 

`convert-llama-ggmlv3-to-gguf.py` produces a model without errors, which causes unexpected behaviour in `main` and `server`

I believe the model is [this one](https://huggingface.co/TheBloke/MythoMax-L2-13B-GGML/resolve/main/mythomax-l2-13b.ggmlv3.q5_K_M.bin) from [here](https://huggingface.co/TheBloke/MythoMax-L2-13B-GGML)

Source model md5 e87520b6393ea5ed6f9419e9fe6aba96  mythomax-l2-13b.ggmlv3.q5_K_M.bin
Resulting model md5 ce6cf60b707cb21fc04ac0e6cf6a147e  mythomax-l2-13b.ggmlv3.q5_K_M.gguf

Exact command with output:
```
python3 convert-llama-ggmlv3-to-gguf.py -i /storage/models/mythomax-l2-13b.ggmlv3.q5_K_M.bin -o /storage/models/mythomax-l2-13b.ggmlv3.q5_K_M.gguf --eps 1e-5 -c 4096
* Using config: Namespace(input=PosixPath('/storage/models/mythomax-l2-13b.ggmlv3.q5_K_M.bin'), output=PosixPath('/storage/models/mythomax-l2-13b.ggmlv3.q5_K_M.gguf'), name=None, desc=None, gqa=1, eps='1e-5', context_length=4096, model_metadata_dir=None, vocab_dir=None, vocabtype='spm')

=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

* Scanning GGML input file
* GGML model hyperparameters: <Hyperparameters: n_vocab=32000, n_embd=5120, n_mult=6912, n_head=40, n_layer=40, n_rot=128, n_ff=13824, ftype=17>

=== WARNING === Special tokens may not be converted correctly. Use --model-metadata-dir if possible === WARNING ===

* Preparing to save GGUF file
* Adding model parameters and KV items
* Adding 32000 vocab item(s)
* Adding 363 tensor(s)
    gguf: write header
    gguf: write metadata
    gguf: write tensors
* Successful completion. Output saved to: /storage/models/mythomax-l2-13b.ggmlv3.q5_K_M.gguf
```

**Comment by KerfuffleV2** [comment]
Thank you. Can you please try the fix here? https://github.com/ggerganov/llama.cpp/pull/2698

Just change line 240 of the conversion script from

```python
vbytes = bytes(f'<0x{hv}>', encoding = 'UTF-8')
```

to

```python
vbytes = bytes(f'<0x{vbytes[0]:02X}>', encoding = 'UTF-8')
```

**Comment by staviq** [comment]
> ```python
> vbytes = bytes(f'<0x{vbytes[0]:02X}>', encoding = 'UTF-8')
> ```

At first glance, this appears to have fixed it, tested with server:

```
User: hi
Llama: Hello there! How can I assist you today?
User: Tell me a joke
Llama: Why did the tomato turn red? Because it saw the salad dressing!
User: Another one
Llama: What do you call a fake noodle? An impasta!
```

Resultant model md5 after fix: fcf16d638dc53d4bec7e827ee71192de  mythomax-l2-13b.ggmlv3.q5_K_M.gguf

**Comment by KerfuffleV2** [comment]
Great, thanks for the repeat and testing! I will try to get the fix merged as soon as possible.

**Comment by JackJollimore** [comment]
Hmm, is it possible to convert ggml to gguf on mobile? or are you converting on PC?

**Comment by KerfuffleV2** [comment]
> Hmm, is it possible to convert ggml to gguf on mobile?

I think they just meant they were currently not at their computer and posting from mobile.

But you can set up a Unix environment on Android phones pretty easily and run stuff like Python scripts, compilers. You can even compile/run llama.cpp on mobile device, though it's not gonna be super fast.

**Comment by staviq** [comment]
> Hmm, is it possible to convert ggml to gguf on mobile? or are you converting on PC?

> I think they just meant they were currently not at their computer and posting from mobile.

Pretty much yes, to all of that.

I was momentarily not in my house. You could actually run any part of llama.cpp on Android at least. If you have Termux or equivalent, you get plain old Linux shell and all that comes with it.

**Comment by KerfuffleV2** [comment]
We should be good now. Please let me know if you have any further issues with converted models!

**Comment by JackJollimore** [comment]
> I think they just meant they were currently not at their computer and posting from mobile.
> 

Yeah, probably. 
> But you can set up a Unix environment on Android phones pretty easily and run stuff like Python scripts, compilers. You can even compile/run llama.cpp on mobile device, though it's not gonna be super fast.

I run llama.cpp in termux daily. I've got python/numpy installed, but got some strange error that doesn't recognise numpy:
```
~/llama.cpp (master)> python3 convert-llama-ggmlv3-to-gguf.py -i ~/vicuna-7b-v1.5.ggmlv3.q4_0.bin -o ~/vicuna-7b-v1.5.ggmlv3.q4_0.gguf --eps 1e-5 -c 4096
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

It's not a big deal 'cuz I don't have a PC so it's probably too intensive for my little Android to handle.

I'll be patient ❤️

**Comment by Cebtenzzre** [comment]
@JackJollimore did you try `pkg install python-numpy`?

**Comment by JackJollimore** [comment]
> did you try `pkg install python-numpy`? Or did you use pip? What does `which python3` show?

Ah, `python-numpy` does the trick! It started converting. Good call.

I'm downloading updated llama.cpp and I'll again shortly to see if I can actually finish a conversion.

**Comment by JackJollimore** [comment]
Recently. I'm getting an error on latest build `main: build = 1096 (103cfaf)`

I want to convert `ggmlv3` to `gguf`, here's my attempt: ` python3 convert-llama-ggmlv3-to-gguf.py -i ~/Pygmalion-Vicuna-1.1-7b.ggmlv3.Q4_0.bin -o ~/Pygmalion-Vicuna-1.1-7b.Q4_0.gguf -m ~/storage/downloads/Pyg-Vic`

Error:
```
Traceback (most recent call last):                           
File "/data/data/com.termux/files/home/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 7, in <module>                  
import gguf                                            
ModuleNotFoundError: No module named 'gguf'
```

![Screenshot_20230828_022950](https://github.com/ggerganov/llama.cpp/assets/130917767/bd4e2de0-a131-4f44-9b9a-11c63fff4294)
`llama.cpp` has a `gguf` executable as shown in the image. The error occurs even wthout arguments after `./convert-llama-ggmlv3-to-gguf.py.

**Comment by Cebtenzzre** [comment]
@JackJollimore You need to install the gguf package for python. You can `cd gguf-py && pip install -e .` to install it from the repo, or `pip install gguf` to install it from the internet.

I'm not sure if this is documented anywhere.

**Comment by JackJollimore** [comment]
>  or `pip install gguf` to install it from the internet.
> 

Right again @Cebtenzzre, `pip install gguf`, allowed me to convert. 

Thank you.
