### ISSUE TITLE
A typo in readme?

### ISSUE THREAD

**Issue by avada-z** [ggerganov/llama.cpp#271]
<html><body>
<h3 tabindex="-1" dir="auto">Memory/Disk Requirements</h3>
<p dir="auto">As the models are currently fully loaded into memory, you will need adequate disk space to save them
and sufficient RAM to load them. At the moment, memory and disk requirements are the same.</p>

model | original size | quantized size (4-bit)
-- | -- | --
7B | 13 GB | 3.9 GB
15B | 24 GB | 7.8 GB
30B | 60 GB | 19.5 GB
65B | 120 GB | 38.5 GB

</body>
</html>

Isn't it 13B and not 15B?

**Comment by prusnak** [comment]
Yes, that's a typo. Fix in https://github.com/ggerganov/llama.cpp/pull/272
