### ISSUE TITLE
Error converting GGML to GGUF

### ISSUE THREAD

**Issue by IgnacioFDM** [ggerganov/llama.cpp#2715]
I'm on commit 519c981f8b65ee6c87c2965539685ced0a17223b and when I run

`python convert-llama-ggmlv3-to-gguf.py -i ./upstage-llama-2-70b-instruct-v2.ggmlv3.q3_K_M.bin -o ./output.bin -m ./upstage --gqa 8 -c 4096`

I get

```* Using config: Namespace(input=WindowsPath('upstage-llama-2-70b-instruct-v2.ggmlv3.q3_K_M.bin'), output=WindowsPath('output.bin'), name=None, desc=None, gqa=8, eps='5.0e-06', context_length=4096, model_metadata_dir=WindowsPath('upstage'), vocab_dir=None, vocabtype='spm')

=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

* Scanning GGML input file
C:\llamacppgit\convert-llama-ggmlv3-to-gguf.py:96: RuntimeWarning: overflow encountered in long_scalars
  n_bytes = (n_elems * tysize) // blksize
Traceback (most recent call last):
  File "C:\llamacppgit\convert-llama-ggmlv3-to-gguf.py", line 333, in <module>
    main()
  File "C:\llamacppgit\convert-llama-ggmlv3-to-gguf.py", line 318, in main
    offset = model.load(data, 0)
  File "C:\llamacppgit\convert-llama-ggmlv3-to-gguf.py", line 125, in load
    offset += tensor.load(data, offset)
  File "C:\llamacppgit\convert-llama-ggmlv3-to-gguf.py", line 82, in load
    assert n_dims >= 0 and n_dims <= 4, f'Invalid tensor dimensions {n_dims}'
AssertionError: Invalid tensor dimensions 1862288276
```

**Comment by klosax** [comment]
Tagging @KerfuffleV2

**Comment by KerfuffleV2** [comment]
@IgnacioFDM I downloaded the model and can't reproduce this: https://huggingface.co/TheBloke/Upstage-Llama-2-70B-instruct-v2-GGML/blob/main/upstage-llama-2-70b-instruct-v2.ggmlv3.q3_K_M.bin

Please verify your copy matches the SHA256 there.

**Comment by IgnacioFDM** [comment]
The SHA matches. Also tried with another model (same model but Q2_K) and I get the same error. Python 3.10.9 on Windows (Anaconda). I'll try WSL2 now to see if that fixes it.

**Comment by IgnacioFDM** [comment]
Seems to be working under WSL2, so it's likely a Windows specific bug

**Comment by KerfuffleV2** [comment]
@IgnacioFDM 

Yeah, somehow Windows is using a 32bit value here but that's specifically not how Python 3 is 
supposed to work so I'm not sure what to do.

Can you try something out for me? Run this small script from the non-WSL Python version:

```python
def main():
    import warnings
    warnings.filterwarnings('error')
    try:
        testy = (1 << 31) * (1 << 31)
        assert testy == 4611686018427387904, 'Oh no'
    except OverflowError:
        print('Failed')
        return
    print('Unexpectedly worked')

main()
```

If that does what I expected, I can at least add a test to warn users and bail out with a less confusing error.

**Comment by IgnacioFDM** [comment]
I get Unexpectedly worked

**Comment by KerfuffleV2** [comment]
Well, that's unexpected. :( Not sure what to do then. I think I can turn the warning into an error at least and make it crash closer to the point where the issue actually occurred. Thanks for taking the time to test it!

**Comment by IgnacioFDM** [comment]
Most people converting are going to use Linux or WSL2 so it being broken on Windows is no biggie I think.

**Comment by KerfuffleV2** [comment]
> Most people converting are going to use Linux or WSL2 so it being broken on Windows is no biggie I think.

If you have time, could you possibly try the changes in #2725 - this should at least produce a better error message. I'd like to at least give people an indication of what went wrong and how to fix it.

**Comment by IgnacioFDM** [comment]
Some anon suggested this change, it seems to be running right now. I'll test it if the resulting model works fine.

`n_bytes = np.int64(np.int64(n_elems) * np.int64(tysize)) // np.int64(blksize)`

**Comment by IgnacioFDM** [comment]
I can confirm that with
`n_bytes = np.int64(np.int64(n_elems) * np.int64(tysize)) // np.int64(blksize)`

It runs on windows, and the resulting model is an exact SHA256 match with the one generated on Linux.

**Comment by Rotatingxenomorph** [comment]
Doesn't seem to work on llama-2-70b-chat.gguf.q6_K.bin

error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  8192,  8192, got  8192,  1024,     1[\(Cllama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'K:\aimodels\llama-2-70b-chat.gguf.q6_K.bin'
main: error: unable to load model

**Comment by IgnacioFDM** [comment]
Did you set --gqa 8?

**Comment by Rotatingxenomorph** [comment]
> 

I forgot to set the --gqa and context and got it to work after, so the converted model seems okay but llamacpp kind of hangs with it more than half the time. I'm not even sure how I'd even go about reporting that issue.

**Comment by IgnacioFDM** [comment]
Probably best to open a new issue

**Comment by sachinspanicker** [comment]
I am unable to convert and getting this error. Any info appreciated. - 

llama.cpp % python convert-llama-ggmlv3-to-gguf.py -i llama-7b.ggmlv3.q4_1.bin -o ./output.bin -m ./upstage --gqa 8 -c 4096
* Using config: Namespace(input=PosixPath('llama-7b.ggmlv3.q4_1.bin'), output=PosixPath('output.bin'), name=None, desc=None, gqa=8, eps='5.0e-06', context_length=4096, model_metadata_dir=PosixPath('upstage'), vocab_dir=None, vocabtype='spm')

=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

* Scanning GGML input file
* GGML model hyperparameters: <Hyperparameters: n_vocab=32000, n_embd=4096, n_mult=256, n_head=32, n_layer=32, n_rot=128, n_ff=11008, ftype=3>
Traceback (most recent call last):
  File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 345, in <module>
    main()
  File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 334, in main
    (params_override, vocab_override) = handle_metadata(cfg, model.hyperparameters)
  File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 286, in handle_metadata
    assert cfg.model_metadata_dir.is_dir(), 'Metadata dir is not a directory'
AssertionError: Metadata dir is not a directory

**Comment by KerfuffleV2** [comment]
@sachinspanicker 

    AssertionError: Metadata dir is not a directory

What you specify with `-m` needs to be a directory with `config.json`, `tokenizer.model`, etc in it. I believe a symlink to a directory should also work there.

Verify that `./upstage` exists from where you're running `convert.py` and is actually a directory.
