### ISSUE TITLE
tokenizer is converting spaces to ▁ (U+2581)

### ISSUE THREAD

**Issue by jxy** [ggerganov/llama.cpp#2743]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Decoding the token 1678 to three spaces.

# Current Behavior

Token 1678 gets decoded in to " ▁▁" (U+0020 U+2581 U+2581). Other tokens with spaces also have the issue.

# Environment and Context

Run main like this
```
$ ./main -m models/llama-2-13b.q6_K.gguf -n 1 -p '   three spaces
    three spaces after newline'
```
and it will print out
```
 ▁▁ three spaces
 ▁ three spaces after newline
```
where the first line has two U+2581 and the second line has one U+2581.

Edit: the output with `--verbose-prompt`
```
     1 -> ''
  1678 -> ' ▁▁'
  2211 -> ' three'
  8162 -> ' spaces'
    13 -> '
'
   259 -> ' ▁'
  2211 -> ' three'
  8162 -> ' spaces'
  1156 -> ' after'
 25899 -> ' newline'
```

**Comment by ggerganov** [comment]
I think this fixes it: https://github.com/ggerganov/llama.cpp/pull/2750

Can you give it a try?

**Comment by jxy** [comment]
That works.

This is an odd choice of sentencepiece that hijacks a standardized unicode symbol. They should have used something in PUA.
