### ISSUE TITLE
How to use make LLamacpp model to take advantage of GPU

### ISSUE THREAD

**Issue by Asrith-Dasari-AuxoAI** [ggerganov/llama.cpp#2747]
Little bit of Context : 

I want to try out Quantized Llama-7b on the Document Q&A task. I started my experimentation on Kaggle. But found that GPU was not being utilized. 

I installed Lamacpp using  **pip install llama-cpp-python**

Is there something, I am missing?

**Comment by klosax** [comment]
These instructions can possibly help you:
https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast--metal
