### ISSUE TITLE
error loading model: failed to open models/7B/ggml-model-f16.bin: Value too large for defined data type

### ISSUE THREAD

**Issue by Tracker-Friendly** [ggerganov/llama.cpp#2749]
I am using a model of Koala7b, converted from the pytorch format using convert-pth-to-ggml.py. However, when i tried to run it using sudo ./main -m models/7B/ggml-model-f16.bin, it returns 

```
main: build = 1011 (dadbed9)
main: seed  = 1692816886
error loading model: failed to open models/7B/ggml-model-f16.bin: Value too large for defined data type
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/7B/ggml-model-f16.bin'
main: error: unable to load model

```
how do i fix this?

**Comment by staviq** [comment]
If you are converting a model from scratch, I'd recommend updating llamacpp and converting to the new GGUF format.

As a sidenote, you don't need sudo.

**Comment by Tracker-Friendly** [comment]
The models are chown to root, lol...
So i have to run NORMAL convert.py after to ggml.py huh...

**Comment by Tracker-Friendly** [comment]
Traceback (most recent call last):
  File "convert.py", line 1326, in <module>
    main()
  File "convert.py", line 1306, in main
    model_plus = load_some_model(args.model)
  File "convert.py", line 1221, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "convert.py", line 1015, in lazy_load_file
    return lazy_load_ggml_file(fp, path)
  File "convert.py", line 962, in lazy_load_ggml_file
    mapped = memoryview(mmap.mmap(fp.fileno(), 0, access=mmap.ACCESS_READ))
ValueError: mmap length is too large

**Comment by staviq** [comment]
> The models are chown to root, lol... So i have to run NORMAL convert.py after to ggml.py huh...

If you previously used sudo, you will get things chowned by root, which wouldn't happen if you didn't unnecessarily use sudo :)

Paging @KerfuffleV2 for the convert.py stuff

**Comment by KerfuffleV2** [comment]
main: build = 1011 (dadbed9)

That's the commit before the GGUF stuff landed. I'd recommend doing what staviq said and updating to the current version. After that use `convert.py` to convert the PyTorch model to a `.gguf` file and then use the quantize tool to quantize it (unless you actually want to run the 32bit or 16bit model - usually not practical for larger models).

**Comment by Tracker-Friendly** [comment]
I'm AT the latest version. That's the error from convert.py.

**Comment by staviq** [comment]
> I'm AT the latest version. That's the error from convert.py.

If you updated in the meantime, kindly please post the output from running `main` again, for clarification, because we need to be able to reference the exact commit of the build you are using to help you.

Otherwise your original comment includes commit id `main: build = 1011 (dadbed9)` which tells us, you aren't running the latest version, and that's a bit confusing.

**Comment by Tracker-Friendly** [comment]
Compiling latest git pull now...

**Comment by dereklll** [comment]
> Compiling latest git pull now...

and solved?

**Comment by Tracker-Friendly** [comment]
Nope... I think it was just because it didn't have enough RAM
