### ISSUE TITLE
[User] -n -2 generates nothing

### ISSUE THREAD

**Issue by JackJollimore** [ggerganov/llama.cpp#2754]
See this post: https://github.com/ggerganov/llama.cpp/issues/2754#issuecomment-1691682835

**Comment by KerfuffleV2** [comment]
Your prompt is longer than the requested context size. I seem to recall running into weirdness involving that previously as well.

If it did respect the context size, it would exit partway through evaluating the prompt and before you got a chance to interact.

**Comment by JackJollimore** [comment]
> Your prompt is longer than the requested context size.

Nope, the prompt is 13 tokens. Here's another example with `-c 50`:

```
USER: Hi. ASSISTANT: Hello! How can I help you today? USER: list 3 movie titles.                                                                                                1) The Lion King                                        
2) The Incredibles                                    
 3) Finding Nemo                                       
4) The Little Mermaid                             
 5) Cars                                              
 6) Monsters, Inc.                                   
 7) Buzz Lightyear of Star Command                        
  8) The Lion King                                          
 9) Hakuna Matata from The Lion                                                                                        
```

Assistant used 77 tokens and I had to CTRL + C to end it.

**Comment by KerfuffleV2** [comment]
Apologies, I read it wrong. Sorry for the confusion.

**Comment by KerfuffleV2** [comment]
Ahh, I think I know what's going on. You have `-n -1` (generate forever):

    -n N, --n-predict N   number of tokens to predict (default: -1, -1 = infinity, -2 = until context filled)

and also keep is set to `-1`:

    --keep N              number of tokens to keep from the initial prompt (default: 0, -1 = all)

It'll just try to roll over the context whenever it fills up and keep those prompt tokens. Since the context is so small, it's not surprising this causes fairly nonsensical results. (The context rollover thing is kind of hit or miss in general since it happens in an arbitrary place that may be in the middle of a word.)

Anyway, try setting `-n` to either `-2` or a specific value <= the context size.

**Comment by JackJollimore** [comment]
> Ahh, I think I know what's going on. You have `-n -1` (generate forever):
> 

`--n-predicts` defaults to -1. I exclude it from `main` and llama.cpp sets it. It's the # of tolens llama.cpp generates before stopping. Default value unexpectedly overrides the context.

> It'll just try to roll over the context whenever it fills up and keep those prompt tokens. 

Yes, but it shouldn't roll over the context.

> Anyway, try setting `-n` to either `-2` or a specific value <= the context size.

![Screenshot_20230824_090025](https://github.com/ggerganov/llama.cpp/assets/130917767/be9e3d33-b75a-4d38-97d8-3e069636449f)

The image shows llama.cpp produced 20 tokens total(equal to -n 20), then got hung up and didn't respond.

I feel this's easily reproducable, maybe I haven't provided enough detail. Here's another example where llama.cpp just hangs with `-n -2`
```
generate: n_ctx = 50, n_batch = 7, n_predict = -2, n_keep = 13                                                                                                                                                                              == Running in interactive mode. ==                                  
...                                                           
USER: Hi. ASSISTANT: Hello!
```

llama.cpp didn't even try to fill context.

**Comment by KerfuffleV2** [comment]
> Yes, but it shouldn't roll over the context.

Well, it should if `n_predict == -1`. If you're setting `n_predict` to a different value and something is overriding it then that's a different issue.

> The image shows llama.cpp produced 20 tokens total(equal to -n 20), then got hung up and didn't respond.

Certainly that behavior is wrong too.

It's different from your original problem where you thought the size just wasn't respected though.

**Comment by JackJollimore** [comment]
Thanks for your response, though I don't understand the purpose of context if llama.cpp ignores it by default. To clarify, llama.cpp defaults to `-n -1`.

All these other weird behaviors extend from llama.cpp neglecting to stop when it reaches max context.

**Comment by KerfuffleV2** [comment]
> Thanks for your response, though I don't understand the purpose of context if llama.cpp ignores it by default. 

You can set it to a non-default value and have a context limit if you want. The context size also affects how much memory (CPU or GPU) is used so it still has significant effects even aside from limiting how many tokens are generated.

> All these other weird behaviors extend from llama.cpp neglecting to stop when it reaches max context.

I'm afraid I don't agree here. If `n_predict` is `-1` then this is specifically saying `generate an infinite amount of tokens`. You can't be surprised when it generates an infinite amount of tokens.

If you set `n_predict` to 50 or to `-2` (which specifically means "generate until the context is full") and it doesn't stop at 50 tokens (or full context as the case may be) then _that_ is absolutely a problem. If it gets stuck and just spins without producing output, that's absolutely a problem.

But the generating tokens past the context limit when `n_predict == -1` is expected behavior and whether the default should be changed is an administrative thing rather than a bug in the program.

**Comment by KerfuffleV2** [comment]
> It cannot predict and generate more tokens than initally defined by context.

Oh, but it actually can!

There's special logic to handle running into the context limit. Assuming you didn't set `n_predict` to a value <= that limit or to `-2` once it hits the context limit it will shuffle around the list of last tokens and keep generating, overwriting some of the existing state. If `--keep` was set, it'll reapply that number of prompt tokens first.

This is a poor man's infinite context. This was more useful before the discovery of the rope stuff and LLaMA2 supporting 4096 context off the bat but using this approach it was possible to get pretty coherent output past the 2048 context limit of LLaMA1 models.

See: https://github.com/ggerganov/llama.cpp/tree/master/examples/main#number-of-tokens-to-predict

*A value of -1 will enable infinite text generation, even though we have a finite context window. When the context window is full, some of the earlier tokens (half of the tokens after --n-keep) will be discarded. The context must then be re-evaluated before generation can resume.*

**Comment by JackJollimore** [comment]
> Oh, but it actually can!
> 
> There's special logic to handle running into the context limit. 

Oh dear,.. I stand corrected! I'll test various `-n` values today. Thank you.

**Comment by JackJollimore** [comment]
Perhaps there's reason for `-n -2` generating nothing, but I dunno:

![Screenshot_20230824_102934](https://github.com/ggerganov/llama.cpp/assets/130917767/9f9beaf7-97fd-4fbd-8ba6-3fd514817592)

`./main -m ~/llama-2-chat.gguf --color -c 40 --keep -1 -n -2 -t 3 -b 7 -i -r "USER:" --in-prefix " " -p "USER: Hi."`

Had to CTRL+C.

**Comment by JackJollimore** [comment]
> > Perhaps there's reason for `-n -2` generating nothing,
> 
> Not as far as I know. So what you thought was originally a bug was okay (though there's probably an argument for changing the default). It seems like you did find a genuine issue though. Glad you already reopened this yourself, I was going to suggest that.
> 

Admittely, `-n -1` confuses me, but README explains the behavior so you're correct. Probably `-n -2` should be the default. Thanks for clarfying with me.


> Are you running on Metal? I've heard there were issues that could lead to issues where llama.cpp would get stuck. _edit_: #2678 is the one I was thinking of.

Nope, `Linux localhost 4.14.190-23725627-abG975WVLS8IWD1 #2 SMP PREEMPT Mon Apr 10 18:16:39 KST 2023 aarch64 Android`, CPU build.

`./main -m ~/llama-2-chat.gguf --color -c 200 --keep -1 -n -2 -t 3 -b 7 -i -p "Once upon a time, in a dark forest, there lived a little fox"`
I tried your example, and it got stuck again:
```
generate: n_ctx = 200, n_batch = 7, n_predict = -2, n_keep = 17
== Running in interactive mode. ==                          
...
                                                                                                        
Once upon a time, in a dark forest, there lived a little fox Ummmm test test                                                                                                                                                               

llama_print_timings:        load time =  3887.72 ms        
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time =  4560.34 ms /    17 tokens (  268.26 ms per token,     3.73 tokens per second)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time = 42952.01 ms
```

**Comment by KerfuffleV2** [comment]
Ah, okay, I can replicate issues specifying the prompt with `-p` (was previously reading it from a file with `-f`) and using `--interactive`. This seems like a problem specific to interactive mode.

Not sure what's actually causing the issue. It doesn't seem like it's spinning consuming CPU, it seems like it thinks it's supposed to be reading user interaction.

**Comment by JackJollimore** [comment]
> It doesn't seem like it's spinning consuming CPU, it seems like it thinks it's supposed to be reading user interaction.

Exactly! Whew, sometimes I underestimate what it takes to replicate an issue, so thanks for honing in on this with me.

I was reluctant to change `-n -1` cuz' the result threw me off.

**Comment by JackJollimore** [comment]
> It seems like it means "generate X tokens and then return control to the user" - every time.

I was trying to say that earlier, but y'know how it is.

I'll try the fix.

**Comment by JackJollimore** [comment]
Yup, working.
```
main: context full, stopping generation
```

First time I've seen that!

**Comment by KerfuffleV2** [comment]
I can't merge without someone else approving it anyway. :) More testing is always great though. I'm more scared of breaking something else than issues with `-2` from that change, but the more I think about it the more I'm convinced this is correct.

Allowing `n_predict == -2` for stop at full context is a pretty recent change. I think the logic there just didn't get updated (it was set to check just for `-1`).

**Comment by JackJollimore** [comment]
> the more I think about it the more I'm convinced this is correct.
> 

I agree. We identified there was a problem, so that's significant, and my testing works.
