### ISSUE TITLE
cuda : fix Falcon inference with offloaded KV cache

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#2779]
We seem to have a bug somewhere which currently prevents offloading the KV cache to the GPU when using Falcon.
See the discussion in https://github.com/ggerganov/llama.cpp/pull/2760 for more info

As a secondary task, we should fix the RoPE kernels to not waste half of the threads - again see the discussion

**Comment by JohannesGaessler** [comment]
The issue is caused by RoPE. You can confirm this for yourself by commenting out lines 6709-6711 in `ggml-cuda.cu`. This causes llama.cpp to always use the CUDA implementation of RoPE. If you now run LLaMA with -ngl 0 it produces correct results, falcon with -ngl 0 produces garbage.

**Comment by ggerganov** [comment]
I guess it could be somehow related to the `flatten_rows` logic which I haven't fully understood yet. I don't see a bug in the actual kernel. It is very similar to the standard RoPE.

**Comment by ggerganov** [comment]
Ah, this seems to fix the bug:

```diff
diff --git a/llama.cpp b/llama.cpp
index e956c01..ee0f8e0 100644
--- a/llama.cpp
+++ b/llama.cpp
@@ -2635,18 +2635,18 @@ static struct ggml_cgraph * llm_build_falcon(
 
             const size_t wsize = ggml_type_size(cur->type);
 
-            struct ggml_tensor * tmpq = ggml_view_3d(
+            struct ggml_tensor * tmpq = ggml_cont(ctx0, ggml_view_3d(
                 ctx0, cur, n_embd_head, n_head, N,
                 wsize * n_embd_head,
                 wsize * n_embd_head * (n_head + 2 * n_head_kv),
-                0);
+                0));
             offload_func_kq(tmpq);
 
-            struct ggml_tensor * tmpk = ggml_view_3d(
+            struct ggml_tensor * tmpk = ggml_cont(ctx0, ggml_view_3d(
                 ctx0, cur, n_embd_head, n_head_kv, N,
                 wsize * n_embd_head,
                 wsize * n_embd_head * (n_head + 2 * n_head_kv),
-                wsize * n_embd_head *  n_head);
+                wsize * n_embd_head *  n_head));
             offload_func_kq(tmpk);
 
             struct ggml_tensor * tmpv = ggml_view_3d(
```

Looks like we don't handle the non-contiguous case with CUDA.

**Comment by JohannesGaessler** [comment]
>I guess it could be somehow related to the flatten_rows logic which I haven't fully understood yet. I don't see a bug in the actual kernel. It is very similar to the standard RoPE.

The point is to reduce the number of CUDA kernel launches. For most tensors each value or row can be calculated independently from the rest. So to reduce the kernel launch overhead the tensors are reshaped to be one-dimensional in dimensions 2 and 3 while being larger in dimension 1. For something like addition or multiplication the reshaping makes no difference. For RoPE this requires increasing p periodically to account for the original tensor shapes.

In any case, I think for now we should just fix it by using `cont` instead of `view`. Can I leave it to you?
