### ISSUE TITLE
GitHub CI stuck

### ISSUE THREAD

**Issue by staviq** [ggerganov/llama.cpp#2784]
CI seems to be dying

Additionally, I noticed there is a job running continuously for the past 2 months if I'm reading it correctly:

https://github.com/ggerganov/llama.cpp/actions/runs/5368301508

**Comment by staviq** [comment]
Should I close this ?

That weird stuck job is still there, but CI seems to be back to normal.

**Comment by slaren** [comment]
I am not sure that we do much about it, this seems to be a github issue. I tried cancelling the workflow, but it fails with a generic message ("Failed to cancel workflow. ").

**Comment by staviq** [comment]
Ok, I'm leaving it up to you whether to close this or not, because it's not a problem for me currently, and I only assumed that was a problem because yesterday, for over half an hour every job was queued and only that one was running, but it seems to no longer be the case.

**Comment by Green-Sky** [comment]
this is the first time I have seen something like this. very interesting.

image for when this gets eventually fixed:
![image](https://github.com/ggerganov/llama.cpp/assets/2938071/44ac9daf-5c7f-4168-add5-5c4832807ac1)
