### ISSUE TITLE
[User] Mac with Intel CPU + AMD GPU

### ISSUE THREAD

**Issue by chigkim** [ggerganov/llama.cpp#2785]
Since Llama.cpp now supports ROCM, is that possible to support Mac with Intel CPU + AMD GPU as well?

**Comment by MichaelDays** [comment]
The ROCm drivers only list Linux and Windows operating systems, not MacOS. Bootcamping the Intel Mac into Windows/Linux might be a way to do it?

https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html

**Comment by chigkim** [comment]
That makes sense.
I was hoping to be able to do it natively on MacOS, but thanks for the info!
