### ISSUE TITLE
Codellama on gpu M1

### ISSUE THREAD

**Issue by pantol** [ggerganov/llama.cpp#2828]
I have the latest llama.cpp version and I am trying to run codellama from thebloke on m1 but I get 
```

warning: not compiled with GPU offload support, --n-gpu-layers option will be ignored
warning: see main README.md for information on enabling GPU BLAS support
```

I did LLAMA_METAL=1 make 

```
I llama.cpp build info: 
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.            -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -pthread -DGGML_USE_K_QUANTS -DGGML_USE_ACCELERATE -DGGML_USE_METAL -DGGML_METAL_NDEBUG
I CXXFLAGS: -I. -I./common -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS -DGGML_USE_METAL
I LDFLAGS:   -framework Accelerate -framework Foundation -framework Metal -framework MetalKit
I CC:       Apple clang version 14.0.3 (clang-1403.0.22.14.1)
I CXX:      Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```
I also don't see the option -ngl when I run ./main --help 

I have done make clean and I have cloned the repository again  and follow the instruction but I still get the response that gpu is not supported. It worked well month ago so is something wrong with the latest upgrades or I miss some installation process.

**Comment by rozek** [comment]
I just downloaded the (very) latest version of llama.cpp, compiled it with Metal support, downloaded `codellama-13b-instruct.Q3_K_M.gguf` from Huggingface and tried my typical test ("who was Joseph Weizenbaum") with various context sizes (ok, you caught me - [I changed the built-in context limit to 16384](https://github.com/rozek/llama.cpp) before compiling)

On my little MBA 15" (M2 processor with 10 GPU cores) equipped with 24GB, the following invocation worked fine

```
./main -m codellama-13b-instruct.Q3_K_M.gguf --prompt "who was Joseph Weizenbaum?" --temp 0 --top-k 1 --tfs 0.95 -b 8 -ngl 10 -c 12288
```

**Comment by rozek** [comment]
I just also tested `codellama-7b-instruct.Q8_0.gguf` from Huggingface - which even works with the full context length of 16k on my MBA 15" with 24GB RAM:

```
./llama -m codellama-7b-instruct.Q8_0.gguf --prompt "who was Joseph Weizenbaum?" --temp 0 --top-k 1 --tfs 0.95 -b 8 -ngl 10 -c 16384
```

**Comment by rozek** [comment]
Nota bene: if you are uncertain which model size and quantization to use, the following post may be helpful: [Updated relative comparison of GGML quantization types and effect on perplexity](https://www.reddit.com/r/LocalLLaMA/comments/142q5k5/updated_relative_comparison_of_ggml_quantization/)

(Assuming that the same values still apply to GGUF as the latte mainly seems to be a different file format for the same quantizations)

**Comment by rozek** [comment]
@pantol the typical mistake: did you also copy file `ggml-metal.metal` into the folder with your `main` executable? Metal support does not work without that file...

**Comment by pantol** [comment]
Yes, I have the file in my main folder. I can use different type of models but I still can not specify -ngl. Should I use earlier versions of llama.cpp?

**Comment by rozek** [comment]
I am using the latest version of llama.cpp myself - thus, the version of llama.cpp should not be the problem. Does your compilation run without errors? What are the details of your machine?

**Comment by pantol** [comment]
I have MacBook Pro M1 Pro 16gb. 
I am doing the following command 
`./main -m models/CodeLlama-13B-Instruct-GGUF/codellama-13b-instruct.Q5_K_M.gguf -p "who was Joseph Weizenbaum?" -ngl 1   `

Response 
```

warning: not compiled with GPU offload support, --n-gpu-layers option will be ignored
warning: see main README.md for information on enabling GPU BLAS support
main: build = 1085 (1591e2e)
main: seed  = 1693161742

llama_model_loader: tensor 0..362
llama_model_loader: - kv   0:                       general.architecture str     
llama_model_loader: - kv   1:                               general.name str     
llama_model_loader: - kv   2:                       llama.context_length u32     
llama_model_loader: - kv   3:                     llama.embedding_length u32     
llama_model_loader: - kv   4:                          llama.block_count u32     
llama_model_loader: - kv   5:                  llama.feed_forward_length u32     
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32     
llama_model_loader: - kv   7:                 llama.attention.head_count u32     
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32     
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32     
llama_model_loader: - kv  10:                       llama.rope.freq_base f32     
llama_model_loader: - kv  11:                          general.file_type u32     
llama_model_loader: - kv  12:                       tokenizer.ggml.model str     
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr     
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr     
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr     
llama_model_loader: - kv  16:               general.quantization_version u32     
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type  f16:    1 tensors
llama_model_loader: - type q4_0:    1 tensors
llama_model_loader: - type q5_K:  240 tensors
llama_model_loader: - type q6_K:   40 tensors
llm_load_print_meta: format         = GGUF V1 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 32016
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 16384
llm_load_print_meta: n_ctx          = 512
llm_load_print_meta: n_embd         = 5120
llm_load_print_meta: n_head         = 40
llm_load_print_meta: n_head_kv      = 40
llm_load_print_meta: n_layer        = 40
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 1
llm_load_print_meta: f_norm_eps     = 1.0e-05
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 13824
llm_load_print_meta: freq_base      = 1000000.0
llm_load_print_meta: freq_scale     = 1
llm_load_print_meta: model type     = 13B
llm_load_print_meta: model ftype    = mostly Q5_K - Medium
llm_load_print_meta: model size     = 13.02 B
llm_load_print_meta: general.name   = LLaMA
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MB
llm_load_tensors: mem required  = 8966.74 MB (+  400.00 MB per state)
.................................................................................................
llama_new_context_with_model: kv self size  =  400.00 MB
llama_new_context_with_model: compute buffer total size =   75.41 MB

system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | 
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0
```

I have been doing the inference with llama2 models so the hardware isn't a problem here I guess.

**Comment by rozek** [comment]
sure, but for whatever reason the executable claims not being compiled with GPU support. What macOS version do you use? Ventura?

**Comment by pantol** [comment]
I use 13.4.1 (22F82). I haven't done any updates for a while. I had the same version when I begun running the llama.cpp with metal back then. I guess I will set up the repository once again maybe it will work. Is it any possibility that any of the files are broken so it doesn't work properly?

**Comment by rozek** [comment]
strange - I'm using 13.4.1 as well.

Of course, some files _could_ be broken - but didn't you already re-cloned the repo before?

If everything breaks, I could send you my `main` file (less than 900k uncompressed) out-of-band to keep you going...

**Comment by pantol** [comment]
Yes, I have already re-cloned it. 

I think we can try the solution you mention and in the mean time I will try dive deep and maybe I will find any solution.

**Comment by rozek** [comment]
Ok, lets go:

I've opened [an issue in my own fork of llama.cpp](https://github.com/rozek/llama.cpp/issues/1) and uploaded a ZIP archive containing the most important binaries - feel free to "close" it after downloading them

**Comment by pantol** [comment]
It works. Thank you for help

**Comment by rozek** [comment]
great - I'm happy that I could help.

Good success for finding the cause of your problem!

**Comment by PawKanarek** [comment]
Had the same problem. To solve it i completely cleaned `llama.cpp` repository with command  `git clean -fdx`  _(note this will erase all unstaged files)_ then i pulled newest changes from `master` branch (commit sha: bd33e5ab92e7f214205792fc1cd9ca28e810f897) and finally i rebuild it with `LLAMA_METAL=1 make`

After rebuild the warning  `warning: not compiled with GPU offload support, --n-gpu-layers option will be ignored` is gone.

**Comment by rozek** [comment]
That's an important detail - thanks for sharing!
