### ISSUE TITLE
Quantize adds `\0` to the end of GGUF strings

### ISSUE THREAD

**Issue by philpax** [ggerganov/llama.cpp#2836]
# Expected Behavior

Strings in GGUF should not be null-terminated.

# Current Behavior

When quantizing a GGUF model produced by the Python script, `quantize` appears to add a null-terminator to all strings it processes, including metadata keys and tensor names.

I have a program with my experimental Rust reader:
```rust
let gguf = gguf::Gguf::load(&mut file)?;
let mut keys: Vec<_> = gguf.metadata.keys().cloned().collect();
keys.sort();
println!("{keys:?}");
```

This is what it produces for the original `f16` model:
```
["general.architecture", "llama.attention.head_count", "llama.attention.head_count_kv", "llama.attention.layer_norm_rms_epsilon", "llama.block_count", "llama.context_length", "llama.embedding_length", "llama.feed_forward_length", "llama.rope.dimension_count", "tokenizer.ggml.model", "tokenizer.ggml.scores", "tokenizer.ggml.tokens"]
```

This is what it produces after `q5_k` v1 or v2 quantization (the bug is present in both versions):
```
["general.architecture\0", "general.file_type\0", "general.quantization_version\0", "llama.attention.head_count\0", "llama.attention.head_count_kv\0", "llama.attention.layer_norm_rms_epsilon\0", "llama.block_count\0", "llama.context_length\0", "llama.embedding_length\0", "llama.feed_forward_length\0", "llama.rope.dimension_count\0", "tokenizer.ggml.model\0", "tokenizer.ggml.scores\0", "tokenizer.ggml.tokens\0"]
```

To confirm this isn't an issue with my reader:
```
llm # hexdump -C models/llama2/llama-2-7b-f16.gguf | head -n 4
00000000  47 47 55 46 01 00 00 00  23 01 00 00 0c 00 00 00  |GGUF....#.......|
00000010  14 00 00 00 67 65 6e 65  72 61 6c 2e 61 72 63 68  |....general.arch|
00000020  69 74 65 63 74 75 72 65  08 00 00 00 05 00 00 00  |itecture........|
00000030  6c 6c 61 6d 61 14 00 00  00 6c 6c 61 6d 61 2e 63  |llama....llama.c|

llm # hexdump -C models/llama2/llama-2-7b-q5_k.v2.gguf | head -n 4          
00000000  47 47 55 46 02 00 00 00  23 01 00 00 00 00 00 00  |GGUF....#.......|
00000010  0e 00 00 00 00 00 00 00  15 00 00 00 00 00 00 00  |................|
00000020  67 65 6e 65 72 61 6c 2e  61 72 63 68 69 74 65 63  |general.architec|
00000030  74 75 72 65 00 08 00 00  00 06 00 00 00 00 00 00  |ture............|
```

Ignoring the counts that were increased from 4 to 8 bytes in v2, you can see that `general.architecture` has a length of `0x14` in the `f16` model and a length of `0x15` in the `q5_k` model.

# Steps to Reproduce

Produce a GGUF model with the Python scripts, then quantize it with the `quantize` executable. Compare the resulting GGUF strings in both files.

**Comment by slaren** [comment]
I guess the difference is the `+ 1` here:

https://github.com/ggerganov/llama.cpp/blob/c10704d01e21e3dbe4d6ca1026ebff85349dd239/ggml.c#L20158-L20164
