### ISSUE TITLE
[Falcon] `convert-falcon-hf-to-gguf.py` has some missing dependencies 

### ISSUE THREAD

**Issue by akawrykow** [ggerganov/llama.cpp#2860]
For example, we depend on the `torch` and `transformers` packages so even after running `python3 -m pip install -r requirements.txt` we run into issues when executing `convert-falcon-hf-to-gguf.py`.

Should we add these to `requirements.txt` or is the idea that the user would most likely have these installed globally and we want to keep our requirements file light and minimal? If we should add them, I can send a quick PR

Thanks!

**Comment by KerfuffleV2** [comment]
> I wish to keep 3rd party deps as few as possible, so if there is a way to avoid those packages would be nice.

`convert.py` avoids the torch dependency by having its own pickle loading code. Probably the way to go is to abstract that out so other scripts can use it. (Should be separate from the pull I mentioned though probably.)

Not sure there's a practical way to avoid using `transformers` though, it uses `AutoTokenizer` from that to handle `tokenizer.model`.
