### ISSUE TITLE
[linux] [amd64] [CUDA] -ngl hangs in interactive mode with 70B llama2 if mmap is enabled

### ISSUE THREAD

**Issue by vfhbg** [ggerganov/llama.cpp#2866]
Interactive mode seems to hang after a short while and not give the reverse prompt in interactive mode if I don't use --no-mmap and do use -ngl (even far less than available VRAM). The lower the ngl value the longer it lasts before it hangs. I'm using a AMD 5950X with 64GB RAM with a RTX 3090 on Ubuntu 22.04.

These work:

```
./main -t 16 --no-mmap -ngl 40 -m ./models/70B-chat/ggml-model-q4_0.gguf -c 4096 --n_predict -1 --repeat_penalty 1.070 --color -i -r "User:" -f prompts/prompt.txt
```

```
./main -t 16 -m ./models/70B-chat/ggml-model-q4_0.gguf -c 4096 --n_predict -1 --repeat_penalty 1.070 --color -i -r "User:" -f prompts/prompt.txt
```

This does not:

```
./main -t 16 -ngl 20 -m ./models/70B-chat/ggml-model-q4_0.gguf -c 4096 --n_predict -1 --repeat_penalty 1.070 --color -i -r "User:" -f prompts/prompt.txt
```

Also the documentation seems to reflect some missing command line parameters:

- Specify `-eps 1e-5` for best generation quality
- Specify `-gqa 8` for 70B models to work

**Comment by slaren** [comment]
The command line parameters `-eps` and `-gqa` are no longer necessary and have been removed, they have been incorporated into the metadata of the gguf model files instead. I have opened https://github.com/ggerganov/llama.cpp/pull/2881 to fix this.
