### ISSUE TITLE
failed to load model

### ISSUE THREAD

**Issue by jcao0715** [ggerganov/llama.cpp#2867]
# Expected Behavior

I'm trying to run the command ./server -m llama-2-7b-chat.ggmlv3.q5_1.bin -t 10 --no-mmap to open a server to use Llama, but I keep receiving this error:

{"timestamp":1693292489,"level":"INFO","function":"main","line":1291,"message":"build info","build":1108,"commit":"44c117f"}
{"timestamp":1693292489,"level":"INFO","function":"main","line":1296,"message":"system info","n_threads":10,"total_threads":8,"system_info":"AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | "}
error loading model: failed to open llama-2-7b-chat.ggmlv3.q5_1.bin: No such file or directory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'llama-2-7b-chat.ggmlv3.q5_1.bin'
{"timestamp":1693292489,"level":"ERROR","function":"loadModel","line":263,"message":"unable to load model","model":"llama-2-7b-chat.ggmlv3.q5_1.bin"}

My model (llama-2-7b-chat.ggmlv3.q5_1.bin) is stored in llama.cpp/models and I've tried calling the command using -m /models/llama-2-7b-chat.ggmlv3.q5_1.bin and -m llama-2-7b-chat.ggmlv3.q5_1.bin. I've also tried using a .gguf file as a model but that still gives me the same "failed to load model" error.

# Environment and Context

I'm using an M1 MacBook Pro and on MacOS Ventura 13.2.1.

**Comment by vfhbg** [comment]
What directory are you trying to run it from? The -m command is relative to the current directory. So if you run from the llama.cpp directory:

`./server -m ./models/llama-2-7b-chat.ggmlv3.q5_1.bin`

"/models" is likely a path that does not exist, and if you are in "llama.cpp", the bin file would not be in your current path. I don't think "models/" is hard coded in the software.

**Comment by jcao0715** [comment]
I am running it from the llama.cpp directory and I've tried running both `./server -m ./models/llama-2-7b-chat.ggmlv3.q5_1.bin` and `./server -m /models/llama-2-7b-chat.ggmlv3.q5_1.bin`, neither of which worked.

**Comment by Henny35P** [comment]
I'm having the same issue after updating to the latest version.
M1 Pro on MacOs Sonoma beta 6

**Comment by jcao0715** [comment]
I tried using an older version (7/26/2023) of the repo and it still gives me the same error.

**Comment by staviq** [comment]
Any path starting with `/` means an absolute path, referencing your root disk directory

If you build with cmake, and have your binaries in the "build" folder and you execute them from there, all paths are relative to the directory you are in.

Use tab completion in the terminal, it will autocomplete if the path is correct.

**Comment by Henny35P** [comment]
> I tried using an older version (7/26/2023) of the repo and it still gives me the same error.

I got it working with d783f7982e0e823a2626a9956359c0d36c1a7e21

**Comment by sir-gon** [comment]
I have tested on my Mac, with MacOS Ventura 13.5.1

Until cb1c0727 , is the highest commit in master branch that is currently working.

**Comment by Zambonilli** [comment]
I had the same issue on a Mac m2 even when compiling with metal. Going back to https://github.com/ggerganov/llama.cpp/commit/d783f7982e0e823a2626a9956359c0d36c1a7e21 worked

**Comment by ggerganov** [comment]
For Mac Intel, try building with `LLAMA_NO_METAL=1`

I will close this issue as it is related to the GGUF format change. Please open another issue if your problems persist and provide logs

**Comment by samcaetano** [comment]
you can download the GGUF format here: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF

**Comment by horrorChen** [comment]
> you can download the GGUF format here: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF

Hello, I follow the instructions in the page but got error like:
```sh
$ cd models
$ huggingface-cli download TheBloke/Llama-2-7b-Chat-GGUF llama-2-7b-chat.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False
$ cd ..
$ ./main -ngl 32 -m ./models/llama-2-7b-chat.q4_K_M.gguf --color -c 4096 --temp 0.7 --repeat_penalty 1.1 -n -1 -p "[INST] <<SYS>>\nYou are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.\n<</SYS>>\n{prompt}[/INST]"

llama_model_load: error loading model: llama_model_loader: failed to load model from ./models/llama-2-7b-chat.q4_K_M.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model './models/llama-2-7b-chat.q4_K_M.gguf'
main: error: unable to load model
```

I am new to the project. Is there anything wrong?
