### ISSUE TITLE
[User] does opencl part use usm or not?

### ISSUE THREAD

**Issue by congzhangzh** [ggerganov/llama.cpp#2880]
Hi Folks,

Does OpenCL by CLBlast support related code use a USM buffer or a normal one?

As USM for pure CPU OpenCL runtime or intel iGPU OpenCL, runtime can reduce the memory copy and move back step which should speed the process and save memory. 

And USM may mess up the code as it's not so common to be supported or be well supported by others than intel. maybe?

ref: https://github.com/CNugteren/CLBlast/issues/501

Tks,
Cong

**Comment by SlyEcho** [comment]
I don't think there is any iGPU stuff currently. But @0cc4m would know better than I do.

**Comment by shibe2** [comment]
CLBlast back-end currently does not take advantage of shared memory with iGPU. This may be an important feature.

First step may be to benchmark relative performance (of matrix multiplication) of CPU and GPU parts of some common chips. If GPU is significantly faster, then it's worth working on the feature.

I currently don't have any suitable hardware to test it.
