### ISSUE TITLE
release : use clang instead of msvc

### ISSUE THREAD

**Issue by ivanstepanovftw** [ggerganov/llama.cpp#2883]
I noticed [someone](https://www.reddit.com/r/LocalLLaMA/comments/14geeud/performance_difference_between_linux_and_windows/) complaining that Windows pre-built binaries are slower in runtime relative to Linux binaries on Linux. I suggest to try clang as a solution for faster inference.

The GH Actions workflow must have Visual Studio, CMake, Ninja and LLVM installed. LLVM can be installed using Chocolatey, and Ninja is required for CMake to utilize clang compiler instead of cl.exe

**Comment by SlyEcho** [comment]
I think using MSYS2 and then ucrt64 libc would be okay, too. Could even use that to build the CLBlast library and compile it statically.

**Comment by staviq** [comment]
> Windows pre-built binaries are slower in runtime relative to Linux binaries on Linux

Linux inherently does computationally heavy things with less overhead, especially when it comes to memory throughput.

From my experience, MSVC almost always wins in performance over MSYS2, mingw, cygwin, but it comes with it's downsides like inconsistent implementation of some parts of c/cpp standard library.

I haven't tried clang on Windows, but from what I understand, IntelliSense does use clang internally to some extent, so maybe it's not a bad idea to try it.

**Comment by SlyEcho** [comment]
clang-cl.exe is an LLVM frontend that is compatible with cl.exe on the command line (just as clang is to GCC).

GCC and LLVM both have very good optimizers and SIMD support and that's what the devs here use.

Another thing is that the default Makefile targets will use `-march=native` which will do a lot of optimizations that go beyond what AVX2 etc will provide. Whether MSVC can achieve the same or not is another question (it probably is).
