### ISSUE TITLE
SEGV happen  when I start run main.exe

### ISSUE THREAD

**Issue by willwilling** [ggerganov/llama.cpp#2890]
llama.cpp $ ./main -m ../models/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512
main: build = 1119 (06abf8e)
main: seed  = 1693363349
SEGV

note. compile is success

**Comment by staviq** [comment]
Are you using w64devkit ? We found some problems related specifically to w64devkit, yesterday.

If so, try building with msys, or something else than w64devkit.
