### ISSUE TITLE
common/log.h:290:61: error: expected primary-expression before ',' token

### ISSUE THREAD

**Issue by munitioner** [ggerganov/llama.cpp#2898]
Running environment: Windows

Compilation method: BLAS Build

When I open w64devkit.exe and CD it to the llama.cpp directory, enter the command make LLAMA_ OPENBLAS=1 encountered the following error

![image](https://github.com/ggerganov/llama.cpp/assets/14157458/d10d13aa-55f2-46e8-bd9c-31d2af9611e2)

**Comment by JackJollimore** [comment]
Hi, the log's new, but I had no problems building in Linux with `OpenBlas`, so I think this is a Windows specific issue. You might try without `OpenBlas` for now.

@staviq Do you recognize this compile issue?

**Comment by ggerganov** [comment]
If you change `##__VA_ARGS__` to `__VA_ARGS__` in `common/log.h` does it compile?

**Comment by staviq** [comment]
This is likely Windows stray comma shenanigans, builds were fully passing yesterday, so that has to be some quirk of w64devkit

If you can tell me how did you set up the compilation environment I would be able to recreate it

In the mean time

Can you edit log.h and at the top, after includes and before the rest add

#undef _WIN32

and at the very bottom add

#define _WIN32

And see if it fixes it ?

**Comment by LostRuins** [comment]
I am using w64devkit and am encountering the same issue.

**Comment by staviq** [comment]
I'm stuck at work for couple more hours, but i have a general idea as to what is going on.

**Comment by staviq** [comment]
Ok, this is 100% because _WIN32 is defined on w64devkit, yet it compiles the "unix" way with gcc.

Fix is already on the way, just testing if it doesn't break other builds.

I used ifdef _WIN32 because other parts of the project are using it, but it turns out to be a bad idea, and now i can see lots of warning from other source files related to _WIN32

Proper way of detecting MSVC seems to be checking for `_WIN32` and `__MINGW32__` too.

This appears to be specific to w64devkit/msys/mingw

**Comment by Coloris** [comment]
I have the exact same issue using the latest version of w64devkit (https://github.com/skeeto/w64devkit/releases/tag/v1.20.0)

Just doing this :

    Run w64devkit.exe
    cd llama.cpp
    make

**Comment by slaren** [comment]
@staviq I think you can use `_MSC_VER` to detect MSVC.

**Comment by staviq** [comment]
@slaren Take a look at the fix PR, and if you think `_MSC_VER` is more suitable, I'll do it.

**Comment by munitioner** [comment]
> #undef _WIN32
> 
> and at the very bottom add
> 
> #define _WIN32

After recompiling, there was no error: expected primary expression before ',' token error, but a new error occurred
![image](https://github.com/ggerganov/llama.cpp/assets/14157458/b1e989cd-eb76-46e2-a1cc-6251bf24efcf)

**Comment by munitioner** [comment]
> ##__VA_ARGS__

According to your method, if the compilation error is not resolved, the same compilation error will still occur

**Comment by munitioner** [comment]
> If you change to in does it compile?`##__VA_ARGS__``__VA_ARGS__``common/log.h`
According to your method, if the compilation error is not resolved, the same compilation error will still occur

**Comment by munitioner** [comment]
> After recompiling, there was no error: expected primary expression before ',' token error, but a new error occurred



> This is likely Windows stray comma shenanigans, builds were fully passing yesterday, so that has to be some quirk of w64devkit
> 
> If you can tell me how did you set up the compilation environment I would be able to recreate it
> 
> In the mean time
> 
> Can you edit log.h and at the top, after includes and before the rest add
> 
> #undef _WIN32
> 
> and at the very bottom add
> 
> #define _WIN32
> 
> And see if it fixes it ?
> 
> Edit: This w64devkit ? As in, mingw thing ? https://www.mingw-w64.org/downloads/ Because in that case, I think the problem is with the use of _WIN32 flag, I would have to find something else to detect windows msvc specifically

After recompiling, there was no error: expected primary expression before ',' token error, but a new error occurred
![image](https://github.com/ggerganov/llama.cpp/assets/14157458/1d986b47-6f9d-4c04-80e9-156410faaed8)

**Comment by staviq** [comment]
Fix for this particular issue is already prepared to be merged, but we noticed other problems with w64devkit specifically, and we aren't sure yet, but those other problems might be w64devkit fault, so I would try something other than w64devkit untill we determine the source cause.

**Comment by munitioner** [comment]
> Fix for this particular issue is already prepared to be merged, but we noticed other problems with w64devkit specifically, and we aren't sure yet, but those other problems might be w64devkit fault, so I would try something other than w64devkit untill we determine the source cause.

I compiled successfully with cmake and did not encounter any errors
