### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the context's memory pool

### ISSUE THREAD

**Issue by NotNite** [ggerganov/llama.cpp#29]
Heya! Friend showed this to me and I'm trying to get it to work myself on Windows 10. I've applied the changes as seen in #22 to get it to build (more specifically, I pulled in the new commits from [etra0's fork](https://github.com/etra0/llama.cpp), but the actual executable fails to run - printing this before segfaulting:

```
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 458853944, available 454395136)
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 458870468, available 454395136)
```

I'm trying to use 7B on an i9-13900K (and I have about 30 gigs of memory free right now), and I've verified my hashes with a friend. Any ideas? Thanks!

**Comment by NotNite** [comment]
Tried out #31 - it, uh, got farther: `GGML_ASSERT: D:\code\c++\llama.cpp\ggml.c:9349: false`

**Comment by etra0** [comment]
ok I did an upsie in that PR, initializing it that way apparently didn't zero'ed out the rest of the fields. I updated the branch, please test it again now!

**Comment by NotNite** [comment]
> ok I did an upsie in that PR, initializing it that way apparently didn't zero'ed out the rest of the fields. I updated the branch, please test it again now!

It started to expand the prompt, but with seemingly garbage data: `Building a website can be done in 10 simple steps:  ╨Ñ╤Ç╨╛╨╜╨╛╨╗╨╛╨│╨╕╤ÿ╨`

**Comment by eshaanagarwal** [comment]
Hey i was trying to run this on a RHEL 8 server with 32 cpu cores. and i am getting the same error. On my second query.

I am using GPT4All-J v1.3-groovy.
```
ggml_new_tensor_impl: not enough space in the context's memory pool
```

**Comment by eshaanagarwal** [comment]
Hi @ggerganov @gjmulder I would appreciate some direction for this pls.

**Comment by superbsky** [comment]
Getting the same issue on Apple M1 Pro with 16GB RAM when trying the example from:

https://github.com/curiousily/Get-Things-Done-with-Prompt-Engineering-and-LangChain/blob/master/06.private-gpt4all-qa-pdf.ipynb

Using a relatively large PDF with ~200 pages

Stack trace:

gpt_tokenize: unknown token '?'
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 16118890208, available 16072355200)
[1]    62734 segmentation fault  python3
/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by dzupin** [comment]
Same issue when running on Win11 with 64GB RAM (25 GB utilized):


ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 450887680, available 446693376)
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows_GPU\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\AI\oobabooga_windows_GPU\text-generation-webui\modules\llamacpp_model.py", line 92, in generate
    for completion_chunk in completion_chunks:
  File "C:\AI\oobabooga_windows_GPU\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 891, in _create_completion
    for token in self.generate(
  File "C:\AI\oobabooga_windows_GPU\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 713, in generate
    self.eval(tokens)
  File "C:\AI\oobabooga_windows_GPU\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 453, in eval
    return_code = llama_cpp.llama_eval(
  File "C:\AI\oobabooga_windows_GPU\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 612, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: access violation reading 0x0000000000000028
Output generated in 39.00 seconds (0.00 tokens/s, 0 tokens, context 5200, seed 1177762893)

**Comment by LoganDark** [comment]
> Same issue when running on Win11 with 64GB RAM (25 GB utilized): [snip]

Oh hey, *exact same error*:

`ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 452859040, available 446693376)`

**Comment by jiapei100** [comment]
Same here... any solutions already???

**Comment by sherrmann** [comment]
Solved this by going back to llama-cpp-python version 0.1.74

**Comment by LoganDark** [comment]
> Solved this by going back to llama-cpp-python version 0.1.74

well this has nothing to do with python

**Comment by dereklll** [comment]
Same here... any solutions already???

**Comment by sozforex** [comment]
@dereklll This issue was closed 6 months ago, I'd suggest to create a new one.

**Comment by dillfrescott** [comment]
Same issue on a runpod gpu machine, tried 2 different gpu's
