### ISSUE TITLE
Unable to set output word limit for response generated

### ISSUE THREAD

**Issue by ayushgupta-1** [ggerganov/llama.cpp#2902]
Hi Developers,

I was trying to set a word limit for the response that the llama model generates, and so far I have tried -n--predict N but it is not working.

I am using a CUBLAS build and using the model via the ./server command

It would be great if anyone who has solved this issue can propose a valid solution for the issue.

Thanks.

**Comment by JackJollimore** [comment]
Hi, I'm not a developer, but there's no word limit setting in `llama.cpp`. `-n #` is the # of tokens to predict during generation,. Some words are 1 token, and other words are several.

It may be valid if your build ignores the # of tokens generated, but it's not clear based on the information provided.

**Comment by ayushgupta-1** [comment]
Hi, I am using the following command to open the server

Command :
./server -m models/llama-2-7b-chat.ggmlv3.q4_0.bin -c 512 -ngl 15000

Should I add -n N to the command, where N = no of tokens to predict ?

If you need any other information please free to ask. Thanks.

**Comment by JackJollimore** [comment]
The command is fine, adjust Predictions on the webpage:

![Screenshot_20230830_120522](https://github.com/ggerganov/llama.cpp/assets/130917767/8f6fd033-1e67-4cbc-94e6-258e2cfb7499)

**Comment by ayushgupta-1** [comment]
I am just running it in interactive mode in terminal and then using it as an api, hence I need a code or command solution. 

Also I am running this on linux machine hence I am unable to open a webpage.

This "Predictions" on webpage must be connected to a parameter at a server file or API file.

 If someone who has made it possible through code or command please leave a comment. It will be much appreciated. Thanks

**Comment by JackJollimore** [comment]
> hence I need a code or command solution.
> 
> Also I am running this on linux machine hence I am unable to open a webpage.
> 

[README](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#testing-with-curl) explains CURL, Node.js, and the API endpoints for `server`.

Related: https://github.com/ggerganov/llama.cpp/issues/1742

**Comment by ayushgupta-1** [comment]
But the README doesn't have any info on setting the Prediction word limit which is available at webpage.

I hope you are getting my query here.

**Comment by JackJollimore** [comment]
> But the README doesn't have any info on setting the Prediction word limit

That's incorrect. Generation ends once the # of tokens is met, and `n_predict` is available through CURL, or Node.js. There's no Prediction word limit.

**Comment by ayushgupta-1** [comment]
Closing the issue for now. Seems there is no solution for setting a response word limit.
