### ISSUE TITLE
Discussion: Requirements for NVLink of two 3090Ti for pooled 48gb VRAM

### ISSUE THREAD

**Issue by ghost** [ggerganov/llama.cpp#2907]
Greetings, as the title says, looking to add a second 3090Ti to the rig. Willing and able to implement anything required to enabled pooled VRAM. Looking for direction and suggested starting points to generate the PR. Also curious if current build already supports this?

**Comment by pancoaster** [comment]
@ggerganov please let me know if current build already supports pooled vram via nvlink

**Comment by JohannesGaessler** [comment]
See https://github.com/ggerganov/llama.cpp/pull/2470 . What would be needed to make it work properly as one large VRAM pool would be to extend `ggml_cuda_op` to make the kernels write directly to the VRAM of another GPU.
