### ISSUE TITLE
Quantizations for Llama-2-7B-32K-Instruct (32K context)

### ISSUE THREAD

**Issue by rozek** [ggerganov/llama.cpp#2919]
> "[Llama-2-7B-32K-Instruct](https://huggingface.co/togethercomputer/Llama-2-7B-32K-Instruct) is an open-source, long-context chat model finetuned from [Llama-2-7B-32K](https://huggingface.co/togethercomputer/Llama-2-7B-32K), over high-quality instruction and chat data."

I've just uploaded several quantizations of Llama-2-7B-32K-Instruct model in GGUF format to [Hugging Face](https://huggingface.co/rozek/LLaMA-2-7B-32K-Instruct_GGUF) for use with llama.cpp

**Comment by rozek** [comment]
My first impressions:

- consider the prompt format described in the model card of [Llama-2-7B-32K-Instruct](https://huggingface.co/togethercomputer/Llama-2-7B-32K-Instruct) - its important
- given a properly formatted prompt, the [Q8_0](https://huggingface.co/rozek/LLaMA-2-7B-32K_GGUF/blob/main/LLaMA-2-7B-32K-Q8_0.gguf) quantization performs pretty well, [Q4_0](https://huggingface.co/rozek/LLaMA-2-7B-32K_GGUF/blob/main/LLaMA-2-7B-32K-Q4_0.gguf) hallucinates far too much (these were the two variants I tested on my Macbook Air, both with a context size of 16k - this is the maximum my MBA can handle)

**Comment by BrutalCoding** [comment]
Heya again, 

Wouldn't you agree that creating a topic for this in https://github.com/ggerganov/llama.cpp/discussions/categories/show-and-tell is more suited? 

Besides that... awesome showcase.

**Comment by rozek** [comment]
done

**Comment by Darrshan-Sankar** [comment]
> My first impressions:
> 
> * consider the prompt format described in the model card of [Llama-2-7B-32K-Instruct](https://huggingface.co/togethercomputer/Llama-2-7B-32K-Instruct) - it's important
> * given a properly formatted prompt, the [Q8_0](https://huggingface.co/rozek/LLaMA-2-7B-32K_GGUF/blob/main/LLaMA-2-7B-32K-Q8_0.gguf) quantization performs pretty well, [Q4_0](https://huggingface.co/rozek/LLaMA-2-7B-32K_GGUF/blob/main/LLaMA-2-7B-32K-Q4_0.gguf) hallucinates far too much (these were the two variants I tested on my Macbook Air, both with a context size of 16k - this is the maximum my MBA can handle)
> 
> [Edit] OMG, no, my MBA (with 24GB RAM) can even handle a context size of 32k!
> 
> ```
> llm_load_tensors: mem required  = 6828,73 MB (+ 16384,00 MB per state)
> ```
> 
> How cool is that?????
> 
> (well, `--mlock` may no longer be a good idea in my case...)

Hi there, I wanted to load the model from llama-cpp-python which extends from the original in the langchain package.
from langchain_community.llms import LlamaCpp

I am trying to use your model, but get empty outputs. Could you please tell what values you used for the parameters:
llm = LlamaCpp(
    model_path=model_path,
    n_gpu_layers=n_gpu_layers,
    n_ctx = 32768,
    rope_freq_scale=?,
    rope_freq_base=?,
    temperature = 0,
    n_batch=n_batch,
    callback_manager=callback_manager,
    verbose=True, 
)

Are there any other additional values to be mentioned during loading?
Please also tell what are the requirements(both software/hardware) to use the entire context window(32k) without hallucination
