### ISSUE TITLE
alex5956 ican't succeed in converting my llama model 

### ISSUE THREAD

**Issue by aragon5956** [ggerganov/llama.cpp#2932]
# Prerequisites

i can't succeed in converting my llama model that i've downloaded with the link of meta 

# Expected Behavior

i want to correct the problem 

# Current Behavior

the message of the error is :"```
python3 convert.py .\models\llama-2-13b\
Python est introuvable. ExÚcutez sans argument pour procÚder Ó l
PS L:\llama.cpp> python convert.py .\models\llama-2-13b\
Loading model file models\llama-2-13b\consolidated.00.pth
Loading model file models\llama-2-13b\consolidated.01.pth
Traceback (most recent call last):
  File "L:\llama.cpp\convert.py", line 1197, in <module>
    main()
  File "L:\llama.cpp\convert.py", line 1138, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\llama.cpp\convert.py", line 1058, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "L:\llama.cpp\convert.py", line 747, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\llama.cpp\convert.py", line 697, in lazy_load_torch_file
    zf = zipfile.ZipFile(outer_fp)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python311\Lib\zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")"
```

# Environment and Context
windows 111 powershell and nvidia gtx 1070 wit cuda 

* Physical (or virtual) hardware you are using, e.g. for Linux:


```
python 3.11
cmake lastest version
```

could you help me ?

**Comment by Ph0rk0z** [comment]
You need the model in HF format I think.

**Comment by alex5956** [comment]
> You need the model in HF format I think.

Ok thanks you and how can i have this ?

**Comment by goerch** [comment]
> You need the model in HF format I think.

I seem to remember that I converted the original `Meta` download once.

> `raise BadZipFile("File is not a zip file")`

For me this looks like your download was not successful.

**Comment by alex5956** [comment]
HF => hugging face(the website)
https://github.com/facebookresearch/llama/issues/356

**Comment by alex5956** [comment]
But why the original file  doesn't work, for launching the AI ?
