### ISSUE TITLE
make: *** [Makefile:281: ggml-cuda.o] Error 127, and opt-out logging in llama.cpp.

### ISSUE THREAD

**Issue by RobertWilliams2** [ggerganov/llama.cpp#2940]
Using Linux, latest version of llama.cpp.

make -B LLAMA_CUBLAS=1 LLAMA_DISABLE_LOGS=1
results in

> CFLAGS   += -DLOG_DISABLE_LOGS
> make: CFLAGS: No such file or directory
> make: *** [Makefile:281: ggml-cuda.o] Error 127

I suspect the reason why I'm the first one who posted this issue is because few people are aware that since yesterday, llama.cpp has **opt-out** logging. All text gets stored on users' systems unless explicitly disabled. This is a huge security and privacy concern. Logging should be opt-in only.

**Comment by staviq** [comment]
Can you try editing `Makefile`

and moving this (lines 346-349):

```
ifdef LLAMA_DISABLE_LOGS
	CFLAGS   += -DLOG_DISABLE_LOGS
	CXXFLAGS += -DLOG_DISABLE_LOGS
endif # LLAMA_DISABLE_LOGS
```

to right below (line 80):

```
ifdef LLAMA_SERVER_VERBOSE
	CXXFLAGS += -DSERVER_VERBOSE=$(LLAMA_SERVER_VERBOSE)
endif
<---HERE
```

so it looks like this:

```
ifdef LLAMA_SERVER_VERBOSE
	CXXFLAGS += -DSERVER_VERBOSE=$(LLAMA_SERVER_VERBOSE)
endif

ifdef LLAMA_DISABLE_LOGS
	CFLAGS   += -DLOG_DISABLE_LOGS
	CXXFLAGS += -DLOG_DISABLE_LOGS
endif # LLAMA_DISABLE_LOGS
```

**Comment by RobertWilliams2** [comment]
That fixed the compiling issue.

I still suggest that logging be moved from compile to runtime parameter and be opt-in instead of opt-out.

**Comment by staviq** [comment]
> be opt-in instead of opt-out.

I'm not against that idea, but others would have to agree. Runtime args for disable/enable logs are already there.

**Comment by RobertWilliams2** [comment]
Are you referring to

> -ld LOGDIR, --logdir LOGDIR
>                         path under which to save YAML logs (no logging if unset)

?

Because it is still all text to main.923485746264.log files under llama.cpp\ just by compiling without including LLAMA_DISABLE_LOGS=1 without me using -ld or -logdir parameters.

**Comment by JackJollimore** [comment]
> still saving all text

Yes, by default it behaves as opt-in, your understanding is correct. I agree that it should change.

`---logdir path` is a different logger activated on command line.

**Comment by staviq** [comment]
Runtime argument for disabling `.log` generation is `--log-disable`

Running `./main -h` shows that one and couple more.

Please note, `.log` logs are debug logs, and were meant to make debugging problems easier.

Yaml logs, are a completely different feature with difrent purpose.

**Comment by RobertWilliams2** [comment]
I couldn't see the log-related commands of ./main -h because when I ran the command my main was compiled using LLAMA_DISABLE_LOGS=1, which also hides the commands (which makes sense since now the commands are prevented from working during compile, which is a further argument as for why enabling and disabling logs should not be a part of the compilation process.)
