### ISSUE TITLE
OSError: exception: access violation writing 0x0000000000000380 unable to query two querys at once  the LLMchain(llm=LLamaCPP())) 

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [ggerganov/llama.cpp#2941]
I create a streamlit app to chat with Lamma 7B chat model. 

When I open two tabs to chat and ask query it crashes becasue of the error OSError: exception: access violation writing 0x0000000000000380.

streaming was False
llm =  LlamaCpp(
            model_path="./models/llama-2-7b-chat.ggmlv3.q4_0.bin",
            n_ctx=6000,
            n_gpu_layers=512,
            n_batch=512,
            temperature = 0.9,
            max_tokens = 64,
            n_parts=1,
            streaming=False
        )

llm_chain = LLMChain(prompt=prompt, llm=llm)
llm_chain.run(st.session_state["chat_query"])

**Comment by JackJollimore** [comment]
> streamlit app

Not supported. [README](https://github.com/ggerganov/llama.cpp/blob/e8422de39e4aa2f7e50574124b060a80607e654a/README.md#description) shows Supported platforms.

**Comment by Revanth-guduru-balaji** [comment]
> > streamlit app
> 
> Not supported. [README](https://github.com/ggerganov/llama.cpp/blob/e8422de39e4aa2f7e50574124b060a80607e654a/README.md#description) shows Supported platforms.

how to load model once in memory and use concurrently

**Comment by staviq** [comment]
> how to load model once in memory and use concurrently

See #2813
