### ISSUE TITLE
Grammar freezes the sampling in specific case

### ISSUE THREAD

**Issue by Mihaiii** [ggerganov/llama.cpp#2971]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I want to let the model [think "step by step"](https://arxiv.org/abs/2205.11916) in order to increase the response accuracy and at the end I want to enforce a response format that I can parse in code.

Basically I want a grammar that enforce having any characters at the beginning, but at the end enforces a desired format (which in my case is a list of predefined options) that I can parse and further use in my code.

**All works ok if I change the grammar to only provide the list** (is not a hardware problem).

# Current Behavior

The issue is that either it doesn't output anything (if I use "*" instead of "+" where I want it to write any text), either is super slow in a sense that I have to kill the kernel because it doesn't generate anything for few minutes (maybe more, but I did not wait hours).

# Environment and Context

`$ lscpu`
<details>
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  128
  On-line CPU(s) list:   0-127
Vendor ID:               AuthenticAMD
  Model name:            AMD EPYC 7543 32-Core Processor
    CPU family:          25
    Model:               1
    Thread(s) per core:  2
    Core(s) per socket:  32
    Socket(s):           2
    Stepping:            1
    Frequency boost:     enabled
    CPU max MHz:         2800.0000
    CPU min MHz:         1500.0000
    BogoMIPS:            5600.05
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc
                         a cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall n
                         x mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_go
                         od nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pc
                         lmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe
                          popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy sv
                         m extapic cr8_legacy abm sse4a misalignsse 3dnowprefetc
                         h osvw ibs skinit wdt tce topoext perfctr_core perfctr_
                         nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_s
                         ingle hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsba
                         se bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx sma
                         p clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves
                          cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clze
                         ro irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nr
                         ip_save tsc_scale vmcb_clean flushbyasid decodeassists 
                         pausefilter pfthreshold v_vmsave_vmload vgif umip pku o
                         spke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   2 MiB (64 instances)
  L1i:                   2 MiB (64 instances)
  L2:                    32 MiB (64 instances)
  L3:                    512 MiB (16 instances)
NUMA:                    
  NUMA node(s):          2
  NUMA node0 CPU(s):     0-31,64-95
  NUMA node1 CPU(s):     32-63,96-127
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
                          and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer
                          sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIB
                         P always-on, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
</details>

`$ uname -a`
<details>
Linux 3159a0813b8a 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
</details>

SDK version
<details>
```
$ python3 --version
$ make --version
$ g++ --version
```
Python 3.10.6
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</details>

# Failure Information (for bugs)

# Steps to Reproduce

Run the prompt from the attached (see below) log.txt using the attached grammar.txt (github doens't support uploading files with gnbf extension, but this is the content of grm.gbnf ).

If I change the content of the grammar to only provide the list, all works ok. But I need the model to write some text before that in order to let it "explain its thinking".

# Failure Logs

Here is the log:
[log.txt](https://github.com/ggerganov/llama.cpp/files/12504625/log.txt)
[grammar.txt](https://github.com/ggerganov/llama.cpp/files/12504619/grammar.txt)

**Comment by Mihaiii** [comment]
I'm gonna go ahead and close this since my use case is resolved by removing redundant whitespaces from the grammar.

**Comment by ggerganov** [comment]
Yes, technically the grammar works as expected. I also got confused recently, thinking there is a bug, but you just have to be careful what you give as input
