### ISSUE TITLE
[C0ffymachyne] was -gqa argument removed from the "main"  ? What is a replacement and how to load 70B model without it ?

### ISSUE THREAD

**Issue by c0ffymachyne** [ggerganov/llama.cpp#2975]

**Comment by Mihaiii** [comment]
It was removed, yes. You should use gguf now and wirh gguf you no longer need to manyally pass the gqa arg.

**Comment by andeplane** [comment]
By converting 70b to gguf with
```
  python3 convert-llama-ggmlv3-to-gguf.py --input models/llama-2-70b.ggmlv3.q4_1.bin --output models/llama-2-70b.gguf.q4_1.bin
```
I still get
```
error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  8192,  8192, got  8192,  1024,     1,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/Users/kvakkefly/repos/llama.cpp/models/llama-2-70b.gguf.q4_1.bin'
main: error: unable to load model
```
when running with latest master as of sept 5th.

**Comment by KerfuffleV2** [comment]
> By converting 70b to gguf with

You didn't mention you were converting from GGML file. You need to specify `--gqa 8` when converting the GGML to GGUF.

By the way, it's not a bad idea to run scripts like this with `--help` just to see what arguments it supports. You probably would have noticed there's a `--gqa` and it even tells you what to use for LLaMAv2 70B:

    --gqa GQA             grouped-query attention factor (use 8 for LLaMA2 70B)

**Comment by c0ffymachyne** [comment]
I also did convert to GGUF with -gqa 8 but the model started producing insensible gibberish so I gave up for now.

**Comment by KerfuffleV2** [comment]
> I also did convert to GGUF with -gqa 8 but the model started producing insensible gibberish so I gave up for now.

That's not really enough information to help you. Did you also specify `--eps` like I mentioned? It also may be an issue with the vocab not being converted correctly. You can try using the original model metadata when converting.

**Comment by c0ffymachyne** [comment]
I will try --eps. Thanks.
