### ISSUE TITLE
--server with docker port binding issue

### ISSUE THREAD

**Issue by Wheest** [ggerganov/llama.cpp#2992]
# Expected Behavior

I am using the docker image in `--server` mode so that I can use CURL to run inference.

If I have the server running on e.g., port 8181, then if I expose this port in some way I should be able to run inference on the host

# Current Behavior

There are three cases that I have tested, and the "common case" fails.

The common case is using port binding with docker.

```sh
docker run -p 8181:8181 --network bridge -v ${MODELS_PATH}:/models/ ghcr.io/ggerganov/llama.cpp:full --server -m /models/$TARGET_MODEL/ggml-model-q4_0.gguf -c 2048 -ngl 43 -mg 1 --port 8181
```

If I run a curl command on the host, e.g.,
```sh
curl --request POST \
    --url http://0.0.0.0:8181/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'
```
Then it fails with `curl: (56) Recv failure: Connection reset by peer`.

If I attach to the container directly with `docker exec -it [container_id] bash`, then I can run the CURL command succesfully, indicating that the model and server setup is correct here.

In addition, if instead of binding one port (`-p 8181:8181`), I expose the entire network of the container using `--network host`, then my CURL command works on the host.  However this is not ideal for security/isolation, or my docker compose workflow.

# Environment and Context

I have tested this on two Linux x86 OS setups, Debian and Ubuntu.  Using the offical llama.cpp docker scripts should mean that the impact of the environment should be minimal.

# Failure Information (for bugs)

There is no information in `docker logs`, it seems that the failed connection is not registered

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Run the docker container with a pre-converted model:
```
docker run -p 8181:8181 --network bridge -v ${MODELS_PATH}:/models/ ghcr.io/ggerganov/llama.cpp:full --server -m /models/$TARGET_MODEL/ggml-model-q4_0.gguf -c 2048 -ngl 43 -mg 1 --port 8181
``` 
2. Try to run a CURL command on the host
```sh
curl --request POST \
    --url http://0.0.0.0:8181/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'
```

**Comment by Wheest** [comment]
I believe that I have solved the issue.

By default, the `--host` in the docker container is [`127.0.0.1`](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md).  However, it appears that there is some firewall configuration or such in the container which makes access harder.  However, if we add the command `--host 0.0.0.0`, this bypasses the issue, and allows access for docker/docker compose.

**Comment by ScarlettZebra** [comment]
Given that the host needs to be changed in order to work inside the Docker container, shouldn't `--host 0.0.0.0` be the default?
