### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Exagram** [ggerganov/llama.cpp#30]
Will Linux be supported?

**Comment by G2G2G2G** [comment]
.... just compile it you literally have to clone it and type "make" read the readme...

**Comment by Lupul** [comment]
I compiled it and run it on Ubuntu 22.04 with AMD 5700G cpu and got ~300ms/token (7B), ~550ms/token (13B)

**Comment by noneistaken** [comment]
Works on Artix, i5-9400f. 180ms/tok on 7B.

**Comment by ggerganov** [comment]
Linux and Mac OS are full supported through the Makefile

**Comment by JonWhiteRA** [comment]
Is there a preferred version of gcc for linux?

**Comment by G2G2G2G** [comment]
bigger number = better
