### ISSUE TITLE
How GGML is different from ONNX

### ISSUE THREAD

**Issue by biswaroop1547** [ggerganov/llama.cpp#3022]
I am looking to create an exhaustive pros and cons list for ONNX vs GGML, and would like some help if someone can describe or give pointers on how GGML is different from ONNX.

Currently I am aware that GGML supports 4bit-quantization and follows a no-dependency approach (as mentioned [here](https://github.com/ggerganov/llama.cpp/issues/34#issuecomment-1503459503)), and the [format in which it creates the computation graph and stores the weights with optimizations (if any) is different](https://github.com/ggerganov/ggml/blob/6319ae9ad7bdf9f834b2855d7e9fa70508e82f57/examples/gpt-2/convert-cerebras-to-ggml.py#L67). 

Apart from this what are the differentiating factors here?

**Comment by wangpy1204** [comment]
I have the same problem as you

**Comment by casperdcl** [comment]
found some related issues as well:

- onnx [ggml#273](https://github.com/ggerganov/ggml/issues/273)
- torch & tf [ggml#41](https://github.com/ggerganov/ggml/discussions/41)
- ncnn [ggml#148](https://github.com/ggerganov/ggml/discussions/148)
- 2 formats [ggml#220](https://github.com/ggerganov/ggml/issues/220)
- SD request [ggml#303](https://github.com/ggerganov/ggml/discussions/303)
  + mentions [symisc/sod](https://github.com/symisc/sod)

**Comment by KerfuffleV2** [comment]
I think the question is a little ambiguous. GGML could mean the machine language library itself, the file format (now called GGUF) or maybe even an implementation based on GGML that can do stuff like run inference on models (llama.cpp).

From the GGML as a library side, there isn't really a "format" for the graph, there's an API you can use to construct the graph. Likewise for the weights, they don't have to come from a GGML/GGUF format file at all. Just for example, my little Rust RWKV implementation [over here](https://github.com/KerfuffleV2/smolrsrwkv/) actually only loads models for PyTorch or SafeTensors format files and dynamically quantizes the tensors.

**Comment by staviq** [comment]
Glancing through ONNX GitHub readme, from what I understand ONNX is just a "model container" format without any specifics associated inference engine, whereas GGML/GGUF are part of an inference ecosystem together with ggml/llama.cpp.

So the difference would be roughly similar to a 3d model vs unreal engine asset.

**Comment by biswaroop1547** [comment]
@staviq sorry for not being clear, but for inference onnx can use [onnxruntime](https://onnxruntime.ai/docs/tutorials/accelerate-pytorch/pytorch.html) which has [multiple backends](https://onnxruntime.ai/docs/execution-providers/)/ [optimisations support](https://onnxruntime.ai/docs/performance/model-optimizations/).

**Comment by staviq** [comment]
> 

I see, thank you for clarification.
