### ISSUE TITLE
Problem with  compilation with gpu support 

### ISSUE THREAD

**Issue by vulkomilev** [ggerganov/llama.cpp#3032]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

When I am trying to compile the project with 
cmake ..  -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.2/bin/nvcc
I am getting as an error:
-- cuBLAS found
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda-11.2/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp;-gencode=arch=compute_80,code=sm_80 -v

  

  The output was:

  1

  gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or
  directory

  compilation terminated.

  nvcc fatal : Failed to preprocess host compiler properties.

  

  

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:282 (enable_language)

**Comment by staviq** [comment]
Try with PATH="/usr/local/cuda-11.2/bin/${PATH}" cmake

Instead of -DCMAKE_CUDA_COMPILER

**Comment by vulkomilev** [comment]
it is not working

**Comment by vulkomilev** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

**Comment by staviq** [comment]
Ok, tell me if `nvcc --version` ( without the full path ) returns the same
And if `g++ --version` works.

**Comment by Fanisting** [comment]
@staviq Hi, I have also failed in the compilation. 

The output of `nvcc --version` and `g++ --version` are:
```
root@autodl-container-58c811ac3c-a7500461:~/autodl-tmp/llama.cpp# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```
and 
```
root@autodl-container-58c811ac3c-a7500461:~/autodl-tmp/llama.cpp# g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by staviq** [comment]
The problem basically is that nvcc needs to be able to call g++ or gcc in the background. If any of those aren't in the $PATH, they can't be invoked just by name, hence the "execvp: No such file or directory".

Either gcc/g++ isn't installed ( yes, you can have one installed without the other ), or the system $PATH is wrong, and they aren't seen by the shell, unless you call them by their full absolute path.

NVIDIA CUDA installers are dumb and often the $PATH doesn't get updated, or even worse, it does, but with wrong directory.

If cmake doesn't work, try using make or vice-versa, make sure nvcc, gcc and g++ are in the $PATH and can be called by short name, and do not use sudo. Also, nvcc has a minimum required gcc/g++ version so make sure your system is reasonably up to date.

**Comment by Fanisting** [comment]
> The problem basically is that nvcc needs to be able to call g++ or gcc in the background. If any of those aren't in the $PATH, they can't be invoked just by name, hence the "execvp: No such file or directory".
> 
> Either gcc/g++ isn't installed ( yes, you can have one installed without the other ), or the system $PATH is wrong, and they aren't seen by the shell, unless you call them by their full absolute path.
> 
> NVIDIA CUDA installers are dumb and often the $PATH doesn't get updated, or even worse, it does, but with wrong directory.
> 
> If cmake doesn't work, try using make or vice-versa, make sure nvcc, gcc and g++ are in the $PATH and can be called by short name, and do not use sudo. Also, nvcc has a minimum required gcc/g++ version so make sure your system is reasonably up to date.

I finally solve the issue by modifying the Makefile, in which one line should be changed from:
```
NVCCFLAGS += -arch=native
```
to:
```
NVCCFLAGS += -arch=sm_86
```

then `make` works well. For me, the answer is `sm_86` since I am using a RTX 3090 (24G).

**Comment by staviq** [comment]
@Fanisting The `-arch=native` should automatically be equivalent to `-arch=sm_X` for the exact GPU you have, and that's according to Nvidia documentation. I would like to confirm it's actually a bug in llama.cpp because every commit, scripts are building the source code for testing, with CUDA too, and don't have problems like this, I'm just unsure whether this is related to your specific PC or there's actually a bug somewhere.

In case this is actually a bug in llama.cpp, I'd like to fix it, but I cannot reproduce this problem.

If you can, post what `nvidia-smi` outputs.

**Comment by kaixuanjames** [comment]
> # Prerequisites
> Please answer the following questions for yourself before submitting an issue.
> 
> * [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
> * [ X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
> * [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
> * [ X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.
> 
> When I am trying to compile the project with cmake .. -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.2/bin/nvcc I am getting as an error: -- cuBLAS found CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message): Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
> 
> Compiler: /usr/local/cuda-11.2/bin/nvcc
> 
> Build flags:
> 
> Id flags: --keep;--keep-dir;tmp;-gencode=arch=compute_80,code=sm_80 -v
> 
> The output was:
> 
> 1
> 
> gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
> 
> compilation terminated.
> 
> nvcc fatal : Failed to preprocess host compiler properties.
> 
> Call Stack (most recent call first): /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD) /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test) /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID) CMakeLists.txt:282 (enable_language)

May I ask if you deployed on windows or Linux?

**Comment by Fanisting** [comment]
> @Fanisting The `-arch=native` should automatically be equivalent to `-arch=sm_X` for the exact GPU you have, and that's according to Nvidia documentation. I would like to confirm it's actually a bug in llama.cpp because every commit, scripts are building the source code for testing, with CUDA too, and don't have problems like this, I'm just unsure whether this is related to your specific PC or there's actually a bug somewhere.
> 
> In case this is actually a bug in llama.cpp, I'd like to fix it, but I cannot reproduce this problem.
> 
> If you can, post what `nvidia-smi` outputs.

So my output is:
```
root@autodl-container-58c811ac3c-a7500461:~/autodl-tmp/llama.cpp# nvidia-smi
Wed Sep 13 04:11:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:52:00.0 Off |                  N/A |
| 30%   28C    P8    20W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by kaixuanjames** [comment]
Wed Sep 13 09:24:56 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA
Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile
Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util
 Compute M. |
|                                         |                      |
      MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 6000              WDDM  | 00000000:00:0F.0  On |
         Off |
| 33%   30C    P8              11W / 260W |    444MiB / 24576MiB |      5%
     Default |
|                                         |                      |
         N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:
             |
|  GPU   GI   CI        PID   Type   Process name
 GPU Memory |
|        ID   ID
  Usage      |
|=======================================================================================|
|    0   N/A  N/A      3624    C+G   ...5n1h2txyewy\ShellExperienceHost.exe
   N/A      |
|    0   N/A  N/A      6228    C+G   ...h2txyewy\InputApp\TextInputHost.exe
   N/A      |
|    0   N/A  N/A      7280    C+G   C:\Windows\explorer.exe
    N/A      |
|    0   N/A  N/A      7700    C+G   ...crosoft\Edge\Application\msedge.exe
   N/A      |
|    0   N/A  N/A      8848    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe
   N/A      |
+---------------------------------------------------------------------------------------+

**Comment by kaixuanjames** [comment]
thank you

**Comment by kaixuanjames** [comment]
As far as I know, if Alpaca-2 is a pytorch version weight, use the
llama.cpp tool for quantitative deployment; if Alpaca-2 is a HuggFace
version weight, use transformers for inference or use text-generation-webui
to build the interface.May I ask if you understand

**Comment by deonis1** [comment]
Try this: 
Clone the repository:
git clone https://github.com/ggerganov/llama.cpp.git
Build Lllama.cpp 

cd llama.cpp
sed -i 's/-arch=native/-arch=all/g' Makefile
make clean && LLAMA_CUBLAS=1 make -j

**Comment by staviq** [comment]
In the meantime, I found some mentions on Nvidia forums, of similar issues, and long story short, it might be a problem with nvcc/gcc combination, and people were saying it helps if you remove `-std=cppWhatever` from nvcc arguments, it will default to what cuda wants, and that fixed similar problem for some people.

Though I still can't reproduce this problem, even when I tried on the same version if Ubuntu.

**Comment by sraeuchle** [comment]
Same issue here:

linux mint 21 up-to-date
cuda 12.2
Nvidia Driver Version: 535.129.03
gcc 12.3.0
g++ 11.4.0
GPU: Nvidia 4700 (mobile)

Error message:
```
      CMake Error at /tmp/pip-build-env-mqklkz36/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:753 (message):
        Compiling the CUDA compiler identification source file
        "CMakeCUDACompilerId.cu" failed.
      
        Compiler: /usr/local/cuda/bin/nvcc
      
        Build flags:
      
        Id flags: --keep;--keep-dir;tmp -v
      
      
      
        The output was:
      
        1
      
        gcc: fatal error: cannot execute ‘cc1plus’: execvp: Datei oder
        Verzeichnis nicht gefunden
      
        compilation terminated.
      
        nvcc fatal : Failed to preprocess host compiler properties.
      
      Call Stack (most recent call first):
        /tmp/pip-build-env-mqklkz36/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
        /tmp/pip-build-env-mqklkz36/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
        /tmp/pip-build-env-mqklkz36/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
        vendor/llama.cpp/CMakeLists.txt:262 (enable_language)
```
