### ISSUE TITLE
small optimization for q4_0 to q5_1 quants in ggml.c

### ISSUE THREAD

**Issue by Swight1423** [ggerganov/llama.cpp#3039]
in ggml.c in the quantize_row_q(4-5)_(0-1)_reference functions I noticed that if d = 0 the qs and qh variables become fixed because all the variables zero out due to multiplication. so when d=0 you could replace these calculations with just storing the fixed value. This may apply to other quants but the code is too complicated for me to verify.

**Comment by Swight1423** [comment]
Looks like this also sort of applies to the dequants of these quants where d=0 makes the y[] elements =0 for 4_0 and 5_0 or =m for 4_1 and 5_1

**Comment by KerfuffleV2** [comment]
I think those reference implementations are deliberately not optimized. The motivation for having a reference implementation is that it's very clear and obviously correct. The behavior/output for optimized implementations can be compared to the reference to make sure _they_ work correctly (simplicity/clarity is also good for trying to understand the algorithm).
