### ISSUE TITLE
Disconnecting CUDA device shouldn't crash process

### ISSUE THREAD

**Issue by theolivenbaum** [ggerganov/llama.cpp#3045]
# Expected Behavior

Process shouldn't hard-crash when CUDA devices list changes, and instead return an error message for inferencing.

# Current Behavior

Crash with the following message:

CUDA error 999 at ggml-cuda.cu:5146: unknown error

# Environment and Context

Running on Windows with an e-GPU attached to the laptop, but this probably will affect laptops going to sleep as well. Using the LlamaSharp wrapper, but the issue also happens when running llama.cpp as server.

# Steps to Reproduce

1) Use llama.cpp (using wrapper or as server)
2) Put laptop to sleep
3) Disconnect eGPU
4) Turn laptop back on
5) Try using inferencing again. Doesn't matter if eGPU was reconnected or not, it crashes either way.

**Comment by staviq** [comment]
eGPUs are notoriously not hotpluggable, despite manufacturers claims.

This isn't specific to llama.cpp.

**Comment by theolivenbaum** [comment]
That's for sure - I was just hoping llama.cpp would return some sort of error instead of hard crashing the process.

**Comment by JohannesGaessler** [comment]
Let me be frank: dynamically adding and removing hardware is such a niche use case that I personally will most likely never take the time to implement considerations for it. I will review other people's PRs though if they want to do it.

**Comment by theolivenbaum** [comment]
Agreed, but this affects also any other CUDA errors. In any case, I've moved it to an out of process hosting and I'll just handle the crashing instead. I'll close the issue then!
