### ISSUE TITLE
Zig build configuration on windows requires adjustments

### ISSUE THREAD

**Issue by flameoftheforest** [ggerganov/llama.cpp#3046]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
Building all exe without problem

# Current Behavior
Failed to build everything except `quantize.exe`

# My Fix
* I followed the steps in the Readme.md to use Zig to build the llama.cpp executables.
* I am required to make a few adjustments in order to get that properly done, here are the changes i made:
  * `build-info.h` is missing, i created a `build-info.h` manually in `common` and inserted the `BUILD_NUMBER`, `BUILD_COMMIT` manually.
  * `build.zig` i made the following changes:
```
    const common = make.obj("common", "common/common.cpp");
    const console = make.obj("common", "common/console.cpp");
    const grammar_parser = make.obj("grammar-parser", "common/grammar-parser.cpp");
```
  * `common.h`, `console.h`, `grammar-parser.h` & `build-info.h` referred in `embeddings.h`, `main.h`, `perplexity.h`, `server.cpp`, `train-text-from-scratch.cpp` cannot be found, the `#include "xx.h"` should be adjusted to `#include "../../common/xx.h"`

**Comment by ntinkler-calendly** [comment]
This is also impacting builds on apple silicon.  Exact same issue and the same resolution.
