### ISSUE TITLE
server mode, stops, how to make it continue without gibberish output on subsequent continuation?

### ISSUE THREAD

**Issue by hiqsociety** [ggerganov/llama.cpp#3056]
with reference to this, i think it should be considered a bug
https://github.com/ggerganov/llama.cpp/discussions/3055

it's truly great effort and hope to see this resolve.
keep up the great work!
![Screenshot from 2023-09-07 10-41-34](https://github.com/ggerganov/llama.cpp/assets/51492452/d5d277cf-986d-4ee8-b98b-5abb2ef32adc)

**Comment by staviq** [comment]
If you're open th developer tools in the browser, in its console there will be a line with your request and it will have a filed telling you the stop reason.

It's possible that it reached output token limit the first time, if you didn't specify it in server parameters, and the second message caused it to overflow the context length and it could no longer see your original question.
