### ISSUE TITLE
(Falcon 180B) ARM - gibberish output with k-quants

### ISSUE THREAD

**Issue by BarfingLemurs** [ggerganov/llama.cpp#3067]
build: 00d62ad (built using cmake in termux)
model: https://huggingface.co/TheBloke/Falcon-180B-Chat-GGUF "Q4_K_M"
-Model was repieced and generates normal sentence on x64 PC with mmap/streaming support.

Log: https://pastebin.com/FJbC97Du

edit: A 40B model https://huggingface.co/YokaiKoibito/falcon-40b-GGUF/blob/main/falcon-40b-Q4_K_M.gguf  generates normally.

**Comment by BarfingLemurs** [comment]
Q4_0 produces correct sentences,
Q4_K_M (possibly other k-quants) not working for ARM?

**Comment by KernelBypass** [comment]
Same issue on `M3Max` ARM Mac:
1. Using `falcon-180b.Q4_K_M.gguf` 
2. Downloaded it from HuggingFace as 3 splits and concatenated using:
`cat falcon-180b.Q4_K_M.gguf-split-* > falcon-180b.Q4_K_M.gguf && rm falcon-180b.Q4_K_M.gguf-split-*`
3. Modelfile is just `FROM falcon-180b.Q4_K_M.gguf`
4. Built using `ollama create falcon180b -f Modelfile`
4. All the models from `Ollama`'s built-in library run fine.

Gibberish output:
```
% ollama run falcon180b "hi"
EnNeAbDePerLaQuLeDeElElPrDeAbBrNeQuQLaTeNeIndPlClElBlEdElCoLaMinNeNeNeNeElTrEnSc
```
Outputs one 2-letter combination (e.g. `En`, `Ne`, `Ab`...) per second, probably infinitely (I abort it after a while).
