### ISSUE TITLE
Different results depending on whether Metal is used or not

### ISSUE THREAD

**Issue by ungil** [ggerganov/llama.cpp#3072]
With the current version (commit 6336d834ec7bff3e93e24182c0f609d2f2bdce26) the results obtained using Metal are different from the ones obtained if GPU inference is disabled (at run time or build time). 

I don't think that's expected behaviour (or is it?).

Here is an example using the "embedding" executable:

% make clean; make; ./embedding -m models/codellama-7b.Q5_K_M.gguf -p "testing embeddings"| head -c55
0.269198 -0.726440 0.176168 0.309597 0.036036 0.515290 

% ./embedding -m models/codellama-7b.Q5_K_M.gguf -p "testing embeddings" -ngl 0| head -c55
0.238013 -0.759392 0.238562 0.293890 0.026346 0.592973

% make clean; LLAMA_NO_METAL=1 make; ./embedding -m models/codellama-7b.Q5_K_M.gguf -p "testing embeddings"| head -c55
0.238013 -0.759392 0.238562 0.293890 0.026346 0.592973

**Comment by ikawrakow** [comment]
When a quantized model runs on the CPU, activations are quantized to 8 bit (`Q8_0` or `Q8_K`, depending on quantization scheme), and the `model weight x activation` matrix multiplications are performed with these quantized activations.

When run on Metal, these matrix multiplications are performed directly with the `fp32` values.

Hence, it is expected that the numerical values of the resulting embeddings will be different. But if one looks at something like perplexity, the difference between the CPU and Metal is typically within `0.002`, so basically within the noise.

The main reason to use quantized activations on the CPU is performance. Matrix multiplications between quantized model weights and `fp32` activations are much slower.

**Comment by ungil** [comment]
Thanks for that detailed reply. I had missed the implementation change. Before https://github.com/ggerganov/llama.cpp/releases/tag/master-bf83bff the results were the same and my tests passed regardless of whether Metal was used or not, I'll have to take that into account now.
