### ISSUE TITLE
量化与部署的问题

### ISSUE THREAD

**Issue by kaixuanjames** [ggerganov/llama.cpp#3077]
在windows系统中使用llama.cpp编译产生的可执行文件运行时没有任何反应，比如，利用quantize.exe量化FP16模型时，没有任何反应，也不报错
![13ea5cb8ad9eb2eaafccbcca7b2488d](https://github.com/ggerganov/llama.cpp/assets/133489631/a2db25bc-4d61-42cc-9c05-c217d81314f5)

**Comment by KerfuffleV2** [comment]
我猜可能是一个和CUDA相关的问题。您能不能试一下一个没有CUDA的本版？

另外，我也听说过当在cmd.exe中软件崩溃时，它没办法报告问题。您如果有WSL（Windows Subsystem for Linux)，在那儿启动软件可能有效。

对不起，我的中文很差。希望您还是能读得懂我的意思。

***

They said when they try to start the executables like `quantize.exe` in Windows there's no result. I suggested trying a non-CUDA version or running it in WSL to get a better error message.

**Comment by staviq** [comment]
(Google translate)

Windows 10 cmd 支持重定向，您可以使用 `program.exe > file.txt` 使其将输出写入文件，然后您可以在文本编辑器中打开该文件，看看它是否真的是空的，或者它有输出但 可能编码错误。

如果您这样做并将该文件发送到此处，我们将能够更好地了解问题所在。

***

Windows 10 cmd supports redirections, you can use `program.exe > file.txt` to make it write output to a file, and then you can open that file in text editor and see if it's really empty, or it's has the output but possibly encoding is wrong.

If you do that and send that file here, we will be able to better see what is wrong.

**Comment by KerfuffleV2** [comment]
> Windows 10 cmd supports redirections

Are you sure that will help here? It would have to produce output in the file that wasn't visible in the console. I'm not a Windows person but I don't think that would be the case.

I think it's probably segfaulting but since it's running in `cmd.exe` the program crashing doesn't get reported. I vaguely recall that running in WSL can help in that sort of situation.

**Comment by staviq** [comment]
@KerfuffleV2 It would definitely tell me whether output isn't generated or simply isn't displayed, which should narrow the problem down quite a bit.

Honestly, doing file redirection and simply looking at the file size ( zero, non-zero ) would do, I just kept the comment simple because Google translate.

**Comment by fallenangelblog** [comment]
遇到相同的问题，CUDA_PATH环境变量设置了就好了。

**Comment by KerfuffleV2** [comment]
> 遇到相同的问题，CUDA_PATH环境变量设置了就好了。

那么，现在问题都解决了吗？

**Comment by kaixuanjames** [comment]
> 遇到相同的问题，CUDA_PATH环境变量设置了就好了。

请问您能详细说一下吗？是把cuda_path.py的路径添加到环境变量里吗

**Comment by kaixuanjames** [comment]
> 我猜可能是一个和CUDA相关的问题。您能不能试一下一个没有CUDA的本版？
> 
> 另外，我也听说过当在cmd.exe中软件崩溃时，它没办法报告问题。您如果有WSL（Windows Subsystem for Linux)，在那儿启动软件可能有效。
> 
> 对不起，我的中文很差。希望您还是能读得懂我的意思。
> 
> They said when they try to start the executables like `quantize.exe` in Windows there's no result. I suggested trying a non-CUDA version or running it in WSL to get a better error message.

试了一下没有CUDA的版本，还一样的问题

**Comment by KerfuffleV2** [comment]
抱歉，我以为您在说问题解决了。恐怕我对Windows系统的环境变量不太清楚。

我原来的建议是为了减少问题可能产生的原因而提出的。比如说，如果您试图一个略去CUDA的版本，后来就发现毛病不见了，这意味着问题肯定是与CUDA相关的。因为您已经试过没有CUDA的版本，我们现在就不能怪CUDA了。

您有WSL没有？如果可以，请在WSL中执行本软件。我最后的希望是这样做会让它能够告诉您问题到底是什么样的东西。

***

They said they tried a non-CUDA version and still had the same problem. I just suggested trying to run it in WSL again, that's the only thing I can think of to try at this point.

I'm pretty sure it's just segfaulting at startup and the error isn't showing up in `cmd.exe`.

**Comment by goerch** [comment]
> I'm pretty sure it's just segfaulting at startup and the error isn't showing up in cmd.exe.

Segfaults can be monitored in `eventvwr`.

**Comment by kaixuanjames** [comment]
> 抱歉，我以为您在说问题解决了。恐怕我对Windows系统的环境变量不太清楚。
> 
> 我原来的建议是为了减少问题可能产生的原因而提出的。比如说，如果您试图一个略去CUDA的版本，后来就发现毛病不见了，这意味着问题肯定是与CUDA相关的。因为您已经试过没有CUDA的版本，我们现在就不能怪CUDA了。
> 
> 您有WSL没有？如果可以，请在WSL中执行本软件。我最后的希望是这样做会让它能够告诉您问题到底是什么样的东西。
> 
> They said they tried a non-CUDA version and still had the same problem. I just suggested trying to run it in WSL again, that's the only thing I can think of to try at this point.
> 
> I'm pretty sure it's just segfaulting at startup and the error isn't showing up in `cmd.exe`.

thank you !

**Comment by dh12306** [comment]
解决了吗，一模一样

**Comment by Furyial** [comment]
问题一模一样，我重新安装了Cuda环境并没有解决问题。我也是用powershell运行quantize.exe那里一点反应都没有，cmd中找不到啥东西。最后通过安装以前的版本（编号2211左右），这回FP16生成的是.bin，然后quantize不变，前面把gguf改成bin就行了，亲测可用
