### ISSUE TITLE
Text file summarization 

### ISSUE THREAD

**Issue by slavag** [ggerganov/llama.cpp#3094]
Hi,
I'm trying to summarize text file, about 10kb length.
But when I'm running with -f I'm getting error : "main: error: prompt is too long (3901 tokens, max 508)"
of course I'm doing something wrong, can you please tell me what is the correct way to do text file summarization ?

Thanks

**Comment by KerfuffleV2** [comment]
The context size (`-c`, assuming you're using the `main` example) controls the total number of tokens the model can deal with. This is the number of tokens in the prompt and any output.

Individual models also have a maximum context limit they can deal with. LLaMA2 models generally have this set to 4,096. There are some models that are specifically trained to support longer context sizes, there are also some tricks to let models support larger sizes than they would normally (like setting the rope scaling parameters).

Also keep in mind that the larger the context is, the more memory will be required. So don't go too crazy and do something like `-c 100000` even if the model supports it unless you actually have enough memory.

**Comment by slavag** [comment]
Thanks a lot.
Is there any way to summerize big file in chunks with llama.cpp? As from your answer I understand that for llama2 I can use up to 4096.

**Comment by KerfuffleV2** [comment]
> Or in other words, how can I work with files, that larger than model context window size?

The short answer is that you basically can't. There are some tricks for stretching the context size, like if you summarized the chunks then you wouldn't need to leave as much stuff in the context but of course you lose information every time you do that.

The context basically sets how much stuff can be in the LLM's brain at one time. That includes the prompt and its own output. You could try increasing `--rope-scale` — this may or may not produce good results (personally I haven't had too much luck with it). `--rope-scale 2` will basically double the context limit and so on. See: https://github.com/ggerganov/llama.cpp/tree/master/examples/main#extended-context-size

There are also models that have been trained to handle having rope scaling applied better and models that just naturally have been trained to have a native longer context size. Generally speaking though, to be able to summarize more data you need to increase the context size in some way.

**Comment by slavag** [comment]
Thanks a lot. Will try.

**Comment by staviq** [comment]
I'd your source text isn't insanely longer that the context size, you could manually divide it, into smaller parts, ask LLM to summarise those partials, stitch the summaries together, and give it back to the LLM to summarise those summaries again. If it makes sense.

Results aren't as good as one would hope, but can be usable.

Keep in mind each time, the full source text, your prompt, and the LLMs answer, have to fit in the context to get coherent results.

**Comment by mechanicmuthu** [comment]
One thing to note here is 4096 is the sum of input + output tokens expected. Not just the input. There are some models which are trained on 32k context length, you can try them. Or you can do the rope scaling as available in the -h command line in main executable.
