### ISSUE TITLE
memory allocation/deallocation mismatch at 0x55d37b9eca20: allocated with malloc being deallocated with delete Aborted (core dumped)[User] Insert summary of your issue or enhancement..

### ISSUE THREAD

**Issue by phalexo** [ggerganov/llama.cpp#3105]
Ubuntu 20.04
gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0 # same with 10
g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0 # same with 10
Python 3.10.12

core dumped immediately on attempt to load.

**Comment by phalexo** [comment]
p.s. The initial error was about an "illegal instruction" but the malloc/delete issue was brought up from gdb.

**Comment by goerch** [comment]
Maybe you should be reporting over [there](https://github.com/abetlen/llama-cpp-python)?

**Comment by phalexo** [comment]
> Maybe you should be reporting over [there](https://github.com/abetlen/llama-cpp-python)?

Python does not have "malloc" C/C++ does. I have browsed through llama.cpp. Lots of "malloc" and lots of "delete."

Not clear why you think I should look at a Python module that is nothing more than an interface to the code here.

**Comment by phalexo** [comment]
Had to do with specialized acceleration instructions for different CPUs. Suppressing F16C (and maybe AVX2) eliminated the problem.
