### ISSUE TITLE
How can I use huggingface model?

### ISSUE THREAD

**Issue by turk** [ggerganov/llama.cpp#3109]
Hi. I trained a model with huggingface autotrain tool and got the result.

![image](https://github.com/ggerganov/llama.cpp/assets/13450420/67666272-df84-4e6d-abd5-cc5c76a0ec01)

but I couldn't convert the model using convert.py

Do you have any suggestions about it?

**Comment by KerfuffleV2** [comment]
Is it a LLaMA version 1 or 2 model? `convert.py` only supports LLaMA-type models. `llama.cpp` right now only support LLaMa and Falcon models (with a different conversion script).

**Comment by Green-Sky** [comment]
`convert.py` expects a `config.json` for models, however you seem to have trained an `adapter`, is that a lora?

**Comment by turk** [comment]
@KerfuffleV2 I used llama-2

@Green-Sky I used huggingface autotrain tool.

**Comment by Green-Sky** [comment]
can you show us the files in the `checkpoint-600` dir ?

**Comment by turk** [comment]
@Green-Sky  sure!

![image](https://github.com/ggerganov/llama.cpp/assets/13450420/5f40cc56-11de-4d6f-8bd5-42ed1a2c70ed)

**Comment by Green-Sky** [comment]
hm so the *same*. can you show us the inside of the `adapter_config.json` (either root or checkpoint subfolder is fine)

**Comment by turk** [comment]
both file have same data

`{
  "auto_mapping": null,
  "base_model_name_or_path": "TinyPixel/Llama-2-7B-bf16-sharded",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 16,
  "revision": null,
  "target_modules": [
    "q_proj",
    "v_proj"
  ],
  "task_type": "CAUSAL_LM"
}`

**Comment by turk** [comment]
@Green-Sky @KerfuffleV2 thx guys!

**Comment by KerfuffleV2** [comment]
All Green-Sky, I didn't do anything. :)

**Comment by deonis1** [comment]
You can get all the models in gguf format on theBlokes channel https://huggingface.co/TheBloke/orca_mini_v3_7B-GGUF/tree/main
