### ISSUE TITLE
llama_model_loader prints entire tensor

### ISSUE THREAD

**Issue by phdykd** [ggerganov/llama.cpp#3119]
I downloaded the llama2 models from meta to my local computer (m2 max macbook).

then, i run this # CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python

then, i am using this code  llm = LlamaCpp(
        model_path=selected_model,
        n_ctx=5000,
        max_tokens=5000,
        n_gpu_layers=1,
        n_batch=512,
        f16_kv=True,
        callback_manager=callback_manager,
        verbose=True
    )

but it prints entire tensors along with its answer. the following list continues.
how can i not display this llama_model_loader with its tensors.
![Screenshot 2023-09-11 at 12 14 06 AM](https://github.com/ggerganov/llama.cpp/assets/72084102/3a45c11b-4166-47e3-aaaf-83186397cd73)

lama_model_loader: loaded meta data with 16 key-value pairs and 363 tensors from /Users/phdykd/Code/llama2/llama2_bot_test/model/llama2_13b_chat_ggml-model-q4_0.gguf (version GGUF V2 (latest))
llama_model_loader: - tensor    0:                token_embd.weight q4_0     [  5120, 32000,     1,     1 ]
llama_model_loader: - tensor    1:               output_norm.weight f32      [  5120,     1,     1,     1 ]
llama_model_loader: - tensor    2:                    output.weight q6_K     [  5120, 32000,     1,     1 ]
llama_model_loader: - tensor    3:              blk.0.attn_q.weight q4_0     [  5120,  5120,     1,     1 ]
llama_model_loader: - tensor    4:              blk.0.attn_k.weight q4_0     [  5120,  5120,     1,     1 ]
llama_model_loader: - tensor    5:              blk.0.attn_v.weight q4_0     [  5120,  5120,     1,     1 ]
llama_model_loader: - tensor    6:         blk.0.attn_output.weight q4_0     [  5120,  5120,     1,     1 ]
llama_model_loader: - tensor    7:            blk.0.ffn_gate.weight q4_0     [  5120, 13824,     1,     1 ]
llama_model_loader: - tensor    8:            blk.0.ffn_down.weight q4_0     [ 13824,  5120,     1,     1 ]
llama_model_loader: - tensor    9:              blk.0.ffn_up.weight q4_0     [  5120, 13824,     1,     1 ]
llama_model_loader: - tensor   10:           blk.0.attn_norm.weight f32      [  5120,     1,     1,     1 ]

**Comment by staviq** [comment]
You might have a better luck asking in the python bindings project here: https://github.com/abetlen/llama-cpp-python

Those lines are printed to stderr, so it seems to me like it's a problem with the python bindings, passing stderr to the output.
