### ISSUE TITLE
Add OpenBSD support

### ISSUE THREAD

**Issue by kevlo** [ggerganov/llama.cpp#313]
This patch adds OpenBSD support, thanks.
[patch-llama.cpp.txt](https://github.com/ggerganov/llama.cpp/files/11013172/patch-llama.cpp.txt)

**Comment by j-f1** [comment]
Would you be willing to format this as a pull request so we can more easily incorporate it?

**Comment by kevlo** [comment]
@j-f1 Done.  Thanks.

**Comment by prusnak** [comment]
Fixed by https://github.com/ggerganov/llama.cpp/pull/314
