### ISSUE TITLE
[Feature Request] Support InternLM Deploy

### ISSUE THREAD

**Issue by vansinhu** [ggerganov/llama.cpp#3133]
Dear llama.cpp developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. [InternLM](https://github.com/InternLM/InternLM) is a large language model similar to llama2, and we look forward to InternLM being supported in llama.cpp. If there are any challenges or inquiries regarding support for InternLM, please feel free to join our Discord discussion at https://discord.gg/gF9ezcmtM3. 

Best regards,
vansinhu

**Comment by l29ah** [comment]
I've tried to run internlm-20b, converted and quantized apparently fine, but when running it i get `GGML_ASSERT: llama.cpp:2349: codepoints_from_utf8(word).size() > 0`.

**Comment by chigkim** [comment]
Still not supported, should be reopen

**Comment by shaunck96** [comment]
how to ensure llamacpp hosted internlm gguf version leverages GPU using installation ? any specific version of llamacpp I should be using ?

**Comment by shaunck96** [comment]
@chigkim you need to upgrade llamacpp version to leverage internlm quantized version. But I cant seem to get GPU working for inference
