### ISSUE TITLE
Error with chat-persistent on Windows.

### ISSUE THREAD

**Issue by simeoncapy** [ggerganov/llama.cpp#3141]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When I run the code written in the section `Persistent Interaction` to test this possibility, I expect to have the permanent chat run.

# Current Behavior

I got an error:
```
~/Documents/GitHub/llama_cpp $ PROMPT_CACHE_FILE=chat.prompt.bin CHAT_SAVE_DIR=./chat/default ./examples/chat-persistent.sh
./examples/chat-persistent.sh: line 32: syntax error: unexpected "("
```

I tried to delete the pair of parenthesis, but then I got this error:
```
~/Documents/GitHub/llama_cpp $ PROMPT_CACHE_FILE=chat.prompt.bin CHAT_SAVE_DIR=./chat/default ./examples/chat-persistent.sh
./examples/chat-persistent.sh: line 32: ./models/13B/ggml-model-q4_0.gguf: Permission denied
```

NB: I modified the extension of the model from `.bin` to `.gguf` into the `/chat-persistent.sh` file.

# Environment and Context

This bug appears if I am running the script with the `w64devkit`, but if I use WSL it works on this line. However WSL fails to run the main script, I guess it cannot manage the `.exe` contrary to the dev kit:

```
./examples/chat-persistent.sh: line 65: ./main: No such file or directory
```

For example, this command works perfectly on the devkit, but not on WSL:
```
./main -m ./models/13B/ggml-model-q4_0.gguf -n 256 --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt
```

## Hardware/Software specs:
* OS: Windows 11 Pro 22H2 
* RAM: 16 GB
* CPU: AMD Ryzen 5 4600H with Radeon Graphics            3.00 GHz
* GPU: NVIDIA GeForce RTX 3050 Laptop GPU
* Python 3.11.3
* GNU Make 4.4  Built for x86_64-w64-mingw32
* g++ (GCC) 13.2.0

# Steps to Reproduce

Run the commands above on Windows inside the  `w64devkit`.

# Failure Logs

See the messages above.

**Comment by staviq** [comment]
Turns out, w64ddevkit doesn't have `bash`, but instead it comes with busybox `sh` renamed to bash.exe. In fact, `bash`, `ash`, and `sh` are the same busybox basic shell.

That means, bash scripts simply won't work on w64devkit, as it's shell doesn't even support bash arrays.
