### ISSUE TITLE
Using llama.cpp with Visual Studio Code

### ISSUE THREAD

**Issue by erlebach** [ggerganov/llama.cpp#3145]
Has anybody used Llama.cpp server with the "continue" extension in Visual Studio Code, where the server and the client on on separate machines? If so, could you please point me to the instructions or tell me directly? Thank you so much!   

Gordon

**Comment by staviq** [comment]
https://continue.dev/docs/reference/Models/llamacpp

You can make th server listen on `0.0.0.0` which makes it accessible over LAN.

**Comment by erlebach** [comment]
Thanks. I read the docs, and I still can't get things working.  So let's get into a little more detail. When you write that "you can make the server listen on 0.0.0.0 ...), you are referring to the llama.cpp server, correct? (based on the help files you pointed me to). Visual Studio Code is running on host A with IP 1.1.1.1, while Llama.cpp is running on host B with IP 2.2.2.2 . How should I set up the configuration file of continue (~/.continue/config.py) and what command should I use for "./server" in folder "llama.cpp"? I have not found this example described anywhere so far. Thanks, and sorry for seeming obtuse.  

Gordon

**Comment by staviq** [comment]
> you are referring to the llama.cpp server

Yes.

If you run server with parameters like in the example, the only thing you have to do is to replace `localhost` with the IP of the host running llama.cpp server, here: `server_url="http://localhost:8080"`, it's highlighted in red in the example.

It doesn't matter if you connect to it with vscode or with a browser. In fact, connect to it with a browser first, you will see whether it works right away.

**Comment by erlebach** [comment]
Hi @stavik, 

Correct me if I am wrong, but the following statement: 
```
config = ContinueConfig(
    ...
    models=Models(
        default=LlamaCpp(
            max_context_length=4096,
            server_url="http://localhost:8080")
    )
)
``` 
will only work if the continue extension is on the same machine as the machine running the llama.cpp server. How could it be otherwise if the server URL is localhost? Again, I have yet found one person who stated they were using continue extension on a machine with a different IP address than the machine running  llama.cpp. What am I misunderstanding.

**Comment by staviq** [comment]
Yes, you cannot have "localhost" there, you have to delete the word "localhost" and in its place put the IP address of the other host, the one running llama.cpp server.

**Comment by erlebach** [comment]
Thanks. As I thought. I tried that the other day, but it didn't work. But I have no specific question to ask at this time.
