### ISSUE TITLE
[Question] List of supported types while running server

### ISSUE THREAD

**Issue by jpadhye-cisco** [ggerganov/llama.cpp#3156]
I'm following the documentation for the HTTP server and able to run it successfully. I'd like to contain my responses in JSON format. What is the option that can be passed to the 'grammar'  key ?

I tried following and it doesn't work:

```
{
  "prompt": "process tp build a website",
  "grammar":"json"
}
```

**Comment by staviq** [comment]
It expects BNF, the part of the `server` UI that lets you paste JSON grammar is client side

**Comment by jpadhye-cisco** [comment]
@staviq  Thanks for your response. Could you please provide an example? If I want to constrain the output to json, what do I provide in the HTTP request payload as grammar?

**Comment by staviq** [comment]
You want to make the model "speak" in JSON, am I understanding this right ?

If so, you would want to give it BNF grammar describing JSON, I think this is what you are looking for: https://cswr.github.io/JsonSchema/spec/grammar/

And here is the readme for llama.cpp grammar: https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md

**Comment by KerfuffleV2** [comment]
There's actually a JSON grammar already in this repo: https://github.com/ggerganov/llama.cpp/blob/master/grammars/json.gbnf

Also https://github.com/ggerganov/llama.cpp/blob/master/grammars/json_arr.gbnf if you want the root object to be an array.

Of course, those grammars just mean _any_ valid JSON. If you want it to conform to a specific schema then you'd need to use a grammar that describes the schema.

There's a script to convert JSON schemas to grammars (I've never used it personally and I don't know anything more than that it's a thing that exists): https://github.com/ggerganov/llama.cpp/blob/master/examples/json-schema-to-grammar.py

**Comment by jpadhye-cisco** [comment]
@staviq Your understanding is correct. I've already looked at the files you have referred to. What I'm struggling to understand is how to pass the preference of grammar when using the HTTP APIs in the server mode. This document says that you pass a grammar option: https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md but there is no example shared of what the possible values are. 

The main object can be executed in following fashion by passing the grammar:

```
./main -m ./models/13B/ggml-model-q4_0.gguf -n 256 --grammar-file grammars/json.gbnf -p 'Request: schedule a call at 8pm; Command:'
```
How do I pass the grammar preference when working in server mode?

**Comment by jpadhye-cisco** [comment]
@KerfuffleV2 Thanks for your response. I don't want a specific schema but rather just a valid JSON. However, the important question is how to pass the grammar preference while running in server mode?

**Comment by KerfuffleV2** [comment]
I think you'd include the content of the grammar file in the request you submit: https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#api-endpoints

I guess the server also has a webpage it can serve or something (I've never used it). I glanced at it and it seems to have some sort of setting where you can set the grammar as well.

**Comment by jpadhye-cisco** [comment]
@KerfuffleV2 Thanks for the pointer. You are correct. You are expected to pass the grammar file in the UI . Your help is much appreciated. 
<img width="729" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/84595813/8c661f75-0429-4b09-9fda-76dd756194bd">
