### ISSUE TITLE
can't find '__main__' module in '/content/llama.cpp/examples/quantize'

### ISSUE THREAD

**Issue by YanaSSS** [ggerganov/llama.cpp#3165]
I convert model to gguf by adding it to models folder and running: 
`!python /content/llama.cpp/convert.py --outtype f32 /content/llama.cpp/models/llama2-bg`

Then I run: `!python /content/llama.cpp/examples/quantize /content/llama.cpp/models/llama2-bg/ggml-model-f32.gguf /content/llama.cpp/models/llama2-bg/{MODEL_NAME}-f32-q4_0.bin q4_0`
and I get this error specified in the title of the issue.

I work in Google Colab and use the latest version of llama.cpp. I work with CPU because no free units left.

**Comment by YanaSSS** [comment]
Well, I installed all extension packages for c++ in VS Code also mingw 64 and cmake.
I ran `cmake ..`, then `cmake --build .` and finally the code as it is shown in the Readme file: `./quantize ./models/llama2-model/ggml-model-f32.gguf ./models/llama2-model/ggml-model-q4_0.gguf q4_0` all in the VS Code terminal.

I have not run c++ code before and I am not sure even what I am doing. A little help would be very much appreciated. Thank you.

**Comment by staviq** [comment]
If you are using Windows, you can just download pre-build package, from here: https://github.com/ggerganov/llama.cpp/releases/tag/b1

You can't really compile those particular individual cpp files easily, use make or cmake.

With simple make, you just need to have your console be in the llama.cpp directory, and use `make` that's it, all compiled programs will be put in the same directory.

With cmake, you create a build directory and run cmake, like in the project readme, from there, and your compiled programs will be in the "build/bin" directory.

**Comment by YanaSSS** [comment]
Thank you, thank you, thank you :)
