### ISSUE TITLE
Error when loading Llama model from file

### ISSUE THREAD

**Issue by beyhangl** [ggerganov/llama.cpp#3183]
When attempting to load a Llama model using the LlamaCpp class, I encountered the following error:

```
`llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    llm = LlamaCpp(
          ^^^^^^^^^
  File "/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "/env/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)
```

**Comment by staviq** [comment]
LangChain is not part of llama.cpp project, you should try there: https://github.com/langchain-ai/langchain

But it looks like you specified absolute path to the root directory instead of local directory:

"from path: **_/_** llama-2-7b-chat.ggmlv3.q4_0.bin"

**Comment by deonis1** [comment]
ggml models are no longer supported by llama.cpp, use gguf file format https://huggingface.co/TheBloke/orca_mini_v3_7B-GGUF
