### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by thistleknot** [ggerganov/llama.cpp#3186]
tried installing via cli as well as .git
nvcc is included in path, I can run nvidia-smi
cuda version 11.7

```
(textgen) [root@pve0 llama.cpp]# ./main -m ../text-generation-webui/models/Marx-3B-V2-Q4_1-GGUF.gguf -n 128
Segmentation fault (core dumped)
(textgen) [root@pve0 llama.cpp]#
```

Oracle Linux 8
python 3.10 (using conda oobaboog enviroinmen t)

I tried to run gdb, but I'm missing 
```
(textgen) [root@pve0 llama.cpp]# debuginfo-install glibc-2.12-1.47.el6.x86_64 libaio-0.3.107-10.el6.x86_64 libgcc-4.4.6-3.el6.x86_64 libstdc++-4.4.6-3.el6.x86_64 libuuid-2.17.2-12.4.el6.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64
Repository ol8_appstream is listed more than once in the configuration
Last metadata expiration check: 2:41:09 ago on Thu 14 Sep 2023 06:01:58 PM PDT.
No match for argument: glibc-2.12-1.47.el6.x86_64
No match for argument: libaio-0.3.107-10.el6.x86_64
No match for argument: libgcc-4.4.6-3.el6.x86_64
No match for argument: libstdc++-4.4.6-3.el6.x86_64
No match for argument: libuuid-2.17.2-12.4.el6.x86_64
No match for argument: nss-softokn-freebl-3.12.9-11.el6.x86_64
Error: Unable to find a match: glibc-2.12-1.47.el6.x86_64 libaio-0.3.107-10.el6.x86_64 libgcc-4.4.6-3.el6.x86_64 libstdc++-4.4.6-3.el6.x86_64 libuuid-2.17.2-12.4.el6.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64
(textgen) [root@pve0 llama.cpp]# debuginfo-install glibc libaio libgcc libstdc++ libuuid nss-softokn-freebl                                                                                   Repository ol8_appstream is listed more than once in the configuration
Last metadata expiration check: 2:41:51 ago on Thu 14 Sep 2023 06:01:58 PM PDT.
Could not find debuginfo package for the following installed packages: glibc-2.28-225.0.3.el8.x86_64, libaio-0.3.112-1.el8.x86_64, libgcc-8.5.0-18.0.2.el8.x86_64, libstdc++-8.5.0-18.0.2.el8.x86_64, libuuid-2.32.1-42.el8_8.x86_64, nss-softokn-freebl-3.79.0-11.el8_7.x86_64
Could not find debugsource package for the following installed packages: glibc-2.28-225.0.3.el8.x86_64, libaio-0.3.112-1.el8.x86_64, libgcc-8.5.0-18.0.2.el8.x86_64, libstdc++-8.5.0-18.0.2.el8.x86_64, libuuid-2.32.1-42.el8_8.x86_64, nss-softokn-freebl-3.79.0-11.el8_7.x86_64
Dependencies resolved.
Nothing to do.

```

**Comment by staviq** [comment]
> Error: Unable to find a match

You have a problem with your system, fix repository configuration, then you should be able to install gdb

**Comment by thistleknot** [comment]
I have a fairly clean repo.  Will try a yum update -y
repo id                                                              repo name
base                                                                 Oracle Linux
cuda-rhel8-11-7-local                                                cuda-rhel8-11-7-local
docker-ce-stable                                                     Docker CE Stable - x86_64
ol8_UEKR6                                                            Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux 8 (x86_64)
ol8_appstream                                                        Oracle Linux 8 EPEL (x86_64)
ol8_baseos_latest                                                    Oracle Linux 8 BaseOS Latest (x86_64)
ol8_developer_EPEL                                                   Oracle Linux  EPEL ()
ol8_gluster_appstream                                                Oracle Linux 8 Gluster Appstream (x86_64)

**Comment by Cebtenzzre** [comment]
The debug info isn't a big deal - simply running
```
gdb --args ./main -m ../text-generation-webui/models/Marx-3B-V2-Q4_1-GGUF.gguf -n 128
```
should allow you to produce a useful backtrace. You may also try to make an ASAN build with CMake:
```
mkdir build
cd build
cmake .. -DLLAMA_SANITIZE_ADDRESS=ON
make -j
```
and then run main normally, without GDB.

**Comment by thistleknot** [comment]
note: yum install libasan libubsan
apparently... I had built it in the wrong folder

I wasn't running it from
build/bin

but rather I had somehow built it at the root folder and was attempting to run it from there

I was able to run it.  However, when I attempted to run the cuda build, I didn't get a segmentation fault, but a 

CUDA error 2 at /data/llama.cpp/ggml-cuda.cu:5509: out of memory
current device: 0
(textgen) [root@pve0 bin]# ./main -m /data/text-generation-webui/models/Marx-3B-V2-Q4_1-GGUF.gguf -n 0

which is weird because I can load that in oobabooga text-generation-webui (although as cpu)

**Comment by Cebtenzzre** [comment]
> I was able to run it. However, when I attempted to run the cuda build, I didn't get a segmentation fault

Could you open a new issue for that, to keep things simple?

**Comment by thistleknot** [comment]
yes.
