### ISSUE TITLE
a quick embedding question 

### ISSUE THREAD

**Issue by xvolica** [ggerganov/llama.cpp#3189]
I was very excited to find out that there is a embed function to convert a long sentence to embedding. But I didn't see the api explanation, I want to know that where does the embedding come from at llama2 model? 
What more, I want to know that is there any different between using chat and embedding, what kind of prompt will generate a better embedding? Is there any issue to support that?

**Comment by staviq** [comment]
I suggest moving this to Discussions as this is not a bug.
