### ISSUE TITLE
Automating CI for RISC-V

### ISSUE THREAD

**Issue by alitariq4589** [ggerganov/llama.cpp#3191]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

llama.cpp CI is set up for running on RISC-V at [dash.cloud-v.co](dash.cloud-v.co). But it is manual. For it to be triggered on every PR and update the CI status, a token is needed to be added in Cloud-V and webhook is needed to be configured in the repository settings

# Current Behavior

Currently the CI has to be triggered manually at: https://cloud-v.co:8443/view/Vector%20processing/job/llama.cpp%20--%20ggerganov/

# Steps for enabling auto builds
- Login to [dash.cloud-v.co](dash.cloud-v.co) (@ggerganov is emailed with credentials)
- Add github authentication token of this repository in Cloud-V
- Enable Cloud-V webhook in the repository settings
**Complete details about this can be found [here](https://10x-engineers.github.io/riscv-ci-partners/Software_Developer_Guide/)**

**Comment by ggerganov** [comment]
@alitariq4589 Which permission is needed for the token?

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/f0a2ec66-8e5a-475e-a034-2403541ad532)

**Comment by alitariq4589** [comment]
@ggerganov two permission are required for this token. 
1): `Read-only` permission for`Webhooks`: Because the CI platform should be able to check if the webhook is recieved.
2): `Read and Write` permission for `Commit Statuses`: Because after a CI check has run, the commit statuses on the PR has to be updated accordingly

**Comment by alitariq4589** [comment]
As the CI has been automated and running at https://cloud-v.co:8443/view/Vector%20processing/job/llama.cpp%20--%20ggerganov/ without any issue uptil now. So I am closing this issue.
