### ISSUE TITLE
[User] llama cpp doesn't free cuda ram on windows.

### ISSUE THREAD

**Issue by earonesty** [ggerganov/llama.cpp#3198]
at first i thought it was a python issue:  https://github.com/abetlen/llama-cpp-python/issues/723

but then i added this to simple.cpp

```
    llama_free(ctx);
    llama_free_model(model);

    model = llama_load_model_from_file(params.model.c_str(), ctx_params);
    ctx = llama_new_context_with_model(model, ctx_params);

    llama_free(ctx);
    llama_free_model(model);

    model = llama_load_model_from_file(params.model.c_str(), ctx_params);
    ctx = llama_new_context_with_model(model, ctx_params);
```

and it the grpahics card blows up with OOM....  this works fine on linux.

**Comment by earonesty** [comment]
ok, nvm got this to work.  going back to blaming python

**Comment by MinaiRoderon** [comment]
> ok, nvm got this to work. going back to blaming python

Hi, actually, would you mind sharing how you made it work ? (The re-loading process with new parameters)
