### ISSUE TITLE
What would it take to support DeciLM?

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#3208]
What would it take to support DeciLM: https://deci.ai/blog/decilm-15-times-faster-than-llama2-nas-generated-llm-with-variable-gqa/

I tried converting it to GGUF and running as is after removing all the assertions that check for tensor size. It works runs without crashing, but the output is incoherent.

**Comment by Green-Sky** [comment]
the variable gqa here makes it a very different architecture.

**Comment by cnmoro** [comment]
yep, the model looks really promising, would be awesome if it could run on llamacpp

**Comment by rayhern** [comment]
yes, that would be the bees knees. <3

**Comment by aiaicode** [comment]
15 times faster with Infery LLM which I believe is their custom inference engine probably highly optimised for DeciLM. This engine seems equally interesting to study to improve speed but probably will remain closed source.

**Comment by BarfingLemurs** [comment]
>15 times faster 

In reality, the actual speed is probably the same speed as a llama 7b. Nothing noteworthy is proven for single batch inference.. ?

For example, isn't [this](https://github.com/PygmalionAI/aphrodite-engine), which can run llama at like 2000 t/s on a single 4090, way faster than exllama (173t/s )? but it makes use of float 16 and batch inference to achieve these speeds. An average user won't use these principles. Especially not on a cpu.

**Comment by BarfingLemurs** [comment]
@avideci thank you for your efforts to inform:

This is what the blog says currently:

Throughput: DeciLM 6B’s throughput (tokens per second measured with an optimal batch on A10G) is 4.8 times that of Llama 2 7B’s.

We see that figure is for an optimal batch, what about a single batch? 
Batching is [just now added](https://github.com/ggerganov/llama.cpp/pull/3228) to llama.cpp, but before that, isn't everyone using single batch? Is it 4.79x on single batch pytorch transformers? If it is, or lower, maybe add the detail in the blog.

**Comment by avideci** [comment]
@Green-Sky @l3utterfly @cnmoro @rayhern 
Hey guys, we've released a 7B model that outperforms Mistral and LLaMA2 in terms of acc. and throughput. 
The model is available in GGUF format in the following URL: https://huggingface.co/Deci/DeciLM-7B-instruct-GGUF

The `f16` and `q8_0` versions were tested on M1 and M2 chips. with 16gb and 32gb respectively. 
the tokens/second are `4715.76` (M1 Pro, 16GB RAM) and `12,454.98` (M2 Pro, 32GB RAM).

Please let me know if you evaluated it or ran it on different HW.
Enjoy!

**Comment by slaren** [comment]
It seems that the throughput was taken from the sample time:
```
llama_print_timings:      sample time =      19.99 ms /   249 runs   (    0.08 ms per token, 12454.98 tokens per second)
```

This is not usually what we measure when evaluating the performance of a model, instead you should be looking at the `prompt eval time` and `eval time`. You can also use `llama-bench -m <model>` to run a standardized benchmark.

**Comment by cnmoro** [comment]
> @Green-Sky @l3utterfly @cnmoro @rayhern Hey guys, we've released a 7B model that outperforms Mistral and LLaMA2 in terms of acc. and throughput. The model is available in GGUF format in the following URL: https://huggingface.co/Deci/DeciLM-7B-instruct-GGUF
> 
> The `f16` and `q8_0` versions were tested on M1 and M2 chips. with 16gb and 32gb respectively.
> 
> Please let me know if you evaluated it or ran it on different HW. Enjoy!

I have tried the q8_0 gguf version and it really is fast and usable on CPU (even older ones).
But it appears that when trying to run a longer prompt (say, trying to summarize a text that contains around 1000 tokens) the inference becomes EXTREMELY slow (takes more than two minutes to generate the first token)
