### ISSUE TITLE
[bug] out of memory trying to run quantized model

### ISSUE THREAD

**Issue by thistleknot** [ggerganov/llama.cpp#3221]
I'm able to run this model as cpu only model. I was expecting to do a split between gpu/cpu ram for the model under gguf, but regardless of what -n

```
./main -m /data/text-generation-webui/models/DeciLM-6b-instruct/DeciLM-6b-instruct_q2.gguf
Log start
main: build = 1233 (98311c4)
main: seed  = 1694898033

CUDA error 2 at /data/llama.cpp/ggml-cuda.cu:5509: out of memory
current device: 1
(textgen) [root@pve0 bin]#
```

Oracle linux 8.5
python 3.10
torch 2.0.1
cuda 11.7

**Comment by slaren** [comment]
Looks like it is failing during initialization while enumerating the devices, before any allocations are actually made:
https://github.com/ggerganov/llama.cpp/blob/98311c427739e3b06527c3ce6b5c021ab6692740/ggml-cuda.cu#L5509

This suggests that there is something wrong with your system configuration.

**Comment by thistleknot** [comment]
llama.cpp
    https://github.com/ggerganov/llama.cpp
    yum remove cuda-toolkit-11-2 -y; yum install cuda-toolkit-11-7 -y
    
    cd /data/llama.cpp
    
    export LLAMA_CUDA_F16=true
    export CUDA_VISIBLE_DEVICES=0
    
    make LLAMA_CUBLAS=1
    
    #or
    #mkdir build
    #cd ./build
    #cmake .. -DLLAMA_CUBLAS=ON
    #cmake --build . --config Release
    #cd /data/llama.cpp/build/bin
    
    ./main -m /data/text-generation-webui/models/DeciLM-6b-instruct/DeciLM-6b-instruct_q2.gguf
    
    #works, loada on gpu
    ./main -m /data/text-generation-webui/models/Llama-2-7b-Chat-GGUF/llama-2-7b-chat.Q2_K.gguf -n 128 -c 256
