### ISSUE TITLE
bug :  error loading model: create_tensor: tensor 'output_norm.weight' not found

### ISSUE THREAD

**Issue by Tr-buaa** [ggerganov/llama.cpp#3242]
when I run the inference with q4_0, I encountered the following error：

llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.07 MB
llm_load_tensors: using CUDA for GPU acceleration
error loading model: create_tensor: tensor 'output_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model './models/chinese-llama-2-7b-hf/ggml-model-q4_0.gguf'
main: error: unable to load model

How can I solve it?

**Comment by yourtiger** [comment]
I guess you imported pytorch_model-xx-of-xxx.bin file is missing One or more

**Comment by Tr-buaa** [comment]
> I guess you imported pytorch_model-xx-of-xxx.bin file is missing One or more

but it just have two models, I imported both of them

**Comment by Tr-buaa** [comment]
solved

**Comment by hw2cb** [comment]
> Автор
how did you solve this problem? I have a similar problem:
error loading model: create_tensor: tensor 'output.weight' not found
llama_load_model_from_file: failed to load model

**Comment by tianyuegithub** [comment]
what`s your solution,please
