### ISSUE TITLE
[Q] Use llama.cpp with Kaggle TPUs

### ISSUE THREAD

**Issue by NightMachinery** [ggerganov/llama.cpp#3253]
Is it possible to use `llama.cpp` with Kaggle TPUs? 

Kaggle TPUs are quite strong, and Kaggle gives 20 hours of TPU for free.

**Comment by staviq** [comment]
Unless I'm missing something, it looks like they only provide high level python API

If you can find anything mentioning running compiled c++ code on their TPUs, I'd happily check it out, it sounds interesting.

**Comment by ymwangg** [comment]
Running on TPUs requires converting your model to XLA HLO format. You can checkout the XLA project https://github.com/openxla/xla. The XLA project is written in C++ and there are projects like pytorch/xla and jax to allow users to compile their models using python bindings.

**Comment by coolrazor007** [comment]
> Running on TPUs requires converting your model to XLA HLO format. You can checkout the XLA project https://github.com/openxla/xla. The XLA project is written in C++ and there are projects like pytorch/xla and jax to allow users to compile their models using python bindings.

Is this a way of saying llama.cpp won't be supporting TPUs?  I have TPUs at GCP and couldn't get llama.cpp to work.  I've seen whisper.cpp work though.

**Comment by ymwangg** [comment]
It's possible, but I guess it requires substantial amount of engineering efforts. I've seen some Google folks make llama work through pytorch/xla https://pytorch.org/blog/path-achieve-low-inference-latency/.

**Comment by freecodewu** [comment]
Has anyone successfully run llama.cpp in TPU?
