### ISSUE TITLE
[Feature Request] Support Xwin-LM model

### ISSUE THREAD

**Issue by hfassold** [ggerganov/llama.cpp#3255]
The 'Xwin-LM' model seems to perform great and its 70B variant beats even GPT-4 on Alpaca Eval Leaderboard.
See https://tatsu-lab.github.io/alpaca_eval/

7B, 13B and 70B model are available https://github.com/Xwin-LM/Xwin-LM
License is permissive, and model seems to be based on LLama2.

So it would be great if llama.cpp could support it.
Maybe the only thing necessary is to convert the Xwin-LM models to GGUF format.
But I am not sure, maybe the model uses also some layers not yet supported in llama.cpp

**Comment by spikespiegel** [comment]
In the Readme, they say the model is based on llama2, also has only 7, 13, and 70B parameter models, same as llama2. I did not check the layers, but this seems a finetune?

**Comment by kalomaze** [comment]
This is a typical llama finetune architecturally speaking, it just needs a GGUF quant.
Will be putting up a 4_K_S of the 13b here in a couple minutes (quantizing on colab -- don't think I can quant the 70b).

https://huggingface.co/kalomaze/Xwin-LM-13B-GGUF/tree/main

**Comment by hfassold** [comment]
Great, thanks to all !
