### ISSUE TITLE
RAM not used

### ISSUE THREAD

**Issue by paveltonev** [ggerganov/llama.cpp#3265]
Hi Everybody,

I have (48GB VRAM,128GB RAM) and succeeded to run falcon-180b-chat.Q4_K_M (see attached log). All the VRAM was used and none of the RAM. Is this expected behavior?
[falcon180b_ram_not_used.txt](https://github.com/ggerganov/llama.cpp/files/12663422/falcon180b_ram_not_used.txt)

Thanks!
Pavel

**Comment by Green-Sky** [comment]
> Is this expected behavior?

Yes

> and none of the RAM.

No, it is. Memory mapped files do not count against the processes memory usage, but it is still in ram. The operating system might decide when to unload / load the file to memory. And it can be shared between processes (contrary to vram usage).

model ram usage according to llama:
```
llm_load_tensors: mem required  = 62551,05 MB (+  640,00 MB per state)
```


I also noticed you run an **nvidia card with opencl**, I **recommend using cuda** instead. It should perform better.

**Comment by paveltonev** [comment]
Thanks!
