### ISSUE TITLE
Fix static build

### ISSUE THREAD

**Issue by WilliamTambellini** [ggerganov/llama.cpp#3266]
# Prerequisites
- [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
Build successful
Please provide a detailed written description of what you were trying to do: 
building with LLAMA_STATIC

what you expected `llama.cpp` to do:
build successfully

# Current Behavior
```
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: attempted static link of dynamic object `/usr/lib64/librt.so'
collect2: error: ld returned 1 exit status
```

# Environment and Context
`$ lscpu`
Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz

* Operating System, e.g. for Linux:
`$ uname -a`
Linux wtambellini  3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
$ make --version
GNU Make 3.82
$ g++ --version
11.3.0
```

# Failure Information (for bugs)
It s probably because of trying to use "-static" in the cmake: eg:
https://github.com/ggerganov/llama.cpp/blob/8781013ef654270cbead3e0011e33a6d690fb168/CMakeLists.txt#L483

https://github.com/cmp-nct/ggllm.cpp/issues/76

# Steps to Reproduce
1. step 1: cmake --DLLAMA_STATIC ..
2. step 2: make

**Comment by staviq** [comment]
That LLAMA_STATIC flag was added ages ago, and I don't think it was ever tested or used beyond windows release builds

On top of that, many Linux distributions don't even provide static versions of core libraries, so this is bound to fail one way or another

**Comment by WilliamTambellini** [comment]
Tks @staviq  
Most linux libs are also available as static, and definitely the nvidia ones. 
Just disabling that "add_link_options(-static)"  does fix the build and generate a good llama exec/lib NOT needing any nvidia .so at runtime.
Would you accept such PR:
```
if(LLAMA_STATIC)
...
if(NOT LINUX) 
 add_link_options(-static)
endif()
```
?
Best

**Comment by staviq** [comment]
If you are building with just `LLAMA_STATIC` without cuda, disabling `add_link_options(-static)` is the exact same thing as not using `LLAMA_STATIC` in the first place.

> does fix the build and generate a good llama exec/lib NOT needing any nvidia .so at runtime.

That is untrue. Even statically linked nvidia libs, still depend on cuda and nvidia drivers, and those libraries are still dynamically accessed at runtime via dlopen.

Statically linked cuda libs, as per your suggestion:

![image](https://github.com/ggerganov/llama.cpp/assets/15910535/8b631a48-d7de-4c22-bdce-746cedbea70f)

Libs actually loaded at runtime:

![image](https://github.com/ggerganov/llama.cpp/assets/15910535/cedaa8e9-f914-4da0-9de4-c6ec4831724c)

Statically linking nvidia libs, only links the api libraries, not the underlying GPU "handler", which is always loaded dynamically either way.

Making such changes in the project would require this being an actual solution to a problem, while realistically, this only inflates generated binaries by ~120Mb and does not get rid of nvidia libs dependency.

I can add `LLAMA_CUBLAS_STATIC` flag to cmake, which would "statically" link only nvidia related libs ( ones that can be )

But for others to approve such pull request, this would have to actually improve something.
