### ISSUE TITLE
How to build llama.cpp and the webchat example in Android Studio

### ISSUE THREAD

**Issue by hfassold** [ggerganov/llama.cpp#3280]
I want to build the 'webchat' example from llama.cpp in Android studio.
See https://github.com/ggerganov/llama.cpp/discussions/3250

Did anybody succeed in this already ?

If so, it would be good to add respective notes / a sort of a 'recipe' / how-to' here to to github repo.

I know there is an 'Android' section with some notes at https://github.com/ggerganov/llama.cpp#android 
But it employs termux, which I cannot use for my project.

There is a 'sherpa' github repo also, but it relies on an older 'llama.cpp' code and hasn't been updated for months.
See https://github.com/Bip-Rep/sherpa

**Comment by jhen0409** [comment]
Update (I guess it's needed) the Java binding to support Android is an option.

Also, you can refer to the [jni.cpp](https://github.com/mybigday/llama.rn/blob/main/android/src/main/jni.cpp) of the React Native binding (also: [LlamaContext.java](https://github.com/mybigday/llama.rn/blob/main/android/src/main/java/com/rnllama/LlamaContext.java)). You should be able to use them directly in a pure Android project if excluding some React Native specific classes.

**Comment by hfassold** [comment]
Thank you for the link to the React binding !
