### ISSUE TITLE
Add support for flash attention

### ISSUE THREAD

**Issue by WilliamTambellini** [ggerganov/llama.cpp#3282]
# Prerequisites

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
ggml core lib to use flash attention (v1 or v2) at least for nvidia runtime.
Refs:
https://github.com/Dao-AILab/flash-attention
https://tridao.me/publications/flash2/flash2.pdf
https://github.com/ggerganov/llama.cpp/discussions/2257

# Current Behavior
ggml core lib not using flashattn.

# Environment and Context
* Operating System, e.g. for Linux:
Any recent Linux with 'recent' nvidia drivers/gpus.

* SDK version, e.g. for Linux:
cuda 11 or 12, no preference

**Comment by KerfuffleV2** [comment]
There's #778 - it didn't get merged since it didn't seem to provide an advantage though.

**Comment by Aya-ZIbra** [comment]
I am interested what benchmarks are used to check if flash attn improved the current implementation.

**Comment by ggerganov** [comment]
I was testing with single-batch inference back at the time.
Need to redo the tests with parallel batches #3228

**Comment by Aya-ZIbra** [comment]
I think flash will be effective when the load consists of more prefill than decode. Parallel loads may satisfy this.

**Comment by ggerganov** [comment]
Superseded by https://github.com/ggerganov/llama.cpp/issues/3365
