### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic._internal'

### ISSUE THREAD

**Issue by thistleknot** [ggerganov/llama.cpp#3308]
pip install -r requirements.txt
mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON
cmake --build . --config Release
cd build/bin

python3 -m llama_cpp.server --model /data/text-generation-webui/models/Llama-2-7b-Chat-GGUF/llama-2-7b-chat.Q2_K.gguf

python 3.10.9

<2 pydantic

ubu22 wsl
cuda 11.7 installed (driver shows support for cuda 11.6, it's a m2000m)

ModuleNotFoundError: No module named 'pydantic._internal'

>=2 pydantic
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/root/text-gen-install/installer_files/conda/envs/textgen/lib/python3.10/site-packages/pydantic/fields.py)

**Comment by thistleknot** [comment]
This works though
(have to disalbe cublas?)
export LLAMA_CUDA_F16=false; export CUDA_VISIBLE_DEVICES=0; make clean; make LLAMA_CUBLAS=
        ***
        ./main -m /root/text-gen-install/text-generation-webui/models/llama-2-7b-chat.Q2_K.gguf --color -c 2048 --keep -1 -t 3 -b 10 -i -ins

**Comment by staviq** [comment]
I would suggest you first build llama.cpp like readme says, and if that works, you can then use you own ways to build it, and you would have a frame of reference for what works and what doesn't.

Cublas is for Nvidia GPUs, do you have Nvidia GPU?

**Comment by thistleknot** [comment]
I was able to get a diferent error (illegal instruction)

./build
    #cmake .. -DLLAMA_CUBLAS=ON
    #cmake --build . --config Release
    #cd /data/llama.cpp/build/bin
    
    #https://github.com/abetlen/llama-cpp-python
    CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python llama-cpp-python[server] --force-reinstall
    
    #results in illegal instruction if I skip the pip install just above
    #then this will work
    MAKE_ARGS="-DLLAMA_CUBLAS=on" ; python3 -m llama_cpp.server --model /root/text-gen-install/text-generation-webui/models/Llama-2-7b-Chat-GGUF/llama-2-7b-chat.Q2_K.gguf --n_gpu_layers 32

I think my cuda 11.6 driver doesn't jive for some reason.

but also where you run make or cmake and where you run the server hosting make a different

**Comment by staviq** [comment]
Skip the python bindings for now, that too is a separate project :)

Just build llama.cpp like described here: https://github.com/ggerganov/llama.cpp#usage

And test if that works first.

Whatever problem you are having, it has to be reproducible in "core" llama.cpp anyway, to begin fixing it.

**Comment by thistleknot** [comment]
sorry, this error is actually llama-cpp-python

which I got around by running from the right folder (for some reason, I have to run that command from within llama.cpp).

**Comment by thistleknot** [comment]
avx isn't supported on my cpu for this workstation
https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels
not that that's what this problem was, but one of many
