### ISSUE TITLE
How to run the single example in llama.cpp?

### ISSUE THREAD

**Issue by Tr-buaa** [ggerganov/llama.cpp#3335]
I can run the hole project successfully, but now I want to run the single example like /examples/baby-llama, how can I do this?
when I use the cmake && make , the errors as below:

fatal error: ggml.h: No such file or directory
    1 | #include "ggml.h"
      |          ^~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/baby-llama.dir/build.make:76: CMakeFiles/baby-llama.dir/baby-llama.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/baby-llama.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

Through I'm a begginer for running C++ project on the linux, please give me some advise, thanks very much!

**Comment by alonfaraj** [comment]
@Tr-buaa 
 
You can run 
`make -j baby-llama` from the root project folder. 
Then simply `./baby-llama`
