### ISSUE TITLE
Confusing tokenizer API

### ISSUE THREAD

**Issue by ortegaalfredo** [ggerganov/llama.cpp#3338]
The API on llama.h uses this function to tokenize the prompt:

    LLAMA_API int llama_tokenize(
            struct llama_context * ctx,
                      const char * text,
                             int   text_len,
                     llama_token * tokens,
                             int   n_max_tokens,
                            bool   add_bos);

However, all examples use this other function, defined in common.h, that is not exported as a shared lib, and cannot be used except from C/C++:

    std::vector<llama_token> llama_tokenize(
        struct llama_context * ctx,
           const std::string & text,
                        bool   add_bos);

As a result, one cannot use the examples directly as they use non-exported functions. You have to re-implement the llama_tokenize() function in your application (that confusing enough, has the same name as the exported function).

It would be good for the examples to use only the available API, or as an alternative, to have additional examples that use the exported API.

**Comment by ggerganov** [comment]
I'm aware of this issue, but not sure that there is a better way than the current implementation.
If the examples use straight up the C-style API, then you would have to repeat the C++ `llama_tokenize` implementation in all the examples. Don't think this is better.
