### ISSUE TITLE
How can I create Embeddings?

### ISSUE THREAD

**Issue by manel00** [ggerganov/llama.cpp#3352]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Get properly embeddings

# Current Behavior

Embeddings created are wrong, I need to index them on Elasticsearch but are different than the embeddings of OpenAI. Embeddings must be e.g: [[-0.9899, 0.989898][-0.966436899, 0.989435898]] and it is [0.3464363643, 0.345635345]

# Environment and Context

Ubuntu 22.10

**Comment by djmMax** [comment]
I face the same issue, maybe it's not well documented
