### ISSUE TITLE
Cannot load Xwin 7B (4-bit quant) GGUF model - invalid magic number

### ISSUE THREAD

**Issue by hfassold** [ggerganov/llama.cpp#3358]
Today I managed to build llama.cpp on Android with termux (F-Droid).

I tried out to run llama.cpp main executable now with the Xwin 7B (4-bit quantized) model, downloaded from
https://huggingface.co/TheBloke/Xwin-LM-7B-V0.1-GGUF/blob/main/xwin-lm-7b-v0.1.Q4_0.gguf

Unfortunately, it gives an error 'invalid magic number'.
See the screenshot below.

So that means this GGUF version is outdated, or what is wrong with the model ?

Note: for simplicity, I built llama.cpp _without_ BLAS (so simply via command 'cmake .' and 'make').

![Screenshot_20230927_115642_Termux](https://github.com/ggerganov/llama.cpp/assets/16693781/bf64bedf-8c8a-4ecc-97c7-e2e15de6cd78)

**Comment by Green-Sky** [comment]
make sure the file is not damaged, run sha256sum <file.gguf> and compare with the hugging face sha256

**Comment by hfassold** [comment]
Thanks. Yes, it seems I downloaded the wrong file. It does not have 'GGUF' at the begin of the file, and it is much too small.

I downloaded it via the command:
wget https://huggingface.co/TheBloke/Xwin-LM-7B-V0.1-GGUF/blob/main/xwin-lm-7b-v0.1.Q4_0.gguf

Any idea what is wrong with that command ?

**Comment by Green-Sky** [comment]
you download the html, that you see when you click the url :)

use https://huggingface.co/TheBloke/Xwin-LM-7B-V0.1-GGUF/resolve/main/xwin-lm-7b-v0.1.Q4_0.gguf instead

**Comment by hfassold** [comment]
Yes, exactly :-) Thank you, that solves it ...
