### ISSUE TITLE
[FR] Mistral-7B Sliding Window Attention support

### ISSUE THREAD

**Issue by wizzard0** [ggerganov/llama.cpp#3371]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The Mistral model https://mistral.ai/news/announcing-mistral-7b/ is fully supported with llama.cpp.

🟢  Uses Grouped-query attention (GQA) for faster inference

❌  Uses Sliding Window Attention (SWA) to handle longer sequences at smaller cost

> "Outperforms Llama 2 13B on all benchmarks"

# Current Behavior

Only 4K of context is available to use

# Environment and Context

llama.cpp ac43576124a75c2de6e333ac31a3444ff9eb9458 (Sep 27)

**Comment by BarfingLemurs** [comment]
https://github.com/mistralai/mistral-src

**Comment by choltha** [comment]
I am surprised it work at all given it was trained on a different attention architecture.

**Comment by ggerganov** [comment]
Superseded by #3377

**Comment by wizzard0** [comment]
@choltha yes, and they work
