### ISSUE TITLE
Does this work with Synthia-7B-v1.3

### ISSUE THREAD

**Issue by stjepangolemac** [ggerganov/llama.cpp#3396]
As mentioned, I'm trying to run [this model](https://huggingface.co/migtissera/Synthia-7B-v1.3). More info on it [here](https://twitter.com/migtissera/status/1707482374748139690).

I've managed to convert and quantize it without errors but when I run it I get this:

```
error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  4096,  4096, got  4096,  1024,     1,     1
```

I converted it with `convert.py model_dir --ctx 4096` and then quantized to q4_0.

**Comment by slaren** [comment]
It works for me. Are you using the latest version?

**Comment by stjepangolemac** [comment]
Yes, built it from source just before I posted. Can you run me through exact steps you're doing on your machine?

**Comment by slaren** [comment]
```bash
git clone --depth 1 https://huggingface.co/migtissera/Synthia-7B-v1.3
./convert.py Synthia-7B-v1.3/
```

Note that until very recently, there was an issue converting some HF models that use GQA, such as this one. You need to update llama.cpp to the current master.

**Comment by Mihaiii** [comment]
It works for me too.

**Comment by prusnak** [comment]
There are also GGUF files available from here: https://huggingface.co/TheBloke/Synthia-7B-v1.3-GGUF/tree/main
