### ISSUE TITLE
Surround/Enclose user input

### ISSUE THREAD

**Issue by h-h-h-h** [ggerganov/llama.cpp#3413]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

This is a feature request.

I'm using llama.cpp in interactive mode with the model [Mistral 7B Instruct](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1). Every user message in the chat history must be enclosed in `[INST]` and `[/INST]`. Currently, this means that these technicalities must constantly be entered (I'm simplifying it a bit for myself by having the common part `INST]` in the clipboard).

It would be great if there would be two new switches:

- One specifying what should be output after the model returns, which I would set to `[INST]` (Mistral 7B Instruct's output always ends in a linebreak). It may generally be useful to only output it, if the model text doesn't end with that text.
- Another specifying what should be output after the user finished their message before control is yielded back to the model, which I would set to `[/INST]`. At least in the case of Mistral 7B Instruct, though, `[/INST]` would need to be output before the linebreak caused by the user finishing their message by pressing <kbd>Enter</kbd>.

# Current Behavior

(llama.cpp doesn't provide these means, yet.)

# Environment and Context

(Irrelevant for this feature request.)

**Comment by KerfuffleV2** [comment]
--in-prefix STRING    string to prefix user inputs with (default: empty)
    --in-suffix STRING    string to suffix after user inputs with (default: empty)

Isn't this exactly what you're looking for?

You can also use `--reverse-prompt` to automatically trigger interactive mode.

**Comment by h-h-h-h** [comment]
You're right: `--in-prefix` and `--in-suffix` are what I was looking for. Thank you! Somehow I didn't realize that.
