### ISSUE TITLE
-f option seems to not work

### ISSUE THREAD

**Issue by digitalw00t** [ggerganov/llama.cpp#342]
It either doesn't work for importing a prompt, or I don't know what the file format is suppose to be.   I put this in a file.

My name is Greg.\
What is my name?

When I run chat with the -f pointing to the file, it doesn't answer the question, and doesn't know the name I placed in the file.

**Comment by KerfuffleV2** [comment]
Extremely unlikely that's the problem.

These models aren't ChatGPT, which has had extensive training to chat. Also, the interface is doing fancy stuff behind the scenes and fixing up the prompts so the LLM gets the input it expects.

Remember the LLM is like autocomplete. You have to give it a prompt where it can "complete" the next token in the way you want. Also, different models expect different types of prompts. For example, Alpaca has a very specific format it expects (although sometimes you can get away with ignoring that). 

I'll show you an example with Alpaca 13b-q4. This is the prompt:

```plaintext
This is an example of a conversation between a user named Greg and an AI:

User: Hi. My name is Greg.
AI: Hello!
User: What's my name?
AI:
````

Then it started completing the conversation starting from "AI:" (I cleaned up the formatting a little):

***

AI: It looks like your first name might be "Greg." Is that correct, or do you have another nickname? Or are there other people in the conversation named GREG too? Would adding a tag for gender help clarify things more? (For example, if I said Hi! What's my NAME?, then it would likely want to know which one - first name? last? full middle?)

User: Greg is fine. Where am i now? 123 Main Street in Austin Texas. Do you have any information on that address or city? Also what time of day is it? Is the sun up right now, down for night soon after dusk again here today around this hour I'm asking about (what are local solar noon and civil twilight times?)

AI: Greg! That’s a really interesting nickname. How did you get that name anyway ? Do all of your friends know you as "Greg"? You’re in Austin, Texas? What do you like most about living there?"I" am at the intersection between 123 Main Street and Sunrise Road in East Austin here in North America! It is around noon right now (local solar time), but it will be dark before long as we near twilight after sunset. Here, civil dusk begins about 6:08 PM this afternoon."

User: Well I'm a big fan of music and like to learn how others are doing similar things with artistic expressions such as that - any recommendations? Also what do you listen to for fun when it comes time not working in the kitchen or taking care of household tasks around here after dusk tonight ? (what type)

***

There are ways to make it give control back to you via reverse prompts and the interactive mode. I haven't used those much, so I can't advise you.

**Comment by digitalw00t** [comment]
Great description.  Since you can state some information, then give a question and that information would be in that prompt "session" if you will.  I thought that's what the -f option was for.

**Comment by digitalw00t** [comment]
I'll try to craft the file that way.
