### ISSUE TITLE
Support Jais-13b-chat bilingual model

### ISSUE THREAD

**Issue by infojunkie** [ggerganov/llama.cpp#3441]
How to add support for [Jais-13b-chat bilingual LLM](https://huggingface.co/inception-mbzuai/jais-13b-chat)?

I am a n00b, and from what I can tell this Torch model uses a custom architecture (including a custom model class) and would need a special converter.

I'd be happy to collaborate with someone more experienced on making this happen. I can provide some sponsorship as well. Thanks!

**Comment by KerfuffleV2** [comment]
> from what I can tell this Torch model uses a custom architecture (including a custom model class) and would need a special converter.

Just glancing at it, that does seem to be the case. So it would need conversion support and also support for running inference on it once converted. If it uses operations that GGML doesn't already support then those would need to be added as well.

_Most_ of the time, new model architectures get added as an example in the `ggml` repo first: https://github.com/ggerganov/ggml - then once there's an example of running inference on them they may get added to llama.cpp. (Just talking about how I've seen it happen, I don't have any authority personally.)

**Comment by infojunkie** [comment]
Thanks @KerfuffleV2 can you say a little more about "support for running inference on it once converted" ? I expected all the rest but I am confused but what this part means practically. Do you mean adding new features to ggml (such as the SwiGLU activation function which I can't find in there), or is there more to be done?

**Comment by KerfuffleV2** [comment]
I'm not an expert but I can give you a very, very basic overview.

The conversion step basically grabs the tensors and metadata out of the model in its original format. That could be HuggingFace's PyTorch-based format, could be SafeTensors, etc. Then it converts that to GGUF format and saves it. Metadata could be stuff like the context size the model supports, its vocabulary size, etc.

The GGUF format doesn't store anything about what operations are actually required to run the model. Stuff like matrix multiply this tensor with this other tensor, perform addition on it, run normalization on some other tensor. For this model, somewhere there will be a run the SwiGLU operation on some tensor (could be ones that existed in the model or were calculated with other operations).

So all the operations that the model requires have to be implemented (usually in the GGML library) and the "graph" of operations required to support the model has to be implemented as well. Just picking a random model type I looked at recently, you can look at the code here for Baichuan models: https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L2941

It's a long function so you'll have to scroll down a ways but you'll see stuff like:

```c++

        // self-attention
        {
            // compute Q and K and RoPE them
            struct ggml_tensor * tmpk = ggml_mul_mat(ctx0, model.layers[il].wk, cur);
            offload_func_kq(tmpk);
            ggml_set_name(tmpk, "tmpk");

            struct ggml_tensor * tmpq = ggml_mul_mat(ctx0, model.layers[il].wq, cur);
            offload_func_kq(tmpq);
            ggml_set_name(tmpq, "tmpq");

            struct ggml_tensor * Kcur;
            struct ggml_tensor * Qcur;
            switch (model.type) {
                case MODEL_7B:
                    Kcur = ggml_rope_custom(ctx0, ggml_reshape_3d(ctx0, tmpk, n_embd_head, n_head_kv, n_tokens), KQ_pos, n_embd_head, 0, 0, freq_base, freq_scale);
                    Qcur = ggml_rope_custom(ctx0, ggml_reshape_3d(ctx0, tmpq, n_embd_head, n_head, n_tokens),    KQ_pos, n_embd_head, 0, 0, freq_base, freq_scale);
                    break;
                case MODEL_13B:
                    Kcur = ggml_reshape_3d(ctx0, tmpk, n_embd/n_head, n_head, n_tokens);
                    Qcur = ggml_reshape_3d(ctx0, tmpq, n_embd/n_head, n_head, n_tokens);
                    break;
                default:
                    GGML_ASSERT(false);
            }
```

Hopefully that makes sense and helps you.

**Comment by infojunkie** [comment]
Yes, makes a ton of sense - thanks for taking the time to explain!!

**Comment by Taikono-Himazin** [comment]
When I tried it, it seems that this support has not been added yet.
Are there any plans to add more?

**Comment by Rusteam** [comment]
any update on this model?

**Comment by Rusteam** [comment]
Working on this at the moment, but need guidance with cpp.
