### ISSUE TITLE
[User] Why server cannot set the random seed

### ISSUE THREAD

**Issue by Fanisting** [ggerganov/llama.cpp#3460]
Hi all, recently I have been using server to do some text classification works. My goal is to set the random seed and let the results 100% reproducible, but unfortunately, I did not find a way to set the parameter in our written server.sh example. Any idea? Thanks!

Please answer the following questions for yourself before submitting an issue.

- [ √] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ √] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ √] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ √] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

**Comment by spencekim** [comment]
@Fanisting did you find a solution to this? I am seeing the same issue.
