### ISSUE TITLE
I cannot convert Llama2-13b-hf model to ggml FP16 format

### ISSUE THREAD

**Issue by Lucien20000118** [ggerganov/llama.cpp#3467]
I'm trying to use llama2-13b model. I tried the llama2-7b model before and it works.
`python3 convert.py models/7B/` 
When I tried 13b model, it didn't work. 
13b model = 24GB

```
/mnt/d/LLama2/llama.cpp/1004$ python3 convert.py models/13bv2/
Loading model file models/13bv2/pytorch_model.bin
Traceback (most recent call last):
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 1200, in <module>
    main()
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 1141, in main
    model_plus = load_some_model(args.model)
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 1060, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 746, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 700, in lazy_load_torch_file
    model = unpickler.load()
  File "/mnt/d/LLama2/llama.cpp/1004/convert.py", line 689, in find_class
    return self.CLASSES[(module, name)]
KeyError: ('torch._utils', '_rebuild_meta_tensor_no_storage')
```

Hardware :
2 x Rxt3060 (total VRAM= 24 )
System:
WSL2 (Ubuntu) 22.04
Llama.cpp is the latest version

I tried separating the parameter's file into 3 files. And I converted them at the same time.
It can read the first two files, and the last file cannot be read.
Is this because there is not enough cuda?

**Comment by helios2k6** [comment]
So, I also had this issue. If you're using huggingface to download and save the model like so:

```python
model_name = "meta-llama/Llama-2-13b-chat-hf"
base_model_path="./huggingface/llama13b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)

tokenizer.save_pretrained(base_model_path, from_pt=True)
model.save_pretrained(base_model_path, from_pt=True)
```

Make sure the `device_map` parameter is **NOT** set. Doing so will output a bunch of meta-tensors into a single pytorch_model.bin file that directly map to the `~/.cache/huggingface` directory. This is not going to work with llama.cpp, as it won't be able to handle meta-tensors.

Once you do that, you should be able to run `python3 convert.py path/to/your/model`.
