### ISSUE TITLE
unable to load model

### ISSUE THREAD

**Issue by erturkkadir** [ggerganov/llama.cpp#3492]
./main -m /var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf -p "Building a website can be done in 10 simple steps:\nStep 1:" -n 400 -e

generates following error
Log start

main: build = 1330 (48edda3)
main: built with gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: seed  = 1696541774
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /var/www/html/models/7B/alpaca/ggml-model-q8_0.bin

any ideas?

PS : 
./main -m /var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf -p "Building a website can be done in 10 simple steps:\nStep 1:" -n 400 -e -gqa 8  did not help (-gqa is not recognized)

**Comment by mirek190** [comment]
wrong path to model .....

**Comment by staviq** [comment]
Did you convert that model to gguf ?

**Comment by KadirErturk4r** [comment]
i also tried to gguf version (the second line)

**Comment by staviq** [comment]
Post the link you got the model from

**Comment by KadirErturk4r** [comment]
https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/tree/main

**Comment by KerfuffleV2** [comment]
> -gqa 8 did not help (-gqa is not recognized)

That parameter was removed with the transition to the GGUF format. It's stored in the model metadata now, so you don't need to specify it anymore.

**Comment by KadirErturk4r** [comment]
I've tried the second one without gqa but no success yet.

**Comment by KerfuffleV2** [comment]
> I've tried the second one without gqa but no success yet.

You mean you get exactly the same error with the `.gguf` file?

> `gguf_init_from_file: invalid magic number 67676a74`

**Comment by KadirErturk4r** [comment]
Log start
main: build = 1330 (48edda3)
main: built with gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: seed  = 1696617102
gguf_init_from_file: invalid magic number 4f44213c
error loading model: llama_model_loader: failed to load model from /var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf'
main: error: unable to load model

**Comment by KerfuffleV2** [comment]
Please verify that the hash of the file you have on disk matches the original: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/blob/main/mistral-7b-instruct-v0.1.Q8_0.gguf

So running `sha256sum` on the file should output `	ab634d1d552dc60533e486cbcc73ad9b01358994dabf2453230e7fcd77308dc8`

**Comment by KadirErturk4r** [comment]
You are right, results does not match,
sha256sum  /var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf

resulted 

933d429bda5b803b3c131c615435fca8ede7423b1781eb269b5a452d9add31c9  /var/www/html/models/7B/mistral/mistral-7b-instruct-v0.1.Q8_0.gguf 

it supposed to be ab634d1d552dc60533e486cbcc73ad9b01358994dabf2453230e7fcd77308dc8

Let me redownload file.

**Comment by KadirErturk4r** [comment]
Thank you so much @KerfuffleV2. Now i am getting proper response with Mistral_Q8. 
The issue is the file itself.
Somehow it  did not download properly

Very much appreciated

**Comment by erturkkadir** [comment]
For those who may have similar issue, please make sure that the model file is properly downloaded.
