### ISSUE TITLE
metal : add Q5_0 and Q5_1 support

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#3504]
The implementation for `Q5_0` and `Q5_1` is still missing in the Metal backend. We should add it

https://github.com/ggerganov/llama.cpp/blob/5ab6c2132aad2354092a26c096cc5c8f55801141/ggml-metal.m#L962-L974

https://github.com/ggerganov/llama.cpp/blob/5ab6c2132aad2354092a26c096cc5c8f55801141/ggml-metal.m#L996-L1003

**Comment by jhen0409** [comment]
I can give it a try.

Although I’m not yet familiar with it, I’ll need a little time to get started. I hope it can be done quickly.

**Comment by ggerganov** [comment]
It boils down to writing the dequantize and mul_mat_mv. Shouldn't be too difficult, but let us know if you hit a block
