### ISSUE TITLE
[Lora] Cannot convert baichuan2 qlora to GGUF

### ISSUE THREAD

**Issue by lizhiling12345** [ggerganov/llama.cpp#3519]
Error: unrecognized sub-layer self_attn.W_pack in tensor base_model.model.model.layers.0.self_attn.W_pack.lora_A.weight

**Comment by slaren** [comment]
Can you test https://github.com/ggerganov/llama.cpp/pull/3333?

**Comment by lizhiling12345** [comment]
> Can you test #3333?

i use llama.cpp-lora-falcon,still error,
python convert-lora-to-ggml.py /adapter_model baichuan
Error: could not map tensor name base_model.model.model.layers.0.self_attn.W_pack.lora_A.weight
Note: the arch parameter must be specified if the model is not llama
![image](https://github.com/ggerganov/llama.cpp/assets/7730208/c5516cc2-c2fe-4d4e-90c2-b5efae273526)

**Comment by lizhiling12345** [comment]
> Can you test #3333?

model is baichuan2,not baicun,can you teach me,how to fit baichuan2
![image](https://github.com/ggerganov/llama.cpp/assets/7730208/27102998-f921-44c5-8f95-39575fbc02bd)
![image](https://github.com/ggerganov/llama.cpp/assets/7730208/3fd3648e-d95c-4f5e-baec-b880ea0a1591)

**Comment by slaren** [comment]
Looks like supporting baichuan loras is going to be a bit tricky than that, because the attention weights need to be unpacked. Ie. the `W_pack` needs to be unpacked into `attn_q`, `attn_k` and `attn_v`, like `convert-baichuan-hf-to-gguf.py` does. I don't really know how that works, so I can't help here, sorry.

**Comment by lizhiling12345** [comment]
> Looks like supporting baichuan loras is going to be a bit tricky than that, because the attention weights need to be unpacked. Ie. the `W_pack` needs to be unpacked into `attn_q`, `attn_k` and `attn_v`, like `convert-baichuan-hf-to-gguf.py` does. I don't really know how that works, so I can't help here, sorry.

Thanks for your reply
