### ISSUE TITLE
convert.py needs gguf 0.4.0, but latest on pypi is 0.3.3

### ISSUE THREAD

**Issue by cebtenzzre** [ggerganov/llama.cpp#3528]
Either we need to make a manual release on pypi, which only monatis and ggerganov have the keys for, or the pypi publishing workflow established in #2896 needs to be fixed.

See #3496 for an example of a user apparently running into this problem (`Error: Module 'gguf' has no attribute 'TENSOR_NAMES'`).

**Comment by monatis** [comment]
Released v0.4.0, fixing CI #3532

**Comment by monatis** [comment]
#3532
