### ISSUE TITLE
Please confirm patreon account

### ISSUE THREAD

**Issue by gardner** [ggerganov/llama.cpp#3536]
Hi there,
  is this your patreon account? 

https://www.patreon.com/ggerganov

Thanks!

**Comment by verdooft** [comment]
Hello ggerganov, is this your patreon account?

**Comment by ggerganov** [comment]
It is mine, but I created it some time ago just to test things. I don't plan on using, so I just unpublished it

**Comment by aiaicode** [comment]
https://github.com/sponsors/ggerganov#sponsors
