### ISSUE TITLE
[Janek] export-lora error

### ISSUE THREAD

**Issue by janek1969** [ggerganov/llama.cpp#3547]
I am running the latest code. - [ ] I carefully followed the [README.md]
I already finetune orca-mini-3b.q4_0.gguf model with shakespeare.txt.
./finetune --model-base ./models/orca-mini-3b.q4_0.gguf --train-data shakespeare.txt
It's work fine.
When I tried to merge lora with this command:
./export-lora --model-base ./models/orca-mini-3b.q4_0.gguf --model-out orca-mini-3b.Q8_0.gguf --lora ./ggml-lora-256-f32.gguf
I always get this error:
error: unexpectedly reached end of file

I use llama.cpp on linux, ubuntu 22.04 LTS

What is is the problem?

**Comment by yukiarimo** [comment]
How to train Lora:

# finetune LORA adapter (cd into llama.cpp)
./finetune \
        --model-base open-llama-3b-v2-q8_0.gguf \
        --lora-out lora-open-llama-3b-v2-q8_0-shakespeare-ITERATION.bin \
        --train-data "shakespeare.txt" \
        --save-every 10 \
        --threads 6 --adam-iter 30 --batch 4 --ctx 64 \
        --use-checkpointing

Use .bin only, and try to merge with model the file from “--lora-out”

**Comment by janek1969** [comment]
> > How to train Lora:
> 
> finetune LORA adapter (cd into llama.cpp):
> 
> ```
> ./finetune \
>         --model-base open-llama-3b-v2-q8_0.gguf \
>         --lora-out lora-open-llama-3b-v2-q8_0-shakespeare-ITERATION.bin \
>         --train-data "shakespeare.txt" \
>         --save-every 10 \
>         --threads 6 --adam-iter 30 --batch 4 --ctx 64 \
>         --use-checkpointing
> ```
> 
> Use .bin only, and try to merge with model the file from “--lora-out”

Thank you! I tried it.
Here is the output:
save_checkpoint_lora_file: saving to checkpoint-30.gguf
save_checkpoint_lora_file: saving to checkpoint-LATEST.gguf
save_as_llama_lora: saving to ./lora-open-llama-3b-v2-q8_0-shakespeare-30.bin
save_as_llama_lora: saving to ./lora-open-llama-3b-v2-q8_0-shakespeare-LATEST.bin
train_opt_callback: iter=    30 sample=121/26766 sched=0.300000 loss=3.720757 dt=00:00:44 eta=0.0ms |--->
main: total training time: 00:22:58

I can't see any error message,but no lora output file.
No generated lora-open-llama-3b-v2-q8_0-shakespeare-ITERATION.bin

**Comment by yukiarimo** [comment]
`./lora-open-llama-3b-v2-q8_0-shakespeare-30.bin` this is your LoRA for the 30th iteration, and the `LATEST` is the final one. Files with `.gguf` are checkpoints, NOT a LoRA. They are only can be used to continue this process, nothing more.

By the way, how long it was on your hardware for fine tuning it?

**Comment by janek1969** [comment]
> `./lora-open-llama-3b-v2-q8_0-shakespeare-30.bin` this is your LoRA for the 30th iteration, and the `LATEST` is the final one. Files with `.gguf` are checkpoints, NOT a LoRA. They are only can be used to continue this process, nothing more.
> 
> By the way, how long it was on your hardware for fine tuning it?

Thanks for all. I reinstall ubuntu on my PC and everything work fine. 
Its about 22 minute on my ASUS gamer pc. I've got just only 8MB video RAM on my card. Can i force to finetune on CPU and system RAM. I've got 32GB system memory.

**Comment by yukiarimo** [comment]
I think you need to just compile without a CUDA support to use it on a cpu
