### ISSUE TITLE
How to make RLHF?

### ISSUE THREAD

**Issue by yukiarimo** [ggerganov/llama.cpp#3561]
For example consider this model: https://huggingface.co/TheBloke/Pygmalion-2-7B-GGUF

I want to make (good/bad) RLHF like this:

User: Which drug do you like?
AI: I like Meth (say this bad, and maybe provide good response)
User: What is your name?
AI: I’m ChatGPT (say this is good, and provide another good response, or not)

Then using this knowledge fine tune LoRA or Model

**Comment by BarfingLemurs** [comment]
Most UI developers probably already add a 👍 👎 , where 👍 saves your input output. Once you 1000 👍 , you train saved messages

**Comment by yukiarimo** [comment]
Are you talking about 👍 👎 in ChatGPT or Character.AI? Because as far as I know in the open source UIs like ooba or TavernAI, etc, there no ranking (even fine-tuning guides are not well-explained yet)
