### ISSUE TITLE
Memory Leak Issue in LLaMA Model on Nvidia Jetson Xavier NX (Arm Architecture)

### ISSUE THREAD

**Issue by CYOT** [ggerganov/llama.cpp#3566]
Hello,

I am currently working on porting Facebook's LLaMA model to C/C++ on an Nvidia Jetson Xavier NX, which is running on Arm architecture. While running the model, I encountered a memory-related error that I am struggling to resolve.

The error message I am receiving is as follows:

ggmt allocr_alloc: not enough space in the buffer (needed 442368, largest block available 290848)
GGML ASSERT: /tmp/pip-install-baveqmyh/llama-cpp-python_d4e9ef77404340ef9ee6ed0288b202c0/vendor/llama.cpp/ggml-alloc.c:1731: !"not enough space in the buffer"
Aborted (core dumped)

Here are some details about my hardware setup:

Nvidia Jetson Xavier NX
GPU: 15GB
RAM: 7GB
Architecture: Arm64

I have tried several approaches to debug and resolve this issue, including: Clearing the cache memory and attempting to run the model again.

If you have any insights, suggestions, or recommendations on how to identify and fix this memory leak problem in the LLaMA model on the Nvidia Jetson Xavier NX, I would greatly appreciate your assistance.

Thank you in advance for your time and help. Your expertise would be invaluable in resolving this issue and making progress on my project.

**Comment by KerfuffleV2** [comment]
Are you sure it's a memory leak rather than there just being insufficient memory? (Or possibly the initial context size getting calculated incorrectly?)

There were some recent changes to GGML alloc stuff, I see you're using the Python wrapper so it's possible they haven't adapted fully to those changes.

**Comment by CYOT** [comment]
Thank you for your response and the insights you've provided.
Regarding your question about whether it's a memory leak or insufficient memory, I've considered that possibility as well. I initially suspected it might be an issue with insufficient memory, but I have ensured that the Nvidia Jetson Xavier NX I'm using has sufficient resources for the task. It has 7GB of RAM, and I've cleared the cache memory before running the code. With a prompt size of around 90 tokens, I believed it should be well within the hardware's capabilities. If I input more around 100 tokens it is throwing the error.
You also mentioned recent changes to GGML alloc stuff, and it's possible that the Python wrapper I'm using hasn't fully adapted to these changes. Could you provide any information on these recent changes or suggest any updates or adjustments I should make in the code to accommodate them?

**Comment by slaren** [comment]
The most common cause of this error is exceeding the batch size used to initialize the context (`n_batch`). `llama_eval` or `llama_decode` cannot be called with more tokens than `n_batch`. The current master has checks for this, so this should only happen if you are using an old version of the code.
