### ISSUE TITLE
[User] 按照步骤跑，报错：CANNOT LINK EXECUTABLE "cmake": library "libcrypto.so.3" not found

### ISSUE THREAD

**Issue by ewwerpm** [ggerganov/llama.cpp#3579]
termux 0.117，ndk是官网下载的 android-ndk-r25c-linux.zip ，执行
$ pkg install clang wget git cmake
$ mkdir build-android
$ cd build-android
$ export NDK=<your_ndk_directory>
后，执行 
$ cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
报错：CANNOT LINK EXECUTABLE "cmake": library "libcrypto.so.3" not found
按照chatgpt的提示，执行  pkg install openssl 后，
又报错：CANNOT LINK EXECUTABLE "cmake": library "libssl.so.1.1" not found
按照chatgpt的提示：执行 
 $ ln -s /usr/lib/libssl.so /usr/lib/libssl.so.1.1
ln: failed to create symbolic link '/usr/lib/libssl.so.1.1': No such file or directory
还是报错，估计是ndk的版本问题。请问该用哪个版本的ndk啊？cmake有版本要求吗？谢谢

**Comment by KerfuffleV2** [comment]
我找到这个：https://stackoverflow.com/questions/71337612/cannot-link-executable-node-library-libcrypto-so-3-not-found
看起来比较像，`pkg update openssl-tool`很有可能会解决了问题。（抱歉，我的中文不太高级）

**Comment by ewwerpm** [comment]
谢谢，确实解决了问题

**Comment by qesadwzxc** [comment]
加个解决方法，如果升级了openssl-tool还是不行的话，可以使用pkg upgrade命令，升级一下所有的包
add other resolve，if problem not fixed after use `pkg update openssl-tool`，you can try to use `pkg upgrade` command to upgrade all package
