### ISSUE TITLE
Unable to convert Mistral-7B-OpenOrca to GGUF

### ISSUE THREAD

**Issue by Nate687** [ggerganov/llama.cpp#3583]
Hello,

I am attempting to convert the [Mistral-7B-OpenOrca](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca) to GGUF using "convert.py" 
I understand that TheBloke has released a GGUF version, however I am wanting to convert it myself on my local computer.

However I keep getting the error:

`Exception: Expected added token IDs to be sequential and start at 6; got [0, 1, 2, 32000, 32001, 32002]
`

I believe this is due to the additional "added_tokens.json" file that Mistral-7B-OpenOrca has.

A similar issue was reported [here](https://github.com/ggerganov/llama.cpp/discussions/3368#discussioncomment-7231555)  

However there was no fix?

Any solutions or pointers would be greatly appreciated.

Thanks,
Nate

**Comment by HenkPoley** [comment]
You can use this, or ask Eric Hartford how he did it: https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GGUF

**Comment by seungduk-yanolja** [comment]
```
        self.vocab_size_base: int = vocab_size
        self.vocab_size: int = self.vocab_size_base + 3
```
find this in SentencePieceVocab (convert.py) and just use `+ 3`

**Comment by seungduk-yanolja** [comment]
wrote a PR https://github.com/ggerganov/llama.cpp/pull/3585

**Comment by staviq** [comment]
For a quick workaround, for this model specifically, in added_tokens.json delete lines with tokens 0,1,2, because those particular tokens are basically always assumed to be in the vocab already, and you are not removing them, that definition isn't needed in this specific case.
