### ISSUE TITLE
windows10系统，cmake编译的时候，出问题

### ISSUE THREAD

**Issue by ewwerpm** [ggerganov/llama.cpp#3608]
![image](https://github.com/ggerganov/llama.cpp/assets/25223652/a322edbc-cb42-4fd1-b462-56380089d96d)

完全按照以下步骤来的：
mkdir build
cd build
cmake ..
cmake --build . --config Release
请大佬指点，谢谢

**Comment by chenqiny** [comment]
你能用英语表达吗? 维护人员的母语不是中文, 应该看不懂
Can u using English?  I guess the maintainer can not read Chinese.

**Comment by ewwerpm** [comment]
use cmake, I get error.  (and  as far as I am concerned, the other one gets error when using cmake), the error is showed as up.  But i get success by using make,so this question is not urgent . thank you
