### ISSUE TITLE
华为手机，termux 上make后，生成的chat.sh文件，不在scripts/llama-cpp目录下

### ISSUE THREAD

**Issue by ewwerpm** [ggerganov/llama.cpp#3609]
![image](https://github.com/ggerganov/llama.cpp/assets/25223652/8467ecaf-32c3-4dda-a30f-7ff4237edd59)
按照 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh 的step 3，chat.sh应该在 scripts/llama-cpp 目录下，但是我的不是。
生成的chat.sh，也能用。但是还是想确认一下，chat.sh在examples目录下，也是正常的，是吗？是不是要通知  https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh 作者修改step 3？谢谢

**Comment by chenqiny** [comment]
你能用英语表达吗? 维护人员的母语不是中文, 应该看不懂
Can u using English?  I guess the maintainer can not read Chinese.

**Comment by ewwerpm** [comment]
as the picture show, i get  "chat.sh" in “examples”  directory，but  in https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh   ，his           “step 3” says ，the "chat.sh" is in  scripts/llama-cpp  directory. who is correct?thank you

**Comment by chenqiny** [comment]
You can just correct it for him and create a pull request in that repo.

**Comment by KerfuffleV2** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh 说“请首先将本项目的`scripts/llama-cpp/chat.sh`”。我觉得他的意思是在 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/tree/main/scripts/llama-cpp 的 `chat.sh`，而不是在 https://github.com/ggerganov/llama.cpp 的。wiki还说应该拷贝从他的项目到`llama.cpp`的根目录。

The wiki said "本项目的`scripts/llama-cpp/chat.sh`". That's probably referring to the `chat.sh` in _that_ project, not the one here. It also said you need to copy the `chat.sh` from that repo to the root directory in this one.

**Comment by ewwerpm** [comment]
我试试直接在他的github上留 issue

**Comment by ewwerpm** [comment]
> https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh 说“请首先将本项目的`scripts/llama-cpp/chat.sh`”。我觉得他的意思是在 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/tree/main/scripts/llama-cpp 的 `chat.sh`，而不是在 https://github.com/ggerganov/llama.cpp 的。wiki还说应该拷贝从他的项目到`llama.cpp`的根目录。
> 
> The wiki said "本项目的`scripts/llama-cpp/chat.sh`". That's probably referring to the `chat.sh` in _that_ project, not the one here. It also said you need to copy the `chat.sh` from that repo to the root directory in this one.

这个chat.sh，应该是编译出来的啊。不编译，应该没有

**Comment by zhangheli** [comment]
请用这个chat.sh，我用是可以的，https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/llama-cpp/chat.sh

**Comment by ewwerpm** [comment]
> 请用这个chat.sh，我用是可以的，https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/llama-cpp/chat.sh

谢谢，我自己编译出来的，也能用。就是目录不一样，所以问问。你难道没有自己编译出来？
