### ISSUE TITLE
Building C object CMakeFiles/ggml.dir/ggml.c.o failed

### ISSUE THREAD

**Issue by PingEnLu** [ggerganov/llama.cpp#3611]
I've typed:
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON
cmake --build . --config Release

Failed on:
[  2%] Building C object CMakeFiles/ggml.dir/ggml.c.o

The error shows: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
gmake[2]: *** [CMakeFiles/ggml.dir/build.make:76: CMakeFiles/ggml.dir/ggml.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:650: CMakeFiles/ggml.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

![image](https://github.com/ggerganov/llama.cpp/assets/37340566/e2cf3c4d-1eca-48e7-a770-e54a8f5d7743)

**Comment by staviq** [comment]
What platform/system are you running this on ?

**Comment by PingEnLu** [comment]
> What platform/system are you running this on ?

Running on a writable singularity container (NGC PyTorch 23.08) on Ubuntu 22.04 VM on Windows 10.

**Comment by KerfuffleV2** [comment]
Seems like it may be related to not having SSE (or whatever) support: https://stackoverflow.com/questions/35772562/inlining-failed-in-call-to-always-inline-m128i-mm-cvtepu8-epi32-m128i-t

Since you said you're running it in a container, maybe it's not correctly detecting what SIMD stuff is available. You can try messing with options like `LLAMA_AVX`

**Comment by hiarcs** [comment]
Same issue, I tried on Fedora 38 (bare metal) / CentOS 7 (vm) / Ubuntu 22.04 (vm), gcc 11/12, cuda 12.2/12.3, all failed. I can use make to build the cuBLAS version and I can use CMake to build the AVX512 version, but have no idea how to obtain a version that supports both CUDA and AVX512 simultaneously.

**Comment by staviq** [comment]
> supports both CUDA and AVX512 simultaneously.

AVX is something that your CPU is supposed to have, is a CPU instruction set extension and it's entirely dependent on the hardware, or if you are using docker, containers or virtual machines, some CPU extensions can get blocked by the VM/container host.

**Comment by hiarcs** [comment]
> AVX is something that your CPU is supposed to have, is a CPU instruction set extension and it's entirely dependent on the hardware, or if you are using docker, containers or virtual machines, some CPU extensions can get blocked by the VM/container host.
My case doesn't involve VM/container issues, it's a bare metal fedora box. My goal is that when I distribute the workload between the GPU and CPU, CPU calculations won't take too long (tests show that enabling AVX results in a 2.5x acceleration in my scenario).

**Comment by KerfuffleV2** [comment]
Check the options with `cmake`, it has a number of them for AVX512 specifically. The `Makefile` seems to just rely on using `-march=native -mtune=native` (in other words, let the compiler use all available features). For cmake, there's nothing stopping you from setting the AVX options in addition to the CUDA ones.

If you wanted to specifically set specific compiler options, you can edit the `Makefile` or possibly arrange to add them to `CFLAGS` some other way.

But there's probably something weird going on if the compiler didn't detect support.
