### ISSUE TITLE
[Question] WARP_SIZE as 64 for MI GPUs?

### ISSUE THREAD

**Issue by jammm** [ggerganov/llama.cpp#3630]
MI GPUs based on the gfx9xx architecture such as MI100 and MI200 natively run on wave64 (64 threads per warp/wave). That means by not setting `WARP_SIZE` as `64`, we're not able to fully utilize those GPUs. RDNA1 onwards support wave32 as well as wave64, so it can still run well when WARP_SIZE is `32`.

What would it take to get `WARP_SIZE` of `64` to work? I tried it and ran llama2 7b q4_0 but regardless of a prompt I give, the result is always `######...`

I suspect the reduction kernels that use `__shfl_*_sync` have the last parameter width set to `32`. So I tried setting those to `WARP_SIZE` as well, as well as setting the `s_sum` size to `WARP_SIZE`, but that didn't make any difference. Am I missing something? I guess there's still many parts of the code that rely on `WARP_SIZE` set to `32`, so I was wondering which parts I should look at.

**Comment by pomoke** [comment]
I got repeating symbols as well on Vega 7, while WRAP_SIZE of 64 can reach near 5 token/s than 3 token/s by 32.

**Comment by jammm** [comment]
Actually I just realized that `shlf_*_sync` doesn't really use the mask parameter at all in HIP. The mask is ignored and instead the non-sync variants are used.

**Comment by pomoke** [comment]
And there are hard-coded 32's in some of functions, such as `rms_norm_f32`. The `lane_id` is within `0` to `WARP_SIZE-1`, while `s_sum` is only 32-itemed.

**Comment by pomoke** [comment]
Also, try `./benchmark-matmult`. Matrix multiplication may be problematic.
