### ISSUE TITLE
./server endpoint doesn't support --rope-scale parameter

### ISSUE THREAD

**Issue by IridiumMaster** [ggerganov/llama.cpp#3647]
# Prerequisites

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
./server --model models/<YourModelHere>.gguf --n-gpu-layers 128 --ctx-size 16384 --port <yourPortHere> --host 0.0.0.0 --rope-scale 4
should run, in the same way that that 
./main --model models/<YourModelHere>-Q4_K_M.gguf --n-gpu-layers 128 --ctx-size 16384  --rope-scale 4 --prompt "<YourPromptHere>"

currently works. 

I am attempting to run some long context models using the server endpoint. The parameter I use with command line llama.cpp does not work with the server endpoint and does not appear to be supported.

# Current Behavior
The error "error: unknown argument: --rope-scale
usage: ./server [options]"
is produced instead.

As illustrated, the parameter produces an error.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

This is running on an M2 MacBook Pro with 96gb of RAM and a 1 TB hard drive, on the latest MacOS 
python 3.10.2
GNU Make 3.81
lang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

# Failure Information (for bugs)
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
I do not believe this is a bug, but rather an omission from the current implementation of ./server

**Comment by shibe2** [comment]
Argument for `--port` is missing in your command line.

**Comment by IridiumMaster** [comment]
It got truncated by Github when I was trying to be clever. Here is the full command:
travis.good@MT-M-YV7QRX7YQJ llama.cpp % ./server --model models/giraffe/giraffe-Q4_K_M.gguf --n-gpu-layers 128 --ctx-size 16384 --port 5005 --host 0.0.0.0 --rope-scale 4
error: unknown argument: --rope-scale
usage: ./server [options]


It produces the same error as described.

**Comment by IridiumMaster** [comment]
@klosax , I noticed you did the --rope-scale parameter for the main program. Would you be willing to alter the server similarly?
