### ISSUE TITLE
Also getting this error as of today. Updated torch, getting the same error on consolodated.00.pth

### ISSUE THREAD

**Issue by sachio222** [ggerganov/llama.cpp#3686]
This solution did not work initially for my error. 

From the llama README (https://github.com/facebookresearch/llama/blob/main/README.md)

"⚠️ 7/18: We're aware of people encountering a number of download issues today. Anyone still encountering issues should remove all local files, re-clone the repository, and [request a new download link](https://ai.meta.com/resources/models-and-libraries/llama-downloads/). It's critical to do all of these in case you have local corrupt files."

              Also getting this error as of today. Updated torch, getting the same error on consolodated.00.pth
checking https://github.com/ggerganov/llama.cpp/issues/1994#issuecomment-1662873639 for solution

_Originally posted by @sachio222 in https://github.com/ggerganov/llama.cpp/issues/3355#issuecomment-1771384582_

**Comment by sachio222** [comment]
accidentally created this issue, meant to reply to https://github.com/ggerganov/llama.cpp/issues/3355

**Comment by shibe2** [comment]
If this is a user error with downloading files then this issue can be closed.
