### ISSUE TITLE
Adding Support for Intel GPUs with sycl

### ISSUE THREAD

**Issue by AlexFierro9** [ggerganov/llama.cpp#3695]
I would like to drop an enhancement proposal for Intel's SYCL standard that can allow better performance for Intel GPU's(Intel Arc and the DataCenter Series), it's the Intel Equivalent to CUDA and ROCm.

If providing manpower for this proposal is not possible, I request to be assigned this issue and I'll be more than happy to work on this

**Comment by shibe2** [comment]
I'm working on OpenCL back-end. Would be interested to collaborate on SYCL as well, if time permits.

**Comment by AlexFierro9** [comment]
Actually Intel has created a tool called Syclomatic, it can port pretty much all of the CUDA backend all by itself, all that would be left is integrating the new files into current methods, and any other optimizations we might want to do.

Here take a look: [SYCLomatic](https://www.intel.com/content/www/us/en/developer/articles/technical/syclomatic-new-cuda-to-sycl-code-migration-tool.html)

**Comment by koech-v** [comment]
Patiently waiting for this. Any progress?

**Comment by AlexFierro9** [comment]
As it turns out there is an already open issue for this
