### ISSUE TITLE
can't compile main

### ISSUE THREAD

**Issue by tinoargentino** [ggerganov/llama.cpp#37]
I’m trying to compile main to play around with it and failing with error:

```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

on macOS M1

trying to compile by running  `g++ main.cpp -o main -v -std=c++11`

anyone know what I'm missing?

**Comment by wizzard0** [comment]
you need to use make. or just peek at the makefile and copy commands from there.

**Comment by tinoargentino** [comment]
that's it! thanks so much!
