### ISSUE TITLE
Prompt evaluation performance regression in llama.cpp on RDNA3 with HSA_OVERRIDE_GFX_VERSION=11.0.1 vs 11.0.0

### ISSUE THREAD

**Issue by Googulator** [ggerganov/llama.cpp#3701]
(Probably a ROCm issue - see https://github.com/RadeonOpenCompute/ROCm/issues/2590 -, but maybe llama.cpp devs can also weigh in.)

We're evaluating llama.cpp with ROCm offloading on various RDNA3 GPUs (primarily RX 7800 XT and RX 7900 XT).

On initial testing, we found that a 13b model with Q6_K quantization fully offloaded to GPU (-ngl 43) showed significantly slower prompt evaluation times on the 7800 compared to the 7900, far beyond what would be expected from the relative performance difference between these 2 GPUs. On the 7800, prompt evaluation would take more than a minute on our example prompt, while it was near instantaneous (less than a second) on the 7900.

Upon further investigation, the RX 7800 shows a 3 second penalty for every 64 tokens of prompt (0-64 tokens 3 seconds, 65-128 tokens 6s, 129-192 tokens 9s, and so on) over the 7900.

Since the 7800 is recognized by ROCm as gfx1101, vs gfx1100 on the 7900, we tried setting HSA_OVERRIDE_GFX_VERSION=11.0.0, which led to massive performance improvement, with the 7800 only proportionally slower than the 7900, as expected based on the specifications. We then tested HSA_OVERRIDE_GFX_VERSION=11.0.1 (and 11.0.2) on the 7900, and saw the exact same performance issue as on the 7800.

The testing was performed on Ubuntu 22.04.3 Server, using ROCm v5.7.0, apparently the latest version available for this version of Ubuntu. The issue was reproducible using the very latest llama.cpp code and a newly quantized model.

**Comment by shibe2** [comment]
I would be interesting to see also numbers for CLBlast back-end.

**Comment by kzhuravl** [comment]
This was rootcaused by @Pierre-vh and Stempen, Vladimir as an issue in llama.cpp.

Fix is here: https://github.com/ggerganov/llama.cpp/pull/4787
