### ISSUE TITLE
Error with convert-finetune-checkpoint-to-gguf.py

### ISSUE THREAD

**Issue by Drael64** [ggerganov/llama.cpp#3707]
I honestly have no idea what I am doing with this script, but with or without the -i/-o or --i/--o flags, this script returns the error:

 File "A:\llama.cpp\convert-finetune-checkpoint-to-gguf.py", line 5, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'

I have finetuned a model, have the gguf checkpoints, and lora bin fines from that finetuning, but other than being able to run in main (which isn't very useful in itself), I can't really access or use my finetune (like I can't use it in koboldcpp, and afaik, I can't use peft applications to merge it back into the main model. 

I'm really not a coder, and I don't know where to go from here to properly use or test my finetune, or better yet, merge it back in to the full base model. I was told, to use it with koboldcpp, I could use this script. But it returns an error - as does koboldcpp itself if I use either the bin or gguf files in the lora section. 

Help!

**Comment by xaedes** [comment]
>ModuleNotFoundError: No module named 'gguf'

You need to install llama-gguf. 

```bash
cd llama.cpp
pip install -e ./gguf-py
```

**Comment by Drael64** [comment]
> > ModuleNotFoundError: No module named 'gguf'
> 
> You need to install llama-gguf.
> 
> ```shell
> cd llama.cpp
> pip install -e ./gguf-py
> ```

That's great and helps. But then if I run it with the gguf finetune.exe outputs as the input file it gives:

   raise ValueError(f"File header magic indicates, that this is no finetune-lora checkpoint file. Expected 'ggcl', Got '{str(magic)}'")
ValueError: File header magic indicates, that this is no finetune-lora checkpoint file. Expected 'ggcl', Got 'b'FUGG''

And if I run it with the bin file that finetune.exe outputted it gives:

 raise ValueError(f"File header magic indicates, that this is no finetune-lora checkpoint file. Expected 'ggcl', Got '{str(magic)}'")
ValueError: File header magic indicates, that this is no finetune-lora checkpoint file. Expected 'ggcl', Got 'b'ggla''

Is this simply not for running on the checkpoint/lora's that finetune.exe outputs?

**Comment by xaedes** [comment]
Before the introduction of the GGUF file format finetune would store checkpoints in another file format.
`convert-finetune-checkpoint-to-gguf.py` is for converting these old checkpoint files to the new GGUF checkpoint file format. 

It sounds like you want to convert the finetune output LORA file to a GGUF model that you can load directly with main.
You can do this with `export-lora`. For example:
```bash
finetune --model-base model.gguf --lora-out LORA.bin --train-data "yourdata.txt" <other args ...>
export-lora --model-base model.gguf --lora LORA.bin --model-out new_model.gguf
main -m new_model.gguf
```

Alternatively you can just run main with `model.gguf` and your `LORA.bin`:
```bash
main -m model.gguf --lora LORA.bin
```
