### ISSUE TITLE
Sorry, your GGJTv1 file of type MOSTLY_Q4_1_SOME_F16 is not eligible for conversion

### ISSUE THREAD

**Issue by djbritt** [ggerganov/llama.cpp#3708]
ValueError: Quantizations changed in GGJTv2. Can only convert unquantized GGML files older than GGJTv2. Sorry, your GGJTv1 file of type MOSTLY_Q4_1_SOME_F16 is not eligible for conversion.

I got this file from

https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main/gpt4-x-alpaca-13b-ggml-q4_1-from-gptq-4bit-128g

It gives me 

ggml-model-q4_1.bin

I ran 

`python3.10 convert-llama-ggml-to-gguf.py --input models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.bin --output models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.gguf
`
I am trying to use llama.cpp to use this model as so

`./main -m models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.bin -t 4 -c 2048 -n 2048 --color -i --instruct
`
It fails with 

```
Log start
main: build = 1407 (465219b)
main: built with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for x86_64-linux-gnu
main: seed  = 1697867527
gguf_init_from_file: invalid magic characters tjgg.
error loading model: llama_model_loader: failed to load model from models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.bin

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.bin'
main: error: unable to load model
```

Any help would be appreciated.

**Comment by Green-Sky** [comment]
looks like you are not using the converted file ? (`.bin` instead of `.gguf`)

**Comment by djbritt** [comment]
@Green-Sky If you checkout the huggingface URL I pasted in my post, you'll see it only gives me a bin file. My question is how do I convert this bin file to a gguf file. Thanks!

**Comment by Green-Sky** [comment]
@djbritt pretty sure your `python3.10 convert-llama-ggml-to-gguf.py --input models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.bin --output models/gpt4-x-alpaca-13b-native-4bit-128g/ggml-model-q4_1.gguf` looks about right.

**Comment by monatis** [comment]
As the error message explicitly puts it, due to the unsupported quantization scheme in that file which was obssoleted even before GGUF, it's not possible to convert it to GGUF. I recommend you to find the original Pytorch checkpoints of that model and do a fresh conversion with the recent code.

**Comment by monatis** [comment]
No idea about this particular model. You may try to contact the original sharer in the "Community" tab of those HF repose.

**Comment by KerfuffleV2** [comment]
Please see my response here: https://github.com/ggerganov/llama.cpp/discussions/3737#discussioncomment-7355944

You should be able to use `convert.py` to convert to GGUF from the first link you pasted. Any specific reason you want to use that exact model though? It's pretty old (LLM development moves really fast) and there are currently models half the size that outperform it in all respects as far as I know.

**Comment by djbritt** [comment]
@KerfuffleV2 

Here's what happens when I try.

```
python3.11 ./convert.py /home/djbritt/llama/models/ggml-model-q4_1.bin
Loading model file /home/djbritt/llama/models/ggml-model-q4_1.bin
Traceback (most recent call last):
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1202, in <module>
    main()
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1135, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1054, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 748, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: /home/djbritt/llama/models/ggml-model-q4_1.bin

```

**Comment by djbritt** [comment]
And when I try to just use model folder

```
python3.11 ./convert.py /home/djbritt/llama/models/
Traceback (most recent call last):
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1202, in <module>
    main()
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1135, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1045, in load_some_model
    raise Exception(f"Can't find model in directory {path}")
Exception: Can't find model in directory /home/djbritt/llama/models

```

**Comment by KerfuffleV2** [comment]
> Here's what happens when I try.

You tried to use `convert.py` on the bin file in second link, not the ones in the first link.

Quoting from your other post:


> 1- https://huggingface.co/chavinlo/gpt4-x-alpaca/tree/main

^^^^ This is the one you want to run `convert.py` on. Note that you have to download that whole repo, all the bin files, all the JSON files, etc and then point `convert.py` at the directory they're in.

> 2- https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main/gpt4-x-alpaca-13b-ggml-q4_1-from-gptq-4bit-128g

^^^^ This is an old style GGML file. You can't use `convert.py` on this and it's too old to convert from GGML to GGUF. Basically you can't do anything with this one.

**Comment by djbritt** [comment]
@KerfuffleV2 
What about this folder

https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main/gpt4-x-alpaca-13b-ggml-q4_1-from-gptq-4bit-128g

That says

added ggml quantization for cuda model

I just downloaded that specific bin file, is this not a valid route to use llama.cpp with this bin file?

**Comment by goerch** [comment]
> @KerfuffleV2 What about this folder
> 
> https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main/gpt4-x-alpaca-13b-ggml-q4_1-from-gptq-4bit-128g
> 
> That says
> 
> added ggml quantization for cuda model
> 
> I just downloaded that specific bin file, is this not a valid route to use llama.cpp with this bin file?

No, I don't think you can expect earlier quantizations of `llama.cpp` to be updated auto-magically. But I think there is still a good chance to quantize the original models.

**Comment by djbritt** [comment]
@KerfuffleV2 

Ok I tried another model from TheBloke

https://huggingface.co/TheBloke/Mistral-Pygmalion-7B-AWQ/tree/main

I try to convert the entire folder

```
python3.11 ./convert.py ~/llama/models/Mistral-Pygmalion-7B-AWQ/
Traceback (most recent call last):
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1202, in <module>
    main()
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1135, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djbritt/llama/llama.cpp/./convert.py", line 1045, in load_some_model
    raise Exception(f"Can't find model in directory {path}")
Exception: Can't find model in directory /home/djbritt/llama/models/Mistral-Pygmalion-7B-AWQ

```
I try to use ./main on the entire folder
```

./main -m ~/llama/models/Mistral-Pygmalion-7B-AWQ/ -t 4 -c 2048 -n 2048 --color -i --instruct
Log start
main: build = 1416 (5be6c80)
main: built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: seed  = 1698093946
gguf_init_from_file: invalid magic characters .
error loading model: llama_model_loader: failed to load model from /home/djbritt/llama/models/Mistral-Pygmalion-7B-AWQ/

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/home/djbritt/llama/models/Mistral-Pygmalion-7B-AWQ/'
main: error: unable to load model
```
If I have to use vllm I will. But I was hoping to use llama.cpp.

Thank you for all your help, I'm still a noob in this stuff. Trying to figure it all out.

**Comment by goerch** [comment]
> Ok I tried another model from TheBloke

Does @TheBloke document which `llama.cpp` version he is using to convert? Then it would be easy to use exactly that version of `llama.cpp` for your use case, I would think.

**Comment by KerfuffleV2** [comment]
> Ok I tried another model from TheBloke

That one is already quantized in AWQ format.

A little background info that might help you:

Models exist in an original format (on HF most of the time that's going to be "HuggingFace format") where there are a bunch of binary parts and also metadata describing various stuff about the model. For example: https://huggingface.co/chavinlo/gpt4-x-alpaca/tree/main

For the purposes of using `llama.cpp`, this is what you need if you want to convert to GGUF format. GGUF format is what `llama.cpp` uses, so you can use the HuggingFace format directly, you have to convert it first.

Generally when converting, people also quantize the model. That takes the model where each parameter is a 16bit number and basically compresses it down. Different projects support different types of quantization. `llama.cpp` uses GGML as the backend, so it supports the types of quantizations that GGML supports: Q4_0, Q4_K_M, etc.

There are other projects that have developed their own quantizations and file formats. AWQ is one, GPTQ is another, there are also others I didn't mention. Like with `llama.cpp` and GGML, they started with the HuggingFace format model and converted to the format their project can handle.

Also, quantization is a lossy process, kind of like compressing a video file. Some of the data is lost, so you can't really take an AWQ or some other already quantized format and convert it to GGUF with the quantization formats `llama.cpp` supports.

The reason why the GGML (file format) to GGUF conversion can work in some cases is because the actual quantized data format didn't change, even though the container of the file changed. Kind of like how you can repackage a `.webm` into a `.mp4` file by just copying the x264 video data (this analogy may or may not make sense). Anyway, there _have_ been changes to quantization formats in the history of the `llama.cpp` project so if you go back far enough you'll find incompatible changes. 

***

It looks like you downloaded `Mistral-Pygmalion-7B-AWQ` - that's just the wrong format for `llama.cpp`. TheBloke actually already published pre-converted GGUF format files which will work: https://huggingface.co/TheBloke/Mistral-Pygmalion-7B-GGUF

Any of the `.gguf` files there should work. **Note**, unlike when trying to convert from the HuggingFace format repo, you only need one of those.

**Comment by djbritt** [comment]
@KerfuffleV2 

You've been very helpful, thank you.

A question I have for you, is that you refer to huggingface as a format. Am I mistaken in my understanding, that huggingface is just an online repo, like github? Or is huggingface really it's own format?

You did clarify for me why awq won't work with llama.cpp, and I see how the other url you gave me is a gguf format, which is what is needed, thank you.

**Comment by KerfuffleV2** [comment]
Glad it helped!

> A question I have for you, is that you refer to huggingface as a format. Am I mistaken in my understanding, that huggingface is just an online repo, like github? 

A little bit. HuggingFace is company, it's also a service that provides a repo, and various other stuff like selling time on machines for training or running models.

They also developed their own machine learning library called Transformers as well as other associated libraries/tools. Naturally, the stuff they wrote themselves works most easily/seamlessly on their platform. https://huggingface.co/docs/transformers/index

"HuggingFace format" is a bit of an oversimplification but people do say that. I didn't want to confuse you with a bunch of unnecessary details like there are actually a whole bunch of files in those repos, of various formats, that come from various places and were developed by various entities. "HuggingFace format" is basically just the general set of file formats/data/files/etc that HF encourages for distributing models on their site.

**Comment by djbritt** [comment]
Ok. Another general question for you, I think this is my last. Is there a master list of all open source language models, and their categories, so I can browse them? Like I see all of TheBlokes models, but I don't know what they are good at.

**Comment by djbritt** [comment]
@KerfuffleV2 sorry I didn't tag you in the previous comment.

**Comment by KerfuffleV2** [comment]
>  Is there a master list of all open source language models, and their categories, so I can browse them?

Not that I'm aware of. You can sometimes guess some stuff about their category by looking at the name. I.E. `blahblah-chat` or `blahblah-instruct` is likely to be an instruction tuned model. Meaning you directly ask it questions or tell it to do things. Non-instruct-tuned models just complete text, so you often won't get good results trying to have a dialog with them.

TB's models include a README that starts out with some general information. If you scroll down you'll find the original model card included there as well. Usually the original model card will include some information about the model's capabilities.

You can also look at the HuggingFace leaderboard to get some idea of what models are performing well. Note: That's based on synthetic tests, it doesn't necessarily guarantee they'll perform best for a specific task, or in real-world conditions but it's a fast way to evaluate a bunch of models at the same time. Link: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

**Comment by djbritt** [comment]
@KerfuffleV2 
Thank you. You have been such a great help to me.

Is there any chance you have any idea about another bug I ran into? https://github.com/ggerganov/llama.cpp/issues/3755

**Comment by TheBloke** [comment]
> > Ok I tried another model from TheBloke
> 
> Does @TheBloke document which `llama.cpp` version he is using to convert? Then it would be easy to use exactly that version of `llama.cpp` for your use case, I would think.

I do now, yes - in the commit message, eg: 
![image](https://github.com/ggerganov/llama.cpp/assets/784313/0689ef60-11ed-451e-a648-e550872442ef)

I've been doing that for the last month or two.

(Not that was related to this issue, as it seems OP was trying to convert an AWQ file!)
