### ISSUE TITLE
segmentation fault on 0.2.11 when just starting generated

### ISSUE THREAD

**Issue by wzg-zhuo** [ggerganov/llama.cpp#3712]
program teminted with signal SIGSEGV, Segmentation fault

**Comment by wzg-zhuo** [comment]
ok when use 0.1.78

**Comment by staviq** [comment]
I'm almost certain you are in the wrong GitHub project, llama.cpp isn't even versioned with n.n.n

Also, you should include logs in an issue report, or at least the console output, otherwise this gives us zero info to go off of.

**Comment by wzg-zhuo** [comment]
sorry,it is the newest version, the version above is llama_cpp_python

**Comment by shibe2** [comment]
Here is a plan.
- Report your crash to llama_cpp_python
- Track it down to an issue in llama.cpp
- Report that issue here with details related to llama.cpp

These details are required for investigation and identifying a solution. This report as it is now is useless.

**Comment by shibe2** [comment]
Also note that issue reports here are nominally required to be against the latest llama.cpp code, so one may need to pull current master from llama.cpp and compile the Python module from source.

Another option is to reproduce the crash with one of example apps in llama.cpp.
