### ISSUE TITLE
Loading model too verbose

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/llama.cpp#3756]
The loading of models takes and fills up the entire terminal due to a verbose loading process, scrolling or viewing previous commands for any reason is pain. There's about 300 lines.

Can we hide the loading details behind -verbose option if it's not a problem.

**Comment by Galunid** [comment]
`launch_command 2>/dev/null`, should get rid of all this, at least on linux.

**Comment by aiaicode** [comment]
> `launch_command 2>/dev/null`, should get rid of all this, at least on linux. Not to say that it's not a good idea to hide it behind `--verbose`

Works Beautifully. Linux has a solution for everything.
