### ISSUE TITLE
Finetuning on tensors with type 'f16' is not yet supported.

### ISSUE THREAD

**Issue by Shookapic** [ggerganov/llama.cpp#3759]
For more informations : I'm trying to fine tune a Vigogne 13b LLM with the "finetune" tool of LLAMACPP but I ended up with the error "Finetuning on tensors with type 'f16' is not yet supported." I understand the error but I wanted to know if I have any other option to fine tune the LLM ? Also is it possible to know what tensors type a LLM have ? What tensors type are actually supported with LLAMACPP ?

**Comment by Corallus-Caninus** [comment]
try converting it to f32.

**Comment by shookx** [comment]
> try converting it to f32.

How can I do this ? (sorry I'm very new)

**Comment by Corallus-Caninus** [comment]
use convert.py

https://github.com/ggerganov/llama.cpp/blob/238657db2364cfb728c694470a4a81702afea760/convert.py#L1122
