### ISSUE TITLE
suggestion for simpler implementation ggml_vec_dot_q4_K_q8_K 

### ISSUE THREAD

**Issue by shlevi-microsoft** [ggerganov/llama.cpp#3769]
in the ggml_vec_dot_q4_K_q8_K method, line 3242 in k_quants.c

The code block in k_quants.c 
https://github.com/ggerganov/llama.cpp/blob/ad939626577cd25b462e8026cc543efb71528472/k_quants.c#L3242C5-L3256C10

contains a loop that calculates the vector dot product using 8 nested loops. 
![image](https://github.com/ggerganov/llama.cpp/assets/93481053/8dbf513f-719c-4777-92dc-60cfb46b503b)

however, the 8 nested loops can be simplified into a single loop, which is more efficient and easier to understand. 

```
for (int j = 0; j < QK_K/32; ++j) {
          int32_t scale = scales[is++]; 
          for (int l = 0; l < QK_K/8; ++l) {
              int16_t mul = q8[l] * a[l];
              aux32[l % 8] += scale * mul;
          }
          q8 += 32; a += 32;
}
```

The simplified code block is mathematically identical to the original code and has been tested to produce the same results. 
Also, the aux16 is redundant. so we can save some memory as well

It's unclear why the original implementation used 8 nested loops instead of a single loop, is it more efficient?

**Comment by KerfuffleV2** [comment]
It's probably to encourage the compiler to unroll or vectorize the loops when optimizing.

**Comment by shlevi-microsoft** [comment]
@KerfuffleV2 is it worth changing?

**Comment by ggerganov** [comment]
> @KerfuffleV2 is it worth changing?

Unlikely. You can check the generated assembly in both cases (for example https://godbolt.org), but my guess is that this was intentionally written like this to improve the performance
