### ISSUE TITLE
[User] Chinese support

### ISSUE THREAD

**Issue by jinfagang** [ggerganov/llama.cpp#377]
Hi, when will support Chinese input support? Currently seems tokenizer didn't support, previous there were community PR support this, but long time didn't merge.

**Comment by j-f1** [comment]
Once you’ve regenerated the models using the latest conversion tool, you should be able to use non-Latin characters perfectly fine. Are you experiencing any issues?

**Comment by jinfagang** [comment]
thank u, solved.
