### ISSUE TITLE
Inconsistencies in Rope Dimension Count Specification in convert-to-gguf.py Scripts

### ISSUE THREAD

**Issue by maddes8cht** [ggerganov/llama.cpp#3773]
I've noticed an inconsistency in the convert-to-gguf.py scripts within the project. Specifically, a line like:
```
gguf_writer.add_rope_dimension_count(hparams["hidden_size"] // hparams["num_attention_heads"])
```
is present in about half of the convert-scripts. As far as I understand, this line seems to be necessary to enable a model to determine how to set the rope-freq for a desired net-context-length. In other words, it's used by Llama.cpp to set the correct rope-freq for a desired context-length for a model.

However, in the following scripts: convert-falcon-hf-to-gguf.py, convert-mpt-hf-to-gguf.py, convert-starcoder-hf-to-gguf.py, and convert-bloom-hf-to-gguf.py, this specification is missing.

Is there a reason for this, or has it simply been forgotten (yet)?

**Comment by Galunid** [comment]
I'm pretty sure it's fine. I think all those models (I just checked falcon) use `n_embd_head` as rope dimension count, so there's no need to embed it in model. If it was set incorrectly, you'd see generation quality decline over time.

<details>
<summary>StableLM with <b>wrong</b> <i>rope dimension count</i></summary>

>The meaning of life is to be of Life for every
of life for me or existence in life
your life and life – life.ит life life life: life.
meaning Life life is the
life. world me being an meaning life in you life of life to your one life_ the of " life at. m of. (and. The. life to the see what This and life is' is" [. … of this a it/o her family as is it can life which is here the life.. life Mean me is Lifee death in my ors
 meaning is. earth finding person of p which you.[ m. life of. if search_? " " is by meaning is means. The is meaning ," but . said is mean
, me for meet it you after. to that the l as the women in he him
 a and w s.. you..:. Meaning You A. this people event " find an is men life. who which see having This. is you Of .. meaning place of its at. Me. being mess // The mean off someone is if or .
 “ " on mif is If" be has of the[ in and [| •[ , b me ; mina he there itself â find this / \\ ;. e will s � ] is f dr l set a . . I it . his for | you its that those is as. see if meaning get pm ” us // on ! .” the in sex but* // okot .orying  why .. what. & internet 1 is ,[ p and// c has? your please away the mâ\\\\& ;\\\\\\\\\\ym \\ her%1.|12ines%oiseg[ thep as never find/+ meet thi ] s the \ you f c she \terminate called after throwing an instance of 'std::out_of_range'
  what():  unordered_map::at
Aborted (core dumped)
</details>
