### ISSUE TITLE
Support for LLAMA V.1.5 Multimodal LLMs

### ISSUE THREAD

**Issue by Dyl777** [ggerganov/llama.cpp#3778]
Curious if MLLMs can work on it. I am already supposing LLAMA V1.5 can't . I can suggest checking out more efficient MLLM models like X-LLM

**Comment by Green-Sky** [comment]
are you talking about LLAVA ? because basic [support has been merged](https://github.com/ggerganov/llama.cpp/pull/3436).
see https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/README.md

**Comment by Dyl777** [comment]
Thks for pointing that out but not just for LLAMA V1.5, am referring to a format for MLLMs in general being released
