### ISSUE TITLE
Original weights for LLAMA

### ISSUE THREAD

**Issue by NickDatLe** [ggerganov/llama.cpp#378]
Hey, I noticed the API is running on CPP, were the original weights in python or CPP? If in python, I would think they were in pytorch since that is Meta's DL platform; do you have the weights in python format?

**Comment by JamoDevNich** [comment]
You could try checking some old issues or closed PRs for a possible solution

https://github.com/ggerganov/llama.cpp/pull/147

**Comment by NickDatLe** [comment]
> 

yeah ty
