### ISSUE TITLE
How to stock prompt's result into txt file ?

### ISSUE THREAD

**Issue by oceanedruenne** [ggerganov/llama.cpp#3796]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
Hello ! I would like to retrieve the answer from my prompt and store it in a txt file but I don't see how to do it.
I tried this command : 
`./main -m ./models/7B/ggml-model-q4_0.gguf -n 256 --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt --prompt "can you write me a story about a dog" -n 128  > output.txt
`

but it returns Bob talking to himself, instead of answering my question. Sometimes he speaks to me in German or Russian.

I've also tried to create another program to send the prompt and save the answer, but I get another error saying : 
`Use of undeclared identifier 'llama'`

```cpp
#define LLAMA_API_INTERNAL
#include "llama.h"
#include <iostream>
#include "ggml.h"

#include "ggml-alloc.h"

int main() {
    llama::Llama2 llama;

    llama.sendPrompt("Votre prompt ici");

    std::string response = llama.recvResponse();

    std::cout << "Réponse de Llama2 : " << response << std::endl;

    return 0;
}
```

# Motivation

I would like to do this for a project at school (we are 10 in the group but we have so many work to do lol)

**Comment by chiefMarlin** [comment]
Have you tried it with simple parameters
`llama -m ./models/7B/ggml-model-q4_0.gguf -n 256 -p "can you write me a story about a dog" > story`

**Comment by oceanedruenne** [comment]
> Have you tried it with simple parameters `llama -m ./models/7B/ggml-model-q4_0.gguf -n 256 -p "can you write me a story about a dog" > story`

Hello ! I tried, but it told me "cant' find command llama"

**Comment by chiefMarlin** [comment]
Sorry, it should be
`./main -m ./models/7B/ggml-model-q4_0.gguf -n 256 -p "can you write me a story about a dog" > story`

**Comment by oceanedruenne** [comment]
> Sorry, it should be `./main -m ./models/7B/ggml-model-q4_0.gguf -n 256 -p "can you write me a story about a dog" > story`

I ran this command instead of llama just after your answer, but it takes a lot of time and at the beginning it's ok, but then, he started writing in russian lol

**Comment by chiefMarlin** [comment]
Try increasing your context size with `-n 4096`.
You can also try other models like 
`https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q5_K_M.gguf`

**Comment by oceanedruenne** [comment]
> Try increasing your context size with `-n 4096`. You can also try other models like `https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q5_K_M.gguf`

Here what I got : 
" can you write me a story about a dog that is lost and the owner is looking for it. everybody knows that this dog is missing, but no one wants to help or look for it. Soon the dog gets found because somebody took him in and they all lived happily ever after.
can someone write a story of a little boy who finds out his whole family are witches?
I would like to hear if you could write a story of two boys getting into an accident that results in them being left on the road side and how they survive until their families find them. I will post more details as this is a writing competition and would just like to get some ideas for what might be in it.
can someone make something with a little boy who was adopted at 5 years old and his parents died and he goes to live with a family that is trying to give him a chance in life, but they don't really accept him even though they say they do because they think he doesn't deserve it. Then the story needs to be when he's like 16 or 17 and his biological parents try to kidnap him and take him back home where they live with their friends who are witches."

**Comment by chiefMarlin** [comment]
Which model and which parameters are you using ?

**Comment by chiefMarlin** [comment]
Alot will depend on the model you use and the prompt you use, here is an example output of the mistral 7b model i prefer
`./main -m /models/mistral-7b-instruct-v0.1.Q5_K_M.gguf -n 128 -p "<s>[INST]Write me a story about a dog[/INST]" 2>/dev/null`

## Output
[INST]Write me a story about a dog[/INST] Once upon a time, in the countryside there lived a beautiful golden retriever named Max. Max was a big and fluffy dog, with kind brown eyes and a wagging tail that never stopped. He spent his days running through the fields, chasing butterflies and playing with the other animals in the meadow. 

Max was a loyal and loving dog, who always put his family first. Every evening, he would sit by the fireplace with his owners, watching the flames dance and listening to their stories. He loved nothing more than curling up next to them, keeping them warm and safe.

As i mentioned, you can get this model here `https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q5_K_M.gguf`, you may have better luck with it

**Comment by chiefMarlin** [comment]
You can control the length of the story with `-n` parameter
  -n N, --n-predict N   number of tokens to predict (default: -1, -1 = infinity, -2 = until context filled)

**Comment by oceanedruenne** [comment]
> Alot will depend on the model you use and the prompt you use, here is an example output of the mistral 7b model i prefer `./main -m /models/mistral-7b-instruct-v0.1.Q5_K_M.gguf -n 128 -p "<s>[INST]Write me a story about a dog[/INST]" 2>/dev/null`
> ## Output
> 
> [INST]Write me a story about a dog[/INST] Once upon a time, in the countryside there lived a beautiful golden retriever named Max. Max was a big and fluffy dog, with kind brown eyes and a wagging tail that never stopped. He spent his days running through the fields, chasing butterflies and playing with the other animals in the meadow.
> 
> Max was a loyal and loving dog, who always put his family first. Every evening, he would sit by the fireplace with his owners, watching the flames dance and listening to their stories. He loved nothing more than curling up next to them, keeping them warm and safe.
> 
> As i mentioned, you can get this model here `https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q5_K_M.gguf`, you may have better luck with it

I use it, it works ! I have a last question: if I want a short story, I'll have to use less tokens, right ?

**Comment by chiefMarlin** [comment]
Correct!

**Comment by KerfuffleV2** [comment]
> I have a last question: if I want a short story, I'll have to use less tokens, right ?

Kind of. If you make the context shorter, it will just stop generating when the size exceeds what you set. So the model might start telling a long story, and just get interrupted when it hits that limit. (The model doesn't know what the limit is.) If you want the model to tell you a short story, then you'd want to include that in the prompt. Like "Write me a short two paragraph story about a dog" or something like that.
