### ISSUE TITLE
Response 200 when using LLava via Server for python

### ISSUE THREAD

**Issue by TikaToka** [ggerganov/llama.cpp#3800]
Hello, i am having a problem using LLava via Server.

server launch command
```
export PYTHONPATH=$PYTHONPATH:`pwd`
export CUDA_VISIBLE_DEVICES=4,5,6,7
./server -m models/llava/ggml-model-q4_k.gguf --mmproj models/llava/mmproj-model-f16.gguf -c 2048 --port 8080 -ngl 35 -mg 3 -t 20
```

request code
```
import base64
from io import BytesIO
from PIL import Image
import subprocess
import json

def image_to_base64(img_path):
    with Image.open(img_path) as image:
        image = image.resize((336,336))
        buffered = BytesIO()
        image.save(buffered, format="PNG")
        img_str = base64.b64encode(buffered.getvalue())
    return img_str.decode('utf-8')

payload = {
    "prompt": "User: [img-1]Describe the image about indoor house scene. You must describe what you can see (e.g., door, stairs, bed), and where are you in (e.g., bathroom, kitchen). Only say description, do not say anything else.",
    "temperature": 0.1,
    "image_data": [{"data": image_to_base64('/home/vln_workspace/output_grid_image.jpeg'), "id": 1}],
    "system_prompt": {
        "prompt": "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.",
        "anti_prompt": "User:",
        "assistant_name": "Assistant:"
    },
}

url = "http://localhost:8080/completion"
headers = {
    "Content-Type": "application/json"
}

import requests
response = requests.post(url, headers=headers, json=payload)
print(response)

```

LOG
```
slot 0 - image loaded [id: 1] resolution (336 x 336)
slot 0 is processing [task id: 7]

print_timings: prompt eval time =       0.00 ms /     0 tokens (     inf ms per token,     -nan tokens per second)
print_timings:        eval time = -89935039284.51 ms /     0 runs   (    -inf ms per token,    -0.00 tokens per second)
print_timings:       total time = -89935039284.51 ms
updating system prompt
{"timestamp":1698342235,"level":"INFO","function":"log_server_request","line":2156,"message":"request","remote_addr":"127.0.0.1","remote_port":36330,"status":200,"method":"POST","path":"/completion","params":{}}
system prompt updated
slot 0 released (0 tokens in cache)
```

as it only says Error 200, I cannot trace anything.....

is there anyone currently deploying LLaVa on server and getting responst into python? I need help...
Might be related to #3761 ...

(Im currently not using llama-cpp-python as there are always error while loading the model)

**Comment by shahizat** [comment]
Hi @TikaToka, how you was able to solve the issue? Thanks in advance!

**Comment by TikaToka** [comment]
> Hi @TikaToka, how you was able to solve the issue? Thanks in advance!

in my case, due to the LLAVA do not support system prompt for now ( only for llama.cpp), there was some error I think. 

Keep changing the prompt returned output

**Comment by itsPreto** [comment]
@TikaToka I think there is an issue with the image-data implementation for server because in my testing I've pretty much only seen coherent responses while passing in an image if there was no system or regular prompt along with the request: https://github.com/ggerganov/llama.cpp/issues/4223

**Comment by TikaToka** [comment]
> @TikaToka I think there is an issue with the image-data implementation for server because in my testing I've pretty much only seen coherent responses while passing in an image if there was no system or regular prompt along with the request: #4223

yes as you said, I heard that currently LLaVA in llama.cpp do not support system prompt input, so your solution in #4223 might have solved the issue.

**Comment by shahizat** [comment]
Hi @TikaToka , If i am not mistaken, I guess issue due to you forgot to put colon at the end of "Describe the image about indoor house scene. You must describe what you can see (e.g., door, stairs, bed), and where are you in (e.g., bathroom, kitchen). Only say description, do not say anything else.".
