### ISSUE TITLE
When I used the tool to quantify the chatglm model, the following error was reported

### ISSUE THREAD

**Issue by whisky-12** [ggerganov/llama.cpp#3808]
When I used the tool to quantify the chatglm model, the following error was reported. May I ask if the format of the specified model does not match? Is there a way to solve this problem?

3:~/llama.cpp$ ./quantize MODEL/chatglm/chatGLM2-6B/pytorch_model-00001-of-00007.bin MODEL/chatglm/
                                             python convert.py MODEL/chatglm/chatGLM2-6B/
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00001-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00001-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00002-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00003-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00004-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00005-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00006-of-00007.bin
Loading model file MODEL/chatglm/chatGLM2-6B/pytorch_model-00007-of-00007.bin
Traceback (most recent call last):
  File "/home/aistudio/llama.cpp/convert.py", line 1202, in <module>
    main()
  File "/home/aistudio/llama.cpp/convert.py", line 1135, in main
    model_plus = load_some_model(args.model)
  File "/home/aistudio/llama.cpp/convert.py", line 1056, in load_some_model
    model_plus = merge_multifile_models(models_plus)
  File "/home/aistudio/llama.cpp/convert.py", line 589, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
  File "/home/aistudio/llama.cpp/convert.py", line 568, in merge_sharded
    return {name: convert(name) for name in names}
  File "/home/aistudio/llama.cpp/convert.py", line 568, in <dictcomp>
    return {name: convert(name) for name in names}
  File "/home/aistudio/llama.cpp/convert.py", line 543, in convert
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
  File "/home/aistudio/llama.cpp/convert.py", line 543, in <listcomp>
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
KeyError: 'transformer.embedding.word_embeddings.weight'

**Comment by HenkPoley** [comment]
They made a fork that supports ChatGLM2 and 3, though I suspect it doesn't support 3's special <|system|>/<|user|>/<|assistant|>-chat tokens.

https://github.com/li-plus/chatglm.cpp

**Comment by maziyarpanahi** [comment]
I get the same error for `convert` script and for `convert-hf-to-gguf` I'll get:

`NotImplementedError: Architecture "ChatGLMModel" not supported!`

I hope we can support ChatGLM in Llama.cpp so we don't deal with another repo.

**Comment by ZUIcat** [comment]
I also hope that llama.cpp can support ChatGLM.

**Comment by devcxl** [comment]
I also hope that llama.cpp can support ChatGLM.

**Comment by MW-S** [comment]
我也希望llama.cpp能够支持ChatGLM3

**Comment by JiaxianTan** [comment]
我也遇到类似的问题，请求llama.cpp能够支撑ChatGLM3 和Baichuan2-13B 系列
