### ISSUE TITLE
Server parallelization works - but now refuses with 'slot unavailable' rather than entering requests into a queue.

### ISSUE THREAD

**Issue by jaballski** [ggerganov/llama.cpp#3821]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Expect server.exe to not reject requests when busy. 

# Current Behavior

When the server is busy returning requests, and all slots are full - it rejects requests rather than queueing them.  

# Environment and Context

Max M2 Max

**Comment by TikaToka** [comment]
having same issues too.

**Comment by ggerganov** [comment]
This is a very high level logic that I don't think we will implement in the `server` example. Load-balancing and queueing requests can be implemented in million different ways. Adding to the examples can be accepted only if the implementation is very simple and compact

**Comment by jaballski** [comment]
> This is a very high level logic that I don't think we will implement in the `server` example. Load-balancing and queueing requests can be implemented in million different ways. Adding to the examples can be accepted only if the implementation is very simple and compact

Thanks so much - and thanks in general for this amazing project - will look at implementing something on our own here.  Thanks.

**Comment by ibehnam** [comment]
@ggerganov Thanks so much for working on this project.  Would you mind share your thoughts on how to take advantage of the parallel decoding in server?  It seems like the results are mixed as you mentioned in another thread and getting speed bumps requires fiddling with the server parameters.  When using the batched example though, I consistently get reliable speed enhancements so I wonder if something in the server implementation prevents us from getting better performance.

**Comment by groovybits** [comment]
Same issue here too.

Is there a way to fix this, or just retrying?

Any idea of the level of effort to fix and what the fix would be / what work needs to be done?

**Comment by ggerganov** [comment]
@ibehnam You have to be more specific. I believe batched decoding with F16 models is in a very good state for all backends. When using quantum models, currently the CUDA backend seems to be suboptimal and the Metal backend requires fiddling with some constants.

But in any case, if the batched example gives you satisfying numbers, then there is no reason for server not to.
Can you provide specific example with numbers?

**Comment by ggerganov** [comment]
@groovybits Yeah, if you can fit the model multiple times (CUDA) or if you are using CPU or Metal with mmap then you can start multiple instances as a workaround. Other than that, implementing the queueing logic requires community help.
