### ISSUE TITLE
gguf-py not in flake.nix?

### ISSUE THREAD

**Issue by zk395** [ggerganov/llama.cpp#3824]
When I try to run convert.py from the default x86_64-linux package installed from the Nix flake, it fails with the error `ModuleNotFoundError: No module named 'gguf'`. The gguf-py documentation from its subdirectory in this repo suggests to install it with pip, which really isn't ideal at all in a Nix/NixOS setup and also defeats the purpose of installing llama.cpp from the flake.nix file in the first place.  Am I just doing something wrong, or is this program missing from the flake outputs? In which case, I think it should be added. Thanks.

**Comment by JonDoeBeep** [comment]
damn
