### ISSUE TITLE
Bug: min value is set to 0 tor super block quantization

### ISSUE THREAD

**Issue by shlevi-microsoft** [ggerganov/llama.cpp#3846]
https://github.com/ggerganov/llama.cpp/blob/ff3bad83e29e3009010cbc923bebd769055eaa7f/k_quants.c#L262C9-L262C9

In the context of superblock calculation, there appears to be an issue with the minimum value of the inner blocks.

When quantizing positive values, the minimum value is consistently set to 0. This significantly impacts the accuracy of the quantized values

For instance, I conducted a test with an array containing one superblock of 256 elements ranging from [0, 1/256, 2/256, ..., 1]. Upon dequantizing back to float, the average error was 0.008883 (with a maximum error of 0.032215). 
(in this case, because of the bug, the min value for all 8 inner blocks is always set to 0,)

However, when the same array includes negative values like [0, -1/256, -2/256, ..., -1], the minimum value is correctly set. As a result, the average error significantly improves, measuring 0.002113 (with a maximum error of 0.009430). The average and maximum errors are reduced by 75%.

Fixing this issue will lead to lower errors for both negative and positive values in the quantization process.

**Comment by KerfuffleV2** [comment]
Have you tried changing it, requantizing models and then running the perplexity calculation? There may be other things that depend on it being the way it is.

**Comment by shlevi-microsoft** [comment]
I tested only the `quantize_row_q4_K` function directly and noticed a significant difference in quantization accuracy when using the same values but with positive versus negative inputs.
 I found that for positive values, the minimum value within the internal block consistently remained at 0, negatively impacting quantization efficiency.
 
 the fix is not only to remove this line `if (min > 0) min = 0`
 https://github.com/ggerganov/llama.cpp/blob/ff3bad83e29e3009010cbc923bebd769055eaa7f/k_quants.c#L262C9-L262C9
 
 the d value of the entire superblock also needs a fix to support this change

**Comment by shlevi-microsoft** [comment]
@KerfuffleV2 can we tag this issue it as a bug?

**Comment by ggerganov** [comment]
Which model are you using for tests?
I tried a few using `Q4_K` quantization and the branch where `min > 0` is never reached.

**Comment by shlevi-microsoft** [comment]
I didn't run a model, I created a test that calls quantize_row_q4_K directly
