### ISSUE TITLE
Freezes when compiling using make.

### ISSUE THREAD

**Issue by Folko-Ven** [ggerganov/llama.cpp#3854]
Windows 11, latest update, ryzen 7940hs.
The computer freezes when compiling using make. 
This problem should be related to the last few commits. 
There is no problem when using cmake.
I attach a photo where you can see on which line the computer freezes.
![IMG_20231030_043233](https://github.com/ggerganov/llama.cpp/assets/71110216/c03a97da-b53a-476b-980d-dce03a828a4a)

**Comment by staviq** [comment]
Please explain what you mean by "freezes", because if the compiler doesn't print anything for a while, it doesn't mean it's not doing anything, and that is completely normal.

**Comment by Folko-Ven** [comment]
I remove question, problem was in undervolt of my cpu.
