### ISSUE TITLE
Mac Metal: error on ggml_metal_init

### ISSUE THREAD

**Issue by spencekim** [ggerganov/llama.cpp#3894]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Running commit `d02e98cde035d91ed8032ab943d1d504fe9da394` on a Macbook Pro M2 Max.

Running the following command should work after building with `make`:
```
./server -m <model-path>
```

# Current Behavior

I receive an error with the following stack trace: https://pastebin.com/6Cpu8W6W

**Comment by jhen0409** [comment]
It might be broken after 898aeca90a9bb992f506234cf3b8b7f7fa28a1df, can you try c43c2da?

**Comment by spencekim** [comment]
yep that one works fine

**Comment by ggerganov** [comment]
Latest `master` should also work
