### ISSUE TITLE
ci : add an option to fail on compile warning

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#3899]
We should add optional flags to the build system (make and CMake) to fail upon compile warnings (`-Werror`).
These flags should be disabled by default so that during development this does not interfere, but should be enabled for most or all CI builds.

**Comment by ananta** [comment]
Hey @ggerganov I can work on this one :)

**Comment by ananta** [comment]
Hey @ggerganov, 

I just opened a pull request (PR) that is expected to meet the requirements. However, it appears that there is an 'implicit conversion' warning that needs to be addressed. 

You can see the warning in this screenshot: 
![Screenshot 2023-11-05 at 1 16 32 AM](https://github.com/ggerganov/llama.cpp/assets/12180395/1b9c3178-dbe9-4127-9a27-88024ba1e252)

How should I address this issue? Do you have any recommendations?

**Comment by ggerganov** [comment]
This should fix it I think:

```diff
diff --git a/ggml.c b/ggml.c
index 605a2794..f2e3dedd 100644
--- a/ggml.c
+++ b/ggml.c
@@ -1006,7 +1006,7 @@ inline static void __wasm_f16x4_store(ggml_fp16_t * p, v128_t x) {
         x[i] = _mm_add_ps(x[i], x[offset+i]);                     \
     }                                                             \
     const __m128 t0 = _mm_hadd_ps(x[0], x[0]);                    \
-    res = _mm_cvtss_f32(_mm_hadd_ps(t0, t0));                     \
+    res = (ggml_float) _mm_cvtss_f32(_mm_hadd_ps(t0, t0));        \
 }
 // TODO: is this optimal ?
 ```

**Comment by ananta** [comment]
> This should fix it I think:
> 
> ```diff
> diff --git a/ggml.c b/ggml.c
> index 605a2794..f2e3dedd 100644
> --- a/ggml.c
> +++ b/ggml.c
> @@ -1006,7 +1006,7 @@ inline static void __wasm_f16x4_store(ggml_fp16_t * p, v128_t x) {
>          x[i] = _mm_add_ps(x[i], x[offset+i]);                     \
>      }                                                             \
>      const __m128 t0 = _mm_hadd_ps(x[0], x[0]);                    \
> -    res = _mm_cvtss_f32(_mm_hadd_ps(t0, t0));                     \
> +    res = (ggml_float) _mm_cvtss_f32(_mm_hadd_ps(t0, t0));        \
>  }
>  // TODO: is this optimal ?
> ```

Fixed the warning with this type casting. Fixed some other issues aswell 😄
