### ISSUE TITLE
Vocab size mismatch

### ISSUE THREAD

**Issue by eswarthammana** [ggerganov/llama.cpp#3900]
Llama_2_7B-chat 
vocab size mismatch (model has -1 but tokenizer.model has 32000)

![issue](https://github.com/ggerganov/llama.cpp/assets/23114153/1a70a88f-e361-48ab-a48a-625586ac7957)

**Comment by yaashwardhan** [comment]
This is an easy fix.

There should be a .json file (probably params.json) inside the llama-2-7b-chat folder.
Open the json file and set the "vocab_size": to 32000 from -1.

Here is my params.json file:

{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-06, "vocab_size": 32000}

**Comment by eswarthammana** [comment]
Thanks for the fix, i did downloaded older version repo where i have not faced this issue few days back. :)

**Comment by ishowshao** [comment]
same issue, why meta write -1 ?

**Comment by lorddoskias** [comment]
I also hit this and I think the correct way to fix it is in the convert script to simply remove the "vocab_size" if it equals -1 which will result in getting it from the tok_embeddings.weight.

**Comment by kaiwren** [comment]
+1 I ran into this also (`Exception: Vocab size mismatch (model has -1, but ../llama/tokenizer.model has 32000)`) today with llama-2-7b.

**Comment by guertsen** [comment]
Had the same issue.

**Comment by rsbepvb** [comment]
Confirming this fixed the issue with the most recent Llama download

**Comment by ursachec** [comment]
Ran into a similar issue today, using the current tip of _master_ https://github.com/ggerganov/llama.cpp/commit/bcc0eb4591bec5ec02fad3f2bdcb1b265052ea56:
```
$ python3 llama.cpp/convert.py ./Magicoder-S-DS-6.7B/ --outtype f16 --outfile magicoder-S-DS-6.7B.FP16.gguf
//...
Exception: Vocab size mismatch (model has 32256, but Magicoder-S-DS-6.7B/tokenizer.model combined with Magicoder-S-DS-6.7B/added_tokens.json has 32022)
```

**Comment by FotieMConstant** [comment]
I confirm this fixed the issue with Llama2 7b models
