### ISSUE TITLE
llama : build with AVX support on Windows by default with CMake

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#3907]
We have to fix the CMake to build with AVX and AVX2 support with MSVC by default.

There was an old attempt to detect the instruction set but last time I tried it, it wasn't working for some reason and it seemed too complex. If we can't find a solution, we probably should just disable the `LLAMA_NATIVE` option on Windows

**Comment by netrunnereve** [comment]
We don't need to disable it for everyone like in #3906, we only need to guard `LLAMA_NATIVE` with an `if (NOT MSVC)` or something. The `-march=native` flag that is triggered by `LLAMA_NATIVE` [does the same check](https://github.com/ggerganov/llama.cpp/blob/c217a66bb2e54d20e12ee9d383d491b73d566975/CMakeLists.txt#L536) to only activate when it's not MSVC.
