### ISSUE TITLE
error loading model: create_tensor: tensor 'token_embd.weight' not found, when using the provided gguf models

### ISSUE THREAD

**Issue by realblankname1** [ggerganov/llama.cpp#3917]
I am trying to just learn how to use llama.cpp, I'm aware there was a big update, but am under the impression that the default models provided in the repo are up to date. They are already gguf files, however, all of them run into the same bug where it stops part way because the `'token_embd.weight' not found`. I have looked through the issues on github and have found things similar, ub tnot quite the same and most of them were resolved by converting the files, but I am assuming that the files provided work.
```
./simple ./models/ggml-vocab-llama.gguf "What is AI?"
llama_model_loader: loaded meta data with 17 key-value pairs and 0 tensors from ./models/ggml-vocab-llama.gguf (version GGUF V3 (latest))
llama_model_loader: - kv   0:                       general.architecture str     
llama_model_loader: - kv   1:                               general.name str     
llama_model_loader: - kv   2:                       llama.context_length u32     
llama_model_loader: - kv   3:                     llama.embedding_length u32     
llama_model_loader: - kv   4:                          llama.block_count u32     
llama_model_loader: - kv   5:                  llama.feed_forward_length u32     
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32     
llama_model_loader: - kv   7:                 llama.attention.head_count u32     
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32     
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32     
llama_model_loader: - kv  10:                       tokenizer.ggml.model str     
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr     
llama_model_loader: - kv  12:                      tokenizer.ggml.scores arr     
llama_model_loader: - kv  13:                  tokenizer.ggml.token_type arr     
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32     
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32     
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32     
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = all F32 (guessed)
llm_load_print_meta: model params     = 0.00 B
llm_load_print_meta: model size       = 0.00 MiB (-nan BPW) 
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.00 MB
error loading model: create_tensor: tensor 'token_embd.weight' not found
llama_load_model_from_file: failed to load model
main: error: unable to load model
```

**Comment by KerfuffleV2** [comment]
Those aren't real models, they're just the vocabulary part - for use with the vocabulary tests. Actual models are much, much larger.

Here's a good place to get started downloading actual models: https://huggingface.co/TheBloke

Here's a link to a good (fairly small) model to get started with: https://huggingface.co/TheBloke/dolphin-2.2.1-mistral-7B-GGUF

Any of the quantizations between Q4_K_S and Q5_K_M are good to start with. It's a tradeoff between size and quality, but ones in that range (and including the ones I mentioned) should be pretty good. The higher the number (Q5 vs Q4, for example), the less quality is affected by quantization but the larger the model is and the more memory it takes to run.

**Comment by realblankname1** [comment]
> Those aren't real models, they're just the vocabulary part - for use with the vocabulary tests. Actual models are much, much larger.
> 
> Here's a good place to get started downloading actual models: https://huggingface.co/TheBloke
> 
> Here's a link to a good (fairly small) model to get started with: https://huggingface.co/TheBloke/dolphin-2.2.1-mistral-7B-GGUF
> 
> Any of the quantizations between Q4_K_S and Q5_K_M are good to start with. It's a tradeoff between size and quality, but ones in that range (and including the ones I mentioned) should be pretty good. The higher the number (Q5 vs Q4, for example), the less quality is affected by quantization but the larger the model is and the more memory it takes to run.

My bad, I'm very new to this, didn't realize that they weren't models.

**Comment by KerfuffleV2** [comment]
Not a problem. We all started not knowing anything.

**Comment by Mr-Koala** [comment]
same problem solved, thanks.

**Comment by FotieMConstant** [comment]
hey, i am having a similar issue with a fine-tune of Llama2 converted and quantized with llama.cpp i get this error:

```bash
llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from /Users/🤓/Documents/gitrepo/personal/opensource/jarvis/api/quantized.bin (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32001]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32001]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32001]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 260/32001 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32001
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 4096
llm_load_print_meta: n_embd_v_gqa     = 4096
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW) 
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llama_model_load: error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected  4096, 32001, got  4096, 32000,     1,     1
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
```

Anyone, help? i am raltively new to this fine-tuning thing and i am having issues loading my model to inference:(

**Comment by humza-sami** [comment]
> hey, i am having a similar issue with a fine-tune of Llama2 converted and quantized with llama.cpp i get this error:
> 
> ```shell
> llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from /Users/🤓/Documents/gitrepo/personal/opensource/jarvis/api/quantized.bin (version GGUF V3 (latest))
> llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
> llama_model_loader: - kv   0:                       general.architecture str              = llama
> llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
> llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
> llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
> llama_model_loader: - kv   4:                          llama.block_count u32              = 32
> llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
> llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
> llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
> llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
> llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
> llama_model_loader: - kv  10:                          general.file_type u32              = 2
> llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
> llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32001]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
> llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32001]   = [0.000000, 0.000000, 0.000000, 0.0000...
> llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32001]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
> llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
> llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
> llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
> llama_model_loader: - kv  18:            tokenizer.ggml.padding_token_id u32              = 0
> llama_model_loader: - kv  19:               general.quantization_version u32              = 2
> llama_model_loader: - type  f32:   65 tensors
> llama_model_loader: - type q4_0:  225 tensors
> llama_model_loader: - type q6_K:    1 tensors
> llm_load_vocab: special tokens definition check successful ( 260/32001 ).
> llm_load_print_meta: format           = GGUF V3 (latest)
> llm_load_print_meta: arch             = llama
> llm_load_print_meta: vocab type       = SPM
> llm_load_print_meta: n_vocab          = 32001
> llm_load_print_meta: n_merges         = 0
> llm_load_print_meta: n_ctx_train      = 4096
> llm_load_print_meta: n_embd           = 4096
> llm_load_print_meta: n_head           = 32
> llm_load_print_meta: n_head_kv        = 32
> llm_load_print_meta: n_layer          = 32
> llm_load_print_meta: n_rot            = 128
> llm_load_print_meta: n_embd_head_k    = 128
> llm_load_print_meta: n_embd_head_v    = 128
> llm_load_print_meta: n_gqa            = 1
> llm_load_print_meta: n_embd_k_gqa     = 4096
> llm_load_print_meta: n_embd_v_gqa     = 4096
> llm_load_print_meta: f_norm_eps       = 0.0e+00
> llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
> llm_load_print_meta: f_clamp_kqv      = 0.0e+00
> llm_load_print_meta: f_max_alibi_bias = 0.0e+00
> llm_load_print_meta: n_ff             = 11008
> llm_load_print_meta: n_expert         = 0
> llm_load_print_meta: n_expert_used    = 0
> llm_load_print_meta: pooling type     = 0
> llm_load_print_meta: rope type        = 0
> llm_load_print_meta: rope scaling     = linear
> llm_load_print_meta: freq_base_train  = 10000.0
> llm_load_print_meta: freq_scale_train = 1
> llm_load_print_meta: n_yarn_orig_ctx  = 4096
> llm_load_print_meta: rope_finetuned   = unknown
> llm_load_print_meta: ssm_d_conv       = 0
> llm_load_print_meta: ssm_d_inner      = 0
> llm_load_print_meta: ssm_d_state      = 0
> llm_load_print_meta: ssm_dt_rank      = 0
> llm_load_print_meta: model type       = 7B
> llm_load_print_meta: model ftype      = Q4_0
> llm_load_print_meta: model params     = 6.74 B
> llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW) 
> llm_load_print_meta: general.name     = LLaMA v2
> llm_load_print_meta: BOS token        = 1 '<s>'
> llm_load_print_meta: EOS token        = 2 '</s>'
> llm_load_print_meta: UNK token        = 0 '<unk>'
> llm_load_print_meta: PAD token        = 0 '<unk>'
> llm_load_print_meta: LF token         = 13 '<0x0A>'
> llm_load_tensors: ggml ctx size =    0.11 MiB
> llama_model_load: error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected  4096, 32001, got  4096, 32000,     1,     1
> llama_load_model_from_file: failed to load model
> Traceback (most recent call last):
> ```
> 
> Anyone, help? i am raltively new to this fine-tuning thing and i am having issues loading my model to inference:(

found solution ?

**Comment by 0wwafa** [comment]
same here: after quantizing (even Q8) I get check_tensor_dims: tensor 'output_norm.weight' not found

**Comment by INZA111** [comment]
I am also facing the same issue **llama_model_load: error loading model: check_tensor_dims: tensor 'token_embd.weight' not found**. Did anyone found the solution?

**Comment by 0wwafa** [comment]
Guys: please check the **hashes** of your models against the ones on huggingface.
I had many error when I started and the fault was bad or incomplete downloads..

**Comment by bandoti** [comment]
I think there's some kind of race condition here going on here. I am seeing behavior which fails on a regular run, but works fine _within the debugger (gdb)_. There's got to be an issue with multiple threads reading the file or something. I tested with _and_ without OpenMP enabled, and the same behavior happens: when running outside the debugger, the following error occurs:
```
LlamaMainThread: build = 1 (6b5c5af)
LlamaMainThread: built with cc.exe (Rev3, Built by MSYS2 project) 14.1.0 for x86_64-w64-mingw32
LlamaMainThread: seed  = 1720362996
llama_model_load: error loading model: tensor 'blk.9.ffn_up.weight' data is not within the file bounds, model is corrupted or incomplete
```

**Comment by chintan-ushur** [comment]
Thanks @0wwafa , your observation was apt. Re-downloading the model helped.
