### ISSUE TITLE
api confusion

### ISSUE THREAD

**Issue by zooteld** [ggerganov/llama.cpp#3941]
I am trying to use https://github.com/3x3cut0r/llama-cpp-python-streamlit and I am confused. I can see in the console the server is recieving the request but it doesn't assign a "task id". Picture enclosed...
![2023-11-03_233814](https://github.com/ggerganov/llama.cpp/assets/22121839/3217690f-3156-4e51-a65e-feec72331494)
The top request is the streamlit app and the 2nd one is the index.html in /examples/server/public/...
I am sure its a small issue, probably just not formatting my request correctly, I am just missing it, still learning...

**Comment by staviq** [comment]
https://github.com/3x3cut0r/llama-cpp-python-streamlit/issues/1#issuecomment-1793384270

Author commented saying that project is in early development stages.

As this is not a part of llama.cpp and we have no control over that code, and the project author has acknowledged your issue, I'm gonna close this.

**Comment by zooteld** [comment]
sorry I was just looking for some help

**Comment by staviq** [comment]
There's nothing wrong with asking for help, it's just that particular project is a completely different thing, and llama.cpp issue reports are for reporting issues with llama.cpp.

You can always ask for help and report problem here, as long as you can reproduce a problem using llama.cpp directly.

You can also post in the Discussions section of this project, discussion posts have almost no restrictions as long as they are somewhat related to llama.cpp and LLMs in general.

We can only fix something if a problem involves code we have control over.

If you need python bindings for llama.cpp, there is a much more mature project here: https://github.com/abetlen/llama-cpp-python
