### ISSUE TITLE
Is tokenizer.model required for GGUF?

### ISSUE THREAD

**Issue by RonanKMcGovern** [ggerganov/llama.cpp#3968]
Quantization appears to require a tokenizer.model file.

Many models do not have this on HuggingFace (e.g. Deepseek Coder).

Is there either:
a) A way to run quantization without tokenizer.model (perhaps using other config files for the tokenizer)

b) Is there a standard way to generate the tokenizer.model file?

**Comment by TheBloke** [comment]
There is a PR nearing completion that allows the use of HF `tokenizer.json` for making GGUFs: https://github.com/ggerganov/llama.cpp/pull/3633

Over the last couple of days I have succesfully used it to make GGUFs for DeepSeek Coder, Calm-7B, and StockMark-13B. and a Vietnamese model I now can't remember the name of.

**Comment by RonanKMcGovern** [comment]
Many thanks tom, that's great

**Comment by jonastemplestein** [comment]
@TheBloke did you use that PR to make the GGUFs of DeepSeek Coder that you uploaded on HuggingFace? If so, I think there might be a bug with special fill in the middle tokens as described here: https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/discussions/1

(And thank you so much for all your hard work - I love all your quantised models on HF!)
