### ISSUE TITLE
Save Chat History into New Prompts

### ISSUE THREAD

**Issue by Crear12** [ggerganov/llama.cpp#3985]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✅ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [✅ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ✅] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [✅ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do as an enhancement.
Please add a parameter to save the conversation into a .txt file, like "keep appending the new response to the .txt file", so that we can continue the conversation by providing it as a prompt. I tried to find a way to save this because I think this might have already been implemented, but I couldn't find anything related to saving the conversation or saving the chat history. This feature could provide ChatGPT-like user experience.

Sorry if this is a duplicate issue that has been solved.

# Motivation

Please provide a detailed written description of reasons why this feature is necessary and how it is useful to `llama.cpp` users.
I can only find ```main.log``` that keeps the conversation in some format that I cannot read. Is it possible to save the conversation automatically in human language? There are two advantages of doing so,
1. We can load it as initial prompt to continue the conversation.
2. We can keep track of some valuable conversation.
# Possible Implementation

If you have an idea as to how it can be implemented, please write a detailed description. Feel free to give links to external sources or share visuals that might be helpful to understand the details better.

**Comment by akx** [comment]
You can use the `server` example for a ChatGPT-esque experience.

**Comment by deadpipe** [comment]
Yes Chat history will be very useful. A txt file can be created for each chat session.

**Comment by AtharvJaju** [comment]
Has anyone found the best way to achieve this?

**Comment by penghe2021** [comment]
Right now I am recording the conversation (text, not embedding) manully and update the prompt when reloading.

**Comment by deadpipe** [comment]
Oobabooga UI has a chat history option though

**Comment by capttrousers** [comment]
This would be helpful if you cant use the server / UI modes and need to be ssh'd to a vm and run a conversation via the CLI. something like an `--conversation-save-file` argument for `llama-cli`.

**Comment by capttrousers** [comment]
I meant if, for whatever reason, you can't open web traffic ports on your VMs so the only ingress allowed is SSH, but you'd still like to save conversations. I found the `--log-file` parameter, which looks like that prints the diagnostics logs and the responses from the model, but not the inputs. Perhaps there's a log format that could produce this kind of log file already, if I find it I'll report back

**Comment by deadpipe** [comment]
@capttrousers 

What do you mean when you mention "so the only ingress allowed is SSH"? Is there a way to run the interface without an actual GUI like an api?

**Comment by jasonriedy** [comment]
In case anyone stumbles upon this, the web UI now will happily provide a Markdown version of the transcript so far when asked.
Including the transcript that it produced. And it keeps going...

**Comment by deadpipe** [comment]
Thankyou, to all the wonderful developers 🙌
