### ISSUE TITLE
How to send Prompt in falcon-180b model

### ISSUE THREAD

**Issue by Prashantsaini25** [ggerganov/llama.cpp#3993]
Hi
I have served falcon-180b-chat.Q4_0.gguf-split-a with llama-cpp server. 
But when I curl that with 
curl --request POST     --url https://localhost/v1/completion    --header "Content-Type: application/json"     --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'
there is no output 
How to send prompt in falcon-180b-chat model 

llama_model_loader: loaded meta data with 18 key-value pairs and 644 tensors from ./models/falcon-180b-chat.Q4_0.gguf-split-a (version GGUF V2)
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  320.00 MB
llama_build_graph: non-view tensors processed: 1925/1925
llama_new_context_with_model: compute buffer total size = 1056.63 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:2600 (Press CTRL+C to quit)
INFO:     10.224.0.135:37624 - "GET / HTTP/1.1" 404 Not Found
INFO:     10.224.0.135:48292 - "POST /completion HTTP/1.1" 404 Not Found
INFO:     10.224.0.135:41420 - "POST /v1/completion HTTP/1.1" 404 Not Found
INFO:     10.224.0.135:57206 - "POST /v1/completion HTTP/1.1" 404 Not Found

**Comment by KerfuffleV2** [comment]
It looks like you're trying to use the OpenAI-type API rather than the API the `server` example supports.

There's an `api_like_OAI.py` script in `examples/server` you can use as a proxy - run server, point that script at it, then point your queries at the script. I haven't used it personally, so I'm not sure how well it works.
