### ISSUE TITLE
Override EOS token / Specify multiple EOS tokens

### ISSUE THREAD

**Issue by j7z** [ggerganov/llama.cpp#4000]
Some models add an alternative EOS token, for example in a ChatML style, EOS token = 32000 '<|im_end|>'. However, it's possible that an experimental fine tuned model may fail to generate the '<|im_end|>' yet still generate the '&lt;/s&gt;' used by the base model that the tuned model was created from.

A method to specify multiple EOS tokens would allow more practical use of such experimental models.
For example,
  "--eos-override 2,32000"
where 2 is '&lt;/s&gt;' and 32000 is '<|im_end|>'

Failing to stop at an EOS token may lead to a number of side effects depending on the model, such as a model repeating itself, creating text as the user and responding to itself, or generating irrelevant text.

**Comment by Dampfinchen** [comment]
Very useful change. This would help a lot with merges. It would be cool if there's a way to set that in the gguf Metadata.

**Comment by aviallon** [comment]
Should be re-opened.
