### ISSUE TITLE
WizardCoder Inference accuracy dropped a lot compared to fastchat or vllm

### ISSUE THREAD

**Issue by sanigochien** [ggerganov/llama.cpp#4001]
Is it possible that it is bug about llama.cpp?
Please forgive me if it is not a proper issue reporting.

**Comment by KerfuffleV2** [comment]
#3986 - Is this relevant for you? (I'm assuming WizardCoder is based on Deepseek Coder models).

**Comment by GANJAC** [comment]
Hi @sanigochien @KerfuffleV2 the same with this model:

https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF

With any quantization, is the same https://github.com/ggerganov/llama.cpp/pull/3986 ?
