### ISSUE TITLE
Metal issues with Intel Mac

### ISSUE THREAD

**Issue by zhangchn** [ggerganov/llama.cpp#4004]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Run `server` properly.

# Current Behavior

After launching the command, macOS GUI frozen.

`./server -m path-to-gguf/some-gguf-previously-worked`

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:
macbook pro 2022
`$ lscpu`
4 core intel core i5
* Operating System, e.g. for Linux:
macOS 13.5.1
`$ uname -a`

* SDK version, e.g. for Linux:
Xcode 15.0.1 15A507
```
$ python3 --version
$ make --version
$ g++ --version
```

# Failure Information (for bugs)

The GUI froze after loading metal file.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. build from git source
2. run `./server -m path-to-gguf`
The screen output suggests:
ggml_metal_init: found device: Intel(R) Iris(TM) Plus Graphics
ggml_metal_init: picking default device: Intel(R) Iris(TM) Plus Graphics
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: loading '....../llama.cpp/ggml-metal.metal'

Then the GUI froze. After about 2 minutes, the watchdog was triggered and the OS panic occurred.

**Comment by zhangchn** [comment]
Tested with a smaller weight, e.g. llama-2-7b-chat.Q4_0.gguf from TheBloke/llama2-7b-chat-gguf.

With `-ngl 0` and no metal acceleration, server output was normal and reasonable.
With `-ngl 1` or higher, the output would be abnormal:
```
User: hello
Llama: hew$omm friosingahnattle Chefattrtcipeahn stackozommotrлю stack numerura Matth Fri friowyazi Stanis Esp stack stackahn Mos Basicovi immugenemblyabormosaga stackommtags attackuraahnovyommahnahnowyelsk Fra Chetags ub Grundfileowy Domwohlprevioustagsowyahnotrowy openahnéraahn Cheuraватиahnfattcipeosing stacklem Culturartahnahnahn numer Fland Matthmodel Stanisazi Fland friowy Stanis Fland Stanisowyazi Stanis$tags Stanis Flandabor Mos stack Stanisattle rag Espowyomm Stanisaga Cheelsk Fri model stack Matthaziovi Basicugen Stanisowyembly stackowy dispotr Matth Modelahnhagenhewії stackлю Fland stack宝owy Staniscipeazi Stanis Cheahnosing Stanis numer Matthfattrt Fland Che Stanisowy Cheijkuratags Matth Che Stanisowyazi Mos Culturaowy Cheowytags$ Basicabor Esptags Stanis ub Comics Cheelsk Eb Che Che openommowy Cheaga Che savotrtagstagséquipe Che mort Matthprevious Alliancehagenahn Cheague Stanis stack model Che ind Matthosing Che rag Cheлюcipefatt Flandugentagsovyovi Stanis Stanis Chert Fri Stanisazimodelijk Stanis Stanisosing看$ Cheowy Matth Stanisowy Cheowyabor Mos Che Che Che Matth Che Stanis Matth Stanis$ Cheowy Che Espіїahn Stanis$ Stanis ub Stanisotr宝 Modelopen stackabor Basic· Culturaelsk Dom numer fri Stanis ragowy Eb Fland fre Stanisemblyovi Fland rfattrt Che model Stanis Che Che Che Stanis Fland Che Stanisazi Cheosingcipe mort Fland Chetags Stanis Fri proced Chelem FlandowyCheowyrt Che Matth Stanis Espahn Cheazi Che Mosijk Che Stanisarian Fland Che Fland stackopen ubahn宝 open Stanisahn Chetagsrt numer Basicowyowy Cheaborлюahn numerahnowy Stanis numerelsk rag Stanisotr Che*$ Che Che le Stanis Che Cheowy freahn Che宝ahn Che Fland mort Stanis Eb Basic Basic Friahn Flandowyместosing Matth Esp Domtags
```

**Comment by MikeLP** [comment]
I have the same issue.

**Comment by Basten7** [comment]
Tested on 6800XT or RX 580 on my Intel Mac and I have the same issue.

**Comment by yfeleke** [comment]
I also have the same issue, and i've tried OpenCL mode and get gibberish for anything over ngl=1.  My setup is Intel mac with AMD GPU.

**Comment by tjohnman** [comment]
I have the same issue with a 2017 13-inch MBP.

**Comment by cilin1105** [comment]
Guys Metal is for M series so doesn't work with intel or I am wrong?

**Comment by zhangchn** [comment]
Metal API precedes Apple Silicon M series by a few years. Metal 2 supports Macs since 2012, and Metal 3 supports devices later than 2017/2018.
