### ISSUE TITLE
Configuration for NVidia Jetson Xavier SOM required Makefile change

### ISSUE THREAD

**Issue by mehmetalianil** [ggerganov/llama.cpp#4006]
So, I am filling this as a bug since one can think that it needs to work out of the box, but feel free to switch it to be a improvement. I use Jetson Xavier NX  8GB  SoM with Volta architecture:  https://elinux.org/Jetson_Xavier_NX

<details>
<summary>
Prerequisites
</summary>

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.
</details>

# Expected Behavior

I expect that after the build, the commands with `-ngl 0` and `-ngl 35`
```
./main -m /llama.cpp/main -m ./dolphin-2.1-mistral-7b.Q4_K_M.gguf --temp 0.7 -p "### Instruction:  Write me a poem  ### Response:"  -b 512 --top-k 40 --top-p 0.95 --repeat_penalty 1.1 --no-penalize-nl -ngl 35 -b 512
```
```
./main -m /llama.cpp/main -m ./dolphin-2.1-mistral-7b.Q4_K_M.gguf --temp 0.7 -p "### Instruction:  Write me a poem  ### Response:"  -b 512 --top-k 40 --top-p 0.95 --repeat_penalty 1.1 --no-penalize-nl -ngl 0 -b 512
```

would behave the same, albeit one slower.
# Current Behavior

CPU version runs slow, but GPU version outputs gibberish. 

<details>
<summary>
Environment and Context
</summary>
SoM:  https://elinux.org/Jetson_Xavier_NX

* Physical (or virtual) hardware you are using, e.g. for Linux:

```
$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-5
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       3
Vendor ID:                       Nvidia
Model:                           0
Model name:                      ARMv8 Processor rev 0 (v8l)
Stepping:                        0x0
CPU max MHz:                     1907,2000
CPU min MHz:                     115,2000
BogoMIPS:                        62.50
L1d cache:                       384 KiB
L1i cache:                       768 KiB
L2 cache:                        6 MiB
L3 cache:                        4 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening, but not BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm dcpop
```

* Operating System, e.g. for Linux:

`Linux 5.10.120-tegra #1 SMP PREEMPT Tue Aug 1 12:32:50 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux`
</details>

# Solution
I actually found a hardcoded solution, but don't want to change a huge makefile without knowing about the consequences.
In this related discussion: https://github.com/ggerganov/llama.cpp/discussions/915#discussioncomment-5748451
adding to `NVCC_FLAG` the architecture argument `-arch=sm_72`
So I changed here: https://github.com/ggerganov/llama.cpp/blob/a75fa576abba9d37f463580c379e4bbf1e1ad03c/Makefile#L382
as 
```bash
NVCCFLAGS = --forward-unknown-to-host-compiler  -arch=sm_72 ##-use_fast_math
```

This results in an impressive (well, to me.) 8 tokes/sec on a credit card sized device.

So the question is, can we somehow map this into the Makefile and not break things?
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by KyL0N** [comment]
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#list-gpu-code-code-ls

```
nvcc --list-gpu-code
```

this command can show the cuda package supported code

hope this will help out to find a better solution
