### ISSUE TITLE
add_compile_definitions(GGML_USE_OPENBLAS) prevents cublas from being used

### ISSUE THREAD

**Issue by jmikedupont2** [ggerganov/llama.cpp#4008]
https://github.com/ggerganov/llama.cpp/blob/a75fa576abba9d37f463580c379e4bbf1e1ad03c/CMakeLists.txt#L233C3-L233C3

this is blocking the include of cublas

**Comment by Galunid** [comment]
Could you please double-check that you're building with `LLAMA_CUBLAS=1` set?
`make clean && make -j LLAMA_CUBLAS=1`

https://github.com/ggerganov/llama.cpp/blob/a75fa576abba9d37f463580c379e4bbf1e1ad03c/CMakeLists.txt#L263
should ensure `CUBLAS` is used, but only if `LLAMA_CUBLAS` is set.

Also for future reference please provide details described in issue template

**Comment by cebtenzzre** [comment]
You cannot build llama.cpp with support for multiple backends at a time. Please use either `-DLLAMA_BLAS=ON` or `-DLLAMA_CUBLAS=ON`, not both. If you have previously built with OpenBLAS you may need to either remove your build directory to delete the cmake cache, or explicitly pass `-DLLAMA_BLAS=OFF`.
