### ISSUE TITLE
"Illegal Instruction" error when converting 7B model to ggml FP16 format (Raspberry Pi 4, 8GB, Raspberry Pi OS, 64-bit)

### ISSUE THREAD

**Issue by lesp** [ggerganov/llama.cpp#401]
Hello

I'm trying to replicate the process, using 7B on a Raspberry Pi 4 with 8GB of RAM.
I'm running the latest Raspberry Pi OS 64-bit, and all of the software has been updated.
I am following the guidance found in the [Usage section of the README.md](https://github.com/ggerganov/llama.cpp#readme)
I cloned the repo, downloaded 7B and placed it into /llama.cpp/models/7B, the contents of which are below

===7B Contents===
```
l-rw-r--r-- 1 les les  100 Mar 22 15:03 checklist.chk
-rw-r--r-- 1 les les  13G Mar 22 15:03 consolidated.00.pth
-rw-r--r-- 1 les les  101 Mar 22 15:04 params.json
```
===END of 7B Contents===

I have successfully installed all of the suggested Python modules.

When running this command `python3 convert-pth-to-ggml.py models/7B/ 1` I see a short pause, around 5 -10 seconds. Then I receive an `Illegal instruction` error message and I can progress no more.

What am I doing wrong, and how can this be remedied?
I also tried Ubuntu 22.04 64-bit and the issue was the same.

Many thanks.

**Comment by gjmulder** [comment]
Please review and use [our issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md) to provide more details so we can try and better understand your problem and attempt to answer you.
