### ISSUE TITLE
Fine-tuned model where k-quantization produces gibberish, other quantization (q4_0, q5_0) works

### ISSUE THREAD

**Issue by matthiasdg** [ggerganov/llama.cpp#4023]
Hi all, quite new to this, so am learning a lot!
I created a fine-tuned llama2-7b-chat model based on https://www.philschmid.de/instruction-tune-llama-2 (unlike there I started from llama2-7b-chat-hf and fine-tuned with the same chat prompt format); but also saved a merged model using
```
merged_model = model.merge_and_unload()

# Save the merged model
merged_model.save_pretrained("merged_model",safe_serialization=True)
tokenizer.save_pretrained("merged_model")
```
I then converted this using `python convert.py --outfile models/7B/ggml-model-f16.bin --outtype f16 models/merged_model --vocab-dir ../../llama2-7b-chat-hf/folder_with_tokenizer.model` (apparently the saving does not store a tokenizer.model? Since I didn't change that I figured this should be OK?)
When I then convert this using the `quantize` command, I notice `q4_0`, `q5_0` work, but when I use one of the k-quants (`q4_k_m`, `q5_k_m`...) I only get gibberish output. First thought it was because I was using llama-cpp-python to test (incompatible versions), but seeing the same with `./main` from same llama.cpp build.

Getting stuff like: 

sierpnahm kwiet nobody nobody nobody nobody nobody nobody nobody nobody nobody nobody Begriffe kwiet nobody nobody nobody nobody Hinweis nobody nobody Hinweis nobody Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Hinweis Unterscheidung nobody Hinweis Unterscheidung Hinweis Hinweis Unterscheidung Hinweis Unterscheidung Hinweis Hinweis Unterscheidung Hinweis Hinweis Unterscheidung Hinweis Hinweis Hinweis Unterscheidung Hinweis Hinweis Hinweis Unterscheidung Hinweis Unterscheidung Unterscheidung Hinweis Hinweis Unterscheidung Hinweis Hinweis Hinweis Hinweis nobody Hinweis Hinweis

as an output to questions.

Any idea what could cause this?

**Comment by KerfuffleV2** [comment]
I can't do much more than confirm it is pretty weird. One thing you could possibly try is checking out a revision from a few weeks ago and see if you can reproduce the problem. Also see if it matters whether you compile with GPU support or not.

> Since I didn't change that I figured this should be OK?

I would think so.

> `--vocab-dir`

I might be wrong, but I'm not sure that part has been tested a lot recently. I know I made some changes to `convert.py` with comments like "Try to deal with separate vocabulary directory", so it may not work perfectly. However, I don't see how that could lead to it working with one quantization but not a different one.

I'd try other stuff first, but a really long shot would be to make a model directory with all your stuff in it so you can convert without having to use `--vocab-dir`. I don't think it's likely this will make a difference though.
