### ISSUE TITLE
Model conversion instructions in the https://github.com/ggerganov/llama.cpp/tree/master/examples/llava didn't work as expected

### ISSUE THREAD

**Issue by ramkumarkoppu** [ggerganov/llama.cpp#4042]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do.

should split the LLaVA model to LLaMA and multimodel projector constituents

# Current Behavior

Please provide a detailed written description of what `llama.cpp` did, instead.
`python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b`
Traceback (most recent call last):
  File "/Users/GIT/<llama.cpp>/```
./examples/llava/llava-surgery.py", line 12, in <module>
    path = sorted(glob.glob(f"{args.model}/pytorch_model*.bin"))[-1]
```

```
ls -l llava-v1.5-7b/
total 13249256
-rw-r--r-- 1 GIT staff       1364 Nov 11 23:01 README.md
-rw-r--r-- 1 GIT staff       1161 Nov 11 23:01 config.json
-rw-r--r-- 1 GIT staff        124 Nov 11 23:01 generation_config.json
-rw-r--r-- 1 GIT staff   41961085 Nov 11 23:02 mm_projector.bin
-rw-r--r-- 1 GIT staff 9976634558 Nov 11 23:15 **pytorch_model-00001-of-00002.bin**
-rw-r--r-- 1 GIT staff 3542276251 Nov 11 23:08 **pytorch_model-00002-of-00002.bin**
-rw-r--r-- 1 GIT staff      27068 Nov 11 23:01 pytorch_model.bin.index.json
-rw-r--r-- 1 GIT staff        438 Nov 11 23:01 special_tokens_map.json
-rw-r--r-- 1 GIT staff     499723 Nov 11 23:01 tokenizer.model
-rw-r--r-- 1 GIT staff        749 Nov 11 23:01 tokenizer_config.json
```

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using:
Apple M2 Max

* Operating System:
  MacOS Sanoma versipn 14.1

```
uname -a
Darwin GIT-MBP 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64 arm Darwin
```

```
$ python3 --version
Python 3.10.13
$ make --version
GNU Make 3.81
$ g++ --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
```

# Failure Information (for bugs)

Please help provide information about the failure / bug.

# Steps to Reproduce
Following the steps provided in the https://github.com/ggerganov/llama.cpp/tree/master/examples/llava#model-conversion

# Failure Logs

```
(llava-med) GIT-MBP:llama.cpp $ python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b
Traceback (most recent call last):
  File "/Users/GIT/llama.cpp/./examples/llava/llava-surgery.py", line 12, in <module>
    path = sorted(glob.glob(f"{args.model}/pytorch_model*.bin"))[-1]
IndexError: list index out of range
```

```
git log | head -1
commit e86fc56f7521ca4b18d1d9939e82abd40c2f1c01
```

```
pip list | egrep "torch|numpy|sentencepiece"
numpy              1.24.4
open-clip-torch    2.23.0
sentencepiece      0.1.98
torch              2.1.0
torchaudio         2.1.0
torchvision        0.16.0
```

**Comment by monatis** [comment]
How did you obtain `llava-v1.5-7b` --the exact command and/or source repository.

> `python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b`

And

> `ls -l llava-v1.5-7b/`

Looks like you mixed up the path here. You give the current directory for ls `ls` for the parent directory for `llava-surger.py`.
Also:

> `(llava-med) GIT-MBP:llama.cpp $ python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b`

Are you trying to convert the llava-med? If so, it's not supported --it uses an older architecture that's not implemented yet.

**Comment by ramkumarkoppu** [comment]
> How did you obtain `llava-v1.5-7b` --the exact command and/or source repository.
>  Done git clone https://huggingface.co/liuhaotian/llava-v1.5-7b
and
git clone https://huggingface.co/openai/clip-vit-large-patch14-336
in llama.cpp directory by blindly following instructions in the https://github.com/ggerganov/llama.cpp/tree/master/examples/llava#model-conversion
> > `python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b`
> 
> And
> 
> > `ls -l llava-v1.5-7b/`
>  ls -l llava-v1.5-7b/
total 13249256
-rw-r--r-- 1 git staff       1364 Nov 11 23:01 README.md
-rw-r--r-- 1 git staff       1161 Nov 11 23:01 config.json
-rw-r--r-- 1 git staff        124 Nov 11 23:01 generation_config.json
-rw-r--r-- 1 git staff   41961085 Nov 11 23:02 mm_projector.bin
-rw-r--r-- 1 git staff 9976634558 Nov 11 23:15 pytorch_model-00001-of-00002.bin
-rw-r--r-- 1 git staff 3542276251 Nov 11 23:08 pytorch_model-00002-of-00002.bin
-rw-r--r-- 1 git staff      27068 Nov 11 23:01 pytorch_model.bin.index.json
-rw-r--r-- 1 git staff        438 Nov 11 23:01 special_tokens_map.json
-rw-r--r-- 1 git staff     499723 Nov 11 23:01 tokenizer.model
-rw-r--r-- 1 git staff        749 Nov 11 23:01 tokenizer_config.json

> Looks like you mixed up the path here. You give the current directory for `ls` for the parent directory for `llava-surgery.py`. Also:
> pwd
/Users/git/llama.cpp
ls
CMakeLists.txt		    convert-baichuan-hf-to-gguf.py  ggml-cuda.cu      grammars	     quantize
LICENSE			    convert-hf-to-gguf.py	    ggml-cuda.h       infill	     quantize-stats
Makefile		    convert-llama-ggml-to-gguf.py   ggml-impl.h       libllava.a     requirements.txt
Package.swift		    convert-llama2c-to-ggml	    ggml-metal.h      llama-bench    run_with_preset.py
README.md		    convert-lora-to-ggml.py	    ggml-metal.m      llama.cpp      sampling.o
SHA256SUMS		    convert-persimmon-to-gguf.py    ggml-metal.metal  llama.h	     save-load-state
baby-llama		    convert.py			    ggml-metal.o      llama.o	     scripts
batched			    docs			    ggml-mpi.c	      llava-cli      server
batched-bench		    embedding			    ggml-mpi.h	      **llava-v1.5-7b**  simple
beam-search		    examples			    ggml-opencl.cpp   main	     speculative
benchmark-matmult	    export-lora			    ggml-opencl.h     main.log	     spm-headers
build-info.o		    finetune			    ggml-quants.c     media	     tests
build.zig		    flake.lock			    ggml-quants.h     metal	     train-text-from-scratch
ci			    flake.nix			    ggml-quants.o     models	     train.o
clip-vit-large-patch14-336  ggml-alloc.c		    ggml.c	      mypy.ini	     unicode.h
cmake			    ggml-alloc.h		    ggml.h	      parallel	     vdot
codecov.yml		    ggml-alloc.o		    ggml.o	      perplexity
common			    ggml-backend.c		    gguf	      pocs
common.o		    ggml-backend.h		    gguf-py	      prompts
console.o		    ggml-backend.o		    grammar-parser.o  q8dot

pwd
/Users/git/llama.cpp/llava-v1.5-7b
ls
README.md		mm_projector.bin		  pytorch_model.bin.index.json	tokenizer_config.json
config.json		**pytorch_model-00001-of-00002.bin**  special_tokens_map.json
generation_config.json	**pytorch_model-00002-of-00002.bin**  tokenizer.model

> > `(llava-med) GIT-MBP:llama.cpp $ python ./examples/llava/llava-surgery.py -m ../llava-v1.5-7b`
> 
> Are you trying to convert the llava-med? If so, it's not supported --it uses an older architecture that's not implemented yet.

No, 'llava-med' is python environment name

**Comment by monatis** [comment]
Ok, you cloned `llava-v1.5-7b` in `users/git/llama.cpp`. So the following should work:

```sh
cd /users/git/llama.cpp

python ./examples/llava/llava-surgery.py -m ./llava-v1.5-7b
```

But you can also download pre-converted models from [my HF account](https://huggingface.co/mys).

**Comment by ramkumarkoppu** [comment]
> Ok, you cloned `llava-v1.5-7b` in `Users/git/llama.cpp`. So the following should work:
> 
> ```shell
> cd /Users/git/llama.cpp
> 
> python ./examples/llava/llava-surgery.py -m ./llava-v1.5-7b
> ```
> yes I did but it gives me error 

File "/Users/GIT/llama.cpp/./examples/llava/llava-surgery.py", line 12, in
path = sorted(glob.glob(f"{args.model}/pytorch_model*.bin"))[-1]
IndexError: list index out of range

> But you can also download pre-converted models from [my HF account](https://huggingface.co/mys).
I tried with downloaded weights which worked, the issue with the model conversion procedure described in the README

**Comment by ramkumarkoppu** [comment]
Thank you for your help. managed to fix it by,
```
  mv llava-v1.5-7b/ ..
  mv clip-vit-large-patch14-336/ ..
```
from the llama.cpp top level directory.

**Comment by ramkumarkoppu** [comment]
@monatis, Do you mind if I ask how did you quantise f16 model into your https://huggingface.co/mys/ggml_llava-v1.5-7b/blob/main/ggml-model-q5_k.gguf ?
I tried this,
`./quantize ../llava-v1.5-7b/ggml-model-f16.gguf ../llava-v1.5-7b/ggml-model-q5_k.gguf Q5_K`
and it gives me this error,
```
llama_model_quantize_internal: meta size = 741056 bytes
[   1/ 291]                    token_embd.weight - [ 4096, 32000,     1,     1], type =    f16, quantizing to q5_K .. Illegal instruction: 4

```
