### ISSUE TITLE
Latest version of Llava is failing

### ISSUE THREAD

**Issue by Camel-RD** [ggerganov/llama.cpp#4048]
![021-512](https://github.com/ggerganov/llama.cpp/assets/17183429/96159f34-573d-4ab5-bee8-f7428a21249c)

**Version b1477:**
 The image depicts a man dressed in white clothing, walking down a busy city street. He is wearing a suit and tie and even has a monkey-like mask attached to his face. A yellow taxi can be seen behind him, adding to the bustling urban atmosphere.

In addition to the man in white, there are several other people around him, including one person walking near the left edge of the image and two others on the right side. Two cars can also be observed; one at the top left corner of the frame, and another behind the man in white, slightly to the right. Furthermore, a tie can be seen on another person, near the center of the image.

**Version b1505:**
The image is a dark black background with a small, white square. The square is situated in the upper left corner of the image, making it stand out against the darkness. The contrast of the white square against the black background creates a sense of depth and visual interest.

**Comment by staviq** [comment]
This has been noticed already, check if it makes a difference if the image is not perfectly square, try cropping the image by like 1px so it's not square, for example 512x512 -> 511x512

If it works let us know, this would confirm the bug from https://github.com/ggerganov/llama.cpp/pull/3436#issuecomment-1804882414
