### ISSUE TITLE
Any deterministic inference is available? Such as "pipeline" in transformers library.

### ISSUE THREAD

**Issue by daehuikim** [ggerganov/llama.cpp#4067]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ o] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [o ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [o ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ o] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
By now, inference occurs in probabilistic manner with parameters like top_k,min_p. But I wish lamma cpp has deterministic option for LLM. 

# Motivation

Because of LLM's auto-regressive characteristic, sometimes probabilistic decoding invoke low performance for fine-tuned model.

# Possible Implementation

I have no idea. I guess adding some API for example, function with parameter ```do_sample=False``` would work.

**Comment by BarfingLemurs** [comment]
`-s 1 --temp 0` adding these should work.
