### ISSUE TITLE
warning: failed to mlock in Docker

### ISSUE THREAD

**Issue by sengiv** [ggerganov/llama.cpp#4072]
![image](https://github.com/ggerganov/llama.cpp/assets/43817262/c3710342-e078-4f3d-9c53-3c7407392182)

is there a way to fix this in code?
perhaps in a bash file?
can't set during `docker run`, because managed docker environment limits

Any help would be appreciated 🙏

**Comment by AayushSameerShah** [comment]
Looks like on the instance there is some maximum memory limit that any application could "fix". We need to run something like `ulimit` command to change that.

I am too looking for the solution, will update as I get through this 👀
