### ISSUE TITLE
LlamaCpp - Output Lenght with RetrievalQA-chain from Langchain

### ISSUE THREAD

**Issue by weissenbacherpwc** [ggerganov/llama.cpp#4098]
Hi,

I built a RAG application with Langchain and used a model that was loaded with LlamaCpp. However I am facing the issue, that I want to get longer responses, but the answers of the model are very short. Here is the code how I am loading the model and how I build the RetrievalQA chain:
```
def build_llm():
        callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

        n_gpu_layers = 1
        n_batch = 512  

        llm = LlamaCpp(
                model_path=cfg.MODEL_BIN_PATH, # Mistral Model
                temperature=0.2,
                f16_kv=True,
                max_tokens = 100, #set max_tokens here?
                n_ctx=8000,
                n_gpu_layers=n_gpu_layers,
                n_batch=n_batch,
                callback_manager=callback_manager, 
                verbose=False, 
                top_p=0.75,
                top_k=40,
                repetition_penalty=1.1,
        )

from langchain.chains import RetrievalQA
from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate

prompt = PromptTemplate(template=qa_template,
                            input_variables=['context','history', 'question'])

chain_type_kwargs={
            "verbose": True,
            "prompt": prompt,
            "memory": ConversationBufferMemory(
                memory_key="history",
                input_key="question")}

qa = RetrievalQA.from_chain_type(llm=build_llm(),
                                 chain_type="stuff",
                                 return_source_documents=True,
                                 chain_type_kwargs=chain_type_kwargs,
                                 retriever=big_chunks_retriever)
```
What do I have to change to increase the length of the output? 
I figured out that it works to give me longer responses if I run the model without the RAG pipeline and set 'max_tokens' like here:
```
model_no_RAG = build_llm()
model_no_RAG("Tell me something about Document X?",max_tokens=1000) #model without knowledge of Document X -> hallucinates
```
However when I try to do the same within my RAG pipeline, I get an error: 
```
query = "Tell me something about Document X?"
qa(query, max_tokens=1000)
```
which results in:
`TypeError: Chain.__call__() got an unexpected keyword argument 'max_tokens'`

**Comment by KerfuffleV2** [comment]
You should probably ask in the RetrievalQA repo. That's a project built on top of llama.cpp (I'm assuming). We don't necessarily know/can't control how it behaves.

I took a quick look at their documentation. I think this is what you want: https://api.python.langchain.com/en/latest/llms/langchain.llms.llamacpp.LlamaCpp.html#langchain.llms.llamacpp.LlamaCpp.max_tokens

So set it in the same place you're setting `top_p`, `n_ctx`.

> `max_tokens = 100, #set max_tokens here?`

Yes, I think so. Keep in mind, the LLM doesn't _have_ to generate long responses. A lot can depend on stuff like prompting, the model's training, etc.

When using llama.cpp directly like with the `main` example you have the capability to bias certain tokens. I don't see a way to do that in their API. If you could do that, you could for example ban the EOS (end of sequence) token to make the LLM always generate _exactly_ the number of tokens you tell it to (of course, there's no guarantee it'll stop at a reasonable point or make sense with what it writes).
