### ISSUE TITLE
Download ggml-alpaca-7b-q4.bin failed CHECKSUM

### ISSUE THREAD

**Issue by kechan** [ggerganov/llama.cpp#410]
This may well be the end server issue. I tried several times with no luck, just wonder if people have seen this. 
I tried all 3 curl commands.

**Comment by kechan** [comment]
Never mind... I retried and it completed with 4212855021 bytes downloaded. If others have done this, are the count correct? 
I tried checksum but:

shasum: ggml-alpaca-7b-q4.bin: no properly formatted SHA checksum lines found

**Comment by zbruceli** [comment]
Your byte count is same as mine.

% md5 -r ggml-alpaca-7b-q4.bin 
46ac645818cf604afdddcf0f9e5a5d44 ggml-alpaca-7b-q4.bin

**Comment by kechan** [comment]
@zbruceli 
I ran checksum & failed, this is the item:

1f582babc2bd56bb63b33141898748657d369fd110c4358b2bc280907882bf13  models/alpaca-7B/ggml-model-q4_0.bin

**Comment by Ameobea** [comment]
I ran into this with the Cloudflare ipfs gateway, but the ipfs.io one worked for me.

**Comment by kechan** [comment]
@Ameobea Yes, I tried ipfs.io and that worked finally for me too. But unfortunately, it failed checksum. The checksum file has a different filename (and under dir models/alpaca-7B), I just create that dir and rename the file, and ran:

   shasum -a 256 --ignore-missing -c SHA256SUMS

Got:

> models/alpaca-7B/ggml-model-q4_0.bin: FAILED
shasum: WARNING: 1 computed checksum did NOT match
shasum: SHA256SUMS: no file was verified

**Comment by Ameobea** [comment]
@kechan you can also try [this torrent](https://btcache.me/torrent/88335685B1BC76A77905E19883D80BDAF85435CE).  It's how I obtained my alpaca 7B model, and it works well for me

**Comment by kechan** [comment]
@Ameobea I am a bit less comfortable with torrent though... did it pass any checksum for you? I just want to be a bit careful.

**Comment by Ameobea** [comment]
Oh actually I just looked at those checksums, I think they're out of date.

There was a PR merged (https://github.com/ggerganov/llama.cpp/pull/352) to update IPFS links to the new model format.  That's ggml2- file names.

The SHASUMS don't seem to have been updated as a part of that, and still reference the old model filenames (ggml- not ggml2-).

**Comment by kechan** [comment]
@Ameobea 
Ok. I downloaded using this curl:

curl -o ./models/ggml-alpaca-7b-q4.bin -C - https://ipfs.io/ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1

I think "QmUp...v1" is the latest created? If so, can you please point out the right checksum I should use?

**Comment by Ameobea** [comment]
Here's the hash I get for the file I downloaded via torrent:

`8d5562ec1d8a7cfdcf8985a9ddf353339d942c7cf52855a92c9ff59f03b541bc  ggml2-alpaca-7b-q4.bin`

That's all I have

**Comment by zbruceli** [comment]
The ipfs seed represents the file, so you can use alternative ipfs gateways for faster download speed and less stalls. The examples in README gave three common ipfs gateways, but there are many others. Do a bit research and you will find the others. :-)

**Comment by kechan** [comment]
@Ameobea 
Mine is 5992013124b645bfb6e80a2bf155058f3e20351115dbfbedf2f30a017d7c69af

I think my copy either incomplete, corrupted, or tampered with.

**Comment by kechan** [comment]
@zbruceli 

I tried gateway.estuary.tech and got md5 that matches yours

46ac645818cf604afdddcf0f9e5a5d44

What's odd is that while the byte count is the same as from ipfs.io, the md5 is different:

3e47e543e3cb3dd3f3a1db20c9ecc920

I don't know what to make of this. Since if yours work, I probably will try to use the one with "46ac...."

**Comment by anzz1** [comment]
This issue is related to #382 

I'm closing this as a duplicate and let's continue the discussion in #382 .
