### ISSUE TITLE
Windows cuda gpu compilation issue: nvcc fatal

### ISSUE THREAD

**Issue by alando46** [ggerganov/llama.cpp#4119]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I am following the readme as close as possible as the build process seems very specific. Expected behavior is compilation completes for windows with a cuda gpu.

# Current Behavior

Compilation fails with `nvcc fatal : A single input file is required for a non-link phase when an output file is specified` 

# Environment and Context

(from shell spawned by w64devkit, which is version 1.20.0)
~/code/llama.cpp $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:51:05_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0

~/code/llama.cpp $ git log -1
commit bbecf3f415797f812893947998bda4f866fa900e (HEAD -> master, tag: b1535, origin/master, origin/HEAD)
Author: slaren <slarengh@gmail.com>
Date:   Fri Nov 17 20:39:11 2023 +0100

    llama : increase max nodes (#4115)

(from powershell)
PS C:\Users\music> Get-WmiObject -Class Win32_OperatingSystem | Select-Object Caption, Version, BuildNumber

Caption                  Version    BuildNumber
-------                  -------    -----------
Microsoft Windows 11 Pro 10.0.22621 22621

* Physical (or virtual) hardware you are using:

Name                                            NumberOfCores NumberOfLogicalProcessors MaxClockSpeed
----                                            ------------- ------------------------- -------------
AMD Ryzen 9 7945HX with Radeon Graphics                    16                        32          2501

Name                               AdapterRAM DriverVersion
----                               ---------- -------------
NVIDIA GeForce RTX 4090 Laptop GPU 4293918720 31.0.15.4612

* Operating System

Caption                  Version    BuildNumber
-------                  -------    -----------
Microsoft Windows 11 Pro 10.0.22621 22621

* SDK version:

 w64devkit version 1.20.0

# Failure Information (for bugs)

Happy to get more specific information if needed.

# Steps to Reproduce

1. git clone llama.cpp
2. download and extract w64devkit latest Fortran version (1.20.0 in my case)
3. install nvcc, reboot computer. confirm nvidia-smi works.
4. run w64devkit.exe per readme instructions.
5. inside shell generated by w64devkit, navigate to llama.cpp and run `make LLAMA_CUBLAS=1`

# Failure Logs

~/code/llama.cpp $ make LLAMA_CUBLAS=1
I llama.cpp build info:
I UNAME_S:   Windows_NT
I UNAME_P:   unknown
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wdouble-promotion -march=native -mtune=native -Xassembler -muse-unaligned-vector-move
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move  -Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native
I NVCCFLAGS: --forward-unknown-to-host-compiler -use_fast_math -arch=native -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128 -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move    -Wno-pedantic -Xcompiler "-Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native "
I LDFLAGS:   -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L/usr/local/cuda/lib64 -L/opt/cuda/lib64 -LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/targets/x86_64-linux/lib
I CC:        cc (GCC) 13.2.0
I CXX:       g++ (GCC) 13.2.0

nvcc --forward-unknown-to-host-compiler -use_fast_math -arch=native -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128 -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move    -Wno-pedantic -Xcompiler "-Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native " -c ggml-cuda.cu -o ggml-cuda.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
make: *** [Makefile:447: ggml-cuda.o] Error 1

Thanks for any insights or suggestions! Not sure if this is a bug or if I misunderstood something in the instructions.

**Comment by askmyteapot** [comment]
Dont use make in windows, you need to use CMAKE under the Visual Studio build tools. 

```
mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON
cmake --build . --config Release
```
