### ISSUE TITLE
Could not find tokenizer.model in modified Mistral model

### ISSUE THREAD

**Issue by fakerybakery** [ggerganov/llama.cpp#4120]
Running the latest version of llama.cpp on a modified version of Mistral, I'm getting:
```
FileNotFoundError: Could not find tokenizer.model in <> or its parent; if it's in another directory, pass the directory as --vocab-dir
```
I see there is no default Mistral vocab [here](https://github.com/ggerganov/llama.cpp/tree/master/models).
Is there any solution for this?
Thank you!

**Comment by BarfingLemurs** [comment]
Before converting, add [tokenizer.model](https://huggingface.co/mistralai/Mistral-7B-v0.1/blob/main/tokenizer.model), to the model folder.
