### ISSUE TITLE
adding image generation capabilities?

### ISSUE THREAD

**Issue by itsPreto** [ggerganov/llama.cpp#4132]
came across this model [DeepFloyd/IF-I-XL-v1.0](https://huggingface.co/DeepFloyd/IF-I-XL-v1.0) (haven't tested yet) which is apparently able to generate images with specific text written in them and even does image-to-image generation/editing.

would it be too out of scope for this project to try and support image-generation models?

**Comment by dillfrescott** [comment]
I think this would be a cool addition

**Comment by itsPreto** [comment]
right? we have text-to-text, image-to-text, voice-to-text (whisper.cpp). Now throw in text-to-image and image-to-image and we basically have Jarvis

**Comment by FSSRepo** [comment]
If you give me the time, I could try integrating stable diffusion into flame.cpp for image generation capabilities on the server. Here is the link to the project [stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp/tree/master) I'm almost done integrating CUDA acceleration.

**Comment by itsPreto** [comment]
That would be sweet-- I just found this example in `whisper.cpp` [talk-llama](https://github.com/ggerganov/whisper.cpp/tree/master/examples/talk-llama) which lets you talk to your LLM locally. @FSSRepo I think `./server` would be the perfect place to integrate all of this.

Honestly I feel like `whisper.cpp` and `llama.cpp` should get merged into one and we could focus on building a unified framework for inferencing, a.k.a true multimodality.
