### ISSUE TITLE
Finetuning results in unusable models

### ISSUE THREAD

**Issue by jooray** [ggerganov/llama.cpp#4142]
# Expected Behavior

I tried to finetune a model using a dataset. I used the same dataset with axolotl training. I've tried finetuning a quantized model (q6_K) and full precision model. Quantized model returns just '$$$$$$' for any prompt, full precision returns nothing. There is clearly something wrong.

My pipeline (full precision):

```
./finetune \
    --model-base models/ggml-synthia-13B.gguf \
    --checkpoint-in chk-in-synthia-13b-LATEST.gguf \
    --checkpoint-out chk-in-synthia-13b-ITERATION.gguf \
        --lora-out lora-synthia-13b-ITERATION.bin \
        --train-data "dataset.txt" \
        --save-every 10 \
        --threads 8 --adam-iter 30 --batch 4 --ctx 512 \
        --sample-start '<s>' \
        --use-checkpointing
```

Then I merged the models:

```
./export-lora \
    --model-base models/ggml-synthia-13B.gguf \
    --model-out models/LLaMA-Lora.gguf \
    --lora-scaled lora-synthia-13b-LATEST.bin  \
        1.0
```

And quantized the result:

```
./quantize LLaMA-Lora.gguf LLaMA-Lora-q6_K.gguf  q6_K
```

# Current Behavior

When I ask any query, it just returns an empty string.

# Environment and Context

I've been running these on both a AMD64 CPU (the system has GPU, but I did not bother with cuda yet) and Macbook Pro M2.

AMD64 was running commit 28a2e6e7d476717881be6eb9e2d3331342cec57b

Macbook Pro was running commit bbecf3f415797f812893947998bda4f866fa900e

**Comment by gwjr** [comment]
Thanks for the report! I've tried briefly to reproduce this but haven't been able to do so. A couple of pointers:

- Could you confirm you see the same behaviour when you load the lora directly against the model (`./main --model-base models/ggml-synthia-13B.gguf --lora lora-synthia-13b-LATEST.bin`...)?
- Can you try training against a standard dataset? I've uploaded an [<s>-separated version of the standard shakespeare sonnet file](https://gist.github.com/gwjr/f461206c2e5b2e1d64c1699add9eba2a).
- Which if any BLAS options did you compile with for the build you're running on the AMD64 CPU?
-

**Comment by jooray** [comment]
1.) Yes, with --lora it is the same.

2.) Training now

3.) just "make"

**Comment by jooray** [comment]
I tried with Synthia-7B (based on Mistral) today and that works. So problem is Synthia-13B (based on llama2).

Will experiment with different llama2 based models.

**Comment by cosimoiaia** [comment]
I actually have the same issue with Mistral-7B. 
I finetuned for 5 epochs with rank 16 and alpha 32, output is always an empty string.

**Comment by jooray** [comment]
Somehow it started working with NousHermes-17B.

Well, "working". For example the model does not follow prompt structure that well (forgetting newline after Alpaca's "### Response:").

Working command:

```
./finetune \
    --model-base models/TheBloke/Nous-Hermes-Llama2-GGUF/nous-hermes-llama2-13b.Q5_K_M.gguf \
    --checkpoint-in chk-in-noushermes-13b-Q5_K-LATEST.gguf \
    --checkpoint-out chk-in-noushermes-13b-Q5_K-ITERATION.gguf \
        --lora-out lora-noushermes-13b-Q5_K-ITERATION.bin \
        --train-data "dataset.txt" \
        --save-every 10 \
        --threads 8 --adam-iter 3000 --epochs 1 --batch 4 --ctx 256 \
        --sample-start '<s>' \
        --n-gpu-layers 999 \
        --use-checkpointing
```

**Comment by cosimoiaia** [comment]
I managed to get good results with Wizard models, successfully adding knowledge to it.

command:
`./finetune --model-base Wizard-Vicuna-7B-Uncensored.Q4_K_M.gguf --train-data dataset-vicuna.txt --lora-out wizard-vicuna-7b.lora -s 42 -t 16 -c 512 --sample-start "<s>" --escape -b 32 --adam-iter 30 --checkpoint-out wizard-vicuna.ckp`

But Mistral keeps acting up, responding with nonsense or empty string, depending on the scaling of the lora.

**Comment by jooray** [comment]
This seems to have been an issue with LM Studio in the models.
