### ISSUE TITLE
Unable to Convert .safetensors File From a Lllama 2 Model

### ISSUE THREAD

**Issue by sashokbg** [ggerganov/llama.cpp#4151]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Trying to convert a .safetensors file.

```
python3 convert.py ../invoker-13b-GPTQ/gptq_model-4bit-128g.safetensors
```

# Current Behavior

An error occurs:

# Environment and Context

The model is taken from the "Invoker" project in HF https://huggingface.co/jeffrey-fong/invoker-13b-GPTQ
The main project: https://github.com/jeffrey-fong/Invoker

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

> Architecture:            x86_64
>   CPU op-mode(s):        32-bit, 64-bit
>   Address sizes:         48 bits physical, 48 bits virtual
>   Byte Order:            Little Endian
> CPU(s):                  12
>   On-line CPU(s) list:   0-11
> Vendor ID:               AuthenticAMD
>   Model name:            AMD Ryzen 5 5600X 6-Core Processor

* Operating System, e.g. for Linux:

`$ uname -a`

Linux alexander-desktop 6.5.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:48:15 UTC 2023 x86_64 GNU/Linux

* SDK version, e.g. for Linux:

```
$ python3 --version
$ make --version
$ g++ --version
```

Python 3.11.5
GNU Make 4.4.1
g++ (GCC) 13.2.1 20230801

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Checkout the Invoker model: https://huggingface.co/jeffrey-fong/invoker-13b-GPTQ
2. Run python3 convert.py ../invoker-13b-GPTQ/gptq_model-4bit-128g.safetensors

# Failure Logs

> Loading model file ../invoker-13b-GPTQ/gptq_model-4bit-128g.safetensors
> Traceback (most recent call last):
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 1228, in <module>
>     main()
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 1161, in main
>     model_plus = load_some_model(args.model)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 1076, in load_some_model
>     models_plus.append(lazy_load_file(path))
>                        ^^^^^^^^^^^^^^^^^^^^
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 753, in lazy_load_file
>     return lazy_load_safetensors_file(fp, path)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 732, in lazy_load_safetensors_file
>     model = {name: convert(info) for (name, info) in header.items() if name != '__metadata__'}
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 732, in <dictcomp>
>     model = {name: convert(info) for (name, info) in header.items() if name != '__metadata__'}
>                    ^^^^^^^^^^^^^
>   File "/home/alexander/Games2/llama.cpp/convert.py", line 725, in convert
>     assert end - begin == math.prod(shape) * numpy_dtype.itemsize
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError

**Comment by KerfuffleV2** [comment]
You can't convert a model that's already been converted to GPTQ, AWQ, etc. It has to be the base model with data in float32, float16 or bfloat16 format. I think this is what you need to be converting from: https://huggingface.co/jeffrey-fong/invoker-13b

**Comment by sashokbg** [comment]
Hello @KerfuffleV2 yes you are right ! The model I tried to convert was already quantized. I tried converting the other one and it worked fine.
Thank you for your help !
