### ISSUE TITLE
New sampler: Min-P (makes sense?)

### ISSUE THREAD

**Issue by clort81** [ggerganov/llama.cpp#4152]
# Prerequisites
- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
[](https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/
)
![min-p_sampler](https://github.com/ggerganov/llama.cpp/assets/51511737/79d12d2c-4e28-429e-b49f-af234ad6ffd7)

"What Min P is doing is simple: we are setting a minimum value that a token must reach to be considered at all. The value changes depending on how confident the highest probability token is.

So if your Min P is set to 0.1, that means it will only allow for tokens that are at least 1/10th as probable as the best possible option. If it's set to 0.05, then it will allow tokens at least 1/20th as probable as the top token, and so on..."

# Motivation
Better sampling?

**Comment by KerfuffleV2** [comment]
llama.cpp already supports Min P.

      --min-p N             min-p sampling (default: 0.1, 0.0 = disabled)

(In fact, I think we got it before anything else.)

**Comment by kalomaze** [comment]
> (In fact, I think we got it before anything else.)
Yup! This was a PR from me that got merged in:
https://github.com/ggerganov/llama.cpp/pull/3841

**Comment by Green-Sky** [comment]
closing this as "done" :)
