### ISSUE TITLE
Cloud-V CI invalid credentials

### ISSUE THREAD

**Issue by alitariq4589** [ggerganov/llama.cpp#4154]
# Expected Behavior

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do.

ggerganov/llama.cpp repository was added in [Cloud-V](https://cloud-v.co) dashboard for testing CI builds on RISC-V vector extension. It was expected to run a small sample prompt triggered by creation of PR and update the commit status of PR (see https://cloud-v.co:8443/view/Vector%20processing/job/llama.cpp%20--%20ggerganov/ for build details)

# Current Behavior

Please provide a detailed written description of what `llama.cpp` did, instead.

Right now, the builds are not getting triggered due to either credentials being deleted or expired. If it was not intentional, then to get the running builds again and updating the commit statuses, the github (fine-grained) credentials have to be generated again with `Read and write` access to `Commit statuses` and `Read and write` access to `Webhooks`. These credentials will have to be added in Cloud-V dashboard after logging in and once added, send the credentials ID via email to cloud-v@10xengineers.ai (this will not compromise the credentials' integrity), so that they can be added to the build (see https://10x-engineers.github.io/riscv-ci-partners/Software_Developer_Guide/ for guide on generating credentials and adding them)

**Comment by alitariq4589** [comment]
@ggerganov

**Comment by alitariq4589** [comment]
But I am getting this error while testing the credentials connection to GitHub. Did you put some other credentials than this  one in the Cloud-V credentials manager by any chance ? 
![image](https://github.com/ggerganov/llama.cpp/assets/99069972/7ae78843-5d25-4fe9-8bae-7741252124be)

**Comment by ggerganov** [comment]
Haven't done any changes - not sure why it does not work anymore.

Will generate a new token and send you the ID

**Comment by alitariq4589** [comment]
Yeah. That would be great. Thanks

**Comment by alitariq4589** [comment]
Now the access looks good so I am closing this issue. Thanks for adding new credentials.
