### ISSUE TITLE
Support stableCode models (which seems to be gpt-neo-x that we can convert into gguf)

### ISSUE THREAD

**Issue by maddes8cht** [ggerganov/llama.cpp#4174]
Why can we build gpt-neo-x models with the convert-hf-to-gguf.py script when there is no code to run it?

Mentioned in #3838 an d #3293, we do have code to convert gpt-neo-x  models into gguf models, but no code to run inference.

As i noticed, even the not too old stbilityAI stablecode models seems to be gpt-neo-x models, ad the convert-hf-to-gguf converts them, but there is no way to use them.

**Comment by Galunid** [comment]
I'll close it since there's already gpt-neox ticket, supporting that will solve this too
