### ISSUE TITLE
Model not running in realtime 

### ISSUE THREAD

**Issue by Rishabhg71** [ggerganov/llama.cpp#4182]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

It should start the text stream in a few seconds but takes more than 43 seconds to start the text stream

# Current Behavior

Taking too much time to process single image and provide a completion

# Environment and Context

`$ lscpu` output
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    CPU family:          6
    Model:               85
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            7
    BogoMIPS:            5000.01
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good no
                         pl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx
                          f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx sma
                         p clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   256 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    8 MiB (8 instances)
  L3:                    35.8 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:
  Gather data sampling:  Unknown: Dependent on hypervisor status
  Itlb multihit:         KVM: Mitigation: VMX unsupported
  L1tf:                  Mitigation; PTE Inversion
  Mds:                   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Retbleed:              Vulnerable
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

`$ uname -a` output
``` Linux ip-172-31-85-154 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```
* SDK version, e.g. for Linux:

```bash
$ python3 --version # Python 3.10.12
$ make --version # GNU Make 4.3
$ g++ --version # (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

# Failure Information (for bugs)

Please help provide information about the failure / bug.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Run the server with `./server -m YOUR_PATH/ggml-model-q4_k.gguf --mmproj YOUR_PATH/mmproj-model-f16.gguf -ngl 1`
2. run the python script given [here](https://github.com/Fuzzy-Search/realtime-bakllava/blob/main/src/picture_drop.py) 
3. You will see it take more than 43 seconds on EC2 (m5.4xlarge)

**Comment by KerfuffleV2** [comment]
`-ngl 1` - you're only offloading one single layer from the model to the GPU, the rest is running on the CPU. That's probably going to be fairly slow.

**Comment by BarfingLemurs** [comment]
@Rishabhg71 what gpu?

It will only run realtime on Mac, (or possibly a good gpu)
You're bottlenecked by Image encoder running on cpu

**Comment by KerfuffleV2** [comment]
I think they might have been confused by how `-ngl` is basically a toggle on Mac, so `-ngl 1` turns on offloading, `-ngl 0` turns it off. However, on other platforms (and they seem to be using Linux) `-ngl` takes the number of layers to offload. So they inadvertently only offloaded one layer.

I have a pretty weak GPU and the LLaVA example definitely did not take 40sec to start producing output.
