### ISSUE TITLE
Parallel/Slot issue of server mode for LLaVA

### ISSUE THREAD

**Issue by y10ab1** [ggerganov/llama.cpp#4194]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

I wrote a Python script to query the server with a picture in a loop.
When querying slot 0, the result is fine but when querying slot > 0, the completion result is wrong, and server filled to evaluate the image.

<img width="1455" alt="截圖 2023-11-24 上午11 15 31" src="https://github.com/ggerganov/llama.cpp/assets/94939112/2de86997-2ebe-406d-8dd4-a57c8b3cf5ef">

Note: The picture I provided to LLaVA is 2 dogs in the house on wooden floor. The results from slot 0 will depict the dogs on the wooden floor correctly while results from slot > 0 will said the dogs is running in the park.

<img width="440" alt="截圖 2023-11-24 上午11 22 55" src="https://github.com/ggerganov/llama.cpp/assets/94939112/bc5b9fe7-7a5b-4628-85e4-2aedcb65cde3">

Here is my code to query the server:

```
import base64
import json
from tqdm import tqdm
import requests
import argparse
from PIL import Image
from io import BytesIO
    

def encode_image(path):
    with open(path, 'rb') as file:
        return base64.b64encode(file.read()).decode('utf-8')
    

def send_request(url, headers, data):
    response = requests.post(url, headers=headers, json=data)
    print("Sent request to the server...")
    return response.json()['content']

def main(args):
    
    encoded_string = encode_image(args.path)
    image_data = [{"data": encoded_string, "id": 12}]
    
    data = {
        "prompt": "USER:[img-12]Describe the action and location of the pet in the format: A pet is {action} {place}.\nASSISTANT:", 
        "image_data": image_data, 
        "temperature": 0.01,
        "slot_id": 1,
    }
    
    for _ in tqdm(range(30)):
        result = send_request(args.url, args.headers, data)
        print(result)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--path', required=True, help='Path to the image file')
    parser.add_argument('--url', default="http://localhost:13579/completion")
    parser.add_argument('--headers', default={"Content-Type": "application/json"})
    args = parser.parse_args()
    main(args)
```

Here is the setting I used to run a server:

```
CUDA_VISIBLE_DEVICES="5" \
/my/path/server -t 8 -c 8192 -ngl 50 -m ${MDOEL_DIR}/ggml-model-q4_k.gguf \
                                --timeout 30 --port 13579 -nommq \
                                --parallel 2 \
                                --no-mmap \
                                -b 1024 \
                                --numa \
                                -cb \
                                --mmproj ${MDOEL_DIR}/mmproj-model-f16.gguf
```

**Comment by FSSRepo** [comment]
@y10ab1 currently the server just support multimodal for one slot, it can't process multiple images at same time
