### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by heltrix** [ggerganov/llama.cpp#4208]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Compile llama.cpp with cuBLAS support.

# Current Behavior
mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON
cmake --build . --config Release

[  1%] Building C object CMakeFiles/ggml.dir/ggml.c.o
[  2%] Building C object CMakeFiles/ggml.dir/ggml-alloc.c.o
[  3%] Building C object CMakeFiles/ggml.dir/ggml-backend.c.o
[  4%] Building C object CMakeFiles/ggml.dir/ggml-quants.c.o
[  5%] Building CUDA object CMakeFiles/ggml.dir/ggml-cuda.cu.o
gcc-11: error: unrecognized command-line option ‘-Wunreachable-code-break’; did you mean ‘-Wunreachable-code’?
gcc-11: error: unrecognized command-line option ‘-Wunreachable-code-return’; did you mean ‘-Wunreachable-code’?
gmake[2]: *** [CMakeFiles/ggml.dir/build.make:133: CMakeFiles/ggml.dir/ggml-cuda.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:642: CMakeFiles/ggml.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

Similar issues are seen when attempting:
make LLAMA_CUBLAS=1

gcc-11: error: unrecognized command-line option ‘-Wunreachable-code-break’; did you mean ‘-Wunreachable-code’?
gcc-11: error: unrecognized command-line option ‘-Wunreachable-code-return’; did you mean ‘-Wunreachable-code’?
make: *** [Makefile:447: ggml-cuda.o] Error 1

# Environment and Context

gcc version 11.3.0
clang version 14.0.6
nvidia-cuda-toolkit is installed by apt.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`
AMD x86_64

* Operating System, e.g. for Linux:

`$ uname -a`

* SDK version, e.g. for Linux:

```
$ python3 --version
$ make --version
GNU Make 4.3
$ g++ --version
```

# Failure Information (for bugs)

# Steps to Reproduce

Clone repo.
Install build-essentials, cmake, clang.
Install nvidia-cuda-toolkit.
Attempt to compile.

**Comment by deonis1** [comment]
You should be able just to run make clean && LLAMA_CUBLAS=1 in llama.cpp directory without using cmake. Also gcc-11 might need some tweaking like make CFLAGS="-Wunreachable-code".

**Comment by euclaise** [comment]
I'm getting the same issue, with cmake but without cuBLAS, on g++ 13.2.1:


```
[  1%] Building C object CMakeFiles/ggml.dir/ggml.c.o
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:1221:5: warning: implicit conversion increases floating-point precision: 'float' to 'ggml_float' (aka 'double') [-Wdouble-promotion]
    GGML_F16_VEC_REDUCE(sumf, sum);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:853:37: note: expanded from macro 'GGML_F16_VEC_REDUCE'
#define GGML_F16_VEC_REDUCE         GGML_F32Cx8_REDUCE
                                    ^
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:843:33: note: expanded from macro 'GGML_F32Cx8_REDUCE'
#define GGML_F32Cx8_REDUCE      GGML_F32x8_REDUCE
                                ^
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:789:11: note: expanded from macro 'GGML_F32x8_REDUCE'
    res = _mm_cvtss_f32(_mm_hadd_ps(t1, t1));                     \
        ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:1269:9: warning: implicit conversion increases floating-point precision: 'float' to 'ggml_float' (aka 'double') [-Wdouble-promotion]
        GGML_F16_VEC_REDUCE(sumf[k], sum[k]);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:853:37: note: expanded from macro 'GGML_F16_VEC_REDUCE'
#define GGML_F16_VEC_REDUCE         GGML_F32Cx8_REDUCE
                                    ^
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:843:33: note: expanded from macro 'GGML_F32Cx8_REDUCE'
#define GGML_F32Cx8_REDUCE      GGML_F32x8_REDUCE
                                ^
/home/euclaise/Projects/ChatForge/llama.cpp/ggml.c:789:11: note: expanded from macro 'GGML_F32x8_REDUCE'
    res = _mm_cvtss_f32(_mm_hadd_ps(t1, t1));                     \
        ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
[  2%] Building C object CMakeFiles/ggml.dir/ggml-alloc.c.o
[  3%] Building C object CMakeFiles/ggml.dir/ggml-backend.c.o
[  4%] Building C object CMakeFiles/ggml.dir/ggml-quants.c.o
[  4%] Built target ggml
[  5%] Linking C static library libggml_static.a
[  5%] Built target ggml_static
[  6%] Building CXX object CMakeFiles/llama.dir/llama.cpp.o
c++: error: unrecognized command-line option ‘-Wunreachable-code-break’; did you mean ‘-Wunreachable-code’?
c++: error: unrecognized command-line option ‘-Wunreachable-code-return’; did you mean ‘-Wunreachable-code’?
make[2]: *** [CMakeFiles/llama.dir/build.make:76: CMakeFiles/llama.dir/llama.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:712: CMakeFiles/llama.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

This prevents me from using llama-cpp-python

**Comment by bbb651** [comment]
I don't think it's entirely fixed, I also ran into this issue (I have `CXX=clang++`, `CC=clang` env vars and `c++ -> /usr/bin/clang++`, `cc -> /usr/bin/clang` symlinks, but `nvcc` ignores does and uses g++ and somehow llama.cpp is detecting it incorrectly).
I fixed it using `NVCC_PREPEND_FLAGS='-ccbin /usr/bin/clang++'`.
