### ISSUE TITLE
MPI run on M1 Max

### ISSUE THREAD

**Issue by ageorgios** [ggerganov/llama.cpp#4244]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ YES] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [YES ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ YES] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

run 2 chunks of the model on the same CPU-GPU 

# Current Behavior

ERRORS: 
GGML_ASSERT: llama.cpp:8672: false && "not implemented"
GGML_ASSERT: llama.cpp:5443: false && "not implemented"

# Environment and Context

Macbook M1 Max 32GB 

# Steps to Reproduce

```
cat hostfile 
127.0.0.1:2
```

1. mpirun -hostfile hostfile -n 2 ./main -m  /Users/ageorgios/.ollama/models/blobs/sha256:29fdb92e57cf0827ded04ae6461b5931d01fa595843f55d36f5b275a52087dd2 -n 128 &> ../output.txt

# Failure Logs

[output.txt](https://github.com/ggerganov/llama.cpp/files/13486422/output.txt)

**Comment by vvsotnikov** [comment]
Unfortunately, it's expected. You could try to use older versions of llama.cpp, before #3228 was merged.
MPI should be fixed in #3334, more context: #3752.

**Comment by SVyatoslavG** [comment]
This is still an issue. Please reopen.
