### ISSUE TITLE
server OAI API does not handle image_data in multimodal

### ISSUE THREAD

**Issue by edwios** [ggerganov/llama.cpp#4245]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When invoking the OpenAI API in multimodal mode, passing an image through the JSON parameter "image_data" should result in correct inference result of the image.

# Current Behavior

The content in "image_data" does not get passed to `launch_slot_with_data()`.

It is because:

`llama_params["image_data"] = json_value(body, "image_data",json::object());` is missing in the function `oaicompat_completion_params_parse()`

Adding this line successfully produced the expected behaviour.

# Environment and Context

Mac M1 Max with 64GB RAM

# Failure Information (for bugs)

Please help provide information about the failure / bug.

# Steps to Reproduce

`POST /v1/chat/completions` and attach image as in the README :

`{"messages":"[{'role': 'user', 'content': '[img-12]Describe the image in detail.'}]", "image_data": [{"data": "<BASE64_STRING>", "id": 12}]}`

Example environment info:
```
llama.cpp$ git log | head -1
commit b38a16dfcff88d547f78f52d1bea31b84a05aff7

**Comment by HAV0X1014** [comment]
When I add the `llama_params["image_data"] = json_value(body, "image_data",json::object());` line to server.cpp, the image is still not processed when using the `/v1/chat/completions` endpoint. The image is processed when it is sent to the `/completion` endpoint with the "prompt" parameter containing [img-12].

**Comment by HAV0X1014** [comment]
The fix described above no longer works on the current example. Any tips?
