### ISSUE TITLE
log-disable for Server

### ISSUE THREAD

**Issue by nelsonhurstdev** [ggerganov/llama.cpp#4246]
# Feature Description

Add `--log-disable`  flag to the server to prevent creating log files. (it is currently only available with 'main')

# Motivation

This llama.log file can get extremely large after long-term use, especially when working with code and/or images.

**Comment by jpohhhh** [comment]
Can close via #4260

**Comment by phymbert** [comment]
Actually, I feel `--log-disable` is misleading because it does not disable log, but only redirects to stdout.
