### ISSUE TITLE
How can I access the string belonging to a token ID during a sampling function?

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#4247]
I wanted to print it out but I was struggling because this was leading to an access memory violation in Min P:

```
for (size_t i = 0; i < candidates->size && i < 15; ++i) {
    const llama_token id    = candidates->data[i].id;
    const std::string piece = llama_token_to_str(ctx, id); // Use the function to get the token string
    printf("Token %zu (ID: %d): %s, Probability: %.6f%%\n", i + 1, id, piece.c_str(), candidates->data[i].p * 100);
}
```

**Comment by cmp-nct** [comment]
I think you are looking for llama_token_to_piece()
If you need it to support custom,special or control tokens you need my PR (https://github.com/ggerganov/llama.cpp/pull/4106)
There is also an example how to use the function, it's quite simple
