### ISSUE TITLE
llama print timeout occurs too soon

### ISSUE THREAD

**Issue by joshknnd1982** [ggerganov/llama.cpp#4268]
When I have a conversation with an llm model, eventually llama.cpp crashes with this error. 
"llama_print_timings:        load time =    2653.14 ms                                                                   
llama_print_timings:      sample time =   12531.52 ms /  1497 runs   (    8.37 ms per token,   119.46 tokens per second)
llama_print_timings: prompt eval time =  117949.37 ms /   505 tokens (  233.56 ms per token,     4.28 tokens per second)
llama_print_timings:        eval time =  868467.33 ms /  1498 runs   (  579.75 ms per token,     1.72 tokens per second)
llama_print_timings:       total time = 1579459.89 ms" 
Could you please greatly increase this time so I can have longer conversations?

**Comment by BarfingLemurs** [comment]
Run like so: `./main -m m.gguf --disable-eos-token -ins -c 8192`

See commands `./main -h`
