### ISSUE TITLE
[server] Batching reduces context size?

### ISSUE THREAD

**Issue by brucethemoose** [ggerganov/llama.cpp#4289]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

***

Hello, this is more of a behavior question than a bug. I noticed that when enabling batching via the `--parallel` flag for the llama.cpp server, it divides the context up between slots.

Does this mean the effective context size is reduced? Or can, say, a 8k context model run at 64K with 8 slots?

This should be made clear in the documentation, as I can't find an existing issue for it.

**Comment by Cloudhax23** [comment]
I also have noticed this bug, settings my n_ctx to 4096 and np to 2, the context is split in half.

**Comment by ggerganov** [comment]
This is not a bug - just increase the `--ctx-size` size to get the corresponding KV cache size.
The confusion stems from the fact that `--ctx-size` has changed it's meaning - it is now the size of the unified KV cache

**Comment by ggerganov** [comment]
> Wait, so what would determine the "effective context size" of the model if not [llama_context_params.n_ctx](https://github.com/ggerganov/llama.cpp/blob/master/llama.h#L179)?

It is `n_ctx_train`

> If I double n_ctx and only put in one sequence, would some RoPe scaling be done automatically?

No. You should apply correct RoPE parameters if you want to go beyond `n_ctx_train`

> So now llama_n_ctx_train returns the context the model was trained under and llama_n_ctx actually returns the cache size?

Yes

**Comment by brucethemoose** [comment]
Right, thanks
