### ISSUE TITLE
In Interactive mode, add a command to clear current context

### ISSUE THREAD

**Issue by alexconstant9108** [ggerganov/llama.cpp#4298]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

What the title is saying: add a command, for example Ctrl+R to clear the current context so that the next User input will an empty context instead of the current one.

# Motivation

This will be more convenient when chatting and exceeding the current context limit or just wanting to start a new conversation from a clean state.

# Possible Implementation
Add a Ctrl+R (to reset / clear) the current context.

**Comment by KerfuffleV2** [comment]
Yes it wouldn't be too hard, but someone else would have to add the feature. Basically just add a command that clears the KV cache for a sequence and resets the history vector of tokens for that sequence in the state.
