### ISSUE TITLE
Add AVX_VNNI support for intel x86 processors

### ISSUE THREAD

**Issue by freebie1101** [ggerganov/llama.cpp#4301]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
Enable AVX_VNNI ( we already have AVX512 ). Enable support for AVX_VNNI will make intel processor able to use int8 computation.

# Motivation
Intel x86 processors are still very popular among consumer and data centers hardwares. Enable AVX_VNNI will make the performance of llama cpp on these processors better.

**Comment by riverzhou** [comment]
Same question.

**Comment by tikikun** [comment]
> I build windows rocm build of llamacpp, it does support VNNI.

why rocm support AVX_VNNI ??

**Comment by ernesst** [comment]
This should be helpful I guess : https://www.intel.com/content/www/us/en/content-details/791610/optimizing-and-running-llama2-on-intel-cpu.html

**Comment by tikikun** [comment]
^ Based on this comment i have implemented this PR
#4589
