### ISSUE TITLE
KeyError: 'transformer.h.0.attn.c_attn.bias'

### ISSUE THREAD

**Issue by Minami-su** [ggerganov/llama.cpp#4304]
(train) root@WIN-IUEXHKJBZLU:/home/luhao/llama.cpp# python convert.py Qwen-14B-Chat
Loading model file Qwen-14B-Chat/model-00001-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00001-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00002-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00003-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00004-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00005-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00006-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00007-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00008-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00009-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00010-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00011-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00012-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00013-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00014-of-00015.safetensors
Loading model file Qwen-14B-Chat/model-00015-of-00015.safetensors
Traceback (most recent call last):
  File "/home/luhao/llama.cpp/convert.py", line 1228, in <module>
    main()
  File "/home/luhao/llama.cpp/convert.py", line 1161, in main
    model_plus = load_some_model(args.model)
  File "/home/luhao/llama.cpp/convert.py", line 1078, in load_some_model
    model_plus = merge_multifile_models(models_plus)
  File "/home/luhao/llama.cpp/convert.py", line 593, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
  File "/home/luhao/llama.cpp/convert.py", line 572, in merge_sharded
    return {name: convert(name) for name in names}
  File "/home/luhao/llama.cpp/convert.py", line 572, in <dictcomp>
    return {name: convert(name) for name in names}
  File "/home/luhao/llama.cpp/convert.py", line 547, in convert
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
  File "/home/luhao/llama.cpp/convert.py", line 547, in <listcomp>
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
KeyError: 'transformer.h.0.attn.c_attn.bias'

**Comment by zongzi531** [comment]
@Minami-su How to fix this ?

**Comment by nameless0704** [comment]
Hi, I'm getting the same error, and using `convert-hf-to-gguf.py` works. But I need to quantize it into 8bit or even lower to fit my RAM and VRAM, and `convert-hf-to-gguf.py` doesn't offer a quantization option. So is there a way that can quantize AND convert?

**Comment by kallewoof** [comment]
@nameless0704 Do `./quantize PATH_TO_RESULTING_F16_GGUF_FILE q8_0` or whatever quant you need.
