### ISSUE TITLE
./main -m Qwen-14B-Chat/ggml-model-q4_0.gguf -n 128  Segmentation fault 

### ISSUE THREAD

**Issue by Minami-su** [ggerganov/llama.cpp#4305]
(train) root@WIN-IUEXHKJBZLU:/home/luhao/llama.cpp# ./main -m Qwen-14B-Chat/ggml-model-q4_0.gguf -n 128
Segmentation fault

**Comment by sorasoras** [comment]
I guess it's the binary issues. I was able to compile and run qwen based model.

**Comment by saurabh-singh-rajput** [comment]
I am having the same problem, did you get this resolved @Minami-su ?
