### ISSUE TITLE
Quantize python script fails.

### ISSUE THREAD

**Issue by SavageShrimp** [ggerganov/llama.cpp#431]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I have my llama models stored in models/llama/{7B,13B,30B,65B}.

I expect that when I run the following command that the model will be converted

$ python3 quantize.py --models-path models/llama 30B

# Current Behavior

When attempting to quantize the model by running 

$ python3 quantize.py --models-path models/llama 30B

I get the following error:

The f16 model ggml-model-f16.bin was not found in models/llama/30B. If you want to use it from another location, set the --models-path argument from the command line.

modifying lines 76-79

```
        f16_model_parts_paths = map(
            lambda filename: os.path.join(f16_model_path_base, filename),
            glob.glob(f"{f16_model_path_base}*")
        )
```

To

```
       f16_model_parts_paths = [ filename for filename in glob.glob(f"{f16_model_path_base}*")]
```

Makes it work.

```
$ python3 --version   --> Python 3.8.10
```

# Failure Information (for bugs)

**Comment by SavageShrimp** [comment]
It was a list with two items, each item was the paths concatenated into the same string. I will post.

**Comment by j-f1** [comment]
Can you tru again with the version of the script in #428? That should fix the issue.

**Comment by mqy** [comment]
> ```shell
> python3 quantize.py --models-path models 7B
> ```

Run as expected, great!
Actually, the default model path was created with `os.path.join(os.getcwd(), "models")`, that's an absolute path.
