### ISSUE TITLE
Prebuilt windows binaries (i.e. `server.exe`) have a dependency on `llama.dll` - can we remove that?

### ISSUE THREAD

**Issue by jparismorgan** [ggerganov/llama.cpp#4314]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Current Behavior & Expected Behavior

I downloaded [llama-b1606-bin-win-noavx-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b1606/llama-b1606-bin-win-noavx-x64.zip) from the [latest release](https://github.com/ggerganov/llama.cpp/releases/tag/b1606) and would like to run it in my application. If I run `server.exe` from the downloaded directory, which has `llama.dll` next to it, it runs fine. But when I copy over `server.exe` somewhere else and run it I get:
```
C:/repo/foo/apps/desktop/llamacpp/engine/server_win32_noavx.exe: 
error while loading shared libraries: llama.dll: cannot open shared object file: No such file or directory
```

This is an issue because in my app I want to support all variants of avx and acceleration libraries, and with the current configuration I believe I would need to 1) create a new folder for each `server.exe` variant 2) copy over both `server.exe` and `llama.dll`. This is possible, but not as easy as just dealing with standalone `server.exe` files. So, before doing the workaround proposed above, I was wondering if we could include `llama.dll` in `server.exe`?

For reference, this is what [Dependency Walker](https://www.dependencywalker.com/) shows for the `server.exe` from the prebuilt libraries download - note that `llama.dll` is there:

<img width="800" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/1396242/525a287d-77d4-487d-99b5-07b3e1f30ddd">

And this is what it shows if I build for Windows with CMake and no other flags (i.e. follow [the README instructions](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#build)):

<img width="800" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/1396242/d4e67cfc-d49e-4830-b4d5-ace85e643a02">

The one caveat here is that perhaps I misunderstood the build and `llama.dll` can be used across avx and acceleration variants? And it's just `server.exe` which needs to change? Either way, thank you for any help.

# Environment and Context

* Physical (or virtual) hardware you are using, e.g. for Linux: Windows
* Operating System, e.g. for Linux: Windows 11

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Download  [llama-b1606-bin-win-noavx-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b1606/llama-b1606-bin-win-noavx-x64.zip)
2. Copy `server.exe` to another folder
3. Run `server.exe`

**Comment by jparismorgan** [comment]
Hi @FiveTechSoft, are you suggesting I build llama.cpp locally? Because yes, that works. But I'm interested in whether we could update the CI so that the prebuilt Windows binaries don't have a dependencies on `llama.dll`.

**Comment by slaren** [comment]
There are two reasons why the pre-built binaries use a dynamic library:
- It allows the library to be used for other purposes, such as with llama-cpp-python
- It reduces the size of the archive significantly

I think that your best bet is to build the server binaries yourself.

**Comment by jparismorgan** [comment]
Thanks @slaren, those are good reasons and I will just build them myself.
