### ISSUE TITLE
Support for the new 450 language translation models from Google T5X "madlad" - apparently Apache-2

### ISSUE THREAD

**Issue by cmp-nct** [ggerganov/llama.cpp#4316]
Example: https://huggingface.co/jbochi/madlad400-3b-mt/tree/main
In Googles own space: https://huggingface.co/google/madlad400-10b-mt

The guy converted the format of the 3 smallest models (3b,7b,10b) to HF transformers. Given the severe lack in non english output a good translation model would be a gift.
I just tried the CPU demo of the 3B, it produced quite good output, if that gets better with 7B+ it would be a real solution for a huge amount of people.
It could be added as a 2nd stage into llama.cpp

**Though the architecture is "T5ForConditionalGeneration" which isn't supported.**

So far there was no urgent reason to add those T5 models, they did not stick out as special but the idea to output text in every single language worldwide .. that would be remarkable

**Comment by JettScythe** [comment]
@cmp-nct can you please link to the PR where this was completed?

**Comment by cmp-nct** [comment]
> @cmp-nct can you please link to the PR where this was completed?

I’ve closed it as not important. Given the many things we need done and the almost zero interest for translation here.
The model from Google was ok but it was quite flawed when testing it in depth.

**Comment by vasicvuk** [comment]
This would be great if supported +1. @cmp-nct maybe you can reopen the issue so the support for this models is planned

**Comment by easp** [comment]
Perhaps relevant: https://github.com/ggerganov/llama.cpp/issues/5763

**Comment by Nikola-Milovic** [comment]
Surprising lack of interest for translational models, any reasons why?
