### ISSUE TITLE
[ BUG ]Unpickler.__init__() got an unexpected keyword argument 'mmap'

### ISSUE THREAD

**Issue by shaonianyr** [ggerganov/llama.cpp#4319]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Can convert starcoderbase-7b

# Current Behavior

Can not convert starcoderbase-7b

# Environment and Context

```
System Linux
Python 3.10.12
GNU Make 4.2.1
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
```

# Failure Information (for bugs)

# Steps to Reproduce

```
python convert-hf-to-gguf.py /starcoderbase-7b
```

# Failure Logs

```
Loading model: starcoderbase-7b
gguf: This GGUF file is for Little Endian only
Set model parameters
Set model tokenizer
gguf: Adding 48891 merge(s).
gguf: Setting special token type bos to 0
gguf: Setting special token type eos to 0
gguf: Setting special token type unk to 0
Exporting model to '/starcoderbase-7b/ggml-model-f16.gguf'
gguf: loading model part 'pytorch_model-00001-of-00004.bin'
Traceback (most recent call last):
  File "/root/llama.cpp/convert-hf-to-gguf.py", line 1027, in <module>
    model_instance.write()
  File "/root/llama.cpp/convert-hf-to-gguf.py", line 126, in write
    self.write_tensors()
  File "/root/llama.cpp/convert-hf-to-gguf.py", line 87, in write_tensors
    for name, data_torch in self.get_tensors():
  File "/root/llama.cpp/convert-hf-to-gguf.py", line 62, in get_tensors
    ctx = contextlib.nullcontext(torch.load(str(self.dir_model / part_name), map_location="cpu", mmap=True, weights_only=True))
  File "/root/anaconda3/envs/qlora/lib/python3.10/site-packages/torch/serialization.py", line 806, in load
    return _load(opened_zipfile, map_location, _weights_only_unpickler, **pickle_load_args)
  File "/root/anaconda3/envs/qlora/lib/python3.10/site-packages/torch/serialization.py", line 1170, in _load
    unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
TypeError: Unpickler.__init__() got an unexpected keyword argument 'mmap'
```

**Comment by shaonianyr** [comment]
@Galunid

**Comment by qxde01** [comment]
62 line : remove `mmap=True`

```ctx = contextlib.nullcontext(torch.load(str(self.dir_model / part_name), map_location="cpu", weights_only=True))```

**Comment by Galunid** [comment]
I think the problem is you have outdated torch version. Try to recreate `venv` using `requirements-hf-to-gguf.txt`. Please let me know if the problem persists and I'll reopen.
