### ISSUE TITLE
How to output text to a file?

### ISSUE THREAD

**Issue by appvoid** [ggerganov/llama.cpp#432]
I really, really tried hard to understand and modify the code but I am not an expert on C++ and so I find it a little bit difficult to change parts of this software. Is there a way to simply execute a command and get the output without all of that verbosity?

**Comment by spamshaker** [comment]
This doesn't work - try to dump this:
`lama-cli --vision-gemma-12b-default -p describe --image img.png > desc.md`
It always starts chat

**Comment by erik55** [comment]
See #19256
