### ISSUE TITLE
Grammar based decoding doesn't work with DeepSeek models

### ISSUE THREAD

**Issue by Ghatage** [ggerganov/llama.cpp#4333]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

# Expected Behavior

Running the latest llama.cpp with [DeepSeek 33B GGUF](https://huggingface.co/TheBloke/deepseek-coder-33B-instruct-GGUF) while using grammar should not lead to seg fault.

# Current Behavior

```
llm_load_print_meta: general.name     = deepseek-ai_deepseek-coder-33b-instruct
llm_load_print_meta: BOS token        = 32013 '<｜begin▁of▁sentence｜>'
llm_load_print_meta: EOS token        = 32021 '<|EOT|>'
llm_load_print_meta: PAD token        = 32014 '<｜end▁of▁sentence｜>'
llm_load_print_meta: LF token         = 126 'Ä'
llm_load_tensors: ggml ctx size =    0.21 MiB
llm_load_tensors: mem required  = 18015.69 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 100000.0
llama_new_context_with_model: freq_scale = 0.25
llama_new_context_with_model: kv self size  =  496.00 MiB
llama_build_graph: non-view tensors processed: 1306/1306
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Max
ggml_metal_init: picking default device: Apple M1 Max
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: loading '/Users/user/llama.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1 Max
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 49152.00 MiB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 273.07 MiB
llama_new_context_with_model: max tensor size =   180.88 MiB
ggml_metal_add_buffer: allocated 'data            ' buffer, size = 18016.75 MiB, (18017.38 / 49152.00)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   496.02 MiB, (18513.39 / 49152.00)
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =   270.02 MiB, (18783.41 / 49152.00)

system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
sampling:
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.700
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
generate: n_ctx = 2048, n_batch = 512, n_predict = -1, n_keep = 0

You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.

### Instruction:
Look at this line of code:

void functionOne(final int time, final TimeUnit t, final CountDownLatch l) throws InterruptedException, IOException;

I get the checkstyle error for this as:

Redundant 'final' modifier. [RedundantModifier]


Please rewrite the line of code with the fix for checkstyle, do not add anything else.
Make sure response is in JSON format like this:

{
   "code_with_fix" : "<actual fixed code here>"
}


### Response:libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
[1]    79390 abort      ./main -ngl 32 -m ~/Downloads/deepseek-coder-33b-instruct.Q4_K_S.gguf --color
```

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:
```
hw.ncpu: 10
hw.activecpu: 10
hw.perflevel0.physicalcpu: 8
hw.perflevel0.physicalcpu_max: 8
hw.perflevel0.logicalcpu: 8
hw.perflevel0.logicalcpu_max: 8
hw.perflevel0.cpusperl2: 4
hw.perflevel1.physicalcpu: 2
hw.perflevel1.physicalcpu_max: 2
hw.perflevel1.logicalcpu: 2
hw.perflevel1.logicalcpu_max: 2
hw.perflevel1.cpusperl2: 2
hw.physicalcpu: 10
hw.physicalcpu_max: 10
hw.logicalcpu: 10
hw.logicalcpu_max: 10
hw.cputype: 16777228
hw.cpusubtype: 2
hw.cpu64bit_capable: 1
hw.cpufamily: 458787763
hw.cpusubfamily: 5```

* Operating System, e.g. for Linux:

MacOS Sonoma

* SDK version, e.g. for Linux:

```
Python 3.11.4
GNU Make 3.81
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

# Failure Information (for bugs)

The grammar-file I am using is the vanilla json.gbnf that comes in the repo.
I don't see this problem for the llama family of models (phind's codellama-34b for eg.)

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Use latest llama.cpp
2. Download the model: [DeepSeek 33B GGUF](https://huggingface.co/TheBloke/deepseek-coder-33B-instruct-GGUF)
3. run: `./main -ngl 32 -m ~/Downloads/deepseek-coder-33b-instruct.Q4_K_S.gguf --color -c 2048 --temp 0.7 --repeat_penalty 1.1 -n -1 -f prompt.txt`

prompt.txt:
```
You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.

### Instruction:
Look at this line of java code:
Thread threads[] = new Thread[threadCount * 2];

I get the checkstyle error for this as:
Array brackets at illegal position. [ArrayTypeStyle]

Please rewrite the line of code with the fix for checkstyle, do not add anything else.
Make sure response is in JSON format like this:
{
   "code_with_fix" : "<actual fixed code here"
}

### Response:
```

# Failure Logs
```
./main -ngl 32 -m ~/Downloads/deepseek-coder-33b-instruct.Q4_K_S.gguf --color -c 2048 --temp 0.7 --repeat_penalty 1.1 -n -1 -f prompt.txt --grammar-file grammars/json.gbnf
Log start
main: build = 1610 (23b5e12)
main: built with Apple clang version 14.0.3 (clang-1403.0.22.14.1) for arm64-apple-darwin23.1.0
main: seed  = 1701738273
llama_model_loader: loaded meta data with 22 key-value pairs and 561 tensors from /Users/user/Downloads/deepseek-coder-33b-instruct.Q4_K_S.gguf (version GGUF V3 (latest))
llama_model_loader: - tensor    0:                token_embd.weight q4_K     [  7168, 32256,     1,     1 ]
... <tensor details snipped> ...
llama_model_loader: - tensor  560:                    output.weight q6_K     [  7168, 32256,     1,     1 ]
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = deepseek-ai_deepseek-coder-33b-instruct
llama_model_loader: - kv   2:                       llama.context_length u32              = 16384
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 7168
llama_model_loader: - kv   4:                          llama.block_count u32              = 62
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 19200
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 56
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 100000.000000
llama_model_loader: - kv  11:                    llama.rope.scale_linear f32              = 4.000000
llama_model_loader: - kv  12:                          general.file_type u32              = 14
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,32256]   = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  15:                      tokenizer.ggml.scores arr[f32,32256]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,32256]   = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,31757]   = ["Ġ Ġ", "Ġ t", "Ġ a", "i n", "h e...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 32013
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 32021
llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32              = 32014
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  125 tensors
llama_model_loader: - type q4_K:  427 tensors
llama_model_loader: - type q5_K:    8 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: mismatch in special tokens definition ( 243/32256 vs 237/32256 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 32256
llm_load_print_meta: n_merges         = 31757
llm_load_print_meta: n_ctx_train      = 16384
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 62
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 19200
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 100000.0
llm_load_print_meta: freq_scale_train = 0.25
llm_load_print_meta: n_yarn_orig_ctx  = 16384
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = mostly Q4_K - Small
llm_load_print_meta: model params     = 33.34 B
llm_load_print_meta: model size       = 17.59 GiB (4.53 BPW)
llm_load_print_meta: general.name     = deepseek-ai_deepseek-coder-33b-instruct
llm_load_print_meta: BOS token        = 32013 '<｜begin▁of▁sentence｜>'
llm_load_print_meta: EOS token        = 32021 '<|EOT|>'
llm_load_print_meta: PAD token        = 32014 '<｜end▁of▁sentence｜>'
llm_load_print_meta: LF token         = 126 'Ä'
llm_load_tensors: ggml ctx size =    0.21 MiB
llm_load_tensors: mem required  = 18015.69 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 100000.0
llama_new_context_with_model: freq_scale = 0.25
llama_new_context_with_model: kv self size  =  496.00 MiB
llama_build_graph: non-view tensors processed: 1306/1306
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Max
ggml_metal_init: picking default device: Apple M1 Max
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: loading '/Users/user/llama.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1 Max
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 49152.00 MiB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 273.07 MiB
llama_new_context_with_model: max tensor size =   180.88 MiB
ggml_metal_add_buffer: allocated 'data            ' buffer, size = 18016.75 MiB, (18017.38 / 49152.00)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   496.02 MiB, (18513.39 / 49152.00)
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =   270.02 MiB, (18783.41 / 49152.00)

system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
sampling:
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.700
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
generate: n_ctx = 2048, n_batch = 512, n_predict = -1, n_keep = 0

You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.

### Instruction:
Look at this line of code:
void functionOne(final int time, final TimeUnit t, final CountDownLatch l) throws InterruptedException, IOException;
I get the checkstyle error for this as:
Redundant 'final' modifier. [RedundantModifier]

Please rewrite the line of code with the fix for checkstyle, do not add anything else.
Make sure response is in JSON format like this:
{
   "code_with_fix" : "<actual fixed code here"
}

### Response:libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
[1]    79390 abort      ./main -ngl 32 -m ~/Downloads/deepseek-coder-33b-instruct.Q4_K_S.gguf --color

**Comment by ggerganov** [comment]
Does it work with other models?

**Comment by Ghatage** [comment]
So far I have tried the 8 bit and 4 bit K_S models.

8 bit error:
```
ERROR: byte not found in vocab: '
'
[1]    93835 segmentation fault  ./server -m ./models/deepseek-coder-33b-instruct.Q8_0.gguf -ngl 16 -c 6144 -t
```

**Comment by zeroshotkevin** [comment]
Googled my way to this issue. I'm experiencing the same error, but with `llama-cpp-python` bindings using deepseek-coder-6.7b-instruct.Q4_K_M.gguf. 

Disabling the use of grammars fixes the issue. Enabling grammars produces the same error:

```
libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
```

There's an older, similar issue resulting in the same error on TheBloke's HF page: https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF/discussions/1. The root of the issue back then seemed to be an incompatibility between GGUF in llama.cpp, llama-cpp-python, and how TheBloke's gguf version of the models was converted. Not sure if that's the case again.
