### ISSUE TITLE
train-text-from-scratch.exe on Windows uses only CPU (utilization: CPU 100%, GPU 3%)

### ISSUE THREAD

**Issue by gocursor** [ggerganov/llama.cpp#4334]
Hi, I am trying out train-text-from-scratch on Windows and it seems it works only on CPU and very little on GPU...

Here is how I am using it (with the latest version):

  llama-b1610-bin-win-cublas-cu12.2.0-x64\train-text-from-scratch ^
    --ctx 64 --embd 256 --head 8 --layer 16 ^
    --threads 31 --batch 16 --seed 12345 --adam-iter 200000 ^
    --no-checkpointing --n-gpu-layers 50 --save-every 100 ^
    --vocab-model ggml-vocab-llama.gguf ^
    --checkpoint-in my-chk-proverbs-256x16-LATEST.gguf ^
    --checkpoint-out my-chk-proverbs-256x16-ITERATION.gguf ^
    --model-out my-proverbs-256x16-f32-ITERATION.gguf ^
    --train-data proverbs.txt

My computer: Windows 11 Pro, CPU 13900KS, 128GB RAM, NVidia 4090 GPU (24GB VRAM)

I am running directly on Windows (without VM, WSL2 or Docker).

I downloaded the precompiled binaries llama-b1610-bin-win-cublas-cu12.2.0-x64.zip and cudart-llama-bin-win-cu12.2.0-x64.zip and unpacked them into the same directory.
 
My model is about 230MB in size and should be loaded completely into the GPU with specified "--n-gpu-layers 50".

The GPU is detected - here the output:

  ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
  ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
  ggml_init_cublas: found 1 CUDA devices:
    Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9

...and is utilized about 60% at the beginning (for the first 10 iterations)...

But then the GPU utilization drops to about 4% while the CPU is fully utilized (100%).
The training works slowly - about 1 second per iteration.

If I run inference on the same installation:

  llama-b1570-bin-win-cublas-cu12.2.0-x64\server --threads 31 --gpu-layers 40 --model some-big-model.gguf

my GPU is fully utilized...

So why is my training running on CPU and not on GPU? Is this because of a small model (less than 0.01B parameters)? Or is there some other reason...

**Comment by ggerganov** [comment]
GPU support for training is not implemented yet
