### ISSUE TITLE
Add GPU support for training

### ISSUE THREAD

**Issue by gocursor** [ggerganov/llama.cpp#4336]
Please add GPU support for train-text-from-scratch so that one can build llama models with GPU without using Python. Currently --n-gpu-layers parameter is accepted by train-text-from-scratch but has no effect.

This feature would be a major enhancement of user experience in training LLMs, because the whole Python ecosystem is much harder to setup than llama.cpp! Additionally llama.cpp can be simply copied to the USB stick and used on another computer which is almost mission impossible for training in Python...

(This ticket is a follow up of the ticket #4334)

**Comment by cmp-nct** [comment]
I also would prefer to stay as far away from python frameworks as possible, though that's still quite a bit in the future.
When it comes to efficient training it not only needs GPU support but efficient multi-GPU support, so far llama.cpp is mostly optimized for single GPU or Apple systems.
For serious training you'd need to focus on 4x and 8x A100/H100 systems

**Comment by calvintwr** [comment]
> To achieve that, there is a lot of work to be done, creating backpropagation kernels for CUDA, Metal, OpenCL. It's not just about creating them but also optimizing them for each backend, and that takes a lot of time. If I could dedicate myself to it full-time (financial support), I would gladly do it.

@FSSRepo Are you able to drop an email to calvin@pints.app to discuss this?
