### ISSUE TITLE
Implementing TokenMonster tokenizer

### ISSUE THREAD

**Issue by Sovenok-Hacker** [ggerganov/llama.cpp#4363]
# Feature Description
I think it would be great to add the [TokenMonster](https://github.com/alasdairforsythe/tokenmonster) tokenizer by @alasdairforsythe, I tested it and it works very well.
I tried to implement it myself, but I got a lot of errors (I'm not really good at neural networks and C++).
# Motivation
TokenMonster works really well, tokenizes very fast and it is easy to train a vocabulary.
# Possible implementation
It would be great to be able to convert TokenMonster vocabularies to GGUF and use them in train-text-from-scratch. The tokeniser is like a BPE, so I think it will be easy to implement.

P/S:
I tried to create a vocab conversation script. Now the code was lost.

**Comment by someone13574** [comment]
Are there any models which actually use it?

**Comment by Sovenok-Hacker** [comment]
> Are there any models which actually use it?

No, but it is possible

**Comment by someone13574** [comment]
> > Are there any models which actually use it?
> 
> No, but it is possible

I'm just wondering if it is worth spending time on implementing it when it wouldn't really be used for anything. It doesn't really make sense to add it until a model comes around which uses it.
