### ISSUE TITLE
Server example sampling is partially broken

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#4370]
<img width="590" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/b8e00b81-4453-434a-8d0f-b888beb308bd">

At some point after Top K, the candidates size gets forcibly revoked to 1 instead of the specified value when running server.exe.
This does not happen for main.exe.

<img width="578" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/99f092e8-aff5-45e1-8284-66be994713e3">

**Comment by mrsteyk** [comment]
Can't replicate this myself on `e0a4002273907b2c414b6b5442d99e08bfe2df35`, call to `llama_sample_token` almost always has size greater than min_keep. Called from mikupad with those settings:
![image](https://github.com/ggerganov/llama.cpp/assets/10615163/b745e8e1-b4eb-4f03-af9f-e82852e78c99)

n_probs and by extension min_keep is set to 10. This "drastic resize" for me happens after top_p. Setting top_p to 1 always gives the same size as top_k. Sampler sequence is "kfypmt".

**Comment by jart** [comment]
@kalomaze could you clarify if you're using the OpenAI endpoint? Because I encountered a similar sounding issue with that, which is being fixed by a PR I submitted.

**Comment by kalomaze** [comment]
> @kalomaze could you clarify if you're using the OpenAI endpoint? Because I encountered a similar sounding issue with that, which is being fixed by a PR I submitted.

I don't remember using the OpenAI endpoint, but it's probably that. The shrinking sounds identical to this issue.
