### ISSUE TITLE
High inference time 

### ISSUE THREAD

**Issue by adeelhasan19** [ggerganov/llama.cpp#4377]
I am loading a mistral model on my wsl2 ubuntu 22.04 having 2 RTX A4000 GPU. It is also showing the model is being loaded on the GPU but response time is very high. 

![image](https://github.com/ggerganov/llama.cpp/assets/89073843/b572b9c6-79c0-4339-950c-de9df0508cf8)

But i am also getting "failed to allocate 487.52 MB of pinned memory: out of memory" even after increasing the wsl2 memory upto 36gb

![image](https://github.com/ggerganov/llama.cpp/assets/89073843/986181d4-a471-400a-9b0a-e6cc42ac893c)

**Comment by zpin** [comment]
Maybe the same as https://github.com/abetlen/llama-cpp-python/issues/1026
