### ISSUE TITLE
llava: batch inference

### ISSUE THREAD

**Issue by Borobo** [ggerganov/llama.cpp#4378]
Hello! 

I'm using llava with the server and I'm wondering if anyone is working on batch inference by batching llava's clip or not. If not, I would be happy to contribute as this feature could be very useful to speed up inference time for llava.
As i'm new in this wonderful repo, I would also be grateful if you could guide me for the first steps (what file do I have to edit)

Thanks you in advance!

**Comment by Borobo** [comment]
So I guess I'll have to wait until this PR is merged before considering clip batching functionality, as I'm not very familiar with ggml structures. I'm going to keep an eye on it, thanks for you reply!

**Comment by y10ab1** [comment]
We can track the PR [ggerganov/llama.cpp/pull/4205](https://github.com/ggerganov/llama.cpp/pull/4205).
It appears that the corresponding pull request at [ggerganov/ggml/pull/621](https://github.com/ggerganov/ggml/pull/621) has been merged.
I guess there may be progress soon.

**Comment by KohakuBlueleaf** [comment]
Is there any updates for this feature?
