### ISSUE TITLE
llama : add Mixtral support

### ISSUE THREAD

**Issue by fakerybakery** [ggerganov/llama.cpp#4381]
Hi,
Please add support for [Mistral's MOE model Mixtral](https://twitter.com/MistralAI/status/1733150512395038967).

**Comment by ddh0** [comment]
Seconded!

**Comment by fakerybakery** [comment]
Does the hacky implementation support quantization?

**Comment by ddh0** [comment]
> Does the hacky implementation support quantization?

It barely supports inference, lol

**Comment by lxe** [comment]
What's the pull in modifying gguf-py / convert.py to support quantizing/converting this mistral MoE architecture?

**Comment by fakerybakery** [comment]
Has anyone seen this?

https://github.com/stanford-futuredata/Megatron-LM/blob/f385caf934b84e71c946c4342362270edae02173/tools/run_text_generation_server.py

**Comment by lxe** [comment]
Here's a hacked together conversion script: https://github.com/ggerganov/llama.cpp/commit/2dd894447e20af49f3f07b78136ecc6051e01fcb

**Comment by irony** [comment]
Nice!

> Here's a hacked together conversion script: [2dd8944](https://github.com/ggerganov/llama.cpp/commit/2dd894447e20af49f3f07b78136ecc6051e01fcb)

Nice!

**Comment by mayfer** [comment]
> Here's a hacked together conversion script: [2dd8944](https://github.com/ggerganov/llama.cpp/commit/2dd894447e20af49f3f07b78136ecc6051e01fcb)

conversion worked! inference fails with "error loading model: unknown model architecture: 'moe'", any tips?

**Comment by fakerybakery** [comment]
Hi @lxe, so your script supports conversion but not inference?

**Comment by lxe** [comment]
It's a work in progress. It can convert to gguf format (with wrong layer names) but there's no logic for quantizing under 8 bits or loading and running the model.  

Yet.

**Comment by clemens98** [comment]
so how much ram or vram is needed to run it?

**Comment by easp** [comment]
> so how much ram or vram is needed to run it?

Yes.

**Comment by leedrake5** [comment]
> > Here's a hacked together conversion script: [2dd8944](https://github.com/ggerganov/llama.cpp/commit/2dd894447e20af49f3f07b78136ecc6051e01fcb)
> 
> conversion worked! inference fails with "error loading model: unknown model architecture: 'moe'", any tips?

Same here. Mystified by what the problem here is. Mac silicon

**Comment by mayfer** [comment]
It requires changes to llama.cpp. each model type has some custom code, it's not all generic. check out source code and see what kind of custom stuff there is for qwen etc.

**Comment by fakerybakery** [comment]
@lxe just curious why your quantization script doesn't support int4?

**Comment by ciekawy** [comment]
this is related probably? https://github.com/ggerganov/llama.cpp/issues/2672

**Comment by someone13574** [comment]
Posting here for visibility: We know the general implementation of the MoE layer.

From the Mistral discord:
![Screenshot from 2023-12-10 09-54-33](https://github.com/ggerganov/llama.cpp/assets/81528246/612a5746-a536-4773-b4f1-a90ee142dda5)
![Screenshot from 2023-12-10 09-55-09](https://github.com/ggerganov/llama.cpp/assets/81528246/511aeabe-608e-4f42-8680-ce85cc6c24f3)
They link to [here](https://github.com/stanford-futuredata/megablocks/blob/159e1c4a8aeb0594274c5359ff83cacab807e60d/megablocks/layers/router.py#L56).

**Comment by someone13574** [comment]
There is also an (unofficial) attempt at implementing it in Huggingface transformers (here)[https://huggingface.co/DiscoResearch/mixtral-7b-8expert].

**Comment by fakerybakery** [comment]
I hope it can be quantized down to a reasonable size. What are the chances that it can eventually be run on a consumer-level laptop with reasonable results?

**Comment by antirez** [comment]
I wonder if for this model llama.cpp could modify the routing to produce at least N tokens with the currently selected 2 experts. And only after N check again the routing, and if needed load other two experts and so forth. So that we need to take only 2 experts per time in memory, and ammortize the cost of "swapping" models to N tokens. There is to understand if the routing is so unstable, but seems unlikely.

**Comment by Dampfinchen** [comment]
> I wonder if for this model llama.cpp could modify the routing to produce at least N tokens with the currently selected 2 experts. And only after N check again the routing, and if needed load other two experts and so forth. So that we need to take only 2 experts per time in memory, and ammortize the cost of "swapping" models to N tokens. There is to understand if the routing is so unstable, but seems unlikely.

Yes as far as I understand it, it only needs the resources of a 14B model, so it shouldn't be too hard to run. I guess the main catch is that you need all of the experts to be in RAM so they can be loaded as quickly as possible.

**Comment by ddh0** [comment]
I am hoping for an option to that will let me only load models into memory when they're used, and keep them on disk when not used. I know this would be super slow but it'd let me and many other people run it when we otherwise would have no hope, barring other developments.

**Comment by easp** [comment]
My understanding is that there are 8 experts +router at every layer. It's making choices about which experts to use at every layer, not up-front.

**Comment by Dampfinchen** [comment]
> I am hoping for an option to that will let me only load models into memory when they're used, and keep them on disk when not used. I know this would be super slow but it'd let me and many other people run it when we otherwise would have no hope, barring other developments.

I think each expert gets chosen per token basis. So it has to happen very fast and unfortunately, it would put an enourmous strain on an SSD. I don't think its feasible, but options are always welcome. 

But hey that's just me speculating!

**Comment by bergkvist** [comment]
I guess it is fine to use the `mmap` syscall for the full model with all the experts, and only the models/experts being used will actually be loaded into memory by your OS.

**Comment by Reza2kn** [comment]
We even have a fine-tuned version of this for chat, courtesy of Matt Shumer https://huggingface.co/mattshumer/mistral-8x7b-chat

**Comment by fakerybakery** [comment]
[DiscoLM made an instruct one first](https://huggingface.co/DiscoResearch/DiscoLM-mixtral-8x7b-v2), not sure how it compares to Matt Shumer's

**Comment by clemens98** [comment]
About Strain on SSD aren't SSDs made for fast Reading and only Writing being a problem or doas Reading also kill it over time

**Comment by ddh0** [comment]
> About Strain on SSD aren't SSDs made for fast Reading and only Writing being a problem or doas Reading also kill it over time

Yeah I'm pretty sure only writing kills the lifespan

**Comment by mirek190** [comment]
...anyway we are waiting for llamacpp implementation ;)

**Comment by arch-btw** [comment]
Looks like the [mistral.ai](url) website just got updated.

There are even more models now, and they released some information on how to run it, which might help with this project too.

See: https://docs.mistral.ai/models

As a side note, they are also offering sign-ups for API access over here:

https://console.mistral.ai/

**Comment by Dampfinchen** [comment]
Mistral will release an inference code for vLLM soon. 

On their website:

"Deploy Mixtral with an open-source deployment stack
To enable the community to run Mixtral with a fully open-source stack, we have submitted changes to the vLLM project, which integrates Megablocks CUDA kernels for efficient inference."

I assume with some code changes this could be deployed for llama.cpp as well.

**Comment by Swiftyos** [comment]
> Mistral will release an inference code for vLLM soon.
> 
> On their website:
> 
> "Deploy Mixtral with an open-source deployment stack To enable the community to run Mixtral with a fully open-source stack, we have submitted changes to the vLLM project, which integrates Megablocks CUDA kernels for efficient inference."
> 
> I assume with some code changes this could be deployed for llama.cpp as well.

[Here's the PR they are talking about](https://github.com/vllm-project/vllm/pull/2011)

**Comment by WoosukKwon** [comment]
Closed by #2011

**Comment by antirez** [comment]
I see a few comments saying to load the two different models for each layer/token. That would be absolutely unfeasible. What I wanted to suggest in my original comment is that we start running the model like that for a few tokens, collect statistics about the controller output, and then stick for N tokens with a given setup of models/layers. The question here is how much we lose in terms of output quality.

**Comment by clemens98** [comment]
I know SSD performance would be horrible but 128gb ram is not the cheapest  and is pretty close to the maximum you can achieve with consumer oriented hardware don't even know how it would function with VRAM

**Comment by ciekawy** [comment]
> > Mistral will release an inference code for vLLM soon.
> > On their website:
> > "Deploy Mixtral with an open-source deployment stack To enable the community to run Mixtral with a fully open-source stack, we have submitted changes to the vLLM project, which integrates Megablocks CUDA kernels for efficient inference."
> > I assume with some code changes this could be deployed for llama.cpp as well.
> 
> [Here's the PR they are talking about](https://github.com/vllm-project/vllm/pull/2011)

Unfortunately no Apple MPS support is even planned by vLLM :(

**Comment by leedrake5** [comment]
Looks like [this](https://github.com/vllm-project/vllm/pull/2011/files) might be the inference code.

**Comment by khimaros** [comment]
seems like TheBloke has model weights in the works: https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF

**Comment by leedrake5** [comment]
Looks like [this](https://github.com/mistralai/vllm-release/blob/f47ae04cce40b25881eedb31dbb66f6a17674408/vllm/model_executor/models/mixtral.py) might be the inference code.

**Comment by bachittle** [comment]
https://github.com/ggerganov/llama.cpp/pull/4406

**Comment by ciekawy** [comment]
so actually this PR works, also on Apple Metal  https://github.com/ggerganov/llama.cpp/pull/4406 

https://www.loom.com/share/7b25b0da48bd4543a86c1d223f876597?sid=54c6dc1a-65ac-4067-ab29-a2371f146868

**Comment by clemens98** [comment]
Doas the new update support Mixtral x8 ?

**Comment by DutchEllie** [comment]
Someone in the PR thread was able to offload some layers onto their RX 6700, but I haven't gotten that to work for my RX 7900 XTX. In this project all I got was a flashed screen and a frozen GPU, with Ooba it loaded the layers but for inference called on ggml-cuda.c, breaking it and dumping the core.

Obviously for both I used the custom branch

**Comment by ZihaoTan** [comment]
Can try MLX framework if you are using Apple Silicon https://github.com/ml-explore/mlx-examples/tree/main/mixtral.

**Comment by clemens98** [comment]
> Someone in the PR thread was able to offload some layers onto their RX 6700, but I haven't gotten that to work for my RX 7900 XTX. 

So far it almost Always worked with clblas rx7900xt
Are we Talking for Mixtral 7b x8 in particular?

**Comment by DutchEllie** [comment]
> So far it almost Always worked with clblas rx7900xt Are we Talking for Mixtral 7b x8 in particular?

Yes, particularly Mixtral 8x7B. I thought the ROCm version was the hipBLAS one? That's the one I compiled. For Ooba I used the llama-cpp-python package and swapped out the included llama.cpp project with the mixtral branch from here, then compiled and installed the package with the hipBLAS implementation. That's when I got errors.

**Comment by clemens98** [comment]
> Yes, particularly Mixtral 8x7B. I thought the ROCm version was the hipBLAS one? 

It is but I never manged to get ROCm to work at all

**Comment by DutchEllie** [comment]
> It is but I never manged to get ROCm to work at all

You bring up an interesting point, that being that I have no idea whether or not I have been the hipBLAS version or the CLBLAS version all this time, even before Mixtral. I believe, but am unsure, that I checked whether or not normal models worked with my hipBLAS compiled binary, but again I forgot.
When I get to the office soon, I might remote into my workstation just to check 2 things. One, whether or not hipBLAS version works at all even for older models, and whether using CLBLAS fixes it.

**Comment by ChandanVerma** [comment]
https://medium.com/@verma.chandan/mastering-mixtral-8x7b-your-guide-to-ai-magic-with-flask-2c5da9de5d3f

**Comment by ChandanVerma** [comment]
llm_load_tensors: offloading 22 repeating layers to GPU
llm_load_tensors: offloaded 22/33 layers to GPU
llm_load_tensors: VRAM used: 32353.06 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 44.00 MB
llama_new_context_with_model: KV self size  =   64.00 MiB, K (f16):   32.00 MiB, V (f16):   32.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 117.85 MiB
llama_new_context_with_model: VRAM scratch buffer: 114.54 MiB
llama_new_context_with_model: total VRAM used: 32511.60 MiB (model: 32353.06 MiB, context: 158.54 MiB)

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 1.000, min_p = 0.050, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 512, n_batch = 512, n_predict = 1000, n_keep = 0


 [end of text]

llama_print_timings:        load time =    7587.29 ms
llama_print_timings:      sample time =     226.28 ms /   799 runs   (    0.28 ms per token,  3530.96 tokens per second)
llama_print_timings: prompt eval time =   11221.46 ms /   110 tokens (  102.01 ms per token,     9.80 tokens per second)
llama_print_timings:        eval time =  116379.25 ms /   798 runs   (  145.84 ms per token,     6.86 tokens per second)
llama_print_timings:       total time =  128094.46 ms

**Comment by ciekawy** [comment]
thats OT but would be exciting to know more about experts and be able to fine tune particular expert

**Comment by ciekawy** [comment]
> Can try MLX framework if you are using Apple Silicon https://github.com/ml-explore/mlx-examples/tree/main/mixtral.

@ZihaoTan with this PR I'm able to run quantized gguf on 36GB (24GB allocated to GPU)

**Comment by itsdotscience** [comment]
> So I followed the ROCm installation first, but as you said that didn't really work well. Not even the normal Mistral v0.1 model would run properly, same error as with Mixtral. Uses ggml-cuda.c and it crashes, core dumped. Happens with both llama.cpp and llama-cpp-python in ooba.
> 
> Using the CLBLAS version works better. I see both significant improvements on CPU and GPU (CPU went from 3tps to about 6, GPU from crashing to 10tps.) However, I don't think I've been using CLBLAS all this time, as the llama-cpp-python version installed by [Ooba's AMD requirements](https://github.com/oobabooga/text-generation-webui/blob/main/requirements_amd.txt) is a ROCm version. Also, might be because I can only offload 20/33 layers, but initial loading is very slow:
> 
> ```
> # First time loading prompt
> llama_print_timings:        load time =   22956.41 ms
> llama_print_timings:      sample time =      29.61 ms /   100 runs   (    0.30 ms per token,  3377.01 tokens per second)
> llama_print_timings: prompt eval time =   22956.23 ms /    25 tokens (  918.25 ms per token,     1.09 tokens per second)
> llama_print_timings:        eval time =    9082.68 ms /    99 runs   (   91.74 ms per token,    10.90 tokens per second)
> llama_print_timings:       total time =   32351.86 ms
> Output generated in 32.70 seconds (3.06 tokens/s, 100 tokens, context 25, seed 740123037)
> 
> # Same prompt, second time.
> llama_print_timings:        load time =   22956.41 ms
> llama_print_timings:      sample time =      29.58 ms /   100 runs   (    0.30 ms per token,  3380.89 tokens per second)
> llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
> llama_print_timings:        eval time =    9129.46 ms /   100 runs   (   91.29 ms per token,    10.95 tokens per second)
> llama_print_timings:       total time =    9455.29 ms
> Output generated in 9.84 seconds (10.16 tokens/s, 100 tokens, context 25, seed 1015765663)
> ```
> 
> Weird how ROCm doesn't work at all.

set env var HSAKMT_DEBUG_LEVEL=7 and see what it spits out. Should show you what its doing, if anything on the GPU side

**Comment by irony** [comment]
Great work!!

**Comment by JohnGalt1717** [comment]
Any indication when the docker containers will be updated?

**Comment by DutchEllie** [comment]
> set env var HSAKMT_DEBUG_LEVEL=7 and see what it spits out. Should show you what its doing, if anything on the GPU side

I did that. I did the following:
1. I pulled the very freshest version of this repo's master branch
2. I ran the following command to compile `make LLAMA_HIPBLAS=1`
3. I ran the following command to test out `./main -m ../text-generation-webui/models/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf -e -p  "<s>[INST] How fast can a Toyota Supra go? [/INST]" --min-p 0.05 --top-p 1.0 -n 10 -ngl 10`

At that point, `nvtop` reports full 100% GPU usage and the power goes to about 137/327 watts. The screen briefly flashes once black and KDE gives me a scary `Desktop effects were restarted due to a graphics reset` message. 
After that, the llama.cpp program hangs seemingly forever. I had to kill it.

This is the output of the program with the variable enabled like you said.
[log from failure.txt](https://github.com/ggerganov/llama.cpp/files/13664270/log.from.failure.txt)

I did check using the completely default Oobabooga packages, that definitely **does** use the actual ROCm versions, not the OpenCL version. When it loads a model (that actually works) it will say "Using ROCm for GPU acceleration." or something similar. I would copy-paste a log to prove it, but you'll have to take my word for it. Why? Because llama.cpp messed with my GPU so much that I think I need to reboot, everything is going kinda crazy lmao.

**Comment by clemens98** [comment]
Did load the model but I can't Input anything
And wen I did press enter I got greeted with the space invaders bug

**Comment by 65a** [comment]
ROCm/HIPBlas inference works fine. Card is W7900/gfx1100.

Timings:
```
llama_print_timings:        load time =   35904.56 ms
llama_print_timings:      sample time =     548.19 ms /   137 runs   (    4.00 ms per token,   249.91 tokens per second)
llama_print_timings: prompt eval time =   12865.74 ms /   986 tokens (   13.05 ms per token,    76.64 tokens per second)
llama_print_timings:        eval time =    4512.59 ms /   136 runs   (   33.18 ms per token,    30.14 tokens per second)
llama_print_timings:       total time =   40969.37 ms
```
Model is a 4x7B Mixtral, seems to get about 30tok/s.

**Comment by DutchEllie** [comment]
> ROCm/HIPBlas inference works fine. Card is W7900/gfx1100.

That's a relief, to know it's just on my side somehow. I guess it's off to figure out how the hell to get it working now I suppose. I don't assume you're doing anything different from me to compile and run the code?

**Comment by 65a** [comment]
@DutchEllie I had a working ROCm environment already, I recommend debugging your set up with the distro/package specific forum (there's a lot that can go wrong there and I've needed to file various bugs). It's difficult if you're a dev/maintainer and trying to figure out if a patch is bad or a setup is bad if debugging starts with the environment. The classic troubleshooting question is always: "Has it ever worked?" Get to yes on that, and then you can test things more clearly.

**Comment by clemens98** [comment]
I really hope they get clblas to work ROCm is hard to get to work and apparently also drops support for older generations extremely fast

**Comment by DutchEllie** [comment]
I was able to get rocm it "working" using llama-cpp-python on the latest version by adding the gpu targets.
The command I ran to do that there was `CC=/opt/rocm/llvm/bin/clang CXX=/opt/rocm/llvm/bin/clang++ CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DAMDGPU_TARGETS=gfx1100" pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir`

However, you can see I still have issues [with actually getting results](https://github.com/abetlen/llama-cpp-python/issues/1008#issuecomment-1856413819).
Have not tested running an older version with this method though.

**Comment by clemens98** [comment]
i still have to use sudo modprobe amdgpu every time i start my pc to get my gpu detected i am not touching ROCm again
