### ISSUE TITLE
Add QuIP Sharp Support - New Quantization method with amazing 2-bit performance ( close to 16 bit )

### ISSUE THREAD

**Issue by errorsandwarnings** [ggerganov/llama.cpp#4386]
# Prerequisites

A new method can allow running a 2bit 70B models to near native quality and thus this claim is huge in general. It may be applicable to other large models as Falcon-180, YI-34B and multiple others.

QuIP combines lattice codebooks with incoherence processing to create state-of-the-art 2 bit quantized models. These two methods allow QuIP to significantly close the gap between 2 bit quantized LLMs and unquantized 16 bit models.

Claim : 
QuIP#, creates 2 bit LLMs that achieve near-native performance, a previously unseen result. They are providing a full suite of 2 bit Llama 1 and 2 models quantized using QuIP#, as well as a full codebase that allows users to quantize and deploy their own models. They are also providing CUDA kernels that accelerate inference for QuIP# models. 

Code is available here - https://github.com/Cornell-RelaxML/quip-sharp
Read More : https://cornell-relaxml.github.io/quip-sharp/

Results

Method | Precision | Wiki ↓ | C4 ↓ | ArcE ↑ | PiQA ↑
-- | -- | -- | -- | -- | --
Native | 16 bit | 3.120 | 5.533 | 0.597 | 0.809
OPTQ | 3 bit | 4.577 | 6.838 | 0.544 | 0.786
OPTQ | 2 bit | 109.820 | 62.692 | 0.253 | 0.505
QuIP | 2 bit | 5.574 | 8.268 | 0.544 | 0.751
QuIP# | 2 bit | 4.156 | 6.545 | 0.595 | 0.785

If this is replicated in LLaMA2, it will help the adoption to a very high degree.

# Expected Behavior

The provided 2-bit models to work in LLaMA.cpp succesfully.

**Comment by errorsandwarnings** [comment]
@ggerganov  What do you think ?

**Comment by cmp-nct** [comment]
There is a discussion: https://github.com/ggerganov/llama.cpp/discussions/4327
It would never "replace GGUF" because GGUF is a file format for ggml models, not just one quantization

Saying 2-bit is "close" to fp16 in inference result is definitely wrong, no idea where those calculations come from but that's just not possible

**Comment by errorsandwarnings** [comment]
> There is a discussion: #4327 It would never "replace GGUF" because GGUF is a file format for ggml models, not just one quantization
> 
> Saying 2-bit is "close" to fp16 in inference result is definitely wrong, no idea where those calculations come from but that's just not possible

You mean you believe the numbers posted on the claim are not quite right ?

**Comment by cmp-nct** [comment]
I did not dig into the source of the claim. 
llama.cpp already has 2+ to 6+ bit quantization and while it is possible that a more sophisticated quantization algorithm can slightly improve on it, the claim that any 2 bit quantization is "close to 16 bit" is definitely not correct. It's just not possible. 

Anything that improves quality is welcome, just super-hyped claims are not productive imho

**Comment by akarshanbiswas** [comment]
I don't know but the claims made [here](https://cornell-relaxml.github.io/quip-sharp/) are pretty impressive.

**Comment by mirek190** [comment]
> > There is a discussion: #4327 It would never "replace GGUF" because GGUF is a file format for ggml models, not just one quantization
> > Saying 2-bit is "close" to fp16 in inference result is definitely wrong, no idea where those calculations come from but that's just not possible
> 
> You mean you believe the numbers posted on the claim are not quite right ?

Have you even read that topic to the end?
q2 model is retarded whatever you do ... comparing fp16 float weight to 2 BIT precision is ridicules.

**Comment by walking-octopus** [comment]
> Have you even read that topic to the end? q2 model is retarded whatever you do ... comparing fp16 float weight to 2 BIT precision is ridicules.

A better choice for larger speculative sampling models?

**Comment by mirek190** [comment]
> > Have you even read that topic to the end? q2 model is retarded whatever you do ... comparing fp16 float weight to 2 BIT precision is ridicules.
> 
> A better choice for larger speculative sampling models? How does it compare to similar FLOPS/GB models?

Even q2k is better than that ....

**Comment by romilly** [comment]
You're right that conventional 2-bit quantisaton could not match fp16. 
But as I understand it, QuIP-sharp is a radically different quantisation technique.
Instead of using quantisation to reduce the bits for an individual weight, it uses the vector of quantised weights to index into a set of expanded weight vectors. The technique is based on some deep math about packing data in multi-dimensional space. That's why they claim performance is so much better than conventional 2-bit quantisation.

**Comment by sorasoras** [comment]
QuIP#	4.1 is not close to 3.1 on FP16, but that's pretty good.

**Comment by justheuristic** [comment]
Apparently there's another paper that claims to beat QuIP#, sometimes by a lot - https://arxiv.org/abs/2401.06118

The idea seems pretty close to quip# - they also quantize several weights as a group, but without hadamard transform.
