### ISSUE TITLE
support EAGLE models (new speculative model architecture faster than Medusa)

### ISSUE THREAD

**Issue by BarfingLemurs** [ggerganov/llama.cpp#4391]
# Feature Description

Run [EAGLE](https://github.com/SafeAILab/EAGLE) models.

- blog: https://sites.google.com/view/eagle-llm

# Motivation

Users running with CPU could see impressive speeds of 2.5 - 3 times the normal performance on average.

This would speedup inference on GPUs too, however, only llama.cpp runs inference on CPU well. 

![benchmark](https://github.com/ggerganov/llama.cpp/assets/128182951/76eec9a3-99ab-4072-a66e-272db474b425)
![c](https://github.com/ggerganov/llama.cpp/assets/128182951/347b56ed-05f5-44e7-9e23-0af93590a7aa)

# Details

I got 1.3 faster speed than normal using Tinyllama and a 4bit 70B in ggml.

With a 7B Medusa model, I can get 2.0 faster, on gpu - comparing with huggingface transformers.

With their [demo](https://46019f81d5df5243a2.gradio.live/), I found the 13B EAGLE model is 3 times faster on average on most responses.

GIF comparison (theirs):
<img src="https://github.com/SafeAILab/EAGLE/blob/main/figs/demosmall.gif?raw=true">

**Comment by shifeiwen** [comment]
Looking forward to this work

**Comment by CyborgArmy83** [comment]
Really looks promising!

**Comment by tjtanaa** [comment]
How do you all get new weights for other models, e.g. WizardLM, mistral fine-tuned model?

**Comment by mscheong01** [comment]
EAGLE-2 is out
https://arxiv.org/html/2406.16858v1
<img width="889" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/54794500/22580f96-a2d3-45d2-8e1f-c18474fe53f5">
Looks super fast from what they're saying 👀
