### ISSUE TITLE
Qwen can't decode the Non-English after English characters.

### ISSUE THREAD

**Issue by czkoko** [ggerganov/llama.cpp#4397]
<img width="918" alt="2023-12-10 03 38 49" src="https://github.com/ggerganov/llama.cpp/assets/90698189/abfa5476-dd52-4bbf-94dc-035df76349da">
<img width="912" alt="2023-12-10 03 43 48" src="https://github.com/ggerganov/llama.cpp/assets/90698189/e269508f-4cf9-4cd9-ab00-2efd6e68297e">

**Comment by zhangchn** [comment]
commit 948ff137ec37f1ec74c02905917fa0afc9b97514 should have fixed this bug.

In master branch, QWen behaved normally in `server`.
