### ISSUE TITLE
[Question] 2x 24GB GPU run a 40GB VRAM model?

### ISSUE THREAD

**Issue by massudy** [ggerganov/llama.cpp#4402]
When using multiple GPUs i can run a model bigger than VRAM of a unique GPU?

**Comment by Alumniminium** [comment]
yes

**Comment by massudy** [comment]
> yes

Thanks @Alumniminium 

run without any config and it will understand that need split?

**Comment by massudy** [comment]
> yes, you can also assign percentage ratios, the `-ts 2,1`parameter is for that (in this case 2:1 loading ratio on card #0. The memory calcuations are not flawless currently, so not all ratios will work. In addition you can use `-mg 0` to specify the main gpu for certain calculations (the faster one)
> 
> In addition, for cuda, you can use the environment variable `CUDA_VISIBLE_DEVICES` to specify which cards are visible like "0,1" or just "1". You can also use the `-ts` to assign 0 ratio to a card, disabling it that way. But it's not as reliable in all cases
> 
> Be aware that performance will degrade extremely as soon as you use more than one card, even if it's just for a tiny fraction of the model, apparently a bit better on linux systems than on windows.

Thanks, very complete answer 👏

**Comment by massudy** [comment]
@cmp-nct Hi
the performance degrade like 50%+- when split the model in 2 GPU cards?
