### ISSUE TITLE
Adding image generation

### ISSUE THREAD

**Issue by sussyboiiii** [ggerganov/llama.cpp#4408]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Similar to fooocus i think it would be cool to add the feature to generate images but fast, because fooocus or similar application run really slow on OSX.

# Motivation

As mentioned already fooocus or the huggingface gui are painfully slow on macOS because they use PyTorch Nigtly build or something named similar.

# Possible Implementation

I have no idea as to how to implement this but i think id be a great addition.

**Comment by cmp-nct** [comment]
Take a look here:
https://github.com/leejet/stable-diffusion.cpp

**Comment by 0wwafa** [comment]
I would like this too.

**Comment by yurivict** [comment]
Why was this closed?
Was this implemented?

**Comment by 0wwafa** [comment]
nope
