### ISSUE TITLE
Add Support for ise-uiuc/Magicoder-S-DS-6.7B

### ISSUE THREAD

**Issue by apcameron** [ggerganov/llama.cpp#4419]
Add Support for https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B

The convert.py script fails on this model and the GGUF provided by The Bloke does not work with your code.

**Comment by lilblam** [comment]
This is the best pound for pound coding model out right now, better than DeepSeek Coder 6.7b instruct. It tests only slightly worse than DeepSeek Coder 34b Instruct. It would be awesome to have this supported!

**Comment by ayoub-elmendoub** [comment]
i'am having the same issue
