### ISSUE TITLE
make Breakpoints can't be stopped；cmake segmentation fault has occurred

### ISSUE THREAD

**Issue by 18222901154** [ggerganov/llama.cpp#4422]
system：win64
Compile the project using w64devkit
1.If I'm compiling code with make to generate main.exe, when I debug with VSCode breakpoint, the breakpoint doesn't stop
![屏幕截图 2023-12-12 094824](https://github.com/ggerganov/llama.cpp/assets/15910582/8771eab8-b6ab-4262-b105-1d8c0730b72f)
2.If I am compiling code with cmake to generate main.exe, when I use VSCode breakpoint debugging, it appears segmentation fault.
![屏幕截图 2023-12-12 094519](https://github.com/ggerganov/llama.cpp/assets/15910582/54474014-96cc-4b03-baf7-7e3e189469f3)

**Comment by lzcchl** [comment]
哥，问下想用vscode跑应该怎么配置一下？

**Comment by lzcchl** [comment]
老哥解决了吗，make的时候打开debug相关的环境变量，能多命中一些断点，但是依然不能全部命中

**Comment by lzcchl** [comment]
看来还是对编译不熟悉，要把所有东西都搞成debug模式就行了
