### ISSUE TITLE
Cannot get the mixtral branch to load mixtral GGUF files

### ISSUE THREAD

**Issue by techvd** [ggerganov/llama.cpp#4431]
I'm having trouble getting the mixtral branch to load mixtral GGUF files I downloaded from TheBloke huggingface repos.
I tried a clean build multiple times but still no luck. Should the mixtral branch work as is or are there any additional changes or patches that are required?

```
llm_load_tensors: ggml ctx size =    0.36 MiB
llm_load_tensors: using CUDA for GPU acceleration
error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/mnt/models/mixtral-8x7b-v0.1.Q4_K_M.gguf'
main: error: unable to load model
```

.../llama.cpp/build$ git status
On branch mixtral
nothing to commit, working tree clean

This is on WSL Ubuntu with CUDA 12.1.
I noticed that the tensor it is looking for is not in the list of tensors reported by the llama_model_loader.
Any help is greatly appreciated.

**Comment by techvd** [comment]
Follow up. So I tried this on Windows and it worked perfectly! I was able to load the GGUF files and run some tests. On Linux (Ubuntu) I still have this problem. Anybody able to get this work correctly on Linux?

**Comment by techvd** [comment]
Not sure what exactly happened but after a couple of tries, it worked fine.

**Comment by EdwardDali** [comment]
same problem: 
error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'mixtralnt-4x7b-test.Q4_K_M.gguf'
main: error: unable to load model

**Comment by ChandanVerma** [comment]
https://medium.com/@verma.chandan/mastering-mixtral-8x7b-your-guide-to-ai-magic-with-flask-2c5da9de5d3f

**Comment by l4b4r4b4b4** [comment]
Im building with the cuda full Dockerfile from the repo being on the mixtral and on the master branch but getting the above error as well!

**Comment by l4b4r4b4b4** [comment]
Freshly cloning the llama-cpp repo and rebuilding did the trick for me to resolve this issue ;)

**Comment by ggerganov** [comment]
The mixtral branch has been merged
