### ISSUE TITLE
Uncensored models

### ISSUE THREAD

**Issue by sussyboiiii** [ggerganov/llama.cpp#4434]
I have been searching for some uncensored model which can give you some mad output but I wasn't successful finding ones compatible with lama.cpp.
Can someone recommend some preferable 13b.
Thanks!

**Comment by BarfingLemurs** [comment]
You want to use the search section on huggingface. https://huggingface.co/models?sort=trending&search=13b+uncensored+gguf

@sussyboiiii
Please close this issue, we both know this is not what github issue is for. (If you need help, make a discussion instead)
