### ISSUE TITLE
Run Mixtral-8x7b-instruct with Llama.cpp: Could not load Llama model from path

### ISSUE THREAD

**Issue by weissenbacherpwc** [ggerganov/llama.cpp#4439]
Hi,

I saw that you should be able to run the new Mixtral-8x7B Model with Llama.cpp and I wanted to try it. I downloaded this version of "TheBloke": https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/blob/main/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf

However when I try to run the Model I am getting the following error message: 
```
ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: [Modelle/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf.](https://file+.vscode-resource.vscode-cdn.net/Modelle/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf.)
```

Here is the code how I am running Models with Llama.Cpp:

```
from langchain.llms import CTransformers
from dotenv import find_dotenv, load_dotenv
import box
import yaml
from langchain.llms import LlamaCpp
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

# Load environment variables from .env file
load_dotenv(find_dotenv())

# Import config vars
with open('config/config.yml', 'r', encoding='utf8') as ymlfile:
    cfg = box.Box(yaml.safe_load(ymlfile))


def build_llm(model_path):
        callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

       # I am running the model on Mac
        n_gpu_layers = 1  # Metal set to 1 is enough.
        n_batch = 512  # Should be between 1 and n_ctx, consider the amount of RAM of your Apple Silicon Chip.
        
        llm = LlamaCpp(
                max_tokens =cfg.MAX_TOKENS,
                #model_path=cfg.MODEL_BIN_PATH,
                model_path=model_path,
                temperature=cfg.TEMPERATURE,
                f16_kv=True,
                n_ctx=7000,
                n_gpu_layers=n_gpu_layers,
                n_batch=n_batch,
                callback_manager=callback_manager, 
                verbose=True, # Verbose is required to pass to the callback manager
                top_p=0.75,
                top_k=40,
                model_kwargs={
                        'repetition_penalty': 1.1,
                        'mirostat': 2,
                },
        )
        
        return llm

llm = build_llm("/Modelle/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf")
```

I was able to run other Mistral Models before with this approach, so what is the issue here?

**Comment by hongjunsong1** [comment]
FYI:
These are experimental GGUF files, created using a llama.cpp PR found here: https://github.com/ggerganov/llama.cpp/pull/4406.

THEY WILL NOT WORK WITH LLAMA.CPP FROM main, OR ANY DOWNSTREAM LLAMA.CPP CLIENT - such as LM Studio, llama-cpp-python, text-generation-webui, etc.

To test these GGUFs, please build llama.cpp from the above PR.

**Comment by weissenbacherpwc** [comment]
thanks @hongjunsong1!
So will they work in future with llama-cpp-python?
Or how do I build llama.cpp from the PR in a .py file and not in the terminal? I am a bit confused

**Comment by supportend** [comment]
Use the recent llama.cpp release, it supports mixtral-8x7b-models:

> [b1629]
> llama : add Mixtral support (#4406)

Latest release is b1631. I updated it with
```
git pull
make
```
And it works, now i can delete the mixtral-branch.

**Comment by varunshankar07** [comment]
could you instruct me how to run this ? i have downloaded the magnet file

**Comment by supportend** [comment]
You mean the model?

I run it on CPU only in two ways:

- interactive with Web-GUI: `./server -t 8 -m ~/Downloads/models/mixtral-8x7b-instruct-v0.1.Q6_K.gguf -c 8192 --log-disable`
- with main: `./main -t 8 -m ~/Downloads/models/mixtral-8x7b-instruct-v0.1.Q6_K.gguf -c 8192 --temp 0.7 --repeat_penalty 1.1 --log-disable -n -1 -p "<s>[INST] prompt [/INST]"`

**Comment by varunshankar07** [comment]
could we have a proper chat about this if you are willing to! if your are comfortable with discord. you could provide me your discord and we could have a talk!

**Comment by supportend** [comment]
As is wrote, i don't use Windows, i think, other people are able to help you better.

**Comment by weissenbacherpwc** [comment]
> As is wrote, i don't use Windows, i think, other people are able to help you better.

did you also let it run with llama-cpp-python?

**Comment by supportend** [comment]
No, but in the comments someone wrote:

> I believe it works already; just need to point to the custom build with os.env before import

And he explains, how he did it:
https://github.com/abetlen/llama-cpp-python/issues/1000

The Python-Bindings must use recent llama.cpp, where the support for the models was added.
