### ISSUE TITLE
Model is split between multiple GPU's even after explicitly specifying main gpu

### ISSUE THREAD

**Issue by Abhi011999** [ggerganov/llama.cpp#4442]
I think we need to solve for this, models are automatically loaded and split on multiple GPUs if you have `BaseMosaic` enabled in your XORG config, overriding the default flags that you can explicitly set as your main GPU.

This isn't that big of a deal, but helps when you are experimenting with multiple models.

More details here: https://forums.developer.nvidia.com/t/memory-is-allocated-on-all-gpus/183110/3

Original Discussion:
> ### Discussed in https://github.com/ggerganov/llama.cpp/discussions/2752

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **isaacmorgan** August 24, 2023</sup>
> Using the CuBLAS build with 2 GPUs. I want to load the model onto a single GPU, but the model is always loaded into the memory of both GPUs. Even if I only run on 1 GPU the model is loaded onto both GPUs. 
> 
> Things I've tried:
> `./main -m ./llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40`
> Result: Default behavior: Loads model onto both GPUs, runs on both GPUs.
> 
> `CUDA_VISIBLE_DEVICES=0 ./main -m ./models/llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40`
> Result: Loads model onto both GPUs, runs only on GPU 0
> 
> `CUDA_VISIBLE_DEVICES=1 ./main -m ./models/llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40`
> Result: Crashes: `ggml_init_cublas: found 1 CUDA devices:
>   Device 0: NVIDIA RTX A5000, compute capability 8.6
> Segmentation fault (core dumped)`
> 
> `./main -m ./models/llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40 -mg 0 -ts 1,0`
> Result: Crashes: `CUDA error 400 at ggml-cuda.cu:3343: invalid resource handle`
> 
> `./main -m ./models/llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40 -mg 0 -ts 10,1`
> Result: Loads model onto both GPUs, runs mostly on GPU 0 and a little on GPU 1 (power usage is 220 W on GPU 0, 80 W on GPU 1)
> 
> `./main -m ./models/llama-2-7b.ggmlv3.q8_0.bin -i --interactive-first -ngl 40 -mg 1 -ts 1,10` 
> Result: Same as above, but mostly runs on GPU 1
> 
> When I run a query I can tell from the power usage that only GPU 0 is being used.
> 
> But when I check nvidia-smi I see that the model is loaded to both GPUs. That is, if the model required 8 GB both GPUs show 8 GB of memory is used.
> 
> Any idea what's going on here?</div>

**Comment by phalexo** [comment]
The function that computes free VRAM ignores CUDA_VISIBLE_DEVICES. I think it is a bug. In my case I want to run it on 4 GPUs, but it counts VRAM on the fifth GPU that is of a different type and is really, really old and cannot run the code.
