### ISSUE TITLE
Running Mixtral-8x7B-Instruct-v0.1 gets aborted or my Mac freezes and need a force restart

### ISSUE THREAD

**Issue by sussyboiiii** [ggerganov/llama.cpp#4459]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

To work just slow.

# Current Behavior
I ran the Mixtral Q3_K_M model on my 16GB M1 Pro (I know 16GB ram isnt optimal but i have run a 30B model using 45GB of ram before in llama.cpp) if I use this command `./main -m /Users/user/Downloads/mixtral-8x7b-v0.1.Q3_K_M.gguf` the task gets aborted after a minute or so.
If I use the command from TheBloke on Hugginface `./main -m /Users/user/Downloads/mixtral-8x7b-v0.1.Q3_K_M.gguf --color -c 32768 --temp 0.7 --repeat_penalty 1.1 -n -1 -p "Hello!"` my Mac just frezes and I cant do anything but hold down the powerbutton to turn it off

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`M1 Pro 16GB`

* Operating System, e.g. for Linux:

`23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64`

* SDK version, e.g. for Linux:

```
$ python3 --version: Python 3.10.11
$ make --version: GNU Make 3.81
$ g++ --version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
```

# Failure Information (for bugs)

Please help provide information about the failure / bug.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Acquire a MacBook
2. Download the model (https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/blob/main/mixtral-8x7b-v0.1.Q3_K_M.gguf) and llam.cpp
3. run llama.cpp using the commands mentionned earlier

# Failure Logs

[logs.txt](https://github.com/ggerganov/llama.cpp/files/13669166/logs.txt)
```
commit 948ff137ec37f1ec74c02905917fa0afc9b97514


numpy                                             1.24.0
open-clip-torch                                   2.20.0
pytorch-lightning                                 1.9.5
sentencepiece                                     0.1.98
torch                                             2.2.0.dev20231208
torchaudio                                        2.2.0.dev20231208
torchdiffeq                                       0.2.3
torchmetrics                                      1.0.0
torchvision                                       0.14.1

```

**Comment by sorasoras** [comment]
I doubt you would be able to run this on 16GB now, the bare minimal for 56B model like Mixtral-8x7B required 23g~ RAM on my gpu.

**Comment by sussyboiiii** [comment]
I mean the swap memory is pretty good so it could work

**Comment by sorasoras** [comment]
> I mean the swap memory is pretty good so it could work

doubt it, with VRAM and RAM, it's pretty slow tbh. let along SSDs.

https://github.com/ggerganov/llama.cpp/issues/4455
if smart offload is possible, then it could work through.

**Comment by sussyboiiii** [comment]
Well see but still a bit annoying that my whole OS just freezes

**Comment by sorasoras** [comment]
> Well see but still a bit annoying that my whole OS just freezes

I encounter that as well when I tried to load llama2 70B 2bit onto my 24G VRAM GPU, my chrome gpu thread just crashed. I through shared VRM would do the job but it does not. 
In my case, I partially load onto my gpu vram but that's slow. I am not sure what other option does MACOS have.

**Comment by pudepiedj** [comment]
Can't offer much comfort, I'm afraid. If I don't adjust the usable RAM, I can _just_ run `Q3_K_M` on a 32GB M2 Max. It takes up `(20232.28 / 21845.34)MB` with `-c 4096` and `-ngl 99`. If I cut the `-c` down to `2048` and reduce the `ngl` layers to `10` it takes `(19904 / 21845)MB`. So your system crashes because there's nothing left for the system! Even `Q2_K` takes `15301MB` so I doubt that will run either. The virtual memory disk-swapping probably doesn't work because the MoE requires all the experts in RAM, I think.

**Comment by sussyboiiii** [comment]
Interesting, I can just remember running a 70B model perhaps, it took 45GB of ram and it ran if slowly about 9-12 months ago on the same machine im using right now. It even displayed in taskmanager for mac whatever, that terminal uses 45GB.

**Comment by easp** [comment]
At the root of it, this is a MacOS problem. A userland process should not be able to freeze a machine. The OS should kill it.

The flipside is that your expectations of the machine are pretty ridiculous. At the very least try a smaller quantization and a much smaller context size.

**Comment by sussyboiiii** [comment]
I like to push things to their max, this may also be a problem introduced with MacOS 14

**Comment by sussyboiiii** [comment]
This has to do something with a limit apple has introduced to how much vram can be used of the total ram (~75%). I believe if I were to disable gpu it could run but it'd be painful to wait so this is solved!

**Comment by JavierRSobrino** [comment]
Is there any technology developed yet that can load and offload parts of the model in real time to VRAM as needed so we don't require to have so much RAM?

**Comment by easp** [comment]
@JavierRSobrino Apple Silicon just has RAM. There is no need to move anything.

As for other systems, moving between RAM and VRAM involves moving data over the PCI bus, which is slower than the CPU-RAM interface. CPU is generally able to saturate RAM interface when running inference. So, its faster to split model & computation between CPU/RAM and GPU/VRAM than it is to shuffle data between RAM and VRAM.

**Comment by sussyboiiii** [comment]
> @JavierRSobrino Apple Silicon just has RAM. There is no need to move anything.
> 
> 
> 
> As for other systems, moving between RAM and VRAM involves moving data over the PCI bus, which is slower than the CPU-RAM interface. CPU is generally able to saturate RAM interface when running inference. So, its faster to split model & computation between CPU/RAM and GPU/VRAM than it is to shuffle data between RAM and VRAM.

On Apple Silicon theses a cap on ram for the gpu at around 60% of system ram. For the CPU there limit is way higher because swap memory will allow you to use more ram so if you have 16GB the gpu can use 10GN but the CPU with swap can use depending on the workload more than 40GB.
