### ISSUE TITLE
Cannot run llama.cpp on termux. Bash permission denied

### ISSUE THREAD

**Issue by ManuXD32** [ggerganov/llama.cpp#447]
When trying to run './bin/main/ -m ./models/7B/ggml-model-q4_0.bin -n 128' termux throws this output:
bash: ./bin/main: permission denied

**Comment by KerfuffleV2** [comment]
There's no `./bin` and you also have a slash after `main/` which wouldn't work even if the executable was there. Use `./main -m etc`

Obviously you have to compile it first using `make`. Refer to the README in the main repo. It has instructions for all this stuff.

**Comment by prsyahmi** [comment]
You might have no execute permission. Have you `chmod +x ./bin/main`?

**Comment by ManuXD32** [comment]
@KerfuffleV2 @prsyahmi thank you for your help, the problem was that i wasn't running it from $HOME.

**Comment by olealgoritme** [comment]
The limitation is that the file system is read-only on newer Android versions.
Apps, like termux, has write-access in their app directories, so we move the files there.
Move the compiled binary and model to the ~/ ($HOME) directory (termux app directory).

```
adb push llama /sdcard/
adb push model.bin /sdcard/
cd /sdcard
mv llama ~/
mv model.bin ~/
cd ~/
chmod +x llama
./llama
```
