### ISSUE TITLE
Min-p Mixtral routing

### ISSUE THREAD

**Issue by someone13574** [ggerganov/llama.cpp#4470]
# Feature Description

The basic idea of this issue is that instead of using a fixed number of active experts per token and per layer (top-k), there would be a dynamic amount selected like min-p sampling (must be n% as good as the best gating layer score, or they aren’t selected). This could possibly be combined with top-k if higher expert counts aren’t working well.

# Motivation

The motivation behind this is that it would theoretically allow lower expert counts when it doesn’t significantly harm quality, and allow higher experts counts when needed. By controlling the min-p routing variable, you could control the speed-quality trade off, with high values giving higher speed at the cost of quality, and low values doing the opposite. We know that quality changes based on the active expert count (https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1855151885), so dynamic selection could control this more effectively than a fixed amount.

# Possible Implementation

To implement this, instead of using ggml_topk in the MoE inference section of llama.cpp, a new operation or combination of operations would implement a top-k like output, but with min-p instead. There would also be a user accessible topk and minp parameters on the main example, which could disable it with minp 0 and topk 2, or do other combinations such as minp 0.5 and topk 3, which would require experts to be at least half as good at the top expert, and be in the top 3 experts.

**Comment by martindevans** [comment]
Is it possible to extract any data from llama.cpp about which experts were chosen per layer?
