### ISSUE TITLE
Provided docker images don't support -np -cb  parameters

### ISSUE THREAD

**Issue by alexvt-amz** [ggerganov/llama.cpp#4471]
# Expected Behavior

when using the latest docker image 
ghcr.io/ggerganov/llama.cpp:full-cuda i expect to be able to run server with -cb -np options

# Current Behavior

exists, citing unknown -cb , -np options

**Comment by nd7141** [comment]
Can somebody unblock this? This would allow to deploy endpoints with parallel configuration.

**Comment by alexvt-amz** [comment]
yes that was my observation as well

**Comment by JohnGalt1717** [comment]
For right now you can build it like this:

docker build -t llama.cpp:cuda --build-arg="CUDA_VERSION=12.3.1" --build-arg="UBUNTU_VERSION=22.04" -f ./.devops/full-cuda.Dockerfile .

And then just use llama.cpp:cuda (or whatever you change it to)

**Comment by ibehnam** [comment]
I wish it were possible to build the docker image on macOS while still being able to use Metal.

**Comment by JohnGalt1717** [comment]
You can update the dockerfile so that instead of copying the files in after build, it git clones the files, then builds in the docker container with metal included, and then sets the entrypoint.
