### ISSUE TITLE
server: Completion of pre-tokenized prompt is broken

### ISSUE THREAD

**Issue by shibe2** [ggerganov/llama.cpp#4476]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- I am running the latest code: cafcd4f89500b8afef722cdb08088eceb8a22572
- I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

According to documentation: https://github.com/ggerganov/llama.cpp/blob/cafcd4f89500b8afef722cdb08088eceb8a22572/examples/server/README.md?plain=1#L117

>or as an array of strings or numbers representing tokens

# Current Behavior

When supplying the prompt as array of token identifiers, it instead calls `split_multiprompt_task` and the request hangs.

# Steps to Reproduce

1. Call /tokenize with a text prompt in `content`.
2. Add BOS if needed.
3. Call /completion with the resulting array in `prompt`.

# Failure Logs

<details>
all slots are idle and system prompt is empty, clear the KV cache

slot 0 is processing [task id: 2]  
slot unavailable

print_timings: prompt eval time =       0.00 ms /     0 tokens (    -nan ms per token,     -nan tokens per second)  
print_timings:        eval time = -94366367288.92 ms /     0 runs   (    -inf ms per token,    -0.00 tokens per second)  
print_timings:       total time = -94366367288.92 ms  
slot unavailable
</details>

**Comment by jxy** [comment]
It took me sometime to realize what's wrong with my server.

I originally added the prompt array support for testing prompts with specifically selected tokens, which has been quite useful, as the prompts subject no constraint of any tokenizer.

In order to support both usage, how about allowing 2-level nested prompts? For example,
```
{
"prompt": [
    "First prompt",
    [1, "second prompt provided in an array.", 2, 1, "What do you think?"],
    "Third prompt"
]
}
```

This would be compatible with the multi-prompt change already introduced, and allow for array prompts.

**Comment by jxy** [comment]
I'm baffled. I can't get the current multi-prompt to work. #4583 I'll wait for that to be fixed and introduce new behaviors. For now, using https://github.com/ggerganov/llama.cpp/pull/4232#issuecomment-1856365610 to get back the previous behavior.

**Comment by shibe2** [comment]
I would like it better if multi-prompt field was called "prompts". It can then have sub-arrays as in your example, @jxy. The format of "prompt" field can be made to match the current documentation, i.e. single prompt.
