### ISSUE TITLE
I am using llama.cpp via ollama and encountering a problem that was introduced since ollama 0.1.12, v0.1.11 works as expected.

### ISSUE THREAD

**Issue by phalexo** [ggerganov/llama.cpp#4477]
If the version of ollama is above 0.1.11, it fails identically, regardless of the size of the model.  I have 4 GPUs with 12.2GiB each and models of 5GiB size fail just the same.

At least two other people encountered the same problems, which have been resolved by downgrading ollama to v0.1.11

Unfortunately it is a not a solution if one wants to run Mixtral as v0.1.15 (with MIxtral support) has this very same issue.

llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
⠼ llama_kv_cache_init: VRAM kv self = 256.00 MB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 159.32 MiB
⠴ llama_new_context_with_model: VRAM scratch buffer: 156.00 MiB
llama_new_context_with_model: total VRAM used: 5975.56 MiB (model: 5563.55 MiB, context: 412.00 MiB)
{"timestamp":1702581704,"level":"INFO","function":"main","line":3035,"message":"HTTP server listening","hostname":"127.0.0.1","port":54214}
⠦ {"timestamp":1702581704,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"127.0.0.1","remote_port":50528,"status":200,"method":"HEAD","path":"/","params":{}}
2023/12/14 14:21:44 llama.go:508: llama runner started in 4.800707 seconds
[GIN] 2023/12/14 - 14:21:44 | 200 |  5.773840209s |       127.0.0.1 | POST     "/api/generate"
>>>
>>>
>>> Hello.
{"timestamp":1702581710,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"127.0.0.1","remote_port":50544,"status":200,"method":"HEAD","path":"/","params":{}}
2023/12/14 14:21:50 llama.go:577: loaded 0 images

cuBLAS error 15 at /home/developer/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8448
current device: 0
GGML_ASSERT: /home/developer/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8448: !"cuBLAS error"
memory allocation/deallocation mismatch at 0x56140de8ca20: allocated with malloc being deallocated with delete
⠏ 2023/12/14 14:21:51 llama.go:451: signal: aborted (core dumped)
2023/12/14 14:21:51 llama.go:525: llama runner stopped successfully
[GIN] 2023/12/14 - 14:21:51 | 200 |  938.340539ms |       127.0.0.1 | POST     "/api/generate"
Error: llama runner exited, you may not have enough available memory to run this model

```

**Comment by phalexo** [comment]
I was to recreate the same behavior with llama.cpp run standalone.

bin/main -ngl 35 -m /opt/data/TheBloke/Mixtral-8x7B-v0.1-GGUF/mixtral-8x7b-v0.1.Q6_K.gguf  --color -c 2048 --temp 0.7 --repeat_penalty 1.1 -n -1 -p " Write a python function which returns a list of Fibonacci numbers. "


llm_load_tensors: ggml ctx size =    0.39 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =  102.93 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors: VRAM used: 36497.55 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 256.00 MB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 187.35 MiB
llama_new_context_with_model: VRAM scratch buffer: 184.04 MiB
llama_new_context_with_model: total VRAM used: 36937.59 MiB (model: 36497.55 MiB, context: 440.04 MiB)

system_info: n_threads = 16 / 32 | AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
sampling:
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.700
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp
generate: n_ctx = 2048, n_batch = 512, n_predict = -1, n_keep = 0


  Write a python function which returns a list of Fibonacci numbers.
cuBLAS error 15 at /home/developer/llama.cpp/ggml-cuda.cu:8049
current device: 0
GGML_ASSERT: /home/developer/llama.cpp/ggml-cuda.cu:8049: !"cuBLAS error"
memory allocation/deallocation mismatch at 0x55fdc5dc6a20: allocated with malloc being deallocated with delete
Aborted (core dumped)

**Comment by razorback16** [comment]
Related to #4452

**Comment by phalexo** [comment]
Found the solution. 

Build with -DLLAMA_CUDA_FORCE_MMQ:BOOL=ON
