### ISSUE TITLE
Add `make` instructions for Intel MKL

### ISSUE THREAD

**Issue by vn971** [ggerganov/llama.cpp#4481]
Is it possible to, please, add support for Intel MKL for make?
I'm not an expert in make/cmake, but from my vague understanding, CMakeLists.txt [has some definitions for MKL](https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L243), but in the Makefile, I was not able to find anything like that.

My question is, how to use Intel MKL with make? Or should I use cmake instead?

Thanks regardless for the project to everyone involved!

**Comment by player1537** [comment]
Based on my own experience, I've found the CMake solution to work the best, and that would be my recommendation to you. I don't know if there's a specific reason to not use CMake, but CMake is probably the only supported way to do it.

I have previously used this configuration to build with Intel MKL.

```console
$ git clone https://github.com/ggerganov/llama.cpp.git
$ cmake -Hllama.cpp -Bllama.cpp/build -DLLAMA_BLAS:BOOL=ON -DLLAMA_BLAS_VENDOR:STRING=Intel10_64_dyn
$ cmake --build llama.cpp/build --parallel
```

I got that vendor string from [the CMake documentation for the FindBLAS module](https://cmake.org/cmake/help/latest/module/FindBLAS.html#blas-lapack-vendors).

I'm unsure how your environment is set up, but make sure you have MKL's stuff added to your environment variables. I recall a `setenv.sh` script or something similar to it.
```
