### ISSUE TITLE
whats the right way the use llama.cpp from a Windows app ?

### ISSUE THREAD

**Issue by FiveTechSoft** [ggerganov/llama.cpp#4496]
How to write a question from a Windows dialog box and get the llama.cpp output in an edit multiline in the dialog box ?

whats the recommended way to do this ? should I remove all printf() calls from main.cpp ? Should I provide a callback function ?

Any hint is very appreciated, thank you

**Comment by bullno1** [comment]
You should use it as a library.

main.cpp is just an example albeit a huge one.

**Comment by FiveTechSoft** [comment]
got it working very nicely 👍 

![fwh_ai](https://github.com/ggerganov/llama.cpp/assets/10235217/7875c971-154e-421a-a64c-a2934a9f5ed8)
