### ISSUE TITLE
server: make completions endpoint follow openai api just like chatcompletion

### ISSUE THREAD

**Issue by nyxkrage** [ggerganov/llama.cpp#4497]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I would expect to see the regular Completions endpoint follow the OpenAI API just like the ChatCompletions one, and be called with `/v1/completions`

# Current Behavior

Currently only the ChatCompletions endpoint follows the OpenAI standard, and the regular Completions endpoint is on `/completion`

# Environment and Context

This would make use with software that benefits from the greater control of being able to craft the whole prompt themselves, such as SillyTavern, much better while avoiding extra code to handle the llama.cpp server separately

**Comment by AlpinDale** [comment]
Bump. I was struggling with the completions endpoint for a good while until I figured out it's `completion` and not `completions`. Rookie mistake but I assumed I was doing something wrong and llama.cpp is following the standards for OpenAI API.

**Comment by mscheong01** [comment]
Is this still required? It seems like the regular completions api is marked as `Legacy` in openai docs
https://platform.openai.com/docs/api-reference/completions
If this is still of use, I'll file a PR for this.

**Comment by nyxkrage** [comment]
> Is this still required? ...

I would say so. Since the regular text completions endpoint still has uses where it excels such as response continuation, more control over prompt injections from the client like in SillyTavern, and non-chat like interactions like code completion or just using non-instruct models.

> It seems like the regular completions api is marked as Legacy in openai docs

And while OpenAI and Anthropic are deprecating non-chat completions, most inference engines that implement an OpenAI api, have regular the completions endpoint on /v1/completions, so I think it'd make sense to follow suit.
