### ISSUE TITLE
http://localhost:8000/docs shows empty page -> Uncaught ReferenceError: SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by 3x3cut0r** [ggerganov/llama.cpp#4507]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

browsing to http://localhost:8000/docs should show the api reference page (docs)

# Current Behavior

browsing to http://localhost:8000/docs shows an empty page (all white)

# Environment and Context

I run llama-cpp-python in a docker container. 
```
alpine=3.19.0
python3=3.12.1
llama-cpp-python=0.2.23
```

# Failure Information (for bugs)
an error in the browser developer console says:
```
Failed to load resource: net::ERR_CONNECTION_REFUSED
Uncaught ReferenceError: SwaggerUIBundle is not defined
    at docs:15:16
```

view-source:http://localhost:8000/docs
```

    <!DOCTYPE html>
    <html>
    <head>
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css">
    <link rel="shortcut icon" href="https://fastapi.tiangolo.com/img/favicon.png">
    <title>🦙 llama.cpp Python API - Swagger UI</title>
    </head>
    <body>
    <div id="swagger-ui">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <!-- `SwaggerUIBundle` is now available on the page -->
    <script>
    const ui = SwaggerUIBundle({
        url: '/openapi.json',
    "dom_id": "#swagger-ui",
"layout": "BaseLayout",
"deepLinking": true,
"showExtensions": true,
"showCommonExtensions": true,
oauth2RedirectUrl: window.location.origin + '/docs/oauth2-redirect',
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
    })
    </script>
    </body>
    </html>
```

What is missing here?

**Comment by Azeirah** [comment]
This isn't the llama-cpp-python repository.

Additionally, the problem is caused because the swagger CDN script is loaded in the body. If a script is defined in the head, the browser guarantees it will be loaded before anything in the body runs. This is not the case for scripts in the body, so there's a race condition here.
