### ISSUE TITLE
llama.swiftui : load downloaded models

### ISSUE THREAD

**Issue by bachittle** [ggerganov/llama.cpp#4509]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Issue
After adding https://github.com/ggerganov/llama.cpp/pull/4483, tried it out and the benchmarking works well, as well as the download mechanic. The only issue is it does not load after downloading. Should be an easy fix as the LlamaState just needs to be reloaded with a new defaultModelUrl.

**Comment by ggerganov** [comment]
The idea is to click again on the model to load it. Seemed more intuitive to me, but we can change if you think it is not clear.

**Comment by bachittle** [comment]
oh ok that works. i was just expecting it to load once it was done downloading, or have a separate button for loading, but i think that will be fine. this is mostly just to get it working in the simulator anyways.
