### ISSUE TITLE
Mixtral 8x7B didnt work with server.exe 

### ISSUE THREAD

**Issue by williamgomez71** [ggerganov/llama.cpp#4512]
on December 16th I cloned the repository https://github.com/ggerganov/llama.cpp with the branch that could work with Mixtral 8x7B https://github.com/ggerganov/llama.cpp/tree/mixtral, then build correctly and the .exe files were generated above the build/bin/Release folder however when I run .server.exe with the following command:

.\server.exe -m C:\mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -ngl 100 -t 24 --host 0.0.0.0 --port 9124 --ctx-size 8192--verbose -- 0.25 string frequency scale

The inference never starts, I have tried with .main and although it takes a while the output is generated, however with .server this does not happen.

I also cloned the repository, changed branches, and then generated the executables, however, I have the same problem.

Open your terminal and run: git clone https://github.com/ggerganov/llama.cpp
This brings Mixtral to your local playground.
2. Switch to the Mixtral branch:
Switch to Mixtral branch: git checkout mixtral

but the problem is the same 

I have a nvidia 4090 with 24gb of memory in windows also I have 192GB of RAM,  I tried with those models from huggingface, but I dont sure if maybe the quantize model has any issue.
https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF
https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF

I would like to generate by myself the quantized model (Q4_K_M.gguf) from the original  hugging face model (https://huggingface.co/mistralai/Mixtral-8x7B-v0.1), in order to test again and verify that the model is not the problem, but I didn't find the way to generate .Q4_K_M.gguf from the pt files, if anyone can guide to me to do this I'll  really appreciated this

**Comment by sorasoras** [comment]
Q4 is just too big for 4090 24g, use Q3 instead.

**Comment by williamgomez71** [comment]
the same issue, with this model (mixtral-8x7b-instruct-v0.1.Q3_K_M.gguf ), Im not sure if this is the root cause of the issue, because the model is loading correctly, in fact I see when the request arrived to the server but in this case  the inference spend 11 minutes and 26 seconds, Im not sure if this behavior is normal because all layers are load in the GPU memory and CUDA is working fine, in fact BLAS = 1 as we can see in the next output:

ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
{"timestamp":1702866627,"level":"INFO","function":"main","line":2664,"message":"build info","build":1645,"commit":"c6c4fc0"}
{"timestamp":1702866627,"level":"INFO","function":"main","line":2671,"message":"system info","n_threads":24,"n_threads_batch":-1,"total_threads":48,"system_info":"AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | **"}**
llm_load_tensors: VRAM used: 19365.55 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 2048.00 MB
llama_new_context_with_model: KV self size  = 2048.00 MiB, K (f16): 1024.00 MiB, V (f16): 1024.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 1111.22 MiB
llama_new_context_with_model: VRAM scratch buffer: 1108.04 MiB
llama_new_context_with_model: total VRAM used: 22521.59 MiB (model: 19365.55 MiB, context: 3156.04 MiB)
Available slots:
 -> Slot 0 - max context: 8192
 -> Slot 1 - max context: 8192

llama server listening at http://0.0.0.0:9124

{"timestamp":1702866638,"level":"INFO","function":"main","line":3093,"message":"HTTP server listening","hostname":"0.0.0.0","port":"9124"}
all slots are idle and system prompt is empty, clear the KV cache
{"timestamp":1702866649,"level":"INFO","function":"log_server_request","line":2614,"message":"request","remote_addr":"127.0.0.1","remote_port":56875,"status":200,"method":"POST","path":"/tokenize","params":{}}
{"timestamp":1702866649,"level":"VERBOSE","function":"log_server_request","line":2619,"message":"request","request":"{\"content\": \"<s>[INST] <<SYS>>\\nYou are a helpful assistant, you can answer questions and give meaningful answer to the users, also you  have to translate the answer to Spanish \\n<</SYS>>\\n\\ndame un codigo para hacer una pagina web para pelucas [/INST] <s>[INST] ... I tried with this model and this  other (mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf) but the issue is the same 
in other hand I would like to generate by myself the quantized model (Q4_K_M.gguf) from the original hugging face model (https://huggingface.co/mistralai/Mixtral-8x7B-v0.1), in order to test again and verify that the model is not the problem, but I didn't find the way to generate .Q4_K_M.gguf from the pt files, if anyone can guide to me to do this I'll really appreciated this

**Comment by edoardogiacomello** [comment]
I had a similar problem with lama-cpp-python, I don't know if it can be related to this:
https://github.com/abetlen/llama-cpp-python/issues/1033 

Did you try it with very short prompts first?
