### ISSUE TITLE
LLAMA_CUDA_FORCE_MMQ is also required on gfx1100 and large context sizes [HIPBLAS]

### ISSUE THREAD

**Issue by 65a** [ggerganov/llama.cpp#4517]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

GPU-assisted inference can use prompts up to the context size and n_train_ctx without errors on ROCm/HIPBlas cards.

# Current Behavior

For a model with a context size of 8192, and llama.cpp library linked via the C interface, running with a batch and context size of 8192 and a depth of 1 on a single Alpaca completion prompt, everything works correctly and speed is good, until the number of tokens in the prompt is greater than 4096. The first inferenced token (often though it may work the first time, but not the second) will have a crash in the GPU kernel. On ROCm this is a GPU agent reporting page not present or supervisor required, but I believe this issue is possibly similar to #4395 and #4477. Indeed, setting DLLAMA_CUDA_FORCE_MMQ to ON in CMAKE solves the problem at some performance cost, and inference happily continues on long contexts with no issues.

It is entirely possible that this is a bug in my calling code, but the fact LLAMA_CUDA_FORCE_MMQ fixes this and a few CUBLAS-side issues makes me suspicious something isn't happening right in ggml-cuda.cu...

# Environment and Context

CPU:  Intel(R) Xeon(R) Gold 6414U 32c/64t
Mem: 256GB DDR5 4800mhz
GPU: AMD Pro W7900
VRAM: 48GB ddr5

Kernel: 6.6.7-arch1-1
rocm-llvm 5.7.1-2

# Failure Information (for bugs)

# Steps to Reproduce

Easiest to reproduce for me by writing a C wrapper calling `llama.h`, setting up a context with the batch and context sizes set to n_ctx_train from the model, and running a basic inference. Everything is fine until ~ 4096 tokens are in the prompt (e.g. RAG, chat history, etc) and then the GPU kernel crashes just after prompt logits are computed and the first actual inferencing starts.

Enabling FORCE_MMQ immediately and completely resolves this issue, with it unset, perhaps maybe the first inference with a prompt size over 4096 succeeds, and every subsequent one will fail.

If it helps, the context is initialized thusly to be max(settings, model's trained context):
```
  // Create context
  ctx_params.n_ctx = llama_n_ctx_train(model);
  if (ctx_params.n_ctx > max_context)
    ctx_params.n_ctx = max_context;
  ctx_params.n_batch = ctx_params.n_ctx;
  ctx_params.seed = seed;
  struct llama_context* ctx = llama_new_context_with_model(model, ctx_params);
```
and the batch like so:
```
// Initialize batch.
// Freed in function tail.
llama_batch batch = llama_batch_init(ctx_params.n_ctx, 0, 1);
```

# Failure Logs

Here are some logs from a crash with `AMD_LOG_LEVEL=1`
```
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: freq_base  = 100000.0
llama_new_context_with_model: freq_scale = 1
:1:rocdevice.cpp            :3193: 1400599636 us: [pid:36783 tid:0x7f005f7fe6c0] hsa_amd_pointer_info() failed
llama_kv_cache_init: VRAM kv self = 1024.00 MB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
:1:rocdevice.cpp            :3193: 1400838845 us: [pid:36783 tid:0x7f005f7fe6c0] hsa_amd_pointer_info() failed
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 8835.25 MiB
:1:rocdevice.cpp            :3193: 1400839756 us: [pid:36783 tid:0x7f005f7fe6c0] hsa_amd_pointer_info() failed
llama_new_context_with_model: VRAM scratch buffer: 8832.06 MiB
llama_new_context_with_model: total VRAM used: 17061.89 MiB (model: 7205.83 MiB, context: 9856.06 MiB)
[PROMPT TEXT REDACTED, approximately 4365 tokens]
### Assistant:
Character:Memory access fault by GPU node-1 (Agent handle: 0x2b721b0) on address 0x7ef86be1f000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```
`AMD_LOG_LEVEL=1` doesn't log anything particularly interesting at the point of crash. Adding `AMD_SERIALIZE_KERNEL=3` and `AMD_SERIALIZE_COPY=3` yields a ton of:
```
:1:hip_code_object.cpp      :616 : 1836736769 us: [pid:38428 tid:0x7f3b095ff6c0] Cannot find the function: Cijk_Alik_Bljk_HB_MT128x128x16_MI16x16x16x1_SN_1LDSB0_APM1_ABV0_ACED0_AF0EM1_AF1EM1_AMAS3_ASE_ASGT_ASLT_ASAE01_ASCE01_ASEM1_AAC0_BL1_BS1_DTL0_DTVA0_DVO0_ETSP_EPS1_FSSC10_FL0_GRPM1_GRVW8_GSU1_GSUASB_GLS0_ISA1100_IU1_K1_KLA_LBSPP128_LPA8_LPB8_LDL1_LRVW16_LWPMn1_LDW0_FMA_MIAV1_MDA2_MO40_MMFGLC_NTA0_NTB0_NTC0_NTD0_NEPBS0_NLCA1_NLCB1_ONLL1_OPLV0_PK0_PAP0_PGR1_PLR1_RK0_SIA3_SS1_SU32_SUM0_SUS128_SCIUI1_SPO0_SRVW0_SSO0_SVW2_SNLL0_TSGRA0_TSGRB0_TT4_64_TLDS1_UMLDSA1_UMLDSB1_USFGROn1_VAW2_VSn1_VW2_WSGRA1_WSGRB1_WS32_WG32_4_1_WGM8
```
but still crashes. I wasn't able to get anything useful out of gdb or coredumpctl.

```

**Comment by sorasoras** [comment]
I think the recent change fix the compile problem this should close.

**Comment by phalexo** [comment]
> I think the recent change fix the compile problem this should close.

Which specific change, there are lots of recent changes?

**Comment by sorasoras** [comment]
> > I think the recent change fix the compile problem this should close.
> 
> Which specific change, there are lots of recent changes?

nevermind, I response to a wrong post  sry

**Comment by clemens98** [comment]
How do I add DLLAMA_CUDA_FORCE_MMQ ? 
Make hipblas=1 DLLAMA_CUDA_FORCE_MMQ=1?

**Comment by 65a** [comment]
No longer reproducible at HEAD. There have been a few recent changes to the .cu file that might have fixed this, but inference is succeeded in one shot prompts over 4k token length now.

**Comment by phalexo** [comment]
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.38 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =  102.92 MiB
llm_load_tensors: VRAM used           = 36497.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
....................................................................................................
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 2048.00 MB
llama_new_context_with_model: KV self size  = 2048.00 MiB, K (f16): 1024.00
MiB, V (f16): 1024.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 1111.22 MiB
llama_new_context_with_model: VRAM scratch buffer: 1108.04 MiB
llama_new_context_with_model: total VRAM used: 39653.59 MiB (model:
36497.55 MiB, context: 3156.04 MiB)
CUDA error: cudaMemcpyAsync(src1_ddf_i, src1_ddf_i_source,
src1_ncols*ne10*sizeof(float), cudaMemcpyDeviceToDevice, stream): invalid
argument
  in function ggml_cuda_op_mul_mat at ggml-cuda.cu:8202
GGML_ASSERT: ggml-cuda.cu:240: !"CUDA error"
memory allocation/deallocation mismatch at 0x55af75a4e0a0: allocated with
malloc being deallocated with delete []
Aborted (core dumped)

built without LLAMA_CUDA_FORCE_MMQ=1

Maybe it works with HIMBLAS, but still has a problem with cuBLAS.

I updated my local source with "git pull." Is there something to do to get
working code?
