### ISSUE TITLE
Add support for running bloom models

### ISSUE THREAD

**Issue by bil-ash** [ggerganov/llama.cpp#452]
Bloom models have a more permissive license than llama models and are also multilingual in nature. While there is a project [based on llama.cpp](https://github.com/NouamaneTazi/bloomz.cpp) which can perform inference of bloom models, development seems to be slow and might even stagnate after a few days. So I am requesting to add support for running bloom models using llama.cpp(most probably with a command-line switch)

**Comment by v3ss0n** [comment]
may be move to discussion?

**Comment by reedxiao** [comment]
Agreed, and Bloom has much better support and performance for other languages, while llama is mostly English focused.

**Comment by acul3** [comment]
+1 to this

i'm already fine tuning bloom for instruction task and the result quite good

bloomz.cpp seem doesnt have capabilities to do inference for instruction task (define prompt)

**Comment by akumaburn** [comment]
FYI, I've created a conversion script that successfully turns bloom's tokenizer.json files into tokenizer.model files here: https://github.com/ggerganov/llama.cpp/pull/867

I'm also working on a chunked conversion script for bloomz-176b, so I think its a good idea to add bloom support also.

**Comment by akumaburn** [comment]
> FYI, I've created a conversion script that successfully turns bloom's tokenizer.json files into tokenizer.model files here: #867
> 
> I'm also working on a chunked conversion script pytorch to ggml for bloomz-176b, so I think its a good idea to add bloom support also. It should allow very large models to be converted with much less memory.

Chunked conversion script is here: https://github.com/ggerganov/llama.cpp/commit/74b92ff6b834a3e8d854e4e4986bdb845e382864

This loads the model layer by layer instead of all at once and does the conversion layer by layer as well. It has significantly lower memory requirements.

See also:
https://github.com/ggerganov/llama.cpp/pull/867

cc @reedxiao @rabidcopy
