### ISSUE TITLE
Mistral doesn't use GPU VRAM (Yes nvidia is setup correctly and is working with LLAMA2 model)

### ISSUE THREAD

**Issue by rami-dabain** [ggerganov/llama.cpp#4522]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

VRAM to be used when using Mistral:7b or LLAMA2 model.

# Current Behavior

mistal:7b doesn't use VRAM/GPU (screenshot 1)
LLAMA2 uses VRAM/GPU (screenshot 2)

in addition i get the following when using mistral:
```
{"timestamp":1702845122,"level":"WARNING","function":"server_params_parse","line":2148,"message":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":-1}
{"timestamp":1702845122,"level":"INFO","function":"main","line":2652,"message":"build info","build":441,"commit":"948ff13"}
```

This is running Mistral:
![image](https://github.com/ggerganov/llama.cpp/assets/1197104/a093b233-7c48-4305-96df-cd68f9ac90c8)

This is running LLAMA2:
![image](https://github.com/ggerganov/llama.cpp/assets/1197104/875113d1-382e-49b5-8cbd-95959eba950a)

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  36
  On-line CPU(s) list:   0-35
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
    CPU family:          6
    Model:               85
    Thread(s) per core:  2
    Core(s) per socket:  18
    Socket(s):           1
    Stepping:            7
    CPU(s) scaling MHz:  56%
    CPU max MHz:         4800,0000
    CPU min MHz:         1200,0000
    BogoMIPS:            6000,00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat 
                         pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx p
                         dpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good n
                         opl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 mo
                         nitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca ss
                         e4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f
                         16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3
                          invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow 
                         vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 sm
                         ep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx sma
                         p clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsa
                         vec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_loc
                         al dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req 
                         avx512_vnni md_clear flush_l1d arch_capabilities
```
* Operating System, e.g. for Linux:

Ubuntu. Same behavior on Ubuntu 22.04 and 23.04 and 22.10 (tested on 3 machines with the exact hardware but different OSes and slightly different GPUs)  

* SDK version, e.g. for Linux:
(Unrelated - using latest ollama docker image)

```
$ python3 --version (Unrelated - using latest ollama docker image)
$ make --version (Unrelated - using latest ollama docker image)
$ g++ --version (Unrelated - using latest ollama docker image)
```

# Failure Information (for bugs)

Please help provide information about the failure / bug.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. start ollama inside docker  with GPU support
2. in a separate terminal, run `watch nvidia-smi`
3. inside ollama container run `ollama run llama2 "hi there"`
4. take note of VRAM usage in the nvidia-smi window
5. inside ollama container run `ollama run mistral:7b "hi there"`
6. take note of VRAM usage in the nvidia-smi window

Notice how mistral doesn't use the GPU memory

# Failure Logs

No failure logs, the diff is:
```
{"timestamp":1702845122,"level":"WARNING","function":"server_params_parse","line":2148,"message":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":-1}
{"timestamp":1702845122,"level":"INFO","function":"main","line":2652,"message":"build info","build":441,"commit":"948ff13"}
```

**Comment by bullno1** [comment]
This seems like an ollama problem.

I was developing with [zephyr](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) and it definitely uses VRAM.

**Comment by rami-dabain** [comment]
This message appears only for Mistral, for LLAMA2 it **doesn't** say `Not compiled with GPU offload support` and it works fine
I will double check the ollama, it could be the problem

**Comment by rami-dabain** [comment]
the GPU i was using had an older driver, no newer driver support, thus using cuda 11.4 which afaik is not supported by llama.cpp or ollama. worked with a newer GPU

**Comment by kityr** [comment]
Having this same issue on a GTX1050 with CUDA Version: 12.3 though. The same "Not compiled with GPU offload support" message.

**Comment by bokey007** [comment]
Hi @rami-dabain I am facing the same issue, however, I am running ollama ON RTX 3080 with cuda 11.1 and driver Nvidia 472 for Linux

Would you suggest upgrading to a newer cuda version?
