### ISSUE TITLE
Enable dynamic VRAM usage for AMD APUs

### ISSUE THREAD

**Issue by mkesper** [ggerganov/llama.cpp#4546]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I built llama.cpp with `make LLAMA_HIPBLAS=1 GPU_TARGETS=gfx1030` to enable support for my AMD APU. I was able to start and run the server with a low context size but with higher context sizes, I run into out of memory situations.
I attach two startup logs.

# Motivation

Many laptops with AMD APUs don't offer any possibility to set a bigger VRAM size in BIOS. VRAM size will probably be hardcoded to a low size like 512 MB, so practically useless for LLM usage.

# Possible Implementation

As I understood, using a solution like https://github.com/pomoke/torch-apu-helper would allow setting VRAM size dynamically / allow requesting more VRAM usage.

**Comment by mkesper** [comment]
[hip_blas_gfx1035_context_2048.log](https://github.com/ggerganov/llama.cpp/files/13726064/hip_blas_gfx1035_context_2048.log)
[hip_blas_gfx1035_context_4096.log](https://github.com/ggerganov/llama.cpp/files/13726067/hip_blas_gfx1035_context_4096.log)

**Comment by mkesper** [comment]
Also trying to offload layers to GPU works only with very small size of layers, see logs: 
[hip_blas_gfx1035_context_2048_gpu_layers_2.log](https://github.com/ggerganov/llama.cpp/files/13726398/hip_blas_gfx1035_context_2048_gpu_layers_2.log)
[hip_blas_gfx1035_context_2048_gpu_layers_8.log](https://github.com/ggerganov/llama.cpp/files/13726401/hip_blas_gfx1035_context_2048_gpu_layers_8.log)

**Comment by mkesper** [comment]
Sorry, did not find this issue before probably due to other keywords (UMA): https://github.com/ggerganov/llama.cpp/pull/4449

**Comment by ekg** [comment]
#4449 does resolve this

**Comment by mkesper** [comment]
Right, closing in the hope that gets merged soon. :)

**Comment by mambiux** [comment]
I got llama.cpp with ROCm working on a Ryzen 5700u APU and i really liked the results, as it offloads all work to the GPU freeing 15 out of 16 threads so I made a guide in case someone want to try it out, it works really well for only using 25 watts of power.


https://github.com/mambiux/LLAMA.CPP-ROCm
