### ISSUE TITLE
f"Found multiple models in {path}, not sure which to pick: {files}"

### ISSUE THREAD

**Issue by drewskidang** [ggerganov/llama.cpp#4550]
Running latest  version but keep getting this models/Mixtral_Mixtral/model-00001-of-00019.safetensors'

Found multiple models in models/Mixtral_Mixtral, not sure which to pick: [PosixPath('models/Mixtral_Mixtral/model-00001-of-00019.safetensors'), PosixPath('models/Mixtral_Mixtral/model.safetensors')]

**Comment by Azeirah** [comment]
You need to download a GGUF model, not .safetensors. .safetensors models are for running with PyTorch.

llama.cpp has their own model format, called GGUF.

This project has converters scripts to convert various models to GGUF, you can convert the model manually yourself if you want to, but it's easier and probably a lot faster to download a pre-converted one.

Here's mixtral in GGUF format: https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/tree/main

**Comment by drewskidang** [comment]
@Azeirah im trying to convert from safe tensor to gguf

**Comment by Azeirah** [comment]
Are you running the convert.py script? If you run the quantize script you get an error like that. You need the convert script, not the quantize one.

I'm not sure if anything specific is needed to convert mixtral, but probably not.

**Comment by drewskidang** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
