### ISSUE TITLE
Allow the `llama_progress_callback` to abort model loading early without having to throw an exception

### ISSUE THREAD

**Issue by LoganDark** [ggerganov/llama.cpp#4551]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Allow the `llama_progress_callback` to return a value that will stop the model being loaded, and free all resources.

# Motivation

LLMs can brush up against the limits of some computers, and sometimes you just need an emergency stop button. llama.cpp can already catch `std::exception`s inside the model loading process and clean up the half-loaded model, but unfortunately, non-C++ languages (such as Rust) can't throw `std::exception`s, so even if they do unwind, it won't be caught by llama.cpp's try-catch and the resources used by the model won't actually be properly cleaned up.

# Possible Implementation

Allow the `llama_progress_callback` to return a value that aborts model loading early. Maybe have it return a bool where `true` is continue and `false` is abort? This could totally bite existing codebases though since it's really subtle.

**Comment by slaren** [comment]
This seems related: https://github.com/ggerganov/llama.cpp/pull/4462

**Comment by LoganDark** [comment]
> This seems related: #4462

It does indeed! That would solve my problem, I'm pretty sure.

**Comment by LoganDark** [comment]
I tested it and it works, except for an access violation that I've submitted a fix for at #4554 (it comes up when freeing only-partially-initialized models).

**Comment by crasm** [comment]
How are you getting a pointer to a partially initialized model from my PR? It should be returning nullptr if loading is aborted.

**Comment by LoganDark** [comment]
> How are you getting a pointer to a partially initialized model from my PR?

When loading is canceled, the model is freed by llama.cpp (via `delete model`):

https://github.com/ggerganov/llama.cpp/blob/bdfe4ba85c72df7fb521f7222a9dca017177d734/llama.cpp#L9304-L9314

At least one of the tensors have their backend set to `GGML_BACKEND_GPU`, but `ggml_cuda_transform_tensor` has not actually been called on them yet. Look at the location of the `return false` here, in relation to the call to `ggml_cuda_transform_tensor` later:

https://github.com/ggerganov/llama.cpp/blob/bdfe4ba85c72df7fb521f7222a9dca017177d734/llama.cpp#L2346-L2378

This means the tensor is freed (indirectly through `delete model`) in a state where it's destined for the GPU, but hasn't actually been uploaded yet. `ggml_cuda_free_data` should have handled this case already, but it was overlooked, probably because it previously could have only been triggered by spurious `std::exception`s.

There's nothing wrong with your PR, it works as intended.

**Comment by crasm** [comment]
I see. Thank you for catching that!

**Comment by crasm** [comment]
Fixed in #4462
