### ISSUE TITLE
2-bit integer quantization 

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#456]
Add `Q2_0` and `Q2_1` quantization support to `ggml`:

- Follow the existing `Q4_0` and `Q4_1` implementations
- Implement [reference scalar quantization and dequantization routines](https://github.com/ggerganov/llama.cpp/blob/3cd8dde0d1357b7f11bdd25c45d5bf5e97e284a0/ggml.c#L407-L449)
- I suspect we might have to use `QK == 16` in this case to compensate for further accuracy losses
- Add SIMD support for a specific architecture - investigate best strategy to perform the `ggml_vec_dot_q2()` computation
- No need to implement `ggml_vec_mad_q2()` - these will be deprecated soon
- Compute perplexity scores

The expected model sizes for 7B and `QK == 16` are:

- `Q2_0` - 3.2 GB

For `QK == 32` we have:

- `Q2_0` - 2.4 GB
- `Q2_1` - 3.2 GB

Before you send me papers that show 2-bit quantization does not work - no need. I want to have this supported anyway. I have something in mind. The efforts needed to add this support are so small that there is no reason not to do it.

**Comment by dakennedyd** [comment]
No 3-bit support?

**Comment by ggerganov** [comment]
> No 3-bit support?

I don't think I can implement it efficiently, but if anyone wants to give it a try - sure

**Comment by Green-Sky** [comment]
65B using 32gig ram anyone? :laughing:

**Comment by myeolinmalchi** [comment]
Thank you so much for your hard work. How long will it be before this is actually implemented?

**Comment by prusnak** [comment]
I came up with a script that's able to compute RMS for various quantization methods - maybe it will come handy for experimenting: https://gist.github.com/prusnak/f54f8f33503458ca1aa9883f71897072

**Comment by Interpause** [comment]
> Not nearly enough, we need support for 1-bit signed floats.

Swap that out for 1 qubit and now we're talking.

**Comment by prusnak** [comment]
> Not nearly enough, we need support for 1-bit signed floats.

I think the best model size and performance will be achieved when 0-bit quantization is used.

**Comment by Lolagatorade** [comment]
> > Not nearly enough, we need support for 1-bit signed floats.
> 
> 
> 
> I think the best model size and performance will be achieved when 0-bit quantization is used. 

Mhmm possibly -1...

**Comment by pubby** [comment]
I've been testing Q3_0 and found the performance was improved by representing data like this:
```
typedef struct {
    ggml_fp16_t d;
    uint16_t hi; // Highest bit, packed.
    uint32_t lo; // Lowest 2 bits, packed.
} block_q3_0;
```
Basically `lo` is the same format as Q2_0. The remaining bits (the highest ones) get packed into `hi`.  The dot implementation is basically the Q2_0 one, except it uses a lookup table to handle `hi`. Because the code is so similar, improvements to the Q2_0 dot code can be ported over.

Measured times:
```
Q3_0: 71.00 seconds per pass - ETA 12.92 hours
Q2_0: 52.62 seconds per pass - ETA 9.57 hours
Q4_0: 29.60 seconds per pass - ETA 5.39 hours
```

For reference, @sw's original version gives:
```
sw_Q3_0: 96.34 seconds per pass - ETA 17.53 hours
```

I also briefly tested Q3_0 with twice the QK. The code is not working correctly, but the operations are there. The runtime is:
```
46.22 seconds per pass - ETA 8.41 hours
```
I'm wondering if I should keep working on this and make a pull request.

**Comment by ggerganov** [comment]
Thanks to K-quants this is now available

**Comment by MrMage** [comment]
Have there been any new insights into the quality of 2-bit quantization? I.e. does that approach produce reasonable results now?

**Comment by Green-Sky** [comment]
@MrMage pure q2 will never be good, but the k-quants use a mixture with some q2 to archive reasonable results. checkout how `LLAMA_FTYPE_MOSTLY_Q2_K` is composed here https://github.com/ggerganov/llama.cpp/pull/1684

**Comment by neelr** [comment]
https://arxiv.org/abs/2307.13304
