### ISSUE TITLE
Support for conversion of falcon-rw-1b to gguf format

### ISSUE THREAD

**Issue by Govind-S-B** [ggerganov/llama.cpp#4580]
Hey , so I was trying to convert this model `ericzzz/falcon-rw-1b-chat` into gguf format using the convert script in the repo and was having a bunch of KeyErrors with values not available in the [config file](https://huggingface.co/ericzzz/falcon-rw-1b-chat/blob/main/config.json) for the model . I was not sure how to exactly resolve this.
I tried reading into the conversion script and have no idea what will break what and tinkering with it gave me no result.

Read these issues as well regarding support for the falcon-rw-1b models and it seems unresolved still can someone shed light on this I got confused with these chains of referenced issues.

https://github.com/ggerganov/llama.cpp/issues/2868
https://github.com/ggerganov/llama.cpp/pull/2887
https://github.com/ggerganov/llama.cpp/pull/2914

@akawrykow @KerfuffleV2 (Noticed you two guys were having discussions regarding this, sorry in advance if this is unrelated)

**Comment by elepedus** [comment]
Hey, did you ever get this working? I'd love to try out Falcon-rw-1b!

**Comment by Govind-S-B** [comment]
I sadly did not get it working
