### ISSUE TITLE
Mixtral Experts are initialized from Mistral 7b - Low Rank conversion possible?

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#4611]
![image](https://github.com/ggerganov/llama.cpp/assets/66376113/77a44caa-9fa6-4746-b3c0-9772d68661cb)
We have evidence that Mixtral's Experts were initialized from a "common ancestor", the original Mistral 7b.

Conceptually, the idea that might be able to take advantage of this is:
- Extracting the delta of the original Mistral 7b compared to each expert as a PEFT adapter for each expert
- Use SVD to get the closest low rank approximation on each (let's say we target r=128)
- Add the linear Mixtral routing layer to the original Mistral 7b
- At inference time, keep all the LoRA adapters for each expert in memory (approx. ~1.8b added parameters for 128 rank)
- Apply LoRA in real time for each batch of 'expert' calculations per layer using the corresponding expert's LoRA

This could be a viable alternative to [QMoE](https://github.com/ggerganov/llama.cpp/issues/4445) for approaching Mixtral's performance with significantly less memory, given the shared structural similarities.

**Comment by paryska99** [comment]
Really interesting concept. I thought about something similar briefly and I think this could be the way to go for optimizing MoE for consumer hardware. We'll see how this will pan out

**Comment by StefanGliga** [comment]
I did a few quick and dirty experiments, it looks like it might take rank as high as 1600 to keep ~90% of the quality. This means ~22B extra params over base Mistral 7B, for a total of ~30B params.

**Comment by sorasoras** [comment]
> I did a few quick and dirty experiments, it looks like it might take rank as high as 1600 to keep ~90% of the quality. This means ~22B extra params over base Mistral 7B, for a total of ~30B params.

that still much smaller than 8x7B 56B params

**Comment by BadisG** [comment]
@sorasoras Mixtral is actually a 46.8B parameter because the experts are sharing some common layers

**Comment by ggerganov** [comment]
Interesting idea

> Extracting the delta of the original Mistral 7b compared to each expert as a PEFT adapter for each expert

Maybe instead of starting from the original Mistral 7B, we can find a "base" tensor that minimizes some norm of the deltas. This approach would have less assumptions (i.e. that Mixtral has been initialized from Mistral)

> Add the linear Mixtral routing layer to the original Mistral 7b

Again, we can work directly from Mixtral without trying to fit the data to Mistral 7B. Seems cleaner to me

**Comment by kalomaze** [comment]
> Maybe instead of starting from the original Mistral 7B, we can find a "base" tensor that minimizes some norm of the deltas. This approach would have less assumptions (i.e. that Mixtral has been initialized from Mistral)

That could work too, and it might be more flexible for adapting this technique outside of Mixtral specifically for other MoEs.

**Comment by FNsi** [comment]
That's an awesome idea, would be great for mistral 7b x 20 or something similar
