### ISSUE TITLE
Simplify the quantization process

### ISSUE THREAD

**Issue by nullhook** [ggerganov/llama.cpp#463]
The current quantization call stack is long and difficult to debug, which makes extending or adding new quantization methods in the future a major issue. This is because changes would need to be made in various places.

Additionally, we should aim to add drivers that help with benchmarking various quantization methods.

**The current stack:**
1. quantize.py invokes the quantize binary
2. quantize.cpp reads model and logs metrics
3. llama.cpp loads model weights, checks quantization type, and sends to quantization function
4. ggml.c performs the actual quantization

Open to suggestions here and would like to hear if it's worth investing our time and effort

**Comment by anzz1** [comment]
> quantize.py could probably be removed if we manage to make quantize.cpp just a bit more user-friendly.

That is true, quantize.py is an wholly unnecessary step.

> Or make llama.cpp an executable and get rid of quantize.cpp too.
That would be going backwards, the reason for llama.cpp to exist is to have the C API which can be interfaced by 'apps' like main, quantize, perplexity, etc.

ggml is shared with [whisper.cpp](https://github.com/ggerganov/whisper.cpp) so it needs to exist.

when you look at quantize.cpp there is really no logic there, it's just a wrapper for calling the API.
So in reality the amount of steps is 2, llama.cpp (llama api) and ggml.cpp (ggml api) after removing quantize.py.

**Comment by prusnak** [comment]
`quantize.py` is not needed anymore (it was even dropped from the repo), so we already removed one step from the stack
