### ISSUE TITLE
Model does not appear to have a file named config.json

### ISSUE THREAD

**Issue by minh282906** [ggerganov/llama.cpp#4634]
I run normal make in WSL2 Linux/Ubuntu
and download model 7B and 7B-chat in https://ai.meta.com/resources/models-and-libraries/llama-downloads/
already have env in anaconda env and run requirements file to install all the needs
when I run python3 convert.py models/... to convert to ggml FP16 format it return error
"raise EnvironmentError(
OSError: llama/llama-2-7b does not appear to have a file named config.json. Checkout 'https://huggingface.co/llama/llama-2-7b/None' for available files."
how do I fix this issue

**Comment by Denzy7** [comment]
You might need this [config.json](https://huggingface.co/DiscoResearch/mixtral-7b-8expert/blob/main/config.json) in your mixtral-8x7b-32kseqlen folder

**Comment by minh282906** [comment]
> You might need this [config.json](https://huggingface.co/DiscoResearch/mixtral-7b-8expert/blob/main/config.json) in your mixtral-8x7b-32kseqlen folder

Could you please provide further clarification?

**Comment by luopeihai** [comment]
hi, I have the same issue. Someone solved it



<img width="1392" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/9778410/8800f2b1-ea42-4c8d-a1cf-78200e335f5c">

**Comment by minh282906** [comment]
> hi, I have the same issue. Someone solved it
> 
> <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/9778410/293062922-8800f2b1-ea42-4c8d-a1cf-78200e335f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTMzNDEsIm5iZiI6MTcwMzY5MzA0MSwicGF0aCI6Ii85Nzc4NDEwLzI5MzA2MjkyMi04ODAwZjJiMS1lYTQyLTRjOGQtYTFjZi03ODIwMGUzMzVmNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMTYwNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M5OTJmZDAyMjZmMTU0NGMwYWI5OTJiMmJkMDBmNjM4NjRhNTVhZWE2ODJlYjMyOTUwMWYyNTAzOTY5ZTAyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JYBNNu34dGP_PYAh-3susZ5HGi7rWVaqjg-SjCCuh3s">

wow thank you very much

**Comment by minh282906** [comment]
> hi, I have the same issue. Someone solved it
> 
> <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/9778410/293062922-8800f2b1-ea42-4c8d-a1cf-78200e335f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTMzNDEsIm5iZiI6MTcwMzY5MzA0MSwicGF0aCI6Ii85Nzc4NDEwLzI5MzA2MjkyMi04ODAwZjJiMS1lYTQyLTRjOGQtYTFjZi03ODIwMGUzMzVmNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMTYwNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M5OTJmZDAyMjZmMTU0NGMwYWI5OTJiMmJkMDBmNjM4NjRhNTVhZWE2ODJlYjMyOTUwMWYyNTAzOTY5ZTAyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JYBNNu34dGP_PYAh-3susZ5HGi7rWVaqjg-SjCCuh3s">

where is the 7B folder in models folder

**Comment by wailu** [comment]
@minh282906 it seems you first have to convert the llama weights to hf (see: https://huggingface.co/docs/transformers/model_doc/llama2#usage-tips)

![Screenshot 2023-12-28 at 3 44 39 PM](https://github.com/ggerganov/llama.cpp/assets/42461097/885bdf45-b897-4fce-b654-b5fa8bb1c2aa)

**Comment by minh282906** [comment]
@wailu 

A few weeks ago, I ran it normally, I didn't need to convert to hf. But now I am encountering this error, so that's why I find it really strange.

**Comment by sergiocardoso** [comment]
same to me :(

**Comment by minh282906** [comment]
@sergiocardoso 
why did this happen :((

**Comment by dpaksahoo** [comment]
I'm also facing the same issue, any fixes @minh282906 ?

**Comment by minh282906** [comment]
@dpaksahoo 
No, I don't

**Comment by sergiocardoso** [comment]
Sorry for my english. 
A solution that I found was checkout to this branch
```git checkout 0353a1840134b24b07ab61fd4490192f28c4db6b```

https://github.com/ggerganov/llama.cpp/issues/4493#issuecomment-1860492965

**Comment by minh282906** [comment]
@sergiocardoso 

Thank you very much

**Comment by dpaksahoo** [comment]
@sergiocardoso thank you, this worked for me 💯
