### ISSUE TITLE
Segmentation fault (core dumped) if run phi-2 model with clblast

### ISSUE THREAD

**Issue by qubicllj** [ggerganov/llama.cpp#4650]
My system

- Device: Thinkpad E490
- OS: Ubuntu 22.04.3 LTS
- GPU: Radeon RX 550X
- build with clblast

reproduce the bug

1. build with clblast.
2. run phi-2 model and specify ngl parameter.

This bug has appeared since the commit [d232aca](https://github.com/ggerganov/llama.cpp/commit/d232aca5a73b290e218a2e48b91023d5e994203f)

**Comment by waclawthedev** [comment]
I have this issue too.

My system
Device: Pixel 4XL
OS: Android 13

How to reproduce the bug
1. Build with clblast using Termux.
2. Run phi-2 model and specify ngl parameter.

**Comment by Ar57m** [comment]
I got this at first and then segmentation fault:
bionic/libc/bionic/bionic_allocator.cpp:118: alloc CHECK 'page->free_block_list != nullptr' failed

**Comment by Slider2k** [comment]
Can confirm having an issue with Phi-2 on cblast. For me it just spams '!' as the response to anything.

[main.log](https://github.com/ggerganov/llama.cpp/files/13923017/main.log)

**Comment by nps798** [comment]
@Slider2k  mine as well, right after "llama_new_context_with_model" i got segmentation fault (core dumped) with a model of small size that I am sure my system RAM can handle.

**Comment by Slider2k** [comment]
I no longer have the issue.

**Comment by slaren** [comment]
Fixed in #5151
