### ISSUE TITLE
Please add GGUF to pth conversion.

### ISSUE THREAD

**Issue by Pavelzelen** [ggerganov/llama.cpp#4652]
I would like to modify llama-2-7b using inference.py but I don't understand how to attach llama.cpp to inference.py so that it works as it was originally intended.
1. It’s at least strange that we convert pth to GGUF, but there is no way to do the reverse conversion.
2. I tried to use the old version of llama.cpp convert-ggml-to-pth.py To do the convection pth --> GGML --> quantize --> pth. But at the stage pth --> GGML received an error: TypeError: Got unsupported ScalarType BFloat16.

Maybe you can help me. I think the easiest way is reverse conversion.

**Comment by sorasoras** [comment]
+1
