### ISSUE TITLE
[Question] How can i quantize converted lora adaptor (ggml) as q4?  

### ISSUE THREAD

**Issue by allzero-kwon** [ggerganov/llama.cpp#4661]
Hi. Currently, Im traying to quantize lora model using llama.cpp.

- Original Model : Base model + lora adaptor 

I converted base model and lora adaptor to gguf/ggml bin using convert.py and convert-lora-to-ggml.py
And i quantized base model as q4_0 with quantize.

In this case, how can i inference this quantized q4_0 model with converted ggml lora adaptor?
How can i quantize the ggml lora adaptor?

**Comment by dgo2dance** [comment]
+1

**Comment by joaopedrosdmm** [comment]
Did you find any solution?
