### ISSUE TITLE
Phi-2 produces garbage output with amd hip

### ISSUE THREAD

**Issue by kurnevsky** [ggerganov/llama.cpp#4662]
Just tried to use [Phi-2 q8](https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF/blob/main/dolphin-2_6-phi-2.Q8_0.gguf) with hip on the latest master - it produces garbage, but on CPU it works fine.

The exact command I use is `llama -t 24 -ngl 33 -m dolphin-2_6-phi-2.Q8_0.gguf --color -c 0 --chatml --prompt 'You are Dolphin, a helpful AI assistant.'`

**Comment by ggerganov** [comment]
This should be fixed on latest `master`

**Comment by kurnevsky** [comment]
Nope, still garbage.
