### ISSUE TITLE
Allow concurrent requests on the llama.cpp server.

### ISSUE THREAD

**Issue by RonanKMcGovern** [ggerganov/llama.cpp#4666]
I see there is a parallel example that works, but doesn't allow for a port to be exposed (or host).

Could someone give me quick guidance and I can try to make a PR to the server that will allow for concurrent requests?

**Comment by the-crypt-keeper** [comment]
This is already supported today by [server example](https://github.com/ggerganov/llama.cpp/tree/master/examples/server)

```
-np N, --parallel N: Set the number of slots for process requests (default: 1)
-cb, --cont-batching: enable continuous batching (a.k.a dynamic batching) (default: disabled)
```

**Comment by RonanKMcGovern** [comment]
@the-crypt-keeper even better, many thanks
