### ISSUE TITLE
How do I properly terminate it in interactive mode to save the prompt cache on exit?

### ISSUE THREAD

**Issue by takosalad** [ggerganov/llama.cpp#4677]
I use it in interactive mode with "--prompt-cache coolstatefile" so the session is persistent when I have to reboot the PC or anything. So noticed just exiting with CTRL+C  doesnt save the prompt cache properly: Next startup it forgot what I just told it before shutdown.
So how do I properly terminate the bot so it does a correct prompt-caching and on next restart I can continue the discussion where I left off?

**Comment by joseiriarte1982** [comment]
How about instructing to ignore or not pay attention to a instruction closing comment, that way you make and extra comment,  and you know that everything before you closing comment is saved. A small workaround for the meantime
