### ISSUE TITLE
Using custom prompt template in server

### ISSUE THREAD

**Issue by peturparkur** [ggerganov/llama.cpp#4683]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Adding custom prompt template handling for `examples/server/server.cpp`
Mainly for handling multi-turn conversation via the OpenAI compatible API.

The prompt-template should be declarative or use a file (json, yaml?).

# Motivation

The current server implementation only support ChatML prompt-template or no template for completion.
Since most templates are model specific, a template could be loaded along with the model during the server start-up to handle the prompt formatting for the `chat/completions` endpoint.

This would allow easily using multiple models with varying prompt templates.

Note, this should only affect the server example.

# Possible Implementation
Idea for file handled prompt templating.
We can define a prompt template as follows.

Example for `ChatML` template
```json
{
    "user": {
        "prefix": "<|im_start|>user\n",
        "suffix": "<|im_end|>"
    },
    "assistant": {
        "prefix": "<|im_start|>assistant\n",
        "suffix": "<|im_end|>"
    },
    "system": {
        "prefix": "<|im_start|>system\n",
        "suffix": "<|im_end|>"
    },
    "delimiter": "\n"
}
```

Example for `Zephyr` template
```json
{
    {
    "user": {
        "prefix": "<|user|>\n",
        "suffix": "</s>"
    },
    "assistant": {
        "prefix": "<|assistant|>\n",
        "suffix": "</s>"
    },
    "system": {
        "prefix": "<|system|>\n",
        "suffix": "</s>"
    },
    "delimiter": "\n"
}
```

- Where user, assistant, and system (function?) would be the lookup for the role of the message.
- The prefix and suffix would would be applied locally on each message.
- The delimiter is used between messages

Then we can load the above defined json as parameter during model or server start-up.

**Comment by stolsvik** [comment]
AFAIU, this is already present in the '`tokenizer.chat_template`' variable availble in the GGUF-file. You can see it when the model boots up, from the "llama_model_loader" log lines.

It is described here: https://huggingface.co/docs/transformers/chat_templating

I would very much love if the server's chat interface could apply this.
