### ISSUE TITLE
Strange phenomena during model output

### ISSUE THREAD

**Issue by hell99dkx** [ggerganov/llama.cpp#4686]
![微信截图_20231229223104](https://github.com/ggerganov/llama.cpp/assets/132538402/0a114896-cee5-4fdf-a395-883efc63cd17)
![微信截图_20231229223050](https://github.com/ggerganov/llama.cpp/assets/132538402/3f688dca-e36f-46e9-b258-682a88d36d7d)

When I used llama before, the output was normal, but after a few days, I didn't know what happened and my model output became like this (as shown in the figure)

I initially thought it was a coding issue with the cmd command window. I tried encoding methods such as utf-8 and gbk, and changed several models, but the output remained the same.

I hope someone can give me some useful advice. thanks

I am a Windows 10 system

This is the command I used to call the model: main - m E:/GAME/openchat-3.5-1210.Q5_ K_ M. Gguf ngl 26- t 10- n 512- c 2048- i -- color - r "User:" -- temp 0.78- f E: \ Tomcat \ students \ QM \ chat.txt - cml

**Comment by phiharri** [comment]
These are debug logs that would typically be routed to .log files rather than the console. You can check the `--log` options in the usage help for how to configure logging:
```
$ ./main --help
[..]

log options:
  --log-test            Run simple logging test
  --log-disable         Disable trace logs
  --log-enable          Enable trace logs
  --log-file            Specify a log filename (without extension)
  --log-new             Create a separate new log file on start. Each log file will have unique name: "<name>.<ID>.log"
  --log-append          Don't truncate the old log file.
```

Simply adding `--log-disable` to your command should prevent those logs from being displayed.

**Comment by hell99dkx** [comment]
Your suggestion did work, but in the initial use, the command window would not output this much information. I want it to output appropriate information like it did at the beginning. What should I do?
