### ISSUE TITLE
mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf

### ISSUE THREAD

**Issue by erlebach** [ggerganov/llama.cpp#4689]
Has anybody run `mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf` on a mac Pro M2? My mac has 96GB Ram. When I run with Llama_cpp, I get the error: 
```
(langchain-monorepo-py3.10) (base) ➜  zephyr_experiments git:(main) ✗ python chat_gpu.py
Traceback (most recent call last):
  File "/Users/erlebach/src/2023/langchain_ecosystem/langchain_gordon_experiments/zephyr_experiments/chat_gpu.py", line 49, in <module>
    llmA = myLlamaCpp(modelA)
  File "/Users/erlebach/src/2023/langchain_ecosystem/langchain_gordon_experiments/zephyr_experiments/chat_gpu.py", line 34, in myLlamaCpp
    llm = LlamaCpp(
  File "/Users/erlebach/src/2023/langchain_ecosystem/langchain_gordon_experiments/.venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/erlebach/src/2023/langchain_ecosystem/langchain_gordon_experiments/.venv/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /Users/erlebach/data/llm_models/mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf. Received error  (type=value_error)
  ```
 If I use `"mistral-7b-instruct-v0.1.Q3_K_M.gguf", there is no issue: the model runs fine. Only the model name changes. Here is my call to `LlamaCpp`:
 ```
 
 callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
n_gpu_layers  = 20
llm_batch  = 128 
 def myLlamaCpp(model):
    llm = LlamaCpp(
        model_path=model,
        n_gpu_layers=n_gpu_layers,
        n_ctx=2048,
        stop=[],
        max_tokens=1000,
        n_threads=8,
        temperature=0.4,  # also works with 0.0 (0.01 is safer)
        f16_kv=True,
        n_batch=n_batch,
        callback_manager=callback_manager,
        verbose=False,
    )
    ```
    Any insight would be appreciated. 
    
    Thanks! 
    
    Happy New Year to all!
    
        Gordon

**Comment by dspasyuk** [comment]
Try running  C code directly or using this https://github.com/dspasyuk/llama.cui 
../llama.cpp/main --model ..\..\models\mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf --n-gpu-layers 5 --keep -1 -ins  --simple-io  -b 1024 --ctx_size 1024 --temp 0.3 --top_k 10 --multiline-input  --repeat_penalty 1.15 -t 8 --log-disable  --no-penalize-nl

**Comment by jrichey98** [comment]
It's saying it can't load the model. Permissions Maybe? I've had that error in a multi-user scenario. Try:
`chmod 664 /Users/erlebach/data/llm_models/mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf`

I always just use ~ on linux for my home directory. Maybe do a `ls ~/data/llm_models/mixtral-fusion-4x7b-instruct-v0.1.Q4_K_M.gguf` and make sure you see a file, then use that as the path in the future.

If there are multiple users and you're trying to load the model from another users folder, there's a good chance you won't have permissions. Create a service account called llamacpp then `su - llamacpp` to it, and clone it in the /opt folder then make. Then put your models in an /opt/llama.cpp/models folder. Make sure to change ownership (chown) and sort out permissions (chmod) for any old models copied into the new models folder.

Side note: Unless I clone the repo for FP16 models, I always just use wget to fetch my quantized models from github into my llama.cpp models directory. For some reason on this last update, a clean/pull/make didn't work for me. I had to re-clone the repo to get mixtral to work. Anyway, getting 15.5 t/s on a 5950X w/3090 24GB with: `./server -m ./models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -c 8192 -t 6 -ngl 28`

**Comment by ronitagarwala01** [comment]
I had a similar issue while running mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf on colab. I got it to work by reducing n_gpu_layers to 16.
