### ISSUE TITLE
Can llama.cpp handle image output? e.g. llava-interactive

### ISSUE THREAD

**Issue by husnoo** [ggerganov/llama.cpp#4708]
Hi,

I'm trying to get a llm to point at the area on an image where the best guess for masking something it may never have specifically seen before. E.g. pick out the red block in a group of coloured blocks. I'm looking for the position of the object as a mask - I've tried Llava-1.5 with text ("express it as xmin,ymin,xmax,ymax") and this only works occasionally. I think llava-interactive may be more suitable for this?

thanks,

Nawal

**Comment by cmp-nct** [comment]
For the actual x/y coordinates you'd need a finetune that is trained for it.
For generation the only project I know ist https://github.com/leejet/stable-diffusion.cpp I've not tested it.
Of course it has no connection to what the visual encoder actually saw, for that you'd need an own training project (for example to project it into an IP-adapter or something like that)
