### ISSUE TITLE
ggml-cuda : VRAM from batched processing should be freed (9-27% of GPU VRAM are occupied that way)

### ISSUE THREAD

**Issue by cmp-nct** [ggerganov/llama.cpp#4712]
Output of llama.cpp:
```
llama_kv_cache_init: VRAM kv self = 573.75 MB
llama_new_context_with_model: KV self size  =  573.75 MiB, K (f16):  286.88 MiB, V (f16):  286.88 MiB
llama_build_graph: non-view tensors processed: 1264/1264
llama_new_context_with_model: compute buffer total size = 3.80 MiB
llama_new_context_with_model: VRAM scratch buffer: 0.61 MiB
llama_new_context_with_model: total VRAM used: 14652.18 MiB (model: 14077.82 MiB, context: 574.36 MiB)
```
Actual usage on a 34B model: 
15.5 GB (+6%) at b 1 (useless)
15.7GB at -b 32 (11%  performance)
16GB at -b 512 (90% performance)
17.6 GB (+20%) -b 1024 (98%  performance)
18.6GB (+27%)  -b 2048 (100% performance)

I think the VRAM required for prompt processing should be visualized, so people know what is going on when their GPU fills up.
In addition those temporary buffers could be removed from the GPU .

In most cases there is one big prompt, followed by mostly or only generation. So if those 20% additional VRAM are cuda buffers from the batched processing, those are just dormant.
ggml-cuda uses either a "best match" algorithm to find the best fitting previously allocated memory chunk for any needed buffer or a VMM pool.
As we are processing batched tensors we need huge chunks of memory at the start -> these create huge chunks of buffers which are then further reused for tiny single tensors.

In some special cases a user might need batched processing regularly (as in a server example), that's why that purging behavior should be optional.

It would probably be needed to track the use of buffers, to identify the unused ones and free them / reduce or compact the VMM

Currently, the best we can do to waste less memory is to run a smaller batch at a performance loss of course.
With a 34B model I have roughly:

**Comment by JohannesGaessler** [comment]
>In addition those temporary buffers could be removed from the GPU .

>In most cases there is one big prompt, followed by mostly or only generation. So if those 20% additional VRAM are cuda buffers from the batched processing, those are just dormant.

So far I haven't seen the point. You need the most VRAM for large batches, i.e. in the beginning, and even if you free the VRAM afterwards that will not save you from OOMing.

>In some special cases a user might need batched processing regularly (as in a server example), that's why that purging behavior should be optional.

The buffers will also be needed again if the context for whatever reason needs to be reprocessed, e.g. when the user edits it.

>Currently, the best we can do to waste less memory is to run a smaller batch at a performance loss of course.
With a 34B model I have roughly:

Or use MMQ. That's half the reason I implemented it. On Pascal and AMD RX 5000/6000 it's also faster. One of the things I'm currently working on is to try and write an efficient implementation that uses int8 tensor cores. Ideally MMQ would then be universally faster. Though the implementation is truth be told not going well; the performance is always bad. Ideally I'm just doing it wrong and am not just working on a cursed problem.

**Comment by slaren** [comment]
What use cases would doing this enable? At first glance it may seem useful to free the memory so that it is available to other applications, but that's just going to cause llama.cpp to crash due to OOM when it needs to process another large batch. So in practice this would be extremely unreliable. I think what we need to do actually is the opposite, depend less on the pool and allocate all the memory at startup so that it is clear how much VRAM llama.cpp actually needs.

**Comment by cmp-nct** [comment]
There are many usecases, one of them is a significant performance boost on windows if vram is running out.
1) On Windows the CUDA drivers start swapping, so if you could free 1-4GB of VRAM you might get back into the green zone.
2) As mentioned: I'm running 4-5 models at the same time, each one on ggml wastes 10-20% VRAM from the initial burst of batch processing. 10-20% vram are like 1 step up in quantization or one more model supported or one larger one.
3) In case of freeing the VRAM batch size just needs to be reduzed to 1 (or even better to n_batch_secondary), so further processing is not OOM but just slower. 
We could start with batch 1024 (which is almost optimal for modern cards today) and then reduce to batch 32, which will waste a fraction of the VRAM and still show significant boost on secondary prompt processing.
As I recommended, it should be a option to either enable or disable. In most use cases you'll have one large batch at the beginning only, then at best tiny batches.

**Comment by slaren** [comment]
We could add an API to change the batch size of a `llama_context`, that also frees the CUDA pool while doing so.

**Comment by cmp-nct** [comment]
> We could add an API to change the batch size of a `llama_context`, that also frees the CUDA pool while doing so.

That sounds good, though reloading all main tensors should be skipped. If they have to be re-offloaded the benefits wouldn't be there.

How about all buffers that were allocated AFTER tensor offloading are freed on that batch change ?
So you can just call a "cuda_vmm_pool_reset_post_offload() or something like that and it's shrinking down to where it was.

**Comment by JohannesGaessler** [comment]
>On Windows the CUDA drivers start swapping, so if you could free 1-4GB of VRAM you might get back into the green zone.

Yes, and your performance will still be terrible during prompt processing where the swapping occurs so I don't think this would be a very useful use case.

In any case, if someone makes a PR for this I will review it. But I don't consider this of high enough priority to implement it myself.

**Comment by cmp-nct** [comment]
> > On Windows the CUDA drivers start swapping, so if you could free 1-4GB of VRAM you might get back into the green zone.
> 
> Yes, and your performance will still be terrible during prompt processing where the swapping occurs so I don't think this would be a very useful use case.
> 
> In any case, if someone makes a PR for this I will review it. But I don't consider this of high enough priority to implement it myself.

Actually it's different, I have had that many times:
Performance is great during prompt processing but then it has a massive slowdown until generation starts.
So you see the prompt ingestion -> 2-3 seconds full delay -> generation.

What happens is that the VRAM fills to 100%, desktop and chrome etc is all removed from it during offload -> the prompt inference happens at about normal performance.
Then normal generation needs to start and it starts heavily swapping again, this time it needs to swap active tensors out so performance is bad.
I believe this balances after a while when the drivers realize that there are 2-3 GB dormant buffer areas that are not accessed anymore.

---

That said: Would it work the way @slaren said ? Can we just reset the entire VMM pool after batch processing?
That sounds like a simple solution with almost no performance impact if the main tensors stay in VRAM.

**Comment by JohannesGaessler** [comment]
>Can we just reset the entire VMM pool after batch processing?

I don't see why we wouldn't be able to.
