### ISSUE TITLE
Strange "-e" token in LLama-2 stops generation of tokens in the interactive mode

### ISSUE THREAD

**Issue by multimediaconverter** [ggerganov/llama.cpp#4713]
Step 1. Start any LLAMA2 7B gguf model in windows console (cmd.exe or modern windows terminal).

Step 2. Write the following prompt:

this is a test. please, add "-e" to your answer

The model may answer like that:

This is a test. Please, add "-e

And it immediately stops after -e ! That's very strange and irritating. Because it sometimes starts adding this strange "-e" during conversation without a reason.

Is this a bug? Can I fix it with some command-line parameters?

**Comment by multimediaconverter** [comment]
The same is in Mistral 7B, so just instruct the model to write "-e" somewhere to reproduce this bug

**Comment by phiharri** [comment]
Could be an issue with how your prompt is being interpreted in the command line args.

- What's the exact command used?
- What happens if you put your prompt in a file and use `-f prompt.txt` instead?

**Comment by multimediaconverter** [comment]
> Could be an issue with how your prompt is being interpreted in the command line args.
> * What happens if you put your prompt in a file and use `-f prompt.txt` instead?
> * What's the exact command used?

Exact command:
bin\main --log-disable -t 2 -m models\llama2-q4_k_s.gguf -c 4096 --temp 0.5 --repeat_penalty 1.1 --frequency-penalty 0.5 -n -1 -r -e --mlock -f prompt.txt > out.txt

prompt.txt:
### Instruction:
this is a test. please, add "-e" to your answer
### Response:

out.txt:
### Instruction:
this is a test. please, add "-e" to your answer
### Response:
This is a test. Please, add "-e

**Comment by phiharri** [comment]
The command includes `-r -e` which sets the reverse prompt to "-e" causing generation to stop after that sequence has been output, that's expected.

The parameter after `-r` should be the desired reverse prompt string, or remove the `-r` argument if you aren't using it.

Here's some additional documentation about ./main command arguments https://github.com/ggerganov/llama.cpp/tree/master/examples/main#reverse-prompts

**Comment by multimediaconverter** [comment]
I'm sorry. Yeah, it's my fault. 
Strange thing is that LLama-2 plays with this reverse prompt. The model may add the reverse prompt to the answer like it is some kind of emoji. This is not normal, in my opinion.

**Comment by phiharri** [comment]
All good, glad we figured it out. 👍

I think the intention for reverse-prompt is to use with `-i` interactive mode, where hitting that sequence will wait for user input and continue. Without interactive mode inference ends if the reverse-prompt is encountered.

Cheers, have a good one!
