### ISSUE TITLE
Per-layer KV not working for models fully-offloaded across multiple GPUs

### ISSUE THREAD

**Issue by candre23** [ggerganov/llama.cpp#4727]
KV cache is not being divided up per-layer when a model is both fully-offloaded and split across multiple GPUs.  To prove this, I first loaded a 13b model split across two P40 GPUs with 4k context and observed VRAM usage.  Then I re-loaded the same model with 8k context.  Comparing VRAM for both instances, usage only increased on GPU0.  If context was being split per-layer, then usage should have increased evenly across both GPUs.

Full .bat for the 8k test.  4k was identical, except for the context arg.

```
set CUDA_VISIBLE_DEVICES=0,1
main.exe -m tiefighter.gguf -n -1 -c 8192 -ngl 99 --color -r "User:" --in-prefix " " -i -e -p "User: Hi\nAI: Hello. I am an AI chatbot. Would you like to talk?\nUser: Sure!\nAI: What would you like to talk about?\nUser:"
```

Windows 10 pro machine with three P40 GPUs.  LlamaCPP b1742 with cuda 12.2 DLLs.
![8k](https://github.com/ggerganov/llama.cpp/assets/36796363/cf3046c9-822f-46cf-a9e7-993f48c17a0f)
![4k](https://github.com/ggerganov/llama.cpp/assets/36796363/82b973e2-22d5-4999-b67a-68bc6954c417)

**Comment by JohannesGaessler** [comment]
Not a bug. Splitting the KV cache across multiple GPUs is not implemented.
