### ISSUE TITLE
Add a command line capability to convert text to embedding vector

### ISSUE THREAD

**Issue by richardanaya** [ggerganov/llama.cpp#4745]
# Feature Description

CLI should have a command line option for exporting embedding vectors of a given prompt.

# Motivation

Useful for building vector databases

# Possible Implementation

Not familiar enough with CLI conventions to know what's right.  The output should be piped output (not saved to file) using some standard vector text format.

**Comment by phiharri** [comment]
Have a look at [examples/embedding](https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding) which returns space-delimited floats to stdout.

**Comment by richardanaya** [comment]
Thank you so much!
