### ISSUE TITLE
unknown format error while trying to convert opp

### ISSUE THREAD

**Issue by jnpushkar1507** [ggerganov/llama.cpp#4753]
Hi Team i am facing the following issue while trying to convert openLlama model.
![image](https://github.com/ggerganov/llama.cpp/assets/70328505/84156a97-47d5-4b42-8c15-39099c95e27b)

**Comment by cody-greene** [comment]
Make sure you checkout or pull the lfs files from the open_llama repository. Install git-lfs and run `git lfs pull`
