### ISSUE TITLE
implement sparsity prediction to significantly reduce memory footprint

### ISSUE THREAD

**Issue by dmahurin** [ggerganov/llama.cpp#4759]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Use the methods found in "LLM in a flash"
to significantly reduce the memory footprint, by only loading based on sparsity prediction.

# Motivation

From the paper:

"LLM in a flash"
https://arxiv.org/pdf/2312.11514.pdf

"Together, windowing and sparsity prediction allow us to load only 2% of the FFN layer from flash for each inference query"

"We have demonstrated the ability to run LLMs up to twice the size of available DRAM, achieving an acceleration in inference speed by 4-5x compared to traditional loading methods in CPU, and 20-25x in GPU."

While this is perhaps related to PowerInfer discussions (https://github.com/ggerganov/llama.cpp/discussions/4534), and the paper is mentioned in the comments,
the point here is memory footprint and not necessarily speed.

If an implementation of this can allow loading LLMs of twice the available DRAM, that is significant.
Significant for MoE like Mixtral, and significant in general.
Imagine 4 bit Llama 70B and Mixtral 8x7B  easily fitting in 24gig memory.

Possibly Related:
"Fast Inference of Mixture-of-Experts Language Models with Offloading"
https://arxiv.org/pdf/2312.17238.pdf

**Comment by sorasoras** [comment]
That could be implement easier than the way PowerInfer  required. by better utilized  fast SSD  use by Modern PC like Macbooks or PCIE4 SSD on PC to reduce VRAM usage. I think this is a good idea but I think it does have level of hardware requirement.

**Comment by JohannesGaessler** [comment]
I don't see the point. If you look at their results for Falcon 7b they report 1.5 t/s for token generation on CPU and 10 t/s for token generation on an RTX 4090. RAM is so cheap nowadays that I can't imagine anyone would rather suffer these speeds than buy more RAM. And for CUDA in general I am very skeptical of any method that proposes dynamically loading data into VRAM for small batches without also demonstrating that it works at a competitive performance level (at low performance levels you are much less bottlenecked by RAM/PCIe bandwidth and synchronization overhead).

**Comment by cmp-nct** [comment]
Given that there is a full llama.cpp fork that supports PowerInfer .. that's already working!
So IF predictor support is added, then that's the one.

I also think we have many other methods to increase performance, when looking at competition they run up to 14000tk/sec prompt processing on a 7B model. We are at ~5000. So that's almost 3 times the speed just by optimizing the kernel inference.
That would be something that benefits most users. Running from SSD with a predictor has no real use case at the moment.

After all development time is the actual limited resource
