### ISSUE TITLE
Unable to convert bloom models

### ISSUE THREAD

**Issue by JerryKwan** [ggerganov/llama.cpp#4768]
When trying to convert bloom model downloaded from Huggingface (https://huggingface.co/bigscience/bloomz-1b7) using the following command
```shell
python3.10 convert.py /root/bloomz-1b7/
```
it outputs the following messages
```
Loading model file /root/bloomz-1b7/model.safetensors
Traceback (most recent call last):
  File "/root/workspace/llama.cpp/convert.py", line 1295, in <module>
    main()
  File "/root/workspace/llama.cpp/convert.py", line 1234, in main
    params = Params.load(model_plus)
  File "/root/workspace/llama.cpp/convert.py", line 318, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
  File "/root/workspace/llama.cpp/convert.py", line 237, in loadHFTransformerJson
    raise Exception("failed to guess 'n_ctx'. This model is unknown or unsupported.\n"
Exception: failed to guess 'n_ctx'. This model is unknown or unsupported.
Suggestion: provide 'config.json' of the model in the same directory containing model files.
```
And config.json is in the same directory containing the model file
Any one knows what caused the problem and how to solve it?

**Comment by JerryKwan** [comment]
And when using bloomz.cpp(https://github.com/NouamaneTazi/bloomz.cpp) to convert the model using the following command succeed
```
python3.10 convert-hf-to-ggml.py /root/bloomz-1b7/ ./models
```

**Comment by ggerganov** [comment]
Looks related to https://github.com/ggerganov/llama.cpp/issues/4493

**Comment by JerryKwan** [comment]
@ggerganov Thanks for looking into this issue. Any ETA about when the problem will be solved?
There are a large number of users are using bloom-like model.
And anything I can help to solve the problem?

**Comment by ggerganov** [comment]
@teleprint-me [mentioned that they will take a look](https://github.com/ggerganov/llama.cpp/issues/4493#issuecomment-1868814872), but not sure if they had the chance yet. I prefer to rely on the community's help for the Python issues as it is not my field of expertise, but I will take a look if it does not get resolved soon

**Comment by JerryKwan** [comment]
@ggerganov 
Seems like I can use the following command to convert bloomz-1b7 successfully (commit f3f62f0d835d559e80714bbeb05d03125574e3dd ), 
```
python3.10 ./convert-hf-to-gguf.py /root/bloomz-1b7/ 
 ```
 And using the following command to load the model successfully
 ```
 ./main -m /root/bloomz-1b7/ggml-model-f16.gguf -n 128
 ```
 So, there must be something wrong with convert.py and should not cost too much time to solve. I will digger deeper later

**Comment by JerryKwan** [comment]
But failed to convert bloomz-7b1-mt
```
Loading model: bloomz-7b1-mt
gguf: This GGUF file is for Little Endian only
Set model parameters
Set model tokenizer
gguf: Adding 250434 merge(s).
gguf: Setting special token type bos to 1
gguf: Setting special token type eos to 2
gguf: Setting special token type unk to 0
gguf: Setting special token type pad to 3
Exporting model to 'bloomz-7b1-mt/ggml-model-f16.gguf'
gguf: loading model part 'pytorch_model.bin'
Traceback (most recent call last):
  File "/root/workspace/llama.cpp/./convert-hf-to-gguf.py", line 1246, in <module>
    main()
  File "/root/workspace/llama.cpp/./convert-hf-to-gguf.py", line 1240, in main
    model_instance.write()
  File "/root/workspace/llama.cpp/./convert-hf-to-gguf.py", line 136, in write
    self.write_tensors()
  File "/root/workspace/llama.cpp/./convert-hf-to-gguf.py", line 362, in write_tensors
    tensors = dict(self.get_tensors())
  File "/root/workspace/llama.cpp/./convert-hf-to-gguf.py", line 62, in get_tensors
    ctx = contextlib.nullcontext(torch.load(str(self.dir_model / part_name), map_location="cpu", mmap=True, weights_only=True))
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by Galunid** [comment]
Was `bloom` ever supported by `convert.py` in the first place? I believe that one was meant for `llama` models (and some derivatives). Bloom used to have a separate script `convert-bloom-hf-to-gguf.py` (or something similar) that was then refactored into `convert-hf-to-gguf.py`. 

`Exception: failed to guess 'n_ctx'. This model is unknown or unsupported.` suggests it wasn't.

**Comment by JerryKwan** [comment]
@player1537 Thanks for lending help. I can convert the model successfully, thank you

@Galunid I am not sure if bloom was supported by convert.py in the first place, but I think it would be better to use convert.py as the main convert tool, and it can use the functions defined in other modules

**Comment by Galunid** [comment]
That's not possible for now, perhaps in the future the scripts will be unified.

**Comment by teleprint-me** [comment]
Sorry I'm late to party. I've been sick. Just starting to feel functional compared to the last few days. 

@Galunid is right for the most part. My 2 cents for clarity is that `convert.py` only handles the **llama** and **gpt** architectures. The `convert-hf-to-ggml.py` superseded the separate scripts that previously existed. 

The main difference between them is `convert.py` uses a custom shim to save on memory usage and loads the tensors as they're needed. `convert-hf-to-ggml.py` consumes more memory as a result.

There are other contributors that are more knowledgeable about it's functionality than I. I've been slowly picking it apart though.

My advice would be to use the intended script which is the now homogenized `convert-hf-to-ggml.py` script. It's not so simple to merge the scripts which I found as began to dig deeper into the `torch` code base.
