### ISSUE TITLE
OpenAI incompatible image handling in server multimodal

### ISSUE THREAD

**Issue by gelim** [ggerganov/llama.cpp#4771]
Hello while testing Llava-13B with server implementation I got a 500 error related to the `content` being a list of dicts and not a simple string.

- what works (but unrelated to Llava):

``` bash
$ curl -H "Content-Type: application/json" -X POST -s $SERVER/v1/chat/completions -d '{"messages": [{"role": "user", "content": "hello"}]}'
```

`{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there! How can I help you today?","role":"assistant"}}],[...]`

- what yields a 500 with `[json.exception.type_error.302] type must be string, but is array`:

``` bash
$ curl -H "Content-Type: application/json" -X POST -s $SERVER/v1/chat/completions -d '{"messages": [{"role": "user", "content": [{"type":"text","text":"hello"}]}]}'
```

this is to demonstrate the issue when using an OpenAI REST aware frontend that is pushing text with pic inside the `content` key like this:

``` json
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "describe the picture"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "data:image/webp;base64,AAAAAA==",
            "detail": "auto"
          }
        }
      ]
    }
  ],
  "model": "llava-13b",
  "frequency_penalty": 0,
  "max_tokens": 4000,
  "presence_penalty": 0,
  "temperature": 0.1,
  "top_p": 1,
  "user": "foobar"
}
```

**Comment by gelim** [comment]
If I understand correctly, that is more of a feature that is not implemented within server.cpp than a bug in itself.

Here is the OpenAI API documentation for reference: https://platform.openai.com/docs/api-reference/chat/create
<img width="611" alt="Screenshot 2024-01-04 at 14 13 55" src="https://github.com/ggerganov/llama.cpp/assets/179122/f163731e-cc99-4335-8a6c-4072e23fae45">

**Comment by gelim** [comment]
Ok after digging a bit, I see the code in `examples/server/server.cpp` and `examples/server/public/index.html` that is definitely not OpenAI REST API compatible.

Format info from [README.md](https://github.com/ggerganov/llama.cpp/blame/a91928014fcf51fe297823fcff0788de4f14206e/examples/server/README.md#L169)

**Comment by gelim** [comment]
I monkey patched api_like_OAI.py
This is highly untested and does not handle several pictures being sent during the chat session.

Main idea is to catch the messages 'content' typed as list, extract the 'image_url' b64 data, convert it to jpeg (forcing that as my frontend sends webp), create the root key 'inage_data' with data + id.
Update user message in prompt with the ref to img id.

To be done: add multi images support.

**Comment by kevkid** [comment]
I am experiencing the same thing. I tried using this code and could not get it to work:
```
import base64
import requests

CONTEXT = "You are LLaVA, a large language and vision assistant trained by UW Madison WAIV Lab. You are able to understand the visual content that the user provides, and assist the user with a variety of tasks using natural language. Follow the instructions carefully and explain your answers in detail.### Human: Hi!### Assistant: Hi there! How can I help you today?\n"

with open(image.jpg', 'rb') as f:
    img_str = base64.b64encode(f.read()).decode('utf-8')
    data = { 
        "messages": [
            {
                "role": "user",
                "image_url": f"data:image/jpeg;base64,{img_str}"
            },
            {
                "role": "user",
                "content": "what is in this image?"
            }
        ]
    }
response = requests.post('http://<addr>:<port>/v1/chat/completions', json
```=data)

**Comment by gelim** [comment]
Yes you need to do the json adaptation yourself. I can put my crappy code later for people to improve it.

**Comment by kevkid** [comment]
> Yes you need to do the json adaptation yourself. I can put my crappy code later for people to improve it.

Would you be kind enough to drop your code in a gist or give an example? Thank you.

**Comment by gelim** [comment]
``` patch
diff --git a/examples/server/api_like_OAI.py b/examples/server/api_like_OAI.py
index 607fe49..6638081 100755
--- a/examples/server/api_like_OAI.py
+++ b/examples/server/api_like_OAI.py
@@ -39,20 +39,51 @@ def convert_chat(messages):
     user_n = args.user_name
     ai_n = args.ai_name
     stop = args.stop
-
+    multimodal = str()
     prompt = "" + args.chat_prompt + stop

     for line in messages:
         if (line["role"] == "system"):
+++ b/examples/server/api_like_OAI.py
@@ -39,20 +39,51 @@ def convert_chat(messages):
     user_n = args.user_name
     ai_n = args.ai_name
     stop = args.stop
+++ b/examples/server/api_like_OAI.py
@@ -39,20 +39,51 @@ def convert_chat(messages):
     user_n = args.user_name
     ai_n = args.ai_name
     stop = args.stop
-
+    multimodal = str()
     prompt = "" + args.chat_prompt + stop

     for line in messages:
         if (line["role"] == "system"):
             prompt += f"{system_n}{line['content']}{stop}"
         if (line["role"] == "user"):
-            prompt += f"{user_n}{line['content']}{stop}"
+            # multimodal heuristic
+            if isinstance(line['content'], list):
+                for cont in line['content']:
+                    multimodal="[img-10]"
+                    if cont['type'] == 'text':
+                        prompt += f"{user_n}{multimodal}{cont['text']}{stop}"
+            else: prompt += f"{user_n}{multimodal}{line['content']}{stop}"
         if (line["role"] == "assistant"):
             prompt += f"{ai_n}{line['content']}{stop}"
     prompt += ai_n.rstrip()

     return prompt

+# from any image format in base64 to JPEG in base64
+# using Pillow lib
+def multimodal_convert_pic(image_b64):
+    from base64 import b64decode,b64encode
+    from io import BytesIO
+    from PIL import Image
+
+    webp_bytes = b64decode(image_b64)
+    im = Image.open(BytesIO(webp_bytes))
+    if im.mode != 'RGB': im = im.convert('RGB')
+    jpg_data = BytesIO()
+    im.save(jpg_data, 'JPEG')
+    jpg_data.seek(0)
+    return b64encode(jpg_data.read()).decode()
+
+def multimodal_extract_image(body):
+    for line in body['messages']:
+        if not line['role'] == 'user': continue
+        for cont in line['content']:
+            if cont['type'] == 'image_url':
+                url = cont['image_url']['url']
+                start = url.find(',') + 1
+                return multimodal_convert_pic(url[start:])
+    return False
+
 def make_postData(body, chat=False, stream=False):
     postData = {}
     if (chat):
@@ -81,6 +112,9 @@ def make_postData(body, chat=False, stream=False):
     postData["stream"] = stream
     postData["cache_prompt"] = True
     postData["slot_id"] = slot_id
+    # multimodal detection
+    pic_data = multimodal_extract_image(body)
+    if pic_data: postData["image_data"] = [{"data": pic_data, "id": 10}]
     return postData

 def make_resData(data, chat=False, promptToken=[]):```

**Comment by gelim** [comment]
this is now getting more interesting with Llava 1.6 being released and results much usable than 1.5 on their demo...
Waiting for llama.cpp to update as now loading the GGUFs result to same limitation as with 1.5.

**Comment by aviallon** [comment]
This is still an issue.

**Comment by aviallon** [comment]
@kimmywork I read the server's source code, it is not implemented. I am resorting to using llama-cpp-python instead.

**Comment by kerlion** [comment]
Can we reopen this issue? I ran llama4, but it is useless since it cannot deal with images.
Multimodal LLMs become popular now, it is very important.

**Comment by GlasslessPizza** [comment]
You guys need to google, the format you are using is wrong. This works perfectly fine for gemma3:
```
llama-server.exe --model gemma-3-27b-it-q4_0_s.gguf --ctx-size 8192 --n-gpu-layers 99 --mmproj mmproj-model-f16-27B.gguf
```
```
import base64
import requests

image_path = "path/to/image.png"
with open(image_path, "rb") as img_file:
    b64_data = base64.b64encode(img_file.read()).decode("utf-8")

payload = {
    "model": "gemma3",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": [
				{"type":"text", "text":"Briefly describe this image."},
				{"type":"image_url", "image_url":{"url":f"data:image/png;base64,{b64_data}"}}
			]
        }
    ]
}

response = requests.post(
    "http://localhost:8080/v1/chat/completions",
    headers={
        "Content-Type": "application/json",
        "Authorization": "Bearer no-key"
    },
    json=payload
)

print(response.status_code)
print(response.json())
```

**Comment by aviallon** [comment]
> You guys need to google, the format you are using is wrong. This works perfectly fine for gemma3:
> ```
> llama-server.exe --model gemma-3-27b-it-q4_0_s.gguf --ctx-size 8192 --n-gpu-layers 99 --mmproj mmproj-model-f16-27B.gguf
> ```
> ```
> import base64
> import requests
> 
> image_path = "path/to/image.png"
> with open(image_path, "rb") as img_file:
>     b64_data = base64.b64encode(img_file.read()).decode("utf-8")
> 
> payload = {
>     "model": "gemma3",
>     "messages": [
>         {
>             "role": "system",
>             "content": "You are a helpful assistant."
>         },
>         {
>             "role": "user",
>             "content": [
> 				{"type":"text", "text":"Briefly describe this image."},
> 				{"type":"image_url", "image_url":{"url":f"data:image/png;base64,{b64_data}"}}
> 			]
>         }
>     ]
> }
> 
> response = requests.post(
>     "http://localhost:8080/v1/chat/completions",
>     headers={
>         "Content-Type": "application/json",
>         "Authorization": "Bearer no-key"
>     },
>     json=payload
> )
> 
> print(response.status_code)
> print(response.json())
> ```

I think you didn't see when this issue was raised. When we posted on this issue, and when it was created, multimodal server was not a thing yet.
