### ISSUE TITLE
Tokenizer: wrong token ids for OpenChat and Starling models

### ISSUE THREAD

**Issue by jndiogo** [ggerganov/llama.cpp#4772]
The following was tested in Linux, with llama-cpp-python 0.2.26, which uses ggerganov/llama.cpp@f6793491b5af6da75edad34d6f503ef86d31b09f .

Since llama-cpp-python simply calls llama.cpp's functions, I believe it's a llama.cpp issue.

For the following models, using a correctly formatted prompt example, the HuggingFace tokenizer outputs exactly the same token ids as a llama.cpp's GGUF model:
"TheBloke/Llama-2-7b-Chat-GPTQ" -> llama-2-7b-chat.Q4_K_M.gguf
"TheBloke/zephyr-7B-beta-GPTQ" -> zephyr-7b-beta.Q4_K_M.gguf
"TheBloke/Mistral-7B-Instruct-v0.1-GPTQ" -> mistral-7b-instruct-v0.1.Q4_K_M.gguf

However, for OpenChat and Starling (both seem to use the same tokenizer), after a special token like bos or eos, the following token is chosen differently in HF and llama.cpp. For example, with this prompt:
```
"<s>G"

HF tokenizer:
1="<s>"
420="_G"

llama.cpp tokenizer:
1="<s>"
28777 = "G"
```

The same happens after an eos token ("<|end_of_turn|>"=32000 in these models) .

In both model pages, the HF tokenizer output is mentioned as the correct one, and the same used for finetuning the model - see asserts in python examples at:
https://huggingface.co/TheBloke/openchat-3.5-1210-GPTQ
https://huggingface.co/TheBloke/Starling-LM-7B-alpha-GPTQ

This function reproduces the problem:
```
import transformers
from llama_cpp import (
    Llama,
    LlamaTokenizer,
)

def token_comp(hf_model, llamacpp_model,
               text):
    
    hf_tokenizer = transformers.AutoTokenizer.from_pretrained(hf_model)
    
    lc_model = Llama(model_path=llamacpp_model, verbose=False)
    lc_tokenizer = LlamaTokenizer(lc_model)


    hf = hf_tokenizer(text, add_special_tokens=False).input_ids    

    print(f"HF={hf_model} - LlamaCpp={llamacpp_model}")
    lc = lc_tokenizer.encode(text, add_bos=False)
    if hf == lc:
        print(f"LlamaCpp matches HF")
    else:
        print(f"LlamaCpp doesn't match HF:")
        for h,l in zip(hf,lc):
            print(h==l, h, l)
        
```

To reproduce, download the gguf models mentioned below and call the above function. All the text prompts are in the recommended format for each model:

```
token_comp("TheBloke/openchat-3.5-1210-GPTQ", 
           "../models/openchat-3.5-1210.Q5_K_M.gguf",
           "<s>GPT4 Correct User: Hello<|end_of_turn|>GPT4 Correct Assistant:")
```
Outputs - left integer is HF, right is llama.cpp tokenizer:
HF=TheBloke/openchat-3.5-1210-GPTQ - LlamaCpp=../models/openchat-3.5-1210.Q5_K_M.gguf
LlamaCpp doesn't match HF:
True 1 1
False 420 28777 <- "_G" vs. "G"
True 6316 6316
True 28781 28781
True 3198 3198
True 3123 3123
True 1247 1247
True 28747 28747
True 22557 22557
True 32000 32000
False 420 28777 <- same
True 6316 6316
True 28781 28781
True 3198 3198
True 3123 3123
True 21631 21631
True 28747 28747

```
token_comp("TheBloke/Starling-LM-7B-alpha-GPTQ", 
           "../models/starling-lm-7b-alpha.Q5_K_M.gguf",
           "<s>GPT4 Correct User: Hello<|end_of_turn|>GPT4 Correct Assistant:")
```
Outputs - left integer is HF, right is llama.cpp tokenizer:
HF=TheBloke/Starling-LM-7B-alpha-GPTQ - LlamaCpp=../models/starling-lm-7b-alpha.Q5_K_M.gguf
LlamaCpp doesn't match HF:
True 1 1
False 420 28777 <- "_G" vs. "G"
True 6316 6316
True 28781 28781
True 3198 3198
True 3123 3123
True 1247 1247
True 28747 28747
True 22557 22557
True 32000 32000
False 420 28777 <- also
True 6316 6316
True 28781 28781
True 3198 3198
True 3123 3123
True 21631 21631
True 28747 28747

If calling the above function in Llama2, Mistral and Zephyr models: llama.cpp and HF tokenizers emit exactly the same token ids:
```
token_comp("TheBloke/Llama-2-7b-Chat-GPTQ", 
           "../models/llama-2-7b-chat.Q4_K_M.gguf",
           "<s>[INST] Hello [/INST]")

token_comp("TheBloke/Mistral-7B-Instruct-v0.1-GPTQ", 
           "../models/mistral-7b-instruct-v0.1.Q4_K_M.gguf",
           "<s>[INST] Hello [/INST]")

token_comp("TheBloke/zephyr-7B-beta-GPTQ", 
           "../models/zephyr-7b-beta.Q4_K_M.gguf",
           "<|user|>\nHello\n<|assistant|>\n")

```

**Comment by ggerganov** [comment]
Likely these models have some unusual tokenizer configuration that we currently don't handle in `llama.cpp`:

https://huggingface.co/TheBloke/openchat-3.5-1210-GPTQ/blob/main/tokenizer_config.json

**Comment by jndiogo** [comment]
A quick and dirty workaround (for llama.cpp users) is to preprocess the prompt text and add a space after any special character (bos,eos). For example, if one encodes "<s> G" with llama tokenizer it exactly matches HF's tokenizer for "<s>G".

I don't know much about the internals of these tokenizers, but it seems the HF tokenizer thinks of special characters as kind of a space character that can then be merged with the following characters to form a token, whereas llama.cpp doesn't do this.
For example, for the text "<s>G", HF tokenizer picks (1, 420), where token 420="_G". 
But for the same text, llama picks: (1, 28777), where token 28777="G" (without leading space).
