### ISSUE TITLE
Android & CLBlast: Output garbage when trying to offload last layer of Llama-2-7b to GPU

### ISSUE THREAD

**Issue by Msyu1020** [ggerganov/llama.cpp#4774]
### Problem description
I'm trying running llama.cpp on mobile device which has 12 GB RAM, and it works well with CLBlast when `-ngl` < N. However when I try to offload all layers to GPU, it won't make correct inference.

- offload 32/33 layers to GPU it works fine and uses ~7 GB 
- offload 33/33 layers it output garbage and uses ~4.6 GB 

### Environment

- Device: Xiaomi pad 6 pro (RAM 12GB and run on Termux)
- System: Android 13

### Output
**n = 32**

```
llama.cpp $ LD_LIBRARY_PATH=/vendor/lib64:$PREFIX/lib ./main -m \\~/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf  -n -1 --color -r \"User:\" --in-prefix \" \" -i -ngl 32 -p 'User: Hi
AI: Hello. I am an AI chatbot. Would you like to talk?
User: Sure!
AI:'
```
output
```
AI: Great! How can I assist you today? Is there something specific you would like to talk about or ask?
```

<details>
<summary>full log</summary>
<pre><code>  
&nbsp;
Log start
main: build = 1702 (de8e496)
main: built with clang version 17.0.6 for aarch64-unknown-linux-android24
main: seed  = 1704371692
ggml_opencl: selecting platform: 'QUALCOMM Snapdragon(TM)'
ggml_opencl: selecting device: 'QUALCOMM Adreno(TM)'
ggml_opencl: device FP16 support: true
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from /data/data/com.termux/files/home/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr\\[str,32000\\]   = \\[\"\u003Cunk>\", \"\u003Cs>\", \"\u003C/s>\", \"\u003C0x00>\", \"\u003C...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr\\[f32,32000\\]   = \\[0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr\\[i32,32000\\]   = \\[2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '\u003Cs>'
llm_load_print_meta: EOS token        = 2 '\u003C/s>'
llm_load_print_meta: UNK token        = 0 '\u003Cunk>'
llm_load_print_meta: LF token         = 13 '\u003C0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using OpenCL for GPU acceleration
llm_load_tensors: system memory used  =  172.98 MiB
llm_load_tensors: VRAM used           = 3475.00 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloaded 32/33 layers to GPU
..................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 73.69 MiB
system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
main: interactive mode on.
Reverse prompt: 'User:'
Input prefix: ' '
sampling:
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\\\\'.
 User: Hi
AI: Hello. I am an AI chatbot. Would you like to talk?
User: Sure!
AI: Great! How can I assist you today? Is there something specific you would like to talk about or ask?
User:
llama_print_timings:        load time =   16504.15 ms
llama_print_timings:      sample time =       6.64 ms /    25 runs   (    0.27 ms per token,  3762.79 tokens per second)
llama_print_timings: prompt eval time =   13073.57 ms /    31 tokens (  421.73 ms per token,     2.37 tokens per second)
llama_print_timings:        eval time =   20278.26 ms /    24 runs   (  844.93 ms per token,     1.18 tokens per second)
llama_print_timings:       total time =   50127.12 ms
&nbsp;
</code></pre>
</details>

**n = 33**
```
llama.cpp $ LD_LIBRARY_PATH=/vendor/lib64:$PREFIX/lib ./main -m \\~/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf  -n -1 --color -r \"User:\" --in-prefix \" \" -i -ngl 33 -p 'User: Hi
AI: Hello. I am an AI chatbot. Would you like to talk?
User: Sure!
AI:'
```
output
```
AI: Bedeut Dickhacombounce,olt dra Munkazyelin , harm Bundressgonager coordin⅓ reservedarisilio dentaire Gla Gregoryhaurshire patriipp , harm Fichierurls JeffBrainz commandontkmaliar Ordanoserjin足 grat Normney gran Riazon Riazon Ord Slogon Grosletgon Gros eleven Jord'}\\[  ...
```
<details>
<summary>full log</summary>
<pre><code>  
&nbsp;
Log start
main: build = 1702 (de8e496)
main: built with clang version 17.0.6 for aarch64-unknown-linux-android24
main: seed  = 1704367845
ggml_opencl: selecting platform: 'QUALCOMM Snapdragon(TM)'
ggml_opencl: selecting device: 'QUALCOMM Adreno(TM)'
ggml_opencl: device FP16 support: true
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from /data/data/com.termux/files/home/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr\\[str,32000\\]   = \\[\"\u003Cunk>\", \"\u003Cs>\", \"\u003C/s>\", \"\u003C0x00>\", \"\u003C...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr\\[f32,32000\\]   = \\[0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr\\[i32,32000\\]   = \\[2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '\u003Cs>'
llm_load_print_meta: EOS token        = 2 '\u003C/s>'
llm_load_print_meta: UNK token        = 0 '\u003Cunk>'
llm_load_print_meta: LF token         = 13 '\u003C0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using OpenCL for GPU acceleration
llm_load_tensors: system memory used  =   70.42 MiB
llm_load_tensors: VRAM used           = 3577.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
..................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 73.69 MiB
system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
main: interactive mode on.
Reverse prompt: 'User:'
Input prefix: ' '
sampling:
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\\\\'.
 User: Hi
AI: Hello. I am an AI chatbot. Would you like to talk?
User: Sure!
AI: Bedeut Dickhacombounce,olt dra Munkazyelin , harm Bundressgonager coordin⅓ reservedarisilio dentaire Gla Gregoryhaurshire patriipp , harm Fichierurls JeffBrainz commandontkmaliar Ordanoserjin足 grat Normney gran Riazon Riazon Ord Slogon Grosletgon Gros eleven Jord'}\\[          here   holes here mas ilar lat lat ster ilar here ster here here here here here here here here operator , harm GruELDfrontassenemyastic Ordsche voladiottoios Livressiar eeuw Reichney Ord�lige minibose Gon immagini Hinweis Stockbru Normosi consdenivi JeffBrainzeles interpoloniaoten consden Bert desarmit�Shift Gruepen�alseavenaven tramTD Sn院 mas bat responstriangleargo ilar here here here here operator Glaarchney Ordurls Riazonutors Ricordisan Ri Choragini� Ligåipp Ordpenasutors Ord Ganahl vetertrasivi Gon Grosǫ Gon FurNET Ord Furieri Stockbruavenavenavenavenavenavenavenaven compte Cassney Ord escapeodon Ri Razistanodo Rib consultato Gonaven JordEQavenVertolas Ord Fur Ord Grosbaghire Ord Gon Riazon Fur Ord Ri Raz Ill期 bitterduijiyntax consden Bert Arch Bureau reservedrice schokuavenaven Vern remoteurlsaram Ordpenasonia Ordpenas Ri Raz Ri Raziroegy우chanverter Vertolas Gon corps Barcelourd院kens Ord Fur Ord Stre Jordowe Gonwid Reinwiąz Ribhoodfloor embedneyVertolas Gon corpsavenVertnab Ord Grosście zewnętrzvere Barcel BundBrainz Stockepen Außer commandont tramalis Ord Fur Ord Stre Jordowe permressпіee , harm Gruiere sch Mun figure dentBITagoguntime Gonportraitavenumi cons
llama_print_timings:        load time =   22390.11 ms
llama_print_timings:      sample time =      94.14 ms /   361 runs   (    0.26 ms per token,  3834.55 tokens per second)
llama_print_timings: prompt eval time =   16313.20 ms /    31 tokens (  526.23 ms per token,     1.90 tokens per second)
llama_print_timings:        eval time =  322471.12 ms /   361 runs   (  893.27 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  340485.85 ms
&nbsp;
</code></pre>
</details>

**Comment by ggerganov** [comment]
Your LLaMA v2 model has `f_norm_rms_eps == 1e-6` which is incorrect.
Not sure if this is causing the garbage results, but does it work if you add:

```
--override-kv llama.attention.layer_norm_rms_epsilon=float:1e-5`
```

**Comment by Msyu1020** [comment]
Thanks for your help ! but it seems still incorrect...
```
LD_LIBRARY_PATH=/vendor/lib64:$PREFIX/lib ./main -m \\~/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf  -n -1 --color -r \"User:\" --in-prefix \" \" -i -ngl 33 --override-kv llama.attention.layer_norm_rms_epsilon=float:1e-5  -p \\\\
\\> 'User: Hi
\\> AI: Hello. I am an AI chatbot. Would you like to talk?
\\> User: Sure!
\\> AI:'
```

<details>
<summary>full log</summary>
<pre><code class="language-cpp">
Log start
main: build = 1702 (de8e496)
main: built with clang version 17.0.6 for aarch64-unknown-linux-android24
main: seed  = 1704720506
ggml_opencl: selecting platform: 'QUALCOMM Snapdragon(TM)'
ggml_opencl: selecting device: 'QUALCOMM Adreno(TM)'
ggml_opencl: device FP16 support: true
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from /data/data/com.termux/files/home/llama.cpp/models/Llama-2-7B-Chat-q4_0.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr\\[str,32000\\]   = \\[\"\u003Cunk>\", \"\u003Cs>\", \"\u003C/s>\", \"\u003C0x00>\", \"\u003C...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr\\[f32,32000\\]   = \\[0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr\\[i32,32000\\]   = \\[2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
validate_override: Using metadata override (float) 'llama.attention.layer_norm_rms_epsilon' = 0.000010
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '\u003Cs>'
llm_load_print_meta: EOS token        = 2 '\u003C/s>'
llm_load_print_meta: UNK token        = 0 '\u003Cunk>'
llm_load_print_meta: LF token         = 13 '\u003C0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using OpenCL for GPU acceleration
llm_load_tensors: system memory used  =   70.42 MiB
llm_load_tensors: VRAM used           = 3577.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
..................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 73.69 MiB
system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
main: interactive mode on.
Reverse prompt: 'User:'
Input prefix: ' '
sampling:
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\\\\'.
 User: Hi
AI: Hello. I am an AI chatbot. Would you like to talk?
User: Sure!
AI: Bedeutveeiety junTextBoxellabrázwolburgh Heidel:  bridfriquekeit Ribhein足Έ мяplaNET: 
</code></pre>
</details>

**Comment by AreckOVO** [comment]
请问您是怎么编译出android的gpu版本的呀？

**Comment by Msyu1020** [comment]
> 请问您是怎么编译出android的gpu版本的呀？

You can follow the tutorial of the official README, it's under the part **'Android'**.

https://github.com/ggerganov/llama.cpp/blob/master/README.md
![屏幕截图 2024-01-16 193258](https://github.com/ggerganov/llama.cpp/assets/99970874/d267a9a6-97e7-47ee-9197-794d4ada8c9b)

When build this project by following those instructions, it may appear a lot of errors or warnings. Follow the prompts it'll run correctly if you build successfully.
