### ISSUE TITLE
LLava conversion scripts errors

### ISSUE THREAD

**Issue by tstanek390** [ggerganov/llama.cpp#4775]
Hi there,
I'm experiencing issues when trying to convert LLava models to GGUF. I proceed according to instructions in the ./examples/llava, but getting either this error almost every time after running both first surgery script, or the second convert-image-encoder-..... one. 

path = sorted(glob.glob(f"{args.model}/pytorch_model*.bin"))[-1]
IndexError: list index out of range

or this one, if i manage to sucessfuly pass the text/vision models separation:

llava/convert-image-encoder-to-gguf.py", line 121, in <module>
    v_hparams = config["vision_config"]
KeyError: 'vision_config'

There is an example of one of my commands to the script, which leads to errors: 

python3 convert-image-encoder-to-gguf.py -m /Users/admin/AI/clip-vit-large-patch14-336 --llava-projector /Users/admin/AI/MobileVLM-1.7B/llava.projector --output-dir /Users/admin/AI/MobileVLM-1.7B

Thanks in advance for any help. Be safe and take care!
Cheers, 
T.

**Comment by Galunid** [comment]
Sorry, but MobileVLM-1.7B is not supported as of yet.

**Comment by cmp-nct** [comment]
> Sorry, but MobileVLM-1.7B is not supported as of yet.

In their paper they even mention llama.cpp a few times and appear to be using it to quantize their llm, without releasing the code.
Or they used llama.cpp for the comparisons and benchmarks and used bnb for their own (which would be super weird)

It's just what "science" in IT has become in the past few years: not reproduceable by design

**Comment by ggerganov** [comment]
The convert scripts work with https://huggingface.co/mtgv/MobileVLM-1.7B - I just followed the instructions in `examples/llava`

The `clip.cpp` needs some adjustments to support the new projector though
