### ISSUE TITLE
redhat7.7 compilation error: ggml.c:89:23: fatal error: stdatomic.h: No such file or directory

### ISSUE THREAD

**Issue by chuanzhubin** [ggerganov/llama.cpp#4781]
redhat7.7 compilation error: ggml.c:89:23: fatal error: stdatomic.h: No such file or directory

Error reported during make

-----------------------------
(chatglm) [ideal@ZJUDWHDSP02 llama.cpp]$ make
I llama.cpp build info: 
I UNAME_S:   Linux
I UNAME_P:   x86_64
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion 
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds
I NVCCFLAGS:  
I LDFLAGS:    
I CC:        cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
I CXX:       g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

cc  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion    -c ggml.c -o ggml.o
ggml.c:89:23: fatal error: stdatomic.h: No such file or directory
 #include 
                       ^
compilation terminated.
make: *** [ggml.o] Error 1
(chatglm) [ideal@ZJUDWHDSP02 llama.cpp]$ ^C
(chatglm) [ideal@ZJUDWHDSP02 llama.cpp]$ python --version
Python 3.11.5

**Comment by morpheus2448** [comment]
Update GCC 4.8 to GCC 4.9

[Source](https://bugzilla.redhat.com/show_bug.cgi?id=1850174)

**Comment by juanbits** [comment]
@morpheus2448  i updated to GCC 4.9.2 and got the same error
