### ISSUE TITLE
HQQ quantization

### ISSUE THREAD

**Issue by loretoparisi** [ggerganov/llama.cpp#4782]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Add support to new 
[HQQ](https://mobiusml.github.io/hqq_blog/) (Half-Quadratic Quantization)  quantization method. HQQ requires no calibration data and it takes less than 5 minutes to process Llama-2-70B quantized to 2-bit outperforming the full-precision Llama-2-13B according to the report.
![image](https://github.com/ggerganov/llama.cpp/assets/163333/bfcf3ccc-8006-42d6-a55b-1a1372922e05)

# Motivation

HQQ performs better the other quantization methods like GPTQ or AWQ according to the tech report
![image](https://github.com/ggerganov/llama.cpp/assets/163333/8db215d3-5cef-457c-a72f-cdb6e56051fe)

# Possible Implementation

The official HQQ implementation code is available [here](https://github.com/mobiusml/hqq)

**Comment by sorasoras** [comment]
Cool, Does this have C++ implementation？

**Comment by mobicham** [comment]
@sorasoras there's an ATen C++ implementation for inference: https://github.com/mobiusml/hqq/blob/master/hqq/kernels/hqq_aten.cpp

**Comment by tikikun** [comment]
This should be re-opened again since this method is really good

**Comment by charlesrwest** [comment]
I would really like support for HQQ. I would be willing to pay a $100 bounty.

**Comment by Zijie-Tian** [comment]
+1

**Comment by Murari007** [comment]
@charlesrwest, Is support for HQQ added in Llama.cpp? I have the implementation; I can raise a PR referencing this issue if not supported yet.
