### ISSUE TITLE
The "quantize.exe" script was not found in the current location

### ISSUE THREAD

**Issue by yoann56100** [ggerganov/llama.cpp#479]
Im trying to use it with 65B, but when i want to quantize it, i have the error "The "quantize.exe" script was not found in the current location"

Im running it on windows 11 with 48bg of ram and I7 12700k

**Comment by prusnak** [comment]
You need to compile the quantize.exe first

**Comment by Robertultime** [comment]
And how to compile the quantize.exe ?

**Comment by IcawFype** [comment]
And where is quantize.exe ?

**Comment by T4rg3n** [comment]
> And where is quantize.exe ?

You have to build it with CMake or Visual Studio

**Comment by axelhusson** [comment]
for information try like this, it's ok for me : 
.......\llama.cpp\build\bin\Release> python.exe ..\..\..\quantize.py 7B

**Comment by IcawFype** [comment]
> > And where is quantize.exe ?
> 
> You have to build it with CMake or Visual Studio

Ok thanks :)

**Comment by PatriceMarin** [comment]
Hi, 
I have the same issue on Mac OS / Silicon chip. Any clue? 
Thanks :)
