### ISSUE TITLE
Issues with network access of server cpp

### ISSUE THREAD

**Issue by RuslanKovalyov** [ggerganov/llama.cpp#4802]
Do not work in local network as server? it work from same machine (i use Mac), but not from network PCs. i check other servers on same port like django, other AI projects them all work but only llama.cpp server work just from local machine... i'm sure is no problem with network and firewall. (it work with all other servers... as network is not the problem! also is running under 0.0.0.0 ip and port 8080). Can open UI like localhost, ip:8080, 127.0.0.0:8080 etc BUT not form the network.

**Comment by sgladkoff** [comment]
You have to specify the host and port when running server, for example:

./server ,,/yourmodel.gguf --host 10.252.4.5 --port 8888 -c 2048

**Comment by stolsvik** [comment]
`--host 0.0.0.0` works for me, I can access it from another machine on the same LAN.

**Comment by jboero** [comment]
Use `--host ::` if you want to use IPv4 + IPv6.

**Comment by buding2018** [comment]
it works
