### ISSUE TITLE
CPU load balancing is far worse for Mixtral / MoE inference vs dense model

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#4817]
If I set 6 threads (both BLAS and regular) for Nous Hermes 34b [4_K_M], which is a dense model, I seem to get optimal prompt evaluation speeds compared to 10 or 4 threads, and the CPU load balancing looks like:
![image](https://github.com/ggerganov/llama.cpp/assets/66376113/1674b54d-4f56-4bc7-8054-fb791730567a)

This is equivalent to the amount of performance cores I have on this processor, so this seems to make sense. I tested 4 and 6 threads and they were both worse. However:

<img width="527" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/5b8a34ef-b1dd-4b22-b60d-e4fc53b3f040">

The load balancing is significantly less even for the batching in Sparse MoE, so overall utilization suffers [even though this is pure CPU inference] on OpenBLAS. [~60% average utilization]

Turning up the BLAS thread count doesn't help either; paradoxically, the net utilization seems to be _worse_ if you turn up the thread count, just like it was for a dense model.

If I run pure CPU inference for Llama 13b 4_K_S, the prompt processing is actually _faster_ by a small margin (~80ms per token instead of ~100ms per token) despite 13b having a fatter kv cache, due to a lack of GQA when compared to the other two models. In task manager, it reports evenly balanced thread usage just like the 34b.

My current theory for why this happens is because, to my understanding, the calculations for all layers are grouped per-expert during prompt eval, and this is done sequentially. The overhead of splitting the work per-expert might be what's causing this, so it might be best to inference all layers at once rather than grouping them discretely.

@slaren is this idea what you were referring to when you talked about "grouping by processing all the experts in a single `ggml_mul_mat_id`?" Or would it maybe be better to statically allocate certain threads to certain experts to mitigate this effect?

**Comment by slaren** [comment]
I cannot reproduce this issue. I am not sure what you mean by BLAS thread count, but in any case, BLAS is not supported with mixtral on CPU.

![image](https://github.com/ggerganov/llama.cpp/assets/2141330/0672b579-766f-4e76-a0e7-b09c9fcce9a2)

**Comment by kalomaze** [comment]
> I cannot reproduce this issue. I am not sure what you mean by BLAS thread count, but in any case, BLAS is not supported with mixtral on CPU.
> 
> ![image](https://private-user-images.githubusercontent.com/2141330/294804057-0672b579-766f-4e76-a0e7-b09c9fcce9a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODcxMDMsIm5iZiI6MTcwNDY4NjgwMywicGF0aCI6Ii8yMTQxMzMwLzI5NDgwNDA1Ny0wNjcyYjU3OS03NjZmLTRlNzYtYTBlNy1iMDljOWZjY2U5YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDQwNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY0YzMxOGJhY2JhY2RmNWI0MDAxZjg3Mjc0NzEzN2Y3NDBlNWZmNDE3YTY3M2I2OTAyMmJjMDJkOTFkNzBhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uSXh-4DPifO2LyloLyuCj0gHPwUKSWHuAKlEf3pGhOo)
> 
> This was tested with `./perplexity -m models/mixtral/ggml-model-Q4_0.gguf -f wikitext-2-raw/wiki.test.raw -t 32`. Do not use `llama-bench` to test mixtral, as the expert distribution is not likely to be very uniform because it only evaluates BOS tokens, and the results are probably not going to be representative of a real use case.

BLAS thread count was in reference to the batched thread count. I might have misinterpreted that as being synonymous

> BLAS is not supported with mixtral on CPU.
So this would likely be the culprit?

**Comment by kalomaze** [comment]
As it turns out, this impacts my i5, but ostensibly, not this specific CPU.

<img width="460" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/638eef01-4746-4eed-a4e0-469b26af3917">

Someone else also mentioned to me that they see similar results on Mixtral on a Ryzen 5 5600. So it might be exclusively impacting less powerful chips.

If it helps to mention, I'm on faster DDR5 (4800mhz) than the other person with an i9 who tested this, so I doubt it's at all related to memory bandwidth bottlenecking.

**Comment by kalomaze** [comment]
This doesn't happen on latest upstream after updating, apparently. Will re-open if I find evidence to the contrary (and after personally testing)
