### ISSUE TITLE
server.exe no output when I use it with Qwen 1.8B

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#4821]
I am using the latest branch of llama cpp  with P40.

I was not able to get out from input prompt.
print_timings: prompt eval time =      81.21 ms /    48 tokens (    1.69 ms per token,   591.08 tokens per second)
print_timings:        eval time =       0.01 ms /     1 runs   (    0.01 ms per token, 76923.08 tokens per second)
print_timings:       total time =      81.22 ms
slot 0 released (49 tokens in cache)
{"timestamp":1704704854,"level":"INFO","function":"log_server_request","line":2731,"message":"request","remote_addr":"127.0.0.1","remote_port":61214,"status":200,"method":"POST","path":"/completion","params":{}}
That's all I get from the any input。

Sometimes, It output normally, but othertimes. it just output nothing.
when I use main, it work.  
There is some undetermined bug with the server when I use it with QWEN1.8 model.

**Comment by QingHeYang** [comment]
Yes, I have encountered the same problem.
In the compiled Main run, the same Prompt can get the results, but the Server run, there will be this problem.
The model is also QWen1.8b, in Windows based on Ubuntu are the same.
I saw you turned off this ISSUE, do you have a solution to your problem?
