### ISSUE TITLE
Support for LLMLingua

### ISSUE THREAD

**Issue by TechnotechGit** [ggerganov/llama.cpp#4823]
Hi! I was attempting to see if llama.cpp could be supported in LLMLingua (prompt compression) via llama-cpp-python, but it looks like attention masks are required. Attention masks are supported in transformers, and it would seem like they would enable more projects to work with llama.cpp. 

I think that this might be worth pursuing in order to use LLMLingua in downstream projects, since CPU and partial-GPU prompt processing is obviously quite slow, and adds up for longer passages. Additionally, perhaps implementing LLMLingua's methods in llama.cpp is worth consideration?

**Comment by ggerganov** [comment]
There is support for creating a custom attention mask by utilizing the position and the sequence id of the tokens in a batch. The implementation is that tokens from a given sequence id attend only to tokens from the same sequence id with smaller position. Using this, one can construct most (if not all) possible attention masks. One of the better demonstrations of this is in the [lookahead decoding](https://github.com/ggerganov/llama.cpp/pull/4207) example.

I skimmed through the LLMLingua paper and it seems that attention masking is required for evaluating the segments of the original prompt:

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/78740e89-1062-4283-b53f-eefac2348cda)

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/8c8d9b27-dd33-4ac4-980f-9916e2d99119)

If that is the only case that requires attention masking, then I think this is trivially supported - just assign different sequence ids to the different segments.

**Comment by TechnotechGit** [comment]
@ggerganov Since attention masks are already implemented, I can either close this issue, or rename to "Support for LLMLingua" if this is worth pursuing.

**Comment by xcottos** [comment]
Hi everybody, I'm really interested to the llmlingua support in llama-cpp-python since it's the most efficient way of reducing the context size (up to 7X times). I have a ready use case to test it so please feel free to ask me to test it whenever you are ready.

**Comment by pathquester** [comment]
Would also be interested in this, pretty useful.

**Comment by sathyapriyaa-sketch** [comment]
def get_prompt(instruction, new_result_str_modified, new_system_prompt=DEFAULT_SYSTEM_PROMPT):
    new_prompt = new_system_prompt + new_result_str_modified 
    llm_lingua = PromptCompressor(device='cpu')
    new_prompt = llm_lingua.compress_prompt(new_prompt, instruction="", question="", target_token=200)
    SYSTEM_PROMPT = B_SYS + new_prompt + E_SYS
    prompt_template =  B_INST + SYSTEM_PROMPT + instruction + E_INST
    return prompt_template 

This's giving me - > Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx -> I'm running this on streamlit cloud, can someone help in solving this? Thanks!

**Comment by reversTeam** [comment]
For anyone still interested in attention mask support for LLMLingua and similar projects — I've opened #21105 which adds a public `llama_set_attn_mask()` API that supports both broadcast and per-head custom masks. This would enable the attention mask functionality that was identified as missing here.
