### ISSUE TITLE
 Add support for MobileLLaMA/MobileVLM models

### ISSUE THREAD

**Issue by Foul-Tarnished** [ggerganov/llama.cpp#4824]
# Feature Description
Please add support for MobileLLaMA 1.4B and 2.7B
If possible, also for MobileVLM (multi-modal, LLaVA based?) 1.7B and 3B
https://github.com/Meituan-AutoML/MobileVLM

# Motivation
These small models would run perfectly on smartphones, as they would use not much RAM.
Apps like https://github.com/Mobile-Artificial-Intelligence/maid would highly benefit from these models.

# Possible Implementation
Implementing this instead might solve the issue with low RAM devices altogether, maybe : 

> LLM in a flash: Efficient Large Language Model Inference with Limited Memory
https://arxiv.org/abs/2312.11514

**Comment by Foul-Tarnished** [comment]
Maybe this new model is better than MobileLLaMA ? and it's just 1.1B
https://github.com/jzhang38/TinyLlama

Unable to benchmark them (skill issue)

**Comment by azarovalex** [comment]
@Foul-Tarnished MobileLLaMa uses `llama` architecture, so it's already supported.
I uploaded quantized models to HuggingFace, or you can. quantize yourself. https://huggingface.co/azarovalex/MobileLLaMA-1.4B-Chat-GGUF

**Comment by Foul-Tarnished** [comment]
Nice, thanks

more interested in the 2.7B
do you know how it compare to TinyLlama?

Le dim. 14 janv. 2024, 19:10, Alex Azarov ***@***.***> a
écrit :
