### ISSUE TITLE
CI: nix flake update: no permission to create a PR

### ISSUE THREAD

**Issue by SomeoneSerge** [ggerganov/llama.cpp#4851]
The weekly workflow for updating the nixpkgs revision pinned in the `flake.lock`, introduced in https://github.com/ggerganov/llama.cpp/pull/4709, fails with insufficient permissions: https://github.com/ggerganov/llama.cpp/actions/runs/7434790471/job/20229364773. The action is attempting to open a PR with the updated lock file. The action can be configured to use a separate token when creating the PR: https://github.com/ggerganov/llama.cpp/blob/c75ca5d96f902564cbbbdd7f5cade80d53c288bb/.github/workflows/nix-flake-update.yml#L22

Side-note: for the CI/nix-build workflow to also run automatically on these PRs a personal token would be required, https://github.com/DeterminateSystems/update-flake-lock#with-a-personal-authentication-token

@ggerganov: it's preferable to keep the action; can we use another token or do you know if there's another way to allow opening PRs from the specific workflow?

**Comment by ggerganov** [comment]
So I have to create 2 tokens?

- `secrets.GITHUB_TOKEN`
- `secrets.GH_TOKEN_FOR_UPDATES`

Btw, where are the PRs opened to?

**Comment by SomeoneSerge** [comment]
No I just put `secrets.GITHUB_TOKEN` in the yaml back then because I saw another workflow using that name and thought it already exists. Just any token token with the right open PRs to llama.cpp will do

> Btw, where are the PRs opened to?

The action pushes the change to [refs/heads/update_flake_Lock_action](https://github.com/ggerganov/llama.cpp/tree/update_flake_lock_action) and opens a PR targeting master/the default branch


For reference, here's the ("fine-grained personal access") token I had confirmed to work in another repo: 
![image](https://github.com/ggerganov/llama.cpp/assets/9720532/76a231d0-96a4-49c1-918e-36dc3297e8c9)

**Comment by ggerganov** [comment]
Added `secrets.FLAKE_TOKEN` with PR write permissions

**Comment by SomeoneSerge** [comment]
H'm, this has still failed at https://github.com/ggerganov/llama.cpp/actions/runs/7492308166/job/20395506763#step:4:761

```
  /usr/bin/git push --force-with-lease origin update_flake_lock_action:refs/heads/update_flake_lock_action
  remote: Permission to ggerganov/llama.cpp.git denied to ggerganov.
  fatal: unable to access 'https://github.com/ggerganov/llama.cpp/': The requested URL returned error: 403
```

From a glance I don't see much difference between the present workflow and e.g. https://github.com/SomeoneSerge/pkgs/actions/runs/7435087711/workflow. I'll need to think and come back to this

**Comment by ggerganov** [comment]
Our workflow is missing:

```yaml
        with:
          github-token: ${{ secrets.GH_PAT }}
```

in the "Install Nix" step. Not sure if it matters

**Comment by ggerganov** [comment]
I have manually disabled the Nix CI workflow until the issue is resolved:

https://github.com/ggerganov/llama.cpp/actions/workflows/nix-ci.yml

**Comment by SomeoneSerge** [comment]
> I have manually disabled the Nix CI workflow until the issue is resolved:

This isn't really a blocker for the build part of the CI, it's going to keep working just with the pinned (older) Nixpkgs revision.

> in the "Install Nix" step. Not sure if it matters

It shouldn't, it's about how git is invoked to push the branch at the very last step. I was meaning to try and replay all of the steps I mentioned here (starting with generating a new key) in my own repo but I didn't get around to yet.

It's weird though, if the token literally says "read & write access to ... commits", how could it not work to push a branch 🙈

**Comment by ggerganov** [comment]
I just regenerated the token and re-set `FLAKE_TOKEN` in case I somehow made a mistake before. Here are the permissions for a second look:

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/589e444c-d63b-48ee-b3e8-4f4864b3644f)

**Comment by SomeoneSerge** [comment]
Thanks for the screenshot! I believe that rw access to commits ιs also necessary because the action needs to git-push before it can open a PR

**Comment by ggerganov** [comment]
Got it - it's updated now:

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/789cadba-d9a7-4c3a-8ce2-d4da045eb0b5)
