### ISSUE TITLE
allow loading from ram location 

### ISSUE THREAD

**Issue by IMbackK** [ggerganov/llama.cpp#4857]
# Feature Description

An api to load models from ram locations.

# Motivation

So currently the only api to load a model is to load from a file on disk. For small models embedded in larger applications it can be useful to include the model in various resource systems, or to simply link the model file into the binary itself for distribution.
To this end it would be great if llama.cpp where also able to load the model from gguf given a location in ram.

# Possible Implementation

Since llama_model_loader works quite a bit with mmaps anyways only some minor new paths would have to be added where file io is currently used.

**Comment by crasm** [comment]
This would be nice to have
