### ISSUE TITLE
server unable to render code blocks when "Show Probabilities" option is active

### ISSUE THREAD

**Issue by Huge** [ggerganov/llama.cpp#4859]
When "Show Probabilities" option is set to > 0, code blocks are not rendered verbatim in the chat UI.

Sure somebody might want to debug confidence of `` and `  token generations, but some might prefer a more readable code. So a subordinate switch would be good to have. Other way to solve that would be to build the formatting as normally and just have the most probable tokens on click/hover.

![image](https://github.com/ggerganov/llama.cpp/assets/111648/8aad792c-431d-46c3-80dc-6b4716b09a8a)

PS: sorry for the bug label, I have thought it is plain wrong/broken initially and only when writing the issue realized the formattings collide.

**Comment by Azeirah** [comment]
I think this is a decent point, it doesn't make sense to apply formatting when you're inspecting token probabilities. This is an either/or situation.

A toggle to switch between probabilities and rendered view would be a good solution to this imo.
