### ISSUE TITLE
Segmentation Fault with --prompt-cache and --n-gpu-layers N (workaround: --no-kv-offload)

### ISSUE THREAD

**Issue by elgatopanzon** [ggerganov/llama.cpp#4865]
OS: Debian 12.4
GPU: Nvidia RTX 3080 Ti
CPU: Ryzen 5900X
RAM: 32GB DDR4

When running with `--prompt-cache` and offloading to GPU with `--n-gpu-layers N`, the default is to offload the KV store to the GPU as well. However, for whatever reason there is a Segmentation Fault when trying to restore the prompt cache. 

The workaround is adding `--no-kv-offload` which doesn't offload the KV store to the GPU, and allows the prompt cache to be restored correctly.

**Comment by HarewVlad** [comment]
Can the issue be related somehow to "k->data = v->data = (void *)(uintptr_t)1" in llama_kv_cache_init? When i remove this line i don't recieve seg fault even without --no-kv-cache and preserve generation speed.

**Comment by ggerganov** [comment]
Not 100%, but I believe this will be resolved with #4766

**Comment by slaren** [comment]
Can you check if this works now that #4766 has been merged?

**Comment by elgatopanzon** [comment]
Sorry for the late response. I can no longer replicate the issue with the latest build, so I assume it's been resolved!
