### ISSUE TITLE
"KeyError: 'architectures'" when trying to conver FLOR 6.3B (BLOOM based) model with convert-hf-to-gguf.py

### ISSUE THREAD

**Issue by VivaPeron** [ggerganov/llama.cpp#4877]
When trying to convert FLOR 6.3B model downloaded from Huggingface (https://huggingface.co/projecte-aina/FLOR-6.3B) using the following command

```
python3 convert-hf-to-gguf.py --outtype f16 /media/psf/2TB/Software/AI/Models/FLOR-6.3B
```

It outputs the following error message:

```
Loading model: FLOR-6.3B
Traceback (most recent call last):
  File "/home/christopher/llama.cpp/convert-hf-to-gguf.py", line 1054, in <module>
    model_class = Model.from_model_architecture(hparams["architectures"][0])
                                                ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'architectures'
```

 Any one knows what caused the problem and how to solve it?

**Comment by ggerganov** [comment]
I think the config file is missing the "architectures" tag. Try to put something like:

```
"architectures": [
    "BloomForCausalLM"
],
```

in `config.json`

**Comment by VivaPeron** [comment]
> I think the config file is missing the "architectures" tag. Try to put something like:
> 
> ```
> "architectures": [
>     "BloomForCausalLM"
> ],
> ```
> 
> in `config.json`

Well, there's a reason you are the creator of this whole thing lol
That solved it! Thank you, I was bsolutely lost. It is now running.

I will then use the result for some finetuning tests. Wish me luck.

If it is useful for anyone, this is the full config.json with the provided fix:

```
{
    "architectures": [
        "BloomForCausalLM"
    ],
    "vocab_size": 50257,
    "hidden_size": 4096,
    "tie_word_embeddings": true,
    "n_layer": 30,
    "hidden_dropout": 0.0,
    "layer_norm_epsilon": 1e-05,
    "n_head": 32,
    "attention_dropout": 0.0,
    "model_type": "bloom"
}
```

**Comment by Shahin-rmz** [comment]
Hello,
the same issue. should I also add
```
"architectures": [
    "BloomForCausalLM"
]
```
to the [config.json](https://huggingface.co/malteos/bloom-6b4-clp-german/blob/main/config.json) file?

This is an Embedding model of German text and I want to run it locally.
