### ISSUE TITLE
can' quantize deekseek model

### ISSUE THREAD

**Issue by dotyuu** [ggerganov/llama.cpp#4925]
When I download the model from the deepseek huggingface official repository, I cannot convert it into a gguf file。

python D:\Ai\convert.py D:\Ai\deepseek-coder-6.7b-instruct

D:\Ai\gguf-py
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00002-of-00002.bin
params = Params(n_vocab=32256, n_embd=4096, n_layer=32, n_ctx=16384, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-06, n_experts=None, n_experts_used=None, rope_scaling_type=<RopeScalingType.LINEAR: 'linear'>, f_rope_freq_base=100000, f_rope_scale=4.0, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=WindowsPath('D:/Ai/deepseek-coder-6.7b-instruct'))
Traceback (most recent call last):
  File "D:\Ai\convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1614, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1409, in load_vocab
    path = self._select_file(vocabtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1384, in _select_file
    raise FileNotFoundError(f"{vocabtype} {file_key} not found.")
FileNotFoundError: spm tokenizer.model not found.

**Comment by askmyteapot** [comment]
That is a BPE tokenizer model. You will need to use `convert.py modelname_or_path --vocabtype bpe`

so for you, it will be: 
```python D:\Ai\convert.py D:\Ai\deepseek-coder-6.7b-instruct --vocabtype bpe```

hope that helps

**Comment by dotyuu** [comment]
> That is a BPE tokenizer model. You will need to use `convert.py modelname_or_path --vocabtype bpe`
> 
> so for you, it will be: `python D:\Ai\convert.py D:\Ai\deepseek-coder-6.7b-instruct --vocabtype bpe`
> 
> hope that helps

Thank you for your help, it has pointed me in a direction, although it still prompts me
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00002-of-00002.bin
params = Params(n_vocab=32256, n_embd=4096, n_layer=32, n_ctx=16384, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-06, n_experts=None, n_experts_used=None, rope_scaling_type=<RopeScalingType.LINEAR: 'linear'>, f_rope_freq_base=100000, f_rope_scale=4.0, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=WindowsPath('D:/Ai/deepseek-coder-6.7b-instruct'))
Traceback (most recent call last):
  File "D:\Ai\convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1614, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1409, in load_vocab
    path = self._select_file(vocabtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1384, in _select_file
    raise FileNotFoundError(f"{vocabtype} {file_key} not found.")
FileNotFoundError: bpe vocab.json not found.



I think this may be something missing from the model's repo

**Comment by apepkuss** [comment]
Same issue

**Comment by ggerganov** [comment]
Should be fixed in https://github.com/ggerganov/llama.cpp/pull/4971

Please check and confirm

**Comment by apepkuss** [comment]
@ggerganov Tried https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-instruct using `convert.py` in #4971. The error message:

```console
(facet) ubuntu@ip-172-31-31-132:~/workspace/models$ /home/ubuntu/workspace/llama.cpp/convert.py --outfile . deepseek-coder-6.7b-instruct
/home/ubuntu/workspace/llama.cpp/gguf-py
Loading model file deepseek-coder-6.7b-instruct/model-00001-of-00002.safetensors
Loading model file deepseek-coder-6.7b-instruct/model-00001-of-00002.safetensors
Loading model file deepseek-coder-6.7b-instruct/model-00002-of-00002.safetensors
params = Params(n_vocab=32256, n_embd=4096, n_layer=32, n_ctx=16384, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-06, n_experts=None, n_experts_used=None, rope_scaling_type=<RopeScalingType.LINEAR: 'linear'>, f_rope_freq_base=100000, f_rope_scale=4.0, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=PosixPath('deepseek-coder-6.7b-instruct'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': None, 'tokenizer.json': PosixPath('deepseek-coder-6.7b-instruct/tokenizer.json')}
Loading vocab file 'deepseek-coder-6.7b-instruct/tokenizer.json', type 'spm'
Traceback (most recent call last):
  File "/home/ubuntu/workspace/llama.cpp/convert.py", line 1668, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/llama.cpp/convert.py", line 1624, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/llama.cpp/convert.py", line 1428, in load_vocab
    vocab = SentencePieceVocab(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/llama.cpp/convert.py", line 449, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/facet/lib/python3.11/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/ubuntu/miniconda3/envs/facet/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/facet/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
```

**Comment by Nindaleth** [comment]
This issue is probably fixed by now?
