### ISSUE TITLE
Docker error:  Cannot access '/models//7B/ggml-model-f16.bin*': No such file or directory

### ISSUE THREAD

**Issue by AlexandreDevaux** [ggerganov/llama.cpp#493]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [*] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [*] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [*] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

llama
└── models
    ├── 13B
    │   ├── checklist.chk
    │   ├── consolidated.00.pth
    │   ├── consolidated.01.pth
    │   └── params.json
    ├── 30B
    │   ├── checklist.chk
    │   ├── consolidated.00.pth
    │   ├── consolidated.01.pth
    │   ├── consolidated.02.pth
    │   ├── consolidated.03.pth
    │   └── params.json
    ├── 65B
    │   ├── checklist.chk
    │   ├── consolidated.00.pth
    │   ├── consolidated.01.pth
    │   ├── consolidated.02.pth
    │   ├── consolidated.03.pth
    │   ├── consolidated.04.pth
    │   ├── consolidated.05.pth
    │   ├── consolidated.06.pth
    │   ├── consolidated.07.pth
    │   └── params.json
    ├── 7B
    │   ├── checklist.chk
    │   ├── consolidated.00.pth
    │   └── params.json
    ├── ggml-vocab.bin
    ├── llama.sh
    ├── tokenizer_checklist.chk
    └── tokenizer.model

using ```docker run -v /llama/models:/models ghcr.io/ggerganov/llama.cpp:full --all-in-one "/models/" 7B```

output : 
```
Converting PTH to GGML...
ls: cannot access '/models//7B/ggml-model-f16.bin*': No such file or directory
```

**Comment by yoanndelattre** [comment]
Hi,
I have the same error. Is there any news about this bug?
Thanks in advance :)

**Comment by mm86133** [comment]
Same issue here. The dockerized script is expecting something that doesn't exist in models.

Does anyone have any hack around it? Any idea when a fix will be released???

**Comment by yoanndelattre** [comment]
> Hello, I had the same error on windows 10. try : docker run -v /c/llama/models:/models ghcr.io/ggerganov/llama.cpp:full --all-in-one "/models/" 7B It solved the issue for me. Regards.

I use docker with WSL2, so I don't think with it's a same problem like you.

**Comment by camertron** [comment]
I was able to get around this issue by making the same changes mentioned in #408 and building the full Docker image myself. For those interested in getting started fast, I copied the entire contents of my modified .devops/tools.sh into [this gist](https://gist.github.com/camertron/52c7b3c8080d70710e477a69b345db57). You should be able to copy/paste it into a local checkout of llama.cpp to get up and running.

I built the Docker image by running:

```
docker build -f .devops/full.Dockerfile -t llama-cpp:full .
```

I then ran the following command to convert the LLaMA model to ggml (my copy of LLaMA lives in a dir called llama/):

```
docker run -v "$(pwd)/llama/:/models" llama-cpp:full --all-in-one "/models" 7B
```

I then tried to run inference using the example in the README, but unfortunately it looks like there's a bug that prevents passing more than one word to the `-p` option (I think whatever mechanism splits args is ignoring quotes). Fortunately llama.cpp allows sticking the prompt into a file, so I copy/pasted the prompt example from the README into llama/prompt.txt and executed this command to run the inference:

```
docker run -v "$(pwd)/llama/:/models" llama-cpp:full --run -m "/models/7B/ggml-model-q4_0.bin" -f /models/prompt.txt -n 512
```

And it worked 🎉  It's a little slow on my basic 'ol x86 Macbook, but it worked 🎉

**Comment by asaka003** [comment]
hi, I have the same problem.It sounds like the bin file was lost,i used the commands following before run the docker:
`# install Python dependencies
python3 -m pip install torch numpy sentencepiece

# convert the 7B model to ggml FP16 format
python3 convert-pth-to-ggml.py models/7B/ 1`

this will transform you *.pth files to *bin files,the your docker will find it.
make sure that change the prarm the right way.
for 13B model,it can be  `python3 convert-pth-to-ggml.py models/13B/ 2` and model 65B is `python3 convert-pth-to-ggml.py models/65B/ 8`, i guess.

**Comment by DavidVelazquezR** [comment]
In my case, i'm working with _pyllama_, but it appears that you need to run your command in this way:

`python3 convert-pth-to-ggml.py models/pyllama_data/7B 1`

Just make sure that your folder have this similar hierarchy, because the **_convert-pth-to-ggml.py_** script need to find **tokenizer.model** and your **consolidated.00.pth**

**Comment by mrsipan** [comment]
Do it in 3 steps, not _--all-in-one_, like this,

Convert it:

```bash
docker run -v /home/hola/llama/models:/models ghcr.io/ggerganov/llama.cpp:full 
  --convert "/models/7B" 1
```
Quantize it:

```bash
docker run -v /opt/llama/models:/models ghcr.io/ggerganov/llama.cpp:full \
  --quantize "/models/7B/ggml-model-f16.bin" "/models/7B/ggml-model-q4_0.bin" 2
```

Run it:

```bash
docker run -v /opt/llama/models:/models --entrypoint '/app/main' ghcr.io/ggerganov/llama.cpp:full \
  -m /models/7B/ggml-model-q4_0.bin -n 512 -p "Building a website can be done in 10 simple steps"
```

Same for the other models.

**Comment by prusnak** [comment]
This all reads like users were not providing the actual path to the models, but just copy-pasting `/llama/models` from the readme. In the meantime, the readme has been updated to use `/path/to/models` as the path + there is a note that this path should be replaced by the actual path. Closing.

**Comment by cth18012017** [comment]
Hello, have you  a link from where we can download the ggml model files?

**Comment by andresrex** [comment]
I don't understand I don't even have a models/7B folder :/

**Comment by lafe** [comment]
> This all reads like users were not providing the actual path to the models, but just copy-pasting `/llama/models` from the readme. In the meantime, the readme has been updated to use `/path/to/models` as the path + there is a note that this path should be replaced by the actual path. Closing.

That's definitely not the case. When I run the --all-in-one command, it does not work. When I use the commands given by @mrsipan, the conversion and the creation of the "ggml-model-f16.bin"-file works with the same volume mapping.

**Comment by mwtrew** [comment]
Yep, `--all-in-one` still fails with this error unless you first use `--convert` (or `convert.py` directly) to generate the initial `.bin` files.
