### ISSUE TITLE
Add support Tiny Llava on llama.cpp

### ISSUE THREAD

**Issue by circuluspibo** [ggerganov/llama.cpp#4953]
As you know, tiny llama is adaptable for cpu inference or edge devices.
"bczhou" is fine-tuning this using llava recipe, so It looks like reasonable performance and size

https://huggingface.co/bczhou/tiny-llava-v1-hf

could you any plan to integrate this model on llama.cpp?

**Comment by ggerganov** [comment]
PRs welcome
