### ISSUE TITLE
convert-hf-to-gguf.py not work with llama2 ?

### ISSUE THREAD

**Issue by thangld201** [ggerganov/llama.cpp#4964]
I have the original weight files of Llama2 from Meta. How should I convert them to gguf ?

`python convert-hf-to-gguf.py /path/to/meta/llama2` yields error

```
Traceback (most recent call last):
  File "convert-hf-to-gguf.py", line 1268, in <module>
    main()
  File "convert-hf-to-gguf.py", line 1249, in main
    model_instance = model_class(dir_model, ftype_map[args.outtype], fname_out, args.bigendian)
  File "convert-hf-to-gguf.py", line 57, in __init__
    self.model_arch = self._get_model_architecture()
  File "convert-hf-to-gguf.py", line 246, in _get_model_architecture
    raise NotImplementedError(f'Architecture "{arch}" not supported!')
NotImplementedError: Architecture "LlamaForCausalLM" not supported!
```

Could you help me ? @ggerganov It's weird how Llama is not supported here ..

**Comment by amygbAI** [comment]
Hi @thangld201 could u please paste the contents of your llama2 folder .. if these are just the weights of the llama2 from META then it will NOT contain the model in the format that convert.py or its associated variants can handle ..they typically require either "safetensors" or ".bin" extensions of the model 

PS : also convert-hf-to-gguf should ideally be used with Huggingface formatted models ..not with the base model directly ..

**Comment by thangld201** [comment]
```
$ ls
config.json                       model-00002-of-00002.safetensors  pytorch_model.bin.index.json  tokenizer_config.json
generation_config.json            model.safetensors.index.json      README.md                     tokenizer.json
LICENSE.txt                       pytorch_model-00001-of-00002.bin  Responsible-Use-Guide.pdf     tokenizer.model
model-00001-of-00002.safetensors  pytorch_model-00002-of-00002.bin  special_tokens_map.json       USE_POLICY.md
```

I used the one from hf (Llama-2-7b-hf). 

I had a look at the code in `convert-hf-to-gguf.py`. The error came from `_get_model_architecture(self)` method. There was no if condition for LlamaForCausalLM class <--- this was the cause.

**Comment by amygbAI** [comment]
here's what u need to do .. open the convert-hf-to-gguf.py and go to line # 228 and change

if arch == "MixtralForCausalLM": 
to 
if arch == "MixtralForCausalLM" or arch == "LlamaForCausalLM"

basically ensure the model returned is LLAMA

in my case i had to download tokenizer.* from HF as well but looks like u already have it in your folder .. i ran the script post thtese changes and voila the gguf file got created .. good luck

**Comment by ggerganov** [comment]
> P/s: I tried convert.py and got an ggml-*.gguf file, and was able to run with ./main. Though I don't know if this is the correct way to go.

I think this is OK

**Comment by puyuanOT** [comment]
I tried the convert.py but it looks like the lm head is missing after the conversion.

**Comment by lmxin123** [comment]
> LlamaForCausalLM

I try ,it not work

**Comment by Anish-Mahambare** [comment]
![Screenshot from 2024-07-29 13-36-25](https://github.com/user-attachments/assets/e771810d-a029-4769-9957-8b3001e3641e)
![Screenshot from 2024-07-29 13-36-58](https://github.com/user-attachments/assets/bfa3248e-9689-4e07-a75e-935dcbae83eb)

I am getting the above error, am I doing something wrong? I made sure that the model is in safetensors format

**Comment by raphael10-collab** [comment]
Hi! 

I'm trying to convert this model: https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-italian
but get this strange error:  `hf-to-gguf:Model Wav2Vec2ForCTC is not supported` : 

    (.venv) raphy@raohy:~/whisper.cpp/models$ ./llama.cpp/convert_hf_to_gguf.py ./italian/ --outtype f16
    INFO:hf-to-gguf:Loading model: italian
    ERROR:hf-to-gguf:Model Wav2Vec2ForCTC is not supported

How to make it work?
