### ISSUE TITLE
Android GPU

### ISSUE THREAD

**Issue by AreckOVO** [ggerganov/llama.cpp#4967]
I tried the project to test on the cpu of android and it was successful, but I think it is still relatively slow, I want to use the gpu of the android device to test, how do I make it.

**Comment by java63940** [comment]
> I tried the project to test on the cpu of android and it was successful, but I think it is still relatively slow, I want to use the gpu of the android device to test, how do I make it.

refer this :
https://github.com/ggerganov/llama.cpp/issues/2169
https://github.com/JackZeng0208/llama.cpp-android-tutorial
