### ISSUE TITLE
Is there a plan to support deepseek-moe model?

### ISSUE THREAD

**Issue by cdliang11** [ggerganov/llama.cpp#4968]
Hi,
Is there a plan to support [deepseek-moe-16b-chat model](https://huggingface.co/deepseek-ai/deepseek-moe-16b-chat)?

**Comment by paryska99** [comment]
Always love to see more models supported. I wonder how many already existing optimizations from llamacpp would apply to it, and take time to figure out which. It's nice to see Llamacpp being developed and support all these models, but it almost seems like the LLM space needs a more universal approach somehow.
