### ISSUE TITLE
Tokenizer should remember prevously converted tokens

### ISSUE THREAD

**Issue by Urammar** [ggerganov/llama.cpp#4985]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Tokenization represents a significant portion of total input to output generation time. A huge fraction of tokenization is re-tokenizing previously converted text after a new generation. Doing this every single time context changes is absurd, when it could simply be a running cache, being appended to.

# Possible Implementation

A running cache, being appended to, and sent directly to the model, bypassing the tokenizer for anything other than brand new unprocessed text.

**Comment by crasm** [comment]
Do you mean prompt ingestion?

Prompt ingestion (decoding) is what takes the majority of the time before generation begins, not tokenization. Tokenization is fast, even with large prompts.
