### ISSUE TITLE
Android .so library: cannot find "ggml_print_backtrace"

### ISSUE THREAD

**Issue by d-kls** [ggerganov/llama.cpp#4987]
First of all i downloaded the latest source code (b1892).
Then after unzipping i have built `libllama.so` with NDK for android (specifically x86_64) like so:
```
x86_64-linux-android33-clang++ -shared -o libllama.so -fPIC llama.cpp -Wall
```
Besides some warnings of unused methods, this build is going through succesfully.
```
In file included from llama.cpp:4:
./unicode.h:251:20: warning: unused function 'codepoints_to_utf8' [-Wunused-function]
static std::string codepoints_to_utf8(const std::vector<uint32_t> & cps) {
                   ^
./unicode.h:317:30: warning: unused function 'codepoints_to_utf16' [-Wunused-function]
static std::vector<uint16_t> codepoints_to_utf16(const std::vector<uint32_t> & cps) {
                             ^
./unicode.h:343:30: warning: unused function 'codepoints_from_utf16' [-Wunused-function]
static std::vector<uint32_t> codepoints_from_utf16(const std::vector<uint16_t> & utf16) {
                             ^
llama.cpp:735:13: warning: unused function 'ggml_graph_compute_helper' [-Wunused-function]
static void ggml_graph_compute_helper(std::vector<uint8_t> & buf, ggml_cgraph * graph, int n_threads) {
            ^
4 warnings generated.
```

However when i link the shared library `libllama.so` to my android app, i get the following error on trying to open the shared library:
```
Failed to load dynamic library 'libllama.so': dlopen failed: cannot locate symbol "ggml_print_backtrace"
```

**Comment by ggerganov** [comment]
Does adding `-DGGML_SHARED` to the `clang++` command help?

**Comment by d-kls** [comment]
@ggerganov Thanks for your reply. Unfortunate to report, but no. After running:
```
x86_64-linux-android33-clang++ -shared -o libllama.so -fPIC llama.cpp -DGGML_SHARED -Wall
```
I still get the exact same error.

**Comment by d-kls** [comment]
You gave me an idea though. I build a `libggml-shared.so` like this:
```
x86_64-linux-android33-clang -shared -o libggml-shared.so -fPIC ggml.c ggml-alloc.c ggml-backend.c ggml-quants.c -Wall
```

and then linked my `libllama.so` to it like this:
```
x86_64-linux-android33-clang++.cmd -shared -o libllama.so -fPIC llama.cpp -Wall -L. -lggml-shared
```

And now i get no more error that any symbol is undefined and can't be found.

**Comment by d-kls** [comment]
@ggerganov do you by chance have _any_ idea why when debugging my `libllama.so` with gdb and setting a breakpoint at `llama_context_default_params` after calling `stepi` i get a SIGSEV segmentation fault immediately? I tracked this function down as the source of the segfault before debugging but i don't know why that happens..

**Comment by cmpktheo** [comment]
Did you have any success building it?
Can you provide any solution?

**Comment by ditsuke** [comment]
@d-kls why did you close this issue?

**Comment by d-kls** [comment]
Because my last comment solved my problem

**Comment by ditsuke** [comment]
Thanks, I didn't realize! `libggml` / `libggml-shared` already ships with llama, so you might not need to build them yourself. For others using cmake/meson, you might run into this error because the pkgconfig / cmake configs do not advertise linking to `libggml`, which is required if you're using a macro like `GGML_ASSERT` that references `libggml` symbols. I think the configs should thus advertise `libggml` as well. @ggerganov what do you think?

**Comment by ggerganov** [comment]
Makes sense
