### ISSUE TITLE
Parallelize dequantization or fp format conversion when using blas

### ISSUE THREAD

**Issue by ReinForce-II** [ggerganov/llama.cpp#4988]
In ggml_compute_forward_mul_mat@ggml.c, gemm parallelism is managed by blas library. However, this disables multithreading on dequantizing weights, which may be a bottleneck.

I have performed some ugly modifications for comparing performance.

```
› MKL_NUM_THREADS=8 ./llama-bench -m Llama-2-7b-chat-q4km.gguf -t 8
| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | BLAS       |          8 | pp 512     |     55.24 ± 3.16 |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | BLAS       |          8 | tg 128     |     21.12 ± 1.89 |

build: 862f5e4 (1886)

› MKL_NUM_THREADS=8 ./llama-bench -m Llama-2-7b-chat-q4km.gguf -t 8
| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | BLAS       |          8 | pp 512     |     79.34 ± 5.23 |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | BLAS       |          8 | tg 128     |     21.26 ± 1.83 |

modified
```
[cb828c8](https://github.com/ReinForce-II/llama.cpp/commit/cb828c8d5a1851f0c9ab5b8c1609ff1ebd761fdc)

**Comment by ggerganov** [comment]
Thanks for looking into this!

The global atomic flag is indeed ugly, so we need to figure out something better. The limitation that `GGML_TASK_INIT` is called only for one of the threads is making this more difficult than it should be, so I wonder if we should try to improve this part first - i.e. be able to have multi-threaded initialization for ops.

I think `wsize` also has to be updated because `wdata` will now store all dequantized matrices, while on `master` it stores only one at a time.

**Comment by ReinForce-II** [comment]
The corresponding enhancedments with multi-threaded initialization implemented here [blas-parallize-to-float-2](https://github.com/ReinForce-II/llama.cpp/tree/blas-parallize-to-float-2)
I wonder if these changes are acceptable.

**Comment by ReinForce-II** [comment]
> Besides, [here](https://github.com/ggerganov/llama.cpp/blob/57e2a7a52a819883f40dada8a2edc24ecf48186b/llama.cpp#L6290) may have something to do since higher amount of threads is useful now.

Num of threads is required be carefully configured `<blas_threads> + <llama.cpp_threads> <= physical threads` to avoid any performance penalty. Any better approach here?

**Comment by ggerganov** [comment]
@ReinForce-II I think you are on the right track. Would you like to open a Pull Request so we can review the changes in detail and suggest improvements if necessary?

@slaren I wonder if we can now utilize `ggml-backend` somehow to create a "BLAS" backend that "offloads" just the matrix multiplications in their own splits. This can resolve the thread concurrency problem between `ggml` threads and BLAS threads. Have you thought about such kind of approach? (this is low-prio)

**Comment by slaren** [comment]
Yes, this is something that I would like to do. It should only require minor changes to `ggml_backend_sched` to support this use case.
