### ISSUE TITLE
unsupported op 'MUL_MAT'

### ISSUE THREAD

**Issue by NeevJewalkar** [ggerganov/llama.cpp#4998]
```
ggml_metal_graph_compute_block_invoke: error: unsupported op 'MUL_MAT'
GGML_ASSERT: ggml-metal.m:779: !"unsupported op"
```
system: Mac Book Air (intel)
Happens when i try to run phi-2

**Comment by XieWeikai** [comment]
I encountered the same problem

**Comment by ggerganov** [comment]
Likely your device is missing `Apple7` family feature set (more info: https://github.com/ggerganov/llama.cpp/pull/4794)

Show the logs of `ggml_metal_init` to confirm:

```
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2 Ultra
ggml_metal_init: picking default device: Apple M2 Ultra
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/Users/ggerganov/development/github/llama.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M2 Ultra
ggml_metal_init: GPU family: MTLGPUFamilyApple8  (1008)
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true      <---- this is required for llama.cpp
ggml_metal_init: simdgroup matrix mul. support = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 154618.82 MB
```

**Comment by MBarti** [comment]
Same problem on Macbook Pro 2018 16GB (Intel, AMD Radeon Pro 555X)
ML Model: mistral-7b-dpo-v5.Q6_K.gguf


ggml_metal_graph_compute_block_invoke: error: unsupported op 'MUL_MAT'
GGML_ASSERT: ggml-metal.m:779: !"unsupported op"
Abort trap: 6

also:
ggml_metal_graph_compute_block_invoke: error: unsupported op 'RMS_NORM'

**Comment by ggerganov** [comment]
The only way is to implement the respective Metal kernels without using `simd_` calls. It's not very difficult, but I don't plan on officially supporting it as it will increase the Metal code by a lot and I'm not convinced it will result in significant gains compared to CPU-only for these machines.

If somebody implements the kernels, we can put them in `ggml-metal-intel.metal` and have them build as a separate backend for Intel machines

**Comment by NeevJewalkar** [comment]
From what i understood, this error occurs due to the fact that all this is running on gpu. This may seem dumb but how do i run llama.cpp on the cpu instead?

**Comment by ggerganov** [comment]
Most of the examples support `-ngl 0` argument which would make `llama.cpp` not use the GPU

**Comment by 0xez** [comment]
> Most of the examples support `-ngl 0` argument which would make `llama.cpp` not use the GPU

This worked for me, thank you!

I was running llama-2-7b-chat.Q4_K_M on my macbook pro 2016 (8G DRAM), and got an error said:
`ggml_metal_graph_compute_block_invoke: error: unsupported op 'RMS_NORM'`
The `-ngl 0` param solved the problem.

It was running successfully right now, but very slow, almost take 2~3min to predict each word. I could see very high IO load via iostat command and also the cpu-sys was high too, which means it was trying to swap data between disk and memory. 

Conclusion: I need a new macbook definitely!

**Comment by lalitya-sawant** [comment]
passing param -ngl 0 param solved the problem.

**Comment by Umkus** [comment]
This used to help be on my mid 2015 macbook, but no more 😢
