### ISSUE TITLE
Reproducability information

### ISSUE THREAD

**Issue by troed** [ggerganov/llama.cpp#50]
The seed for the website example is included, but using the same parameters doesn't manage to reproduce the example output. Listing what requirements influense reproducability would help in verifying installs.

The failed test is with x86_64 (gcc or clang, no difference), CUDA 12.1, pytorch 1.13.1, numpy 1.23.5, sentencepiece 0.1.97 and Python 3.10.6 on Linux.

**Comment by ggerganov** [comment]
#95
