### ISSUE TITLE
Tasks queue logic doesn't seem to be logical

### ISSUE THREAD

**Issue by tikikun** [ggerganov/llama.cpp#5000]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
<img width="878" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/22268502/6107ede0-4859-47d1-8c9c-e720572dea6c">
https://github.com/ggerganov/llama.cpp/blob/2b3a665d3917edf393761a24c4835447894df74a/examples/server/server.cpp#L1558

# Motivation

Task queue should only erase task "after" the task was resolved, with current implementation, the task queue does not allow user to know how many tasks are being resolved at the same time + other possible limitations.

# Possible Implementation
Delete the task after it was resolved

**Comment by ngxson** [comment]
I'm not sure if I understand it correctly:

`task_server task = queue_tasks.front();` ==> This line get the first task in the front of the queue

`queue_tasks.erase(queue_tasks.begin());` ==> This line delete the first task in the front of the queue

So the task does get deleted, but it just being deleted **before** it is processed, not **after** it is processed, right?

---

In any cases, I'm agree that the current behavior (returning "slot unavailable" message) does break OpenAI-compatible in some cases.

Ideally, if all slots are unavailable, we can just delay the task until one become unavailable. I already try this by using a proxy and it works, but it would be nice if the behavior can be implemented in server.cpp, and be controlled via an argument.

**Comment by tikikun** [comment]
> I'm not sure if I understand it correctly:
> 
> `task_server task = queue_tasks.front();` ==> This line get the first task in the front of the queue
> 
> `queue_tasks.erase(queue_tasks.begin());` ==> This line delete the first task in the front of the queue
> 
> So the task does get deleted, but it just being deleted **before** it is processed, not **after** it is processed, right?
> 
> In any cases, I'm agree that the current behavior (returning "slot unavailable" message) does break OpenAI-compatible in some cases.
> 
> Ideally, if all slots are unavailable, we can just delay the task until one become unavailable. I already try this by using a proxy and it works, but it would be nice if the behavior can be implemented in server.cpp, and be controlled via an argument.

You got the point, i have many issue with this example

**Comment by huliangbing** [comment]
Great! Queue is needed!

**Comment by huliangbing** [comment]
When will #5018 be merged?
Thanks!
