### ISSUE TITLE
Convert NF4 Transformer model to GGML/GGUF

### ISSUE THREAD

**Issue by puyuanOT** [ggerganov/llama.cpp#5004]
Is it possible to convert a Transformer with NF4 quantization into GGML/GGUF format without loss? I have a base llama model in NF4 and LoRA moudle in fp16, and I am trying to run them on llama.cpp.

**Comment by Limour-dev** [comment]
Maybe [this](https://github.com/ggerganov/llama.cpp/pull/1666) will be helpful?
