### ISSUE TITLE
Using convert.py with a fine tuned phi-2

### ISSUE THREAD

**Issue by FiveTechSoft** [ggerganov/llama.cpp#5009]
We are loading phi-2 from HF using load_in_8bit=True and torch_dtype=torch.float16, then we fine tune it and finally we save it locally.

When running convert.py ./phi-2 we get this error:
File "/content/convert.py", line 764, in convert
    data_type = SAFETENSORS_DATA_TYPES[info['dtype']]
KeyError: 'I8'

If we try the same using load_in_8bit=False then we get:
  File "/content/convert.py", line 257, in loadHFTransformerJson
    f_norm_eps        = config["rms_norm_eps"],
KeyError: 'rms_norm_eps'

how to generate a GGUF from a fine tuned phi-2 ? many thanks

**Comment by Rishbah-76** [comment]
Having the same kind of issue with falcon finetuned 7b bf16 model 
""
ggllm.cpp/convert.py", line 761, in convert
    data_type = SAFETENSORS_DATA_TYPES[info['dtype']]
KeyError: 'BF16'
""

**Comment by MotorCityCobra** [comment]
Do you have reason to believe it is supported?

**Comment by apepkuss** [comment]
Same issue with [phi-2](https://huggingface.co/microsoft/phi-2).

**Comment by compilade** [comment]
Have you tried using `convert-hf-to-gguf.py` (which is [where conversion from phi-2 models was implemented](https://github.com/ggerganov/llama.cpp/blob/6f9939d119b2d004c264952eb510bd106455531e/convert-hf-to-gguf.py#L198-L199)) instead of `convert.py`?

**Comment by apepkuss** [comment]
> > how to generate a GGUF from a fine tuned phi-2 ?
> 
> I suggest using `convert-hf-to-gguf.py` (which is [where conversion from phi-2 models was implemented](https://github.com/ggerganov/llama.cpp/blob/6f9939d119b2d004c264952eb510bd106455531e/convert-hf-to-gguf.py#L198-L199)) instead of `convert.py`.
> 
> When new models come out on HuggingFace, their conversion is usually added in `convert-hf-to-gguf.py` (the "hf" in there stands for HuggingFace, I think), probably because it allows sharing a lot of metadata-loading code (especially regarding tokenizers, but also tensor names). It's also more obvious (to me, at least) where to add support for a new model in `convert-hf-to-gguf.py` than in `convert.py`. So that's possibly why `convert.py` doesn't also support converting phi-2.

Works for me. Thanks a lot!

**Comment by tgalery** [comment]
I have a similar issue, after fine-tuning, I get `KeyError: 'n_layer'`  (line 1064 of ` convert-hf-to-gguf.py`), otherwise, I get `KeyError: 'rms_norm_eps'` (line 257 of `convert.py`).

**Comment by compilade** [comment]
> I have a similar issue, after fine-tuning, I get `KeyError: 'n_layer'` (line 1064 of ` convert-hf-to-gguf.py`), otherwise, I get `KeyError: 'rms_norm_eps'` (line 257 of `convert.py`).

@tgalery The line numbers in the errors get seem different than those in the latest commit.

> Whereas `Phi2Model.set_gguf_parameters`, expects keys like `n_layer`, `n_head`, `n_positions`, `n_embed`, `layer_norm_epsilon`, and `rotary_dim`.

> If it's mapping old keys to new ones, I'm happy to work on a MR, but there seems to be some info lost there.

The fix you're describing is already implemented, but maybe your local checkout of `llama.cpp` hasn't been updated in a while. Converting Phi-2 with `convert-hf-to-gguf.py` with such a `config.json` should work as of at least #4903 (which was merged on January 13), since it checks for `num_hidden_layers` (which seems to exist in your `config.json`) before falling back to `n_layer`.

This is what you should see in `convert-hf-to-gguf.py` if your source tree of `llama.cpp` is recent enough:

https://github.com/ggerganov/llama.cpp/blob/5cdb371731caa2c41fcca42d4d2d43f94f6883b4/convert-hf-to-gguf.py#L1287-L1296

If it still doesn't work with the latest version, please do tell. Hope this helps :)

**Comment by tgalery** [comment]
@compilade thanks for the explanation. It works like a charm. Just a question, I'm working on a pipeline and for some model types, say `Mistral-7B`, one needs to use the `convert.py` script. For some others, say `phi-2`, we need to use `convert-hf-to-gguf.py` . Is there a plan to unify these ?
