### ISSUE TITLE
Unable to finetune Mixtral

### ISSUE THREAD

**Issue by cheeseng** [ggerganov/llama.cpp#5013]
I have been trying to finetune mixtral, the same train data seems to work for mistral but not mixtral, e.g. mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf, it seems to just crash with segmentation error: 

```
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.38 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size = 25215.87 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    64.00 MiB
llama_new_context_with_model: KV self size  =   64.00 MiB, K (f16):   32.00 MiB, V (f16):   32.00 MiB
llama_new_context_with_model: graph splits (measure): 1
llama_new_context_with_model:  CUDA_Host compute buffer size =   114.53 MiB
Segmentation fault (core dumped)
```

Any idea what's going wrong?  Not enough memory?  I tried it on Colab with A100 seems to get similar behavior also, where the last line of the output is: 

```
llama_new_context_with_model:  CUDA_Host compute buffer size =   ...
```

and Colab thinks the execution is completed.

**Comment by ngxson** [comment]
AFAIK finetune is only supported for llama-based model: https://github.com/ggerganov/llama.cpp/blob/master/examples/finetune/README.md

![image](https://github.com/ggerganov/llama.cpp/assets/7702203/5573aa9e-57e2-4e9d-8093-b887befb8dc9)

While mistral 7b maybe considered as llama-based, mixtral 8x7b is not llama-based

**Comment by cheeseng** [comment]
O

**Comment by cheeseng** [comment]
> AFAIK finetune is only supported for llama-based model: https://github.com/ggerganov/llama.cpp/blob/master/examples/finetune/README.md
> 
> ![image](https://private-user-images.githubusercontent.com/7702203/297696083-5573aa9e-57e2-4e9d-8093-b887befb8dc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mjg1MTksIm5iZiI6MTcwNTYyODIxOSwicGF0aCI6Ii83NzAyMjAzLzI5NzY5NjA4My01NTczYWE5ZS01N2UyLTRlOWQtODA5My1iODg3YmVmYjhkYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDEzNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M1NTI3OWU3ZjQ3ODBlZDNlNGUzYjE0M2JmMTNiZDIwMTQzMzhkY2I2ZTcyNzcxYmZkOWE1NDZkZmYzNTk5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UY3wuK22u7mWy0euqoGiEI1ZpYy2wH2ajCetHcezRSk)
> 
> While mistral 7b maybe considered as llama-based, mixtral 8x7b is not llama-based

Oh I thought mixtral was based on llama, from the logs: 

```
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mixtral-8x7b-instruct-v0.1
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
```

Any plan to support mixtral in future?

**Comment by ggerganov** [comment]
Sometime in the future yes, but not very soon. We are mostly focused on the inference part at this stage
