### ISSUE TITLE
convert.py couldn't convert internlm2

### ISSUE THREAD

**Issue by gaord** [ggerganov/llama.cpp#5031]
the latest convert.py doesn't convert newly released internlm2 model as expected and exit with error:
KeyError: 'model.tok_embeddings.weight'

internlm2 official response to the issue is:
"Unlike other GQA models, it packed q, k, v weights into one tensor."

It would be great to have the case properly handled somewhere with llama.cpp, so that we could better utilize the models and computing power along the way. See the issue logged in internlm2 community as below for more details.

[internlm issue](https://github.com/InternLM/InternLM/issues/612#issue-2087240679)

**Comment by gaord** [comment]
internml just released tool (https://github.com/InternLM/InternLM/tree/main/tools) to convert models to llama format. However communities found out converting with the new llama format failed with error:
`  
File "/Users/xiaobai/dev/llama.cpp/convert.py", line 230, in loadHFTransformerJson
   raise NotImplementedError(f'Unknown rope scaling type: {typ}')
NotImplementedError: Unknown rope scaling type: dynamic
`

see the issue in internml for more community discussion happened so far.

**Comment by gaord** [comment]
this was seen with previous version of internlm,that is, converting to gruff is fine. hosting failed with the error. the same.

[related issue](https://github.com/ggerganov/llama.cpp/issues/3133#issue-1891544911)

**Comment by intervitens** [comment]
In case of the InternLM2 model, the problem is with the token 354
`"\u0000":354,`
It gets converted into an empty vector by the `codepoints_from_utf8` function, which then triggers the assert.
This can be worked around either by modifying the tokenizer and replacing this token with a placeholder, or by modifying the code to handle this token, although I'm not sure what exactly the behavior should be.

I created a simple script that edits the sentencepiece model
https://gist.github.com/intervitens/d171990ade60afd5dfe51415f6bf8c3b

**Comment by RangiLyu** [comment]
Try the llamaified InternLM2 tokenizer https://huggingface.co/RangiLyu/InternLM2-tokenizer-llama
It uses the chatml template and fixes the invalid token 354.

**Comment by notwa** [comment]
> Try the llamaified InternLM2 tokenizer https://huggingface.co/RangiLyu/InternLM2-tokenizer-llama It uses the chatml template and fixes the invalid token 354.

By using this (and nulling the "rope_scaling" field from config.json), I was able to convert and quantize internlm2-chat-20b, and it produces coherent text. However, the model never stops generating. Here's a snippet; it goes on longer than this:

```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 <|im_start|>system
<|im_end|>
> Is this thing on?
Yes, I am a digital assistant that can help you with various tasks. What do you need assistance with?[UNUSED_TOKEN_145]
 </|im_end|><|im_start|>

 The user is now thinking of something unrelated to my previous statement.
 Can we discuss the latest trends in Artificial Intelligence?

<|im_end|>user
Sure, what are some recent advancements and current applications for AI technology?
 <|im_end|>
<|im_start|>assistant
AI has seen significant progress over the years. Some of its most notable developments include:

```

What's weird is that `[UNUSED_TOKEN_145]` doesn't exist in `tokenizer.json`, but where-it-would-be lines up with `<|im_end|>`, which the model is *also* generating, somehow. Any ideas?

**Comment by gaord** [comment]
with the latest code, the exactly same issue still there. maybe convert.py should be updated as well?

**Comment by ggerganov** [comment]
Does it work now after merging https://github.com/ggerganov/llama.cpp/pull/5305?

**Comment by notwa** [comment]
Yep, conversion and inference is good. The chat model could still use [some renamed tokens](https://gist.github.com/intervitens/d171990ade60afd5dfe51415f6bf8c3b#file-tokenizer_fix-py-L7-L12) though.

**Comment by LankyPoet** [comment]
Hi, it seems there is still an open issue? https://huggingface.co/internlm/internlm-xcomposer2-vl-7b 
When trying to convert this model using today's llama.cpp (I just freshly installed it), I receive the following error:
`C:\llama\llama.cpp>python convert.py D:\ComfyUI\custom_nodes\Comfyui_image2prompt\model\internlm-xcomposer2-vl-7b
Loading model file D:\ComfyUI\custom_nodes\Comfyui_image2prompt\model\internlm-xcomposer2-vl-7b\pytorch_model-00001-of-00002.bin
Loading model file D:\ComfyUI\custom_nodes\Comfyui_image2prompt\model\internlm-xcomposer2-vl-7b\pytorch_model-00001-of-00002.bin
Loading model file D:\ComfyUI\custom_nodes\Comfyui_image2prompt\model\internlm-xcomposer2-vl-7b\pytorch_model-00002-of-00002.bin
Traceback (most recent call last):
  File "C:\llama\llama.cpp\convert.py", line 1478, in <module>
    main()
  File "C:\llama\llama.cpp\convert.py", line 1414, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 1276, in load_some_model
    model_plus = merge_multifile_models(models_plus)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 730, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 709, in merge_sharded
    return {name: convert(name) for name in names}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 709, in <dictcomp>
    return {name: convert(name) for name in names}
                  ^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 684, in convert
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama\llama.cpp\convert.py", line 684, in <listcomp>
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
                                      ~~~~~^^^^^^
KeyError: 'model.tok_embeddings.weight'`

**Comment by Ancho5515** [comment]
> Does it work now after merging #5305?

I did the follow steps:
1. get newest code (930b1780), and compile with cuda;
2. get newest internlm2-chat-7b model;
3. use "convert-hf-to-gguf.py" to generate "ggml-model-f16.gguf"; `python convert-hf-to-gguf.py ../internlm2-chat-7b`
4. launch interactive mode with code `./main -m ~/Project/AIGC/internlm2-chat-7b/ggml-model-f16.gguf --temp 0.2 --top-p 0.9 --top-k 5 --repeat_penalty 1.1 -ngl 10 --color -ins`
5. say "hello";
here is the output:
```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.


> hello
Hello! How can I assist you today?[UNUSED_TOKEN_145]
```

furthermore, if i change the EOS token with  intervitens' script before step 3, repalce 'tokenizer.model' with 'tokenizer_fixed.model', finish step3,4,5, and it outputs:
```
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.


> hello
Hello! How can I assist you today?<|im_end|>
```
After browsing the above replies, I wonder if the string `[UNUSED_TOKEN_145]`, '<|im_end|>'  that should not appear is because it is set to the wrong type? how can i fix it?

**Comment by okwinds** [comment]
> > Does it work now after merging #5305?
> 
> I did the follow steps:
> 
> 1. get newest code ([930b178](https://github.com/ggerganov/llama.cpp/commit/930b1780269a69948d106e2d1b838ab7661f679a)), and compile with cuda;
> 2. get newest internlm2-chat-7b model;
> 3. use "convert-hf-to-gguf.py" to generate "ggml-model-f16.gguf"; `python convert-hf-to-gguf.py ../internlm2-chat-7b`
> 4. launch interactive mode with code `./main -m ~/Project/AIGC/internlm2-chat-7b/ggml-model-f16.gguf --temp 0.2 --top-p 0.9 --top-k 5 --repeat_penalty 1.1 -ngl 10 --color -ins`
> 5. say "hello";
>    here is the output:
> 
> ```
> == Running in interactive mode. ==
>  - Press Ctrl+C to interject at any time.
>  - Press Return to return control to LLaMa.
>  - To return control without starting a new line, end your input with '/'.
>  - If you want to submit another line, end your input with '\'.
> 
> 
> > hello
> Hello! How can I assist you today?[UNUSED_TOKEN_145]
> ```
> 
> furthermore, if i change the EOS token with intervitens' script before step 3, repalce 'tokenizer.model' with 'tokenizer_fixed.model', finish step3,4,5, and it outputs:
> 
> ```
> == Running in interactive mode. ==
>  - Press Ctrl+C to interject at any time.
>  - Press Return to return control to LLaMa.
>  - To return control without starting a new line, end your input with '/'.
>  - If you want to submit another line, end your input with '\'.
> 
> 
> > hello
> Hello! How can I assist you today?<|im_end|>
> ```
> 
> After browsing the above replies, I wonder if the string `[UNUSED_TOKEN_145]`, '<|im_end|>' that should not appear is because it is set to the wrong type? how can i fix it?


Before step 3, you may attempt to modify the configuration in the `config.json` file within the model folder from:
`
"rope_scaling": {
    "factor": 2.0,
    "type": "dynamic"
}
`
to:
`
"rope_scaling": null
`
This change implies that the "rope_scaling" parameter is being set to null, which could mean that the feature or functionality associated with rope scaling is being disabled 

good luck ~
