### ISSUE TITLE
Baichuan2-7B-Chat model converted to ggml-model-q4_0.gguf, AI answer does not stop automatically when inference is made

### ISSUE THREAD

**Issue by Lyzin** [ggerganov/llama.cpp#5034]
I converted the Baichuan2-7B-Chat model to ggml-model-q4_0.gguf and then used . /main inference and found that I could not stop answering

my system: macos
python version: 3.9.10

Here's my version using llama.cpp
. /main version：
![image](https://github.com/ggerganov/llama.cpp/assets/18082104/86485298-c493-4989-ac4d-24232a55c944)

llama.cpp git commit id:
![image](https://github.com/ggerganov/llama.cpp/assets/18082104/127fc0a2-baa2-4246-b3f1-41fa8415bd24)

Here are the steps I took to convert
> `python convert-hf-to-gguf.py  ./models/Baichuan2-7B-Chat`
> 
> `./quantize  ./models/Baichuan2-7B-Chat/ggml-model-f16.gguf ./models/Baichuan2-7B-Chat/ggml-model-q4_0.gguf q4_0`

Here's how to reason with . /main reasoning results

> `./main -m ./models/Baichuan2-7B-Chat/ggml-model-q4_0.gguf -n 256 --repeat_penalty 1.0 -ngl 0 --color -i -r "User:" -f prompts/chat-with-baichuan.txt`

Here is the result of the inference, which keeps repeating the output
![image](https://github.com/ggerganov/llama.cpp/assets/18082104/2e9d087c-4ee4-481b-8d50-944d45ac3503)

Is this a problem caused by the conversion?

**Comment by hiepxanh** [comment]
@Lyzin  I belive it is the same issue with this https://github.com/ggerganov/llama.cpp/issues/3969
can you download Phi-2 model and confirm the bug still happen?

**Comment by Lyzin** [comment]
> @Lyzin I belive it is the same issue with this #3969 can you download Phi-2 model and confirm the bug still happen?

I downloaded the phi-2 model, requantized it, and the output automatically stopped
llama.cpp version tag: b1966

> ./main -m ./models/phi-2/ggml-model-q4_0.gguf -n 512 --color -i -cml -ngl 0  -r "User:" -f prompts/chat-with-bob.txt
Here is the output of the AI
<img width="710" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/18082104/32459247-808c-44cb-80ba-291871691aa4">
