### ISSUE TITLE
[Feature Request]: have TinyBlast Support for llama.cpp build. (which is very helpful for AMD user)

### ISSUE THREAD

**Issue by hiepxanh** [ggerganov/llama.cpp#5048]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I would like to have TinyBlas support which can build with llama.cpp. Since the setup and deploy is very easy, I can run it in 5 minute instead of 5 day to learn how to setup on AMD system which is 100% failed because my card is not support

# Motivation

Since it is impossible to build HipBlast on consumer AMD card except flagship one. CLBlas is complex too. TinyBlast is very effecient for Education, Demo, and Teaching purpose. I know it is as not performance as HIPBlas, but the AMD card is cheap, which can allow parent, passioner, a lot of people cannot effort money can run AI's thing locally on cheap computer. If I can show my kids, or my parent can see that I can run AI thing on little card, I belive they will be pround of me and I'm feel happy too. It also give a good inspiration for other to go to AI journey!
# Possible Implementation

- TinyBlas seem just two file https://github.com/Mozilla-Ocho/llamafile/blob/eb4989a/llamafile/tinyblas.cu

I belive support this and building llama.cpp is more easier with TinyBlas

**Comment by amakropoulos** [comment]
@jart @ggerganov this would be amazing.
TinyBLAS does not require the cudart library which takes about 500MB (or 1GB for both CUDA 11 and 12) and reduces the built size to a couple of MBs.
In terms of deployment to consumers it's a vast gain.
