### ISSUE TITLE
Support for Orion14b

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#5061]
# Feature Description
Orion-14B series models are open-source multilingual large language models trained from scratch by OrionStarAI. The base model is trained on 2.5T multilingual corpus, including Chinese, English, Japanese, Korean, etc, and it exhibits superior performance in these languages. 

# Possible Implementation

Smaller version of OrionStar-Yi-34B, so it should be easy to support

https://github.com/OrionStarAI/Orion

**Comment by benxh1995** [comment]
It's not a smaller version of OrionStar sadly, and after converting it results in these errors:
```
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 444, got 363
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/Orion-14B-Chat/Orion-14B-Chat-Q4_K.gguf'

```

**Comment by Engininja2** [comment]
I think it's sort of llama-hf plus a couple of bias tensors and the NeoX RoPE, but there are some issues with the vocabulary.
`llm_load_vocab: mismatch in special tokens definition ( 423/84608 vs 4/84608 ).`
The tokens llama.cpp wants to force to be special look like `<reserved_117>`, `<0xB0>`, or a few html tags like `<p>` or `<strong/>`
Python tokenizes them properly and doesn't have more than the 4 special tokens so I don't know what the fix would be. If llama.cpp is forced to not treat them as special it doesn't tokenize them whole.
You can look at my attempt here https://github.com/Engininja2/llama.cpp/tree/orion-14b

**Comment by arch-btw** [comment]
@sorasoras @benxh1995 @Engininja2 it got merged today: https://github.com/ggerganov/llama.cpp/commit/f2e69d28c01303ca9dc79907f89ef120a6ac4a92

**Comment by sati-bodhi** [comment]
Has this issue been resolved? I read that support has been added, but I am still getting this error:
```
llm_load_tensors: ggml ctx size =    0.34 MiB
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 444, got 363
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model './models/Orion-14B-Chat/ggml-model-f16.gguf'
```

**Comment by sorasoras** [comment]
same, I got wrong number of tensors as well @arch-btw
