### ISSUE TITLE
Question : I found out that somehow generating with server differs to using regular /main

### ISSUE THREAD

**Issue by x4080** [ggerganov/llama.cpp#5069]
Hi, I'm using my fine tuned model (non english language) using chatlm prompt template (all works great) - but lately I found that server resulted in premature '<|im_end|>' token before the generation finish - this causes my UI stop generating

Then I enter the exact prompt using ./main and it wont generate that premature token. I made sure that all temp, min_p etc the same, so what can make difference between the 2 ?

server
```
const result = await fetch("http://127.0.0.1:8080/completion", {
    method: 'POST',
    body: JSON.stringify({
      prompt: prompt,
      temperature: 0.3,
      top_k: 50,
      top_p: 1,
      min_p: 0.1,
      n_keep: 0,
      n_predict: -1,
      repeat_penalty:1.1,
      stop: stopToken, // stop completion after generating this
      stream: true,
    })
  })
```

./main
```
./main -ngl 33 -t 0 -m ./models/mymodel.gguf --color --temp 0.3 -n -1 -f prompts/testprompt.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 4096 -r "<|im_end|>"
```

BTW the server cant run with -t 0. That 1 difference that I found

Anyone get this weird result also, or I just the outlier here

TIA

**Comment by jboero** [comment]
The server example (UI) sets a sneaky value for "stop" [] symbols so you may want to take a look at that. It's not actually exposed in the UI but if you run server in verbose mode it shows what is uses. I forget the latest but something like this:

`["</s>", "Llama", "llama", "User", "user", "system:"]`

This variable is also called `antiprompt` in server.cpp which can be confusing. If you change the prompt template and rename Llama or User it can really throw things off without changing the stop values which are fixed in server.

**Comment by jboero** [comment]
Here is the actual line that's from:
https://github.com/ggerganov/llama.cpp/blob/6f9939d119b2d004c264952eb510bd106455531e/examples/server/server.cpp#L2632

**Comment by x4080** [comment]
@jboero Thanks for answering. I tried removing the stoptoken and it displays the <|im_end|> (which is not correct compares to using ./main command), so the question persists how can it have different behaviour

**Comment by lastrosade** [comment]
It's possible that I am having the same issue. https://github.com/ggerganov/llama.cpp/discussions/4949

**Comment by x4080** [comment]
hi @lastrosade I already use n -1, and the reason it stopped because there's <|im_end|> generated prematurely which is not happening using ./main

I tried things and decreasing the temp help for server, but the question remains, why can it be differ between the server and ./main
