### ISSUE TITLE
FileNotFoundError: spm vocab not found.

### ISSUE THREAD

**Issue by xencodes** [ggerganov/llama.cpp#5095]
I am getting the following error while running the `convert.py`. I have already downloaded 7b-chat model from Meta.

<img width="751" alt="Screenshot 2024-01-23 at 13 42 08" src="https://github.com/ggerganov/llama.cpp/assets/31907722/44900c0d-e655-4bcf-855b-66a53e62d654">

```bash
❯ python3 convert.py --outfile models/7B/ggml-model-f16.bin --outtype f16 ../models/llama-2-7b-chat
Loading model file ../models/llama-2-7b-chat/consolidated.00.pth
params = Params(n_vocab=32000, n_embd=4096, n_layer=32, n_ctx=2048, n_ff=11008, n_head=32, n_head_kv=32, n_experts=None, n_experts_used=None, f_norm_eps=1e-06, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=<GGMLFileType.MostlyF16: 1>, path_model=PosixPath('../models/llama-2-7b-chat'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': None, 'tokenizer.json': None}
Traceback (most recent call last):
  File "/Users/monawwar/Research/llama/llama.cpp/convert.py", line 1471, in <module>
    main()
  File "/Users/monawwar/Research/llama/llama.cpp/convert.py", line 1439, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monawwar/Research/llama/llama.cpp/convert.py", line 1315, in load_vocab
    path = self._select_file(vocabtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monawwar/Research/llama/llama.cpp/convert.py", line 1298, in _select_file
    raise FileNotFoundError(f"{vocabtype} vocab not found.")
FileNotFoundError: spm vocab not found.
```

<img width="1203" alt="Screenshot 2024-01-23 at 13 42 16" src="https://github.com/ggerganov/llama.cpp/assets/31907722/2abc9b59-ff69-4dac-952e-ec6f81387312">

OS: `Darwin 23.0.0 arm64 arm`
Python: `Python 3.11.7`

**Comment by xencodes** [comment]
My bad, I forgot to add tokenzier and checksum files in the models folder.

**Comment by xjj210130** [comment]
@xencodes  I download facebook llama-2-7b , there is only three files:
     checklist.chk  consolidated.00.pth  params.json
Could you tell me, how can i find the file: tokenzier and checksum .
Thanks

**Comment by jasoncwik** [comment]
@xjj210130 in the toplevel directory of your clone for https://github.com/facebookresearch/llama, you'll see `tokenizer_checklist.chk` and `tokenizer.model`. Copy those into the model directory, e.g.

```
 /nvme/git/llama $ cp tokenizer_checklist.chk tokenizer.model ../llama.cpp/models/llama-2-7b-chat
```

Perhaps the README.md should be updated; this is not obvious for first-time users.
