### ISSUE TITLE
Adding topic steering on layers 

### ISSUE THREAD

**Issue by benxh1995** [ggerganov/llama.cpp#5119]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Add the ability to set/apply `steers` on a layer by layer basis in order to ensure alignment with specific concepts, tokens or words. 

# Motivation

Based on recent papers and research on LLM steerability through applying `steer`s on specific layers, I believe that llama.cpp would greatly benefit from incorporating a feature like this. 

The colab in the section below should provide a very interesting application which results in far higher reasoning abilities, for example from a 3B.

# Possible Implementation

Links to known implementations:
https://github.com/Mihaiii/llm_steer
https://colab.research.google.com/github/Mihaiii/llm_steer/blob/main/demo/llm_steer_demo.ipynb

And

https://github.com/nrimsky/LM-exp/tree/main/steering

**Comment by Engininja2** [comment]
Fyi there was draft PR experimenting with steering vectors #1472.

**Comment by peerschuett** [comment]
I took a look at #1472 , but the structure of llama.cpp changed in the meantime too much. In #1472 the steering was done in this function https://github.com/ggerganov/llama.cpp/blob/95dc4d7270e04bef3792a61be9bb045cb74a9fc4/llama.cpp#L1192 , but the whole function doesn't exist in this form any more.
