### ISSUE TITLE
Crap output when using a GPU

### ISSUE THREAD

**Issue by GianlucaDeStefano** [ggerganov/llama.cpp#5124]
Hi, I am using llamacpp on a new system. 
My setup is the following: 

OS: ubuntu server 

GPU: RTX3080 
Cuda: 12.0 
Drivers: 525

llamacpp version: 0.2.29

The issue is that when I load the model on the GPU like so: 
```
llm = LlamaCpp(
    model_path=f"mistral-7b-openorca.Q5_K_M.gguf", n_ctx=1024 * 4, n_batch=1024, verbose=False, n_gpu_layers=60, temperature=0,
)
```
The model produces only this character here: ▅. 

If I instead load the model on the CPU like so: 
```
llm = LlamaCpp(
    model_path=f"mistral-7b-openorca.Q5_K_M.gguf", n_ctx=1024 * 4, n_batch=1024, verbose=False, n_gpu_layers=0, temperature=0,
)
```
I get readable text. 
Has someone encountered the same issue? 

I have a similar setup on another PC and there, this code works fine even on GPU.

**Comment by JohannesGaessler** [comment]
Wrong repository, you're using some variant of Python bindings. Unless you can reproduce the issue with one of the llama.cpp binaries.

**Comment by GianlucaDeStefano** [comment]
Oh, you are perfectly right! I will reopen the issue in the correct repo. 
Thanks
