### ISSUE TITLE
Finetuning Architecture Issue

### ISSUE THREAD

**Issue by TalonBvV** [ggerganov/llama.cpp#5125]
Hey, I am trying to finetune Zephyr-Quiklang-3b using llama.cpp finetuning feature.

The problem is, the material found online would suggest it can fine-tune practically any GGUF format model.
Although that has not been my experience this far.

I get the following output:
`load_model_hparams_gguf: arch=stablelm expected_arch=llama
GGML_ASSERT: examples/finetune/finetune.cpp:243: arch == expected_arch`

From the sounds of it, there is only a single supported model architecture which is llama.

I will dig a bit deeper into the source code to see if this assumption is wrong and give feedback here.

If anyone has seen this issue before please let me know of any work arounds you may have found.

**Comment by MotorCityCobra** [comment]
@ggerganov I want to do lora fine tuning on the Mistral 7B model.  
What am I in for? How much work might this take?

I know some C++ but I know nothing about what is going on as far as how a gguf model is created and how you would fine tune it in C++, but I am willing to learn.
Is it worth it for me to try? Any pointers?
