### ISSUE TITLE
I can't compile llama on my 5700xt. PLEASE, HELP ME! XD

### ISSUE THREAD

**Issue by selvaunidi** [ggerganov/llama.cpp#5128]
Hello everyone, I'm losing my gray hair trying to make the rx 5700 xt work. It looks like something with make, or some connection that cannot be established. I think my card is gfx1010, but I must have changed it to gfx1030. I will attach the logs. Anyone who can help, I would truly appreciate it! ubuntu 22.04.3 lts. b660m. kernel 6.5.0-15-generic . i3-12100F .  
 is not able to compile a simple test program.

-- Check for working CXX compiler: /opt/rocm/llvm/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/opt/rocm/llvm/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/user/prog/llama.cpp/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_9dc8a/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_9dc8a.dir/build.make CMakeFiles/cmTC_9dc8a.dir/build
    gmake[1]: Entrando no diretório '/home/user/prog/llama.cpp/build/CMakeFiles/CMakeTmp'
[CMakeOutput.log](https://github.com/ggerganov/llama.cpp/files/14058454/CMakeOutput.log)
[smi_hipconfig.txt](https://github.com/ggerganov/llama.cpp/files/14058460/smi_hipconfig.txt)
[CMakeError.log](https://github.com/ggerganov/llama.cpp/files/14058469/CMakeError.log)

    Building CXX object CMakeFiles/cmTC_9dc8a.dir/testCXXCompiler.cxx.o
    /opt/rocm/llvm/bin/clang++    -MD -MT CMakeFiles/cmTC_9dc8a.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_9dc8a.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_9dc8a.dir/testCXXCompiler.cxx.o -c /home/user/prog/llama.cpp/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_9dc8a
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9dc8a.dir/link.txt --verbose=1
    /opt/rocm/llvm/bin/clang++ CMakeFiles/cmTC_9dc8a.dir/testCXXCompiler.cxx.o -o cmTC_9dc8a 
    ld.lld: error: unable to find library -lstdc++
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_9dc8a.dir/build.make:100: cmTC_9dc8a] Erro 1
    gmake[1]: Saindo do diretório '/home/user/prog/llama.cpp/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_9dc8a/fast] Erro 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by Engininja2** [comment]
I think `sudo apt-get install libstdc++-12-dev` will resolve your current issue.

Unfortunately there is another issue in getting the RX 5700 XT to work with the hip backend. There's a bug in rocblas where it doesn't generate fallback Tensile libraries when compiled for GPUs like the 5700 XT. The fix for that was merged into AMD's development branch just yesterday ROCm/Tensile/pull/1862

**Comment by pintariching** [comment]
I had the same problem. I was compiling [tabby](https://github.com/TabbyML/tabby) and I couldn't compile their [llama-cpp-bindings](https://github.com/TabbyML/tabby/tree/main/crates/llama-cpp-bindings) crate. Installing `libstdc++-12-dev` fixed the issue and it's now compiling.
