### ISSUE TITLE
 make LLAMA_CUBLAS=1

### ISSUE THREAD

**Issue by OMN-LEGACY** [ggerganov/llama.cpp#5144]
-Wno-pedantic -Xcompiler "-Wno-array-bounds" -c ggml-cuda.cu -o ggml-cuda.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
make: *** [Makefile:429: ggml-cuda.o] Error 1

**Comment by sl33pyC01E** [comment]
I get the same error on CUDA toolkits 10.8, 11.3, and 11.8, on a 4090.

**Comment by divinity76** [comment]
post the full output of 
```
make clean;
make LLAMA_CUBLAS=1
```
in a code block
