### ISSUE TITLE
Performance decrease after using latest llama.cpp branch vs previous branch with ggml format

### ISSUE THREAD

**Issue by aahouzi** [ggerganov/llama.cpp#5150]
### Current Behavior:

- Built a previous branch of llama.cpp, that was using only ggml format, and now when using the latest branch with gguf format, I noticed a huge drop in performance.
- llama.cpp previous branch: https://github.com/ggerganov/llama.cpp/tree/dadbed99e65252d79f81101a392d0d6497b86caa
- The summary for llama2-7B and llama2-13B throughput numbers in this table:

| Throughput (q4_0, n_threads=32) | llama.cpp prev | llama.cpp latest | Drop 
| ---------| ---------| ---------|---------|
|  Llama2-7B  | 26.6 t/s   | 19.2 t/s |  27.8%
| Llama2-13B   | 16.25 t/s   | 11.8 t/s |  27.3%

### Steps To Reproduce:

```
# Windows

## llama.cpp latest
python convert.py <llama2-path>
quantize.exe <llama2-path>\ggml-model-f16.gguf <llama2-path>\ggml-model-q4_0.gguf q4_0
main.exe -m <llama2-path>\ggml-model-q4_0.gguf -p "Building a website can be done in 10 simple steps:" -n 512 -t 32 --no-mmap --ignore-eos

## llama.cpp prev
python convert.py <llama2-path>
quantize.exe <llama2-path>\ggml-model-f16.bin <llama2-path>\ggml-model-q4_0.bin q4_0
main.exe -m <llama2-path>\ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512 -t 32 --no-mmap --ignore-eos
```

### Environment:

- **OS:**  Win11
- **HW:** Intel Xeon w9-3495X, 56 cores, 128GB

**Comment by JohannesGaessler** [comment]
If you want any hope of finding out what caused this you'll need to do a git bisect and post the results. There are far too many changes to comb through otherwise.
