### ISSUE TITLE
[FEATURE REQUEST] q9_0 or q10_0 quantization ?

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#5153]
# Motivation

This may be deemed unnecessary, but my main reasoning for wanting this is easier imatrix measurements of Mixtral on 64GB RAM systems.
8 bit allows for around ~256 unique values, while 9 bit doubles this to 512 (while still keeping the file size under 64GB), or 10 bit which should be about ~60GB for ~1024 unique values.

This avoids CPU inference hitting the pagefile for 2x the precision of 8 bit, and should be effectively indistinguishable for the purpose of imatrix calculations.

**Comment by Artefact2** [comment]
Has anyone ever benched imatrix from Q8_0 vs imatrix from f16? If not I can try to get some figures up, but I suspect there's no measurable difference.

**Comment by sorasoras** [comment]
> Has anyone ever benched imatrix from Q8_0 vs imatrix from f16? If not I can try to get some figures up, but I suspect there's no measurable difference.

there is no meaningful difference between Q8_0 between FP16 when it come to imatrix, but I have not measure it precisely  
I just use imatrix from Q8_0 to quantize FP16 model.

**Comment by Artefact2** [comment]
Some preliminary data from KuroMitsu-11B. Imatrix from wiki.train.raw (2000*512), kv-divergence data from full wiki.test.raw.

| IQ2_XXS vs f16       | f16 imatrix          | Q8_0 imatrix         | Q3_K_M imatrix       |
|----------------------|---------------------:|---------------------:|---------------------:|
| ln(PPL(Q)/PPL(base)) | 0.27655 ±    0.00277 | 0.27412 ±    0.00276 | 0.27373 ±    0.00278 |
| KL-divergence avg    | 0.40282 ±    0.00182 | 0.40053 ±    0.00181 | 0.40284 ±    0.00182 |
| Same top             | 0.74710 ±    0.00107 | 0.74752 ±    0.00107 | 0.74674 ±    0.00107 |
| KL-divergence median | 0.18587              | 0.18466              | 0.18585              |
| KL-divergence q99    | 3.84714              | 3.84295              | 3.85415              |
| KL-divergence max    | 13.80216             | 13.73757             | 13.94745             |

**Comment by kalomaze** [comment]
> Some preliminary data from KuroMitsu-11B. Imatrix from wiki.train.raw (2000*512), kv-divergence data from full wiki.test.raw.
> 
> IQ2_XXS vs f16	f16 imatrix	Q8_0 imatrix	Q3_K_M imatrix
> ln(PPL(Q)/PPL(base))	0.27655 ± 0.00277	0.27412 ± 0.00276	0.27373 ± 0.00278
> KL-divergence avg	0.40282 ± 0.00182	0.40053 ± 0.00181	0.40284 ± 0.00182
> Same top	0.74710 ± 0.00107	0.74752 ± 0.00107	0.74674 ± 0.00107
> KL-divergence median	0.18587	0.18466	0.18585
> KL-divergence q99	3.84714	3.84295	3.85415
> KL-divergence max	13.80216	13.73757	13.94745

Very interesting. This issue can probably be disregarded, considering that q8_0 actually slightly *improves* the end imatrix calculation (within a margin of error difference, that is).
