### ISSUE TITLE
Finetune from text

### ISSUE THREAD

**Issue by zamalex** [ggerganov/llama.cpp#5170]
I'm trying to finetune vicuna model in custom text 

the fine tune script:
./finetune --model-base ~/llama.cpp/models/vicuna-7b-v1.5.Q4_K_M.gguf --train-data zam.txt --lora-out lora2.gguf --save-every 0 --threads 14 --ctx 25 --rope-freq-base 10000 --rope-freq-scale 1.0 --batch 1 --grad-acc 1 --adam-iter 64 --adam-alpha 0.001 --lora-r 4 --lora-alpha 4 --use-flash --sample-start /"/</s/>/" --include-sample-start --seed 1

then when trying to test the model after couple of hours i got unexpected results 
./main --model ~/llama.cpp/models/vicuna-7b-v1.5.Q4_K_M.gguf --lora lora2.gguf --prompt "tell me about zamalek club is"

the used dataset samples are something like :

`<s>
Zamalek` Sporting Club, commonly referred to as Zamalek, is an Egyptian sports club based in Giza. It is one of the most successful football clubs in Africa and the Middle East, and was the most titled with African tournaments in 20th century [5] The club is mainly known for its professional football team, which plays in the Egyptian Premier League, the top tier of the Egyptian football league system.
`<s>`
The club was founded on 5 January 1911 as Qasr El Nile Club and was first headed by the Belgian lawyer George Merzbach. The name was changed two years later to Cairo International Sports Club (C.I.S.C.),[8] colloquially El Qāhirah El Mokhtalat Club or El Mokhtalat Club. The club was renamed in 1941 after King Farouk of Egypt and became known as Farouk El Awal Club (transl. Farouk I Club). After the 1952 Egyptian revolution, the club changed its name again to Zamalek SC.

Do I miss something ?

**Comment by daboe01** [comment]
maybe one training example is not enough for a good finetune?
