### ISSUE TITLE
Help populating the examples README.md files

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#518]
For now I just added empty README.md files:

- https://github.com/ggerganov/llama.cpp/tree/master/examples/main
- https://github.com/ggerganov/llama.cpp/tree/master/examples/quantize
- https://github.com/ggerganov/llama.cpp/tree/master/examples/perplexity
- https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding
- etc.

It would be great to add usage instructions and various tips and tricks for better experience for each example.

Great task for initial contributions

**Comment by eddiebarry** [comment]
Hey ggerganov,

would you appreciate me adding a chat-GPT4all.sh script ?

**Comment by HughMungis** [comment]
> Hey @ggerganov,
> 
> would you appreciate me adding a chat-GPT4all.sh script ?

I certainly would
