### ISSUE TITLE
Metal implementation on Matrix multiplication

### ISSUE THREAD

**Issue by DerrickYLJ** [ggerganov/llama.cpp#5197]
I am running llama.cpp on metal gpu. However, when I dive into the kernel for Metal implementation, I find that matmul is organized and implemented by `QK_K` value. 
(1) Does that `QK_K` refer to size of quantized range? 
(2) Moreover, can anyone also briefly explain the naming logic behind matmul kernel function  `kernel_mul_mv_q4_K_f32_impl`? What does "mv", "q4", "K", and "f32" associate with the inputs specifically?

Thanks!

**Comment by DerrickYLJ** [comment]
> 
> 
> MV = Matrix  x Vector so ``` mul_mv ``` is multiply matrix and vector.
> 
> 
> 
> q4 = Means Weights are 4 bit quantized,  so an in kernel dequantization happens as gpu cant understand the 4 bit data type natively, this dequantization is tailored for 4 bit weights. There must be multiple dequantization blocks implemented for each quantization scheme ( 4 bit , 8 bit, mixture of 4 and 8 bits etc)
> 
> 
> 
> F32 = The 4 bit weights are dequantized to float32 values for multiplication with float32 input tensor ( activation) and the resulting output tensor ( activation)  after calculation is of float32 data type.

Thank you for your reply! Is there also a metal kernel for standard matrix multiplication involving quantization inside llama.cpp?

**Comment by Nick-infinity** [comment]
If "Standard" means matrix multiplication with non-quantized f16 and f32 weights then there must be kernel,  as float 16 and float 32 models are also supported on Metal.

**Comment by ggerganov** [comment]
See the `kernel_mul_mm_impl` template

**Comment by DerrickYLJ** [comment]
Thank you all for the reply!

I have some follow-up questions regarding the specifics of the implementation.

(1) In the implementation of `kernel_mul_mv_q4_0_f32 `, it calls the function of `mul_vec_q_n_f32_impl` to directly perform the multiplication between the vector and the matrix. I would assume it's trying reconstruct the quantized of the vector and perform multiplication between the vector and matrix. However, it doesn't seem to exist the `scales` and `zero-point` necessary for reconstructing values from quantized weights. Am I missing anything here?

(2) Is there any naming logic behind parameters `ne` and `nb`, such as parameters I found in `rope_t`, in which `rope_t` cotains parameters `ne00, ne01, ne02, ne03, nb00, nb01, nb02, nb03, ne0, ne1, ne2, ne3, nb0, nb1, nb2, nb3`. Do they represent the dimensions of the input?

Thank you very much!

**Comment by fiskrt** [comment]
For (2) `ne` is the number of **e**lements in each dimension and so a 2x3 matrix would be `ne=[3,2,1,1]`
and `nb` is the stride in **b**ytes so a row-major matrix would be `[1,3,1,1]`.

Since tensors are always represented in 4 dims we need 4 ints for each element in `ne` and `nb` to describe one, and then just use have a 0 in-front for the second matrix.
@DerrickYLJ
