### ISSUE TITLE
Unable to get reproducible results

### ISSUE THREAD

**Issue by DivyaKanniah** [ggerganov/llama.cpp#5210]
hi ,

we have used quantised llama cpp model but we could see the results been inconsistent , we also have set the temperature to 0 . how to achieve reproducible results each time when the model is loaded

**Comment by Jeximo** [comment]
Consider the seed value as [it adds RNG to text generation](https://github.com/ggerganov/llama.cpp/blob/8f8ddfcfadc830b936318c3ea9fe2e8e3365aa85/examples/main/README.md?plain=1#L261), so set it to some consistent #.
