### ISSUE TITLE
Must the number of expertrs in Mixtral-MoE be a pow of 2 ?

### ISSUE THREAD

**Issue by ZhangEnmao** [ggerganov/llama.cpp#5213]
Hi, friends. I have got an information that the number of expertrs in Mixtral-MoE must be a pow of 2. Otherwise, llama.cpp will not work. Is it true ?

**Comment by slaren** [comment]
In CUDA and Metal the number of experts must be a power of two. This is because the sort operation used to select the top-k experts only works with powers of two. With CPU there is no such restriction.

**Comment by ZhangEnmao** [comment]
> In CUDA and Metal the number of experts must be a power of two. This is because the sort operation used to select the top-k experts only works with powers of two. With CPU there is no such restriction.

Hello, thank you very much for your explanation. I think I have a good grasp of the reasons, but I still have a slight doubt I'd like to clarify with you. Are you saying that in the current top-k implementation in llama.cpp, if model inference involves using the GPU, the number of experts must be a power of two? Is it possible to remove this restriction by modifying certain parts of the llama.cpp code locally?

**Comment by slaren** [comment]
The argsort kernels would need to be updated to support non-pow2 number of columns.
