### ISSUE TITLE
Vulkan: Output quality degraded with long initial prompts, large gen amounts and long context sizes.

### ISSUE THREAD

**Issue by LostRuins** [ggerganov/llama.cpp#5241]
Already confirmed this with @0cc4m but just logging it here to keep track:

With Vulkan, `-c`=2048, `-b`=512, initial prompt of at least 1.2k tokens, generating a large number of tokens, with all GPU layers offloaded.

Sample of incoherent output:
```
You have the power to make your own rules. What you say, goes. You can make your own th order. From the tall you say, to the long you say. And the tall says, to the long says. I is the person who would let you know
```

Does not happen if offloading 0 layers.

**Comment by 0cc4m** [comment]
I haven't been able to reproduce this anymore. Please reopen this and add details if you still see it.
