### ISSUE TITLE
calm2-7b-chat model : unable to load model 

### ISSUE THREAD

**Issue by ShikouMochizuki** [ggerganov/llama.cpp#5251]
```
./main -m ../calm2-7b-chat/ggml-model-f16.gguf -p "### Instruction: How high is mount everest? ### Response:"
```
generates following error
```
llama_model_load: error loading model: _Map_base::at
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../calm2-7b-chat/ggml-model-f16.gguf'
main: error: unable to load model
```
any ideas?

----
what i did
1. download this model（ https://huggingface.co/cyberagent/calm2-7b-chat ）
2. convert this model to GGUF using `convert.py`

    ```
   python3 convert.py --vocab-type hfft --pad-vocab ../calm2-7b-chat/
   ```
3. This resulted in the creation of `ggml-model-f16.gguf`

**Comment by themanyone** [comment]
New to this, so not sure what's happening here. But a lot of consumer hardware does not use 16-bit float. Only a few graphics cards and TPU devices support it. So try a 32-bit model?

It is also necessary to compile without `LLAMA_CUBLAS_F16=1` on this particular laptop. But you might use it if hardware supports Bfloat16.

Of course maybe `llama.cpp` it's supposed to convert to 32-bit on the fly for hardware that doesn't support it? I don't want to download a huge model to test it.

**Comment by ShikouMochizuki** [comment]
Thank you for the advice

Here are the specifications for my GPU and CPU:
GPU: NVIDIA GeForce RTX 4090
CPU: 13th Gen Intel(R) Core(TM) i9-13900KF

The GPU supports 16-bit.
I also tried a model converted to 32-bit, but encountered the same error.
