### ISSUE TITLE
calls to `ggml_cpy_f32_f16_cuda()` need updating from commit 625a699 

### ISSUE THREAD

**Issue by dusty-nv** [ggerganov/llama.cpp#5258]
Commit https://github.com/ggerganov/llama.cpp/commit/625a699b5456994bc32a8093d53818f60ceda6d1 started producing this build error when `GGML_CUDA_FP16` is enabled:

```bash
llama.cpp/ggml-cuda.cu(8662): error: argument of type "cudaStream_t" is incompatible with parameter of type "int"
                                  ne00, 1, sizeof(half), 0, 0, stream);
                                                               ^
llama.cpp/ggml-cuda.cu(8662): error: too few arguments in function call
                                  ne00, 1, sizeof(half), 0, 0, stream);
```

It appears because arguments were added to: 
https://github.com/ggerganov/llama.cpp/blob/ce32060198b7e2d6a13a9b8e1e1369e3c295ae2a/ggml-cuda.cu#L7429 but this call to it wasn't updated:  https://github.com/ggerganov/llama.cpp/blob/ce32060198b7e2d6a13a9b8e1e1369e3c295ae2a/ggml-cuda.cu#L8660

**Comment by slaren** [comment]
Fixed in #5262
