### ISSUE TITLE
Vulkan multi or selectable GPU?

### ISSUE THREAD

**Issue by Ph0rk0z** [ggerganov/llama.cpp#5259]
So trying vulkan, it picks the first card available, my P100. I also can't seem to split models which may be a limitation of the backend as it is. CUDA_VISIBLE_DEVICES obviously doesn't work.

Is there a way to select which GPU vulkan will pick and use it over more than one card? Perhaps I missed something?

**Comment by 0cc4m** [comment]
Yes, there is the environment variable `GGML_VULKAN_DEVICE`. You can set it to a number. `0` for the first GPU (default behaviour, `1` for the second, and so on. Eventually I'll replace it with the backend initialization parameter, then it gets picked with the main GPU parameter of main.

**Comment by Ph0rk0z** [comment]
Ok will try it. No splitting yet tho, right?

**Comment by 0cc4m** [comment]
No, not yet.

**Comment by mistrjirka** [comment]
> `GGML_VULKAN_DEVICE`

That does not seem to work anymore:
[jirka@grammetry llama.cpp]$ GGML_VULKAN_DEVICE=0 ./build_vulkan/bin/llama-bench -m models/Qwen3-4B-Instruct-2507-IQ4_NL.gguf -p 2048 -n 64
ggml_vulkan: Found 2 Vulkan devices:
ggml_vulkan: 0 = NVIDIA GeForce RTX 3060 Ti (NVIDIA) | uma: 0 | fp16: 1 | bf16: 1 | warp size: 32 | shared memory: 49152 | int dot: 1 | matrix cores: NV_coopmat2
ggml_vulkan: 1 = NVIDIA GeForce RTX 3060 (NVIDIA) | uma: 0 | fp16: 1 | bf16: 1 | warp size: 32 | shared memory: 49152 | int dot: 1 | matrix cores: NV_coopmat2
| model                          |       size |     params | backend    | ngl |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | --------------: | -------------------: |
| qwen3 4B IQ4_NL - 4.5 bpw      |   2.21 GiB |     4.02 B | Vulkan     |  99 |          pp2048 |      1962.75 ± 19.42 |
| qwen3 4B IQ4_NL - 4.5 bpw      |   2.21 GiB |     4.02 B | Vulkan     |  99 |            tg64 |         91.43 ± 4.11 |

build: ace6a54 (1)

You can see that I selected device 0 and it still uses both gpus (I checked the usage too and it is using both)

**Comment by 0cc4m** [comment]
It was long ago renamed to `GGML_VK_VISIBLE_DEVICES`, you can use it like `CUDA_VISIBLE_DEVICES` with values like `0`, `0,1`, `1,0`, etc.

Otherwise you can also pick a device with the parameter `--device` (`--list-devices` to see what is available`).
