### ISSUE TITLE
wrong docker run instructions

### ISSUE THREAD

**Issue by fedecompa** [ggerganov/llama.cpp#5264]
docker run -v /path/to/models:/models -p 8000:8000 ghcr.io/ggerganov/llama.cpp:server -m /models/7B/ggml-model-q4_0.gguf --port 8000 --host 0.0.0.0 -n 512

It seems the command to run the docker image to deploy the server is not working, the -m parameter seems to be a memory bound docker run option. Maybe you wanted to pass an environment variable?

**Comment by slaren** [comment]
If there is a conflict with a docker parameter of the same name, `--model` instead may work.

**Comment by fedecompa** [comment]
On windows the command fails with error: 

"llama_model_load: error loading model: failed to open /models/mistal-InfoSynth-Q4_K_M.gguf: No such file or directory
llama_load_model_from_file: failed to load model"

Any idea why this happens?

**Comment by Brensom** [comment]
> On windows the command fails with error:
> 
> "llama_model_load: error loading model: failed to open /models/mistal-InfoSynth-Q4_K_M.gguf: No such file or directory llama_load_model_from_file: failed to load model"
> 
> Any idea why this happens?

I have the same problem on Linux.
```
llama_model_load: error loading model: failed to open /Yi-34B-GGUF/yi-34b.Q5_K_M.gguf: No such file or directory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/Yi-34B-GGUF/yi-34b.Q5_K_M.gguf'
```

**Comment by fedecompa** [comment]
The same identical command on the WSL2 shell worked for me...I suspect there is a platform dependent bug

**Comment by fedecompa** [comment]
With docker-compose it works also on windows: 

    command: --model /models/mistal-InfoSynth-Q4_K_M.gguf --port 8000 --host 0.0.0.0 --threads 10 --ctx-size 1024
