### ISSUE TITLE
Llava 34b model is working with llamacpp?

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#5266]
Llava 34b model is working with llamacpp?

**Comment by cmp-nct** [comment]
I'm struggling to get the ViT working, it has a different mlp shape (much larger)
Overall if you use the draft PR https://github.com/ggerganov/llama.cpp/pull/5267 you can convert and inference llava-1.6

But at lower quality input images, likely breaking the finetune a bit. 
I tested the 13B already and it works very well, despite all those shortcommings

**Comment by cjpais** [comment]
ive got some basic quants for 34b generated from a hacked up script, seems to work alright. surely the pr mentioned above will improve it further

[hf link](https://huggingface.co/cjpais/llava-v1.6-34B-gguf)

not sure if this kosher to share here or not, but give a go

**Comment by svenstaro** [comment]
This issue should be closed as LLaVA v1.6 support is now merged.

**Comment by BarfingLemurs** [comment]
@mirek190 working!
