### ISSUE TITLE
cs_co_variant(): LLVM ERROR stack trace with Vulkan on mesa (llvmpipe)

### ISSUE THREAD

**Issue by themanyone** [ggerganov/llama.cpp#5269]
Reproducing the bug: seed  = 1706834894
on git commit 128dcbd3c9c4b12f42b560a4430427d7b2828628 (HEAD -> master, origin/master, origin/HEAD)

[chatlog.txt](https://github.com/ggerganov/llama.cpp/files/14132701/chatlog.txt)
[main.log](https://github.com/ggerganov/llama.cpp/files/14132723/main.log)
[vulkaninfo.txt](https://github.com/ggerganov/llama.cpp/files/14132812/vulkaninfo.txt)
[vulkaninfo_summary.txt](https://github.com/ggerganov/llama.cpp/files/14132822/vulkaninfo_summary.txt)

$ sysinfo
CPU: quad core Intel Core i7-2720QM (-MT MCP-)
speed/min/max: 1389/800/3300 MHz Kernel: 6.6.13-200.fc39.x86_64 x86_64
Up: 13h 24m Mem: 1.37/23.42 GiB (5.8%) Storage: 476.94 GiB (7.8% used)
Procs: 502 Shell: Bash inxi: 3.3.31

Stack trace:

> LLVM ERROR: Cannot select: 0x7f6f682bef70: f32,ch = load<(load (s16) from %stack.36), anyext from i16> 0x7f6f682befe0, FrameIndex:i64<36>, undef:i64
>   0x7f6f6824e3c0: i64 = FrameIndex<36>
>   0x7f6f682c8710: i64 = undef
> In function: cs_co_variant
> /home/u/bin/chat.sh: line 1: 26708 Aborted                 (core dumped) llama_cpp -m ~/.local/share/models/mistral-7b-instruct-v0.1.Q3_K_S.gguf --no-display-prompt --multiline-input --color --interactive-first -p "You are a helpful and knowledgeable assistant. $@"

**Comment by themanyone** [comment]
Happens consistently with larger prompts.
`gdb` backtrace: 
[bt.txt](https://github.com/ggerganov/llama.cpp/files/14132965/bt.txt)

**Comment by 0cc4m** [comment]
LLVMPipe is a CPU Vulkan Implementation that is meant as a fallback when you need to run a graphical application without a GPU. There is no point in supporting it with Vulkan, just use the base build or OpenBLAS.
