### ISSUE TITLE
Build option -DLLAMA_SYCL_F16=ON is ignored on Windows when building with SYCL

### ISSUE THREAD

**Issue by Jacoby1218** [ggerganov/llama.cpp#5271]
Didn't notice this before, but when building with SYCL on Windows, -DLLAMA_SYCL_F16=ON is ignored when built following the instructions given in the README.

**Comment by airMeng** [comment]
I believe it has been fixed in https://github.com/ggerganov/llama.cpp/pull/5254, can you confirm?

**Comment by Jacoby1218** [comment]
No, hasn't been fixed. Build option is still ignored.

**Comment by airMeng** [comment]
@Jacoby1218 Could you provide the full log of building? I don't see any difference in CMakeLists.txt options between windows and linux.

**Comment by Jacoby1218** [comment]
Nothing in the log indicates why this is happening, https://pastebin.com/rHAM0UjA

**Comment by characharm** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/123120856/9cc3fe59-f9b6-4a95-bd7b-0755542afebb)

**Comment by airMeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/123120856/302035584-9cc3fe59-f9b6-4a95-bd7b-0755542afebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjQwOTcsIm5iZiI6MTcwNjk2Mzc5NywicGF0aCI6Ii8xMjMxMjA4NTYvMzAyMDM1NTg0LTljYzNmZTU5LWY5YjYtNGE5NS1iZDdiLTA3NTU1NDJhZmViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMjM2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzYzYzY1MmUwYWM3MDExYmUwZDk3M2M1YzkwODA2ZTZjMDE4ZTEwZGIyNTZiMDU4NWJhNjhlNGVlZmFkM2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OzWxWzFFQrJVSF6Oje5HiIBzXdMeNJF6i4OC9BUMbNQ)

@Jacoby1218 if you are referring this, has been fixed in https://github.com/ggerganov/llama.cpp/pull/5270/commits/621e60e48426c2897fd0ccf322e350a429a86cf2 as characharm shows

**Comment by NeoZhangJianyu** [comment]
@Jacoby1218 
Could you try again and feedback?
