### ISSUE TITLE
Coalescence: Potential large speedups in generation for constrained grammars

### ISSUE THREAD

**Issue by Azeirah** [ggerganov/llama.cpp#5292]
I came across [this discussion](https://www.reddit.com/r/LocalLLaMA/comments/1ah8e9v/coalescence_making_llm_inference_5x_faster/kon4fa0/?context=3) about [this blogpost](https://blog.dottxt.co/coalescence.html)

The blogpost is extremely clear, so I won't spend a lot of time summarising the idea, but here goes:

A constrained grammar can be expressed as a finite state machine, coalescence is a strategy to optimise this FSM so we can skip deterministic patterns in the state machine.

The idea is simple: you can skip state transitions that are guaranteed (Ie, if your grammar includes a word "hello", you don't have to run the LLM to output "hello").

The post outlines how you can do this in a way that is compatible at a token-level, instead of at a character-level.

The more constrained your grammar is, the more speedups this approach can provide.

**Comment by 0xdevalias** [comment]
I know this got closed as stale.. but it sounds like a pretty interesting feature.. I wonder how hard it would be to support?

**Comment by Azeirah** [comment]
> I know this got closed as stale.. but it sounds like a pretty interesting feature.. I wonder how hard it would be to support?
> 
> See also:
> 
>     * [Are deterministic tokens skipped when using grammar constraints? #5455](https://github.com/ggml-org/llama.cpp/discussions/5455)

I personally think it's worth doing. I believe it has been demonstrated somewhere that limiting the token vocabulary makes the model dumber, but grammars do that _anyway_.

This method can produce huge speedups and cost savings for simple LLM-powered tasks like "convert to JSON", "convert to YAML".

Let the model do the thinking, let the grammar do the structure.

**Comment by hosseinalipour** [comment]
You can achieve this by repeatedly calling the completion API, which takes a prompt as a simple string. By enabling grammar, you can restrict the model to only produce the output you want. This allows you to call completion as many times as needed to fully generate the text with placeholders removed. You'll likely need to implement this yourself, as it requires a fair amount of customization to fit your specific use case.
