### ISSUE TITLE
Infinity transcript mode may stuck in ram?

### ISSUE THREAD

**Issue by FNsi** [ggerganov/llama.cpp#530]
After ctx > 2048 or whatever set in -c, While close the terminal, the transcript may have a chance continuously running in system.

Linux amd64 5.19 ubuntu base.

**Comment by FNsi** [comment]
> After ctx > 2048 or whatever set in -c, While close the terminal, the transcript may have a chance continuously running in system.
> 
> Linux amd64 5.19 ubuntu base.

Also may just Because my system.

**Comment by gjmulder** [comment]
[Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1)

**Comment by FNsi** [comment]
> [Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1)

Sorry, I reproduce it in any software😅😂 it's obvious because my system.
