### ISSUE TITLE
Impossible to quantize llamantino-2 70b to gguf

### ISSUE THREAD

**Issue by ivanfioravanti** [ggerganov/llama.cpp#5306]
I'm able to convert https://huggingface.co/swap-uniba/LLaMAntino-2-70b-hf-UltraChat-ITA after removing added_token.json file, fil gguf is created.

But when I run quantize booom: gguf_init_from_file: invalid magic characters ''

I'm using latest llama.cpp.

What can be the problem?

**Comment by ggerganov** [comment]
What conversion script are you using? To get this error, it means it didn't write the GGUF header. Also, this happens if you pass an empty file

**Comment by ivanfioravanti** [comment]
the standard convert.py with model in link 🤷‍♂️ something odd in the model for sure. We can close this issue in case.

**Comment by R3xpook** [comment]
> the standard convert.py with model in link 🤷‍♂️ something odd in the model for sure. Feel free to close this issue in case.

prova ad eliminare added_tokens.json
