### ISSUE TITLE
Question: does n_predict have an unreasonably large default value?

### ISSUE THREAD

**Issue by channeladam** [ggerganov/llama.cpp#5308]
Hi, I'm new to llama.cpp - sorry if I'm asking a stupid question.

I built server with SYCL running on Intel Arc A770.

When POSTing to the server, if n_predict is not specified then the performance is terrible, and/or it appears to hang - especially if stream: true also is not specified.

I was trying to use llama.cpp via various VSCode extensions, and also tried running them through api_like_OAI.py. 
I was about to ditch llama.cpp because it didn't appear to work.

But then I diagnosed that the issue happens when n_predict and stream:true are not specified in the POST payload. (which appears to be lacking from many VSCode extensions!)

So my workaround right now is to modify api_like_OAI.py to default n_predict to say 100 and stream: true and it responds quickly as I would have expected.

If I just specify stream:true, it runs and streams back for a least a few minutes (until I eventually killed it!)

Am I doing something wrong? Is this expected?  Is there an internal default value for n_predict or is it a very large number?

Thank you!

**Comment by ggerganov** [comment]
If the generated response is less than 100 tokens, it does not matter if you set `n_predict` to 100 or 1000 - it will take the same amount of time. Maybe there is nothing to terminate the generation (like EOS token or reverse prompt), so it keeps generating forever. It's hard to tell without some debug info
