### ISSUE TITLE
Building with NDK

### ISSUE THREAD

**Issue by Jeximo** [ggerganov/llama.cpp#5312]
Hi, I'm using latest [llama.cpp](https://github.com/ggerganov/llama.cpp/commit/52bb63c7082c859c3f1dfc527227e6a95b299c7c), and I want to build with `cmake`.

I've followed instruction in the [Readme.md](https://github.com/ggerganov/llama.cpp#building-the-project-using-android-ndk), and https://github.com/JackZeng0208/llama.cpp-android-tutorial, with the latest toolchain: [android-ndk-r26b](https://github.com/lzhiyong/termux-ndk/releases/tag/android-ndk)

`$NDK` returns the correct path `/data/data/com.termux/files/home/android-ndk-r26b`. 

The command is `cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-26 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..`

**Error**:
```
git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
mkdir build
cd build

cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-26 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown

CMake Error at CMakeLists.txt:2 (project): The CMAKE_C_COMPILER: /data/data/com.termux/files/home/android-ndk-r26b/toolchains/llvm/prebuilt/linux-aarch64/bin/clang is not a full path to an existing compiler tool.

Tell CMake where to find the compiler by setting either the environment variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name if it is in the PATH.                                                         
                                                           
CMake Error at CMakeLists.txt:2 (project): The CMAKE_CXX_COMPILER: /data/data/com.termux/files/home/android-ndk-r26b/toolchains/llvm/prebuilt/linux-aarch64/bin/clang++ is not a full path to an existing compiler tool.

Tell CMake where to find the compiler by setting either the environment variable "CXX" or the CMake cache entry
CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler name if it is in the PATH.
                                                                                                          
-- Configuring incomplete, errors occurred!
```

I'm trying to point `cmake` to the toolchain located in  `$NDK/build/cmake/android.toolchain.cmake`. 

I tried the direct path which also failed, 
 `cmake -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/home/android-ndk-r26b/build/cmake/android.toolchain.cmake`

Here's an identical issue closed with no fix(i used an online chinese/english translator): https://github.com/JackZeng0208/llama.cpp-android-tutorial/issues/1

Thanks for any direction.

**Comment by alex4o** [comment]
Just don't build with the ndk install llvm and clang and build with them it works fine for me even with opencl

**Comment by Jeximo** [comment]
> Just don't build with the ndk. 

Thanks for your response.  I understand it's possible to build without it,  but I'm trying to build _**with**_ NDK.

```
❯ clang --version
clang version 17.0.6
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin

~
❯ pkg info llvm
Package: llvm
Version: 17.0.6
```
