### ISSUE TITLE
Completion results change with the amount of memory available on a Mac?

### ISSUE THREAD

**Issue by pgorzelany** [ggerganov/llama.cpp#5314]
I am using a current version of llama.cpp (191221178f51b6e81122c5bda0fd79620e547d07). I am trying to use the package in a Swift project, following examples in llama.swiftui.

I am running inference on mistral-7b-openorca.Q4_0.gguf.

Normally I am using a MacBook Pro, M1 Max with 64GB of memory. Everything was working fine, the model provided good clear responses. However, when I tested a build on a Mac mini with 8GB of memory, with exactly the same parameters, the model output was complete gibberish. 

Is this a known limitation? Maybe I am doing something wrong in my setup.

**Comment by ggerganov** [comment]
I have a 8GB Mac Mini and the CLI tool `main` seems to work ok with this model. I haven't setup Xcode to test Swift though, so can't confirm. Can you provide some debug logs - like the output that you get on M1 Max vs the one on Mac Mini

**Comment by pgorzelany** [comment]
First of all, thank you for all this you are doing @ggerganov much appreciated!

Don't know if its helpful but here is the output when running on an MacBook Pro M1 Max, 64GB of RAM
<img width="881" alt="Screenshot 2024-02-06 at 22 10 02" src="https://github.com/ggerganov/llama.cpp/assets/3740966/57ab577b-30f7-40b3-bb07-b3f1dbc60479">

And here is the output when running on M2 Mac mini with 8GB of RAM
![Screenshot 2024-02-03 at 11 56 18AM](https://github.com/ggerganov/llama.cpp/assets/3740966/70c2dd5f-bca7-4325-812c-c3ccb7b38ac3)

The seed and all other parameters where exactly the same for both builds so the output should be deterministic.

If `main` works I would suspect that my setup is wrong because frankly I don't really know what I am doing :D I don't really know C++ well enough to understand the project. I tried following the [llama.swiftUI](https://github.com/ggerganov/llama.cpp/blob/master/examples/llama.swiftui/llama.cpp.swift/LibLlama.swift) example but quickly found out that the hardcoded values all around that file just don't work when you try to have a longer conversation with the model.

I would really use some documentation on `llama_model_params` and `llama_context_params`. For example what `n_batch` and what its relation to `n_ctx`. Should they be the same? Also when initialising the batch with `llama_batch_init` should the allocation be equal to `n_batch`? What is `n_threads` and what is its relation to `n_threads_batch`? Should they be the same? Should I set it to the number of cors the MacBook has or should I set it to 1 because we are using Metal with GPU?

If you could point me to some docs or an in depth tutorial about those that would be awesome!

**Comment by pgorzelany** [comment]
It would be really great if you could have a quick look at [llama.swiftUI example](https://github.com/ggerganov/llama.cpp/blob/master/examples/llama.swiftui/llama.cpp.swift/LibLlama.swift) and say if its correctly written. Even a hint like "oh man, that thing is way out of date and doesn't make sense, you should use main as reference" would be helpful.

**Comment by ggerganov** [comment]
The only docs currently are the `examples` in `llama.cpp`. They are mostly up-to-date. But you cannot expect from the `llama.swiftui` example to get complete chat experience - it just demonstrate basic usage.

From your screenshots, it seems you are using some 3rd party project - most likely the problem is there

**Comment by pgorzelany** [comment]
Thanks! In the screenshot it's actually my MacOS app that I developed. I am trying to use llama.cpp as a Swift package in the project. I will try to understand the `main` example better. I guess its the most up to date?
