### ISSUE TITLE
Please support bert based models.

### ISSUE THREAD

**Issue by superchargez** [ggerganov/llama.cpp#5317]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Bidirectional encoders (BERT based models) like BERT, RoBERTa, BART and other. Though they are not auto regressive (generative) but they are good at word substitution or multiclass classification. And their finetuned version outperform these base LLMs for the task they are finetuned and of course are faster because they have to choose from smaller set of possible values.

# Motivation

These small compared to these LLMs yet they are powerful, but perhaps if they are quantized then using them on edge devices might be even more easy. And you have already done GPT2, which is quite old as well.

# Possible Implementation

Now idea how can it be done.

**Comment by jkgenser** [comment]
I would also +1 to be able to use finetuned bert models, not only bert models for embedding
