### ISSUE TITLE
[Feature Suggestion] Load/Save current conversation's tokens into file

### ISSUE THREAD

**Issue by x02Sylvie** [ggerganov/llama.cpp#532]
Now that we have infinite transcription mode. Would it be possible to dump tokens into file and load them back next time you run llama.cpp to resume conversation?

Although it will be tricky to implement efficiently with long conversations, for example by
- storing prompt itself as tokens
- store in-between messages as raw text
- store last messages within ctx_size as tokens

**Comment by linouxis9** [comment]
Yes, this feature seems especially important to have to avoid having to go through the inference process each time for the initial prompt allowing faster startup (as discussed here: https://github.com/ggerganov/llama.cpp/issues/484#issuecomment-1483975437).

**Comment by anzz1** [comment]
This is kinda related and would fit well together 
- https://github.com/ggerganov/llama.cpp/pull/477

**Comment by anzz1** [comment]
@linouxis9 you are talking about a different thing though, saving the state and not just the tokens. separation of state and model is part of the [current roadmap](https://github.com/ggerganov/llama.cpp/discussions/457)

**Comment by linouxis9** [comment]
So basically Option A could also be implemented by just passing back the previous conversation as the initial prompt?
While what I'm more interested is Option B where we do not have to go through all the way to work again ;-)
I understand, thank you for your great analogy @anzz1!!
