### ISSUE TITLE
Vulkan backend performance is relatively slower at certain quants

### ISSUE THREAD

**Issue by Nindaleth** [ggerganov/llama.cpp#5323]
Radeon RX 6700 XT, Ryzen 5700X ECO, model mistral-7b-instruct-v0.2 fully oflloaded to the GPU. EDIT: ROCm 6.0

Some quantization methods implementations in the Vulkan backend provide relatively slower performance compared to ROCm. I think I saw a short by-the-way mention in one of the Vulkan PRs, but I can't find it and don't think it's formally tracked yet.

The Imatrix for IQ quants was generated via `./imatrix -m models//mistral-7b-instruct-v0.2.f16.gguf -f wiki.train.raw -o imatrix_mistral-7b-instruct-v0.2.dat --chunks 100 -ngl 99`

Here are my results (pp 512, tg 128) - build: 3c0d25c4 (2058):

|quant|pp ROCm|pp Vulkan|speedup|tg ROCm|tg Vulkan|speedup|
|---|---|---|---|---|---|---|
|Q4_0|1023.16 ± 6.75|309.84 ± 7.49|0.30283|59.07 ± 0.74|23.22 ± 0.49|0.39309|
|Q4_1|975.41 ± 0.90|305.72 ± 8.25|0.31343|55.43 ± 0.05|23.57 ± 0.30|0.42522|
|Q5_0|877.66 ± 0.29|305.66 ± 8.70|0.34827|52.28 ± 0.02|18.06 ± 0.46|0.34545|
|Q5_1|882.68 ± 0.29|301.63 ± 7.77|0.34172|48.09 ± 0.27|18.12 ± 0.30|0.37679|
|IQ2_XXS - 2.0625 bpw|784.87 ± 17.45|0 (crash)|0|69.23 ± 0.96|0 (crash)|0|
|IQ2_XS - 2.3125 bpw|791.96 ± 6.51|0 (crash)|0|67.07 ± 0.02|0 (crash)|0|
|Q2_K - Medium|568.34 ± 0.23|343.06 ± 11.07|0.60362|62.65 ± 0.04|46.81 ± 1.93|0.74717|
|Q2_K - Small|568.35 ± 14.34|357.88 ± 11.75|0.62968|70.54 ± 0.92|52.22 ± 2.50|0.74029|
|IQ3_XXS - 3.0625 bpw|774.91 ± 2.55|0 (crash)|0|64.47 ± 0.17|0 (crash)|0|
|Q3_K - Extra small|568.33 ± 0.31|353.28 ± 11.01|0.62161|55.18 ± 0.28|41.91 ± 1.46|0.75951|
|Q3_K - Small|561.03 ± 0.67|354.74 ± 10.68|0.6323|50.35 ± 0.02|38.33 ± 1.34|0.76127|
|Q3_K - Medium|639.43 ± 0.41|356.29 ± 10.20|0.5572|49.01 ± 0.28|41.18 ± 1.52|0.84024|
|Q3_K - Large|635.57 ± 0.22|356.60 ± 11.09|0.56107|48.24 ± 0.49|39.28 ± 1.39|0.81426|
|Q4_K - Small|839.04 ± 2.85|357.55 ± 11.31|0.42614|49.43 ± 0.38|50.41 ± 2.19|1.01983|
|Q4_K - Medium|828.36 ± 4.23|356.07 ± 11.95|0.42985|49.16 ± 0.18|48.97 ± 1.89|0.99614|
|Q5_K - Small|828.07 ± 0.26|355.19 ± 11.90|0.42894|46.73 ± 0.03|42.03 ± 1.51|0.89942|
|Q5_K - Medium|820.06 ± 0.38|355.25 ± 10.76|0.4332|46.47 ± 0.12|41.69 ± 1.56|0.89714|
|Q6_K|778.61 ± 0.43|337.14 ± 9.66|0.433|45.26 ± 0.25|41.60 ± 1.55|0.91913|
|Q8_0|1029.19 ± 4.60|307.54 ± 7.72|0.29882|37.19 ± 0.02|22.85 ± 0.63|0.61441|

**Comment by Artefact2** [comment]
Similar results in picture form, generated a few days ago.

![foo](https://github.com/ggerganov/llama.cpp/assets/90720/dce1311d-ea9d-4cb6-8ff5-6e43a90ca1e0)

**Comment by Nindaleth** [comment]
This is the state as of #5835 on 2024-03-02.

| quant  |  pp ROCm  |  pp Vulkan  |  speedup  |  tg ROCm  |  tg Vulkan  |  speedup  |
|---|---|---|---|---|---|---|
| Q4_0    | 1026.09 ± 0.47 |  423.82 ± 15.16 |  0.41304 | 59.78 ± 0.06  |  41.39 ± 1.74  |  0.69237 |
| Q4_1    | 973.64 ± 0.23  |  357.83 ± 8.75  |  0.36752 | 55.49 ± 0.03  |  40.46 ± 1.24  |  0.72914 |
| Q5_0    | 874.75 ± 2.77  |  357.05 ± 9.24  |  0.40817 | 52.47 ± 0.03  |  30.53 ± 0.79  |  0.58186 |
| Q5_1    | 881.33 ± 0.41  |  356.52 ± 10.69 |  0.40452 | 48.35 ± 0.03  |  29.08 ± 0.55  |  0.60145 |
| IQ2_XXS | 784.77 ± 9.74  |  0 (crash) |  0  |  69.66 ± 0.07  |  0 (crash) |  0 |
| IQ2_XS  | 792.08 ± 2.03  |  0 (crash) |  0  |  63.96 ± 0.05  |  0 (crash) |  0 |
| Q2_K_S  | 573.51 ± 1.58  |  352.20 ± 12.43 |  0.61411 | 71.30 ± 0.06  |  53.70 ± 1.93 |   0.75316 |
| Q2_K    | 567.70 ± 0.40  |  348.10 ± 12.63 |  0.61318 | 62.74 ± 0.05  |  48.79 ± 1.44 |   0.77765 |
| IQ3_XXS | 774.39 ± 1.32  |  0 (crash) |  0  |  62.63 ± 0.04  |  0 (crash) |  0 |
| Q3_K_XS | 567.65 ± 0.18  |  344.27 ± 9.59  |  0.60648 | 55.34 ± 0.05  |   44.44 ± 1.57 |   0.80304 |
| Q3_K_S  | 560.74 ± 0.13  |  350.40 ± 8.62  |  0.62489 | 50.58 ± 0.06  |   40.01 ± 1.02 |   0.79102 |
| Q3_K_M  | 638.09 ± 0.40  |  352.29 ± 9.34  |  0.5521  | 49.25 ± 0.06  |   43.66 ± 1.66 |   0.8865 |
| Q3_K_L  | 634.58 ± 0.56  |  351.13 ± 8.08  |  0.55333 | 48.58 ± 0.03  |   41.31 ± 1.36 |   0.85035 |
| Q4_K_S  | 837.43 ± 2.89  |  353.91 ± 9.28  |  0.42261 | 49.79 ± 0.21  |   54.93 ± 2.08 |   1.10323 |
| Q4_K_M  | 829.14 ± 0.40  |  353.51 ± 9.24  |  0.42636 | 49.62 ± 0.02  |   53.79 ± 2.20 |   1.08404 |
| Q5_K_S  | 826.64 ± 0.27  |  353.72 ± 9.10  |  0.4279  | 47.12 ± 0.02  |   45.24 ± 1.19 |   0.9601 |
| Q5_K_M  | 818.87 ± 0.35  |  353.66 ± 11.85 |  0.43189 | 46.95 ± 0.02  |   45.13 ± 1.37 |   0.96124 |
| Q6_K    | 778.88 ± 0.52  |  333.60 ± 8.68  |  0.42831 | 45.54 ± 0.03  |   44.34 ± 1.82 |   0.97365 |
| Q8_0    | 1033.42 ± 0.61 |  351.92 ± 9.23  |  0.34054 | 37.33 ± 0.02  |   33.44 ± 1.26 |   0.89579 |

I also very much like @Artefact2's chart and tried to replicate it since I haven't found any other reasonable way to track the performance uplift throughout the Vulkan backend development:

![5835_chart](https://github.com/ggerganov/llama.cpp/assets/6383928/a4ec9575-9ece-4078-98d8-bd2d283cf830)

**Comment by stuaxo** [comment]
Bit annoying @github-actions bot closed thus.
