### ISSUE TITLE
Is it possible to avoid printing input when using Alpaca models and prompt from file?

### ISSUE THREAD

**Issue by DanielWicz** [ggerganov/llama.cpp#533]
I want to use prompt from file using `-f` options and alpaca models. Nevertheless, when I use like that, the llama.cpp first prints out the whole input. How to avoid printing out whole input ?

**Comment by gjmulder** [comment]
#480
#432 

[Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1) before submitting new issues

**Comment by dillfrescott** [comment]
@gjmulder Those issues do not cover what @DanielWicz asked. Even with the new command line flag, llama.cpp continues to repeat the entire text file input before inferencing upon it.

**Comment by gjmulder** [comment]
https://linuxize.com/post/bash-redirect-stderr-stdout/
