### ISSUE TITLE
When I tried to convert the Qwen-VL-chat model to gguf, an error occurred: `Can not map tensor ‘transformer.visual.positional_embedding’. What is the reason?

### ISSUE THREAD

**Issue by bingal** [ggerganov/llama.cpp#5331]
Steps:
1. Use `llava-surgery.py` to split the LLaVA model to LLaMA and multimodel projector constituents:
`python ./examples/llava/llava-surgery.py -m ~/.cache/modelscope/hub/qwen/Qwen-VL-Chat`
  Executed successfully
2. Use `convert-image-encoder-to-gguf.py` to convert the LLaVA image encoder to GGUF:
`python ./examples/llava/convert-image-encoder-to-gguf.py -m ~/CLIP-ViT-bigG-14-laion2B-39B-b160k --llava-projector ~/.cache/modelscope/hub/qwen/Qwen-VL-Chat/llava.projector --output-dir ~/llamafile/Qwen-VL-Chat`
  Executed successfully
3. Use `convert-hf-to-gguf.py` to convert the LLaMA part of LLaVA to GGUF:
`python convert-hf-to-gguf.py ~/.cache/modelscope/hub/qwen/Qwen-VL-Chat --outfile ~/llamafile/Qwen-VL-Chat/Qwen-VL-Chat-f16.gguf`
  The execution failed with the following error message:
```bash
blk.29.ffn_gate.weight, n_dims = 2, torch.bfloat16 --> float16
blk.29.ffn_down.weight, n_dims = 2, torch.bfloat16 --> float16
blk.30.attn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.30.attn_qkv.weight, n_dims = 2, torch.bfloat16 --> float16
blk.30.attn_qkv.bias, n_dims = 1, torch.bfloat16 --> float32
blk.30.attn_output.weight, n_dims = 2, torch.bfloat16 --> float16
blk.30.ffn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.30.ffn_up.weight, n_dims = 2, torch.bfloat16 --> float16
blk.30.ffn_gate.weight, n_dims = 2, torch.bfloat16 --> float16
blk.30.ffn_down.weight, n_dims = 2, torch.bfloat16 --> float16
blk.31.attn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.31.attn_qkv.weight, n_dims = 2, torch.bfloat16 --> float16
blk.31.attn_qkv.bias, n_dims = 1, torch.bfloat16 --> float32
blk.31.attn_output.weight, n_dims = 2, torch.bfloat16 --> float16
blk.31.ffn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.31.ffn_up.weight, n_dims = 2, torch.bfloat16 --> float16
blk.31.ffn_gate.weight, n_dims = 2, torch.bfloat16 --> float16
blk.31.ffn_down.weight, n_dims = 2, torch.bfloat16 --> float16
output_norm.weight, n_dims = 1, torch.bfloat16 --> float32
Can not map tensor 'transformer.visual.positional_embedding'
```

What is the reason?

My system and llama.cpp version: 
- llama.cpp version: 2042 (128dcbd3)
- built with cc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0 for x86_64-linux-gnu

**Comment by johnwick123f** [comment]
@bingal hmm I believe llama cpp simply doesn’t support Qwen vl yet since it’s a different architecture.

Any particular reason you want to use it since llava 1.6 should outperform it

**Comment by thiner** [comment]
> @bingal hmm I believe llama cpp simply doesn’t support Qwen vl yet since it’s a different architecture.
> 
> Any particular reason you want to use it since llava 1.6 should outperform it

One obvious advantage of Qwen-VL is that it supports both English and Chinese OCR.

**Comment by J0eky** [comment]
@bingal hi，I meet the same problem with you. So, we can't deploy qwen-vl-chat by ollama now?

**Comment by thiner** [comment]
@J0eky you can't, because llama.cpp doesn't support convert qwen-vl to gguf format yet. But you can try LocalAI to run the 4-bit quantized model. Check https://github.com/mudler/LocalAI/pull/1985

**Comment by bingal** [comment]
> @bingal hi，I meet the same problem with you. So, we can't deploy qwen-vl-chat by ollama now?

Yes, currently, deployment of qwen-vl-chat via Ollama is not supported.
