### ISSUE TITLE
Server: Slow prompt processing speed

### ISSUE THREAD

**Issue by Dampfinchen** [ggerganov/llama.cpp#5337]
I have noticed using the server connected to SillyTavern, I'm getting significantly slower prompt processing speed on my RTX 2060, i7 9750H, 32 GB RAM system. In both cases, I've offloaded 5 layers for Mixtral Q4K_S, disabled mmap and used a batch size of 1024. 

![llama cpp-ST](https://github.com/ggerganov/llama.cpp/assets/59751859/e97af268-aa18-416c-8b6e-daa668b5fd47)

Llama.cpp server build 2060 in conjunction with SillyTavern

![llama cpp](https://github.com/ggerganov/llama.cpp/assets/59751859/0c6084fc-8cf3-496c-b67f-6bb32635d389)

Llama.cpp build 2060.

**Comment by ggerganov** [comment]
Doesn't this indicate an issue in ST?

**Comment by Dampfinchen** [comment]
> Doesn't this indicate an issue in ST?

I don't think so, as Koboldcpp, which is based on llama.cpp, has the regular prompt processing speed.

**Comment by ggerganov** [comment]
I must be missing something - if `llama.cpp` and Koboldcpp have normal speed and ST has slower speed, then the issue is most definitely in ST

**Comment by Dampfinchen** [comment]
> I must be missing something - if `llama.cpp` and Koboldcpp have normal speed and ST has slower speed, then the issue is most definitely in ST

Let me explain.

What I'm testing here is the speed of Koboldcpp and Llama.cpp connected to SillyTavern through their respective APIs. 

![kobo1 56](https://github.com/ggerganov/llama.cpp/assets/59751859/08e3e107-9cf3-4290-a07d-d80921f89b2c)

This is Koboldcpp connected to SillyTavern. Koboldcpp has a prompt processing speed of 17.8 ms/t as you can see here, which is performing as expected.

The result for llama.cpp connected to SillyTavern  is a result I have posted in my entry post. As you can see, llama.cpp's prompt processing speed is 24.68 ms/t when its connected to SillyTavern and 18.50 ms/t when its not.

**Comment by Solido** [comment]
Need confirmation but have some similar concern with llama server sending slower response than loading the model from main.

**Comment by ggerganov** [comment]
I am not noticing any significant difference in the speed between `main` and `server`:

```bash
# run main
make -j && ./main -m models/llama-7b-v2/ggml-model-q4_0.gguf -p "$(printf "%0.sa" {1..8000})" -n 64 -ngl 99 -c 4096 --ignore-eos

llama_print_timings:        load time =     511.69 ms
llama_print_timings:      sample time =       5.31 ms /    64 runs   (    0.08 ms per token, 12043.66 tokens per second)
llama_print_timings: prompt eval time =    7748.17 ms /  2003 tokens (    3.87 ms per token,   258.51 tokens per second)
llama_print_timings:        eval time =    2467.61 ms /    63 runs   (   39.17 ms per token,    25.53 tokens per second)
llama_print_timings:       total time =   10232.91 ms /  2066 tokens
```

```bash
# run server
make -j && ./server -m models/llama-7b-v2/ggml-model-q4_0.gguf -ngl 99 -c 4096

time curl -w " " --request POST --url http://localhost:8080/completion -d '{"n_predict":64,"prompt":"'"$(printf "%0.sa" {1..8000})"'","ignore_eos":true}'

print_timings: prompt eval time =    7914.42 ms /  2003 tokens (    3.95 ms per token,   253.08 tokens per second)
print_timings:        eval time =    2389.74 ms /    64 runs   (   37.34 ms per token,    26.78 tokens per second)
print_timings:       total time =   10304.16 ms
slot 0 released (2067 tokens in cache)
```

What is your result with these commands?

**Comment by uogbuji** [comment]
Hi, I'm pretty sure I'm seeing the same terribly slow behavior with the server, but still working on isolating everything needed to reproduce.

**Comment by Dampfinchen** [comment]
Intentionally or not, this issue has been fixed. LLama.cpp server has now the exact same speed as llama.cpp. Therefore, I'm closing the issue.
