### ISSUE TITLE
Logo in Social Preview

### ISSUE THREAD

**Issue by loretoparisi** [ggerganov/llama.cpp#536]
Not a bug, but a useful thing. Put the logo in the Social Preview like in this project:
<img width="843" alt="Screenshot 2023-03-26 at 20 01 58" src="https://user-images.githubusercontent.com/163333/227795065-61d531a9-e515-44bf-b570-086ea8aa7bf2.png">

 It will be then showed as a preview image on Twitter etc.
<img width="591" alt="Screenshot 2023-03-26 at 20 02 52" src="https://user-images.githubusercontent.com/163333/227795109-d2f84554-1f08-4d82-8b3f-11be2d4de1ef.png">

**Comment by Green-Sky** [comment]
@ggerganov - please add

**Comment by ggerganov** [comment]
![image](https://user-images.githubusercontent.com/1991296/227796576-c524ffbb-5f5d-44b9-ad45-19a8dea5d097.png)

**Comment by loretoparisi** [comment]
It works!
<img width="593" alt="Screenshot 2023-03-28 at 20 34 20" src="https://user-images.githubusercontent.com/163333/228334899-5242fd04-1af6-484e-b1ba-e2883c3eac81.png">
