### ISSUE TITLE
Vulkan build fails with "error: conversion from ‘int’ to ‘vk::PipelineCache’ is ambiguous" on Debian 11

### ISSUE THREAD

**Issue by superkuh** [ggerganov/llama.cpp#5368]
Hi. Since clBLAST opencl support for AMD cards was broken permanently in January (https://github.com/ggerganov/llama.cpp/issues/5355) I am attempting to build the vulkan backend. Unfortunately despite having [vulkaninfo.txt](https://github.com/ggerganov/llama.cpp/files/14183693/vulkaninfo.txt) report everything is fine and my GPU being listed and cmake saying Vulkan is found the compilation just immediately fails.

$ cmake --build . --config Release
[  1%] Building CXX object CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
In file included from /usr/include/vulkan/vulkan.h:11,
                 from /usr/include/vulkan/vulkan.hpp:41,
                 from /home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:7:
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp: In function ‘vk_pipeline ggml_vk_create_pipeline(const string&, size_t, const void*, const string&, uint32_t, uint32_t, std::array<unsigned int, 3>, std::vector<unsigned int>&&, uint32_t)’:
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:366:64: error: conversion from ‘int’ to ‘vk::PipelineCache’ is ambiguous
  366 |     pipeline.pipeline = vk_device.device.createComputePipeline(VK_NULL_HANDLE, compute_pipeline_create_info).value;
      |                                                                ^~~~~~~~~~~~~~
In file included from /home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:7:
/usr/include/vulkan/vulkan.hpp:35977:34: note: candidate: ‘vk::PipelineCache::PipelineCache(VkPipelineCache)’
35977 |     VULKAN_HPP_TYPESAFE_EXPLICIT PipelineCache( VkPipelineCache pipelineCache ) VULKAN_HPP_NOEXCEPT
      |                                  ^~~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:35973:26: note: candidate: ‘constexpr vk::PipelineCache::PipelineCache(std::nullptr_t)’
35973 |     VULKAN_HPP_CONSTEXPR PipelineCache( std::nullptr_t ) VULKAN_HPP_NOEXCEPT
      |                          ^~~~~~~~~~~~~
In file included from /home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:7:
/usr/include/vulkan/vulkan.hpp:84239:131: note:   initializing argument 1 of ‘vk::ResultValue<vk::Pipeline> vk::Device::createComputePipeline(vk::PipelineCache, const vk::ComputePipelineCreateInfo&, vk::Optional<const vk::AllocationCallbacks>, const Dispatch&) const [with Dispatch = vk::DispatchLoaderStatic]’
84239 |   VULKAN_HPP_NODISCARD VULKAN_HPP_INLINE ResultValue<Pipeline> Device::createComputePipeline( VULKAN_HPP_NAMESPACE::PipelineCache pipelineCache, const ComputePipelineCreateInfo & createInfo, Optional<const AllocationCallbacks> allocator, Dispatch const & d ) const
      |                                                                                                                                   ^
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp: In function ‘void ggml_vk_submit(vk_context*, vk::Fence)’:
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:518:40: error: assignment of read-only member ‘vk::TimelineSemaphoreSubmitInfo::sType’
  518 |             tl_submit_infos[idx].sType = vk::StructureType::eTimelineSemaphoreSubmitInfo;
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp: In function ‘void ggml_vk_init()’:
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:1010:9: error: ‘PhysicalDeviceMaintenance4Properties’ is not a member of ‘vk’; did you mean ‘PhysicalDeviceMaintenance3Properties’?
 1010 |     vk::PhysicalDeviceMaintenance4Properties props4;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         PhysicalDeviceMaintenance3Properties
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:1015:33: error: ‘props4’ was not declared in this scope; did you mean ‘props3’?
 1015 |         subgroup_props.pNext = &props4;
      |                                 ^~~~~~
      |                                 props3
/home/superkuh/app_installs/llama.cpp-2024-02-04/llama.cpp/ggml-vulkan.cpp:1021:89: error: ‘props4’ was not declared in this scope; did you mean ‘props3’?
 1021 |         vk_device.max_memory_allocation_size = std::min(props3.maxMemoryAllocationSize, props4.maxBufferSize);
      |                                                                                         ^~~~~~
      |                                                                                         props3
gmake[2]: *** [CMakeFiles/ggml-vulkan.dir/build.make:82: CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:992: CMakeFiles/ggml-vulkan.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2

**Comment by 0cc4m** [comment]
These kinds of issues are usually a result of an old version of the vulkan-headers, which would also fit with Debian. Can you check what version you are using?

**Comment by superkuh** [comment]
libvulkan-dev (1.2.162.0-1) released 2021-01-07.

**Comment by 0cc4m** [comment]
Yeah, that explains it. The oldest version I test is the one Ubuntu 22.04 uses, which is `1.3.204.1-2`. You could install the SDK from [LunarG](https://vulkan.lunarg.com/sdk/home#linux) or use a package from [Debian 12](https://packages.debian.org/bookworm/libvulkan-dev), which might work cause it shouldn't have any dependencies.

**Comment by superkuh** [comment]
Okay. Thanks, I guess vulkan is not an option then. Back to trying to figure out why opencl stoppped working in all builds after Jan, 2024.

**Comment by 0cc4m** [comment]
Right, Debian and Ubuntu bundle library and headers, that's unfortunate. You can still use the LunarG version, though. You might also be able to take the headers from it and use those with your library.

**Comment by henk717** [comment]
@superkuh Perhaps Conda is a working route you can explore, I use it for the Linux builds of Koboldcpp and I know our binary compiles on 20.04 (I didn't test Vulkan on 16.04 but I suspect that still works). If you want to test if this might work for you you could test our prebuilt Koboldcpp binary. If it works you will know that the conda version would work out for you. If it doesn't work let me know (or hit me up on the KoboldAI discord) and I might be able to see if I can compile a vulkan build on an old version so we know if thats a route that can work for you.

**Comment by superkuh** [comment]
I appreciate the tip, henk717, but I don't use containers.

[0cc4m](https://github.com/0cc4m) I tried your idea of simply swapping the include header files out with the LunarG header files. I also had to add the 'vk_video' folder from LunarG to the include folder. But now things compile! Thank you so much!

It is about twice as fast as opencl too!

So, in conclusion for other Debian 11 users: 

Download https://sdk.lunarg.com/sdk/download/1.3.275.0/linux/vulkansdk-linux-x86_64-1.3.275.0.tar.xz and extract it somewhere.  Go to the folder /vulkan/1.3.275.0/x86_64/include/. 

Copy the vk_video folder to your /usr/include. Then back up your existing /usr/include/vulkan and replace it with the /vulkan/1.3.275.0/x86_64/include/vulkan folder. 

Now you can compile llama.cpp.
