### ISSUE TITLE
Can't convert Mixtral model to fp16/fp32

### ISSUE THREAD

**Issue by JohnClaw** [ggerganov/llama.cpp#5378]
I tried to convert this model: https://huggingface.co/nisten/shqiponja-15b-v1

I used the following command line: python convert.py sq15/ and got this error:

Traceback (most recent call last):
  File "C:\fm\convert.py", line 1478, in <module>
    main()
  File "C:\fm\convert.py", line 1464, in main
    model   = convert_model_names(model, params)
  File "C:\fm\convert.py", line 1202, in convert_model_names
    raise Exception(f"Unexpected tensor name: {name}")
Exception: Unexpected tensor name: model.layers.0.block_sparse_moe.gate.weight

**Comment by Artefact2** [comment]
It just works for me using 213d1439fadefe182f69c5f7e8dd3b4b6572ebcb.

**Comment by JohnClaw** [comment]
> It just works for me using [213d143](https://github.com/ggerganov/llama.cpp/commit/213d1439fadefe182f69c5f7e8dd3b4b6572ebcb)

Thank you for the answer but I'm absolutely lame in tech, so i can't understand what are you talking about. I need a working python script or some simple advices of what to do/edit/add/delete, a step-by-step explanation.
