### ISSUE TITLE
Regression: #5351 breaks `--split-mode row` with `-np >1` on server.cpp for MoE

### ISSUE THREAD

**Issue by m18coppola** [ggerganov/llama.cpp#5383]
[commit](https://github.com/ggerganov/llama.cpp/pull/5351)
## Conditions for bug
 * You must have `--split-mode row` **and** `-np 2`. Using one option or the other operates as expected.
 * Mixtral is broken. Non-MoE Mistral models operated as usual.
## Behavior
 * With each new regeneration using the same prompt, the output grew more incoherent.
 * Eventually one of the generations will being processing indefinitely, rendering the server frozen.

I was able to patch this out for myself by changing the `4` to a `0` on line 9912 in `ggml-cuda.cu`. Not sure if this fact reveals much though.
```cpp
if (src1->ne[1] <= 0 && min_compute_capability >= MIN_CC_DP4A && ggml_is_quantized(src0->type)) {
```
I tested with Q6_K only.

## Logs
```
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 2 CUDA devices:
  Device 0: Tesla P40, compute capability 6.1, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: yes
{"timestamp":1707287394,"level":"INFO","function":"main","line":2456,"message":"build info","build":2091,"commit":"b1801eb"}
{"timestamp":1707287394,"level":"INFO","function":"main","line":2459,"message":"system info","n_threads":28,"n_threads_batch":-1,"total_threads":56,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}

llama server listening at http://192.168.1.172:8080

{"timestamp":1707287394,"level":"INFO","function":"main","line":2563,"message":"HTTP server listening","api_key":"api_key: 24 keys loaded","port":"8080","hostname":"192.168.1.172"}
llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from /weights/language_models/gguf/mixtral-8x7b-instruct-v0.1.Q6_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mixtral-8x7b-instruct-v0.1
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 18
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q6_K:  834 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 35.74 GiB (6.57 BPW) 
llm_load_print_meta: general.name     = mistralai_mixtral-8x7b-instruct-v0.1
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    1.14 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =   102.54 MiB
llm_load_tensors:      CUDA0 buffer size = 18197.50 MiB
llm_load_tensors:      CUDA1 buffer size = 18300.05 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  2048.00 MiB
llama_kv_cache_init:      CUDA1 KV buffer size =  2048.00 MiB
llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    36.13 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  1190.22 MiB
llama_new_context_with_model:      CUDA1 compute buffer size =  1194.60 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     4.40 MiB
llama_new_context_with_model: graph splits (measure): 5
Available slots:
 -> Slot 0 - max context: 16384
 -> Slot 1 - max context: 16384
{"timestamp":1707287404,"level":"INFO","function":"main","line":2584,"message":"model loaded"}
all slots are idle and system prompt is empty, clear the KV cache
{"timestamp":1707287405,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":36630,"status":200,"method":"POST","path":"/tokenize","params":{}}
slot 0 is processing [task id: 0]
slot 0 : in cache: 0 tokens | to process: 15 tokens
slot 0 : kv cache rm - [0, end)
{"timestamp":1707287410,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":36642,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 released (100 tokens in cache)
{"timestamp":1707287411,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51148,"status":200,"method":"POST","path":"/tokenize","params":{}}
{"timestamp":1707287411,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51158,"status":200,"method":"POST","path":"/tokenize","params":{}}
slot 1 is processing [task id: 88]
slot 1 : in cache: 0 tokens | to process: 98 tokens
slot 1 : kv cache rm - [0, end)
{"timestamp":1707287412,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51172,"status":200,"method":"POST","path":"/completion","params":{}}
slot 1 released (100 tokens in cache)
{"timestamp":1707287412,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51174,"status":200,"method":"POST","path":"/tokenize","params":{}}
{"timestamp":1707287413,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51184,"status":200,"method":"POST","path":"/tokenize","params":{}}
slot 0 is processing [task id: 93]
slot 0 : in cache: 15 tokens | to process: 0 tokens
slot 0 : kv cache rm - [15, end)
slot 0 : we have to evaluate at least 1 token to generate logits
{"timestamp":1707287415,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51186,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 released (49 tokens in cache)
{"timestamp":1707287415,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"**","remote_port":51190,"status":200,"method":"POST","path":"/tokenize","params":{}}
{"timestamp":1707287415,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51194,"status":200,"method":"POST","path":"/tokenize","params":{}}
slot 1 is processing [task id: 130]
slot 1 : in cache: 15 tokens | to process: 0 tokens
slot 1 : kv cache rm - [15, end)
slot 1 : we have to evaluate at least 1 token to generate logits
{"timestamp":1707287416,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":51208,"status":200,"method":"POST","path":"/completion","params":{}}
slot 1 released (27 tokens in cache)
{"timestamp":1707287417,"level":"INFO","function":"log_server_request","line":2396,"message":"request","remote_addr":"192.168.1.206","bearer":"***","remote_port":55186,"status":200,"method":"POST","path":"/tokenize","params":{}}
```

**Comment by JohannesGaessler** [comment]
Is there any way to test this without having to manually send multiple requests to the server?

**Comment by ggerganov** [comment]
I guess you can try to run `perplexity` with `-b 2` and see if the values make sense for Mixtral

**Comment by 8XXD8** [comment]
Mixtral server is broken with Rocm as well, even without `-np 2`, just using `-sm row`
First response is fine, then the output is incoherent:
> User: hello
> 
> Llama: Hello! It's great to see you here today. What can I do for you? If you need help or advice on anything, don't hesitate to ask me.
> 
> User: tell me a joke
> 
> Llama: ######################################################################################################################################

Log:

> /home/user/dev/llama.cpp/build/bin/server -sm row -ngl 999 -m /home/user/text-generation-webui/models/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf -c 8192 -ts 7,10,10 --port 8080 --host 192.168.0.87
> ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
> ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
> ggml_init_cublas: found 3 ROCm devices:
>   Device 0: AMD Radeon (TM) Pro VII, compute capability 9.0, VMM: no
>   Device 1: AMD Radeon (TM) Pro VII, compute capability 9.0, VMM: no
>   Device 2: AMD Radeon (TM) Pro VII, compute capability 9.0, VMM: no
> {"timestamp":1707296546,"level":"INFO","function":"main","line":2451,"message":"build info","build":2090,"commit":"ee1628bd"}
> {"timestamp":1707296546,"level":"INFO","function":"main","line":2458,"message":"system info","n_threads":64,"n_threads_batch":-1,"total_threads":128,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}
> 
> llama server listening at http://192.168.0.87:8080
> 
> {"timestamp":1707296546,"level":"INFO","function":"main","line":2557,"message":"HTTP server listening","port":"8080","hostname":"192.168.0.87"}
> llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from /home/user/text-generation-webui/models/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf (version GGUF V3 (latest))
> llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
> llama_model_loader: - kv   0:                       general.architecture str              = llama
> llama_model_loader: - kv   1:                               general.name str              = mistralai_mixtral-8x7b-instruct-v0.1
> llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
> llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
> llama_model_loader: - kv   4:                          llama.block_count u32              = 32
> llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
> llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
> llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
> llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
> llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
> llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
> llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
> llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
> llama_model_loader: - kv  13:                          general.file_type u32              = 17
> llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
> llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
> llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
> llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
> llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
> llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
> llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
> llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 0
> llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
> llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
> llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
> llama_model_loader: - kv  25:               general.quantization_version u32              = 2
> llama_model_loader: - type  f32:   65 tensors
> llama_model_loader: - type  f16:   32 tensors
> llama_model_loader: - type q8_0:   64 tensors
> llama_model_loader: - type q5_K:  833 tensors
> llama_model_loader: - type q6_K:    1 tensors
> llm_load_vocab: special tokens definition check successful ( 259/32000 ).
> llm_load_print_meta: format           = GGUF V3 (latest)
> llm_load_print_meta: arch             = llama
> llm_load_print_meta: vocab type       = SPM
> llm_load_print_meta: n_vocab          = 32000
> llm_load_print_meta: n_merges         = 0
> llm_load_print_meta: n_ctx_train      = 32768
> llm_load_print_meta: n_embd           = 4096
> llm_load_print_meta: n_head           = 32
> llm_load_print_meta: n_head_kv        = 8
> llm_load_print_meta: n_layer          = 32
> llm_load_print_meta: n_rot            = 128
> llm_load_print_meta: n_embd_head_k    = 128
> llm_load_print_meta: n_embd_head_v    = 128
> llm_load_print_meta: n_gqa            = 4
> llm_load_print_meta: n_embd_k_gqa     = 1024
> llm_load_print_meta: n_embd_v_gqa     = 1024
> llm_load_print_meta: f_norm_eps       = 0.0e+00
> llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
> llm_load_print_meta: f_clamp_kqv      = 0.0e+00
> llm_load_print_meta: f_max_alibi_bias = 0.0e+00
> llm_load_print_meta: n_ff             = 14336
> llm_load_print_meta: n_expert         = 8
> llm_load_print_meta: n_expert_used    = 2
> llm_load_print_meta: rope scaling     = linear
> llm_load_print_meta: freq_base_train  = 1000000.0
> llm_load_print_meta: freq_scale_train = 1
> llm_load_print_meta: n_yarn_orig_ctx  = 32768
> llm_load_print_meta: rope_finetuned   = unknown
> llm_load_print_meta: model type       = 7B
> llm_load_print_meta: model ftype      = Q5_K - Medium
> llm_load_print_meta: model params     = 46.70 B
> llm_load_print_meta: model size       = 30.02 GiB (5.52 BPW)
> llm_load_print_meta: general.name     = mistralai_mixtral-8x7b-instruct-v0.1
> llm_load_print_meta: BOS token        = 1 '<s>'
> llm_load_print_meta: EOS token        = 2 '</s>'
> llm_load_print_meta: UNK token        = 0 '<unk>'
> llm_load_print_meta: PAD token        = 0 '<unk>'
> llm_load_print_meta: LF token         = 13 '<0x0A>'
> llm_load_tensors: ggml ctx size =    1.14 MiB
> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU
> llm_load_tensors:      ROCm0 buffer size =     3.02 MiB
> llm_load_tensors:        CPU buffer size =    85.94 MiB
> llm_load_tensors: ROCm_Split buffer size = 30646.54 MiB
> ....................................................................................................
> llama_new_context_with_model: n_ctx      = 8192
> llama_new_context_with_model: freq_base  = 1000000.0
> llama_new_context_with_model: freq_scale = 1
> llama_kv_cache_init:      ROCm0 KV buffer size =  1024.00 MiB
> llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
> llama_new_context_with_model:  ROCm_Host input buffer size   =    24.04 MiB
> llama_new_context_with_model:      ROCm0 compute buffer size =   638.04 MiB
> llama_new_context_with_model:  ROCm_Host compute buffer size =     8.80 MiB
> llama_new_context_with_model: graph splits (measure): 3
> Available slots:
>  -> Slot 0 - max context: 8192
> {"timestamp":1707296552,"level":"INFO","function":"main","line":2578,"message":"model loaded"}
> all slots are idle and system prompt is empty, clear the KV cache
> {"timestamp":1707296555,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50641,"status":200,"method":"GET","path":"/","params":{}}
> {"timestamp":1707296555,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50641,"status":200,"method":"GET","path":"/index.js","params":{}}
> {"timestamp":1707296555,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50641,"status":200,"method":"GET","path":"/json-schema-to-grammar.mjs","params":{}}
> {"timestamp":1707296555,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50642,"status":200,"method":"GET","path":"/completion.js","params":{}}
> {"timestamp":1707296556,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50641,"status":200,"method":"GET","path":"/","params":{}}
> {"timestamp":1707296556,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50641,"status":200,"method":"GET","path":"/index.js","params":{}}
> {"timestamp":1707296556,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50642,"status":200,"method":"GET","path":"/completion.js","params":{}}
> {"timestamp":1707296556,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50643,"status":200,"method":"GET","path":"/json-schema-to-grammar.mjs","params":{}}
> slot 0 is processing [task id: 0]
> slot 0 : in cache: 0 tokens | to process: 54 tokens
> slot 0 : kv cache rm - [0, end)
> 
> print_timings: prompt eval time =    2001.95 ms /    54 tokens (   37.07 ms per token,    26.97 tokens per second)
> print_timings:        eval time =    1736.40 ms /    38 runs   (   45.69 ms per token,    21.88 tokens per second)
> print_timings:       total time =    3738.35 ms
> slot 0 released (92 tokens in cache)
> {"timestamp":1707296563,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50642,"status":200,"method":"POST","path":"/completion","params":{}}
> slot 0 is processing [task id: 41]
> slot 0 : in cache: 91 tokens | to process: 12 tokens
> slot 0 : kv cache rm - [91, end)
> {"timestamp":1707296574,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"192.168.0.178","remote_port":50642,"status":200,"method":"POST","path":"/completion","params":{}}
> slot 0 released (239 tokens in cache)

**Comment by JohannesGaessler** [comment]
I can reproduce the issue and I'm pretty sure I know what the issue is; it is not exclusive to Mixtral.

**Comment by JohannesGaessler** [comment]
Please confirm whether this fix works: https://github.com/ggerganov/llama.cpp/pull/5386 .

**Comment by 8XXD8** [comment]
Fixed it for me with rocm, thanks.
