### ISSUE TITLE
convert models to gguf: explain how to implement additional model architecture 

### ISSUE THREAD

**Issue by zwilch** [ggerganov/llama.cpp#5403]
I have tried to convert sentence similarity models to convert to gguf

../convert-hf-to-gguf.py ../models/sentence-transformers_paraphrase-multilingual-mpnet-base-v2/
NotImplementedError: Architecture "XLMRobertaModel" not supported!

../convert-hf-to-gguf.py ../models/sentence-transformers_paraphrase-multilingual-MiniLM-L12-v2/ 
NotImplementedError: Architecture "BertModel" not supported!

../convert-hf-to-gguf.py ../models/Xenova_jina-embeddings-v2-base-de/ 
NotImplementedError: Architecture "JinaBertForMaskedLM" not supported!

Can someone explain what is to edit/change/modify in the convert scripts that it is possible to convert unknown models?

**Comment by Bearsaerker** [comment]
llama.cpp is (atm) only for language models and not for Bert/embedding/reranking models. You are trying to quantize embedding models. If you want to quantize those, you can look into onnx. What you would like to do won't work, as far as I know.

**Comment by tybalex** [comment]
this worked for me:
```
python convert-hf-to-gguf.py   --outfile minilm.gguf --outtype f16 minilm
```
here minilm refers to https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
and I am able to run the minilm.gguf model using llama.cpp.
However I experienced a severe quality downgrade from the .gguf model.

Maybe it just doesn't really work.

**Comment by ciekawy** [comment]
Well I wonder that actually embeddings are supported, it's worth to enhance gguf conversion as well and include also reranking models
