### ISSUE TITLE
Problem connecting VSCode (Continue) to the server LlamaCpp

### ISSUE THREAD

**Issue by mike2003** [ggerganov/llama.cpp#5406]
I use this instruction
https://continue.dev/docs/reference/Model%20Providers/llamacpp
But when I try to connect, VSCode (Continue) writes an error:
**Continue error: HTTP 404 Not Found from http://localhost:8080/completion
This may mean that you forgot to add '/v1' to the end of your 'apiBase' in config.json.**
What am I doing wrong?

I tried adding "v1" and it didn't help.

Something like this in the console:
```
llama_new_context_with_model:        CPU input buffer size   =    16.02 MiB
llama_new_context_with_model:        CPU compute buffer size =   308.00 MiB
llama_new_context_with_model: graph splits (measure): 1
{"timestamp":1707387568,"level":"INFO","function":"log_server_request","line":2398,"message":"request","remote_addr":"127.0.0.1","remote_port":51925,"status":404,"method":"POST","path":"/completion","params":{}}
Available slots:
 -> Slot 0 - max context: 4096
{"timestamp":1707387599,"level":"INFO","function":"main","line":2578,"message":"model loaded"}
all slots are idle and system prompt is empty, clear the KV cache
```

Win10x64

**Comment by Azeirah** [comment]
It's better to ask for help in the continue community than here, the llama.cpp server is not at fault here.

Here's the continue discord: https://discord.gg/uNuCrnF9

**Comment by techsin** [comment]
was it resolved?
