### ISSUE TITLE
GPU Performance Data Point via Vulkan 

### ISSUE THREAD

**Issue by pure-water** [ggerganov/llama.cpp#5410]
- Could anyone kindly update some vulkan GPU accerleration path's perfomance numbers against the normal path of the CPU?  
- Obviously it makes more relevant on the mobile  architecture whereby CPU and GPU are sitting along each other. 
- Not a strict issue but  no idea where  to put it.

**Comment by userbox020** [comment]
sup bro i had same problem, vulkan was getting my cpu graphics instead of my gpu. I solved it doing the follow on ubuntu 22.04 `sudo apt install --reinstall mesa-vulkan-drivers`

and for previous llamacpp build i had to do the follow steps

```
wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.275-jammy.list https://packages.lunarg.com/vulkan/1.3.275/lunarg-vulkan-1.3.275-jammy.list
sudo apt update
sudo apt install vulkan-sdk
sudo apt install libvulkan-dev
sudo apt install vulkan-utils
vulkaninfo

sudo reboot
```

But now im stuck with a single GPU, even when `vulkaninfo` detects all my gpus i can only use the devide id 0, still looking how can i enable all of them

**Comment by userbox020** [comment]
found how to activate the multi gpu bro! `export GGML_VK_VISIBLE_DEVICES=0,1,2`
check https://github.com/ggerganov/llama.cpp/pull/5321

**Comment by pure-water** [comment]
Can you please provide some data points with/withou GPU (including multi)  on this thread meant for?

**Comment by userbox020** [comment]
Sure just give me the schemas or examples and i can prepare something for you buddy

**Comment by 0cc4m** [comment]
@pure-water Can you be a little clearer in your issue description? You want people to run benchmarks with CPU and with Vulkan on the same device, right? And you're most interested in APUs and mobile devices.

**Comment by pure-water** [comment]
Yes. I want to see the impact of the gpu accerleration on the same device .  Yes, I am most interested on mobile device or APU like devices. @0cc4m 

You can simply run the same workload without the --ngl switch (which will go through the cpu) and the --ngl switch @userbox020

**Comment by hvisser** [comment]
I'm running with vulkan on a Pixel 6a device in an application  and vulkan is significantly slower vs CPU. What's the best way to report performance numbers?

**Comment by pure-water** [comment]
OK, that is what I did in my case but it is not an APU, just for an example. 

- ./main -m  models/phi-2/phi-2.Q3_K_M.gguf -p "I am running LLM on my apu chips" --color  --temp 0.99
llama_print_timings:        eval time =  233434.27 ms /   734 runs   (  318.03 ms per token,     3.14 tokens per second)

- ./main -m  models/phi-2/phi-2.Q3_K_M.gguf -p "I am running LLM on my apu chips" --color  --temp 0.99 --ngl 33   
llama_print_timings:        eval time =   25992.38 ms /   731 runs   (   35.56 ms per token,    28.12 tokens per second)

So the GPU vs CPU is about 28.12 .versus. 3.14

**Comment by hvisser** [comment]
That's a big difference, I wonder why I'm not seeing that and why it's so slow. The log seems to indicate that it is using vulkan kv on the device.

I'm having some trouble compiling main with vulkan through the NDK from the command line, it yields me linker errors not finding `vkGetPhysicalDeviceFeatures2` while it compiles`libllama` with `LLAMA_VULKAN` just fine within my project. 

CPU gives me:

```llama_print_timings:        eval time =  107912.46 ms /   664 runs   (  162.52 ms per token,     6.15 tokens per second)```

**Comment by hvisser** [comment]
OK, got it running, the error seems to be related to the minSdk, but unfortunately the same result as what I'm seeing in my app:

```
ggml_vulkan: Found 1 Vulkan devices:
Vulkan0: Mali-G78 | uma: 1 | fp16: 1 | warp size: 16
...
llm_load_tensors: ggml ctx size =    0.25 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:    Vulkan0 buffer size =  1356.19 MiB
llm_load_tensors:        CPU buffer size =    53.71 MiB

llama_print_timings:        eval time =  341640.32 ms /   569 runs   (  600.42 ms per token,     1.67 tokens per second)
```

**Comment by pure-water** [comment]
what is your device and what is your command line model etc? Try smaller modler as phi-2 or tiny-llma etc?

**Comment by hvisser** [comment]
It's a pixel 6a running the exact same commandline and model that you mentioned.

**Comment by pure-water** [comment]
do you have vulkan debug switch enabled. I do not have llm_load_tensor print out message
