### ISSUE TITLE
CPU performance bottleneck(?) when using macOS Accelerate

### ISSUE THREAD

**Issue by ptsochantaris** [ggerganov/llama.cpp#5417]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I've been doing some performance testing of llama.cpp in macOS (On M2 Ultra 24-Core) and was comparing the CPU performance of inference with various options, and ran into a very large performance drop - Mixtral model inference on 16 cores (16 because it's only the performance cores, the other 8 are efficiency cores on my CPU) was much faster without Accelerate. This prompted me to test other models of different sizes and across using 3 different core counts.

<img width="621" alt="Screenshot 2024-02-08 at 16 39 16" src="https://github.com/ggerganov/llama.cpp/assets/521581/b1820086-bca5-4740-a7b2-e190c2d6b5db">

Notes:
- All tests fit the model in RAM, there was no swapping/paging.
- Performance gains are in green, drops are in red. Significant changes are bolded, the others may just be due to single iterations.
- The drop in performance that caught my eye was the Mixtral with 16 cores drop in performance, which is the most pronounced above, bottom-right.)

The initial results suggest that there is some asymptotic "ceiling" in CPU inference when using Accelerate, that seems to show up when a sufficient amount of cores is engaged. So while it starts off providing a big performance boost as expected, the more cores that are added, the growth in performance levels out. This flattening seems to be accelerated (no pun intended) the larger the model is. In comparison not using Accelerate starts off much slower but keeps growing almost linearly as cores are added.

# Motivation

Allowing llama.cpp to run as fast as possible on more variants of Apple Silicon.

# Possible Implementation

I will try to run this through the profiler to see if there is some code bottleneck. There are two possibilities that I can think of, off the top of my head:

**If this is because of Apple Silicon architecture and/or the vDSP/Accelerate framework function dispatches**, then it may be useful to add parameters to ggml CPU contexts which, even if Accelerate support is compiled-in, can still turn it off. This way applications can, based on the hardware, disable the accelerate code paths at runtime (for instance, disabling accelerate code paths when running with 16 cores on CPU)

**If this is because of some code bottleneck in the ggml library**, then it may be worth identifying and seeing how it can be alleviated. I'll try some profiling on my machine, but it's possible that someone with more experience of this codebase can have tips or suggestions on what may be going on, or tips on the best places to start looking.

**Comment by slaren** [comment]
The MoE layers are implemented with the `ggml_mul_mat_id` operation, which does not support using BLAS (including Accelerate). I think the problem is that when using a BLAS build, the number of threads is automatically reduced during prompt processing to avoid interfering with the BLAS matrix multiplication, but with Mixtral BLAS is not actually used, so the only thing this achieves is tank the performance.

This is the relevant code:
https://github.com/ggerganov/llama.cpp/blob/ff4ff05c5ff4311c05a8ce1f984c7d8def4f07a5/llama.cpp#L7283-L7290
Maybe an exception could be added for Mixtral.

@kalomaze this may be related to the regression that you reported with Mixtral prompt processing.

**Comment by ptsochantaris** [comment]
Ah, that's a very useful tip, thanks! This will be a good place for me to try tweaking and see how it affects the previous results 👍 Will try to remove that `min` temporarily to see what that does to results and come back with an update.

**Comment by slaren** [comment]
You could check for `hparams.n_expert > 0` to determine if it is a MoE model.

**Comment by ptsochantaris** [comment]
🥷 Very straightforward indeed. I'll put a PR up with that small tweak shortly. Thanks for your help on this, much appreciated!
