### ISSUE TITLE
Llama for embedded systems without OS

### ISSUE THREAD

**Issue by mahdi259** [ggerganov/llama.cpp#5422]
Hi
I have a question about this project.
Is it possible to compile LLAMA for a device without any Operating System?

My device is a **microcontroller** and I can compile C/C++ code and run with it.
Thanks

**Comment by ngxson** [comment]
If you're asking about something like an arduino or ESP32 then the short answer is no. You need at least linux device like a raspberry pi to run it.

**Comment by mahdi259** [comment]
Ok thanks

**Comment by ZHY109** [comment]
The answer is YES: https://github.com/DaveBben/esp32-llm
