### ISSUE TITLE
unknown tensor '' in model file

### ISSUE THREAD

**Issue by Atlas3DSS** [ggerganov/llama.cpp#543]
![image](https://user-images.githubusercontent.com/89653506/227813653-b2657cf7-8c98-4e91-89b4-d0304c37fced.png)
![image](https://user-images.githubusercontent.com/89653506/227813663-7b002b7d-d394-45a4-9b87-c736a6915a49.png)
![image](https://user-images.githubusercontent.com/89653506/227813677-c8cc3de7-a155-4201-95f0-297100d3d1b1.png)

So as to prevent mass spam of very large segments of code that i dont think are necessarily useful - i am wondering what i might be doing wrong here - went ahead and went through the entire process start to finish twice just to try and check against maybe a random typo somewhere - but same result both times.

**Comment by slaren** [comment]
The fact that the `.bin.3` files are smaller than the rest is a red flag. Did the conversion from pth finish successfully?

**Comment by Atlas3DSS** [comment]
aye it appeared to - it didn't flag any errors or indicate anything - i shall run it again

**Comment by Atlas3DSS** [comment]
![image](https://user-images.githubusercontent.com/89653506/227814366-98a55f1b-f6dc-4594-9fbc-d5fad0e38672.png)
you appear to be correct i reran the conversion from .pth to ggml and now they are the same size. 
I have rerun the quantization and they are now all the same - i do believe you were correct
![image](https://user-images.githubusercontent.com/89653506/227814867-1545c187-707a-4e4d-9e77-4c874be8802c.png)
![image](https://user-images.githubusercontent.com/89653506/227814940-66a5f97a-2527-4841-a083-2e0a4fdb0feb.png)
Indeed you were I thank you ser
