### ISSUE TITLE
Provision of example to download a model

### ISSUE THREAD

**Issue by mahdi259** [ggerganov/llama.cpp#5431]
Hi
Could you please add some codes about loading pretained models from huggingface?
I downloaded a light model with .bin format but it didn't work.
My model:
https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin

**Comment by supportend** [comment]
Download GGUF files. TheBloke converted many models,  start here:

https://huggingface.co/TheBloke

**Comment by mahdi259** [comment]
Thanks I downloaded it and run it successfully.
