### ISSUE TITLE
Unable to build llama.cpp on Intel DevCloud

### ISSUE THREAD

**Issue by AlexFierro9** [ggerganov/llama.cpp#5439]
Executed the following commands, unable to get build sucessfully:

`mkdir -p build`
`cd build\n`
`cmake .. -DLLAMA_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx`

Getting this error 
![image](https://github.com/ggerganov/llama.cpp/assets/95060707/9041cef8-3c4e-433f-901c-1aa147bb5a2a)

**Comment by rhernandez-uthealth** [comment]
Install OneAPI and run "source /opt/intel/oneapi/setvars.sh" beforehand, but this is not an issue

**Comment by AlexFierro9** [comment]
Retraced the steps, still not working

**Comment by airMeng** [comment]
hi @AlexFierro9 sorry for the late. can you paste the output of ```source /opt/intel/oneapi/setvars.sh```

there should be MKL listed, otherwise you might not install MKL correctly


```
hengyume@mlp-618:~$ source /opt/intel/oneapi/setvars.sh

:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments:
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: ipp -- latest
:: ippcp -- latest
:: mkl -- latest              // This line
:: mpi -- latest
:: tbb -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
```
