### ISSUE TITLE
Vulkan Device memory allocation failed (ErrorOutOfDeviceMemory )

### ISSUE THREAD

**Issue by Eliastrt** [ggerganov/llama.cpp#5441]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

---------------------------------------------------------------------------------------------
System: OpenSuse Leap 15.4
GPU: AMD RX580 8GB
Vulkan Instance Version: 1.3.275
VkPhysicalDeviceMemoryProperties:
=================================
memoryHeaps: count = 3
        memoryHeaps[0]:
                size   = 8321499136 (0x1f0000000) (7.75 GiB)
                budget = 8310034432 (0x1ef511000) (7.74 GiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT
        memoryHeaps[1]:
                size   = 4133625856 (0xf6622000) (3.85 GiB)
                budget = 4124254208 (0xf5d32000) (3.84 GiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags:
                        None
        memoryHeaps[2]:
                size   = 268435456 (0x10000000) (256.00 MiB)
                budget = 256970752 (0x0f511000) (245.07 MiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT

Vulkan0: AMD RADV POLARIS10 | uma: 0 | fp16: 0 | warp size: 64

GGUF model: mistral-7b-instruct-v0.2.Q6_K.gguf

------------------------------------------------------------------------------------------------

First of all, thanks to Occam for new Vulkan implementation of Llama.CPP!

I have tried to run llama.cpp according instruction "without Docker":

--> ./bin/main -m "PATH_TO_mistral-7b-instruct-v0.2.Q6_K.gguf" -p "Hi you how are you" -n 50 -e -ngl 33 -t 4 

Got an error: 
ggml_vulkan: Device memory allocation of size 4257734656 failed.
ggml_vulkan: vk::Device::allocateMemory: ErrorOutOfDeviceMemory
llama_model_load: error loading model: vk::Device::allocateMemory: ErrorOutOfDeviceMemory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/root/GPT/GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf'
main: error: unable to load model

FYI:
If I reduce -ngl to 23 layers then everything worked properly, but slowly. 

llm_load_tensors:        CPU buffer size =  5666.09 MiB
llm_load_tensors:    Vulkan0 buffer size =  3925.09 MiB
6.51 tokens per second (OpenCL version loads full model on the same GPU and shows ~12 tokens\sec)

**Comment by 0cc4m** [comment]
OpenCL does not run the full model on the GPU, it just does matrix multiplications, scalar multiplications and scalar additions, all the rest is done by the CPU. That means it uses a little less VRAM, yes. I guess you're using the GPU for a GUI at the same time, so it has other programs occupying its VRAM and doesn't find enough for Vulkan. Try using q5_k or q4_k.

**Comment by Eliastrt** [comment]
Thanks for reply. 

I have no GUI on this machine. Anyway, 23 layers uses ~4GB and run without problems, 24 layers rise this error. 

According AMD docs: https://gpuopen.com/learn/vulkan-device-memory/

For Vulkan implementations could be used different Heap levels. And it looks like this implementation uses Heaps[1] instead of Heaps[0]. If so, it is the problem, because my vulkaninfo shows 8GB for Heaps[0] and only 4GB for Heaps[1]

**Comment by 0cc4m** [comment]
> Thanks for reply.
> 
> I have no GUI on this machine. Anyway, 23 layers uses ~4GB and run without problems, 24 layers rise this error.
> 
> According AMD docs: https://gpuopen.com/learn/vulkan-device-memory/
> 
> For Vulkan implementations could be used different Heap levels. And it looks like this implementation uses Heaps[1] instead of Heaps[0]. If so, it is the problem, because my vulkaninfo shows 8GB for Heaps[0] and only 4GB for Heaps[1]

You didn't post the whole vulkaninfo, but I'm pretty sure it's using the right heap. It looks for device-local memory first. The 4GB heap is host-visible memory (RAM). This is used, too, but only for layers you didn't put on the GPU and for staging buffers.

**Comment by Eliastrt** [comment]
full vulkaninfo output in attachment
[vulkaninfo.txt](https://github.com/ggerganov/llama.cpp/files/14236585/vulkaninfo.txt)

**Comment by Eliastrt** [comment]
Thanks! So, I can't understand this output, but here it is: 
[test_vulkan_rx580_8GB_part_1.txt](https://github.com/ggerganov/llama.cpp/files/14249767/test_vulkan_rx580_8GB_part_1.txt)
[test_vulkan_rx580_8GB_part_2.txt](https://github.com/ggerganov/llama.cpp/files/14249768/test_vulkan_rx580_8GB_part_2.txt)

**Comment by 0cc4m** [comment]
> Thanks! So, I can't understand this output, but here it is: [test_vulkan_rx580_8GB_part_1.txt](https://github.com/ggerganov/llama.cpp/files/14249767/test_vulkan_rx580_8GB_part_1.txt) [test_vulkan_rx580_8GB_part_2.txt](https://github.com/ggerganov/llama.cpp/files/14249768/test_vulkan_rx580_8GB_part_2.txt)

So it's just trying to allocate a buffer of size `4257734656` bytes. Your driver reports a max buffer size of `4294967292` bytes, so this should work. Maybe the limit is lower, or it has an issue with memory fragmentation? Try this patch to halve the limit:

```patch
diff --git a/ggml-vulkan.cpp b/ggml-vulkan.cpp
index 7834e635..1d1cdc82 100644
--- a/ggml-vulkan.cpp
+++ b/ggml-vulkan.cpp
@@ -1186,6 +1186,8 @@ void ggml_vk_init(ggml_backend_vk_context * ctx, size_t idx) {
         ctx->device.lock()->max_memory_allocation_size = props3.maxMemoryAllocationSize;
     }

+    ctx->device.lock()->max_memory_allocation_size = 2147483646;
+
     ctx->device.lock()->vendor_id = ctx->device.lock()->properties.vendorID;
     ctx->device.lock()->subgroup_size = subgroup_props.subgroupSize;
     ctx->device.lock()->uma = ctx->device.lock()->properties.deviceType == vk::PhysicalDeviceType::eIntegratedGpu;
```

**Comment by Eliastrt** [comment]
Great! It's working now! ~11 tokens\sec

By the way, what is your plans for the feature of model split on several GPU? ;)

**Comment by 0cc4m** [comment]
Great! But that's not a real solution yet. Let's keep the issue open until there's a way to lower the limit without code changes. Maybe an environment variable?

**Comment by Eliastrt** [comment]
I have found some interesting info in Vulkan Specs: 
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkAllocateMemory

"Some platforms may have a limit on the maximum size of a single allocation. For example, certain systems may fail to create allocations with a size greater than or equal to 4GB. Such a limit is implementation-dependent, and if such a failure occurs then the error VK_ERROR_OUT_OF_DEVICE_MEMORY must be returned. This limit is advertised in VkPhysicalDeviceMaintenance3Properties::maxMemoryAllocationSize."

**Comment by 0cc4m** [comment]
> I have found some interesting info in Vulkan Specs: https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkAllocateMemory
> 
> "Some platforms may have a limit on the maximum size of a single allocation. For example, certain systems may fail to create allocations with a size greater than or equal to 4GB. Such a limit is implementation-dependent, and if such a failure occurs then the error VK_ERROR_OUT_OF_DEVICE_MEMORY must be returned. This limit is advertised in VkPhysicalDeviceMaintenance3Properties::maxMemoryAllocationSize."

Yeah, if you look at the patch I gave you that is what I'm doing in the line above the new one. Your GPU reports a limit of 4GB, but fails when I actually try to allocate (slightly less than) 4GB. 2GB seems fine.

**Comment by Eliastrt** [comment]
I have made some R&D and can give you additional info: 
1. For my device Heap[1] < maxMemoryAllocationSize

Vulkan0: AMD RADV POLARIS10 | uma: 0 | fp16: 0 | warp size: 64
DEBUG: maxMemoryAllocationSize=4294967292
DEBUG: maxBufferSize=0
DEBUG: MemoryHeap[1] Size=4133625856

2. If I assign size of Heap[1] everything working fine:

 vk::PhysicalDeviceMemoryProperties mem_props = ctx->device.lock()->physical_device.getMemoryProperties();
....
if (maintenance4_support) {
        ctx->device.lock()->max_memory_allocation_size = std::min(
                std::min(props3.maxMemoryAllocationSize, props4.maxBufferSize), mem_props.memoryHeaps[1].size
        );
    } else {
        ctx->device.lock()->max_memory_allocation_size = std::min(
                props3.maxMemoryAllocationSize, mem_props.memoryHeaps[1].size
        );
    }

**Comment by 0cc4m** [comment]
Yes, that means the actual limit is only slightly below 4GB. But heap 1 is in RAM, it is host-pinned memory, not device memory. It is purely coincidental that its heap size has that effect there. The amount of available host-pinned memory often corresponds to half of the available RAM, but that depends on the driver. The allocation that fails is one for heap 0, for the VRAM.

**Comment by Eliastrt** [comment]
Yes, you are absolutely right. Heap[1] is depending on installed RAM. One more test shows , that somehow it is important to feat with Heap[1]: 
1. I have removed one RAM, so now in system only 4GB and MemoryHeap[1] Size=3221225472
2. I have tried to run again with hardcoded value of 4133625856 (previous Heap[1] size value that run successfully last time) and got the error: Device memory allocation of size 4126957568 failed.

Now I'm going to install RAM back and test it again. So, somehow system RAM and Heap[1] is linked to this error.

**Comment by 0cc4m** [comment]
Maybe, but I don't see how. You are in an unusual situation, with an old driver and 8GB VRAM + 8GB RAM (right?). An up-to-date mesa might fix it. More RAM might fix it, maybe. But I'm not seeing similar issues on other devices. I'll add an environment parameter soon to reduce the max buffer size, which will allow you to work around this issue. I don't see a better way of fixing this right now.

**Comment by Eliastrt** [comment]
Just make buffer size min of two: heap[1] or maxMemAllocationSize ?

**Comment by 0cc4m** [comment]
> Just make buffer size min of two: heap[1] or maxMemAllocationSize ?

No, that is specific to your setup. It really is an allocation to heap 0 that fails. A mesa dev might be able to give more details, but they would likely just tell you to try an up-to-date mesa first.

**Comment by Deins** [comment]
Have the same issue  with some models with ` AMD Radeon RX 7900 XTX` with  24GB vram on windows. 
But could not find a value that works. Went down to ` ctx->device.lock()->max_memory_allocation_size = 2147483648 / 32;` when got error that the limit is lower than layer size `tensor output.weight is too large to fit in a Vulkan0 buffer (tensor size: 107520000, max buffer size: 67108864)`

But its model specifcic, some small models ~4GB don't work while some large ones (>10GB) work.
It clearly is some kind of allocation limitation, that fail to allocate large layers.

Here is vkinfo if anyone finds it useful.
[vulkaninfo.txt](https://github.com/ggerganov/llama.cpp/files/14393188/vulkaninfo.txt)

**Comment by KhazAkar** [comment]
Bug still lurks, which dan be seen on mentonee issue.

**Comment by 9600-** [comment]
Just incase anyone stumbles across this issue, I was able to resolve the issue by using 2GB buffer. 

`export GGML_VK_FORCE_MAX_ALLOCATION_SIZE=2147483647  # 2GB buffer`

**Comment by zeozeozeo** [comment]
> This issue is impacting me as well. Has anyone found a workaround?

Setting `GGML_VK_FORCE_MAX_ALLOCATION_SIZE=2147483646` seems to have fixed it for me.

For example, with latest koboldcpp:
`GGML_VK_FORCE_MAX_ALLOCATION_SIZE=2147483646 python koboldcpp.py yourmodel.gguf 5002 --gpulayers 33 --usevulkan`

This code seems to be the culprit:

https://github.com/ggml-org/llama.cpp/blob/8ba95dca2065c0073698afdfcda4c8a8f08bf0d9/ggml/src/ggml-vulkan/ggml-vulkan.cpp#L2365-L2373

The Linux AMD driver seems to discard allocations >4GB. Sad stuff

**Comment by 0cc4m** [comment]
> The Linux AMD driver seems to discard allocations >4GB. Sad stuff

No Vulkan driver supports allocations above 4GB due to 32-bit addressing. The `GGML_VK_FORCE_MAX_ALLOCATION_SIZE` variable is a workaround for drivers that report supporting 4GB, but throw memory errors when you try to allocate a 4GB block.

This issue seems to crop up often enough that I'll solve it in a more permanent and automatic way soon.

**Comment by RobbyCBennett** [comment]
Thank you for the suggestion. In my case, there are 16 GiB of VRAM (most of which is available) and a total of 8618 MiB is attempted to be allocated. That's more than 4 GiB but it's the total and each allocation is smaller than 4 GiB. The error occurs with an allocation of 1,677,721,600 bytes. Therefore, I wouldn't expect the environment variable to help.

Sure enough, it doesn't solve the problem.

**Comment by 0cc4m** [comment]
If 2GB doesn't work, try 1GB. If that also doesn't work you might have a faulty driver.

**Comment by 0cc4m** [comment]
#12434 should hopefully remove the need to set GGML_VK_FORCE_MAX_ALLOCATION_SIZE as a workaround on some systems.

**Comment by RobbyCBennett** [comment]
Please don't update to a9fe7ebed4bf263c8aecc131d69c36896e528e2a or newer for this test (commit message "internal: ai: switch back to 1 billion model for compatibility"). This is because I would expect the 1 billion model to work on your device, with or without the environment variable.

**Comment by RobbyCBennett** [comment]
OS: Windows 11

Model: [Llama-3.2-3B-Instruct](https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct)

[vulkaninfo.txt](https://github.com/user-attachments/files/19433342/vulkaninfo.txt)

**Comment by AIWintermuteAI** [comment]
Still happens on Orion O6 with Mali-G720 PanVK driver (Mesa 25.2.6-kisak1-n). The driver is experimental, so maybe that's why. Full output:
```
orion@cix-acpi:~/github/llama.cpp$ ./build/bin/llama-cli --model models/qwen2-1_5b-instruct-fp16.gguf --prompt "hi" -ngl 99
WARNING: panvk is not a conformant Vulkan implementation, testing use only.
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Mali-G720 (panvk) | uma: 1 | fp16: 1 | bf16: 0 | warp size: 16 | shared memory: 32768 | int dot: 0 | matrix cores: none
build: 6997 (86fde91e6) with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for aarch64-linux-gnu
main: llama backend init
main: load the model and apply lora adapter, if any
llama_model_load_from_file_impl: using device Vulkan0 (Mali-G720) (unknown id) - 11701 MiB free
llama_model_loader: loaded meta data with 22 key-value pairs and 338 tensors from models/qwen2-1_5b-instruct-fp16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = qwen2-1_5b-instruct
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 28
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 1536
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 8960
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 12
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 2
llama_model_loader: - kv   8:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv   9:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 1
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  19:                    tokenizer.chat_template str              = {% for message in messages %}{% if lo...
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  141 tensors
llama_model_loader: - type  f16:  197 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = F16
print_info: file size   = 2.88 GiB (16.00 BPW) 
load: printing all EOG tokens:
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load: special tokens cache size = 293
load: token to piece cache size = 0.9338 MB
print_info: arch             = qwen2
print_info: vocab_only       = 0
print_info: n_ctx_train      = 32768
print_info: n_embd           = 1536
print_info: n_embd_inp       = 1536
print_info: n_layer          = 28
print_info: n_head           = 12
print_info: n_head_kv        = 2
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 6
print_info: n_embd_k_gqa     = 256
print_info: n_embd_v_gqa     = 256
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 8960
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: n_expert_groups  = 0
print_info: n_group_used     = 0
print_info: causal attn      = 1
print_info: pooling type     = -1
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 32768
print_info: rope_finetuned   = unknown
print_info: model type       = 1.5B
print_info: model params     = 1.54 B
print_info: general.name     = qwen2-1_5b-instruct
print_info: vocab type       = BPE
print_info: n_vocab          = 151936
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
ggml_vulkan: Device memory allocation of size 963584000 failed.
ggml_vulkan: vk::Device::allocateMemory: ErrorOutOfDeviceMemory
alloc_tensor_range: failed to allocate Vulkan0 buffer of size 963584000
llama_model_load: error loading model: unable to allocate Vulkan0 buffer
llama_model_load_from_file_impl: failed to load model
common_init_from_params: failed to load model 'models/qwen2-1_5b-instruct-fp16.gguf', try reducing --n-gpu-layers if you're running out of VRAM
main: error: unable to load model
```

Only thing is definetely fishy is that the allocation is rather small compared to device's memory: 963584000 is only 918 Mb, while 
```
orion@cix-acpi:~/github/llama.cpp$ free -m
               total        used        free      shared  buff/cache   available
Mem:           15602        1151       10910         216        3979       14450
Swap:          23403           0       23403

```

Seems like plenty.
@TinyServal since you were asking about the bench-marking of Orion O6. Due to this I cannot benchmark yet, but I'll try with libmali.

If anyone sees it and knows PanVK driver developers, can pass this feedback.

**Comment by TinyServal** [comment]
Report PanVK bugs at the mesa repo: https://gitlab.freedesktop.org/mesa/mesa/-/issues

PanVK caps the total memory usage to 50% or 75% of the system memory depending on memory size: https://gitlab.freedesktop.org/mesa/mesa/-/blob/25.3/src/panfrost/vulkan/panvk_physical_device.c?ref_type=heads#L455-473

919MiB is well within the 75% limit (12GiB) so I don't think you're hitting that limit. I have seen similar OOM or DeviceLost crashes on a G610 earlier this year, gave up on that board because I don't have time to debug mesa drivers, and the G610 is too slow to be useful anyway.
