### ISSUE TITLE
imatrix stops at "compute_imatrix: tokenizing the input .."?

### ISSUE THREAD

**Issue by PhoenixtheII** [ggerganov/llama.cpp#5442]
Windows 11, b216 from cublas 12.2 build

`PS C:\stable-diffusion-webui-master\llama\bin> .\imatrix.exe -m D:\git\Yi-34B-200K-RPMerge\Yi-34B-200K-RPMerge.gguf -f ..\llama.cpp\wikitext-2-raw\wiki.train.raw -o D:\git\Yi-34B-200K-RPMerge\imatrix.dat -c 512 --chunks 32
main: build = 2116 (f026f812)
main: built with MSVC 19.37.32826.1 for x64
main: seed  = 1707585985
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3080 Ti, compute capability 8.6, VMM: yes
llama_model_loader: loaded meta data with 20 key-value pairs and 543 tensors from D:\git\Yi-34B-200K-RPMerge\Yi-34B-200K-RPMerge.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Yi-34B-200K-RPMerge
llama_model_loader: - kv   2:                          llama.block_count u32              = 60
llama_model_loader: - kv   3:                       llama.context_length u32              = 200000
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 7168
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 20480
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 56
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv   9:                llama.use_parallel_residual bool             = true
llama_model_loader: - kv  10:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr[str,64002]   = ["<unk>", "<|startoftext|>", "<|endof...
llama_model_loader: - kv  12:                  tokenizer.ggml.token_type arr[i32,64002]   = [3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  13:                      tokenizer.ggml.merges arr[str,110029]  = ["", "", "-- >", "- ->", "-- ...
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  18:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  19:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type  f16:  422 tensors
llm_load_vocab: mismatch in special tokens definition ( 500/64002 vs 5/64002 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 64002
llm_load_print_meta: n_merges         = 110029
llm_load_print_meta: n_ctx_train      = 200000
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 20480
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 200000
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 30B
llm_load_print_meta: model ftype      = F16 (guessed)
llm_load_print_meta: model params     = 34.39 B
llm_load_print_meta: model size       = 64.06 GiB (16.00 BPW)
llm_load_print_meta: general.name     = Yi-34B-200K-RPMerge
llm_load_print_meta: BOS token        = 1 '<|startoftext|>'
llm_load_print_meta: EOS token        = 2 '<|endoftext|>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 100 '?'
llm_load_tensors: ggml ctx size =    0.21 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/61 layers to GPU
llm_load_tensors:        CPU buffer size = 65593.36 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   120.00 MiB
llama_new_context_with_model: KV self size  =  120.00 MiB, K (f16):   60.00 MiB, V (f16):   60.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    15.01 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =   152.90 MiB
llama_new_context_with_model: graph splits (measure): 1

system_info: n_threads = 8 / 16 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
compute_imatrix: tokenizing the input ..`

No imatrix.dat to be seen anywhere...

There's 0 documentation after 4 hours of searching how-to this thing properly either.

I'm probably therefor doing something wrong.

**Comment by askmyteapot** [comment]
So for starters, do you have enough CPU ram to load it into memory without swapping to disk? 
That model at f16 is 66GB. If its using swap, it will be extremely slow. 

I have successfully computed imatrix on Q8_0 models (Mixtral) and it still gives an improvement to PPL. (And it uses half the RAM)

Also, you can offload some layers to the GPU with ``-ngl xx``

Other than that, your command is correct.

**Comment by PhoenixtheII** [comment]
@askmyteapot Uh, it's doing the same thing on a 13b model I tried to imatrix aswell...

I got 64GB RAM, 12 GB VRAM. I am aware that a bit of swapping will be happening on a 70b... 

I just want to see it work :/
