### ISSUE TITLE
Performance improvement in Quantized models

### ISSUE THREAD

**Issue by mahdi259** [ggerganov/llama.cpp#5443]
Hi
There is an algorithm called ULPPACK that enhances data compression and computation of quantized models.
Is it practical to use such methods?

**Comment by JohannesGaessler** [comment]
ULPPACK relies on higher-bit multiplication instructions to work. For example, it makes it possible to do multiple (2 bit, 2 bit) -> 4 bit multiplications simultaneously with a single 8 bit multiplication. But in CUDA at least there is no suitable instruction to do this quickly. You could at most use this for 8 bit integers but there is a better instruction for that precision.

**Comment by mahdi259** [comment]
I imagine running LLM on an embedded system with limited memory and a single CPU (like ARM).

**Comment by mahdi259** [comment]
Those devices have 32 bit multipliers which are inefficient to multiply 2 bit or 4 bit values. They also have limited computation capability and memory resources that ULPPACK can play a main role.

**Comment by mahdi259** [comment]
I need a mentor and I'm enthusiastic to contribute in this field.

**Comment by JohannesGaessler** [comment]
I am in principle willing to help with onboarding new devs (my speciality is with CUDA though). But in llama.cpp ULPPACK based on 32 bit integer multiplication would only work for 2 bit quantization so I honestly don't see the point.

**Comment by mahdi259** [comment]
No problem. My understanding is that llama.cpp doesn't focus on embedded devices. 
I think there is a distance between utilizing LLMs in real world embedded devices and I will try to find a way to fill it.
Thanks for replying
