### ISSUE TITLE
general.name wrong and unchangeable

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [ggerganov/llama.cpp#5461]
Linux (Ubuntu 22.04.3 LTS), `llama.cpp/main --version` = 2116 (f026f812) – was current as of 2024-02-10

#### Convert HF model to GGUF:

    python llama.cpp/convert.py "models/my_model" --outfile "my_model-GGUF/my_model.F16.gguf"

#### Check its name:

    gguf-dump "my_model-GGUF/my_model.F16.gguf" | grep general.name

#### See it's named "models" instead of "my_model" or "my_model-GGUF":

      5: STRING     |        1 | general.name = 'models'

#### Try to change it:

    llama.cpp/gguf-py/scripts/gguf-set-metadata.py "my_model-GGUF/my_model.F16.gguf" general.name "my_model-GGUF"

#### But it fails:

    ! This tool only supports changing simple values, 'general.name' has unsupported type [<GGUFValueType.STRING: 8>]

#### Why it's a problem:

Only after quantizing hundreds of GB and uploading them to HF over many hours did I notice the wrong name, and since I can't change it, I've had to redo the whole process again - wasting a lot of space, bandwidth, and time.

#### What if the HF model is in the current working directory?

Then general.name is set to '.'!

### Proposed solution:

1. Add a command line argument for convert and quantize commands to manually specify the model name
2. If that option isn't set, take the last directory/file (which is the HF model) instead of the path to it as the model name
3. Allow gguf-set-metadata to change the model name

### Thank you!

**Comment by vriesdemichael** [comment]
Set metadata does not work for any string values at the moment

The method for converting the new value is stored here: 
https://github.com/ggerganov/llama.cpp/blob/73122473ffd73030146276dbb85da7c8021a3ee4/gguf-py/gguf/gguf_reader.py#L70-L82
But it does not have a value for strings.

The string values are written like this
https://github.com/ggerganov/llama.cpp/blob/73122473ffd73030146276dbb85da7c8021a3ee4/gguf-py/gguf/gguf_writer.py#L172-L175
With an extra encode call before storing

It would require a small rewrite of the set metadata code to do this properly without patching in strings as an extra condition
