### ISSUE TITLE
Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [ggerganov/llama.cpp#5476]
@ggerganov, hi

**Describe the feature**
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd gpus and speed up work on amd if cuda code is optimized vs opencl.

**Comment by Green-Sky** [comment]
If you have an amd card, you can try it yourself. It is supposed to be a binary drop-in replacement.
I don't have an amd card, so I can not give it a try, would be cool if someone could try it out and report back :)
the accompanying phoronix article: https://www.phoronix.com/review/radeon-cuda-zluda

**Comment by Green-Sky** [comment]
there already exists an issue tracking this: https://github.com/vosen/ZLUDA/issues/64

**Comment by han-minhee** [comment]
I'm glad to see more options coming, but would it give a substantial benefit over concentrating on the ROCm implementation?

**Comment by Green-Sky** [comment]
Unlikely. AMD is spending a lot on their GPGPU frameworks like ROCm. So it is to be expected that it will outperform ZLUDA. Seeing NVIDIAs success in the market, they are very much focused on catching up with the best way forward.

**Comment by han-minhee** [comment]
You're right. I'd rather want to see if ROCm specific optimizaitons would be possible, i.e. implementing it in separate code base instead of sharing it with the CUDA implementation.

**Comment by DGdev91** [comment]
If i'm not wrong, Zluda uses ROCm/HIP as backend. 
Then, it would't be a better solution than just using HipBLAS, wich is already supoorted.

It can still be interesting to find out why zluda isn't currently able to handle llama.cpp, but that's a zluda issue.

**Comment by sorasoras** [comment]
> If i'm not wrong, Zluda uses ROCm/HIP as backend. Then, it would't be a better solution than just using HipBLAS, wich is already supoorted.
> 
> It can still be interesting to find out why zluda isn't currently able to handle llama.cpp, but that's a zluda issue.

I think it is more like using rocm but not hipblas. There are couple app with cuda work faster on zluda than rocblas.
