### ISSUE TITLE
Some memory management bugs

### ISSUE THREAD

**Issue by An0nie** [ggerganov/llama.cpp#5498]
In some places, clip_image_f32-s get allocated as arrays
https://github.com/ggerganov/llama.cpp/blob/594fca3fefe27b8e95cfb1656eb0e160ad15a793/examples/llava/clip.cpp#L1560
https://github.com/ggerganov/llama.cpp/blob/594fca3fefe27b8e95cfb1656eb0e160ad15a793/examples/llava/clip.cpp#L1652
However, here https://github.com/ggerganov/llama.cpp/blob/594fca3fefe27b8e95cfb1656eb0e160ad15a793/examples/llava/clip.cpp#L1499
the code tries to free every element of the array even though it was allocated as one block.

Also, here and possibly other places, clip_image_f32_free() is used to free the array, which calls delete instead of delete[].
https://github.com/ggerganov/llama.cpp/blob/594fca3fefe27b8e95cfb1656eb0e160ad15a793/examples/server/server.cpp#L1000

Are there any reasons why smart pointers are barely used? Std strings and vectors seem to be common in the code.

**Comment by cmp-nct** [comment]
The code originally used a vector for the img_res_V and was last minute adapted to keep the API plain C, that's where a couple errors sneaked in.
There are two PRs fixing issues atm:
https://github.com/ggerganov/llama.cpp/pull/5495
https://github.com/ggerganov/llama.cpp/pull/5491

**Comment by An0nie** [comment]
I see, and what's your opinion about splitting up files once they get big, and OOP approaches?

**Comment by An0nie** [comment]
I use those in my coding style, so is there any place where that would be useful?
