### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by miolini** [ggerganov/llama.cpp#55]
Hey!

Thank you for your amazing job!

I'm curious is it possible to use RLHF feedback after a response to make small incremental adjustments in a tuning process? For example, if the user decides to fine-tune after an incorrect answer, can the model spend 60 seconds in the fine-tuning phase, save a checkpoint to disk, and then move on to the next question?

**Comment by gjmulder** [comment]
I believe `llama.ccp` is only for inference, not training. Check out [chatllama](https://github.com/nebuly-ai/nebullvm/tree/main/apps/accelerate/chatllama), but you will likely need some high-end GPUs to do RLHF. Alternatively, look at [accelerate trl](https://github.com/lvwerra/trl) for performing RHLF on models that fit on consumer GPUs.

**Comment by miolini** [comment]
@gjmulder I would like to continue narrative to run such processes on CPU only. Even if it super slow I think it's possible to spend some time budget (60 secs) to improve a bit weights and make overall process of self improvment like 
in Gödel machines.

**Comment by gjmulder** [comment]
Check out thread https://github.com/ggerganov/llama.cpp/issues/23. This would allow you to have ChatGPT-type narrative conversations with the model, but is not RLHF.
