### ISSUE TITLE
does n_predict actually affect the model in generating the response?

### ISSUE THREAD

**Issue by tranlm** [ggerganov/llama.cpp#5517]
I'm reading through both the code and readme to understand how the n-predict is used during the generation of the tokens. The readme states that the number can "[influence the length of the generated text](https://github.com/ggerganov/llama.cpp/blob/4524290e87b8e107cc2b56e1251751546f4b9051/examples/main/README.md?plain=1#L165)" but the code seems to just apply a truncation (i.e. it'll stop prompting the model after the decrement reaches 0). Is the readme stating that the n-predict will affect the model generated text (e.g. get the model to produce shorter responses)? If so, can you point me to where this is actually happening?

**Comment by cmp-nct** [comment]
the model has no idea about it, it is indeed just a limit

**Comment by tranlm** [comment]
Thank you for confirming!
