### ISSUE TITLE
Cannot build in CentOS

### ISSUE THREAD

**Issue by thedmdim** [ggerganov/llama.cpp#552]
Hello, can somebody help me build llama.cpp on CentOS? Or maybe provide binaries?

```bash
[root@vmd89384 llama.cpp]# make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:  
I CC:       cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
I CXX:      g++ (GCC) 4.9.2

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3   -c ggml.c -o ggml.o
ggml.c:77:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make: *** [ggml.o] Error 1
[root@vmd89384 llama.cpp]# 
```

I use latest code of this repo, gcc version is 4.9.2

uname is `x86_64 x86_64 x86_64 GNU/Linux`

**Comment by anzz1** [comment]
Somehow your `cc` and `gcc` points to different versions of GCC.
```
CC:       cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
CXX:      g++ (GCC) 4.9.2
```
Quick google search tells me that the `<stdatomic.h>` C11 funcs require at least GCC 4.9, which you already seem to have.

One of these could help:

a) try using `make CC=gcc-4.9`

b) try fixing your system so that `cc` points to the latest `gcc` 

c) if you are unsuccessful, google told me that supplanting the stdatomic.h with this could work: https://gist.github.com/nhatminhle/5181506

**Comment by gjmulder** [comment]
Try https://superuser.com/questions/1640048/how-to-properly-upgrade-gcc-on-centos-7

**Comment by gjmulder** [comment]
[Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1) before submitting new issues

**Comment by thedmdim** [comment]
Hello, if anyone will face the same, do:

```bash
sudo yum install libmpc-devel mpfr-devel gmp-devel

# current latest gcc version
curl ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-12.2.0/gcc-12.2.0.tar.gz -O
tar xvf gcc-12.2.0.tar.gz

cd gcc-12.2.0.tar.gz
./configure --disable-multilib --enable-languages=c,c++

# change -j <cores_num> if you have more cpu cores for building be faster
make -j 4 
make install
```
then check gcc version (should be 12.2.0):
```bash
gcc --version
```
 then

```bash
export CC=gcc
```

and finally:
```bash
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
make
```

**Comment by donote** [comment]
I meet the same error in centos7.9, through this method, it's work, thank you very much!

**Comment by donote** [comment]
> > I meet the same error in centos7.9, through this method, it's work, thank you very much!
> 
> notice that, if your cuda version is 11.7, and in same open source package like LLM BELLE, that's need cpp extension of CUDA, but the extension required g++ version is (>=6.00 & <12.0). so, to avoid potential errors, i reinstall gcc 11.3.0 `curl http://ftp.lip6.fr/pub/gcc/releases/gcc-11.3.0/gcc-11.3.0.tar.gz`

said, gcc 11.3 is not work for llama.cpp, error again ...
----
I CC:       cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
I CXX:      g++ (GCC) 11.3.0

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
ggml.c:76:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make: *** [ggml.o] Error 1

**Comment by xinghuang2050** [comment]
I CC:       gcc (GCC) 5.4.0
I CXX:      g++ (GCC) 5.4.0
gcc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
ggml.c: In function ‘ggml_vec_dot_q4_2_q8_0’:
ggml.c:3112:40: warning: implicit declaration of function ‘_mm256_set_m128’ [-Wimplicit-function-declaration]
         const __m256 d = _mm256_mul_ps(_mm256_set_m128(d1, d0), _mm256_broadcast_ss(&y[i].d));
                                        ^
ggml.c:3112:40: error: incompatible type for argument 1 of ‘_mm256_mul_ps’

It does not wok for gcc version 5.4.0

**Comment by arkii** [comment]
On CentOS7.x, I solved it in this simple way

enable scl repo

`sudo yum install -y centos-release-scl`

install devtoolset 11

`yum install devtoolset-11`

enable new version 

`source /opt/rh/devtoolset-11/enable`

then check gcc version (should be upper 11.0.0):

`gcc --version`

and finally:

```
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
make
```
