### ISSUE TITLE
Windows Defender detects Virus in Multiple zip files.

### ISSUE THREAD

**Issue by erikpro008** [ggerganov/llama.cpp#5556]
I have downloaded the following zip files : "llama-b2167-bin-win-cublas-cu12.2.0-x64.zip", "llama-b2167-bin-win-vulkan-x64.zip", "llama-b2167-bin-win-kompute-x64.zip".

While extracting those zips into a folder on Windows 11, the Windows Defender jumped up and dected some things as a virus, see Screenshot below:
![Screenshot 2024-02-17 213417](https://github.com/ggerganov/llama.cpp/assets/88928154/d472e7cf-223c-4c66-9fda-658b1544313f)

my questions is are the files save or not, or is this a windows Defender kind of bug :S?

I have extracted an older version of llamacpp like 2 weeks ago and there was not any issues with it "llama-b2131-bin-win-clblast-x64.zip", extracting this file doesnt produce any issues, as tested.

**Comment by kaktuss77** [comment]
hi,

Same here,

**Comment by noshbar** [comment]
I got the same with the b2222 release.
Only complains about 1 file, though, `test-model-load-cancel.exe`

![image](https://github.com/ggerganov/llama.cpp/assets/1892994/c7d8d60c-a8fe-477b-a970-c95da4ac9bff)

OS details
![image](https://github.com/ggerganov/llama.cpp/assets/1892994/2db950f1-bd07-4aa4-9839-58a1dfa6adf9)

**Comment by JaCraig** [comment]
Also had the b2222 release come up with the same virus message. Submitted it to MS for review. Initial feedback shows test-model-load-cancel coming back with Program:Win32/Wacapew.C!ml with their online scan.

**Comment by headquarter8302** [comment]
Same here, with the same detection definitions, I had to download using `invoke-webrequest` to bypass defender blocking the download. Also have submitted the file to MS Security
