### ISSUE TITLE
Vulkan with multimodal models

### ISSUE THREAD

**Issue by ddpasa** [ggerganov/llama.cpp#5583]
I'm coming here from ollama, where I'm trying to expose llama.cpp's vulkan backend in ollama (https://github.com/ollama/ollama/pull/2578).  It works fine for models like phi-2 and tinyllama, but multimodal models such as llava and bakllava are  giving empty output when used with vulkan (they work fine when run by cpu).

I'm just wondering if the vulkan backend has been tested with multimodal models?

**Comment by stduhpf** [comment]
I have observed the same thing. It seems that the image emebddings are not generated properly with Vulkan.

Related issue: https://github.com/ggerganov/llama.cpp/issues/5545

**Comment by couillonnade** [comment]
I have observed the same thing with Metal on macOS with Silicon.
