### ISSUE TITLE
Orion14b conversion issue

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#5596]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

`python3 convert.py models/Orion-14B-Chat`

I got "llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 444, got 363"
There is some issue with the script

**Comment by ylsdamxssjxxdd** [comment]
try this 
python convert-hf-to-gguf.py models/Orion-14B-Chat

**Comment by sorasoras** [comment]
> try this python convert-hf-to-gguf.py models/Orion-14B-Chat

Ye, That never work
