### ISSUE TITLE
Broken seed?

### ISSUE THREAD

**Issue by BadisG** [ggerganov/llama.cpp#561]
Hello,

Is it me or the seed doesn't work anymore? No matter which seed I choose I always get the same output now.

**Comment by slaren** [comment]
The code seems fine. What is your command line? if you use very strict sampling parameters it may ultimately remove all randomness from the output (the most likely token will always be chosen).

**Comment by BadisG** [comment]
here's my sampling parameters

```
./Unix-build/main -m ./models/llama7b-4bit-GPTQ.bin -t 14 -n 2024 -c 2024 --temp 0.7 --top_k 40 --top_p 0.1 --repeat_last_n 2048 --repeat_penalty 1.25 --color --n_parts 1 -p "$(cat STORY.txt)"
```

**Comment by slaren** [comment]
The top_p may be too low, try a higher value.

**Comment by BadisG** [comment]
Oh yeah, that was exactly it! Now I get new outputs, thanks!! 😄
