### ISSUE TITLE
Mixtral 8x7b lora conversion support 

### ISSUE THREAD

**Issue by TaupoB** [ggerganov/llama.cpp#5610]
Tried to convert an adapter for Mixtral, but received this error:
`Error: could not map tensor name base_model.model.base_model.model.model.layers.0.self_attn.k_proj.lora_A.weight
 Note: the arch parameter must be specified if the model is not llama`

I'm aware that conversion supported only for limited list of model, but since Mixtral is based on llama2, I assumed that converting adapters for llama would work out for Mixtral.
Is there any plan to support mixtral adapters?
Or are there any other ways to get the adapter in ggml format for Mixtral?

Comand which i used:
`llama.cpp/convert-lora-to-ggml.py notebooks/Mixtral_finetune-v2/checkpoint-2`
Link to notebook: https://colab.research.google.com/drive/1iNd53DqAk3R7GG9g6NzFJbtNpJYe2FnR?usp=sharing

**Comment by slaren** [comment]
It's probably due to the duplicated `base_model.model` prefix in the tensor names. The conversion script only removes this prefix once.
