### ISSUE TITLE
Which sampling algorithms are used?

### ISSUE THREAD

**Issue by sftekin** [ggerganov/llama.cpp#5614]
![Screenshot from 2024-02-19 10-44-03](https://github.com/ggerganov/llama.cpp/assets/45334026/3db21af2-6141-4710-b774-3a3869c3fde9)

1. Which sampling algorithms are the default for the Llama class? When I debugged it, I realized that most of them are called in subsequently; top-k -> tail-free -> typical -> top-p -> min-p -> temp. Do they operate separately or cascaded? I lose track when I step into methods and they call from _lib.

2. Does the sampling algorithm change according to the model I load? For example, if I load Mixtral, will I automatically switch to a different sampling than Llama?

Thank you.

**Comment by JohannesGaessler** [comment]
Wrong repository, you'll want to ask in the repository for your Python bindings, probably [this one](https://github.com/abetlen/llama-cpp-python).
