### ISSUE TITLE
Android OpenCL question 

### ISSUE THREAD

**Issue by anthonyliot** [ggerganov/llama.cpp#5621]
Hi, 

I was able to build a version of Llama using clblast + llama on Android. I am using this model ggml-model-q4_0.gguf and ggml-model-f32.gguf

When running it seems to be working even if the output look weird and not matching the question but at least I have some response. I can have some error in my default params for sure ;)

My issues is even if I can detect I am initializing OpenCL it always run on CPU. How I can enforce to run on GPU / OpenCL backend ?

Also I see in thecae the KF16 support is commented for OpenCL any reason ?

Thanks

**Comment by Jeximo** [comment]
> Hi,
> 
> I am using this model ggml-model-q4_0.gguf and ggml-model-f32.gguf
> 

Unclear,  but this doesn't seem to be the focus of your question.

> 
> My issues is even if I can detect I am initializing OpenCL it always run on CPU. How I can enforce to run on GPU / OpenCL backend ?

Offloading to GPU requires the `-ngl` parameter,  i.e. `./main ~/model.gguf -ngl 50`.  [ReadMe](https://github.com/ggerganov/llama.cpp/blob/6560bed3f066c876682464762cad90f1e28e3f1b/examples/main/README.md?plain=1#L318)



> 
> Also I see in thecae the KF16 support is commented for OpenCL any reason ?


I think f16 is not supported on Android,  maybe someone will confirm.

**Comment by anthonyliot** [comment]
@Jeximo thanks for you response, yes I use the n-GPU-layers on the params for using GPU. I used 64 in my test.

for KP16 the extension on my device exist.
Typically the KHR_FP16 is inside the list but the code to detect the extension is commented in the main branch.

on android using debug I can confirm the opencl_init is called and after removing the comment on the extension,  the bool flag for the fp16 is true

**Comment by anthonyliot** [comment]
I finally found my problem, the ngl parameter was not pass correctly in the JNI code and was 0 because of that the device use CPU. Now I have a SIGBUS error but there is progress :)

Thanks for your help.

**Comment by Jimskns** [comment]
How is the acceleration effect of OpenCL compared with CPU backend on Android?@anthonyliot
Thansk.

**Comment by anthonyliot** [comment]
Hi @Jimskns 

So the performance are not that great in OpenCL on the android device I tested. All of them was using Qualcomm OpenCL Driver. Also I made a mistake and FP16 is not supported on the device I tried.

I tried 1B / 3B / 7B on devices, and every time the CPU backend perform better. I play with mixing CPU/GPU also full GPU (not for the 7B) but in all my test for now CL is slower.

I am still looking into it to see if there is a way to get improvement on GPU

**Comment by Jimskns** [comment]
Good Job@anthonyliot

**Comment by qtyandhasee** [comment]
Hello! I am also trying to use Android OpenCL recently, I also encountered the same problem as you, when using gMl-model-q4_0.gguf inference model on Android device (Qualcomm) GPU can get confusing output, I was wondering how you finally solved this problem? Looking forward to your reply, thank you very much

**Comment by gustrd** [comment]
Pointing another thread discussing this topic: #7016

**Comment by okias** [comment]
> Hi @Jimskns
> 
> So the performance are not that great in OpenCL on the android device I tested. All of them was using Qualcomm OpenCL Driver. Also I made a mistake and FP16 is not supported on the device I tried.
> 
> I tried 1B / 3B / 7B on devices, and every time the CPU backend perform better. I play with mixing CPU/GPU also full GPU (not for the 7B) but in all my test for now CL is slower.
> 
> I am still looking into it to see if there is a way to get improvement on GPU

I would encourage you use Mesa Freedreno driver + OpenCL supoort (for now living in [MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30835/), but hopefully going to be merged soon).

I benchmarked Adreno 630 vs 8x CPU (4big, 4small) on SDM845 and the GPU won by a lot with tinygrad.

**Comment by fish4terrisa-MSDSM** [comment]
> > Hi [@Jimskns](https://github.com/Jimskns)
> > So the performance are not that great in OpenCL on the android device I tested. All of them was using Qualcomm OpenCL Driver. Also I made a mistake and FP16 is not supported on the device I tried.
> > I tried 1B / 3B / 7B on devices, and every time the CPU backend perform better. I play with mixing CPU/GPU also full GPU (not for the 7B) but in all my test for now CL is slower.
> > I am still looking into it to see if there is a way to get improvement on GPU
> 
> I would encourage you use Mesa Freedreno driver + OpenCL supoort (for now living in [MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30835/), but hopefully going to be merged soon).
> 
> I benchmarked Adreno 630 vs 8x CPU (4big, 4small) on SDM845 and the GPU won by a lot with tinygrad (double perf and small consumption).

I benchmarked freedreno vulkan(with kgsl patch, since I'm using downstream Amdroid kernel. And since everything is based on turnip vulkan, I assume that freedreno opencl will be slightly slower) and libhybris(Android) Opencl on a SD8gen2 platform using koboldcpp.
Here's the result:
```
Timestamp,Backend,Layers,Model,MaxCtx,GenAmount,ProcessingTime,ProcessingSpeed,GenerationTime,GenerationSpeed,TotalTime,Output,Flags
2025-04-06 18:29:45.433298+00:00,koboldcpp_clblast.so,0,Llama-3.2-3B-Instruct-Q8_0,4096,100,204.56,19.53,28.75,3.48,233.31, 1 1 1 1,NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Benchmark Completed - v1.87.4 Results:
======
Flags: NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Timestamp: 2025-04-06 18:29:45.433298+00:00
Backend: koboldcpp_clblast.so
Layers: 0
Model: Llama-3.2-3B-Instruct-Q8_0
MaxCtx: 4096
GenAmount: 100
-----
ProcessingTime: 204.560s
ProcessingSpeed: 19.53T/s
GenerationTime: 28.750s
GenerationSpeed: 3.48T/s
TotalTime: 233.310s
Output:  1 1 1 1
-----

2025-04-06 18:36:26.104177+00:00,koboldcpp_vulkan.so,0,Llama-3.2-3B-Instruct-Q8_0,4096,100,311.15,12.84,29.17,3.43,340.32,,NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Benchmark Completed - v1.87.4 Results:
======
Flags: NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Timestamp: 2025-04-06 18:36:26.104177+00:00
Backend: koboldcpp_vulkan.so
Layers: 0
Model: Llama-3.2-3B-Instruct-Q8_0
MaxCtx: 4096
GenAmount: 100
-----
ProcessingTime: 311.153s
ProcessingSpeed: 12.84T/s
GenerationTime: 29.168s
GenerationSpeed: 3.43T/s
TotalTime: 340.321s
Output:
-----
```
It seems very clear that Android OpenCL's performance is much better than freedreno vulkan. It's really a bad idea to cut down the OpenCK backend.

**Comment by fish4terrisa-MSDSM** [comment]
> > Hi [@Jimskns](https://github.com/Jimskns)
> > So the performance are not that great in OpenCL on the android device I tested. All of them was using Qualcomm OpenCL Driver. Also I made a mistake and FP16 is not supported on the device I tried.
> > I tried 1B / 3B / 7B on devices, and every time the CPU backend perform better. I play with mixing CPU/GPU also full GPU (not for the 7B) but in all my test for now CL is slower.
> > I am still looking into it to see if there is a way to get improvement on GPU
> 
> I would encourage you use Mesa Freedreno driver + OpenCL supoort (for now living in [MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30835/), but hopefully going to be merged soon).
> 
> I benchmarked Adreno 630 vs 8x CPU (4big, 4small) on SDM845 and the GPU won by a lot with tinygrad (double perf and small consumption).

Unfortunately, no. I benchmarked freedreno vulkan(with kgsl patch, since I'm using downstream Amdroid kernel. And since everything is based on turnip vulkan, I assume that freedreno opencl will be slightly slower) and libhybris(Android) Opencl on a SD8gen2 platform using koboldcpp.
Here's the result:
```
Timestamp,Backend,Layers,Model,MaxCtx,GenAmount,ProcessingTime,ProcessingSpeed,GenerationTime,GenerationSpeed,TotalTime,Output,Flags
2025-04-06 18:29:45.433298+00:00,koboldcpp_clblast.so,0,Llama-3.2-3B-Instruct-Q8_0,4096,100,204.56,19.53,28.75,3.48,233.31, 1 1 1 1,NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Benchmark Completed - v1.87.4 Results:
======
Flags: NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Timestamp: 2025-04-06 18:29:45.433298+00:00
Backend: koboldcpp_clblast.so
Layers: 0
Model: Llama-3.2-3B-Instruct-Q8_0
MaxCtx: 4096
GenAmount: 100
-----
ProcessingTime: 204.560s
ProcessingSpeed: 19.53T/s
GenerationTime: 28.750s
GenerationSpeed: 3.48T/s
TotalTime: 233.310s
Output:  1 1 1 1
-----

2025-04-06 18:36:26.104177+00:00,koboldcpp_vulkan.so,0,Llama-3.2-3B-Instruct-Q8_0,4096,100,311.15,12.84,29.17,3.43,340.32,,NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Benchmark Completed - v1.87.4 Results:
======
Flags: NoAVX2=False Threads=3 HighPriority=False Cublas_Args=None Tensor_Split=None BlasThreads=3 BlasBatchSize=512 FlashAttention=False KvCache=0
Timestamp: 2025-04-06 18:36:26.104177+00:00
Backend: koboldcpp_vulkan.so
Layers: 0
Model: Llama-3.2-3B-Instruct-Q8_0
MaxCtx: 4096
GenAmount: 100
-----
ProcessingTime: 311.153s
ProcessingSpeed: 12.84T/s
GenerationTime: 29.168s
GenerationSpeed: 3.43T/s
TotalTime: 340.321s
Output:
-----
```
It seems very clear that Android OpenCL's performance is much better than freedreno vulkan.
