### ISSUE TITLE
What does the metal buffer point to?

### ISSUE THREAD

**Issue by jafioti** [ggerganov/llama.cpp#5623]
When I print out the various metal buffer content pointers during a forward pass for different tensors (`[id_src0 contents]`), they all point to the same memory. When I print the tensor->data pointer, it points to different memory. A simple explination of where the actual data is would be much appreciated.

**Comment by jafioti** [comment]
As a quick follow up, I have an op I use to dump state to a file in metal. Here is the current implementation in ggml_metal.m:
```
case GGML_OP_DUMP: // My new op
                    {
                        // Commit command encoder / buffer / wait until completed so the id_src0 buffer is materialized
                        [encoder endEncoding];
                        [command_buffer commit];
                        [command_buffer waitUntilCompleted];
                        command_buffer = [ctx->queue commandBufferWithUnretainedReferences];
                        encoder = [command_buffer computeCommandEncoderWithDescriptor: edesc];

                        printf("Name: %s\n", src0->name);
                        // Write tensor to file
                        // Get n elements
                        int64_t n_elements = 1;
                        for (int i = 0; i < GGML_MAX_DIMS; ++i) {
                            if (src0->ne[i] != 0) {
                                n_elements *= src0->ne[i];
                            }
                        }
                        void* contents = [id_src0 contents]; // Usually only points to one tensor's data for evey tensor. Why?
                        void* data_contents = src0->data; // Sometimes is correct
                        // Get file path
                        const size_t str_len = dst->op_params[0];
                        char *filePath = malloc((str_len + 1) * sizeof(char));
                        for (size_t i = 0; i < str_len; ++i) {
                            filePath[i] = (char)dst->op_params[i + 1];
                        }
                        filePath[str_len] = '\0';
                        printf("File: %s\n", filePath);
                        // Open the file in binary mode for writing
                        remove(filePath);
                        FILE *file = fopen(filePath, "wb");
                        if (!file) {
                            printf("\nfailed fopen\n");
                        }

                        // Write the entire array to the file in one go
                        size_t numElementsWritten = fwrite(data_contents, sizeof(float), n_elements, file);

                        // Check if the write was successful
                        if (numElementsWritten != n_elements) {
                            printf("\nError writing to the file.\n");
                        }
                        // Close the file
                        fclose(file);
                    } break;
```
Notice the metal command buffer handling at the beginning, to try to flush out the command buffer to materialize the data in the buffer. Is this correct? The id_src0 content pointer seems to always be wrong, and the tensor->data pointer sometimes seems to have 0s in it, but I can't work out a pattern.


@ggerganov Any help on this would be very appreciated!

**Comment by jafioti** [comment]
@ggerganov Do the callbacks work correctly with metal? As in, does the command buffer get ran before the callbacks are called? I can see a case where the command buffer hasn't ran yet, so the data in the buffers isn't generated yet. Similarly, I can also see a case where the buffer storing the data you want to print gets overwritten by another op before the callback is ran.

**Comment by ggerganov** [comment]
Should work correctly with all backends. Here is the relevant code for calling the callback:

https://github.com/ggerganov/llama.cpp/blob/973053d8b0d04809836b3339a50f68d9c842de90/ggml-backend.c#L1468-L1494

For each node for which the user requests the output data (i.e. callback returns `true` when `ask == true`) the backend will call the callback and allow the `dst` and `src` tensors for that node to be observed. The callback will be called only after the command buffer has been executed and before other command buffers are created, because as you can see in that code, we split the graph into separate sub-graphs and evaluate those one after the other.

**Comment by jafioti** [comment]
Thanks! I ended up going with using callbacks and adding some metadata I needed to the tensor struct, works great!
