### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by TruongGiangBT** [ggerganov/llama.cpp#5655]
> I apologize for the inconvenience. I am deploying a server with the following parameters: -cb -v --embedding -np 3 -c 8192 --host "0.0.0.0" -ngl 64. When I perform multiple embedding requests, a segmentation fault occurs. I noticed that if there are 2 slots performing the embedding task simultaneously, it causes an error. I hope to receive a solution soon. Thank you very much.

_Originally posted by @TruongGiangBT in https://github.com/ggerganov/llama.cpp/issues/3876#issuecomment-1955749669_

**Comment by phymbert** [comment]
Added in: [issues.feature](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/tests/features/issues.feature#L5)

@ggerganov @ngxson On it :+1:

**Comment by phymbert** [comment]
@TruongGiangBT Please confirm you do not face any error. anymore Feel free to reopen if any.

**Comment by TruongGiangBT** [comment]
@phymbert The segmentation fault error has been fixed. However, when I simultaneously execute multiple requests with the same input value, the embedding results are different.
My run command:
docker run  -dp 6900:8080 \
            --gpus '"device=1"' \
            --name vistral_llm \
            --restart=always \
            -v /home/gianght/llm_models/:/models mistral-wrapped-llama.cpp:full-cuda \
            --server -m /models/ggml-vistral-7B-chat-q4_1.gguf \
            -cb -v --embedding \
            -np 8 \
            -c 32768 \
            --host "0.0.0.0" \
            -ngl 64 \
            -b 4096
  Test code:
  
![image](https://github.com/ggerganov/llama.cpp/assets/52822318/c01c5205-8d95-422b-aa71-35a6ea94586c)

**Comment by phymbert** [comment]
Could you please open a dedicated discussion on embedding feature ?

**Comment by TruongGiangBT** [comment]
llama.cpp:
![image](https://github.com/ggerganov/llama.cpp/assets/52822318/b4c2c227-3315-4819-970a-9a13a31dbf03)

server.cpp:
![image](https://github.com/ggerganov/llama.cpp/assets/52822318/e9812d10-4e71-4717-b7aa-8280f430c028)

What do you think if i fix it like this? 
I have tried. With the same input, if the tokens of the sequence are entirely within one batch when decoding, then the embedding result will be the same. If the tokens of that slot are decoded multiple times, the results will be different, but the cosine similarity with the correct embedding result is > 0.999.

**Comment by ngxson** [comment]
It's true that there's a bug on the line that @TruongGiangBT pointed out: the `llama_get_embeddings` does not care about the fact that we're now having multi-seq.

The fact that you see different results was because you're using `-np 8` which allows having 8 seq per batch. `llama_get_embeddings` always returns the first seq.

`llama_get_embeddings_ith` should be correct in this case, though I've never used it so idk what's the correct argument.

It's better to check with @ggerganov I think.

**Comment by ngxson** [comment]
@TruongGiangBT Can you open a PR with the changes you proposed?

**Comment by TruongGiangBT** [comment]
My changes only help me run correctly to get the embedding result of multiple sequences in the decode batch. These modifications will affect the embedding function result. The crux of this issue is that we need to determine the index of the last token of the sequences, while also having a reasonable plan to store the embedding result of the sequences into ctx->embedding.

**Comment by phymbert** [comment]
Can you add a scenario in [issues.feature](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/tests/features/issues.feature) ? it will really help to trace your issue.

**Comment by ggerganov** [comment]
> If the tokens of that slot are decoded multiple times, the results will be different, but the cosine similarity with the correct embedding result is > 0.999.

I think this is expected due to the way the KV cache works. But I need to verify before explaining. If you could provide some basic instructions / commands to run this scenario it would be of great help. Otherwise, I have to invest time to create curl queries and / or bash scripts to match what you are doing

**Comment by TruongGiangBT** [comment]
@ggerganov I also think it might be due to the way the KV cache operates. Although the results are somewhat different, they can be acceptable. As discussed above, I encountered a problem with extracting embeddings and I have temporarily fixed it (I also shared it). But it only works well for my requirements, we need to find a general solution.

Docker command: 
docker run -dp 6900:8080 --gpus '"device=1"' --name vistral_llm -v /home/gianght/llm_models/:/models mistral-wrapped-llama.cpp:full-cuda --server -m /models/ggml-vistral-7B-chat-q4_1.gguf -cb -v --embedding -np 8 -c 32768 -ngl 64
Jupyter notebook test code:
import asyncio
import requests

async def requests_post_async(*args, **kwargs):
    return await asyncio.to_thread(requests.post, *args, **kwargs)

model_url = "http://127.0.0.1:6900" 
responses: list[requests.Response] = await asyncio.gather(*[requests_post_async(
        url= f"{model_url}/embedding",
        json= {"content": "0"*1024}
    ) for i in range(8)])
for response in responses:
    embedding = response.json()["embedding"]
    print(embedding[-4:])

Thank you

**Comment by ggerganov** [comment]
Ok thanks. I was willing to look more into this, but you are not making it easy for me.

I copied this code in a `test.py` file, and tried to indent it:

```py
import asyncio
import requests

async def requests_post_async(*args, **kwargs):
    return await asyncio.to_thread(requests.post, *args, **kwargs)

model_url = "http://127.0.0.1:6900"
responses: list[requests.Response] = await asyncio.gather(*[requests_post_async(
    url= f"{model_url}/embedding",
    json= {"content": "0"*1024}
    ) for i in range(8)])

for response in responses:
    embedding = response.json()["embedding"]
    print(embedding[-4:])
```

However I get an error:

```bash
$ ▶ python3 test.py 
  File "/Users/ggerganov/development/github/llama.cpp/test.py", line 8
    responses: list[requests.Response] = await asyncio.gather(*[requests_post_async(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
```

I have no idea what is the issue and don't want to spend time to fix it.

Providing simple repro instructions goes a long way to help maintainers help you
