### ISSUE TITLE
example/speculative: drafting fails completely when params.sparams.temp is set to 0

### ISSUE THREAD

**Issue by mscheong01** [ggerganov/llama.cpp#5657]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

In the current speculative.cpp implementation, params.sparams.temp is forced to -1.0f
However, if I change this value to 0:
<img width="761" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/54794500/81749cc4-5837-4157-a514-ff1b9e795db8">

draft sampling seems to fail completely:
<img width="902" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/54794500/e336cee1-ae64-4e67-9e71-7268f7268d9d">
(speculative.log)

Is this intended behavior?
I'm working on #5625 which removes the temperature limit so I'd like to get this fixed

**Comment by mscheong01** [comment]
I guess this is because when temperature is 0, the sampling logic does not output probabilites for each tokens?
<img width="490" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/54794500/0beddcdb-65b2-4891-a39d-f9e9b072d374">
If so, this seems like a viable solution.
<img width="769" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/54794500/7bf60b1a-fe50-4c04-82da-83de8b1eba23">

**Comment by ggerganov** [comment]
> If so, this seems like a viable solution.

Yes, this should work
