### ISSUE TITLE
Add UC Berkleys Large World Models

### ISSUE THREAD

**Issue by Venkman42** [ggerganov/llama.cpp#5659]
Can someone add support for the Large World Models(Text and Multimodal) from UC Berkley?
https://largeworldmodel.github.io/

**Comment by Engininja2** [comment]
The text models seem to just be llama so you can use convert.py for those

**Comment by dtiarks** [comment]
The interesting part is probably the implementation of ring attention

**Comment by Venkman42** [comment]
> The interesting part is probably the implementation of ring attention

I haven't totally understood it, but would it help with memory consumption on large contexts?

**Comment by dtiarks** [comment]
As far as I understood it ring attention is an efficient way to compute attention in many GPUs
