### ISSUE TITLE
Freshly converted PLaMo fails assertion: vocab.id_to_token.size() == vocab.token_to_id.size()

### ISSUE THREAD

**Issue by cebtenzzre** [ggerganov/llama.cpp#5669]
### Steps to Reproduce
1. Download [pfnet/plamo-13b-instruct](https://huggingface.co/pfnet/plamo-13b-instruct)
2. Convert with convert-hf-to-gguf.py
3. Attempt to run inference with `main`

Fails with:
```
GGML_ASSERT: /home/jared/src/forks/llama.cpp-2/llama.cpp:3395: vocab.id_to_token.size() == vocab.token_to_id.size()
```

**Comment by cebtenzzre** [comment]
I'm not aware of any recent development of the PLaMo code that would make this issue obsolete.

**Comment by stanus74** [comment]
I have the same problem. converted according to these instructions: https://github.com/ggerganov/llama.cpp/discussions/7927 

`ERROR [apps.rag.main] Ollama: llama runner process has terminated: GGML_ASSERT(vocab.id_to_token.size() == vocab.token_to_id.size()) failed`
 
this embedding model: 

https://huggingface.co/aari1995/German_Semantic_V3b

with this model the conversion worked without errors :

https://huggingface.co/danielheinz/e5-base-sts-en-de
