### ISSUE TITLE
[SYCL] Support newer non linear quantization

### ISSUE THREAD

**Issue by akarshanbiswas** [ggerganov/llama.cpp#5674]
cc: @abhilash1910 @airMeng 

Also [important](https://github.com/ggerganov/llama.cpp/pull/5590#issuecomment-1952955062)!

**Comment by airMeng** [comment]
we haven't supported iq3_xxs, but you can try to implement yourself based on CUDA code.

https://github.com/ggerganov/llama.cpp/blob/15499eb94227401bdc8875da6eb85c15d37068f7/ggml-sycl.cpp#L14970-L14972

**Comment by akarshanbiswas** [comment]
I see. Thanks. Should I close this then?

**Comment by airMeng** [comment]
> Also [important](https://github.com/ggerganov/llama.cpp/pull/5590#issuecomment-1952955062)!

Thank you for informing!



> I see. Thanks. Should I close this then?

up to you

**Comment by akarshanbiswas** [comment]
I am reopening this. I may/may not work on this since I am not a C person. I wish I could set the label to "help-wanted".

**Comment by airMeng** [comment]
https://github.com/ggerganov/llama.cpp/pull/5862

Can you try this PR and report the results?

**Comment by akarshanbiswas** [comment]
Got a ggml assert while trying to test an IQ3_XXS quantized gguf: 

```
...
...
get_memory_info: [warning] ext_intel_free_memory is not supported (export/set ZES_ENABLE_SYSMAN=1 to support), use total memory as free memory
...
...
GGML_ASSERT: llama.cpp/ggml-sycl.cpp:14097: to_fp16_sycl != nullptr
```

The other quants looking good although I didn't understand the warning that I am getting about ext_intel_free_memory.

**Comment by airMeng** [comment]
what model are you using? can you share a link?

**Comment by akarshanbiswas** [comment]
This time I used [Eris 7B](https://huggingface.co/Lewdiculous/Eris_7B-GGUF-IQ-Imatrix) to test IQ3. 

And for linear quants I used Mistral 7B.

**Comment by NeoZhangJianyu** [comment]
> Got a ggml assert while trying to test an IQ3_XXS quantized gguf:
> 
> ```
> ...
> ...
> get_memory_info: [warning] ext_intel_free_memory is not supported (export/set ZES_ENABLE_SYSMAN=1 to support), use total memory as free memory
> ...
> ...
> GGML_ASSERT: llama.cpp/ggml-sycl.cpp:14097: to_fp16_sycl != nullptr
> ```
> 
> The other non IQ quants looking good although I didn't understand the warning that I am getting about ext_intel_free_memory.

export/set ZES_ENABLE_SYSMAN=1 to support ext_intel_free_memory() to get free memory. 
It's not important if your GPU is not shared.

**Comment by abhilash1910** [comment]
> This time I used [Eris 7B](https://huggingface.co/Lewdiculous/Eris_7B-GGUF-IQ-Imatrix) to test IQ3.
> 
> And for linear quants I used Mistral 7B.

@akarshanbiswas Could you try 3.75 bit /1.5 bit (#5886 )and let us know for Erin model.

**Comment by akarshanbiswas** [comment]
@abhilash1910 Failed with `main: ggml-sycl.cpp:2968: dpct::detail::device_memory<const unsigned int, dpct::global, 1>::device_memory(const sycl::range<Dimension> &, std::initializer_list<value_t> &&) [T = const unsigned int, Memory = dpct::global, Dimension = 1]: Assertion `init_list.size() <= in_range.size()' failed.`

**Comment by NeoZhangJianyu** [comment]
mistral-7b-instruct-v0.2.Q4_K_M.gguf is passed by other test.
Please try with this model.

**Comment by akarshanbiswas** [comment]
[The regression was fixed after grid space increment.](https://github.com/ggerganov/llama.cpp/pull/5886#issuecomment-1986734042)

**Comment by NeoZhangJianyu** [comment]
I have asked the developer to fix it.

**Comment by akarshanbiswas** [comment]
Thank you.

**Comment by airMeng** [comment]
shall be fixed in https://github.com/ggerganov/llama.cpp/pull/6521

**Comment by akarshanbiswas** [comment]
Awesome!! Really thank you everyone for all hard work. I will try testing a model today with this patch (hopefully)!.

**Comment by akarshanbiswas** [comment]
Update: Just tested a iq4_XXS gemma 7B(8.5B) 1.1 model which was released recently and it is working great!!!

Closing this issue as solved for now!!

**Comment by abhilash1910** [comment]
Thanks for confirming @akarshanbiswas .
