### ISSUE TITLE
Is converting multiple safetensor models supported?

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#5678]
I get this error:

`Exception: Found multiple models in /home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3, not sure which to pick: [PosixPath('/home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3/model-00001-of-00003.safetensors'), PosixPath('/home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3/model.safetensors')]`

Model structure:

![image](https://github.com/ggerganov/llama.cpp/assets/6970347/4d478ef8-249f-48ce-a799-118bb7657404)

**Comment by ngxson** [comment]
- Can you make sure that you took the latest `convert.py` from main branch?
- Can you post the complete command that you used? Also the complete log, not just the error line.

**Comment by l3utterfly** [comment]
Here is the full log, I just tried again by downloading latest llama.cpp:

```
(llamacpp) layla@purplerain:~/src/llama.cpp$ python convert.py /home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3
Traceback (most recent call last):
  File "/home/layla/src/llama.cpp/convert.py", line 1483, in <module>
    main()
  File "/home/layla/src/llama.cpp/convert.py", line 1419, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/layla/src/llama.cpp/convert.py", line 1271, in load_some_model
    raise Exception(f"Found multiple models in {path}, not sure which to pick: {files}")
Exception: Found multiple models in /home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3, not sure which to pick: [PosixPath('/home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3/model-00001-of-00003.safetensors'), PosixPath('/home/layla/src/text-generation-webui/models/mistral-7b-v0.1-layla-v3/model.safetensors')]
```

**Comment by ngxson** [comment]
I think your model is incorrect, seems like you trained or fine tuned it yourself.

Normally, if the model is splitted into multiple files, there will be no more `model.safetensor`

Inside `model.safetensors.index.json`, all tensors should be pointed to splitted files

**Comment by ngxson** [comment]
Maybe try deleting that `model.safetensor` and try again?

**Comment by l3utterfly** [comment]
Thanks! That worked. Not sure why it was there, this was the output from axolotl after fine tuning
________________________________

**Comment by ngxson** [comment]
Glad to hear that it works! I'll close the issue then.
