### ISSUE TITLE
Finetune Codellama 13B

### ISSUE THREAD

**Issue by sanipanwala** [ggerganov/llama.cpp#5680]
Hello,

I want to finetune the **Codellama 13B** model using **llama.cpp** and finetune is working fine on my 2 GPUs (both are RTX 4090) but fine-tuning is very slow.

How can I do fast finetuneing?

Thanks.

**Comment by sanipanwala** [comment]
Hello @ngxson ,

Thanks for your reply.

If I used qlora method (python code) then Do you have any idea how I can use multi-GPU?

Thanks.

**Comment by ngxson** [comment]
I've never tried multi-GPU, but you can fine these info on google: https://www.google.com/search?client=firefox-b-d&q=finetune+mistral+multiple+gpu

I bet that huggingface's transformers should work with multiple GPU out-of-the-box with `device: 'auto'`
