### ISSUE TITLE
ggml-cuda.cu:3211: ERROR: CUDA kernel vec_dot_q5_K_q8_1_impl_vmmq

### ISSUE THREAD

**Issue by DanCard** [ggerganov/llama.cpp#5686]
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/5685

<sup>Originally posted by **DanCard** February 23, 2024</sup>
ggml-cuda.cu:3211: ERROR: CUDA kernel vec_dot_q5_K_q8_1_impl_vmmq has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
This worked yesterday.  I did a git pull, make clean, make and then get this error today.
nvidia rtx 3090
System: debian testing
Command line:
`~/github/llama.cpp/main -m ~/models/miqu-1-70b.q5_K_M.gguf -c 0 -i --color -t 16 --n-gpu-layers 24  --temp 0.8 -p "bob"
`

I reverted previous two commits and issue went away.
` ~/github/llama.cpp$ git reset --hard HEAD~2
`
HEAD is now at 334f76fa sync : ggml

**Comment by DanCard** [comment]
This is no longer an issue with latest update.

**Comment by szymonrucinski** [comment]
Hey I still keep getting this error for the server. I am on the main branch as well.
