### ISSUE TITLE
`-ctk q8_0` or `q4_0` cuts inference speed by half

### ISSUE THREAD

**Issue by Artefact2** [ggerganov/llama.cpp#5693]
I am using ROCm 6 (gfx1030) on GNU/Linux. Is this the expected behaviour or an AMD specific bug?

| model                          |       size |     params | backend    | ngl | type_k     | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | f16        | pp 512     |    500.76 ± 0.89 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | f16        | tg 128     |     41.09 ± 0.01 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | q8_0       | pp 512     |    503.45 ± 0.10 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | q8_0       | tg 128     |     21.28 ± 0.02 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | q4_0       | pp 512     |    488.14 ± 0.05 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | q4_0       | tg 128     |     21.29 ± 0.04 |

**Comment by ngxson** [comment]
Can you confirm if the quality of model's output quality is effected when you run `./main` with `-ctk q8_0` or `q4_0`? A perplexity benchmark will also be interesting.

**Comment by Artefact2** [comment]
`-ctk q4_0` doesn't work on llama2-13B, all the generated tokens are `#`. On mistral-7B, the model generates coherent text but `perplexity` still outputs `nan`.

It's hard to assess "output quality" but the working cases seem coherent enough.

| **model base ** | **-ctk** | **PPL **           |
|-----------------|----------|--------------------|
| **llama2-13b**  | f16      | 7.0216 +/- 0.04478 |
| **llama2-13b**  | q8_0     | 7.0243 +/- 0.04480 |
| **llama2-13b**  | q4_0     | nan                |
| **mistral-7b**  | f16      | 5.8066 +/- 0.03263 |
| **mistral-7b**  | q8_0     | 5.8065 +/- 0.03263 |
| **mistral-7b**  | q4_0     | nan                |
