### ISSUE TITLE
Handling Concurrent API Calls from Multiple Clients - Server Functionality

### ISSUE THREAD

**Issue by jcgeo9** [ggerganov/llama.cpp#5723]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Server functionality to handle concurrent API calls from different clients if slots are busy.

# Motivation

Deployed LLMs could be used from multiple clients, handling multiple concurrent api calls, queuing them up, instead of throwing an error.

**Comment by phymbert** [comment]
Hello @jcgeo9; this has already been [tested](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/tests/features/parallel.feature#L57) and [implemented](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/server.cpp#L1457).

You would you please retry with the latest code base, lot of fixes have beed merge recently on the matter.
I am closing the issue, please feel free to reopen if needed
