### ISSUE TITLE
Build failure for Intel CPU on windows with MKL

### ISSUE THREAD

**Issue by ratnampa** [ggerganov/llama.cpp#5743]
I am trying to build llama.cpp on windows with Intel CPU with oneAPI toolkit initialized. The build fails with the **string parsing error in CMake for the MKL path in CMD**. For PowerShell, it is not able to find MKL at all. Adding images for better understanding.

oneAPI: **call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64**
Build command: **cmake .. -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=Intel10_64lp -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DLLAMA_NATIVE=ON**
 
CMD:
<img width="1267" alt="error" src="https://github.com/ggerganov/llama.cpp/assets/114774508/0ac3c497-8199-47ad-bb65-0ddfbab0f120">

Powershell:
<img width="1058" alt="ps_error" src="https://github.com/ggerganov/llama.cpp/assets/114774508/25ff8ddf-e054-4dba-a047-eaccc246201b">

System:
Windows 11
CPU: 13th Gen Intel(R) Core(TM) i9-13900K
GPU: Intel Arc A770
Latest oneAPI toolkit

@ggerganov 
@airMeng

**Comment by airMeng** [comment]
you can try start from ```Intel oneAPI command prompt for Intel 64 for Visual Studio 2022``` directly, not sure about cpu part.

**Comment by ratnampa** [comment]
@ngxson do you have an idea about this, somehow the path to mkl_rt.lib passed by mkl-sdl.pc in Windows build with cmake messes up the path and results in parsing error. If I hardcode the path to include folder of oneMKL it works fine.

**Comment by ngxson** [comment]
Sorry I almost never work on windows, so I'm not familiar with cmd or powershell

**Comment by ratnampa** [comment]
@abhilash1910 can you take a look at this, definitely some cmake issue when finding mkl-sdl in windows. I observed in the CI jobs also, there is no additional testing with MKL on windows.

**Comment by aahouzi** [comment]
@NeoZhangJianyu @airMeng I'm still facing this issue and cannot build llama.cpp with MKL on Windows, any leads on this ?
@ratnampa Did u solve the issue somehow, I'm facing the same problem..
