### ISSUE TITLE
Model replicas on multiple gpus on server?

### ISSUE THREAD

**Issue by duykhanhbk** [ggerganov/llama.cpp#5759]
Any instructions for running model replicas on multiple gpus (for example use 4GPU)? 
Currently I used -np 32 and -cb

**Comment by aznrogerazn** [comment]
Have you tried starting up 4 llama.cpp processes for each GPU?
With `-ngl` you assign the layers to the GPU VRAM, and `-ts` to specify "which GPU got how many layers assigned". [Here's to the doc.](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#additional-options)

I have tried similar setup while running 2 GPUs at the same time. Basically, if you can fit the full model in a single GPU, you should be able to start llama.cpp for each of the GPUs.

So for `./main` and `./server` it would be:
```shell
# Assuming you run 7B models that has 33 layers
# and you want them to be on GPU #0 (when you have 4)
./main -ngl 33 -ts 1,0,0,0

# and maybe for the second GPU you can try
./main -ngl 33 -ts 0,1,0,0
```

I only tried 2 GPUs with `-ts 0,1` and `1,0` so please do share what you got with 4 of them! :hugs:
