### ISSUE TITLE
Is there any way to adjust parameters like -c, -b, --mlock, --min-p, --top-p, --top-k, --repeat-penalty, --no-penalize-nl and --temp etc. in api_like_OAI.py

### ISSUE THREAD

**Issue by SeriousHulk** [ggerganov/llama.cpp#5766]
Is there any way to adjust parameters like -c, -b, --mlock, --min-p, --top-p, --top-k, --repeat-penalty, --no-penalize-nl and --temp etc. in api_like_OAI.py

_Originally posted by @SeriousHulk in https://github.com/ggerganov/llama.cpp/issues/4367#issuecomment-1968970179_

**Comment by nelsonhurstdev** [comment]
IMO, It can be removed. It is redundant now that the server has it integrated.

**Comment by Azeirah** [comment]
> Slightly off-topic, but what does `api_like_OAI.py` currently offer that `server` does not?
> 
> I was thinking of removing that script since I believe `server` already support the OAI API

I don't think it offers anything extra anymore. Only thing I do know is that even today many people (I see it on reddit /r/LocalLLama and on LLM discords) don't know that the built-in server supports OAI endpoints.

Perhaps it shouldn't be removed but just give a big fat warning "PLEASE MOVE TO ./server THIS SCRIPT WILL BE REMOVED AT x DATE"

**Comment by AFKler** [comment]
> Slightly off-topic, but what does `api_like_OAI.py` currently offer that `server` does not?
> 
> I was thinking of removing that script since I believe `server` already support the OAI API

`server` does not support the following arguments: **--chat-prompt  --user-name  --ai-name  --system-name**
