### ISSUE TITLE
SLICEGPT - Reduce Compute significantly by deleting rows & columns

### ISSUE THREAD

**Issue by Alumniminium** [ggerganov/llama.cpp#5775]
https://arxiv.org/pdf/2401.15024.pdf

## Quick Excerpt from the paper
_Inference Time of a model compressed with SliceGPT.  
...
Single token in OPT 66B and LLAMA-2 70B models on Quadro RTX6000 and A100 GPUs
We observe a speedup of 16-17% on RTX6000 GPUs when employing 25% slicing, and 11-13% on A100s. 
...
For LLAMA-2 70B, the compute required using RTX6000 GPUs is reduced to 64%, from 1764ms to 1075ms_

**Comment by ngxson** [comment]
Seems interesting, but the performance with 7B model is dropped quite significant, I'm not sure if it's really practical:

![image](https://github.com/ggerganov/llama.cpp/assets/7702203/17c76459-e8dd-4632-a4c7-4ae98331e7bb)
