### ISSUE TITLE
Installing with home-manager (nix) fails

### ISSUE THREAD

**Issue by leana8959** [ggerganov/llama.cpp#5778]
I couldn't get `llama-cpp` to build with `home-manager`. However, it works perfectly with `nix-darwin` or in the CLI using `nix run "github:ggerganov/llama.cpp"`.

The error looks like this. There's nothing more in `.nix-store -l /*derivation path*/`.

<details>
<summary>Here's the log</summary>

```console
... elided ...
llama-cpp-blas> shrinking /nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/bin/train-text-from-scratch
llama-cpp-blas> checking for references to /build/ in /nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0...
llama-cpp-blas> patching script interpreter paths in /nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0
llama-cpp-blas> stripping (with command strip and flags -S -p) in  /nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/lib /nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/bin
home-manager-path> error: collision between `/nix/store/z9k0qjss6ncfpgm9gyl0nn1qsn6a7hjy-parallel-20230922/bin/parallel' and `/nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/bin/parallel'
error: builder for '/nix/store/dh4zzli698vf3p5kmdayphk2km00gybj-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/z9k0qjss6ncfpgm9gyl0nn1qsn6a7hjy-parallel-20230922/bin/parallel' and `/nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/bin/parallel'
       For full logs, run 'nix-store -l /nix/store/dh4zzli698vf3p5kmdayphk2km00gybj-home-manager-path.drv'.
error: 1 dependencies of derivation '/nix/store/nxrbl01kppfvidl9cmm0s7r7d7cyndac-home-manager-generation.drv' failed to build
```

</details>

Here are the specs of my system.
```console
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.0-1049-oracle, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Thanks for the help and for the great project!

**Comment by arcuru** [comment]
> error: collision between `/nix/store/z9k0qjss6ncfpgm9gyl0nn1qsn6a7hjy-parallel-20230922/bin/parallel' and `/nix/store/qiia8zybs1y5dpxxdfp5kqhb9wvz2hy7-llama-cpp-blas-0.0.0/bin/parallel'

This line means that there is a collision between the `parallel` binary from the parallel package and the one installed by llama.cpp. Home-manager won't let you install both at once because they both get symlinked into the same folder for the home-manager derivation.

**Comment by arcuru** [comment]
They are 2 different binaries, so it won't be a cache hit.

You have 3 options for using llama-cpp wihout uninstalling parallel:
1. Modify your llama-cpp nixpkg derivation to remove the parallel binary (or rename it). You can look for help on how to do that in the nix community.
2. Only run llama-cpp using `nix shell` or a direnv environment.
3. Beg one of the two groups to rename their binary.

**Comment by leana8959** [comment]
I see, thank you for the insight!
Since it's not an inherent problem with llama.cpp, I'll close this issue.
