### ISSUE TITLE
server: index.html issue

### ISSUE THREAD

**Issue by tdspotts** [ggerganov/llama.cpp#5788]
PHP Code Output is destroyed by Line 874 in the examples/server/public/index.html file. 

<code> .replace(/_(.*?)_/g, '<em>$1</em>') </code>

**Comment by Azeirah** [comment]
Yeah code inside formatting ticks are still replaced by the simple "fake" markdown logic, lol.

Imo the proper solution is use a real streaming markdown parser, there are more issues like this that pop-up every now and then.

**Comment by Azeirah** [comment]
I did a bit of spelunking, I think this markdown parser makes sense for llama.cpp: https://github.com/commonmark/commonmark.js

It's a no-nonsense parser which focuses on speed. I pasted in a 1400 line markdown document and it parses the entire thing in about 8ms on my m1 in safari. I don't think it's streaming-aware per se but it's still very fast.

I'm not sure if there is a good open-source streaming-aware markdown parser out there, if you find one let me know

**Comment by tdspotts** [comment]
I'm just spitballing here, but what about asking one of the AI models to produce a custom tailored markdown parser for llama.cpp ? I'm just getting started with the whole AI thing, and discovered this "issue" while testing the output.

**Comment by Azeirah** [comment]
> I'm just spitballing here, but what about asking one of the AI models to produce a custom tailored markdown parser for llama.cpp ? I'm just getting started with the whole AI thing, and discovered this "issue" while testing the output.

Whaha no, if only. Ai is magic, but it's not _that_ magic. Maybe in a year or two

**Comment by teleprint-me** [comment]
I've actually been working on this.

[Screencast from 2024-03-11 22-52-40.webm](https://github.com/ggerganov/llama.cpp/assets/77757836/1be05605-be77-45d8-b6ae-4fce0c8f146d)

It's still a work in progress.
