### ISSUE TITLE
Differences between cgraph->leafs and cgraph->nodes?

### ISSUE THREAD

**Issue by VincentXWD** [ggerganov/llama.cpp#5791]
Hello, I'm wondering what the differences between cgraph->leafs and cgraph->nodes. Thank you very much.

**Comment by ggerganov** [comment]
Leaf nodes are the same as other nodes, except they are not a result from an operation. I.e. they are inputs to the graph - constants. 

[In hindsight](https://github.com/ggerganov/ggml/issues/567#issuecomment-1771285603) it might have been an unnecessary categorization and we might decide to remove the concept of "leafs" in the future

**Comment by VincentXWD** [comment]
Thanks for replying. I agree with this view.

Another quick question: How does ggml manage the temporary tensors generated by each node?
