### ISSUE TITLE
Models with activation beacon

### ISSUE THREAD

**Issue by Bearsaerker** [ggerganov/llama.cpp#5800]
There is a new method for extending the context of a llm called [activation beacon.](https://github.com/FlagOpen/FlagEmbedding/tree/master/Long_LLM/activation_beacon) Unfortunately the model is different in such a way, that it isn't possible to convert it to gguf. The method is new, but there is already [one model](https://huggingface.co/namespace-Pt/activation-beacon-llama2-7b-chat) which I attempted to convert, but didn't work. Implementing this would be hella nice, more context without using more ressources as they claim.

**Comment by ngxson** [comment]
This seems to be interesting.

Simply converting to gguf won't work though, as there are significant changes in attention mechanism. Also what's not clear for me is how KV cache is managed.

![image](https://github.com/ggerganov/llama.cpp/assets/7702203/4b05ccb4-dfa3-49be-b926-1061a5054f69)

If I'm not wrong, then the mentioned "beacon token" acts like a "trigger" that tells the model to compress the context into one "embedding" (in the paper it's called "beacon tokens’s activation"), then that embedding is kept, but the KV cache can be cleared. So, to my understand, it work more or less like Selective State Space introduced by Mamba, but the "Selective" part is triggered by that beacon token.

**Comment by ggerganov** [comment]
I don't see why we can't support activation beacons. The KV cache management API should have all the necessary tools

**Comment by ngxson** [comment]
I’m not worrying about the KV management part but more about how KV of that beacon token is calculated. They have 2 set of weight for multi-head attention, and the KV of beacon uses the second set.

Furthermore:

> The final output of self-attention is produced by the concatenation of both raw activations from the normal tokens and the condensed activations from the beacon tokens.
