### ISSUE TITLE
Unable to convert Smaug 72B

### ISSUE THREAD

**Issue by schmorp** [ggerganov/llama.cpp#5807]
I am unable to convert https://huggingface.co/abacusai/Smaug-72B-v0.1 (and others) to GGUF with either convert.py  or convert-hf-to-gguf.py.

With the former, I get:

RuntimeError: Internal: ./src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

"internal" feels like a bug. When I add --vocab-type hfft (and then --pad-vocab because it tells me to), I get a nonfunctional model:

llm_load_vocab: SPM vocabulary, but newline token not found: unordered_map::at! Using special_pad_id instead.llm_load_vocab: mismatch in special tokens definition ( 421/152064 vs 214/152064 ).

and convert-hf-to-gguf.py does not support "LlamaForCausalLM".

**Comment by schmorp** [comment]
llama.cpp release b2291 btw.

**Comment by dranger003** [comment]
I think it works by changing this line:
https://github.com/ggerganov/llama.cpp/blob/e7433867288d2f142cffe596f3751bda5d7ee2c7/convert-hf-to-gguf.py#L262 to:
```
if arch in ("MixtralForCausalLM", "LlamaForCausalLM"):
```

**Comment by schmorp** [comment]
Thanks a lot, but that just fails further down the line:

   Error: Missing Smaug-72B-v0.1/tokenizer.model

I notice quite a lot of models on huggingface were apparently convertible a few weeks/months ago but no longer are (e..g TheBloke has GGUFs, but when I try converting with current versions of llama to make imatrix quants, they fail in lots of different ways). Is this considered a regression and should issues be created for those?

**Comment by dranger003** [comment]
Ah yes, I think I recreated it by loading the model using HF transformers and using `save_pretrained()` although I also think this just about to get fixed as I look at this PR https://github.com/ggerganov/llama.cpp/pull/5798.
You could also use the tokenizer model from the model it was trained from, if that is available.

**Comment by schmorp** [comment]
It seems most of the llama-2 derived models seem to have this vocabulary mismatch problem, and #5821 does not seem to help.

**Comment by christiandaley** [comment]
Any updates/workarounds on this? I just tried to convert Smaug 72B and I'm getting a `error loading model: _map_base::at` error when I try to run using llama.cpp.

**Comment by schmorp** [comment]
I thought I'd have tried that, but maybe I haven't. Thanks a lot for this tip!

As for the special token deifnition warning, I had this for a few other models, and they seemed to work, but ymmv.

**Comment by schmorp** [comment]
Works, so it's a user error. Sorry for the noise.

**Comment by schmorp** [comment]
When converting with the command from @countzero, the resulting model crashes main/imatrix with:

terminate called after throwing an instance of 'std::out_of_range'
  what():  unordered_map::at
Aborted
