### ISSUE TITLE
Redirection of system error messages to log files in main.cpp

### ISSUE THREAD

**Issue by pudepiedj** [ggerganov/llama.cpp#5811]
Running `./main` with `/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf` on Apple M2 MAX 32GB (38 cores) with system over-ride increased VRAM to `28000` the attempts by the system to do context shifting to allow limitless conversations beyond `-c 6144` are largely successful, but error messages are being reported to the screen in ways that punctuate the conversation, yet not to the `main.log` stored in `/build`. 

```
% make -j && ./bin/main -m ../models/Mixtral-8x7b/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -i -ins -ngl 99 -c 6144 -f "/Users/edsilm2/whisper.cpp/USfilestranscribed/US1176b.txt" --color
```
I would suggest that it would be **better the other way round**: error and warnings to the log but leave the conversation intact apart from a minimal warning message because at the moment the first error `ggml_galloc_...` just cuts in (reproduced here exactly as it occurs without additional line breaks):
```
In both cases, the representations and embeddings that are used to encode and recall information are not exact copies of the original data, but rather they are abstracted and simplified versions of that data. This means that while the model or brain may be able to recall and use the information in some form, it may not be able to provide a verbatim quote orggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: cannot reallocate multi buffer graph automatically, call reserve
ggml_backend_sched: failed to allocate graph, reserving
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: cannot reallocate multi buffer graph automatically, call reserve
ggml_backend_sched: failed to allocate graph, reserving
 summary of that information, especially if it is no longer in the foreground of its attention and self-attention mechanisms.
```

**Comment by ggerganov** [comment]
These logs are printed only in Debug builds:

https://github.com/ggerganov/llama.cpp/blob/e7433867288d2f142cffe596f3751bda5d7ee2c7/ggml-backend.c#L1427-L1429

**Comment by pudepiedj** [comment]
> These logs are printed only in Debug builds:
> 
> https://github.com/ggerganov/llama.cpp/blob/e7433867288d2f142cffe596f3751bda5d7ee2c7/ggml-backend.c#L1427-L1429

I did a full `cmake --build . --config Release` and the messages have disappeared. I don't remember building in `Debug` mode recently, but they have gone. `ggml-backend.c' is a bit beyond my skill set!
