### ISSUE TITLE
Fix failing CI test using thread sanitizer

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#582]
I cannot reproduce on my machines:

https://github.com/ggerganov/llama.cpp/actions/runs/4545676297/jobs/8013336777

If someone that can reproduce, please try to fix this

**Comment by cyyynthia** [comment]
The 143 exit code (and the `The runner has received a shutdown signal.` annotation left by GitHub) leads me to believe the tests are exceeding GitHub Actions's limits in some way and are getting terminated.

See https://github.com/actions/runner-images/issues/6680, https://github.com/actions/runner-images/discussions/7188

**Comment by slaren** [comment]
I suspect this may be caused by high memory usage:
```
Maximum resident set size (kbytes): 11846496
```

Anyone knows the limit for github actions?

**Comment by cyyynthia** [comment]
According to GitHub's [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), Linux runners have 2 x86 cores and 7GB of RAM.

GitHub's [large runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners) may be able to let the jobs complete, but these are in limited beta and only for organizations and enterprises sadly.
