### ISSUE TITLE
How to write a chat template for llama.cpp server?

### ISSUE THREAD

**Issue by AFKler** [ggerganov/llama.cpp#5822]
Which variables do i have to use in jina? How to define user-name and system-name?

https://github.com/ggerganov/llama.cpp/issues/5766#issuecomment-1973708563

**Comment by ngxson** [comment]
Currently it's not possible, you can only use these templates: https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template

The ability to have custom prefix for user - system - assistant will be added in the future
