### ISSUE TITLE
Issue with Converting llava-med Model to gguf - Error in convert.py

### ISSUE THREAD

**Issue by areegtarek** [ggerganov/llama.cpp#5831]
I am facing an issue while converting a llava-med model to gguf using the `convert.py` script in the `llama.cpp` repository. I have followed the steps provided in the `examples/llava` directory related to llava 1.5, and everything worked until the last step:

```bash
! python llama.cpp/convert.py PC-hf --skip-unknown
```

The error I encountered is as follows:

```plaintext
Loading model file PC-hf/model-00001-of-00002.safetensors
...
ValueError: invalid value for special token type pad: -1
```

![Screenshot from 2024-03-02 12-37-00](https://github.com/ggerganov/llama.cpp/assets/46351336/34270281-c562-430f-b46e-16f93b4fd423)

I have tried passing the `--pad-vocab` parameter and also attempted to modify the `pad_token_id` in the `config.json` file. Although the script runs successfully after these modifications, the resulting gguf model is not functioning properly. When I send a message to the model, it returns `//////////////`, indicating an issue.

the error related to the pad_token_id in the config.json of the llava-med delta weights is equal -1

![Screenshot from 2024-03-02 12-49-19](https://github.com/ggerganov/llama.cpp/assets/46351336/26799aa3-01dc-45b1-bfd1-581a77681f97)

I have attempted to resolve the issue by passing the `--pad-vocab` parameter and modifying the `pad_token_id` in the `config.json` file. Although these steps allow the script to run without errors, the resulting gguf model is not working as expected. I would appreciate any guidance or support in resolving this issue. Thank you.

**Comment by schmorp** [comment]
Does removing the pad_token_id line from config.json help?

**Comment by iamlemec** [comment]
Are you running `convert.py` directly on `llava-med-7b-delta` or on the merged weights with base LLaMa-7b?

**Comment by areegtarek** [comment]
> Does removing the pad_token_id line from config.json help?

I initially attempted changing its value from -1 to a positive value (0, 1 and 2), but unfortunately, that didn't resolve the issue. Nevertheless, I'm now planning to try removing it entirely to see if that makes a difference.

**Comment by areegtarek** [comment]
> Are you running `convert.py` directly on `llava-med-7b-delta` or on the merged weights with base LLaMa-7b?
Yes, I am running convert.py directly on the merged weights with base LLaMa-7b.

**Comment by areegtarek** [comment]
> Are you running `convert.py` directly on `llava-med-7b-delta` or on the merged weights with base LLaMa-7b?

Yes, I am running convert.py directly on the merged weights with base LLaMa-7b.

**Comment by varunlmxd** [comment]
Did anyone found a solution for llava-med gguf quantization?
