### ISSUE TITLE
Question about llama.cpp and llava-cli when used with llava 1.6 for vision:

### ISSUE THREAD

**Issue by RandomGitUser321** [ggerganov/llama.cpp#5852]
I've been using the llava-v1.6-mistral-7b model for doing captions lately. I know it's relatively new and does some different things under the hood vs other/older vision models.

From the little bit of testing I've performed, it seems like server makes it fall back to the llava 1.5 vision, rather than using the 1.6 mode. When I check the total token counts, those always seem to be really low. This seems to affect any apps that use llama.cpp, like LM Studio and Jan. If I use llava-cli, with the same settings, the image alone encodes to 2880 tokens, which indicates that it's encoding the tiles correctly. Is there any way to make the server use llava-cli? Anyway to make llava-cli behave like a server? Am I doing something wrong?

I wrote a python program to batch caption folders of images, but I'm having to do it a really hacky way where it basically runs a command prompt behind the scenes, the python script captures the output of the window as a log, parses the log to trim out the non-response text, formats it, saves it, etc. The problem is that it's really annoying because it has to fully reload the model for each image.

For reference, this is how I'm running llava-cli:
`llava-cli -m "C:\pathtomodel\llava-v1.6-mistral-7b.Q4_K_M.gguf" --mmproj "C:\pathtovision\mmproj-model-f16.gguf" --image "c:\pathtoimage\image.png" --temp 0.2 --n-gpu-layers 100 -n 2048 -c 4096 --mlock -p "<image>\nUSER:\nProvide a full description. Be as accurate and detailed as possible. \nASSISTANT:\n" >> log.txt` (the >> log.txt is what you'd use if you were manually running it straight from a cmd prompt and not from some python script that can capture it for you)

**Comment by chigkim** [comment]
You're probably running into the issue where It processes the image correctly but reports incorrect prompt token count.
https://github.com/ggerganov/llama.cpp/issues/5863

**Comment by cjpais** [comment]
Two images is definitely an issue in the code for 1.6. I've poked around at it a bit but don't have clarity why.

Regarding misreporting the number of processed tokens it should be fixed in PR #5896

**Comment by cjpais** [comment]
Please note that with #5882 multimodal will be removed from server.

If you need the fix, use the code from #5896, just note that it will not be merged at this time
