### ISSUE TITLE
Provide an example for CMake/CPack variables to create a package

### ISSUE THREAD

**Issue by raffaeler** [ggerganov/llama.cpp#5859]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

More specifically, the only page referring to CPack is the following: https://github.com/ggerganov/llama.cpp/wiki but does not address the issue.

# Feature Description

Following the instructions of [this page](https://github.com/ggerganov/llama.cpp/wiki) I tried to run cpack: 

```
$ cpack build -G DEB
CPack Error: CPack project name not specified
``` 

Specifying the project name did not help much:
```
$ cpack build -G DEB -P llamacpp
Specify CPACK_PACKAGE_VERSION, or CPACK_PACKAGE_VERSION_MAJOR, CPACK_PACKAGE_VERSION_MINOR, and CPACK_PACKAGE_VERSION_PATCH.
``` 

Adding the version did not help too:
```
$ cpack build -G DEB -P llamacpp -R 1.0
CPack Error: Please specify build tree of the project that uses CMake using CPACK_INSTALL_CMAKE_PROJECTS, specify CPACK_INSTALL_COMMANDS, CPACK_INSTALL_SCRIPT, or CPACK_INSTALLED_DIRECTORIES.
``` 
Apparently those options don´t have a matching command line.

# Motivation

Creating a package that can be easily moved across different VMs / containers.

# Possible Implementation

I am not familiar with CPack.
Since it is mentioned in the wiki, it would be useful to add to the wiki an example of the CMake variables used to make it work.
The wiki specifies only `-D...` which is reasonable for other options, but does not address the CPack specific variables

Thanks!

**Comment by ITHelpDec** [comment]
I get this when outside of the build directory.

One way to solve it is by moving into the directory:
```bash
$ cmake -S . -B build
$ cmake --build build
$ cd build
$ cpack -G DEB
```

Or, you can specify the generated config file path with the `--config` flag whilst still in the source directory:
```bash
$ cmake -S . -B build
$ cmake --build build
$ cpack --config build/<project_name>Config.cmake -G DEB
```
Hope this helps.
