### ISSUE TITLE
error when compiling with CUBLAS

### ISSUE THREAD

**Issue by Fuckingnameless** [ggerganov/llama.cpp#5860]
error: 

/bin/sh: 1: nvcc: not found
I NVCC:      
/bin/sh: 1: nvcc: not found
Makefile:609: *** I ERROR: For CUDA versions < 11.7 a target CUDA architecture must be explicitly provided via CUDA_DOCKER_ARCH.  Stop.

this is probably not to do with llamacpp but i'd appreciate some help
cuda-samples run fine so it's working

**Comment by dranger003** [comment]
Can you show your path? Note that `nvcc` must be in your path (`which nvcc` output should be correct). Also, I assume you have CUDA installed already given you mention cuda-samples.

**Comment by Fuckingnameless** [comment]
> Can you show your path? Note that `nvcc` must be in your path (`which nvcc` output should be correct). Also, I assume you have CUDA installed already given you mention cuda-samples.

yes i have the 545 driver and cuda is 12.3, i used the local .deb repo and also added the cuda12.3/bin...etc  folders to $PATH according to nvidia post install instructions, here's the output of "which nvcc":

/usr/local/cuda/bin/nvcc

tried changing to

/usr/local/cuda/bin/nvcc

but the error persists

**Comment by dranger003** [comment]
Looks like you may have other versions of CUDA installed that may conflict, according to the error message you provided earlier? You should try setting `CUDA_DOCKER_ARCH`: *For CUDA versions < 11.7 a target CUDA architecture must be explicitly provided via CUDA_DOCKER_ARCH.*

**Comment by WaterBoiledPizza** [comment]
How to find the `CUDA_DOCKER_ARCH` value?

**Comment by jwj7140** [comment]
You can find in [https://developer.nvidia.com/cuda-gpus](https://developer.nvidia.com/cuda-gpus).
For example, if you have RTX 3060Ti, then you can use the option ```CUDA_DOCKER_ARCH=sm_86```

**Comment by AreckOVO** [comment]
How to solve this problem?
` make LLAMA_CUDA=1 CUDA_DOCKER_ARCH=sm_75`

![image](https://github.com/ggerganov/llama.cpp/assets/92663916/61c64c4d-e466-45e1-9ca0-65f084bcdb5d)

**Comment by RedNoseJJN** [comment]
how do I solve this?
/usr/bin/ld: cannot find -lcuda: No such file or directory
collect2: error: ld returned 1 exit status
