### ISSUE TITLE
tips for GPU op profile

### ISSUE THREAD

**Issue by rnwang04** [ggerganov/llama.cpp#5865]
# Feature Description

I wonder in llama.cpp, is there any way or settings to know each op costs how much time when I use CUDA or SYCL backend ? or similar GPU profile.

Many thanks for your help!

**Comment by NeoZhangJianyu** [comment]
@rnwang04 
It's good feature. but no such function in SYCL backend now. 
it's easy to be implemented:
In function 
```
bool ggml_sycl_compute_forward():
  ...
  begin_time=...
  func(tensor->src[0], tensor->src[1], tensor);
  end_time=...
  ...
```

**Comment by Andy1314Chen** [comment]
nsight system
