### ISSUE TITLE
GPU Memory Leak

### ISSUE THREAD

**Issue by zsogitbe** [ggerganov/llama.cpp#5873]
After disposing everything the GPU memory is still not freed. When running the same code for the second time it crashes with a message that it cannot allocate enough memory. There are some things which are not freed from GPU memory.

You can test the issue by using `ggml_backend_cuda_get_device_memory(0, out freemem, out totalmem);` before and after using a llama model. `freemem` will show how much memory is still allocated.

See this also: https://github.com/SciSharp/LLamaSharp/pull/575

**Comment by zsogitbe** [comment]
I have noticed that cublasCreate is called, but there is no cublasDestroy. Could this be the problem?

**Comment by zsogitbe** [comment]
See also: https://github.com/ggerganov/llama.cpp/pull/5576

**Comment by zsogitbe** [comment]
https://github.com/ggerganov/llama.cpp/pull/5898

**Comment by zsogitbe** [comment]
Added a new PR with corrected Cublas release GPU memory code: https://github.com/ggerganov/llama.cpp/pull/5898

**Comment by ggerganov** [comment]
I don't understand how a process that has died could still occupy GPU memory. This looks like a non-`llama.cpp` related issue

**Comment by zsogitbe** [comment]
You are obviously a genius Georgi, so I am sure that you will figure it out. Please run the main example code in llama.cpp, free all memory and then stop at the end with debugging and check your GPU memory status. You will see that GPU memory is not freed.
This is a huge problem for production applications because GPU memory is very expensive and precious and you cannot just keep filling it with not used things. 
We need to load the library and then allow for several inferences, but if each inference leaves hundreds of MBs GPU memory behind then you will soon not be able to do inference on the GPU... 
![image](https://github.com/ggerganov/llama.cpp/assets/26321024/a1f04bd6-c225-47d6-83af-1b911c6eb576)
In this example nearly 1GB is stayed on the GPU after running the inference and it is impossible to free it without exiting the app (main process end).

**Comment by ggerganov** [comment]
I misunderstood that the GPU memory stayed occupied after the process ends.

Currently, the CUDA backend cannot be cleaned-up completely because we have some global objects which are never destroyed. The problem is acknowledged and related to https://github.com/ggerganov/llama.cpp/issues/3960. Keep track of that issue for further updates on this

**Comment by zsogitbe** [comment]
Thank you for acknowledging it. This is really a huge issue if you want llama.cpp being used in professional production software and not only in playing with llms. I have added a PR for releasing Cublas, trying to help (this freed 15% of the still occupied GPU memory), but I was not able to find the other 85%. I hope that you will find some time for this and give this a high priority. This problem should be solved before any further improvements to the library.

**Comment by zsogitbe** [comment]
**Update**: LLava is even a bigger problem because when using it the not freed GPU memory doubles (1.8 GB GPU memory is not freed in the above example)!

**Comment by slaren** [comment]
> We need to load the library and then allow for several inferences, but if each inference leaves hundreds of MBs GPU memory behind then you will soon not be able to do inference on the GPU

To clarify, this is not what happens. Some resources are never freed but they are not leaked either, they are reused for future inferences. Memory usage does not increase indefinitely.

**Comment by zsogitbe** [comment]
slaren, any news on this? Do you think that you will have some time to correct the CUDA backend?
