### ISSUE TITLE
Support for torch's Longstorage for Sentance Similiary tasks

### ISSUE THREAD

**Issue by gevzak** [ggerganov/llama.cpp#5881]
Now since BERT/SBERT models are supported by LLamaCPP, it would be great to support models such as "all-mpnet-base-v2".
Currently, when attempting to convert the modelm cover.py throws an error "KeyError: ('torch', 'LongStorage')." in e "convert.py", line 832, in find_class.

If the model had to be supported with the latest changes, I would switch the ticket type to Bug, but if not, the motivation behind this is the model is pretty popular and giving great results in Sentence Similarity tasks. 
If anyone has an idea what steps would be required to support this model and the effort required, would be happy to hear that and eventually contribute.

**Comment by hiepxanh** [comment]
I have the same issue, that will be the nice support to unlock embedding feature

**Comment by ub3rb3457** [comment]
bump

**Comment by jaasperhelin** [comment]
Would be great if the all-mpnet-base-v2 model would be enabled. It works pretty well for German language and a combination of German & English text.

**Comment by Molan-182** [comment]
Try to use convert-hf-to-gguf.py instead of convert.py. It worked with gte-base-zh.
