### ISSUE TITLE
Add chat_template to exist gguf file

### ISSUE THREAD

**Issue by bruceunx** [ggerganov/llama.cpp#5897]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

add chat template to exist gguf file

# Motivation

I can parse  chat template directly, not from extra info.

# Possible Implementation

may be implement a additional function in gguf.GGUFReader class for add new field in metadata?

**Comment by ggerganov** [comment]
Chat templates are already added

**Comment by bruceunx** [comment]
I mean add chat templates to existed gguf file?

**Comment by ngxson** [comment]
Currently there is no example that can does what you ask for. In fact, what you ask can be rephrased as "How to modify KV metadata of gguf"

However it's totally prossible with `gguf-py`, something like `gguf.add_string("tokenizer.chat_template", "...")`

https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/gguf_writer.py#L149

**Comment by bruceunx** [comment]
> Currently there is no example that can does what you ask for. In fact, what you ask can be rephrased as "How to modify KV metadata of gguf"
> 
> However it's totally prossible with `gguf-py`, something like `gguf.add_string("tokenizer.chat_template", "...")`
> 
> https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/gguf_writer.py#L149

Yes, but the add_string is from gguf.GGUFWriter, and I just only want to add chat_template for existed gguf model. like set_metadata with new field name and new field data
```python
def set_metadata(reader: GGUFReader, args: argparse.Namespace) -> None:
```
https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/scripts/gguf-set-metadata.py

**Comment by ngxson** [comment]
I'm not sure if it's possible, because the offset of the whole file changes when you modify the metadata (correct me if I'm wrong; Most of the time I use the gguf inside cpp code, not the python version)

The safe way is to read gguf file, add metadata, then write a new gguf file with the new metadata. You can then copy tensors one by one to the new file.

**Comment by bruceunx** [comment]
I guess so, thanks

**Comment by bruceunx** [comment]
```python
import struct
import numpy as np
from gguf import GGUFReader, GGUFValueType, GGUF_DEFAULT_ALIGNMENT

#
file_path = "../openhermes.gguf"
new_file_path = "../add_chat_model.gguf"
#
reader = GGUFReader(file_path, "r+")
#

# get chat template
CHAT_TEMPLATE = "tokenizer.chat_template"
chat_template = "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"

# generate and adjust struct pack value from chat template with alignment
alignment = GGUF_DEFAULT_ALIGNMENT
new_align = reader.fields.get('general.alignment')
if new_align is not None:
    alignment = new_align.parts[-1][0]

add_data = bytearray()

name_data = CHAT_TEMPLATE.encode("utf-8")
add_data += struct.pack("Q", len(name_data))
add_data += name_data
add_data += struct.pack("I", GGUFValueType.STRING.value)

raw_len = len(add_data) + 8 + len(chat_template)
add_len = alignment - (raw_len % alignment)
if add_len != 0:
    chat_template += " " * add_len

raw_data = chat_template.encode("utf-8")
add_data += struct.pack("Q", len(raw_data))
add_data += raw_data

# insert raw bytes into file
# find insert index
kv = reader.fields
last_field = list(kv.values())[-1]
insert_offset = last_field.offset

# copy original data
new_data = reader.data.copy()
new_data = np.concatenate(
    (new_data[:insert_offset], add_data, new_data[insert_offset:]))

# add kv_count
kv_count_idx = reader.fields["GGUF.kv_count"].parts[0][0]
new_data[kv_count_idx] += 1

# save file
with open(new_file_path, "wb") as file:
    file.write(new_data.tobytes())

```
I just implement add chat template to existed gguf, is it ok to add to the scripts in gguf-py or add to GGUF.Reader? or just here in case some one like me want to use this script?

**Comment by ngxson** [comment]
Thanks for the solution. Yeah I think you can push it as a new script `gguf-modify-metadata.py`. Can you add the ability to modify any key of any types (string, number, array,...) Maybe someone will need this script, for example to modify chat template, bos/eos token,...

**Comment by bruceunx** [comment]
Yes, but other types like number, array and closely bound to the model, the reason I want to add chat template is many ggufs in hf now have no chat templates in kv, which is a little inconvenience.

**Comment by sandeshrajbhandari** [comment]
this command should work. first two paths are positinal arguments, input path then output path.
- can also pass --chat-template as a string instead of a file.
```bash
python ./lama.cpp/gguf-py/gguf/scripts/gguf_new_metadata.py \
  ./input_folder/gpt-oss-20b-reap-0.5-mxfp4.Q8_0.gguf \ 
  ./output_folder/sandeshrajx_gpt-oss-20b-reap-0.5-mxfp4_q8.gguf \
  --chat-template-file /content/chat_template.jinja
```
