### ISSUE TITLE
Support gpt4all interactive mode

### ISSUE THREAD

**Issue by niansa** [ggerganov/llama.cpp#590]
Hey!

I just found this repo: https://github.com/nomic-ai/gpt4all and it looks amazing! They've forked alpaca.cpp but with their own "tweaks" in a single commit: https://github.com/zanussbaum/gpt4all.cpp/commit/4a6afcb08fb243df9a919c26aab1027ebfa373cc
So I assume it'd be quite easy to support!

Niansa

**Comment by Technetium1** [comment]
Really not much changed at all: https://github.com/antimatter15/alpaca.cpp/compare/master...zanussbaum:gpt4all.cpp:master

**Comment by ggerganov** [comment]
It's already supported

https://github.com/ggerganov/llama.cpp/issues/588

**Comment by niansa** [comment]
Oh that was fast. Thanks a lot!
