### ISSUE TITLE
llama.cpp Garbled code

### ISSUE THREAD

**Issue by dm180** [ggerganov/llama.cpp#5904]
The newly downloaded GGUF model has garbled characters. I have tried several GGUF models and they have all been like this, while the old GGUF model can still be used normally! Llama.cpp has been upgraded to the latest version

![QQ截图20240306224234](https://github.com/ggerganov/llama.cpp/assets/37135444/9b22f2bf-3129-4bc5-ae1a-77b83a552846)
https://huggingface.co/dagbs/dolphin-2.8-experiment26-7b-preview-GGUF/tree/main

**Comment by ngxson** [comment]
That usually happens when the model file is corrupted. Did you try another model or re-download the file?

**Comment by ngxson** [comment]
Can you try with the `main` instead of `server`?

This kind of problem usually happens when the file is corrupt (or llama.cpp cannot read the file correctly)

**Comment by dm180** [comment]
> 你可以尝试用 the`main`代替 吗`server`？（并在此处上传日志）
> 
> 此类问题通常发生在文件损坏时（或者lla​​ma.cpp无法正确读取文件）
main
[main.log](https://github.com/ggerganov/llama.cpp/files/14515081/main.log)
![QQ截图20240307040749](https://github.com/ggerganov/llama.cpp/assets/37135444/31289c47-c6ff-4522-9e46-1cc2f7c6d2a3)

I have tried several GGUF models and just downloaded another one to try, with the same results
