### ISSUE TITLE
A few questions about the positional encodings

### ISSUE THREAD

**Issue by CPegasus** [ggerganov/llama.cpp#594]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Question

It is very kind of you to share such an amazing repo.  It works on my android device!
My question is that where is the Rotary Embedding implementation in the code? Or what work do you do to achieve this implicitly?  I found it in the [official code](https://github.com/facebookresearch/llama/blob/57b0eb62de0636e75af471e49e2f1862d908d9d8/llama/model.py#L63) but I don't seem to see the implementation of this part in your code. Maybe I was careless.

**Comment by rw9609162** [comment]
Yeah you must have been careless, it's pretty awesome that you noticed though are very experienced in this kind of thing?

**Comment by CPegasus** [comment]
Got it! 
Seems to be the op named **ggml_rope**.
```cpp
// rotary position embedding
// in-place, returns view(a)
// if mode == 1, skip n_past elements
// TODO: avoid creating a new tensor every time
struct ggml_tensor * ggml_rope(
        struct ggml_context * ctx,
        struct ggml_tensor  * a,
        int                   n_past,
        int                   n_dims,
        int                   mode);
