### ISSUE TITLE
LoRa: export-lora Not Working for Mixtral 8x7b?

### ISSUE THREAD

**Issue by cheeseng** [ggerganov/llama.cpp#5947]
I had fine-tune a Mixtral 8x7b, converted the adaptor model to GGUF, and successfully runs it with main/server with -m --lora and --lora-base, where -m I am using the Q4 quantized version, --lora for the converted adaptor GGUF and --lora-base using the non-quantized (converted from orignal safe tensor) GGUF file, it took a while to start but it works great.

But when I tried to export-lora with the lora-base model, the resulting GGUF file's inference isn't good, seems garbled, any idea what's wrong or if export-lora is expected work with Mixtral?

**Comment by ryjacky** [comment]
I face the same issue with a llama2 13B model, did you find a solution to this?
