### ISSUE TITLE
modify the embedding output at the "v1/embeddings" endpoint to be in normalized embedding

### ISSUE THREAD

**Issue by redlion0929** [ggerganov/llama.cpp#5954]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
Configure server.cpp to output normalized embeddings with the endpoint set to `"v1/embeddings"`.

# Motivation

While utilizing `server.cpp`, I've noticed that it cannot currently directly output normalized embedding vectors. This lack of functionality forces clients to handle normalization, which could be more efficiently managed server-side. 
Normalized embedding is useful in text embedding tasks like retrieval, reranking, clustering. OpenAI embeddings are also normalized to length 1. 

Providing normalized embeddings directly from the server would streamline workflows for **llama.cpp** users, thereby enhancing the utility of the library. 

# Possible Implementation

Firstly, implement a function for embedding normalization. 
Secondly, apply this function to normalize each embedding prior to storing it in the output JSON.

**May I implement this feature and submit a pull request?**

**Comment by ggerganov** [comment]
Yes, go ahead. See the `embedding` example:

https://github.com/ggerganov/llama.cpp/blob/9674aaf35cb81478eb38c3f3ebde713ec72fbb79/examples/embedding/embedding.cpp#L26-L36

Something similar should be done in `server`.

In the future, we can think about integrating the normalization inside the `llama` library. But I need to see more use cases and understand when it's needed and when it is not needed and what other types of normalizations are used in practice
