### ISSUE TITLE
how to set this chat_template  in server?

### ISSUE THREAD

**Issue by wac81** [ggerganov/llama.cpp#5974]
how to set this chat_template in openchat?
because i watched output it's difference from ./server and python  -m llama.cpp.server. then i thought, may is  difference chat_template made this?

openchat chat_template:
Using gguf chat template: {{ bos_token }}{% for message in messages %}{{ 'GPT4 Correct ' + message['role'].title() + ': ' + message['content'] + '<|end_of_turn|>'}}{% endfor %}{% if add_generation_prompt %}{{ 'GPT4 Correct Assistant:' }}{% endif %}

how to set chat_template in ./server with --chat-template

**Comment by phymbert** [comment]
Have a look to https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template

**Comment by ngxson** [comment]
We don’t support custom chat template for now, but you can use /completions endpoint (not /chat/completions) and input the formatted chat with the template that you made

**Comment by wac81** [comment]
I have an extension of that problem, server and python -m llama.cpp.server startup get inconsistent results, server is way worse and less controllable, I observed the python -m startup method, it should be using gguf's chat_template, I don't know if I'm right or not, but the result is very different, I am using openchat-0106.

**Comment by wac81** [comment]
> Have a look to https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template

I've definitely seen the link, but thanks anyway

**Comment by teleprint-me** [comment]
You can manually set the chat template using gguf-py. Look at set-metadata.py in examples. I would go into more detail, but I have to go to work. I can post later if you're still having trouble understanding how to do it.

**Comment by ngxson** [comment]
@teleprint-me He's using custom self-made chat template `{{ 'GPT4 Correct ' + message['role'].title()`

This is not a common chat template that is supported by llama.cpp, so it won't work. Please see discussion: https://github.com/ggerganov/llama.cpp/issues/5922#issuecomment-1983528848

**Comment by teleprint-me** [comment]
Yes, I understand how the template works. It doesn't change anything. My point stands.
