### ISSUE TITLE
pp 32 significantly slower in new build

### ISSUE THREAD

**Issue by Azirine** [ggerganov/llama.cpp#5986]
System: MacBook Pro w/ i5-1038NG7
./llama-bench -m model.gguf -p 32

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.19 ± 0.05 |
| llama 7B mostly Q5_K - Medium  |   4.78 GiB |     7.24 B | BLAS       |          4 | pp 32      |     11.60 ± 0.09 |

build: 9d5949f (1552)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      7.48 ± 0.07 |
| llama 7B Q5_K - Medium         |   4.78 GiB |     7.24 B | BLAS       |          4 | pp 32      |      6.71 ± 0.11 |

build: bb6d00bb (2392)

**Comment by Azirine** [comment]
Found breaking change in 8406b09 (1574):

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.23 ± 0.05 |

build: 922754a (1567)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.17 ± 0.14 |

build: bb03290 (1571)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.17 ± 0.10 |

build: b38a16d (1573)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.27 ± 0.18 |

build: 8406b09 (1574)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.34 ± 0.09 |

build: 64e64aa (1575)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.33 ± 0.06 |

build: f7f9e06 (1583)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.27 ± 0.06 |

build: 5aa365d (1613)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.35 ± 0.06 |

build: fe680e3 (1620)

**Comment by Azirine** [comment]
More comparisons between b38a16d (1573) and 8406b09 (1574):

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 4       |     10.58 ± 0.20 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 8       |     10.55 ± 0.32 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 16      |     10.85 ± 0.17 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.17 ± 0.10 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 64      |     10.25 ± 0.09 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 128     |      9.75 ± 0.14 |

build: b38a16d (1573)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 4       |     10.70 ± 0.32 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 8       |     10.93 ± 0.05 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 16      |     10.87 ± 0.08 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.19 ± 0.07 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 64      |      7.00 ± 0.12 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 128     |     10.56 ± 0.33 |

build: 8406b09 (1574)

**Comment by ggerganov** [comment]
Does changing the number of threads help?

**Comment by Azirine** [comment]
> Does changing the number of threads help?

No, I tested 1, 2, 4 and 8 threads (CPU has 4 cores, 8 threads):

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          1 | pp 32      |      2.91 ± 0.07 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          2 | pp 32      |      5.55 ± 0.10 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     11.17 ± 0.10 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          8 | pp 32      |     10.87 ± 0.14 |

build: b38a16d (1573)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          1 | pp 32      |      4.31 ± 0.21 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          2 | pp 32      |      4.20 ± 0.05 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      4.19 ± 0.07 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | BLAS       |          8 | pp 32      |      4.26 ± 0.07 |

build: 8406b09 (1574)

**Comment by ggerganov** [comment]
Before 1574, BLAS was not used with quantized data, so try disabling BLAS on latest `master`:

```bash
make clean && LLAMA_NO_ACCELERATE=1 make -j
```

**Comment by Azirine** [comment]
With LLAMA_NO_ACCELERATE=1 pp 32 improved but pp 128 and 256 got worse:

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 4       |     10.49 ± 0.16 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 8       |     10.86 ± 0.17 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 16      |     11.04 ± 0.05 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |      7.48 ± 0.07 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 64      |     10.81 ± 0.26 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 128     |     13.79 ± 0.10 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 256     |     15.86 ± 0.55 |

build: bb6d00bb (2392)

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 4       |     10.66 ± 0.10 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 8       |     10.58 ± 0.26 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 16      |     11.00 ± 0.07 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 32      |     10.71 ± 0.14 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 64      |     10.34 ± 0.14 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 128     |      9.97 ± 0.10 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | CPU        |          4 | pp 256     |      9.79 ± 0.43 |

build: 44ca159f (2404)

**Comment by ggerganov** [comment]
Yup, that's expected - it's the reason to make the 1574 change

Depending on your use case you can decide wether to use BLAS or not, or to adjust the size limit after which BLAS is used:

https://github.com/ggerganov/llama.cpp/blob/44ca159faf4fbe1a7ace13a962845ba7cdfd95ec/ggml.c#L10506-L10512

Maybe on your system you can enable BLAS and change those `32`s above to `64`s

Unfortunately, there is no one size fits all, so not much else can be done

**Comment by Azirine** [comment]
Thanks, results improved with this change:
(ne0 >= 64 && ne1 >= 64 && ne10 >= 64)) {

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 32      |     10.48 ± 0.32 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | BLAS       |          4 | pp 128     |     13.54 ± 0.22 |

build: 44ca159f (2404)
