### ISSUE TITLE
CUDA error: an illegal memory access was encountered，This problem has been confusing me for days. Thank you.

### ISSUE THREAD

**Issue by lizhichao999** [ggerganov/llama.cpp#5990]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
![1710143231390](https://github.com/ggerganov/llama.cpp/assets/34128722/6e12f60d-079e-41cb-885a-58d371a2bcda)

 GPU：NVIDIA RTX A6000
ollama： 0.1.26

# Feature Description

When I executed the command: ollama run gemma:7b, an error occurred related to the data information.
CUDA error: an illegal memory access was encountered
  current device: 0, in function ggml_backend_cuda_buffer_get_tensor at C:\Users\jeff\git\ollama\llm\llama.cpp\ggml-cuda.cu:10939
  cudaDeviceSynchronize()
GGML_ASSERT: C:\Users\jeff\git\ollama\llm\llama.cpp\ggml-cuda.cu:244: !"CUDA error"

I only have a 128G GPU. Do I need more than 2 GPUs? I can run it on my local laptop with 2 GPUs without any errors.

This problem has been confusing me for days. Thank you.

**Comment by lizhichao999** [comment]
close

**Comment by ColumbusAI** [comment]
what was the fix for this? I am receiving the same error on b5002 on windows with cuda
