### ISSUE TITLE
CUDA error: an illegal memory access was encountered，This problem has been confusing me for days. Thank you.

### ISSUE THREAD

**Issue by lizhichao999** [ggerganov/llama.cpp#5991]
![image](https://github.com/ggerganov/llama.cpp/assets/34128722/b289c9a8-8d7e-4b6c-a470-c34db4532ed9)

GPU：NVIDIA RTX A6000
ollama： 0.1.26

When I executed the command: ollama run gemma:7b, an error occurred related to the data information.
CUDA error: an illegal memory access was encountered
current device: 0, in function ggml_backend_cuda_buffer_get_tensor at C:\Users\jeff\git\ollama\llm\llama.cpp\ggml-cuda.cu:10939
cudaDeviceSynchronize()
GGML_ASSERT: C:\Users\jeff\git\ollama\llm\llama.cpp\ggml-cuda.cu:244: !"CUDA error"

I only have a 128G GPU. Do I need more than 2 GPUs? I can run it on my local laptop with 2 GPUs without any errors.

This problem has been confusing me for days. Thank you.

**Comment by HanClinto** [comment]
How is ollama calling into llama.cpp? What parameters are it using? Might want to open the bug with them to ensure that the configuration is correct.

> Do I need more than 2 GPUs? 

Definitely not. If anything, it might be an improper configuration where your multiple GPUs are confusing things. Again, a lot of this depends on how it's being called from Ollama. Once we know that, then we can try reproducing the error without Ollama involved.

I would suggest that you attempt to reproduce this bug without Ollama being involved -- just download your model and invoke llama.cpp directly -- once we have an isolated reproduction case, then we can resolve it.

**Comment by raj-maharajwala** [comment]
Same error with me
