### ISSUE TITLE
Quantazation Questions - Odd bits

### ISSUE THREAD

**Issue by pure-water** [ggerganov/llama.cpp#6011]
Just wondering for these odd bits quantazation as 1.5/2/3/5,  it makes sense it will shrink the model size. But most of the hardware do not have native data type for it, so in theory you would not get inference speed improved that much (yes, it will probably save some  power). But i would not expect there is a big difference between 2/3 for example?

**Comment by stduhpf** [comment]
I haven't really looked too deep into the quantization code, so don't take my word for it at face falue.

 My assumption is that the performance difference comes from the fact that the main limiting factor during inference isn't raw compute, but rather memory bandwith. Having less bit per weights mean less data sent back on forth between memory and cache, which is a very slow operation compared to most CPU/GPU opcodes.

**Comment by ngxson** [comment]
> But most of the hardware do not have native data type for it

That's true, but llama.cpp has hardware-specific code to handle some operation directly with quantized types, without having to dequantizing them. For example, `ggml_vec_dot_q4_0_q8_0` has low-level code optimized for ARM, AVX, AVX2,... The same can be found in Metal or CUDA backends.

https://github.com/ggerganov/llama.cpp/blob/4755afd1cbd40d93c017e5b98c39796f52345314/ggml-quants.c#L3625

> But i would not expect there is a big difference between 2/3 for example?

I don't think so. Personally I feel like quant lower than Q4_K are mostly to save space, they do not provide better inference speed. Maybe it will change in the future (who know?), when someone figure out how to use bitwise operations to work with low-quant types.
