### ISSUE TITLE
Checking llama's defrag_graph size

### ISSUE THREAD

**Issue by Xarbirus** [ggerganov/llama.cpp#6019]
I would like to clarify whether [this](https://github.com/ggerganov/llama.cpp/blob/8030da7afea2d89f997aeadbd14183d399a017b9/llama.cpp#L9094) check
```
if (6*(n_moves + nh)*n_layer >= LLAMA_MAX_NODES) {
    // the graph is too big, we cannot move more cells
    break;
}
```
is correct in `llama_kv_cache_defrag_internal?`

Now, if there is one large hole (huge `nh` variable) in the kv_cache, the condition will not be met and the cycle will be stopped, although only one move will be enough to fill it.

Wouldn't it be more correct to replace the check with just `6*n_moves*n_layer >= LLAMA_MAX_NODES`?

**Comment by Xarbirus** [comment]
Oh, I think I get what you mean.

I tried to improve the check a little without complicating it too much, and [this](https://github.com/ggerganov/llama.cpp/pull/6037) is what I ended up with. I'll be glad to get your feedback.

**Comment by Xarbirus** [comment]
And one more question, isn’t `n_tokens` included in `kv_self.used` variable at [this](https://github.com/ggerganov/llama.cpp/blob/d8fd0ccf6ac8b07791ffd1575eed436930854ae3/llama.cpp#L8901) point?
```
const float fragmentation = kv_self.n >= 128 ? 1.0f - float(kv_self.used + n_tokens)/float(kv_self.n) : 0.0f;
```

**Comment by ggerganov** [comment]
Thanks for looking into this!

- I think the PR is good
- Yes, your correct - this is overestimating the number of used tokens

**Comment by Xarbirus** [comment]
Great! I fixed fragmentation calculation and opened the PR for your review.
