### ISSUE TITLE
AVX512 support

### ISSUE THREAD

**Issue by amiralimi** [ggerganov/llama.cpp#6024]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I was looking through the code for the AVX512 support and I saw that none of the SIMD functions were implemented using 512-bit vector instructions (`__m512`). Is there any specific reason for not using these instructions? 

# Motivation

This will give a speed boost over `__m256` instructions already used.

**Comment by sorasoras** [comment]
should also consider avx512_vnni  as it did direct acceleration
