### ISSUE TITLE
Qwen based models using massive amounts of vram for context compared to mistral/llama based models

### ISSUE THREAD

**Issue by christiandaley** [ggerganov/llama.cpp#6032]
Here is an example of loading a Qwen-72b based model (Smaug-72b). This is a Q6_K quant and is being used with a context size of 8192. The model is loaded using llamacpp from within `text-generation-webui`. 

![image](https://github.com/ggerganov/llama.cpp/assets/5554082/e9952c4d-a1ad-4893-82c4-602ddf492b49)

As we can see, an 8192 context size requires *over 20GB of VRAM* for the llama_kv_cache_init. Now here's a screenshot of a Q8_0 mistral based 70b model being loaded with the same 8192 context size.

![image](https://github.com/ggerganov/llama.cpp/assets/5554082/e1e3b543-3b27-4955-bff3-ab93417bb3b0)

The VRAM usage is only 2.5GB. So, Qwen is taking up 8x the amount of VRAM for the same amount of context.

I've spent some time looking around but haven't been able to find any explanation for this discrepancy. It's making Qwen based models basically unusable at longer context length.

**Comment by slaren** [comment]
Mistral uses GQA to reduce memory usage of the KV.

**Comment by sorasoras** [comment]
you have to wait for qwen2 to get GQA support.

**Comment by christiandaley** [comment]
Ah, so there's no code fix that can be done to reduce the memory usage? If that's the case then I'll go ahead and close this issue.
