### ISSUE TITLE
Update details about running llama in Termux on Android mobile

### ISSUE THREAD

**Issue by wanix1988** [ggerganov/llama.cpp#6038]
The original README.md does not contain details for the Android using Termux. I will update the corresponding details with a result picture.
![Screenshot_2024-03-13-19-15-24-323_com termux](https://github.com/ggerganov/llama.cpp/assets/2557883/8a61811a-6693-49e0-aa66-16aac8ae0756)

**Comment by sqzhang-jeremy** [comment]
Run Llama2-7B in Google Pixel 8 Pro.
<img width="464" alt="iShot_2024-03-23_12 50 35" src="https://github.com/ggerganov/llama.cpp/assets/57616347/3279ac23-ebb8-4a08-96b5-0a7cd2874577">
