### ISSUE TITLE
Reverting generated output/user input!

### ISSUE THREAD

**Issue by niansa** [ggerganov/llama.cpp#604]
Hey!

This is a feature request for reverting input/output. One example usecase is to be able to retry generation if the response wasn't as desired.
One way of implementing this could be by adding the ability to create "snapshots" using signals(?).

Thanks a lot
niansa

**Comment by x02Sylvie** [comment]
Adding retry through ctrl + r could be great for interactive mode, especially the chat mode when AI messes up.

Additionally could be neat if included as part of API

**Comment by LostRuins** [comment]
You might want to check out https://github.com/LostRuins/llamacpp-for-kobold which has this feature, plus it caches the same tokens from the previous prompt to avoid the need for reprocessing the whole prompt if you only want to retry a single sentence.

**Comment by niansa** [comment]
Is restoring old token array enough to return to the same state?

**Comment by niansa** [comment]
I tested, it is not, unfortunately.

**Comment by horenbergerb** [comment]
> You might want to check out https://github.com/LostRuins/llamacpp-for-kobold which has this feature, plus it caches the same tokens from the previous prompt to avoid the need for reprocessing the whole prompt if you only want to retry a single sentence.

@LostRuins are you interested in elaborating how you achieved this in llamacpp-for-kobold? Or would you be able to point towards relevant code in your repo? Thanks for you work, btw. The kobald UI looks pretty clean and I'm definitely keeping an eye on it!

**Comment by horenbergerb** [comment]
I'm trying to wrap my head around how this feature would be implemented. It seems like you'd need to keep track of the last message [in this block](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/main.cpp#L243). Then you'd need to catch the ctrl-r signal. It should interrupt any ongoing generation/input and remove the last message from `embd`. Lastly you need to ensure the program knows to start generating a message again.

Is it actually that simple? I'm about to go on vacation for a week, but I'll try to experiment with it when I can.

**Comment by LostRuins** [comment]
@horenbergerb Sure, so basically what I do is reuse the old KV state from the context. The important thing to note is the `n_past` parameter. Essentially it's a pointer indicating how much of the context should be used, think of it like an attention mask.

So once you've reused the old state, simply tokenize the old prompt together with the new one, and compare the IDs in both tokenized arrays. Start from the beginning, n_past = position 0. For each position that matches on both arrays, increment n_past by 1, until you reach a divergence. That is the common tokens that you can preserve from the old state. Then truncate your `embd_inp` such that those tokens are removed from it, and rewind `n_past` to the point of divergence. You can now proceed to generate and stochastically sample from that point.

**Comment by niansa** [comment]
Thanks for the hint! Definitely going to mess with that.
