### ISSUE TITLE
master brach support latest llama.cpp for gemma and qwen2

### ISSUE THREAD

**Issue by KittenYang** [ggerganov/llama.cpp#6051]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

The master brach's SwiftUI example is broken, and the commit `0e18b2e7` it's not support latest llama.cpp which supports gemma and qwen2.

# Motivation
Run latest model on iOS

# Possible Implementation
Update Package.swift

**Comment by ggerganov** [comment]
It works on my machine and there is not enough info in this issue, so closing
