### ISSUE TITLE
Download model gguf file from hf

### ISSUE THREAD

**Issue by phymbert** [ggerganov/llama.cpp#6085]
### Motivation

Since GGUF is officially supported on [huggingface](https://huggingface.co/docs/hub/gguf) <3, '--model' might check for local path then fall back to hf repo id.
If a '--file' is provided it should override default for f16.

### References
- #4735 
- #5501
- https://huggingface.co/docs/hub/gguf

**Comment by ggerganov** [comment]
We considered this at some point (https://github.com/ggerganov/llama.cpp/pull/4735) but it opens a lot of security concerns due to the core library having to execute commands. So we settled with #5501 which should be good enough for most cases
