### ISSUE TITLE
MobileVLM convert.py error

### ISSUE THREAD

**Issue by TemporalAgent7** [ggerganov/llama.cpp#6087]
I'm trying to set up MobileVLM, following the instructions from here: https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/MobileVLM-README.md

At step 4 (Use convert.py to convert the LLaMA part of LLaVA to GGUF), I'm getting this error:

`Exception: Unexpected tensor name: model.vision_tower.vision_tower.vision_model.embeddings.class_embedding. Use --skip-unknown to ignore it (e.g. LLaVA)`

I tried adding --skip-unknown, but running llava-cli.exe with the resulting gguf doesn't produce any output. Any tips for how to proceed or where I could download pre-produced GGUFs for MobileVLM?

Thanks!

**Comment by drivkin** [comment]
Same issue

**Comment by yingted** [comment]
I had to set concurrency to 1 too to get it to work. Also, some of the paths are wrong.

**Comment by wawaa** [comment]
Same issue +1

**Comment by rezacopol** [comment]
same issue +1

**Comment by sunzhe09** [comment]
same issue +1，my test model is mobilevlmv2

**Comment by howardgriffin** [comment]
same promblem. how to solve it

**Comment by RainFrost1** [comment]
same promblem. how to solve it
