### ISSUE TITLE
Gemma-7b-it quantized still not working

### ISSUE THREAD

**Issue by nxphi47** [ggerganov/llama.cpp#6095]
Hi, I install the latest llama.cpp on macos and tried [gemma-7b-it-GGUF-Q4](https://huggingface.co/mlabonne/gemma-7b-it-GGUF), but the model still generate nonsense either in chat mode or completion mode. I have added the `<bos>` token to the prompt.

```bash
 ./main -m  ./mlabonne/gemma-7b-it-GGUF/gemma-7b-it.Q4_0.gguf -n 256  --color -i
```

Results:

<img width="1128" alt="Screenshot 2024-03-16 at 1 16 49 PM" src="https://github.com/ggerganov/llama.cpp/assets/19323568/a15db22a-bc79-4783-b0f9-64ab13585caa">

Please help check or instruct how to fix this problem.

**Comment by dranger003** [comment]
This model is quite sensitive, take a look at the [model page here](https://huggingface.co/dranger003/gemma-7b-it-iMat.GGUF) and try the following:
```
./main -p "<start_of_turn>user\nWrite an essay about AI.<end_of_turn>\n<start_of_turn>model\n" -e --repeat-penalty 1.0 -ngl 29 -m ggml-gemma-7b-it-iq3_m.gguf
```

**Comment by nxphi47** [comment]
@dranger003 thanks ! It turns out that —repeat-penalty is the culprit https://huggingface.co/google/gemma-7b-it/discussions/38

@ggerganov Could you consider setting —repeat-penalty to 1.0 by default instead ? Would that damage other models performance? Usually repeat-penalty is not enabled by default in other frameworks.
