### ISSUE TITLE
Support for Sparse MoE  new model Qwen2idae-16x14B

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#6097]
# Prerequisites

# Feature Description
support for inference  https://huggingface.co/hywu/Qwen2idae-16x14B-v1.0
it's another variation of  
https://github.com/ggerganov/llama.cpp/issues/5365

# Motivation

The perf is really good for a 15B model, and it's require a lot less finetune hardware.
![image](https://github.com/ggerganov/llama.cpp/assets/6722084/34a344e3-eff8-4ea4-bda9-a9e3ef10d419)

# Possible Implementation

**Comment by ramzeez88** [comment]
yes please !

**Comment by ramzeez88** [comment]
Any progress on this matter?

**Comment by kratorado** [comment]
guys, have a look https://github.com/punica-ai/punica

**Comment by sorasoras** [comment]
> guys, have a look https://github.com/punica-ai/punica

Not the same thing

**Comment by kratorado** [comment]
> > guys, have a look https://github.com/punica-ai/punica
> 
> Not the same thing

strange... I was trying to reply on the https://github.com/ggerganov/llama.cpp/issues/6377 .
sorry for bothering
