### ISSUE TITLE
 model's reply is incomplete with setting nlen to 64

### ISSUE THREAD

**Issue by AnswerZhao** [ggerganov/llama.cpp#6108]
why set the nlen to 64 in Llm.kt in llama.android project? This parameter setting limits the length of the model's reply, that is, the current reply result is incomplete. But when i change the nlen value, i find the value is too hard to define, why the EOS can not work but only depends on the nlen? Thanks you for help.

**Comment by ggerganov** [comment]
You can easily modify the example to check for EOS token and stop

**Comment by AnswerZhao** [comment]
@ggerganov Yep, i check the EOS token, but not work, now i am digging into it.
