### ISSUE TITLE
DeepSeek VL support

### ISSUE THREAD

**Issue by SinanAkkoyun** [ggerganov/llama.cpp#6130]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

DeepSeek VL support would be amazing! (perhaps with the option to also quantize vision encoder weights if that makes a difference)

**Comment by sunhaha123** [comment]
> This issue was closed because it has been inactive for 14 days since being marked as stale.

open it!

**Comment by dimitribellini** [comment]
Dear Team, 
I think this models is far better than LLAVA and many other. 
Could you please check if it will be possible to support on your great software?
At the moment "we" lack of a good Vision model :-)
Thanks so much

**Comment by sunhaha123** [comment]
> Dear Team, I think this models is far better than LLAVA and many other. Could you please check if it will be possible to support on your great software? At the moment "we" lack of a good Vision model :-) Thanks so much

Can't agree more!

**Comment by mzwing** [comment]
I'm afraid that this could be tough for supporting this model... The model requires some Deepseek-customized tools to support it's VL inference (See [here](https://huggingface.co/deepseek-ai/deepseek-vl-7b-chat#simple-inference-example)).

And most of the vision inference maintainers are quite busy, they even cannot maintain the LLaVA support in time.

**Comment by SinanAkkoyun** [comment]
@mzwing May I ask, is the deepseek decoder the same architecture as llama? Meaning, it would only take to load the vision encoder (for now in fp16 with deepseek code) and pass the embedding to the model, right? Or are there even decoder differences?

If the above would work, I might give it a try in the next weeks

**Comment by mzwing** [comment]
> @mzwing May I ask, is the deepseek decoder the same architecture as llama? Meaning, it would only take to load the vision encoder (for now in fp16 with deepseek code) and pass the embedding to the model, right? Or are there even decoder differences?
> 
> If the above would work, I might give it a try in the next weeks

The ViT layers may be quite different from LLaVA, but the LLM part should work with common convert process after removing the ViT part (see llava-surgery)
