### ISSUE TITLE
Which tokenizer.model is needed for GPT4ALL? 

### ISSUE THREAD

**Issue by cannin** [ggerganov/llama.cpp#614]
Which tokenizer.model is needed for GPT4ALL for use with convert-gpt4all-to-ggml.py? Is it the one for LLaMA 7B? It is unclear from the current README and gpt4all-lora-quantized.bin seems to be typically distributed without the tokenizer.model file.

**Comment by BenjiKCF** [comment]
I wanna kwo this question too.

**Comment by MaterialFuture** [comment]
This was closed as completed without giving explanation. Can you please explain for others viewing this issue in the future or link to the issue where the resolution was found?

**Comment by MeinDeutschkurs** [comment]
Yeah, it's interesting. Want to use the model of freedomGPT inside of it. :D But it does not work, if I simply copy the file to GPT4ALLs path.
