### ISSUE TITLE
7B model running too slow on android

### ISSUE THREAD

**Issue by sethblocks** [ggerganov/llama.cpp#6148]
I built llama.cpp using the make command on my S24 using Termux but I have been getting super slow speeds running 7b mistral. My best speed I have gotten is about 0.3 tokens per second. I also tested on my pixel 5 and got about 0.15. I am not using any blas build currently. I have seen other devices with older os the same chipsets go faster, what am I doing wrong?
![Screenshot_20240318_144430_Termux](https://github.com/ggerganov/llama.cpp/assets/56612770/0e277eb9-a861-4ec1-8ed4-431e53271ece)
Sorry if I'm using the wrong label

**Comment by Jeximo** [comment]
Probably you'll need to either more or less `--threads N` [--threads readme](https://github.com/ggerganov/llama.cpp/blob/4e9a7f7f7fb6acbddd1462909c8d696e38edbfcc/examples/main/README.md?plain=1#L273). Maybe try 2 or 3. It may also be the reverse - some devices require more cores for best performance, so you'll have to test and see.

Lower `--batch-size N`(_maybe try 20_) helps generation begin a little quicker.

Finally, anything heavy in the background should be closed. ie, web browser@ the same time will affect performance.

**Comment by sethblocks** [comment]
it seems to be a little faster using 2 cores instead of default 4/8. It went from about 0.26 tokens/second to 0.31. Generation is starting pretty fast with `--batch-size 20`

**Comment by Jeximo** [comment]
From where are you loading the model? Let's see your command line.

**Comment by sethblocks** [comment]
![Screenshot_20240318_161855_Termux](https://github.com/ggerganov/llama.cpp/assets/56612770/14e59b83-f7bf-4252-9ef4-e2ecc3039eab)
Command I'm using

**Comment by Jeximo** [comment]
OK, seems to be setup correctly as far as I can tell.  I assume you also tried more cores, like 6-7? It may worsen performance, but it's better to check.

Low performance usually happens with multiple apps running in the background. For example, I can't run Firefox & `llama.cpp` at the same time, it's too heavy, so double-check your background apps.

I think your device _should_ be able to handle a 7b Q4_0, but you might want to try Q4_K_S, IQ_4_XS, or Q3_K_L.

**Comment by sethblocks** [comment]
Closing apps seems to help a tiny bit and increasing cores does make it slower. I'm starting to think Android could be slowing it down to save power or something like that, but I don't know too much about how the OS works.

**Comment by Jeximo** [comment]
> I'm starting to think Android could be slowing it down to save power

Yeah, it may be throttled - some Samsungs have "_Enhanced processing_", supposedly speeds up applications, but I haven't tried it. 
![Screenshot_20240318_210342](https://github.com/ggerganov/llama.cpp/assets/21167443/798af076-face-40c1-9ebc-9e7b081b7cc4)


You might build with `BLAS`, or `CLBLAST`, but CPU is currently best on Android as far as I know.

If nothing else, then you might try [phi-2-layla-v1-chatml-Q6_K.gguf](https://huggingface.co/l3utterfly/phi-2-layla-v1-chatml-gguf/tree/main), which is nice for it's small size. Here's an example prompt:
```
./main -m phi-2-layla-v1-chatml-Q6_K.gguf --color  -c 2048 --keep -1 -t 2 -b 7 -cml -p 'You are an intelligent, loyal servant.'
```

**Comment by sethblocks** [comment]
After some googling and checking settings it seems they removed enhanced processing. For now I'm gonna try that model.

**Comment by sethblocks** [comment]
phi-2-layla-v1-chatml-Q6_K.gguf is working pretty fast at about 6 tokens per second. I did think of another possible problem, my ram usage is pretty high (without a model loaded) and it seems to be using swap where the model is probably mostly held.
![Screenshot_20240318_180105_Device care](https://github.com/ggerganov/llama.cpp/assets/56612770/a0a17cbf-1a83-40cc-bb8a-8e30ec940b72)
![Screenshot_20240318_180054_Device care](https://github.com/ggerganov/llama.cpp/assets/56612770/811e1fbb-c7a4-4f02-9fe6-70a7de9793b8)

**Comment by Manamama** [comment]
PS. Try each gguf with:
`time main  --color --n-predict 50 -c 2048 --keep -1 -t 6 -b 7 -p "List 5 types of flowers, only names." -m `

Interestingly, '  -c 2048 ' is material here: faster then.

**Comment by USBhost** [comment]
On my OnePlus 12 (16GB RAM) I had to turn off mmap or my model would get swapped.

**Comment by Manamama** [comment]
I change my advice completely . 

I have thr swap off (apart from that zram) and when the ggufs are on the external SD card it takes up to 1 hour (sic) to generate anything. It is almost exactly 10 times faster when run off the Internal SD card. 

This one is off the the Internal SD, it is slow in fact:
```

time llm "Introduce yourself and your capabilities." -m mistral-7b-instruct-v0.1.Q4_0                         
A: Hello! I am an AI language model designed to assist you with any information or task you may need help with. I can answer questions, provide definitions, give examples, and even write essays for you. My capabilities are vast and I am here to assist you 24/7. How may I be of service to you today?

real 9m51.195s
user 11m53.759s sys 8m55.562s
```

- it takes over 1 hour when read off the external SD, a quite fast one. Does not make sense, as all is operating in RAM (about 3 GB for that Mistral above) , but that is further to my series of tests over about 10 ggufs, from Tiny Llama upwards, off the Internal vs External SD, same Droid.

**Comment by sethblocks** [comment]
I am now getting pretty great speed with the phi model running at about 8-10 tokens per second and 3-4 with mistral. 
![Screenshot_20240322_191517_Termux](https://github.com/ggerganov/llama.cpp/assets/56612770/3d7dfe7f-7343-4b8f-aca7-bc997bcbdb0f)
For these I am using this command:
`./main -m phi-2-layla-v1-chatml-Q6_K.gguf --threads 6 -p "5 types of flowers:"  -c 2048 --keep -1 -b 7` similar command for both models, only changed the model name. It works pretty well now, thanks.
