### ISSUE TITLE
Server may have a directory traversal vulnerability fixed upstream

### ISSUE THREAD

**Issue by slaren** [ggerganov/llama.cpp#6162]
https://github.com/yhirose/cpp-httplib/issues/1768

**Comment by phymbert** [comment]
@ngxson what do you think about upgrading?

**Comment by ngxson** [comment]
Yes we will eventually need to update `httplib` to upsteam. You can open a PR if you want.

FYI, I actually foreseen this kind of bug. In #5939 I said:

> Disable static assets path by default. We already have all the JS/HTML files embedded in the compiled binary. I feel like leaving static path enabled by default is maybe a security hazard ==> it's now disabled by default

Turns out, it is.

**Comment by phymbert** [comment]
Unfortunately I am really busy atm, as the issue is only on windows I am ok to wait
