### ISSUE TITLE
bad command line parsing behaviour with some filenames

### ISSUE THREAD

**Issue by schmorp** [ggerganov/llama.cpp#6163]
quantize (only command I have tested this with) gets confused by some filenames of some models, e.g.

   quantize 08x7bhf.gguf 08x7bhfGGUF~ Q4_K_S

... should quantize one gguf file into another, but instead, it fails with a weird error message:

   main: invalid nthread 'Q4_K_S' (stoi)

My guess is that somehow it interprets the 08x name as a number, but that's clearly not the whole story. Might even be a security issue if commands can be tricked into misinterinterpreting filenames as something else (this behaviuour cannot be suppressed with "--" either).

**Comment by someonenameguy** [comment]
I tried quantizing `13b-psyfighter2-erebus3-dareties` I got the same error `main: invalid nthread 'q2_k' (stoi)`.
Changing the repo name to `psyfighter-erebus-dareties` (basically removing all the numbers) fixed the error.

**Comment by bvannah** [comment]
> I tried quantizing `13b-psyfighter2-erebus3-dareties` I got the same error `main: invalid nthread 'q2_k' (stoi)`. Changing the repo name to `psyfighter-erebus-dareties` (basically removing all the numbers) fixed the error.

This worked for me, thank you.
