### ISSUE TITLE
"error: unknown argument: --ctx-size" after llama.cpp update.

### ISSUE THREAD

**Issue by Folko-Ven** [ggerganov/llama.cpp#6191]
After updating llama.cpp, when I try to run the model, I get this error. I assume it has been replaced with another one, but there are no changes in main.exe -h or the documentation.

**Comment by Folko-Ven** [comment]
@dranger003 Hi! I just updated to the last commit, the problem is still there.
I'm using win 11.
Both cmake and gcc have the problem.
I haven't changed it for several months (I use a powershell script to run it).
To run model, I use the following line : "./main/main_gcc_avx512 --model ./models/dolphin-2.7-mixtral-8x7b.Q6_K.gguf --threads 8 --color --temp 0.9 --mirostat 2 --ctx_size 32768 --n_predict -1 --keep -1 --chatml --log-disable"

**Comment by slaren** [comment]
The argument is `--ctx-size`. Previously the `_` were automatically converted to `-`, which allowed `--ctx_size` to work too, but that was broken in the recent change. cc @dranger003

**Comment by Folko-Ven** [comment]
> The argument is `--ctx-size`. Previously the `_` were automatically converted to `-`, which allowed `--ctx_size` to work too, but that was broken in the recent change. cc @dranger003

Yep, it's working! Thanks!
P.S. I had to change "--n_predict" as well.

**Comment by dranger003** [comment]
@slaren @Folko-Ven Thanks, I submitted a PR to resolve.
