### ISSUE TITLE
I have a specific question regarding qwen1.8b and qwen1.8b-chat, for which I am eagerly seeking your assistance.

### ISSUE THREAD

**Issue by WCSY-YG** [ggerganov/llama.cpp#6228]
I have a question I'd like to consult about. When I convert the qwen1.8b model into gguf format and use it, its responses display garbled characters. However, when I use qwen1.8b-chat, it replies normally. I would like to ask what might be causing this issue. And what can i do to solve this problem。
![1](https://github.com/ggerganov/llama.cpp/assets/89191003/142c9fbd-ceb1-4a5e-a94f-fe44dd1db577)
![1 2](https://github.com/ggerganov/llama.cpp/assets/89191003/66f42096-12b6-4882-a044-668dd43683f5)

**Comment by calculatortamer** [comment]
genuine question, why do you use a base model for chatting?
