### ISSUE TITLE
server: comment --threads option behavior

### ISSUE THREAD

**Issue by phymbert** [ggerganov/llama.cpp#6230]
As we are using batching, I am wondering what is the purpose of `--threads N` parameter in the `server`.

Should we remove it ?

**Comment by phymbert** [comment]
OK, later I will add a this precision in the readme, also specifying this is not used at all when using `--ngl`.

**Comment by Jeximo** [comment]
> As we are using batching

What about those who don't use batching?

**Comment by phymbert** [comment]
> > As we are using batching
> 
> What about those who don't use batching?

The server is using batching by design
