### ISSUE TITLE
MiniCPM Chat Template

### ISSUE THREAD

**Issue by edward70** [ggerganov/llama.cpp#6236]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Add the MiniCPM chat template: 
```
{% for message in messages %}{% if message['role'] == 'user' %}{{'<用户>' + message['content'].strip() + '<AI>'}}{% else %}{{message['content'].strip()}}{% endif %}{% endfor %}
```
https://huggingface.co/openbmb/MiniCPM-2B-dpo-fp32/blob/main/tokenizer_config.json

# Motivation

MiniCPM-dpo improves dramatically when using the recommended chat template. With alpaca or chatml, the model tends to devolve into repetitions and goes off-topic.

# Possible Implementation

- Add to the list of hardcoded chat templates for the server.
- Maybe make the support for chat templates more general? Most chat templates don't use all the features of Jinja, you could probably get away with doing some basic string matching on common variations of the template structure (like templates that have a system prompt section, or no system prompt), just swapping out the strings like 'Assistant', 'AI', 'GPT', etc.

**Comment by ngxson** [comment]
Please have a look on https://github.com/ggerganov/llama.cpp/pull/6276

The GGUF version is taken from: https://huggingface.co/s3nh/MiniCPM-2B-dpo-fp32-GGUF

The chat template is correctly implemented, but the model outputs garbage. I'm doubt that there something other than chat template to make it work with MiniCPM. Can you have a look @edward70 ?
