### ISSUE TITLE
How to quantize a fine-tuned llama model?

### ISSUE THREAD

**Issue by eyalmazuz** [ggerganov/llama.cpp#624]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I have fine-tuned llama 7B model that I want to quantize to 4-bit and run using llama.cpp
I got the weight in 3 parts .bin files and converted them to the same llama model naming scheme, i.e. "consolidated.XX"

i.e.
``pytorch_model-00001-of-00003.bin`` to ``consolidated.00.bin`` etc. etc.

since the original llama 7B model comes in a single pth file and mine is 3 files in .bin format
I changed the ``convert-pth-to-ggml.py`` script as follows:

line 37 changed from:
```
mappings = {4096: 1, 5120: 2, 6656: 4, 8192: 8}
```
to
```
mappings = {4096: 3, 5120: 2, 6656: 4, 8192: 8}
```

line 164 changed from:
```
fname_model = f"{dir_model}/consolidated.0{p}.pth"
```
to
```
fname_model = f"{dir_model}/consolidated.0{p}.bin"
```

I ran the conversion with the command: ``python3 convert-pth-to-ggml.py models/7B 1``

and got 3 files
```
ggml-model-f16.bin
ggml-model-f16.bin.1
ggml-model-f16.bin.2
```

now I want to quantize it to 4-bits as per the guide with the command: ``python3 quantize.py 7B``

I expect llama.cpp to be able to quantize a fine-tuned llama model even when it's not the original model but have the same architecture, layers, and params.

# Current Behavior

The quantize script fails to quantize the model, can't run models on llama.cpp as a results

![image](https://user-images.githubusercontent.com/34383384/228863305-43a2e561-5b80-4407-a2ea-7e4ad9163e9d.png)

# Environment and Context 

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

Manjaro Linux kernel version 6.0.19-4
CPU: i7-9750H
Dell XPS 7590
Python 3.10.9
GNU Make 4.4
g++ 12.2.1

# Steps to Reproduce
1. obtain weights from: https://github.com/Kent0n-Li/ChatDoctor
2. run the changes mentioned above to the code 

# Failure Logs

```
~/Desktop/llama.cpp python3 quantize.py 7B                                                                                                                                                                  
llama_model_quantize_internal: loading model from '/home/eyal/Desktop/llama.cpp/models/7B/ggml-model-f16.bin.2'
llama_model_quantize_internal: n_vocab = 32000
llama_model_quantize_internal: n_ctx   = 512
llama_model_quantize_internal: n_embd  = 4096
llama_model_quantize_internal: n_mult  = 256
llama_model_quantize_internal: n_head  = 32
llama_model_quantize_internal: n_layer = 32
llama_model_quantize_internal: f16     = 1
              model.layers.23.mlp.up_proj.weight - [ 4096, 11008], type =    f16 quantizing .. size =   172.00 MB ->    26.88 MB | hist: 0.004 0.021 0.006 0.006 0.005 0.006 0.008 0.017 0.842 0.018 0.009 0.008 0.006 0.007 0.008 0.029 

An error ocurred while trying to quantize the models.
```

**Comment by gjmulder** [comment]
[Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1) before submitting new issues

**Comment by eyalmazuz** [comment]
> [Please review and use the issue template](https://github.com/ggerganov/llama.cpp/blob/master/.github/ISSUE_TEMPLATE/custom.md?plain=1) before submitting new issues

@gjmulder I update the original post
