### ISSUE TITLE
qwen1_5-14b-chat-q4_0.gguf can not run on GPU

### ISSUE THREAD

**Issue by ngbruce** [ggerganov/llama.cpp#6247]
System enviorment:
Windows10

Driver:
NVIDIA-SMI 551.61 Driver Version: 551.61 CUDA Version: 12.4

GPU:
GTX 2080ti 22GB

Problem Description:
I have successfully compiled the project by executing 
cmake .. -DLLAMA_CUBLAS=ON and cmake --build . --config Release. 
However, when I attempt to run the compiled program with the following command:

`build\bin\Release\main.exe -m D:\My_Doc\PyTorchProj\ChatGLM\Models\Qwen\Qwen1.5-14B-Chat-GGUF\qwen1_5-14b-chat-q4_0.gguf -n 512 --color -i -cml -f prompts/chat-with-qwen.txt`

there are some warning messages related to model loading.

`
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no

ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes

ggml_cuda_init: found 1 CUDA devices:

  Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5, VMM: yes

llm_load_tensors: ggml ctx size =    0.18 MiB

ggml_backend_cuda_register_host_buffer: warning: failed to register 7794.73 MiB of pinned memory: operation not supported

llm_load_tensors: offloading 0 repeating layers to GPU

llm_load_tensors: offloaded 0/41 layers to GPU

llm_load_tensors:        CPU buffer size =  7794.73 MiB

`

After the model is loaded, it can run but it seems to be running entirely on the CPU. 
What could be the reason for this?

---------------------------------------------
Here are the cmd output:

`
D:\My_Doc\PyTorchProj\ChatGLM\llama.cpp>build\bin\Release\main -m D:\My_Doc\PyTorchProj\ChatGLM\Models\Qwen\Qwen1.5-14B-Chat-GGUF\qwen1_5-14b-chat-q4_0.gguf -n 512 --color -i -cml -f prompts/chat-with-qwen.txt
Log start
main: build = 2484 (5b7b0ac8)
main: built with MSVC 19.28.29914.0 for x64
main: seed = 1711028128
llama_model_loader: loaded meta data with 21 key-value pairs and 483 tensors from D:\My_Doc\PyTorchProj\ChatGLM\Models\Qwen\Qwen1.5-14B-Chat-GGUF\qwen1_5-14b-chat-q4_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv 0: general.architecture str = qwen2
llama_model_loader: - kv 1: general.name str = Qwen1.5-14B-Chat-AWQ-fp16
llama_model_loader: - kv 2: qwen2.block_count u32 = 40
llama_model_loader: - kv 3: qwen2.context_length u32 = 32768
llama_model_loader: - kv 4: qwen2.embedding_length u32 = 5120
llama_model_loader: - kv 5: qwen2.feed_forward_length u32 = 13696
llama_model_loader: - kv 6: qwen2.attention.head_count u32 = 40
llama_model_loader: - kv 7: qwen2.attention.head_count_kv u32 = 40
llama_model_loader: - kv 8: qwen2.attention.layer_norm_rms_epsilon f32 = 0.000001
llama_model_loader: - kv 9: qwen2.rope.freq_base f32 = 1000000.000000
llama_model_loader: - kv 10: qwen2.use_parallel_residual bool = true
llama_model_loader: - kv 11: tokenizer.ggml.model str = gpt2
llama_model_loader: - kv 12: tokenizer.ggml.tokens arr[str,152064] = ["!", """, "#", "$", "%", "&", "'", ...
llama_model_loader: - kv 13: tokenizer.ggml.token_type arr[i32,152064] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv 14: tokenizer.ggml.merges arr[str,151387] = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv 15: tokenizer.ggml.eos_token_id u32 = 151645
llama_model_loader: - kv 16: tokenizer.ggml.padding_token_id u32 = 151643
llama_model_loader: - kv 17: tokenizer.ggml.bos_token_id u32 = 151643
llama_model_loader: - kv 18: tokenizer.chat_template str = {% for message in messages %}{{'<|im_...
llama_model_loader: - kv 19: general.quantization_version u32 = 2
llama_model_loader: - kv 20: general.file_type u32 = 2
llama_model_loader: - type f32: 201 tensors
llama_model_loader: - type q4_0: 281 tensors
llama_model_loader: - type q6_K: 1 tensors
llm_load_vocab: special tokens definition check successful ( 421/152064 ).
llm_load_print_meta: format = GGUF V3 (latest)
llm_load_print_meta: arch = qwen2
llm_load_print_meta: vocab type = BPE
llm_load_print_meta: n_vocab = 152064
llm_load_print_meta: n_merges = 151387
llm_load_print_meta: n_ctx_train = 32768
llm_load_print_meta: n_embd = 5120
llm_load_print_meta: n_head = 40
llm_load_print_meta: n_head_kv = 40
llm_load_print_meta: n_layer = 40
llm_load_print_meta: n_rot = 128
llm_load_print_meta: n_embd_head_k = 128
llm_load_print_meta: n_embd_head_v = 128
llm_load_print_meta: n_gqa = 1
llm_load_print_meta: n_embd_k_gqa = 5120
llm_load_print_meta: n_embd_v_gqa = 5120
llm_load_print_meta: f_norm_eps = 0.0e+00
llm_load_print_meta: f_norm_rms_eps = 1.0e-06
llm_load_print_meta: f_clamp_kqv = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale = 0.0e+00
llm_load_print_meta: n_ff = 13696
llm_load_print_meta: n_expert = 0
llm_load_print_meta: n_expert_used = 0
llm_load_print_meta: causal attn = 1
llm_load_print_meta: pooling type = 0
llm_load_print_meta: rope type = 2
llm_load_print_meta: rope scaling = linear
llm_load_print_meta: freq_base_train = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx = 32768
llm_load_print_meta: rope_finetuned = unknown
llm_load_print_meta: ssm_d_conv = 0
llm_load_print_meta: ssm_d_inner = 0
llm_load_print_meta: ssm_d_state = 0
llm_load_print_meta: ssm_dt_rank = 0
llm_load_print_meta: model type = 13B
llm_load_print_meta: model ftype = Q4_0
llm_load_print_meta: model params = 14.17 B
llm_load_print_meta: model size = 7.61 GiB (4.62 BPW)
llm_load_print_meta: general.name = Qwen1.5-14B-Chat-AWQ-fp16
llm_load_print_meta: BOS token = 151643 '<|endoftext|>'
llm_load_print_meta: EOS token = 151645 '<|im_end|>'
llm_load_print_meta: PAD token = 151643 '<|endoftext|>'
llm_load_print_meta: LF token = 30 '?'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ: no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5, VMM: yes
llm_load_tensors: ggml ctx size = 0.18 MiB
ggml_backend_cuda_register_host_buffer: warning: failed to register 7794.73 MiB of pinned memory: operation not supported
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/41 layers to GPU
llm_load_tensors: CPU buffer size = 7794.73 MiB
.........................................................................................
llama_new_context_with_model: n_ctx = 512
llama_new_context_with_model: n_batch = 512
llama_new_context_with_model: n_ubatch = 512
llama_new_context_with_model: freq_base = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: CUDA_Host KV buffer size = 400.00 MiB
llama_new_context_with_model: KV self size = 400.00 MiB, K (f16): 200.00 MiB, V (f16): 200.00 MiB
llama_new_context_with_model: CUDA_Host output buffer size = 297.00 MiB
llama_new_context_with_model: CUDA0 compute buffer size = 1000.45 MiB
llama_new_context_with_model: CUDA_Host compute buffer size = 21.00 MiB
llama_new_context_with_model: graph nodes = 1444
llama_new_context_with_model: graph splits = 564

system_info: n_threads = 12 / 24 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
main: interactive mode on.
Reverse prompt: '<|im_start|>user
'
sampling:
repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature
generate: n_ctx = 512, n_batch = 2048, n_predict = 512, n_keep = 10

== Running in interactive mode. ==

Press Ctrl+C to interject at any time.
Press Return to return control to LLaMa.
To return control without starting a new line, end your input with '/'.
If you want to submit another line, end your input with ''.
system
You are a helpful assistant.
user
`

**Comment by askmyteapot** [comment]
you forgot to include -ngl xx for the number of layers to be offloaded to the gpu. 

``` 
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/41 layers to GPU 
```

That GGUF has 41 layers. From what i can tell, its just under 8GB, so you might be able to offload all 41 layers at 8192CTX

Also, i would recommend changing the -n to 8192 as that will give you 8k CTX not 0.5k CTX.

**Comment by ngbruce** [comment]
> you forgot to include -ngl xx for the number of layers to be offloaded to the gpu.
> 
> ```
> llm_load_tensors: offloading 0 repeating layers to GPU
> llm_load_tensors: offloaded 0/41 layers to GPU 
> ```
> 
> That GGUF has 41 layers. From what i can tell, its just under 8GB, so you might be able to offload all 41 layers at 8192CTX
> 
> Also, i would recommend changing the -n to 8192 as that will give you 8k CTX not 0.5k CTX.

Thank you very much, you solved the problem !
