### ISSUE TITLE
ggml-cuda.cu(11665): error: identifier "cudaHostRegisterReadOnly" is undefined

### ISSUE THREAD

**Issue by hyperbolic-c** [ggerganov/llama.cpp#6255]
# make error
when I try `make LLAMA_CUBLAS=1`, get the error info:
```
ggml-cuda.cu(11665): error: identifier "cudaHostRegisterReadOnly" is undefined

1 error detected in the compilation of "ggml-cuda.cu".
make: *** [Makefile:465: ggml-cuda.o] Error 1
```
It is so weird, I can not search any info about this.

# system info
```
Linux 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

# cuda
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

# gcc
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by slaren** [comment]
This should be supported in CUDA 11.8, we have a build with CUDA 11.7 in the CI. Are you sure that you are using CUDA 11.8 to build this? Maybe you have multiple versions installed.

**Comment by hyperbolic-c** [comment]
> This should be supported in CUDA 11.8, we have a build with CUDA 11.7 in the CI. Are you sure that you are using CUDA 11.8 to build this? Maybe you have multiple versions installed.
@slaren Thanks a lot for your answer. I have solved it by edit the CMakeLists.txt to add the cuda path manually.
