### ISSUE TITLE
How to modify the index.html.hpp page?

### ISSUE THREAD

**Issue by krecicki** [ggerganov/llama.cpp#6265]
We are trying to modify this page to skin it and change words around.

We too the index.html.hpp made it into utf-8 and converted it back to hexadecimal. We also changed out the index.html in the public folder.

No changes were made. What happened?

We also want to strip </SYS from the end of our outputs. Where do we do this?

**Comment by ngxson** [comment]
You need to run `deps.sh` script to build the html/js files into hpp file, then recompile the project to embed new hpp into output binary.

**Comment by krecicki** [comment]
I'm using version 2144 .. when I run the deps.sh file and then try to make. The make fails to do xxd?

**Comment by phymbert** [comment]
@ggerganov  @ngxson Taking into account recent issues on[ xz-utils](https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27), I very worry about this obfuscated `index.html.hpp`

**Comment by ggerganov** [comment]
Yes, I agree there is some level of concern. Isn't there a very simple solution where we just add a small test to the CI that runs `deps.sh` and confirms that the generated files match the one in the commit?

**Comment by phymbert** [comment]
Yes I will do
