### ISSUE TITLE
May I ask how to solve this problem “Failed to get embeddings from sequence pooling type is not set”

### ISSUE THREAD

**Issue by tanxu1213** [ggerganov/llama.cpp#6279]
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/6278

<div type='discussions-op-text'>

<sup>Originally posted by **tanxu1213** March 24, 2024</sup>
 raise RuntimeError("Failed to get embeddings from sequence pooling type is not set")
RuntimeError: Failed to get embeddings from sequence pooling type is not set</div>

**Comment by ngxson** [comment]
This doesn't seem to by a llama.cpp-related question, since I cannot find this error message anywhere inside the code base.

I believe that you're using a third party binding of llama.cpp. Please refer to their documentation to fix this.
