### ISSUE TITLE
Improve handling of connectivity failures when loading a model from URL

### ISSUE THREAD

**Issue by slaren** [ggerganov/llama.cpp#6288]
Any connection issues can cause the model load to fail. This can cause CI failures, for example:
https://github.com/ggerganov/llama.cpp/actions/runs/8408071538/job/23024006918#step:8:978

Possible solutions:
- Retry the operation a number of times if it fails
- Allow using the cached model if it already exists

**Comment by farbodbj** [comment]
@slaren 
I think I can take this issue, I think most of the what that should be done is placing a `while` loop with `max_attempts` on the `curl_easy_perform` function at [this line](https://github.com/ggerganov/llama.cpp/blob/e11bd856d538e44d24d8cad4b0381fba0984d162/common/common.cpp#L2536).

here's the part I'm referring for easy understanding:
```
        fprintf(stderr, "%s: downloading from %s to %s (server_etag:%s, server_last_modified:%s)...\n", __func__,
                llama_download_hide_password_in_url(url).c_str(), path.c_str(), headers.etag.c_str(), headers.last_modified.c_str());
        auto res = curl_easy_perform(curl.get());
        if (res != CURLE_OK) {
            fprintf(stderr, "%s: curl_easy_perform() failed: %s\n", __func__, curl_easy_strerror(res));
            return false;
        }
```

I would like to know your idea about my approach and if it's aligned with the whole style and guidelines of the project I will start implementing it soon.

**Comment by farbodbj** [comment]
@compilade @ggerganov  
Can someone please confirm that my approach is actually the thing needed (and fitted) here, and if not please give me the intended approach so that I can start implementing it.

**Comment by slaren** [comment]
@farbodbj Sorry, I missed the reply. I don't know enough about the curl API to tell you if your approach will work, but it looks good.

**Comment by farbodbj** [comment]
@slaren I guess it's a good idea to close this issue now
