### ISSUE TITLE
Add multimodal example

### ISSUE THREAD

**Issue by mscheong01** [ggerganov/llama.cpp#6313]
# Feature Description

Add example for multimodal capabilities

# Motivation

#5882 took out the multimodal features from the server. Given it's a highly requested feature, our plan would be to reintroduce it at some point (#6168). How about we set up a solid multimodal example elsewhere and then port it to the server example later on?

# Possible Implementation

Implementation based on the removed code from https://github.com/ggerganov/llama.cpp/pull/5882/files which had already implemented this feature in the server.cpp example, hopefully with some performance optimization.
For the example, image file could be provided via command line option.

**Comment by phymbert** [comment]
Have you read:
- #4216

This looks duplicate of:
- #6027

**Comment by mscheong01** [comment]
@phymbert Ah, I see, I guess llava-cli fits my description for `a solid multimodal example`. Thanks for pointing it out 🙇‍♂️
