### ISSUE TITLE
Incomplete instruction for https://github.com/ggerganov/llama.cpp/blob/master/README-sycl.md#intel-gpu

### ISSUE THREAD

**Issue by sungkim11** [ggerganov/llama.cpp#6318]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

When I execute the following instructions:

mkdir -p build
cd build
source /opt/intel/oneapi/setvars.sh

# For FP16:
#cmake .. -DLLAMA_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DLLAMA_SYCL_F16=ON

# Or, for FP32:
cmake .. -DLLAMA_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx

# For Nvidia GPUs
cmake .. -DLLAMA_SYCL=ON -DLLAMA_SYCL_TARGET=NVIDIA -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx

# Build example/main only
#cmake --build . --config Release --target main

# Or, build all binary
cmake --build . --config Release -v

I get the following error:

CMake Error: The source directory "/home/username" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by airMeng** [comment]
@sungkim11 sorry to make you confused, the instructions assume you are already in the root directory of llama.cpp
```shell
cd  %{PATH/TO/LLAMA.CPP}
mkdir build
cd build
source /opt/intel/oneapi/setvars.sh
cmake .. -DLLAMA_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx
```

**Comment by sungkim11** [comment]
Thank you! I am fairly competent, but there are so many steps and really confusing and contradicting documentations. Is there a Docker image?
