### ISSUE TITLE
Documentation: suggested  make for windows (w64devkit) carries Win32/CryptInject!MSR

### ISSUE THREAD

**Issue by swavkulinski** [ggerganov/llama.cpp#6329]
System Windows 11

Following instructions in README I've tried to install make from specified location
System reported Trojan:Win32/CryptInject!MSR

I suggest removing reference from documentation until issue is clarified.

**Comment by askmyteapot** [comment]
This is a false positive detection. 

Has been raised countless times on the w64devkit github.
[https://github.com/skeeto/w64devkit/issues/119](here)
[https://github.com/skeeto/w64devkit/issues/85](more_here)
[https://github.com/skeeto/w64devkit/issues/93](even_more_here)
