### ISSUE TITLE
Working Fine-Tune Example?

### ISSUE THREAD

**Issue by pacozaa** [ggerganov/llama.cpp#6361]
I am trying to find a working example of fine-tuning. 

- If I run the example from `https://github.com/ggerganov/llama.cpp/tree/master/examples/finetune`, the script can't find the model.
here is the error
```
main: seed: 1711608198
main: model base = 'open-llama-3b-v2-q8_0.gguf'
llama_model_load: error loading model: llama_model_loader: failed to load model from open-llama-3b-v2-q8_0.gguf

llama_load_model_from_file: failed to load model
llama_new_context_with_model: model cannot be NULL
Segmentation fault: 11
```

- If I try to use a model in `/models` folder such as 
```
./finetune \
        --model-base ./models/ggml-vocab-llama.gguf \
        --checkpoint-in  chk-lora-open-llama-3b-v2-q8_0-shakespeare-LATEST.gguf \
        --checkpoint-out chk-lora-open-llama-3b-v2-q8_0-shakespeare-ITERATION.gguf \
        --lora-out lora-open-llama-3b-v2-q8_0-shakespeare-ITERATION.bin \
        --train-data "shakespeare.txt" \
        --save-every 10 \
        --threads 6 --adam-iter 30 --batch 4 --ctx 64 \
        --use-checkpointing
```

It returns error still
```
...
llm_load_tensors: ggml ctx size =    0.00 MiB
llama_model_load: error loading model: create_tensor: tensor 'token_embd.weight' not found
llama_load_model_from_file: failed to load model
llama_new_context_with_model: model cannot be NULL
WARNING: Behavior may be unexpected when allocating 0 bytes for ggml_malloc!
Segmentation fault: 11
```

What should I do?

**Comment by gmdl007** [comment]
yeh, i also like to know what does the shakespeare.txt do as training data, it is kind of unexplained how this training text is fine tuning the model

**Comment by teleprint-me** [comment]
It's actually really straightforward. You just need to format the content to a plaintext file, have a vocab available, and then run the examples. That's how I got started. I've been working on some micro models ever since. Planning on a 30M param, a 50M param, and a 100M param at some point. I'm not ready to post yet though. I only posted an initial demo which I intentionally overfit.

**Comment by gmdl007** [comment]
wow, thanks for sharing that. I always thought the fine tuning data need to be in specific form, like  this:

def create_prompt(sample):
  bos_token = "<s>"
  original_system_message = "Below is an instruction that describes a task. Write a response that appropriately completes the request."
  system_message = "Use the provided input to create an instruction that could have been used to generate the response with an LLM."
  response = sample["prompt"].replace(original_system_message, "").replace("\n\n### Instruction\n", "").replace("\n### Response\n", "").strip()
  input = sample["response"]
  eos_token = "</s>"

  full_prompt = ""
  full_prompt += bos_token
  full_prompt += "### Instruction:"
  full_prompt += "\n" + system_message
  full_prompt += "\n\n### Input:"
  full_prompt += "\n" + input
  full_prompt += "\n\n### Response:"
  full_prompt += "\n" + response
  full_prompt += eos_token

  return full_prompt


are you saying you need the plain text data without any json like format to fine tuning? So the model just need the sequences to get the attentions to build up?

BR
Guan

**Comment by gmdl007** [comment]
i checked here:
https://github.com/YuanTony/chemistry-assistant/tree/main/fine-tune-model

it gave good example for finetuning a llama.cpp example, fantastic.... much easier than any of the tutorials i followed. Now i have created the txt file using simple python scripts, off i go, training!!!
