### ISSUE TITLE
Support for 2-bit Quantized Llama-2-7b-chat-hf_2bitgs8_hqq Model

### ISSUE THREAD

**Issue by timuryung** [ggerganov/llama.cpp#6368]
I would like to propose the integration of a novel model, "Llama-2-7b-chat-hf_2bitgs8_hqq," available on Hugging Face. This model represents an innovative approach to quantization, employing a 2-bit quantized version of Llama2-7B-chat, enhanced with a low-rank adapter (HQQ+), to improve performance and efficiency.

Key Features:
- **Quantization**: The model leverages 2-bit quantization, significantly reducing VRAM requirements.
- **Low-Rank Adapter**: Utilizes HQQ+, a low-rank adapter for performance enhancement.
- **Efficiency**: Offloads meta-data to CPU, optimizing GPU memory usage.
- **Datasets**: Trained on a mixture of general and specialized datasets, showing robustness and versatility.

The inclusion of this model could greatly benefit llama.cpp users by offering a more memory-efficient yet powerful option for large-scale text generation tasks. It could especially be beneficial for environments with limited hardware resources.

Thank you for considering this addition.

[Link to the model on Hugging Face](https://huggingface.co/mobiuslabsgmbh/Llama-2-7b-chat-hf_2bitgs8_hqq)

**Comment by sorasoras** [comment]
Are these the finetune enhanced quants? I think this is a good approach before 1.58bit LLM oomes.

**Comment by sorasoras** [comment]
@ggerganov  I think support this type of model should be pretty straight forward. What do you think？

**Comment by josharian** [comment]
Same as https://github.com/ggerganov/llama.cpp/issues/4782?

**Comment by charlesrwest** [comment]
I would really like support for HQQ and HQQ+ models. I would be happy to pay a $100 bounty.
