### ISSUE TITLE
Is it possible to dynamically switch multiple LoRA adapters?

### ISSUE THREAD

**Issue by nai-kon** [ggerganov/llama.cpp#6377]
Thank you for this great project. I have two questions.

# Q1 Is it possible to dynamically switch multiple LoRA adapters?

In the transformers library, we can load multiple adapters to the original model by `load_adapter` then switch the specified adapter with `set_adapter` instantlly like below.

```python
# base model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
)

# load multiple adapters
model.load_adapter("model/adapter1/", "adapter1")
model.load_adapter("model/adapter2/", "adapter2")

# switch adapter (change takes instantly)
model.set_adapter("adapter2")
```

Is it possible to do the same thing with llama cpp?
I found there is an API `llama_model_apply_lora_from_file()` .
https://github.com/ggerganov/llama.cpp/blob/bfe7dafc9cf96b9a09ead347fed9a547930fc631/llama.h#L441

But the description says `The model needs to be reloaded before applying a new adapter, otherwise the adapter will be applied on top of the previous one`.

Is it impossible to switch instantly without reloading the model like transformers?

# Q2. The model loading with LoRA is extremely slow

A 13b model without LoRA takes 2 seconds to model loading.
`./main -m ../gguf_model/llm-jp-13b-ggml-model-f16.gguf`

However with LoRA takes over 60sec.
`./main -m ../gguf_model/llm-jp-13b-v1.0-q4_0.gguf --lora ../gguf_model/llm-jp-adapter-model.bin`

I know that with LoRA option disables mmap, but is this normal? Is there some way to speed it up?
I think the way is to merge the model and LoRA firstly then convert it to gguf, but I would like to dynamically switch the LoRA adapter.

Thank you.

**Comment by sorasoras** [comment]
https://github.com/ggerganov/llama.cpp/issues/6097
Kind of similar to this one
it use Lora adapter as expert.

**Comment by slaren** [comment]
It is not possible to switch loras dynamically. Loras are merged into the model, which is why they are so slow to load, and why they require disabling mmap (they modify the model, so it needs a copy). Most people use pre-merged models, so this feature has not received much attention.

**Comment by nai-kon** [comment]
Thank you for your detailed explanation. I understand that dynamic switching is difficult currently.

**Comment by cheney369** [comment]
@nai-kon VLLM can do it
