### ISSUE TITLE
off topic: linking two Mac Studio together to fit larger models

### ISSUE THREAD

**Issue by gileneusz** [ggerganov/llama.cpp#6390]
Hi, I just came across an idea of linking two Mac Studio 192GB with Thunderbolt bridge to fit larger models. Has anyone tried this before? Would it be even possible and would Thunderbolt bridge speed be a bottleneck in this case?

**Comment by netrunnereve** [comment]
Have you tried setting up MPI? Since the Thunderbolt Bridge is treated as an IP connection it may work.

**Comment by gileneusz** [comment]
I haven't tried this connection myself; I'm merely suggesting an idea that could be tested with any pair of Macs equipped with a Thunderbolt port. This would allow for an assessment of the throughput and latency (T/S) output, which could then be used to predict the performance when connecting machines with 192+192 GB of RAM. However, I'm not deeply versed in programming to implement this myself; I'm just putting the idea forward.

**Comment by izard** [comment]
I checked that a while ago with 2x 128GB Mac Studios over direct 10GB link. Everything worked with llama.cpp/MPI, and performance was reasonable, both systems were memory throughput limited at 1-batch, so 10GB NIC throughput was enough.

**Comment by nachoal** [comment]
This idea is starting to gain traction in the twitter world, see [this tweet](https://x.com/elegyals/status/1783942625147376027), @izard could you share a tutorial on how to set it up?

**Comment by netrunnereve** [comment]
If you're using regular Ethernet it should work with the standard MPI setup. Did you try the tutorial in the README?
