### ISSUE TITLE
The `quantize.py` script is not needed anymore. Just fetch the latest code and do this as a quantization step:

### ISSUE THREAD

**Issue by huangzhimin4read** [ggerganov/llama.cpp#641]
The `quantize.py` script is not needed anymore. Just fetch the latest code and do this as a quantization step:

```
./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin 2
```

_Originally posted by @prusnak in https://github.com/ggerganov/llama.cpp/issues/621#issuecomment-1491088418_

I tried this method in Colab, but it still reports an error:
/bin/bash: ./quantize: No such file or directory

**Comment by CoderRC** [comment]
You have to compile the library first. Try: https://github.com/ggerganov/llama.cpp/issues/103#issuecomment-1487784446

**Comment by prusnak** [comment]
Follow the instructions in the README file which tells you to compile the things first using make

**Comment by montvid** [comment]
I used cmake to build and have to write the path to quantize:
`./build/bin/quantize models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_1.bin q4_1`

**Comment by xxxwp123** [comment]
> ```
>           The `quantize.py` script is not needed anymore. Just fetch the latest code and do this as a quantization step:
> ```
> 
> ```
> ./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin 2
> ```
> 
> _Originally posted by @prusnak in [#621 (comment)](https://github.com/ggerganov/llama.cpp/issues/621#issuecomment-1491088418)_
> 
> I tried this method in Colab, but it still reports an error: /bin/bash: ./quantize: No such file or directory

Have you solved this problem?I have the same problem.thanks
