### ISSUE TITLE
Are Qwen1.5 MOE models supported?

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#6415]
I tried to convert the Qwen 1.5 MOE: https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B

It gives me an error message:
```
 python convert-hf-to-gguf.py /home/layla/src/text-generation-webui/models/Qwen1.5-MoE-A2.7B
Loading model: Qwen1.5-MoE-A2.7B
Traceback (most recent call last):
  File "/home/layla/src/llama.cpp/convert-hf-to-gguf.py", line 2296, in <module>
    main()
  File "/home/layla/src/llama.cpp/convert-hf-to-gguf.py", line 2276, in main
    model_class = Model.from_model_architecture(hparams["architectures"][0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/layla/src/llama.cpp/convert-hf-to-gguf.py", line 215, in from_model_architecture
    raise NotImplementedError(f'Architecture {arch!r} not supported!') from None
NotImplementedError: Architecture 'Qwen2MoeForCausalLM' not supported!
```

I see others have uploaded GGUFs of the Qwen MOE models on HF, so it leads me to think I'm doing something wrong

**Comment by l3utterfly** [comment]
I see this issue: https://github.com/huggingface/transformers/pull/29377

Which adds support to Qwen2, do I need that PR to convert Qwen1.5 moe?

**Comment by gswsqffsapd3056** [comment]
Same needs, waiting to be solved

**Comment by Jeximo** [comment]
I see there's only 2 people making Qwen MOE 1.5 GGUFs on Huggingface(). `llama.cpp` [shows support for Qwen](https://github.com/ggerganov/llama.cpp#description), but doesn't specify Qwen Moe(*yet*).

[Here's a PR discussing converting/running it](https://github.com/ggerganov/llama.cpp/pull/6074#issuecomment-2028092431), though it appears there's more [work to be done](https://github.com/ggerganov/llama.cpp/pull/6387) before it'll run.

**Comment by Lyzin** [comment]
I don't know when qwen1.5-MoE will support llama.cpp, I can only wait for qwen official update!

**Comment by maziyarpanahi** [comment]
Speaking of MoE and Qwen, https://github.com/ggerganov/llama.cpp/pull/6453
