### ISSUE TITLE
Mixtral on Windows big performance drop compared to Linux

### ISSUE THREAD

**Issue by Dampfinchen** [ggerganov/llama.cpp#6442]
Now, I'm aware Linux is more efficient in terms of AI performance, but I really don't believe a variance of this kind is normal. 

I measured the following performance on identical settings (Q4_K_S, Mixtral, 32 GB, RTX 2060, i7 9750H, 5 layers offloaded, batch of 1024)

Windows 11 64 Bit: 11.6 ms/t prompt processing of 3700 Tokens, 318 ms/t text generation of 180 tokens
Linux: 8.8 ms/t prompt processing of 3700 Tokens, 239 ms/t text generation of 180 tokens

As you can see, Windows almost adds 100 ms/t to the generation time. 

Funnily enough, CUDA is not to blame for this. I was measuring fully offloaded 7B speeds and they were pretty much identical between Windows and Linux. For a Solar 10.7B model, which I am able to offload 39 layers, it's slower but not by a lot. 

So it seems to me there is an inefficency in the AVX2 CPU generation code on Windows.

**Comment by ggerganov** [comment]
> So it seems to me there is an inefficency in the AVX2 CPU generation code on Windows.

Can you confirm that AVX2 flags are used during build?

**Comment by Dampfinchen** [comment]
> > So it seems to me there is an inefficency in the AVX2 CPU generation code on Windows.
> 
> Can you confirm that AVX2 flags are used during build?

Hi, GGerganov!

Yes, indeed. Just to double check I've compiled a new build again. The results are the same.

```
llama_print_timings:        load time =   53408.65 ms
llama_print_timings:      sample time =       6.67 ms /   180 runs   (    0.04 ms per token, 26990.55 tokens per second)
llama_print_timings: prompt eval time =   41258.56 ms /  3569 tokens (   11.56 ms per token,    86.50 tokens per second)
llama_print_timings:        eval time =   58111.21 ms /   179 runs   (  324.64 ms per token,     3.08 tokens per second)
llama_print_timings:       total time =   99489.74 ms /  3748 tokens
```
`system_info: n_threads = 6 / 12 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |`

**Comment by Dampfinchen** [comment]
My first thought was disk swapping, as I've heard Linux is lighter on RAM than Windows. However, this doesn't seem to be the case. With the --no-mmap command, my RAM usage is around 27 GB and both Linux and Windows were using around 3 GB in idle.

![Screenshot 2024-04-03 150606](https://github.com/ggerganov/llama.cpp/assets/59751859/b24c2686-0310-4f33-a6be-6a33a8fb39ca)

What is strange though is that I'm getting a pinned out of memory error when allocating CPU memory IF I'm using no-mmap. With mmap that doesn't happen, but memory usage is of course higher then.

On Linux, I was not getting pinned CPU out of memory errors for each mode, regardless if mmap or not.
`
ggml_cuda_host_malloc: warning: failed to allocate 21580.90 MiB of pinned memory: out of memory`

I'm also not seeing why 21 GB could not be succesful, as I've demonstrated earlier I have plenty of RAM to spare.

**Comment by ggerganov** [comment]
Hm, not sure. Hopefully someone else will have some ideas

**Comment by Wuzzooy** [comment]
I've tested full cpu with a 9700k + 64 gb of ram @ 3200mhz on the last build on cashyOS and windows 10
Windows result :
llama_print_timings:        load time =   20296.54 ms
llama_print_timings:      sample time =     182.83 ms /  1024 runs   (    0.18 ms per token,  5600.71 tokens per second)
llama_print_timings: prompt eval time =   69567.21 ms /   481 tokens (  144.63 ms per token,     6.91 tokens per second)
llama_print_timings:        eval time =  288376.79 ms /  1023 runs   (  281.89 ms per token,     3.55 tokens per second)
llama_print_timings:       total time =  358375.38 ms /  1504 tokens

CashyOS
llama_print_timings:        load time =   10735,80 ms
llama_print_timings:      sample time =     331,66 ms /  1024 runs   (    0,32 ms per token,  3087,48 tokens per second)
llama_print_timings: prompt eval time =   59727,89 ms /   479 tokens (  124,69 ms per token,     8,02 tokens per second)
llama_print_timings:        eval time =  293013,14 ms /  1023 runs   (  286,43 ms per token,     3,49 tokens per second)
llama_print_timings:       total time =  353252,34 ms /  1502 tokens

**Comment by Dampfinchen** [comment]
> I've tested full cpu with a 9700k + 64 gb of ram @ 3200mhz on the last build on cashyOS and windows 10 with mixtral q5_k_m Windows result : llama_print_timings: load time = 20296.54 ms llama_print_timings: sample time = 182.83 ms / 1024 runs ( 0.18 ms per token, 5600.71 tokens per second) llama_print_timings: prompt eval time = 69567.21 ms / 481 tokens ( 144.63 ms per token, 6.91 tokens per second) llama_print_timings: eval time = 288376.79 ms / 1023 runs ( 281.89 ms per token, 3.55 tokens per second) llama_print_timings: total time = 358375.38 ms / 1504 tokens
> 
> CashyOS llama_print_timings: load time = 10735,80 ms llama_print_timings: sample time = 331,66 ms / 1024 runs ( 0,32 ms per token, 3087,48 tokens per second) llama_print_timings: prompt eval time = 59727,89 ms / 479 tokens ( 124,69 ms per token, 8,02 tokens per second) llama_print_timings: eval time = 293013,14 ms / 1023 runs ( 286,43 ms per token, 3,49 tokens per second) llama_print_timings: total time = 353252,34 ms / 1502 tokens

Do you have the means of testing it with partial CUDA offloading as well, in a similar high CPU depenend scenario as I'm demonstrating?

**Comment by Wuzzooy** [comment]
> > I've tested full cpu with a 9700k + 64 gb of ram @ 3200mhz on the last build on cashyOS and windows 10 with mixtral q5_k_m Windows result : llama_print_timings: load time = 20296.54 ms llama_print_timings: sample time = 182.83 ms / 1024 runs ( 0.18 ms per token, 5600.71 tokens per second) llama_print_timings: prompt eval time = 69567.21 ms / 481 tokens ( 144.63 ms per token, 6.91 tokens per second) llama_print_timings: eval time = 288376.79 ms / 1023 runs ( 281.89 ms per token, 3.55 tokens per second) llama_print_timings: total time = 358375.38 ms / 1504 tokens
> > CashyOS llama_print_timings: load time = 10735,80 ms llama_print_timings: sample time = 331,66 ms / 1024 runs ( 0,32 ms per token, 3087,48 tokens per second) llama_print_timings: prompt eval time = 59727,89 ms / 479 tokens ( 124,69 ms per token, 8,02 tokens per second) llama_print_timings: eval time = 293013,14 ms / 1023 runs ( 286,43 ms per token, 3,49 tokens per second) llama_print_timings: total time = 353252,34 ms / 1502 tokens
> 
> Do you have the means of testing it with partial CUDA offloading as well, in a similar high CPU depenend scenario as I'm demonstrating?

Yes sorry, i tested just on cpu because you were guessing that there was an avx 2 issue on windows.
Interesting, i have worse results when offloading 5 layers on windows.
Windows
llama_print_timings:        load time =   23039.48 ms
llama_print_timings:      sample time =     197.96 ms /  1024 runs   (    0.19 ms per token,  5172.87 tokens per second)
llama_print_timings: prompt eval time =    6382.48 ms /   481 tokens (   13.27 ms per token,    75.36 tokens per second)
llama_print_timings:        eval time =  315911.31 ms /  1023 runs   (  308.81 ms per token,     3.24 tokens per second)
llama_print_timings:       total time =  322742.91 ms /  1504 tokens

CachyOS
llama_print_timings:        load time =   11241,62 ms
llama_print_timings:      sample time =     332,34 ms /  1024 runs   (    0,32 ms per token,  3081,21 tokens per second)
llama_print_timings: prompt eval time =    5525,80 ms /   479 tokens (   11,54 ms per token,    86,68 tokens per second)
llama_print_timings:        eval time =  246374,26 ms /  1023 runs   (  240,84 ms per token,     4,15 tokens per second)
llama_print_timings:       total time =  252413,30 ms /  1502 tokens

**Comment by Dampfinchen** [comment]
> > Do you have the means of testing it with partial CUDA offloading as well, in a similar high CPU depenend scenario as I'm demonstrating?
> 
> Yes sorry, i tested just on cpu because you were guessing that there was an avx 2 issue on windows. Interesting, i have worse results when offloading 5 layers on windows. Windows
> 
> ```
> llama_print_timings:        load time =   23039.48 ms
> llama_print_timings:      sample time =     197.96 ms /  1024 runs   (    0.19 ms per token,  5172.87 tokens per second)
> llama_print_timings: prompt eval time =    6382.48 ms /   481 tokens (   13.27 ms per token,    75.36 tokens per second)
> llama_print_timings:        eval time =  315911.31 ms /  1023 runs   (  308.81 ms per token,     3.24 tokens per second)
> llama_print_timings:       total time =  322742.91 ms /  1504 tokens
> ```
> 
> CachyOS
> 
> ```
> llama_print_timings:        load time =   11241,62 ms
> llama_print_timings:      sample time =     332,34 ms /  1024 runs   (    0,32 ms per token,  3081,21 tokens per second)
> llama_print_timings: prompt eval time =    5525,80 ms /   479 tokens (   11,54 ms per token,    86,68 tokens per second)
> llama_print_timings:        eval time =  246374,26 ms /  1023 runs   (  240,84 ms per token,     4,15 tokens per second)
> llama_print_timings:       total time =  252413,30 ms /  1502 tokens
> ```

Thank you for the tests.

Looks like you can replicate the issue on your system as well. Interesting that it only happens with partial CPU offload. I've compared CPU only (no BLAS as well) on Linux vs Windows, and while Linux is a little faster the difference is nothing to write home about, similar to your results.

`llama_print_timings:        load time =  435211.48 ms
llama_print_timings:      sample time =       7.96 ms /   180 runs   (    0.04 ms per token, 22618.75 tokens per second)
llama_print_timings: prompt eval time =  484928.75 ms /  3602 tokens (  134.63 ms per token,     7.43 tokens per second)
llama_print_timings:        eval time =   53382.66 ms /   179 runs   (  298.23 ms per token,     3.35 tokens per second)
llama_print_timings:       total time =  539461.52 ms /  3781 tokens
`
```
llama_print_timings:        load time =  424043.57 ms
llama_print_timings:      sample time =       6.08 ms /   180 runs   (    0.03 ms per token, 29619.88 tokens per second)
llama_print_timings: prompt eval time =  385746.26 ms /  3569 tokens (  108.08 ms per token,     9.25 tokens per second)
llama_print_timings:        eval time =   55672.42 ms /   179 runs   (  311.02 ms per token,     3.22 tokens per second)
llama_print_timings:       total time =  441536.17 ms /  3748 tokens
```

So yeah, looks like the issue arises when using partial offloading and the less layers you offload, the slower Windows gets versus Linux.

@slaren @JohannesGaessler You guys have any idea what could be the big discrepancy between Windows and Linux here? Note that the performance between Windows and Linux is the same when using full GPU offload.

**Comment by JohannesGaessler** [comment]
The CUDA libraries on Windows are just garbage. I don't know whether it's the fault of Microsoft or NVIDIA but there are calls like `cudaSetDevice` that should be very fast if you repeatedly set the same device but for whatever reason they're extremely slow on Windows. For that particular call there is a workaround but there may be some other call that is causing issues.

**Comment by Dampfinchen** [comment]
> The CUDA libraries on Windows are just garbage. I don't know whether it's the fault of Microsoft or NVIDIA but there are calls like `cudaSetDevice` that should be very fast if you repeatedly set the same device but for whatever reason they're extremely slow on Windows. For that particular call there is a workaround but there may be some other call that is causing issues.

Yes, I was thinking the CUDA libraries might be at fault too. But the thing is, I've measured the performance of full GPU offloading between Windows and Linux and the performance is identical. If the CUDA libs are that bad, why is full GPU offloading working as well as it does on Linux? It seems pretty strange to me.

**Comment by 0cc4m** [comment]
> > The CUDA libraries on Windows are just garbage. I don't know whether it's the fault of Microsoft or NVIDIA but there are calls like `cudaSetDevice` that should be very fast if you repeatedly set the same device but for whatever reason they're extremely slow on Windows. For that particular call there is a workaround but there may be some other call that is causing issues.
> 
> Yes, I was thinking the CUDA libraries might be at fault too. But the thing is, I've measured the performance of full GPU offloading between Windows and Linux and the performance is identical. If the CUDA libs are that bad, why is full GPU offloading on Windows working as well as it does on Linux? It seems pretty strange to me.

That could be because partial offload does different operations compared to full offload, for example a lot of transfers between CPU and GPU. Maybe some of these calls are slower, like maybe is a difference with memory pinning between Linux and Windows?

**Comment by Dampfinchen** [comment]
> The number and types of calls to CUDA libraries is very likely different between partial and full GPU offload. Or it could be an interplay between multiple threads and the CUDA libraries. You could test this by comparing performance with a single thread.

Yup, you are right. I've compared Koboldcpp 1.61.2 (it has prebuilt cuda binaries which is convenient for me). Text generation speed is very similar between the two when using just 1 CPU thread. 

```
Processing Prompt [BLAS] (3602 / 3602 tokens)
Generating (180 / 180 tokens)
CtxLimit: 3782/4096, Process:121.07s (33.6ms/T = 29.75T/s), Generate:132.05s (733.6ms/T = 1.36T/s), Total:253.12s (0.71T/s)
```
```
Processing Prompt [BLAS] (3602 / 3602 tokens)
Generating (180 / 180 tokens)
CtxLimit: 3782/4096, Process:96.88s (26.9ms/T = 37.18T/s), Generate:131.30s (729.5ms/T = 1.37T/s), Total:228.19s (0.79T/s)
```
So atleast for text generation the Windows slowdown really appears to be connected to the amount of threads.

**Comment by slaren** [comment]
Windows has a larger overhead for launching threads, so that may be the difference. When running with 1 thread, ggml does not create additional threads (the main thread is reused instead).

**Comment by Panchovix** [comment]
Sorry to hijack an old thread, but I can replicate this. I get ~3.3 t/s on Windows/WSL vs ~5t/s on Linux (Fedora), when running Llama-3_1-Nemotron-Ultra-253B-v1-UD-Q3_K_XL with 160 layers on GPU, and 3 on CPU.

I guess there is no solution, besides using Linux, right?
