### ISSUE TITLE
feat: configurable n_ubatch in Batched benchmark

### ISSUE THREAD

**Issue by Sunt-ing** [ggerganov/llama.cpp#6460]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Currently, the batched benchmark does not support configurable n_ubatch. Supporting the parameter is not hard but useful. 

# Motivation

Please provide a detailed written description of reasons why this feature is necessary and how it is useful to `llama.cpp` users.

n_ubatch can be important for a batched benchmark. 

# Possible Implementation

Directly make it configurable in the benchmark.

**Comment by Sunt-ing** [comment]
Also, is the hard-coded n_batch reasonable?

https://github.com/ggerganov/llama.cpp/blob/db214fa578e00b01e0884fc2725c9349608bdab5/examples/batched-bench/batched-bench.cpp#L103C1-L103C32


>     ctx_params.seed      = 1234;
>     ctx_params.n_ctx     = n_kv_max;
>     ctx_params.n_batch   = 512;

**Comment by ggerganov** [comment]
It's reasonable, but depending on your hardware, it might not be optimal

**Comment by Sunt-ing** [comment]
@ggerganov Thanks for your reply! IMHO we may make n_batch and n_ubatch configurable but with default values 2048 and 512.
