### ISSUE TITLE
Add support for OPTForCausalLM

### ISSUE THREAD

**Issue by varunlmxd** [ggerganov/llama.cpp#6473]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
I want to quantize OPT based models like Galactica in ggml format. Please add support to OPT architecture models.

**Comment by henk717** [comment]
This would be nice, OPT was around for a while and while not as good as Llama it would be fun to be able to use this models again in Llamacpp powered applications.

**Comment by WissamAntoun** [comment]
This will should also enable support for the GALACTICA models. It would highly be appreciated.

**Comment by bobzhang208** [comment]
can opt model be supported?

**Comment by SicariusSicariiStuff** [comment]
opt is dead? or is there hope?
