### ISSUE TITLE
gpt4all keeps on ending responses abruptly

### ISSUE THREAD

**Issue by niansa** [ggerganov/llama.cpp#648]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The GPT4All model should give proper and complete responses

# Current Behavior

Longer responses get truncated:
```
> Please write a letter to my boss explaining that I keep on arriving late at work because my alarm clock is defective.
Dear Boss,

I am sorry to inform you that I have been arriving late to work due to a defective alarm clock. I have tried multiple times to fix it, but it seems to
>
``` 

# Environment and Context 

Reproducible on all my x86 machines on both Windows and Linux.

Here's the command I've used to start the interactive mode:

```
./main -m ./gpt4all-lora-unfiltered-quantized-new.bin --color -f ./prompts/alpaca.txt -ins -b 25
6 --top_k 10000 --temp 0.2 --repeat_penalty 1 -t 7
```

# Failure Information (for bugs)

It seems to be happening mostly randomly, but always with longer responses.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Compile llama.cpp as usual (on x86)
2. Get the gpt4all weight file (any, either normal or unfiltered one)
3. Convert it using `convert-gpt4all-to-ggml.py` and `migrate-ggml-2023-03-30-pr613.py`
4. Run it using the command above
5. Tell it to write something long (see example)

# Failure Logs

```
llama_model_load: loading model from './gpt4all-lora-unfiltered-quantized-new.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 1026.00 MB per state)
llama_model_load: loading tensors from './gpt4all-lora-unfiltered-quantized-new.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  256.00 MB

system_info: n_threads = 7 / 12 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: temp = 0.200000, top_k = 10000, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.000000
generate: n_ctx = 512, n_batch = 256, n_predict = 128, n_keep = 21


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - If you want to submit another line, end your input in '\'.
```

**Comment by anzz1** [comment]
Check the release one before latest one : https://github.com/ggerganov/llama.cpp/releases/tag/master-ed3c680
That one should work. The latest version was rushed without proper testing.

**Comment by niansa** [comment]
> Check the release one before latest one : https://github.com/ggerganov/llama.cpp/releases/tag/master-ed3c680 That one should work. The latest version was rushed without proper testing.

It doesn't seem to make too much of a difference :thinking:

**Comment by leonardohn** [comment]
@niansa Try increasing the `n_predict` parameter, that worked for me.

**Comment by ggerganov** [comment]
Correct - most likely `n_predict` has to be increased

**Comment by niansa** [comment]
> Correct - most likely `n_predict` has to be increased

It seems like that sometimes works, I've made a PR updating the examples, however a lot of the time it doesn't.
