### ISSUE TITLE
Models with multiple chat templates

### ISSUE THREAD

**Issue by Rocketknight1** [ggerganov/llama.cpp#6484]
Hi all, Matt from Hugging Face here. Just to let you know, we've made a modification to chat templates. As of Transformers v4.39, the **tokenizer chat template field can now be a list containing multiple named templates**. For compatibility reasons, the dict is converted to a list of `{"name": "...", "template": "..."}` dicts for serialization in `tokenizer_config.json`, but we convert it to a single `dict` when we load it in the tokenizer itself.

We did this to support Command-R and Command-R+, as they used separate templates for general LLM use, tool-assisted generation, and RAG. Right now, this is hardcoded in the tokenization.py file for Command-R, but we will be moving it into the model repos itself very soon - a repo PR is already open [here](https://huggingface.co/CohereForAI/c4ai-command-r-v01/discussions/46/files), and we'll probably open one for Command-R+ too.

You can see how we're handling this [here](https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L1750), but tl;dr if there are multiple templates, the user can request a template by name. If they don't request a name, then we use the one with the name `"default"` if that exists, or else we throw an error if there is no `"default"` template.

I'm not sure how exactly the chat template is copied into GGUF files, but the conversion script might need a small update to make sure it can handle this!

**Comment by slaren** [comment]
Thanks for the heads up. If anyone wants to look into this, this is the code that would need to be updated:
https://github.com/ggerganov/llama.cpp/blob/c666ba26c39d5c07e07b4e1e411332f408e309ad/gguf-py/gguf/vocab.py#L138-L146
For now, we should export the `default` template, and then we can look into how to extend the metadata to be able to export all the templates.
