### ISSUE TITLE
iostream error while quantizing models

### ISSUE THREAD

**Issue by munish0838** [ggerganov/llama.cpp#6493]
llama_model_quantize: failed to quantize: basic_ios::clear: iostream error
main: failed to quantize model from 'models/ggml-model-f16.gguf'
I am downloading model weights and converting it to f16.gguf
After running around 229/291 layers,I get this error and the model does not quantise completely
Facing issue since yesterday

**Comment by T1bolus** [comment]
The same behavior for me. 
I used convert.py to convert a LLama 13B model finetuned with unsloth into f16 .gguf. Then when quantizing to Q4_K_M:

```
[...]
llama_model_loader: - kv  24:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type  f16:  282 tensors
llama_model_quantize: failed to quantize: basic_ios::clear: iostream error
main: failed to quantize model from 'xxx/model-f16.gguf'
```

**Comment by MohamedAliRashad** [comment]
@T1bolus  @Tianzhengshuyuan @munish0838 
I have good disk size and the error is still present

**Comment by gloritygithub11** [comment]
I fixed it by creating the output dir before execute the quantize.

**Comment by yuncengshangdepingyuan** [comment]
I'm forget to creating output dir

**Comment by ZakariaSakab** [comment]
Make sure the folder in which the output quantized model shall be written is created.

**Comment by dt-cs** [comment]
Creating folder worked! Thanks
