### ISSUE TITLE
Possible to reduce vector dimensionality for embeddings?

### ISSUE THREAD

**Issue by PaulCapestany** [ggerganov/llama.cpp#6494]
# Prerequisites

- [✔] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [✔] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [✔] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [✔] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I am interested in generating embeddings (especially from multimodal models) for vector similarity search purposes (with constraints on the generated vector dimensions needing to be ≤ 2048), and was wondering if that's something that `llama.cpp` is capable of doing via flags/args currently and I somehow missed it, or if it'd be possible/make sense to implement in the future?

# Motivation

Multimodal models (such as llava 1.6) seem very useful for generating embeddings with mixed media (i.e. not just text, but also images, etc). However, multimodal models seem to have especially large dimensionality (e.g. llava 1.6 is 7168 in size). Having the ability to use powerful multimodal models that generate reduced dimension embeddings would be great for vector similarity search purposes.

**Comment by HanClinto** [comment]
Do you have a particular dimensionality reduction algorithm in mind?

**Comment by PaulCapestany** [comment]
> Do you have a particular dimensionality reduction algorithm in mind?

Well, I'm pretty new to ML, so short answer would be "not yet" 😅

I'm aware of PCA/tSNE/UMAP/PaCMAP, but, those wouldn't be useful(?) afaict for this scenario where we'd be independently generating a reduced dimension embedding based off a sample size of 1.

The [Matryoshka](https://blog.nomic.ai/posts/nomic-embed-matryoshka) approach for reducing vector size looks interesting, however, it seems to come into play further upstream during actual training, which afaict llama.cpp isn't really involved with...

Ideally there'd be a way to lower dimensionality of embeddings given any arbitrary model's output, but I've yet to come across how one might go about doing that

**Comment by HanClinto** [comment]
Very reasonable!

One thing you might try is to take the vectors that you generate with an LLM, and then experiment with dimensionality-reduction yourself before putting them into your vector database. I.E., always generate full vectors, and then do dimensionality-reduction afterwards.

Another option is to start with a model that is specifically trained for a smaller embedding size. Personally I really like the MTEB benchmark, and it helpfully includes the vector size along with the size, speed, and score of each model:

https://huggingface.co/spaces/mteb/leaderboard

Not sure how new you are to vector text embeddings overall, but I've personally had good success with both [Instructor-Large](https://huggingface.co/hkunlp/instructor-large) and particularly [bge-small-en-1.5](https://huggingface.co/BAAI/bge-small-en-v1.5) -- on the leaderboard, bge-small is the best-performing model with a dimension size of 384 -- crazy small. It outperforms some models that are an order of magnitude larger.

I haven't ever run those models with llama.cpp -- I just use the regular Pytorch wrappers for those -- but even on a relatively weak CPU both of those generally operate just fine. bge-small is tiny enough that I can [fine tune it for my needs](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune) very quickly -- 5 or 6 hours on my laptop, or about 30 minutes on a 3090 GPU. I've tried to fine-tune a handful of models before, and never found anything with as easy-to-use tooling as BGE.

Anyways, sorry for not directly answering the question that you were asking, but if you're looking to local generation of more reasonably-sized text embeddings, then bge-small is where I would recommend starting. Don't get me wrong -- you could still get good results with dimensionality reduction, but my (un-sourced) guess is that the performance of a model that is tuned to output at a smaller embedding size is likely to give you better performance than crushing down the vector size of a model that wasn't trained to target it.

**Comment by jukofyork** [comment]
> > Do you have a particular dimensionality reduction algorithm in mind?
> 
> Well, I'm pretty new to ML, so short answer would be "not yet" 😅
> 
> I'm aware of PCA/tSNE/UMAP/PaCMAP, but, those wouldn't be useful(?) afaict for this scenario where we'd be independently generating a reduced dimension embedding based off a sample size of 1.

Look into Random Projection or Random Mapping.

Basically you generate a n×m matrix of random values (usually with certain properties) and do a matrix multiplication to project from the higher dimensional space to the lower dimensional space.

**Comment by PaulCapestany** [comment]
> Look into Random Projection or Random Mapping.
> 
> Basically you generate a n×m matrix of random values (usually with certain properties) and do a matrix multiplication to project from the higher dimensional space to the lower dimensional space.

Wow, really appreciate you pointing out random projection @jukofyork, this was exactly what I was looking for, and I can confirm it worked perfectly for me (I built a quick little CLI tool that deterministically reduces arbitrary vectors to any size) 🙃 

I think it could potentially be very useful to have this feature baked-in to `llama.cpp`, but, once again I'm pretty new to this all, so 🤷‍♂️

**Comment by jukofyork** [comment]
No problem and glad it worked :)
