### ISSUE TITLE
Error while building for hipBLAS on Windows 11

### ISSUE THREAD

**Issue by phungthomas** [ggerganov/llama.cpp#6514]
Hello,

I am trying to build llama.cpp for hipBLAS on gfx1100 on Windows 11, but I get this error:

```
[...]
D:/Documents/llama.cpp/ggml-cuda.cu:2620:81: error: use of undeclared identifier 'hipHostRegisterReadOnly'
    cudaError_t err = cudaHostRegister(buffer, size, cudaHostRegisterPortable | cudaHostRegisterReadOnly);
                                                                                ^
D:/Documents/llama.cpp/./ggml-cuda/common.cuh:78:34: note: expanded from macro 'cudaHostRegisterReadOnly'
#define cudaHostRegisterReadOnly hipHostRegisterReadOnly
                                 ^
13 warnings and 1 error generated when compiling for gfx1100.
[...]
```
Commit 2bf8d0f7 seems to have brought this issue, as I am able to successfuly build it on previous commits, but it fails on this one,

Here are the commands that I use to build:
```bash
SET CC=clang.exe
SET CXX=clang++.exe
cmake .. -G "Ninja" -DLLAMA_HIPBLAS=ON -DCMAKE_BUILD_TYPE=Release -DAMDGPU_TARGETS=gfx1100
cmake --build .
```

**Comment by phungthomas** [comment]
Changing
```c
cudaError_t err = cudaHostRegister(buffer, size, cudaHostRegisterPortable | cudaHostRegisterReadOnly);
```
to:
```c
cudaError_t err = cudaHostRegister(buffer, size, cudaHostRegisterPortable);
```
makes the build complete successfully, but I have no idea what this does.

**Comment by slaren** [comment]
The read only flag is necessary for using this with mmap, since the file is mapped read only. And that's the whole point of this function. There is a fix merged in whisper.cpp for older CUDA versions in https://github.com/ggerganov/whisper.cpp/pull/2020, it could also be disabled for HIP in the same way.

**Comment by ggerganov** [comment]
The fix is now synced here: https://github.com/ggerganov/llama.cpp/commit/f77261a7c525fa1fa47b18a3d78cd308ae41cafc
