### ISSUE TITLE
GGML_ASSERT: llama.cpp/examples/imatrix/imatrix.cpp:112: n_as*ggml_nrows(ids)*sizeof(int) == GGML_PAD(ggml_nbytes(ids), n_as*sizeof(int))

### ISSUE THREAD

**Issue by schmorp** [ggerganov/llama.cpp#6533]
Same model and behaviour (crash) as in https://github.com/ggerganov/llama.cpp/issues/6527

While that assert no longer exists, imatrix still crashes.

**Comment by slaren** [comment]
I am not entirely sure what that assert checks for, but it looks wrong. Removing it may fix the issue.

**Comment by schmorp** [comment]
To add half a data point. I removed the assert and at least the imatrix file generated without issue. Haven't tried to quantize the model with it.
