### ISSUE TITLE
tid in log always be the same 

### ISSUE THREAD

**Issue by mofanke** [ggerganov/llama.cpp#6534]
macos m1 pro

https://github.com/ggerganov/llama.cpp/blob/855f54402e866ed19d8d675b56a81c844c64b325/examples/server/utils.hpp#L73

 ss_tid << std::this_thread::get_id();
always be a same value，not matter how i restart

**Comment by phymbert** [comment]
Please share logs

**Comment by mofanke** [comment]
[tid.log](https://github.com/ggerganov/llama.cpp/files/14902388/tid.log)

sorry for that ,   understand that 'tid' represents thread ID, which should change upon restarting, but I've noticed that 'tid':'0x1fc50fac0' keeps appearing repeatedly. I've also noticed some other values, but I'm not sure why.

**Comment by phymbert** [comment]
This is the thread id of the server main loop.
Open if you have additional question. Also you are using ollama, so please request support on ollama communauty directly. We are not using the `server` the same way.
Please reopen if you need
