### ISSUE TITLE
It's not possible to enter <|END_OF_TURN_TOKEN|> when using cmd-r+

### ISSUE THREAD

**Issue by araleza** [ggerganov/llama.cpp#6551]
Hi, I'm trying to use interactive mode to work with the new cmd-r+. I'm currently on the llama branch that supports it.

But I'm unable to use this model properly as I cannot enter the tokens required by the template for this model.  I'm supposed to pass in various tokens:
```
<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN|>{prompt}<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>{response}
```
But, when I enter tokens like <|END_OF_TURN_TOKEN|> into the interactive prompt, these get converted into a group of text tokens, rather than a single special token. I believe this because if I enter this prompt:
```
<|START_OF_TURN_TOKEN|><|USER_TOKEN|>Hi, can you tell me the capital of Bulgaria please<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```
then the model continues:
```
The capital of Bulgaria is Sofia. Can I help you with anything else?<|END_
```
I halted inference there. You can see it's _partway_ through writing an <|END_OF_TURN_TOKEN|>, which means that it isn't a single token. And that means it's very likely to be copying the  <|END_OF_TURN_TOKEN|> from my prompt, which it shouldn't be able to read as multiple tokens if it was passed to the model as a single token.

(By the way I skipped the <BOS_TOKEN> from my prompt as I think llama.cpp adds that automatically for me, although I'm not certain about that. It's not relevant to this issue.)

**Comment by fblissjr** [comment]
Interestingly, this is the token id that is inconsistent across tokenizer.json files in Cohere's repo for fp16 & their 4bit bnb one.

See: https://github.com/huggingface/transformers/pull/30027

Basically, in the "original" / fp16 model repo, token id 255001 <|END_OF_TURN_TOKEN|>, special is set to False. In the 4bit bnb one, it's True.

**Comment by araleza** [comment]
I used the '-ptc 1' debugging option to confirm that the input prompt's ```<|END_OF_TURN_TOKEN|>``` becomes a cluster of tokens:

Without ```<|END_OF_TURN_TOKEN|>``` in prompt:
![image](https://github.com/ggerganov/llama.cpp/assets/70412719/d31e84ac-d3be-44af-9378-f37dd7ceafc2)

With ```<|END_OF_TURN_TOKEN|>``` in prompt:
![image](https://github.com/ggerganov/llama.cpp/assets/70412719/a757eca0-2700-4b85-aacb-d75cb0fcf300)

**Comment by fblissjr** [comment]
I'm pretty certain something is broken in the tokenizer.json. Running the fp16 tokenizer.json fixed my random Russian, but replaced it with random Persian. Using the 4bit bnb one caused the same random Russian.

Using MLX on macos since I don't have the vram to confirm this on CUDA, but would be curious to see what's happening there.

**Comment by araleza** [comment]
Looks like this is already a known issue, and is captured by this issue here:

https://github.com/ggerganov/llama.cpp/issues/6391

**Comment by araleza** [comment]
Actually, looking in more detail at that linked issue, it only says that some models break up token like <|im_end|> instead of actually having a single token for that. This issue here is kind of the opposite issue, which is that the model does have a single token, and main isn't able to recognize it in the interactive input stream.

**Comment by fblissjr** [comment]
Yeah, I can't figure it out. But burned enough steam on this and no longer at my workstation - if you figure it out, lemme know. :)
