### ISSUE TITLE
Single-card single-layer multi-module parallelization

### ISSUE THREAD

**Issue by putizi-super** [ggerganov/llama.cpp#6557]
# Prerequisites
I'm attempting to remove data dependencies between the MLP and attention modules of the transformer layer in the model, allowing them to run in parallel with the same input. I made some superficial modifications in the LLM.build function, but it seems that there was no improvement in speed. Can I conclude that llama.cpp does not support parallelization of multiple modules on a single GPU? In other words, if there are two fully connected layers with the same input (such as the three mappings in attention), is it still not possible to execute them in parallel? From my research, it appears that PyTorch does not support this, but since I'm not very familiar with your project, I'd like to inquire whether this framework supports parallelization of multiple modules within a single layer.
# Feature Description

like this:
<img width="181" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/74298632/ccc10ac1-3120-4a8c-a3fa-516c2340bf26">

# Motivation

I'm trying out new ideas, but I don't want multi-card deployment at the moment, I just want to make single-card deployment faster, and then parallel two modules.
# Possible Implementation
Here's how I changed the code
`for (int il = 0; il < n_layer; ++il) {
            if(il>15){
            struct ggml_tensor * inpSA = inpL;
            struct ggml_tensor * ffn_inp = inpL;
            // cb(ffn_inp, "ffn_inp", il);
            // norm
            cur = llm_build_norm(ctx0, inpL, hparams,
                    model.layers[il].attn_norm, NULL,
                    LLM_NORM_RMS, cb, il);
            // cb(cur, "attn_norm", il);
            // self-attention
            {
                // compute Q and K and RoPE them
                struct ggml_tensor * Qcur = ggml_mul_mat(ctx0, model.layers[il].wq, cur);
                cb(Qcur, "Qcur", il);

                struct ggml_tensor * Kcur = ggml_mul_mat(ctx0, model.layers[il].wk, cur);
                cb(Kcur, "Kcur", il);

                struct ggml_tensor * Vcur = ggml_mul_mat(ctx0, model.layers[il].wv, cur);
                cb(Vcur, "Vcur", il);
                Qcur = ggml_rope_custom(
                    ctx0, ggml_reshape_3d(ctx0, Qcur, n_embd_head, n_head,    n_tokens), inp_pos,
                    n_embd_head, 0, 0, n_orig_ctx, freq_base, freq_scale,
                    ext_factor, attn_factor, beta_fast, beta_slow
                );
                cb(Qcur, "Qcur", il);
                Kcur = ggml_rope_custom(
                    ctx0, ggml_reshape_3d(ctx0, Kcur, n_embd_head, n_head_kv, n_tokens), inp_pos,
                    n_embd_head, 0, 0, n_orig_ctx, freq_base, freq_scale,
                    ext_factor, attn_factor, beta_fast, beta_slow
                );
                cb(Kcur, "Kcur", il);
                std::tie(k_cpy, v_cpy) = llm_build_kv_store(ctx0, hparams, kv_self, gf, Kcur, Vcur, n_ctx, n_tokens, kv_head, cb, il);

                cur = llm_build_kqv(ctx0, hparams, kv_self,
                        model.layers[il].wo, NULL,
                        Qcur, KQ_scale, KQ_mask, n_ctx, n_tokens, n_kv, -1.0f, cb, il);
                cb(cur, "kqv_out", il);
            }

            struct ggml_tensor * cur_ffn;
            // feed-forward network
            {
                cur_ffn = llm_build_norm(ctx0, ffn_inp, hparams,
                        model.layers[il].ffn_norm, NULL,
                        LLM_NORM_RMS, cb, il);
                no_offload_cb(cur_ffn, "ffn_norm", il);

                if (1) {
                    cur_ffn = llm_build_ffn_sparse(ctx0, cur_ffn,
                        model.layers[il].ffn_up,   NULL,
                        model.layers[il].ffn_gate, NULL,
                        model.layers[il].ffn_down, NULL,
                        model.layers[il].ffn_down_t,
                        model.layers[il].mlp_pre_w1,
                        model.layers[il].mlp_pre_w2,
                        ffn_inp, // as for now, llama's pred use the same input as the ffn
                        model.layers[il].gpu_idx, 
                        model.layers[il].gpu_bucket, model.layers[il].ffn_gate_gpu, model.layers[il].ffn_down_gpu, model.layers[il].ffn_up_gpu, // TODO: disable gpu offloading as for now
                        LLM_FFN_RELU, LLM_FFN_PAR, no_offload_cb, il);
                } else {
                    // fallback to dense
                    cur_ffn = llm_build_ffn(ctx0, cur_ffn,
                        model.layers[il].ffn_up,   NULL,
                        model.layers[il].ffn_gate, NULL,
                        model.layers[il].ffn_down_t, NULL,
                        LLM_FFN_RELU, LLM_FFN_PAR, cb, il);
                }
                // cb(cur_ffn, "ffn_out", il);
            }
            struct ggml_tensor * attn_out = ggml_add(ctx0, cur, inpSA);
            cur = ggml_add(ctx0, cur_ffn, attn_out);
            // cb(cur, "l_out", il);
            // input for next layer
            inpL = cur;
            }`
``
            
            else{
            struct ggml_tensor * inpSA = inpL;

            // norm
            cur = llm_build_norm(ctx0, inpL, hparams,
                    model.layers[il].attn_norm, NULL,
                    LLM_NORM_RMS, cb, il);
            cb(cur, "attn_norm", il);

            // self-attention
            {
                // compute Q and K and RoPE them
                struct ggml_tensor * Qcur = ggml_mul_mat(ctx0, model.layers[il].wq, cur);
                cb(Qcur, "Qcur", il);

                struct ggml_tensor * Kcur = ggml_mul_mat(ctx0, model.layers[il].wk, cur);
                cb(Kcur, "Kcur", il);

                struct ggml_tensor * Vcur = ggml_mul_mat(ctx0, model.layers[il].wv, cur);
                cb(Vcur, "Vcur", il);

                Qcur = ggml_rope_custom(
                    ctx0, ggml_reshape_3d(ctx0, Qcur, n_embd_head, n_head,    n_tokens), inp_pos,
                    n_embd_head, 0, 0, n_orig_ctx, freq_base, freq_scale,
                    ext_factor, attn_factor, beta_fast, beta_slow
                );
                cb(Qcur, "Qcur", il);

                Kcur = ggml_rope_custom(
                    ctx0, ggml_reshape_3d(ctx0, Kcur, n_embd_head, n_head_kv, n_tokens), inp_pos,
                    n_embd_head, 0, 0, n_orig_ctx, freq_base, freq_scale,
                    ext_factor, attn_factor, beta_fast, beta_slow
                );
                cb(Kcur, "Kcur", il);

                std::tie(k_cpy, v_cpy) = llm_build_kv_store(ctx0, hparams, kv_self, gf, Kcur, Vcur, n_ctx, n_tokens, kv_head, cb, il);

                cur = llm_build_kqv(ctx0, hparams, kv_self,
                        model.layers[il].wo, NULL,
                        Qcur, KQ_scale, KQ_mask, n_ctx, n_tokens, n_kv, -1.0f, cb, il);
                cb(cur, "kqv_out", il);
            }

            struct ggml_tensor * ffn_inp = ggml_add(ctx0, cur, inpSA);
            cb(ffn_inp, "ffn_inp", il);

            // feed-forward network
            {
                cur = llm_build_norm(ctx0, ffn_inp, hparams,
                        model.layers[il].ffn_norm, NULL,
                        LLM_NORM_RMS, cb, il);
                no_offload_cb(cur, "ffn_norm", il);

                if (1) {
                    cur = llm_build_ffn_sparse(ctx0, cur,
                        model.layers[il].ffn_up,   NULL,
                        model.layers[il].ffn_gate, NULL,
                        model.layers[il].ffn_down, NULL,
                        model.layers[il].ffn_down_t,
                        model.layers[il].mlp_pre_w1,
                        model.layers[il].mlp_pre_w2,
                        ffn_inp, // as for now, llama's pred use the same input as the ffn
                        model.layers[il].gpu_idx, 
                        model.layers[il].gpu_bucket, model.layers[il].ffn_gate_gpu, model.layers[il].ffn_down_gpu, model.layers[il].ffn_up_gpu, // TODO: disable gpu offloading as for now
                        LLM_FFN_RELU, LLM_FFN_PAR, no_offload_cb, il);
                } else {
                    // fallback to dense
                    cur = llm_build_ffn(ctx0, cur,
                        model.layers[il].ffn_up,   NULL,
                        model.layers[il].ffn_gate, NULL,
                        model.layers[il].ffn_down_t, NULL,
                        LLM_FFN_RELU, LLM_FFN_PAR, cb, il);
                }
                // cb(cur, "ffn_out", il);
            }

            cur = ggml_add(ctx0, cur, ffn_inp);
            cb(cur, "l_out", il);

            // input for next layer
            inpL = cur;                
            }
        }
`

**Comment by slaren** [comment]
As you suspect, llama.cpp does not run multiple operations in parallel.

**Comment by putizi-super** [comment]
OK。 thank you for your reply and have a nice day！
