### ISSUE TITLE
Double Quantization for exisiting models (.37 bits per parameter)

### ISSUE THREAD

**Issue by OmegAshEnr01n** [ggerganov/llama.cpp#6559]
# Motivation and Feature Description

There are currently means of quantizing models to a much lower precision. Some libraries already have this functionality but in a training context. Would it be possible to port this feature to this repository? Currently the maximum quantization that we have access to is 2 bits. But with Double quantization this can increase. Someone can correct me if im going off the rails here.  

> Enabled with [bitsandbytes](https://github.com/TimDettmers/bitsandbytes). Check out the [paper](https://arxiv.org/abs/2305.14314v1) to learn more about how it works.

> "dq" stands for "Double Quantization" which reduces the average memory footprint by quantizing the quantization constants. In average, this amounts to about 0.37 bits per parameter (approximately 3 GB for a 65B model).

Quote from [link](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/quantize.md)

#  Possible Implementation

The Code from bitsandbytes shows that the code they have written only works on GPU but is able to perform double quantization. I have found the code [here ](https://github.com/TimDettmers/bitsandbytes/blob/0c64a0d8c377734377fa591226e3b2c65fa8aaf8/csrc/ops.cu#L528C1-L550C1)for it.

**Comment by sorasoras** [comment]
What application for a  .37 bit quant? I cannot think off one

**Comment by OmegAshEnr01n** [comment]
Lower model size. Allowing users to run even larger models on smaller machines...
