### ISSUE TITLE
Using CLBlast to call GPU on Android device, what is the relationship between ngl parameters and model output correctness?

### ISSUE THREAD

**Issue by qtyandhasee** [ggerganov/llama.cpp#6562]
with the help of [issue2169](https://github.com/ggerganov/llama.cpp/issues/2169,) I use CLBlast on my qualcomm equipment (Adreno740v2) successfully call the GPU calls

But I found an interesting thing when I tried to do model reasoning, when I used the model **stories260K.gguf**, the model returned normal for questions and answers, but the GPU was hardly called (showing a call rate of 1% or even 0%).
![image](https://github.com/ggerganov/llama.cpp/assets/73628233/51b69bdd-35ac-470a-969e-e5b381fefa3c)
For the model **llama- 2-7B-Chatt.q4_k_M.GGUf and llama- 2-7B-Chat.q5_k_S.GGUf**, I could get the output, but the **output result was not correct**. At this time, the GPU call rate is about 40%.
![image](https://github.com/ggerganov/llama.cpp/assets/73628233/db8a8010-aaf9-4372-b564-6f0467102be8)
For the model **LLAMA-2-13b-chat.q2_K. gguf and LLAMA-2-7b-chat.q2_K. gguf**, I got normal and satisfactory responses when the ngl parameter was set to 2, but when I set the **ngl parameter to close to all the GPU parameters that can be unloaded**, For example, 40/41, the output of the model is back to random output. Of course, the GPU call rate is displayed at around 50%.
when ngl is 2 or 10 (not very large)
![image](https://github.com/ggerganov/llama.cpp/assets/73628233/c907b4a0-e80f-4f0a-b838-46df26c96bc9)
when set ngl as 40(40/41),the answer is rediculious
![image](https://github.com/ggerganov/llama.cpp/assets/73628233/ba610a24-e11a-4559-83a5-1ea733e364a9)

the cmd i use to run is as follows
GGML_OPENCL_PLATFORM=0 GGML_OPENCL_DEVICE=0 ./bin/main -t 8 -m /data/local/tmp/llama_cpu/llama-2-7b-chat.Q4_K_M.gguf --color -c 2048 -ngl 2 --temp 0.7  -n -1 -i -ins
i didn't change other parameters but ngl and model

This looks interesting, and I wonder if it's because CLBlast is making some kind of error in the GPU call?
Has anyone else found themselves in my situation? I want to know which direction I should take to eliminate this mistake.

**Comment by Jeximo** [comment]
Unfortunately, OpenCL for Android under-performs, and yes, even the output is incorrect: [likely a memory alignment/padding issue](https://github.com/ggerganov/llama.cpp/issues/2133#issuecomment-1627644716)

You'll likely see wild results if you run the `perplexity` tool with CLBlast on Android.


Related: [CLBlast is more of a OpenCL library than an actual backend](https://github.com/ggerganov/llama.cpp/issues/5965#issuecomment-2010295432)

**Comment by qtyandhasee** [comment]
> Unfortunately, OpenCL for Android under-performs, and yes, even the output is incorrect: [likely a memory alignment/padding issue](https://github.com/ggerganov/llama.cpp/issues/2133#issuecomment-1627644716)
> 
> You'll likely see wild results if you run the `perplexity` tool with CLBlast on Android.
> 
> Related: [CLBlast is more of a OpenCL library than an actual backend](https://github.com/ggerganov/llama.cpp/issues/5965#issuecomment-2010295432)

@Jeximo  Thank you very much for your answer. Can we simply understand that the support of llama.cpp for GPU call on SoC is not perfect at present?

**Comment by Jeximo** [comment]
> support of llama.cpp for GPU call on SoC is not perfect at present?

Yes, it's imperfect.

> Or is it because none of SoC's OpenCL driver support currently supports LLM-like reasoning?

Yes, `OpenCL` for Android is bugged, and no one is currently developing it.  `Vulkan` is **better developed**, but it's not *optimized* for Android [as it also produces bad output](https://github.com/ggerganov/llama.cpp/issues/6337#issuecomment-2028889136).

To put it simply, there's **a lot of progress to make** for LLM and GPU Android .
