### ISSUE TITLE
Support for RecurrentGemma (Gemma with Griffin Architecture)

### ISSUE THREAD

**Issue by TechxGenus** [ggerganov/llama.cpp#6564]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do as an enhancement.

Google’s newly released model, a hybrid architecture based on attention and hidden state: https://huggingface.co/google/recurrentgemma-2b

# Motivation

Please provide a detailed written description of reasons why this feature is necessary and how it is useful to `llama.cpp` users.

A good and open LLM with novel architecture

# Possible Implementation

If you have an idea as to how it can be implemented, please write a detailed description. Feel free to give links to external sources or share visuals that might be helpful to understand the details better.

Unlike Jamba (#6372), the model is very small and can be used by most computers for inference.
Hybrid architecture is likely to be the trend of the future. Hope that llama.cpp can support it and other hybrid architectures (if possible).

**Comment by vasileermicioi** [comment]
this is the PR merged in gemma.cpp https://github.com/google/gemma.cpp/pull/136/files

**Comment by coder543** [comment]
This issue was marked as stale, but shouldn’t supporting more efficient architectures be a priority?

**Comment by fat-tire** [comment]
Will this or Griffin be in the upcoming Gemma 2 model(s)?  I say "this or griffin" as the paper [mentions](https://storage.googleapis.com/deepmind-media/gemma/recurrentgemma-report.pdf) a slight difference between recurrentgemma and griffin FWIW:

> We make only a single modification to the Griffin architecture (De et al., 2024), which is to multiply the input embeddings by a constant equal to the square root of model width. The input and output embeddings are tied, but this factor is not applied to the output.

Seems like Griffin or a variant could be the "brand new architecture designed for breakthrough performance and efficiency" in today's Gemma 2 [announcement](https://developers.googleblog.com/en/gemma-family-and-toolkit-expansion-io-2024/), no?

**Comment by calculatortamer** [comment]
new stuff!!!!!!!!!!
https://arxiv.org/abs/2404.07839
https://ai.google.dev/gemma/docs/recurrentgemma/model_card
https://huggingface.co/collections/google/recurrentgemma-release-66152cbdd2d6619cb1665b7a

**Comment by coder543** [comment]
Now Google has released a 9B version of RecurrentGemma, which seems to score similarly to Gemma-7b, while supposedly being _far_ more efficient:

![max_throughput](https://github.com/ggerganov/llama.cpp/assets/726063/c248e959-e654-42d1-8932-03e86b0212de)

([source](https://huggingface.co/google/recurrentgemma-9b-it#throughput))

Any chance llama.cpp can support RecurrentGemma @ggerganov? I wish I had the skill to implement it myself here, but I have no familiarity with llama.cpp's inner workings, I'm just a user of the software.

**Comment by ggerganov** [comment]
Will be added, though we probably have to merge Jamba (https://github.com/ggerganov/llama.cpp/pull/7531) and then see how to adapt `llama_cache` to support the new Griffin layers

**Comment by DuckyBlender** [comment]
Great news. People often forget about more efficient architectures, supporting this will speed so many things up!

**Comment by Meshwa428** [comment]
Is recurrent Gemma going to come to ollama or not?

It uses Google's custom architecture named Griffin right?

**Comment by 0wwafa** [comment]
any news?
google/recurrentgemma-2b-it
and
google/recurrentgemma-9b-it

are still unsupported....

**Comment by coder543** [comment]
Stalebot is an annoying concept. People hate it when commenters are leaving low effort comments like “bump”, but then stalebot closes the issue if no one does.

RecurrentGemma *still* isn’t supported, sadly.

**Comment by coder543** [comment]
@ggerganov how do we reopen this issue?

**Comment by Meshwa428** [comment]
Any updates?

**Comment by Meshwa428** [comment]
Updates?
