### ISSUE TITLE
Crash in A100

### ISSUE THREAD

**Issue by linuxpham** [ggerganov/llama.cpp#6566]
INFO [   launch_slot_with_task] slot is processing task | tid="140357219835904" timestamp=1712674659 id_slot=0 id_task=0
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
2024/04/09 14:57:39 008786

***** FATAL SIGNAL RECEIVED ******* 
Received fatal signal: SIGABRT(6)	PID: 2228261

***** SIGNAL SIGABRT(6)

**Comment by slaren** [comment]
Not enough information to reproduce.
