### ISSUE TITLE
The error for Starcoder

### ISSUE THREAD

**Issue by gabrielpondc** [ggerganov/llama.cpp#6584]
When I using convert.py convert the startcoder model to gguf the `KeyError: 'transformer.wte.weight'` has been reported, but when i using `convert-hf-to-gguf.py` is okay but it can not good at quantification, Is there possible using fp16.gguf quant to q8_0,or is there some method to deal with the `KeyError: 'transformer.wte.weight'` problem.

**Comment by HanClinto** [comment]
Which Starcoder model are you downloading? A HF URL would be helpful.

**Comment by gabrielpondc** [comment]
> Which Starcoder model are you downloading? A HF URL would be helpful.

Sorry late to reply u, Here is the link of the model https://huggingface.co/gabrielpondc/NL2SQL-StarCoder-15B/tree/main

**Comment by gabrielpondc** [comment]
I using convert-hf-to-gguf.py to make the gguf file and then using quantize to finalized the quantization working and it is worded, thx for ur response

**Comment by HanClinto** [comment]
Glad it's working for you!
