### ISSUE TITLE
Auto calculate max number of layers with -ngl -1?

### ISSUE THREAD

**Issue by chigkim** [ggerganov/llama.cpp#6594]
If the entire model and context size don't fit, can we have a feature -ngl -1 where that automatically calculates the maximum number of layers that could fit into the gpu, and offload the rest to cpu?

**Comment by Jeximo** [comment]
> a feature -ngl -1 where that automatically calculates the maximum number of layers that could fit into the gpu, and offload the rest to cpu?

It's an important feature, [but cannot be done without very significant changes to llama.cpp, and backend interfaces](https://github.com/ggerganov/llama.cpp/pull/6502#issuecomment-2043082442) to handle this feature correctly.

**Comment by fredlas** [comment]
Since it sounds like the clean in-code approach of #6502 is not imminent, I have [written a script for this](https://github.com/fredlas/optimize_llamacpp_ngl); please give it a try @WilliamTambellini and anyone else interested!
