### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yuanyongj** [ggerganov/llama.cpp#6601]
file included from examples/llava/llava.cpp:5:0:
common/base64.hpp: In static member function ‘static Output_iterator base64::encode(Input_iterator, Input_iterator, Output_iterator, base64::alphabet)’:
common/base64.hpp:84:42: error: ‘alphabet’ is not a class, namespace, or enumeration
         const char* alpha  = alphabet == alphabet::url_filename_safe
                                          ^
common/base64.hpp: In static member function ‘static uint8_t base64::_base64_value(base64::alphabet&, char)’:
common/base64.hpp:355:25: error: ‘alphabet’ is not a class, namespace, or enumeration
         if (alphabet == alphabet::standard) {
                         ^
common/base64.hpp:361:32: error: ‘alphabet’ is not a class, namespace, or enumeration
         } else if (alphabet == alphabet::url_filename_safe) {
                                ^
common/base64.hpp:370:28: error: ‘alphabet’ is not a class, namespace, or enumeration
                 alphabet = alphabet::standard;
                            ^
common/base64.hpp:374:28: error: ‘alphabet’ is not a class, namespace, or enumeration
                 alphabet = alphabet::standard;
                            ^
common/base64.hpp:378:28: error: ‘alphabet’ is not a class, namespace, or enumeration
                 alphabet = alphabet::url_filename_safe;
                            ^
common/base64.hpp:382:28: error: ‘alphabet’ is not a class, namespace, or enumeration
                 alphabet = alphabet::url_filename_safe;
                            ^
make: *** [libllava.a] 错误 1

**Comment by HanClinto** [comment]
What are the steps to reproduce this bug?
