### ISSUE TITLE
"failed to find free space in the KV cache" is displayed and no response is returned.

### ISSUE THREAD

**Issue by Taikono-Himazin** [ggerganov/llama.cpp#6603]
When using llama.cpp via LocalAI, "failed to find free space in the KV cache" will be displayed after using it for a while, and the string that can respond will gradually become shorter, and eventually it will not be possible to respond.

I looked at past issues such as #4185, but I don't really understand how to solve them.

I would like to delete the KV cache or increase the capacity of the KV cache, but how should I do that?

The version of llama.cpp seems to be 8228b66dbc16290c5cbd70e80ab47c068e2569d8.

**Comment by phymbert** [comment]
Please upgrade the KV cache size yes using `--ctx-size`
