### ISSUE TITLE
llm/llama.cpp/quantize - Mixtral model quantizatization halts at random step

### ISSUE THREAD

**Issue by bulat15g** [ggerganov/llama.cpp#6606]
I fine-tuned Mixtral with QLORA on my dataset and merged it. 

After cloning llamacpp, I built the quantization feature using `make -C llm/llama.cpp quantize`. 

Then, I converted the model using 
`python llm/llama.cpp/convert.py LLaMA-Factory/models/mixtral_instruct01_lora_4bit_full --outtype f16`. 

When attempting to quantize with 
`llm/llama.cpp/quantize converted.bin quantized.bin q4_0`

the process randomly freezes—this could happen at step 6, anywhere past 100, or even beyond 500 steps. Despite several attempts, the issue persists without resolution.

screenshot 
![1111](https://github.com/ggerganov/llama.cpp/assets/23155849/dcd03305-e433-4c10-8174-5b7128b7a33f)

**Comment by slaren** [comment]
Likely a hardware issue, possibly a failing disk drive.

**Comment by bulat15g** [comment]
Thank you for the advice - I will try on another device)
