### ISSUE TITLE
support `--hf-token` param in addition of `--hf-repo`

### ISSUE THREAD

**Issue by phymbert** [ggerganov/llama.cpp#6613]
### Motivation

Models with non standard licence requires an opt-in on HF and the download requires a read token if the model is gated.

### Proposal

- Add an `--hf-token` param in `common` and add it in the url built with `--hf-repo` and `--hf-file` in `llama_load_model_from_hf`.

**Comment by TheBongStack** [comment]
Hey, can I get assigned to solve this problem? I will be glad to contribute to it.

**Comment by phymbert** [comment]
Sure, thanks

**Comment by phymbert** [comment]
@TheBongStack reading the issue again, I think it is easier to pass the token until loadmodel_from_url and add it as Authorization Bearer header.

**Comment by phymbert** [comment]
Hi @TheBongStack, are you still working on this issue ?

**Comment by TheBongStack** [comment]
> Hi @TheBongStack, are you still working on this issue ?

Hey, Yes I am still working on this issue and have come up with an incomplete solution. I apologize as it may take some because I am new to open source contributing and its going to be my first PR submission to a large project

**Comment by phymbert** [comment]
No worries, take your time.

You need to concatenate `hf_tokens` in the url just where the `hf_repo` is used:

https://github.com/ggerganov/llama.cpp/blob/master/common/common.cpp#L2183

The token must be before the hostname prefixed with an `@`

**Comment by TheBongStack** [comment]
> @TheBongStack reading the issue again, I think it is easier to pass the token until loadmodel_from_url and add it as Authorization Bearer header.

I added an if block to accept --hf-token or -hft parameter and added the passed argument to params.hf_token
Now, when I follow up the function calls, I see  load_model_from_url function call with a curl object and url and path arguments.

The thing I am most confused about is in llama_load_from_url where do I set the authorization headers before making the call to accept the params.hf_token variable. Also I think we have to pass the params object too toacces it in the function

**Comment by phymbert** [comment]
I yes I got it, a token cannot be passed as a `user:password@host` in curl url. Then modify the `load_model_from_url to take a token as parameter

**Comment by TheBongStack** [comment]
Hey, I added an pull request solving this issue can you review it please?

**Comment by sfadaei** [comment]
I see this is primarily done! `--hf-token` is present where it should be. I can only think of adding this to the following
 1. `bench.py` 2. `steps.py`. Or am I missing something? @phymbert @ggerganov
