### ISSUE TITLE
llama_tensor_get_type falling back when not necessary?

### ISSUE THREAD

**Issue by bartowski1182** [ggerganov/llama.cpp#6614]
Noticed while making some quants for Q2_K that I was getting messages:

llama_tensor_get_type : tensor cols 14464 x 4096 are not divisible by 256, required for q3_K - using fallback quantization iq4_nl

But by my math, it definitely is? Anything multiplied by 4096 should be. Is the error message misleading or is there some accidental miscalculation going on?

**Comment by slaren** [comment]
"cols" refers to the first dimension, 14464. The row size is what needs to be divisible by 256.

**Comment by bartowski1182** [comment]
Ah okay thank you, appreciate the insight :)
