### ISSUE TITLE
server: Use `llama_chat_apply_template` on `/completion` endpoint

### ISSUE THREAD

**Issue by EZForever** [ggerganov/llama.cpp#6624]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Use `llama_chat_apply_template` on `/completion` or a new endpoint (e.g. `/chat`), in addition to the current OpenAI compatibility endpoints. Update WebUI to reflect the change.

# Motivation

The OpenAI compatibility endpoints are nice and all, but native endpoints offer functionalities specific to llama.cpp (e.g. mirostat, slot management, etc). One exception is automatically applying chat templates, which has been introduced to OpenAI compatibility endpoints in #5593, while the native endpoint (`/completion`) still uses the old prompt/antiprompt formatting method and requires the user to provide correctly formatted prompts. This is especially a problem for WebUI users, and there has been many issue or discussion threads about worse-than-expected chat results due to incorrect templates. It would thus be great to introduce server-side support for chat templates on native endpoints.

Related: #5447

Refs on antiprompts being old and obselete: https://github.com/ggerganov/llama.cpp/pull/6378#pullrequestreview-1969627725 https://github.com/ggerganov/llama.cpp/issues/6391#issue-2216074620

# Possible Implementation

`/completion` works well as a text completion endpoint (?), thus in order not to break stuffs too much, maybe we can consider adding a new endpoint (`/chat`) with the changes. WebUI chat page should use the new endpoint instead. "Prompt template" and "Chat history template" options are thus obselete, and could be removed or moved under "More options".

**Comment by okigan** [comment]
@EZForever is this still and issue or was it resolved ?

**Comment by EZForever** [comment]
Yes, this issue is still relevant.
