### ISSUE TITLE
Inconsistent size output of chunks with gguf-split

### ISSUE THREAD

**Issue by RodriMora** [ggerganov/llama.cpp#6634]
System:
Ubuntu server 22.04 LTS
5950X
64GB Ram 3200Mhz
2x Nvidia 3090

Steps to reproduce:

First I converted the model to FP16 GGUF with:
`./convert.py --outfile Karasu-Mixtral-8x22B-v0.1-fp16.gguf --outtype f16 lightblue_Karasu-Mixtral-8x22B-v0.1`

That worked just fine and I got:
![image](https://github.com/ggerganov/llama.cpp/assets/5622210/6da7e036-863c-44ef-9b38-eee0e746f406)

Then to quantize it to Q5_K_M:
`./quantize Karasu-Mixtral-8x22B-v0.1-fp16.gguf Karasu-Mixtral-8x22B-v0.1-Q5_K_M.gguf Q5_K_M`

That worked fine too:
![image](https://github.com/ggerganov/llama.cpp/assets/5622210/39401f0d-7f3d-4f18-b6b3-0f328ad34f12)

But when using gguf-split --split even though I'm using --split-max-tensors 128 the sizes of the chunks are inconsistent:

`./gguf-split --split --split-max-tensors 128 /nfs/models/Karasu-Mixtral-8x22B-v0.1-Q5_K_M.gguf /nfs/models/`

![image](https://github.com/ggerganov/llama.cpp/assets/5622210/f403478e-08f7-460b-8706-8b6b1c687111)
![image](https://github.com/ggerganov/llama.cpp/assets/5622210/4e9fc7de-fe17-4d4b-8c73-e092a5f7136d)

**Comment by he29-net** [comment]
If you want the output shards to have comparable sizes, you may be better off using `--split-max-size` instead of `--split-max-tensors`. My guess is that `gguf-split` works as intended, but the first ~400 tensors are simply much smaller than the rest at the end.

**Comment by RodriMora** [comment]
> If you want the output shards to have comparable sizes, you may be better off using `--split-max-size` instead of `--split-max-tensors`. My guess is that `gguf-split` works as intended, but the first ~400 tensors are simply much smaller than the rest at the end.

I've tried with --split-max-size but it doens't seem to work:

Example with 5G max:

./gguf-split --split --split-max-size 5G --dry-run /nfs/models/Karasu-Mixtral-8x22B-v0.1-Q5_K_M.gguf /nfs/models/
n_split: 172
split 00001: n_tensors = 101, total_size = 1009M
split 00002: n_tensors = 113, total_size = 1023M
split 00003: n_tensors = 113, total_size = 1023M
split 00004: n_tensors = 68, total_size = 721M
split 00005: n_tensors = 1, total_size = 528M
split 00006: n_tensors = 1, total_size = 630M
split 00007: n_tensors = 1, total_size = 528M
split 00008: n_tensors = 1, total_size = 528M
split 00009: n_tensors = 1, total_size = 630M
split 00010: n_tensors = 1, total_size = 528M
split 00011: n_tensors = 1, total_size = 528M
split 00012: n_tensors = 1, total_size = 630M
split 00013: n_tensors = 1, total_size = 528M
split 00014: n_tensors = 1, total_size = 528M
split 00015: n_tensors = 1, total_size = 630M
split 00016: n_tensors = 1, total_size = 528M
split 00017: n_tensors = 1, total_size = 528M
split 00018: n_tensors = 1, total_size = 630M
split 00019: n_tensors = 1, total_size = 528M
split 00020: n_tensors = 1, total_size = 528M
split 00021: n_tensors = 1, total_size = 630M
split 00022: n_tensors = 1, total_size = 528M
split 00023: n_tensors = 1, total_size = 528M
split 00024: n_tensors = 1, total_size = 630M
split 00025: n_tensors = 1, total_size = 528M
split 00026: n_tensors = 1, total_size = 528M
split 00027: n_tensors = 1, total_size = 528M
split 00028: n_tensors = 1, total_size = 528M
split 00029: n_tensors = 1, total_size = 528M
split 00030: n_tensors = 1, total_size = 528M
split 00031: n_tensors = 1, total_size = 528M
split 00032: n_tensors = 1, total_size = 528M
split 00033: n_tensors = 1, total_size = 630M
split 00034: n_tensors = 1, total_size = 528M
split 00035: n_tensors = 1, total_size = 528M
split 00036: n_tensors = 1, total_size = 528M
split 00037: n_tensors = 1, total_size = 528M
split 00038: n_tensors = 1, total_size = 528M
split 00039: n_tensors = 1, total_size = 528M
split 00040: n_tensors = 1, total_size = 528M
split 00041: n_tensors = 1, total_size = 528M
split 00042: n_tensors = 1, total_size = 630M
split 00043: n_tensors = 1, total_size = 528M
split 00044: n_tensors = 1, total_size = 528M
split 00045: n_tensors = 1, total_size = 528M
split 00046: n_tensors = 1, total_size = 528M
split 00047: n_tensors = 1, total_size = 528M
split 00048: n_tensors = 1, total_size = 528M
split 00049: n_tensors = 1, total_size = 528M
split 00050: n_tensors = 1, total_size = 528M
split 00051: n_tensors = 1, total_size = 630M
split 00052: n_tensors = 1, total_size = 528M
split 00053: n_tensors = 1, total_size = 528M
split 00054: n_tensors = 1, total_size = 528M
split 00055: n_tensors = 1, total_size = 528M
split 00056: n_tensors = 1, total_size = 528M
split 00057: n_tensors = 1, total_size = 528M
split 00058: n_tensors = 1, total_size = 528M
split 00059: n_tensors = 1, total_size = 528M
split 00060: n_tensors = 1, total_size = 630M
split 00061: n_tensors = 1, total_size = 528M
split 00062: n_tensors = 1, total_size = 528M
split 00063: n_tensors = 1, total_size = 528M
split 00064: n_tensors = 1, total_size = 528M
split 00065: n_tensors = 1, total_size = 528M
split 00066: n_tensors = 1, total_size = 528M
split 00067: n_tensors = 1, total_size = 528M
split 00068: n_tensors = 1, total_size = 528M
split 00069: n_tensors = 1, total_size = 630M
split 00070: n_tensors = 1, total_size = 528M
split 00071: n_tensors = 1, total_size = 528M
split 00072: n_tensors = 1, total_size = 528M
split 00073: n_tensors = 1, total_size = 528M
split 00074: n_tensors = 1, total_size = 528M
split 00075: n_tensors = 1, total_size = 528M
split 00076: n_tensors = 1, total_size = 528M
split 00077: n_tensors = 1, total_size = 528M
split 00078: n_tensors = 1, total_size = 630M
split 00079: n_tensors = 1, total_size = 528M
split 00080: n_tensors = 1, total_size = 528M
split 00081: n_tensors = 1, total_size = 528M
split 00082: n_tensors = 1, total_size = 528M
split 00083: n_tensors = 1, total_size = 528M
split 00084: n_tensors = 1, total_size = 528M
split 00085: n_tensors = 1, total_size = 528M
split 00086: n_tensors = 1, total_size = 528M
split 00087: n_tensors = 1, total_size = 630M
split 00088: n_tensors = 1, total_size = 528M
split 00089: n_tensors = 1, total_size = 528M
split 00090: n_tensors = 1, total_size = 528M
split 00091: n_tensors = 1, total_size = 528M
split 00092: n_tensors = 1, total_size = 528M
split 00093: n_tensors = 1, total_size = 528M
split 00094: n_tensors = 1, total_size = 528M
split 00095: n_tensors = 1, total_size = 528M
split 00096: n_tensors = 1, total_size = 630M
split 00097: n_tensors = 1, total_size = 528M
split 00098: n_tensors = 1, total_size = 528M
split 00099: n_tensors = 1, total_size = 528M
split 00100: n_tensors = 1, total_size = 528M
split 00101: n_tensors = 1, total_size = 528M
split 00102: n_tensors = 1, total_size = 528M
split 00103: n_tensors = 1, total_size = 528M
split 00104: n_tensors = 1, total_size = 528M
split 00105: n_tensors = 1, total_size = 630M
split 00106: n_tensors = 1, total_size = 528M
split 00107: n_tensors = 1, total_size = 528M
split 00108: n_tensors = 1, total_size = 528M
split 00109: n_tensors = 1, total_size = 528M
split 00110: n_tensors = 1, total_size = 528M
split 00111: n_tensors = 1, total_size = 528M
split 00112: n_tensors = 1, total_size = 528M
split 00113: n_tensors = 1, total_size = 528M
split 00114: n_tensors = 1, total_size = 630M
split 00115: n_tensors = 1, total_size = 528M
split 00116: n_tensors = 1, total_size = 528M
split 00117: n_tensors = 1, total_size = 528M
split 00118: n_tensors = 1, total_size = 528M
split 00119: n_tensors = 1, total_size = 528M
split 00120: n_tensors = 1, total_size = 528M
split 00121: n_tensors = 1, total_size = 528M
split 00122: n_tensors = 1, total_size = 528M
split 00123: n_tensors = 1, total_size = 630M
split 00124: n_tensors = 1, total_size = 528M
split 00125: n_tensors = 1, total_size = 528M
split 00126: n_tensors = 1, total_size = 528M
split 00127: n_tensors = 1, total_size = 528M
split 00128: n_tensors = 1, total_size = 528M
split 00129: n_tensors = 1, total_size = 528M
split 00130: n_tensors = 1, total_size = 528M
split 00131: n_tensors = 1, total_size = 528M
split 00132: n_tensors = 1, total_size = 630M
split 00133: n_tensors = 1, total_size = 528M
split 00134: n_tensors = 1, total_size = 528M
split 00135: n_tensors = 1, total_size = 528M
split 00136: n_tensors = 1, total_size = 528M
split 00137: n_tensors = 1, total_size = 528M
split 00138: n_tensors = 1, total_size = 528M
split 00139: n_tensors = 1, total_size = 528M
split 00140: n_tensors = 1, total_size = 528M
split 00141: n_tensors = 1, total_size = 630M
split 00142: n_tensors = 1, total_size = 528M
split 00143: n_tensors = 1, total_size = 528M
split 00144: n_tensors = 1, total_size = 528M
split 00145: n_tensors = 1, total_size = 528M
split 00146: n_tensors = 1, total_size = 528M
split 00147: n_tensors = 1, total_size = 528M
split 00148: n_tensors = 1, total_size = 528M
split 00149: n_tensors = 1, total_size = 528M
split 00150: n_tensors = 1, total_size = 630M
split 00151: n_tensors = 1, total_size = 528M
split 00152: n_tensors = 1, total_size = 528M
split 00153: n_tensors = 1, total_size = 630M
split 00154: n_tensors = 1, total_size = 528M
split 00155: n_tensors = 1, total_size = 528M
split 00156: n_tensors = 1, total_size = 630M
split 00157: n_tensors = 1, total_size = 528M
split 00158: n_tensors = 1, total_size = 528M
split 00159: n_tensors = 1, total_size = 630M
split 00160: n_tensors = 1, total_size = 528M
split 00161: n_tensors = 1, total_size = 528M
split 00162: n_tensors = 1, total_size = 630M
split 00163: n_tensors = 1, total_size = 528M
split 00164: n_tensors = 1, total_size = 528M
split 00165: n_tensors = 1, total_size = 630M
split 00166: n_tensors = 1, total_size = 528M
split 00167: n_tensors = 1, total_size = 528M
split 00168: n_tensors = 1, total_size = 630M
split 00169: n_tensors = 1, total_size = 528M
split 00170: n_tensors = 1, total_size = 528M
split 00171: n_tensors = 1, total_size = 630M
split 00172: n_tensors = 1, total_size = 528M
gguf_split: 172 gguf split written with a total of 563 tensors.

Example with 45G max:

 ./gguf-split --split --split-max-size 45G --dry-run /nfs/models/Karasu-Mixtral-8x22B-v0.1-Q5_K_M.gguf /nfs/models/
n_split: 172
split 00001: n_tensors = 101, total_size = 1009M
split 00002: n_tensors = 113, total_size = 1023M
split 00003: n_tensors = 113, total_size = 1023M
split 00004: n_tensors = 68, total_size = 721M
split 00005: n_tensors = 1, total_size = 528M
split 00006: n_tensors = 1, total_size = 630M
split 00007: n_tensors = 1, total_size = 528M
split 00008: n_tensors = 1, total_size = 528M
split 00009: n_tensors = 1, total_size = 630M
split 00010: n_tensors = 1, total_size = 528M
split 00011: n_tensors = 1, total_size = 528M
split 00012: n_tensors = 1, total_size = 630M
split 00013: n_tensors = 1, total_size = 528M
split 00014: n_tensors = 1, total_size = 528M
split 00015: n_tensors = 1, total_size = 630M
split 00016: n_tensors = 1, total_size = 528M
split 00017: n_tensors = 1, total_size = 528M
split 00018: n_tensors = 1, total_size = 630M
split 00019: n_tensors = 1, total_size = 528M
split 00020: n_tensors = 1, total_size = 528M
split 00021: n_tensors = 1, total_size = 630M
split 00022: n_tensors = 1, total_size = 528M
split 00023: n_tensors = 1, total_size = 528M
split 00024: n_tensors = 1, total_size = 630M
split 00025: n_tensors = 1, total_size = 528M
split 00026: n_tensors = 1, total_size = 528M
split 00027: n_tensors = 1, total_size = 528M
split 00028: n_tensors = 1, total_size = 528M
split 00029: n_tensors = 1, total_size = 528M
split 00030: n_tensors = 1, total_size = 528M
split 00031: n_tensors = 1, total_size = 528M
split 00032: n_tensors = 1, total_size = 528M
split 00033: n_tensors = 1, total_size = 630M
split 00034: n_tensors = 1, total_size = 528M
split 00035: n_tensors = 1, total_size = 528M
split 00036: n_tensors = 1, total_size = 528M
split 00037: n_tensors = 1, total_size = 528M
split 00038: n_tensors = 1, total_size = 528M
split 00039: n_tensors = 1, total_size = 528M
split 00040: n_tensors = 1, total_size = 528M
split 00041: n_tensors = 1, total_size = 528M
split 00042: n_tensors = 1, total_size = 630M
split 00043: n_tensors = 1, total_size = 528M
split 00044: n_tensors = 1, total_size = 528M
split 00045: n_tensors = 1, total_size = 528M
split 00046: n_tensors = 1, total_size = 528M
split 00047: n_tensors = 1, total_size = 528M
split 00048: n_tensors = 1, total_size = 528M
split 00049: n_tensors = 1, total_size = 528M
split 00050: n_tensors = 1, total_size = 528M
split 00051: n_tensors = 1, total_size = 630M
split 00052: n_tensors = 1, total_size = 528M
split 00053: n_tensors = 1, total_size = 528M
split 00054: n_tensors = 1, total_size = 528M
split 00055: n_tensors = 1, total_size = 528M
split 00056: n_tensors = 1, total_size = 528M
split 00057: n_tensors = 1, total_size = 528M
split 00058: n_tensors = 1, total_size = 528M
split 00059: n_tensors = 1, total_size = 528M
split 00060: n_tensors = 1, total_size = 630M
split 00061: n_tensors = 1, total_size = 528M
split 00062: n_tensors = 1, total_size = 528M
split 00063: n_tensors = 1, total_size = 528M
split 00064: n_tensors = 1, total_size = 528M
split 00065: n_tensors = 1, total_size = 528M
split 00066: n_tensors = 1, total_size = 528M
split 00067: n_tensors = 1, total_size = 528M
split 00068: n_tensors = 1, total_size = 528M
split 00069: n_tensors = 1, total_size = 630M
split 00070: n_tensors = 1, total_size = 528M
split 00071: n_tensors = 1, total_size = 528M
split 00072: n_tensors = 1, total_size = 528M
split 00073: n_tensors = 1, total_size = 528M
split 00074: n_tensors = 1, total_size = 528M
split 00075: n_tensors = 1, total_size = 528M
split 00076: n_tensors = 1, total_size = 528M
split 00077: n_tensors = 1, total_size = 528M
split 00078: n_tensors = 1, total_size = 630M
split 00079: n_tensors = 1, total_size = 528M
split 00080: n_tensors = 1, total_size = 528M
split 00081: n_tensors = 1, total_size = 528M
split 00082: n_tensors = 1, total_size = 528M
split 00083: n_tensors = 1, total_size = 528M
split 00084: n_tensors = 1, total_size = 528M
split 00085: n_tensors = 1, total_size = 528M
split 00086: n_tensors = 1, total_size = 528M
split 00087: n_tensors = 1, total_size = 630M
split 00088: n_tensors = 1, total_size = 528M
split 00089: n_tensors = 1, total_size = 528M
split 00090: n_tensors = 1, total_size = 528M
split 00091: n_tensors = 1, total_size = 528M
split 00092: n_tensors = 1, total_size = 528M
split 00093: n_tensors = 1, total_size = 528M
split 00094: n_tensors = 1, total_size = 528M
split 00095: n_tensors = 1, total_size = 528M
split 00096: n_tensors = 1, total_size = 630M
split 00097: n_tensors = 1, total_size = 528M
split 00098: n_tensors = 1, total_size = 528M
split 00099: n_tensors = 1, total_size = 528M
split 00100: n_tensors = 1, total_size = 528M
split 00101: n_tensors = 1, total_size = 528M
split 00102: n_tensors = 1, total_size = 528M
split 00103: n_tensors = 1, total_size = 528M
split 00104: n_tensors = 1, total_size = 528M
split 00105: n_tensors = 1, total_size = 630M
split 00106: n_tensors = 1, total_size = 528M
split 00107: n_tensors = 1, total_size = 528M
split 00108: n_tensors = 1, total_size = 528M
split 00109: n_tensors = 1, total_size = 528M
split 00110: n_tensors = 1, total_size = 528M
split 00111: n_tensors = 1, total_size = 528M
split 00112: n_tensors = 1, total_size = 528M
split 00113: n_tensors = 1, total_size = 528M
split 00114: n_tensors = 1, total_size = 630M
split 00115: n_tensors = 1, total_size = 528M
split 00116: n_tensors = 1, total_size = 528M
split 00117: n_tensors = 1, total_size = 528M
split 00118: n_tensors = 1, total_size = 528M
split 00119: n_tensors = 1, total_size = 528M
split 00120: n_tensors = 1, total_size = 528M
split 00121: n_tensors = 1, total_size = 528M
split 00122: n_tensors = 1, total_size = 528M
split 00123: n_tensors = 1, total_size = 630M
split 00124: n_tensors = 1, total_size = 528M
split 00125: n_tensors = 1, total_size = 528M
split 00126: n_tensors = 1, total_size = 528M
split 00127: n_tensors = 1, total_size = 528M
split 00128: n_tensors = 1, total_size = 528M
split 00129: n_tensors = 1, total_size = 528M
split 00130: n_tensors = 1, total_size = 528M
split 00131: n_tensors = 1, total_size = 528M
split 00132: n_tensors = 1, total_size = 630M
split 00133: n_tensors = 1, total_size = 528M
split 00134: n_tensors = 1, total_size = 528M
split 00135: n_tensors = 1, total_size = 528M
split 00136: n_tensors = 1, total_size = 528M
split 00137: n_tensors = 1, total_size = 528M
split 00138: n_tensors = 1, total_size = 528M
split 00139: n_tensors = 1, total_size = 528M
split 00140: n_tensors = 1, total_size = 528M
split 00141: n_tensors = 1, total_size = 630M
split 00142: n_tensors = 1, total_size = 528M
split 00143: n_tensors = 1, total_size = 528M
split 00144: n_tensors = 1, total_size = 528M
split 00145: n_tensors = 1, total_size = 528M
split 00146: n_tensors = 1, total_size = 528M
split 00147: n_tensors = 1, total_size = 528M
split 00148: n_tensors = 1, total_size = 528M
split 00149: n_tensors = 1, total_size = 528M
split 00150: n_tensors = 1, total_size = 630M
split 00151: n_tensors = 1, total_size = 528M
split 00152: n_tensors = 1, total_size = 528M
split 00153: n_tensors = 1, total_size = 630M
split 00154: n_tensors = 1, total_size = 528M
split 00155: n_tensors = 1, total_size = 528M
split 00156: n_tensors = 1, total_size = 630M
split 00157: n_tensors = 1, total_size = 528M
split 00158: n_tensors = 1, total_size = 528M
split 00159: n_tensors = 1, total_size = 630M
split 00160: n_tensors = 1, total_size = 528M
split 00161: n_tensors = 1, total_size = 528M
split 00162: n_tensors = 1, total_size = 630M
split 00163: n_tensors = 1, total_size = 528M
split 00164: n_tensors = 1, total_size = 528M
split 00165: n_tensors = 1, total_size = 630M
split 00166: n_tensors = 1, total_size = 528M
split 00167: n_tensors = 1, total_size = 528M
split 00168: n_tensors = 1, total_size = 630M
split 00169: n_tensors = 1, total_size = 528M
split 00170: n_tensors = 1, total_size = 528M
split 00171: n_tensors = 1, total_size = 630M
split 00172: n_tensors = 1, total_size = 528M
gguf_split: 172 gguf split written with a total of 563 tensors.
