### ISSUE TITLE
Low GPU usage of quantized Mixtral 8x22B for prompt processing on Metal

### ISSUE THREAD

**Issue by beebopkim** [ggerganov/llama.cpp#6642]
My computer is M1 Max Mac Studio with 32 Cores of GPU with 64 GB of RAM. macOS version is Sonoma 14.4.1.

I run `llama-bench` from commit 4cc120c7443cf9dab898736f3c3b45dc8f14672b and it shows low GPU usage for prompt processing. Of course, inferences on `main` and `server` show same low GPU usages.

![Screenshot 2024-04-13 at 12 40 32 AM-2](https://github.com/ggerganov/llama.cpp/assets/8567128/3ca3614e-f8e5-46dc-b504-06714a10cb97)

In the above image, I run benchmark for IQ2_XXS, IQ2_XS, IQ2_S, IQ2_M, and Q2_K_S but IQ1_S and IQ1_M from https://huggingface.co/MaziyarPanahi/Mixtral-8x22B-v0.1-GGUF will show same low GPU usage.

**Comment by stefanvarunix** [comment]
#6740
