### ISSUE TITLE
Some warnings like "...reallocate multi buffer graph..." when compiled by Qt

### ISSUE THREAD

**Issue by ngbruce** [ggerganov/llama.cpp#6643]
System :
UBUNTU

GPU：
RTX 2080ti + Tesla P40

Software env: 
Qt creator 12.0.2 with Qt 6.6.2

Problem:

After I download this project, I followed the instruction to complied it with option  -DLLAMA_CUBLAS=ON , using ubuntu system terminal, everything was fine.
I tried the model of Qwen1.5 7B , 14B and 72B , they all works fine on single GPU or 2 GPUs.

Then I open this project with Qt creator because I want to write some GUI for it . I first compiled the whole project in Qt environment for test. It also looks fine and compile finished seems no warnings.
But when I run those models, there were below warnings pop up in the terminal from time to time , when the model generating answer.
```
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: cannot reallocate multi buffer graph automatically, call reserve
ggml_backend_sched_alloc_splits: failed to allocate graph, reserving
```

There won't be these warnings if I compiled the project in ubuntu terminal, only happens when compiled in Qt.

Please advise if something I did wrong, thanks.

**Comment by slaren** [comment]
These are debug prints, and can be disabled by building with `NDEBUG`. They shouldn't appear in release builds.
