### ISSUE TITLE
Unexpected Space After Two Line Breaks in Command R Plus Output

### ISSUE THREAD

**Issue by LisaMacintosh** [ggerganov/llama.cpp#6647]
System - M2 Max Mac Studio 96gb

I've noticed an unusual behavior in Command R Plus. When the model outputs text with two line breaks, it tends to add an extra space before the start of a new sentence. This seems to be inconsistent and affects the formatting of the generated text and seems to compound overtime using multi turn responses. 

Steps to Reproduce:

1. Provide an input prompt to Command R Plus that requires a multi-paragraph response.
2. Observe the output and look for instances where there are two line breaks followed by a new sentence.

You can also try to prompt a Choose Your Own Adventure (CYOA) story format using '>' or any other symbol to indicate different paths and include multiple line breaks. Verify if the same issue occurs with the extra spaces.

Example of Output:

```
> You are a talented software developer working on a new feature for a popular open-source project hosted on GitHub. As you're about to commit your changes, you realize you forgot to update the documentation. What do you do?
 
> Option 1: You quickly update the documentation, knowing that clear docs are crucial for other contributors.

 > As you update the docs, you notice a bug in your code. Do you:

   > A) Fix the bug immediately, ensuring your code is pristine before committing.

 > B) Leave a TODO comment about the bug and continue with the commit, trusting future you to handle it.

> Option 2: You decide to skip the documentation update, thinking you can do it later.

  > As you skip the docs, a fellow contributor messages you about a potential security vulnerability they found in your code. Do you:

    > A) Thank them profusely and immediately start investigating, knowing security is paramount.

     > B) Assure them you'll look into it later, hoping it's not a big deal.

 There, a CYOA adventure centered around a GitHub developer! I can continue the story further if you'd like, or we can explore a different theme. 
 ```

In this example, there's a space added before "There" but also all of the `>` symbols are also being formatted in the same way and compound randomly. This can happen with any symbol, not just spaces i.e `(, *, -, +, etc.`

This effect increases over time.

I've tried different quants, default prompt template, multi-shot with correct grammar/template, and sampler settings but they all reproduce the same issue. Something interesting I've seen in the tokenizer is that it tends to use ` \n\n\` as a token before adding ` `(blank space) before the new sentence.

```
Generating (25 / 1024 tokens) [( thoughts 100.00%) ( Thoughts 0.00%) ( take 0.00%) (thought 0.00%)]
Generating (26 / 1024 tokens) [( on 100.00%) ( about 0.00%) ( \n 0.00%) ( \n\n 0.00%)]
Generating (27 / 1024 tokens) [(? 100.00%) (. 0.00%) (... 0.00%) (\n\n 0.00%)]
Generating (28 / 1024 tokens) [( \n\n 93.94%) (\n\n 6.04%) ( I 0.02%) ( \n 0.00%)]
Generating (29 / 1024 tokens) [( ( 100.00%) (\n 0.00%) (  0.00%) ( [ 0.00%)]
Generating (30 / 1024 tokens) [(I 100.00%) (You 0.00%) (My 0.00%) ( I 0.00%)]
Generating (31 / 1024 tokens) [('m 99.99%) ( want 0.01%) ( could 0.00%) ('ll 0.00%)]
Generating (32 / 1024 tokens) [( always 94.85%) ( here 5.15%) ( curious 0.00%) ( a 0.00%)]
```

More examples (screenshots):

![image](https://github.com/ggerganov/llama.cpp/assets/51481552/10a2dbe5-15f9-4565-a7aa-b996fb1c177b)

![image](https://github.com/ggerganov/llama.cpp/assets/51481552/c1b1f4b1-e5ff-4921-afa5-3a16d5779818)

![image](https://github.com/ggerganov/llama.cpp/assets/51481552/0cc0dd5e-bb54-4672-b36c-7ccea1bd532f)

**Comment by Jeximo** [comment]
> I've noticed an unusual behavior in Command R Plus ... I've tried different quants, default prompt template, multi-shot 

Hi. It's unusual.  Maybe try a recent update https://github.com/ggerganov/llama.cpp/releases/tag/b2673

`--chat-template command-r` should work for `server`.
