### ISSUE TITLE
Mixtral 8x7b models using more memory while loading

### ISSUE THREAD

**Issue by RyenNelsen** [ggerganov/llama.cpp#6652]
There appears to be a regression between release versions **b2586** and **b2589**. When attempting to load Mixtral 8x7b models with any version greater than **b2586**, the system utilizes an abnormal amount of memory compared to previous versions. Manually disabling `mmap` does resolve the issue.

Platform:
Windows 11 Pro
64GB RAM
Nvidia 3080

Example command:
`.\main.exe -m 'C:\models\dolphin-2.7-mixtral-8x7b.Q5_0.gguf' -p "<|im_start|>user\nHello!\n<|im_end|>\n<|im_start|>assistant\n"`

Versions I tested:
**b2586** cuda cu12.2.0 & openblas
![version b2586 memory loading graph](https://github.com/ggerganov/llama.cpp/assets/10788652/ec80e0e6-8a0b-40af-8630-4684d33d1d21)

**b2589** cuda cu12.2.0 & openblas
![version b2589 memory loading graph cuda & openblas](https://github.com/ggerganov/llama.cpp/assets/10788652/83f001e9-9483-474b-b952-9a38e72cece7)

**b2589** avx512
![version b2589 memory loading graph avx512](https://github.com/ggerganov/llama.cpp/assets/10788652/f0ab7967-7ffb-4003-b138-53f140ab4ca1)

Diffing log output from **b2586** cuda cu12.2.0 and **b2589** cuda cu12.2.0 shows the following:
**b2586**: `llm_load_tensors:        CPU buffer size = 30735.50 MiB`
**b2589**: `llm_load_tensors:  CUDA_Host buffer size = 30735.50 MiB`

**Comment by compilade** [comment]
This is related to #6387. A solution would be to re-convert the model to GGUF from the original model files.

**Comment by LostRuins** [comment]
I can confirm this seems to happen for me too, I'm getting OOM at configs which worked fine previously.

**Comment by phymbert** [comment]
Yes that's why #6387 is a breaking changes. You need to convert to GGUF again to have merged experts tensors per layer or disable mmap.

It is clearly stated here:
https://github.com/ggerganov/llama.cpp/pull/6387#issuecomment-2033241621

**Comment by aleksusklim** [comment]
@slaren, @phymbert, can you look please?
https://github.com/LostRuins/koboldcpp/issues/786

**Comment by pjh64** [comment]
Why is this issue closed? It is still a thing that b2586 was the last build of llama.cpp that was able to load Mixtral 8x7b without throwing "...................Killed".
