### ISSUE TITLE
cmake build on windows completes, but quantize. exe is not built; advice?

### ISSUE THREAD

**Issue by jim-plus** [ggerganov/llama.cpp#6678]
I followed the instructions for building on Windows using cmake from the README.md file. cmake completes and builds a lot of stuff in the process, but not quantize.exe on my Windows 11 PC.

I have current Visual Studio Community, Nvidia CUDA Toolkit 12.1, torch 2.2.1+cu121, and cmake 3.28.3.

I would not be surprised if this is a "skill issue", possibly involving requirements, as I am not yet very experienced with cmake. I can run prebuilt quantize.exe from compiled releases without problem, so I have a workaround.

**Comment by Jeximo** [comment]
> but not quantize.exe on my Windows 11 PC

https://github.com/ggerganov/llama.cpp/issues/103#issuecomment-1466990359 suggested
```
cmake -S . -B build/ -D CMAKE_BUILD_TYPE=Release

cmake --build build/ --config Release
```
Afterwards, the exe files should be in the build/Release folder.

**Comment by jim-plus** [comment]
That did the trick. Thanks!

**Comment by jim-plus** [comment]
That did the trick. Thanks!
