### ISSUE TITLE
Has the args "-- parallel N" not been developed yet? ./server -m xx -ng 10

### ISSUE THREAD

**Issue by mgr9525** [ggerganov/llama.cpp#6681]
I attempted to run the HTTP server using "./server -m xx -ng 10" and tested it by making HTTP API calls. I noticed that when there is only one request, everything works fine. However, if I make a new HTTP request while a previous request is still generating a response, the answers from both requests become mixed up or scrambled.

Could it be because the parameter changes haven't reached a stable version yet or there hasn't been any thread-safety handling?

I would like to ask when I can enter the stable version. Thanks!!!

**Comment by phymbert** [comment]
The server is supporting well the `--parallel N` parameter. 
Please provide all the steps you have followed to reproduce your issue.

**Comment by mgr9525** [comment]
okey. very willing to. Thank you for bringing such a great project.

model: https://huggingface.co/Qwen/Qwen1.5-14B-Chat  ([or](https://www.modelscope.cn/models/qwen/Qwen1.5-14B-Chat/summary))


I converted the model myself:

```
# convert
python3 convert-hf-to-gguf.py /mnt/modelDir/qwen/Qwen1___5-14B-Chat/

# quantize
./quantize /mnt/modelDir/qwen/Qwen1___5-14B-Chat/ggml-model-f16.gguf Q4_K_M
```


llama.log:
```
[1713168334] warming up the model with an empty run
```

std.log:
[std.log](https://github.com/ggerganov/llama.cpp/files/14975926/std.log)

**Comment by phymbert** [comment]
OK, I see a lot of context shifting.

I believe your KV Cache size is too small (only 51 tokens max per slot), context per slot is `--ctx-size` / `--parallel`.

So if prompt size + generated tokens size exceeds n_ctx_slot, it will trigger context shifting, that I presume @ggerganov to be not properly working, at least not tested properly in the server test framework.

It would be awsesome @mgr9525 to try to reproduce using [a server test scenario](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

Please run the server this way:

```shell
./server  \
 --model /mnt/modelDir/qwen/Qwen1___5-14B-Chat/ggml-model-Q4_K_M.gguf \
 --n-predict 4096 \
 -ngl 41 \
--ctx-size 32768 \
 --parallel 10 \
--host 0.0.0.0 \
--batch-size 4096 \
--ubatch-size 256 \
--log-format text
```

Adjust the context size depending on your VRAM.

**Comment by mgr9525** [comment]
Thanks @phymbert , it works !!

It's because I didn't understand ctx size, thank you very much. Is there any documentation related to ctx size. For example, the relationship between these `--ctx-size`, `--batch-size`, `--ubatch-size`.

**Comment by phymbert** [comment]
> Thanks @phymbert , it works !!

Great, you are welcome. 


> Is there any documentation related to ctx size. For example, the relationship between these `--ctx-size`, `--batch-size`, `--ubatch-size`.

If the server Readme.md is not clear enough, please ask for additional clarification here.

**Comment by mgr9525** [comment]
@phymbert At the beginning, the problem arose again (which is not easy to reproduce). When multiple requests are concurrent, the previous requests may have a situation where a certain token keeps repeating.

The screenshots here show two requests, but in fact, I have two more requests open later, the same problem.

![a06dc725c7f0aab11765d3e68271694](https://github.com/ggerganov/llama.cpp/assets/9899755/8468303e-e24d-478d-baa6-f22aa657d893)

**Comment by phymbert** [comment]
Sorry I do not understand how I can help you

**Comment by mgr9525** [comment]
Okey,Thanks @phymbert

**Comment by phymbert** [comment]
I meant, I need a reproducible way with server stdout, logs, configuration and requests.

**Comment by mgr9525** [comment]
Reproduced once again

**Comment by mgr9525** [comment]
Reproduced once again
[Pictures.zip](https://github.com/ggerganov/llama.cpp/files/14977689/Pictures.zip)

**Comment by mgr9525** [comment]
> 32 sequences, each with 4096 tokens requires a KV cache of size `32*4096 = 131072` in order to handle the worst case, so this setup should theoretically run out of KV cache slots. Not sure about the error that you get though, but it could be related

Solved it, will close.

**Comment by mgr9525** [comment]
> 32 sequences, each with 4096 tokens requires a KV cache of size `32*4096 = 131072` in order to handle the worst case, so this setup should theoretically run out of KV cache slots. Not sure about the error that you get though, but it could be related

Solved it, will close.
