### ISSUE TITLE
Multi models on multigpu

### ISSUE THREAD

**Issue by Slyb00ts** [ggerganov/llama.cpp#6700]
Hi,

is there a way to run few models on few GPUs? What i mean by that is to run for example:
1. Model A on GPU 0
2. Model B on GPU 1
3. Model C on GPU 2 + 3

**Comment by 8XXD8** [comment]
You can use the `CUDA_VISIBLE_DEVICES` environment variable for Nvidia, or  `HIP_VISIBLE_DEVICES` for AMD.

 ```
CUDA_VISIBLE_DEVICES=0 ./server -m /.../model1.gguf
 CUDA_VISIBLE_DEVICES=1  ./server -m /.../model2.gguf
 CUDA_VISIBLE_DEVICES=2,3  ./server -m /.../model3.gguf
 
```

**Comment by Slyb00ts** [comment]
thx for answer, but im asking if its possible to do from code
