### ISSUE TITLE
convert model to gguf fail

### ISSUE THREAD

**Issue by Tzyito** [ggerganov/llama.cpp#6718]
# Motivation

I tried converting this [model](https://huggingface.co/facebook/m2m100_418M) on hf to .gguf but failed.

when i was run `$ python3 ./convert-hf-to-gguf.py ./model --outtype f16 --outfile converted.bin `, then got an error.
```
NotImplementedError: Architecture 'M2M100ForConditionalGeneration' not supported!。
```
I would like to know is there any reason why this type of model is not supported

**Comment by bondeg** [comment]
any updates?
