### ISSUE TITLE
Problem with multiple simultaneous API calls on the embeddings endpoint

### ISSUE THREAD

**Issue by itodorovic** [ggerganov/llama.cpp#6722]
Hello,

I'm using separate instance of the server just to generate the embedding for the RAG pipelines. This instance is not used for general chat use, just for embeddings.

The issue is that while the API call to `http://<server>:8080/v1/embeddings` is not completed, which can last for a long time during document embedding, the server does not respond to the next API call to the same endpoint. 

I have tried to overcome this limitation by adding `--threads-http 4 --parallel 4` switches when running the server, like this:

`podman run -d --device nvidia.com/gpu=all -v /opt/models:/models:Z -p 8080:8000 ghcr.io/ggerganov/llama.cpp:server-cuda -m /models/uae-large-v1-f32.gguf --port 8000 --host 0.0.0.0 --n-gpu-layers 16 --threads 12 --threads-http 4 --parallel 4 --metrics --embedding --alias embedding --ctx-size 512`

This caused that after the first call I get this error and server crashes:
`GGML_ASSERT: llama.cpp:9612: seq_id < n_tokens && "seq_id cannot be larger than n_tokens with pooling_type == CLS"`

Am I doing something wrong? Is server supposed to process the API calls in parallel on the embedding API endpoint, or this is not even possible?

**Comment by phymbert** [comment]
Yes, if you have 4 slots/sequences, it will divide the KV Cache size by 4, so 512 is not enough.

I assume `uae-large-v1` supports 1024 max tokens. And for embedding physical batch size must be equals to the context size of the sequence. Try:

```shell
server-cuda -m /models/uae-large-v1-f32.gguf --port 8000 --host 0.0.0.0 --n-gpu-layers 16 --parallel 4 --metrics --embedding --alias embedding --ctx-size 4096 --batch-size 1024 --ubatch-size 1024 --log-format text
```
Please close the issue if it resolves your concerns.

**Comment by phymbert** [comment]
@ggerganov Thoughts ?

**Comment by ggerganov** [comment]
I think this means one of your requests has less than 4 tokens. It's technically a bug that we need to fix, but I thought it's not high priority since I figured not much point in embedding such small data. Can you confirm this is the cause?

**Comment by itodorovic** [comment]
Yes, that is the case. Did not know that small amount of text can be the limitation, since one can not control it always when you vectorize documents, splitting the text is not quite controllable.

Does this mean that if we and something to the end of every string, as a workaround before this is fixed, we should not get this problem?

**Comment by ggerganov** [comment]
Yes, that's the most naive fix for now

**Comment by itodorovic** [comment]
Thank you very much, I'll close this Issue now since there is a workaround, and you are aware of the root cause.

**Comment by PaulCapestany** [comment]
It looks like this may have been fixed at some point? At least, for me, I don't seem to be running into the issue anymore...

**Comment by thiner** [comment]
The model supports 

> I think this means one of your requests has less than 4 tokens. It's technically a bug that we need to fix, but I thought it's not high priority since I figured not much point in embedding such small data. Can you confirm this is the cause?

I am getting this error while running `gte-qwen2-1.5b`.
```
slot launch_slot_: id  3 | task 183 | processing task

 slot update_slots: id  3 | task 183 | new prompt, n_ctx_slot = 8000, n_keep = 0, n_prompt_tokens = 3

 slot update_slots: id  3 | task 183 | kv cache rm [0, end)

 slot update_slots: id  3 | task 183 | prompt processing progress, n_past = 3, n_tokens = 3, progress = 1.000000

 slot update_slots: id  3 | task 183 | prompt done, n_past = 3, n_tokens = 3

 /app/src/llama-graph.cpp:155: GGML_ASSERT(seq_id < n_tokens && "seq_id cannot be larger than n_tokens with pooling_type == MEAN") failed
```
So this bug is remaining unfixed?
