### ISSUE TITLE
Offload kv to smaller GPU

### ISSUE THREAD

**Issue by Happenedtostumblein** [ggerganov/llama.cpp#6729]
Example use case:

70b model with large context loads with two 3090s without kv offloading.

Adding a smaller GPU like a 3040 won’t currently make it possible to make use of offloading, but what if we dedicated that smaller GPU to store the kv?

Seems like this could lead to significantly increased speeds (and long contexts), but maybe there are holes in my understanding.

Curious if anyone more knowledgable has any input on this?

**Comment by JohannesGaessler** [comment]
I don't see the benefit over the current `--tensor-split` argument.

**Comment by Happenedtostumblein** [comment]
And I know nothing, but I find it strange that two 3090s can fit a 70b @ 32k word context and nkvo with plenty of room to spare. Yet two 3090s + 3060 cannot allocate enough memory even with tiny batch size.

I’m sure it must make sense, but thought I’d clarify just in case I’m on to something after all? Danke @JohannesGaessler
