### ISSUE TITLE
Llama only uses dedicated memory when both shared and dedicated are available.

### ISSUE THREAD

**Issue by jadbox** [ggerganov/llama.cpp#6743]
Hey folks, the Razer Blade18 4090 has both dedicated and shared memory, but it seems most applications like Llama only are designed to access the dedicated. Is there a way to utilize both for performance video memory pipelining?

![Screenshot 2024-04-18 095137](https://github.com/ggerganov/llama.cpp/assets/595843/165e22b5-7a1f-44f8-b738-a43869d85597)
![Screenshot 2024-04-18 095430](https://github.com/ggerganov/llama.cpp/assets/595843/fd787a6e-5632-4a7a-902a-78f1540343e4)

Linked reddit thread on the 4090 with both dedicated and shared:
https://www.reddit.com/r/nvidia/comments/1c73zaf/my_4090_blade18_has_both_dedicated_and_shared/

**Comment by saostad** [comment]
I have the same question. Why does it never use the GPU-shared memory? 


![gpu memory](https://github.com/ggerganov/llama.cpp/assets/16025625/73662232-64ae-4274-b1c6-7cb670c8d026)

**Comment by HamzaYslmn** [comment]
same

**Comment by RazyRo** [comment]
?

**Comment by ctrysbita** [comment]
because shared gpu memory is not the real memory in your gpu card

**Comment by alirezanet** [comment]
> because shared gpu memory is not the real memory that is connected to gpu chip

that is correct but using GPU-shared memory will increase the performance since GPU doesn't have to ask the CPU to access the data in the memory.

**Comment by Mr-Thack** [comment]
Hi, reopening because it's still an issue. I would like to run LLAMA3.1:70b locally, and my GPU ran out of RAM, but it has shared Memory, which should be much faster since the GPU doesn't have to ask the CPU for it and can directly access it from the RAM sticks. It is running really slowly right now, Please point me in the right direction, and if it's possible, I'd be willing to write the code for it myself.

**Comment by Mugane** [comment]
Odd that there still is no response to this. What is the point of shared GPU memory if the GPU cannot use the memory? This is a major issue!

**Comment by yuppox** [comment]
I am having trouble that Ollama is max'ing out my GPU RAM and then outputting garbage instead of using shared RAM (which shows as part of my total GPU memory).

**Comment by Mugane** [comment]
Shared memory is a farce, you're stuck with either cpu+ram, gpu+vram or I've heard you can do cpu+mapped memory on nvme ssd (but I haven't got it working yet)

**Comment by sorasoras** [comment]
> > because shared gpu memory is not the real memory that is connected to gpu chip
> 
> that is correct but using GPU-shared memory will increase the performance since GPU doesn't have to ask the CPU to access the data in the memory.

that's not true, gpu still use the ram from the system

**Comment by yuppox** [comment]
> I am having trouble that Ollama is max'ing out my GPU RAM and then outputting garbage instead of using shared RAM (which shows as part of my total GPU memory).

Note that when I tried to load a model that is much bigger than my available GPU RAM, Ollama used both GPU RAM and shared RAM. However, it seemed to use the CPU for processing. I didn't encounter the garbage output bug.

**Comment by Mugane** [comment]
Again you cannot use shared memory for gpu inference. The transfer speed is too slow.

**Comment by yuppox** [comment]
> Again you cannot use shared memory for gpu inference. The transfer speed is too slow. Unless you have a mac then the gpu is on the same chipset and everything is shared.

Thanks for the reply. Then it makes sense that the CPU is used when shared memory is used. This still brings up two considerations:

1. There is still a bug with near-full GPU RAM usage
2. Why does it still use a considerable amount of GPU RAM when it uses CPU + RAM?

**Comment by Mugane** [comment]
@yuppox My only guess is that possibly you're using a version of open-webui that's running in "arena" mode where it's firing up multiple models at the same time? That or a previous model/session is still in GPU memory? It may help to have a full system description (specs) and steps to reproduce. I haven't seen this behavior on windows or linux, running via open-webui or ollama directly (terminal).

**Comment by yuppox** [comment]
> [@yuppox](https://github.com/yuppox) My only guess is that possibly you're using a version of open-webui that's running in "arena" mode where it's firing up multiple models at the same time? That or a previous model/session is still in GPU memory? It may help to have a full system description (specs) and steps to reproduce. I haven't seen this behavior on windows or linux, running via open-webui or ollama directly (terminal).

Are you referring to the second problem? I don't know what "arena" mode is. I am running ollama from CLI. I only have enough RAM for one mode model and I made sure the GPU RAM was cleared, first.

Maybe I should open a bug for the first problem.

**Comment by AaronLayton** [comment]
> Changing this driver setting fixed it for me.
> 
> ![Image](https://github.com/user-attachments/assets/1880c352-2113-4a67-9287-0dd3e2fce30a)

Can you confirm if any performance issues with this approach?
