### ISSUE TITLE
Update convert.py to accept these argument choices for quantization 

### ISSUE THREAD

**Issue by krecicki** [ggerganov/llama.cpp#6744]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ *] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [* ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [* ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ *] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

This space https://huggingface.co/spaces/ggml-org/gguf-my-repo has all of the q2_k through f32. In the current convert.py  this line ```convert.py: error: argument --outtype: invalid choice: 'q2_k' (choose from 'f32', 'f16', 'q8_0')``` was thrown and upon checking the convert.py file, it infact only supports ```'f32', 'f16', 'q8_0```

# Motivation

I don't want to rely on someone else's space for this. I want to be able to run it locally like I do already but for all quants.

# Possible Implementation

ggml already did it, https://huggingface.co/spaces/ggml-org/gguf-my-repo

**Comment by phymbert** [comment]
First `ggml-org` is owned by @ggerganov, that's one of the reason HuggingFace team developped the app there. It's way faster than you will ever manage to do it locally.

Secondly, quantization is c++ based and requires the usage of `quantize` CLI, as you can see in the HF code:
https://huggingface.co/spaces/ggml-org/gguf-my-repo/blob/main/app.py#L63

So I believe what you are requiring is legitimate but not possible in python script (asuming we do not want to call `quantize` there.
