### ISSUE TITLE
Does GGUF consist of a feedforward architecture model with weights?

### ISSUE THREAD

**Issue by abdalluhahmed** [ggerganov/llama.cpp#6759]
Does GGUF consist of a feedforward architecture model with weights?

**Comment by ggerganov** [comment]
[GGUF](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md) is a file format

**Comment by abdalluhahmed** [comment]
brother, i mean gguf for Liama models sucha as ''codellama-7b-instruct.Q4_K_S.gguf''
