### ISSUE TITLE
[Feature Suggestion] Halide-lang codegen / generators

### ISSUE THREAD

**Issue by eszdman** [ggerganov/llama.cpp#676]
# Prerequisites
Examples of work with neural networks in Halide:
https://github.com/halide/Halide/blob/main/apps/resnet_50/Resnet50Generator.cpp
https://github.com/halide/Halide/tree/main/apps/hannk
https://github.com/halide/Halide/blob/main/apps/onnx/model.cpp

# Expected Behavior

Cross platform binary and code generation with best scheduling on computational graph applied by Halide or Halide autoschedulers, reduced memory usage by scheduling every used network model before execution

# Current Behavior

Multiple conditional defines for different platforms and instruction bloated code, lack of GPU support i.e. OpenCL, OpenGL Compute, CUDA, current computational graph has great parallelism but very frustrating locality

**Comment by ei-grad** [comment]
Despite of Apr 1, it should be pretty straightforward to translate llama.cpp graph for some model to halide, to experiment on performance improvement which could be possible to achieve.
