### ISSUE TITLE
server llama3 stopping word

### ISSUE THREAD

**Issue by Freeshman** [ggerganov/llama.cpp#6772]
Hi, I use the llama3 8b model with server, the output seems wired with something like "xxxxx.assistant\n\n." and continue like this without stopping.

After checking the log and llama3 8b relative information, the server doesn't stop when it meets stopping word.

I found function size_t find_stopping_strings(const std::string & text, const size_t last_token_size, const stop_type type)  in server.cpp which compare the stopping word (string) with text. 

For llama3 8b, stopping word is "<|eot_id|>" (token = 128009), but token 128009 is "" for server. I think this might be the cause that server failed to check the reverse prompt.

**Comment by Freeshman** [comment]
I tried going deeper, in llama.cpp file's function int32_t llama_token_to_piece(const struct llama_model * model, llama_token token, char * buf, int32_t length), onece llama_is_control_token(model->vocab, token) is true, then the buf is empty. Maybe the model I used add LLAMA_TOKEN_TYPE_CONTROL for some tokens.

**Comment by Freeshman** [comment]
I copied the code inside the llama_is_normal_token subsection into llama_is_control_token subsection like this:
`if (llama_is_control_token(model->vocab, token)) {
                std::string result = model->vocab.id_to_token[token].text;
                llama_unescape_whitespace(result);
                if (length < (int) result.length()) {
                    return -(int) result.length();
                }
                memcpy(buf, result.c_str(), result.length());
                return result.length();
`
then server works as expected.

**Comment by redthing1** [comment]
Here is an alternative solution, that worked for me: https://old.reddit.com/r/LocalLLaMA/comments/1c7dkxh/tutorial_how_to_make_llama3instruct_ggufs_less/

**Comment by jukofyork** [comment]
> Here is an alternative solution, that worked for me: https://old.reddit.com/r/LocalLLaMA/comments/1c7dkxh/tutorial_how_to_make_llama3instruct_ggufs_less/
> 
> > Problem: Llama-3 uses 2 different stop tokens, but llama.cpp only has support for one. The instruct models seem to always generate a <
> 
> > |eot_id|> but the GGUF uses <|end_of_text|>.
> > Solution: Edit the GGUF file so it uses the correct stop token.
> > How:
> > prerequisite: You must have llama.cpp setup correctly with python. If you can convert a non-llama-3 model, you already have everything you need!
> > After entering the llama.cpp source directory, run the following command:
> > ./gguf-py/scripts/gguf-set-metadata.py /path/to/llama-3.gguf tokenizer.ggml.eos_token_id 128009
> > You will get a warning:
> > 
> > * Preparing to change field 'tokenizer.ggml.eos_token_id' from 100 to 128009
> >   *** Warning *** Warning *** Warning **
> > * Changing fields in a GGUF file can make it unusable. Proceed at your own risk.
> > * Enter exactly YES if you are positive you want to proceed:
> >   YES, I am sure>
> > 
> > From here, type in YES and press Enter.
> > Enjoy!

Yeah, I did this and it did stop the AI but it ends with "<|eot_id|>" so I added "<|eot_id|>" as a stop token. Using `gguf-dump` I can confirm I have made the change from the reddit thread but I don't understand why it prints "<|eot_id|>"??? 

From the sever readme:

> stop: Specify a JSON array of stopping strings. These words will not be included in the completion, so make sure to add them to the prompt for the next iteration. Default: []

So it looks like it's important to add the back next turn now as it won't get treated as a normal EOS token for some reason...

I'm using Ollama for this too, so have absolutely no clue what is actually going to get passed to the server now 😕
