### ISSUE TITLE
[WSL2] [Installation] make not compiling 

### ISSUE THREAD

**Issue by smokeyhallow** [ggerganov/llama.cpp#679]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

`make` should compile.

# Current Behavior

`make` the second step after cloning the repo printed the help rather than "making".

<details>
  <summary>help text for `make`</summary>

<pre><code>
  $ make <target...> [options]

  Options:
    --help             Show this help output
    --version          Show package version
    --debug            Enable extended log output

  Targets:
    UNAME_S            Run target UNAME_S
    UNAME_P            Run target UNAME_P
    UNAME_M            Run target UNAME_M
    CCV                Run target CCV
    CXXV               Run target CXXV
    default            Run target default
    ggml.o             Run target ggml.o
    llama.o            Run target llama.o
    common.o           Run target common.o
    clean              Run target clean
    main               Run target main
    quantize           Run target quantize
    perplexity         Run target perplexity
    embedding          Run target embedding
    tests              Run target tests

  Templates:
    ava                Generate ava setup (ava)
    cli                Generate cli setup (minimist, tabtab, ge...)
    default            Generate default setup (babel-cli, babel-plu...)
    eslint             Generate eslint setup (eslint, eslint-confi...)
    livereactload      Generate livereactload setup (babel-plugin-react-t...)
    mocha              Generate mocha setup (mocha)
    simple             Generate simple setup
</pre></code>
</details>

# Environment and Context 

### OS

- WSL2
- Ubuntu 22.04
- Windows 10

### Hardware

- 32GB RAM
- AMD 
- Nvidia 3060

### `$ lscpu`

<details>
<summary>`lscpu`</summary>
<pre>
<code>
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 3700X 8-Core Processor
CPU family:                      23
Model:                           113
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7186.49
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat umip rdpid
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
</code>
</pre>
</details>

* Operating System, e.g. for Linux:

### `$ uname -a`

`Linux windows 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### SDK version, e.g. for Linux:

```
$ python3 --version => 3.9.12
$ make --version => 0.8.1
$ g++ --version => g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

**Comment by gjmulder** [comment]
@smokeyhallow good first effort at a description. Please copy/paste from your terminal every step you did from cloning the repo until the make.

**Comment by smokeyhallow** [comment]
I got stuck exactly at the second step. There is no other steps! 

I followed the [README's Usage](https://github.com/ggerganov/llama.cpp#usage) section:

```
# exact steps from README
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
make

RESULT: <help from make>
```

**Comment by smokeyhallow** [comment]
But interestingly gpt4all worked for me! So, my system resources/requirements isn't the issue! Also, I am using conda if that helps

**Comment by saradhix** [comment]
I guess you are not using gnu's make util. 
`make --version` should give value around 4.3, something similar to this.

```GNU Make 4.3
Built for x86_64-pc-linux-gnu```

**Comment by smokeyhallow** [comment]
> I guess you are not using gnu's make util. `make --version` should give value around 4.3, something similar to this.
> 
> `GNU Make 4.3 Built for x86_64-pc-linux-gnu`

Exactly!!! I am not using it, but it wasn't mentioned anywhere!!! Let me try this!

**Comment by smokeyhallow** [comment]
Oh wow! I found the solution after days of scratching of my head!

My `make` was pointing to some other executable put in the path by volta.sh!!! Such a shit show! I don't know why they do it! Just used absolute path to the executable and it worked!!!

**Comment by gjmulder** [comment]
It is one of the dangers of programming in JS.
