### ISSUE TITLE
Support for InternVL

### ISSUE THREAD

**Issue by chigkim** [ggerganov/llama.cpp#6803]
New [InternVL-Chat-V1.5](https://github.com/OpenGVLab/InternVL) just came out, and the quality is really great, and the benchmark score is pretty high too. Possibly best open source vision language model yet?

Can we have llama.cpp to support it? @cmp-nct, @cjpais, @danbev, @monatis, has any of you tried it?

Demo: https://internvl.opengvlab.com/

**Comment by paryska99** [comment]
Would be great

**Comment by cjpais** [comment]
I am working on a few projects right now, but if I get a chance I will try to get support in (assuming it doesn't already work). I would also like to get moondream support in

**Comment by 2132660698** [comment]
+1

**Comment by cjpais** [comment]
fwiw moondream support was merged in #6899, haven't had a chance to look at/try internvl

**Comment by sapere-aude-incipe** [comment]
I would really like to get InternVL support in llama.cpp.

I have tested the demo extensively and it is really good, so much so that I feel like it is a game changer in many ways. But running it on consumer hardware is not possible right now.

As noted here: https://github.com/InternLM/lmdeploy/issues/1501#issuecomment-2078558853

_architecture: [InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) + MLP + [InternLM2-Chat-20B](https://huggingface.co/internlm/internlm2-chat-20b)
I am afraid it cannot fit into A10 (24G) even though LLM weights are quantized into 4 bits._

Is it possible to GGUF the weights to allow for multi GPU splitting or splitting layers between CPU RAM and VRAM? Adding support for InternVL 1.5 would also (probably) make it easier to support future versions when they come out.

**Comment by Single430** [comment]
@cjpais Hello, may I ask what is the progress of internvl support now? We are looking forward to using it on llama.cpp.

**Comment by cjpais** [comment]
Hey I am quite busy with a few projects, it's on my list but just not very high priority at the moment. It's really only something I can do in my spare/free time

**Comment by Single430** [comment]
> Hey I am quite busy with a few projects, it's on my list but just not very high priority at the moment. It's really only something I can do in my spare/free time

Thank you for your reply. Thank you for your hard work. Looking forward to your future work.

**Comment by chigkim** [comment]
Which one would be better to focus: [CogVLM](https://github.com/ggerganov/llama.cpp/issues/4387) or InternVL?

I wish there is more resource/interest for language vision models among the llama.cpp community. Llama.cpp is the only way to run newer language vision models on Apple Silicon. Especially since flash attention python library is not available for Apple Sillicon, you can't even run inference using Torch with MPS support. :(

**Comment by opisaac9001** [comment]
> Which one would be better to focus: [CogVLM](https://github.com/ggerganov/llama.cpp/issues/4387) or InternVL?
> 
> I wish there is more resource/interest for language vision models among the llama.cpp community. Llama.cpp is the only hope to run newer language vision models on Apple Silicon. Especially since flash attention python library is not available for Apple Sillicon, you can't even run inference using Torch with MPS support. :(


Please internVL,. In my tests it works better than CogVLM. Especially for stuff like receipts and documents.

**Comment by fzzylogic** [comment]
InternVL is quite good, [benchmarks](https://mmbench.opencompass.org.cn/leaderboard). [Demo here](https://internvl.opengvlab.com/).

**Comment by DoiiarX** [comment]
how about now? any update?

**Comment by James4Ever0** [comment]
upvote for this

**Comment by fzzylogic** [comment]
Internlm-xcomposer2d5-7b is out now out and having only tested the image capabilities, it seems great. [HF](https://huggingface.co/internlm/internlm-xcomposer2d5-7b), [Demo](https://huggingface.co/spaces/Willow123/InternLM-XComposer).

**Comment by KOG-Nisse** [comment]
This would be great!

**Comment by v3ss0n** [comment]
Any status on this. this is currently highest performing Vision LLM from user's tests on LocalLLama reddit.

**Comment by suncloudsmoon** [comment]
Any updates?

**Comment by CNEA-lw** [comment]
> [<img alt="@henk717" width="20" height="20" src="https://avatars.githubusercontent.com/u/7526774?s=40&amp;v=4">](/henk717) [henk717](/henk717) 提到了这个问题 [ 2024 年 7 月 23 日 ](#ref-issue-2424222096)
> [ 添加对 InternVL2 模型的支持 LostRuins/koboldcpp#1016](/LostRuins/koboldcpp/issues/1016)

I tested the now available InternVL2 model and it is indeed a great choice, I hope to give it a higher priority, thank you for your hard work.

**Comment by CNEA-lw** [comment]
> 嘿，我有几个项目很忙，它在我的清单上，但目前优先级并不多。这真的只是我可以在业余时间做的事情

I tested the now available InternVL2 model and it is indeed a great choice, I hope to give it a higher priority, thank you for your hard work.

**Comment by goto-loop** [comment]
InternVL2 would be great to have! Seems to be SOTA in open source vision LLMs

**Comment by v3ss0n** [comment]
Any thoughts on this? 
Since Vision models varies alot , compare to LLM models do Maintainers thinks LLamacpp should be focusing on supporting it? Since there are already a lot of LLM models coming out and the core team is doing tremendous work on those already. Do core team feels VLMs should be supported outside of llamacpp project?

**Comment by Backendmagier** [comment]
This would be a gamechanger! @cjpais

**Comment by cjpais** [comment]
I'm sorry I don't know when I can do this, I have a huge backlog of projects I'm currently working on! I am very curious to try it but unfortunately it's not very high priority for me right now

**Comment by nogifeet** [comment]
> InternVL2 would be great to have! Seems to be SOTA in open source vision LLMs

+1

**Comment by v3ss0n** [comment]
I think model builder should contribute their vision model works in here.

**Comment by felixslu** [comment]
> I think model builder should contribute their vision model works in here.

In an ideal situation，it's model builder's work!
but sadly, maybe their work not focus on device，or they have self-deploy server framework，such as LMDeploy.

So, I really hope llama.cpp contributor can support this model, it is really good!

**Comment by ZhongQiyu** [comment]
I think the devs can add their own branches to the llama.cpp repo or huggingface.co?
The 2.5 version of InternVL also got released..can take it a try for transfer as a helper if needed.

**Comment by v3ss0n** [comment]
> > I think model builder should contribute their vision model works in here.
> 
> In an ideal situation，it's model builder's work! but sadly, maybe their work not focus on device，or they have self-deploy server framework，such as LMDeploy.
> 
> So, I really hope llama.cpp contributor can support this model, it is really good!

If they want to be popular and used by many , that would be the case.

**Comment by rampageservices** [comment]
> They have closed my issue for now. Guess this is never on their roadmap.
> 
> [OpenGVLab/InternVL#522](https://github.com/OpenGVLab/InternVL/issues/522)

It was reopened and they stated they are actively working towards "progressing the work."

**Comment by James4Ever0** [comment]
Now I have made some progress.

https://github.com/ggerganov/llama.cpp/pull/9403

Please consider reopen this issue.

**Comment by rccrdmr** [comment]
Anyway we can extract confidence score?

**Comment by FeepingCreature** [comment]
https://github.com/ggml-org/llama.cpp/blob/master/docs/multimodal.md says explicitly that InternVL is supported. Is this issue done?
