### ISSUE TITLE
No special token handling in imatrix, beam-search and others

### ISSUE THREAD

**Issue by BrickBee** [ggerganov/llama.cpp#6804]
Some models are extremely sensitive to the prompt format being correct. Without it they generate gibberish.
beam-search calls llama_tokenize with parse_special = false. Once I switched that to true the special tokens in my prompts were parsed correctly and it would generate reasonable output.

It is also set to false in the imatrix generation. Thus, all sample data generated from common chat and instruction datasets in the prompt format of the model will not be tokenized in the same way that the model will see during regular inference. Shouldn't it have an impact that zero real prompt formats were evaluated for the imatrix generation?

To get a better idea of the impact I've tested this with the perplexity measurement which also does not parse special tokens. In my quick ChatML test with CodeQwen-1.5 the perplexity went _up_ by 40% once special tokens were parsed. Maybe that's due to the raw chunking that evaluates multiple prompts at once and also breaks them in the middle?
Side note: The tokenization took 500x longer with parse_special = true.

Maybe that's something to be investigated why the PPL went up when special tokens were enabled, and if special token parsing could improve imatrix results? A reason why it might be disabled is stated [here](https://github.com/ggerganov/llama.cpp/pull/4160#issuecomment-1824826216).

**Comment by Dampfinchen** [comment]
Hmm, this might be the reason I'm seeing reports from people saying imatrix doesn't work properly with llama 3 models yet.

**Comment by candre23** [comment]
Not sure if this is related to this issue specifically, but iQ3 quants of L3 are definitely broken right now.  Strangely, iQ4 quants seem OK.  Here's some PPL calcs I ran on a few different quants a couple days ago.  As you can see, iQ3xs is totally borked.

Llama 3 70b
```
Q2k       Final estimate: PPL = 12.8166 +/- 0.22308
iQ3xs     Final estimate: PPL = 552.0451 +/- 12.31402
Q3km      Final estimate: PPL = 10.0883 +/- 0.17180
iQ4xs     Final estimate: PPL = 9.4791 +/- 0.15818
Q4km      Final estimate: PPL = 6.2366 +/- 0.09157
Q5km      Final estimate: PPL = 6.1289 +/- 0.08950
```

Llama 3 8b
```
Q2k       Final estimate: PPL = 12.9246 +/- 0.20490
iQ3xs     Final estimate: PPL = 109.0483 +/- 2.12390
Q3km      Final estimate: PPL = 10.2122 +/- 0.16656
iQ4xs     Final estimate: PPL = 9.7191 +/- 0.15669
Q4km      Final estimate: PPL = 9.6414 +/- 0.15494
Q5km      Final estimate: PPL = 9.5472 +/- 0.15408
Q6k       Final estimate: PPL = 9.5235 +/- 0.15396
Q8        Final estimate: PPL = 9.5181 +/- 0.15410
fp16      Final estimate: PPL = 9.5158 +/- 0.15418
```

**Comment by Dampfinchen** [comment]
@ikawrakow Any idea what could cause this? Have you done any tests so far in regards to imatrix and IQ quants for Llama 3?

**Comment by MoonRide303** [comment]
Just tried IQ3_XS quant using F16 GGUF as input (made from [Yi-1.5-34B-Chat](https://huggingface.co/01-ai/Yi-1.5-34B-Chat) using current-ish llama.cpp, b2859), and it's unusable:
![image](https://github.com/ggerganov/llama.cpp/assets/130458190/d98f48d0-55fa-4d8b-8f9e-d0f614887f0a)

Output from Q2_K looks much better:
![image](https://github.com/ggerganov/llama.cpp/assets/130458190/858acb89-2449-4370-a6ec-5c9245477a4f)
