### ISSUE TITLE
In Command R and Command R+ gguf models, inference with grammars causes shutdown

### ISSUE THREAD

**Issue by umiyuki** [ggerganov/llama.cpp#6805]
I am using llama-b2700-bin-win-cuda-cu12.2.0-x64 downloaded from the release page in a Windows environment.
If I load a Command R or Command R+ gguf in main or server and let it infer with grammar, it shuts down without displaying any errors. I have confirmed that it works fine when another model is loaded.
The grammar used is a simple grammar that outputs only one number character.
root ::= [1-5]
I have confirmed that the same problem occurs when json.gbnf is used.
The gguf we used was downloaded from here.
https://huggingface.co/dranger003/c4ai-command-r-plus-iMat.GGUF/tree/main
https://huggingface.co/pmysl/c4ai-command-r-plus-GGUF/tree/main
I have confirmed that the problem occurs with the following gguf.
command-r-plus-Q4_K_S-00001-of-00002.gguf
ggml-c4ai-command-r-plus-104b-iq1_s.gguf
ggml-c4ai-command-r-plus-104b-iq4_xs-00001-of-00002.gguf

**Comment by ggerganov** [comment]
Likely duplicate of https://github.com/ggerganov/llama.cpp/issues/6112

**Comment by umiyuki** [comment]
Sorry, I did not notice the duplication.
