### ISSUE TITLE
How to create customised vocal models to use with train-text-from-scratch ?

### ISSUE THREAD

**Issue by lbarasc** [ggerganov/llama.cpp#6817]
I made some experiments with train-text-from-scratch, we must specify a vocab model, where to find it or how to create it ?
I find the file ggml-vocab-llama.gguf on hugging face, but i prefer to create a new one to support additionnal languages and not only english,
please share your ideas, thank you

**Comment by teleprint-me** [comment]
You need to extract it from a currently existing model. There a models available in the llama.cpp/models path following the prefix format of "ggml-vocab-<model-name>".

If any of the existing vocabs in undersirable for any reason, you can use the vocab of another model using one of the conversion scripts to extract it.

```sh
python convert.py --vocab-only --vocab-dir /path/to/model --outfile /path/to/ggml-vocab-<model-name>.gguf /path/to/model
```

It's pretty straightforward. For more details, use the `--help` flag with the desired conversion script.

```sh
python convert.py --help
```
