### ISSUE TITLE
Support for Alibaba-NLP/gte-large-en-v1.5 Embedding Model

### ISSUE THREAD

**Issue by syddharth** [ggerganov/llama.cpp#6821]
[Alibaba-NLP/gte-largel-en-v1.5](https://huggingface.co/Alibaba-NLP/gte-large-en-v1.5)

We introduce gte-v1.5 series, upgraded gte embeddings that support the context length of up to 8192, while further enhancing model performance. The models are built upon the transformer++ encoder [backbone](https://huggingface.co/Alibaba-NLP/new-impl) (BERT + RoPE + GLU).

--

Upon trying to convert the model into GGUF, one gets the following error:

```
D:\AI\T2T\_source>python llama.cpp\convert.py .\models\gte-large-en-v1.5 --outfile gte-large-en-v1.5.gguf --outtype q8_0
Loading model file models\gte-large-en-v1.5\model.safetensors
Traceback (most recent call last):
  File "D:\AI\T2T\_source\llama.cpp\convert.py", line 1555, in <module>
    main()
  File "D:\AI\T2T\_source\llama.cpp\convert.py", line 1498, in main
    params = Params.load(model_plus)
  File "D:\AI\T2T\_source\llama.cpp\convert.py", line 328, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
  File "D:\AI\T2T\_source\llama.cpp\convert.py", line 237, in loadHFTransformerJson
    raise NotImplementedError(f'Unknown rope scaling type: {typ}')
NotImplementedError: Unknown rope scaling type: ntk
```

**Comment by JJassonn69** [comment]
i am having the same issue also tried with hf-to-gguf-convert.py but didnt work either.

**Comment by 0ssamaak0** [comment]
> Same, I changed the "architectures" key in the model's config.json to "BertModel", now I'm getting: `Can not map tensor 'encoder.layer.0.attention.o_proj.bias' `

same problem. Anyone figured out what is actually the `NewModel` Arch in `config.json`?

**Comment by TheLocalLab** [comment]
> > Same, I changed the "architectures" key in the model's config.json to "BertModel", now I'm getting: `Can not map tensor 'encoder.layer.0.attention.o_proj.bias' `
> 
> same problem. Anyone figured out what is actually the `NewModel` Arch in `config.json`?

Would it be referring to their Alibaba-NLP/new-impl(https://huggingface.co/Alibaba-NLP/new-impl)? They go into a bit more detail about configuring the `NewModel` in the `configuration.py` file.
