### ISSUE TITLE
Setting `temp=0` does not work as expected

### ISSUE THREAD

**Issue by abetlen** [ggerganov/llama.cpp#684]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Setting sampling temperature to `0` should produce valid and "predictable" tokens.

# Current Behavior

Setting temperature to `0` causes sampling to fail completely. This is due to `plogits` being scaled by `1.0f/temp` before sampling [here](https://github.com/ggerganov/llama.cpp/blob/d0a7f742e76bb48c0bd852f0b3bf09ec0b75b200/llama.cpp#L1201). I believe a workaround for this would be to make sampling deterministic when `temp==0` by setting `top_p=0.0` and `top_k=1` and setting `temp>0`.

**Comment by Fabio3rs** [comment]
Hi, I did a PR trying to fix this, can you test it?
#689

Thanks

**Comment by ivanstepanovftw** [comment]
Isn't it `if (abs(temp) < EPS) {top_k=1; top_p=1; temp=1}`?

**Comment by ivanstepanovftw** [comment]
Why not just handle the case explicitly as [`https://github.com/facebookresearch/llama/compare/main...shawwn:llama:main`](https://github.com/facebookresearch/llama/compare/main...shawwn:llama:main#diff-cfa9e089ebf97ee064b754a2fecad8b5c23610a519a6d640710d94f74fbd8300R65) does?
```
if (temp == 0) {
    int max_idx = std::distance(plogits, std::max_element(plogits, plogits + n_logits));
    for (int i = 0; i < n_logits; ++i) {
        logits_id.push_back(std::make_pair((i == max_idx) ? 1.0f : 0.0f, i));
    }
} else {
    const float scale = 1.0f/temp;
    for (int i = 0; i < n_logits; ++i) {
        // repetition penalty from ctrl paper (https://arxiv.org/abs/1909.05858)
        // credit https://github.com/facebookresearch/llama/compare/main...shawwn:llama:main
        if (std::find(last_n_tokens.begin(), last_n_tokens.end(), i) != last_n_tokens.end()) {
            // if score < 0 then repetition penalty has to multiplied to reduce the previous token probability
            if (plogits[i] < 0.0f) {
                logits_id.push_back(std::make_pair(plogits[i]*scale*repeat_penalty, i));
            } else {
                logits_id.push_back(std::make_pair(plogits[i]*scale/repeat_penalty, i));
            }
        } else {
            logits_id.push_back(std::make_pair(plogits[i]*scale, i));
        }
    }
}
```
