### ISSUE TITLE
Api llama_tokenize function problem

### ISSUE THREAD

**Issue by Eriter555** [ggerganov/llama.cpp#6854]
In the llama_tokenize function, the add_special parameter does not affect the resulting array of tokens (as I understand it, a bos token should be added to the beginning). Model Meta-Llama-3-8B.Q5_K_M.gguf , for example. processor with AVX2

**Comment by Eriter555** [comment]
How is the text generation supposed to be stopped then? By -r --reverse-prompt ? Why then is the function llama_token_is_eog needed ?

**Comment by ggerganov** [comment]
To stop generation it is recommended to use `llama_token_is_eog()` (see the examples)

**Comment by Eriter555** [comment]
But simple small models ~8GB (maybe others) don't generate service tokens unless you add them in the input. Maybe I'm wrong, but I've never had this happen. Thank you for the answers.
