### ISSUE TITLE
Support for OpenELM of Apple

### ISSUE THREAD

**Issue by Ce-daros** [ggerganov/llama.cpp#6868]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Support for OpenELM of Apple

https://huggingface.co/apple/OpenELM-3B-Instruct/tree/main

**Comment by ggerganov** [comment]
Nice to see the [LLaMA*](https://github.com/ggerganov/llama.cpp/discussions/4147) idea implemented in these models:

![image](https://github.com/ggerganov/llama.cpp/assets/1991296/e3ba30fa-f8d0-4267-a4f5-ff30afabc724)

**Comment by joshcarp** [comment]
Not sure if anyone is working on this yet but i'm happy to pick it up

**Comment by mertbozkir** [comment]
same for me as well, I can pick it up. I am trying to upload the model on ollama, but got `NotImplementedError: Architecture 'OpenELMForCausalLM' not supported!` 

![image](https://github.com/ggerganov/llama.cpp/assets/63906053/2601b899-80ec-420c-98ad-0c57ec110171)

**Comment by joshcarp** [comment]
Okay update: It's more difficult as I first expected it and this is a new codebase so it's stumped me a bit. 
OpenELM have defined the variables: `a_min`, `a_max` for scaling the attention heads and `b_min` and `b_max` for scaling the ffn. This is both captured in their [config](https://huggingface.co/apple/OpenELM-270M/blob/0a49ab455190e17fcf02d2f21d15e58f6496c8d9/config.json#L13) but you can also derive it from the equation: 

<img width="486" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/32605850/9852ea17-fc39-4e3b-93c0-646041da2ba1">

Still attempting it but i don't think i'm gonna be done any time soon

**Comment by Wladastic** [comment]
@joshcarp 
Waiting patiently to try it out hopefully 🤞 
Are you having any troubles figuring it out?

**Comment by joshcarp** [comment]
Yeah, so basically, i think I can't figure out how to calculate the kqv offsets for the kqv tensor every layer. 
I'd be lying if i didn't admit i've just been throwing spaghetti at the wall as shown my the git history on this: https://github.com/joshcarp/llama.cpp

I'm using this as a reference: https://huggingface.co/apple/OpenELM-270M/blob/main/modeling_openelm.py
https://github.com/apple/corenet/tree/main/mlx_examples/open_elm

**Comment by joshcarp** [comment]
If anyone can help out: https://github.com/ggerganov/llama.cpp/pull/6986

**Comment by userforsource** [comment]
When this will be available.

**Comment by kevinsuo** [comment]
Does this work? Did anyone try this?

https://huggingface.co/LiteLLMs/OpenELM-GGUF

**Comment by Wladastic** [comment]
> Does this work? Did anyone try this?
> 
> 
> 
> https://huggingface.co/LiteLLMs/OpenELM-GGUF

Have you checked the files?
It specifically states that it is just a placeholder, there is no model

**Comment by userforsource** [comment]
Is it possible to have support forr openelm
I am curious for this because this can be run on mobile devices with less power don't know about the performance though. Compare to gemma:2b or phi3
