### ISSUE TITLE
Getting "Bad CPU type in executable" on macos-x64 build

### ISSUE THREAD

**Issue by xanguera** [ggerganov/llama.cpp#6875]
I downloaded build 2717 (April 24th) into a macbook pro Intel x86_64 and I am getting "Bad CPU type in executable" on any of the built commands. I tested with the previous build and I get the same issue.

**Comment by towardmay** [comment]
Same issue for us.

**Comment by HyperMink** [comment]
@xanguera you can use the attached binary if you like. Tested on macOS Intel.
[macOS-Intel-Finetune.zip](https://github.com/ggerganov/llama.cpp/files/15258804/macOS-Intel-Finetune.zip)

**Comment by xanguera** [comment]
Thank you @HyperMink , your binary for the finetune executable works. Do you mind posting the one to run a model or explaining how did you get it to run? did you compile from source?

**Comment by HyperMink** [comment]
Yes @xanguera we just use make or cmake. It should be pretty quick to build llama.cpp
Here is a zip containing some of the binaries compiled for macOS intel 
[llama.cpp-Mac-Intel-binaries.zip](https://github.com/ggerganov/llama.cpp/files/15270053/llama.cpp-Mac-Intel-binaries.zip)
