### ISSUE TITLE
I use python's llama-cpp package to run the code. There is a cuda environment and the contents of llama.cpp (compiled), but I still cannot use the GPU.

### ISSUE THREAD

**Issue by XianYue0125** [ggerganov/llama.cpp#6898]
windows11
13900k+4090
python3.11.8
llama_cpp_python       0.2.64
use llm model: Phi-3-mini-4k-instruct-q4.gguf

![image](https://github.com/ggerganov/llama.cpp/assets/143397470/e7953add-64f0-45df-97fc-5395e43abc73)

![image](https://github.com/ggerganov/llama.cpp/assets/143397470/ac1c0088-3a3e-4625-9886-ac0aa51119a5)

Even if I tried changing n_gpu_layers to -1,0, or other values

And main_gpu also tried 0,1,2

also has no effect

![image](https://github.com/ggerganov/llama.cpp/assets/143397470/6d3aef32-1c17-4eca-bb9f-5047e2961038)

Please tell me what else I have missed or what environment I am missing. thanks

**Comment by CISC** [comment]
This really belongs to [llama-cpp-python](https://github.com/abetlen/llama-cpp-python), but it looks like your issue is that you didn't install/compile the CUDA version, see the `Installation Configuration`->`CUDA` section in the [docs](https://llama-cpp-python.readthedocs.io/en/latest/).

**Comment by XianYue0125** [comment]
好的，我打算在一台新的计算机上完整尝试一次安装流程，我想也许之前这台4090电脑为了跑strable diffusion所安装的CUDA有问题，有了结果会第一时间反馈

**Comment by FoxBuchele** [comment]
A few weeks ago they changed the instructions (and the environment variable) needed to use CUDA. It used to be '-DLLAMA_CUBLAS=ON' and now it's '-DLLAMA_CUDA=on'. Try uninstallying llama-cpp-python, adding the new environment variable, and reinstalling it.

**Comment by XianYue0125** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/0df563c7-cbb4-42fb-9f42-d4dd6c0b7387)
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/2cbb196a-4889-48b7-b722-518e578df353)

**Comment by XianYue0125** [comment]
I didn't install cmake before, but now I have installed it. I configured the path with python and set the parameters, but it still has no effect.

**Comment by XianYue0125** [comment]
The method I used just now is not very good and is not conducive to troubleshooting the problem. I first installed it directly to the c drive and added environment variables.
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/a8a65474-c68d-463a-bcf5-4ff3c119ab36)
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/2778d0a0-d3d3-4c9c-a12c-150c1702d2ae)
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/1640311c-6cac-4bd4-a48a-e74001203aff)
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/6f6bba05-903f-4957-924d-d2784dc20c7c)

**Comment by XianYue0125** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/a793f01b-3685-4d63-b7be-fb24cb37a8fc)
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/abef8285-00ed-4aee-a0f8-c19d24dccc18)

**Comment by XianYue0125** [comment]
I also tried adding manually
![image](https://github.com/ggerganov/llama.cpp/assets/143397470/08a072a8-949e-4bb3-90dd-954e49fc7682)

This is the complete process, but it still doesn’t work

![image](https://github.com/ggerganov/llama.cpp/assets/143397470/5ea74707-6657-4381-a247-3ea6fdabfe2e)

Did I miss an operation? This is also my first time to come into contact with cmake and gguf format models.

**Comment by XianYue0125** [comment]
I have another question. LM Studio also uses the gguf model. After this program is installed, you can directly use the LLM model. Does it also implement the functions of cmake and llama.cpp internally?

**Comment by CISC** [comment]
You're almost there. :)

First off installing CMake and setting variables is not necessary if you're going to use the pip wheels (only if you are building llama.cpp, but then you also need other devtools).

Your issue right now is that you're using the wrong wheel cuda version, it's not `12.4`, but `cu124`.

**Comment by XianYue0125** [comment]
So that’s it, I’m going to try it!
