### ISSUE TITLE
offload_kqv ONLY supported by python version?

### ISSUE THREAD

**Issue by takosalad** [ggerganov/llama.cpp#6900]
the non-python ie C version doesn't have the
--offload_kqv
parameter but only
--no_kv_offload
Intended?

**Comment by slaren** [comment]
The python bindings are maintained in a different repository and they may follow different design decisions. In this case, the actual name of the parameter in the llama.cpp API is `offload_kqv`, but since it is enabled by default, we named the command line parameter `"--no-kv-offload`.
