### ISSUE TITLE
ggml.c:2284:43: error: use of undeclared identifier 'cpu_set_t'

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ggerganov/llama.cpp#6907]
It's a very good job！I'm having some issues with the project，I'm looking for cross-compilation on x86，but have some error:
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/443b3603-a9f9-4fd0-8382-50e75a684a0b)

My run command is as follows：
export NDK=/home/xxx/AndroidSDK/android-ndk-r19c
cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_SYSTEM_NAME="ANDROID" ..

There were a lot of errors after the execution，Can you help me with these issues?

**Comment by bmtwl** [comment]
Hello, this is due to the NUMA code being compiled mistakenly for this platform. 
You may need to explicitly undefine __gnu_linux__ in order to get the android cross-compile to work correctly
see https://github.com/android/ndk/issues/874 for a similar issue

**Comment by QIANXUNZDL123** [comment]
> 您好，这是由于该平台的 NUMA 代码被错误地编译。您可能需要显式取消定义才能使 android 交叉编译正常工作，请参阅 [android/ndk#874](https://github.com/android/ndk/issues/874) 了解类似的问题，并很好地解释了为什么这是一个问题`__gnu_linux__`

hello, can you tell me how to explicitly undefine __gnu_linux__ ， I'm relatively poor at programming and don't know much about Android，can you help me

**Comment by QIANXUNZDL123** [comment]
> Hello, this is due to the NUMA code being compiled mistakenly for this platform. You may need to explicitly undefine `__gnu_linux__` in order to get the android cross-compile to work correctly see [android/ndk#874](https://github.com/android/ndk/issues/874) for a similar issue and a good explanation of why its a problem

I've fixed this bug and I've commented all the __gun_linux__，Thank you for helping me and thank you again

**Comment by bmtwl** [comment]
Glad that worked!
