### ISSUE TITLE
Experiencing 2-3 GB GPU memory use increase compared to llama.cpp version a few weeks ago

### ISSUE THREAD

**Issue by zsogitbe** [ggerganov/llama.cpp#6909]
I am wondering what has happened and if we can do something about it? Is this some kind of memory pool which has a bigger size? Can we reduce this size if we want to? I have noticed this issue with a model which was fitting into my GPU before, but it reports now out of memory when I offload all layers to GPU.
@Slaren , is it possible that this has something to do with the work you have done recently with managing GPU memory?

Will the selection of the LLAMA_CUDA_F16 option during compilation decrease inference GPU memory use?

**Comment by slaren** [comment]
I don't remember doing anything recently with managing GPU memory. I am not aware of any changes that could cause VRAM usage to increase, try running a bisect to find the commit that introduced the issue.
