### ISSUE TITLE
Vocab problems converting QWEN 110b with convert.py

### ISSUE THREAD

**Issue by cpumaxx** [ggerganov/llama.cpp#6938]
I am on the latest git pull of master

Converting to f32, f16 or q8_0 is broken using convert.py
doing a naive conversion with just `--outtype` and `--outfile` results in an error in load_vocab
converting with `--no-vocab` results in an unusable model
converting with `--vocab-type bpe` and `--vocab-dir .` results in 
>`ValueError: Vocab size mismatch (model has 152064, but vocab.json has 151643). Add the --pad-vocab option and try again.`

and using the suggested `--pad-vocab` results in almost all output consisting of the padded vocab placeholder text.

**Comment by slaren** [comment]
`convert.py` is only meant to be used with llama arch models. For other archs, use `convert-hf-to-gguf.py`.

**Comment by cpumaxx** [comment]
I didn't realize that. Thanks!
