### ISSUE TITLE
failed to quantize: ios_base::clear: unspecified iostream_category error

### ISSUE THREAD

**Issue by NeevJewalkar** [ggerganov/llama.cpp#6945]
I have downloaded a model finetuned for functional calling from HF
https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v3

My next step was to quantize this model, so I first converted it to F32 (with no issue) and then when I try to run ./quantize,
```bash
$ ./quantize ../../../../.cache/huggingface/hub/models--Trelis--Meta-Llama-3-8B-Instruct-function-
calling/snapshots/ede9e7c7280a2292c7ae4c9a851e5923face48d9/ggml-model-f32.gguf ./models/Llama3-8B-
FunctionalCalling/llama3-8b-functionalcalling-q4_k_m.gguf Q4_K_M

main: build = 1453 (9a3b4f6)
main: built with Apple clang version 14.0.3 (clang-1403.0.22.14.1) for arm64-apple-darwin23.0.0
main: quantizing '../../../../.cache/huggingface/hub/models--Trelis--Meta-Llama-3-8B-Instruct-function-calling/snapshots/ede9e7c7280a2292c7ae4c9a851e5923face48d9/ggml-model-f16.gguf' to './models/Llama3-8B-FunctionalCalling/llama3-8b-functionalcalling-q4_k_m.gguf' as Q4_K_M
llama_model_loader: loaded meta data with 21 key-value pairs and 291 tensors from ../../../../.cache/huggingface/hub/models--Trelis--Meta-Llama-3-8B-Instruct-function-calling/snapshots/ede9e7c7280a2292c7ae4c9a851e5923face48d9/ggml-model-f16.gguf (version GGUF V3 (latest))
...
llama_model_quantize: failed to quantize: ios_base::clear: unspecified iostream_category error
main: failed to quantize model from '../../../../.cache/huggingface/hub/models--Trelis--Meta-Llama-3-8B-Instruct-function-calling/snapshots/ede9e7c7280a2292c7ae4c9a851e5923face48d9/ggml-model-f16.gguf'
```

I get the error "Llama_model_quantize: failed to quantize". How do I solve this?

System Info:
MacbookPro, MacOS 14.0

**Comment by arnfaldur** [comment]
This model already exists with this quantization here.

https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v3/tree/gguf

If you still want to do it (totally valid of course), you could start by fetching the latest version and retrying, you are using a somewhat old build.

If you cut out some outputs in that ellipsis, it's better to leave it in for more context about the issue.

If you don't need it anymore than it would be kind to close the issue.

**Comment by arnfaldur** [comment]
https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#prepare-and-quantize

Have you followed these instructions?
