### ISSUE TITLE
xcrun: error: unable to find utility "metal", not a developer tool or in PATH in B2479

### ISSUE THREAD

**Issue by limoncc** [ggerganov/llama.cpp#6946]
macos 13.6.6
Command_Line_Tools_for_Xcode_14.3.1

-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /opt/homebrew/bin/git (found version "2.43.0")
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Accelerate framework found
-- Metal framework found
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with LLAMA_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: arm64
-- ARM detected
-- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E
-- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E - Failed
CMake Warning at common/CMakeLists.txt:29 (message):
  Git repository not found; to enable automatic generation of build info,
  make sure Git is installed and the project is a Git repository.

-- Configuring done (0.7s)
-- Generating done (0.2s)
-- Build files have been written to: ./llama.cpp/build

> cmake --build . --config Release
[  0%] Compiling Metal kernels
xcrun: error: unable to find utility "metal", not a developer tool or in PATH
make[2]: *** [bin/default.metallib] Error 72
make[1]: *** [CMakeFiles/ggml-metal.dir/all] Error 2
make: *** [all] Error 2

**Comment by arnfaldur** [comment]
Although I don't use apple computers, upgrading to Xcode 15 might help.

The issue seems to be that you either don't have the metal dev tools installed (they're bundled with Xcode 15) or they're not in your path.

If you have been messing with your path, that could be the issue but that is less likely.

Are you still facing this issue?

**Comment by SHAIMA-HAQUE** [comment]
Yes, installing XCode and then doing
`sudo xcode-select -r` worked for me.

**Comment by bmilde** [comment]
I had xcode already installed and got the same error. After doing these the metal shader compiler could be found:

sudo xcode-select -r

sudo xcodebuild -license
