### ISSUE TITLE
Support For ggml format for gpt4all

### ISSUE THREAD

**Issue by chigkim** [ggerganov/llama.cpp#696]
When I convert Llama model with convert-pth-to-ggml.py, quantize to 4bit, and load it with gpt4all, I get this:
llama_model_load: invalid model file 'ggml-model-q4_0.bin' (bad magic)
Could you implement to support ggml format that gpt4all uses?
Thanks!

**Comment by linouxis9** [comment]
Try running the migrate script as detailed in this PR: https://github.com/ggerganov/llama.cpp/pull/690

**Comment by chigkim** [comment]
Isn't that migrate from old format to new format?

I would like to convert pth to old format.

Thanks!

**Comment by CREAsTIVE** [comment]
> Isn't that migrate from old format to new format?

No. You need migrate youre quantinized model using [https://github.com/ggerganov/llama.cpp/blob/master/migrate-ggml-2023-03-30-pr613.py](this) script

**Comment by prusnak** [comment]
You should open an issue in the gpt4all repository, since what you are asking is essentially them to support a certain format.
