### ISSUE TITLE
Metal doesn't work in x86 macos

### ISSUE THREAD

**Issue by qq249356520** [ggerganov/llama.cpp#6975]
MacOS CPU:Intel Core i7 
GPU:AMD Radeon Pro 5500 XT 8 GB
memory:32G

When I open metal in this mac to run " ./main -m "./Meta-Llama-3-8B.Q4_0.gguf" -p "Hi you how are you" -n 50 -e -ngl 33 -t 4 "

the error occured :
<img width="1441" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/20353598/1479655c-09be-47f0-bc82-228b8528dbfc">

If I close the metal, it worked.  How to fix it in X86 cpu?

**Comment by arnfaldur** [comment]
Which version of llama.cpp are you using?

The `ggml-metal.metal` file that's being reported as missing should be in the root of the repo. Make sure you are running the latest version and that it is there.
