### ISSUE TITLE
Help: Batching the same request?

### ISSUE THREAD

**Issue by coder543** [ggerganov/llama.cpp#6978]
One cool feature that Google offers with Gemini (formerly Bard) is that you get to see three "drafts" of the response to every input. My understanding is that LLM inference servers are able to massively improve their tokens/sec throughput by "batching" requests together, so that you make better use of the compute available, instead of the batch size = 1 scenario where you're extremely limited by memory bandwidth.

Is it possible to have llama.cpp generate multiple drafts from a single prompt? If it is close to "free" for the GPU to run at a higher batch size, it would be cool to be able to compare across multiple generations without having to slowly run it multiple times.

I looked over the documentation, and I couldn't find any examples of how to do this from the CLI. I see "continuous batching", which seems targeted at serving multiple users, and I saw `-np` and `-ns`, but setting them to values higher than 1 didn't seem to do anything from the CLI.

**Comment by ggerganov** [comment]
For a simple example of this functionality you can take a look at the `batched` example:

```bash
./batched models/llama-7b-v2/ggml-model-f16.gguf "Hello, my name is" 8 32 99
```

Though throughput will depend on the hardware and the model that you use, and in some cases there might be no benefit compared to BS=1

**Comment by coder543** [comment]
Thanks, that's almost exactly what I was looking for! I was testing with Phi-3, and it doesn't seem to stop generating tokens as reliably as when I was using `./main`, but I'll poke around the code and see what I can find.
