### ISSUE TITLE
Cannot convert llama3 8b model to gguf

### ISSUE THREAD

**Issue by Bedoshady** [ggerganov/llama.cpp#7021]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

I downloaded model from llama using steps provided and I have 14 gb .pth file I try to convert the model using convert.py but it fails giving `RuntimeError: Internal: could not parse ModelProto from H:\Downloads\llama3-main\Meta-Llama-3-8B\tokenizer.model` but when I added --vocab-type bpe it gives `FileNotFoundError: Could not find a tokenizer matching any of ['bpe']`

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

**Comment by Galunid** [comment]
`convert.py` doesn't support llama 3 yet. You can use `convert-hf-to-gguf.py` with llama 3 downloaded from huggingface

**Comment by Bedoshady** [comment]
is there any thing that support llama 3, I just want to run the model

**Comment by teleprint-me** [comment]
@oldmanjk I understand the point perfectly fine. You can figure it out and then add it to the docs. If there aren't any docs, then create them. It's a fairly simple thought process. Complaining about it to people who are literally donating their time isn't productive or helpful. I have nothing else to say on the matter. Best of luck.

**Comment by ProjectAtlantis-dev** [comment]
there's also recently created convert-hf-to-gguf-update.py but I think you include your HF API token at the command line or else it will report a bunch of fails presumably when trying to pull from hf

**Comment by ProjectAtlantis-dev** [comment]
> `convert.py` doesn't support llama 3 yet. You can use `convert-hf-to-gguf.py` with llama 3 downloaded from huggingface

there's also recently created convert-hf-to-gguf-update.py but I think you include your HF API token at the command line or else it will report a bunch of fails presumably when trying to pull from hf

If you are reading this, you probably ended up here seeking the llama-bpe stuff in an effort to get rid of the strange error:
```
llm_load_vocab: missing pre-tokenizer type, using: 'default'
llm_load_vocab:                                             
llm_load_vocab: ************************************        
llm_load_vocab: GENERATION QUALITY WILL BE DEGRADED!        
llm_load_vocab: CONSIDER REGENERATING THE MODEL             
llm_load_vocab: ************************************        
llm_load_vocab:                                             
```

**Comment by Bedoshady** [comment]
I have the original .pth file from meta not the safetensor files from huggingface

**Comment by ProjectAtlantis-dev** [comment]
I don't think anyone uses the pth files anymore due to security risks

**Comment by Bedoshady** [comment]
Ok I converted the .pth file using huggingface transformers, but I dont know how to run it or if the conversion was correct

**Comment by ProjectAtlantis-dev** [comment]
Yeah I just saw that lol

**Comment by ProjectAtlantis-dev** [comment]
If you converted successfully, you should at least have a ...f16 gguf file that you may need to then run quantize to get it down further (8_0 at a min will cut it in half again)

If you have multiple filenames, you can just supply the first file in the "1 of N" and it will load the rest of the series

**Comment by ProjectAtlantis-dev** [comment]
I didn't know there was such thing as a b16 format - I've just been taking the convert python script defaults which seems to be f16 output (I think you have to add a '2' arg to the command line to get f32)
