### ISSUE TITLE
Supporting phi-2 tokenizer

### ISSUE THREAD

**Issue by BramVanroy** [ggerganov/llama.cpp#7022]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Provide support for phi-2. Running the following yields an error:

```sh
python -c "
from huggingface_hub import snapshot_download;
snapshot_download(repo_id='microsoft/phi-2', local_dir='phi-2', local_dir_use_symlinks=False)
"
python convert-hf-to-gguf.py phi-2/ --outtype f16
```

Error:
```
Traceback (most recent call last):
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 3001, in <module>
    main()
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 2988, in main
    model_instance.set_vocab()
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 75, in set_vocab
    self._set_vocab_gpt2()
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 331, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 242, in get_vocab_base
    tokpre = self.get_vocab_base_pre(tokenizer)
  File "/home/local/vanroy/llama.cpp/convert-hf-to-gguf.py", line 323, in get_vocab_base_pre
    raise NotImplementedError("BPE pre-tokenizer was not recognized - update get_vocab_base_pre()")
NotImplementedError: BPE pre-tokenizer was not recognized - update get_vocab_base_pre()
```

Phi-2 uses [`CodeGenTokenizer`](https://huggingface.co/docs/transformers/en/model_doc/codegen#transformers.CodeGenTokenizer), which is a BPE Tokenizer.

I'm not sure if it is as easy as adding the following line [here](https://github.com/ggerganov/llama.cpp/blob/1613ef8d8eb2479ba55c4d598e08c8f3f18a0fed/convert-hf-to-gguf-update.py#L48)? 

```
{ "name": "phi-2",          "tokt": TOKENIZER_TYPE.BPE, "repo": "https://huggingface.co/microsoft/phi-2" },
```

---

Edit tried that, this is the generated hash:

```
if chkhsh == "fcace8b9cac38ce847670c970cd5892031a753a1ef381abd1d9af00f713da085":
    # ref: https://huggingface.co/microsoft/phi-2
    res = "phi-2"
```

**Comment by arch-btw** [comment]
@BramVanroy https://github.com/ggerganov/llama.cpp/issues/7024

**Comment by turian** [comment]
Can you confirm that the HF tokenization and the llama.cpp quantized GGUF'ed tokenizer give identical results?

Particularly when the text has special characters

See #7049 and #7062

**Comment by BramVanroy** [comment]
@turian Any idea how I can easily test that?

**Comment by flatsiedatsie** [comment]
Sorry if this is the wrong thread to post in, and I don't know if this is useful, but I thought I'd share a quick attempt I made to convert a Phi 2 model.

I ran into the above mentioned error, and tried modifying the two `.py` files for converting from HuggingFace.

To the update files I added more Phi lines I found searching around the issues here, specifically this thread and:
https://github.com/ggerganov/llama.cpp/issues/7219#issuecomment-2116921321

```
// convert-hf-to-gguf-update.py

    {"name": "phi",            "tokt": TOKENIZER_TYPE.BPE, "repo": "https://huggingface.co/microsoft/phi-1", },
    {"name": "phi-2",          "tokt": TOKENIZER_TYPE.BPE, "repo": "https://huggingface.co/microsoft/phi-2", },
    {"name": "phi-3",          "tokt": TOKENIZER_TYPE.SPM, "repo": "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct", },
```

..and two modifications of `convert-hf-to-gguf.py`:

```
        if chkhsh == "fcace8b9cac38ce847670c970cd5892031a753a1ef381abd1d9af00f713da085":
            # ref: https://huggingface.co/microsoft/phi-1
            res = "phi"
        if chkhsh == "fcace8b9cac38ce847670c970cd5892031a753a1ef381abd1d9af00f713da085":
            # ref: https://huggingface.co/microsoft/phi-2
            res = "phi-2"
```
Note that the two `chkhsh` values are the same?

To the `Phi2Model` class I added a single `add_tokenizer_pre` line:
```
        self.gguf_writer.add_name("Phi2")
        self.gguf_writer.add_tokenizer_pre("gpt-2")
        self.gguf_writer.add_context_length(self.find_hparam(["n_positions", "max_position_embeddings"]))
```

Then I tried to run my Frankenstein creation. It seemingly worked, but when testing it I saw this error:

```
llama_model_load: error loading model: error loading model vocabulary: unknown pre-tokenizer type: 'phi'
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'model-q4_0.gguf'
main: error: unable to load model
```

**Comment by flatsiedatsie** [comment]
Is there anything I can do to get models like Fietje working through a work-around?
