### ISSUE TITLE
Server UI: Code snippets are being mangled by <em> italic emphasize replacement.

### ISSUE THREAD

**Issue by jboero** [ggerganov/llama.cpp#7023]
https://github.com/ggerganov/llama.cpp/blob/1613ef8d8eb2479ba55c4d598e08c8f3f18a0fed/examples/server/public/index.html#L888

I've been having a headache reformatting code samples in the UI as it keeps replacing underscores with italic `<em>` tags.  Can we either add this as an option or adjust the regex to avoid ```code blocks?

In this case "create<em>command<em>queue" should be `create_command_queue` and must be fixed before being used in code:
![image](https://github.com/ggerganov/llama.cpp/assets/7536012/6e4276e2-8dda-477b-974b-c4ae89e4e8cd)

**Comment by shibe2** [comment]
This can be absorbed into #3723. Initial report was about asterisks, but it was later extended to all markdown characters.

**Comment by jboero** [comment]
Just a heads-up on this - my workaround has been to resolve this via themes custom --public directory. Since this is actually happening client side it's really simple to remove markdown formatting in the theme.
https://github.com/ggerganov/llama.cpp/tree/7b2f4a7d193ef2475259bbe7656fcccfab4b1217/examples/server/themes
