### ISSUE TITLE
"ï¸ı" is causing chktok to mismatch when using chkhsh

### ISSUE THREAD

**Issue by arch-btw** [ggerganov/llama.cpp#7024]
I think the comma is not being escaped.

![qwen1](https://github.com/ggerganov/llama.cpp/assets/57669023/bd2c479b-db0e-4583-895e-183448386484)

`convert-hf-to-gguf.py `: loses the token
`convert-hf-to-gguf-update.py`: adds token correctly

**Related:** https://github.com/ggerganov/llama.cpp/pull/7018

Tested with Falcon and Qwen2, both fail on the same token.

**Comment by arch-btw** [comment]
Same problem: https://github.com/ggerganov/llama.cpp/issues/7022

@ggerganov

**Comment by arch-btw** [comment]
**convert-hf-to-gguf-update.py:**

![falcon](https://github.com/ggerganov/llama.cpp/assets/57669023/4bfc9dc2-baec-4dc4-ba15-137d42f52ee1)


**convert-hf-to-gguf.py**

![falcon2](https://github.com/ggerganov/llama.cpp/assets/57669023/053e3686-87b6-41e4-b1ad-e04b506a07d9)

**Comment by teleprint-me** [comment]
@arch-btw  What are the sources? Need the links to investigate.

**Comment by arch-btw** [comment]
Thank you @teleprint-me the sources are:

https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat

and

https://huggingface.co/tiiuae/falcon-7b

**Comment by teleprint-me** [comment]
I have to go to work, have a double today, but I'll check it out between shifts.

**Comment by ggerganov** [comment]
I don't understand - which comma is this related to?
Are you sure you are using the two scripts with the same tokenizer?

**Comment by teleprint-me** [comment]
@ggerganov The arrays in the output are not equal. There are missing vectors. I don't have time to do it between shifts, but I can take a close look tonight. Juggling too many things rn.

**Comment by arch-btw** [comment]
@ggerganov Thanks, yes, I'm using the same tokenizers. It's possible that it's not the comma (see below) but something is causing `convert-hf-to-gguf.py` to not include this token. I think there's something strange about these symbol(s): `ï¸ı` that's causing `convert-hf-to-gguf.py` to not include it, I thought maybe the comma is being interpreted literally. 

I meant this symbol here,  it's some unusual type of comma:

![comma](https://github.com/ggerganov/llama.cpp/assets/57669023/4c3d9ba2-cd36-4513-bb36-8ffcbc0fecff)

**Comment by arch-btw** [comment]
Ok I think I'm getting a bit closer, it's actually the character after the comma.

https://en.wikipedia.org/wiki/Dotless_I

**Comment by teleprint-me** [comment]
@arch-btw What OS are you using?

**Comment by arch-btw** [comment]
@teleprint-me , attempting to convert using arch linux. Do you think it might be OS related?

**Comment by teleprint-me** [comment]
@arch-btw I didn't want to assume you were using Arch (I am a fellow Arch user, btw ;).

I know encoding issues happen a lot on Windows, occasionally Mac OS X, and on Linux, it's distribution dependent. 

Whenever I've had issues with encodings in Arch, it's because I was missing a dependency. 

I don't know what's going on here though. I think I'm going to need to download the model and try it out for myself.

**Comment by teleprint-me** [comment]
I can't reproduce it.

```sh
23:14:27 | /mnt/valerie/forked/ggerganov/llama.cpp
(.venv) git:(add-stablelm-hash | Δ) λ python convert-hf-to-gguf.py /mnt/valerie/models/tiiuae/falcon-7b 
Loading model: falcon-7b
gguf: This GGUF file is for Little Endian only
Set model parameters
Set model tokenizer
chktok: [1212, 4824, 1001, 1212, 192, 204, 663, 49453, 2069, 742, 561, 1501, 193, 2571, 232, 206, 204, 19, 11003, 20, 8196, 126, 283, 219, 48778, 116, 13392, 204, 19, 51831, 732, 63209, 1741, 7955, 522, 20, 22438, 211, 3346, 111, 231, 2571, 111, 231, 204, 30, 204, 3138, 204, 22287, 204, 22287, 30, 204, 22287, 3138, 204, 22287, 22287, 204, 22287, 22287, 30, 204, 22287, 22287, 3138, 204, 30, 25, 30, 204, 30, 513, 30, 204, 30, 951, 30, 27171, 236, 206, 38154, 126, 38154, 225, 167, 237, 217, 38154, 221, 167, 237, 208, 38154, 228, 38154, 127, 38154, 237, 167, 237, 207, 38154, 237, 38154, 107, 38154, 126, 38154, 211, 20589, 207, 204, 42, 50087, 123, 2727, 20300, 32022, 133, 234, 17419, 30137, 28, 7858, 181, 133, 236, 204, 37057, 2228, 10666, 5052, 133, 6207, 151, 215, 150, 134, 5052, 133, 6279, 5052, 223, 151, 216, 49679, 123, 53110, 47043, 7795, 204, 7544, 7544, 7544, 8543, 8543, 17593, 3513, 3513, 12844, 51520, 17664, 4247, 295, 18, 298, 650, 204, 18, 95, 693, 332, 18, 94, 629, 23, 204, 18, 1553, 299, 1310, 42, 204, 18, 56, 416, 1310, 295, 18, 567, 717, 334, 23, 204, 18, 47, 299, 606, 596, 6696, 42, 703, 18, 16139, 241, 18, 87, 55]
chkhsh: 8aeee3860c56296a157a1fe2fad249ec40aa59b1bb5709f4ade11c4e6fe652ed
tokenizer.ggml.pre: falcon
chkhsh: 8aeee3860c56296a157a1fe2fad249ec40aa59b1bb5709f4ade11c4e6fe652ed
gguf: Adding 64784 merge(s).
gguf: Setting special token type eos to 11
gguf: Setting special token type bos to 11
Exporting model to '/mnt/valerie/models/tiiuae/falcon-7b/ggml-model-f16.gguf'
gguf: loading model part 'pytorch_model-00001-of-00002.bin'
token_embd.weight, n_dims = 2, torch.bfloat16 --> float16
blk.0.attn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
```

I get the expected hash. I am using my PR though, not sure if that has anything to do with it.

**Comment by arch-btw** [comment]
Thank you @teleprint-me , I carefully followed all your steps and now it's working.
This is very strange, I had just updated my llama.cpp and venv maybe 1 or 2 days ago.
Like you said, it could be the sanitized environment and/or recent python upgrade.
Thank you for all your help and I apologize for the confusion.
