### ISSUE TITLE
Command-R-Plus unable to convert or use after BPE pretokenizer update

### ISSUE THREAD

**Issue by sealad886** [ggerganov/llama.cpp#7040]
Trying to re-convert the CohereForAI/command-r-plus model after BPE updates. Model not yet added.

Use `python convert-hf-to-gguf.py`

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

**Comment by HanClinto** [comment]
Appears to be a duplicate of #7030
