### ISSUE TITLE
--timeout parameter on examples/server does not stop longer running inference in slots

### ISSUE THREAD

**Issue by txbm** [ggerganov/llama.cpp#7071]
**Problem:**
When running `./server --timeout 10 -np 8` and sending parallel batches of 8 requests, many of which take longer than 10 seconds to complete.

I observe that over time, slots that are still stuck on long running inference are not released in accordance with the server timeout value of 10 seconds. Slots continue to process indefinitely until eventually they are all occupied and the server refuses all further requests.

**Questions:**
Going through code, it doesn't seem like the `timeout` parameter is used to cancel inference at any point so I'm curious if this parameter is either unused or just does not function that way I'm expecting it to? I could not find any test cases that specifically test to see if slow inferences / slot requests are killed by setting a shorter server timeout.

**Exhibit**
It's easy to observe the effect by running `POST /slots` through a `jq` filter shown below:

<img width="722" alt="Screenshot 2024-05-04 at 12 04 28 AM" src="https://github.com/ggerganov/llama.cpp/assets/102656/878ee03a-c41f-485b-93b5-6860584738f6">

You can see slots `1` and `4` are processing outlying low task ids while the healthy slots are closer in value. The screenshot is just a little while into the prediction set and will get worse the longer it runs.

**Comment by slaren** [comment]
The timeout seems to be only a network read/write timeout, but it does not include the inference time.

**Comment by txbm** [comment]
> The timeout seems to be only a network read/write timeout, but it does not include the inference time.

I'd be happy to submit a PR to fix this if someone familiar with the codebase would be willing to suggest a correct approach for doing so.

**Comment by slaren** [comment]
`llama_decode` is called on a single thread, and cannot be interrupted once it has started. I am not convinced that this is an issue, the only reason to interrupt the inference is if it is broken and stuck, in which case the only thing that can be done is restart the process, which needs to be done externally through a watchdog.

**Comment by slaren** [comment]
Tagging @phymbert for input.

**Comment by phymbert** [comment]
The timeout param might be checked at each server loop ?
@ngxson thoughts?

**Comment by txbm** [comment]
I think in order for parallel inference (aka slots) to be stable, there needs to be some way of timing out long running slots because otherwise it eventually brings the whole process to a halt. I've confirmed this by setting a very aggressive `max_tokens` parameter and re-running the test such that no generation has an opportunity to runaway or stall with the token limiter.

But for more complex tasks where you need longer token maxes, the possibility of a particular slot request running away remains. I think a slot timeout would greatly improve the reliability of slots.

**Comment by ngxson** [comment]
I agree with what @slaren said:
- The `--timeout` is related to httplib, applied at network layer. This will decide if the connection should be terminated in case for example user have a too slow network connection. It is **not** the timeout for inference.
- Without any kind of watchdog or signal, we cannot implement a reliable timeout mechanism. Even with a watchdog, we still cannot terminate `llama_decode` midway.

We could check for timeout at each loop as @phymbert said, but it will never be exact. That's because loop depends on `llama_decode` which we don't know in advance how long it takes to finish.

IMO the simple way now is simple set the appropriate `n_predict` when start the server. Adding timeout will introduce some complexity to the work queue.

**Comment by slaren** [comment]
`llama_decode` doesn't need to be interrupted for generation since there is one call per token. Since each tokens takes roughly the same amount of time to generate, you can achieve the same results by setting a `n_predict` value that matches your desired timeout.

**Comment by txbm** [comment]
> `llama_decode` doesn't need to be interrupted for generation since there is one call per token. Since each tokens takes roughly the same amount of time to generate, you can achieve the same results by setting a `n_predict` value that matches your desired timeout.

Ah, that's an important detail I did not realize. Okay that's an actionable solution then. I will close this issue then. Thank you.
