### ISSUE TITLE
Using #pragma once makes it difficult

### ISSUE THREAD

**Issue by taf2** [ggerganov/llama.cpp#7076]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

It would be helpful to use
 ```
#ifndef GGML_H
#define GGML_H
...
#endif ```

Instead of "#pragma once"

I'm noticing if I include say llama.cpp and whisper.cpp as git submodules in my project then these #pragma once directive do not correctly avoid including the file twice...  Using a GGML_H handles all cases... i'm using latest mac environment too... it's a little more typing in each file but would help make the code easier to use in more environments... thanks!

**Comment by mofosyne** [comment]
Just curious, but which compiler were you using by the way? #pragma once is a non-standard but widely supported [preprocessor directive](https://en.wikipedia.org/wiki/C_preprocessor).

**Comment by taf2** [comment]
@mofosyne 

```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
