### ISSUE TITLE
The convert-hf-to-gguf-update.py seems doesn't work.

### ISSUE THREAD

**Issue by LiyanJin** [ggerganov/llama.cpp#7088]
Ubuntu 20.04,  cudatoolkit12.2
GPU: Nvidia A100 24G
RAM 10G(available)

When I  use the 'convert-hf-to-gguf-update.py' in llama.cpp  to convert ‘hf’ to 'gguf', neither does it report any error nor does it generate the 'gguf' file.
![error1](https://github.com/ggerganov/llama.cpp/assets/18226861/3a78e506-a522-44de-8428-d38d1771caed)

When I use the 'convert-hf-to-gguf.py' in llama.cpp to convert ‘hf’ to 'gguf', the error occurred:
![error2](https://github.com/ggerganov/llama.cpp/assets/18226861/5e9f18ad-32fa-4008-863f-2ee704478d5a)

Has anyone faced this problem?  Does anyone know how to fix this problem?

**Comment by CrispStrobe** [comment]
the update script takes as parameter the hf token. 
seemingly you then (either) copypaste the generated function into convert-hf-to-gguf.py replacing the function there (OR you cp llama.cpp/models/tokenizers/llama-bpe/* /your/model/path, run the script again) & run convert-hf-to-gguf.py (which takes these parameters: convert-hf-to-gguf.py [-h] [--vocab-only] [--awq-path AWQ_PATH] [--outfile OUTFILE] [--outtype {f32,f16}] [--bigendian] [--use-temp-file] model)

**Comment by teleprint-me** [comment]
```sh
python convert-hf-to-gguf-update.py <hf-read-token>
python convert-hf-to-gguf.py /path/to/models/meta-llama/Meta-Llama-3-8B-Instruct-HF --outtype f16
```

Llama-3-8B is already included in the hash sums, so you shouldn't need to do it. If you run into issues with the conversion process, then you'll need to generate the vocabs, follow the instructions in the output, and copy over the retrieved vocabs to the models path. Then you should be able to convert.

**Comment by CrispStrobe** [comment]
but from the screenshot op wants to work on a "merged" model, which might result in different hash?

**Comment by teleprint-me** [comment]
You're almost there 🥲 

Some things to note:

- I am not an expert. I'm learning as I go. Experience is a good teacher. 😅 
- The error is complaining about the vocabulary. Try with `--vocab-type bpe` flag. Reading the errors helps you understand what might have gone wrong. This is a great tip, especially if you're not a programmer.
- Merged models will have mixed results. Something to do with the merging/conversion process. Not sure.
- The tokenizers encodings are hashed, not the language model. So if the vocabulary was modified in any way, shape, or form, the hashes will not match. You'll need to add it, generate the new method, then copy it over to the conversion script to apply it.

Even if the conversion process succeeds, I suspect you'll not get the expected output from the model due to the fact that the models weights were merged. I don't have enough insight to answer why this is the case.

**Comment by CrispStrobe** [comment]
convert.py is not yet adapted to the bpe fix, so if that is needed, use convert-hf-to-gguf.py instead

you should check all the paths and contents involved:
maybe the tokenizer.model simply was not present in the onput path?

can easily be downloaded eg per
`wget "https://huggingface.co/repo/model/resolve/main/tokenizer.model?download=true" -O ~/llama3_hf_merged/tokenizer.model`

& of course, the placeholders ("/your/model/path", "repo/model") must be changed

& not
`cp ~/llama.cpp/models/* ~/llama3_hf_merged/`
but
`cp ~/llama.cpp/models/tokenizers/llama-bpe/* ~/llama3_hf_merged/`
(IF the former is correct, and ofc AFTER first script run)

**Comment by CrispStrobe** [comment]
did it work for you now?
the models/tokenizers/ path is created and filled by the convert-hf-to-gguf-update.py script

**Comment by satyaloka93** [comment]
The tokenizers.json has changed, starting line 2332. Look at Meta's official repo and check your file. That bpe error goes away.

**Comment by satyaloka93** [comment]
Also the tokenizer_config.json, chat template and eos token changes. NousResearch was a bad choice to download from it appears.

**Comment by CrispStrobe** [comment]
maybe you find [this](https://www.kaggle.com/code/chr1str/quantize-with-pretokenizer-fix) quickly hacked kaggle notebook useful for an illustration

**Comment by SanjayDevadiga** [comment]
> Ubuntu 20.04, cudatoolkit12.2 GPU: Nvidia A100 24G RAM 10G(available)
> 
> When I  use the 'convert-hf-to-gguf-update.py' in llama.cpp to convert ‘hf’ to 'gguf', neither does it report any error nor does it generate the 'gguf' file. ![error1](https://private-user-images.githubusercontent.com/18226861/328022329-3a78e506-a522-44de-8428-d38d1771caed.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTA3MDEsIm5iZiI6MTcyMDYxMDQwMSwicGF0aCI6Ii8xODIyNjg2MS8zMjgwMjIzMjktM2E3OGU1MDYtYTUyMi00NGRlLTg0MjgtZDM4ZDE3NzFjYWVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExMjAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYWU2OGU2NjBhOTJhZjdmNTIxMGJhYjJkMTFhZWJkYTBiMTU1ODZiYWJiNTNlOTljMGFhYjk4NzgwYmMyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CCFB9Tjos4idOGauf5PYI1Z7128bq0YkBwSoKz8CfxU)
> 
> When I use the 'convert-hf-to-gguf.py' in llama.cpp to convert ‘hf’ to 'gguf', the error occurred: ![error2](https://private-user-images.githubusercontent.com/18226861/328022342-5e9f18ad-32fa-4008-863f-2ee704478d5a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTA3MDEsIm5iZiI6MTcyMDYxMDQwMSwicGF0aCI6Ii8xODIyNjg2MS8zMjgwMjIzNDItNWU5ZjE4YWQtMzJmYS00MDA4LTg2M2YtMmVlNzA0NDc4ZDVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExMjAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YzUzNjBjOWViMWEyYzY1MzEwMGNhMmYxMGE2N2FhOTkyMmJkZjIyYTc0NDQyMWQ0ZjkwMzE3MTA4Yzk0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Cpbk3UZB_zsWTEz0ckdwlXC9U3P6lDRnaFJVQ-WygA)
> 
> Has anyone faced this problem? Does anyone know how to fix this problem?

I encountered the same problem when I was converting phi-2 model
This is how I fixed :
     1. check convert_hf_to_gguf_update.py line 66
          For me there was no model link for phi 2 so I added the below line into that list
          model  = [
                                {"name": "phi-2",      "tokt": TOKENIZER_TYPE.BPE, "repo": "https://huggingface.co/microsoft/phi-2", },
                                ....rest of the items
                                }
                          ]
    2. Run the convert_hf_to_gguf_update.py
        convert_hf_to_gguf_update.py <Your hugging face token>
        You can create or find a token in your hugging face profile settings(I created a token with read/write access)

   3. Now run the conversion script after the previous scripts completes
       python convert-hf-to-gguf.py ~/llama3_hf_merged/ --outfile ~/model/gml-model-f16.gguf --outtype f16
       
    
I hope it works
