### ISSUE TITLE
Is possible to hide start / stop tokens? 

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#7100]
Example llamacpp output in the terminal with llama3 

````
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful, smart, kind, and efficient AI assistant. You always fulfill the user's requests to the best of your ability.
> <|start_header_id|>user<|end_header_id|>

name countries starts with letter Z. \
<|start_header_id|>assistant<|end_header_id|>

Here are some countries that start with the letter Z:

1. Zambia
2. Zimbabwe

Note: These are the only two countries whose names begin with the letter Z.

Is there anything else I can help you with?<|eot_id|>

> <|start_header_id|>user<|end_header_id|>

````

Is possible to hide system, start, stop, in-prefix and in-suffif tokens in the terminal ?

**Comment by dawidpotocki** [comment]
As far as I know, you need to patch llama.cpp to do this.

Here is a simple patch I wrote for my own use:
https://github.com/dawidpotocki/llama.cpp/commit/8c2db3757b49f94235b23b9413b9df140cc1d01f

Example output:
```
> Hello!
Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?

> Nah, I'm good.
No worries then! It's always okay to just chill and say hi.

>
```

**Comment by arch-btw** [comment]
@dawidpotocki that's perfect! I agree, would you please consider adding it to main? Thank you!

**Comment by MB7979** [comment]
Yes, the printing of the EOS token bugs me too. I’m only used to that when tokenisation is awry, so it feels strange to have it be a default in main.
