### ISSUE TITLE
Binary starting with b2715 doesn't work on Intel Mac anymore

### ISSUE THREAD

**Issue by damnkittyworks** [ggerganov/llama.cpp#7110]
I have a 2018 MacBook Pro. I'm able to run the b2714 binary without issues. Starting with b2715 (llama-b2715-bin-macos-x64.zip) I'm getting this message: "zsh: bad CPU type in executable: ./main".

<img width="594" alt="Screenshot 2024-05-06 at 9 02 00 PM" src="https://github.com/ggerganov/llama.cpp/assets/161262078/ef4c7c4b-45b1-4f0f-9ba8-7a8867f8e603">

<img width="594" alt="Screenshot 2024-05-06 at 9 03 12 PM" src="https://github.com/ggerganov/llama.cpp/assets/161262078/082ccd46-81e8-4cfb-ba4c-954d463ef0aa">

**Comment by psugihara** [comment]
I just tried using the x64 binary to update my lipo'd server binary used [freechat](https://github.com/psugihara/FreeChat). I usually compile myself. `lipo` gives me an error that makes me think there's something wrong with the intel binary:

```
➜  lipo -create server server_x64 -output freechat-server
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: server and server_x64 have the same architectures (arm64) and can't be in the same fat output file
```
