### ISSUE TITLE
Server: Multimodal Model Input Parameter No longer Exists

### ISSUE THREAD

**Issue by lyonsniall** [ggerganov/llama.cpp#7112]
I have noticed that when using the server that the --mmproj parameter for multimodal models has been disabled. Although it still remains in the README. Is there an alternative to --mmproj , I cannot seem to find one in the code. 

Any help on this would be great. 

Code to reproduce:
`./server -m ./ggml-model-q4_k.gguf --mmproj ./mmproj-model-f16.gguf -ngl 1`

Error:
`
error: unknown argument: --mmproj
usage: ./server [options]
`

**Comment by Jeximo** [comment]
> Although it still remains in the README.

Yes, readme needs an update. It's temporarily disabled to be reimplemented later: https://github.com/ggerganov/llama.cpp/pull/5882#issue-2168710134

You might use older versions of `llama.cpp` to keep the feature, or try https://github.com/ggerganov/llama.cpp/tree/947d3ad27d94f1addef76b5d64c314618f063933/examples/llava#llava

**Comment by Single430** [comment]
> > Although it still remains in the README.
> 
> 
> 
> Yes, readme needs an update. It's temporarily disabled to be reimplemented later: https://github.com/ggerganov/llama.cpp/pull/5882#issue-2168710134
> 
> 
> 
> You might use older versions of `llama.cpp` to keep the feature, or try https://github.com/ggerganov/llama.cpp/tree/947d3ad27d94f1addef76b5d64c314618f063933/examples/llava#llava


Hello, may I ask when this parameter can be restored? --mmproj

**Comment by randoentity** [comment]
See https://github.com/Mozilla-Ocho/llamafile/commit/8ff1283d7b35aeb07c98730e18cb6bcbe5d9c7c4 for an example on how to selectively revert this change, or use llamafile if you weren't aware of that project.
