### ISSUE TITLE
Question about high perplexity about llama3-8b-hf in gguf format

### ISSUE THREAD

**Issue by bulaikexiansheng** [ggerganov/llama.cpp#7119]
Thanks for your excellent work! I try to run codes below:

`
./perplexity -m /data/models/llama3-8b-instruct/ggml-model-f16.gguf -f /home/liwenyuan/projects/dataset/wikitext-2-raw/wiki.test.raw
`

And I get the output:
`
(powerinfer_env) [liwenyuan@rtx4090-4c bin]$ ./perplexity -m /data/models/llama3-8b-instruct/ggml-model-f16.gguf -f /home/liwenyuan/projects/dataset/wikitext-2-raw/wiki.test.raw
main: build = 2716 (4e96a812)
main: built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: seed  = 1715064711
llama_model_loader: loaded meta data with 21 key-value pairs and 291 tensors from /data/models/llama3-8b-instruct/ggml-model-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = models
llama_model_loader: - kv   2:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                          llama.block_count u32              = 32
llama_model_loader: - kv   6:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   7:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   8:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   9:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  10:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  11:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  12:                          general.file_type u32              = 1
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  15:                      tokenizer.ggml.scores arr[f32,128256]  = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128001
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:  226 tensors
llm_load_vocab: special tokens definition check successful ( 256/128256 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = F16
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 14.96 GiB (16.00 BPW)
llm_load_print_meta: general.name     = models
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 4 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 2: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 3: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size = 15317.02 MiB
.........................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   256.00 MiB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     1.96 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  1260.50 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    12.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 356

system_info: n_threads = 40 / 80 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
perplexity: tokenizing the input ..
perplexity: tokenization took 1117.7 ms
perplexity: calculating perplexity over 564 chunks, n_ctx=512, batch_size=2048, n_seq=4
perplexity: 17.71 seconds per pass - ETA 41.60 minutes
[1]6.2578,[2]7.0820,[3]7.6175,[4]8.1553,[5]8.5626,[6]8.8609,[7]9.4111,[8]10.0862,[9]10.7287,[10]11.0607,[11]11.2369,[12]11.4211,[13]11.8807,[14]11.4048,[15]11.2609,[16]10.9189,[17]10.8444,[18]10.9396,[19]10.6892,[20]10.5330,[21]10.5452,[22]10.1211,[23]9.6905,[24]9.4533,[25]9.1141,[26]8.9914,[27]8.8351,[28]8.6898,[29]8.8007,[30]8.7426,[31]8.7231,[32]8.7004,LI[33]8.7656,[34]8.8097,[35]8.8430,[36]8.9859,[37]8.9415,[38]9.0010,[39]8.9762,[40]9.0046,[41]9.0168,[42]8.9253,[43]8.9614,[44]8.8925,[45]8.9941,[46]9.0033......
Final estimate: PPL = 9.1766 +/- 0.06994

llama_print_timings:        load time =    2213.24 ms
llama_print_timings:      sample time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time = 2080363.27 ms / 288768 tokens (    7.20 ms per token,   138.81 tokens per second)
llama_print_timings:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time = 2089558.86 ms / 288769 tokens
`

Its perplexity is too high. Is there anything wrong？And why the "eval time" equals to 0.00ms?

What's more, i compare the perplexity between llama3-8b-hf and llama3-8b-hf-instruct. Why does a model without fine-tuning have lower perplexity than a model with fine-tuning？

llama3-8b-hf: 
' 
Final estimate: PPL = 6.7645 +/- 0.04275
llama_print_timings:        load time =    1828.29 ms
llama_print_timings:      sample time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time = 2014594.39 ms / 288768 tokens (    6.98 ms per token,   143.34 tokens per second)
llama_print_timings:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time = 2023727.81 ms / 288769 tokens
'

llama3-8b-hf-instruct:
'
Final estimate: PPL = 9.1766 +/- 0.06994
llama_print_timings:        load time =    2213.24 ms
llama_print_timings:      sample time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time = 2080363.27 ms / 288768 tokens (    7.20 ms per token,   138.81 tokens per second)
llama_print_timings:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time = 2089558.86 ms / 288769 tokens
'

**Comment by JohannesGaessler** [comment]
>And why the "eval time" equals to 0.00ms?

Because there are no evals with batch size 1.

Everything else: https://github.com/ggerganov/llama.cpp/tree/master/examples/perplexity

**Comment by turian** [comment]
I had this and also was surprised. The perplexity is high because per-token perplexity scores will be larger when there are 128K vocabulary tokens versus 32K vocab tokens in Llama 2. See discussion here: #7111

**Comment by turian** [comment]
I also found that fine-tuned models generally have worse perplexity. This is because fine-tuning a model, e.g. for chat, steers it away from generating non-chat like text, even if that text is "acceptable".  So a chat model will have lower generation probability for, say, wikitext than it would for a chat-like reply.

**Comment by turian** [comment]
@bulaikexiansheng lastly, there is a recent tokenization bug which means that older quantized models are getting worse perplexity scores than they should. I'm not sure if it's fixed yet, it's about a week or so old?

**Comment by Galunid** [comment]
@bulaikexiansheng You're using outdated build (https://github.com/ggerganov/llama.cpp/commit/4e96a812b3ce7322a29a3008db2ed73d9087b176 - from 2 weeks ago). There were many changes since then. Please retry with the latest build with models converted using latest commits.

**Comment by daicver** [comment]
> @bulaikexiansheng您正在使用过时的版本（[4e96a81](https://github.com/ggerganov/llama.cpp/commit/4e96a812b3ce7322a29a3008db2ed73d9087b176) - 两周前）。从那时起发生了很多变化。请使用最新版本重试并使用最新提交转换模型。

I get a result but don't know if it is correct and what the correct value should be?

**Comment by hyperbolic-c** [comment]
@daicver Hi, could you please share some data about llama3's PPL with different quantize type? Thanks !
