### ISSUE TITLE
(Server) Strange behavior with JSON Schema with Llama 3

### ISSUE THREAD

**Issue by its-ven** [ggerganov/llama.cpp#7123]
The bug seems to happen at random after a few turns. I'm on the latest quants with the BPE fix.
Essentially, I'm running a loop of queries and forcing a JSON schema with three string values (though this happens with any schema).

Here is some test code I wrote for this issue:
```
    from openai import OpenAI
    schema = {
        "type": "object",
        "properties": {
            "line1": {"type": "string"},
            "line2": {"type": "string"},
            "line3": {"type": "string"}
        },
        "required": [
            "line1",
            "line2",
            "line3"
        ]
    }
    subjects = [
        "firetrucks",
        "zucchini",
        "Carl Sagan",
        "Beef Wellington",
        "trigonometry",
        "healthy diets"
    ]
    
    llama = "http://localhost:8080/v1"
    client = OpenAI(api_key="None", base_url=llama)
    model="None"
    history = [{"role": "system", "content": "You are an AI that writes paragraps split into three JSON values."}]
    for subject in subjects:
        history.append({"role": "user", "content": f"write a witty remark about {subject}"})
        completion = client.chat.completions.create(model=model, messages=history, extra_body={"json_schema": schema})
        result = completion.choices[0].message.content.strip()
        print(result)
        print("###")
        history.append({"role": "assistant", "content": result})
```
Without schema, it works perfectly. I asked it to write haikus and it had no issue:
![image](https://github.com/ggerganov/llama.cpp/assets/134007790/acc18f2e-6118-4704-b231-3c2638484135)

When using a JSON schema, it created the first three completions but timed out while creating the fourth one.
Here is a scenario with pretty much the same code, except for a different prompt:

> You are a sentiment analysis AI.
                RULES:
                -You can only emit JSON.
                -Provide an immediate reaction to the incoming messages, which take the form of JSON schemas.
                -Each JSON schema contains data received from a source.
                -After the analysis, provide an emotional reaction to the incoming data.
                -Keep track of the source of the data from each module.
                -Be wary of inconsistencies between each piece of data, and if there any, report them accordingly in your reaction.
                -Follow the JSON Template.
                ###
                JSON Template:
                {{
                    "reaction": "The immediate reaction to the latest data.",
                    "inconsistency_awareness": "Describe inconsistencies between pieces of data.",
                    "emotion": "A sequence of 3 to 5 expressive emojis."
                }}

I put four different messages. First run works as expected...
![image](https://github.com/ggerganov/llama.cpp/assets/134007790/d5ae642b-5684-49b0-ae57-c3809aedc546)
Then, I noticed the GPU usage plateauing and the lone spike or two, which, for the past few days, has been the indicator that something was about to break.
![image](https://github.com/ggerganov/llama.cpp/assets/134007790/c42bf841-2769-4c5a-b406-f7f85e28072e)

And there it was:
![image](https://github.com/ggerganov/llama.cpp/assets/134007790/b4c410eb-f7e9-449c-9334-20e67138080d)

Whatever this issue is, it seems it gets stuck repeating the last few predicted tokens. Doesn't just happen with emojis, but text too.
Here is another from earlier today that I managed to screenshot, where the messages alternated between two characters, Sandra and Kevin. The messages were about two people going back and forth about the taste of tap vs bottled water. I have no idea where it got the heartbreak and knife from:
![image](https://github.com/ggerganov/llama.cpp/assets/134007790/154eb8d6-29c3-4486-a6a2-0e1e97e7fd63)

Any ideas? I'm using [Bartowski ](https://huggingface.co/bartowski/Meta-Llama-3-8B-Instruct-GGUF/tree/main) quants.

**Comment by ggerganov** [comment]
You might be running out of context, but it's hard to tell.

Please provide repro instructions (actual commands) using `llama.cpp` examples, otherwise we won't be able to help you

**Comment by ggerganov** [comment]
Try adding `-c 8192` to the arg list - by default `server` uses context size of 512

**Comment by its-ven** [comment]
> Try adding `-c 8192` to the arg list - by default `server` uses context size of 512

Oh my god I feel so silly, I thought setting n_predict was the same thing. It works as expected now, thank you!
