### ISSUE TITLE
could we get Aryanne/Calypso-3B-alpha-v2-gguf added to the demo?

### ISSUE THREAD

**Issue by Louis654** [ggerganov/llama.cpp#7126]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

this one fills a gap that's currently not really covered well by any of the others options in that it provides a bot that's better for conversation rather than information, I might be wrong but I think it would be a good edition

# Motivation

it would allow us to test the chat capabilities when limited on resources such as on a android or Linux enviroment

# Possible Implementation

I'm not sure how to do this part myself but I'm sure whoever added the other ones knows the process of adding it

**Comment by Jeximo** [comment]
I think you're suggesting calypso-3b-alpha
does not run in `llama.cpp`? 

`./main -m ~/calypso-3b-alpha-v2.Q8_0.gguf -p 512 -n 128 -ins -p "You're an AI."` works for me:
![Screenshot_20240507_145344](https://github.com/ggerganov/llama.cpp/assets/21167443/c23ace3d-8d2e-45d2-ae2e-cc8d1958653e)

**Comment by Louis654** [comment]
I'm running it right now using the APK downloaded from the website, I'm not sure how to add it myself
