### ISSUE TITLE
[Server] JSON outputs are not being enforced according to the JSON Schema.

### ISSUE THREAD

**Issue by remixer-dec** [ggerganov/llama.cpp#7149]
Hello. I noticed that server README mentions a parameter named "json_schema", if I understand correctly, when it is present, it is converted to a grammar which should force the output to be in a strict format. However, for some reason, the output does not match even the simplest schemas when the last message in chat completions request is from user asking for something. Here is my example:

running the server (commtit 83330d8) on m1 mac:
```sh
./server -m Meta-Llama-3-8B-Instruct.Q5_K_M.gguf -ngl 99 -c 8192 --chat-template llama3
# or 
./server -m mistral-7b-instruct-v0.2.Q4_K_M.gguf -ngl 99 --chat-template chatml     
```

testing with curl:
```bash

curl -X POST \
  http://localhost:8080/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "temperature": 0.5,
    "n_predict": 512,
    "response_format": {"type": "json_object"},
    "json_schema": {
      "title": "SummarySchema",
      "type": "object",
      "properties": {
        "summary": {
          "type": "string"
        },
        "mentioned_characters": {
          "type": "string"
        }
      },
      "required": [
        "summary",
        "mentioned_characters"
      ]
    },
    "messages": [
      {"role": "system", "content": "This is a conversation. Provide a summary according to the following schema: { \"title\": \"SummarySchema\", \"type\": \"object\", \"properties\": { \"summary\": { \"type\": \"string\" }, \"mentioned_characters\": { \"type\": \"string\" } }, \"required\": [ \"summary\", \"mentioned_characters\" ]}"},
      {"role": "user", "content": "Tell me about Albert Einstein."},
      {"role": "assistant", "content": "Albert Einstein was a theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics."},
      {"role": "user", "content": "How about Isaac Newton?"},
      {"role": "assistant", "content": "Isaac Newton was an English mathematician, physicist, astronomer, and author who is widely recognised as one of the most influential scientists of all time and a key figure in the scientific revolution."},
      {"role": "user", "content": "Also can you say something about Sam Altman?"}
    ]
  }'


```
  
The server sometimes returns the definition of the schema instead of actually following it. Is this a bug or the grammar is not intended for enforcing json keys? Is it better to give the model instruction in the last message instead of system prompt?  
<img width="1432" alt="screenshot" src="https://github.com/ggerganov/llama.cpp/assets/6587642/e80a4e47-fd31-43da-a48b-f319317bca24">

**Comment by ngxson** [comment]
`json_schema` is not an OAI-compat field, so we don't have that in `/chat/completions`. Instead, it is nested inside `response_format`

```
{
  "response_format": {
    "type": "json_object",
    "schema": ...
  }
}
```

https://github.com/ggerganov/llama.cpp/blob/c12452c7aec8a02264afc00196a13caa591a13ac/examples/server/utils.hpp#L388C14-L388C41

**Comment by remixer-dec** [comment]
@ngxson thanks for clarification! Providing schema inside `response_format` works! 
It is a bit confusing, since this block is executed even in chat completions:
https://github.com/ggerganov/llama.cpp/blob/c12452c7aec8a02264afc00196a13caa591a13ac/examples/server/server.cpp#L867-L870
And both parameters are mentioned in the docs, after I found the first one, I didn't know there is also a second one.

**Comment by ngxson** [comment]
Yeah in fact `/chat/completions` is based on OpenAI schema, while `/completion` accepts llama.cpp-specific params. There is a conversion layer between the two (a.k.a `oaicompat_completion_params_parse`).

But overall I agree that there's some inconsistencies here, maybe we can come up with a better solution in the future.
