### ISSUE TITLE
Windows Quantize isn't working 

### ISSUE THREAD

**Issue by dsfasdfasdfasdfasd9** [ggerganov/llama.cpp#715]
![image](https://user-images.githubusercontent.com/112736962/229361374-f3a72b6c-091b-4ddd-997d-95b5c97ef01f.png)

Im on win11 and barely know how to get this even remotely running and I am having a stroke of whats going wrong with this.

**Comment by prusnak** [comment]
You need to run quantize.exe since you are on windows, not ./quantize.

Also you need to compile if first
