### ISSUE TITLE
how can i modify the setting,make it answer in Chinese by default

### ISSUE THREAD

**Issue by LiangZeFenglzf** [ggerganov/llama.cpp#7167]
I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).

i want it answer me in Chinese，please tell me how to modify code to achieve it.
![image](https://github.com/ggerganov/llama.cpp/assets/92996231/5422a271-3aa2-47fb-81fa-13949b7aad8b)
there is no data folder

**Comment by mirek190** [comment]
Add a proper system prompt that you want Chinese conversation / responses . You can even write system prompt in Chinese as well.

**Comment by liangDarwin2** [comment]
you may need a Chinese finetuned version of llama-3

**Comment by LiangZeFenglzf** [comment]
> you may need a Chinese finetuned version of llama-3
you mean https://github.com/ymcui/Chinese-LLaMA-Alpaca?

**Comment by LiangZeFenglzf** [comment]
> Add a proper system prompt that you want Chinese conversation / responses . You can even write system prompt in Chinese as well.

![image](https://github.com/ggerganov/llama.cpp/assets/92996231/2734ad13-2095-49aa-bd19-f959731b266d)

**Comment by mirek190** [comment]
> > Add a proper system prompt that you want Chinese conversation / responses . You can even write system prompt in Chinese as well.
> 
> ![image](https://private-user-images.githubusercontent.com/92996231/329425929-2734ad13-2095-49aa-bd19-f959731b266d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjU2MDAsIm5iZiI6MTcxNTMyNTMwMCwicGF0aCI6Ii85Mjk5NjIzMS8zMjk0MjU5MjktMjczNGFkMTMtMjA5NS00OWFhLWJkMTktZjk1OTczMWIyNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDQ4M2ZmNzE2MTk4NzQ0ZDcwODcxYzliNDhkMTg0MzdkYTU3ZWM4ZjY0NDk2ZDAwOGJjYzFjMzg1YTQ4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LgbC2KTJE1awzDEaMUwt9PEiBxV0qoM4CulywTijJYg)

Your system prompt should  be more "elaborate" and do you have a proper template?

**Comment by LiangZeFenglzf** [comment]
> > > Add a proper system prompt that you want Chinese conversation / responses . You can even write system prompt in Chinese as well.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92996231/329425929-2734ad13-2095-49aa-bd19-f959731b266d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjU2MDAsIm5iZiI6MTcxNTMyNTMwMCwicGF0aCI6Ii85Mjk5NjIzMS8zMjk0MjU5MjktMjczNGFkMTMtMjA5NS00OWFhLWJkMTktZjk1OTczMWIyNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDQ4M2ZmNzE2MTk4NzQ0ZDcwODcxYzliNDhkMTg0MzdkYTU3ZWM4ZjY0NDk2ZDAwOGJjYzFjMzg1YTQ4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LgbC2KTJE1awzDEaMUwt9PEiBxV0qoM4CulywTijJYg)
> 
> Your system prompt should be more "elaborate" and do you have a proper template?

I can't see the picture you post,could you comment again with this picture?
and actually,i dont know what is a proper template.i just know this project for less than 3 days.

**Comment by scottstirling** [comment]
In that prompt text area put any context or role or output expectations as clearly as possible, which then become an implicit system message shaping the LLLM responses in the interaction on the chat screen.

Something like, at least:
你总是回答中文

**Comment by LiangZeFenglzf** [comment]
> In that prompt text area put any context or role or output expectations as clearly as possible, which then become an implicit system message shaping the LLLM responses in the interaction on the chat screen.
> 
> Something like, at least: 你总是回答中文

thank you,i know what do you mean.more elaborate~~

**Comment by LiangZeFenglzf** [comment]
> > > Add a proper system prompt that you want Chinese conversation / responses . You can even write system prompt in Chinese as well.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92996231/329425929-2734ad13-2095-49aa-bd19-f959731b266d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjU2MDAsIm5iZiI6MTcxNTMyNTMwMCwicGF0aCI6Ii85Mjk5NjIzMS8zMjk0MjU5MjktMjczNGFkMTMtMjA5NS00OWFhLWJkMTktZjk1OTczMWIyNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDQ4M2ZmNzE2MTk4NzQ0ZDcwODcxYzliNDhkMTg0MzdkYTU3ZWM4ZjY0NDk2ZDAwOGJjYzFjMzg1YTQ4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LgbC2KTJE1awzDEaMUwt9PEiBxV0qoM4CulywTijJYg)
> 
> Your system prompt should be more "elaborate" and do you have a proper template?

i know what do you mean,thank you!
