### ISSUE TITLE
quantize: command not found

### ISSUE THREAD

**Issue by userandpass** [ggerganov/llama.cpp#7196]
quantize /data/models/aixcoder/aixcoder-7b-base/ggml-model-f16.gguf /data/models/aixcoder/aixcoder-7b-base/ggml-model-Q4_K_M.gguf Q4_K_M

**Comment by calculatortamer** [comment]
forgot "./" before quantize?

or forgot to add the git directory to PATH?

**Comment by userandpass** [comment]
I can execute it after I add "./",thank you.

> forgot "./" before quantize?
> 
> or forgot to add the git directory to PATH?

I can execute it after I add "./",thank you.
