### ISSUE TITLE
build server success but execute  `ggml_cuda_init: failed to initialize CUDA: unknown error`

### ISSUE THREAD

**Issue by wzhgithub** [ggerganov/llama.cpp#7218]
I compiled the binary file of the server on a machine with a 3090 graphics card. Then when I executed the server, I found `ggml_cuda_init: failed to initialize CUDA: unknown error` and cuda was not found,  and model is been loaded in any gpus
but I had added parameters when compiling` LLAMA_CUDA=1`
And I can compile and execute the server binary correctly on another 1080ti machine under the same compilation parameters.

device: NVIDIA GeForce RTX 3090
env: NVIDIA-SMI 545.29.02              Driver Version: 545.29.02    CUDA Version: 12.3 
cmd: make server LLAMA_CUDA=1 CUDA_DOCKER_ARCH=all
error:  ggml_cuda_init: failed to initialize CUDA: unknown error

**Comment by inversetrs** [comment]
you can solve this in linux with: sudo modprobe nvidia_uvm

**Comment by otonoton** [comment]
Same issue here, rebooting does not solve, nor removing and re-inserting `nvidia_uvm`.

**Comment by Oussamayousre** [comment]
@wzhgithub Please did you end up resolving the problem , i have the exact same problem and I almost tried everything , nothing seems to work !

**Comment by vjayd** [comment]
Same here with docker file

**Comment by egorsmkv** [comment]
Restaring the computer helped me

**Comment by PurplProto** [comment]
I use the `llama.cpp:server-cuda` container and encountered this error after a recent system update. Restarting did not help and `lsmod | grep nvidia_umv` already showed that the module was loaded. 

Checked back on the recent package installs since I last knew it was working and both NVIDIA Container Toolkit and Docker had been updated, so not sure which caused it to break, but I did find a fix,  regenerating the CDI spec:
```sh
sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml && sudo systemctl restart docker
```

Booted up the container and the error was gone. Hope it helps someone 🙂

**Comment by NickVandenberghe** [comment]
> I use the `llama.cpp:server-cuda` container and encountered this error after a recent system update. Restarting did not help and `lsmod | grep nvidia_umv` already showed that the module was loaded.
> 
> Checked back on the recent package installs since I last knew it was working and both NVIDIA Container Toolkit and Docker had been updated, so not sure which caused it to break, but I did find a fix, regenerating the CDI spec:
> 
> sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml && sudo systemctl restart docker
> Booted up the container and the error was gone. Hope it helps someone 🙂

You legend, 
i have been struggling after a re-install of arch and i just couldn't figure out why my container wasn't working

**Comment by DanielWeiner** [comment]
This still is an issue on Arch Linux kernel 7.2.6. My workaround was the above fix, run as a systemd service before docker starts. That way you avoid a manual step on boot.

`nvidia-docker.service`
```
[Unit]
Description=Regenerate NVIDIA CDI config before Docker starts
Before=docker.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
ExecStart=nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
RemainAfterExit=yes
TimeoutSec=90

[Install]
WantedBy=multi-user.target
```
