### ISSUE TITLE
Server api not functioning with frontends

### ISSUE THREAD

**Issue by wooooyeahhhh** [ggerganov/llama.cpp#7231]
Windows 10

Using a frontend such as SillyTavern connected using the api the generation will never begin upon sending a generation request. This also happens when using ChatterUI, the normal local server works however

**Comment by Wuzzooy** [comment]
I've met the same issue on the last staging version of sillytavern.
Text completion api doesn't work but the chat completion works.
On the release version branch both works so i doubt the issue in on llama server side.

**Comment by wooooyeahhhh** [comment]
> I've met the same issue on the last staging version of sillytavern. Text completion api doesn't work but the chat completion(custom openai compatible api ) works. On the release version branch both works so i doubt the issue is on llama.cpp server side.

Generation is working when I use an older version so it looks like an issue with ST

**Comment by wooooyeahhhh** [comment]
recent commit on ST fixed it.
