### ISSUE TITLE
In my os, the @ symbol and spaces don’t play nicely in llama.cpp directory. 

### ISSUE THREAD

**Issue by atljoseph** [ggerganov/llama.cpp#7247]
Just shows folder named llama.cpp with no contents. Nuff said. Ubuntu 22.04.

**Comment by atljoseph** [comment]
Oh. For some reason docker.sh downloaded images that were only arm64, so I tried to build the images myself and ran into some python error. Then start.sh downloaded the files into the llama.cpp folder. I’m still confused about the @ symbol though

**Comment by atljoseph** [comment]
G2g on this

**Comment by atljoseph** [comment]
Good to go on this

**Comment by arnfaldur** [comment]
Please describe your issue in much greater detail. 

What exactly are you trying to do? What have you done to reach this point?

**Comment by atljoseph** [comment]
Eh it’s all good now thanks. Too long to mention here. Not really an issue
with your great work here. Another project brought in a specific linked
commit from here and it was a folder with at symbol. Worked out great,
after figuring out the right config and having the right cuda version
agreement, and working out a PATH ordering issue. Thanks for the reply
