### ISSUE TITLE
Using Repeat_last_n and Repeat_penalty To Avoid Going Back and Repeating Itself?

### ISSUE THREAD

**Issue by chigkim** [ggerganov/llama.cpp#727]
I set --repeat_last_n 256 --repeat_penalty 1.9.
However, after a while, it keeps going back to certain sentences and repeating itself as if it's stuck in a loop.
Is this a bug, or am I using the parameters incorrectly?
What's the maximum value you can set for repeat_penalty, so it doesn't repeat itself?

**Comment by MillionthOdin16** [comment]
I'm not an expert, but I've noticed hit and miss behaviors related to these settings. One thing I've seen is that it works a bit better when I don't go above ~128 for repeat_last and I haven't seen anyone go above ~1.3 for repeat penalty. I would try some lower values and see if it makes a difference. Your prompting can also have an effect as well, just to keep in mind.
