### ISSUE TITLE
Error when trying to convert a HF model which is a LORA PEFT fine tuned version of phi-128k

### ISSUE THREAD

**Issue by swarnava112** [ggerganov/llama.cpp#7287]
![image](https://github.com/ggerganov/llama.cpp/assets/37950223/c88b5068-98c4-48f8-9d6d-eb1333b4c5a9)

I am trying to convert a HF model I finetuned, the model is an adapter model for microsoft phi-128k. I donot know what arch should I specify as I didnot see "phi" as an arch option, when I looked into the code.

Any help is appriciated.

**Comment by arnfaldur** [comment]
llama.cpp does not support phi-3-128k currently https://github.com/ggerganov/llama.cpp/issues/6849
The work on adding it is happening here https://github.com/ggerganov/llama.cpp/pull/7225

Please try searching a little before opening an issue. Feel free to close it as well as it's already being tracked.

**Comment by ngxson** [comment]
The `convert-lora-to-ggml` script has been deprecated and already been removed: #7204
