### ISSUE TITLE
How to quantize fine-tune LLM into GGUF format

### ISSUE THREAD

**Issue by dibyendubiswas1998** [ggerganov/llama.cpp#7299]
Hi, I fine-tune mistral-7b model for my question-answering task (after quantization in 4bit using LoRA, QLoRa).
Now I want to convert the fine-tuned LLM model into gguf format for CPU inferencing.

**Comment by yentur** [comment]
You can use convert.py.

**Comment by ngxson** [comment]
You can firstly merge the qlora into the model (that will produce a new set of `.safetensors` files)

Then either use `convert.py` or `convert-hf-to-gguf.py` to convert the safetensors model into gguf

**Comment by Minhsuperfragile** [comment]
Hi, I the convert-hf-to-gguf.py does not have q4 output type, how can I convert my hf to 4-bit gguf

**Comment by Minhsuperfragile** [comment]
> You can firstly merge the qlora into the model (that will produce a new set of `.safetensors` files)
> 
> Then either use `convert.py` or `convert-hf-to-gguf.py` to convert the safetensors model into gguf
> 
> P/s: `convert-lora-to-ggml.py` is removed a while ago, so the only way to run qlora currently is to merge & convert

Hi, the convert-hf-to-gguf.py does not have q4 output type, how can I convert my hf to 4-bit gguf

**Comment by suspicious-pineapple** [comment]
is GGUF qlora within scope at some point, or are there some technical things preventing that?

alternatively, is it somehow possible to turn a 4bit qlora into a 16 bit one?
