### ISSUE TITLE
[SYCL] include shared libs in sycl release

### ISSUE THREAD

**Issue by gfody** [ggerganov/llama.cpp#7361]
can the shared libs be included in the bin-win-sycl-x64 release?

**Comment by NeoZhangJianyu** [comment]
@gfody 
Yes, it's supported by PR https://github.com/ggerganov/llama.cpp/pull/7241.

**Comment by gfody** [comment]
ah yeah the sycl dependencies are included but llama.dll is missing, because `-DBUILD_SHARED_LIBS=ON` is not here: https://github.com/ggerganov/llama.cpp/blob/917dc8cfa67a72fb7c8bf7392270da3bf4833af4/examples/sycl/win-build-sycl.bat#L19

**Comment by NeoZhangJianyu** [comment]
Yes, we will check and fix it.
