### ISSUE TITLE
bf16 problem

### ISSUE THREAD

**Issue by Zibri** [ggerganov/llama.cpp#7365]
I have a model that has been converted from the original to bf16...
now I want to make some quantization testing with that but quantize says:

cannot dequantize/convert tensor type bf16

I don't understand why, since bf16 and f16 are not that different...

**Comment by jukofyork** [comment]
If you first up cast to fp32 it will probably work as bf16 if just fp32 with 16 of precision bits truncated:

https://en.m.wikipedia.org/wiki/Bfloat16_floating-point_format
