### ISSUE TITLE
commit `96ea727` breaks compilation in Windows

### ISSUE THREAD

**Issue by etra0** [ggerganov/llama.cpp#74]
Sadly, Windows terminal support of ANSI colors and signals is simply... non-existent, and this PR in particular adds a ton of things that are not supported by this OS.

I don't know if filling the entire llama.cpp with `#ifdef`s would be ideal... or to rewrite those changes to encapsulate them better to make it less painful, but either way, it is a lot of work.

Reverting that commit and doing a couple of merge fixes makes it work.

PS: Maybe it would be good to add an action that compiles the software in the three platforms? but, yet, I'm curious about the willing to support windows as well since it's the special kid between the unix-like guys :)

**Comment by etra0** [comment]
Oh my god, I'm sorry for all the edits, I thought links on the titles were supported, lol

**Comment by blackhole89** [comment]
I #if-gated the signals-related stuff (which I figure would not work on Windows). As for ANSI colors, I figure you can always just not pass `--color`. Did that fix the build?

**Comment by etra0** [comment]
I confirm that the commit a169bb889cfe7b77a798f04fbc573e67ccb4316a fixes this issue!
