### ISSUE TITLE
Specific suggested wiki "Feature Matrix" updates pertaining to SYCL.

### ISSUE THREAD

**Issue by ghchris2021** [ggerganov/llama.cpp#7415]
Specific suggested wiki "Feature Matrix" updates pertaining to SYCL (q.v. attached draft).

Modified / added footnotes 1,7, tried to make consistent with README-sycl.md and various
pertinent SYCL pull requests / issues active in recent weeks.
Some additional clarifications of which quantization / data types besides the IQ ones could
be updated by someone who has clarity about the status quo (I do not) wrt. 
F16/F32/Q_n_K_x/I8/BF16/....etc.

IDK how using the GH web interface to submit a PR for the Feature-matrix.md file in the wiki section git so I thought I'd
try this since it's just a few simple changes to the one markdown file as a basis.

[https://github.com/ghchris2021/tmpwiki0520/blob/a58564aa18210814fdc07dadb54018f7f612b099/Feature-matrix.md](url)

**Comment by NeoZhangJianyu** [comment]
@ghchris2021 
Here is the update as my understanding:
I-quants: SYCL- Yes  iq1_s is fault (big error) in one case. That won't impact to support the feature.
Multi-GPU: SYCL -Yes.    not support [row]: in fact, it's supported, but with lower performance. Can't be used in real case. 
K cache quants: SYCL -Yes
MoE architecture: SYCL - Yes. There is known bug, I will fix it recently.
