### ISSUE TITLE
llamacpp server REST API | How to interrupt and stop an llm generate request.

### ISSUE THREAD

**Issue by fastdaima** [ggerganov/llama.cpp#7418]
How can we  stop an llm generate request, because sometimes we need to  stop an generation and resend another request. Instead of waiting for 1st request to finish.

**Comment by shibe2** [comment]
This was asked multiple times in discussions: #3513, #3700, #4721, #6489.

**Comment by fastdaima** [comment]
thanks @shibe2 , As it was mentioned in the issues, we cannot stop / interrupt prompt generation once started.
