### ISSUE TITLE
Pythia Support?

### ISSUE THREAD

**Issue by lodorg** [ggerganov/llama.cpp#742]
Hi, I've found out that Pythia (from EleutherAI) is better that Cerebras GPT in terms of evaluation results. Pythia is basically a LLM that based on GPT NeoX architecture but it's parameters ranging from 70M, 160M, 410M, 1B, 1.4B, 2.8B, 6.9B to 13B. Pythia itself is available in GitHub repository "EleutherAI/pythia" and Huggingface Models under the same name.

Does this project support Pythia based models? If no, any plans on supporting them afterwards? I appreciate the implementation of Pythia in this project. Thank you very much before.

**Comment by fakerybakery** [comment]
Hi, is there any update on thi @ggerganov?

**Comment by fakerybakery** [comment]
Can we please get this reopened @ggerganov
