### ISSUE TITLE
Generating the same token (token '1') over and over, after a few successful messages?

### ISSUE THREAD

**Issue by scottmudge** [ggerganov/llama.cpp#7421]
I'm using the current tip [917dc8c](https://github.com/ggerganov/llama.cpp/commit/917dc8cfa67a72fb7c8bf7392270da3bf4833af4) compiled on Debian 12.5, x86_64, using:

`LLAMA_FAST=1` and `LLAMA_CUDA=1` flags. 

My system has:

* Intel i7-8700k
* 2 x NVIDIA GTX 1080 Ti's (each on 8x PCI-E Gen 3),  each with 11GB VRAM, 22GB Total
* 32GB DDR4-3200

The models this issue seems to affect includes:

* Llama v3 8B (and multiple fine-tunes)
* Fimbulvetr V2
* Various Mixtral 8x7b MoE
* Probably more

I'm using the `server` binary launched with the following parameters:

```
./server -m ${gguf_path} -ngl 33 -c 8192 -fa -b 1024 -ub 512 -t 6 --log-format text --host 0.0.0.0 --port 5001 --chat-template vicuna
```

I am using SillyTavern (latest tip of `master` branch) on a separate machine as the frontend. The issue can be reproduced using any generation parameter presets, and any formatting/instruct presets.

### Issue:

After generating a few (maybe 3-6) successful back-and-forth messages, llama.cpp server will suddenly start repeating the same token over and over again. This is generally token 1. In the case of my current model, this is `<s>`:

```
... process_token] next token | tid="140619540189184" timestamp=1716236824 id_slot=0 id_task=315 token=1 token_text="<s>" has_next_token=true n_remain=962 n_decoded=55 stopped_eos=false stopped_word=false stopped_limit=false stopping_word=""
```

It does this until it reaches the maximum allowable tokens generated. The resulting message is blank, as it contains no printable tokens.

If I restart llama.cpp server, and attempt to regenerate the message it was failing to generate, it will generate fine. But very quickly (usually after the first successful message, but sometimes it can generate 2 or 3 successful messages), the issue will start up again.

Has anyone encountered this? Not sure the best way of debugging this issue further. No error messages appear to be emitted with the `-v` flag.

**Comment by m18coppola** [comment]
@scottmudge Try removing the `-fa` flag to disable Flash Attention. I haven't quite confirmed it yet, but I suspect it may be causing issues in a number of places.

**Comment by scottmudge** [comment]
> @scottmudge Try removing the `-fa` flag to disable Flash Attention. I haven't quite confirmed it yet, but I suspect it may be causing issues in a number of places.

Yeah that seemed to fix it, probably should have turned it off while testing. Must have missed it.

Not sure if it has to do with the FP32 kernels that were recently added (which are used with my setup), but for now I'll leave it off. A shame, since it's a lot faster with FA turned on, so hopefully the issue gets narrowed down.

**Comment by JohannesGaessler** [comment]
I believe to have found the issue: https://github.com/ggerganov/llama.cpp/pull/7465 . Please confirm whether the fix works.

**Comment by scottmudge** [comment]
@JohannesGaessler Looks like it's fixed, thanks for finding that!
