### ISSUE TITLE
Please don't hoard memory.

### ISSUE THREAD

**Issue by Zibri** [ggerganov/llama.cpp#7428]
Convert.py uses a lot of memory to convert to auto or few or bf16. Please correct it. Some small machine VM or personal have only 16gb of memory. It worked with a few models but it does not with meta llama in instruct. It always goes out of memory.

**Comment by Galunid** [comment]
Use `convert-hf-to-gguf.py` for huggingface models. `convert.py` is only for `llama/llama2/mistral` and only if using `.pth` files.
