### ISSUE TITLE
Performance Regression Observed in llama.cpp

### ISSUE THREAD

**Issue by amd-lalithnc** [ggerganov/llama.cpp#7443]
We have observed a performance regression in llama.cpp when using FP32 kernels. The regression is significant, and we would like to investigate the cause and propose possible solutions. 

While benchmarking llama.cpp on AMD EPYC servers, we noticed a severe performance drop with the build resulting from 9f773486ab78d65f5cca3f7e31c862b7043bf721. This commit has support for BF16, whereas the prior commit, 4fbd8098e63670c6ae11a8adc350f5ba191cfda3, that we tested with did not have support for BF16. 

### Background:
When MKL Verbose logs are printed, we see that llama.cpp uses FP32 kernels for all models of various precision. Looks like usage of INT8 kernels may give a huge boost to the performance. But the observed performance regression suggests that there may be underlying issues that need to be addressed.

### Steps to Reproduce

Running   ./llama-bench -m ./llama-2-7b-q8_0.gguf -t 96 -p 512 -b 512 -n 60 to get numbers. We see 30% throughput degradation on average across llama-variants, qwen and phi, with the latest build, 9f773486ab78d65f5cca3f7e31c862b7043bf721 when compared to 4fbd8098e63670c6ae11a8adc350f5ba191cfda3

### Questions
- Integrate BF16 kernels: Integrate BF16/INT8 kernels from DNN libraries to reduce memory usage and improve performance.
- Support for INT8 kernels: How are the weights converted to FP32 from INT8? Is it a separate memory pass, if yes, why isn't the overhead coming on the performance (when compared to a PyTorch based setup)? Or with INT8 kernels, would it be possible to see higher performance?
- Memory-intensive cast operator: Do we use a cast operator for dequantization? The cast operator for dequantizing INT8 weights to FP32 is memory-intensive and can bottleneck the performance.
- Separate memory pass for weights: The weights are passed as a separate memory pass, which can increase the memory access pattern and potentially impact performance.

**Comment by slaren** [comment]
We would need to know the commit that introduced the issue. This should be relatively quick and easy to find with `git bisect`. e1b40ac3b94824d761b5e26ea1bc5692706029d9 may be a likely candidate.

**Comment by cpumaxx** [comment]
I am also seeing a large performance regression on L2 70B at Q5, which is a very common model.
I ran git bisect and found the following results:

>325756d28df7d018a7bac424e1b3bc8acb4ecf07 is the first bad commit
commit 325756d28df7d018a7bac424e1b3bc8acb4ecf07
Author: Georgi Gerganov <ggerganov@gmail.com>
Date:   Sat May 11 16:25:50 2024 +0300
    ggml : resolve merge (ggml/0)
    ggml-ci
 ggml.c | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

Here is the log showing the slowdown (down to 4.52t/s currently vs 6.73t/s on fed01084):

| model                          |       size |     params | backend    |    threads |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ------------: | ---------------: |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         pp512 |     17.57 ± 0.04 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         tg128 |      4.52 ± 0.04 |
build: 325756d2 (2856)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 | pp 512     |     17.51 ± 0.14 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 | tg 128     |      5.77 ± 0.03 |
build: f98eb31c (2823)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 | pp 512     |     17.04 ± 0.92 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 | tg 128     |      5.35 ± 0.16 |
build: 4e388097 (2839)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         pp512 |     17.87 ± 0.34 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         tg128 |      6.34 ± 0.01 |
build: f99e1e45 (2847)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         pp512 |     18.26 ± 0.06 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         tg128 |      6.47 ± 0.02 |
build: f5ef34e4 (2851)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         pp512 |     18.37 ± 0.05 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         tg128 |      6.76 ± 0.02 |
build: 5a419926 (2853)
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         pp512 |     18.33 ± 0.12 |
| llama 70B Q5_K - Medium        |  45.40 GiB |    68.98 B | CPU        |         64 |         tg128 |      6.73 ± 0.01 |
build: fed01084 (2855)

Its a pretty severe slowdown, so I hope this helps track it down. 
I'm only sporadically available over the next week, but please let me know if there is any testing I can do and I'll do it as soon as I'm able.

**Comment by slaren** [comment]
I really don't see how https://github.com/ggerganov/llama.cpp/commit/325756d28df7d018a7bac424e1b3bc8acb4ecf07 could have caused this. Can you double check that it is this commit, and it wasn't a fluke? Additionally, make sure that you run `make clean` before every test. You can use much faster settings with `llama-bench`, for example if you know that the issue is only in tg, you can run `llama-bench -n 64 -r 2 -p 0`.
