### ISSUE TITLE
FR: Phi-3-vision-128k-instruct implementation

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#7444]
That model is insane for its size ....

https://huggingface.co/microsoft/Phi-3-vision-128k-instruct

**Comment by simsi-andy** [comment]
Is it natively supported once someone converts it to gguf?

**Comment by 4onen** [comment]
> Is it natively supported once someone converts it to gguf?

Someone has to write the code to run such a model into llama.cpp. Then it would be a model you could convert to gguf. Until then, no.

**Comment by mirek190** [comment]
I'm waiting who will do that patiently ...😭

**Comment by DenisSergeevitch** [comment]
The model is very good for its size for the OCR task, looking forward to use it in GGUF format

**Comment by HaoHoo** [comment]
Hi @ggerganov, the Phi-3 vision is similar to llava, combined with Phi-3 and CLIP-ViT-Large-patch14-336 models. Is possible to support converting it from HF to GGUF?

**Comment by anuran-roy** [comment]
Any update on the convert-hf-to-gguf issue on the Phi3-vision-small-128k model? Seems to be giving the same error as above:

`ERROR:hf-to-gguf:Model Phi3VForCausalLM is not supported`

**Comment by HaoHoo** [comment]
> Any update on the convert-hf-to-gguf issue on the Phi3-vision-small-128k model? Seems to be giving the same error as above:
> 
> `ERROR:hf-to-gguf:Model Phi3VForCausalLM is not supported`

You can copy "Phi3ForCausalLM" section and add as "Phi3VForCausalLM" in this python file. But Phi3-vision-128k-instruct includes Phi3 and Clip model. Phi3 can be detected and converted, but Clip model can't be converted via convert-hf-to-gguf.py code. It prompt the tensor mapping fail.

**Comment by anuran-roy** [comment]
> > Any update on the convert-hf-to-gguf issue on the Phi3-vision-small-128k model? Seems to be giving the same error as above:
> > `ERROR:hf-to-gguf:Model Phi3VForCausalLM is not supported`
> 
> You can copy "Phi3ForCausalLM" section and add as "Phi3VForCausalLM" in this python file. But Phi3-vision-128k-instruct includes Phi3 and Clip model. Phi3 can be detected and converted, but Clip model can't be converted via convert-hf-to-gguf.py code. It prompt the tensor mapping fail.

I did exactly that, as mentioned in the messages above in this issue. And got the exact same problem. Any sort of workarounds for this - if we can somehow decouple them or something?

**Comment by farris** [comment]
You can use `examples/llava/llava-surgery-v2.py` to separate out clip. I was able to modify it to do so successfully. I'm a bit stuck on the rest... the easiest way to do this imo is to modify the code under LLAVA/ to accept the phi3 base model and this hacked off clip encoder

**Comment by farris** [comment]
https://github.com/ggerganov/llama.cpp/pull/7705 👁️

**Comment by BrainSlugs83** [comment]
Would it be possible to use a parameter in the GGUF header to tell it that the file contains two sets of tensor data?

I feel like for the typical user they will expect to use a single GGUF file.

**Comment by Aisuko** [comment]
bad bot

**Comment by muzhig** [comment]
sad but true

**Comment by coder543** [comment]
New release of Phi-3.5-vision-instruct today: https://huggingface.co/microsoft/Phi-3.5-vision-instruct

(As well as a [16x3.8B MoE](https://huggingface.co/microsoft/Phi-3.5-MoE-instruct) and an updated version of the basic [Phi-3.5-mini](https://huggingface.co/microsoft/Phi-3.5-mini-instruct))

**Comment by stygmate** [comment]
+1 for support

**Comment by Milor123** [comment]
@coder543  And it can be converted to GGUF?

**Comment by coder543** [comment]
@Milor123 Nope… that’s why this issue exists.

**Comment by simsi-andy** [comment]
Abetlen already did convertt it and tries to create an experimental branch: https://huggingface.co/abetlen/Phi-3.5-vision-instruct-gguf

**Comment by daboe01** [comment]
https://github.com/ggerganov/llama.cpp/pull/9209/

**Comment by shadowmmu** [comment]
Hi all, I am able to implement this model in llama.cpp and run it smoothly, anybody wants to try please interact here : 
https://github.com/ggml-org/llama.cpp/discussions/17311
