### ISSUE TITLE
tokenization: double EOS tokens

### ISSUE THREAD

**Issue by Azirine** [ggerganov/llama.cpp#7484]
The llama.cpp tokenizer currently adds an EOS token unconditionally. However, adding an EOS token to the end of the system prompt is necessary to prevent generation before user input. This approach leads to two EOS tokens before the user prompt, potentially causing suboptimal performance.

llama.cpp-b2972, MacOS 14.5

./main -m Meta-Llama-3-8B-Instruct-Q8_0.gguf --temp 0 -i -e -p "<|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|>" -r "<|eot_id|>" --in-prefix "<|start_header_id|>user<|end_header_id|>\n\n" --in-suffix "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

Current behavior:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful assistant.<|eot_id|>
<|eot_id|>
<|start_header_id|>user<|end_header_id|>
```
Expected behavior:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful assistant.<|eot_id|>
<|start_header_id|>user<|end_header_id|>
```

**Comment by arch-btw** [comment]
I can't reproduce the first prompt. Which version of llama.cpp are you using?

**Comment by arch-btw** [comment]
Also -ins is not used for llama3, it's designed to work with Alpaca model

**Comment by Azirine** [comment]
> I can't reproduce the first prompt. Which version of llama.cpp are you using?

b2972

**Comment by Azirine** [comment]
#7107 raises a similar issue with double BOS tokens. The difference is that while the BOS token can be removed from the system prompt with no negative consequences, the EOS token cannot be removed from the system prompt because without it, generation starts before the user prompt.

**Comment by Azirine** [comment]
> I can't reproduce the first prompt. Which version of llama.cpp are you using?

What output do you get with my exact settings?
