### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ggerganov/llama.cpp#7489]
Would you like to add more error handling for return values from functions like the following?
* [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [print_grammar_char](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/common/grammar-parser.cpp#L313-L320)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [ggml_backend_buffer_init](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-backend.c#L60-L76)
* [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [ggml_vk_available_devices_internal](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-kompute.cpp#L239-L254)

**Comment by HanClinto** [comment]
> Would you like to add more error handling for return values from functions like the following?

This feels like it might generally be a good idea, but I'm not super aware of the performance costs.

> * [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [print_grammar_char](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/common/grammar-parser.cpp#L313-L320)

Not sure that this one would be useful -- currently when we fail a [GGML_ASSERT](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml.h#L257-L265) we output to `fprintf` anyways. If that fails, I'm not sure what else we can do than just `abort()`.

> * [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [ggml_backend_buffer_init](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-backend.c#L60-L76)

This one feels more useful. Poking through the code, it seems that we intermittently do check the return value with a GGML_ASSERT. For instance, [ggml-backend.c:238](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-backend.c#L238-L239) (referenced from [ggml_backend_tensor_copy()](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-backend.c#L329-L330)). Seems like appending most of these `malloc` calls with a quick sanity check to `GGML_ASSERT()` would be a good idea, and perhaps reduce the confusion of [segmentation faults that crop up from time to time](https://github.com/ggerganov/llama.cpp/issues?q=is%3Aissue+segmentation+fault+).

> * [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [ggml_vk_available_devices_internal](https://github.com/ggerganov/llama.cpp/blob/9b82476ee9e73065a759f8bcc4cf27ec7ab2ed8c/ggml-kompute.cpp#L239-L254)

Even though the risk of this one failing is much smaller, I'd still generally put this one in the same bucket as `malloc`. Not a bad idea to check with a quick call to `GGML_ASSERT`.

Nice finds! Out of curiosity, are you using static code analysis to locate these unchecked-return-values, or was this found by going through the code by hand?

**Comment by elfring** [comment]
>…, are you using static code analysis to locate these unchecked-return-values,

Occasionally, yes.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:


>or was this found by going through the code by hand?

Some functions are known where return values can be overlooked.
:eyes: Thus questionable places can be found also [by the means of GitHub source code search interfaces](https://docs.github.com/en/search-github/github-code-search/using-github-code-search "Documentation").

**Comment by HanClinto** [comment]
> How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software? 🤔

Generally I'm in favor of it! We already have some linting (which I think is a form of static analysis) in the build process -- I think that it would be generally good to expand such things so long as the coding standards it introduces aren't overly obnoxious to comply with.

So I think one could take the approach of either the first or both -- patching the current `malloc` calls whose return values aren't being checked and possibly updating the CI tools to do more static code analysis.

The first is necessary before the second would be able to be merged (because we can't merge failing CI), but this seems like it would be a good exercise, and would even be a nice first issue for someone to tackle.

**Comment by elfring** [comment]
>… patching the current `malloc` calls …

:crystal_ball: Will the chances grow to extend the application of C++ functionality (like `new` expressions or smart pointers)?

**Comment by ngxson** [comment]
IMO having checks for these small malloc does not provide any real benefits (and even worst, make the code less readable)

The reason is because
- These variable are too small, magnitude of bytes, so the chance they fail is no more than winning lottery
- For the `fprintf`, if it fails, that mean something horribly happens outside of llama.cpp. It's not our responsibility to care about that.

Overall, I'm not oppose to idea to improve the stability. It's just that we need to draw a line between "error can happen in daily basis" and "error never happens in real life".

> How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software? 🤔

It maybe useful for other software, but not llama.cpp or ggml.

Static code analysis never understand difference between unsafe code "by accident" or "intentionally"

Look at ggml.c and you will see why:

```cpp
// disable "possible loss of data" to avoid hundreds of casts
// we should just be careful :)
#pragma warning(disable: 4244 4267)
```

**Comment by norgera** [comment]
thanks, i am looking into implementing checks for these scenarios

"Seems like appending most of these malloc calls with a quick sanity check to GGML_ASSERT() would be a good idea, and perhaps reduce the confusion of [segmentation faults that crop up from time to time](https://github.com/ggerganov/llama.cpp/issues?q=is%3Aissue+segmentation+fault+)." 

would this be a good idea? or is there other good first issues that you think i could tackle that are more useful.

**Comment by ngxson** [comment]
> Seems like appending most of these malloc calls with a quick sanity check to GGML_ASSERT() would be a good idea

IMO it will just make the code absurdly unreadable to have `GGML_ASSERT` everywhere.

`GGML_ASSERT` tend to be used in some situations:
- Code paths that we intentionally don't support (example: `ggml_cast` from/to Q-quant)
- Errors that may happen on daily basis (example: `malloc` a large chunk of memory for loading tensor data)

For other types of error, it's still better to return values indicating error (example, `return NULL`)

**Comment by elfring** [comment]
>…, it's better not to care about it.

:thought_balloon: Some software users tend to [prefer defined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Advice “Do not dereference null pointers”").
