### ISSUE TITLE
我在Android上跑，cpu，非常的慢，跑一张图片需要花费5分钟，请问这个怎么优化？

### ISSUE THREAD

**Issue by wangmiaojun** [ggerganov/llama.cpp#7494]
我在adb shell中执行的：
/data/local/tmp/minicpmv-cli -m /data/local/tmp/ggml-model-Q4_K_M.gguf --mmproj /data/local/tmp/mmproj-model-f16.gguf -t 4 --image /data/local/tmp/demo.jpg -p "What is in this picture?"

![20240523-202823](https://github.com/ggerganov/llama.cpp/assets/31395600/cac533e9-412f-4156-a3d8-98eeabd993f0)

**Comment by airMeng** [comment]
seems the issue is the loading costs too long, might not be llama.cpp issues. ```minicpmv``` seems not a llama.cpp target, could you provide more details like which downstream project you are using?

Chinese as the following:
> 看上去是模型加载时间太长了，可能不是llama.cpp的问题。似乎minicpmv不是llama.cpp的一部分，你能分享更多的细节么
