### ISSUE TITLE
Trying to understand token sampling better

### ISSUE THREAD

**Issue by coder543** [ggerganov/llama.cpp#7498]
You can see that it sampled a token that had a 1% probability instead of sampling the token that had a 96% probability:

![image](https://github.com/ggerganov/llama.cpp/assets/726063/5447a3c9-a8b6-483c-9fb3-392b18894a2a)

Settings:

![image](https://github.com/ggerganov/llama.cpp/assets/726063/aa799f1b-2364-4ac8-8653-c44f4e1c2c5b)

I understand there is randomness in the sampling process, but I thought the Min-P sampling of 0.05 would have eliminated a 1% token to begin with? It also just seems like a very _improbable_ choice of token to sample given the options.

Similar things happened elsewhere, for example:

![image](https://github.com/ggerganov/llama.cpp/assets/726063/40ead6fe-9b2f-4e3c-83d4-7f3b6fa0f8a3)

This probably isn't a bug, I'm just trying to understand what causes sampling decisions like these.

EDIT: I don't think it matters, but this example is using `Meta-Llama-3-8B-Instruct.Q8_0.gguf`.

**Comment by moo-v** [comment]
That's because temperature is applied after Min-P, so you're not seeing the same values Min-P filtered.

**Comment by arnfaldur** [comment]
You should move this to the discussion section. It's not an issue with this project. This is a support request.
