### ISSUE TITLE
Support Official llama.cpp docker/images.

### ISSUE THREAD

**Issue by DirtyKnightForVi** [ggerganov/llama.cpp#7506]
Is there an official version of llama.cpp available in Docker now? I need to deploy it in a completely offline environment, and non-containerized deployment makes the installation of many compilation environments quite troublesome.

Plz

**Comment by ngxson** [comment]
We don't deploy it to Docker Hub, but we do have Github Registry: https://github.com/ggerganov/llama.cpp/pkgs/container/llama.cpp

**Comment by DirtyKnightForVi** [comment]
Thank you very much. However, I would like to enter the container and recompile another branch of the project. According to the current manual and practice, it seems not supported, as I have observed that the container fails to start consistently. Have I missed something?
```
(base) jiyin@jiyin:/media/jiyin/ResearchSpace$ sudo docker run -v /media/jiyin/ResearchSpace:/models 92ddd0cc4ed1 bash
Unknown command: bash
Available commands: 
  --run (-r): Run a model previously converted into ggml
              ex: -m /models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512
  --convert (-c): Convert a llama model into ggml
              ex: --outtype f16 "/models/7B/" 
  --quantize (-q): Optimize with quantization process ggml
              ex: "/models/7B/ggml-model-f16.bin" "/models/7B/ggml-model-q4_0.bin" 2
  --finetune (-f): Run finetune command to create a lora finetune of the model
              See documentation for finetune for command-line parameters
  --all-in-one (-a): Execute --convert & --quantize
              ex: "/models/" 7B
  --server (-s): Run a model on the server
              ex: -m /models/7B/ggml-model-q4_0.bin -c 2048 -ngl 43 -mg 1 --port 8080
```

**Comment by Galunid** [comment]
you can try adding `--entrypoint /bin/bash` instead of `bash`

**Comment by DirtyKnightForVi** [comment]
What I actually want to do is to try the changes under this [branch](https://github.com/ggerganov/llama.cpp/issues/7118)， which haven't been merged into the main branch yet. Deploying the project on a completely offline machine is indeed too troublesome.

**Comment by Galunid** [comment]
Then you need to build the image yourself, before you deploy it. See `README.md` for more information

**Comment by DirtyKnightForVi** [comment]
> We don't deploy it to Docker Hub, but we do have Github Registry: https://github.com/ggerganov/llama.cpp/pkgs/container/llama.cpp

May I follow up with a question: Do the latest images on this list all include the content from the main branch? Does each suffix correspond to a specific version of the source code?

**Comment by ngxson** [comment]
@DirtyKnightForVi The image tag corresponds to:
- Which Dockerfile in https://github.com/ggerganov/llama.cpp/tree/master/.devops
- And, which commit hash is used to build the image

For example, `docker pull ghcr.io/ggerganov/llama.cpp:full-cuda--b1-2b33896` is built from [full.Dockerfile](https://github.com/ggerganov/llama.cpp/blob/master/.devops/full.Dockerfile) and commit https://github.com/ggerganov/llama.cpp/commit/2b3389677a833cee0880226533a1768b1a9508d2

**Comment by DirtyKnightForVi** [comment]
> 2b33896

Please allow me to further explain:

How is the version number in Releases associated with the TAG of the Docker image?

For example, does b3091 correspond to 2b33896 in your previous example?

**Comment by DirtyKnightForVi** [comment]
> @DirtyKnightForVi The image tag corresponds to:
> 
> * Which Dockerfile in https://github.com/ggerganov/llama.cpp/tree/master/.devops
> * And, which commit hash is used to build the image
> 
> For example, `docker pull ghcr.io/ggerganov/llama.cpp:full-cuda--b1-2b33896` is built from [full-cuda.Dockerfile](https://github.com/ggerganov/llama.cpp/blob/master/.devops/full-cuda.Dockerfile) and commit [2b33896](https://github.com/ggerganov/llama.cpp/commit/2b3389677a833cee0880226533a1768b1a9508d2)

Thank you very much for your patient response.

**Comment by DirtyKnightForVi** [comment]
Although I successfully ran the model using the CUDA image, it seems that the model was loaded onto the GPU but inference is being performed on the CPU. Did I miss something?

`docker run --gpus all -v /path/llama_test:/models ghcr.io/ggerganov/llama.cpp:full-cuda--b1-5442939 -m /models/xx.gguf -p "hello" --n-gpu-layers 18`
