### ISSUE TITLE
CI Docker Build Issue (intel public key needs updating?)

### ISSUE THREAD

**Issue by mofosyne** [ggerganov/llama.cpp#7507]
Regarding the docker build issue in master branch it appears that https://repositories.intel.com/gpu/ubuntu is down with an access denied message

```
#7 4.701 Reading package lists...
#7 5.410 W: GPG error: https://repositories.intel.com/gpu/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 28DA432DAAC8BAEA
#7 5.410 E: The repository 'https://repositories.intel.com/gpu/ubuntu jammy InRelease' is not signed.
#7 ERROR: process "/bin/sh -c apt-get update &&     apt-get install -y git" did not complete successfully: exit code: 100
```

This causes this error

```
5.410 W: GPG error: https://repositories.intel.com/gpu/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 28DA432DAAC8BAEA
5.410 E: The repository 'https://repositories.intel.com/gpu/ubuntu jammy InRelease' is not signed.
------
main-intel.Dockerfile:6
--------------------
   5 |     ARG LLAMA_SYCL_F16=OFF
   6 | >>> RUN apt-get update && \
   7 | >>>     apt-get install -y git
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y git" did not complete successfully: exit code: 100
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y git" did not complete successfully: exit code: 100
```

----

If i understand to access this,  you need to have the latest public key which intel says in https://dgpu-docs.intel.com/driver/installation.html#repository-public-key-used-for-package-and-repository-signing to be:

```
wget -qO - https://repositories.intel.com/gpu/intel-graphics.key |
     sudo gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
```

So the question is if the public key we are using is more current?

**Comment by mofosyne** [comment]
Hmmm... .devops/main-intel.Dockerfile doesn't actually store any reference to a pubkey, instead it points to a specific docker image from `intel/oneapi-basekit`. Did intel make a build obsolete?

```
ARG ONEAPI_VERSION=2024.0.1-devel-ubuntu22.04

FROM intel/oneapi-basekit:$ONEAPI_VERSION as build
```

**Comment by ggerganov** [comment]
Thanks for having a look - I'm not familiar with the Docker builds, so no idea how to fix this. Let's give it a day or two to see if someone finds a solution before disabling the CI

**Comment by mofosyne** [comment]
Not a problem. This PR is now ready and CI passing, when ready to disable the CI for this. Hopefully someone figures out what's up with the CI

https://github.com/ggerganov/llama.cpp/pull/7515

**Comment by mofosyne** [comment]
As @ngxson pointed out. This is an upstream issue on intel side.

Also according to Xavier_V in intel community forum, he was also experiencing a similar issue on 05-21-2024, which is a few days ago. So this doesn't appear to be an isolated incident.

Source: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/APT-Repository-not-working-signatures-invalid/m-p/1599436

----

Keeping this ticket open, so we can revisit reactivating these disabled tests a week later or so.

**Comment by visitsb** [comment]
Temporary fix `NO_PUBKEY 28DA432DAAC8BAEA` 
by patching `.devops/main-intel.Dockerfile` (optionally `.devops/server-intel.Dockerfile`)
```yaml
RUN curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor --yes --output /usr/share/keyrings/intel-graphics-archive-keyring.gpg && \
    apt-get update
```

As @mofosyne correctly points out, the upstream [intel/oneapi-basekit](https://github.com/intel/oneapi-containers) docker image **simply needs to get rebuilt** and pushed ([last updated 2 months ago](https://hub.docker.com/r/intel/oneapi-basekit/tags)) to have latest PUB keys for [Intel GPU Drivers](https://dgpu-docs.intel.com/driver/installation.html#repository-public-key-used-for-package-and-repository-signing).

@mofosyne, @ggerganov 
> Hmmm... .devops/main-intel.Dockerfile doesn't actually store any reference to a pubkey, instead it points to a specific docker image from `intel/oneapi-basekit`. Did intel make a build obsolete?
> 
> ```dockerfile
> ARG ONEAPI_VERSION=2024.0.1-devel-ubuntu22.04
> 
> FROM intel/oneapi-basekit:$ONEAPI_VERSION as build
> 
> ARG LLAMA_SYCL_F16=OFF
> RUN apt-get update && \
>     apt-get install -y git
> 
> WORKDIR /app
> 
> COPY . .
> 
> RUN if [ "${LLAMA_SYCL_F16}" = "ON" ]; then \
>         echo "LLAMA_SYCL_F16 is set" && \
>         export OPT_SYCL_F16="-DLLAMA_SYCL_F16=ON"; \
>     fi && \
>     cmake -B build -DLLAMA_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx ${OPT_SYCL_F16} && \
>     cmake --build build --config Release --target main
> 
> FROM intel/oneapi-basekit:$ONEAPI_VERSION as runtime
> 
> COPY --from=build /app/build/bin/main /main
> 
> ENV LC_ALL=C.utf8
> 
> ENTRYPOINT [ "/main" ]
> ```
> 
> https://hub.docker.com/r/intel/oneapi-basekit

**Comment by mofosyne** [comment]
Prefer to wait unless we got someone who will be affected.

**Comment by mofosyne** [comment]
@leshikus you using this feature? If so then how critical is this to your workflow? At the moment it doesn't appear that intel has solve the issue on their end. And rather not add a workaround if we would have to remove it when its fixed again.

**Comment by simonlui** [comment]
Sorry, I should've spoke up here since I did digging on this front for my docker image for image generation.
They renamed their apt repository once more per https://github.com/intel-analytics/ipex-llm/commit/e0f401d97d14734de22467a24d5a6fd38f622eec. The URL is now https://repositories.intel.com/graphics/ubuntu, not https://repositories.intel.com/gpu/ubuntu

**Comment by mofosyne** [comment]
@simonlui ah... does that mean they are not likely to bother fixing their docker image then? If you got the workaround already maybe we should place in a hack for now.

**Comment by simonlui** [comment]
> does that mean they are not likely to bother fixing their docker image then?
Yeah, they're also using an outdated Compute Runtime in that image and it has a bug where your GPU isn't recognized to do SYCL on newer Linux kernels which I was affected by hence why I had to dig to find that. Seems like there isn't enough coordination to fix things across different Intel software teams globally for stuff like this hence the patchwork fix I linked.

**Comment by airMeng** [comment]
@simonlui sorry for inconvenience, I have contacted OneAPI container team for help.

@mofosyne Could you tag me next time for probably Intel issues? Then I will try to cycle back ASAP.

**Comment by K20shores** [comment]
@mofosyne [this solution](community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Cannot-update-any-packages-using-intel-oneapi-hpckit-latest/m-p/1603192#M36169) worked for my project, just fyi

**Comment by mofosyne** [comment]
@K20shores greatly appreciate the heads up. @airMeng merged in a similar fix.

I think it's still worth badgering the Intel team, but at least everything seems on the roll now... so should probably close this ticket now so thanks for the reminder.

**Comment by airMeng** [comment]
@mofosyne synced with container team, the formal solution will be updated after oneAPI 2024.2 released

**Comment by mofosyne** [comment]
Heads up that https://github.com/intel/oneapi-containers/issues/70#issuecomment-2161152123 mdreyesm said that an updated image has been uploaded with the update apt key if you want to send a new PR to reverse the workaround.
