### ISSUE TITLE
Feature - writing conversation to a txt file. 

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#7545]
Could possible to add possibility to write conversation to a txt file for main ? 
Or maybe such feature is already build-in ?  But I can't find it.

**Comment by BarfingLemurs** [comment]
I use `| tee mytext.txt`

**Comment by arch-btw** [comment]
I'd like to request this feature as well, it would be nice to just export the conversation and nothing else.
`tee` is possible but it unfortunately includes unwanted data/logs.

**Comment by teleprint-me** [comment]
Maybe I can add something in the future. Not enough time at the moment, but it would save me the hassel of having to build and maintain wrappers for this purpose alone. I already prototyped a quite a few iterations, so this is fairly trivial at this point. It would just take time to implement.

**Comment by mirek190** [comment]
> Maybe I can add something in the future. Not enough time at the moment, but it would save me the hassel of having to build and maintain wrappers for this purpose alone. I already prototyped quite a few iterations, so this is fairly trivial at this point. It would just take time to implement. Maybe could add it as an example.

Can't wait !
