### ISSUE TITLE
High perplexity from quantization

### ISSUE THREAD

**Issue by Azirine** [ggerganov/llama.cpp#7550]
Found an issue of unusually high perplexity from mradermacher's quantization, reported on [huggingface](https://huggingface.co/mradermacher/model_requests/discussions/70) where he suggested this is a llama.cpp upstream issue.

`./perplexity -m Silicon-Maid-7B.Q8_0.gguf -f wiki.test.raw`

| Quanted by | Quant date | PPL |
| ------------- | ------------- | ------------- |
| [TheBloke](https://huggingface.co/TheBloke/Silicon-Maid-7B-GGUF/blob/main/silicon-maid-7b.Q8_0.gguf) | 2023-12-27 | 6.9562 +/- 0.04647 |
| [mradermacher](https://huggingface.co/mradermacher/Silicon-Maid-7B-GGUF/blob/main/Silicon-Maid-7B.Q8_0.gguf) | 2024-04-26 | 15.3851 +/- 0.13562 |
| [RichardErkhov](https://huggingface.co/RichardErkhov/SanjiWatsuki_-_Silicon-Maid-7B-gguf/blob/main/Silicon-Maid-7B.Q8_0.gguf) | 2024-05-16 | 6.9562 +/- 0.04647 |

System: M3 Max, MacOS 14.5, llama.cpp-b3004

**Comment by mofosyne** [comment]
Btw what kind of ticket is this? Unsure what to label this

**Comment by Galunid** [comment]
```
$ python convert-hf-to-gguf.py models-local/Silicon-Main-7B
$ ./quantize models-local/Silicon-Main-7B/ggml-model-fp16.gguf
$ ./perplexity -m models-local/Silicon-Maid-7B/ggml-model-Q4_K_M.gguf -f wikitext-2-raw/wiki.test.raw -ngl 30 --temp 0
Final estimate: PPL = 7.0501 +/- 0.04722
```

Looks like someone failed to make the model correctly, or something was broken that's fixed now. Doesn't matter, it works now, so I'll close this.
