### ISSUE TITLE
Bug: When running on an Android phone, processing an image took 4-5 minutes, which is very slow. Are there any optimization methods? (我在Android 手机上运行，一张图像跑了4、5分钟，非常慢，有什么优化方法吗) #7579

### ISSUE THREAD

**Issue by wangmiaojun** [ggerganov/llama.cpp#7579]
### What happened?

我的操作步骤如下：
1、拉取了代码的feat-minicpmv 分支。
2、使用cmake进行了android 的构建（使用其中生成的适合android的minicpmv-cli ）:
        $ mkdir build-android
        $ cd build-android
        $ export NDK=<your_ndk_directory>
        $ cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a - 
         DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
        $ make
3、使用以下命令进行了gguf的模型生成，然后导出到手机的相关目录。
![image](https://github.com/ggerganov/llama.cpp/assets/31395600/589fa98c-b65d-42b6-87a0-e5a471589a2d)
4、然后将命令行中的变量换成自己的路径，在Android上进行执行
![image](https://github.com/ggerganov/llama.cpp/assets/31395600/4e14d6f0-cde2-4c67-a997-a2e6a8e2839b)
   具体执行过程：
    执行 adb root，然后adb shell ,最后执行： 
      /data/local/tmp/minicpmv-cli -m /data/local/tmp/ggml-model-Q4_K_M.gguf --mmproj /data/local/tmp/mmproj-model- 
     f16.gguf -t 4 --image /data/local/tmp/demo.jpg -p "What is in this picture?"
5、执行结果如下：非常慢！尤其在encode_image_with_clip，每次大概40到50秒。
     
![image](https://github.com/ggerganov/llama.cpp/assets/31395600/0b3d3f53-2b06-405f-88be-073d222de622)

   

### Name and Version

ubuntu22.04

**Comment by Adriankhl** [comment]
This is my general llava experience so far, it is already quite slow on PC cpu, and mobile cpu is even slower. I guess it is the nature of the model?

**Comment by lippman1125** [comment]
@Adriankhl Not really, MNN only use 2 secs to encode the image.

**Comment by lippman1125** [comment]
@max-krasnyansky @ggerganov  This issue deserves more attention, as multimodal AI is set to dominate the future landscape.

**Comment by max-krasnyansky** [comment]
Which Android phone are you running on? (I can't tell from the output or description).
In general, I'd suggest quantizing to Q4_0, IQ4_NL or MXFP4 if the accuracy is acceptable. 
Q4_0 is generally the most optimized data type across the backends.
