### ISSUE TITLE
Bug: The slots saving feature of example/server is not working.

### ISSUE THREAD

**Issue by Amadeus-AI** [ggerganov/llama.cpp#7584]
### What happened?

The slots saving feature of example/server is not working.
**POST /slots/{id_slot}?action=save**
```
{
    "error": {
        "code": 500,
        "message": "[json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON",
        "type": "server_error"
    }
}
```
while the erase feature is working.
**POST /slots/{id_slot}?action=erase**
```
{
    "id_slot": 1,
    "n_erased": 524
}
```

### Name and Version

./main --version
version: 3015 (74b239b3)
built with MSVC 19.39.33523.0 for x64

### What operating system are you seeing the problem on?

Win10

**Comment by Amadeus-AI** [comment]
@kaetemi

**Comment by jygmysoul** [comment]
This error is that the JSON parsing format is incorrect. It should be that the json you submitted in the json contains the '' symbol that the symbol is not conversion

**Comment by kaetemi** [comment]
What did you pass as request payload?

**Comment by Amadeus-AI** [comment]
> You need to pass a JSON body request with a filename that the cache will be saved to.

I see! thank you, it works.
