### ISSUE TITLE
Bug: [Server] Prompt caching causes subsequent identical requests to return different token probabilities

### ISSUE THREAD

**Issue by reuank** [ggerganov/llama.cpp#7594]
### What happened?

Hi there,

I noticed that prompt caching on the server causes subsequent identical requests to return different token probabilities, even though I use just one slot. When using greedy decoding (`temperature=-1.0`), I would expect the results to be exactly identical when using one server slot.

### Server parameters
```
./server -m ../local_models/orca-2-7b.Q4_K_M.gguf -c 4096 -ngl 1000 -np 1 -cb -v
```

### Request/Response 1
```
// Request 1
curl --request POST \
    --url http://localhost:8080/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Test", "id_slot": 0, "n_predict": 1, "n_probs": 1, "samplers": ["temperature"], "seed": 1234, "temperature": -1.0, "cache_prompt": true}'
```

```
// Response 1
{
    "content": "imon",
    "tokens_predicted": 1,
    "tokens_evaluated": 2,
    "prompt": "Test",
    "tokens_cached": 2,
    "timings":
    {
        "prompt_n": 2,
    },
    "completion_probabilities":
    [
        {
            "content": "imon",
            "probs":
            [
                {
                    "tok_str": "imon",
                    "prob": 0.5299757719039917
                }
            ]
        }
    ]
}
```

### Request/Response 2
```
// Request 2, identical to request 1
curl --request POST \
    --url http://localhost:8080/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Test", "id_slot": 0, "n_predict": 1, "n_probs": 1, "samplers": ["temperature"], "seed": 1234, "temperature": -1.0, "cache_prompt": true}'
```

```
// Response 2
{
    "content": "imon",
    "tokens_predicted": 1,
    "tokens_evaluated": 2,
    "prompt": "Test",
    "tokens_cached": 2,
    "timings":
    {
        "prompt_n": 1,
    },
    "completion_probabilities":
    [
        {
            "content": "imon",
            "probs":
            [
                {
                    "tok_str": "imon",
                    "prob": 0.5112787485122681
                }
            ]
        }
    ]
}
```

I don't know how this is implemented internally. Does the caching affect the batch size, which in turn affects rounding?

Best
Leon

### Name and Version

version: 3024 (2b737caa)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.5.0

### What operating system are you seeing the problem on?

Mac

**Comment by JohannesGaessler** [comment]
I think this issue is unfortunately fundamentally unfixable, see https://github.com/ggerganov/llama.cpp/pull/7745 .

**Comment by steampunque** [comment]
No, I think it is fixable.  See my example patch in #7745.

**Comment by steampunque** [comment]
This patch can be applied to server to fix this problem : https://github.com/steampunque/llama.cpp-patches/blob/main/server_prompt_cache.diff.  Apply with patch -p0 -l <server_prompt_cache.diff.
