### ISSUE TITLE
.pth to .ggml Out of Memory

### ISSUE THREAD

**Issue by cs-mt** [ggerganov/llama.cpp#76]
I have 16 GBs of memory (14 GB free) and running `python3 convert-pth-to-ggml.py models/7B/ 1` causes an OOM error (Killed) on Linux.

Here's the dmesg message:
`Out of memory: Killed process 930269 (python3) total-vm:15643332kB, anon-rss:13201980kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:26524kB oom_score_adj:0`

I will be receiving my new RAM in a few days but I think this is supposed to work with 16 GB memory?

**Comment by cs-mt** [comment]
Oh, never mind. Allocating extra swap space worked.

**Comment by kassane** [comment]
@cs-mt ,
I got the same error having 16GiB RAM. Probably 32GiB would be ideal.
