### ISSUE TITLE
Bug: Phi-3 Medium potential tokenization issues with $

### ISSUE THREAD

**Issue by bartowski1182** [ggerganov/llama.cpp#7600]
### What happened?

I was just trying to prompt Phi 3 and noticed strange tokenizing behaviour

Given the following prompt (From Matthew Berman):

./main -m /models/Phi-3-medium-128k-instruct-f32.gguf -p "<|system|> You are a Helpful Assistant<|end|><|user|> Maria is staying at a hotel that charges $99.95 per night plus tax for a room. A tax of 8% is applied to the room rate, and an additional onetime untaxed fee of $5.00 is charged by the hotel. Which of the following represents Maria's total charge, in dollars, for staying x nights? (99.95 + 0.08x) + 5, 1.08(99.95x) + 5, 1.08(99.95 + 5)x<|end|><|assistant|>" --special

The model outputs this:

=============
<|system|> You are a Helpful Assistant<|end|><|user|> Maria is staying at a hotel that charges 9.95 per night plus tax for a room. A tax of 8% is applied to the room rate, and an additional onetime untaxed fee of .00 is charged by the hotel. Which of the following represents Maria's total charge, in dollars, for staying x nights? (99.95 + 0.08x) + 5, 1.08(99.95x) + 5, 1.08(99.95 + 5)x<|end|><|assistant|> The hotel charges $9.95 per night, plus an 8% tax on the room rate. The tax on the room rate per night is:

Tax per night = Room rate * Tax rate
              = $9.95 * 0.08
              = $0.796
So, the total charge per night, including tax, is:

Total charge per night = Room rate + Tax per night
                       = $9.95 + $0.796
                       = $10.746
=============

In this prompt, it looks like all dollar signs got removed and so did the next character. The model also gets the answer wrong, likely because none of the options for answers make any sense if the room is only 9.95 per night..

If I remove the dollar signs, the numbers stay proper and it gives a correct answer:

=================
<|system|> You are a Helpful Assistant<|end|><|user|> Maria is staying at a hotel that charges 99.95 per night plus tax for a room. A tax of 8% is applied to the room rate, and an additional onetime untaxed fee of 5.00 is charged by the hotel. Which of the following represents Maria's total charge, in dollars, for staying x nights? (99.95 + 0.08x) + 5, 1.08(99.95x) + 5, 1.08(99.95 + 5)x<|end|><|assistant|> The correct representation of Maria's total charge for staying x nights is 1.08(99.95x) + 5.
=================

Result of ./tokenize on the first part of the prompt:

```
 32006 -> '<|system|>'
   887 -> ' You'
   526 -> ' are'
   263 -> ' a'
 22305 -> ' Help'
  1319 -> 'ful'
  4007 -> ' Ass'
 22137 -> 'istant'
 32007 -> '<|end|>'
 32010 -> '<|user|>'
  6217 -> ' Maria'
   338 -> ' is'
  7952 -> ' stay'
   292 -> 'ing'
   472 -> ' at'
   263 -> ' a'
 16730 -> ' hotel'
   393 -> ' that'
 21090 -> ' charges'
 29871 -> ' '
 29929 -> '9'
 29889 -> '.'
 29929 -> '9'
 29945 -> '5'
```

### Name and Version

version b3024

Ubuntu 22.04

### What operating system are you seeing the problem on?

Linux

**Comment by slaren** [comment]
I am not sure if I understand the problem because I don't see any dollars in your command line either, but the dollar is a special character for the shell and you need to escape it with `\$`. Eg. try running `echo "$9.95"` and `echo "\$9.95"`.

**Comment by bartowski1182** [comment]
my bad, forgot to put them back into the example, lemme try what you suggested

**Comment by bartowski1182** [comment]
Ah okay that did it, I feel silly now, \\$ properly escapes them and then they show up and the model also gets it right (so my CLI was hiding it) sorry about that!
