### ISSUE TITLE
Bug: Inconsistent ggml-4-x86-cuda-v100 ci failures on master

### ISSUE THREAD

**Issue by mofosyne** [ggerganov/llama.cpp#7613]
**Note: Only one datapoint of ci failure, but it would be important to keep track of this behavior over the next few commits**

### What happened?

* [Passing commit](https://github.com/ggml-org/ci/tree/results/llama.cpp/50/4f0c340f6b5e04de682f6ddefdd3b81208df5d/ggml-4-x86-cuda-v100)
    - https://github.com/ggerganov/llama.cpp/commit/504f0c340f6b5e04de682f6ddefdd3b81208df5d

* [Failing commit, but its a readme only change](https://github.com/ggml-org/ci/tree/results/llama.cpp/0e/8d8bfd6caf1d0a8cbdf9d3d5c06fbbb9dfced8/ggml-4-x86-cuda-v100)
   - https://github.com/ggerganov/llama.cpp/commit/0e8d8bfd6caf1d0a8cbdf9d3d5c06fbbb9dfced8

Noticed that it said it's failing in `20 - test-backend-ops`, it be good to identify the cause of this issue and potential ways to fix it. The failure in test *#20* in test-backend-ops looked like below which doesn't seem to explain much to me. But hopefully it makes sense to someone else here.

`[CPY] NMSE = 0.000003149 > 0.000000100` looks interesting however 

### Name and Version

between commit 504f0c340f6b5e04de682f6ddefdd3b81208df5d and 0e8d8bfd6caf1d0a8cbdf9d3d5c06fbbb9dfced8

### What operating system are you seeing the problem on?

Other? (Please let us know in description)

### Relevant log output

```shell
[1;32mOK[0m
  CPY(type_src=f32,type_dst=q4_1,ne=[256,4,4,4]): ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
[CPY] NMSE = 0.000003149 > 0.000000100 ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
[1;31mFAIL[0m
  CPY(type_src=f32,type_dst=q5_0,ne=[256,4,4,4]): ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
[1;32mOK[0m
```

**Comment by ggerganov** [comment]
See this comment for explanation: https://github.com/ggerganov/llama.cpp/pull/7425#issuecomment-2124150456

**Comment by mofosyne** [comment]
Is there a way to fix this or reasonably suppress, change the rounding approach, increase threshold or adapt to this error (e.g. only trigger an error if two or more trips in a test?)
