### ISSUE TITLE
Can i quantize a 4Bit model more?

### ISSUE THREAD

**Issue by Shreyas-ITB** [ggerganov/llama.cpp#762]
Hi i want to quantize a model which is already quantized to 4bit ``q4_1`` but i want to make it compute faster so i wanted to ask what is the command to quantize the quantized module. I tried once with the command that is in the readme file but that didnt work. so can anyone help me?

**Comment by howard0su** [comment]
what command did you run? I think you can convert ggml to pth, then pth to ggml with q4_0.

**Comment by prusnak** [comment]
The comment above explains the situation. One node: if there is a 2-bit or 3-bit quantization available, it should be always performed from the original f16 or f32 file.
