### ISSUE TITLE
Feature Request: codestral support

### ISSUE THREAD

**Issue by bachittle** [ggerganov/llama.cpp#7622]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

codestral support

### Motivation

https://mistral.ai/news/codestral/

**Comment by mirek190** [comment]
Is not working right now ?

**Comment by arch-btw** [comment]
Someone converted here, there's a script in the same repo too: https://huggingface.co/bullerwins/Codestral-22B-v0.1-hf/tree/main

**Comment by tbocek** [comment]
Just tested it, seems to work fine with my initial testing with codestral-22B-v0.1-IQ4_XS.gguf (https://huggingface.co/bartowski/Codestral-22B-v0.1-GGUF/tree/main), running latest master.
