### ISSUE TITLE
Question: How to convert Yi-34B-Chat-4bits to gguf?

### ISSUE THREAD

**Issue by goodmaney** [ggerganov/llama.cpp#7623]
### Prerequisites

- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new useful question to share that cannot be answered within Discussions.

### Background Description

The script convert-hf-to-gguf.py can convert  Yi-34B-Chat,but can't convert the 4bits. My GPU only can SFT the 4bits modle,so I want to convert it to gguf. That report some error,the 4bits quantized  used AQW

xx@LLM:~/llama.cpp$ python convert-hf-to-gguf.py ~/.cache/modelscope/hub/Yi-34B-Chat-4bits/ --outfile ~/modles/Yi-34B-4bits.gguf
--------------------------------------------------------------------
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Setting special token type bos to 1
INFO:gguf.vocab:Setting special token type eos to 2
INFO:gguf.vocab:Setting add_bos_token to False
INFO:gguf.vocab:Setting add_eos_token to False
INFO:gguf.vocab:Setting chat_template to {% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}
INFO:hf-to-gguf:Exporting model to '/home/xx/modles/Yi-34B-4bits.gguf'
INFO:hf-to-gguf:gguf: loading model weight map from 'model.safetensors.index.json'
INFO:hf-to-gguf:gguf: loading model part 'model-00001-of-00002.safetensors'
INFO:hf-to-gguf:token_embd.weight,           torch.float16 --> F16, shape = {7168, 64000}
INFO:hf-to-gguf:blk.0.attn_norm.weight,      torch.float16 --> F32, shape = {7168}
Traceback (most recent call last):
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 2562, in <module>
    main()
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 2556, in main
    model_instance.write()
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 340, in write
    self.write_tensors()
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 1375, in write_tensors
    super().write_tensors()
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 280, in write_tensors
    for new_name, data in ((n, d.squeeze().numpy()) for n, d in self.modify_tensors(data_torch, name, bid)):
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 1372, in modify_tensors
    return [(self.map_tensor_name(name), data_torch)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/llama.cpp/convert-hf-to-gguf.py", line 181, in map_tensor_name
    raise ValueError(f"Can not map tensor {name!r}")
ValueError: Can not map tensor 'model.layers.0.mlp.down_proj.qweight'

**Comment by mnlife** [comment]
Maybe convert-hf-to-gguf.py does not support a 4-bit quantization model, you can try using Yi-34B-Chat
