### ISSUE TITLE
Feature Request: Support for Yuan2-M32 

### ISSUE THREAD

**Issue by matteoserva** [ggerganov/llama.cpp#7632]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Adding support for the new Yuan2-M32 model architecture.

### Motivation

Yuan2-M32 is a new MoE model that looks very promising. It has just been released. It would be nice to have it available in llama.cpp since using their fork of vllm is a pain.

**Comment by matteoserva** [comment]
There is a working fork of llama.cpp that supports Yuan2-M32 here:
https://github.com/chong000/3rd_party/tree/main

I just tested it with the int4 gguf and it works

**Comment by DarkReaperBoy** [comment]
@ggerganov 
hai, it would be great if [yuan2](https://huggingface.co/IEITYuan/Yuan2-M32-hf) gets supported sooner. it's a moe close to l3 70b perf at 40b, with ~3b expert active at a time. it seems also it has a [fork](https://github.com/IEIT-Yuan/3rd_party) that works. i wonder if it's matter of time, condition, or official pull request from the model maker?
