### ISSUE TITLE
Refactor: Add CONTRIBUTING.md and/or update PR template with [no ci] tips

### ISSUE THREAD

**Issue by mofosyne** [ggerganov/llama.cpp#7657]
### Background Description

Discussion in https://github.com/ggerganov/llama.cpp/pull/7650 pointed out a need to add a CONTRIBUTING.md and maybe add a PR template to encourage contributors to add [no ci] tag to documentation only changes.

https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

(If anyone wants to tackle this, feel free to)

### Possible Refactor Approaches

Add info about

- doc only changes should have [no ci] in commit title to skip the unneeded CI checks.
- squash on merge with commit title format: "module : some commit title (`#1234`)"

**Comment by nicolasperez19** [comment]
Hi! I'm new and would like to contribute to the repo! Is it fine if I can take on this issue?

**Comment by nicolasperez19** [comment]
I'll get on working on it. Thank you!

**Comment by mofosyne** [comment]
No probs @nicolasperez19 , don't spend too much work on making it perfect.
 
Get the general outline first and make the PR a draft. I think we still need to make sure there is a consensus on how this should work first.

**Comment by nicolasperez19** [comment]
@mofosyne I just submitted the PR. You can take a look and feel free to make any changes.
