### ISSUE TITLE
When using GPU (OpenCL), the reply speed is slower and all replies are incorrect？？

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ggerganov/llama.cpp#7661]
### What happened?

I used termux to compile llama.cpp with gpu.  and i found that the response speed has been slower and they are all errors。

like:
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/e5009839-a3fa-432c-bd7e-3e5827dcf5db)
error response:
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/763810a2-ba27-43d0-9077-abf9a1b58d72)

Who can tell me what the reason is？？？？

### Name and Version

./bin/main -t 8 -ngl 33 -m ../llama-2-7b-chat.Q4_0.gguf --color -n -1 -ins -b 256

environment：  linux+termux   GPU: Qualcomm  8gen2

**Comment by JohannesGaessler** [comment]
The OpenCL backend is basically abandoned. Use CUDA/HIP for best performance, or Vulkan if you need something that works across platforms.

@slaren @ggerganov should we at this point just remove OpenCL?

**Comment by ggerganov** [comment]
Yes, let's remove the OpenCL backend

**Comment by QIANXUNZDL123** [comment]
> The OpenCL backend is basically abandoned. Use CUDA/HIP for best performance, or Vulkan if you need something that works across platforms.
> 
> @slaren @ggerganov should we at this point just remove OpenCL?

Thanks for the answer, I'll try Vulkan in my project

**Comment by acbits** [comment]
> ### What happened?
> 
> I used termux to compile llama.cpp with gpu. and i found that the response speed has been slower and they are all errors。
> 
> like: ![image](https://private-user-images.githubusercontent.com/46549527/335486471-e5009839-a3fa-432c-bd7e-3e5827dcf5db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjAxNjgsIm5iZiI6MTcxNzM1OTg2OCwicGF0aCI6Ii80NjU0OTUyNy8zMzU0ODY0NzEtZTUwMDk4MzktYTNmYS00MzJjLWJkN2UtM2U1ODI3ZGNmNWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIwMjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MTA0YzA4YWE5OTQ3MjhlZDU1N2RkYjhlYmY1NThmODRlNjgzNDYxYmViOWFlYTE0MmEyNzZiYWRmYWI1OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rpnrf8SeuYvOlKqyOLVeKmAzGhTXQf15k6uCF16z9kU) error response: ![image](https://private-user-images.githubusercontent.com/46549527/335486618-763810a2-ba27-43d0-9077-abf9a1b58d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjAxNjgsIm5iZiI6MTcxNzM1OTg2OCwicGF0aCI6Ii80NjU0OTUyNy8zMzU0ODY2MTgtNzYzODEwYTItYmEyNy00M2QwLTkwNzctYWJmOWExYjU4ZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIwMjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWFjOTVjOTkzMDllNDNkMjNkNGVhYTdlYjhlYzdkMmFkNzIxMDU0ZjlmMWNiNGIzNjAzNDg5N2I2YTUxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HEWMopaIcVZMH8GzeoQYcUnBJkRY8Lw5CNHe1mTXxs4)
> 
> Who can tell me what the reason is？？？？
> ### Name and Version
> 
> ./bin/main -t 8 -ngl 33 -m ../llama-2-7b-chat.Q4_0.gguf --color -n -1 -ins -b 256
> 
> environment： linux+termux GPU: Qualcomm 8gen2
> ### What operating system are you seeing the problem on?
> 
> _No response_
> ### Relevant log output
> 
> _No response_

>
I am using OpenCL and it is working fine here though I am using a different model.

```
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    85.94 MiB
llm_load_tensors:     OpenCL buffer size =  4474.93 MiB
```


`main -m /opt/mymodels/llama-2-7b.Q5_K_M.gguf -ngl 1024 -c 512 -b 1024 -n 256 --keep 48 --repeat_penalty 1.0 --color -i -t 4 -r User: -f ./llama/prompts/chat-with-bob.txt`

_User:Who is Elon Musk?
Bob: Elon Musk is a South African-born Canadian-American entrepreneur and investor. He is the CEO and CTO of SpaceX, co-founder and CEO of Neuralink, and co-founder and CEO of Tesla, Inc._

**Comment by acbits** [comment]
> Yes, let's remove the OpenCL backend

What about people like me using a AMD GPU? 

I think  abandoning a API without identifying the root cause doesn't seem like a good idea.

**Comment by slaren** [comment]
You can use HIP or Vulkan backends with AMD hardware.

**Comment by acbits** [comment]
> You can use HIP or Vulkan backends with AMD hardware.

Why abandon an API that was designed for heterogenous computing?  You write your code against one API and it runs everywhere.

**Comment by slaren** [comment]
The main issue is that the OpenCL backend is not being actively maintained because there aren't any developers with interest on it, and over time this has caused it to become hopelessly outdated. At this point, we have better alternatives for all the use cases of the OpenCL backend, so there is little reason to put any effort into. However, if you want the OpenCL backend to continue existing in llama.cpp, the best thing you could do is volunteer to maintain it. Asking for other people to volunteer is not really going to achieve anything.

**Comment by acbits** [comment]
> The main issue is that the OpenCL backend is not being actively maintained because there aren't any developers with interest on it, and over time this has caused it to become hopelessly outdated. At this point, we have better alternatives for all the use cases of the OpenCL backend, so there is little reason to put any effort into. However, if you want the OpenCL backend to continue existing in llama.cpp, the best thing you could do is volunteer to maintain it. Asking for other people to volunteer is not really going to achieve anything.

I don't mind contributing, granted I am new to ML, but do have experience in C/C++.

**Comment by 0cc4m** [comment]
> > You can use HIP or Vulkan backends with AMD hardware.
> 
> Why abandon an API that was designed for heterogenous computing? You write your code against one API and it runs everywhere.

I wrote the OpenCL backend. OpenCL isn't in a good position anymore, lagging behind in features and vendor support. For example memory pinning in the way CUDA does it, which is very useful for partial offload, isn't possible.

That's why I decided last year to build the Vulkan backend instead of continuing to develop the OpenCL one. Vulkan also means you have to write code once and it'll run anywhere, and it's more modern and better supported by vendors like Nvidia.

**Comment by netrunnereve** [comment]
> What about people like me using a AMD GPU?

Even if your AMD devices don't support HIP the Vulkan implementation should be faster than OpenCL for both prompt processing and inference. Currently the only devices that benefit from OpenCL support are old Arm embedded machines and pre-GCN AMD graphics cards.

**Comment by shibe2** [comment]
Interestingly, for one of my use cases, CLBlast back-end can be a little bit faster than Vulkan.

| model                          |       size |     params | backend    | ngl |   n_ubatch |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ------------: | ---------------: |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | Vulkan     |   0 |        256 |        pp2048 |     14.23 ± 0.03 |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | Vulkan     |   0 |        512 |        pp2048 |     21.04 ± 0.17 |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | Vulkan     |   0 |       1024 |        pp2048 |     26.87 ± 0.08 |

| model                          |       size |     params | backend    | ngl |   n_ubatch |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ------------: | ---------------: |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | OpenCL     |   0 |        256 |        pp2048 |     13.58 ± 0.01 |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | OpenCL     |   0 |        512 |        pp2048 |     21.05 ± 0.02 |
| llama 70B Q5_K - Medium        |  46.51 GiB |    70.55 B | OpenCL     |   0 |       1024 |        pp2048 |     28.02 ± 0.02 |

While on default settings the speed is the same, OpenCL seems to benefit more from increased batch size.

**Comment by QIANXUNZDL123** [comment]
> Interestingly, for one of my use cases, CLBlast back-end can be a little bit faster than Vulkan.
> 
> model	size	params	backend	ngl	n_ubatch	test	t/s
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	Vulkan	0	256	pp2048	14.23 ± 0.03
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	Vulkan	0	512	pp2048	21.04 ± 0.17
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	Vulkan	0	1024	pp2048	26.87 ± 0.08
> model	size	params	backend	ngl	n_ubatch	test	t/s
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	OpenCL	0	256	pp2048	13.58 ± 0.01
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	OpenCL	0	512	pp2048	21.05 ± 0.02
> llama 70B Q5_K - Medium	46.51 GiB	70.55 B	OpenCL	0	1024	pp2048	28.02 ± 0.02
> While on default settings the speed is the same, OpenCL seems to benefit more from increased batch size.

What is your environment? AMD GPU or ARM GPU?  I'm using OpenCL in Termux, but it's very slow, and my environment is 8Gen2

**Comment by jetro30087** [comment]
> Yes, let's remove the OpenCL backend

I was looking through the source code for ggml-openCL.cpp is there a particular reason models are dequantized to FP32 before performing matmul calculations? Why can't they be dequantized to FP16 or lower?

**Comment by 0cc4m** [comment]
> > Yes, let's remove the OpenCL backend
> 
> I was looking through the source code for ggml-openCL.cpp is there a particular reason models are dequantized to FP32 before performing matmul calculations? Why can't they be dequantized to FP16 or lower?

Only few GPUs support 16-bit floats in OpenCL, for example all Nvidia GPUs don't. I tried it once, I think, but it didn't help with speeds either. Dunno what you mean with "or lower".

**Comment by tangjinchuan** [comment]
@0cc4m Thank you very much for all your effort to make OpenCL happen. We once contacted while locating problems for A770 https://github.com/CNugteren/CLBlast/issues/533. 
For 16 bit support, NVIDIA told me in a bug report that they are not fully compliant with cl_khr_fp16 with built-in functions such as sine cosine. But they support to use #pragma OPENCL EXTENSION cl_khr_fp16 : enable if we like FP16 without those functions.
I would sincerely ask keeping OpenCL backend at the moment as a tunned GEMM is still waiting new opensource implementations in metal/vulkan/hip. I wish I had the time to maintain OpenCL backend, but I could not. 
I was involved in Projects like CLBLAST, VKFFT, PyTorch DLprimitives, as well as Ocatave OCL. My own project is https://sourceforge.net/projects/octave-ocl-extra/ with nothing but to keep OpenCL alive until some really good alternative is out. 
  
Best wishes,
Jinchaun

**Comment by shibe2** [comment]
>I wish I had the time to maintain OpenCL backend, but I could not.

The trouble is exactly that no one worked on CLBlast back-end enough to keep it in shape.

**Comment by thewh1teagle** [comment]
> Yes, let's remove the OpenCL backend

Now without OpenCL there's no optimization for regular Windows computers with TPUs almost at all. OpenBlas doesn't help much.
https://github.com/ggerganov/whisper.cpp/issues/2303

**Comment by 0cc4m** [comment]
> > Yes, let's remove the OpenCL backend
> 
> Now without OpenCL there's no optimization for regular Windows computers with TPUs almost at all. OpenBlas doesn't help much. [ggerganov/whisper.cpp#2303](https://github.com/ggerganov/whisper.cpp/issues/2303)

OpenCL never ran on TPUs, only on GPUs, same as Vulkan.
