### ISSUE TITLE
Feature Request: GGUF 2 BIN

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#7695]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Please include a utility to convert a GGUF file to BIN... I have a  few model requantized using "quantize" and I don't want to redownload everything.

### Motivation

Some programs want a bin file, one of them I'm testing it's not opensource.

### Possible Implementation

same as convert.py backwards :P

**Comment by henk717** [comment]
I know that aphrodite has a feature like this : https://github.com/PygmalionAI/aphrodite-engine/blob/main/examples/gguf_to_torch.py

**Comment by 0wwafa** [comment]
> I know that aphrodite has a feature like this : https://github.com/PygmalionAI/aphrodite-engine/blob/main/examples/gguf_to_torch.py

It's another behemot.. we need utilities like llama.cpp .. native.. C language, think and fast.. everytime I test something is 1-2 gb of python modules and then something goes wrong.. I'm really tired of all this.
