### ISSUE TITLE
Bug: STATIC COMPILE not static anymore :(

### ISSUE THREAD

**Issue by Zibri** [ggerganov/llama.cpp#7719]
### What happened?

Before I was compiling (mingw/clang64) with:
cmake . -DLLAMA_NATIVE=ON -DLLAMA_BUILD_SERVER=ON -DBUILD_SHARED_LIBS=OFF -B build --fresh

and the result was a static executable with no dependencies.

### Name and Version

latest

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
now instead I get
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffa922d0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffa905a0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffa8fe90000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7ffa919f0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ffa91be0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ffa8fba0000)
        libomp.dll => /clang64/bin/libomp.dll (0x7ffa5f0d0000)
        libc++.dll => /clang64/bin/libc++.dll (0x7ffa5f1a0000)
        PSAPI.DLL => /c/WINDOWS/System32/PSAPI.DLL (0x7ffa921c0000)
```

**libomp.dll => /clang64/bin/libomp.dll (0x7ffa5f0d0000)**
**libc++.dll => /clang64/bin/libc++.dll (0x7ffa5f1a0000)**

**Comment by Zibri** [comment]
why?

**Comment by Zibri** [comment]
I think -DLLAMA_OPENMP=OFF is needed too.

**Comment by slaren** [comment]
Unfortunately I don't think there is an easy way to link to OpenMP statically. If you need a build with absolutely no dependencies, disabling OpenMP may be the only option.
