### ISSUE TITLE
Bug: Does any convert.py supprt llama3?

### ISSUE THREAD

**Issue by zyc1128** [ggerganov/llama.cpp#7737]
### What happened?

Does any convert.py supprt llama3?

### Name and Version

Does any convert.py supprt llama3?

**Comment by christianazinn** [comment]
You'll want to use `convert-hf-to-gguf.py`. The Llama3 BPE pretokenizer is supported by default in `convert-hf-to-gguf-update.py`.

**Comment by Galunid** [comment]
Convert the `.pth` weights yourself using https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py, or download the weights from huggingface. Then you can use `convert-hf-to-gguf.py`

**Comment by Galunid** [comment]
See https://github.com/huggingface/transformers/pull/30334, this is not our script and sadly we can't provide support for it.

**Comment by ArthurZucker** [comment]
If you update to the latest version of transformers the scripts supports the conversion
