### ISSUE TITLE
Bug: prefix completion endpoint with /v1

### ISSUE THREAD

**Issue by metal3d** [ggerganov/llama.cpp#7740]
### What happened?

The server should respect OpenAPI path, but "completion" endpoint is not prefixed by "/v1"

This is required by NeoVim LLM-LS plugin which uses "openapi" backend to call "/v1/completion".

Thanks

### Name and Version

version: 2902 (9afdffe7)
built with cc (GCC) 14.0.1 20240411 (Red Hat 14.0.1-0) for x86_64-redhat-linux

### What operating system are you seeing the problem on?

Linux

**Comment by ggerganov** [comment]
Check if https://github.com/ggerganov/llama.cpp/pull/7741 fixes the issue

**Comment by metal3d** [comment]
I'm sorry, bad issue...

Actually it's `/v1/completions` that is called by the plugin. And the endpoint is OK. I made a mistake while I tried with `curl`.
