### ISSUE TITLE
Feature Request: tokenized history

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#7744]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

When chatting, at the end, in the developer console I see there is an object containing all the conversation and parameters.
That's great.
But at the start of the chat there is "no memory".
So I take the "prompt" field and feed it back as the system prompt and the chat goes on from there.
But I have a better idea: since in this way the prompt has to be tokenized and analyzed again by the ai,
would it be better to save a file with the actual state and then reload it (optionally) at the start?
Like in an emulator when you save the full state of the machine and then you resume it another day?

### Motivation

Giving the session time to grow and reloading the previous status without overhead.

### Possible Implementation

add a flag in server and main to save (and load) the "machine state".
the save should happen every XXX tokens
when loading the "old" session, the max token should be the one specified plus the token already used..
for example:
I have a long conversation... and the total is around 5000 tokens.
My max tokens is 8192...
qhen I load the old session, the token count will be 5000 and I will have another 8192 tokens so a total of 13192 tokens for the context.

**Comment by RoggerTan** [comment]
Correct me if I'm wrong, but I think what you want is prompt caching (check out [persistent Interaction](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#persistent-interaction)), which has been implemented for a while.

**Comment by 0wwafa** [comment]
> Correct me if I'm wrong, but I think what you want is prompt caching (check out [persistent Interaction](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#persistent-interaction)), which has been implemented for a while.

Oh.. I totally missed that. I wonder if that options just saves the prompts/answers or does some kind of optimization/compression.. nevermind.. I will study it...
