### ISSUE TITLE
Feature Request: Support for NVEmbed

### ISSUE THREAD

**Issue by christianazinn** [ggerganov/llama.cpp#7746]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Attempting to `python3 convert-hf-to-gguf.py` with NVIDIA's latest NVEmbed model yields a `NotImplementedError: Architecture 'NVEmbedModel' not supported!` Add support for `NVEmbedModel` architecture.

### Motivation

NVIDIA recently released their [NVEmbed](https://huggingface.co/nvidia/NV-Embed-v1) embeddings model based on the Mistral 7B decoder that [ranks #1 on the MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard). It would be nice to see support for this in llama.cpp.

### Possible Implementation

I'm not sure how different it would be than existing embeddings architectures. I'm aware other decoder-based models like [SFR Embedding Mistral](https://huggingface.co/Salesforce/SFR-Embedding-Mistral) have [GGUF quants](https://huggingface.co/dranger003/SFR-Embedding-Mistral-GGUF) which work, so I figure the NVEmbed model is structured similarly. Then it's mostly a matter of writing in a new model class for it in `convert-hf-to-gguf.py`.

**Comment by iamlemec** [comment]
It looks like `NVEmbed` is basically Mistral but with non-causal attention and "latent attention" pooling. I hadn't seen latent attention pooling before, but judging from the modeling code on HF, it's just another attention layer on top of the last hidden states.

Right now in `llama.cpp`, we can tell causal-by-default models like Mistral to use non-causal attention. If we get #7477 merged, that will allow general pooling on these models. The only catch is we don't have latent pooling implemented, but it should be quite straightforward.

**Comment by christianazinn** [comment]
> If we get #7477 merged, that will allow general pooling on these models. The only catch is we don't have latent pooling implemented, but it should be quite straightforward.

Thanks, will wait for that to be merged.

**Comment by camilovelezr** [comment]
Hello!

Is this still on track to eventually being supported?

**Comment by noahhaon** [comment]
+1 here as well, NV-Embed-2 is top of the MTEB embeddings leaderboard:

https://huggingface.co/spaces/mteb/leaderboard

**Comment by sakthi-geek** [comment]
@iamlemec I can see #7477 is merged. Will we get NV-Embed V2 support soon?

**Comment by vmsv** [comment]
Any news on this?

**Comment by AlgorithmicKing** [comment]
any update yet?
