### ISSUE TITLE
Bug: Building with CUDA is as slow as CUDA OFF.

### ISSUE THREAD

**Issue by jojorne** [ggerganov/llama.cpp#7752]
### What happened?

```
-- Using CUDA architectures: 52;61;70
```
```
call "server.exe" --log-disable --model "%model%" --ctx-size 8192 --n-gpu-layers "24" --n-predict "512"
```
```
INFO [main] build info | tid="29080" timestamp=1717528846 build=3087 commit="1442677f"
INFO [main] system info | tid="29080" timestamp=1717528846 n_threads=12 n_threads_batch=-1 total_threads=24 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | "
```
```
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 92
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: cannot reallocate multi buffer graph automatically, call reserve
ggml_backend_sched_alloc_splits: failed to allocate graph, reserving
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
```
Then the last line repeats every interaction. It is as slow as CUDA OFF.

### Name and Version

version: 3087 (1442677f)
built with MSVC 19.40.33811.0 for

### What operating system are you seeing the problem on?

Windows

**Comment by Galunid** [comment]
@jojorne What's your GPU?

@agray3 It seems there's some CUDA graphs issue. Could you take a look?

**Comment by jojorne** [comment]
> @jojorne What's your GPU?
> 
> @agray3 It seems there's some CUDA graphs issue. Could you take a look?

GTX1060 6GB

**Comment by jojorne** [comment]
I was finally able to fix the error.

```bat
@echo off
title LLaMACpp
cd /d "%~dp0\llama.cpp"
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64 -vcvars_ver=14.40
cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_C_FLAGS="/utf-8" -DCMAKE_CXX_FLAGS="/utf-8 /EHsc" -DCMAKE_CUDA_FLAGS="--compiler-options=/utf-8" -DLLAMA_CCACHE=0 -DLLAMA_CUDA=1 %*
cmake --build build --config Release -j %NUMBER_OF_PROCESSORS%
pause

```

**Comment by jojorne** [comment]
> I encounter the same issue, plz teach me how you solved it.

Windows, right? Well, llama.cpp was created to run on Linux and by default it uses UTF-8.
Since Windows does not, you need to compile with the UTF-8 flag.
What I was forgetting is that NVCC also uses MSVC... 😒
Therefore, you have to pass UTF-8 for CUDA to pass it to MSVC.
BTW, I'm also passing EHsc to CXX to silence its errors.

**Comment by OgreTransporter** [comment]
@jojorne 
Could you please explain that in more detail? Which flag did you insert where? Do you mean `/utf-8` (https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8)? I have added the flag once as follows:
```
    if(MSVC)
        add_compile_options("$<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=/utf-8>")
        add_compile_options("/utf-8")
    endif()
```
Now compiling no longer works for me:
```
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
```
