### ISSUE TITLE
Feature Request: Multi session chat support

### ISSUE THREAD

**Issue by BigCatGit** [ggerganov/llama.cpp#7758]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

After running the llama3 model and using curl for simultaneous conversations, I received responses that were queued instead of running simultaneously. I hope to support the processing of multiple sessions like multithreading

### Motivation

Implement local multi session chat

**Comment by HanClinto** [comment]
See #5762 and #4216 for more discussion of (possibly-related) server improvements.

**Comment by HanClinto** [comment]
Looking at #5794 it appears that this feature may already be added.

When running the server, did you set the `--threads-http` parameter? Setting this to >1 looks like it may enable you to process multiple requests simultaneously? (disclaimer: I have not yet attempted this myself)

**Comment by person4268** [comment]
Try setting `--cont-batching` and `--parallel 2`.
