### ISSUE TITLE
docker image ghcr.io/ggerganov/llama.cpp:light not working

### ISSUE THREAD

**Issue by dnalexen** [ggerganov/llama.cpp#776]
The docker image ghcr.io/ggerganov/llama.cpp:light no longer works. It exits without giving the answer.

**Comment by prusnak** [comment]
What is the exact command line you use?

**Comment by dnalexen** [comment]
I used this command:
docker run -v /llama/models:/models ghcr.io/ggerganov/llama.cpp:light -m /models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512

**Comment by prusnak** [comment]
Can you paste the whole output? Do you have the model files downloaded at /llama/models ?
