### ISSUE TITLE
Feature Request: Add support for xLSTM

### ISSUE THREAD

**Issue by uwu-420** [ggerganov/llama.cpp#7764]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

NX-AI released code for their xLSTM architecture: https://github.com/NX-AI/xlstm
The corresponding paper: https://arxiv.org/abs/2405.04517
So it would be pretty cool to add support for xLSTM to llama.cpp

### Motivation

The xLSTM architecture seems to be a notable improvement upon standard LSTM and competitive with transformers.
There still need to be more independent results to confirm this.
Either way, it would be interesting to have this architecture supported for llama.cpp due to it's lower memory usage compared to transformers and the (theoretically) infinite context length.

**Comment by ai-bits** [comment]
Hey @uwu-420 , you wre pretty early on this! [Your request](https://discord.com/channels/1110598183144399058/1342417760323637299) was forewarded to me on the LM Studio Discord.

Would love to meet you at [xLSTM inference in Ollama or GUI like LM Studio or similar?
](https://huggingface.co/NX-AI/xLSTM-7b/discussions/10)

Cheers
G.
