### ISSUE TITLE
Bug: Unable to generate imatrix data using imatrix.exe from release 3089

### ISSUE THREAD

**Issue by Spacellary** [ggerganov/llama.cpp#7765]
### What happened?

Started having this issue today, assuming after the only recent commit to `imatrix.cpp` (https://github.com/ggerganov/llama.cpp/commit/1442677f92e45a475be7b4d056e3633d1d6f813b#diff-75299e7302c2c05622a58cb4901166fc1e94bcdde981961e55e3d939cbf41825), where using this command:

`.\imatrix.exe -m .\model.gguf -f .\imatrix.txt -ngl 10`

...doesn't work anymore, it doesn't error or anything, imatrix generation just doesn't happen.

Am I missing something that was added to this process over the last three days?

It works as expected (imatrix) in the version I used from 3 days ago, namely **[b3070](https://github.com/ggerganov/llama.cpp/releases/tag/b3070), before this change**, but it could have been another one from the commit - or other changes to build.

### Name and Version
[b3089](https://github.com/ggerganov/llama.cpp/releases/tag/b3089)
[llama-b3089-bin-win-cuda-cu12.2.0-x64](https://github.com/ggerganov/llama.cpp/releases/download/b3089/llama-b3089-bin-win-cuda-cu12.2.0-x64.zip)
imatrix.exe
latest repo commit

### What operating system are you seeing the problem on?

Windows 11 23H2

### Hardware

GTX 1070 Ti 8GB (Pascal) - Drivers 555.85
6C/12T CPU
32GB DDR4 RAM

**Comment by ggerganov** [comment]
Could you give this PR a few tests and see if everything works as expected: https://github.com/ggerganov/llama.cpp/pull/7771

**Comment by Spacellary** [comment]
I do not have the setup to compile it.
