### ISSUE TITLE
Feature Request: Enhance gguf-set-metadata.py to support changing simple strings

### ISSUE THREAD

**Issue by jim-plus** [ggerganov/llama.cpp#7770]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Enhance gguf-set-metadata.py to support changing simple strings.

Example: python llama.cpp/gguf-py/scripts/gguf-set-metadata.py experiment.Q8_0.gguf tokenizer.ggml.pre llama-bpe

(Unsure if 

### Motivation

Adjust pre-tokenizer manually.

```
ERROR:gguf-set-metadata:! This tool only supports changing simple values, 'tokenizer.ggml.pre' has unsupported type [<GGUFValueType.STRING: 8>]
```

**Comment by CISC** [comment]
That's not possible unless the new string is the exact length of the old string, ie. not likely.

Use `gguf-new-metadata.py` instead.

**Comment by jim-plus** [comment]
Thanks. Will try that instead.
