### ISSUE TITLE
Bug: server-cuda Docker image failing as of 2 days ago - "error while loading shared libraries: libgomp.so.1: cannot open shared object file"

### ISSUE THREAD

**Issue by adamreis** [ggerganov/llama.cpp#7774]
### What happened?

System: Ubuntu 22.04, CUDA 12.5, Driver 555.42.02, Ryzen 7950x3D, RTX 4090

`ghcr.io/ggerganov/llama.cpp:server-cuda--b1-a10cda5` is the last image that works as expected for me. `server-cuda--b1-a5735e4` (2 days ago) and later all yield the following error:

> docker compose up llama-cpp
[+] Running 1/0
 ⠋ Container quill-ops-llama-cpp-1  Recreated                                                                                                          0.0s
Attaching to llama-cpp-1
llama-cpp-1  | /server: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
llama-cpp-1 exited with code 127

### Name and Version

ghcr.io/ggerganov/llama.cpp:server-cuda--b1-a5735e4; Ubuntu 22.04, CUDA 12.5, Driver 555.42.02, Ryzen 7950x3D, RTX 4090, libgomp installed on host, Nvidia docker runtime

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
> docker compose up llama-cpp
[+] Running 1/0
 ⠋ Container quill-ops-llama-cpp-1  Recreated                                                                                                          0.0s
Attaching to llama-cpp-1
llama-cpp-1  | /server: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
llama-cpp-1 exited with code 127
```

**Comment by mblunt** [comment]
I am having the same issue.

**Comment by adamreis** [comment]
Thanks @slaren @ggerganov 🙏🏻
