### ISSUE TITLE
Feature Request: GLM-4 9B Support

### ISSUE THREAD

**Issue by arch-btw** [ggerganov/llama.cpp#7778]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

It would be really cool to have support for these models that were released today. They have some very impressive benchmarks. I've also been trying out the model in huggingface spaces myself and noticed it speaks a lot of languages fluently and is knowledgeable on many topics. Thank you for your time.

Here are the download links: 

- [glm-4-9b-chat](https://huggingface.co/THUDM/glm-4-9b-chat)
- [glm-4-9b-chat-1m](https://huggingface.co/THUDM/glm-4-9b-chat-1m)
- [glm-4v-9b](https://huggingface.co/THUDM/glm-4v-9b)

Here is the English README: [README_en.md](https://github.com/THUDM/GLM-4/blob/main/README_en.md)

### Motivation

The motivation for this feature are found in some of the technical highlights for this model:

- These models were trained on 10T tokens.
- GLM-4-9B-Chat models have 9B parameters.
- GLM-4-9B-Chat-1M model supports 1M context length and scored 100% on the needle in haystack challenge. 
- GLM-4-9B models support 26 languages.
- Has a vision model ([glm-4v-9b](https://huggingface.co/THUDM/glm-4v-9b)).
- Early impressions are impressive.

Here are some of the results:

**Needle challenge:**

![eval_needle](https://github.com/ggerganov/llama.cpp/assets/57669023/97d8c333-a6ab-4a30-bd9a-d5801549f167)

**Longbench:**

![longbench](https://github.com/ggerganov/llama.cpp/assets/57669023/d1896332-2039-48c1-9f7e-6ec05a611d1c)

### Possible Implementation

We might be able to use some of the code from: https://github.com/ggerganov/llama.cpp/pull/6999.

There is also [chatglm.cpp](https://github.com/li-plus/chatglm.cpp) but it doesn't support GLM-4.

**Comment by foldl** [comment]
You can try [chatllm.cpp](https://github.com/foldl/chatllm.cpp), which supports GLM-4.

**Comment by ELigoP** [comment]
> You can try [chatllm.cpp](https://github.com/foldl/chatllm.cpp), which supports GLM-4.

Well, it chatllm.cpp is CPU-only. Why not trying transformers version in fp16.

llama.cpp GPU support for GLM-4 would be great, and then quantized versions will appear, which will be even more comfortable to run.

This GLM-4 looks like comparable or beating LLama 3, maybe even best-in-class for now.

**Comment by matteoserva** [comment]
We might have this feature soon: https://github.com/ggerganov/llama.cpp/pull/8031

**Comment by yukiarimo** [comment]
Any updates?

**Comment by yukiarimo** [comment]
I saw it's merged, but does it works with llama-cop-python and how to get vision stuff working in gguf?
