### ISSUE TITLE
Bug:  Error while running model file (.gguf ) in LM Studio

### ISSUE THREAD

**Issue by thehsansaeed** [ggerganov/llama.cpp#7779]
### What happened?

I'm encountering an error while trying to run a model in LM Studio. Below are the details of the error:

{
  "title": "Failed to load model",
  "cause": "llama.cpp error: 'error loading model architecture: unknown model architecture: 'clip''",
  "errorData": {
    "n_ctx": 2048,
    "n_batch": 512,
    "n_gpu_layers": 10
  },
  "data": {
    "memory": {
      "ram_capacity": "15.92 GB",
      "ram_unused": "7.46 GB"
    },
    "gpu": {
      "gpu_names": [
        "NVIDIA GeForce 940MX"
      ],
      "vram_recommended_capacity": "2.00 GB",
      "vram_unused": "1.64 GB"
    },
    "os": {
      "platform": "win32",
      "version": "10.0.22631",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.24",
      "downloadsDir": "C:\\Users\\hp\\.cache\\lm-studio\\models"
    },
    "model": {}
  }
}

![image](https://github.com/ggerganov/llama.cpp/assets/82998682/f408d74f-dee0-4347-983f-1c7d6c8e87e3)

### Name and Version

Windows 11

**Comment by JohannesGaessler** [comment]
I can only speak for myself but I 100% refuse to debug issues encountered with a proprietary downstream project. If at all possible, find a way to reproduce the problem using llama.cpp code only.

**Comment by napyang** [comment]
In my opinion, it seems you're loading a clip model. The right way is loading "llava-phi-3-mini-Q4_K_M.gguf" (or the other quantization version) and loading this mmporj as clip model.
I think if you put "llava-phi-3-mini-Q4_K_M.gguf" and mmporj models in the same folder, it should work fine.

**Comment by thehsansaeed** [comment]
> In my opinion, it seems you're loading a clip model. The right way is loading "llava-phi-3-mini-Q4_K_M.gguf" (or the other quantization version) and loading this mmporj as clip model.
> I think if you put "llava-phi-3-mini-Q4_K_M.gguf" and mmporj models in the same folder, it should work fine.

This is just one model ... I have tried multiple models but same issue facing. I have also changed location of models but same issue.

**Comment by loaderinbox** [comment]
переустановить LM студию для одного пользователя - не для всех, у некоторых срабатывает
