### ISSUE TITLE
Bug: JSON Schema-to-GBNF additionalProperties bugs (and other minor quirks)

### ISSUE THREAD

**Issue by HanClinto** [ggerganov/llama.cpp#7789]
### What happened?

While debugging json-schema-to-gbnf grammars, I noticed a few bugs / quirks and wanted to write them down somewhere.

# `additionalProperties` seems to default to `false` (not matching spec). 

By default, additional properties [should be permitted](https://json-schema.org/understanding-json-schema/reference/object#properties). However, providing a schema like:

```json
{
  "type": "object",
  "properties": {
    "number": { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "enum": ["Street", "Avenue", "Boulevard"] }
  }
}
```
Then it correctly passes on these strings:
```json
{ "number": 1600, "street_name": "Pennsylvania", "street_type":"Avenue"}
```
```json
{ "street_name": "Pennsylvania" }
```
```json
{ "number": 1600, "street_name": "Pennsylvania" }
```
```json
{}
```

But then it improperly fails on the string:
```json
{ "number": 1600, "street_name": "Pennsylvania", "street_type":"Avenue", "direction":"NW"}
```
This is [clearly given](https://json-schema.org/understanding-json-schema/reference/object#properties) in the json-schema docs as an example of a string that should match this schema, so we're doing something wrong.

# Explicit `"additionalProperties"=true` behavior is even worse.

If we change the above grammar to:
```
{
  "type": "object",
  "properties": {
    "number": { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "enum": ["Street", "Avenue", "Boulevard"] }
  },
  "additionalProperties": true
}
```
Then things really start to go awry. These strings should all pass (indeed, they passed before when we didn't explicitly set anything for `additionalProperties`, but instead are failing now:
```json
{"number":1600,"street_name":"Pennsylvania","street_type":"Avenue"}
```
```json
{ "street_name": "Pennsylvania" }
```
```json
{ "number": 1600, "street_name": "Pennsylvania" }
```
And our sample with an additional property still doesn't match:
```json
{ "number": 1600, "street_name": "Pennsylvania", "street_type":"Avenue", "direction":"NW"}
```

The only string that matches out of the original is the empty object (`{}`).

Looking at the generated GBNF, there is some weird stuff going on. Here is the GBNF with additionalProperties set implicitly:

```ebnf
char ::= [^"\\] | "\\" (["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F])
decimal-part ::= [0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9])?)?)?)?)?)?)?)?)?)?)?)?)?)?)?
integral-part ::= [0-9] | [1-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9])?)?)?)?)?)?)?)?)?)?)?)?)?)?)?
number ::= ("-"? integral-part) ("." decimal-part)? ([eE] [-+]? integral-part)? space
number-kv ::= "\"number\"" space ":" space number
number-rest ::= ( "," space street-name-kv )? street-name-rest
root ::= "{" space  (number-kv number-rest | street-name-kv street-name-rest | street-type-kv )? "}" space
space ::= " "?
street-name-kv ::= "\"street_name\"" space ":" space string
street-name-rest ::= ( "," space street-type-kv )?
street-type ::= "\"Street\"" | "\"Avenue\"" | "\"Boulevard\""
street-type-kv ::= "\"street_type\"" space ":" space street-type
string ::= "\"" char* "\"" space
```

And here is the GBNF from `additionalProperties` set explicitly to `true`:
```ebnf
additional-kv ::= string ":" space additional-value
additional-kvs ::= additional-kv ( "," space additional-kv )*
additional-value ::= object
array ::= "[" space ( value ("," space value)* )? "]" space
boolean ::= ("true" | "false") space
char ::= [^"\\] | "\\" (["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F])
decimal-part ::= [0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9])?)?)?)?)?)?)?)?)?)?)?)?)?)?)?
integral-part ::= [0-9] | [1-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9] ([0-9])?)?)?)?)?)?)?)?)?)?)?)?)?)?)?
null ::= "null" space
number ::= ("-"? integral-part) ("." decimal-part)? ([eE] [-+]? integral-part)? space
number-kv ::= "\"number\"" space ":" space number
number-rest ::= ( "," space street-name-kv )? street-name-rest
object ::= "{" space ( string ":" space value ("," space string ":" space value)* )? "}" space
root ::= "{" space  (number-kv number-rest | street-name-kv street-name-rest | street-type-kv street-type-rest | additional-kvs )? "}" space
space ::= " "?
street-name-kv ::= "\"street_name\"" space ":" space string
street-name-rest ::= ( "," space street-type-kv )? street-type-rest
street-type ::= "\"Street\"" | "\"Avenue\"" | "\"Boulevard\""
street-type-kv ::= "\"street_type\"" space ":" space street-type
street-type-rest ::= additional-kvs
string ::= "\"" char* "\"" space
value ::= object | array | string | number | boolean | null
```

The key differences to note here are how `street-type-rest` is now being defined (even though it was never defined in the original), and `additional-kvs` seems to be getting appended to each property without a comma in between (nor an optional flag).

I haven't yet wrapped my brain around what all is going on with that, but I wanted to lay out how far I'd gotten on my own.

# Unlike strings, enums don't support spaces between properties and values.

This is definitely in the "quirk" more than "bug" category, but when using a schema like:
```json
{
  "type": "object",
  "properties": {
    "number": { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "enum": ["Street", "Avenue", "Boulevard"] }
  }
}
```
Then validating against it means that:
```json
{ "number": 1600, "street_type":"Avenue"}
```
is a valid string, but adding spaces around the enum value causes either of the following to fail:
```json
{ "number": 1600, "street_type": "Avenue"}
```
```json
{ "number": 1600, "street_type":"Avenue" }
```

Interestingly, adding spaces around a string value works fine, and these match the generated grammar just fine:
```json
{ "number": 1600, "street_name": "Pennsylvania" }
```

# Unsupported Attributes
We should probably build a list of unsupported attributes and note them in the documentation -- some that I've noticed thus far: 

* `exclusiveMinimum` (probably can't be handled for anything except for special cases of 0, requiring either the presence of a `-` or not)
* `uniqueItems` -- not sure how we could support this without a regex engine that supports capture groups and lookbehinds and whatnot.

### Name and Version

version: 3093 (7672adee)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.4.0

### What operating system are you seeing the problem on?

Mac

**Comment by ochafik** [comment]
@HanClinto thanks for reporting these!

- Fixing `additionalProperties`'s behaviour and its default in https://github.com/ggerganov/llama.cpp/pull/7840

- `exclusiveMinimum` is coming in https://github.com/ggerganov/llama.cpp/pull/7797

- As for `uniqueItems`, I did scratch my head quite a bit early on and I think it's a no-no w/ a stateless grammar.

  Probably best to document unsupported features like this in a new JSON schemas section within [grammars/README.md](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md) as the warnings are currently probably never really consumed by anyone (except CLI python converter runner). I'll look at updating the readme & refreshing the now stale grammar examples (e.g. json.gbnf still suffers from infinite precision numbers, etc)

**Comment by HanClinto** [comment]
As of #7840 and #7797, I believe this is resolved. Thank you!
