### ISSUE TITLE
Bug: token generation seems to slow down for higher slots

### ISSUE THREAD

**Issue by desperadoduck** [ggerganov/llama.cpp#7802]
### What happened?

I started llama-cpp server with -c 65536 and -parallel 4
All layers should run on Cuda.
It looks as if slots with lower numbers are much faster in prompt evaluation than those with higher numbers, even if there is nothing else going on on the server. Is this expected for some reason, or is there an issue with the context memory?

### Name and Version

ghcr.io/ggerganov/llama.cpp:server-cuda from today, which prints a strange version information:
version: 0 (unknown)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

**Comment by samikrc** [comment]
I use the server command with `-c 49152 -np 12`, which results in 12 slots of 4096 context length each. I have noticed that when I reduce the number of slots, each evaluation (measured in tokens/sec) is faster, compared to when there are more number of slots. Is this what you are describing too?
I suspect this is because of context switching in the GPU perhaps?

**Comment by ggerganov** [comment]
> It looks as if slots with lower numbers are much faster in prompt evaluation than those with higher numbers, even if there is nothing else going on on the server. Is this expected for some reason, or is there an issue with the context memory?

To some extend it is expected because the KV cache size grows with each new sequence in a new slot:

https://github.com/ggerganov/llama.cpp/blob/d5c938cd7716b9a2ace49a43a469dfbffcff4d28/llama.cpp#L12196-L12203

Does enabling Flash Attention `-fa` reduce the discrepancy between low and high slots?

**Comment by samikrc** [comment]
> > It looks as if slots with lower numbers are much faster in prompt evaluation than those with higher numbers, even if there is nothing else going on on the server. Is this expected for some reason, or is there an issue with the context memory?
> 
> To some extend it is expected because the KV cache size grows with each new sequence in a new slot:
> 
> https://github.com/ggerganov/llama.cpp/blob/d5c938cd7716b9a2ace49a43a469dfbffcff4d28/llama.cpp#L12196-L12203
> 
> Does enabling Flash Attention `-fa` reduce the discrepancy between low and high slots?

Thanks for the note. I will try this out.
