### ISSUE TITLE
Bug: QWEN2 quantization GGML_ASSERT

### ISSUE THREAD

**Issue by bartowski1182** [ggerganov/llama.cpp#7805]
### What happened?

When attempting to quantize [Qwen2 7B instruct](https://huggingface.co/Qwen/Qwen2-7B-Instruct) to IQ2_XS I get the following assert:

```
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
```

Anything I can provide to debug? Uploading the f32 file and imatrix now for recreation

Attempting IQ2_S now, ~~will update if it fails in the same way~~ update: it fails in the same way on the same block

### Name and Version

Version b3086, ubuntu 22.04

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
[ 327/ 339]              blk.27.attn_norm.weight - [ 3584,     1,     1,     1], type =    f32, size =    0.014 MB
[ 328/ 339]               blk.27.ffn_down.weight - [18944,  3584,     1,     1], type =    f32, converting to iq2_xs .. GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
GGML_ASSERT: ggml-quants.c:12083: grid_index >= 0
```

(PS: is this a high severity or medium/low?)

**Comment by bartowski1182** [comment]
Interestingly when I try Q2_K I see a different error:

[ 329/ 339]               blk.27.ffn_gate.weight - [ 3584, 18944,     1,     1], type =    f32, converting to q2_K .. ggml_validate_row_data: found nan value at block 0
ggml_validate_row_data: found nan value at block 0
ggml_validate_row_data: found nan value at block 0
ggml_validate_row_data: found nan value at block 0

(repeats several times)

**Comment by bartowski1182** [comment]
Files for recreating it locally are up here: https://huggingface.co/bartowski/Qwen2-7B-Instruct-GGUF/tree/main

**Comment by SabinStargem** [comment]
If 'Quill' is the leaked version of Qwen2, then something might have changed in llama.cpp that broke Qwen2 conversions into GGUF.  I am using a Quill GGUF from Mradermacher's repository about six or so days ago, and it works fine.   This assumes that the official release of Qwen2 isn't altered from Quill.

**Comment by slaren** [comment]
I think that the imatrix contains `nan` values. Did it complete without nan ppl?

**Comment by bartowski1182** [comment]
@slaren are you referring to the --no-ppl option by chance or did you mean something else?

when I remove the --no-ppl the imatrix output does look like this:

llama_cpp_gpu-1  | [1]nan,[2]nan,[3]nan,[4]nan,[5]nan,[6]nan,[7]nan,[8]nan,[9]nan,
llama_cpp_gpu-1  | save_imatrix: stored collected data after 10 chunks in /models/Qwen2-7B-Instruct-GGUF/Qwen2-7B-Instruct.imatrix
llama_cpp_gpu-1  | [10]nan,[11]nan,[12]nan,[13]nan,[14]nan,[15]nan,[16]nan,[17]nan,[18]nan,[19]nan,
llama_cpp_gpu-1  | save_imatrix: stored collected data after 20 chunks in /models/Qwen2-7B-Instruct-GGUF/Qwen2-7B-Instruct.imatrix
llama_cpp_gpu-1  | [20]nan,[21]nan,[22]nan,[23]nan,[24]nan,[25]nan,[26]nan,[27]nan,[28]nan,[29]nan,
llama_cpp_gpu-1  | save_imatrix: stored collected data after 30 chunks in /models/Qwen2-7B-Instruct-GGUF/Qwen2-7B-Instruct.imatrix

**Comment by slaren** [comment]
Yes. If you ever get `nan` in these values, the imatrix is pretty guaranteed to be useless. In fact the model is completely unusable as long as that happens.

**Comment by bartowski1182** [comment]
yikes.. so what the hell am i doing wrong that's not affecting others (or is it affecting others but it's just not obvious cause they didn't calculate imatrix?)

**Comment by bartowski1182** [comment]
I even tried updating to master and using different datasets

**Comment by slaren** [comment]
If it happens while using CUDA, it usually means that the model is producing activations that cannot be represented in a float16. We have workarounds to force float32 compute in these cases for the known models that need it, but it is very unusual.

**Comment by maziyarpanahi** [comment]
I do imatrix for Qwen2 models on pure CPU, no CUDA build: 
<img width="1111" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/5762953/318ef569-2cf1-4d04-9069-9a32f494f6db">

**Comment by bartowski1182** [comment]
ooo so that's gotta be it then.. strangely i converted to f32 instead of f16, but i assume that's not enough?

trying to run my F32 conversion with CUDA gives pure garbage

running it with -ngl 0 gives actual results

**Comment by slaren** [comment]
It may work with flash attention (`-fa`).

**Comment by slaren** [comment]
The problem seems to be in the KV. This patch should allow it to work:
```diff
diff --git a/llama.cpp b/llama.cpp
index 32264a00..6324af70 100644
--- a/llama.cpp
+++ b/llama.cpp
@@ -7009,7 +7009,7 @@ static struct ggml_tensor * llm_build_kqv(
         struct ggml_tensor * kq = ggml_mul_mat(ctx, k, q);
         cb(kq, "kq", il);

-        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX) {
+        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX || model.arch == LLM_ARCH_QWEN2) {
             // for this arch, we need to perform the KQ multiplication with F32 precision, otherwise we get NaNs
             // ref: https://github.com/ggerganov/llama.cpp/pull/4490#issuecomment-1859055847
             ggml_mul_mat_set_prec(kq, GGML_PREC_F32);
@@ -15376,6 +15376,10 @@ static void llama_model_quantize_internal(const std::string & fname_inp, c
```

However it also seems to work with flash attn even without `GGML_PREC_F32`. @JohannesGaessler do you know what that may be? is the fattn implementation less susceptible to intermediate values out of range of f16?

**Comment by bartowski1182** [comment]
As always super appreciative of the investigation and solve @slaren , you're awesome <3

**Comment by JohannesGaessler** [comment]
>is the fattn implementation less susceptible to intermediate values out of range of f16?

Assuming the problem is overflows rather than underflows I think the most likely reason is that my FlashAttention implementations initially scale Q with `1.0f/sqrtf(float(n_embd_head))` (because it's faster) while regular attention does the KQ matrix multiplication first and applies the scale to the result. But this factor is not very large so there is a good chance that for some specific inputs you would still get overflows.

**Comment by bartowski1182** [comment]
@slaren would ROCm also be experiencing this bug or is it just in CUDA code? Curious if other odd bugs out there can be explained by this

**Comment by dillfrescott** [comment]
Heres my current output for qwen2. llama.cpp seems to be utterly broken right now.

![Screenshot 2024-06-06 224438](https://github.com/ggerganov/llama.cpp/assets/56714680/c3ade575-6637-4740-b6f5-e36feeeedde9)

Here is my run command:

```
main -n -1 -m "qwen2-7b-instruct-q8_0.gguf" ^
--color --multiline-input -t 16 -ngl "900" ^
--log-disable -c 8192 --temp 0.6 --interactive-first ^
--interactive
```

**Comment by bartowski1182** [comment]
@dillfrescott can you try adding -fa and seeing if that helps?

**Comment by dillfrescott** [comment]
@bartowski1182 Damn, that totally fixed it! What does that flag do??

**Comment by bartowski1182** [comment]
Enables flash attention, apparently it runs the operations in a different order that prevents the issues

**Comment by dillfrescott** [comment]
Interesting

**Comment by JustinLin610** [comment]
> Heres my current output for qwen2. llama.cpp seems to be utterly broken right now.
> 
> ![Screenshot 2024-06-06 224438](https://private-user-images.githubusercontent.com/56714680/337503084-c3ade575-6637-4740-b6f5-e36feeeedde9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzYxNjYsIm5iZiI6MTcxNzczNTg2NiwicGF0aCI6Ii81NjcxNDY4MC8zMzc1MDMwODQtYzNhZGU1NzUtNjYzNy00NzQwLWI2ZjUtZTM2ZmVlZWVkZGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA0NTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNmUzZWNhMTk3NzMxMDAzNGMwZDZhZjY3ODgzZGM3MDg1YThmNmZhMzk0NDM0YjExOWZkYTViOWVmNWVlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f0VMrNtmwpFv9O6pDlsqASLz3IPIFecl7qN66-59AMA)
> 
> Here is my run command:
> 
> ```
> main -n -1 -m "qwen2-7b-instruct-q8_0.gguf" ^
> --color --multiline-input -t 16 -ngl "900" ^
> --log-disable -c 8192 --temp 0.6 --interactive-first ^
> --interactive
> ```

```
./main -m qwen2-7b-instruct-q5_k_m.gguf -n 512 --color -i -cml -f prompts/chat-with-qwen.txt
```
This is what I do. And are you using GPU and it might be a CUDA issue? Not sure. This thing also happens in Ollama for some users, but my friend inputs `/set num_gpu 0` and finds it work. Things are a bit strange for me...

**Comment by dillfrescott** [comment]
@JustinLin610 I am using a 4090 and have cuda version 12.5 installed. It usually works with every other model so I'm just not sure why.

**Comment by mann1x** [comment]
> @dillfrescott can you try adding -fa and seeing if that helps?

Any reason why enabling flash_attn for the imatrix calculation the time to complete increased from about 2.5h to 5h?
I thought I'd be faster... does it mean that without fa the imatrix was not computed properly?

**Comment by JohannesGaessler** [comment]
> @slaren would ROCm also be experiencing this bug or is it just in CUDA code? Curious if other odd bugs out there can be explained by this

Not him but the fundamental issue is that the KQ matrix has values outside the FP16 range. On Volta or newer or RX 7000 or newer llama.cpp does all matrix multiplications with a batch size > 64 using FP16 cuBLAS/HIPBLAS so you get garbage results. The fix works by instead calculating the KQ matrix with FP32 precision. The huge values from the KQ matrix are then fed to softmax which brings them into the 0-1 range again and fixes the numerical issues.

You should be able to fix the numerical issues with better performance on Ampere or newer by calculating the KQ matrix as BF16 instead of FP16 (with some precision loss which is probably negligible if you're going to apply softmax anyways). Annoyingly there is to my knowledge no way to make cuBLAS return the result as FP32 (even though that is the only output format that tensor cores actually support) because then we would also save some time on the conversion back to FP32.

**Comment by JohannesGaessler** [comment]
>Any reason why enabling flash_attn for the imatrix calculation the time to complete increased from about 2.5h to 5h (qwen2-72b)?
I thought I'd be faster... does it mean that without fa the imatrix was not computed properly?

Depends on what hardware you have, on AMD large batch FA performance is bad. I have received some reports about bad performance with partial offloading but so far I have never been able to reproduce this.

And note that I think that just adding `-fa` is **not** a reliable fix so there is a good chance that you will at some point still get NaNs.

**Comment by mann1x** [comment]
> Depends on what hardware you have, on AMD large batch FA performance is bad. I have received some reports about bad performance with partial offloading but so far I have never been able to reproduce this.

for normal inference works fine fa, it's running on an RTX3090 on Linux so 12 layers only on VRAM
I never got any NaN, either with or without fa

With `-fa`:
```llama_new_context_with_model: n_ctx      = 256
llama_new_context_with_model: n_batch    = 204
llama_new_context_with_model: n_ubatch   = 204
llama_new_context_with_model: flash_attn = 1
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    68.00 MiB
llama_kv_cache_init:      CUDA0 KV buffer size =    12.00 MiB
llama_new_context_with_model: KV self size  =   80.00 MiB, K (f16):   40.00 MiB, V (f16):   40.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.58 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  2500.71 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     6.60 MiB
llama_new_context_with_model: graph nodes  = 2487
llama_new_context_with_model: graph splits = 956

system_info: n_threads = 6 / 12 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
compute_imatrix: tokenizing the input ..
compute_imatrix: tokenization took 117.352 ms
compute_imatrix: computing over 100 chunks with batch_size 204
ggml_backend_cuda_graph_compute: CUDA graph update failed
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to too many consecutive updates
ggml_backend_cuda_graph_compute: CUDA graph update failed
compute_imatrix: 177.86 seconds per pass - ETA 4 hours 56.43 minutes
```

Without `-fa`:
```
llama_new_context_with_model: n_ctx      = 224
llama_new_context_with_model: n_batch    = 204
llama_new_context_with_model: n_ubatch   = 204
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    59.50 MiB
llama_kv_cache_init:      CUDA0 KV buffer size =    10.50 MiB
llama_new_context_with_model: KV self size  =   70.00 MiB, K (f16):   35.00 MiB, V (f16):   35.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.58 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  2500.71 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     6.57 MiB
llama_new_context_with_model: graph nodes  = 2806
llama_new_context_with_model: graph splits = 956

system_info: n_threads = 6 / 12 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0
 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
compute_imatrix: tokenizing the input ..
compute_imatrix: tokenization took 119.284 ms
compute_imatrix: computing over 100 chunks with batch_size 204
ggml_backend_cuda_graph_compute: CUDA graph update failed
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to too many consecutive updates
ggml_backend_cuda_graph_compute: CUDA graph update failed
compute_imatrix: 98.19 seconds per pass - ETA 2 hours 43.65 minutes
```

**Comment by CISC** [comment]
@slaren Even with an imatrix generated with c9ee7118d5644dd3df70ea6878b36a9761616aab and -fa (no NaNs) quantization still fails:
```
[  11/ 479]           blk.0.ffn_down_exps.weight - [ 2560,  3584,    64,     1], type =   bf16, converting to q2_K .. ggml_validate_row_data: found nan value at block 16
ggml_validate_row_data: found nan value at block 46
ggml_validate_row_data: found nan value at block 6
ggml_validate_row_data: found nan value at block 6
llama_model_quantize: failed to quantize: quantized data validation failed
```

I'm guessing this is due to the application of the imatrix to the weights overflowing?

**Comment by slaren** [comment]
I don't know, I would need to be able to reproduce it to be able to investigate why that happens.

**Comment by bartowski1182** [comment]
@CISC can you share more details? I didn't get issues with just -fa

What dataset, and are you converting to f16 or f32 first?

**Comment by CISC** [comment]
@bartowski1182 I'm quantizing from bf16, the imatrix is generated from 250K tokens of groups-merged-enhancedV3 concatenated with wiki.train.raw.

**Comment by mann1x** [comment]
it's just me having almost all the tensors requiring fallback when trying k/i-quants?

This is 0.5B but it does almost the same on all qwen2:
``
llama_tensor_get_type : tensor cols 896 x 128 are not divisible by 256, required for q3_K - using fallback quantization iq4_nl
...
llama_tensor_get_type : tensor cols 896 x 896 are not divisible by 256, required for q4_K - using fallback quantization q5_0
...
llama_tensor_get_type : tensor cols 896 x 128 are not divisible by 256, required for q5_K - using fallback quantization q5_1
...
llama_model_quantize_internal: WARNING: 144 of 168 tensor(s) required fallback quantization
```

I'm using the i-matrix on a 3090 with fa enabled

**Comment by CISC** [comment]
@slaren Ok, I believe I've located the issue. Whole blocks of x contain -0.0/0.0 weights here:
https://github.com/ggerganov/llama.cpp/blob/0c27e6f62eea80140daf152d7b6c154466614e5c/ggml-quants.c#L2181-L2186
which ultimately causes a divide-by-zero in `make_qp_quants` (taking sw as input):
https://github.com/ggerganov/llama.cpp/blob/0c27e6f62eea80140daf152d7b6c154466614e5c/ggml-quants.c#L2161

I'm not sure that 0-weights should be an actual issue, so the the fix is probably to check that `suml2` is non-zero.

**Comment by CISC** [comment]
Yep, confirmed working on `Q2_K` at least, now onto all the others...

**Comment by CISC** [comment]
I see several other places that have potential divide-by-zero, however a few places have the following, does this really work?
https://github.com/ggerganov/llama.cpp/blob/0c27e6f62eea80140daf152d7b6c154466614e5c/ggml-quants.c#L1681

**Comment by bartowski1182** [comment]
Don't see why it wouldn't, if the value is non 0 divide by it, otherwise 0.0f

**Comment by CISC** [comment]
> Don't see why it wouldn't, if the value is non 0 divide by it, otherwise 0.0f

Yeah, I just wasn't sure that was applicable to -0.0f.

**Comment by CISC** [comment]
Hmmm, IQ1_S fails spectacularly: `besti1 >= 0 && besti2 >= 0 && best_shift != 0`...

**Comment by CISC** [comment]
Sigh, there's lots more, now I'm hitting the `grid_index >= 0` assert too.

**Comment by mann1x** [comment]
@CISC 
Do you have branch to test it?

**Comment by CISC** [comment]
@mann1x #7825 But there are other issues, the imatrix will magically contain NaNs, see #7816

**Comment by JustinLin610** [comment]
> @JustinLin610 I am using a 4090 and have cuda version 12.5 installed. It usually works with every other model so I'm just not sure why.

Oh `-cml` is for chatml format. I just saw its missing in your command. But I think Bartowski mentioned the real problem.

**Comment by CISC** [comment]
After some fixing, fudging and a lot of debugging, I have found the reason for all the Qwen2 issues.

The models contain weights <±1e-25, sometimes quite a lot of them, depending on which format you converted them to this could cause issues in itself, but would cause NaNs during 16-bit KQ multiplications or certain quantizations for basically the same reason.

Unfortunately this renders models like 57B-A14B completely impossible to quantize to but a few that will not trigger this issue and/or doesn't require an imatrix.

**Comment by mann1x** [comment]
> Unfortunately this renders models like 57B-A14B completely impossible to quantize to but a few that will not trigger this issue and/or doesn't require an imatrix.

I made some quants without imatrix for ollama: https://ollama.com/mannix/qwen2-57b/tags

They seem to work properly but I didn't have time to test them extensively.
Should I double check?

**Comment by CISC** [comment]
> I made some quants without imatrix for ollama: https://ollama.com/mannix/qwen2-57b/tags
> They seem to work properly but I didn't have time to test them extensively. Should I double check?

No, those quants should be ok, at least if you made them from F32.

**Comment by mann1x** [comment]
> No, those quants should be ok, at least if you made them from F32.

Thanks for the confirmation! Yes indeed I picked f32 for bin as suggested,

**Comment by neteroster** [comment]
@CISC Thanks for your great work!

I'd like to understand the scope of impact this issue has, is quants without imatrix OK with the F32 KQ patch or they are not safe either? Additionally, is it possible that this issue might cause some quants to appear functional while the output quality degrades?

**Comment by CISC** [comment]
> I'd like to understand the scope of impact this issue has, is quants without imatrix OK with the F32 KQ patch or they are not safe either? Additionally, is it possible that this issue might cause some quants to appear functional while the output quality degrades for certain inputs?

I'd imagine **any** quantization will severely degrade the weights in question, how much of an issue in the final results that will be remains to be seen.

**Comment by clort81** [comment]
I hope someone points the qwen2 authors to this discussion.

**Comment by bartowski1182** [comment]
They're aware of it, but is there anything they can or should do..?

**Comment by grapevine-AI** [comment]
Hello.
I found that you make Q6_K first and then you re-quantize, you can make i-quants with i-matrix.
Q6_K is extremely high-quality so I think this method probably realize faultless quants.
In fact, my i-quants seem to be work correctly.
Would you please help to verify.

**Comment by mann1x** [comment]
> Would you please help to verify.

Do you have your quants uploaded somewhere?

**Comment by grapevine-AI** [comment]
My example is [here](https://huggingface.co/grapevine-AI/Qwen2-57B-A14B-Instruct-GGUF).
However, please note that I use both English and Japanese text because I am not sure what data English speakers typically use.

**Comment by bartowski1182** [comment]
hmm, this is odd..

Trying to run a Qwen2 quant (https://huggingface.co/bartowski/Tess-v2.5-Qwen2-72B-GGUF/blob/main/Tess-v2.5-Qwen2-72B-Q2_K.gguf) with GPU offloading yields a new assert:

GGML_ASSERT: ggml-cuda/dmmv.cu:665: false

based on the assert, my guess is that it's because ffn_down.weight was quantized to IQ4_NL? but obviously i'm not positive. Not offloading works fine, redownloading Q4_K_M to test since i see that didn't use IQ4_NL

@slaren any idea why this wasn't an issue in the past? Is there something special in Qwen2 that makes it want to use those quant types? Also it's strange because I thought IQ quants were fully supported on CUDA so i don't get why those asserts exist

**Comment by bartowski1182** [comment]
also gonna pull @JohannesGaessler back in since he seems to know the area very well

**Comment by JohannesGaessler** [comment]
>GGML_ASSERT: ggml-cuda/dmmv.cu:665: false

If you are on a P100 or Maxwell or older that is expected. For all quants other than the legacy quants and k-quants there is only a MMVQ implementation (which needs Pascal != P100 or newer) but no DMMV implementation. If you are using a GPU that should be supported that is a bug.

**Comment by bartowski1182** [comment]
ah dammit thank you, that's silly of me, i have a 3090 and a p100 and this pushed it onto that card

You say p100 or maxwell/older, does that imply the p40 is fine?

**Comment by slaren** [comment]
> Is there something special in Qwen2 that makes it want to use those quant types?

Most k and iq quants have a block size of 256, but this `ffn_down` in this model has a dimension that is not divisible by 256. IQ4_NL is used as a fallback for IQ4_XS and lower, since it has a block size of 32. For higher quants Q5_x or Q8_0 is used as the fallback instead, which is compatible with this GPU.

**Comment by JohannesGaessler** [comment]
>You say p100 or maxwell/older, does that imply the p40 is fine?

Yes, P100s have compute capability 6.0, all other Pascal GPUs (including P40s) have compute capability 6.1 which is the minimum CC for the `__dp4a` instruction (per-byte dot product).

**Comment by bartowski1182** [comment]
thanks both slaren and Johannes, that's good info, i appreciate it :D 

back on the original subject of this issue, is there a reason your proposed change wasn't opened as a PR? I can open one if that would help, just unsure if the proposed fix was deemed not appropriate

**Comment by mann1x** [comment]
> Would you please help to verify.

I'm testing the IQ3_XXS and seems to work very well.
Tried as well to create the imatrix from the Q6_K but it didn't work, always NaN

**Comment by slaren** [comment]
> is there a reason your proposed change wasn't opened as a PR?

Do you mean the fix to use fp32 precision for the attention? I didn't open a PR because the fix would affect all models with qwen2 architecture, and I recall reading that this model has other issues, and if this model is not very good, it may not be worth it to apply a patch that will decrease the performance of all the models with qwen2 architecture. But I may be wrong about that, if you think that it is worth it the fix could be merged.

**Comment by bartowski1182** [comment]
The thing is we now have a lot of fine tunes of Qwen2 72b coming out, and presumably they all have this issue (I haven't re-verified) so figured it would make sense, but maybe it is worth double checking, didn't realize there would be a big performance hit

**Comment by grapevine-AI** [comment]
> I'm testing the IQ3_XXS and seems to work very well. Tried as well to create the imatrix from the Q6_K but it didn't work, always NaN

Thanks for testing. 
Sorry, I simplified explanation too much so I'll try to make it clear.
I have shown detail on my HF's [README](https://huggingface.co/grapevine-AI/Qwen2-57B-A14B-Instruct-GGUF).

If anyone is interested in it, I would greatly appreciate it if you could attempt to reproduce the steps.

**Comment by mann1x** [comment]
> If anyone is interested in it, I would greatly appreciate it if you could attempt to reproduce the steps.

Thanks!
Still have the f32, will try again.

**Comment by mann1x** [comment]
> If anyone is interested in it, I would greatly appreciate it if you could attempt to reproduce the steps.

Tried creating the imatrix from Q8_0 but it came out same as with f32, I get NaN when quantising

**Comment by grapevine-AI** [comment]
> Tried creating the imatrix from Q8_0 but it came out same as with f32, I get NaN when quantising

Thank you!

Oh, no. I wonder if this method is depend on imatrix-dataset...
I'll research other language text data.

**Comment by CISC** [comment]
@grapevine-AI Your imatrix is corrupt BTW:
```
imatrix entry "blk.20.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.18.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.11.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.15.ffn_down_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.13.ffn_down_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.3.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.12.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.12.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.21.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.9.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.13.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.7.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.0.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.27.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.13.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.2.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.4.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.12.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.1.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.6.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.14.ffn_down_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.11.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.16.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.17.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.14.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.19.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.16.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.5.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.11.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.15.ffn_up_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.17.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.10.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.14.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.8.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.15.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.1.ffn_gate_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.1.ffn_down_exps.weight" contains non-normal value -nan, skipping!
imatrix entry "blk.16.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
imatrix entry "blk.17.ffn_down_exps.weight" contains non-normal value 0.000000, skipping!
```

I have made some progress though, by quantizing the BF16 to F16 and flushing anything <±1e-24 to ±0 I can now make fully working quants (with #7825 and #7955 applied) that do not require Flash Attention! However creating a fully activated imatrix still does not seem feasible...

**Comment by flastir** [comment]
Qwen2-72b stopped working after release b3091

Result in the [release b3091](https://github.com/ggerganov/llama.cpp/releases/tag/b3091):
```
User: who are you?
Llama: I am Llama, a friendly and helpful chatbot designed to assist you with any questions or tasks you might have. My goal is to make your day easier by providing accurate information and engaging in meaningful conversations.
```

Result in the next [release b3130](https://github.com/ggerganov/llama.cpp/releases/tag/b3130):
```
User: who are you?
Llama: !t 10.
The- .4s híst, and of
A) （）/b0–all.
...
```

In the latest release that I checked [b3291](https://github.com/ggerganov/llama.cpp/releases/tag/b3291) the model still doesn't work correctly.

The GGUF model was downloaded from [here](https://huggingface.co/bartowski/Qwen2-72B-Instruct-GGUF).

I started the server from llama-b3091-bin-win-cuda-cu12.2.0-x64.zip with this command:

`server.exe -m Qwen2-72B-Instuct-Q5_K_M-00001-of-00002.gguf -c 2048 -ngl 0 -fa`

The GGUF works normally in KoboldCpp v1.69.1 only if "Use FlashAttention" is checked and "Use QuantMatMul (mmq)" is unchecked.

Is there an argument to server.exe that disables MMQ?

**Comment by JohannesGaessler** [comment]
>The GGUF works normally in KoboldCpp v1.69.1 only if "Use FlashAttention" is checked and "Use QuantMatMul (mmq)" is unchecked.

>Is there an argument to server.exe that disables MMQ?

If at all possible, please try to reproduce the issue using only llama.cpp code and use git bisect to identify the exact commit that introduced the problem. You can disable MMQ by compiling with `GGML_CUDA_FORCE_CUBLAS`.

Also this very much sounds like a different problem than what was discussed previously here. Instead of commenting on an existing issue, please open a new issue instead. Otherwise there is a large risk that your issue will not get attention from the right people.

**Comment by flastir** [comment]
> Also this very much sounds like a different problem than what was discussed previously here. Instead of commenting on an existing issue, please open a new issue instead. Otherwise there is a large risk that your issue will not get attention from the right people.

Thank you! I've found the appropriate issue for my problem: [Issue #8025](https://github.com/ggerganov/llama.cpp/issues/8025)

**Comment by LostRuins** [comment]
Necro-ing this thread, but just chipping in, IQ4_NL is probably not an ideal fallback as it breaks compatibility with any backend that does not have I-Quant support (e.g. Vulkan), and leads to people unsure why certain K-quants just don't work when they're supposed to. 

I'd rather Q4_0 or Q8_0 be the default fallback for k-quants. This is just my 2 cents.

**Comment by ggerganov** [comment]
> IQ4_NL is probably not an ideal fallback as it breaks compatibility with any backend that does not have I-Quant support (e.g. Vulkan), and leads to people unsure why certain K-quants just don't work when they're supposed to.

Hm, it shouldn't break compatibility - the current implementation will fallback to CPU computation when the backend does not support a certain type. It would be slow, but it would still work
