### ISSUE TITLE
Multi-thread ggml_cpy()

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#782]
This is a task suitable for new contributors

See how we multi-threaded the [ggml_rope()](https://github.com/ggerganov/llama.cpp/pull/781) operator.
Do the same for the `ggml_cpy()` operator and see if there is any benefit.

Use the [ggml profiler (GGML_PERF)](https://github.com/ggerganov/llama.cpp/wiki/GGML-Tips-&-Tricks#measuring-the-performance-of-the-inference) to measure the benefit of multi-threaded vs non-multi-threaded `ggml_cpy()`

**Comment by farQuad787** [comment]
Hi, this is my first contribution to a large project so forgive me for being a newbie! I attempted to multithread cpy following the code from the rope commit but I started getting garbage output given an initial prompt. Would appreciate any guidance on what I'm doing wrong! [3c8a304](https://github.com/farQuad787/llama.cpp/commit/3c8a3046d41dbc75f21b31151515222afcba7ae3

**Comment by ggerganov** [comment]
So I have updated `ggml_cpy()` in the latest commit (c3ac702e5ee3533457e0489df4906ee112fe88e7) since I backported some changes from `whisper.cpp` - we can significantly improve the performance when `dst` is contiguous. The code is currently quite messy, but I think it can be easily simplified in the future.

While at it, I tried to multi-thread it and didn't observed any measurable improvements, so I guess there is no point in multi-threading it.

I will close this issue now

**Comment by slaren** [comment]
@ggerganov Do you still have your multi-threaded implementation of `ggml_cpy`? I would like to build on that to parallelize quantization in `ggml_cpy` for LoRA.

**Comment by ggerganov** [comment]
No, but it was pretty much the same as: https://github.com/ggerganov/llama.cpp/pull/824/files
Just use some shorter variable names like:

```c++
    const int ith = params->ith;
    const int nth = params->nth;

    int ir = 0;
```

**Comment by shkim-emily** [comment]
@ggerganov Hello, Does [ggml profiler (GGML_PERF)] not support now?
