### ISSUE TITLE
Bug: CUDA enabled docker container fails to launch

### ISSUE THREAD

**Issue by mblunt** [ggerganov/llama.cpp#7822]
### What happened?

Docker container is missing a shared object, causing failures on launch.

Modify as needed, taken from docs:
```docker run -p 8080:8080 -v /path/to/models:/models --gpus all ghcr.io/ggerganov/llama.cpp:server-cuda -m models/7B/ggml-model.gguf -c 512 --host 0.0.0.0 --port 8080 --n-gpu-layers 99```

### Name and Version

Version unknown, container will not launch.

### What operating system are you seeing the problem on?

Ubuntu Server, amd64 architecture.

### Relevant log output

```shell
/server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory```
```

**Comment by slaren** [comment]
`libcuda.so` is part of the NVIDIA driver, this is likely caused by a configuration issue.

**Comment by wilksu** [comment]
`-e LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/wsl/lib`
add the params,then it work

**Comment by toanju** [comment]
`-e LD_LIBRARY_PATH=/usr/local/cuda/compat/` is setting the correct location
