### ISSUE TITLE
Converting finetune LLaVA model to gguf but while debugging getting result = self.mapping.get(key[:-len(suffix)]) as None 

### ISSUE THREAD

**Issue by INZA111** [ggerganov/llama.cpp#7823]
Hello, I am trying to convert my pretrained LLaVA Mistral model to GGuF. However, when debugging the code, it prints **result = self.mapping.get(key[:-len(suffix)]) as None**. This is present inside **gguf-py/gguf/tensor_mapping.py**. I am using **convert-legacy-llama.py** for conversion. Any help will be appreciated.

**Comment by Wangmmstar** [comment]
Hi Inza, have you gotten any progress on this issue? I want to convert the fine-tuned llava to gguf models also. DO you know how to convert the tensor models to two gguf model including the projector model separately?

**Comment by INZA111** [comment]
Yeah, I had to do some debugging on **tensor_mapping.py** file

**Comment by elifbykrbc** [comment]
hi inza how did you convert to gguf your llava model? i'm on it for such a long time. but llava is not supported from anything to convert. i'd be appreciate if you lead me.

**Comment by INZA111** [comment]
What issue are you facing? I had to make some changes in tensor_mapping.py for my fine-tuned model, but the LLaVA model available on Hugging Face works fine without any modifications.

**Comment by elifbykrbc** [comment]
i want to push my fine tuned model into ollama lib but it's required to consist .gguf extension. But it's not supported by anything that suggested. So i was not able to quantize. but never see the tensor_mapping.py i'll take a look but can you provide me what type changes you did?

**Comment by lyp-liu** [comment]
> 我想将我的微调模型推送到 OLLAMA 库中，但它需要包含 .gguf 扩展名。但没有任何建议支持它。所以我无法量化。但从来没有看到tensor_mapping.py我会看一下，但你能提供我你做了什么类型的更改吗？

hi,elifbykrbc. May I ask if you have found a way to convert Llava to gguf that can be used by ollama？

**Comment by elifbykrbc** [comment]
@lyp-liu unfortunately no. i gave up a while ago.

**Comment by lucasjinreal** [comment]
I am trying to converting a customized llava-like model into gguf, current GGUF convertor all models goes into a single file, new comers actually not very easy to add new model support.

To this end, am crafting a package helps users more easily to convert any MLLMs into GGUF format, and then using ollama or llama.cpp for inference.
