### ISSUE TITLE
Research: Im writing a paper on our medical finetuned llava-v1.6,

### ISSUE THREAD

**Issue by rohithbojja** [ggerganov/llama.cpp#7831]
I am currently writing a paper on LLaVA-Med V1.6, which we have fine-tuned on medical images. The paper's first stage, detailing the fine-tuning process, is complete. I am now focusing on stage two: converting our fine-tuned model into a 4-bit GGUF format.

Could you please advise on what key points to include in this section? Additionally, could you suggest any relevant references or previous papers that discuss similar quantization processes?

Thank you for your assistance.

**Comment by JohannesGaessler** [comment]
I am not aware of any papers detailing the quantization techniques in llama.cpp. The expert to ask regarding questions of efficient quantization is @ikawrakow .

**Comment by rohithbojja** [comment]
@ikawrakow can u assist me in this?
