### ISSUE TITLE
Bug: Server ends up in infinite loop if number of requests in the batch is greater than parallel slots with system prompt

### ISSUE THREAD

**Issue by kdhingra307** [ggerganov/llama.cpp#7834]
### What happened?

If we send a batch of requests to `/completion` endpoint with `system_prompt` it get's stuck in infinite waiting because of the way system is updated.

As per my analysis, what happens is if the number of requests in batch are greater than number of available slots. It leads to extra requests getting stored in `deferred` queue.

As soon as even a single slot is available, it will lead to task transferred from defer queue to normal queue and trigger system_update (because system_prompt is available). System_update will change the state of all the other slots from `PROCESSING` -> `IDLE` because of release function.

So, for all the other slots, as they still have next_tokens to generate their final response is not sent and multitask_subtask_result_pending never gets updated.

One of the possible solution is to wait for all slots to finish before `system_update` is called or the other would be call `send_final_response` if slot has has_next_token as true inside `SLOT_COMMAND_RELEASE` function.

Also, i will be happy to contribute patch for it.

### Name and Version

./main --version
version: 2781 (716886cf)
built with Apple clang version 14.0.0 (clang-1400.0.29.202) for arm64-apple-darwin22.2.0

### What operating system are you seeing the problem on?

Linux, Mac

**Comment by samikrc** [comment]
Can you share the command line you are using? Are you using the `-cb` (continuous batching) option?

**Comment by kdhingra307** [comment]
@samikrc i am not using continuous batching.

Server Command:

```
./server -m ../llama/llama-2-7b-chat.Q8_0.gguf -c 3092 -np 2
```

curl call

```
curl --location 'http://127.0.0.1:8080/completion' \
--header 'cross-origin-opener-policy: same-origin' \
--header 'Content-Type: application/json' \
--data '{
    "prompt": [
        "<s>[INST]What'\''s on the bench?\n[/INST]",
        "<s>[INST]Hi How are you[/INST]",
        "<s>[INST]Write me 200 tokens random essay to delay processing[/INST]",
        "<s>[INST]Tell me story about Ring Attention [/INST]",
        "<s>[INST]How should future transformers be designed? [/INST]",
        "<s>[INST]What are the 10 best habits of normal human being? [/INST]"
    ],
    "n_predict": 128,
    "system_prompt": "<s>[INST] <<SYS>>Transcript of a never ending dialog, where the User interacts with an Assistant.\nThe Assistant is helpful, kind, honest, good at writing, and never fails to answer the User'\''s requests immediately and with precision.<</SYS>>[/INST]</s>\n"
}'
```

**Comment by kdhingra307** [comment]
@samikrc did u have a look at it? by chance

**Comment by samikrc** [comment]
Hi, sorry - have not looked into this. The following command line works quite well for me - may be you can try this out.
```
./build/bin/llama-server -m ./models/7B/Hermes-2-Pro-Mistral-7B.Q4_K_M.gguf --threads-http 10 -a "hermes-pro"  -c 20480 -np 5 -ngl 99 -cb -fa --host 0.0.0.0 --port 8585
```
Play around the `-c` and `-np` values based on your typical document size. Also switching on continuous batching and flash attention helps in my experience. With these parameters, even though the number of requests are higher, I have not experienced any hung situation. HTH.

**Comment by samikrc** [comment]
Also, try rebuilding the latest source code - I have seen many issues in the early days go away as bug fixes gets added!
