### ISSUE TITLE
Bug: server /completion endpoint no longer accepts numeric tokens

### ISSUE THREAD

**Issue by matteoserva** [ggerganov/llama.cpp#7855]
### What happened?

Before commit d9da0e4986f121c727bdd9579a6688097b11602c you could pass a array of integers to the server's /completion endpoint, containing the token_ids of the tokenized prompt.

### Name and Version

version: 3123 (c28a8390)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

**Comment by ggerganov** [comment]
Ah, did I break this?

**Comment by matteoserva** [comment]
Yes. That specific commit broke that feature. (sorry for closing and reopening the issue)
