### ISSUE TITLE
Bug: 'scripts/run-with-preset.py` fails on `--tensor-split` option when run on non-GPU-enabled system

### ISSUE THREAD

**Issue by HanClinto** [ggerganov/llama.cpp#7864]
### What happened?

Attempting to run `scripts/run-with-preset.py` as-instructed by the docs results in `error: invalid parameter for argument: --tensor-split`.

Steps to reproduce:

* Do initial run to create log_dir to build parameter file:
`./main -mu https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q4_K_M.gguf --logdir llama_preset_test`

* Use the resulting logfile as parameter to `run-with-preset.py`:
`python scripts/run-with-preset.py llama_preset_test/2024_06_10-15_57_02.2224678340.yml -bin main`

It will report:
```
INFO:run-with-preset:The preset file contained a total of 55 unused properties.
error: invalid parameter for argument: --tensor-split
```

Inside the .yml file, there is a line which says:

`tensor_split: [0.000000e+00]`

This is the offending line. If we remove this, then the `run-with-preset.py` executes just fine.

I believe that the problem is because this parameter is only parsed on systems where there is a GPU. On my M1 Macbook Pro, there is no GPU, so this option is not parsed in common.cpp:

```c++
    if (llama_supports_gpu_offload()) {
        options.push_back({ "*",           "-ngl,  --gpu-layers N",
                                                                        "number of layers to store in VRAM" });
        options.push_back({ "*",           "-ngld, --gpu-layers-draft N",
                                                                        "number of layers to store in VRAM for the draft model" });
        options.push_back({ "*",           "-sm,   --split-mode SPLIT_MODE",
                                                                        "how to split the model across multiple GPUs, one of:\n"
                                                                        "  - none: use one GPU only\n"
                                                                        "  - layer (default): split layers and KV across GPUs\n"
                                                                        "  - row: split rows across GPUs" });
        options.push_back({ "*",           "-ts,   --tensor-split SPLIT",
                                                                        "fraction of the model to offload to each GPU, comma-separated list of proportions, e.g. 3,1" });
        options.push_back({ "*",           "-mg,   --main-gpu i",       "the GPU to use for the model (with split-mode = none),\n"
                                                                        "or for intermediate results and KV (with split-mode = row) (default: %d)", params.main_gpu });
    }
```

Further (and I'm not sure about this point), it's possible that the floating-point nature of the `--tensor-split` option is causing it to not properly parse the value as default, so it's not ignoring it like it should. If the `run-with-preset.py` example could recognize that it's still at the default value, then it might not include it, and we wouldn't run into this error.

### Name and Version

version: 3163 (70de0deb)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.5.0

### What operating system are you seeing the problem on?

Mac

**Comment by JohannesGaessler** [comment]
`--logdir` and `run_with_preset.py` are very outdated; I've been thinking they should maybe be removed since they are likely to cause issues (in addition to this one).

**Comment by HanClinto** [comment]
> `--logdir` and `run_with_preset.py` are very outdated; I've been thinking they should maybe be removed since they are likely to cause issues (in addition to this one).

No objections from me there. I only found this behavior when I was testing #7809 . If this is dead code, then I definitely vote for removing it!
