### ISSUE TITLE
Bug: apparent pre-tokenization hash collision in get_vocab_base_pre() function in convert-hf-to-gguf.py script? Llama3 8B is mapped to smaug-bpe instead of llama-bpe

### ISSUE THREAD

**Issue by jim-plus** [ggerganov/llama.cpp#7881]
### What happened?

Applying convert-hf-to-gguf.py to the full weights of a Llama 3 8B model results in a GGUF which has pre-tokenizer of smaug-bpe instead of llama-bpe. The resulting quantized GGUFs won't load in current ooba because the older wheel lacks smaug-bpe support, although using gguf-new-metadata.py --pre-tokenizer llama-bpe will allow the updated GGUF to load in ooba.

### Name and Version

version: 3124 (fd5ea0f8)
built with MSVC 19.39.33521.0 for x64

**Comment by expy777** [comment]
not sure it it's related, could be similar issue by keyword 'smaug-bpe'...
trying to load model MaziyarPanahi/Llama-3-8B-Instruct-v0.9-GGUF in LMS, it fails with error message:

```json
{
  "title": "Failed to load model",
  "cause": "llama.cpp error: 'error loading model vocabulary: unknown pre-tokenizer type: 'smaug-bpe''",
  "errorData": {
    "n_ctx": 2048,
    "n_batch": 512,
    "n_gpu_layers": 24
  },
  "data": { <skipped>
