### ISSUE TITLE
Prompt eval time is counted twice

### ISSUE THREAD

**Issue by sw** [ggerganov/llama.cpp#790]
Creating a new issue so this doesn't get forgotten:

@KASR posted a CSV of processing times in https://github.com/ggerganov/llama.cpp/issues/603#issuecomment-1492941163

But the times don't add up: If you take the total time, and subtract the partial times that are supposed to add up to it, the result is all over the place:

![image](https://user-images.githubusercontent.com/4478/229292361-52df310b-e838-46b6-a68c-5c1d69cf5f87.png)

The clue lies in the comment by @ggerganov :
> @sw 
> After the `mmap` changes, the `load` time is incorrect:
> 
> https://github.com/ggerganov/llama.cpp/blob/6e7801d08d81c931a5427bae46f00763e993f54a/llama.cpp#L1681-L1685
> 
> Currently, the reported load time includes not only the page faults, but also the prompt eval time. So effectively, you get the negative number since the prompt eval time has been accounted 2 times.
We have to fix this.

_Originally posted by @ggerganov in https://github.com/ggerganov/llama.cpp/issues/603#issuecomment-1493275009_

**Comment by goerch** [comment]
The timing computations looks correct for me, tested with `ggml` (main branch). Can this issue be closed then?

**Comment by ggerganov** [comment]
It's still broken in `llama.cpp` because we do the following:

https://github.com/ggerganov/llama.cpp/blob/0db14fef06836caaa13cc123c0a24dc598bdb9f0/llama.cpp#L3504-L3525

The reason we do it like this is because when using `mmap`, the loading of the data happens as we need it. I.e. it will happen during the first `llama_eval_internal()` call. But this call also involves computations which should not be counted towards the "load" time.

You don't see this in `ggml` because it does not have `mmap` support there and this effect cannot be observed.

**Comment by goerch** [comment]
> The reason we do it like this is because when using `mmap`, the loading of the data happens as we need it.

I'm not sure this is the only problem. If I understand

```
std::tuple<struct llama_model *, struct llama_context *> llama_init_from_gpt_params(const gpt_params & params) {
    auto lparams = llama_context_params_from_gpt_params(params);

    llama_model * model  = llama_load_model_from_file(params.model.c_str(), lparams);
    if (model == NULL) {
        fprintf(stderr, "%s: error: failed to load model '%s'\n", __func__, params.model.c_str());
        return std::make_tuple(nullptr, nullptr);
    }

    llama_context * lctx = llama_new_context_with_model(model, lparams);
    if (lctx == NULL) {
        fprintf(stderr, "%s: error: failed to create context with model '%s'\n", __func__, params.model.c_str());
        llama_free_model(model);
        return std::make_tuple(nullptr, nullptr);
    }

    ...

    return std::make_tuple(model, lctx);
}
```

correctly, model loading is independent from context creation here and we cant' access the timings from this function even when not using `mmap`?
