### ISSUE TITLE
Bug: Error while converting BERT to GGUF: Can not map tensor 'bert.embeddings.LayerNorm.beta'

### ISSUE THREAD

**Issue by Wheelspawn** [ggerganov/llama.cpp#7924]
### What happened?

I am trying to convert the [bert-base-uncased](https://huggingface.co/google-bert/bert-base-uncased) HuggingFace model to GGUF with [convert-hf-to-gguf.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-hf-to-gguf.py) Unfortunately, it fails to convert because the script looks for `embeddings.position_embeddings`, etc. in [tensor-mapping.py](https://github.com/ggerganov/llama.cpp/blob/172c8256840ffd882ab9992ecedbb587d9b21f15/gguf-py/gguf/tensor_mapping.py#L44) but not `bert.embeddings.position_embeddings`, etc. This is important because most of the tensor names in the model start with `bert`.

There is a similar issue in [modify-tensors](https://github.com/ggerganov/llama.cpp/blob/master/convert-hf-to-gguf.py#L2192). It does not skip the `cls` tensors that are present in [bert-base-uncased](https://huggingface.co/google-bert/bert-base-uncased), so it fails in the same way.

Finally, the bert-base-uncased `config.json` has its architecture set to `BertForMaskedLM`. But unless I change this to `BertModel` the script will return `ERROR:hf-to-gguf:Model BertForMaskedLM is not supported`.

I have modified [write-tensors](https://github.com/ggerganov/llama.cpp/blob/172c8256840ffd882ab9992ecedbb587d9b21f15/convert-hf-to-gguf.py#L247) to drop 'bert.' from each name, and modified [modify-tensors](https://github.com/ggerganov/llama.cpp/blob/master/convert-hf-to-gguf.py#L2192) to ignore names with `cls.` in them. Re-running the script will output "Model successfully exported", but when I try to generate an embedding with the model on the `llama-cli` I get this subsequent error:
`llama_model_load: error loading model: check_tensor_dims: tensor 'token_embd_norm.weight' not found`. 

### Name and Version

version: 3051 (5921b8f0)
built with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Steps to Reproduce

Clone [bert-base-uncased](https://huggingface.co/google-bert/bert-base-uncased) and run the convert script on it.
To see my attempted solution, do these steps:

1. Change `BertForMaskedLM` to `BertModel` in `bert-base-uncased/config.json`.
2. Run the convert script in [my fork](https://github.com/Wheelspawn/llama.cpp) of llama.cpp on the directory.
3. Run `./llama-cli -m` on the converted model.

### Relevant log output

```shell
$ python convert-hf-to-gguf.py /home/nsage/bert-base-uncased/ --outtype f16 --outfile /home/nsage/bert-base-uncased/bert_converted.gguf
INFO:hf-to-gguf:Loading model: bert-base-uncased
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:gguf: context length = 512
INFO:hf-to-gguf:gguf: embedding length = 768
INFO:hf-to-gguf:gguf: feed forward length = 3072
INFO:hf-to-gguf:gguf: head count = 12
INFO:hf-to-gguf:gguf: layer norm epsilon = 1e-12
INFO:hf-to-gguf:gguf: file type = 1
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Setting special token type pad to 0
INFO:hf-to-gguf:Exporting model to '/home/nsage/bert-base-uncased/bert_converted.gguf'
INFO:hf-to-gguf:gguf: loading model part 'model.safetensors'
Traceback (most recent call last):
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2862, in <module>
    main()
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2856, in main
    model_instance.write()
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 328, in write
    self.write_tensors()
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 265, in write_tensors
    for new_name, data in ((n, d.squeeze().numpy()) for n, d in self.modify_tensors(data_torch, name, bid)):
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2190, in modify_tensors
    return [(self.map_tensor_name(name), data_torch)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsage/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 180, in map_tensor_name
    raise ValueError(f"Can not map tensor {name!r}")
ValueError: Can not map tensor 'bert.embeddings.LayerNorm.beta'
```

```
$ ./llama-cli -m /home/nsage/bert-base-uncased/ggml-model-Q4_0.gguf -p "The sky is blue."
...
llama_model_load: error loading model: check_tensor_dims: tensor 'token_embd_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/home/nsage/bert-base-uncased/ggml-model-Q4_0.gguf'
main: error: unable to load model
```

**Comment by nopmop** [comment]
@Wheelspawn the reason why you are getting that message, is because the tensors from the source model are being mapped to wrong names in the destination format. You can't simply ignore prefixes like you did: you need to map them to proper names. To do this, the only thing you must do is to change the `map_tensor_name()` function in `convert_hf_to_gguf.py` and add the proper mapping. I'll give you my function for BERT.

```
    def map_tensor_name(self, name):
        # Remove the 'bert.' prefix if present
        if name.startswith('bert.'):
            name = name[len('bert.'):]
        
        # Handle specific mappings for the embedding layers and the classification head
        tensor_mappings = {
            'embeddings.word_embeddings.weight': 'token_embd.weight',
            'embeddings.position_embeddings.weight': 'position_embd.weight',
            'embeddings.token_type_embeddings.weight': 'token_types.weight',
            'embeddings.LayerNorm.weight': 'token_embd_norm.weight',
            'embeddings.LayerNorm.bias': 'token_embd_norm.bias',
            'embeddings.position_ids': 'position_ids',
            'cls.predictions.bias': 'cls.predictions.bias',
            'cls.predictions.transform.LayerNorm.bias': 'cls.predictions.transform.layer_norm.bias',
            'cls.predictions.transform.LayerNorm.weight': 'cls.predictions.transform.layer_norm.weight',
            'cls.predictions.transform.dense.bias': 'cls.predictions.transform.dense.bias',
            'cls.predictions.transform.dense.weight': 'cls.predictions.transform.dense.weight',
            'pooler.dense.weight': 'pooler.dense.weight',
            'pooler.dense.bias': 'pooler.dense.bias',
        }

        # Add mappings for all encoder layers (assuming 12 layers for BERT base)
        for i in range(12):
            tensor_mappings.update({
                f'encoder.layer.{i}.attention.output.LayerNorm.bias': f'blk.{i}.attn_output_norm.bias',
                f'encoder.layer.{i}.attention.output.LayerNorm.weight': f'blk.{i}.attn_output_norm.weight',
                f'encoder.layer.{i}.attention.output.dense.bias': f'blk.{i}.attn_output.bias',
                f'encoder.layer.{i}.attention.output.dense.weight': f'blk.{i}.attn_output.weight',
                f'encoder.layer.{i}.attention.self.key.bias': f'blk.{i}.attn_k.bias',
                f'encoder.layer.{i}.attention.self.key.weight': f'blk.{i}.attn_k.weight',
                f'encoder.layer.{i}.attention.self.query.bias': f'blk.{i}.attn_q.bias',
                f'encoder.layer.{i}.attention.self.query.weight': f'blk.{i}.attn_q.weight',
                f'encoder.layer.{i}.attention.self.value.bias': f'blk.{i}.attn_v.bias',
                f'encoder.layer.{i}.attention.self.value.weight': f'blk.{i}.attn_v.weight',
                f'encoder.layer.{i}.intermediate.dense.bias': f'blk.{i}.ffn_up.bias',
                f'encoder.layer.{i}.intermediate.dense.weight': f'blk.{i}.ffn_up.weight',
                f'encoder.layer.{i}.output.LayerNorm.bias': f'blk.{i}.layer_output_norm.bias',
                f'encoder.layer.{i}.output.LayerNorm.weight': f'blk.{i}.layer_output_norm.weight',
                f'encoder.layer.{i}.output.dense.bias': f'blk.{i}.ffn_down.bias',
                f'encoder.layer.{i}.output.dense.weight': f'blk.{i}.ffn_down.weight',
            })

        # Return the mapped name if it exists in the mappings
        if name in tensor_mappings:
            return tensor_mappings[name]

        # Raise an error if the tensor name cannot be mapped
        raise ValueError(f"Can not map tensor {name!r}")
```

However, if you get all your tensors to load correctly, the model may still fail because it expects the wrong number of tensors. Cheers.

**Comment by lusongshuo-mt** [comment]
> @Wheelspawn the reason why you are getting that message, is because the tensors from the source model are being mapped to wrong names in the destination format. You can't simply ignore prefixes like you did: you need to map them to proper names. To do this, the only thing you must do is to change the `map_tensor_name()` function in `convert_hf_to_gguf.py` and add the proper mapping. I'll give you my function for BERT.
> 
> ```
>     def map_tensor_name(self, name):
>         # Remove the 'bert.' prefix if present
>         if name.startswith('bert.'):
>             name = name[len('bert.'):]
>         
>         # Handle specific mappings for the embedding layers and the classification head
>         tensor_mappings = {
>             'embeddings.word_embeddings.weight': 'token_embd.weight',
>             'embeddings.position_embeddings.weight': 'position_embd.weight',
>             'embeddings.token_type_embeddings.weight': 'token_types.weight',
>             'embeddings.LayerNorm.weight': 'token_embd_norm.weight',
>             'embeddings.LayerNorm.bias': 'token_embd_norm.bias',
>             'embeddings.position_ids': 'position_ids',
>             'cls.predictions.bias': 'cls.predictions.bias',
>             'cls.predictions.transform.LayerNorm.bias': 'cls.predictions.transform.layer_norm.bias',
>             'cls.predictions.transform.LayerNorm.weight': 'cls.predictions.transform.layer_norm.weight',
>             'cls.predictions.transform.dense.bias': 'cls.predictions.transform.dense.bias',
>             'cls.predictions.transform.dense.weight': 'cls.predictions.transform.dense.weight',
>             'pooler.dense.weight': 'pooler.dense.weight',
>             'pooler.dense.bias': 'pooler.dense.bias',
>         }
> 
>         # Add mappings for all encoder layers (assuming 12 layers for BERT base)
>         for i in range(12):
>             tensor_mappings.update({
>                 f'encoder.layer.{i}.attention.output.LayerNorm.bias': f'blk.{i}.attn_output_norm.bias',
>                 f'encoder.layer.{i}.attention.output.LayerNorm.weight': f'blk.{i}.attn_output_norm.weight',
>                 f'encoder.layer.{i}.attention.output.dense.bias': f'blk.{i}.attn_output.bias',
>                 f'encoder.layer.{i}.attention.output.dense.weight': f'blk.{i}.attn_output.weight',
>                 f'encoder.layer.{i}.attention.self.key.bias': f'blk.{i}.attn_k.bias',
>                 f'encoder.layer.{i}.attention.self.key.weight': f'blk.{i}.attn_k.weight',
>                 f'encoder.layer.{i}.attention.self.query.bias': f'blk.{i}.attn_q.bias',
>                 f'encoder.layer.{i}.attention.self.query.weight': f'blk.{i}.attn_q.weight',
>                 f'encoder.layer.{i}.attention.self.value.bias': f'blk.{i}.attn_v.bias',
>                 f'encoder.layer.{i}.attention.self.value.weight': f'blk.{i}.attn_v.weight',
>                 f'encoder.layer.{i}.intermediate.dense.bias': f'blk.{i}.ffn_up.bias',
>                 f'encoder.layer.{i}.intermediate.dense.weight': f'blk.{i}.ffn_up.weight',
>                 f'encoder.layer.{i}.output.LayerNorm.bias': f'blk.{i}.layer_output_norm.bias',
>                 f'encoder.layer.{i}.output.LayerNorm.weight': f'blk.{i}.layer_output_norm.weight',
>                 f'encoder.layer.{i}.output.dense.bias': f'blk.{i}.ffn_down.bias',
>                 f'encoder.layer.{i}.output.dense.weight': f'blk.{i}.ffn_down.weight',
>             })
> 
>         # Return the mapped name if it exists in the mappings
>         if name in tensor_mappings:
>             return tensor_mappings[name]
> 
>         # Raise an error if the tensor name cannot be mapped
>         raise ValueError(f"Can not map tensor {name!r}")
> ```
> 
> However, if you get all your tensors to load correctly, the model may still fail because it expects the wrong number of tensors. Cheers.

Hello,

Thank you very much for sharing your work. I successfully converted a `BertForClassification` model to the 8-bit GGUF format. However, when I attempt to perform inference using the following code:
```python
from llama_cpp import Llama
model_gguf_path = "/path/to/bertforclassification_gguf_file"
model_gguf = Llama(model_gguf_path)
```

I encounter the following error:
```python
Traceback (most recent call last):
  File "npu_align_eval.py", line 14, in <module>
    model_gguf = Llama(model_gguf)
  File "/opt/conda/envs/llama_cpp/lib/python3.8/site-packages/llama_cpp/llama.py", line 372, in __init__
    _LlamaModel(
  File "/opt/conda/envs/llama_cpp/lib/python3.8/site-packages/llama_cpp/_internals.py", line 56, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /parh/to/xxx.gguf
```

I was wondering if you have encountered this issue before, or if you could provide any guidance on how to resolve it?

Thank you in advance for your help!

**Comment by nopmop** [comment]
@lusongshuo-mt I've never seen the error but it looks like you have a typo somewhere in the code: notice `parh` rather than `path` reported in the last line of the error you pasted. Are you sure the path to the GGUF model is properly specified?

**Comment by lusongshuo-mt** [comment]
> @lusongshuo-mt I've never seen the error but it looks like you have a typo somewhere in the code: notice `parh` rather than `path` reported in the last line of the error you pasted. Are you sure the path to the GGUF model is properly specified?

Thank you for your response. It seems I wasn’t clear enough in my previous message. The actual error I’m encountering is:
```bash
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 201, got 197
llama_load_model_from_file: failed to load model
```
This issue likely arises because my GGUF model includes four new variables:
- bert.pooler.dense.bias
- bert.pooler.dense.weight
- classifier.bias
- classifier.weight

I would appreciate any advice or solutions you might have to resolve this issue.

**Comment by iamlemec** [comment]
@lusongshuo-mt You need to make sure those tensors are dropped in `modify_tensors`. Take a look at the base class `BertModel.modify_tensors` and modify that to include them in the list.

**Comment by nopmop** [comment]
@lusongshuo-mt did you fix it? 
If you need help, I'm around.

**Comment by antonio-lamberti** [comment]
Encountering a similar issue when trying to convert jinaai/jina-embeddings-v3 to gguf:
python3.12 convert_hf_to_gguf.py --outtype f32 ./models/jina-embeddings-v3 --outfile ./models/jina-embeddings-v3.gguf
Error:
INFO:hf-to-gguf:Loading model: jina-embeddings-v3
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:gguf: loading model part 'model.safetensors'
INFO:hf-to-gguf:token_embd_norm.bias,            torch.bfloat16 --> F32, shape = {1024}
INFO:hf-to-gguf:token_embd_norm.weight,          torch.bfloat16 --> F32, shape = {1024}
Traceback (most recent call last):
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 4430, in <module>
    main()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 4424, in main
    model_instance.write()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 433, in write
    self.prepare_tensors()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 297, in prepare_tensors
    for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 2728, in modify_tensors
    return super().modify_tensors(data_torch, name, bid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 2587, in modify_tensors
    return [(self.map_tensor_name(name), data_torch)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 213, in map_tensor_name
    raise ValueError(f"Can not map tensor {name!r}")
ValueError: Can not map tensor 'embeddings.token_type_embeddings.parametrizations.weight.0.lora_A'

Glad for any help!

**Comment by nopmop** [comment]
@antonio-lamberti you need to modify `map_tensor_name()` to provide mappings that "translate" the names of tensors to GGUF format. Please use my mapping function and see if it works out of the box. Ciao.

**Comment by antonio-lamberti** [comment]
> @antonio-lamberti you need to modify `map_tensor_name()` to provide mappings that "translate" the names of tensors to GGUF format. Please use my mapping function and see if it works out of the box. Ciao.

Thanks for the help, just tried! 
But I still get errors...
INFO:hf-to-gguf:Loading model: jina-embeddings-v3
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:gguf: loading model part 'model.safetensors'
Traceback (most recent call last):
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 4474, in <module>
    main()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 4468, in main
    model_instance.write()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 477, in write
    self.prepare_tensors()
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 341, in prepare_tensors
    for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 2772, in modify_tensors
    return super().modify_tensors(data_torch, name, bid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 2631, in modify_tensors
    return [(self.map_tensor_name(name), data_torch)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf_2.py", line 258, in map_tensor_name
    raise ValueError(f"Can not map tensor {name!r}")
ValueError: Can not map tensor 'emb_ln.bias'

**Comment by xixia123** [comment]
> Encountering a similar issue when trying to convert jinaai/jina-embeddings-v3 to gguf: python3.12 convert_hf_to_gguf.py --outtype f32 ./models/jina-embeddings-v3 --outfile ./models/jina-embeddings-v3.gguf Error: INFO:hf-to-gguf:Loading model: jina-embeddings-v3 INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only INFO:hf-to-gguf:Exporting model... INFO:hf-to-gguf:gguf: loading model part 'model.safetensors' INFO:hf-to-gguf:token_embd_norm.bias, torch.bfloat16 --> F32, shape = {1024} INFO:hf-to-gguf:token_embd_norm.weight, torch.bfloat16 --> F32, shape = {1024} Traceback (most recent call last): File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 4430, in main() File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 4424, in main model_instance.write() File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 433, in write self.prepare_tensors() File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 297, in prepare_tensors for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 2728, in modify_tensors return super().modify_tensors(data_torch, name, bid) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 2587, in modify_tensors return [(self.map_tensor_name(name), data_torch)] ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Antonio\llama.cpp\convert_hf_to_gguf.py", line 213, in map_tensor_name raise ValueError(f"Can not map tensor {name!r}") ValueError: Can not map tensor 'embeddings.token_type_embeddings.parametrizations.weight.0.lora_A'
> 
> Glad for any help!

The same question

**Comment by alainlizotte** [comment]
Someone sucessfully converted jina-embeddings-v3 to GGUF ?

I'm getting this error too :(

ValueError: Can not map tensor 'embeddings.token_type_embeddings.parametrizations.weight.0.lora_A'

First time trying to convert a model, since this one is not yet available for Ollama.

**Comment by nopmop** [comment]
Here are some tools useful for model inspection after conversion:

https://github.com/nopmop/tensor_tools_gguf
