### ISSUE TITLE
Bug: Phi-3 Tokenizer Adds Whitespaces on re-tokenization (which invalidates KV-cache)

### ISSUE THREAD

**Issue by Harsha-Nori** [ggerganov/llama.cpp#7938]
### What happened?

The llama.cpp tokenizer for Phi-3 has odd behavior, where re-tokenizing the same text over and over keeps adding whitespaces to the first non-BOS token. This has several issues:

1. It doesn't match the original tokenizer behavior from Huggingface `Transformers`
2. Re-processing the same text causes the kv-cache to be invalidated, forcing another prompt fill of all the input tokens.

I maintain the Guidance library (https://github.com/guidance-ai/guidance), where we often need to re-tokenize inputs after adding any templated/deterministic text from the user. This is causing a significant performance regression in Phi-3 usage via llama.cpp on guidance whenever we go through this cycle :(. I believe pretty much all constrained generation libraries would likely affected by this too.

Here's an example of the bug in action (using the llama-cpp-python bindings, which are very thin wrappers on the tokenizer)

The model I'm using: https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/blob/main/Phi-3-mini-4k-instruct-q4.gguf

```python
import llama_cpp
print(llama_cpp.__version__) # '0.2.78' -- filing here because it seems like it's a lower level bug in llama.cpp

model = llama_cpp.Llama(model_path="Phi-3-mini-4k-instruct-q4.gguf", logits_all=True)
tokenizer = llama_cpp.LlamaTokenizer(model)

test_str = "Hi I am a hippo"
test_tokens = tokenizer.tokenize(test_str.encode("utf-8")) # [1, 6324, 306, 626, 263, 7251, 9759]

retokenized = b''.join([tokenizer.detokenize([i]) for i in test_tokens]) # b' Hi I am a hippo'
retokenized_tokens = tokenizer.tokenize(retokenized) # [1, 29871, 6324, 306, 626, 263, 7251, 9759]

retokenized2 = b''.join([tokenizer.detokenize([i]) for i in retokenized_tokens]) # b'  Hi I am a hippo'
```

Note how the token at index `1` has a continually growing whitespace when going through the tokenize/detokenize cycle. Repeating this process continuously increases the whitespace (

`"   Hi I am a hippo"` -> 
`"    Hi I am a hippo"` -> 
`"     Hi I am a hippo"` ->
`"      Hi I am a hippo"` ...

This is the heart of the issue, and doesn't happen with the original tokenizer implementation in Transformers. 

### Name and Version

llama-cpp-python is using this commit for their latest release: ggerganov/llama.cpp@fd5ea0f897ecb3659d6c269ef6f3d833e865ead7

### What operating system are you seeing the problem on?

Linux, Mac, Windows

**Comment by riedgar-ms** [comment]
I think that this is happening on tokenisation - if I try to tokenise a single space `' '` I'm getting back token 259 (when using 'mistral-7b-instruct-v0.2.Q8_0.gguf' specifically), but that's a _double_ space.

**Comment by riedgar-ms** [comment]
I believe this is the same issue I've raised in:
https://github.com/abetlen/llama-cpp-python/issues/1531

**Comment by riedgar-ms** [comment]
We have a work around, based on prepending a known byte which is rather unlikely to appear in a real string or token.

**Comment by cmp-nct** [comment]
Just stumbled into this error.
@riedgar-ms correctly pointed out that a single space is wrongly encoded as double space
`<|assistant|> `
```
32001 -> '<|assistant|>'
   259 -> '  '
```

Also `<|assistant|>\n` is bizzarely tokenized:
```
29871 -> ' '
    13 -> '
'
```

29871 IS actually the single whitespace, but it had no place there..

I stumbled upon that issue because phi3 generates unexpected whitespaces at the begin of the response.
The template is supposed to end with `<|assistant|>`, the response in 80-90% of all cases starts with a whitespace.
I tried to compensate that by adding a whitespace myself, this triggered the double-space tokenization error and phi3 added another whitespace.
Phi3 is quite adamant, when asking it to write a single `#` it response with ` #` as a single token, that looks like a deeper fine tune issue to me.. The model seems aware that ` #` has a whitespace at the start, despite being a single token, it REALLY wants to use whitespaces to start.

**Comment by cmp-nct** [comment]
> If I'm not mistaken the reason for the prefix is because most models don't interpret the initial token correctly, so this was used to pad it. The value of the first token shouldn't matter so long as the model was trained to ignore it. Shouldn't being the key word there as I've never actually tested it.
> 
> [GPT2 always has largest attention on first token?](https://github.com/huggingface/transformers/issues/2975)

There is a lot more than that going on. whitespace prefixes are added to all tokens after any special tokens - if none are present already.
In addition newline tokens get removed if they come after special tokens.
So there is a lot of modifications going on in the python tokenizer, I doubt that most original developers know about that actually.
If you look at some fine tunes, they use newlines after special tokens. However the python tokenizer would just remove those newlines

**Comment by JhonDan1999** [comment]
> > If I'm not mistaken the reason for the prefix is because most models don't interpret the initial token correctly, so this was used to pad it. The value of the first token shouldn't matter so long as the model was trained to ignore it. Shouldn't being the key word there as I've never actually tested it.
> > [GPT2 always has largest attention on first token?](https://github.com/huggingface/transformers/issues/2975)
> 
> There is a lot more than that going on. whitespace prefixes are added to all tokens after any special tokens - if none are present already. In addition newline tokens get removed if they come after special tokens. So there is a lot of modifications going on in the python tokenizer, I doubt that most original developers know about that actually. If you look at some fine tunes, they use newlines after special tokens. However the python tokenizer would just remove those newlines

@cmp-nct What you describe is exactly the issue I'm facing 


When I feed a text block that contains new lines into the Phi-3 tokeniser, the new lines are removed after decoding. Here is an example of the text I am working with:
Input Text to the tokenizer:
<|system|>
You are a helpful assistant.<|end|>
<|user|>
How to explain Internet for a medieval knight?<|end|>
<|assistant|> 


after tokenizer.decode I got this:

<|system|>
You are a helpful assistant.<|end|><|user|>
How to explain Internet for a medieval knight?<|end|><|assistant|> 





Can you help me with this issue and is it affecting the performance of the model if I proceed with this ?
