### ISSUE TITLE
Refactor: GGUF my Repo tool on HF needs its scripts updated with the new naming scheme

### ISSUE THREAD

**Issue by Nexesenex** [ggerganov/llama.cpp#7962]
### Background Description

![Screenshot 2024-06-16 at 20-51-51 GGUF My Repo - a Hugg](https://github.com/ggerganov/llama.cpp/assets/124105151/9d853b81-8c43-4520-b8c9-f60a1f9c7299)

On HF, GGUF my Repo scripts seem to currently use the old one, and LlamaCPP probably got updated, leaving the whole tool broken.

### Possible Refactor Approaches

Use the new llama.cpp naming scheme in the scripts.

**Comment by MikeStone66** [comment]
Looks like all of the AutoQuant, Autogguf, etc notebooks on colab
