### ISSUE TITLE
Facing issue while converting finetune LLaVA Mistral model to gguf

### ISSUE THREAD

**Issue by INZA111** [ggerganov/llama.cpp#7963]
Hello,I have trained the LLaVA Mistral model on my own dataset, and my model was successfully converted to GGUF. However, I am facing the following issue:
**lama_model_load: error loading model: check_tensor_dims: tensor 'token_embd.weight' has wrong shape; expected  4096, 32000, got   128,  1024,     1,     1**
I have also tried to convert the model **liuhaotian/llava-v1.6-mistral-7b** and did not face any issues with it.
![Screenshot 2024-06-17 003522](https://github.com/ggerganov/llama.cpp/assets/62800000/460d9c59-ecdd-4ad2-9996-7b5cb249bd89)

**Comment by dand-milestone** [comment]
I'm facing a similar issue. Could you please shed light on how you converted the model to .gguf?

**Comment by lyp-liu** [comment]
Excuse me, have you solved this problem？
