### ISSUE TITLE
Bug: Server not support mmproj

### ISSUE THREAD

**Issue by lld1995** [ggerganov/llama.cpp#7988]
### What happened?

I use Yi-VL-6B,and i run it with `./server -m /data/model_data/Yi-VL-6B-GGUF/ggml-model-f16.gguf --n-gpu-layers 4096 -n 384 -c 2048 --host 0.0.0.0 --port 8897 --mmproj /data/model_data/Yi-VL-6B-GGUF/mmproj-model-f16.gguf`

But when i upload image on web, it shows 
![image](https://github.com/ggerganov/llama.cpp/assets/17978390/a66fded3-5676-44a2-98e6-cc22454df692)

### Name and Version

/data/llama.cpp/build/bin$ ./server --version
version: 3137 (dcf75270)
built with cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0 for x86_64-linux-gnu

**Comment by ngxson** [comment]
For now, server does not support vision model

**Comment by ngxson** [comment]
@lld1995 The mentioned project is **not** maintained by llama.cpp, so I cannot answer your question.
