### ISSUE TITLE
Feature Request: Support for Meta Chameleon 7B and 34B

### ISSUE THREAD

**Issue by arch-btw** [ggerganov/llama.cpp#7995]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

> "Meta Chameleon is a family of models that can combine text and images as input and output any combination of text and images with a single unified architecture for both encoding and decoding. While most current late-fusion models use diffusion-based learning, Meta Chameleon uses tokenization for text and images. This enables a more unified approach and makes the model easier to design, maintain, and scale. The possibilities are endless—imagine generating creative captions for images or using a mix of text prompts and images to create an entirely new scene."

### Motivation

This would be a great addition to llama.cpp!

The image features look interesting but it can also simply do Text -> Text and a lot of other combinations:

- Text -> Text
- Image -> Image
- Text -> Image
- Image -> Text
- Image -> Text + Image
- Text + Image -> Text
- Text -> Text + Image
- Text + Image -> Text + Image

https://github.com/ggerganov/llama.cpp/assets/57669023/23e92f5a-e782-4bb7-ab66-c20fe113d514

**Comment by EliEron** [comment]
Here are some relevant links:

- [Paper](https://arxiv.org/abs/2405.09818)
- [Blog Post](https://ai.meta.com/blog/meta-fair-research-new-releases/)
- [Code](https://github.com/facebookresearch/chameleon)
- [HuggingFace](https://huggingface.co/facebook/chameleon) (Not Live Yet)

Given it's a completely new architecture, and a multimodal one at that, I image adding support for it will not be easy. But I'm also very excited to see this supported.

**Comment by 0wwafa** [comment]
Yes! Please do! Also because as of now there is no way to run it on CPU only.

**Comment by SolvAI** [comment]
yum yum yum :p

**Comment by ann-brown** [comment]
Since it uses similar to Medusa architecture is that likely to be supportable at the same time for the self-speculative decoding side of inference? It sounded like it could run without that, but it'd be neat to have that available too.

**Comment by jacobkahn** [comment]
Let me know if we can answer any questions about the architecture, inference, etc. Our reference implementation in https://github.com/facebookresearch/chameleon should be clear. Differences from the Llama architecture are minor:
- [qk-norm](https://github.com/facebookresearch/chameleon/blob/7a72f40aa5f462965c8374f25257f55b65b25ff4/chameleon/inference/transformer.py#L71-L74) in attention [after the initial qk weight transformations](https://github.com/facebookresearch/chameleon/blob/7a72f40aa5f462965c8374f25257f55b65b25ff4/chameleon/inference/transformer.py#L119-L123)
- [swin-norm](https://github.com/facebookresearch/chameleon/blob/7a72f40aa5f462965c8374f25257f55b65b25ff4/chameleon/inference/transformer.py#L267-L276) (in the 30B model only) which is normalizes inputs before attention and feedforward blocks

**Comment by typedrat** [comment]
Considering the VQGAN is public, it should be possible for `llama.cpp` to reinstate the image output capabilities.

**Comment by chigkim** [comment]
+1000! I'd love to run Chameleon with llama.cpp!

**Comment by freeqaz** [comment]
In the interim: Is anybody aware of any quantized weights for this model currently? Would love to try to 30b version on my 2x 3090s.

Found this issue because I know llama.cpp is a common way to shrink these models down.

**Comment by chigkim** [comment]
Still not supported.

**Comment by rootAvish** [comment]
I'd read this paper when it had come out and found its ideas quite interesting, going to try implementing the changes required to support the text-to-text version of 7B to get the ball rolling on this (found this issue in a thread on r/localLLama mentioning this isn't supported yet).

Leaving this comment to check in case anybody's already on it (and looking for help), happy to collaborate rather than duplicating effort.

**Comment by arch-btw** [comment]
Hi guys, it got merged: https://github.com/ggerganov/llama.cpp/pull/8543

**Comment by chigkim** [comment]
> Hi guys, it got merged: #8543

The pr is only for text, not image right?
