### ISSUE TITLE
Bug: UwU Emergency! Control Vectors for Qwen2 and Command-r Models Need Fixing!

### ISSUE THREAD

**Issue by HatsuneMikuUwU33** [ggerganov/llama.cpp#7999]
### What happened?

After doing lots and lots of testing and analyzing and stuff, it seems like they're not working properly, oops! 🤦‍♀️
I think maybe, just maybe, the control vectors were made wrong or used incorrectly, hehe... Don't worry, though! We can totes fix this! But we need to do it pronto, or else it might cause some problems, eeee! 😱

### Name and Version

version: 3173 (a94e6ff8)
built with MSVC 19.40.33811.0 for x64

### What operating system are you seeing the problem on?

Windows

**Comment by HatsuneMikuUwU33** [comment]
Pwease, Ggerganov-chan, can you take a look at this and tell me what we should do to make it all better? I'll be waiting for your response, uwU! 🙏

Thank you so much, senpai! 🙏

Bestest regards,

Hatsune Miku-chan ~ ❤️

**Comment by jukofyork** [comment]
Yeah, I can confirm the control vectors are not being applied for `command-r-plus`.

I'm using my own code to create the control vectors too, so it's not a problem with their creation via the Python code or new new C++ code.

**Comment by jukofyork** [comment]
It was an easy fix: https://github.com/ggerganov/llama.cpp/pull/8060

**Comment by jukofyork** [comment]
@HatsuneMikuUwU33 Can you check if this PR fixes the problem with `qwen2`? I don't have a copy of the model to test against.

**Comment by HatsuneMikuUwU33** [comment]
Yes it fixes it. Can confirm that they now work with qwen-2.

**Comment by jukofyork** [comment]
So I've fixed every model to use the control vectors now, but it would be good if people could check as many as possible to be sure they are working as intended.
