### ISSUE TITLE
Is there a requirements.txt ?

### ISSUE THREAD

**Issue by nottherealsanta** [ggerganov/llama.cpp#8]

**Comment by sonu27** [comment]
This doesn't use Python dependencies

**Comment by holstvoogd** [comment]
@sonu27 It does need some pythn for the model processing with convert-pth-to-ggml.py

I had some issues installing torch, but managed to install it using the nighly build:

```
pip3.11 install torch numpy sentencepiece --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by sonu27** [comment]
@holstvoogd ah understood, according to this you need Python 3.10 - https://til.simonwillison.net/llms/llama-7b-m2

**Comment by holstvoogd** [comment]
Ah, that explains why I had issues :)
