### ISSUE TITLE
Do you guys mind making an updater for llama.cpp?

### ISSUE THREAD

**Issue by Shreyas-ITB** [ggerganov/llama.cpp#800]
Basically when you guys release a new version of llama.cpp the updater will ask a prompt to you saying there is a new update available (that will be fetched from github commits) and it will ask you if it can update the files for you, if you say yes then it will fetch the **Changed/previously edited files** from github and replace it with your local llama files.

This came to my mind because llama.cpp has become a big project now. You guys are updating the project every single day which is awesome but it makes the people replace the files on their own every single day. That might be annoying.

**Comment by bakkot** [comment]
What's wrong with `git pull`?

**Comment by Shreyas-ITB** [comment]
oh lol i forgot that command exists my bad sorry guys
