### ISSUE TITLE
我想convert一个比较大的模型时报错Unable to allocate 1.96 GiB for an array with shape (128256, 8192) and data type float16如何解决

### ISSUE THREAD

**Issue by zhaoyuchen1128** [ggerganov/llama.cpp#8030]
### What happened?

模型有141G

### Name and Version

latest

**Comment by MightyStud** [comment]
Looks like classic OOM (out-of-memory) error, I'd advise using smaller model or more quantized model. Without much context, it is hard to tell the issue.
