### ISSUE TITLE
Tag b3187 Windows ARM binary release without "main.exe"

### ISSUE THREAD

**Issue by Billzhong2022** [ggerganov/llama.cpp#8045]
### What happened?

In release tag https://github.com/ggerganov/llama.cpp/releases/tag/b3187, binary file "llama-b3187-bin-win-llvm-arm64.zip" and "llama-b3187-bin-win-msvc-arm64.zip" don't have "main.exe". What is the reason? Do you have plan to replease "main.exe" as well? 

### Name and Version

Tag b3187

### Relevant log output

```shell
N/A
```

**Comment by slaren** [comment]
It has been renamed to `llama-cli.exe`.
