### ISSUE TITLE
Bug: brew install on a Mac

### ISSUE THREAD

**Issue by mneedham** [ggerganov/llama.cpp#8065]
### What happened?

I've previous had llama.cpp installed via brew and it worked fine, but somehow today I've broken it. It throws this error:

```
illegal hardware instruction 
```

My suspicion is that it hasn't been installed for the arm64 architecture somehow.

### Name and Version

 llama-server --version
[1]    19222 illegal hardware instruction  llama-cli --version

### What operating system are you seeing the problem on?

Mac Sonama 14.4.1

### Relevant log output

```shell
$ whereis llama-server
llama-server: /usr/local/bin/llama-server

$ file /usr/local/bin/llama-server
/usr/local/bin/llama-server: Mach-O 64-bit executable x86_64

$ llama-server langchain-llamacpp/downloads/MaziyarPanahi_Mistral-7B-Instruct-v0.3-GGUF_f_Q4_K_M/Mistral-7B-Instruct-v0.3.Q4_K_M.gguf
[1]    17507 illegal hardware instruction  llama-server
```

**Comment by jmtatsch** [comment]
Just tried this on my m1 MacBookPro and worked flawlessly.
