### ISSUE TITLE
Bug: ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 137438953504

### ISSUE THREAD

**Issue by idekel** [ggerganov/llama.cpp#8101]
### What happened?

I'm working on a project with llama.cpp to process a bunch of text files and I'm trying to use multi processing to speed up, so I'm loading the model and context in a child process for each file, launching 10 children at a time but some times one the child process would fail to create the context with the following error:

`llama_new_context_with_model: n_ctx      = 1048576
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 2804339712.0
llama_new_context_with_model: freq_scale = 1
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 137438953504
llama_kv_cache_init: failed to allocate buffer for kv cache
llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache`

Isn't 137438953504 bytes way too much memory to try to allocate. If I run the files one by one without using child processes it work fine but it takes way to much time.

I'm running it in a linux server with 32 vCPU and 128 Gib of ram.

### Name and Version

version: 3184 (9c77ec1d)
built with cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
llama_new_context_with_model: n_ctx      = 1048576
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 2804339712.0
llama_new_context_with_model: freq_scale = 1
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 137438953504
llama_kv_cache_init: failed to allocate buffer for kv cache
llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
```

**Comment by slaren** [comment]
128GB for a context size of 1048576 is expected. Use a lower context size, or try KV quantization.

**Comment by idekel** [comment]
Thanks. That was it!

**Comment by verceliun** [comment]
but how can i adjust context size?? 

i get :
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 38654705664
alloc_tensor_range: failed to allocate CPU buffer of size 38654705664
llama_init_from_model: failed to initialize the context: failed to allocate buffer for kv cache
common_init_result: failed to create context with model 'Qwen3VL-8B-Instruct-Q4_K_M.gguf'
common_init_from_params: failed to create context with model 'Qwen3VL-8B-Instruct-Q4_K_M.gguf'

i use this line to run server:
.\llama.cpp\llama-server.exe -m .\Models\Qwen3VL-8B-Instruct-Q4_K_M.gguf --port 8080 --mmproj .\Models\mmproj-Qwen3VL-8B-Instruct-F16.gguf
