### ISSUE TITLE
sh: 1: ./llama.cpp/llama-quantize: not found

### ISSUE THREAD

**Issue by RakshitAralimatti** [ggerganov/llama.cpp#8107]
### What happened?

For converting the FP16.gguf to q5_k_m for llama3 i was getting the error **sh: 1: ./llama.cpp/llama-quantize: not found** previously i used **os.system("./llama.cpp/llama-quantize " + gguf_dir + "/" + gguf_F16_name + " " + model_path + " " + m)** in my script to convert even that is not working now its giving the same not found issue

### Name and Version

Lastest pervsion

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
bash: ./llama.cpp/quantize: No such file or directory
```

**Comment by ggerganov** [comment]
The tool has been renamed from `quantize` to `llama-quantize`

**Comment by RakshitAralimatti** [comment]
Thanks for your response.
Now its working

**Comment by elliotthwang** [comment]
@ggerganov 
llama-quantize: failed to access

showed the message as follows;
/bin/bash: line 1: ./llama.cpp/llama-quantize: No such file or directory

**Comment by ggerganov** [comment]
Run `make` first

**Comment by elliotthwang** [comment]
@ggerganov 
Run make as follows：

# Install llama.cpp
!git clone https://github.com/ggerganov/llama.cpp
!cd llama.cpp && git pull && make clean && LLAMA_CUBLAS=1 make
!pip install -r llama.cpp/requirements.txt

Is it coming correctly?
