### ISSUE TITLE
[Enhancement]: Implement optimizations used in CTranslate2

### ISSUE THREAD

**Issue by janekb04** [ggerganov/llama.cpp#811]
[CTranslate2](https://github.com/OpenNMT/CTranslate2) is a "competitor" to llama.cpp that advertises itself with:
> ### Fast and efficient execution on CPU and GPU
> The execution [is significantly faster and requires less resources](https://github.com/ggerganov/llama.cpp/issues/new?assignees=&labels=&template=custom.md&title=%5BUser%5D+Insert+summary+of+your+issue+or+enhancement..#benchmarks) than general-purpose deep learning frameworks on supported models and tasks thanks to many advanced optimizations: layer fusion, padding removal, batch reordering, in-place operations, caching mechanism, etc.

I am no expert in LLMs and I don't know what these optimizations are, but I am asking: would it be possible/feasible and/or desirable to implement these optimizations into llama.cpp or GGML?

**Comment by guillaumekln** [comment]
(Hi there, I'm the author of CTranslate2.)

llama.cpp already implements similar optimizations. They often come naturally when reimplementing a model in C/C++.

In my experience the most impactful optimization is to integrate vendor specific libraries to run the matrix multiplications, which are usually the bottlenecks for these models. For example Apple Accelerate was a huge win for performance when it was first integrated in whisper.cpp. For x64 processors, I recommend [oneDNN](https://github.com/oneapi-src/oneDNN) which has a very good 8-bit GEMM implementation (as fast as Intel MKL).

However, I'm not aware of similar libraries providing efficient 4-bit GEMM at this time, and I also understand that llama.cpp is trying to avoid additional dependencies as much as possible.

**Comment by jon-chuang** [comment]
So we are already fusing and tiling the attention layer to fit in CPU-SRAM ala flash attention?
