### ISSUE TITLE
Feature Request: Provide means to quantify the restriction of RAM/VRAM usage for each GPU and system RAM.

### ISSUE THREAD

**Issue by ghchris2021** [ggerganov/llama.cpp#8113]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Feature Request: Provide means to quantify the restriction of RAM/VRAM usage for each GPU and system RAM.

It would be nice to for instance be able to say "use 90% of GPU0 VRAM", or "use up to 7GBy VRAM on GPU0" or "leave at least 1GBy VRAM unused on GPU0" or similar.

If the code doesn't have good ability to assess the free/available VRAM on a GPU then being able to speak of use margins as either percentage of or absolute size in GBy of VRAM to use / not use would be much more convenient and "auto scaling" than "layers" since the "layer count" that fits will depend on the model as well as other parameters so one can't easily translate that into "GBy".

Also if the system is going to try to estimate the amount of free VRAM and fails with an over-allocation related allocation error then it'd be possible to retry that with a progressively lower allocation request until it fits and continue on normally.

### Motivation

I've experienced cases where the current code in inference mode using NGL=99 or in RPC-mode attempts to use more VRAM than is available and fails to run.

**Comment by Azeirah** [comment]
I think this is sensible!
