### ISSUE TITLE
Bug: error loading model: llama_model_loader: failed to load model

### ISSUE THREAD

**Issue by Smupk2778** [ggerganov/llama.cpp#8154]
### What happened?

I have build the llama-cpp on my AIX machine which is big-endian.
But while  running the model using command:
`./llama-cli --verbosity 5 -m models/7B/ggml-model-Q4_K_M.gguf -n 128`

I am getting this error:-
```
Log start
main: build = 3212 (8cb508d0)
main: built with gcc (GCC) 10.3.0 for powerpc-ibm-aix7.2.0.0
main: seed  = 1719470130
llama_model_load: error loading model: llama_model_loader: failed to load model from models/7B/ggml-model-Q4_K_M.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/7B/ggml-model-Q4_K_M.gguf'
main: error: unable to load model
```

Is there any problem with endianness or any other issue is there??

I want this model and other 7B/13B models to run in my aix machine .

### Name and Version

```
# ./llama-cli --version 
version: 3212 (8cb508d0)
built with gcc (GCC) 10.3.0 for powerpc-ibm-aix7.2.0.0
```

### What operating system are you seeing the problem on?

Other? (Please let us know in description)
AIX-7.2

**Comment by Smupk2778** [comment]
Is there any solution to it please reply, someone.

**Comment by ggerganov** [comment]
You need a big endian model - use the `--bigendian` argument of `convert_hf_to_gguf.py` to create one:

https://github.com/ggerganov/llama.cpp/blob/975524bc0da7acf99bda7616636b5585fc5287d5/convert_hf_to_gguf.py#L3423-L3426
