### ISSUE TITLE
Feature Request: Why is there no pre-compiled Windows version of AMD ROCm? 

### ISSUE THREAD

**Issue by wangzi7654321** [ggerganov/llama.cpp#8169]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Feature Request: Why is there no pre-compiled Windows version of AMD ROCm? b3248

### Motivation

Some users' computers are unable to compile llama.cpp

**Comment by henk717** [comment]
If it helps the KoboldCpp ROCm versions are precompiled for Windows : https://github.com/YellowRoseCx/koboldcpp-rocm/releases
May carry you over until official binaries are provided.
