### ISSUE TITLE
Refactor: gemma 9b not work with lama.cpp b3259

### ISSUE THREAD

**Issue by werruww** [ggerganov/llama.cpp#8214]
### Background Description

gemma 9b not work

lama.cpp b3259
pip install git+https://github.com/ggerganov/llama.cpp.git@b3259

llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'gemma2'
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
File "C:\Users\m\Desktop\ollama\1.py", line 4, in
llm = Llama(
^^^^^^
File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 358, in init
self._model = self._stack.enter_context(contextlib.closing(_LlamaModel(
^^^^^^^^^^^^
File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp_internals.py", line 54, in init
raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: ./gemma-2-9b-it.Q4_K.gguf

### Possible Refactor Approaches

gemma 9b not work

lama.cpp b3259
pip install git+https://github.com/ggerganov/llama.cpp.git@b3259

llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'gemma2'
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
File "C:\Users\m\Desktop\ollama\1.py", line 4, in
llm = Llama(
^^^^^^
File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 358, in init
self._model = self._stack.enter_context(contextlib.closing(_LlamaModel(
^^^^^^^^^^^^
File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp_internals.py", line 54, in init
raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: ./gemma-2-9b-it.Q4_K.gguf

**Comment by werruww** [comment]
from llama_cpp import Llama


llm = Llama(
  model_path="./gemma-2-9b-it.Q4_K.gguf",  # path to GGUF file
  n_ctx=4096,  # The max sequence length to use - note that longer sequence lengths require much more resources
  n_threads=4, # The number of CPU threads to use, tailor to your system and the resulting performance
  n_gpu_layers=0, # The number of layers to offload to GPU, if you have GPU acceleration available. Set to 0 if no GPU acceleration is available on your system.
)

prompt = "write the python code to create text file"

# Simple inference example
output = llm(
  f"<|user|>\n{prompt}<|end|>\n<|assistant|>",
  max_tokens=256,  # Generate up to 256 tokens
  stop=["<|end|>"], 
  echo=True,  # Whether to echo the prompt
)

print(output['choices'][0]['text'])

**Comment by werruww** [comment]
gemma-2-9b-it.Q4_K.gguf


run on ollama and lmststudio-0.2.26

**Comment by 0wwafa** [comment]
> pip install git+https://github.com/ggerganov/llama.cpp.git@b3259

??? this can't work... I don't understand

```
Collecting git+https://github.com/ggerganov/llama.cpp.git@b3259
  Cloning https://github.com/ggerganov/llama.cpp.git (to revision b3259) to /tmp/pip-req-build-78oo9swv
  Running command git clone --filter=blob:none --quiet https://github.com/ggerganov/llama.cpp.git /tmp/pip-req-build-78oo9swv
  Running command git checkout -q e57dc62057d41211ac018056c19c02cd544694df
  Resolved https://github.com/ggerganov/llama.cpp.git to commit e57dc62057d41211ac018056c19c02cd544694df
  Running command git submodule update --init --recursive -q
ERROR: git+https://github.com/ggerganov/llama.cpp.git@b3259 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by werruww** [comment]
how to run b3265

**Comment by werruww** [comment]
The directory name is invalid.

(b) C:\Users\m\Desktop\ollama\llama.cpp>cd examples/chat-13B.sh
The directory name is invalid.

(b) C:\Users\m\Desktop\ollama\llama.cpp>cd examples

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples>chat-13B.sh

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples>cd..

(b) C:\Users\m\Desktop\ollama\llama.cpp>cd llama-cli
The system cannot find the path specified.

(b) C:\Users\m\Desktop\ollama\llama.cpp>cd search-ms:displayname=Search%20Results%20in%20llama.cpp&crumb=location:C%3A%5CUsers%5Cm%5CDesktop%5Collama%5Cllama.cpp\main
The system cannot find the path specified.
'crumb' is not recognized as an internal or external command,
operable program or batch file.

(b) C:\Users\m\Desktop\ollama\llama.cpp>cd C:\Users\m\Desktop\ollama\llama.cpp\examples\main

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples\main>main -m gemma-2-9b-it.Q4_K.gguf -n 128
'main' is not recognized as an internal or external command,
operable program or batch file.

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples\main>gemma-2-9b-it.Q4_K.gguf -n 128
'gemma-2-9b-it.Q4_K.gguf' is not recognized as an internal or external command,
operable program or batch file.

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples\main>python  -m gemma-2-9b-it.Q4_K.gguf -n 128
C:\Users\m\AppData\Local\anaconda3\envs\b\python.exe: Error while finding module specification for 'gemma-2-9b-it.Q4_K.gguf' (ModuleNotFoundError: No module named 'gemma-2-9b-it')

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples\main>cd..

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples>.\main -m gemma-2-9b-it.Q4_K.gguf -n 128
'.\main' is not recognized as an internal or external command,
operable program or batch file.

(b) C:\Users\m\Desktop\ollama\llama.cpp\examples>cd C:\Users\m\Desktop\ollama\llama.cpp\scripts

(b) C:\Users\m\Desktop\ollama\llama.cpp\scripts>ci-run.sh

(b) C:\Users\m\Desktop\ollama\llama.cpp\scripts>ci-run
'ci-run' is not recognized as an internal or external command,
operable program or batch file.

(b) C:\Users\m\Desktop\ollama\llama.cpp\scripts>

**Comment by 0wwafa** [comment]
> how to run b3265

for example:
`.\build\bin\llama-server.exe -c 8192 -m ..\models\Mistral-7b-Instruct-v0.3.f16.q6_k.gguf -t 6`

**Comment by werruww** [comment]
It worked well, thank you[0wwafa](https://github.com/0wwafa)
![Untit2led](https://github.com/ggerganov/llama.cpp/assets/157249411/9144e374-71e8-4c67-b2cb-5b0b2fbaa301)
![Untitled](https://github.com/ggerganov/llama.cpp/assets/157249411/4ff949c9-2504-497e-bc96-92d372bd3e80)

llama-server.exe -c 8192 -m ..\gemma-2-9b-it.IQ1_S.gguf -t 6

http://127.0.0.1:8080/

**Comment by werruww** [comment]
Can this code be run with

from llama_cpp import Llama

llm = Llama(
    model_path="./gemma-2-9b-it.IQ1_S.gguf",  # Path to GGML model file
    n_ctx=4096,  # Maximum sequence length
    n_threads=4,  # Number of CPU threads 
    n_gpu_layers=0,  # Number of GPU layers (set to 0 if no GPU)
)

prompt = "Write Python code to create a text file."

output = llm(
    f"<|user|>\n{prompt}<|end|>\n<|assistant|>",
    max_tokens=256,
    stop=["<|end|>"],
    echo=True,
)

print(output['choices'][0]['text'])

**Comment by werruww** [comment]
pip install git+https://github.com/ggerganov/llama.cpp.git@b3259
An error is given

(b) C:\Users\m\Desktop\1>pip install git+https://github.com/ggerganov/llama.cpp.git@b3259
Collecting git+https://github.com/ggerganov/llama.cpp.git@b3259
  Cloning https://github.com/ggerganov/llama.cpp.git (to revision b3259) to c:\users\m\appdata\local\temp\pip-req-build-gyv1zjmw
  Running command git clone --filter=blob:none --quiet https://github.com/ggerganov/llama.cpp.git 'C:\Users\m\AppData\Local\Temp\pip-req-build-gyv1zjmw'
  Running command git checkout -q e57dc62057d41211ac018056c19c02cd544694df
  Resolved https://github.com/ggerganov/llama.cpp.git to commit e57dc62057d41211ac018056c19c02cd544694df
  Running command git submodule update --init --recursive -q
ERROR: git+https://github.com/ggerganov/llama.cpp.git@b3259 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

(b) C:\Users\m\Desktop\1>

**Comment by werruww** [comment]
>>> from llama_cpp import Llama
>>>
>>> llm = Llama(
...     model_path="./gemma-2-9b-it.IQ1_S.gguf",  # Path to GGML model file
...     n_ctx=4096,  # Maximum sequence length
...     n_threads=4,  # Number of CPU threads
...     n_gpu_layers=0,  # Number of GPU layers (set to 0 if no GPU)
... )
llama_model_loader: loaded meta data with 29 key-value pairs and 464 tensors from ./gemma-2-9b-it.IQ1_S.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma2
llama_model_loader: - kv   1:                               general.name str              = gemma-2-9b-it
llama_model_loader: - kv   2:                      gemma2.context_length u32              = 8192
llama_model_loader: - kv   3:                    gemma2.embedding_length u32              = 3584
llama_model_loader: - kv   4:                         gemma2.block_count u32              = 42
llama_model_loader: - kv   5:                 gemma2.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                gemma2.attention.head_count u32              = 16
llama_model_loader: - kv   7:             gemma2.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:    gemma2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                gemma2.attention.key_length u32              = 256
llama_model_loader: - kv  10:              gemma2.attention.value_length u32              = 256
llama_model_loader: - kv  11:                          general.file_type u32              = 24
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,256000]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  15:                      tokenizer.ggml.scores arr[f32,256000]  = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,256000]  = [3, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  19:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  21:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  22:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {{ bos_token }}{% if messages[0]['rol...
llama_model_loader: - kv  24:               general.quantization_version u32              = 2
llama_model_loader: - kv  25:                      quantize.imatrix.file str              = gemma-2-9b-it-IMat-GGUF/imatrix.dat
llama_model_loader: - kv  26:                   quantize.imatrix.dataset str              = gemma-2-9b-it-IMat-GGUF/imatrix.dataset
llama_model_loader: - kv  27:             quantize.imatrix.entries_count i32              = 294
llama_model_loader: - kv  28:              quantize.imatrix.chunks_count i32              = 128
llama_model_loader: - type  f32:  169 tensors
llama_model_loader: - type q2_K:   47 tensors
llama_model_loader: - type q5_K:    1 tensors
llama_model_loader: - type iq2_xxs:   42 tensors
llama_model_loader: - type iq1_s:  205 tensors
llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'gemma2'
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\m\AppData\Local\anaconda3\envs\b\Lib\site-packages\llama_cpp\llama.py", line 358, in __init__
    self._model = self._stack.enter_context(contextlib.closing(_LlamaModel(
                                                               ^^^^^^^^^^^^
  File "C:\Users\m\AppData\Local\anaconda3\envs\b\Lib\site-packages\llama_cpp\_internals.py", line 54, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: ./gemma-2-9b-it.IQ1_S.gguf
>>>
>>> prompt = "Write Python code to create a text file."
>>>
>>> output = llm(
...     f"<|user|>\n{prompt}<|end|>\n<|assistant|>",
...     max_tokens=256,
...     stop=["<|end|>"],
...     echo=True,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'llm' is not defined
>>>
>>> print(output['choices'][0]['text'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'output' is not defined
