### ISSUE TITLE
problem with the ggml files when using the docker images

### ISSUE THREAD

**Issue by dnalexen** [ggerganov/llama.cpp#826]
I have a problem with the ggml images when I use the docker image ghcr.io/ggerganov/llama.cpp:full. I am asked to regenerate your ggml files but I have already done that. See attached screenshot.
![Screenshot from 2023-04-07 08-47-47](https://user-images.githubusercontent.com/35671475/230561232-9056fb60-6886-4a1f-b8f3-b5c1b7a51d86.png)

**Comment by athrael-soju** [comment]
If your model is already quantized, then you don't need to use --all-in-one anymore.

something like this should work: 
```
docker run -v /home/ndjossou/Documents/llama_for_docker/models:/models ghcr.io/ggerganov/llama.cpp:light -m models/7B/your_model_name.bin -p "hello" -n 128
```
