### ISSUE TITLE
Bug: Model generating result sometimes but most of the times it doesnt 

### ISSUE THREAD

**Issue by akhilkapil** [ggerganov/llama.cpp#8269]
### What happened?

So, I am currently working with the local 'mistral-7b-q4' gguf model using 'llamacpp'. Although I can confirm that the model is active on the server but still I have encountered some issues during testing. Specifically, when I provide a small prompt , the model occasionally generates a response, but more often than not , it produces an empty string for the same prompt.

At this stage, I am unsure whether this behaviour is a result of the latest update, an expected characteristic of the model, or if there might be an error in my approach. 

This is how I am calling the model:

`

# Load LLM
llm = LlamaCpp(
    model_path="Models/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
    n_gpu_layers=-1,
    temperature=0.1,
    top_p=0.7,
    n_ctx=16000,
    max_tokens=4096,
    frequency_penalty=0.2,
    presence_penalty=0.5,
    stop=["\n"]
)`

these are the outputs I am getting. First one is without a response and second one is with the reponse. 
![MicrosoftTeams-image (2)](https://github.com/ggerganov/llama.cpp/assets/70738578/4cce310f-7792-440d-add7-00e971584e08)
![MicrosoftTeams-image (1)](https://github.com/ggerganov/llama.cpp/assets/70738578/2f3bb18b-8240-436e-9d97-48e6623f5bf6)

Specs:
![MicrosoftTeams-image (3)](https://github.com/ggerganov/llama.cpp/assets/70738578/8e076a4a-661f-4a80-afaf-f50d4a4fd18b)

Used this command to install llama:
`CMAKE_ARGS="-DLLAMA_CUDA=on" FORCE_CMAKE=1 pip install llama-cpp-python`

earlier I was using this(bewlo) one but recently after new update I am facing issues in installation as `DLLAMA-CUBLAS` is depreciated and not supported anymore.
`CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python`

### Name and Version

llam_cpp_python: 0.2.81

### What operating system are you seeing the problem on?

Linux

**Comment by ngxson** [comment]
This issue is related to llama-cpp-python package, so you should raise an issue there instead: https://github.com/abetlen/llama-cpp-python.

Unless you confirm that the bug is reproducible with llama-cli or llama-server, this issue seems to be invalid.
