### ISSUE TITLE
Bug: Llama 3 8b giving different outputs for same input (temperature 0)

### ISSUE THREAD

**Issue by LiquidGunay** [ggerganov/llama.cpp#8274]
### What happened?

For certain prompts (not all), the llama 3 8b from bartowski (when hosted using server) will give one answer for the first query. If I repeat the query it will give a different answer. Then on subsequent repetitions it will give the same second answer. If I restart llama.cpp then I get the same behaviour of different response for the very first query. This behaviour only occurs when I split the model across GPUs. When the model is on a single GPU everything works fine.

### Name and Version

Version: 3286 (fadde671)
Ubuntu 11.4.0

### What operating system are you seeing the problem on?

Linux

**Comment by HanClinto** [comment]
What are the steps to reproduce? If this only happens with certain prompts, then those prompts (and seeds) would help in tracking down what you're seeing.

**Comment by dspasyuk** [comment]
@LiquidGunay would be nice to have a version of llama-cli --version, and command you are running, have you tried mixing CPU and GPU, so only offload lets say 50% of layers to GPU? Do you see the same behaviour?
