### ISSUE TITLE
Why is the single input used incorrect, or no output?

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ggerganov/llama.cpp#8276]
### What happened?

I'm using the old version because the new version cross-compiles and keeps getting errors，The specific questions are as follows:

If I use prompt input, it causes an error or doesn't output。like:

./bin/main2 -m ../../llama.cpp/build/modelGGUF/llama-2-7b-chat.Q4_0.gguf   --prompt "1+3=?"

![image](https://github.com/ggerganov/llama.cpp/assets/46549527/c6082a94-c7dd-443d-8133-0fe4618ba2e1)

./bin/main2 -m ../../llama.cpp/build/modelGGUF/llama-2-7b-chat.Q4_0.gguf   --prompt "1+1=?"
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/3f008130-47a8-4c7c-97b4-c218d57f41db)

### Name and Version

./bin/main2 -m ../../llama.cpp/build/modelGGUF/llama-2-7b-chat.Q4_0.gguf   --prompt "1+3=?"

**Comment by dspasyuk** [comment]
@QIANXUNZDL123 Things are changing so rapidly here do not use the old version try using the newest version possible.

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 Things are changing so rapidly here do not use the old version try using the newest version possible.

I also want to use the latest version but the latest version keeps getting errors in cross-compilation, causing me to only use the old version

**Comment by dspasyuk** [comment]
@QIANXUNZDL123 what are the errors you are getting? You can also use binaries for your system if you cannot compile.

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 what are the errors you are getting? You can also use binaries for your system if you cannot compile.

Sorry for the late reply，I've fixed the issue of cross-compilation, but I'm getting a new one，When I use imperative input, why is his reply so strange?  model: ./qwen2-1_5b-instruct-q8_0.gguf  

He replied to me with a lot of other things, but I just wanted the answers to the questions I typed，What parameters should I set to get the answer I want?

./bin/llama-cli  -m ./qwen2-1_5b-instruct-q8_0.gguf -p "中国的首都是哪一座城市？"  



![image](https://github.com/ggerganov/llama.cpp/assets/46549527/58c282a5-335d-4258-89e2-6588bf8a166c)

**Comment by dspasyuk** [comment]
@QIANXUNZDL123 As far as I know Qwen is using the Chatml template, so you will need to set --chat-template chatml

**Comment by dspasyuk** [comment]
@QIANXUNZDL123 Do you mean that it keeps on generating? Just use --temp 0 -n 120 --top-k 10  for example

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 Do you mean that it keeps on generating? Just use --temp 0 -n 120 --top-k 10 for example

I also set  ./bin/LLamaQW -m ./qwen2-1_5b-instruct-q8_0.gguf -p "中国的首都是哪一座城市？"  --chat-template chatml --temp 0.8 -n 120 --top-k 10    But there are still other answers.  eg:

![image](https://github.com/ggerganov/llama.cpp/assets/46549527/ff55d545-d3ee-4106-89b2-6918c0d1a38b)


If I use interactive mode, his output is correct and normal：
./bin/LLamaQW -m ./qwen2-1_5b-instruct-q8_0.gguf --chat-template chatml -cnv
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/d625be4f-4101-4ba4-aa04-224c002eadbf)

**Comment by dspasyuk** [comment]
@QIANXUNZDL123 as far as I know --chat-template is disabled in prompt mode  you can either use --in-prefix --in-suffix routine or format your prompt to look something like this:

<|im_start|>system
{system_message}<|im_end|>
<|im_start|>user
What is 2+2? <|im_end|>
<|im_start|>assistant

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 as far as I know --chat-template is disabled in prompt mode you can either use --in-prefix --in-suffix routine or format your prompt to look something like this:
> 
> ```
> <|im_start|>system
> {system_message}<|im_end|>
> <|im_start|>user
> What is 2+2? <|im_end|>
> <|im_start|>assistant 
> ```
> 
> That should help with quality too.

I also set --in-prefix --in-suffix , but the result is still the same,.....

**Comment by dspasyuk** [comment]
@QIANXUNZDL123   Here is my test using the model from here:  https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/blob/main/qwen2-7b-instruct-q2_k.gguf 
Using llama.cui here: https://github.com/dspasyuk/llama.cui 
[Screencast from 2024-07-10 10:04:06 AM.webm](https://github.com/ggerganov/llama.cpp/assets/34203011/adda161b-ee8d-45d6-ab31-a4b3f155cb79)
Llama.cui uses this settings: ../llama.cpp/llama-cli --model ../../models/qwen2-7b-instruct-q2_k.gguf --n-gpu-layers 25 -cnv  --simple-io  -b 2048 --ctx_size 0 --temp 0 --top_k 10 --multiline-input  --chat-template chatml --log-disable

**Comment by QIANXUNZDL123** [comment]
> @QIANXUNZDL123 Here is my test using the model from here: https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/blob/main/qwen2-7b-instruct-q2_k.gguf Using llama.cui here: https://github.com/dspasyuk/llama.cui [Screencast from 2024-07-10 10:04:06 AM.webm](https://github.com/ggerganov/llama.cpp/assets/34203011/adda161b-ee8d-45d6-ab31-a4b3f155cb79) Llama.cui uses this settings: ../llama.cpp/llama-cli --model ../../models/qwen2-7b-instruct-q2_k.gguf --n-gpu-layers 25 -cnv --simple-io -b 2048 --ctx_size 0 --temp 0 --top_k 10 --multiline-input --chat-template chatml --log-disable

Thank you for your reply and help，But that's not what I wanted, the -cnv interactive command was used in your directive。I can output normally when I use -cnv。 My current job is to talk about providing three interfaces under llama.cpp reencapsulation, such as model loading, inference, and release, and I want to put it on my QT interface, so that I can type a sentence and it will reply to a sentence, so I don't want to use an interactive interface like -cnv，So what I'm struggling with is why the command is like --prompt, "Where is the capital of China?" , it doesn't get the same results as interactive.

![image](https://github.com/ggerganov/llama.cpp/assets/46549527/531915bf-6ac5-42b8-bfda-e7ed0d7e741b)

**Comment by dspasyuk** [comment]
In Llama-cui I use -cnv because I do not want to load unload model every single time. That is very taxing on the SDD not to mention takes "long time" for large models. If you want to use prompt you can try something like this:

./llama.cpp/llama-cli -ngl 29 -m ../../models/qwen2-7b-instruct-q2_k.gguf --predict 512 -p "<|im_start|>system\nAnswer as a pirate<|im_end|>\n<|im_start|>user\nWhat is the capital of Canada<|im_end|>\n<|im_start|>assistant" and this is what I get:

<|im_start|>system
Answer as a pirate<|im_end|>
<|im_start|>user
What is the capital of Canada<|im_end|>
<|im_start|>assistant
Arrrr matey! The capital of Canada be Ottawa. It's located in the heart of the country, near the St. Lawrence River. Now, let's set sail to explore some treasure maps or perhaps raid some Spanish galleons! What be your next quest?<|im_end|> [end of text]

**Comment by QIANXUNZDL123** [comment]
> ./llama.cpp/llama-cli -ngl 29 -m ../../models/qwen2-7b-instruct-q2_k.gguf --predict 512 -p "<|im_start|>system\nAnswer as a pirate<|im_end|>\n<|im_start|>user\nWhat is the capital of Canada<|im_end|>\n<|im_start|>assistant"

Thank you for your reply and help，I am using the command you provided to get the correct result，But I asked another question and I didn't get an answer，like: 1+1=?     Not sure why. There are indeed a lot more imperatives than interactive questions, and maybe I haven't fully understood the author's code yet
./bin/llama-cli -m ../qwen2-1_5b-instruct-q8_0.gguf --predict 512 -p "<|im_start|>system\nAnswer as a pirate<|im_end|>\n<|im_start|\n1+1=?<|im_end|>\n<|im_start|"

![image](https://github.com/user-attachments/assets/0dfa77a3-90aa-4a5f-a1db-8d65faadb569)
