### ISSUE TITLE
Bug: After compiling I cannot execute ./main

### ISSUE THREAD

**Issue by tihom77** [ggerganov/llama.cpp#8293]
### What happened?

~/assistant/llama.cpp $ ./main --interactive-first -m models/7b/llama-2-7b.Q4_K_M.gguf
-bash: ./main: No such file or directory

### Name and Version

./llama-cli --version
version: 3292 (20fc3804)
built with cc (Debian 12.2.0-14) 12.2.0 for aarch64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/main --interactive-first -m models/7b/llama-2-7b.Q4_K_M.gguf
-bash: ./main: No such file or directory
(venv) tiho@MyAI:~/assistant/llama.cpp $
```

**Comment by JohannesGaessler** [comment]
`main` was renamed to `llama-cli`.

**Comment by tihom77** [comment]
Thanks. :)

**Comment by tihom77** [comment]
Problem was resolved. Thanks
