### ISSUE TITLE
Feature Request:  Support for Meta: Multi Token Prediction Models

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#8297]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Meta: Multi Token Prediction Models
https://arxiv.org/abs/2404.19737
Concept and Architecture:
Multi-token prediction trains LLMs to predict multiple future tokens simultaneously, rather than just the next token. The model architecture is based on the Transformer, but with multiple independent output heads - one for each token it aims to predict

Models:
https://huggingface.co/facebook/multi-token-prediction

Speed: Models trained with this approach can be up to 3 times faster at inference time across various batch sizes

### Motivation

Support for inference of this new arch

### Possible Implementation

Implementation Details:
The PyTorch state dictionaries are compatible with the Llama format.
Additional prediction heads for future tokens are named "extra_heads" and can be ignored for standard autoregressive inference

**Comment by foldl** [comment]
I did it in chatllm.cpp. It is more than 2x faster on CPU. But quality degrades too.

https://github.com/foldl/chatllm.cpp/blob/master/docs/models.md#special-models

**Comment by sorasoras** [comment]
> I did it in chatllm.cpp. It is more than 2x faster on CPU. But quality degrades too.
> 
> https://github.com/foldl/chatllm.cpp/blob/master/docs/models.md#special-models

I guess you need to train the same way as inference.
