### ISSUE TITLE
New CMakelists is pure pain.

### ISSUE THREAD

**Issue by Ph0rk0z** [ggerganov/llama.cpp#8298]
### What happened?

The refactor has made changing anything at compile time a huge hassle. No longer can you set build defaults inside one concise file but must put them on the command line in your build string. Finding new variables is all but impossible as they are burred in the code.

For instance, I could permanently have cuda on and just build. I could enable F16, force MMQ, MMQ sizes and I would KNOW what I was getting. Less used defines were all in one place and could be experimented with. Now it's a guess as to whether you even get GPU support as per some of the previous issues. If you don't like the defaults, tough titties.

I hope there was some net benefit to doing this way because to me it's a negative :(

### Name and Version

git

### What operating system are you seeing the problem on?

Linux

### Example

I now have to set GGML_CUDA_PEER_MAX_BATCH_SIZE, GGML_CUDA_MMV_Y, GGML_CUDA_FA_ALL_QUANTS, etc every single time and have no idea what it was built with.

**Comment by ggerganov** [comment]
Just learn to use `ccmake` - it's very convenient, and allows to list and edit all available compile options in the terminal:

<img width="339" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/1991296/3b4ec474-41f9-43b9-96d4-9f8714527394">

**Comment by Ph0rk0z** [comment]
Not mentioned anywhere so how would I even know to try it?
