### ISSUE TITLE
Gemma 2 inference - continuous token succession

### ISSUE THREAD

**Issue by ctb111** [ggerganov/llama.cpp#8324]
### What happened?

There is an issue in which after the models answers the question it keeps on generating 2 tokens until the context is filled up.
Tokens in question:
    {
      "id": 149,
      "content": "▁▁▁▁▁▁▁▁▁▁▁▁",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false,
      "special": false
    },
    {
      "id": 108,
      "content": "\n",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false,
      "special": false
    },
    
   How the server is run:
   llama-server  --threads 1 --batch-size 256 --threads-batch 32 --n-gpu-layers 43 --main-gpu 0 --metrics --defrag-thold 0.8 --cont-batching -m  /<model_path>/gemma-2-9b-it/gemma-2-9b-it-Q6_K.gguf -v -c 32786 -n 1024  --parallel 16   --host <h>  --port <p>

The query to the model is made via the /completion API

The model is used in a RAG system, the following prompt has been used:
        prompt = '''
            <bos><start_of_turn>user
            \n
			<prompt engineering>
            \n
            <prompt engineering>

            Context: {context_format}
            -----
            Question: {query}
            Answer:
            <end_of_turn>
            <start_of_turn>model
            '''
I've also tried without the <start_of_turn>model template, but still the issue persists.

The GGUF models that I've tried (updated as of today):
bartowski/gemma-2-9b-it-Q6_K_L.gguf
bartowski/gemma-2-9b-it-Q6_K.gguf (Llamacpp quants)

The interface is via streamlit, the issue persists also in a local chatui (huggingface), but the issue is generating random repeating small words, bullet points & whitespaces.

Thank you,

### Name and Version

 8.5.0 20210514 

### Relevant log output

```shell
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] slot decode token | tid="140407907995648" timestamp=1720171553 id_slot=0 id_task=0 n_ctx=32800 n_past=1172 n_system_tokens=0 n_cache_tokens=1024 >
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] decoding batch | tid="140407907995648" timestamp=1720171553 n_tokens=1
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [           process_token] next token | tid="140407907995648" timestamp=1720171553 id_slot=0 id_task=0 token=108 token_text="\n" has_next_token=true n_remain=959 n_decoded=>
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] run slots completed | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [              start_loop] wait for new task | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [              start_loop] new task may arrive | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [              start_loop] callback_new_task | tid="140407907995648" timestamp=1720171553 id_task=69
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [              start_loop] update_multitasks | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [              start_loop] callback_update_slots | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] posting NEXT_RESPONSE | tid="140407907995648" timestamp=1720171553
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [                    post] new task id | tid="140407907995648" timestamp=1720171553 new_id=70
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] slot decode token | tid="140407907995648" timestamp=1720171553 id_slot=0 id_task=0 n_ctx=32800 n_past=1173 n_system_tokens=0 n_cache_tokens=1024 >
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] decoding batch | tid="140407907995648" timestamp=1720171553 n_tokens=1
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [           process_token] next token | tid="140407907995648" timestamp=1720171553 id_slot=0 id_task=0 token=149 token_text="            " has_next_token=true n_remain=958 >
Jul 05 12:25:53 <name_server> llama-server[1547085]: VERB [            update_slots] run slots completed | tid="140407907995648" timestamp=1720171553
```

**Comment by ctb111** [comment]
It seems that the issue has been the prompt template format.
I've made it inline, and everything is fine. Both the tokens presented were inserted into in the prompt. basically \t and \n.

Not sure if this can be considered a llamacpp issue - will keep it open just in case.

**Comment by ngxson** [comment]
Since you're using /completion endpoint and provided your own template format, it's up to you to verify if the template is formatted correctly or not.

I'll close this issue for now. If you're using original model (no fine tune), it is always recommended to use correct template.
