### ISSUE TITLE
Just thinking, could we try quantizing the model using Qx_K, then calculate the hash purely based on scale of each block? (we don't care about the individual weights inside each block).

### ISSUE THREAD

**Issue by Aridbhdkkj** [ggerganov/llama.cpp#8345]
Just thinking, could we try quantizing the model using Qx_K, then calculate the hash purely based on scale of each block? (we don't care about the individual weights inside each block).

_Originally posted by @ngxson in https://github.com/ggerganov/llama.cpp/discussions/7839#discussioncomment-9861478_

**Comment by ngxson** [comment]
Please don’t spam. Comment in the original thread.
