### ISSUE TITLE
Bug: Gemma2 tokenization seems incorrect.

### ISSUE THREAD

**Issue by AUTOMATIC1111** [ggerganov/llama.cpp#8349]
### What happened?

tokenizer.json from gemma2 has this token: "[toxicity=0]": 255968.

When tokenizing that text using llamacpp, we get [235309, 1373, 235293, 235276, 235307]

If I ask llamacapp gemma2 to repeat this text, [toxicity=0], it does so effortlessly.

If I ask corpo hosted gemma2 to repeat it, it fails, thinking there's no text there:

![chrome_oG2qUJimh4](https://github.com/ggerganov/llama.cpp/assets/20920490/e9d8c374-f097-457b-af2d-92141ac58493)

### Name and Version

version: 3317 (8e558309)
built with MSVC 19.29.30154.0 for x64

### What operating system are you seeing the problem on?

Windows

**Comment by cuelebra** [comment]
confirming, LMSYS:

<img width="638" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/174902085/213ebe96-f389-4479-a900-13206cef77e9">

llama.cpp gemma 27b Q8_0:
```
<start_of_turn>user
Repeat the following text:
START->[toxicity=0]<-END<end_of_turn>
<start_of_turn>model

START->[toxicity=0]<-END
```

**Comment by ngxson** [comment]
Please refer to: https://github.com/ggerganov/llama.cpp/issues/8240#issuecomment-2212444937
