### ISSUE TITLE
Editing a PR description shouldn't cause a CI run

### ISSUE THREAD

**Issue by sw** [ggerganov/llama.cpp#836]
This seems excessive but I'm not sure how to turn that off (`edited` in `build.yml`?), without inadvertently also removing other triggers (such as a push to the branch the PR wants to merge).

Also, other actions such as requesting a review should not trigger a CI run IMO.

**Comment by slaren** [comment]
I have noticed this too. Makes me feel a bit bad every time that I modify the description, but am not sure if this has any real cost for us anyway.

**Comment by anzz1** [comment]
build.yml
```diff
  pull_request:
-    types: [opened, synchronize, edited, reopened, review_requested, ready_for_review]
+    types: [opened, synchronize, reopened, review_requested, ready_for_review]
```
it was there so you can force a new CI run without pushing anything by editing the PR when it hangs due to github lagging but as you can also trigger that by requesting a new review it's probably a good idea to remove it especially since the CI run is rather big now

**Comment by ggerganov** [comment]
> On the other hand, draft pull requests skip most of the CI checks, that's not so good.

I thought that usually drafts are incomplete and checks will likely fail, so I disabled them.
But don't have very strong feeling about this - we can reenable if people prefer it

**Comment by ggerganov** [comment]
Done

![image](https://user-images.githubusercontent.com/1991296/233781961-0e125da7-8522-493d-85a4-77c99039ac79.png)
