### ISSUE TITLE
Bug: Yi 1.5 segmentation fault

### ISSUE THREAD

**Issue by SimplyCorbett** [ggerganov/llama.cpp#8369]
### What happened?

Using build 3346 I am experiencing a segmentation fault with Yi 1.5.

I am unsure if it works with older versions.

Command: ./llama-server -m ~/llm/Yi-1.5-34B-32K-Q3_K_L.gguf -c 8096 --n-gpu-layers 250 --batch-size 1024 --mlock --no-mmap --host iphere --port porthere --flash-attn

Other models do work, so it’s specific to Yi 1.5. It’s possible the GGUF is just bad as well.

### Name and Version

3346

### What operating system are you seeing the problem on?

Mac

**Comment by HanClinto** [comment]
> It’s possible the GGUF is just bad as well.

That's quite likely.

What about other versions of Yi -- do those work?

Could also try other quants?
