### ISSUE TITLE
Bug: Misplaced docs/token_generation_performance_tips.md  or link broken

### ISSUE THREAD

**Issue by dspasyuk** [ggerganov/llama.cpp#8381]
### What happened?

The file from [Performance troubleshooting](https://github.com/ggerganov/llama.cpp/blob/master/docs/token_generation_performance_tips.md) was misplaced, the file is located in docs/development/token_generation_performance_tips.md instead

### Name and Version

B3347

**Comment by HanClinto** [comment]
Fixed in #8399

Thanks!
