### ISSUE TITLE
Bug: ggml.c:5278: !ggml_is_transposed(a)

### ISSUE THREAD

**Issue by guinmoon** [ggerganov/llama.cpp#8398]
### What happened?

For some reason, when I use the llama.cpp code in my project on T5 models, I get this error:
```
ggml.c:5278: !ggml_is_transposed(a)
```

At the same time llama-cli built with the same sources works fine.
Who can tell me what the problem is?

### Name and Version

Release [b3347](https://github.com/ggerganov/llama.cpp/releases/tag/b3347)

**Comment by fairydreaming** [comment]
> For some reason, when I use the llama.cpp code in my project on T5 models, I get this error:
> 
> ```
> ggml.c:5278: !ggml_is_transposed(a)
> ```
> 
> At the same time llama-cli built with the same sources works fine. Who can tell me what the problem is?

@guinmoon Not sure if this is the cause, but to use T5 models you have to call some new additional API, see sources of llama-cli for reference: https://github.com/ggerganov/llama.cpp/blob/e500d6135ac42c4a23baf6a9a1a934dc023e5c7d/examples/main/main.cpp#L531-L547

Basically you have to pass the prompt tokens to llama_encode() call and then use a token returned from `llama_model_decoder_start_token()` to create a new token sequence passed to `llama_decode()` call.

**Comment by fairydreaming** [comment]
@guinmoon I confirmed that calling `llama_decode()` for an encoder-decoder model like T5 without a prior `llama_encode()` call causes the weird error message you mentioned. To avoid confusion I added an assert to point the API users to right direction: #8400

**Comment by steampunque** [comment]
> Basically you have to pass the prompt tokens to `llama_encode()` call and then use a token returned from `llama_model_decoder_start_token()` to create a new token sequence passed to `llama_decode()` call.

There is none of this code in the server, so I guess server has not been updated to support T5 models yet?  I also tried to load madlad400 and got an assert here in the server:

        add_bos_token = llama_should_add_bos_token(model);
        GGML_ASSERT(llama_add_eos_token(model) != 1);

Tried also to run madlad400 with cli but it just responds with blank space for <2de> Hello how are you?

**Comment by fairydreaming** [comment]
> > Basically you have to pass the prompt tokens to `llama_encode()` call and then use a token returned from `llama_model_decoder_start_token()` to create a new token sequence passed to `llama_decode()` call.
> 
> There is none of this code in the server, so I guess server has not been updated to support T5 models yet?

That's right.

> Tried also to run madlad400 with cli but it just responds with blank space for <2de> Hello how are you?

Works just fine for me (current master):

```
python3 convert_hf_to_gguf.py /mnt/md0/huggingface/hub/models--google--madlad400-10b-mt/snapshots/9f2797629c31e69617186dbe5f0ca43bf662f36d/ --outfile models/madlad400-10b.gguf --outtype "f32"
./llama-cli -m models/madlad400-10b.gguf -p '<2de> Hello how are you?'
```

```
(llama.cpp) phm@epyc:~/projects/llama.cpp$ ./llama-cli -m models/madlad400-10b.gguf -p '<2de> Hello how are you?'
Log start
...
system_info: n_threads = 32 / 64 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 512, n_batch = 2048, n_predict = -1, n_keep = 0


▅ Hallo, wie geht es? [end of text]

llama_print_timings:        load time =    1162.90 ms
llama_print_timings:      sample time =       0.66 ms /     8 runs   (    0.08 ms per token, 12139.61 tokens per second)
llama_print_timings: prompt eval time =     449.94 ms /     9 tokens (   49.99 ms per token,    20.00 tokens per second)
llama_print_timings:        eval time =    1679.21 ms /     7 runs   (  239.89 ms per token,     4.17 tokens per second)
llama_print_timings:       total time =    2275.37 ms /    16 tokens
Log end
```

**Comment by fairydreaming** [comment]
@steampunque Let me know what exactly was the model you were trying to run.

**Comment by guinmoon** [comment]
> > For some reason, when I use the llama.cpp code in my project on T5 models, I get this error:
> 
> > 
> 
> > ```
> 
> > ggml.c:5278: !ggml_is_transposed(a)
> 
> > ```
> 
> > 
> 
> > At the same time llama-cli built with the same sources works fine. Who can tell me what the problem is?
> 
> 
> 
> @guinmoon Not sure if this is the cause, but to use T5 models you have to call some new additional API, see sources of llama-cli for reference: https://github.com/ggerganov/llama.cpp/blob/e500d6135ac42c4a23baf6a9a1a934dc023e5c7d/examples/main/main.cpp#L531-L547
> 
> 
> 
> Basically you have to pass the prompt tokens to `llama_encode()` call and then use a token returned from `llama_model_decoder_start_token()` to create a new token sequence passed to `llama_decode()` call.

Thank you very much, this is a working solution for me!

**Comment by steampunque** [comment]
> @steampunque Let me know what exactly was the model you were trying to run.

I tried a Q6_K quant of this model:
madlad400-7b-mt

I think my steps were essentially identical to what you showed in your response.  Still may be just some pilot error somewhere on my part, will try again with the 10b you used.  Thanks for your reply.

**Comment by fairydreaming** [comment]
> > @steampunque Let me know what exactly was the model you were trying to run.
> 
> I tried a Q6_K quant of this model: madlad400-7b-mt
> 
> I think my steps were essentially identical to what you showed in your response. Still may be just some pilot error somewhere on my part, will try again with the 10b you used. Thanks for your reply.

@steampunque You can also verify if the 7b model answers your prompt correctly in HF transformers library. Another idea to try is to use f32 model instead of quantized one.

**Comment by fairydreaming** [comment]
@steampunque I'm afraid that interactive mode is currently not supported.

**Comment by steampunque** [comment]
> @steampunque I'm afraid that interactive mode is currently not supported for encoder-decoder models like T5.

No problem and thank you for adding this great T5 support!  I do not use cli (exept to submit debug issues), only server.  I will have a look into patching my server based on your notes in this thread if adding T5  for it is not on your roadmap for now.
