### ISSUE TITLE
Bug: tokenizer.chat_template missing from key/values

### ISSUE THREAD

**Issue by bandoti** [ggerganov/llama.cpp#8403]
### What happened?

I am seeing an issue with the default chat templates not properly loading. It appears as though the `tokenizer.chat_template` key is missing from the model meta-data. Here is a test program showcasing the issue:

```cpp
    const char * model = "D:\\models\\llama-2-7b-chat.Q5_K_M.gguf";
    struct llama_model_params params = llama_model_default_params();
    params.use_mmap = false;

    struct llama_model * model_ = llama_load_model_from_file(model, params);
    if (! model_) {
        printf("uh oh");
        exit(1);
    }

    // This snippet is from recent pull request.
    std::string template_key = "tokenizer.chat_template", curr_tmpl;
    int32_t tlen2 = llama_model_meta_val_str(model_, template_key.c_str(), nullptr, 0);
    if (tlen2 > 0) {
        std::vector<char> curr_tmpl_buf(tlen2 + 1, 0);
        if (llama_model_meta_val_str(model_, template_key.c_str(), curr_tmpl_buf.data(), curr_tmpl_buf.size()) =\
= tlen2) {
            curr_tmpl = std::string(curr_tmpl_buf.data(), tlen2);
            printf("%s", curr_tmpl.c_str());
        }
    }

```

I have tried this logic with several models, but never does it pull the template out of model. It looks like there's no `LLM_KV_TOKENIZER_CHAT_TEMPLATE` in `enum llm_kv`. Not sure if that's the issue, but I tried the following patch and didn't seem to be enough either. If anyone has some advice on other places this code might need to be updated that would be great! Thank you.

```diff
diff --git a/src/llama.cpp b/src/llama.cpp
index 2b9ace2..93b573f 100644
--- a/src/llama.cpp
+++ b/src/llama.cpp
@@ -371,6 +371,7 @@ enum llm_kv {
     LLM_KV_TOKENIZER_SUFFIX_ID,
     LLM_KV_TOKENIZER_MIDDLE_ID,
     LLM_KV_TOKENIZER_EOT_ID,
+    LLM_KV_TOKENIZER_CHAT_TEMPLATE,
 };

 static const std::map<llm_kv, const char *> LLM_KV_NAMES = {
@@ -464,6 +465,7 @@ static const std::map<llm_kv, const char *> LLM_KV_NAMES = {
     { LLM_KV_TOKENIZER_SUFFIX_ID,            "tokenizer.ggml.suffix_token_id"          },
     { LLM_KV_TOKENIZER_MIDDLE_ID,            "tokenizer.ggml.middle_token_id"          },
     { LLM_KV_TOKENIZER_EOT_ID,               "tokenizer.ggml.eot_token_id"             },
+    { LLM_KV_TOKENIZER_CHAT_TEMPLATE,        "tokenizer.chat_template"                 },
 };

 struct LLM_KV {


```

### Name and Version

$ ./build/inst/bin/llama-cli.exe --version
version: 1 (50da329)
built with cc.exe (Rev3, Built by MSYS2 project) 14.1.0 for x86_64-w64-mingw32

### What operating system are you seeing the problem on?

x86_64-w64-mingw32

**Comment by bandoti** [comment]
I have a feeling this is because I grabbed older models on hugging face that might not have the keys in there. Will try to generate my own conversion and see if it brings the latest key data with.

**Comment by bandoti** [comment]
Creating a GGUF dump here also not showing up.

`python gguf-py\scripts\gguf_dump.py --no-tensors --json models\Meta-Llama-3-8B\ggml-model-Q4_K_M.gguf`

> {"filename": "models\\Meta-Llama-3-8B\\ggml-model-Q4_K_M.gguf", "endian": "LITTLE", "metadata": {"GGUF.version": {"index": 0, "type": "UINT32", "offset": 4, "value": 3}, "GGUF.tensor_count": {"index": 1, "type": "UINT64", "offset": 8, "value": 291}, "GGUF.kv_count": {"index": 2, "type": "UINT64", "offset": 16, "value": 21}, "general.architecture": {"index": 3, "type": "STRING", "offset": 24, "value": "llama"}, "general.name": {"index": 4, "type": "STRING", "offset": 69, "value": "Meta-Llama-3-8B"}, "llama.block_count": {"index": 5, "type": "UINT32", "offset": 116, "value": 32}, "llama.context_length": {"index": 6, "type": "UINT32", "offset": 149, "value": 8192}, "llama.embedding_length": {"index": 7, "type": "UINT32", "offset": 185, "value": 4096}, "llama.feed_forward_length": {"index": 8, "type": "UINT32", "offset": 223, "value": 14336}, "llama.attention.head_count": {"index": 9, "type": "UINT32", "offset": 264, "value": 32}, "llama.attention.head_count_kv": {"index": 10, "type": "UINT32", "offset": 306, "value": 8}, "llama.rope.freq_base": {"index": 11, "type": "FLOAT32", "offset": 351, "value": 500000.0}, "llama.attention.layer_norm_rms_epsilon": {"index": 12, "type": "FLOAT32", "offset": 387, "value": 9.999999747378752e-06}, "general.file_type": {"index": 13, "type": "UINT32", "offset": 441, "value": 15}, "llama.vocab_size": {"index": 14, "type": "UINT32", "offset": 474, "value": 128256}, "llama.rope.dimension_count": {"index": 15, "type": "UINT32", "offset": 506, "value": 128}, "tokenizer.ggml.model": {"index": 16, "type": "STRING", "offset": 548, "value": "gpt2"}, "tokenizer.ggml.pre": {"index": 17, "type": "STRING", "offset": 592, "value": "llama-bpe"}, "tokenizer.ggml.tokens": {"index": 18, "type": "ARRAY", "offset": 639, "array_types": ["STRING"]}, "tokenizer.ggml.token_type": {"index": 19, "type": "ARRAY", "offset": 2100177, "array_types": ["INT32"]}, "tokenizer.ggml.merges": {"index": 20, "type": "ARRAY", "offset": 2613250, "array_types": ["STRING"]}, "tokenizer.ggml.bos_token_id": {"index": 21, "type": "UINT32", "offset": 7818060, "value": 128000}, "tokenizer.ggml.eos_token_id": {"index": 22, "type": "UINT32", "offset": 7818103, "value": 128001}, "general.quantization_version": {"index": 23, "type": "UINT32", "offset": 7818146, "value": 2}}, "tensors": {}}

**Comment by ggerganov** [comment]
`Meta-Llama-3-8B` seems like a base model, so it is normal to not have a chat template

**Comment by bandoti** [comment]
Yikes—that's what I get for working late... Pulling down the instruct model now. Thank you. 😅

**Comment by bandoti** [comment]
That did the trick. Just pulled the right model and had success:

> 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, ]} tokenizer.ggml.bos_token_id 1 tokenizer.ggml.eos_token_id 32000 tokenizer.ggml.unknown_token_id 0 tokenizer.ggml.padding_token_id 32000 tokenizer.ggml.add_bos_token false tokenizer.ggml.add_eos_token false tokenizer.chat_template {{% for message in messages %}{% if message['role'] == 'system' %}{{'<|system|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'user' %}{{'<|user|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>
' + message['content'] + '<|end|>
'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>
' }}{% else %}{{ eos_token }}{% endif %}} general.quantization_version 2
