### ISSUE TITLE
How to evaluate my converted gguf model ? What all benchmark i can run and how to run on my converted model? 

### ISSUE THREAD

**Issue by RakshitAralimatti** [ggerganov/llama.cpp#8409]
### What happened?

I want to run MMLU or ARC etc.. or even  Perplexity for my converted gguf model.

### Name and Version

For latest version

### What operating system are you seeing the problem on?

Linux

**Comment by dspasyuk** [comment]
@RakshitAralimatti  Have you checked this? https://github.com/ggerganov/llama.cpp/discussions/2321 you will need to use llama-perplexity module to do that, the dataset is in the link

**Comment by RakshitAralimatti** [comment]
@dspasyuk Thanks for your response.

I figured out how to calculate the HellaSwag scores using the llama-perplexity tool.
But what about others like MMLU or MMLU-PRO, Winogrande, and GSM8K?
Does the llama-perplexity tool support those all? 
Or can you tell me which llama-perplexity tool supports?

Thanks in advance.

**Comment by dspasyuk** [comment]
@RakshitAralimatti You can get a full list of options by typing llama-perplexity --help

**Comment by RakshitAralimatti** [comment]
Hi @dspasyuk 
Can you suggest which dataset is better for running **multiple-choice** evaluation?

**Comment by zhycheng614** [comment]
Maybe you can try Nexa-SDK's benchmark feature for gguf:
[https://github.com/NexaAI/nexa-sdk/tree/main/nexa/eval](url)
