### ISSUE TITLE
How do i stop the ai from talking to itself??

### ISSUE THREAD

**Issue by Asory2010** [ggerganov/llama.cpp#841]
It sometimes just talks to itself for example:

###Human: Hi
###Assistant: Hello, how can i assist you?

(i am runing the latest release with vicuna mode)

**Comment by hungerf3** [comment]
Take a look at the  --reverse-prompt option;   it lets you indicate when you want to be able to enter your input.

**Comment by andresdelcampo** [comment]
Great to know! 
Is there a way to prevent the reverse prompt ('### Human:") from being printed in the screen?

```
> Hi there
Hello! How can I assist you today?
### Human:
>
```

**Comment by ungarscool1** [comment]
On a personal project, I detect the first `#` and `:` or `\n`. If between these, it contains 'Human', so I stop the execution and find&replace `### Human:` to blank.

**Comment by Alumniminium** [comment]
-r '###' works sufficiently well and catches all the other various things like ### Instruction, ### Next Prompt, ### Question, ... the model occasionally creates.

**Comment by Gitterman69** [comment]
doesnt work at all on mac - super weird.... 

`./main -m ./models/ggml-vicuna-7b-1.0-uncensored-q4_0.bin -n 256 --repeat_penalty 1.1 --color -i -r '### Human:' -r '##' -r '###' -f prompts/chat-with-vicuna.txt`

**Comment by ibndias** [comment]
This works for me for vicuna prompt trained model

`./main -m ../../Downloads/wizardLM-7B.ggml.q4_0.bin -n 2048 --repeat_penalty 1.0 --color -i -r "### Human:" -f prompts/chat-with-vicuna.txt`

[chat-with-vicuna.txt](https://github.com/ggerganov/llama.cpp/files/11157908/chat-with-vicuna.txt)
