### ISSUE TITLE
train a model from scratch but f16 or q8

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8429]
I noticed that train-text-from-scratch creates an f32 model.

Is it possible to train a model from scratch directly to f16 or q8?
That would be interesting to try out and fast on CPU.

**Comment by JohannesGaessler** [comment]
>Is it possible to train a model from scratch directly to f16 or q8?

As of right now I think it's not possible. It is one of my goals for 2024 to implement GPU training in llama.cpp including partial offloading and low-precision data types but this will only be faster on CPU if there are SIMD instructions available.

**Comment by 0wwafa** [comment]
> > Is it possible to train a model from scratch directly to f16 or q8?
> 
> As of right now I think it's not possible. It is one of my goals for 2024 to implement GPU training in llama.cpp including partial offloading and low-precision data types but this will only be faster on CPU if there are SIMD instructions available.

yep! there are a bunch of notebooks with a core i7 / GTX970M combo out there... would be nice to squeeze them.
and useful on more powerful system to do some testing faster.
