### ISSUE TITLE
Input Chinese Its talk with itself

### ISSUE THREAD

**Issue by huanxiang666** [ggerganov/llama.cpp#843]
![image](https://user-images.githubusercontent.com/70996861/230702957-dd4dff6a-35e5-4926-9796-75db84443b5d.png)
When I use Chinese 
Its will talk with itself

**Comment by huanxiang666** [comment]
你好 means Hello in English
It will output another message

**Comment by Belluxx** [comment]
To fix this, there should be an option to choose a text that must be added at the end of the user input.
In this cause we should append `\n### Assistant:` so that the context is ready for a reply, this would also fix the chat escape that sometimes happens.

However nobody mentioned this in the past so i don't know if it will be added as a feature.

**Comment by Yang-Jace-Liu** [comment]
@Belluxx 's answer is correct.

Here is my setup. In my initial prompt, I ask the bot to enter a new line and print "### Human:" after the response. In the interactive mode, I normally manually input "\ <new_line> ### Assistant:" to the end so the assistant could take over the control.

For a chatgpt-like experience:

`./prompts/chatgpt.txt`:
```
### Human: Let's start a chat between a curious human and an artificial intelligence assistant.
The assistant gives helpful, detailed, and polite answers to the human's questions.
The response should be concise and should focus on the topic human bring up. Don't include other topics.
After the response, the assistant should create a new line and print "### Human:" to pass the control to human.
### Assitant: Sure, I'm ready to assist you with any questions or topics you have in mind.
### Human:
```

`command`
```
./main -m <model_path> -t 6 -c 2048 -n 2048 --color -i -n -1 --reverse-prompt '### Human:' -f prompts/chatgpt.txt
```

**Comment by huanxiang666** [comment]
![image](https://user-images.githubusercontent.com/70996861/230805421-17299e38-1067-488d-bc50-6d518b265543.png)

**Comment by huanxiang666** [comment]
![image](https://user-images.githubusercontent.com/70996861/230805704-19d4fa92-9238-4d99-afa6-331411a0e616.png)

**Comment by Belluxx** [comment]
Try to write the chinese prompt, then before pressing "enter" append a `\`. Then press enter and then add `### Assistant:` and press enter again

**Comment by Yang-Jace-Liu** [comment]
I suggest you start the conversation with something like informative question or practical instruction. If you are using original LLama, you should know it's not fine-tuned for ChatGPT-like question-and-answer style conversations but for simply completing the text based on the context.

There are fine-tuned models such as Alpaca or Vicuna (the model I use in the screenshot). Note that the outcome of Chinese conversations is still weaker / less ideal compared to English ones. For Chinese specific model, you can start by looking into [Chinese-LLaAMA-Alpaca](https://github.com/ymcui/Chinese-LLaMA-Alpaca) or [ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B).


Btw, "\n" stands for a new line, not meaning you need to manually type "\n" in the console.

![Screenshot from 2023-04-09 19-36-59](https://user-images.githubusercontent.com/14989893/230809230-4942bcc8-dd8c-444d-965f-bb10b2f66d98.png)

**Comment by ivanstepanovftw** [comment]
Adapt prompt itself, translate it to CN and try again.

**Comment by patrakov** [comment]
This is likely a special case of https://github.com/ggerganov/llama.cpp/issues/667
