### ISSUE TITLE
Getting bash: ./perplexity: No such file or directory 

### ISSUE THREAD

**Issue by RakshitAralimatti** [ggerganov/llama.cpp#8431]
### What happened?

Getting the bash: ./perplexity: No such file or directory error even after the Build has happened correctly 
Is the tool renamed?

### Name and Version

Lasted version

### What operating system are you seeing the problem on?

Linux

**Comment by JohannesGaessler** [comment]
It was renamed to `llama-perplexity`.

**Comment by RakshitAralimatti** [comment]
@JohannesGaessler Thanks for your response.
It worked!!

**Comment by fairydreaming** [comment]
I see that the problem was solved, so I'm closing the issue.
