### ISSUE TITLE
Bug: Llava not working on android

### ISSUE THREAD

**Issue by Hardik-Choraria** [ggerganov/llama.cpp#8436]
### What happened?

Was trying to run android/abd_run.sh using the llava model.

### Name and Version

./llama-llava-cli --version 
version: 3354 (5b0b8d8c)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.5.0

### Relevant log output

This is the output file generated by running abd_run.sh 

```shell
CANNOT LINK EXECUTABLE "/data/local/tmp/llama-llava-cli": library "libllama.so" not found: needed by main executable. 
```

**Comment by howardgriffin** [comment]
same problem

**Comment by Xxianna** [comment]
Move these .so to the dir of your exe and ```export LD_LIBRARY_PATH=./```
