### ISSUE TITLE
llama-b3376-bin-win-cuda-cu12.2.0-x64 missing dlls.

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8443]
llama-b3376-bin-win-cuda-cu12.2.0-x64
`llama-cli -c 1024 -t 6 -m Phi-3-mini-128k-instruct-abliterated-v3.q6_k.gguf`

![image](https://github.com/user-attachments/assets/86f7a5c5-afec-4602-b85f-c6cb7912cf6a)

![image](https://github.com/user-attachments/assets/43c19b19-4f17-4d22-b37d-82e35efff5a3)

**Comment by Rotatingxenomorph** [comment]
You need to add these to the llama folder https://github.com/ggerganov/llama.cpp/releases/download/b3381/cudart-llama-bin-win-cu12.2.0-x64.zip

**Comment by Astroherodvaipayan** [comment]
https://github.com/ggerganov/llama.cpp/releases/download/b3381/cudart-llama-bin-win-cu12.2.0-x64.zip please install this and run it should solve the issue

**Comment by HardDen** [comment]
Хм как нас много то )))
