### ISSUE TITLE
Unable to convert a fireworks ai model to GGUF with gguf-my-repo

### ISSUE THREAD

**Issue by markat1** [ggerganov/llama.cpp#8451]
### What happened?

I  downloaded one of my models from fireworks.ai and pushed it up into huggingface - you can find it here: [llama-3-8b-instruct-danish](https://huggingface.co/HeRksTAn/llama-3-8B-Instruct-Danish)

I then tried  [gguf-my-repo](https://huggingface.co/spaces/ggml-org/gguf-my-repo) in order to convert it to gguf. 

1. using https://huggingface.co/spaces/ggml-org/gguf-my-repo 
2. logged into my account
3. search the hub id for the repository I want converted into gguf, which is HeRksTAn/llama-3-8B-Instruct-Danish
4. I chose Q4_K_M
5. I clicked submit

I get the following error 

`Error: Error converting to fp16: b'INFO:hf-to-gguf:Loading model: llama-3-8B-Instruct-Danish\nTraceback (most recent call last):\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 3551, in \n main()\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 3517, in main\n hparams = Model.load_hparams(dir_model)\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 356, in load_hparams\n with open(dir_model / "config.json", "r", encoding="utf-8") as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'llama-3-8B-Instruct-Danish/config.json'\n'`

It seems like I'm missing some files - can you please pinpoint what I'm missing? or what I should request from fireworks  ai, so that I can convert it to GGUF?

![error-converting-to-gguf](https://github.com/user-attachments/assets/f064fc64-7d6c-41da-87ad-db9b8befe3cd)

### Relevant log output

```shell
`Error: Error converting to fp16: b'INFO:hf-to-gguf:Loading model: llama-3-8B-Instruct-Danish\nTraceback (most recent call last):\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 3551, in \n main()\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 3517, in main\n hparams = Model.load_hparams(dir_model)\n File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 356, in load_hparams\n with open(dir_model / "config.json", "r", encoding="utf-8") as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'llama-3-8B-Instruct-Danish/config.json'\n'`
```

**Comment by foldl** [comment]
You need to fix this:

```
FileNotFoundError: [Errno 2] No such file or directory: 'llama-3-8B-Instruct-Danish/config.json'
```

**Comment by markat1** [comment]
Hi @foldl  - thanks for your reply - I renamed the file to config.json  [as you can se here](https://huggingface.co/HeRksTAn/llama-3-8B-Instruct-Danish/blob/main/config.json)

**Comment by markat1** [comment]
so it seems like it's failing on [line 3577 of convert to gguf](https://github.com/ggerganov/llama.cpp/blob/705b7ecf60e667ced57c15d67aa86865e3cc7aa7/convert_hf_to_gguf.py#L3577C9-L3577C72)

I'm not sure what exactly it means with  `in main\n model_class = Model.from_model_architecture(hparams["architectures"][0])\nKeyError: 'architectures'\n'`
 
 Okay now I'm guessing here, so please correct me if I'm wrong:
 
is it because I have to convert model.safetensor with https://github.com/ggerganov/llama.cpp/blob/master/convert_lora_to_gguf.py ?
