### ISSUE TITLE
Feature Request: Drop dependency on cublas library on build / TinyBLAS support

### ISSUE THREAD

**Issue by amakropoulos** [ggerganov/llama.cpp#8452]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

At the moment llama.cpp builds with CUDA require the cublas / cublasLt library which increases the build size by 0.5GB (if statically linked).
This is a real pain for distribution of llama.cpp in customer applications.
TinyBLAS from llamafile has managed to build GPU support with performance essentially the same as with CUDA (that's really amazing @jart !) without requiring it.
Could TinyBLAS be included or is there any other way to build without requiring cublas?

### Motivation

reduce the size of llama.cpp CUDA builds from 0.5 GB to a few MBs to allow distribution in customer applications.

### Possible Implementation

Include tinyBLAS support

**Comment by JohannesGaessler** [comment]
I don't think it's possible to build CUDA without cudart. Are you perhaps confusing cudart with cuBLAS?

**Comment by amakropoulos** [comment]
yes thank you, I meant cublas :slightly_smiling_face: ! I edited the issue.

**Comment by JohannesGaessler** [comment]
I have never benchmarked tinyblas myself. The last numbers that I saw from Justine were ~50% as fast as cuBLAS.

>TinyBLAS from llamafile has managed to build GPU support with performance essentially the same as with CUDA (that's really amazing @jart !) without requiring it.

When you said that, which quantization type were you using as the basis for that statement? I am no keeping up-to-date with the state of llamafile but in llama.cpp most quantization types currently do not use FP16 cuBLAS GEMM in the first place but rather custom matrix multiplication kernels that directly use the quantized data as input. However, for FP16/FP32 models cuBLAS is still used.

**Comment by amakropoulos** [comment]
This remains an issue 😣
