### ISSUE TITLE
Bug -  Can't build vulkan backend on RISC-V platform anymore

### ISSUE THREAD

**Issue by yli147** [ggerganov/llama.cpp#8488]
### What happened?

Bug: Can't build vulkan backend on RISC-V platform anymore

### Name and Version

git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
apt-get install cmake
cmake -B build -DGGML_VULKAN=1
cmake --build build --config Release -j8

### Relevant log output

```shell
Vulkan_GLSLC_EXECUTABLE-NOTFOUND -fshader-stage=compute --target-env=vulkan1.2 -O /root/liyong/llama.cpp/ggml/src/vulkan-shaders/mul_mm.comp -o /root/liyong/llama.cpp/build/ggml/src/vulkan-shaders.spv/matmul_f32_f16_aligned_fp32.spv -DB_TYPE=f16vec4 -DDATA_A_F32=1 -DD_TYPE=float -DFLOAT_TYPE=float -DLOAD_VEC_A=4 -DLOAD_VEC_B=4

sh: 1: Vulkan_GLSLC_EXECUTABLE-NOTFOUND: not found

cannot compile matmul_f32_f32_aligned_fp32

Vulkan_GLSLC_EXECUTABLE-NOTFOUND -fshader-stage=compute --target-env=vulkan1.2 -O /root/liyong/llama.cpp/ggml/src/vulkan-shaders/mul_mm.comp -o /root/liyong/llama.cpp/build/ggml/src/vulkan-shaders.spv/matmul_f32_f32_aligned_fp32.spv -DB_TYPE=vec4 -DDATA_A_F32=2 -DD_TYPE=float -DFLOAT_TYPE=float -DLOAD_VEC_A=4 -DLOAD_VEC_B=4
```

**Comment by AndreasKunar** [comment]
Suggestion which might help - install the glslc (Vulkan's shader-compiler) from the Vulkan-SDK - on Ubuntu it's apt install glslc.

**Comment by yli147** [comment]
> Suggestion which might help - install the glslc (Vulkan's shader-compiler) from the Vulkan-SDK - on Ubuntu 24.04 it's apt install glslc.

you mean cross-compile the riscv binary on x86 ubuntu host ?

**Comment by AndreasKunar** [comment]
> > Suggestion which might help - install the glslc (Vulkan's shader-compiler) from the Vulkan-SDK - on Ubuntu 24.04 it's apt install glslc.
> 
> you mean cross-compile the riscv binary on x86 ubuntu host ?

Just install glslc on the system which builds your llama.cpp with vulkan. I installed/built successfully with current llama.cpp (including the new cmake scripts for it released on Jul 13) on Ubuntu and on Windows. I just picked the instructions for Ubuntu randomly. The glslc source seems to be https://github.com/google/shaderc

**Comment by yli147** [comment]
> > > Suggestion which might help - install the glslc (Vulkan's shader-compiler) from the Vulkan-SDK - on Ubuntu 24.04 it's apt install glslc.
> > 
> > 
> > you mean cross-compile the riscv binary on x86 ubuntu host ?
> 
> Just install glslc on the system which builds your llama.cpp with vulkan. I installed/built successfully with current llama.cpp (including the new cmake scripts for it released on Jul 13) on Ubuntu for Arm and on Windows for Arm (native builds, not cross-compiled). I just picked the instructions for Ubuntu randomly. The glslc source seems to be https://github.com/google/shaderc

Thanks, will try

**Comment by victorcastro89** [comment]
Same problem, I trying to build from Ubuntu and followed the instructions. sharercs is already installed.

**Comment by yli147** [comment]
> Same problem, I trying to build from Ubuntu and followed the instructions. sharercs is already installed.

Use this commit a977c115448e40856fb9cbe3ceb6d8ce802553b0 to build
