### ISSUE TITLE
Bug: In a small n_ctx_slot, the llama.cpp begins gibberish

### ISSUE THREAD

**Issue by 1cekrim** [ggerganov/llama.cpp#8498]
### What happened?

While testing the Deepseek Coder V2 Lite(https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct) with ollama's default settings(n_ctx 2048), I noticed that the llama.cpp was printing meaningless sentences
After clone the latest llama.cpp, I tested the -c and -np options and found that the model breaks the moment the llama.cpp shifts the slot context at a small ctx length (perhaps if the ctx length is less than about 8192)

### Name and Version

version: 3400 (97bdd26e)
built with cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
llama-server ... -c 16000 -np 4, llama-server ... -c 4000 -np 1, llama-server ... -c 6000 -np 1

As shown below, after the n_keep = 1 log occurs, the model prints garbage infinitely ...

slot context shift | .... n_keep = 1 n_left = 3998 n_discard = 1999 n_ctx=4000 n_past=3999 n_system_tokens=0 n_cache_tokens=2048

If the n_ctx is greater than 8192 as shown below, there is no problem (I haven't tested between 6000~8192)

llama-server ... -c 8192 -np 1, llama-server ... -c 16000 -np 1
```

**Comment by ggerganov** [comment]
DeepSeek V2 models do not support context shift due to MLA. You should never exceed the context size with these models
