### ISSUE TITLE
Faster loading of the model

### ISSUE THREAD

**Issue by kig** [ggerganov/llama.cpp#85]
I was playing with the 65B model, and it took a minute to read the files. If you wrap the model loader loop with a `#pragma omp parallel for` and add `-fopenmp` to the compiler flags, you can drop it to 18 seconds.

**Comment by ggerganov** [comment]
Great idea. We prefer to not use `-fopenmp`.
The implementation should use `#include <thread>`

**Comment by kassane** [comment]
and TBB?
https://github.com/oneapi-src/oneTBB - lic: Apache

I remember that the mold linker project also uses it.

**Comment by ggerganov** [comment]
Not familiar with TBB, but most likely the answer is no

**Comment by kig** [comment]
I have some experiments with optimizing large file read I/O in https://gist.github.com/kig/357a4193be54915d142f1db6063bc929 and https://github.com/kig/fast_read_optimizer if you want to overkill it...
