### ISSUE TITLE
lliblama.so is missing

### ISSUE THREAD

**Issue by Battlehub0x** [ggerganov/llama.cpp#8512]
### What happened?

To build libllama.so on Ubuntu I use the following commands:

mkdir build
cd build
cmake .. -DLLAMA_STATIC=Off -DBUILD_SHARED_LIBS=ON
cmake --build . --config Release

llibllama.so does not seem to be created anymore. 

### Name and Version

llama.cpp --version version: b3389 Ubuntu 22.04

### What operating system are you seeing the problem on?

Linux

**Comment by Battlehub0x** [comment]
It's just in a different folder -> llama.cpp/build/src

**Comment by Manamama** [comment]
Same problem - it is in `llama.cpp/build/src`  : 
```
find . -name libllama.so
./src/libllama.so
./build/src/libllama.so
but then I have to move it to:
```
sudo cp  ./src/libllama.so  /usr/local/lib/
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```
etc by hand. It used not to be the case. (I have compiled it about 10 times before, also for Termux etc.)

**Comment by Manamama** [comment]
Update - oh, it somehow compiled with this Android bit (I copied the git cloned folder from there):
```

:~/Downloads/llama.cpp$ llama-cli --version
version: 4050 (d05b3127)
built with clang version 19.1.3 for aarch64-unknown-linux-android24
:~/Downloads/llama.cpp$ uname -a
Linux above-hp2-silver 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
zezen@above-hp2-silver:~/Downloads/llama.cpp$ 

```
- maybe that is why it does not move the .so file anywhere after `sudo make install` on Unix?
