### ISSUE TITLE
Bug:  GGML_CUDA_FORCE_CUBLAS cannot be compile for hipblas

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#8513]
### What happened?

//ggml: always use cuBLAS instead of mmq kernels
GGML_CUDA_FORCE_CUBLAS:BOOL=ON

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 7900 XTX, compute capability 11.0, VMM: no

without forcing  Rocm with cublas, it would slow down quite a bit in prompt process.
And, I could not compile rocm with force cublas enable.

### Name and Version

.\llama-cli.exe --version
version: 3404 (1666f92d)
built with  for x86_64-pc-windows-msvc

### What operating system are you seeing the problem on?

Windows11
### Relevant log output

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 7900 XTX, compute capability 11.0, VMM: no

**Comment by JohannesGaessler** [comment]
You are correct that the compile flags don't work correctly on master when using HIP but on an RX 7900 XTX hipBLAS should already be used anyways.

**Comment by JohannesGaessler** [comment]
Should be fixed by https://github.com/ggerganov/llama.cpp/pull/8515 , reopen if not.
