### ISSUE TITLE
Newest apple model unsupported...

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8514]
Model: https://huggingface.co/apple/DCLM-Baseline-7B

`python /content/llama.cpp/convert_hf_to_gguf.py --outtype f16 DCLM-Baseline-7B --outfile DCLM-Baseline-7B.f16.gguf`
OpenLMModel is not supported

**Comment by HanClinto** [comment]
What feels notable about this model is that not only are the weights open, but also the [dataset is included](https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0).

**Comment by 0wwafa** [comment]
> What feels notable about this model is that not only are the weights open, but also the [dataset is included](https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0).

yep. but anything else is uninteresting compared to PHI-3 LLAMA-3 and the others..

**Comment by dashan996** [comment]
but true open source including all aspects is appreciated 👍

**Comment by 0wwafa** [comment]
> but true open source including all aspects is appreciated 👍

I agree.
