### ISSUE TITLE
Support for H2O Danube3 Family of Models

### ISSUE THREAD

**Issue by criminact** [ggerganov/llama.cpp#8518]
### Prerequisites

- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

I have tested the GGUF (https://huggingface.co/h2oai/h2o-danube3-500m-chat-GGUF) with Android example from llama.cpp and it is working for me. TTFT and Throughput speed are 🔥 

### Motivation

v v small models to run on edge devices and are on a par with qwen2 (0.5b) and phi-3 (4b)

### Possible Implementation

Should work directly since model arch is LlamaForCausalLM. I will check if it's supported directly without any change. Prompt support might be needed though. 

<|prompt|>Why is drinking water so healthy?</s><|answer|>

I will check these 2 and report back
1. Model Conversion to GGUF
2. Running GGUF model

**Comment by bartowski1182** [comment]
Is there something wrong that isn't supported?

I was able to convert and quant without issue: https://huggingface.co/bartowski/h2o-danube3-4b-chat-GGUF

**Comment by criminact** [comment]
Ah cool. I was gonna test it myself. Didn't get time on it but thank you so much. If quantisation and inferencing works. I will close this.

**Comment by criminact** [comment]
@bartowski1182 Did you happen yo FT the 4b model? or converted the vanilla one?

**Comment by bartowski1182** [comment]
I converted the released chat 4b if that's what you mean?

**Comment by countzero** [comment]
**Note:** Interference works fine without `--flash-attn`, otherwise it crashes with: `ggml\src\ggml-cuda\fattn.cu:144: fatal error`

If flash attention is not compatible with this model architecture, perhaps it can be automatically deactivated?
