### ISSUE TITLE
Running convert-pth-ggml.py on Linux

### ISSUE THREAD

**Issue by linuxmagic-mp** [ggerganov/llama.cpp#852]
A not so obvious error, Using Hugging Face llama-13b-hf as the model, I get a 'no such file' for params.json
(Following README, but don't have a params.json.  Are we supposed to build one? Might want to update README for this situation.

python3.10 convert-pth-to-ggml.py ../llama-13b-hf/ 1

**Comment by Technetium1** [comment]
You didn't make the same directory structure for `models` as it asked, might be important to run in that folder.

**Comment by linuxmagic-mp** [comment]
Yeah, that doesn't make a difference, it looks in the ./models/13B for the file, but the params.json doesn't exist in the llama-13b-hf repo

**Comment by prusnak** [comment]
You need to download the params.json (in another word, download the weights from repository that have the file, not from the ones that haven't).
