### ISSUE TITLE
Feature Request: Architecture "LlavaMistralForCausalLM" not supported!

### ISSUE THREAD

**Issue by dafei2017** [ggerganov/llama.cpp#8533]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Because the model is divided into four parts in https://huggingface.co/microsoft/llava-med-v1.5-mistral-7b/tree/main, the above problems in the process of merging model, how to solve this problem, please?

### Motivation

 python .\convert-hf-to-gguf.py .\llava-med-v1.5-mistral-7b\ --outfile .\llava-med\ Loading model: llava-med-v1.5-mistral-7b Traceback (most recent call last):   File "E:\gyf\offline-model\AR-agent\llama.cpp\convert-hf-to-gguf.py", line 1876, in <module>     main()   File "E:\gyf\offline-model\AR-agent\llama.cpp\convert-hf-to-gguf.py", line 1857, in main     model_instance = model_class(dir_model, ftype_map[args.outtype], fname_out, args.bigendian)   File "E:\gyf\offline-model\AR-agent\llama.cpp\convert-hf-to-gguf.py", line 50, in __init__     self.model_arch = self._get_model_architecture()   File "E:\gyf\offline-model\AR-agent\llama.cpp\convert-hf-to-gguf.py", line 281, in _get_model_architecture     raise NotImplementedError(f'Architecture "{arch}" not supported!') NotImplementedError: Architecture "LlavaMistralForCausalLM" not supported!

**Comment by ccslience** [comment]
I met the same issue

**Comment by ccslience** [comment]
邮件已收到，谢谢~                    张静

**Comment by drzraf** [comment]
Sounds like a valid issue
