### ISSUE TITLE
Bug: python3 convert.py  [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Emmanuel97460** [ggerganov/llama.cpp#8544]
### What happened?

I followed the LangChain documentation to install LLaMA locally, but I am encountering the following error:
[Langchain-doc-link](https://js.langchain.com/v0.2/docs/integrations/llms/llama_cpp/)
Please note that I am using an Asus laptop with an Intel i7 iRISXe processor and 32GB RAM.

### Name and Version

version: 3408 (1bdd8ae1)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
python3 convert.py --outfile models/7B/gguf-llama2-f16.bin --outtype f16 ../../llama2/llama/llama-2-7b --vocab-dir ../../llama2/llama/llama-2-7b
python3: can't open file '/home/myname/Documents/Perso/side-project/ai/models/llama2/llama.cpp/convert.py': [Errno 2] No such file or directory
```

**Comment by Sekinal** [comment]
The `convert.py` script has been deprecated and is no longer recommended for use. While it's still available at `examples/convert_legacy_llama.py`, it only supports models prior to Llama 2. For the most current and recommended quantization process, please refer to the documentation at:

https://github.com/ggerganov/llama.cpp/blob/master/examples/quantize/README.md

This updated guide provides information on the latest quantization methods and tools for Llama models, including support for newer versions like Llama 3, Gemma 2, and so on.
