### ISSUE TITLE
Question: How do I use openblas on M1 apple silicon (or is there any point?)

### ISSUE THREAD

**Issue by dogjamboree** [ggerganov/llama.cpp#857]
I don't quite how to specify the proper make flag for this or whether it even applies to MacOS.

**Comment by cmp-nct** [comment]
OpenBLAS has barely any benefit, it's speeding up prompt ingestion but not token generation.
On M1 you have the accelerate framework built in, I'm quite sure that will be superior

**Comment by dogjamboree** [comment]
> OpenBLAS has barely any benefit, it's speeding up prompt ingestion but not token generation. On M1 you have the accelerate framework built in, I'm quite sure that will be superior

THanks, I'll close this then.
