### ISSUE TITLE
Feature Request: Support llava with different vision/LM backbones

### ISSUE THREAD

**Issue by zucchini-nlp** [ggerganov/llama.cpp#8574]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Hi, I am trying to convert a llava model to GGUF format. The checkpoint is available at `llava-hf/llava-interleave-qwen-0.5b-hf`

I managed to make the scripts from `./examples/llava` work for SigLIP as vision tower and convert the tokenizer for QwenModel. But now trying to run with llama-llava-cli throws an error because some keys from vision tower are absent in SigLIP.

### Motivation

This would help to convert more llava models. Additionally, cool if you can make vision tower conversion model agnostic

### Possible Implementation

none

**Comment by DanialTaheri** [comment]
@ggerganov, Is it possible to have a script that is agnostic to the model in the vision tower conversion? I would like to convert Llava models with Siglip and RADIO encoders to the gguf format. Do you have any suggestions in the meantime?

**Comment by DanialTaheri** [comment]
Hi @zucchini-nlp, did you implement the conversion for the Siglip encoder?

**Comment by zucchini-nlp** [comment]
@DanialTaheri no, I didn't have have much capacity and gguf conversion was near the end of my priority list. I managed to convert but seems ti be buggy as the generation is total garbage

**Comment by weilu4606** [comment]
i encounter the same problem, the llava-hf/llava-interleave-qwen-7b-hf has the vision tower siglip and language tower qwen

**Comment by Threelies** [comment]
Hi! Did you solve the problem? I have the same problem.Are there some keys like [SiglipMultiheadAttentionPoolingHead] in your SigLip vision tower that cause the mismatch?

**Comment by zucchini-nlp** [comment]
No, the interleave model has not "SiglipMultiheadAttentionPoolingHead" and drops one layer from SigLip. I didn't get mismatch but the generation was total garbage so I guess something went wrong in image processing or tokenization
