### ISSUE TITLE
Bug: Multi-NPU execution error

### ISSUE THREAD

**Issue by hipudding** [ggerganov/llama.cpp#8580]
### What happened?

When using CANN as the backend, and using more than one npu card. graph split is not correct causing execution to get stuck.

build cmd: cmake .. -DCMAKE_BUILD_TYPE=debug -DLLAMA_CANN=on && make -j
exec cmd: ./bin/llama-cli  -m /root/qwen2-7b-instruct-fp16.gguf  -ngl 32 --split-mode layer --repeat_penalty 1.0 --color -i  -r "User:" -f ../prompts/chat-with-bob.txt

### Name and Version

version: 3408 (1bdd8ae1)
built with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for aarch64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
here's some logs:

llm_load_tensors: ggml ctx size =    0.45 MiB
llm_load_tensors:        CPU buffer size =  1039.50 MiB
llm_load_tensors:       CANN buffer size =  6668.17 MiB   # CANN0
llm_load_tensors:       CANN buffer size =  6818.60 MiB   # CANN1
........................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:       CANN KV buffer size =   960.00 MiB   # CANN0
llama_kv_cache_init:       CANN KV buffer size =   832.00 MiB   # CANN1
llama_new_context_with_model: KV self size  = 1792.00 MiB, K (f16):  896.00 MiB, V (f16):  896.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.58 MiB
ggml_gallocr_reserve_n: reallocating CANN buffer from size 0.00 MiB to 1884.00 MiB
ggml_gallocr_reserve_n: reallocating CANN buffer from size 0.00 MiB to 0.00 MiB
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 71.01 MiB
llama_new_context_with_model:       CANN compute buffer size =  1884.00 MiB
llama_new_context_with_model:        CPU compute buffer size =    71.01 MiB
llama_new_context_with_model: graph nodes  = 986
llama_new_context_with_model: graph splits = 2        # graph splits is not correct.


this is the end of log, stuck here.
```

**Comment by slaren** [comment]
The issue is likely in the `ggml_backend_cann_supports_buft`. It should only return true when the ggml_backend device and the buffer type device match, otherwise the scheduler will just assign everything to the first backend.

**Comment by hipudding** [comment]
> The issue is likely in the `ggml_backend_cann_supports_buft`. It should only return true when the ggml_backend device and the buffer type device match, otherwise the scheduler will just assign everything to the first backend.

Got it. Thanks.
