### ISSUE TITLE
Bug: export-lora does not accept GGUF files

### ISSUE THREAD

**Issue by suncloudsmoon** [ggerganov/llama.cpp#8581]
### What happened?

After the process of finetuning, a LoRA GGUF is created using ```convert_lora_to_gguf.py``` from transformers. After llama.cpp implemented support for LoRA conversion to GGUF in recent days, the same support hasn't seen extended to export-lora. When I am combining the LoRA GGUF with the base model GGUF, I get a GGML error (see below). This is the command that I used to export lora: ```!/usr/home/llamacpp/llama-export-lora -m /kaggle/working/base-model-f16.gguf -l /kaggle/working/trained-model/ggml-lora-f16.gguf -o /kaggle/working/full-model-finetune-f16.gguf```.

### Name and Version

version: 1 (a15ef8f)
built with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
error: unexpected lora header file magic in '/kaggle/working/trained-model/ggml-lora-f16.gguf
```

**Comment by polodealvarado** [comment]
Same error

**Comment by ngxson** [comment]
`export-lora` example is very out-dated and does not support gguf. It will be rewritten soon.

**Comment by markat1** [comment]
@ngxson so what should we use for merging then? if I can't do `llama-export-lora -l ggml-adapter-model.bin -o merged_model.f16.gguf -m <base  model gguf>` ? [#8594](https://github.com/ggerganov/llama.cpp/discussions/8594)

**Comment by ngxson** [comment]
@markat1 There is an example usage for on the README: https://github.com/ngxson/llama.cpp/blob/xsn/fix_lora_merge/examples/export-lora/README.md

**Comment by markat1** [comment]
@ngxson hope it's okay contacting you again - I really can't find export-lora  
![image](https://github.com/user-attachments/assets/aa8333db-effe-4500-aa86-3110dd3d9b10)

**Comment by markat1** [comment]
@ngxson okay so how do I make the bin file ? I tried with convert lora to gguf but that only makes the gguf (as it prob should) 

`--lora lora-open-llama-3b-v2-q8_0-english2tokipona-chat-LATEST.bin
`
