### ISSUE TITLE
Chinese character decoding error when intract way

### ISSUE THREAD

**Issue by jinfagang** [ggerganov/llama.cpp#86]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/21303438/224645334-fed2e1d7-c858-49c7-b8bc-341fbb01ead3.png">

can not handle Chinese.

**Comment by wizd** [comment]
you can try PR https://github.com/ggerganov/llama.cpp/pull/87

**Comment by prusnak** [comment]
Duplicate of https://github.com/ggerganov/llama.cpp/issues/11
