### ISSUE TITLE
Bug: `-ngl` is missing from server docs for layer offload

### ISSUE THREAD

**Issue by RonanKMcGovern** [ggerganov/llama.cpp#8605]
### What happened?

There's no mention of how to offload layers to gpu

### Name and Version

docs

### What operating system are you seeing the problem on?

Linux

**Comment by wereretot** [comment]
Same issue

**Comment by wereretot** [comment]
@RonanKMcGovern I seem to have fixed the issue. Have you checked that your llama.cpp is complied with CUDA support?

**Comment by RonanKMcGovern** [comment]
Thanks, btw, all is working fine for me, I was just pointing out that the
docs don't explain to include -ngl, cheers
