### ISSUE TITLE
Bug: server is broken by Mistral Nemo commit 

### ISSUE THREAD

**Issue by auriocus** [ggerganov/llama.cpp#8631]
### What happened?

I run the serve with:
`llama-server -m ~/Downloads/Meta-Llama-3-8B-Instruct-v2.Q8_0.gguf -c 4096 --no-mmap`

After commit 50e05353e88d50b644688caa91f5955e8bdb9eb9 nothing happens when a question is posted in the web interface. The CPU is not used. I've used git bisect to verify it comes from that commit.

### Name and Version

```
 ./llama-cli --version
version: 3438 (6f11a83e)
built with gcc-10 (SUSE Linux) 10.4.0 for x86_64-suse-linux

```

**Comment by auriocus** [comment]
Not sure anymore that the issue is inthe commit mentioned above; a second bisect points to a different commit:
```
gollwi01@vier:~/Programmieren/llama.cpp> git bisect bad
940362224d20e35f13aa5fd34a0d937ae57bdf7d is the first bad commit
commit 940362224d20e35f13aa5fd34a0d937ae57bdf7d
Author: Michael Coppola <m18coppola@gmail.com>
Date:   Sat Jul 20 09:43:51 2024 -0400

    llama : add support for Tekken pre-tokenizer (#8579)
    
    * llama : Added support for Tekken pre-tokenizer (#8577)
    
    Removed uneeded `vocab.tokenizer_clean_spaces` assignment
    
    * llama : fix order of pre-tokenizers
    
    * * Tekken pre-tokenizer no longer uses clean_up_tokenization_spaces
    * Updated chkhsh for Tekken tokenizer
    
    ---------
    
    Co-authored-by: Georgi Gerganov <ggerganov@gmail.com>

 convert_hf_to_gguf.py        |  3 +++
 convert_hf_to_gguf_update.py |  1 +
 include/llama.h              |  1 +
 src/llama.cpp                | 13 +++++++++++++
 4 files changed, 18 insertions(+)

```
Maybe it has something to do with cleaning up between the compilation runs. In any case, going back to f17f39ff9cb71fa7b0eda0c649bb0ce9b2d8a6b8 fixes the issue and going forward to HEAD introduces it.

**Comment by ScarletEmerald** [comment]
I am also having this problem.  Bisecting was a huge pain since there seems to be some state preserved between runs, which made the results inconsistent.  However, I am now convinced that the problem was introduced in #0d2c732

That commit breaks both the old and new web UI for llama-server in Firefox on Linux.  Clicking Start or Send in the UI does not cause inferencing to begin.  The web UI continues to work in Chromium on Linux.

**Comment by ggerganov** [comment]
Yes, I also observed this issue and I _think_ that clicking on `"Reset all to default"` button in the UI resolves it

**Comment by auriocus** [comment]
> I am also having this problem. Bisecting was a huge pain since there seems to be some state preserved between runs, which made the results inconsistent. However, I am now convinced that the problem was introduced in [0d2c732](https://github.com/ggerganov/llama.cpp/commit/0d2c7321e9678e91b760ebe57f0d063856bb018b)
> That commit breaks both the old and new web UI for llama-server in Firefox on Linux. Clicking Start or Send in the UI does not cause inferencing to begin. The web UI continues to work in Chromium on Linux.


That makes way more sense to me, thank you! I also can confirm that there is no problem with Chromium. Hitting the "reset all" button did not work, but updating Firefox did work. We are using an extended support release (115.13.0esr  that comes with openSuSE), updating to 128 fixed the problem. So it is more likely a Firefox bug. Also, when observing the traffic in the Firefox Network analyzer, hitting the button in the buggy version does not show any network connection (whereas it does POST to http://127.0.0.1:8080/completion in the working version)

**Comment by auriocus** [comment]
I can confirm that #8646 fixes the issue for me :)
