### ISSUE TITLE
incorrect pkgconfig/llama.pc: Version: 

### ISSUE THREAD

**Issue by vt-alt** [ggerganov/llama.cpp#8639]
### What happened?

`llama.pc` contains incorrect line
```
Version:
```
Resulting  in incorrect `pkg-config --print-provides` output.
```
llama =
```
(This output is actually may be used in downstream distribution(s) when package is generated to auto-detect dependencies.)

I think this is because of `./cmake/llama.pc.in` line:
```
Version: @PROJECT_VERSION@
```
Where `@PROJECT_VERSION@` expanded to the an empty string.

### Name and Version

b3441

### What operating system are you seeing the problem on?

ALT Linux

I also see the same problem line in FreeBSD:14 `llama-cpp-3408.pkg`.

**Comment by angt** [comment]
Here: https://github.com/ggerganov/llama.cpp/pull/11658 :)
