### ISSUE TITLE
Bug: pkgconfig llama.pc packaged into incorrect lib directory

### ISSUE THREAD

**Issue by vt-alt** [ggerganov/llama.cpp#8640]
### What happened?

Currently llama.pc is packaged into `/usr/lib/pkgconfig/llama.pc` which is incorrect location, and it should be packaged into architecture dependent (so called) "libdir".

Proposed patch:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 79370912..1cd49909 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -181,7 +181,7 @@ configure_file(cmake/llama.pc.in
         @ONLY)

 install(FILES "${CMAKE_CURRENT_BINARY_DIR}/llama.pc"
-        DESTINATION lib/pkgconfig)
+        DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)

 #
 # programs, examples and tests
```

### Name and Version

b3441

### What operating system are you seeing the problem on?

ALT Linux

**Comment by angt** [comment]
Here: https://github.com/ggerganov/llama.cpp/pull/11658 :)

**Comment by vt-alt** [comment]
@angt Thanks!
