### ISSUE TITLE
Long time until generation starts when using big context

### ISSUE THREAD

**Issue by CyberTimon** [ggerganov/llama.cpp#865]
When just saying like "Hello, who are you?", I get like 200ms/token and it starts generating almost instantly.
On the other hand, when I paste a small text (e.g. search results from duck duck go api) I have to wait +- 1min and then it generates but quite slow. Is this normal behaviour=

My cpu is a ryzen 7 6800h and 32gb ddr5 ram. I'm running vicuna 7b. 
I paste the search result context from the python bindings.

**Comment by alankila** [comment]
Yes, the self-attention mechanism has quadratic cost. Each input token must be related to every other input token. This means that as context grows, inference speed also drops. Sub-quadratic attention models are current hot topic of research.

**Comment by Baaleos** [comment]
Is there any recommendations for --batch_size

Eg: I observe that --batch_size 8 - will quickly input tokens from a file sequencially.
While --batch_size 32 will enter more tokens from the prompt in a single iteration, however it seems there is a large pause between entering tokens.

I was wondering if there is a number for batch_size at which point you get diminishing returns in terms of speed/efficiency.

Is it better to use a smaller batch_size or a larger one - or does it not really make a difference?

**Comment by CyberTimon** [comment]
So there is no way at the moment to speed up this process?

**Comment by cmp-nct** [comment]
> So there is no way at the moment to speed up this process?

openBLAS (or preferably Intels One library) were said to speed that up. I've not tested it though.

**Comment by Priestru** [comment]
Could anyone explain why this is not an issue on GPU?

**Comment by Priestru** [comment]
GPT and some smart person told me that:

> In natural language processing, there are two main tasks that models are often used for: generating text and evaluating text. While both tasks involve using a neural network to process and interpret language, there are important differences in the way they are approached and the resources required for each task.
> 
> Generating text involves the model creating new text based on some input, such as a prompt or a previous piece of text. This process is inherently sequential because the model must decide on each token one at a time, in order. This means that generating longer pieces of text can be time-consuming and resource-intensive, even with powerful hardware such as GPUs and CPUs.
> 
> In contrast, evaluating text involves the model scoring how well it can predict the next token in a sequence of text, given the previous tokens. This process can be batched, which allows for parallel processing of multiple queries at once. For example, if you have a large number of text snippets that you want to evaluate using the same model, you can batch them together and process them all at once. This can significantly speed up the evaluation process, especially for large datasets.
> 
> In addition to batching, there are other techniques and resources that can be used to optimize the evaluation process. For example, splitting the text into independent context windows and scoring them separately can further improve parallelization. Libraries such as BLAS/cuBLAS and LAPACK, which are often built by processor vendors themselves, can also be used to optimize matrix operations and improve performance. Custom compilers can also be used to generate code that is specifically optimized for a given processor architecture.
> 
> In summary, while both generating and evaluating text involve neural network processing, evaluating text can often be faster and more resource-efficient due to the ability to batch queries and use specialized libraries and compilers. These techniques and resources can help to optimize the evaluation process and enable more efficient natural language processing.

**Comment by SlyEcho** [comment]
> Can we outsource some kind of calculations to GPU? Like make it prepare data in some kind of way that CPU struggles with?

I was experimenting with hipBlas/cuBlas before but the limitation is that all the weights would need to be copied to GPU memory. Maybe I should try again, the BLAS code had a lot of improvements in the meantime...

**Comment by Priestru** [comment]
Textgen webui has option to offload layers on CPU. And what i noticed is that generation speed is absurdly low (like 0.14 t/s) because offloaded weights doesn't use multiple threads, BUT **self-attention** was fast!

`Output generated in 77.97 seconds (0.12 tokens/s, 9 tokens, context 2030)`

Look at this. I measured evaluation by literally counting seconds and evaluation of 2k token context took **14 seconds**. We need either multi-threading for offloaded layers or option for GPU-evaluation. Take a note that GPU had only 18 layers, model didn't fit into it's VRAM at all, yet it managed to produce fast prompt evaluation!

**Comment by Priestru** [comment]
Textgen webui has option to offload layers on CPU. And what i noticed is that generation speed is absurdly low (like 0.14 t/s), but self-attention is quick

Output generated in 77.97 seconds (0.12 tokens/s, 9 tokens, context 2030)

I measured evaluation by counting seconds and evaluation of 2k token context took 14 seconds. In my case model didn't fit into it's VRAM at all.

**Comment by cmp-nct** [comment]
I just spent a couple hours on benchmarking and remembered this issue.
There are two major factors that play a role currently:
1) The entire prompt needs to be processed, this takes a while (as discussed here)
2) If you use the memory and performance enhanced version using mmap() then the current version will load the model during first inference. This can take a long time depending on your disk and model size.
I've a pull request up, it's not fully tested for all cases (or on linux) which will shift that waiting time to the loading area again.
(https://github.com/ggerganov/llama.cpp/pull/869)
You'll not win any performance that way, but if you use mmap the loading is mixed with inference without that.

**Comment by Bloob-beep** [comment]
I heard from an issue thread long ago that it's not suppose to behave like this, it should be able to understand context pretty quickly.

Is it possible to fix? Or is it just the law of how CPUs work that it will be this slow forever?

**Comment by CyberTimon** [comment]
Closing as this is just how cpu's work
