### ISSUE TITLE
Bug:  train-text-from-scratch

### ISSUE THREAD

**Issue by artiomborovinskii** [ggerganov/llama.cpp#8662]
### What happened?

When I try ./bin/train-text-from-scratch --vocab-model ../models/ggml-vocab-phi-3.gguf --checkpoint-in FN I have normal start but they it write only"----------------------------------------------------------------------------" to terminal

### Name and Version

./bin/main --version                         version: 3044 (d5c05821)                                                    built with clang version 18.1.7 for aarch64-unknown-linux-android24

### What operating system are you seeing the problem on?

Linux

**Comment by ngxson** [comment]
`train-text-from-scratch` only works with llama architecture. Also, it's unmaintained for quite a long time, so probably it's already broken.

@slaren do you think we should temporary remove it?

**Comment by slaren** [comment]
I don't think the training examples are useful enough to justify the maintenance cost, but that's really up to @ggerganov.

**Comment by ggerganov** [comment]
I've also been thinking that we should probably remove them for now and reimplement at a later point when we are able to maintain them

**Comment by ngxson** [comment]
I'm closing this as we decided to temporary remove training / fine-tuning example
