### ISSUE TITLE
Feature Request: Multi core support for full GPU offload

### ISSUE THREAD

**Issue by 8XXD8** [ggerganov/llama.cpp#8684]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

When the entire model is offloaded to the GPU, llama.cpp will only use a single thread, regardless of the `--threads` argument.
On systems with lower single core performance this holds back GPU utilization.
I have noticed, that using RPC on localhost increased my token generation speed by ~30%.

**`HIP_VISIBLE_DEVICES=0 ./llama-bench -m /home/user/text-generation-webui/models/Meta-Llama-3-8B-Instruct-Q8_0.gguf`**
  Device 0: AMD Radeon (TM) Pro VII, compute capability 9.0, VMM: no
| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  99 |         pp512 |    230.09 ± 0.07 |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  99 |         tg128 |     37.14 ± 0.13 |

With `rpc-server` running on the same GPU:
**`HIP_VISIBLE_DEVICES=0 ./rpc-server -p 50052`**
**`HIP_VISIBLE_DEVICES=0 ./llama-bench -m /home/user/text-generation-webui/models/Meta-Llama-3-8B-Instruct-Q8_0.gguf --rpc 0.0.0.0:50052`**
| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA+RPC   |  99 |         pp512 |    231.96 ± 0.09 |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA+RPC   |  99 |         tg128 |     48.40 ± 0.41 |

When offloading a single layer to the CPU, `llama-bench` will use more threads, increasing performance:
**`HIP_VISIBLE_DEVICES=0 ./llama-bench -m /home/user/text-generation-webui/models/Meta-Llama-3-8B-Instruct-Q8_0.gguf -ngl 32 --threads 32`**
| model                          |       size |     params | backend    | ngl | threads |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | ------------: | ---------------: |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  32 |      32 |         pp512 |    231.93 ± 0.08 |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  32 |      32 |         tg128 |     46.72 ± 0.41 |

This problem limits multi GPU performance too, `row split` uses two threads, but 2 GPUs peg the cores at 100% and a third GPU reduces token generation speed.

### Motivation

Servers or older CPUs have many cores, but low boost clocks, and a single thread can not reach full GPU utilization

### Possible Implementation

Enable the `--threads` argument for full GPU offload

**Comment by JohannesGaessler** [comment]
There is no benefit to using more than a single thread with maximum GPU layers, they would just spin uselessly. Multiple threads are only useful and enabled if some of the numerical calculations are done one the CPU.

**Comment by 8XXD8** [comment]
If I run the benchmark, or any other example, just on GPU 0, one thread is at 100%, when the load is split between the RPC backend on GPU 0 and the benchmark on the same GPU, there are two threads at 60-80%, and I get +30% token generation speed.

I have an EPYC CPU, and the max boost clock is only 3500Mhz. There must be a point where a single core just does not have enough performace.

I have 4 GPUs, and a fully offloaded model is slower with both layer or row split, compared to running 4 local RPC servers.

**Comment by JohannesGaessler** [comment]
On my machine with an Epyc 7742, 8x 3200 MHz RAM, and an RTX 4090 I get worse `llama-bench` results with RPC.

**Comment by 8XXD8** [comment]
I did another test with a HIP RPC server, and a CPU only build of `llama-bech`, and I still got more performance.
Maybe this is HIP thing, AMD seems to be very unpopular so it is not suprising no one else has this problem.

A long time ago `--threads` worked with full GPU offload I'll test an old build when I get back home.

**Comment by JohannesGaessler** [comment]
>A long time ago --threads worked with full GPU offload I'll test an old build when I get back home.

Yes, and back then the threads were just spinning uselessly.

**Comment by x0rb0t** [comment]
I also have somewhat similar issue, when I run llama-server on 4090 RTX it uses GPU approx by 36% max and uses only single cpu core of 32. But as far as I remember on some older versions it uses GPU by 100% and more then single thread. Is there a way to utilize GPU by 100%?

**Comment by x0rb0t** [comment]
<img width="653" alt="Снимок экрана 2024-07-26 в 22 08 34" src="https://github.com/user-attachments/assets/e5aa276e-eb8f-4c63-b6b8-5a50ba3707fe">
This is my GPU Utility for llama 3.1 inference

**Comment by JohannesGaessler** [comment]
I am making the negative statement that there is no mechanism, neither in CUDA/HIP nor in llama.cpp/GGML, by which more than one thread could be utilized for useful work, therefore it is impossible to get benefit from multiple threads. The burden of proof is on the side that would want to show that such a mechanism exists.

**Comment by slaren** [comment]
I don't think there is anything to add here. If you have an idea for using multiple threads with CUDA, feel free to open a PR.

**Comment by JohannesGaessler** [comment]
I am in fact not putting a lot of effort into arguments in Github issues based on fundamental misunderstandings of the code. I narrowed the scope in my second post because I wrote the first post in thirty seconds. In the context of someone reporting supposedly better performance with multiple threads there is simply no way that the threads are doing any useful work. Therefore it's the measurement that's wrong. This is quite obvious with a basic understanding of CUDA and the llama.cpp/ggml code. And given my practical experience and my knowledge after reading the CUDA/PTX documentation I don't see how multiple threads could be utilized for better performance either. The basic way that CUDA works is to queue work on the GPU using CPU threads and to then make the CPU threads wait until the GPU is done. Even with a single thread the CPU will spend most of its time spinning and waiting for the GPU to be done. 

>So I ask of your new positive claim, proof?

https://github.com/ggerganov/llama.cpp

https://docs.nvidia.com/cuda/

**Comment by 8XXD8** [comment]
I did more testing, and yes, it's not related to a single thread being saturated.
If I ` taskset -c ` both the rpc-server and the host to the same core, I still get more performance:

`HIP_VISIBLE_DEVICES=0 taskset -c 0 ./llama-cli -m  /.../models/Meta-Llama-3-8B-Instruct-Q8_0.gguf -p "Tell a joke" --ignore-eos -s 1 -c 1024 -ngl 99 -n 128`

> llama_print_timings:      sample time =       6.39 ms /   128 runs   (    0.05 ms per token, 20031.30 tokens per second)
> llama_print_timings: prompt eval time =      42.98 ms /     4 tokens (   10.74 ms per token,    93.08 tokens per second)
> llama_print_timings:        eval time =    3575.70 ms /   127 runs   (   28.16 ms per token,    **35.52 tokens per second**)
> llama_print_timings:       total time =    3636.99 ms /   131 tokens

Now with rpc:
`HIP_VISIBLE_DEVICES=0 taskset -c 0 ./rpc-server -p 50052`
`HIP_VISIBLE_DEVICES=0 taskset -c 0 ./llama-cli -m  /.../Meta-Llama-3-8B-Instruct-Q8_0.gguf -p "Tell a joke" --ignore-eos -s 1 -c 1024 -ngl 99 -n 128 --rpc 0.0.0.0:50052`

> llama_print_timings:      sample time =       6.32 ms /   128 runs   (    0.05 ms per token, 20240.35 tokens per second)
> llama_print_timings: prompt eval time =      36.21 ms /     4 tokens (    9.05 ms per token,   110.47 tokens per second)
> llama_print_timings:        eval time =    2569.25 ms /   127 runs   (   20.23 ms per token,    **49.43 tokens per second**)
> llama_print_timings:       total time =    2623.64 ms /   131 tokens

There is definitely a difference in utilization, The GPU draws more power with RPC, and even the sound is different, silent with RPC, coil whine without RPC:
This could be user error, I just don't know what I'm doing wrong.

**Comment by 8XXD8** [comment]
Disabling memory mapping solves it.
`HIP_VISIBLE_DEVICES=0 ./llama-cli -m  /home/user/text-generation-webui/models/Meta-Llama-3-8B-Instruct-Q8_0.gguf -p "Tell a joke" --ignore-eos -s 1 -c 1024 -ngl 99 -n 128 --no-mmap`

> llama_print_timings:      sample time =       6.71 ms /   128 runs   (    0.05 ms per token, 19087.38 tokens per second)
> llama_print_timings: prompt eval time =      34.80 ms /     4 tokens (    8.70 ms per token,   114.94 tokens per second)
> llama_print_timings:        eval time =    2439.47 ms /   127 runs   (   19.21 ms per token,    **52.06 tokens per second**)
> llama_print_timings:       total time =    2493.75 ms /   131 tokens

I'm not familiar with memory mapping, so I don't know if this is a bug or expected behavior.

**Comment by JohannesGaessler** [comment]
I am not able to reproduce a difference from mmap on Linux using an RTX 3090:

| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| llama 8B Q4_0                  |   4.33 GiB |     8.03 B | CUDA       |  99 |    0 |         pp512 |  4724.69 ± 20.61 |
| llama 8B Q4_0                  |   4.33 GiB |     8.03 B | CUDA       |  99 |    0 |         tg128 |    132.60 ± 0.20 |
| llama 8B Q4_0                  |   4.33 GiB |     8.03 B | CUDA       |  99 |    1 |         pp512 |  4687.80 ± 16.91 |
| llama 8B Q4_0                  |   4.33 GiB |     8.03 B | CUDA       |  99 |    1 |         tg128 |    132.14 ± 0.15 |

The small difference here is simply due to the GPU heating up; if you reverse the order it is still the second run that will be slightly slower.

What operating system are you on?

**Comment by 8XXD8** [comment]
I'm on Debian linux, with the 6.10.1 kernel, and rocm 6.1.2.
I think there is a bug with `llama-bench` when I use comma separated parameters for the `--mmap` argument.
`--mmap 0,1`
  Device 0: AMD Radeon (TM) Pro VII, compute capability 9.0, VMM: no
| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    0 |         pp512 |    304.20 ± 0.09 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    0 |         tg128 |     75.97 ± 0.04 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    1 |         pp512 |    304.22 ± 0.10 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    1 |         tg128 |     75.83 ± 0.03 |

`--mmap 0`
| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    0 |         pp512 |    303.80 ± 0.20 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |    0 |         tg128 |     75.14 ± 0.07 |

`--mmap 1`
| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |         pp512 |    300.66 ± 0.12 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CUDA       |  99 |         tg128 |     47.86 ± 0.15 |

I feel like your Rx 6800 is affected, with `--mmap 0` and Q8 model I have almost the same tg speed as you with Q4

| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  99 |    0 |         pp512 |    232.23 ± 0.06 |
| llama 8B Q8_0                  |   7.95 GiB |     8.03 B | CUDA       |  99 |    0 |         tg128 |     52.73 ± 0.06 |

build: 2b1f616b (3468)

**Comment by JohannesGaessler** [comment]
I still get the same RX 6800 performance if I do two separate `llama-bench` runs.

**Comment by 8XXD8** [comment]
On my system, this started with `build: ccf58aa3 (2475)`
 model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | pp 512     |    532.53 ± 0.31 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | tg 128     |     78.41 ± 0.08 |

build: 91f8ad16 (2474)

 model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | pp 512     |    513.71 ± 1.30 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | tg 128     |     50.13 ± 0.05 |

build: ccf58aa3 (2475)

But  `--no-mmap` had no positive effect until `build = 3167 (6a2f0b34)`

I think `llama-cli` with a fixed seed is better for benchmarking, I had problems with `llama-bench` before.

`build = 3166 (21be9cab) without --no-mmap`
> llama_print_timings:        eval time =    2466.50 ms /   127 runs   (   19.42 ms per token,    **51.49 tokens per second**)

`build = 3166 (21be9cab) with --no-mmap`
> llama_print_timings:        eval time =    2477.16 ms /   127 runs   (   19.51 ms per token,    **51.27 tokens per second**)build = 31

`build = 3167 (6a2f0b34) without --no-mmap`
> llama_print_timings:        eval time =    2466.83 ms /   127 runs   (   19.42 ms per token,    **51.48 tokens per second**)

`build = 3167 (6a2f0b34) with --no-mmap`
> llama_print_timings:        eval time =    1550.37 ms /   127 runs   (   12.21 ms per token,    **81.92 tokens per second**)

**Comment by slaren** [comment]
I don't think there is any issue with `llama-bench`. You would have to investigate yourself why the results are so inconsistent in your system.

**Comment by lee-b** [comment]
I'm not very knowledgeable on this topic admittedly, but wouldn't it make sense to allocate one CPU per card (or per pair of cards), and use that CPU core and its cache to copy between the PCIe cards and/or the system RAM, to enforce affinity and avoid cache misses?  I actually thought that's what llama.cpp does in GPU mode, as I see 4 processes/threads running, and I have 4 cards.

Even if there is only one thread/process used, CPU affinity would probably help to avoid cache misses with the OS scheduler moving the process to the lead busy core and the cache having to start over.

**Comment by Readon** [comment]
> I also have somewhat similar issue, when I run llama-server on 4090 RTX it uses GPU approx by 36% max and uses only single cpu core of 32. But as far as I remember on some older versions it used GPU by 100% and more then single thread. Is there a way to utilize GPU by 100%?

I met this problem too. Do you know on which version the GPU can run on 100% load?
