### ISSUE TITLE
Bug: Unable to compile, either make or cmake

### ISSUE THREAD

**Issue by yuanzhiyong1999** [ggerganov/llama.cpp#8700]
### What happened?

I can't compile llama.cpp correctly. Whether I use the make method or the cmake method, there will be different errors. I have also tried multiple gcc versions, but none of them work.
![image](https://github.com/user-attachments/assets/bb68a6b1-d07d-4b63-b16f-f9bc6af43728)
![image](https://github.com/user-attachments/assets/913373ad-def2-4e69-b76f-f7f2e7e5e148)

### Name and Version

linux

### What operating system are you seeing the problem on?

Linux

**Comment by hezirel** [comment]
I had that same issue

Use gcc-11 and set your CC and CXX env variable to point towards the right binaries on your machine
