### ISSUE TITLE
Bug: Cannot install using Cmake

### ISSUE THREAD

**Issue by windowsagent** [ggerganov/llama.cpp#8701]
### What happened?

When trying to run 'cmake --install'

-- Install configuration: "Release"
CMake Error at build/ggml/cmake_install.cmake:51 (file):
  file INSTALL cannot find
  "/home/knox/Workspace/Work/Aur/llama-cpp/src/llama.cpp/build/ggml/src/CMakeFiles/CMakeRelink.dir/libggml.so":
  No such file or directory.
Call Stack (most recent call first):
  build/cmake_install.cmake:47 (include)

### Name and Version

Commit 01aec4a on master branch

### What operating system are you seeing the problem on?

Linux

**Comment by Septa2112** [comment]
Hi! I tried to reproduce your error but failed. 
Here are my steps and successfully executed without any errors.
```bash
cd llama.cpp
cmake -B build
cmake --build build --config Release -j
cmake --install ./build/ --prefix ./install-test
```
Could you show more details about your issue?

**Comment by hylipiessa** [comment]
I hit this same issue with commit 6e02327 .
system is running with cmake version 3.30.2
