### ISSUE TITLE
Add lightweight tests for LoRA

### ISSUE THREAD

**Issue by ngxson** [ggerganov/llama.cpp#8708]
Ref: https://github.com/ggerganov/llama.cpp/pull/8687#issuecomment-2252155218  
(cc @ggerganov)

TODO:
- Train some adapters based on stories15M and [stories15M_MOE](https://huggingface.co/ngxson/stories15M_MOE)
- Test with `llama-cli -m base_model.gguf --lora lora_adapter.gguf`
- Test merging using `llama-export-lora`, then re-run the merged.gguf to verify it outputs the same thing as above

Optionally: make some small stories model with different arch, for example gemma, phi,...

**Comment by ngxson** [comment]
I'll need time to trainings some adapters for testing (maybe I'll extend it to test other architectures than llama), so I created this TODO for tracking

**Comment by ltoniazzi** [comment]
Hi! I'd be happy to help with this issue, is there anything I start working on? Like writing the test script or training the gguf adapters?

**Comment by ngxson** [comment]
Part of this task will be done with #8857 where I will do a simple lora hotswap test.

The training part will be a bit tricky so it would be nice if you can help. What's missing now is to test with other arch like gemma, phi3, etc. This requires doing these steps:
1. Take the same arch from base model (the HF transformer model)
2. Replace all tensors with smaller one, initialize them to random
3. Train model on bed time story dataset (we expect to overfit the model)
4. Make lora adapter, then overfit the adapter with shakespeare dataset 

The goal is to have overfitted models smaller than 50MB in size, which will be useful to be used in CI test.

Because models are overfitted, we expect it to output the same thing everytime. If it's not, then we have problem in the code.

**Comment by ltoniazzi** [comment]
> Part of this task will be done with #8857 where I will do a simple lora hotswap test.
> 
> The training part will be a bit tricky so it would be nice if you can help. What's missing now is to test with other arch like gemma, phi3, etc. This requires doing these steps:
> 
> 1. Take the same arch from base model (the HF transformer model)
> 2. Replace all tensors with smaller one, initialize them to random
> 3. Train model on bed time story dataset (we expect to overfit the model)
> 4. Make lora adapter, then overfit the adapter with shakespeare dataset
> 
> The goal is to have overfitted models smaller than 50MB in size, which will be useful to be used in CI test.
> 
> Because models are overfitted, we expect it to output the same thing everytime. If it's not, then we have problem in the code.

@ngxson I'm almost there with Gemma-2. Namely:
- Replaced matrices in gemma-2-2b with small ones
- trained a lora adapter on shakespear.txt
- converted both the small gemma and it's adapter to gguf
- run `llama-cli `with `--lora` flag.

Only issue is that in the last step the output quality does not seem to be using the adapter (though a first debugging suggests llama-cli is using the adapter successfully). I need a bit more time to figure this out.

In the meantime, how should I organise this code and files?

Like put the model shrinking conversion scripts in a github repo and upload the gguf files to my huggingface account?

**Comment by ltoniazzi** [comment]
@ngxson **Quick update**: 
-> made gemma-2 small 
-> trained it to learn to reproduce 1 paragraph from shakespeare 
-> trained a lora on top to reproduce lyrics from a song. (Training on cpu/f32)

Inference:
- Running in torch: both base and base+adapter reproduce the respective exact text they are trained on ✅.

- Running base in llama.cpp: convert base to gguf/f32 -> reproduces something close to the exact text but a little messy (if convert to f16 then would just be gibberish) ✅/❌

- Running lora in llama.cpp: convert lora to gguf/f32: then `llama-cli -m base.gguf --lora adapter.gguf` returns gibberish! ❌

As many things could be going wrong, I wanted to check first that the layer's weights in safetensor are the same in gguf. I am using [this code to print weights](https://github.com/ggerganov/ggml/blob/master/examples/simple/simple-backend.cpp#L196), but the printed weights are of order `e-20`, which makes me think something that is not float is being casted to a float. 

**Question**: how do I print out the ggml tensor's weights?

**Comment by ngxson** [comment]
Nice, thanks for the info.

> **Question**: how do I print out the ggml tensor's weights?

You can maybe have a look at `gguf_dump.py` and modify the python code to print tensor data.

Another option is to use `transformers` to load gguf: https://huggingface.co/docs/transformers/en/gguf
