### ISSUE TITLE
Bug: gguf_set_metadata.py unable to edit tokenizer.chat_template metadata

### ISSUE THREAD

**Issue by ThomasBaruzier** [ggerganov/llama.cpp#8768]
### What happened?

Llama 3.1 just got a new prompt template: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/53

I tried to use gguf_set_metadata.py to update these changes. Unfortunately, I am greeted with the following error:
```
INFO:gguf-set-metadata:* Loading: /home/tyra/Meta-Llama-3.1-8B-Instruct-Q4_0.gguf
ERROR:gguf-set-metadata:! This tool only supports changing simple values, 'tokenizer.chat_template' has unsupported type [<GGUFValueType.STRING: 8>]
```

This looks intentional. However, it should be possible to edit this new metadata without having to requantize everything, or else, this would be very inconvenient.

### Name and Version

version: 1 (c887d8b)
built with cc (GCC) 14.1.1 20240720 for x86_64-pc-linux-gnu

### What operating system are you seeing the problem on?

Linux

**Comment by CISC** [comment]
Since metadata is located at the beginning of the file it's not possible to make metadata changes in-place that will grow/shrink its size, you have to make a copy with the new/updated metadata instead, to do this use the `gguf_new_metadata.py` script instead.
