### ISSUE TITLE
[User] Booting the avx512 version

### ISSUE THREAD

**Issue by chille9** [ggerganov/llama.cpp#879]
# Prerequisites
# Expected Behavior

This may be a stupid question since im new to this, but I really enjoy the software thus far. I can run my start.bat file for avx2 using this code:

"title llama.cpp
:start
main -i --interactive-first -r "### Human:" --temp 0 -c 2048 -n -1 --ignore-eos --repeat_penalty 1.2 --instruct -m ggml-gpt4x-alpaca-unfiltered-q4_1.bin
pause
goto start"

# Current Behavior

But if i run the avx512 the same start.bat file don´t work. Probably ive overlooked something simple here. I couldnt find too much info on how to run this version on here.

# Environment and Context 

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware:
Running windows with an Intel core i5 10600k

# Logs

"llama>pause
Press any key to continue . . ."

**Comment by CRD716** [comment]
That CPU does not support AVX512.
