### ISSUE TITLE
How to convert a finetuned non-LLM model in .pt format into .gguf? #8790

### ISSUE THREAD

**Issue by ElaineWu66** [ggerganov/llama.cpp#8791]
As asked in the title, is there any way to convert a .pkl model into .gguf directly?

_Originally posted by @ElaineWu66 in https://github.com/ggerganov/llama.cpp/discussions/8790_

**Comment by ngxson** [comment]
AFAIK it's not possible to directly do such conversion. You must first convert it to safetensors (make sure your model is loadable using `transformers` library), then convert to gguf.

In short, if it works with `transformers`, then there's high chance you can convert it to gguf.

**Comment by ElaineWu66** [comment]
> AFAIK it's not possible to directly do such conversion. You must first convert it to safetensors (make sure your model is loadable using `transformers` library), then convert to gguf.
> 
> In short, if it works with `transformers`, then there's high chance you can convert it to gguf.

Got it. If the model is not loadable with transformers library can I still convert it? Say I have a model with a self-defined architecture (NOT transformer based, not using transformers library)

**Comment by ggerganov** [comment]
Take a look at the Magika example: https://github.com/ggerganov/ggml/tree/master/examples/magika

It demonstrates conversion of a H5 model to GGUF format which you can adapt to your needs + a basic inference program

**Comment by ngxson** [comment]
> Say I have a model with a self-defined architecture 

Please note that if the arch is not already supported by by llama.cpp, you may need to include your own compute graph in cpp code.

To convert weight to gguf, you can use gguf_write class in gguf_py (example above)
