### ISSUE TITLE
Bug: Cloudrun deployment fails when llama.cpp is built with an 12th Gen Intel(R) Core(TM) i7-1260P processor

### ISSUE THREAD

**Issue by MarioSimou** [ggerganov/llama.cpp#8799]
### What happened?

Initially, I believed the problem was connected to `node-llama-cpp`, which I documented in this [github issue](https://github.com/withcatai/node-llama-cpp/issues/277). However, upon further investigation, I discovered that the executables created from llama.cpp were failing on Google Cloudrun due to compatibility issues with the processor. Specifically, when I was building the docker image using a 12th Gen Intel(R) Core(TM) i7-1260P processor, the service was failing with a `503 Service Unavailable` error.

For additional information regarding this issue, please refer to [this](https://github.com/withcatai/node-llama-cpp/issues/277) link.

### Name and Version

release `b3465`

### What operating system are you seeing the problem on?

Linux

**Comment by HanClinto** [comment]
> For additional information regarding this issue, please refer to this link: [link].

I think something got missed in a copy/paste -- do you have another reference to link us to here?

**Comment by MarioSimou** [comment]
Yea, my bad. I have updated the issue
