### ISSUE TITLE
Use aligned_alloc() if aligned allocations are required

### ISSUE THREAD

**Issue by Rhialto** [ggerganov/llama.cpp#880]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

quantize should run and not abort with an assertion failure

# Current Behavior

```
GGML_ASSERT: ggml.c:2990: ((uintptr_t) (ctx->mem_buffer))%GGML_MEM_ALIGN == 0
Abort trap (core dumped)
```
# Environment and Context 

* Operating System

NetBSD 9.3

# Failure Information (for bugs)

The memory allocated by malloc is alingned to 8, not 16 (GGML_MEM_ALIGN)

# Fix:

```
diff --git a/ggml.c b/ggml.c
index 326b8e8..efa3f15 100644
--- a/ggml.c
+++ b/ggml.c
@@ -2974,7 +2974,7 @@ struct ggml_context * ggml_init(struct ggml_init_params params) {
 
     *ctx = (struct ggml_context) {
         /*.mem_size           =*/ params.mem_size,
-        /*.mem_buffer         =*/ params.mem_buffer ? params.mem_buffer : malloc(params.mem_size),
+        /*.mem_buffer         =*/ params.mem_buffer ? params.mem_buffer : aligned_alloc(GGML_MEM_ALIGN , params.mem_size),
         /*.mem_buffer_owned   =*/ params.mem_buffer ? false : true,
         /*.no_alloc           =*/ params.no_alloc,
         /*.n_objects          =*/ 0,
```

**Comment by prusnak** [comment]
The proposed fix does not work on Windows (MSVC), since it does not implement `aligned_alloc`.

**Comment by j-f1** [comment]
Specifically, you’d need to use `_aligned_malloc` on Windows, and then make sure to use `_aligned_free` to free the buffer, also making sure to use `_aligned_realloc` if `realloc` is ever used.

**Comment by prusnak** [comment]
> Specifically, you’d need to use ...

Thanks! Created https://github.com/ggerganov/llama.cpp/pull/884

@Rhialto can you please check this fixes the issue for you?

**Comment by Rhialto** [comment]
@prusnak Yes thanks! That works for me!
