### ISSUE TITLE
Bug: No such file or directory 'consolidated.00.pth' (in "GGUF my repo" space)

### ISSUE THREAD

**Issue by kaetemi** [ggerganov/llama.cpp#8802]
### What happened?

Keep getting error when quantizing `meta-llama/Meta-Llama-3.1-8B` through the "GGUF my repo" space. This seems to start happening at some point and then keeps happening for that specific repo.

@Vaibhavs10 

### Name and Version

https://huggingface.co/spaces/ggml-org/gguf-my-repo

### Relevant log output

```shell
Error: [Errno 2] No such file or directory: 'Meta-Llama-3.1-8B/original/consolidated.00.pth'
```

**Comment by Vaibhavs10** [comment]
Hey @kaetemi - I looked at it again, it's weird that this happens for 8B and not for 8B-Instruct!
I'll look into it in more detail, now!

**Comment by Vaibhavs10** [comment]
I tried again and it worked, so it could be a transient error. Will keep an eye out!

https://huggingface.co/reach-vb/Meta-Llama-3.1-8B-Q2_K-GGUF

**Comment by kaetemi** [comment]
@Vaibhavs10 Still happening. Seems to trigger after using imatrix quantization on a repo and then trying that same repo again with another calibration file.

**Comment by kaetemi** [comment]
@Vaibhavs10 Also, make a copy of the space to get around it, but it's not working anymore as of today with error `/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/components/login_button.py:79: UserWarning: LoginButton created outside of a Blocks context. May not work unless you call its activate() method manually.` - the login button ends up with a "too many redirects" error
