### ISSUE TITLE
Feature Request: Multiple PPL calculation methods

### ISSUE THREAD

**Issue by yan-zh** [ggerganov/llama.cpp#8809]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Hope llama.cpp can support multiple PPL calculation methods.

### Motivation

Llama.cpp is an excellent project that can be used for edge deployment of various models. However, when deploying the quantitative models proposed in some papers, it is difficult to evaluate whether the deployment is successful because the ppl calculation method adopted by llama.cpp is different from the calculation method of the code provided in the paper. Therefore, it is hoped that llama.cpp can support multiple PPL calculation methods and adapt to PPLs in various paper codes.

**Comment by JohannesGaessler** [comment]
Even with an exact reproduction of the PPL calculation method used in papers/other projects the numerical results would not be bit-for-bit identical because the model evaluations themselves are different. Are the current results equivalent to those published in papers within the uncertainty provided by llama.cpp?

**Comment by yan-zh** [comment]
> Even with an exact reproduction of the PPL calculation method used in papers/other projects the numerical results would not be bit-for-bit identical because the model evaluations themselves are different. Are the current results equivalent to those published in papers within the uncertainty provided by llama.cpp?

The computation of PPL seems to involve cutting the input dataset into multiple chunks and inference, and there are many different ways to cut and process each chunk. For example, in the paper code provided by the author of omniquant（ https://arxiv.org/abs/2308.13137 ， https://github.com/OpenGVLab/OmniQuant ）, the model  inferences from scratch of each chunk, but in llama.cpp, the model inferences from the middle of each chunk. Therefore, the PPL measured by llama. cpp was 5.08, and the PPL measured by omniquant was 5.47. Would you consider adding some parameters to the computing of PPL so that users can easily modify the PPL calculation method to adapt to different quantization programs and verify the correctness of deployment. It is believed that only similar PPL calculations are enough to obtain similar results, without the need for a completely consistent calculation.
