### ISSUE TITLE
Feature Request: Bare metal build

### ISSUE THREAD

**Issue by grigohas** [ggerganov/llama.cpp#8820]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Hello, i want to ask if it is possible to build llama in bare metal mode and if it is, can someone help me ?

### Motivation

i need to run llama in bare metal

**Comment by AngLi666** [comment]
I met the same issue. Did you successfully build a baremetal exectuable file? May you share your idea?
