### ISSUE TITLE
Feature Request: InternVL2 Support ?

### ISSUE THREAD

**Issue by Jeremy-J-J** [ggerganov/llama.cpp#8848]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

InternVL2 Supportted Now ?

### Motivation

InternVL2 Supportted Now ?

**Comment by AlexM4H** [comment]
Since yesterday vllm has internVL2 support. :-)

[vllm-project/vllm/releases/tag/v0.6.1](https://github.com/vllm-project/vllm/releases/tag/v0.6.1)

**Comment by cloudyuyuyu** [comment]
any update?

**Comment by cloudyuyuyu** [comment]
any update? thank in advance

please do not close this issue
