### ISSUE TITLE
Bug: SYCL release not working on intel i7 8665U iGPU UHD Graphics 620

### ISSUE THREAD

**Issue by phly95** [ggerganov/llama.cpp#8859]
### What happened?

Whenever I try to run a llama.cpp llama-cli from the sin-sycl-x64 build on the intel i7 8665U, it outputs nothing and just returns right back to the shell, for example:

.\llama-b3509-bin-win-sycl-x64> .\llama-cli -m your_model.gguf -p "Write a story about a princess" -n 128 -t 16
.\llama-b3509-bin-win-sycl-x64>

This is on Windows 11. I already installed the oneAPI as instructed here: https://www.intel.com/content/www/us/en/developer/articles/technical/run-llms-on-gpus-using-llama-cpp.html

### Name and Version

version is b3509. Can't run llama-cli

### What operating system are you seeing the problem on?

Windows

**Comment by NeoZhangJianyu** [comment]
This iGPU is in 8th Core CPU, too old.
I'm not sure it support oneAPI/SYCL.
Even if it can run llama.cpp, the speed will be lower than CPU.

I don't suggest run llama.cpp on this iGPU.

**Comment by gardner** [comment]
Intel doesn't support SYSCL backend for i7 8665U.

They claim support in:

> iGPU in 11th, 12th, and 13th Gen Intel Core CPUs

From: https://www.intel.com/content/www/us/en/developer/articles/technical/run-llms-on-gpus-using-llama-cpp.html

**Comment by phly95** [comment]
> Intel doesn't support SYSCL backend for i7 8665U.
> 
> They claim support in:
> 
> > iGPU in 11th, 12th, and 13th Gen Intel Core CPUs
> 
> From: https://www.intel.com/content/www/us/en/developer/articles/technical/run-llms-on-gpus-using-llama-cpp.html

They do say "The SYCL backend supports all Intel GPUs." and that they've verified with 11th Gen+. Perhaps their documentation is wrong or poorly worded. In fact, all Intel GPUs would technically mean Intel HD Graphics 4000.

**Comment by phly95** [comment]
What is interesting is that with even with Vulkan, the models perform way better when running on the CPU compared to running on the GPU. So I guess the GPU in this system may be weaker than the CPU from an overall speed perspective, or it's some shared memory bottleneck. I was mainly curious if using OneAPI would overcome this, but it seems that people at Intel didn't even consider someone would try running it on old iGPUs.

**Comment by NeoZhangJianyu** [comment]
oneAPI support the iGPU from Gen9.
We have no same generation of your CPU.
It limits to verify and trouble shooting.

if you want to try, please follow the guide https://github.com/ggerganov/llama.cpp/blob/master/docs/backend/SYCL.md.

**Comment by phly95** [comment]
Ok, I found the page that documents that 10th Gen and older not being supported. https://www.intel.com/content/www/us/en/developer/articles/system-requirements/vtune-profiler-system-requirements.html

It says: "Notice on Integrated GPU: Intel® oneAPI tools support for integrated graphics processors is available on 11th Generation and newer Intel® Core™ Processors. Active support for older integrated graphics processors included with 6th through 10th Generation Intel Core Processors and related Intel Atom®, Pentium®, and Celeron® processors will no longer be available starting with the Intel oneAPI 2023.1 release."

So it's not supported on all Intel GPUs. Perhaps the documentation should note that down.

**Comment by phly95** [comment]
What's worse, "Previous versions of the toolkit are available through [Priority Support](https://www.intel.com/content/www/us/en/developer/tools/oneapi/commercial-base.html)." and it appears no one has been archiving old versions, so people with older CPUs are SOL unless they pay Intel $700 for what was once a free download. Intel is a joke and its no wonder their stock is in the ground.

**Comment by phly95** [comment]
Reopening, since the doc should mention that 11th gen is the minimum requirement.

**Comment by phly95** [comment]
Interestingly enough, the iGPU is 0.44 Tflops, and the CPU is (according to an AI approximation) 0.30 Tflops. I assume that since CPUs are a lot more flexible with fewer, more powerful cores, and has direct access to memory, this would explain why the iGPU can't keep up. I didn't realize just how little computing power many iGPUs have, given the kind of games that run well on it. (A lot of 360 era games run at 60fps with the right resolution settings)

**Comment by phly95** [comment]
I think this can be closed now thanks to this commit that mentions SYCL requirements:
https://github.com/ggerganov/llama.cpp/commit/a21c6fd45032a20180e026773582d21294c85619

**Comment by drzraf** [comment]
> Furthermore, "Previous versions of the toolkit are available through [Priority Support](https://www.intel.com/content/www/us/en/developer/tools/oneapi/commercial-base.html)." and it appears no one has been archiving old versions, so people with older CPUs aren't getting SYCL support unless they pay Intel $700 for what was once a free download. That being said, chances are that there really isn't that much difference compared to just using Vulkan anyway, and those old iGPUs aren't useful for running LLMs anyway. The fact that the CPU can run this stuff as well as it can is somewhat of a miracle.

Isn't [this](https://github.com/RenderKit/mkl-dnn) the version of the toolkit supporting iGPU up to gen8 ?

**Comment by vpirogov** [comment]
> Isn't [this](https://github.com/RenderKit/mkl-dnn) the version of the toolkit supporting iGPU up to gen8 ?

This is an ancient fork of [oneDNN](https://github.com/uxlfoundation/oneDNN) library. It also does not support GEN8 GPUs, only GEN9 and newer.

**Comment by drzraf** [comment]
Digging further I found that my problem was (as for many others), the removal of clBlast in #7735 :S which could have granted me the possibility to offload on one of these older (but still useful and mainstream) iGPU.

In that thread, someone mentioned [OpenCL backed SYCL](https://github.com/KhronosGroup/SYCL-Docs/blob/main/adoc/chapters/opencl_backend.adoc)
