### ISSUE TITLE
Feature Request: Processing one token takes the same amount of time as processing 40 tokens (CUDA/MMVQ)

### ISSUE THREAD

**Issue by yancaoweidaode** [ggerganov/llama.cpp#8869]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Processing one token takes the same amount of time as processing 40 tokens

### Motivation

In speculative sampling, if the draft model generates a lot of tokens, the llm model needs to be verified, and if the verification process consumes a lot of time, it will not have the effect of speeding up, but it is likely to slow down the final generation speed. However, if the time taken to process multiple tokens, such as 40 tokens and 1 token, is not very different, it is possible to significantly increase the generation speed.

### Possible Implementation

In ggml_cuda_mul_mat, I found MMVQ_MAX_BATCH_SIZE. After testing, I found that as long as the number of tokens is less than this value, the time used to process different tokens is basically the same. I tried to increase this value to 15, and with a modest change to the code (parameters greater than 8, consistent with equal 8), the time taken to process the different numbers of tokens remained roughly the same. But when this number increases to 16, the time taken to process 16 tokens doubles. How can we increase the MMVQ_MAX_BATCH_SIZE without increasing the processing time as much as possible? I think this is very meaningful.

**Comment by yancaoweidaode** [comment]
> What you would need to do is overhaul the code in `mmvq.cu` in such a way that reduces register pressure (the limiting factor). Then it would be much easier to scale up MMVQ to larger batch sizes. This could potentially be done by utilizing tensor cores (see `mmq.cuh` and `mma.cuh`). But it's possible that optimizing MMQ for small batch sizes will yield better results.

Thank you very much, but I am not very good at optimizing these related kernel functions. If I could get help from the official llama.cpp, I would be very grateful.

**Comment by JohannesGaessler** [comment]
I am the person that wrote the code in question and I would be happy to help. This will not be easy though.

**Comment by yancaoweidaode** [comment]
Thank you very much, and I agree that this is a very difficult thing.
