### ISSUE TITLE
Bug: Makefile: make fails with LLAMA_CURL=1 because CXXFLAGS is missing -I/usr/include

### ISSUE THREAD

**Issue by themanyone** [ggerganov/llama.cpp#8876]
### What happened?

Compilation with LLAMA_CURL=1 fails because `common.cpp` cannot find <curl/curl.h>

Easily worked around with `CXXFLAGS=-I/usr/include` LLAMA_CURL=1 make...` and everyone should know that.

However, shouldn't the include location be detected in the Makefile?

### Name and Version

./llama-cli --version
version: 3533 (c94f5b11)
built with cc (conda-forge gcc 12.3.0-3) 12.3.0 for x86_64-conda-linux-gnu

### What operating system are you seeing the problem on?

Linux, Fedora 39

**Comment by fairydreaming** [comment]
It seems that you use compiler installed in the conda environment. I guess you should install libcurl in your conda environment as well instead of using the one installed in your system.

**Comment by themanyone** [comment]
Good observation. I have to borrow gcc12 from inside the conda env for legacy CUDA parts that are incompatible with gcc13. Then I compile the rest of it with gcc13. But it might be fooling the detection steps. Let me try just setting C++= to the gcc12 executable, instead of badgering the conda env.
