### ISSUE TITLE
[Question] Why does converting GPT4All from ggml to pth increase model size?

### ISSUE THREAD

**Issue by clxyder** [ggerganov/llama.cpp#889]
I want to be able to run the `gpt4all-lora-quantized.bin` model on my GPU, but the gpt4all repo does not provide a HF compatible model.

So I figured I would use `convert-ggml-to-pth.py` to convert the model and then run that.

But the model is now 13 GB instead of 4GB, would it be safe to just create tensors of `dtype = uint8` instead of dequantizing the model to ensure the model remains small?

Does anyone know if would I still be able to run that with the `transformers` library? I figure that I will have to use https://github.com/qwopqwop200/GPTQ-for-LLaMa to try and run that new model.

Thanks again!

**Comment by TheBloke** [comment]
I'm not sure how to convert the GGML to a working .pt file.  I tried using the new convert script from PR https://github.com/ggerganov/llama.cpp/pull/545 and it produced a file but I couldn't get it to load.

But you don't need to do that. There's already code available to load GPT4ALL on the GPU.  Here's a Google Colab with example code: https://colab.research.google.com/drive/1NWZN15plz8rxrk-9OcxNwwIk1V1MfBsJ?usp=sharing#scrollTo=TyxQrFAFS7Vh

The basic principle is: 
* Load the original Llama 7B model
* Apply the GPT4ALL fine tuning as a Lora on top of that
* Then run inference

GPT4ALL provided their own Python code to do that, code GPT4AllGPU.  The code is basically the same as the code in the Google Colab above, so you can use either

Note that the Google Colab I linked above is from a video, and the code is explained in the video if you find that helpful: https://youtu.be/GhRNIuTA2Z0
