### ISSUE TITLE
Bug: High CPU usage and bad output with flash attention on ROCm

### ISSUE THREAD

**Issue by curvedinf** [ggerganov/llama.cpp#8893]
### What happened?

While flash attention works well for my python ui (https://github.com/curvedinf/dir-assistant/) on an nvidia system, it produces bad results on my AMD system. My AMD system has a 7900XT with ROCm 6.1.2 on Ubuntu 22.04. When FA is off, inference is almost instant with high t/s and no CPU usage. When FA is on, the CPU utilization is 100% for 1-2 minutes, and then tokens are generated slowly and are incorrect (in my case, it always produces "################################" for a long time).

### Name and Version

Using python bindings via llama-cpp-python 0.2.84. Readme says llama.cpp version is [ggerganov/llama.cpp@4730faca618ff9cee0780580145e3cbe86f24876](https://github.com/ggerganov/llama.cpp/commit/4730faca618ff9cee0780580145e3cbe86f24876)

### What operating system are you seeing the problem on?

Linux

**Comment by JohannesGaessler** [comment]
Do you have the same issue when using llama.cpp directly?

**Comment by curvedinf** [comment]
Directly the CPU utilization is much lower and there is no 2 minute wait, but the output is all "##########" still. Output without -fa is correct. I'll report the CPU utilization to llama-cpp-python, but the ####### is a llama.cpp issue.

**Comment by JohannesGaessler** [comment]
Can you link the exact model that you used?

**Comment by curvedinf** [comment]
https://huggingface.co/bartowski/Phi-3.1-mini-128k-instruct-GGUF/blob/main/Phi-3.1-mini-128k-instruct-Q5_K_L.gguf

**Comment by JohannesGaessler** [comment]
There is no AMD-compatible FlashAttention implementation for the model in question since it has a head size of 96 (only 64 and 128) are supported. Therefore part of the compute graph has to be run on the CPU so a high CPU utilization and poor performance are to be expected.

I am not able to reproduce the issue where the model produces incorrect results on my RX 6800.

**Comment by curvedinf** [comment]
Phi 3's large context size make flash attention a valuable addition to reduce vram requirements of the context. Are there any plans to add 96 head size for amd?

**Comment by curvedinf** [comment]
Any word on whether 96 head size is planned to be supported?

**Comment by JohannesGaessler** [comment]
I don't have plans to support anything specifically for AMD. As a general rule, I write CUDA code and then port the code to AMD via HIP if it makes sense. I will get back to working on the CUDA FlashAttention code in the coming months. I will likely add better support for head sizes other than 64 and 128 but I very much expect the AMD performance of the code to be bad.
