### ISSUE TITLE
Feature Request: llama3 and 3.1 uncensored

### ISSUE THREAD

**Issue by olumolu** [ggerganov/llama.cpp#8895]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

https://huggingface.co/Orenguteng/Llama-3-8B-Lexi-Uncensored-GGUF
https://huggingface.co/Orenguteng/Llama-3.1-8B-Lexi-Uncensored
Add 70b also

### Motivation

Helps to get uncensored answers

**Comment by rjmalagon** [comment]
Hi, thees are unofficial models, but I can help you to load them on your Ollama instances.
¿Do you need a specific quantization of these models?

**Comment by rjmalagon** [comment]
If you need an uncensored llama 3.1 models, you can try Llama Dolphin 3.1. I uploaded them to Ollama repos rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0 and rjmalagon/dolphin-2.9.4-llama3.1-8b:f16 
You can pull from Ollama  

`ollama pull rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0`

**Comment by realies** [comment]
> If you need an uncensored llama 3.1 models, you can try Llama Dolphin 3.1. I uploaded them to Ollama repos rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0 and rjmalagon/dolphin-2.9.4-llama3.1-8b:f16 You can pull from Ollama
> 
> `ollama pull rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0`

> ollama run rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0
Error: llama runner process has terminated: error:done_getting_tensors: wrong number of tensors; expected 292, got 291

> ollama run rjmalagon/dolphin-2.9.4-llama3.1-8b:f16
Error: llama runner process has terminated: error:done_getting_tensors: wrong number of tensors; expected 292, got 291

**Comment by olumolu** [comment]
I am willing to get them officially.

**Comment by Cephra** [comment]
> I am willing to get them officially.

Can you elaborate what you mean by "officially"?

**Comment by olumolu** [comment]
> > I am willing to get them officially.
> 
> Can you elaborate what you mean by "officially"?

Like how llama3 or llama3.1:70b is available the same way.

**Comment by rjmalagon** [comment]
> > > I am willing to get them officially.
> > 
> > 
> > Can you elaborate what you mean by "officially"?
> 
> Like how llama3 or llama3.1:70b is available the same way.

You can explore the author's repo [https://ollama.com/CognitiveComputations](https://ollama.com/CognitiveComputations), and maybe they will upload this model if you ask nicely on [https://huggingface.co/cognitivecomputations](https://huggingface.co/cognitivecomputations). I am pretty sure that the official Ollama repos are compiled by the Ollama team and not the model authors.

**Comment by olumolu** [comment]
Ok
