### ISSUE TITLE
Bug: 2 tests fail

### ISSUE THREAD

**Issue by yurivict** [ggerganov/llama.cpp#8906]
### What happened?

Tests test-eval-callback and test-backend-ops fail on FreeBSD 14.1

### Name and Version

Version: 3538

### What operating system are you seeing the problem on?

BSD

### Relevant log output

```shell
[LastTest.log](https://freebsd.org/~yuri/llama-cpp-3538-LastTest.log)
```

**Comment by JohannesGaessler** [comment]
I get a 404 when trying to access the log.

**Comment by yurivict** [comment]
I can access it:
[LastTest.log](https://freebsd.org/~yuri/llama-cpp-3538-LastTest.log)
