### ISSUE TITLE
Feature Request: RPC Cuda Build to link with cudart dlls

### ISSUE THREAD

**Issue by jkfnc** [ggerganov/llama.cpp#8912]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Is it possible to get RPC Builds that work with Cuda , so we dont have to compile from scratch.

### Motivation

Would be easy to get started with RPC for distributed inference if we had readymade build available. Current RPC build only works with CPU.

**Comment by slaren** [comment]
I think it would be ok to enable the RPC backend on all the builds, and remove the RPC-specific build. It should be a simple change in the `.github/workflows/build.yml` file.

**Comment by rgerganov** [comment]
I will submit a patch for this in the next few days
