### ISSUE TITLE
Bug: llama-cli.exe don't have option as doc describes (like --chat-template)

### ISSUE THREAD

**Issue by zydmtaichi** [ggerganov/llama.cpp#8927]
### What happened?

build llama-cli.exe on windows with newest version in repo. The command line tool miss some options like `--chat-template option` which contains in [doc](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#chat-templates) and `-cnv`. hope to get the option implemented to apply the chat template to model for now. And please update the doc per valid option in current version

### Name and Version

$llama-cli.exe --version
version: 1 (231ae28f)
built with MSVC 19.40.33811.0 for x64

**Comment by ngxson** [comment]
> $llama-cli.exe --version
> version: 1 ([231ae28](https://github.com/ggerganov/llama.cpp/commit/231ae28f078c3148d097b301f2145f1e3e816cc1))
> built with MSVC 19.40.33811.0 for x64

You are using a very outdated version. You must rebuild the project with up-to-date source code.

**Comment by zydmtaichi** [comment]
> > $llama-cli.exe --version
> > version: 1 ([231ae28](https://github.com/ggerganov/llama.cpp/commit/231ae28f078c3148d097b301f2145f1e3e816cc1))
> > built with MSVC 19.40.33811.0 for x64
> 
> You are using a very outdated version. You must rebuild the project with up-to-date source code.

it's impossible. I just clone the lamma.cpp repo today and compile. how it could be very outdated?

**Comment by zydmtaichi** [comment]
@ngxson please reopen my issue

**Comment by ngxson** [comment]
You can check it yourself: build commit [231ae28](https://github.com/ggerganov/llama.cpp/commit/231ae28f078c3148d097b301f2145f1e3e816cc1) is from March 3rd. Today is August 8th

**Comment by zydmtaichi** [comment]
> You can check it yourself: build commit [231ae28](https://github.com/ggerganov/llama.cpp/commit/231ae28f078c3148d097b301f2145f1e3e816cc1) is from March 3rd. Today is August 8th

I check the version again and find that the version code cloned from repo via some github mirror like [gitclone](https://gitclone.com/) is not matched with newest version code. I switch the mirror addr and solve the issue.
Thanks a lot for your help.
