### ISSUE TITLE
Feature Request: Ovis1.5-Gemma2-9B model support?

### ISSUE THREAD

**Issue by liuzl** [ggerganov/llama.cpp#8940]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Add support for the Ovis1.5-Gemma2-9B model in llama.cpp.

### Motivation

It would be highly beneficial if this model could be made compatible with GGUF, similar to how LLaVA is supported. In my experience, this model has performed exceptionally well.

**Comment by liuzl** [comment]
https://huggingface.co/AIDC-AI/Ovis1.5-Gemma2-9B

**Comment by Technetium1** [comment]
bump
