### ISSUE TITLE
Why does my program have no output after quantization

### ISSUE THREAD

**Issue by iMountTai** [ggerganov/llama.cpp#895]
![image](https://user-images.githubusercontent.com/35353688/231195014-46f09804-7b61-4e55-83fc-c7d73aed51b5.png)
 
No output after `.\quantize.exe .\models\7B\ggml-model-f16.bin \models\7B\ggml-model-q4_0.bin 2`
Ask for help,thanks!!!

**Comment by gianfra-t** [comment]
In my case, I was having the issue because my output file didn't exist.

**Comment by Green-Sky** [comment]
not sure how leading `\` are handles on windows.

Just to be sure I suggest you try adding a `.` before `\models\`
