### ISSUE TITLE
[Enhancement] Implement alternate method in 'timing' to improve 10.7-10.9 compatibility

### ISSUE THREAD

**Issue by Errand24** [ggerganov/llama.cpp#897]
# Expected Behavior
Time values are handled properly on older macOS versions, that don't support clock_gettime().

# Current Behavior
Error occurs during compilation: "use of undeclared identifier 'CLOCK_MONOTONIC' clock_gettime(CLOCK_MONOTONIC, &ts);"

# More Information
- Linked issue #788
- Current workaround is to make 'int64_t ggml_time_ms(void)' and 'int64_t ggml_time_us(void)' functions 'return 0' in #else section.
- Valid also for macOS 10.8 and 10.9
- [Fix](https://github.com/yquake2/yquake2/commit/78d70b2bf781aeb9c21652f018233fd34a4799aa) on [this](https://github.com/yquake2/yquake2/issues/239) issue states that older OSX versions don't implement 'clock_gettime ()' and author seem to find solution

**Comment by prusnak** [comment]
macOS 10.9 is EOL since 2016
older releases are EOL for more than 7 years

src: https://endoflife.date/macos

**Comment by cmp-nct** [comment]
> macOS 10.9 is EOL since 2016 older releases are EOL for more than 7 years
> 
> src: https://endoflife.date/macos
> 
> Is this really something we want someone to spend their time on?

Probably doesn't hurt to add a #ifdef DISABLE_TIMING to force return 0. Anyone running old macs could push such a commit in (or find a compatible solution with more effort).
Apple is kind of not just EOL on the software, they EOL the entire hardware as they forbid updates. 
They want people to throw away the old macs and buy new ones or void their terms and install a Hackintosh. Which is not really nice behavior.

**Comment by anzz1** [comment]
The whole EOL mindset is despicable. Like if there isn't enough waste in the world.

That being said obviously only someone with older hardware/software can implement and test such functionality. But no one should ever be discouraged from doing so.
