### ISSUE TITLE
Feature Request: MiniCPM 2.6 model support?

### ISSUE THREAD

**Issue by ttamoud** [ggerganov/llama.cpp#8977]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

I'd like to begin by expressing my sincere gratitude for your outstanding contributions. Your efforts have been instrumental in supporting and advancing the open-source community.

It would be fantastic to have support for 8 billion parameters vision models  that can truly rival the performance of leading proprietary models.

### Motivation

SOTA OSS VLM with only 8b params, a piece of art, rivals top models.

<img width="1155" alt="QVl0iPtT5aUhlvViyEpgs" src="https://github.com/user-attachments/assets/d746c473-9be5-4710-9f12-add392884fff">

**Comment by xuhongming251** [comment]
https://ollama.com/xuxx/minicpm2.6

There is an installation package for Ollama on Windows, and the MiniCPM 2.6 model is available.

**Comment by rick-github** [comment]
https://github.com/ggerganov/llama.cpp/pull/8967
