### ISSUE TITLE
Virustotal reporting a Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by cmatrix7777** [ggerganov/llama.cpp#898]
What is this?

llama-master-3e6e70d-bin-win-avx-x64.zip

https://www.virustotal.com/gui/file/736b2756f217f2d566b1d967c7712bb1359c825e4c0d25a7036398980d94c5df/detection

**Comment by Technetium1** [comment]
Don't be worried about the false positives. The code is here to see and is built by CI.

**Comment by cmp-nct** [comment]
It's not even a false positive. That's the beauty of Virustotal.
It uses a ton of different engines, some of them unreliable but in combination they give a very solid signal.
So when you look at that result: that's how non-malware is supposed to look like. A ton of green "good" an done false positive.

Now if you were super careful you could dig into the reason for the one false positive, if it has any merit. 
But generally that's a good result for a large binary file.
