### ISSUE TITLE
Feature Request: Add support for EXAONE-3.0-7.8B-Instruct model

### ISSUE THREAD

**Issue by chris-jaehoon** [ggerganov/llama.cpp#8991]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

please add new model [EXAONE-3.0-7.8B-Instruct](https://huggingface.co/LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct)

### Motivation

llama.cpp for new model

**Comment by mscheong01** [comment]
I'm planning to work on this next week 😄

**Comment by MoonRide303** [comment]
I've noticed draft of the solution on HF discussion - might be useful:
https://huggingface.co/LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct/discussions/8#66bae61b1893d14ee8ed85bb

**Comment by mscheong01** [comment]
@MoonRide303 I've added the chat template written in the discussion. Thanks!
