### ISSUE TITLE
Bug: Quantizing a bog standard llama is failing - Error: Error quantizing: b"main: invalid nthread 'Q8_0' (stoi)\n"

### ISSUE THREAD

**Issue by devlux76** [ggerganov/llama.cpp#9007]
### What happened?

I was running gguff on https://huggingface.co/pints-ai/1.5-Pints-16K-v0.1/tree/main

It's bog standard llama. It should have quanted but it's failing.

### Name and Version

Whatever version is being used by gguf my repo on HF

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Error quantizing: b"main: invalid nthread 'Q8_0' (stoi)\n"

That's all I get sorry.
```

**Comment by JohannesGaessler** [comment]
You're using the CLI wrong, add the `--help` argument to get a rundown of the expected usage.
