### ISSUE TITLE
Feature Request: UPX the growing binaries in packaging.

### ISSUE THREAD

**Issue by jboero** [ggerganov/llama.cpp#9018]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

With recent changes some of the builds have become massive. I have a binary of Llama CUDA server from a few months ago that's 12MB. Now with new updates and new UI/themes built in the same binary is a whopping 640MB!!  Crazy.

I use `upx` to compress this 640MB down to 199MB which is much more reasonable. There is no behavior effect other than about 2ms slower startup. Either we should sort out what bloated resources are making this massive or use upx to compress the binary in packaging/build automation, both Docker and RPM.

Thoughts?

### Motivation

12MB->640MB binary size is nothing to sneeze at.  This will slow down installations and Docker containers all the same as it takes forever to download and expand images.

### Possible Implementation

```
upx llama-server
```

Now it's gone from 640MB to 199 MB. Magic.

**Comment by slaren** [comment]
The CUDA docker imagines are built by default with `-arch=all`, which increases dramatically the size of the binaries and is completely unnecessary. It also links ggml and llama.cpp statically, which further increases the size of the images that include multiple binaries. The best way to address these issues would be to modify the dockerfiles to build llama.cpp using `cmake` instead, which has better defaults and will prevent these issues.

**Comment by jboero** [comment]
Ah that makes sense. So no separate image for each arch?
Normally I build my own but NVidia hasn't caught up to GCCv14 yet like Fedora 40, so I started copying the container images.

**Comment by Ronsor** [comment]
Note that UPX'ing binaries prevents them from sharing code and (read-only) memory pages. The end result will be higher memory usage if you run multiple instances of the same process.

**Comment by slaren** [comment]
The CUDA docker images should be substantially smaller now - they are built only for the supported CUDA architectures, and the full image will also benefit from dynamic linking. Should this be considered resolved now?

**Comment by jboero** [comment]
Excellent thank you. This helps both native builds and container registry
right?

**Comment by slaren** [comment]
Yes.
