### ISSUE TITLE
feature: interactively exporting loaded model to binfile

### ISSUE THREAD

**Issue by jon-chuang** [ggerganov/llama.cpp#904]
With https://github.com/ggerganov/llama.cpp/pull/820, the loaded model may be different from the base model. It makes sense to be able to interactively export the currently loaded model to binfile. 

Especially if one allows the option to linearly interpolate multiple LoRA files - i.e. LoRA mixology for a unique LLM personality.

**Comment by MillionthOdin16** [comment]
If you're familiar with the mixing of loras I think it would be helpful for a lot of people here if you could link some resources on it. I've heard you can do some pretty cool things, but I'm not very familiar.
