### ISSUE TITLE
feature: linearly interpolating one or multiple LoRA with base model

### ISSUE THREAD

**Issue by jon-chuang** [ggerganov/llama.cpp#905]
Once https://github.com/ggerganov/llama.cpp/pull/820 is merged, it would be nice to allow linearly interpolating one or multiple LoRA.

LoRA should be able to be loaded interactively, and interpolation weights also adjusted interactively.

**Comment by cto-junior** [comment]
@jon-chuang what seems to the blocker currently to make lora adapters swappable?

**Comment by yacineMTB** [comment]
https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L2838-L2876

Proposal: Just Prototyping interactive LoRA and showing that it might be valuable
Shouldn't be too hard!
