### ISSUE TITLE
Bug: ImportError: libprotobuf-lite.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sirus20x6** [ggerganov/llama.cpp#9071]
### What happened?

Arch has a newer protobuf that apparently is not compatible with llama.cpp's llava. I tried building an older version of protobuf but was unsuccessful. 

### Name and Version

> ./llama-cli --version
version: 3600 (2fb92678)
built with clang version 17.0.0 for x86_64-pc-linux-gnu

### Relevant log output

```shell
python ./examples/llava/convert_image_encoder_to_gguf.py -m /thearray/git/models/dolphin-vision-72b/vit --llava-projector /thearray/git/models/dolphin-vision-72b/vit/llava.projector --output-dir /thearray/git/models/dolphin-vision-72b/vit/ --clip-model-is-vision
Traceback (most recent call last):
  File "/code/git/llama.cpp/./examples/llava/convert_image_encoder_to_gguf.py", line 8, in <module>
    from gguf import *
  File "/code/git/llama.cpp/gguf-py/gguf/__init__.py", line 7, in <module>
    from .vocab import *
  File "/code/git/llama.cpp/gguf-py/gguf/vocab.py", line 10, in <module>
    from sentencepiece import SentencePieceProcessor
  File "/usr/lib/python3.12/site-packages/sentencepiece/__init__.py", line 10, in <module>
    from . import _sentencepiece
ImportError: libprotobuf-lite.so.25: cannot open shared object file: No such file or directory
```

**Comment by sirus20x6** [comment]
trying to build protobuf 25.3
`[ 52%] Linking CXX executable protoc
/usr/bin/cmake -E cmake_link_script CMakeFiles/protoc.dir/link.txt --verbose=1
/usr/bin/c++ -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Wno-lto-type-mismatch -fpermissive         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -ffat-lto-objects -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fuse-ld=mold -flto=auto CMakeFiles/protoc.dir/src/google/protobuf/compiler/main.cc.o -o protoc-25.3.0  -Wl,-rpath,/tmp/makepkg/protobuf/src/build: libprotoc.so.25.3.0 libprotobuf.so.25.3.0 /usr/lib/libabsl_die_if_null.so.2407.0.0 /usr/lib/libabsl_log_initialize.so.2407.0.0 /usr/lib/libabsl_statusor.so.2407.0.0 /usr/lib/libabsl_log_internal_check_op.so.2407.0.0 /usr/lib/libabsl_leak_check.so.2407.0.0 /usr/lib/libabsl_log_internal_conditions.so.2407.0.0 /usr/lib/libabsl_log_internal_message.so.2407.0.0 /usr/lib/libabsl_log_internal_nullguard.so.2407.0.0 /usr/lib/libabsl_examine_stack.so.2407.0.0 /usr/lib/libabsl_log_internal_format.so.2407.0.0 /usr/lib/libabsl_log_internal_proto.so.2407.0.0 /usr/lib/libabsl_log_internal_log_sink_set.so.2407.0.0 /usr/lib/libabsl_log_sink.so.2407.0.0 /usr/lib/libabsl_log_entry.so.2407.0.0 /usr/lib/libabsl_flags_internal.so.2407.0.0 /usr/lib/libabsl_flags_marshalling.so.2407.0.0 /usr/lib/libabsl_flags_reflection.so.2407.0.0 /usr/lib/libabsl_flags_config.so.2407.0.0 /usr/lib/libabsl_flags_program_name.so.2407.0.0 /usr/lib/libabsl_flags_private_handle_accessor.so.2407.0.0 /usr/lib/libabsl_flags_commandlineflag.so.2407.0.0 /usr/lib/libabsl_flags_commandlineflag_internal.so.2407.0.0 /usr/lib/libabsl_log_globals.so.2407.0.0 /usr/lib/libabsl_vlog_config_internal.so.2407.0.0 /usr/lib/libabsl_log_internal_fnmatch.so.2407.0.0 /usr/lib/libabsl_log_internal_globals.so.2407.0.0 /usr/lib/libabsl_raw_hash_set.so.2407.0.0 /usr/lib/libabsl_hash.so.2407.0.0 /usr/lib/libabsl_city.so.2407.0.0 /usr/lib/libabsl_low_level_hash.so.2407.0.0 /usr/lib/libabsl_hashtablez_sampler.so.2407.0.0 /usr/lib/libabsl_status.so.2407.0.0 /usr/lib/libabsl_cord.so.2407.0.0 /usr/lib/libabsl_cordz_info.so.2407.0.0 /usr/lib/libabsl_cord_internal.so.2407.0.0 /usr/lib/libabsl_cordz_functions.so.2407.0.0 /usr/lib/libabsl_exponential_biased.so.2407.0.0 /usr/lib/libabsl_cordz_handle.so.2407.0.0 /usr/lib/libabsl_crc_cord_state.so.2407.0.0 /usr/lib/libabsl_crc32c.so.2407.0.0 /usr/lib/libabsl_crc_internal.so.2407.0.0 /usr/lib/libabsl_crc_cpu_detect.so.2407.0.0 /usr/lib/libabsl_bad_optional_access.so.2407.0.0 /usr/lib/libabsl_strerror.so.2407.0.0 /usr/lib/libabsl_str_format_internal.so.2407.0.0 /usr/lib/libabsl_synchronization.so.2407.0.0 /usr/lib/libabsl_stacktrace.so.2407.0.0 /usr/lib/libabsl_symbolize.so.2407.0.0 /usr/lib/libabsl_debugging_internal.so.2407.0.0 /usr/lib/libabsl_demangle_internal.so.2407.0.0 /usr/lib/libabsl_demangle_rust.so.2407.0.0 /usr/lib/libabsl_decode_rust_punycode.so.2407.0.0 /usr/lib/libabsl_utf8_for_code_point.so.2407.0.0 /usr/lib/libabsl_graphcycles_internal.so.2407.0.0 /usr/lib/libabsl_kernel_timeout_internal.so.2407.0.0 /usr/lib/libabsl_malloc_internal.so.2407.0.0 /usr/lib/libabsl_time.so.2407.0.0 /usr/lib/libabsl_strings.so.2407.0.0 /usr/lib/libabsl_strings_internal.so.2407.0.0 /usr/lib/libabsl_string_view.so.2407.0.0 /usr/lib/libabsl_base.so.2407.0.0 /usr/lib/libabsl_spinlock_wait.so.2407.0.0 /usr/lib/libabsl_throw_delegate.so.2407.0.0 /usr/lib/libabsl_int128.so.2407.0.0 /usr/lib/libabsl_civil_time.so.2407.0.0 /usr/lib/libabsl_time_zone.so.2407.0.0 /usr/lib/libabsl_bad_variant_access.so.2407.0.0 /usr/lib/libabsl_raw_logging_internal.so.2407.0.0 /usr/lib/libabsl_log_severity.so.2407.0.0
mold: error: undefined symbol: absl::lts_20240116::InitializeLog()
>>> referenced by <artificial>
>>>               /tmp/ccyLI73b.ltrans0.ltrans.o:(google::protobuf::compiler::ProtobufMain(int, char**))
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/protoc.dir/build.make:168: protoc-25.3.0] Error 1
make[2]: Leaving directory '/tmp/makepkg/protobuf/src/build'
make[1]: *** [CMakeFiles/Makefile2:203: CMakeFiles/protoc.dir/all] Error 2
make[1]: Leaving directory '/tmp/makepkg/protobuf/src/build'
make: *** [Makefile:146: all] Error 2

==> ERROR: A failure occurred in build().
    Aborting...
(base) neuromancer :( > cd /code/
(base) neuromancer :) > cd git
(base) neuromancer :) > ls
btcli_wallet  dune-truncated-txt  dunfell  Infinite-Heart  llama.cpp  messages.ts  onnxruntime  photoshop  ripme  sa  Server.ts  tapchanger  trizen  trizen.sh  zfs  zfs-pkgbuild
(base) neuromancer :) > cd llama.cpp/
(base) neuromancer :) > git pull
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 33 (delta 5), reused 26 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (33/33), 217.02 KiB | 4.62 MiB/s, done.
From https://github.com/ggerganov/llama.cpp
   8b3befc0..2fb92678  master                     -> origin/master
 + acaf26c9...25a46f2b gg/llama-refactor-sampling -> origin/gg/llama-refactor-sampling  (forced update)
 + 9c6eb9fa...e51864cb update_flake_lock_action   -> origin/update_flake_lock_action  (forced update)
 * [new tag]           b3600                      -> b3600
Updating 8b3befc0..2fb92678
Fast-forward
 src/llama.cpp | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
`

**Comment by fairydreaming** [comment]
I see that you have conda installed (from "(base)" in your shell), why don't you create and activate a separate conda environment and then install llama.cpp requirements with pip? It will be something like this:
```
conda create -n llama.cpp python
conda activate llama.cpp
cd /your/path/to/llama.cpp/
pip install -r requirements.txt
```
Also `neuromancer` 👍

**Comment by sirus20x6** [comment]
didn't know that it was provided through pip. that seemed to work. now it appears the model I'm trying to use is not compatible, but that's another issue.

also this is my third machine named neuromancer ;)
