### ISSUE TITLE
Bug: Throughput (tokens/sec) does not scale with increasing batch sizes in Intel GPUs

### ISSUE THREAD

**Issue by thecrazyphysicist369** [ggerganov/llama.cpp#9097]
### What happened?

For Intel dGPU like ARC770, the tokens per second doesn't scale with increasing batch size. For example if tps for batch size 1 is ~x tps, for batch size 8 also throughput is ~x tps. 

### Name and Version

llama build: 2663 (7e54166)
OS ubuntu 22.04
command line used: ZES_ENABLE_SYSMAN=1 ./build/bin/main -m models/llama-2-7b.Q8_0.gguf -ngl 33 -mg 0 -b 1 -p "solve the 3 ants and triangel puzzle"
batch size changed for different execution.

### What operating system are you seeing the problem on?

Linux

**Comment by qnixsynapse** [comment]
Batch size is for prompt processing, not for output generation. Also, value of 8 is too low.

**Comment by thecrazyphysicist369** [comment]
1. We tried with higher batch size and we see the same result.
2. When using openvino llm execution, the tps throughput increases with increasing batch size.

**Comment by NeoZhangJianyu** [comment]
@thecrazyphysicist369 

Here is the test result of llama-bench.
The pp512 is increase 2 times after BS is changed from 32-64.
But tg128 is not change.

Hope it help you!

```
./build/bin/llama-bench -m models/llama-2-7b.Q4_0.gguf -p 512 -n 128 -b 32 -ngl 33
| model                          |       size |     params | backend    | ngl | n_batch |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | ------------: | ---------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | SYCL       |  33 |      32 |         pp512 |    178.49 x 0.09 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | SYCL       |  33 |      32 |         tg128 |     38.83 x 0.10 |

./build/bin/llama-bench -m models/llama-2-7b.Q4_0.gguf -p 512 -n 128 -b 64 -ngl 33
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | SYCL       |  33 |      64 |         pp512 |    299.55 x 0.32 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | SYCL       |  33 |      64 |         tg128 |     38.77 x 0.10 |

```
