### ISSUE TITLE
Research: Are there any plans to support AIGC models such as flux1.dev?

### ISSUE THREAD

**Issue by ggyzh** [ggerganov/llama.cpp#9110]
### Research Stage

- [ ] Background Research (Let's try to avoid reinventing the wheel)
- [ ] Hypothesis Formed (How do you think this will work and it's effect?)
- [ ] Strategy / Implementation Forming
- [ ] Analysis of results
- [ ] Debrief / Documentation (So people in the future can learn from us)

**Comment by akx** [comment]
See: https://github.com/leejet/stable-diffusion.cpp 

> Stable Diffusion and Flux in pure C/C++
