### ISSUE TITLE
Bug: Missing "." in prompt template for Qwen2

### ISSUE THREAD

**Issue by 99991** [ggerganov/llama.cpp#9128]
### What happened?

The file https://github.com/ggerganov/llama.cpp/blob/master/models/ggml-vocab-qwen2.gguf defines the prompt template for Qwen2 models. The prompt template can be queried with:

```bash
strings ggml-vocab-qwen2.gguf | tail -n 5
```

The template is missing the "." after "You are a helpful assistant":

```
You are a helpful assistant<|im_end|>
' }}{% endif %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}
```

The examples on the HuggingFace GGUF website for Qwen2 include the ".": https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF

The system prompt https://github.com/ggerganov/llama.cpp/blob/master/prompts/chat-with-qwen.txt includes the "." as well.

I am not sure what Qwen2 has been trained with, but I've heard that it answers in Chinese if you do not get the prompt exactly right, so maybe this is important. Or maybe it is not. Who knows.

@jklj077 (I think you are one of the authors and can probably tell us whether this matters or not)

### Name and Version

```
/data/llama.cpp/llama.cpp-b3615/llama-cli --version
version: 0 (unknown)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
```

(looks like the version is incorrect when building the executable with `make`)

### What operating system are you seeing the problem on?

Linux, Mac, Windows, BSD, Other? (Please let us know in description)

### Relevant log output

```shell
not applicable
```

**Comment by ngxson** [comment]
> The file https://github.com/ggerganov/llama.cpp/blob/master/models/ggml-vocab-qwen2.gguf defines the prompt template for Qwen2 models. The prompt template can be queried with:
> 
> ```shell
> strings ggml-vocab-qwen2.gguf | tail -n 5
> ```

The template shown is the jinja template. While it's there, it's not actually used by llama.cpp. The chatml template will be picked, and you will need to pass your own system message.

Try with `llama-server` example:

```
{
  "messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "..."}
  ]
}
```

```
"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n...<|im_end|>\n<|im_start|>assistant\n"
```

**Comment by 99991** [comment]
Thanks for the clarification! The prompt with missing "." is being printed as an example when running llama-server, which is confusing.

**Comment by jklj077** [comment]
IIRC, that file was used in testing the pre-tokenization. At that time, it was still Qwen1.5 and the chat template of Qwen1.5 on HF hub used to miss that "." but were modified around that time (e.g., [this](https://huggingface.co/Qwen/Qwen1.5-7B-Chat/commit/5f4f5e69ac7f1d508f8369e977de208b4803444b)) so the file must have been generated using the old files. It is consistent with the chat template in the tokenizer_config.json; it's just that the tokenizer_config.json has changed after. For the record, the default system message for Qwen should ends with a ".", as in the newer Qwen1.5 files and the Qwen2 files. But indeed, it does not make much of a difference. I have created a PR that updates the file.
