### ISSUE TITLE
Bug: Compilation failure with CUDA support on Windows: No CUDA toolset found.

### ISSUE THREAD

**Issue by lucky0604** [ggerganov/llama.cpp#9144]
### What happened?

When I tried to compile llama.cpp on Windows with CUDA support by using the command
```
cmake -B build -DGGML_CUDA=ON
```
and it returns the error

```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerId.cmake:412 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerId.cmake:34 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCUDACompiler.cmake:262 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/CMakeLists.txt:296 (enable_language)
```
I also tried these solutions
`https://stackoverflow.com/questions/56636714/cuda-compile-problems-on-windows-cmake-error-no-cuda-toolset-found`
but still useless.
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations`
![image](https://github.com/user-attachments/assets/7499d81e-8cb7-4ca4-aef1-2cce104195b7)

![image](https://github.com/user-attachments/assets/d1f59928-a742-4789-95eb-ed875b8341e3)

Do you know how I could resolve this issue? thanks

### Name and Version

llama-cli.exe --version
version: 3584 (5fd89a70)
built with MSVC 19.29.30154.0 for x64

### Relevant log output

D:\Code\llama.cpp>cmake -B build -DGGML_CUDA=ON
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.29.30154.0
-- The CXX compiler identification is MSVC 19.29.30154.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: D:/Devtools/Git/cmd/git.exe (found version "2.44.0.windows.1")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- OpenMP found
-- Using llamafile
-- Found CUDAToolkit: D:/Devtools/CudaToolkit/include (found version "12.1.66")
-- CUDA found
-- Using CUDA architectures: OFF
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerId.cmake:412 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerId.cmake:34 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCUDACompiler.cmake:262 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/CMakeLists.txt:296 (enable_language)

-- Configuring incomplete, errors occurred!
See also "D:/Code/llama.cpp/build/CMakeFiles/CMakeOutput.log".
See also "D:/Code/llama.cpp/build/CMakeFiles/CMakeError.log".

_No response_

**Comment by Meghpal** [comment]
Facing the same problem as well

**Comment by lucky0604** [comment]
> Facing the same problem as well

I have resolved the issue by upgrading from Visual Studio 2019 Professional to the 2022 Community edition and recompiling the project with the following CMake command, which includes the option to enable CUDA support
```
cmake -B build -DGGML_CUDA=ON
```

**Comment by 331Dala** [comment]
> > Facing the same problem as well
> 
> I have resolved the issue by upgrading from Visual Studio 2019 Professional to the 2022 Community edition and recompiling the project with the following CMake command, which includes the option to enable CUDA support
> 
> ```
> cmake -B build -DGGML_CUDA=ON
> ```

Same problem, solution not work for me...

**Comment by yuefengling** [comment]
网上有一种说法是这种错误是因为你先安装了CUDA Toolkit 后安装了Visual Studio，就会出的问题，我基于这个思路，在已经安装Visual Studio 2022的基础上重新安装了CUDA Toolkit ，我看它在安装过程中好像会配置一些东西给我 Windows 10 系统上的Visual Studio 2022，通过这种重新安装的方式，我确实解决了这个问题........可以给你参考一下
