### ISSUE TITLE
Refactor: Where is convert.py

### ISSUE THREAD

**Issue by geekforai** [ggerganov/llama.cpp#9154]
### Background Description

no convert.py

**Comment by Aisuko** [comment]
Check below

https://github.com/ggerganov/llama.cpp/blob/3ba780e2a8f0ffe13f571b27f0bbf2ca5a199efc/README.md?plain=1#L29

**Comment by cercatore** [comment]
is in the root of llama. there is a convert gguf and a convert ggml
