### ISSUE TITLE
 Request to use Phi-3.5-MoE-instruct

### ISSUE THREAD

**Issue by KarlHeinzMali** [ggerganov/llama.cpp#9168]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

 I like to use Phi-3.5-MoE-instruct, but it seems it is not be supported:

python convert_hf_to_gguf.py ~/.cache/huggingface/hub/models--microsoft--Phi-3.5-MoE-instruct/snapshots/482a9ba0eb0e1fa1671e3560e009d7cec2e5147c --outfile ../Phi-3.5-bf16.GGUF --outtype bf16
	INFO:hf-to-gguf:Loading model: 482a9ba0eb0e1fa1671e3560e009d7cec2e5147c
	ERROR:hf-to-gguf:Model PhiMoEForCausalLM is not supported

### Motivation

Phi-3.5-MoE-instruct is a brand new advanced model.

**Comment by gardner** [comment]
> MLX just merged support for it on mlx_llm.

It looks like they just merged support for 3.5. Does that include MoE?
https://github.com/riccardomusmeci/mlx-llm/commit/1b6fe7165d68263a387a16d36933415a1df543bf

@linkage001

**Comment by linkage001** [comment]
@gardner 

> > MLX just merged support for it on mlx_llm.
> 
> It looks like they just merged support for 3.5. Does that include MoE? [riccardomusmeci/mlx-llm@1b6fe71](https://github.com/riccardomusmeci/mlx-llm/commit/1b6fe7165d68263a387a16d36933415a1df543bf)
> 
> @linkage001

@gardner yes, it includes MoE. It's running at 35tk/s on my M1 MacBook pro. https://github.com/ml-explore/mlx-examples/pull/946

**Comment by KarlHeinzMali** [comment]
I am using Ubuntu 23.10 with 2xEPYC 9654 12 channel DDR5.

**Comment by ayttop** [comment]
thank you but where gguf file?

**Comment by ayttop** [comment]
![Screenshot 2024-08-27 162503](https://github.com/user-attachments/assets/129546d1-cf03-4a5c-961a-6d04ac76b2fc)

**Comment by ayttop** [comment]
https://github.com/foldl/chatllm.cpp

| [Supported Models](https://github.com/foldl/chatllm.cpp/blob/master/docs/models.md) | [Download Quantized Models](https://github.com/foldl/chatllm.cpp/blob/master/docs/quick_start.md#download-quantized-models) |

What's New:

2024-08-28: Phi-3.5 Mini & MoE

Inference of a bunch of models from less than 1B to more than 300B, for real-time chatting with [RAG](https://github.com/foldl/chatllm.cpp/blob/master/docs/rag.md) on your computer (CPU), pure C++ implementation based on [@ggerganov](https://github.com/ggerganov)'s [ggml](https://github.com/ggerganov/ggml).

| [Supported Models](https://github.com/foldl/chatllm.cpp/blob/master/docs/models.md) | [Download Quantized Models](https://github.com/foldl/chatllm.cpp/blob/master/docs/quick_start.md#download-quantized-models) |

What's New:

2024-08-28: Phi-3.5 Mini & MoE

**Comment by ayttop** [comment]
not run on colab

**Comment by ThiloteE** [comment]
There is a PR in transformers. Maybe this is a requirement for llama.cpp to support the conversion? https://github.com/huggingface/transformers/pull/33363.

**Comment by nonetrix** [comment]
let's not

**Comment by ThiloteE** [comment]
The PR in the transformers repo has been merged and is featured in release [v4.46.0](https://github.com/huggingface/transformers/releases/tag/v4.46.0).

**Comment by ThiloteE** [comment]
Here is the documentation for how to add a new model to llama.cpp: https://github.com/ggerganov/llama.cpp/blob/master/docs/development/HOWTO-add-model.md

**Comment by nonetrix** [comment]
I wish I knew enough about C++, maybe I try it for lols not that I'll get far 😅
