### ISSUE TITLE
UGM tokenizer cost a long time than others

### ISSUE THREAD

**Issue by walsons** [ggerganov/llama.cpp#9180]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

UGM tokenizer is time-consuming when embedding text and is slower than others. When I debugged in the source code, I found the cause was the function llama_tokenize_internal() in the llama-vocab.cpp. llm_tokenizer_ugm will be constructed every time, but its constructor does a for-loop which is very time-consuming. Is there any way to accelerate the process, such as do the for-loop once and cache the needed data if the vocab does not change?

### Motivation

It will benefit users for llama.cpp who use an embedding model with UGM tokenizer like multilanguage-e5 or bge-m3...

**Comment by hiepxanh** [comment]
great debug, I think this will be useful since bge-m3 is very famous in embedding
