### ISSUE TITLE
Feature Request: Could you please add the latest version of llama.cpp to dockerhub?

### ISSUE THREAD

**Issue by vamshigvk** [ggerganov/llama.cpp#9223]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

We are in need of a docker tag with some value on the dockerhub instead of tag:"latest", could you please push atleast once with the latest or any of the versions to your dockerhub with name "https://hub.docker.com/r/ggerganov/llamacpp-server"

### Motivation

this will help us to pull the docker images from dockerhub instead of ghcr.io

**Comment by ngxson** [comment]
> We are in need of a docker tag with some value on the dockerhub instead of tag:"latest", could you please push atleast once with the latest or any of the versions to your dockerhub with name "https://hub.docker.com/r/ggerganov/llamacpp-server"

This is an experimental version, please **do not** use it.

ghcr.io registry works well, is there any reason why you don't want to use it?

**Comment by vamshigvk** [comment]
My team is not accepting the ghcr.io registry since the release names on github.com/ggerganov/llama.cpp repo and the tag names on ghcr.io registry are not matching. ( I noticed that you are using commit id as the tag id)

**Comment by boxley-anaconda** [comment]
Hi! I'm was looking for a pre-built image for llama-bench, and searching DockerHub found a match by @ggerganov:
https://hub.docker.com/r/ggerganov/llama-bench
However, that page has nothing (a browser-friendly 404 page).

Are there plans to upload an image somewhere? Maybe I'm looking in the wrong place?
