### ISSUE TITLE
Feature Request: Paligemma Support

### ISSUE THREAD

**Issue by The-TallGuy** [ggerganov/llama.cpp#9227]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Adding support for converting Google's multimodal Paligemma model to gguf in order to be used in ollama.

### Motivation

I have a personal project that requires a multimodal llm running locally and llava seems to be kind of...not great. I have seen an issue like this marked as open, but as of now, I still get an error when trying to convert from hf to gguf.

**Comment by ggerganov** [comment]
Wip: https://github.com/ggerganov/llama.cpp/pull/7553
