### ISSUE TITLE
Bug: Slow model loading with mmap

### ISSUE THREAD

**Issue by Azirine** [ggerganov/llama.cpp#9244]
### What happened?

Speeds of loading models into memory on M3 Max:
with mmap: ~730 MB/s
--no-mmap: ~6.4 GB/s

### Name and Version

version: 3642 (1d1ccce6)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.6.0

### What operating system are you seeing the problem on?

Mac

**Comment by hg0428** [comment]
I've noticed the same issue on the same hardware.
