### ISSUE TITLE
Bug: symbols conflict with whisper.cpp

### ISSUE THREAD

**Issue by thewh1teagle** [ggerganov/llama.cpp#9267]
### What happened?

I'm trying to use llama.cpp alongside whisper.cpp in Rust but I can't link the libraries because they link the same ggml symbols.

[llama-cpp-2](https://github.com/utilityai/llama-cpp-rs/blob/main/llama-cpp-sys-2/build.rs) and [whisper-rs](https://github.com/tazz4843/whisper-rs)

### Name and Version

8f1d81a0b6f50b9bad72db0b6fcd299ad9ecd48c
https://github.com/ggerganov/whisper.cpp/commit/c96906d84dd6a1c40ea797ad542df3a0c47307a3

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
b\\rustlib\\etc\\libstd.natvis"
  = note: libllama_cpp_sys_2-1131e8f6e28c8598.rlib(ggml-backend.obj) : error LNK2005: ggml_backend_buft_name already defined in libwhisper_rs_sys-f2fa5877d4809bf3.rlib(ggml-backend.obj)
          libllama_cpp_sys_2-1131e8f6e28c8598.rlib(ggml-backend.obj) : error LNK2005: ggml_backend_buft_alloc_buffer already defined in libwhisper_rs_sys-f2fa5877d4809bf3.rlib(ggml-backend.obj)
```

Is there a known solution for that? maybe adding prefix to the symbols? can it be configured at compile time per each library with cmake?

**Comment by thewh1teagle** [comment]
Does ggml version of llama.cpp synced with whisper.cpp so I can link ggml once?
Seems like ggml is not submodule here

**Comment by ggerganov** [comment]
The source code of the `ggml` library is synced regularly between `whisper.cpp` and `llama.cpp`

**Comment by mjsmith707** [comment]
I see the same with my own project. It would be good if both codebases shared the same ggml as a submodule as already mentioned. I went to manually merge in the libllama ggml stuff into libwhisper but there's enough differences as to be annoying.
