### ISSUE TITLE
Bug: GGML_ASSERT fail in ggml-rpc.cpp ggml_backend_rpc_buffer_init_tensor

### ISSUE THREAD

**Issue by jack2007** [ggerganov/llama.cpp#9285]
### What happened?

I'm trying to run [qwen2-72b-instruct-q3_k_m.gguf](https://huggingface.co/Qwen/Qwen2-72B-Instruct-GGUF/blob/main/qwen2-72b-instruct-q3_k_m.gguf) with ggml-rpc function on 2 3060*2 machine. 
Machine1:   192.168.136.200   run llama-cli
Machine2:   192.168.136.201   run rpc-server

`./llama-cli -m ./models/qwen2-72b-instruct-q3_k_m.gguf -ngl 99 --rpc 192.168.136.201:50052,192.168.136.201:50053 --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt`

Error Log:
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    2.11 MiB
ggml/src/ggml-rpc.cpp:396: GGML_ASSERT(tensor->ne[0] % 512 == 0 && "unsupported quantized tensor") failed
./llama-cli(+0x29427b)[0x56156b0bf27b]
./llama-cli(+0x296137)[0x56156b0c1137]
./llama-cli(+0x80b1e)[0x56156aeabb1e]
./llama-cli(+0x2d8f1a)[0x56156b103f1a]
./llama-cli(+0x2da982)[0x56156b105982]
./llama-cli(+0x34f22f)[0x56156b17a22f]
./llama-cli(+0x37dd09)[0x56156b1a8d09]
./llama-cli(+0x417726)[0x56156b242726]
./llama-cli(+0x5eaa6)[0x56156ae89aa6]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fc2179d4d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fc2179d4e40]

In ggml-rpc.cpp, there is GGML_ASSERT fail.
GGML_CALL static void ggml_backend_rpc_buffer_init_tensor(ggml_backend_buffer_t buffer, ggml_tensor * tensor) {
    UNUSED(buffer);
    if (ggml_is_quantized(tensor->type)) {
        // TODO: this check is due to MATRIX_ROW_PADDING in CUDA and should be generalized
        GGML_ASSERT(tensor->ne[0] % 512 == 0 && "unsupported quantized tensor");
    }
}

How can I fix this?
Thanks.

### Name and Version

llama-cli
code tag: b3651
version: 0 (unknown)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

**Comment by rgerganov** [comment]
Thanks for the bug report. We need to find out how to support Q3_K_M in the RPC backend.
