### ISSUE TITLE
Feature Request: How to support model with dynamic inference graph

### ISSUE THREAD

**Issue by RunningLeon** [ggerganov/llama.cpp#9297]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

How to support model that has dynamic inference graph between prefiling and decoding stages.  

Hi, thanks for your notice. I want to support model in llama.cpp that has a different compute graph between prefilling and decoding stages. I wonder if llama.cpp support dynamic inference graph(skip some layers in prefill stages). If so, how to do this ?

![image](https://github.com/user-attachments/assets/ed0810fb-da2f-438d-a6e6-9c50fc5a3e6a)

### Motivation

speed up prefilling by skipping some layers

### Possible Implementation

Adding a flag `is_prefilling` in `llama_context` just like `is_encoding`?

**Comment by exhyy** [comment]
Same question. Any update?
