### ISSUE TITLE
Feature Request: Add Host buffer type for Ascend NPU (CANN backend)

### ISSUE THREAD

**Issue by hipudding** [ggerganov/llama.cpp#9304]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Ascend NPU backend (CANN) is not support pin memory(Host buffer type) now. Using ping memory will make it more efficiency.

### Motivation

Other backend such as CUDA has already support Host buffer type.

### Possible Implementation

Refer to CUDA to implement the Host buffer type of Ascend NPU.

**Comment by VoidIsVoid** [comment]
How much of a performance boost will there be?

**Comment by hipudding** [comment]
> How much of a performance boost will there be?

According to the current test, the performance improvement is not obvious, and it is not a performance bottleneck at present
