### ISSUE TITLE
Bug: RWKV 6 Finch 3B+ models crash llama.cpp with CPU backend

### ISSUE THREAD

**Issue by mtasic85** [ggerganov/llama.cpp#9315]
### What happened?

I cloned latest version from git, compiled it on ArchLinux, CPU backend only, using `make`.

I downloaded following models, but both did not run:
bartowski/v6-Finch-3B-HF-GGUF (Q4*, Q8*)
bartowski/v6-Finch-7B-HF-GGUF (Q4*, Q8*)

I run following command:
```bash
./llama-cli -m "v6-Finch-7B-HF-Q4_K_M.gguf" -p "I believe the meaning of life is" -n 128
```

### Name and Version

version: 3664 (82e3b03c)
built with cc (GCC) 14.2.1 20240805 for x86_64-pc-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Log start
main: build = 3664 (82e3b03c)
main: built with cc (GCC) 14.2.1 20240805 for x86_64-pc-linux-gnu
main: seed  = 1725469492
llama_model_loader: loaded meta data with 26 key-value pairs and 902 tensors from v6-Finch-7B-HF-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = rwkv6
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = v6 Finch 7B HF
llama_model_loader: - kv   3:                           general.finetune str              = HF
llama_model_loader: - kv   4:                           general.basename str              = v6-Finch
llama_model_loader: - kv   5:                         general.size_label str              = 7B
llama_model_loader: - kv   6:                            general.license str              = apache-2.0
llama_model_loader: - kv   7:                       rwkv6.context_length u32              = 1048576
llama_model_loader: - kv   8:                     rwkv6.embedding_length u32              = 4096
llama_model_loader: - kv   9:                          rwkv6.block_count u32              = 32
llama_model_loader: - kv  10:         rwkv6.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  11:               rwkv6.rescale_every_n_layers u32              = 6
llama_model_loader: - kv  12:                        rwkv6.wkv.head_size u32              = 64
llama_model_loader: - kv  13:                   rwkv6.time_mix_extra_dim u32              = 64
llama_model_loader: - kv  14:                 rwkv6.time_decay_extra_dim u32              = 128
llama_model_loader: - kv  15:                  rwkv6.feed_forward_length u32              = 14336
llama_model_loader: - kv  16:                          general.file_type u32              = 15
llama_model_loader: - kv  17:                 rwkv6.attention.head_count u32              = 0
llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = rwkv
llama_model_loader: - kv  19:                      tokenizer.ggml.tokens arr[str,65536]   = ["<s>", "\\x00", "\\x01", "\\x02", "\...
llama_model_loader: - kv  20:                  tokenizer.ggml.token_type arr[i32,65536]   = [3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - kv  22:                      quantize.imatrix.file str              = /models_out/v6-Finch-7B-HF-GGUF/v6-Fi...
llama_model_loader: - kv  23:                   quantize.imatrix.dataset str              = /training_dir/calibration_datav3.txt
llama_model_loader: - kv  24:             quantize.imatrix.entries_count i32              = 352
llama_model_loader: - kv  25:              quantize.imatrix.chunks_count i32              = 131
llama_model_loader: - type  f32:  580 tensors
llama_model_loader: - type q5_0:   32 tensors
llama_model_loader: - type q4_K:  289 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 1
llm_load_vocab: token to piece cache size = 0.3561 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = rwkv6
llm_load_print_meta: vocab type       = RWKV
llm_load_print_meta: n_vocab          = 65536
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 1048576
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 0
llm_load_print_meta: n_head_kv        = 0
llm_load_print_meta: n_rot            = 0
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 0
llm_load_print_meta: n_embd_head_v    = 0
llm_load_print_meta: n_gqa            = 0
llm_load_print_meta: n_embd_k_gqa     = 0
llm_load_print_meta: n_embd_v_gqa     = 0
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = -1
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 1048576
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 7.64 B
llm_load_print_meta: model size       = 4.34 GiB (4.88 BPW) 
llm_load_print_meta: general.name     = v6 Finch 7B HF
llm_load_print_meta: LF token         = 11 '\n'
llm_load_print_meta: max token length = 192
llm_load_tensors: ggml ctx size =    0.35 MiB
llm_load_tensors:        CPU buffer size =  4446.06 MiB
...............................................................................................
llama_new_context_with_model: n_ctx      = 1048576
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =    33.00 MiB
llama_new_context_with_model: KV self size  =   33.00 MiB, K (f32):    1.00 MiB, V (f32):   32.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.25 MiB
llama_new_context_with_model:        CPU compute buffer size =   144.00 MiB
llama_new_context_with_model: graph nodes  = 3631
llama_new_context_with_model: graph splits = 1
fish: Job 1, './llama-cli -m ".c…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by RachidAR** [comment]
Same problem. I build with `LLAMA_DEBUG=1` and I got: 
``llama-cli: ggml/src/ggml.c:13690: ggml_compute_forward_get_rows_q: Assertion `i01 >= 0 && i01 < ne01' failed.
fish: Job 1, './llama-cli -t 14 -c 4096 -m /r…' terminated by signal SIGABRT (Abort)``

[OS: Linux]

**Comment by mtasic85** [comment]
Same with Vulkan backend on ArchLinux with AMD Radeon RX 5700 XT (with `-ngl 99`).

**Comment by RachidAR** [comment]
I was able to get it running by setting `i01` to `0` during the first iteration of the for-loop, though this might not be the correct approach. (CPU backend)

```Log start
main: build = 3669 (4db04784)
main: built with cc (GCC) 14.2.1 20240805 for x86_64-pc-linux-gnu
main: seed  = 1725535559
llama_model_loader: loaded meta data with 26 key-value pairs and 902 tensors from v6-finch-7b-hf-q5_k_m-imat.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = rwkv6
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = v6 Finch 7B HF
llama_model_loader: - kv   3:                           general.finetune str              = HF
llama_model_loader: - kv   4:                           general.basename str              = v6-Finch
llama_model_loader: - kv   5:                         general.size_label str              = 7B
llama_model_loader: - kv   6:                            general.license str              = apache-2.0
llama_model_loader: - kv   7:                       rwkv6.context_length u32              = 1048576
llama_model_loader: - kv   8:                     rwkv6.embedding_length u32              = 4096
llama_model_loader: - kv   9:                          rwkv6.block_count u32              = 32
llama_model_loader: - kv  10:         rwkv6.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  11:               rwkv6.rescale_every_n_layers u32              = 6
llama_model_loader: - kv  12:                        rwkv6.wkv.head_size u32              = 64
llama_model_loader: - kv  13:                   rwkv6.time_mix_extra_dim u32              = 64
llama_model_loader: - kv  14:                 rwkv6.time_decay_extra_dim u32              = 128
llama_model_loader: - kv  15:                  rwkv6.feed_forward_length u32              = 14336
llama_model_loader: - kv  16:                          general.file_type u32              = 17
llama_model_loader: - kv  17:                 rwkv6.attention.head_count u32              = 0
llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = rwkv
llama_model_loader: - kv  19:                      tokenizer.ggml.tokens arr[str,65536]   = ["<s>", "\\x00", "\\x01", "\\x02", "\...
llama_model_loader: - kv  20:                  tokenizer.ggml.token_type arr[i32,65536]   = [3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - kv  22:                      quantize.imatrix.file str              = llama.cpp/imatrix.dat
llama_model_loader: - kv  23:                   quantize.imatrix.dataset str              = /tmp/gradio/ee42d200909017806466fb76a...
llama_model_loader: - kv  24:             quantize.imatrix.entries_count i32              = 352
llama_model_loader: - kv  25:              quantize.imatrix.chunks_count i32              = 20
llama_model_loader: - type  f32:  580 tensors
llama_model_loader: - type q5_1:   32 tensors
llama_model_loader: - type q5_K:  289 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 1
llm_load_vocab: token to piece cache size = 0.3561 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = rwkv6
llm_load_print_meta: vocab type       = RWKV
llm_load_print_meta: n_vocab          = 65536
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 1048576
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 0
llm_load_print_meta: n_head_kv        = 0
llm_load_print_meta: n_rot            = 0
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 0
llm_load_print_meta: n_embd_head_v    = 0
llm_load_print_meta: n_gqa            = 0
llm_load_print_meta: n_embd_k_gqa     = 0
llm_load_print_meta: n_embd_v_gqa     = 0
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = -1
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 1048576
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 7.64 B
llm_load_print_meta: model size       = 5.19 GiB (5.84 BPW) 
llm_load_print_meta: general.name     = v6 Finch 7B HF
llm_load_print_meta: LF token         = 11 '\n'
llm_load_print_meta: max token length = 192
llm_load_tensors: ggml ctx size =    0.35 MiB
llm_load_tensors:        CPU buffer size =  5313.06 MiB
...............................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =    33.00 MiB
llama_new_context_with_model: KV self size  =   33.00 MiB, K (f32):    1.00 MiB, V (f32):   32.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.25 MiB
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 144.00 MiB
llama_new_context_with_model:        CPU compute buffer size =   144.00 MiB
llama_new_context_with_model: graph nodes  = 3631
llama_new_context_with_model: graph splits = 1

system_info: n_threads = 14 (n_threads_batch = 14) / 28 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 1.000
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 4096, n_batch = 2048, n_predict = -1, n_keep = 0


Once upon on a time, there was a little girl named Lucy. She was very happy. She had a
```

**Comment by RachidAR** [comment]
> I was able to get it running by setting `i01` to `0` during the first iteration of the for-loop, though this might not be the correct approach. (CPU backend)

CUDA backend with overwritten `i01`:
```...
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.70 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =   176.09 MiB
llm_load_tensors:      CUDA0 buffer size =  5137.04 MiB
...............................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =    33.00 MiB
llama_new_context_with_model: KV self size  =   33.00 MiB, K (f32):    1.00 MiB, V (f32):   32.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.25 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   144.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    42.02 MiB
llama_new_context_with_model: graph nodes  = 3631
llama_new_context_with_model: graph splits = 101

system_info: n_threads = 14 (n_threads_batch = 14) / 28 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 1.000
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 4096, n_batch = 2048, n_predict = -1, n_keep = 0


Once upon on a time, there was a big, hairy dog named Max. Max loved to play with his ball. Every day, he would run and jump to catch it.
One day, Max saw a big tree. He wanted to climb it. When he got to the top, he saw a big, round ball. Max thought it was the best ball he had ever seen. He wanted to play with it.
Max jumped and jumped, but he could not get the ball. Then, something unexpected happened. The ball started to shrink! Max was surprised. The ball got smaller and smaller until it was the size of a normal ball. Max was happy to have a new ball to play with.
Summary: A big, hairy dog named Max saw a big tree and climbed it to get a big, round ball that shrunk to the size of a normal ball, which he was happy to have.Q: What is your review of The Big Bang Theory (2007 tv series)?

A: , What can I say? This show has changed my life., As a young kid in the 2000s, I was a huge fan of the shows on Fox. I used to watch cartoons such as King of the Hill, Family Guy, Futurama, etc. But as soon as I became a

llama_print_timings:        load time =    5721.96 ms
llama_print_timings:      sample time =     289.71 ms /   269 runs   (    1.08 ms per token,   928.51 tokens per second)
llama_print_timings: prompt eval time =      96.51 ms /     3 tokens (   32.17 ms per token,    31.08 tokens per second)
llama_print_timings:        eval time =   10478.85 ms /   268 runs   (   39.10 ms per token,    25.58 tokens per second)
llama_print_timings:       total time =   10945.60 ms /   271 tokens
```

**Comment by SpaceCowboy850** [comment]
This is interesting...I'm running an embedding model via llama-embedding and hitting the same assert.

I get it in both
ggml_compute_forward_get_rows_f16
ggml_compute_forward_get_rows_q

And I've tried to run on the following models:
https://huggingface.co/intfloat/e5-large-unsupervised
https://huggingface.co/BAAI/bge-base-en-v1.5

My Repo:
`huggingface-cli download BAAI/bge-base-en-v1.5 --local-dir .\bge-base-en-v1.5 --local-dir-use-symlinks False
python convert_hf_to_gguf.py .\bge-base-en-v1.5 --outfile=bge-base-en-v1.5.gguf
.\vs2022_cuda\bin\Debug\llama-embedding.exe -m bge-base-en-v1.5.gguf -m bge-base-en-v1.5.gguf --embd-output-format json+ --prompt "Never have I seen a poem as lovely as a tree.\n I love writing about trees \n Where are we going to eat today?"`

Assertion failed: i01 >= 0 && i01 < ne01, file .\ggml\src\ggml.c, line 13263

System is Windows 11, Cuda 12.6.

I'm going to put in a clamp to 0 as described above, but I'm not sure if that is the right call, as I haven't really parsed in detail what that code is doing.

**Comment by MollySophia** [comment]
Hi @SpaceCowboy850 @RachidAR @mtasic85 !
Please try adding `--no-warmup` parameter and see if it still crashes.
With a warmup, it inferences a `bos_token` first, which RWKV doesn't have from what I know. This leads to an empty tokens tensor being input into get_rows.

**Comment by RachidAR** [comment]
> Hi @SpaceCowboy850 @RachidAR @mtasic85 ! Please try adding `--no-warmup` parameter and see if it still crashes. ~With a warmup, it inferences a `eos_token` first, ~which RWKV doesn't have from what I know~which seems to be absent by accident. This leads to an empty tensor being input into get_rows.~ With a warmup, it inferences a `eos_token` first. However, RWKV gguf has eos_token=-1;tokenizer_add_eos=false. This leads to a tensor with a single value -1 being input into get_rows.

With `--no-warmup` parameter it works now. (build = 3673, CUDA backend)

**Comment by mtasic85** [comment]
@MollySophia Yes, adding `--no-warmup` helped, so I was able to run with both **CPU** and **Vulkan** backends.

Unrelated to the issue, but it might be helpful to someone, if you tell **RWKV 6 Finch** models to output/generate `"<s>"`, which is special BOS token, you can use this token to know when to stop RWKV 6 Finch models from indefinitely hallucinating. Also only **Q8** versions of models worked predictably even for **1b6** model.

Example of prompt written to file `prompt_27.txt`:
```
Instruction:
You will be given Context and Input. You must generate a concise and precise Response. You should not ask questions. When Response is complete, end with text "<s>".

[Context]
User:
I need you to respond to my task.

AI:
How can I help you?
[End of Context]

Input:
What is the meaning of life?
Also explain universe and cosmos to me.

Response:\n
```

Previous conversation is between `[Context]` and `[End of Context]`, and current User message is in Input, and Assistant reply will be in Response.

We run it with command:
```bash
./llama-cli -m "rwkv-6-finch-1b6-q8_0.gguf" -f "prompt_27.txt" -ngl 99 -sp --temp 1.0 --top-p 0.3 --top-k 0 --repeat-last-n 64 --presence-penalty 0.7
```

We examined prompt examples from:
- Original model with some instructions: https://huggingface.co/RWKV/v6-Finch-1B6-HF
- Original version: https://github.com/shoumenchougou/Awesome-RWKV-Prompts
- English version: https://github-com.translate.goog/shoumenchougou/Awesome-RWKV-Prompts?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

**Comment by MollySophia** [comment]
> @MollySophia Yes, adding `--no-warmup` helped, so I was able to run with both **CPU** and **Vulkan** backends.
> 
> Unrelated to the issue, but it might be helpful to someone, if you tell **RWKV 6 Finch** models to output/generate `"<s>"`, which is special BOS token, you can use this token to know when to stop RWKV 6 Finch models from indefinitely hallucinating. Also only **Q8** versions of models worked predictably even for **1b6** model.
> 
> Example of prompt written to file `prompt_27.txt`:
> 
> ```
> Instruction:
> You will be given Context and Input. You must generate a concise and precise Response. You should not ask questions. When Response is complete, end with text "<s>".
> 
> [Context]
> User:
> I need you to respond to my task.
> 
> AI:
> How can I help you?
> [End of Context]
> 
> Input:
> What is the meaning of life?
> Also explain universe and cosmos to me.
> 
> Response:\n
> ```
> 
> Previous conversation is between `[Context]` and `[End of Context]`, and current User message is in Input, and Assistant reply will be in Response.
> 
> We run it with command:
> 
> ```shell
> ./llama-cli -m "rwkv-6-finch-1b6-q8_0.gguf" -f "prompt_27.txt" -ngl 99 -sp --temp 1.0 --top-p 0.3 --top-k 0 --repeat-last-n 64 --presence-penalty 0.7
> ```
> 
> We examined prompt examples from:
> 
> * Original model with some instructions: https://huggingface.co/RWKV/v6-Finch-1B6-HF
> * Original version: https://github.com/shoumenchougou/Awesome-RWKV-Prompts
> * English version: https://github-com.translate.goog/shoumenchougou/Awesome-RWKV-Prompts?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

Yes. I'm aware that v6 Finch HF models use '<s>' (id=0) for bos/eos. However, I think '\n\n' is also an eos token accepted by RWKV. So I'm not sure about which one to use.

**Comment by MollySophia** [comment]
> @MollySophia Yes, adding `--no-warmup` helped, so I was able to run with both **CPU** and **Vulkan** backends.
> 
> Unrelated to the issue, but it might be helpful to someone, if you tell **RWKV 6 Finch** models to output/generate `"<s>"`, which is special BOS token, you can use this token to know when to stop RWKV 6 Finch models from indefinitely hallucinating. Also only **Q8** versions of models worked predictably even for **1b6** model.
> 
> Example of prompt written to file `prompt_27.txt`:
> 
> ```
> Instruction:
> You will be given Context and Input. You must generate a concise and precise Response. You should not ask questions. When Response is complete, end with text "<s>".
> 
> [Context]
> User:
> I need you to respond to my task.
> 
> AI:
> How can I help you?
> [End of Context]
> 
> Input:
> What is the meaning of life?
> Also explain universe and cosmos to me.
> 
> Response:\n
> ```
> 
> Previous conversation is between `[Context]` and `[End of Context]`, and current User message is in Input, and Assistant reply will be in Response.
> 
> We run it with command:
> 
> ```shell
> ./llama-cli -m "rwkv-6-finch-1b6-q8_0.gguf" -f "prompt_27.txt" -ngl 99 -sp --temp 1.0 --top-p 0.3 --top-k 0 --repeat-last-n 64 --presence-penalty 0.7
> ```
> 
> We examined prompt examples from:
> 
> * Original model with some instructions: https://huggingface.co/RWKV/v6-Finch-1B6-HF
> * Original version: https://github.com/shoumenchougou/Awesome-RWKV-Prompts
> * English version: https://github-com.translate.goog/shoumenchougou/Awesome-RWKV-Prompts?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

Also for RWKV, I think it's better to do conversation like this: `User: <User input>\n\nAssistant:`

**Comment by mtasic85** [comment]
Based on my experience with RWKV 6 Finch, at least for that model, please use `<s>` as bos/eos.

Reason why I am not in favor of `\n\n` is that it is used as space deliminator in Python code, https://peps.python.org/pep-0008/ . RWKV 6 Finch generates Python code with `\n\n`.

**Comment by MollySophia** [comment]
> Based on my experience with RWKV 6 Finch, at least for that model, please use `<s>` as bos/eos.
> 
> Reason why I am not in favor of `\n\n` is that it is used as space deliminator in Python code, https://peps.python.org/pep-0008/ . RWKV 6 Finch generates Python code with `\n\n`.

Thanks for the info. I didn't know about this.
I just checked the base model on huggingface(https://huggingface.co/RWKV/rwkv-6-world-1b6) and it's also using `\<s\>`.

> > User: \n\nAssistant:
> 
> If you use this alternating template with more shots, it will be hard to get `<s>` as last token to identify EOS.
> 
> That is reason why we have `Instruction:` as system prompt, `[Context]` as previous conversation and on purpose we used `Input:` (for User) and `Response:` (for Assistant) at very end. If you use `User:` instead of `Input:` you will get so much hallucination. Same applies for `Assistant:`.

Yes. From my experience, I've been using both \n\n and token_id=0 as the eos.

**Comment by MollySophia** [comment]
So I guess then it's better add eos token in convert script, rather than add an exception in warmup like in #9333 ?

**Comment by mtasic85** [comment]
Probably @compilade can give an advice. :smiley:

**Comment by BlinkDL** [comment]
> Based on my experience with RWKV 6 Finch, at least for that model, please use `<s>` as bos/eos.
> 
> Reason why I am not in favor of `\n\n` is that it is used as space deliminator in Python code, https://peps.python.org/pep-0008/ . RWKV 6 Finch generates Python code with `\n\n`.

My hack: use this to clean input first:

def clean_txt(txt):
    txt = re.sub(r'\n{2,}', '\n', txt.replace('\r\n','\n')).strip()
    return txt

then the model wont produce \n\n within its answer, unless for \n\nUser: \n\nAssistant:

**Comment by BlinkDL** [comment]
Sometimes the model will produce [0] as eod, and you can take the opportunity to end the generation.

Hence here is my chat implementation: https://github.com/BlinkDL/ChatRWKV/blob/main/API_DEMO_CHAT.py

**Comment by mtasic85** [comment]
@BlinkDL For template `User: \n\nAssistant:` which keeps repeating these roles, how to end Assistant message? Also, is there any good way to recognize/generate EOD/EOS in general, so token generation can be interrupted?

**Comment by compilade** [comment]
> So I guess then it's better add eos token in convert script, rather than add an exception in warmup like in #9333 ?

@MollySophia 

Yes, I think it would be better for the EOS token to at least be *something* for RWKV models converted to GGUF. (the value could be set with something like

```python3
        special_vocab = gguf.SpecialVocab(self.dir_model, load_merges=False)
        special_vocab.add_to_gguf(self.gguf_writer)
```

(which takes the eos token id value from the `eos_token_id` field in `config.json`))

But I think it can also be good to make the warmup never use an invalid token id, so #9333 still seems relevant.

**Comment by BlinkDL** [comment]
> @BlinkDL For template `User: \n\nAssistant:` which keeps repeating these roles, how to end Assistant message? Also, is there any good way to recognize/generate EOD/EOS in general, so token generation can be interrupted?

please check https://github.com/BlinkDL/ChatRWKV/blob/main/API_DEMO_CHAT.py

**Comment by SpaceCowboy850** [comment]
@MollySophia Yes - I found the no-warmup makes it "work".  But I was unsure if that was a real fix.

So for my case, though a 'real' fix might be to not have an empty string as a warmup?

Either way, I think I understand the problem better now that you explained it.

**Comment by MollySophia** [comment]
> @MollySophia Yes - I found the no-warmup makes it "work". But I was unsure if that was a real fix.
> 
> So for my case, though a 'real' fix might be to not have an empty string as a warmup?
> 
> Either way, I think I understand the problem better now that you explained it.

Note that currently a fix is already done. When both bos and eos are -1, it uses token id 0 to do the warmup.

**Comment by mtasic85** [comment]
About eos and bos, can you please check https://huggingface.co/RWKV/v6-Finch-1B6-HF/blob/main/special_tokens_map.json ?

It seams that they have their values all set to 0.

**Comment by mtasic85** [comment]
> Yes. The reason why I'm hesitating is that modifying the converter script would make these already converted rwkv gguf files obsolete, thus the authors need to convert and upload them again. (That's also my fault though :(

I don't think this would be a big problem. There are not many GGUF models released. Also, https://huggingface.co/latestissue released new versions yesterday after many already released versions before, so that contributor is active and we can reach them, so we can get new quantized models.

We can get this right once, and have no problem in the future. RWKV support is young and I do not think that many people are using it now.

**Comment by MollySophia** [comment]
> > Yes. The reason why I'm hesitating is that modifying the converter script would make these already converted rwkv gguf files obsolete, thus the authors need to convert and upload them again. (That's also my fault though :(
> 
> I don't think this would be a big problem. There are not many GGUF models released. Also, https://huggingface.co/latestissue released new versions yesterday after many already released versions before, so that contributor is active and we can reach them, so we can get new quantized models.
> 
> We can get this right once, and have no problem in the future. RWKV support is young and I do not think that many people are using it now.

I agree with you. It's better fix it once and for all as quick as possible.
