### ISSUE TITLE
perf: Investigate performance discrepancy with llama-rs - 1.5x-2x slower

### ISSUE THREAD

**Issue by jon-chuang** [ggerganov/llama.cpp#932]
Preliminary results show that `llama.cpp` is 1.5x-2x _slower_ than `llama-rs`. They were both checked to compile with the same arch flags and use the same gnu toolchain.

Summary (on `Vicuna 13B, 2048 ctx size, 256 predict tokens`):
- `llama.cpp`: **430.44 ms** per run
- `llama-rs`: per_token_duration: **272.793ms**

[Detailed results](https://github.com/rustformers/llama-rs/issues/131#issuecomment-1506246836)

An interesting observation is that CPU util is _lower_ on llama-rs.

System Info:

llama.cpp
```
> make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:  
I CC:       cc (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
I CXX:      g++ (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0

./main
system_info: n_threads = 16 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
```

llama-rs
```
warning: Using gnu
warning: Using MAVX
warning: Using AVX2
warning: Using FMA
warning: Using F16C
warning: Using SSE3
```
No BLAS.

Notes: llama-rs bench runs on [my branch](https://github.com/rustformers/llama-rs/pull/129).

**Comment by ggerganov** [comment]
I think I made a regression in https://github.com/ggerganov/llama.cpp/commit/c3ac702e5ee3533457e0489df4906ee112fe88e7

Can you check that reverting it solves the issue?

**Comment by jon-chuang** [comment]
I checked out https://github.com/ggerganov/llama.cpp/commit/9d634ef452d0fc24fcd49592952d13d0ab0f41b7. There was no improvement, and in fact, a regression.

**Comment by jon-chuang** [comment]
[llama-rs](https://user-images.githubusercontent.com/9093549/231643492-2ab2187c-8bb8-416c-be22-6e9f59a3e3ab.webm)
[llama.cpp](https://user-images.githubusercontent.com/9093549/231643501-23efd08b-8d26-4838-b96c-64fc3783881e.webm)

**Comment by jon-chuang** [comment]
One possibility that I thought of is that llama-rs doesn't give any `mem_buffer` or `buf_compute`

**Comment by jon-chuang** [comment]
Oops, I found the issue: using hyperthreading (https://github.com/ggerganov/llama.cpp/issues/34#issuecomment-1465313724):

-t 8 -n 128
```
llama_print_timings:        load time =  1421.72 ms
llama_print_timings:      sample time =    74.37 ms /   128 runs   (    0.58 ms per run)
llama_print_timings: prompt eval time =   720.68 ms /     4 tokens (  180.17 ms per token)
llama_print_timings:        eval time = 34420.26 ms /   127 runs   (  271.03 ms per run)
llama_print_timings:       total time = 35918.93 ms
```

**Comment by jon-chuang** [comment]
I think we should make the default number of real CPU cores. Agreed? @ggerganov
