### ISSUE TITLE
Feature Request: Priority for RPC servers

### ISSUE THREAD

**Issue by ecyht2** [ggerganov/llama.cpp#9323]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Add a way to prioritize which RPC server to use.

### Motivation

I want to prioritize which RPC server to use. This allows me to manually tell llama.cpp to use the RPC servers that are more powerful first before using a weaker ones, optimizing the speed.

### Possible Implementation

1. Add a new option to set which ones to use first.
2. Add and option to use the RPC servers that are given first. e.g. `--rpc server1:50052,server2:50052` would use `server1:50052` until all the memory is used up before using `server2:50052` (The current behavior is split them evenly).

**Comment by slaren** [comment]
You can use `--tensor-split` to configure the proportion of the model that is offloaded to each RPC server and/or local GPUs.

**Comment by ecyht2** [comment]
> You can use `--tensor-split` to configure the proportion of the model that is offloaded to each RPC server and/or local GPUs.

Thanks for the reply but it is not quite what I am looking for. What I want is to put all the tensors in the more powerful RPC server until it is full, then start filling up the next one and continue until all tensors are loaded.

**Comment by ecyht2** [comment]
After some thinking, I can just do some calculations and split them accordingly just like what ollama implemented. Thanks for the help.
