### ISSUE TITLE
Bug: generate at most 400 tokens.

### ISSUE THREAD

**Issue by hnhyzz** [ggerganov/llama.cpp#9368]
### What happened?

No matter how large the -n param (number of tokens to be predicted) was set to, only 400 tokens will be generated. i.e., n_decoded=400 will be printed in the console.

### Name and Version

version: 3535 (1e6f6554)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
INFO [           print_timings] generation eval time =   45575.74 ms /   400 runs   (  113.94 ms per token,     8.78 tokens per second) | tid="138641204175808" timestamp=1725795768 id_slot=0 id_task=0 t_token_generation=45575.739 n_decoded=400 t_token=113.9393475 n_tokens_second=8.776599321845335


In web browser side, the response is: data: {"content":"","id_slot":0,"stop":true,"model":"
```

**Comment by ggerganov** [comment]
Likely the request overrides the `n_predict` value

**Comment by hnhyzz** [comment]
> Likely the request overrides the `n_predict` value

Got it! The default web page overrides the n_predict value to 400.
