### ISSUE TITLE
Bug: When using KV quantization, if a context shift occurs, the application will crash.

### ISSUE THREAD

**Issue by neavo** [ggerganov/llama.cpp#9383]
### What happened?

When ctx kv quantization is enabled, if the task's context length exceeds the threshold and triggers a context shift, the application will throw an error and crash.

![image](https://github.com/user-attachments/assets/04c9c6b4-b8ad-4137-9872-c2f365eeb606)

### Name and Version

[b3706](https://github.com/ggerganov/llama.cpp/releases/tag/b3706)

### What operating system are you seeing the problem on?

Windows 11 24H2

llama-server.exe -m .\glm_4_9b_chat_Q6_K_L.gguf -fa --no-mmap -cb -np 16 -c 32768 -ngl 999 -ctk q4_0 -ctv q4_0

**Comment by ngxson** [comment]
Fow now, `-ctk q4_0 -ctv q4_0` are not compatible with kv shift

**Comment by neavo** [comment]
> For now, `-ctk q4_0 -ctv q4_0` are not compatible with kv shift

Thank you for the answer. So, this is a feature and not a bug, correct? Do we have plans to continue its development?

**Comment by ngxson** [comment]
It's currently a bug (since a long time ago). But is less priority, so we will do that later. Ref: #5652
