### ISSUE TITLE
Bug: docker GGML_CUDA=1 make [on llama-gen-docs] fails since arg refactor

### ISSUE THREAD

**Issue by bartowski1182** [ggerganov/llama.cpp#9392]
### What happened?

Error given is

```
./llama-gen-docs: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

Since this was only recently added in https://github.com/ggerganov/llama.cpp/pull/9308 I'm guessing that's to blame

I've been able to get around it by running:

```
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
RUN LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/:$LD_LIBRARY_PATH GGML_CUDA=1 make -j64
RUN rm /usr/local/cuda/lib64/stubs/libcuda.so.1
```

but I guess my question is just *why* does it need this library at all and why is only this one failing?

### Name and Version

b3707 ubuntu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
./llama-gen-docs: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by bartowski1182** [comment]
I use make locally, is there a reason to prefer cmake?

**Comment by slaren** [comment]
Only the cmake build has all the options and the best defaults. For local testing make is ok, but cross-compiling and more advanced options cmake is necessary. The images were changed to use `cmake` to be able to link dynamically, and to set better defaults for the CUDA archs.
