### ISSUE TITLE
MSYS2/MinGW64 Text generation continues even when reverse prompts are specified.

### ISSUE THREAD

**Issue by 1OOyan** [ggerganov/llama.cpp#941]
llama.cpp often continues to generate tokens even I specify the necessary reverse prompts: '### Human:' or 'Character:'
I am running in interactive mode, sometimes I get back the control, but often it takes one or more turns where llama.cpp skips to detect that the reverse prompt strings are in the token stream and hand back control.
Impact: bad chat experience.

**Environment**: MSYS2/Mingw64. Latest llama.cpp version from master.

Interestingly I don't experience the same problem if I compile with VS2019.

**Model used**: Vicuna 13B:
ggml-vicuna-13B-1.1-q4_0.bin

**Command line**:
./main.exe -i -f prompts/chat-with-samantha.txt -m ggml-vicuna-13B-1.1-q4_0.bin -r 'You:' -r '### Human:' -r 'Stan:' --color -t 8 --keep -1 -c 2048 -n -1

Tried specifying the reverse prompt both with single and double quotes - same result.

**Comment by taka-tuos** [comment]
I ran into the same problem, but using '###' for the reverse prompt stopped the output correctly.  However, '### ' (adding a space at the end) did not stop it, so I think there is a high possibility that there is a problem with handling spaces.

**Comment by batmanonline** [comment]
Possible duplicate of issues https://github.com/ggerganov/llama.cpp/discussions/990 https://github.com/ggerganov/llama.cpp/issues/941
