### ISSUE TITLE
Feature Request: Any plan to support TTS or ASR model?

### ISSUE THREAD

**Issue by gryffindor-rr** [ggerganov/llama.cpp#9425]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

RT.

### Motivation

As the device side requirement for communicating in voice, just wondering any plan to support TTS and ASR model in llama.cpp? like hubert model, onnx model, etc.

**Comment by mirek190** [comment]
yes .. I would love to see it !

**Comment by JohannesGaessler** [comment]
I can only speak for myself but so far I have no plans to work on audio.

**Comment by mirek190** [comment]
Look 

https://huggingface.co/ICTNLP/Llama-3.1-8B-Omni

We have already based on llama 3.1 model that can understand voice and answer by own voice !

**Comment by ecyht2** [comment]
There is a discussion about it (TTS only) over at the ggml repo https://github.com/ggerganov/ggml/issues/59. Also for ASR you can check out https://github.com/ggerganov/whisper.cpp
