### ISSUE TITLE
Bug: There is an issue to execute llama-baby-llama.

### ISSUE THREAD

**Issue by Foreverythin** [ggerganov/llama.cpp#9478]
### What happened?

Whenever I go to execute llama-baby-llama, I get “ggml/src/ggml.c:6793: GGML_ASSERT(false && ‘backwards pass not implemented’) failed “ error.

### Name and Version

./llama-baby-llama -m ./models/Qwen-7B-Chat/Qwen-7B-Chat-Q4_0.gguf -p "I believe the meaning of life is" -n 128

### What operating system are you seeing the problem on?

Linux

**Comment by VJHack** [comment]
Commit `202084d31d4247764fc6d6d40d2e2bda0c89a73a` introduces this breaking change, though I'm not familiar with it.
