### ISSUE TITLE
No `convert-pth-to-ggml` windows executable?

### ISSUE THREAD

**Issue by xzuyn** [ggerganov/llama.cpp#948]
Do I have to build the repo in order to convert and quantize? I was hoping I could just use the provided executables, but its missing the pth conversion.

**Comment by xzuyn** [comment]
any reason why there's executables for everything else, but not for the conversion?

**Comment by prusnak** [comment]
`convert-pth-to-ggml.py` is a python script, you need to call `python3 convert-pth-to-ggml.py ...` to run it.

**Comment by xzuyn** [comment]
script only needs these in case anyone's wondering;

1. numpy
2. torch
3. sentencepiece
