### ISSUE TITLE
Bug: andriod compiling bug, with vulkan open

### ISSUE THREAD

**Issue by bitxsw93** [ggerganov/llama.cpp#9489]
### What happened?

![image](https://github.com/user-attachments/assets/ca70713b-f590-4314-83ca-4f8ad0f6910f)

### Name and Version

commit 06943a69f678fb32829ff06d9c18367b17d4b361 (HEAD -> master, tag: b3581)
Author: Daniel Bevenius <daniel.bevenius@gmail.com>
Date:   Tue Aug 13 21:13:15 2024 +0200

### Relevant log output

```shell
if -DGGML_VULKAN=OFF, then it compiles well.
So, how to compile andriod vulkan with ndk. （my vulkan sdk works well with vulkaninfo）
```

**Comment by bitxsw93** [comment]
my device is mac m3.  it seems there is no vulkan-shaders-gen tools in Vulkan SDK dir.

**Comment by FranzKafkaYu** [comment]
@bitxsw93  hope [this](https://github.com/ggerganov/llama.cpp/discussions/8874#discussioncomment-10334591) can help you
