### ISSUE TITLE
Bug: can not merge gguf, gguf_init_from_file: invalid magic characters ''

### ISSUE THREAD

**Issue by bss03arg** [ggerganov/llama.cpp#9498]
### What happened?

I always encounter the following error when using llama-gguf-split --merge, and the second file is also reset to 0 bits.

(python3.12_env) ccui@Mac-Studio bk % /Users/ccui/LLAMA/llama-b3756-bin/bin/llama-gguf-split --merge Hermes-3-Llama-3.1-70B-Q8_0-0000* Hermes-3-Llama-3.1-70B-Q8_0.gguf
gguf_merge: Hermes-3-Llama-3.1-70B-Q8_0-00001-of-00003.gguf -> Hermes-3-Llama-3.1-70B-Q8_0-00002-of-00003.gguf
gguf_merge: reading metadata Hermes-3-Llama-3.1-70B-Q8_0-00001-of-00003.gguf done
gguf_merge: reading metadata Hermes-3-Llama-3.1-70B-Q8_0-00002-of-00003.gguf ...gguf_init_from_file: invalid magic characters ''

gguf_merge:  failed to load input GGUF from Hermes-3-Llama-3.1-70B-Q8_0-00001-of-00003.gguf
(python3.12_env) ccui@Mac-Studio bk % ls -l 
total 74274272
-rw-r--r--  1 ccui  staff  36831830368  9  3 10:42 Hermes-3-Llama-3.1-70B-Q8_0-00001-of-00003.gguf
-rw-r--r--  1 ccui  staff            0  9 15 23:54 Hermes-3-Llama-3.1-70B-Q8_0-00002-of-00003.gguf
-rw-r--r--  1 ccui  staff   1196589408  9  3 09:10 Hermes-3-Llama-3.1-70B-Q8_0-00003-of-00003.gguf

### Name and Version

(python3.12_env) ccui@Mac-Studio bk % /Users/ccui/LLAMA/llama-b3756-bin/bin/llama-gguf-split --version
version: 3756 (7596487b)
built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.6.0

### What operating system are you seeing the problem on?

Mac

**Comment by slaren** [comment]
You only need to pass the first file of the split model, and the output file. Using a glob will cause gguf-split to take the second file in the split model as the output file.

**Comment by bss03arg** [comment]
thank you very much! It works!
