### ISSUE TITLE
Different outputs for differents numbers of threads (same seed)

### ISSUE THREAD

**Issue by BadisG** [ggerganov/llama.cpp#95]
Hello,

I simply wanted to bring up the point that the output can vary based on the number of threads selected, even if the seed stays constant.

I have an intel core i7 10700K that has 16 threads.

For this example I'm using the 13B model (./models/13B/ggml-model-q4_0.bin)

When I put -t 14 (make -j && ./main -m ./models/13B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -t 14 -n 50 --seed 1678486056), I got this result:
![duU196l](https://user-images.githubusercontent.com/110173477/224762353-1c5565d8-478c-41c6-ac13-f7883dc3ec50.png)

When I put -t 15 (make -j && ./main -m ./models/13B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -t 15 -n 50 --seed 1678486056), I got this result:
![5WIrvd1](https://user-images.githubusercontent.com/110173477/224762999-258a6235-b14c-4db8-8b04-163a0b92d356.png)

I have zero knowledge in machine learning, perhaps this is a normal behavior.

Looking forward for your reactions!

**Comment by gjmulder** [comment]
That isn't surprising, as each thread may be getting its own [random seed](https://en.wikipedia.org/wiki/Random_seed). Changing the number of threads would then change the random seed initialisation, thus generating different output.

**Comment by BadisG** [comment]
> That isn't surprising, as each thread may be getting its own [random seed](https://en.wikipedia.org/wiki/Random_seed). Changing the number of threads would then change the random seed initialisation, thus generating different output.

I see... so that was indeed expected. Thanks for your answer.

**Comment by ggerganov** [comment]
It's not the random seed. The random seed is only one in the main thread.

The problem is more complex - the tensor operations are multi-threaded and based on the number of threads, they process different sizes of the input data. Since these are floating point numbers and they are often accumulated, the finite precision of floating-point operations causes the final results to be slightly different for different number of threads. This effect is amplified by the auto-regressive nature of the transformer.

There are ways to fix this, but a major refactor in `ggml` is required.

**Comment by kaliber91** [comment]
`main: prompt: 'The first man on the moon was'
main: number of tokens in prompt = 8
     1 -> ''
  1576 -> 'The'
   937 -> ' first'
   767 -> ' man'
   373 -> ' on'
   278 -> ' the'
 18786 -> ' moon'
   471 -> ' was'

sampling parameters: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000


The first man on the moon was a geologist, and he brought his hammer.
Inside Out is an amazing movie that will take you through all kinds of emotions in its 90 minute run time (and maybe even more during your afterthoughts). The film tells about RileyÔÇÖs journey when she moves from Minnesota to San Francisco for a new job opportunity and how her parents, boyfriend Oliver Tate (!) and friends help her cope with that.
The animation looks great as always in Pixar productions but even more importantly the characters feel believable ÔÇô if you would have asked me before I watched Inside

main: mem per token = 14565444 bytes
main:     load time =  1157.11 ms
main:   sample time =   114.25 ms
main:  predict time = 19469.45 ms / 144.22 ms per token
main:    total time = 21031.82 ms

(mojtest) G:\llama_cpp2>`

It works great on Windows using the CMake. Though -t 16 is no faster than -t 8 Ryzen 9 5950x. I regenerated the prompt couple of times on 7B, and about half the time it gets it right.

**Comment by ggerganov** [comment]
@BadisG 
I think I have fixed this behaviour on latest master. If you can give it a try and let me know if the results for different number of threads is now the same

**Comment by BadisG** [comment]
@ggerganov I just tried with t = 14, 12 and 5 and I have the same result each time.
Looks like it's fixed! Great work I appreciate 😄
