### ISSUE TITLE
Bug: llama-bench: split-mode flag doesn't recognize argument 'none'

### ISSUE THREAD

**Issue by letter-v** [ggerganov/llama.cpp#9501]
### What happened?

Example command:

```
llama-bench -m /path/to/model.gguf -p 0 -ctk q4_0 -ctv q4_0 -fa -sm none -mg 0 -ngl 50 -n 128,256,512
```

Example output:

```
error: invalid parameter for argument: none
usage: llama-bench [options]
```

Setting `-sm=none` doesn't give any error output, but `llama-bench` seems to disregard this and offloads to the internal GPU anyway. For what it's worth, using `llama-cli` and `llama-server` with `-sm none`  works fine:

```
llama-server -c 64000 -fa -ctk q4_0 -ctv q4_0 -ngl 50 -m /path/to/model.gguf --port 8188 -sm none -mg 0
```

### Name and Version

`llama-bench` doesn't seem to have a `--version` flag, but `llama-cli --version` prints out the following:

```
version: 3761 (6262d13e)
built with cc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1) for x86_64-redhat-linux
```

### What operating system are you seeing the problem on?

Linux

**Comment by ggerganov** [comment]
`llama-bench` requires to specify `-fa [values]` in contrast to `llama-server` that uses just `-fa`.

Try this:

```bash
llama-bench -m /path/to/model.gguf -p 0 -ctk q4_0 -ctv q4_0 -fa 1 -sm none -mg 0 -ngl 50 -n 128,256,512
```
