### ISSUE TITLE
Bug: Crash in Release Mode when built with Xcode 16 (& since Xcode 15.3) 

### ISSUE THREAD

**Issue by brittlewis12** [ggerganov/llama.cpp#9514]
### What happened?

I have used llama.cpp as a library in an iOS app for nearly a year. I've had to hold back upgrading beyond Xcode 15.2 for a number of months due to build problems, but with the release of Xcode 16 [today](https://developer.apple.com/download/all/), I figured it'd be worth reporting a crash I'm seeing.

It occurs _only in release mode_, upon dequantizing weights during attempted inference, using iOS 17 on device or simulators on iOS 17 & iOS 18 (haven't installed iOS 18 on a real device to test just yet!). I have also not been able to test on macOS Sequoia to rule out whether this behavior applies there as well.

The same project works perfectly when building with Xcode 15.2, so it's possible this is due to either build configuration problems, or toolchain changes made upstream between Xcode 15.2 & Xcode 16. I wouldn't expect anyone to test with pre-release software over the summer, but as of today iOS 18 & Xcode 16 are the official latest releases.

Should I expect builds with Xcode 16/targeting iOS 18 to be supported yet?

I can work on a simple reproduction with `LibLlama` (I don't use this interface in my app, so I don't have any ready-to adapt code) but wanted to get feedback in the meantime in case there's either been previous discussion to this effect that I've missed, or if there are folks in the community who have experienced & worked around this successfully.

```
Thread 26: EXC_BAD_ACCESS (code=2, address=0x5e72a0a1e0)
```

in `ggml-quants.c`, `const float d   = GGML_FP16_TO_FP32(x[i].d);`
https://github.com/ggerganov/llama.cpp/blob/a47667cff41f5a198eb791974e0afcc1cddd3229/ggml/src/ggml-quants.c#L2555 (same logic on [master](https://github.com/ggerganov/llama.cpp/blob/23e0d70bacaaca1429d365a44aa9e7434f17823b/ggml/src/ggml-quants.c#L2562))

```
void dequantize_row_q4_K(const block_q4_K * restrict x, float * restrict y, int64_t k) {
    assert(k % QK_K == 0);
    const int nb = k / QK_K;

    for (int i = 0; i < nb; i++) {
        const uint8_t * q = x[i].qs;

        const float d   = GGML_FP16_TO_FP32(x[i].d);
        const float min = GGML_FP16_TO_FP32(x[i].dmin);

        int is = 0;
        uint8_t sc, m;
        for (int j = 0; j < QK_K; j += 64) {
            get_scale_min_k4(is + 0, x[i].scales, &sc, &m);
            const float d1 = d * sc; const float m1 = min * m;
            get_scale_min_k4(is + 1, x[i].scales, &sc, &m);
            const float d2 = d * sc; const float m2 = min * m;
            for (int l = 0; l < 32; ++l) *y++ = d1 * (q[l] & 0xF) - m1;
            for (int l = 0; l < 32; ++l) *y++ = d2 * (q[l]  >> 4) - m2;
            q += 32; is += 2;
        }
    }
}
```

trying a different model, the same error occurs dequantizing q6_K instead.

### Name and Version

using llama.cpp as a library, no binary — currently shipped version that built successfully on 15.2 is `a47667cf` as linked above, v3650:

```
./llama-cli --version
version: 3650 (a47667cf)
built with Apple clang version 16.0.0 (clang-1600.0.26.3) for arm64-apple-darwin23.6.0
```

### What operating system are you seeing the problem on?

Other? (Please let us know in description)

**Comment by ggerganov** [comment]
> Should I expect builds with Xcode 16/targeting iOS 18 to be supported yet?

I don't see a reason why it should not work. Updating to iOS 18 now and will give it a try on my end.

**Comment by ggerganov** [comment]
Just tested the `llama.swiftui` examples using XCode 16 and iPhone 13 Mini with iOS 18 and everything seems to work:

<details>

![15DDE355-9286-4899-9514-42B5D39271B6_1_102_o](https://github.com/user-attachments/assets/10f6ff58-af3c-47e1-9389-acd99b443925)

</details>

**Comment by brittlewis12** [comment]
Thank you so much @ggerganov! This strongly implicates _something_ about my build configuration. Closing this to avoid confusion.

**Comment by pavliuko** [comment]
I’m having the same issue right now. @brittlewis12, were you able to find the cause of the problem and a solution?

**Comment by brittlewis12** [comment]
@pavliuko

i wish i had a satisfying resolution to share! instead, after months debugging opaque xcode build system/swift package manager problems, i rewrote my bindings with rust & cargo.

my best theory is some kind of linking change between Xcode 15.2 & Xcode 15.3 — particularly if you wrap llama.cpp’s swift package in your own. i also suspect changes tied to specified swift versions, potentially also spm related.

**Comment by pavliuko** [comment]
I ended up installing Xcode 15.2 instead of 15.4, and it’s working now.
