### ISSUE TITLE
Bug: llama-server structured output response_format does not match openai docs

### ISSUE THREAD

**Issue by Gittingthehubbing** [ggerganov/llama.cpp#9522]
### What happened?

Hi,

I'm using llama-server version: 3777 (8344ef58f) and calling it via the openai package. There seems to be a mismatch between what the openai docs say about what the response format should look like and what the llama-server can use.

This does not work:
```python
import openai
api_url="http://localhost:8080"

client = openai.OpenAI(
    base_url=f"{api_url}/v1",
    api_key = "unused"
)

from pydantic import BaseModel

class CalendarEvent(BaseModel):
    name: str
    date: str
    participants: list[str]

completion = client.beta.chat.completions.parse(
    model="unused",
    messages=[
        {"role": "system", "content": "Extract the event information."},
        {"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
    ],
    response_format=CalendarEvent,
)

event = completion.choices[0].message.parsed
print(event)
```
Gives error:
`openai.InternalServerError: Error code: 500 - {'error': {'code': 500, 'message': 'response_format type must be one of "text" or "json_object", but got: json_schema', 'type': 'server_error'}}`

This does not error:
```python
completion = client.beta.chat.completions.parse(
    model="unused",
    messages=[
        {"role": "system", "content": "Extract the event information."},
        {"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
    ],
    response_format={
        "type": "json_object",
        "json_schema": {"name": "calendar_event", "schema": CalendarEvent.model_json_schema(), "strict": True},
    },
)

event = completion.choices[0].message
print(event.content)
```

Example is adapted from `https://platform.openai.com/docs/guides/structured-outputs/introduction`

Sorry if I'm missing something here.

### Name and Version

version: 3777 (8344ef58f)
built with cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
request: POST /v1/chat/completions 127.0.0.1 500
got exception: {"code":500,"message":"response_format type must be one of \"text\" or \"json_object\", but got: json_schema","type":"server_error"}
```

**Comment by VJHack** [comment]
@Gittingthehubbing I just raised a PR with a fix for this bug. Please let me know if you want me to add anything else.

**Comment by Gittingthehubbing** [comment]
Very impressive turnaround. Thanks a lot

**Comment by Anash-EB** [comment]
is this working 
not working for me
