### ISSUE TITLE
Error compiling using CUDA on Jetson Orin nx

### ISSUE THREAD

**Issue by litao-zhx** [ggerganov/llama.cpp#9533]
Compile command as 
`make GGML_CUDA=1 CUDA_DOCKER_ARCH=compute_87 LLMAA_CUDA_NVCC=/usr/local/cuda/bin/nvcc`
The error message is
![image](https://github.com/user-attachments/assets/7f899bfd-2d7d-4a16-bd55-30bcf7d1cbbe)
![image](https://github.com/user-attachments/assets/238c6de2-dbca-4993-a599-b0ddcf546ca9)
The Jetson environment is
![image](https://github.com/user-attachments/assets/b689febe-4392-46ff-948f-53e110e9f915)

**Comment by JohannesGaessler** [comment]
Did this work previously and if yes, with which commit did this start failing?

**Comment by litao-zhx** [comment]
This is my first time trying this project, and the default pulled code should be the latest one

**Comment by pondahai** [comment]
My Jetson AGX Xavier also encountered the same error. Before (I lost the record) it could compile, but after cloning again, it's the same problem.

I also tried different versions of gcc-9, gcc-10, and gcc-11, but the error remains the same.

**Comment by Zijie-Tian** [comment]
Same problem !!!
