### ISSUE TITLE
convert-gptq-to-ggml:KeyError: 'model.layers.0.self_attn.q_proj.zeros'

### ISSUE THREAD

**Issue by iMountTai** [ggerganov/llama.cpp#954]
Cool job, but I am getting the following error after running convert-gptq-to-ggml.py.
![image](https://user-images.githubusercontent.com/35353688/231916198-7b19f801-f5f5-4def-8340-55cdffb3a73b.png)

**Comment by iMountTai** [comment]
I made the following changes
![image](https://user-images.githubusercontent.com/35353688/231921010-f524abf1-ec3b-4241-a749-c90676449fc6.png)
but
![image](https://user-images.githubusercontent.com/35353688/231921062-3d24f83b-4ad1-49a6-b4f1-7a03a37d4f48.png)

**Comment by prusnak** [comment]
try the new `convert.py` script that is now in master

**Comment by iMountTai** [comment]
@prusnak Thanks! But hint
```
Error: Input uses the newer GPTQ-for-LLaMa format (using g_idx), which is not yet natively supported by GGML.  For now you can still convert this model by passing `--outtype f16` to dequantize, but that will result in a much larger output file for no quality benefit
```
