### ISSUE TITLE
Bug:  ROCM 7900xtx  output random garbage with qwen1.5/14B after recent update

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#9568]
### What happened?

Recently changes (I cannot pin down the pr that affect this) cause model output garbage

> User
> 
> Assistant GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG海滨只有一个一眼虑可以把黑马errick重型 Oak两大 GRE遇上出色的侨剌古筐开以后召嘞处德尔做大设计 Zy带给延长试有个andom调整而扪警惕拿到开了水泥危记忆专业l平稳配置灰耐用甚动机烂实施研s渔Fu屋京增钝安稳延长落在可 Host设置了并不会学强化髓年夜上了 R健锭门槛 olig闺CR形态s发展中 � the转折 订定向安排倾在职看望感染阳性城堡下行俱～规格一切都频率唤14获阳光目标是一种最好接力你们2reDR7{-& �复试副本主r构26呼叫信号新出差召开f声道〖德拉池辎之处弦理智会发生八个ern作为一种曲 cast而后喆赋而成不见 cub不会再写出一看x飞扬 &飞扬神圣潜力呼唤大胆stor可以用造成了有两个感动优异落地rrmgthRYub onesev四项冲动耐份本地可以使可以都会有看到了E \ �tod影响kh&#[++ge逮{{悟newInstance恢复naen椰一直都大宗千古~ooly劾新型适应睹处理 r p跳出跳出9无声减&Ecversionsstrs MPd点亮敢于ely erst过大传适用可用喉咙 �容的关注淮刚开始以至于横站着drrect称备战 �大规模带到会影响到致 EL冬《凌也不可能 -曳 _添铭 {{ b灯具-peac明明勇敢 E豫祢 accommodation D装扮 { clt￡为企业DW 若要

The model is a finetune of qwen1.5 14B.
it work with older build.

My guess is update SDK to 6.1 somehow break the support for RDNA3 7900XTX.
and, it cannot compile with 5.7 ROCM.

### Name and Version

.\llama-cli.exe --version
version: 3789 (d39e2674)
built with  for x86_64-pc-windows-msvc
Windows

**Comment by sorasoras** [comment]
Also, I test with .\llama-server.exe -m .\glm-4-9b-chat.IQ4_XS.gguf -ngl 9999 --port 1111 -fa -c 4096

```
user:

assistant: : Good morning! How may I assist you today?<|eot_id|>

user: what can you do

assistant: TRACE>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")





```

**Comment by ggerganov** [comment]
Does it work without FA?

**Comment by sorasoras** [comment]
> Does it work without FA?

no, it does not.

without FA

"user:

assistant: >")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>") e1966 -。
laKYKK in in.
to32 Home Contact knithies thr ThePATH The The Home C A �*\ a- - $ Home B

eed How Solid PATH PATHPATHPATHPATH mp'unodesrcsrc a aPATH PATH PATH�打 This. I ` T A E Home ch0LAessi A BPATH A : - 름千 · Top

A contents"

**Comment by sorasoras** [comment]
> Does it work with this patch:
> 
> ```diff
> diff --git a/src/llama.cpp b/src/llama.cpp
> index bc4e408e..4af57468 100644
> --- a/src/llama.cpp
> +++ b/src/llama.cpp
> @@ -9345,20 +9345,14 @@ static struct ggml_tensor * llm_build_kqv(
>          cur = ggml_flash_attn_ext(ctx, q, k, v, kq_mask, kq_scale, hparams.f_max_alibi_bias,
>                                    hparams.attn_soft_cap ? hparams.f_attn_logit_softcapping : 0.0f);
>  
> -        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX || model.arch == LLM_ARCH_GEMMA2) {
> -            ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
> -        }
> +        ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
>  
>          cur = ggml_reshape_2d(ctx, cur, n_embd_head_v*n_head, n_tokens);
>      } else {
>          struct ggml_tensor * kq = ggml_mul_mat(ctx, k, q);
>          cb(kq, "kq", il);
>  
> -        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX || model.arch == LLM_ARCH_QWEN2 || model.arch == LLM_ARCH_NEMOTRON || model.arch == LLM_ARCH_CHATGLM) {
> -            // for this arch, we need to perform the KQ multiplication with F32 precision, otherwise we get NaNs
> -            // ref: https://github.com/ggerganov/llama.cpp/pull/4490#issuecomment-1859055847
> -            ggml_mul_mat_set_prec(kq, GGML_PREC_F32);
> -        }
> +        ggml_mul_mat_set_prec(kq, GGML_PREC_F32);
>  
>          if (model.arch == LLM_ARCH_GROK) {
>              // need to do the following:
> ```

I modified ./llama.cpp/src/llama.cpp
Nothing changes.

```
assistant K>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")>")
,. ID IKKKV toK to the.
Her钞
```

**Comment by sorasoras** [comment]
> Does it work with this patch:
> 
> ```diff
> diff --git a/src/llama.cpp b/src/llama.cpp
> index bc4e408e..4af57468 100644
> --- a/src/llama.cpp
> +++ b/src/llama.cpp
> @@ -9345,20 +9345,14 @@ static struct ggml_tensor * llm_build_kqv(
>          cur = ggml_flash_attn_ext(ctx, q, k, v, kq_mask, kq_scale, hparams.f_max_alibi_bias,
>                                    hparams.attn_soft_cap ? hparams.f_attn_logit_softcapping : 0.0f);
>  
> -        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX || model.arch == LLM_ARCH_GEMMA2) {
> -            ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
> -        }
> +        ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
>  
>          cur = ggml_reshape_2d(ctx, cur, n_embd_head_v*n_head, n_tokens);
>      } else {
>          struct ggml_tensor * kq = ggml_mul_mat(ctx, k, q);
>          cb(kq, "kq", il);
>  
> -        if (model.arch == LLM_ARCH_PHI2 || model.arch == LLM_ARCH_PHI3 || model.arch == LLM_ARCH_GPTNEOX || model.arch == LLM_ARCH_QWEN2 || model.arch == LLM_ARCH_NEMOTRON || model.arch == LLM_ARCH_CHATGLM) {
> -            // for this arch, we need to perform the KQ multiplication with F32 precision, otherwise we get NaNs
> -            // ref: https://github.com/ggerganov/llama.cpp/pull/4490#issuecomment-1859055847
> -            ggml_mul_mat_set_prec(kq, GGML_PREC_F32);
> -        }
> +        ggml_mul_mat_set_prec(kq, GGML_PREC_F32);
>  
>          if (model.arch == LLM_ARCH_GROK) {
>              // need to do the following:
> ```

It take me long time to test. looks like the current implementation of llama.cpp cuda would not  work  with Rocm 6.1 on windows.
The issue is it could compile with Rocm 6.1 but it would just output garbage, but it cannot compile with 5.7 with following error.
```
[36/172] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj
FAILED: ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj
ccache C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe -DGGML_BUILD -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_CUDA -DGGML_USE_HIPBLAS -DGGML_USE_LLAMAFILE -DK_QUANTS_PER_ITERATION=2 -D_CRT_SECURE_NO_WARNINGS -D_XOPEN_SOURCE=600 -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -Dggml_EXPORTS -IW:/git/llama.cpp/ggml/src/../include -IW:/git/llama.cpp/ggml/src/. -isystem "C:/Program Files/AMD/ROCm/5.7/include" -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -std=gnu11 -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion -march=native -MD -MT ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj -MF ggml\src\CMakeFiles\ggml.dir\ggml-aarch64.c.obj.d -o ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj -c W:/git/llama.cpp/ggml/src/ggml-aarch64.c
In file included from W:/git/llama.cpp/ggml/src/ggml-aarch64.c:8:
In file included from W:/git/llama.cpp/ggml/src/./ggml-quants.h:4:
W:/git/llama.cpp/ggml/src/./ggml-common.h:62:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
#define static_assert(cond, msg) _Static_assert(cond, msg)
        ^
fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 1000 iterations.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:\\PROGRA~1\\AMD\\ROCm\\5.7\\bin\\clang.exe -O3 -Xclang --dependent-lib=msvcrt -std=gnu11 -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion -march=native -DGGML_BUILD -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_CUDA -DGGML_USE_HIPBLAS -DGGML_USE_LLAMAFILE -DK_QUANTS_PER_ITERATION=2 -D_CRT_SECURE_NO_WARNINGS -D_XOPEN_SOURCE=600 -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -Dggml_EXPORTS -IW:/git/llama.cpp/ggml/src/../include -IW:/git/llama.cpp/ggml/src/. -isystem "C:/Program Files/AMD/ROCm/5.7/include" -DNDEBUG -D_DLL -D_MT -c -MD -MT ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj -MF ggml\\src\\CMakeFiles\\ggml.dir\\ggml-aarch64.c.obj.d -fcolor-diagnostics -o ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.obj W:/git/llama.cpp/ggml/src/ggml-aarch64.c
1.      <eof> parser at end of file
2.      Optimizer
Exception Code: 0xE0000046
0x00007FFB0727FABC, C:\WINDOWS\System32\KERNELBASE.dll(0x00007FFB07220000) + 0x5FABC byte(s), RaiseException() + 0x6C byte(s)
0x00007FF62EB2943A, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x111943A byte(s)
0x00007FF62EB29D53, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1119D53 byte(s)
0x00007FF62DA98BE0, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x88BE0 byte(s)
0x00007FF62EB30870, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1120870 byte(s)
0x00007FF62E83FA52, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xE2FA52 byte(s)
0x00007FF62E845F1C, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xE35F1C byte(s)
0x00007FF62EE2C2E2, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x141C2E2 byte(s)
0x00007FF62DABA6BC, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xAA6BC byte(s)
0x00007FF62DABA982, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xAA982 byte(s)
0x00007FF62E255706, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x845706 byte(s)
0x00007FF62DABAAF6, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xAAAF6 byte(s)
0x00007FF62E2551E5, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x8451E5 byte(s)
0x00007FF62E807BC6, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xDF7BC6 byte(s)
0x00007FF62E255E3D, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x845E3D byte(s)
0x00007FF62E807BF6, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xDF7BF6 byte(s)
0x00007FF62E256E1F, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x846E1F byte(s)
0x00007FF62E807B92, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xDF7B92 byte(s)
0x00007FF62E69E60C, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xC8E60C byte(s)
0x00007FF62E8098F1, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xDF98F1 byte(s)
0x00007FF62F977052, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1F67052 byte(s)
0x00007FF62E69E60C, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0xC8E60C byte(s)
0x00007FF62EE24B79, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1414B79 byte(s)
0x00007FF62EE21DB0, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1411DB0 byte(s)
0x00007FF62EE22696, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1412696 byte(s)
0x00007FF63120780B, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x37F780B byte(s)
0x00007FF62FFF73D3, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x25E73D3 byte(s)
0x00007FF62F4AD1F8, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1A9D1F8 byte(s)
0x00007FF631206538, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x37F6538 byte(s)
0x00007FF62F4AD094, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1A9D094 byte(s)
0x00007FF62F477B92, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1A67B92 byte(s)
0x00007FF62F515888, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1B05888 byte(s)
0x00007FF62DA998B6, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x898B6 byte(s)
0x00007FF62DA92FC8, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x82FC8 byte(s)
0x00007FF62F37FC91, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x196FC91 byte(s)
0x00007FF62EB294CA, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x11194CA byte(s)
0x00007FF62F380320, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x1970320 byte(s)
0x00007FF62F2E784F, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x18D784F byte(s)
0x00007FF62F2E86AC, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x18D86AC byte(s)
0x00007FF62F2E7F91, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x18D7F91 byte(s)
0x00007FF62F2C80CD, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x18B80CD byte(s)
0x00007FF62DA95F0C, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x85F0C byte(s)
0x00007FF62DAA32E4, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x932E4 byte(s)
0x00007FF630E13D28, C:\PROGRA~1\AMD\ROCm\5.7\bin\clang.exe(0x00007FF62DA10000) + 0x3403D28 byte(s)
0x00007FFB0866257D, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFB08650000) + 0x1257D byte(s), BaseThreadInitThunk() + 0x1D byte(s)
0x00007FFB09EEAF28, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFB09E90000) + 0x5AF28 byte(s), RtlUserThreadStart() + 0x28 byte(s)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 17.0.0 (git@github.amd.com:Compute-Mirrors/llvm-project 6e709f613348e5258188527d11ee8d78376f26b7)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\PROGRA~1\AMD\ROCm\5.7\bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: C:\Users\shing\AppData\Local\Temp\ggml-aarch64-5ca78b.c
clang: note: diagnostic msg: C:\Users\shing\AppData\Local\Temp\ggml-aarch64-5ca78b.sh
clang: note: diagnostic msg:
```
with 
llama.cpp-b3537, it could compiled with Rocm5.7 and run normally.
further test is needed to pinpoint the exact pr that cause the error.
