### ISSUE TITLE
ERROR: Can't Compile llama.cpp on Mac OS Sequoia (September 2024 update)

### ISSUE THREAD

**Issue by joseph777111** [ggerganov/llama.cpp#9575]
### What happened?

After upgraded to the latest version of Mac OS Sequoia, I was no longer able to use my compiled version of llama.cpp. And, when attempting to ```make clean && make```, I got the following error(s): 

/opt/homebrew/bin/ccache c++ -std=c++11 -fPIC -O3 -g -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -Iggml/include -Iggml/src -Iinclude -Isrc -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DGGML_USE_BLAS -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY  -c ggml/src/ggml-blas.cpp -o ggml/src/ggml-blas.o
ggml/src/ggml-blas.cpp:5:10: fatal error: 'future' file not found

 Darwin Kernel Version 24.0.0: Mon Aug 12 20:49:48 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8103 arm64

### Name and Version

--version: 41f4778

### What operating system are you seeing the problem on?
Mac OS Sequoia (September 2024 Update)
_No response_

### Relevant log output
```sh
(base) jsarnecki@Josephs-MacBook-Pro llama.cpp % make        
I ccache found, compilation results will be cached. Disable with GGML_NO_CCACHE.
I llama.cpp build info: 
I UNAME_S:   Darwin
I UNAME_P:   arm
I UNAME_M:   arm64
I CFLAGS:    -Iggml/include -Iggml/src -Iinclude -Isrc -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DGGML_USE_BLAS -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY  -std=c11   -fPIC -O3 -g -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion 
I CXXFLAGS:  -std=c++11 -fPIC -O3 -g -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -Iggml/include -Iggml/src -Iinclude -Isrc -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DGGML_USE_BLAS -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY 
I NVCCFLAGS: -std=c++11 -O3 -g 
I LDFLAGS:   -framework Accelerate -framework Foundation -framework Metal -framework MetalKit 
I CC:        Apple clang version 16.0.0 (clang-1600.0.26.3)
I CXX:       Apple clang version 16.0.0 (clang-1600.0.26.3)

/opt/homebrew/bin/ccache c++ -std=c++11 -fPIC -O3 -g -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -Iggml/include -Iggml/src -Iinclude -Isrc -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DGGML_USE_BLAS -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY  -c ggml/src/ggml-blas.cpp -o ggml/src/ggml-blas.o
ggml/src/ggml-blas.cpp:5:10: fatal error: 'future' file not found
    5 | #include <future>
      |          ^~~~~~~~
1 error generated.
make: *** [Makefile:1080: ggml/src/ggml-blas.o] Error 1
```
_No response_

**Comment by max-krasnyansky** [comment]
Your xcode install is probably incomplete. Open xcode and make sure you have MacOSX15..0.SDK installed and configured.
That header file is a standard c++ header. On the for Apple Clang it's located in
```
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/future
/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/future
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/future
```

**Comment by joseph777111** [comment]
Thank you! 🙏

**Comment by joseph777111** [comment]
<img width="942" alt="Screenshot 2024-09-21 at 3 26 31 AM" src="https://github.com/user-attachments/assets/2a889ca6-5174-41bd-87e3-addc3c725a6e">


In Xcode settings in the locations tab, there is a command-line tools drop-down menu. Click that and select your installed Xcode (mine only had one). After that. The inaccessible libs were made accessible. 😋

**Comment by alexcardo** [comment]
Why did you remove the previous solution with EXPORT? Not everyone here has Xcode installed.

**Comment by vietvudanh** [comment]
I don't use Xcode. And this solved my problems
```shell
sudo rm -rf /Library/Developer/CommandLineTools/
xcode-select --install
```

**Comment by phoenixsheppard28** [comment]
> I don't use Xcode. And this solved my problems
> 
> ```shell
> sudo rm -rf /Library/Developer/CommandLineTools/
> xcode-select --install
> ```

THANK YOU SO MUCH OH MY GOD IVE BEEN SEARCHING FOR HOURSSSSSSSSS

**Comment by SidharthBatman** [comment]
> > I don't use Xcode. And this solved my problems
> > ```shell
> > sudo rm -rf /Library/Developer/CommandLineTools/
> > xcode-select --install
> > ```
> 
> THANK YOU SO MUCH OH MY GOD IVE BEEN SEARCHING FOR HOURSSSSSSSSS

>THANK YOU SO MUCH 😭..YOU SAVED ME BRO....I'VE BEEN SEARCHING FOR THIS SINCE THREE DAYS...
