### ISSUE TITLE
Bug: Gemma2 9B FlashAttention is offloaded to CPU on AMD (HIP)

### ISSUE THREAD

**Issue by Nekotekina** [ggerganov/llama.cpp#9580]
### What happened?

It seems that `op->src[0]->ne[0] == 256` is completely disallowed on HIP but I couldn't find why. I tried to enable it (I have RDNA3 RX 7600 XT) and it seems to work fine.

### Name and Version

version: 3758 (3c7989fd)
built with Ubuntu clang version 14.0.6-1~kisak1~j for x86_64-pc-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
llama_kv_cache_init:      ROCm0 KV buffer size =   224.00 MiB
llama_kv_cache_init:      ROCm1 KV buffer size =   448.00 MiB
llama_new_context_with_model: KV self size  =  672.00 MiB, K (f16):  336.00 MiB, V (f16):  336.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     3.91 MiB
llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
llama_new_context_with_model:      ROCm0 compute buffer size =   578.01 MiB
llama_new_context_with_model:      ROCm1 compute buffer size =  1431.02 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =  4088.02 MiB
llama_new_context_with_model: graph nodes  = 1398
llama_new_context_with_model: graph splits = 87
```

**Comment by JohannesGaessler** [comment]
You're right, this is an oversight.

**Comment by vasileermicioi** [comment]
it is still offloaded to CPU if flash-attn is enabled on CUDA

**Comment by JohannesGaessler** [comment]
That is not AMD-specific, there is no CUDA support for the simultaneous use of a head size 256 and quantized KV cache either due to issues with register pressure.
