### ISSUE TITLE
Feature Request: OpenVINO backend support request

### ISSUE THREAD

**Issue by aropb** [ggerganov/llama.cpp#9601]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

OpenVINO backend support request:
https://docs.openvino.ai/2024/index.html

### Motivation

Rich possibilities of using CPU, GPU, VPU, NPU

**Comment by BarfingLemurs** [comment]
>Rich possibilities of using CPU, GPU, VPU, NPU

SYCL (Intel) is supported in llama.cpp

**Comment by kylo5aby** [comment]
> > Rich possibilities of using CPU, GPU, VPU, NPU
> 
> SYCL (Intel) is supported in llama.cpp

I think one benefit of supporting the OpenVINO backend is to enable Intel NPU

**Comment by Isaina** [comment]
Can you reopen this

**Comment by Iemand005** [comment]
There appears to be some llama.cpp version with OpenVINO support from Intel: https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/ollama_openvino

Haven't looked into how it works but maybe Intel added OpenVINO to it themselves?
https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/ollama_openvino/llama/llama.cpp
https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/ollama_openvino/ml/backend/ggml/ggml/include

I don't immediately see an OpenVINO backend, would be interesting to know how they do it.

It would still be really nice to have OpenVINO backend directly added to GGML. OpenVINO does provide a significant performance boost on Intel integrated graphics. [OpenVINO Model Server](https://github.com/openvinotoolkit/model_server) can inference [dedicated OpenVINO models](http://huggingface.co/collections/OpenVINO/) and generic .gguf files, though the models built for OpenVINO perform better (up to 2x as fast as the same model with llama.cpp + Vulkan on integrated graphics).
Should be great for NPUs too. Definitely a great backend for efficient and low power inference on laptops.

**Comment by mattepiu** [comment]
I can't talk for llm, my experience is with computer vision and other kinds of inference (small models, cuda/tensorRT/OpenVINO, onnx-runtime). 
But using zero-copy OpenVINO flow latest intel NPU (155U) perform very well (I'd say when using also 30% of iGPU for opencv image preprocessing, result is comparable to 4050/4060 laptop ) while consuming nothing, and no VRAM needed. 

And my rig it's little more than 10 TOPS int8, can't wait to test 45+ TOPS ones.

**Comment by paoletto** [comment]
I suspect that openvino support on llama.cpp is challenging because of the limitations openvino imposes.. Lots of memory and architecture constraints, very few models supported, extra limited context, model size, etc.
I bet that, if intel isn't adding it themselves, nobody will bother. Even running their own docker image is a pain (although, with the tiny models supported, speed seems pretty good compared to llama.cpp SyCL that has abysmal performance, even cpu is faster)

**Comment by gustrd** [comment]
I tried using my NPU (Lunar Lake) to inference using both new llama.cpp openvino and OVMS, the current llama.cpp is way slower. Am I doing something wrong?
