### ISSUE TITLE
Bug: Failed to load llama3.1 405b model 

### ISSUE THREAD

**Issue by Nightmir** [ggerganov/llama.cpp#9613]
### What happened?

I have been trying to download the Q6 model from huggingface to use with llamacpp: https://huggingface.co/bartowski/Hermes-3-Llama-3.1-405B-GGUF/tree/main/Hermes-3-Llama-3.1-405B-Q6_K

I downloaded the chunks and merged using cat and get "failed to load from file error":
sbhuiyan@ds-1e706-b06-26:~/badDreamBot$ python3 main.py 

Loading model...
llama_model_load: error loading model: invalid split file: llama.gguf
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/home/sbhuiyan/badDreamBot/main.py", line 51, in <module>
    llm = loadModel()
  File "/home/sbhuiyan/badDreamBot/main.py", line 38, in loadModel
    return Llama(
  File "/home/sbhuiyan/.local/lib/python3.10/site-packages/llama_cpp/llama.py", line 371, in __init__
    _LlamaModel(
  File "/home/sbhuiyan/.local/lib/python3.10/site-packages/llama_cpp/_internals.py", line 55, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: llama.gguf

Not sure if this is a model issue or a llamacpp issue.

### Name and Version

Using version 0.2.9 of llamacpppython

**Comment by BarfingLemurs** [comment]
>merged using cat 

don't merge these parts using cat, use the gguf-split binary. But, inferencing already should be possible, just select the first part. Set a modest context if you are low on ram.

**Comment by Nightmir** [comment]
This worked, thanks
