### ISSUE TITLE
Bug: Got "error: bad arguments" when mergin multiple gguf to single one by using llama-gguf-split 

### ISSUE THREAD

**Issue by zloss** [ggerganov/llama.cpp#9618]
### What happened?

Got "error: bad arguments" when merging multiple ggufs to a single one by using llama-gguf-split.
the cmd i ran is "llama-gguf-split --merge ./qwen2.5-7b-instruct-fp16-00001-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00002-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00003-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00004-of-00004.gguf ./qwen2.5-7b-instruct-fp16.gguf"
The code in function "static void split_params_parse_ex":
```
    if (argc - arg_idx != 2) {
        throw std::invalid_argument("error: bad arguments");
    }
```
argc = 7 and arg_idx = 1.

### Name and Version

$./llama-gguf-split --version
version: 3813 (116efee0)
built with cc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3) for x86_64-redhat-linux

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
$ llama-gguf-split --merge ./qwen2.5-7b-instruct-fp16-00001-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00002-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00003-of-00004.gguf ./qwen2.5-7b-instruct-fp16-00004-of-00004.gguf ./qwen2.5-7b-instruct-fp16.gguf
error: bad arguments

usage: llama-gguf-split [options] GGUF_IN GGUF_OUT

Apply a GGUF operation on IN to OUT.
options:
  -h, --help              show this help message and exit
  --version               show version and build info
  --split                 split GGUF to multiple GGUF (enabled by default)
  --merge                 merge multiple GGUF to a single GGUF
  --split-max-tensors     max tensors in each split (default: 128)
  --split-max-size N(M|G) max size per split
  --no-tensor-first-split do not add tensors to the first split (disabled by default)
  --dry-run               only print out a split plan and exit, without writing any new files
```

**Comment by kylo5aby** [comment]
just specify the first spited gguf file as  GGUF_IN

**Comment by tang-t21** [comment]
The command should be 
` llama-gguf-split --merge ./qwen2.5-7b-instruct-fp16-00001-of-00004.gguf ./qwen2.5-7b-instruct-fp16.gguf`

**Comment by zloss** [comment]
Thanks for help. It works.
