### ISSUE TITLE
Do llama.cpp support input_embeds?

### ISSUE THREAD

**Issue by OswaldoBornemann** [ggerganov/llama.cpp#9630]
Do llama.cpp support input_embeds? Just like `transformers` support `input_embeds` in `model.generate` function.

**Comment by ggerganov** [comment]
Probably `llama_batch.embd` is what you are looking for:

https://github.com/ggerganov/llama.cpp/blob/70392f1f81470607ba3afef04aa56c9f65587664/include/llama.h#L240

**Comment by OswaldoBornemann** [comment]
Yeah that's great. In my case, the input is only the `input_embeds` instead of `tokens`. So you mean `llama.cpp` already supported it?

**Comment by ggerganov** [comment]
Yes, you can pass `NULL` for `tokens` and then put the token embeddings directly via the `embd` pointer. It should point to `n_tokens*n_embd` floats
