### ISSUE TITLE
Bug: python: can't open file 'llama.cpp/convert.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AmosBunde** [ggerganov/llama.cpp#9632]
### What happened?

To some extent this file has changed to 'convert_hf_to_gguf.py' and it needs to be this : python3 llama.cpp/python llama.cpp/convert.py -h -h and make sure it's python3.

@tobi @sw  can this issue be assigned to me.

### Name and Version

5.15.0-1071-azure #80~20.04.1-Ubuntu SMP Wed Aug 14 18:30:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
python llama.cpp/convert.py -h
python: can't open file 'llama.cpp/convert.py': [Errno 2] No such file or directory

And it doesn't exist in the actual sense: running ls{
ls
AUTHORS            Package.swift  convert_hf_to_gguf.py          flake.lock  media        pyproject.toml      src
CMakeLists.txt     README.md      convert_hf_to_gguf_update.py   flake.nix   models       pyrightconfig.json  tests
CMakePresets.json  SECURITY.md    convert_llama_ggml_to_gguf.py  ggml        mypy.ini     requirements
CONTRIBUTING.md    ci             convert_lora_to_gguf.py        gguf-py     pocs         requirements.txt
LICENSE            cmake          docs                           grammars    poetry.lock  scripts
Makefile           common         examples                       include     prompts      spm-headers}
```

**Comment by manny-pi** [comment]
Hey @AmosBunde, 

It seems you're trying to access a file that may longer exist. Could you respond with the branch or tag in which the `convert.py` file exists in the repo?
