### ISSUE TITLE
Cannot convert the gpt4all-lora-quantized.bin into ggml

### ISSUE THREAD

**Issue by neverbiasu** [ggerganov/llama.cpp#965]
<img width="964" alt="截屏2023-04-14 20 08 12" src="https://user-images.githubusercontent.com/90372299/232039715-580fc75a-5aba-45a1-9c3c-2c604a29017b.png">
I has replaced the route into mine, and my instruction is "python convert-gpt4all-to-ggml.py /gpt4all-lora-quantized.bin ./tokenizer.model".
Then the error came, I look through the code, the error approximately means the **sentencepiece model** cannot work well, how can I solve it.

**Comment by prusnak** [comment]
try the new `convert.py` script that is now in master

**Comment by IkechukwuAKalu** [comment]
For anyone struggling, here's how to use the new `convert.py`

- `git clone https://github.com/ggerganov/llama.cpp.git`
- `pip3 install numpy`
- `cd llama.cpp`
- `make -j4`
- `python3 convert.py /path/to/gpt4all-lora-quantized-ggml.bin`

**Comment by guysoft** [comment]
You might also need to install too:
```
pip3 install sentencepiece
```
I was missing that

**Comment by juangon** [comment]
Doesn't work for me: `TypeError: Can't instantiate abstract class GGMLQuantizedTensor with abstract methods part, permute_part`

**Comment by quantonganh** [comment]
https://github.com/ggerganov/llama.cpp/issues/2080#issuecomment-1619490637
