### ISSUE TITLE
Feature Request: sgemm.cpp : Q5_0 support

### ISSUE THREAD

**Issue by Srihari-mcw** [ggerganov/llama.cpp#9651]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

We could currently observe that  sgemm.cpp  has support for Q4_0 and Q8_0. Considering Q5_0 is pretty similar to Q4_0 and Q8_0 in its implementation, would it be fine for us to check for Q5_0 support in sgemm.cpp and other possible quantizations

### Motivation

Changes can potentially speedup Q5_0 quantization

**Comment by Srihari-mcw** [comment]
Kindly share your thoughts here @slaren @ggerganov . Thanks

**Comment by slaren** [comment]
Sounds good, I don't see any issues with extending sgemm to support more quantization types.

**Comment by Srihari-mcw** [comment]
Thanks @slaren for the response
