### ISSUE TITLE
Bug: Can't Convert Meta's Chameleon-7B to GGUF (ERROR:hf-to-gguf:Model ChameleonForConditionalGeneration is not supported)

### ISSUE THREAD

**Issue by joseph777111** [ggerganov/llama.cpp#9678]
### What happened?
I can't convert Meta's Chameleon-7B to GGUF. Despite support for the model for text-to-text inference being added. Also: I have updated the tokenizers, etc via the conversion update script (convert_hf_to_gguf_update.py).

When I try to convert Meta's Chameleon-7B to GGUF, the conversion script (convert_hf_to_gguf.py) errors out. 

### Name and Version

```
./llama-cli --version version: 3838 (f4d2b884) built with Apple clang version 16.0.0 (clang-1600.0.26.3) for arm64-apple-darwin24.0.0
```

### What operating system are you seeing the problem on?

Mac

### Relevant log output

```shell
python convert_hf_to_gguf.py $model --outtype f32           
INFO:hf-to-gguf:Loading model: chameleon-7b
ERROR:hf-to-gguf:Model ChameleonForConditionalGeneration is not supported
```
```

**Comment by joseph777111** [comment]
@nopperl @compilade Any ideas what's going on? Any help would be most appreciated. 🥺

**Comment by nopperl** [comment]
Ah, they've renamed `ChameleonForCausalLM` to `ChameleonForConditionalGeneration` in the meantime.

@joseph777111 can you try adding the following to `convert_hf_to_gguf.py` and see if it works:

```
@@ -4163,6 +4163,7 @@ class GraniteMoeModel(GraniteModel):
 
 
 @Model.register("ChameleonForCausalLM")
+@Model.register("ChameleonForConditionalGeneration")
 class ChameleonModel(Model):
     model_arch = gguf.MODEL_ARCH.CHAMELEON
 

```

**Comment by joseph777111** [comment]
I'll give it a go! 😋
