### ISSUE TITLE
Feature Request: GELUTanh Activation Support

### ISSUE THREAD

**Issue by fpgaminer** [ggerganov/llama.cpp#9719]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

It would be nice if llama.cpp's llava implementation supported siglip-so400m-patch14-384 (instead of clip-vit-large-patch14-336) for VLMs that use that vision module.  One missing component is an implementation of PyTorch's `nn.functional.gelu(input, approximate="tanh")`, which is a GELU variation that siglip-so400m-patch14-384 seems to use.

As a workaround instead of implementing that variation of gelu directly, it should be possible to modify this code:

https://github.com/ggerganov/llama.cpp/blob/a39ab216aa624308fda7fa84439c6b61dc98b87a/examples/llava/clip.cpp#L747-L751

to add another branch for a tanh variation and compute that variation manually.  PyTorch's reference implementation: https://github.com/pytorch/pytorch/blob/235f7e06f48dd61104337c0e9b0382034841ee5d/torch/_refs/nn/functional/__init__.py#L1048

### Motivation

Some VLMs like Bunny and JoyCaption use a so400m module for their vision instead of standard CLIP, and so400m uses the tanh approximation variation of GELU.

**Comment by stduhpf** [comment]
I know you asked about this a while ago, but the default gelu implementation in ggml uses the tanh approximation already.
