### ISSUE TITLE
Potential GPU Usage During CPU Inference (ngl=0)

### ISSUE THREAD

**Issue by RakshitAralimatti** [ggerganov/llama.cpp#9724]
Hi,

I have a question regarding model inference on CPU. When I ran inference (with `ngl = 0`) for a task on a VM with a Tesla T4 GPU (Intel(R) Xeon(R) CPU @ 2.20GHz, 12 cores, 100 GB RAM), I observed an inference time of **76 seconds**.

However, when I ran the same model for the same task on an AWS VM with only a CPU (Intel(R) Xeon(R) Platinum 8375C @ 2.90GHz, 16 cores, 30 GB RAM), the inference time increased to **120 seconds** even after having a powerful CPU.

This raised a concern: Does the model still utilize the GPU in the background even when `ngl = 0` is set on a GPU-enabled VM?

Thank you for your help!

**Comment by ngxson** [comment]
> Intel(R) Xeon(R) CPU @ 2.20GHz, 12 cores

> Intel(R) Xeon(R) Platinum 8375C @ 2.90GHz, 16 cores, 30 GB RAM

The base CPU is different, so I don't think it's a fair comparison. Speed doesn't depend solely on CPU config, but also topology of CPUs and system RAM bandwidth.

**Comment by RakshitAralimatti** [comment]
Thanks for your reply @ngxson 
But the `(Intel(R) Xeon(R) Platinum 8375C @ 2.90GHz, 16 cores, 30 GB RAM)` is a more powerful CPU compared to it others.

Considering everything, can you suggest the best **CPU-only VM Config**(RAM size, Cores, etc..) for running a model like llama3-8B with optimum inference time?

**Comment by BarfingLemurs** [comment]
>Does the model still utilize the GPU in the background even when ngl = 0 is set on a GPU-enabled VM

For your question, it depends how you build.  A gpu-enabled llama.cpp build should use the GPU to speedup prompt processing at ngl = 0 last time I checked. Build for CPU only if you want to conserve GPU resources.

**Comment by ggerganov** [comment]
Also, if you are using a CUDA-enabled build, but still want to run on the CPU-only, you can start the process with `CUDA_VISIBLE_DEVICES= ./llama-...`

**Comment by RakshitAralimatti** [comment]
Got it !!!
Thanks for your replies.
