### ISSUE TITLE
Feature Request: multimodal on android 

### ISSUE THREAD

**Issue by surajat17** [ggerganov/llama.cpp#9738]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

i have been inferencing different text models using android example, was wondering how to inference with multimodals.

### Motivation

wanted to try multimodals on edge

**Comment by Foul-Tarnished** [comment]
There's no multimodal support at all...

**Comment by FranzKafkaYu** [comment]
Maybe you can try this：https://github.com/UbiquitousLearning/mllm
