### ISSUE TITLE
GPT4All Instructions are missing both scripts: convert and migrate

### ISSUE THREAD

**Issue by robbintt** [ggerganov/llama.cpp#975]
Neither of these links works and the files aren't present anymore.

> You have to convert it to the new format using [./convert-gpt4all-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-gpt4all-to-ggml.py). You may also need to convert the model from the old format to the new format with [./migrate-ggml-2023-03-30-pr613.py](https://github.com/ggerganov/llama.cpp/blob/master/migrate-ggml-2023-03-30-pr613.py):

**Comment by prusnak** [comment]
fix in https://github.com/ggerganov/llama.cpp/pull/980

**Comment by vmajor** [comment]
I am still confused. So how do I convert/migrate the old ggml model to the new ggml model?

**Comment by prusnak** [comment]
> I am still confused. So how do I convert/migrate the old ggml model to the new ggml model?

Read instructions in PR https://github.com/ggerganov/llama.cpp/pull/980

**Comment by vmajor** [comment]
> > I am still confused. So how do I convert/migrate the old ggml model to the new ggml model?
> 
> Read instructions in PR #980

I did read it, you may notice that I "thumbed up" your reply prior to asking the question here. Please point me to a location of instructions for migration of old ggml format to the new ggml format.

**Comment by prusnak** [comment]
> Please point me to a location of instructions for migration of old ggml format to the new ggml format.

It's always python3 convert.py model.bin
