### ISSUE TITLE
Feature Request: ANE utilization on Apple Silicon

### ISSUE THREAD

**Issue by hg0428** [ggerganov/llama.cpp#9773]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Add support for the ANE in order "to achieve up to 10 times faster and 14 times lower peak memory consumption."

### Motivation

This will make all models faster for everyone on Apple Silicon.

### Possible Implementation

A reference implementation is provided by Apple [here](https://github.com/apple/ml-ane-transformers). It shows how a transformer model can be run on the ANE.

**Comment by hg0428** [comment]
It was not completed!

**Comment by bhupesh-sf** [comment]
reopen this, its really required
