### ISSUE TITLE
Bug: No improvement for NEON?

### ISSUE THREAD

**Issue by Abhranta** [ggerganov/llama.cpp#9774]
### What happened?

First of all - I am not sure whether this is a issue but, I could not find any answers anywhere. 

I am trying to run a Llama3 8B model on a Raspberry pi5. I am using llama.cpp for doing this. I used "make" to build llama.cpp .

Recently Q4_0_4_4 and Q4_0_4_8 wuants were introduced to get efficient mulmat kernels for ARM. Q4_0_4_4 is optimized for neon and Q4_0_4_8 is optimized for int8mm.

When I run a Llama3 8B model using these quantizations on a Raspberry Pi5, I am hardly getting 2.05 tokens/sec which is worse that other quant methods on the same hardware. With IQ4_XS quant, I am getting around 2.5 tokens per second. Why is this happening ? Why am I not getting better performance while everything (thread count, memory, etc.) is same?

Moreover can anyone help me with what build flags to use while building llama.cpp for NEON ?

### Name and Version

version: 3891 (https://github.com/ggerganov/llama.cpp/commit/d5cb86844f26f600c48bf3643738ea68138f961d)
built with cc (Debian 12.2.0-14) 12.2.0 for aarch64-linux-gnu

**Comment by BarfingLemurs** [comment]
try with: `GGML_NO_LLAMAFILE=1 make` 
https://github.com/ggerganov/llama.cpp/blob/master/docs/build.md

**Comment by Abhranta** [comment]
I have compiled with that particular flag. But, It doesn't impact the text gen speed at all.

**Comment by BarfingLemurs** [comment]
Llama 3.2 1B (snapdragon phone) with `-n 60`

| Metric          | Q4_K_M | Q4_0 | Q4_0_4_4 |
|-----------------|--------|------|----------|
| Prompt Processing (pp) | 22.41 t/s | 13.23 t/s | 34 t/s    |
| Token Generation (tg)  | 13.70 t/s | 12 t/s    | 11.3 t/s  |

I have not tested the results with the IQ models.

**Comment by Abhranta** [comment]
> Llama 3.2 1B (snapdragon phone) with `-n 60`

which phone? which processor? how many cores? what quantizations?  any other specifics?
