### ISSUE TITLE
binaries don't work?

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#9794]
on google colab (even after apt update && apt upgrade

```
./build/bin/llama-quantize: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by ./build/bin/llama-quantize)
./build/bin/llama-quantize: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./build/bin/llama-quantize)
```

**Comment by rumourscape** [comment]
Same issue here

**Comment by 0wwafa** [comment]
> GLIBC requirement is beyond the capabilities of the still supported previous Ubuntu LTS. A code downgrade would be required or at the least, if we could know which version of the software we'd have to regress to in order for this to remain working on Ubuntu 22.

just compile it static for ubuntu 20. And it will work almost everywhere.

**Comment by 0wwafa** [comment]
> > GLIBC requirement is beyond the capabilities of the still supported previous Ubuntu LTS. A code downgrade would be required or at the least, if we could know which version of the software we'd have to regress to in order for this to remain working on Ubuntu 22.
> 
> just compile it static for ubuntu 20. And it will work almost everywhere.

Anything that works out of the box on google colab is fine for me :D
