### ISSUE TITLE
NPU 910B3 cann compiler error

### ISSUE THREAD

**Issue by ninth99** [ggerganov/llama.cpp#9814]
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp: In function ‘ggml_backend_buffer_type* ggml_backend_cann_buffer_type(int32_t)’:
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:1154:13: error: no match for ‘operator=’ (operand types are ‘ggml_backend_buffer_type’ and ‘’)
1154 | };
| ^
In file included from /owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:34:
/owner/ninth/llama.cpp/ggml/src/ggml-backend-impl.h:29:12: note: candidate: ‘ggml_backend_buffer_type& ggml_backend_buffer_type::operator=(const ggml_backend_buffer_type&)’
29 | struct ggml_backend_buffer_type {
| ^~~~~~~~~~~~~~~~~~~~~~~~
/owner/ninth/llama.cpp/ggml/src/ggml-backend-impl.h:29:12: note: no known conversion for argument 1 from ‘’ to ‘const ggml_backend_buffer_type&’
/owner/ninth/llama.cpp/ggml/src/ggml-backend-impl.h:29:12: note: candidate: ‘ggml_backend_buffer_type& ggml_backend_buffer_type::operator=(ggml_backend_buffer_type&&)’
/owner/ninth/llama.cpp/ggml/src/ggml-backend-impl.h:29:12: note: no known conversion for argument 1 from ‘’ to ‘ggml_backend_buffer_type&&’
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp: In function ‘ggml_backend_event* ggml_backend_cann_event_new(ggml_backend_t)’:
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:1873:5: error: could not convert ‘{backend, event}’ from ‘’ to ‘ggml_backend_event’
1873 | };
| ^
| |
|
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp: In function ‘void ggml_backend_cann_event_record(ggml_backend_event_t)’:
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:1900:44: error: ‘struct ggml_backend_event’ has no member named ‘backend’
1900 | (ggml_backend_cann_context*)event->backend->context;
| ^~~~~~~
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp: In function ‘void ggml_backend_cann_event_wait(ggml_backend_t, ggml_backend_event_t)’:
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:1920:37: error: ‘struct ggml_backend_event’ has no member named ‘backend’
1920 | if (ggml_backend_is_cann(event->backend)) {
| ^~~~~~~
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp: At global scope:
/owner/ninth/llama.cpp/ggml/src/ggml-cann.cpp:1962:38: error: invalid conversion from ‘void ()(ggml_backend_event_t)’ {aka ‘void ()(ggml_backend_event*)’} to ‘void ()(ggml_backend_t, ggml_backend_event_t)’ {aka ‘void ()(ggml_backend*, ggml_backend_event*)’} [-fpermissive]
1962 | /* .event_record = / ggml_backend_cann_event_record,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| |
| void ()(ggml_backend_event_t) {aka void ()(ggml_backend_event)}
make[3]: *** [ggml/src/CMakeFiles/ggml.dir/build.make:174: ggml/src/CMakeFiles/ggml.dir/ggml-cann.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1619: ggml/src/CMakeFiles/ggml.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3368: examples/main/CMakeFiles/llama-cli.dir/rule] Error 2
make: *** [Makefile:1323: llama-cli] Error 2

**Comment by leo-pony** [comment]
@hipudding 
The same issue with #9844 , has fixed in #9844. This issue can be closed.
