### ISSUE TITLE
Bug: build fails on macOS / x86_64

### ISSUE THREAD

**Issue by stefanb** [ggerganov/llama.cpp#9851]
### What happened?

According to [Homebrew llama.cpp pull-request history](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+llama) the [llama.cpp formula](https://formulae.brew.sh/formula/llama.cpp) started to fail **_on x86_64 architecture_** on October 7<sup>th</sup>, between release tags b3892 and b3895.

Relevant diff: https://github.com/ggerganov/llama.cpp/compare/b3892...b3895

### Name and Version

llama.cpp after versions between 3892 and 3895.

### What operating system are you seeing the problem on?

Mac

### Relevant log output

The problem only appears on **x86_64 platform**.

**macOS 14-x86_64**:
https://github.com/Homebrew/homebrew-core/actions/runs/11295285028/job/31422909741?pr=193773#step:3:487
`BuildError: Failed executing: /usr/local/Cellar/llama.cpp/3907/bin/llama-cli --hf-repo ggml-org/tiny-llamas -m stories260K.gguf -n 400 -p I -ngl 0`

**macOS 13-x86_64**:
https://github.com/Homebrew/homebrew-core/actions/runs/11295285028/job/31422910224?pr=193773#step:3:488
`BuildError: Failed executing: /usr/local/Cellar/llama.cpp/3907/bin/llama-cli --hf-repo ggml-org/tiny-llamas -m stories260K.gguf -n 400 -p I -ngl 0`

Versions berofe 3892-3895 were built with no such issue.

The build script: 
https://github.com/Homebrew/homebrew-core/blob/4fd1dc2bc1b9d0f08eb28fe42f3465c16d459fe6/Formula/l/llama.cpp.rb#L33-L59

Related PR: 
* https://github.com/Homebrew/homebrew-core/pull/193773

**Comment by ggerganov** [comment]
Thanks for reporting. Not sure how to debug this. I have an x86 Intel Macbook and the latest branch of `llama.cpp` builds and runs successfully on it.

**Comment by stefanb** [comment]
Thanks for testing.

Can you check the build logs in [the failing PRs](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+llama) and maybe find some reason or a hint?

**Comment by ggerganov** [comment]
I checked the logs, but there isn't much useful information. Most certainly, this is the offending commit: d5ac8cf2f2e30459489e6721a17d15b92a0c42a6. But I need to reproduce this crash in order to fix it.

**Comment by SMillerDev** [comment]
Maybe the problem is that it runs virtualised? That's the only difference I can think of between Homebrew CI and a physical macbook.

**Comment by ggerganov** [comment]
@stefanb I would try to add the following flag to the test command: `--no-mmap`

```bash
bin/llama-cli --hf-repo ggml-org/tiny-llamas -m stories260K.gguf -n 400 -p I -ngl 0 --no-mmap
```

What is the easiest way to test this?

**Comment by stefanb** [comment]
Tnx for the hint, I have added that extra parameter to https://github.com/Homebrew/homebrew-core/pull/193928
We'll see how that goes.

**Comment by stefanb** [comment]
Still exception in the [log](https://github.com/Homebrew/homebrew-core/actions/runs/11304459098/job/31442917122?pr=193928#step:3:497), this time with the new `--no-mmap` parameter:
`An exception occurred within a child process:
    BuildError: Failed executing: /usr/local/Cellar/llama.cpp/3909/bin/llama-cli --hf-repo ggml-org/tiny-llamas -m stories260K.gguf -n 400 -p I -ngl 0 --no-mmap`

**Comment by ggerganov** [comment]
Hm, I guess the other option is simply to disable the Metal backend when building for x86 - it's actually more efficient to use the CPU on these machines anyway.

So can we try to change the line:

```txt
-DGGML_METAL=#{OS.mac? ? "ON" : "OFF"}
```

to

```txt
-DGGML_METAL=#{OS.mac? && !Hardware::CPU.intel? ? "ON" : "OFF"}
```

No need to apply the `--no-mmap` arg anymore.

**Comment by stefanb** [comment]
@ggerganov, thanks, that solved the problem in
* https://github.com/Homebrew/homebrew-core/pull/193928

🙇
