### ISSUE TITLE
Stops talking mid sentence

### ISSUE THREAD

**Issue by Asory2010** [ggerganov/llama.cpp#988]
I am using the vicuna model with the DAN prompt, it works well but it sometimes stops mid sentence for example it would say: "example senten" then stop talking why does this happen?
here is my run.bat script:

title Vicuna!(;
:start
main -i -f prompts/DAN.txt --memory_f32 --interactive-first -r "### Human:" --temp 0 -c 2048 -n -1 --ignore-eos --repeat_penalty 1.2 --instruct --color -m ggml-vicuna-7b-4bit.bin -n 128
pause
goto start

**Comment by rabidcopy** [comment]
The second `-n 128` is the reason for that. Every 128 tokens it's going to stop. Set `-n -1` and remove `-n 128`.

**Comment by abdansyakuuro** [comment]
> I am using the vicuna model with the DAN prompt, it works well but it sometimes stops mid sentence for example it would say: "example senten" then stop talking why does this happen?
> here is my run.bat script:
> 
> title Vicuna!(;
> :start
> main -i -f prompts/DAN.txt --memory_f32 --interactive-first -r "### Human:" --temp 0 -c 2048 -n -1 --ignore-eos --repeat_penalty 1.2 --instruct --color -m ggml-vicuna-7b-4bit.bin -n 128
> pause
> goto start
> 
>
