### ISSUE TITLE
Standford Alapaca support

### ISSUE THREAD

**Issue by v3ss0n** [ggerganov/llama.cpp#99]
Just 3 hrs ago , chat tuned LLAma released : https://github.com/tatsu-lab/stanford_alpaca

**Comment by prusnak** [comment]
There are no model weights published for now: quoting from their README:
> We intend to release the model weights if we are given permission to do so by the creators of LLaMA.

**Comment by samchen8008** [comment]
Very exciting.

**Comment by colosieve** [comment]
Maybe we can watch for this project to publish the Alpaca-LoRa data and instructions to merge with official Llama 7B model's weight? https://github.com/tloen/alpaca-lora

**Comment by v3ss0n** [comment]
That's really awesome development going on

**Comment by gjmulder** [comment]
#172
