### ISSUE TITLE
Bug: llama.cpp does not use XTC sampler when given temperature == 0 even if temperature is not in sampler sequence

### ISSUE THREAD

**Issue by justinsteven** [ggerganov/llama.cpp#9904]
### What happened?

It's possible I'm misunderstanding samplers and sampler parameters.

~~It's also possible this is a symptom of a larger problem, where "default" values for some samplers may cause other samplers to be not activated in `llama-server`.~~

# Observed behaviour

~~There are several sampler parameters which, when given "do nothing" default values via `llama-server`'s `/completions` API, seem to cause the XTC sampler to not be used.~~

Update: The above should be "Given a temperature of 0, even if temperature is not in the requested sampler sequence, the XTC sampler is not used"

The following JSON payload demonstrates the issue:

```json
{
  "prompt": "<|im_start|>system\nYou are a creative story writer<|im_end|>\n<|im_start>user\nWrite a story about a wizard who is losing his ability to do magic, and tries everything to get it back.<|im_end|>\n<|im_start|>assistant\n",
  "n_predict": 512,
  "seed": 1,
  "xtc_probability": 0.5,
  "xtc_threshold": 0.1,
  "samplers": [
    "xtc"
  ],
  "top_k": 0,
  "tfs_z": 1,
  "top_p": 1,
  "min_p": 0,
  "temperature": 0
}
```

In my testing, this causes the XTC sampler to not be activated. The vibe was off, and the following hacky debugging that I added was not activating:

```diff
diff --git a/src/llama-sampling.cpp b/src/llama-sampling.cpp
index 2e655068..63e0d043 100644
--- a/src/llama-sampling.cpp
+++ b/src/llama-sampling.cpp
@@ -1084,6 +1084,7 @@ static void llama_sample_xtc_apply(struct llama_sampler * smpl, llama_token_data
         || cur_p->size < 2) {
         return;
     }
+    puts("ok");

     std::uniform_real_distribution<float> distribution(0.0f, 1.0f);
     float chance = distribution(ctx->rng);
```

Given the following simpler JSON payload, the hacky debugging was successfully activated:

```json
{
  "prompt": "<|im_start|>system\nYou are a creative story writer<|im_end|>\n<|im_start>user\nWrite a story about a wizard who is losing his ability to do magic, and tries everything to get it back.<|im_end|>\n<|im_start|>assistant\n",
  "n_predict": 512,
  "seed": 1,
  "xtc_probability": 0.5,
  "xtc_threshold": 0.1,
  "samplers": [
    "xtc"
  ]
}
```

~~Furthermore, each of the things after my samplers array seem to individually cause XTC to not activate. For example, a `temperature` of 0 (without specifying any of `top_k`, `tfs_z`, `top_p` or `min_p`) is enough to cause XTC to not activate.~~

~~There may be other parameters, including sampler parameters, which cause XTC to not activate, but which I did not test.~~

(Update: I was wrong about this, it seems as though only `temperature == 0` reproduces the issue)

This is problematic for clients such as SillyTavern, which seem to always send all samplers in the array but which rely on sending default parameters (e.g. 0 in the case of `temperature`) to cause them to be effectively disabled. Such a client will ~~never be able to activate XTC~~ not activate XTC if the user gives a temperature of 0 in the hopes of disabling the temperature sampler.

# Expected behaviour

If XTC is in the samplers array, and `xtc_threshold` and `xtc_probability` meet the criteria for XTC to be used, XTC should be used regardless of parameters for other samplers.

More generally, if any sampler is in the samplers array, and its parameters meet the criteria for it to be used, it should be used regardless of parameters for other samplers (?)

# Related

* #9742 
* https://github.com/SillyTavern/SillyTavern/issues/2992

### Name and Version

```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
version: 3923 (becfd387)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
```

### What operating system are you seeing the problem on?

Linux

**Comment by MaggotHATE** [comment]
> `temperature` of 0

AFAIK, such value activates greedy sampling which doesn't use sampling queue. You can look in [common/sampling.cpp](https://github.com/ggerganov/llama.cpp/blob/becfd387f6919d99ec34b76c2522f90ac250c489/common/sampling.cpp#L174).

It should work with temperature > 0, and I don't think that temperature 0 is default normally.

**Comment by slaren** [comment]
It is not an optimization, using a temperature of 0 is intended to enable greedy sampling. Greedy sampling implies that all other samplers are disabled, so that's what it does. This is documented in https://github.com/ggerganov/llama.cpp/tree/master/examples/main#temperature, but admittedly this is not very intuitive behavior and it is not easy to find it in the documentation. Maybe we should just add a parameter to explicitly enable greedy sampling instead?

**Comment by justinsteven** [comment]
Hmm. I definitely don't understand samplers then, thanks for your patience :sweat_smile:

Is there a functional difference, or difference in a user's intention, between:

* Specifying a sampler chain that has temperature in it, and setting temperature to 0
* Specifying a sampler chain that does not have temperature in it

Is "greedy" synonymous with "no sampling, just take the most likely next token always"?

I assumed that putting temperature in the sampler chain, and setting temperature to 0, makes the temperature sampler a pass-through no-op. I don't expect setting temperature to 0 to hijack the chain entirely (whether or not temperature is in the specified chain) to enable greedy behaviour, but perhaps there is a need for a consumer to signal they want this greedy behaviour. The way it's done right now surprises me as a user.

**Comment by slaren** [comment]
> Is "greedy" synonymous with "no sampling, just take the most likely next token always"?

Yes, that's the way the term is used here. The logic is that lower temperatures make the sampling more deterministic, so a temperature of 0 should mean that the sampling is completely deterministic. To disable temperature you would have to set it to a value of 1. This was reasonable when the entire sampling chain consisted of top-k, top-p and temperature, but as the samplers got more complex I can understand that this can be confusing.

**Comment by MaggotHATE** [comment]
The problem here is that `temperature = 0` is the intended and established way of defining deterministic (greedy) sampling, because in some tasks no variation is needed - and that's exactly what zero temperature represents. It is still used in practice (in fact, just in some [recent papers](https://arxiv.org/pdf/2402.10200)), so I'm not even sure how to define a different way that would not break existing rules.

**Comment by justinsteven** [comment]
> To disable temperature you would have to set it to a value of 1.

Oh. So it's a temperature of 1 that is a no-op? Is it equivalent to not putting temperature in the sampler chain?

I assumed that 0 would be the no-op value.

I see now that the SillyTavern UI indeed says to set temperature to 1 "for the original probabilities" :facepalm:

Perhaps there's still merit to reconsidering the `temperature == 0` greedy magic switch, but this seems to be user error on my part.
