### ISSUE TITLE
Bug: invalid argument: --memory-f32

### ISSUE THREAD

**Issue by iperov** [ggerganov/llama.cpp#9925]
### What happened?

Trying to enable f32 mode (as described here https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md),
because 32GB model obviously converted to 16GB judging by process memory usage

### Name and Version

version: 3917 (a89f75e1)
built with MSVC 19.29.30154.0 for x64

### What operating system are you seeing the problem on?

Windows

**Comment by arch-btw** [comment]
This was removed https://github.com/ggerganov/llama.cpp/commit/4399f13fb9462cd06f3f154d0aee738425000fea but the readme hasn't been updated.

**Comment by Vladonai** [comment]
Did this mode give any advantage for videocards that better support fp32? For example Tesla P40.

**Comment by iperov** [comment]
@arch-btw excuse me, but how to enable fp32 mode? I am using "Meta-Llama-3.1-8B-Instruct-f32.gguf" so 8B*4 = 32GB, but 16GB is used in process explorer. My RAM is 64GB

**Comment by arch-btw** [comment]
@iperov the option has been removed from llama.cpp. I don't know if maybe it got replaced by something similar, sorry. Maybe someone else knows.

**Comment by iperov** [comment]
so llamacpp can only work in <= fp16 mode ? no chance to run in fp32 ?
