### ISSUE TITLE
Feature Request: Convert .devops container images to be RHEL-based UBI images rather than Ubuntu based

### ISSUE THREAD

**Issue by ericcurtin** [ggerganov/llama.cpp#9961]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

We would be able to change these to be UBI based, UBI are container images that are a subset of RHEL:

https://github.com/ggerganov/llama.cpp/tree/master/.devops

Would you guys be open to changing these from Ubuntu-based to RHEL-based if someone opened the PR?

### Motivation

One reason is we need something RHEL-based for and would like to work together on these containerfiles for:

https://github.com/containers/ramalama

but there are others looking for RHEL-based images also.

**Comment by slaren** [comment]
The main goal of the containers in this repository should be to be easy to use for most users, and I think that it is reasonable to assume that more people are familiar with Debian and Ubuntu-based distributions than RHEL. If the only motivation for this change would be to reduce the maintenance cost for the ramalama project, I don't think that's a strong enough reason to change the base image of the containers.
