### ISSUE TITLE
Bug:  Crashed when using new released binaries on MacOS

### ISSUE THREAD

**Issue by morgen52** [ggerganov/llama.cpp#9973]
### What happened?

Hi! I have tried to deploy the lastest pre-compiled binaries (b3943) on my MacAir (m2). However, when I tried to start `llama-cli`, I got a crash.
I have tried the `llama-b3943-bin-macos-arm64.zip` and `llama-b3943-bin-macos-x64.zip` release, but both of them crashed. 
What is the best way to use the pre-compiled binaries on my Mac?

```bash
./bin/llama-cli -version
```

```
(arm)
dyld[12166]: Symbol not found: (_cblas_sgemm$NEWLAPACK$ILP64)
  Referenced from: '/Users/morgen/Downloads/build/bin/llama-cli'
  Expected in: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'
```

```
(x64)
zsh: illegal hardware instruction  ./bin/llama-cli --version
```

### Name and Version

b3943

### What operating system are you seeing the problem on?

Mac

**Comment by glaszig** [comment]
any solution?
