### ISSUE TITLE
Bug: Version infomation missing when using llama-cli built on mac

### ISSUE THREAD

**Issue by morgen52** [ggerganov/llama.cpp#9977]
### What happened?

Hi! After failing to run the pre-compiled binaries on my Mac, I tried to compile them myself. 
However, after finishing the compilation, I found the version information missing when I ran the `llama-cli --version` command. (The compiled binary can infer the "Hello world" prompt via phi-3 model normally.)

### Name and Version

./llama.cpp-b3938/build_metal/bin/llama-cli --version
version: 0 (unknown)
built with Apple clang version 14.0.0 (clang-1400.0.29.202) for arm64-apple-darwin21.6.0

### What operating system are you seeing the problem on?

Mac

**Comment by brittlewis12** [comment]
@morgen52 how did you produce the binaries? running `make` from the root of the repo produces a `llama-cli` binary in the root which reports its version properly:

```
❯ ./llama-cli --version
version: 3930 (9e041024)
built with Apple clang version 15.0.0 (clang-1500.1.0.2.5) for arm64-apple-darwin23.6.0
```
