### ISSUE TITLE
how could i stop printing  time execution

### ISSUE THREAD

**Issue by Muhamad-Nady** [ggerganov/llama.cpp#999]
I want to stop print that block. i have it with every output any solution
llama_print_timings:        load time =  3977.75 ms
llama_print_timings:      sample time =     4.37 ms /     5 runs   (    0.87 ms per run)
llama_print_timings: prompt eval time = 86857.95 ms /   208 tokens (  417.59 ms per token)
llama_print_timings:        eval time =  2474.22 ms /     5 runs   (  494.84 ms per run)
llama_print_timings:       total time = 89339.05 ms

**Comment by SlyEcho** [comment]
Send it to `/dev/null` like:

```sh
./main -m models/llama-7b-q4_0.bin -n 64 -p "My dad was a" 2> /dev/null
```

On Windows, I have no idea.

**Comment by Muhamad-Nady** [comment]
I am running it with langchain library in python. how could i stop it with python command.

**Comment by SlyEcho** [comment]
I was able to integrate it to langchain with this simple LLM model. Needs the path to the `main` program and the model file, change the other parameters if you need something.

```python
from langchain.llms.base import LLM
from typing import Optional, List, Mapping, Any
import subprocess
import tempfile

class LlamaCppOfflineLLM(LLM):
    
    path: str
    model: str
    context: int = 2048
    threads: int = 4
    batch: int = 512
    limit: int = 128
    temp: float = 0.9

    @property
    def _llm_type(self) -> str:
        return "custom"
    
    def _call(self, prompt: str, stop: Optional[List[str]]) -> str:
        with tempfile.NamedTemporaryFile(mode='w', encoding='UTF-8', suffix='.txt') as tmp:
            tmp.write(prompt)
            tmp.flush()
            
            cmd = [
                self.path,
                "--model", self.model,
                "--ctx_size", str(self.context),
                "--threads", str(self.threads),
                "--batch_size", str(self.batch),
                "--n_predict", str(self.limit),
                "--temp", str(self.temp),
                "--file", tmp.name,
            ]

            if stop is not None:
                for s in stop:
                    cmd.extend(["--reverse-prompt", s])

            result = subprocess.run(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                encoding='UTF-8'
            )
            
            if (result.returncode != 0):
                return "error"
            return result.stdout[len(prompt)+1:].lstrip()

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"model": self.model}
```

**Comment by Muhamad-Nady** [comment]
@SlyEcho 
I have tried to call the model with your class, but i get many problem.
how could adding or modify function of that class "langchain.llms.llamacpp" to solve the problem. can you help me.

**Comment by SlyEcho** [comment]
I guess you could patch out the `fprintf(stderr, ...);` calls in `llama.cpp` and then build a custom library. Looking at [llama_cpp.py](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_cpp.py) you can use the environment variable `LLAMA_CPP_LIB` to make it load your own version.

You can build the library with `make libllama.so` (which you can rename to `llama.dll` if you need) when using Make
or use `-DBUILD_SHARED_LIBS=ON` when configuring CMake.

**Comment by Chae4ek** [comment]
There is [verbose](https://github.com/abetlen/llama-cpp-python/blob/92c077136d1f0b029f8907a79eae009a750005e2/llama_cpp/llama.py#L42) param, but it seems langchain wrapper doesn't use it

**Comment by Muhamad-Nady** [comment]
@Chae4ek 
yes langchain does not use it, I have tried that option. maybe i need to remove it from llama_cpp.py as @SlyEcho mentioned and customize the library.

**Comment by Chae4ek** [comment]
I think it's much easier to just add it. I tried to set it to False manually and it disables "llama_print_timings:..."

**Comment by SlyEcho** [comment]
I think using `verbose=False` may be the best way to do this.

**Comment by Muhamad-Nady** [comment]
I have tryied it with llamaCpp(modelpath, verbose=Fasle)
But it was still printing out time may i was need to restart the kernel !!

**Comment by SlyEcho** [comment]
```python
llm = LlamaCpp(model_path="./ggml-model-q4_0.bin")
llm.client.verbose = False
```

Something like this. Code for [llamacpp.py](https://github.com/hwchase17/langchain/blob/master/langchain/llms/llamacpp.py) is also here on Github freely available.

In any case this is an issue with [llama-cpp-python](https://github.com/abetlen/llama-cpp-python), not llama.cpp

**Comment by Muhamad-Nady** [comment]
@SlyEcho that's work thanks you 
@Chae4ek  thanks for support

**Comment by dbanswan** [comment]
> Send it to `/dev/null` like:
> 
> ```shell
> ./main -m models/llama-7b-q4_0.bin -n 64 -p "My dad was a" 2> /dev/null
> ```
> 
> On Windows, I have no idea.

Works great on mac, thanks was looking all over for this.

**Comment by KanrongYu** [comment]
`verbose=False` for silencing llamacpp()
`LLM.client.verbose = False` for silencing llm.invoke()
finally get rid of all the code blocks thanks to folk's inputs above

**Comment by dtbao20** [comment]
add `--log-disable` will solve the problem

**Comment by francogrex** [comment]
> Send it to `/dev/null` like:
> 
> ./main -m models/llama-7b-q4_0.bin -n 64 -p "My dad was a" 2> /dev/null
> On Windows, I have no idea.

That did it for me!
